### ISSUE TITLE
🐛 Table controls on admin pages look pretty bad on narrow viewport

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#10038]
## 🐛 Bug

Table table controls look pretty bad on a narrow viewport

## 📋 Steps to Reproduce

1. http://localhost:8000/en/admin/settings/skills
2. Narrow viewport to about 1230px with sidemenu open

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/d3d9d476-b4e9-4188-b321-30fd03ecd74e)

![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/252986f8-e6a4-4b47-a6ef-021cb23824d9)

## 🙋‍♀️ Proposed Solution

![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/78b3f581-4a95-4cac-a919-29f58e5fe166)

## ✅ Acceptance Criteria

- [ ] Mobile view matches provided design

**Comment by gobyrne** [comment]
@substrae when you're back could you propose a solution for devs to implement please?

**Comment by substrae** [comment]
@gobyrne @petertgiles 

For now:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/ae7bf5c0-ba1d-4b6f-9196-ed8aed9419c9)
