### ISSUE TITLE
Asset skills not required on assessment plan

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#10044]
## Details

**Decision: we are gonna keep it simple for now and just not require asset skills to be assessed on the plan.**

> During testing, every user raised the following complaint
> 
> > "We dont actually assess 'Asset' skill, why are you forcing me to add an assessment for it?"
> 
> This is a complicated question, since we will NOT be requiring them to assess it, but NOT planning for it will make it difficult to include it later on if necessary. Should we force users to plan for it? or should we create a feature that allows Assessment plans to be amended somehow?
> 
> We could still benefit from making it clear right now that "Adding a plan for your assets does not mean you need to perform those assessments" The 'instructions' should probably include something to that effect.

## Copy update
This small copy update. Insert "essential" before the word skill.

![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/8e58b57c-d809-4a87-ba04-46d82e1c427c)

### English
https://github.com/GCTC-NTGC/gc-digital-talent/blob/5c259f4a821bf4826a944f07ad849a721e35a0f7/apps/web/src/pages/Pools/AssessmentPlanBuilderPage/components/OrganizeSection.tsx#L184-L190

### French
https://github.com/GCTC-NTGC/gc-digital-talent/blob/5c259f4a821bf4826a944f07ad849a721e35a0f7/apps/web/src/lang/fr.json#L378-L381

## Acceptance criteria
- [ ] Asset skills are not required to be assessed for the assessment plan to be complete.
- [ ] Asset skills do not show up on the list of "missing" skills.
- [ ] Copy updated to reflect that only essential skills are required.

**Comment by mnigh** [comment]
@gobyrne @Jerryescandon The current paragraph has more difference than just missing the word **essential**. Can you confirm what the copy should be?

<img width="1166" alt="Screen Shot 2024-04-15 at 11 49 30" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/a8b39d6c-15b9-4d7f-92f0-70f531261b1f">

**Comment by Jerryescandon** [comment]
> @gobyrne @Jerryescandon The current paragraph has more difference than just missing the word **essential**. Can you confirm what the copy should be?
> 

Good catch, I think the best solution is to leave this paragraph as-is. HOWEVER the subtitle above (in UAT) is the one that currently contains that sentence, and that's where the "essential" should be updated.

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/69f9a20c-7462-4054-91d3-ee918e7da015)

**Comment by Jerryescandon** [comment]
Also, whatever happened to https://github.com/GCTC-NTGC/gc-digital-talent/issues/9637 ?? 😢

**Comment by mnigh** [comment]
> > @gobyrne @Jerryescandon The current paragraph has more difference than just missing the word **essential**. Can you confirm what the copy should be?
> 
> Good catch, I think the best solution is to leave this paragraph as-is. HOWEVER the subtitle above (in UAT) is the one that currently contains that sentence, and that's where the "essential" should be updated.
> 
> ![image](https://private-user-images.githubusercontent.com/16977254/322904050-69f9a20c-7462-4054-91d3-ee918e7da015.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyODM4MjksIm5iZiI6MTcxMzI4MzUyOSwicGF0aCI6Ii8xNjk3NzI1NC8zMjI5MDQwNTAtNjlmOWEyMGMtNzQ2Mi00MDU0LTkxZDMtZWU5MThlN2RhMDE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE2VDE2MDUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2ODIwYWIxMGI2ZDhiNWU4ZmZlMDJmODU5MDk0MTU2YTZhMmM5YTViOTYwZTIyOWI1MDg2ZDM0NDY4ZmIxZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._4VAJaroKv58oYrQpZrNuLXoZvGfQp6n-QCoKaUp8pY)

@gobyrne if you are ok with this, could you please update the issue accordingly before it is ready for dev?

**Comment by gobyrne** [comment]
Updated
