### ISSUE TITLE
IT-05 not showing up in search page

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#10062]
## Details

The candidates for the IT-05 pilot were not showing up in the search page count. This appears to be because the "other" publishing group was used.

So, we can just add the "other" publishing group to the count and match queries.

The snippet in question:

![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/80e1d26e-0eaf-47d0-b54b-621862355dbe)

## Acceptance criteria

- [ ] Candidates qualified in "Other" publishing group processes are included in the count on the search page
- [ ] Candidates qualified in "Other" publishing group processes appear in matches for searches

**Comment by tristan-orourke** [comment]
That's a good point! Since its already closed, the main reason for keeping the poster out of `IT_JOBS` publishing group is closed.

**Comment by vd1992** [comment]
I think part of the reason for adjusting scope is that this isn't a first time problem, so it may be applicable repeatedly until the community/teams rework thing
