### ISSUE TITLE
♻️ Bump `pnpm` to v9

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#10068]
## ♻️ Debt/Refactor

New version of `pnpm` has been released. I wonder if we try bumping to it before rolling back to `npm` to see if that fixes something with dependabot :woman_shrugging: 

## 🕵️ Details

While there does not seem to be any breaking changes, there are some nice new defaults we can use along with changes to the lock file.

https://github.com/pnpm/pnpm/releases

## ✅ Acceptance Criteria

- [ ] `pnpm` version bumped to `>= 9.0.0` in files
- [ ] Can we remove the `.npmrc` files and still have it work?

**Comment by petertgiles** [comment]
Looks like dependabot only supports v7 and v8 right now.
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem

**Comment by mnigh** [comment]
The [docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem) still don't list support for v9 but this is interesting in terms of support for v9 actually making it into dependabot-core: https://github.com/dependabot/dependabot-core/releases/tag/v0.263.0#:~:text=Bump%20default%20PNPM%20to%209.4.0%20by%20%40deivid%2Drodriguez%20in%20%2310073

**Comment by mnigh** [comment]
🥳 pnpm v9 support added to docs as well:
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem

## Screenshot
<img width="1042" alt="Screen Shot 2024-07-08 at 10 49 55" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/16d3f56f-30a6-41e1-a3e7-62c4bd9e28e4">
