### ISSUE TITLE
🔤 Copy for new API error messages

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#10075]
## 🔤 Copy

There has been a batch of error codes added or to be added as part of the RoD second phase, they will need frontend messages to display.

## 🕵️ Details

RoD relevant
```
ExpiryDateRequired = Expiry date is missing. Enter a date.
ExpiryDateAfterToday = Expiry date must be after today. Enter a valid date.
InvalidStatusForQualification = An error occurred during qualification. Contact support if this problem persists.
InvalidStatusForDisqualification = An error occurred during disqualification. Contact support if this problem persists.
InvalidStatusForRevertFinalDecision = An error occurred while reverting final decision. Contact support if this problem persists.
InvalidStatusForPlacing = An error occurred while placing the candidate. Contact support if this problem persists.
CandidateNotPlaced = An error occurred while placing the candidate. Contact support if this problem persists.
```

Others in error enums file have own issue https://github.com/GCTC-NTGC/gc-digital-talent/issues/10359.

## ✅ Acceptance Criteria

- [ ] Decided upon error codes have frontend copy with translations complete
- [ ] strings added to `packages/i18n/src/messages/apiMessages.ts`

## Blocked by

```[tasklist]
### Blocked by
- [ ] #9190
- [ ] #9191
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/9149
```

**Comment by vd1992** [comment]
@gobyrne @mnigh 

I'm assuming "Contact support if this problem persists." should also be present for `InvalidStatusForQualification` otherwise that is an odd exception. 

As well, this appears to be accidentally duplicated

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/f40dd252-8f58-489f-a70c-34d732a0f6e4)

**Comment by gobyrne** [comment]
@vd1992 yes, thanks. I've updated it in the description.

**Comment by vd1992** [comment]
> @vd1992 yes, thanks. I've updated it in the description.

What about the second one? `InvalidStatusForPlacing` and `CandidateNotPlaced` have the same attached message. 

Candidate not placed comes from trying to revert placing a candidate that wasn't placed to begin with. So should it be something like "An error occurred while reverting the candidate's placement..."?

**Comment by gobyrne** [comment]
I think it's fine as-is. @vd1992
