### ISSUE TITLE
🛠️ Improve Database Monitoring

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#10136]
## 🛠️ Tooling

We recently found out that our database monitoring was not very good.  How do we improve it?

## 🕵️ Details

Our database is a PostgreSQL server running on a virtual machine in Azure.  We're currently only getting basic metrics about the host VM itself into Azure.  We don't know anything about the health of the database server itself.

## 🙋‍♀️ Proposed Solution

Probably will need to work with IMTD on this one.

## ✅ Acceptance Criteria

- [ ] Database health metrics monitorable
- [ ] Alerts sent out when the server becomes unhealthy

**Comment by brindasasi** [comment]
Monitoring DB health would definitely be  the longer term solution.
For the time being I think setting up alert on "Connection Refused" errors should also be possible from our side.

**Comment by petertgiles** [comment]
> For the time being I think setting up alert on "Connection Refused" errors should also be possible from our side.

You're probably right, though I've only ever set up alerts based on built-in metrics before.  Well, you'll need to work with IMTD to set up any new alert anyway.  

Both approaches have their benefits.  An alert on database health might let us intervene before a total failure.  An alert on the "connection refused" error would let us know if there was a network failure when the database was still healthy.  Maybe we could eventually have both?

**Comment by gobyrne** [comment]
I created:
https://jira.tbs-sct.gc.ca/browse/AZ-19898

**Comment by petertgiles** [comment]
Jira ticket was closed.  Dan St.Pierre confirmed there is a check every 5 minutes that will send an alert if the service goes down.
