### ISSUE TITLE
🐛 FEATURE_EXECUTIVE_TEASER still exists in IaC

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#10134]
## 🐛 Bug

The feature flag FEATURE_EXECUTIVE_TEASER still exists in the IaC even though it has been removed from the code base.

## ✅ Acceptance Criteria

- [ ] FEATURE_EXECUTIVE_TEASER removed from IaC

**Comment by mnigh** [comment]
I have removed all the references to the executive teaser in the four appsvc json files of the IaC repository in Azure. However, none of these changes have been deployed to any of the three verticals (dev, uat, prod).
