### ISSUE TITLE
🛠️ Storybook build timing out

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#10140]
## 🛠️ Tooling

Storybook is timing out in our chromatic workflow, we need to fix this to get snapshots working again.

## 🕵️ Details

We recently bumped to `8.0.8` so it might be related to that but cannot be sure.

## 🙋‍♀️ Proposed Solution

Maybe try downgrading to the previous version we were on before the bump (`8.0.6`)?

## ✅ Acceptance Criteria

- [ ] Storybook can run and build locally with no issue
- [ ] Chromatic workflow works as expected without timeouts

**Comment by mnigh** [comment]
Fixed with #10142.
