### ISSUE TITLE
🧪  [Spike] Decide on changes to permissions for supporting Communities

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#10144]
## 🧪  Spike

We want to support multiple communities. This will involve a few new data models, probably, but the biggest changes will involve the roles and permission system. Roles which are currently associated with Teams and recruitment will mostly be restricted to a single Community.

## 🕵️ Details

Figure out concrete details of what this means. 
- What will the new roles and permissions be? 
- Create dev tickets to get started

## Results

- New tentative roles & permissions defined in new sheet of [spreadsheet](https://docs.google.com/spreadsheets/d/1RC7wufxwjLEvaEunHsfZfOzBefg218dvvzkDwKSiQjI/edit#gid=1880825518)
- Remaining questions for dev and design summarized in https://github.com/GCTC-NTGC/gc-digital-talent/issues/10144#issuecomment-2083329072

## 🕐 Timebox
5 days

**Comment by tristan-orourke** [comment]
Let's revisit the question of which profiles a community recruiter can see. Is it only users who have applied to a poster in the community, or can users express interest in headhunting some other way? If a user did apply to a community poster, is there a way to rescind interest? If recruiters can see the applicant's level of interest, do we need to worry about the visibility of their profile from a privacy perspective?

**Comment by tristan-orourke** [comment]
Should we update some of our nomenclature? For example, `view-any-pool` to `view-any-process` or `view-any-poster`?

**Comment by tristan-orourke** [comment]
Should Platform Admins explicitly be given permissions like `update-any-pool`? If they really want to, they can always make themselves a Community Admin...

**Comment by tristan-orourke** [comment]
Who can update published pools? Just the admins, or lower level roles as well?

**Comment by vd1992** [comment]
Assuming all these questions aren't rhetorical or notes for yourself, to offer my opinion where I can do so

> When we need multiple fine-grain permissions, is it better to create new actions (verbs) or resources (nouns)?
eg

I prefer most clarity in the permission name itself, less leaning on explanatory comments so
`update-team-draftPool`
`amend-team-publishedPool`

Resource clear, distinction between update and amend

> Should we update some of our nomenclature? For example, view-any-pool to view-any-process or view-any-poster?

Strong no. 
Backend should be consistent with backend, where we use "pool" everywhere. 
Frontend copy is too fluid and inconsistent 

> Should Platform Admins explicitly be given permissions like update-any-pool? If they really want to, they can always make themselves a Community Admin...

Yeah I lean towards the latter to avoid making platform admins the do everything and anything role

> Who can update published pools? Just the admins, or lower level roles as well?

Tempted to keep it restricted as in personal opinion, amending published processes should be ideally minimal. For fairness for applicants

**Comment by tristan-orourke** [comment]
Changes:
- combine Application Notes and Assessment Results into Application Assessment
- rename Application Status to Application Decision
- split Application Placement from Application Decision?

**Comment by tristan-orourke** [comment]
Does there need to be a distinction between interacting with Application Decision (qualified, disqualified, removed) and Application Placement? Are there any roles which can update one but not the other?
- Can single-pool operators from another department place candidates in addition to qualifying them, or is that something only Community Recruiters can do?

**Comment by tristan-orourke** [comment]
Is there any real distinction between "User" and "Applicant Profile" when it comes to permissions? 

What does "User" contain that "Applicant Profile" doesn't?
- auth info (sub and roles)
- notifications
- applications

Each of those seems like it can have its own permissions. That suggests to me we don't need both a User and an ApplicantProfile permission.

**Comment by tristan-orourke** [comment]
What data will Community model actually hold? Should it be publicly visible? Should its team members be publicly visible?

Should team members in general be public or not? Consider community members, or everyone with permissions to access a process in some way.

**Comment by tristan-orourke** [comment]
# Collected questions

## Questions for Design

### Controlling access to live applicant profiles
Let's revisit the question of which profiles a community recruiter can see. Is it only users who have applied to a poster in the community, or can users express interest in headhunting some other way? If a user did apply to a community poster, is there a way to rescind interest? If recruiters can see the applicant's level of interest, do we need to worry about the visibility of their profile from a privacy perspective?

### Should Platform Admins explicitely get permission to do everything?

Or is it enough if they have the ability to give themselves all other roles? Note: the latter is easier.

### Amending published pools

Which roles can do it? Platform Admin, Community Admin, Community Recruiter, Pool Operator?

### Placing candidates

Can single-pool operators from another department place candidates in addition to qualifying them, or is that something only Community Recruiters can do?
- Dev note: this impacts whether we need separate permissions for Applicant Placement vs Applicant Decision (qualified, disqualified, removed). If any roles can do one but not the other, they need separate permissions.

### the Team model

What data will Community model actually hold? Should it be publicly visible? Should its team members be publicly visible?

Should team members in general be public or not? Consider community members, or everyone with permissions to access a process in some way.

Should `view-team-communityMembers` be a different permission from `view-team-community`?
## Questions for Dev

### More verbs or more nouns for permissions?

When we need multiple fine-grain permissions, is it better to create new actions (verbs) or resources (nouns)?  
eg

```
update-team-pool // note: only applies to draft pools. Published pools cannot be updated
amend-team-pool // note: only applies to published pools. Update permission is used for draft pools
```

vs

```
update-team-draftPool
update-team-publishedPool
```

Another example of explicit permission naming:

- only the Applicant should be able to edit their applications
- applications cannot be edited after submission
- this should be enforced by validation on the update mutation
- should it also be reflected in the permission name we use? `update-own-application` vs `update-own-draftApplication`
    - `update-own-application` keeps the number of resource names we have to manage lower, and is more consistent with related permission names
        - many mutations will always have more validation logic than can be reflected in permission names anyway
    - `update-own-draftApplication` is very explicit about when it should be used
        - pro: more readable
        - pro: if we want to give a different role (like admins) ability to update non-draft applications, it will need a different permission name (though it could be `amend application` instead)

#### Opinions
- Vachan: doesn't mind more verbs AND more nouns, if it makes permissions more clear/explicit
- Matt: prefers sticking to CRUD

### User vs Applicant Profile

Is there any real distinction between "User" and "Applicant Profile" when it comes to permissions?

What does "User" contain that "Applicant Profile" doesn't?
- auth info (sub and roles)
- notifications
- applications

Each of those seems like it can have its own permissions. That suggests to me we don't need both a User and an ApplicantProfile permission. Conceptually, it makes the most sense to me to have separate permissions for interacting with
- User Basic Info
- User Roles
- User Auth Info
- Notifications
- Applicant Profile
- Applications
And not have an overarching User permission at all.
Somewhat related to [#8291](https://github.com/gctc-ntgc/gc-digital-talent/issues/8291).

### Controlling who can assign roles

How should permissions to assign roles be handled? A separate permission for each role? Or should we store a hierarchy of roles somewhere, and follow the general rule that any role can assign rules under it in the hierarchy?

```
// every role has its own permission for assigning it
assign-any-communityAdmin // Platform admins can assign admins to any community
assign-any-communityRecruiter // Platform admins can assign Recruiters to any community
assign-team-communityRecruiter // Community admins can assign Recruiters to their own community
assign-team-processOperator // Community Admins and Community Recruiters can assign Process Operators to processes in their community
```

```
// Role models know about the roles they're allowed to assign
PlatformAdmin {
  teamRole: false
  childRoles: [CommunityAdmin, CommunityRecruiter] // Since teamRole is false (this role is not specific to a team) these translate into "assign-any-<role>" permissions
}
CommunityAdmin {
  teamRole: true
  childRoles: [CommunityRecruiter, ProcessOperator] // Since this is a team role, these translate into "assign-team-<role>" permissions
}
CommunityRecruiter {
  teamRole: true
  childRoles: [ProcessOperator]
}
ProcessOperator {
  teamRole: true
  childRoles: [ProcessViewer] // Since ProcessOperator's team is a Pool, they can only assign ProcessViewers to that same team.
}
```

^ After writing out the above, I think I like explicit permissions more...

Is there a way to phrase assignation permissions as crud?

- `update-any-platformAdminMembership` ? `update-any-platformAdminRole` ?
- `update-any-communityAdminMembership`
- `update-team-communityRecruiterMembership`  
    ^ How do we feel about that compared to `assign-any-platformAdminRole`?

**Comment by brindasasi** [comment]
**When we need multiple fine-grain permissions, is it better to create new actions (verbs) or resources (nouns)?**
_update-team-draftPool
update-team-publishedPool** is more clear_ 

**How should permissions to assign roles be handled?**

_I like below one .. differentiates role assignment permission from actual update operation_
```
assign-any-communityAdmin // Platform admins can assign admins to any community
assign-any-communityRecruiter // Platform admins can assign Recruiters to any community
assign-team-communityRecruiter // Community admins can assign Recruiters to their own community
assign-team-processOperator // Community Admins and Community Recruiters can assign Process Operators to processes in their community
```

_hierarchy looks nice .. but probably we would get stuck in the long run when the use case becomes like_
_` this person wants to do that but not that ' kind of things. It will not allow lot of flexibility._

**Comment by petertgiles** [comment]
> More verbs or more nouns for permissions?

I don't think there's a general rule for this.  In your "update-team-pool' example above I think "update-team-draftPool" is much better.  However, there are situations where more verbs are better, like "publish pool".  Publishing speaks more to a state change than simply updating some properties. I think the naming has to be informed by the business logic.  With the permissions system, I think readability and understandability are top priority.

> Each of those seems like it can have its own permissions. That suggests to me we don't need both a User and an ApplicantProfile permission.

You know I'm always the "make things a simple as possible" guy.  I think you're right that this needs to be determined by when permissions will be different.  There's no point in breaking this into a bunch of permissions that will be assigned identically.

> After writing out the above, I think I like explicit permissions more...

For sure - this permissions model is all about explicit over convention.

> Is there a way to phrase assignation permissions as crud?

I like the membership version better.  Sure, it's longer but it's more precise.  You're updating a membership, not the role itself.  Brinda suggested "assign" as a new verb.  I think this could be a good place for a non-crud verb but I'm not sure assign is the right one since presumably this permission would allow "unassignment" as well.

**Comment by tristan-orourke** [comment]
Responses to design questions:

1. Viewing member can be specific to teams
2. Qualifying and placing do need to be distinct. Process operators should assess and qualify but NOT place. They should have to go through recruiters.
3. Community Admin. "amending" is essentially re-publishing.
4. Platform Admins don't need to hold all permissions directly. Only need permissions related to their work. View all posters, but publish permissions can require a community role. View all users. View all applications.
5. We can keep the current solution for now.

Sidenote: In future, managers may be able to start draft posters without them being seen by Communities. But as soon as they want to share it with anyone else, they have to tie it to a Functional Community and Community recruiters can see it again. (edited)
