### ISSUE TITLE
♻️ Squash database migrations

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#10187]
## ♻️ Debt/Refactor

As part of the Laravel 11 upgrade we're considering squashing all our existing database migrations.

https://laravel.com/docs/11.x/upgrade#modifying-columns
https://laravel.com/docs/10.x/migrations#squashing-migrations

This might have some performance and debt cleanup benefits as well.

## 🕵️ Details

Some considerations:
- Perhaps we want to practice a database restore again before attempting this?
- We'll need to carefully synchronize this change with our release schedule and any other PRs that might contain migrations before and after it gets squashed.
- We'll need to carefully test how it behaves, both with a fresh setup and an existing environment.

## ✅ Acceptance Criteria

- [ ] Migrations squashed
- [ ] Existing migrations no longer run for new environment setups
- [ ] Running `db:migrate` on existing environments (like UAT and prod) continues to be safe

## 🛑 Blockers

Issues which must be completed before this one.

```[tasklist]
### Blocked By
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/10204
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/10205
```

**Comment by mnigh** [comment]
@esizer what is this issue blocked by?

**Comment by esizer** [comment]
Will need to install the postgres dump command to do this.
