### ISSUE TITLE
🐛 Weird to have a "status changed" notification when starting a new application

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#10208]
## 🐛 Bug

I find it weird that we get a "status changed" notification when starting a new application.

-  Like, I know, I just did that.
- Changed from "Not Available" to "Draft" makes no sense.

## 📋 Steps to Reproduce

1. Log in
2. Start a new application
3. Check your notifications

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/26c99f2c-a8ab-4600-aff2-5a1fc75d57ad)

## 🙋‍♀️ Proposed Solution

Either change the text to something like "You started a new application in xyz" or just don't fire a notification at all.

## ✅ Acceptance Criteria

- [ ] Criteria 1
- [ ] Criteria 2

**Comment by vd1992** [comment]
I vote for no notification at all. The notification would be redundant given the application creation pops a toast and redirects you to the created application

**Comment by gobyrne** [comment]
Where did this come from? I think only "final decision" and "removed" actions should trigger a notification to candidates.

**Comment by petertgiles** [comment]
This was set up almost a year ago, in  #6927, but has never been turned on with the feature flag.  As per that issue, all status changes generate a notification.

**Comment by vd1992** [comment]
The issue for this notification proper is https://github.com/GCTC-NTGC/gc-digital-talent/issues/9642 which is pending and should replace the existing status notification

**Comment by vd1992** [comment]
The linked notification issue includes removing the existing status notification, which means this issue will be resolved through it
Closing
