### ISSUE TITLE
🐛 Notification "unread" indicator at bottom of text

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#10209]
## 🐛 Bug

The "unread" indicator for the list of notifications is on the last line of text.  It looks quite strange to me.

## 🦋 Expected Behaviour

I'm not sure, but probably not the bottom line.  Vertically centred?  At the top?

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/20955167-31d0-4b46-a989-c1f731995bc3)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Criteria 1
- [ ] Criteria 2

**Comment by gobyrne** [comment]
@substrae could you please just tell us where to put this indicator?

**Comment by substrae** [comment]
@gobyrne @petertgiles 

I think we can safely align it with the center of the first line of text.

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/25cc7cad-ced9-4918-968c-745c2aaf0362)
