### ISSUE TITLE
🐛 Uneven spacing in resource training card

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#10219]
## 🐛 Bug

There is uneven spacing in resource training card.

## 🦋 Expected Behaviour

Spacing should be even

## 📋 Steps to Reproduce

1. Navigate to https://talent.canada.ca/en/directive-on-digital-talent
2. Observe uneven spacing in Training session presentation card

## 📸 Screenshot

<img width="678" alt="Screen Shot 2024-04-30 at 11 12 26" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/68a117b9-0068-46ea-acd0-da6bc1803f07">

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] even spacing in card

**Comment by substrae** [comment]
@mnigh I'd be fine getting rid of it, but you'll have to check with Lauren/Rosita about whether it's still necessary or needs to be updated. If we're keeping it, the padding should match above and below.

**Comment by mnigh** [comment]
> @mnigh I'd be fine getting rid of it, but you'll have to check with Lauren/Rosita about whether it's still necessary or needs to be updated. If we're keeping it, the padding should match above and below.

Thanks @substrae. If we get rid of it altogether, do you have a preference for how the other card would look on its own on 768px+ widths? Maybe something like the following screenshot? A lot of empty space, but trying to keep it simple without having to drastically alter the design.

## Screenshot

<img width="1166" alt="Screen Shot 2024-05-07 at 09 38 41" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/97bcbc43-8c34-49ae-93f0-1a680cc4b219">

**Comment by substrae** [comment]
@mnigh Do you happen to have a screenshot handy of what it looked like originally? I'm probably leaning towards what you've got here, but I just wanna see if we should rework it instead.

**Comment by mnigh** [comment]
> @mnigh I'd be fine getting rid of it, but you'll have to check with Lauren/Rosita about whether it's still necessary or needs to be updated.

@substrae we have approval from lauren via @marc-donofrio to 🪓 the card. 🥳

**Comment by substrae** [comment]
🪓 🪓 🪓  Okay, great! For now, because this page was in Brooke's domain, I'm going to go with your suggestion to just keep the card its current size and shift it over to the first slot in the grid on wider screens.

**Comment by mnigh** [comment]
Closing in favour of https://github.com/GCTC-NTGC/gc-digital-talent/issues/10297.
