### ISSUE TITLE
♻️ Avoid nesting component definititions

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#10228]
## ♻️ Debt/Refactor

We have a few spots where we define components within other components and should be avoiding this.

## 🕵️ Details

Some pages have conditional rendering or other such control logic for rendering different content. Instead of using different components, we define and redefine components inside of others. This is [a common pitfall](https://react.dev/learn/your-first-component#:~:text=Components%20can%20render%20other%20components%2C%20but%20you%20must%20never%20nest%20their%20definitions%3A) in react that should be avoided.

## 🙋‍♀️ Proposed Solution

Find places where we engage in this pattern and refactor to define those components at the top level rather than nested inside their parent component.

## :world_map: Locations

- [ConsideredLanguages](https://github.com/GCTC-NTGC/gc-digital-talent/blob/a358b73f3da67e5893fc76a4790e045708c541d7/apps/web/src/components/Profile/components/LanguageProfile/ConsideredLanguages.tsx#L41-L71)
- [ScreeningDecisionDialogFrom](https://github.com/GCTC-NTGC/gc-digital-talent/blob/a358b73f3da67e5893fc76a4790e045708c541d7/apps/web/src/components/ScreeningDecisions/ScreeningDecisionDialogForm.tsx#L111-L126)
- [ExperienceItem](https://github.com/GCTC-NTGC/gc-digital-talent/blob/6560e7589fac549577fd5b9428aacf085a18257f/apps/web/src/components/UserProfile/PrintExperienceByType/ExperienceItem.tsx#L45-L59)
- [LinkCareerTimeline](https://github.com/GCTC-NTGC/gc-digital-talent/blob/c17cee02ede23d2889273e79e621ce614b28675f/apps/web/src/pages/Applications/ApplicationEducationPage/LinkCareerTimeline.tsx#L172-L289)
- [SignedOutPage](https://github.com/GCTC-NTGC/gc-digital-talent/blob/a9d2747db9cde770e3b100467e12c7554d17b2d7/apps/web/src/pages/Auth/SignedOutPage/SignedOutPage.tsx#L30-L38)
- [SignInPage](https://github.com/GCTC-NTGC/gc-digital-talent/blob/a9d2747db9cde770e3b100467e12c7554d17b2d7/apps/web/src/pages/Auth/SignInPage/SignInPage.tsx#L67-L71)
- [SignUpPage](https://github.com/GCTC-NTGC/gc-digital-talent/blob/a9d2747db9cde770e3b100467e12c7554d17b2d7/apps/web/src/pages/Auth/SignUpPage/SignUpPage.tsx#L74-L78)
- [SkillWithExperiences](https://github.com/GCTC-NTGC/gc-digital-talent/blob/a9d2747db9cde770e3b100467e12c7554d17b2d7/apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/ApplicationPrintButton/SkillWithExperiences.tsx#L85-L130)
- [ProfileDetails](https://github.com/GCTC-NTGC/gc-digital-talent/blob/a9d2747db9cde770e3b100467e12c7554d17b2d7/apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/ProfileDetails/ProfileDetails.tsx#L21-L118)??
- [ViewPoolCandidatePage](https://github.com/GCTC-NTGC/gc-digital-talent/blob/a9d2747db9cde770e3b100467e12c7554d17b2d7/apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/ViewPoolCandidatePage.tsx#L592-L729)
- [DeleteDialog](https://github.com/GCTC-NTGC/gc-digital-talent/blob/a9d2747db9cde770e3b100467e12c7554d17b2d7/apps/web/src/pages/Pools/AssessmentPlanBuilderPage/components/DeleteDialog.tsx#L18-L44)
- [SkillSummaryTable](https://github.com/GCTC-NTGC/gc-digital-talent/blob/a9d2747db9cde770e3b100467e12c7554d17b2d7/apps/web/src/pages/Pools/AssessmentPlanBuilderPage/components/SkillSummaryTable.tsx#L157-L194)
- [EducationRequirementsSection](https://github.com/GCTC-NTGC/gc-digital-talent/blob/a9d2747db9cde770e3b100467e12c7554d17b2d7/apps/web/src/pages/Pools/EditPoolPage/components/EducationRequirementsSection.tsx#L63-L79)
- [SkillAccordion](https://github.com/GCTC-NTGC/gc-digital-talent/blob/a9d2747db9cde770e3b100467e12c7554d17b2d7/apps/web/src/pages/Pools/PoolAdvertisementPage/components/SkillAccordion.tsx#L109-L123)

## ✅ Acceptance Criteria

- [ ] All components are defined at the top level

**Comment by petertgiles** [comment]
Is there an easy way to find all examples in the codebase?
