### ISSUE TITLE
✨ Use paginated query on Screening and Assessment page

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#10223]
## ✨ Feature

The screening and assessment page currently uses the `Pool.poolCandidates` field to fetch all candidates in a single query. We're aware that the number of candidates, and complexity of the PoolCandidate model, could the query to take a long time, and in worst case, crash. Also, we want to add filters to the page, which would further complicate the query.

The solution is to use pagination to load a manageable number of candidates at a time. 

## 🕵️ Details

Convert the ScreeningAndEvaluationPage.tsx component to use the `poolCandidatesPaginated` query. It should fetch candidates 100 at a time, and continue until all candidates are loaded. Don't show the results candidates until loading is complete. We have a new loading skeleton to show until then.

## 🎨 Design File

[Figma file](https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Admin---Processes%2FPools%2FRecruitments---Record-of-Decision?type=design&node-id=8738%3A34452&mode=design&t=DFf6UMQtRFQF0ln7-1) by @Jerryescandon 

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/bef80483-25f2-4f79-b012-4713a82a5f78)

## 🙋‍♀️ Proposed Implementation

Repeatedly call the paginated query to load chunks of the results, until complete. Let's say 100 at a time, if that seems reliable?

QUESTION: should we modify the Pool type in the graphql schema to make it impossible to try to load all candidates without pagination?

## 🌎 Localization

?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Instead of trying to load all candidates at once, the Screening and Assessment page uses the poolCandidatesPaginated query
- [ ] The page displays a loading skeleton until all results are loaded

**Comment by vd1992** [comment]
I think the results per fetch ought to be decided with respect to the prod environment. So to say, how long does it usually take the `poolCandidatesPaginated` query to fetch 100?
