### ISSUE TITLE
♻️ Store enabled notification preferences, not ignored preferences

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#10227]
## ♻️ Debt/Refactor

Right now, in the database, we stored which notifications are ignored, not which notifications are enabled.  This seems backwards to me and I think we should change it.

On the frontend, we have to read and store the absence of a checkmark as data.  On the backend, we have to test for the absence of data to send a notification.

## 🕵️ Details

If we switch...

Pros: 
- It makes the data model understandable more understandable.
- It becomes easier to store and test notification preferences.

Cons: 
- When we add a new notification that we want to have on by default we need to fill every existing row with it.
- When we create a new user they must be populated with the default permissions.

## ✅ Acceptance Criteria

- [ ] Database stores enabled notifications instead of ignored ones
- [ ] Existing data in database migrated
- [ ] Settings page works
- [ ] Notification sending works
- [ ] New user initialization works

## 🛑 Blockers

```[tasklist]
### Blocked By
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/10329
```

**Comment by mnigh** [comment]
> * When we add a new notification that we want to have on by default we need to fill every existing row with it.

We should not be forcing notifications on by default.
