### ISSUE TITLE
✨ Remove beta label from theme switcher

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#10299]
## ✨ Feature

The theme switcher was merged in over three months ago in https://github.com/GCTC-NTGC/gc-digital-talent/pull/9217 .  Time to remove the beta label?

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/f1c73210-5f9c-4018-932d-962460a847fa)

## ✅ Acceptance Criteria

- [ ] Beta label removed from theme switcher

## 🛑 Blockers

```[tasklist]
### Blocked By
```

**Comment by mnigh** [comment]
@GCTC-NTGC/designers do you approve so we can ✂️?

**Comment by substrae** [comment]
@mnigh @petertgiles I chatted with Marc this morning in #desfam about this very thing. We've had zero tickets related to dark mode since its release, so I think we're safe to remove it, yes.
