### ISSUE TITLE
✨ Add Community-Team and Pool-Team relations

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#10302]
## ✨ Feature

Communities and Pools need a one-to-one relationship to a Team, which will allow permissions (via Roles) to be grouped by Community and by Pool.

## 🕵️ Details

QUESTION: Should we ensure every past and future Community or Pool has a linked Team, or simply create Teams as necessary when assigning roles which need them?
1. Create and attach a team for every community and pool already in the database. Create event listeners which create and attach a team any time a new Community or Pool is created. From then on, we can assume the team field is non-null.
2. Existing pools and communities are left with no matching team. We ensure the api and/or client can interpret that has having no team members. The mutation (or seeders) which add team members to a Pool or Community must check for team existence, and create it first if necessary.

ANSWER: Lets go with number 2. If we use a polymorphic relationship, the database can't guarantee every Teamable resource has a Team. It therefore seems safest to assume that it may not, and simply interpret that as having no team members. The only place Teams need to be created should ultimately be in the mutations which assign roles (or seeders and tests, of course).

QUESTION: 
Teams need a unique `name` field, used by Laratrust. When creating teams for Communities and Pools, how should the `name` field for each team be generated? 
ANSWER: just use the name of the related data model, Community.id or Pool.id.

QUESTION: should the foreign key go on the Team table, or the Community/Pool tables? 
 - Putting the foreign key on the Team table requires using [Laravel polymorphism](https://laravel.com/docs/11.x/eloquent-relationships#one-to-one-polymorphic-relations), which adds some extra complexity and 'magic'. However, it guarantees that the Team is related to at most one resource.
 - Putting the foreign key in the Community and Pool tables is simpler (no polymorphism) and allows us to guarantee, if we want, that every Community/Pool has a Team. However, its now technically possible for one Team in the database to be related to multiple resources.
ANSWER: let's go with a Polymorphic relation. That's the way the Laravel framework intends this kind of relationship to work, and we don't want to fight the framework.

## 🎨 Design File

Include a link to the design file (if it exists).

### 🧑‍🎨 Designer

Include the author of the linked design file's name (or even better, their `@githubUsername`) for future reference.

## 📸 Screenshot

Add a screenshot of the new feature (if possible).

## 🙋‍♀️ Proposed Implementation

The relationship should probably be implemented as a "teamable" polymorphic relationship on Team. This will ensure every team is associated with a single resource, if any.

This schema attempts to simplify things by abstracting away the Team model, with the intention of later removing it entirely. The Laratrust team model is still required on the backend, acting as a kind of pivot table between RoleAssignment and a Teamable resource (Pool or Community), but it doesn't need to be visible to the client.

```
# This version attempts to abstract away the Team model, removing one extra layer for the client (and devs) to think about.
# Later we deprecate the Team model, then remove it entirely.

interface HasRoleAssignments {
  roleAssignments: [RoleAssignment!]
}
  
type Team implements HasRoleAssignments {
  id: ID!
  name: String! # represents a unique key for a team
  displayName: LocalizedString @rename(attribute: "display_name")
  description: LocalizedString
  departments: [Department] @belongsToMany
  contactEmail: Email @rename(attribute: "contact_email")
  pools: [Pool] @hasMany @canResolved(ability: "view")
  roleAssignments: [RoleAssignment!]
    @hasMany
    @canRoot(ability: "viewTeamMembers")
}
  
type Community implements HasRoleAssignments {
  ...
  roleAssignments: [RoleAssignment!]
}
  
type Pool implements HasRoleAssignments {
  ...
  roleAssignments: [RoleAssignment!]
}
  
type Role {
  id: ID!
  name: String! # represents a unique key for a role
  displayName: LocalizedString
  description: LocalizedString
  isTeamBased: Boolean
  roleAssignments: [RoleAssignment!]
}
  
# This model represents the polymorphic role_user table and allows querying the team relationship
type RoleAssignment {
  id: ID!
  role: Role
  team: HasRoleAssignments
  user: UserPublicProfile
}
```

The RoleAssignment team relationship _may_ need to be an Accessor instead of an Eloquent Relationship. It might be implementable with some kind of polymorphic hasOneThrough relationship, but the fact that sometimes it returns the pivot model (the Team itself) complicates things.

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

- [ ] Communities and Pools can be associated with a single team.
- [ ] RoleAssignment team field in schema returns Pool or Community if the team is related to that resource
- [ ] Relationships exist on Eloquent models which allow for getting the community/pool assocated with a team, or the team associated with a community/pool, or the RoleAssignments associated with a community/pool.
- [ ] It is possible to query for the Community/Pool associated with the appropriate RoleAssignment, or query for the RoleAssignments associated with a Community/Pool, provided one has the correct permissions (see #10349)

## 🛑 Blockers

Issues which must be completed before this one.

```[tasklist]
### Blocked By
- [ ] #10298 
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/10349
```

**Comment by petertgiles** [comment]
![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/1c7a5fb1-beda-4084-997a-8c435cc283db)

I think that Team won't implement Teamable, right?  Also, instead of having a field with a collection of pools it will be a collection of Teamables, right?

**Comment by petertgiles** [comment]
![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/f91d6417-8c67-466a-ad92-16087732ae53)

Related, if Team isn't a Teamable then this relationship should point to either a Team or Teamable, but can't be both, right?

**Comment by tristan-orourke** [comment]
Okay, replaced the Teamable interface with `HasRoleAssignments` interface and a `Teamlike` union type, to differentiate them from the `Teamable` polymorphic type, which appies to Pool and Community but not Teams themselves.
