### ISSUE TITLE
🐛 Notifications settings UI is backwards 

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/gc-digital-talent#10329]
## 🐛 Bug

On the new Account page the Notifications Settings section is showing the incorrect values. The checkbox values are backwards, so it's showing true for the boxes we want to ignore. Shout out to @petertgiles for catching this 🔎.

## 📸 Screenshot

![image (8)](https://github.com/GCTC-NTGC/gc-digital-talent/assets/22059495/d5beadf0-582b-471f-9b05-7f672423c6d9)

## ✅ Acceptance Criteria

- [ ] Ensure the notification default values are false if the user wants to ignore the notification type, and vise versa.

**Comment by petertgiles** [comment]
Could you check the setting link on the notifications page in this issue, too?


![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/84de2d30-ac4f-40ef-9b10-44356defaa10)
