### ISSUE TITLE
🐛 CSV column header text

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#10335]
## 🐛 Bug

Not properly loading the variable text into the cell. Likely due to the CSV not accepting styling of text, so need a string without styling used here. 

## 📋 Steps to Reproduce

1. Download pool candidates CSV
2. Observe column title

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/ea1ea2d0-9105-4bb4-8e63-217d97ee9de3)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/ef92f4e5-9f00-46d7-849f-b4c122f96f2e)

## ✅ Acceptance Criteria

- [ ] Text renders without strong tags in the CSV
- [ ] Don't forget French

**Comment by petertgiles** [comment]
Simple possible solution: https://stackoverflow.com/a/63575059
