### ISSUE TITLE
🐛 Adding showcase skills from my library doesn't work

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#10330]
## 🐛 Bug

If you have some skills in your skill library, they don't appear in the skill picker for the "my library" category.

## 🦋 Expected Behaviour

Skill library skills should appear in the skill picker (minus the ones already in a showcase?).

## 📋 Steps to Reproduce

1. Log in
2. Add at least one skill to your skill library
3. Try to add a skill to a showcase
4. Select "my library" from the skill picker

## 📸 Screenshot

https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/9ccabe5e-e926-4ace-b130-f4d3bc0d93e9

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

- [ ] Skill library skills appear in skill picker under "my library"

**Comment by esizer** [comment]
One thing to note: Looks like you only have technical skills in your library and are trying to add to your top behavioral skills so I would not expect anything to appear there.

**Comment by petertgiles** [comment]
> Looks like you only have technical skills in your library and are trying to add to your top behavioral skills

Doh!  You're right.  :eagle:   It works as expected, actually.
