### ISSUE TITLE
♻️ Move static files in `apps/web/src/assets/documents` to blob storage

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#10341]
## ♻️ Refactor

These files are all pdf, docx, or pptx and are not actually rendered as part of the application and slows down builds.

## 🕵️ Details

Currently add up to ~15MB worth of files.

## 🙋‍♀️ Proposed Solution

1. Move all the files in `apps/web/src/assets/documents` to [blob storage in Azure](https://azure.microsoft.com/en-us/products/storage/blobs) and update the links accordingly
2. Delete dir and files in `apps/web/src/assets/documents`

Custom subdomain to point to Azure hosted static files?
Consider that we may move other things to this storage solution in the future, like tc-report.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] files are still able to be accessed but not directly bundled as part of the application
- [ ] e2e tests to ensure that links to assets stay live
- [ ] redirect from old links
  - nginx?  F5 firewall?

**Comment by petertgiles** [comment]
Possible duplicate: [#9492](https://github.com/GCTC-NTGC/gc-digital-talent/issues/9492)

**Comment by mnigh** [comment]
> Possible duplicate: [#9492](https://github.com/GCTC-NTGC/gc-digital-talent/issues/9492)

Similar in that we would need static hosting set up to do both of these issues, but this issue is specific to the files in `apps/web/src/assets/documents` where as #9492 is for the two PDF files in `tc-report/assets`.

**Comment by petertgiles** [comment]
AZ-20282 submitted in Jira

**Comment by brindasasi** [comment]
@gobyrne could you bump this ticket?

**Comment by brindasasi** [comment]
Dan is currently working on this ticket at present 🥳.
