### ISSUE TITLE
🐛 Unstable story - AdminLayout

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#10343]
## 🐛 Bug

The AdminLayout story triggers diffs on unrelated branches

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/19cbdd38-a80f-4098-aba4-54710e01fd20)

## ✅ Acceptance Criteria

- [ ] Story is stable

**Comment by mnigh** [comment]
The diff started when https://github.com/GCTC-NTGC/gc-digital-talent/pull/10304 got merged into `main` (https://github.com/GCTC-NTGC/gc-digital-talent/commit/a4f74fc54ca936f73a88b14b2f5d52ef2a0b2ba3).

REF: https://www.chromatic.com/build?appId=61e099a1bb1465003a73d3ce&number=7380

## Screenshot
<img width="1019" alt="Screen Shot 2024-05-10 at 10 16 39" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/97d99e5d-2505-4c59-92f7-d39bd7485755">

**Comment by mnigh** [comment]
I also wonder if we need a story for `AdminLayout` at all. This seems more like a jest test, no?

**Comment by petertgiles** [comment]
> I also wonder if we need a story for `AdminLayout` at all. This seems more like a jest test, no?

I think we need it.  It's the only story with the side menu, right?
https://github.com/GCTC-NTGC/gc-digital-talent/issues/8184#issuecomment-1834371986

**Comment by mnigh** [comment]
> > I also wonder if we need a story for `AdminLayout` at all. This seems more like a jest test, no?
> 
> I think we need it. It's the only story with the side menu, right? [#8184 (comment)](https://github.com/GCTC-NTGC/gc-digital-talent/issues/8184#issuecomment-1834371986)

We actually have a story for the `SideMenu` component [already](https://61e099a1bb1465003a73d3ce-srsliarslj.chromatic.com/?path=/story/ui-src-components-sidemenu--side-menu), though it doesn't show the same `children` as referenced in the `AdminLayout` component.
