### ISSUE TITLE
🔤 API error messages need human-readable strings

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#10359]
## 🔤 Copy

Some API error messages are missing human-readable strings.

## 🕵️ Details

`api/database/helpers/ApiErrorEnums.php`

1. `SkillUsedByActivePoster`
2. `FailedDueToSkillBeingDeleted`
3. `CannotReopenUsingDeletedSkill`
4. `EssentialSkillsContainsDeleted`
5. `NonEssentialSkillsContainsDeleted`

## Proposed solution

Approved by @gobyrne:

- `SkillUsedByActivePoster`: This skill cannot be deleted. The skill is in use by a process that is currently accepting applications.
- `CannotReopenUsingDeletedSkill`: This process cannot be re-opened. This process contains a required skill that has been deleted.
- `FailedDueToSkillBeingDeleted`: This operation failed. This skill was previously deleted.
- `EssentialSkillsContainsDeleted`: This operation failed. This skill was previously deleted.
- `NonEssentialSkillsContainsDeleted`: This operation failed. This skill was previously deleted.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the copy has been added or updated appropriately.

- [ ] API error messages have human-readable strings in English and French

**Comment by petertgiles** [comment]
@gobyrne and @mnigh Are you up for another round of error message writing?

**Comment by mnigh** [comment]
@gobyrne what do you think?

1. `SkillUsedByActivePoster`: Cannot delete a skill being used by an active process.
2. `FailedDueToSkillBeingDeleted`: Cannot delete an already deleted skill.
3. `CannotReopenUsingDeletedSkill`: Cannot re-open a process with a required skill that has been deleted.
4. `EssentialSkillsContainsDeleted`: Cannot include a required skill that has been deleted in a process.
5. `NonEssentialSkillsContainsDeleted`: Cannot include an optional skill that has been deleted in a process.
