### ISSUE TITLE
✨ Update Request pages to include Community scope

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#10366]
## ✨ Feature

#10331 ensured every search request is associated with a community, but didn't do anything with that data. Now, we want to
1. explicitly scope the search results by community
2. label the community on the Request page, on the admin side
3. ensure new Community roles can see requests to their community

## 🕵️ Details

1. Community field in ApplicantFilter scopes search results to candidates in pools in that community
2. Somewhere on the Single Request page, the associated Community is listed
3. Community becomes an input field in Candidate Table filter modal
4. Community column added to Request table, but hidden by default
5. Requests index and Single Request page become available to Community Admin and Community Recruiter roles. Link to Requests page is available on dashboard and in nav menu.
6.  authorizedToView scope on requests query should ensure the new roles only see requests in their communities. Policies to view requests, to search candidates, and to update requests (notes, status) are updated for these roles, if necessary. Legacy roles continue to work.

## 🎨 Design File

[Figma file](https://www.figma.com/design/em5ArPr044YaIe1Vb1zCZz/Record-of-Decision-(Communities)?node-id=9374-59294&t=2MFpsy3hqotDbLKI-1) by @Jerryescandon 

## 📸 Screenshot

Jerbo: "Given the amount of fields, we might need to rework this whole card into 3 columns instead"

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/0d893cec-aa83-4b51-88b5-b3b473887424)

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Community field in ApplicantFilter scopes search results to candidates in pools in that community
- [ ] Somewhere on the Single Request page, the associated Community is listed
- [ ] Community becomes an input field in PoolCandidates Table filter modal
- [ ] Community column added to Request table, but hidden by default
- [ ] Requests index and Single Request page become available to Community Admin and Community Recruiter roles. 
- [ ] authorizedToView scope on requests query should ensure the new roles only see requests in their communities. Policies to view requests, to search candidates, and to update requests (notes, status) are updated for these roles, if necessary. Legacy roles continue to work.
- [ ] phpunit tests that the community scope works for candidate search, and that the new roles can only see the correct requests and candidates
- [ ] playwright tests for new roles able to interact with these pages

## 🛑 Blockers

Issues which must be completed before this one.

```[tasklist]
### Blocked By
- [ ] #10302 
- [ ] #10331 
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/10364
```

**Comment by petertgiles** [comment]
@Jerryescandon please add link to design and screenshot

**Comment by tristan-orourke** [comment]
@Jerryescandon I think the Community should appear in the Request Information section, not the Manager Information section. It describes who the request is made _to_ (which community responds to the request), not which community the hiring manager is part of.

**Comment by Jerryescandon** [comment]
You're right! I think I just went with instinct. I'll redo it.

**Comment by vd1992** [comment]
Blocking as some thing are not possible yet without the pool-community relation first

Like this part for example 
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/f8447512-4ae7-4604-9b51-c9b17c369d5a)

**Comment by vd1992** [comment]
@tristan-orourke 

A little confused about

![image](https://github.com/user-attachments/assets/fb897b1a-97ea-4a67-af32-5549d1d678e6)

Given no one has viewing requests scoped to their community

![image](https://github.com/user-attachments/assets/4dc56806-217e-4dfc-b6d4-bf0ec15d16bb)

![image](https://github.com/user-attachments/assets/97504bc3-dec4-4109-8c89-76be0179827c)

![image](https://github.com/user-attachments/assets/ce2b4daf-fe44-41c3-b15b-58a3e0e50721)
