### ISSUE TITLE
✨ New 2 page registration with email verification in the middle

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#10362]
## ✨ Feature

Updates to the registration form and we're adding in email verification as part of the registration process. This will change the flow of the registration UI.

## 🕵️ Details

This will break apart the registration into 2 steps:
1. One step for everyone
2. One step for government employees.

In this issue, we will be building both steps, but we will not include the collection of employee email on the employee step (and so no verification for employee email either)

## 🎨 Design File

[New registration and email verification design file](https://www.figma.com/design/L3TpcR1boZNXoSEZ4022zu/Registration-form-(All-users)?node-id=1-3&t=E520U8xrOCRY3yL8-0)

### 🧑‍🎨 Designer

@substrae 

## 📸 Screenshot

<details>
  <summary>Old Forms</summary>
### Old registration form:

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/62a7ff0b-2601-486e-8f8a-39eceeaf6608)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/7125145b-eb74-4940-a1ea-2c933a93045d)

</details>

### New registration form step 1 (all users):
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/4454219f-ddaf-41cb-a5f4-ccb26bbf83d9)

### Email verification:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/8c0e757d-cfa9-4c7f-afcb-62b180ab8574)

### New registration form step 2 (employees)
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/fe9bd841-5c09-4d69-8f79-b670f0bdbf3a)

### URLs and breadcrumbs
**URLs should be**
/getting-started
/email-verification
/employee-registration

**Breadcrumb should be**
Home > Register for all 3 (if that's a thing)

## ✅ Acceptance Criteria

- [x] Please the above URLs for the 3 pages
- [ ] New registration form **Getting started** page built to design
- [ ] **Verify your contact email** button takes you to email verification
- [ ] **Save and skip verification** link goes directly to step 2 (email verification is optional during registration)
- [ ] **Verify your contact email** page built to design.
- [ ] Button and link bring you to Employee information page (though button validates)
- [ ] New registration form **Employee information** page built to design
- [ ] All content except the Employee status is hidden until "Yes, I am a Gov..." is selected
- [ ] Do not build the work email section
- [ ] Button at the bottom brings you to the dashboard (like the current registration page)
- [ ] If "I agree to receive email notifications from GC Digital Talent" is checked, on submit: all of the users email notifications should be checked on (on their settings page)
- [ ] If "I agree to receive email notifications from GC Digital Talent" is NOT checked, they should all be set to unchecked instead
- [ ] There is no way to go back between steps. (the can change all this is their profile though) If a use tries to navigate away from these pages (but they haven't yet completed them) they should be brought back to these pages.
- [ ] Users who have already completed registration (in the past) should never be forced into these pages.

## 🛑 Blockers

Issues which must be completed before this one.

```[tasklist]
### Blocked By
- [ ] #10378
```

**Comment by brindasasi** [comment]
@substrae could make this design public?

**Comment by tristan-orourke** [comment]
Instead of `/employee-information`, I suggest the url `/employee-registration`. We might want to keep the `/employee-information` url free for a post-registration page they visit to update their employee information.

**Comment by tristan-orourke** [comment]
Recommendation for email notification consent text: "You can control which types of notifications you receive in your account settings."

**Comment by substrae** [comment]
@brindasasi as far as I know, it should already be public 🤔 

https://www.figma.com/design/L3TpcR1boZNXoSEZ4022zu/Registration-form-(All-users)?node-id=63-4848&t=WXSSbGSnO42Ih4re-4

**Comment by brindasasi** [comment]
> @brindasasi as far as I know, it should already be public 🤔 
> 
> https://www.figma.com/design/L3TpcR1boZNXoSEZ4022zu/Registration-form-(All-users)?node-id=63-4848&t=WXSSbGSnO42Ih4re-4

I wasn't be able to get it without signing in to my google account.

@vd1992 does it work for you ?

**Comment by vd1992** [comment]
> > @brindasasi as far as I know, it should already be public 🤔
> > https://www.figma.com/design/L3TpcR1boZNXoSEZ4022zu/Registration-form-(All-users)?node-id=63-4848&t=WXSSbGSnO42Ih4re-4
> 
> I wasn't be able to get it without signing in to my google account.
> 
> @vd1992 does it work for you ?

Nope

For reference, here is a Figma link with no login barrier that I can view without issue

https://www.figma.com/design/oZhQe9ahidHFfaiqgREvxa/Dashboard-(All-users)?node-id=245-10680

**Comment by substrae** [comment]
Should be working now
