### ISSUE TITLE
✨ Add Community relation to Pools

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#10364]
## ✨ Feature

Ensure all Pools, old and new, are associated with a Community. 

## 🕵️ Details

Create a relationship between Pool and Community - a required (ie non-nullable) `community_id` field on the Pool table. For existing entities in the database, assign a community the same way we did for Requests (#10331).

Community id becomes a required field on the create Pool mutation. ~At the same time, remove the team_id field in the mutation input~. Validation must ensure that the user has permission to create a pool in this community  (create-any-pool or create-team-pool).

~Replace the team dropdown~ In addition to the team dropdown on the Create Pool page, add a community dropdown. The communities that appear depend on the users roles: platform admins and the legacy roles (community admin and request responder) see all Communities. Users without those roles, but with Community Admin or Community Recruiter roles, can see the communities they are part of. (Basically, avoid inputs which will fail on the backend.)

### 🧑‍🎨 Designer

@Jerryescandon 

## 📸 Screenshot

![image](https://github.com/user-attachments/assets/6fc065dd-fda5-49ed-afdd-c1f35e663932)

## 🙋‍♀️ Proposed Implementation

A lot of this work will just involve updating policies so that the new roles can interact with the appropriate queries and mutations.

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Resolve TODOs associated to this issue by searching for 10364 in repository
- [ ] migration adds a non-nullable community_id field to pools. Existing pools have the field populated based on their work stream (existing pools belong to digital unless they are ATIP work stream)
- [ ] Add Pool.community relationship to schema and Eloquent model
- [ ] Add community to Pool factory
- [ ] ~Replace team with~ Add community in createPool mutation and validation. Policy must check that user permission to create-any-pool or create-team-pool in this Community's team.
- [ ] also update "duplicate pool" dialog
- [ ] ~Replace team with community input~ add it in beside, leave team, in Create Pool form. ~Users only see Communities in the dropdown they are will be allowed to use according to validation.~
- [ ] Community Admin and Community Recruiter roles can access Create Pool page
- [ ] PHPUnit tests that each of these roles can and cannot do the appropriate actions.
- [ ] Playwright tests that appropriate roles can do this through UI?

## 🛑 Blockers

Issues which must be completed before this one.

```[tasklist]
### Blocked By
- [ ] #10351
- [ ] #10331
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/10365
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/10566
```

## 🚚 Deployment

Run sync-roles script.

**Comment by petertgiles** [comment]
@tristan-orourke please break this up

**Comment by vd1992** [comment]
@tristan-orourke 

If the `teamId` field is being left in the create mutation, what should it reference now? Community comes from community table, should `teamId` now point at the `community->team()` relation?
Should team even be selectable by a user?

**Comment by tristan-orourke** [comment]
Okay, sorry for the confusion. The screenshot is inaccurate. We will leave the team select input as is right now, and simply add a Community select. There is no relation between this Team and this Community! This Team select will be removed in the cleanup ticket.

**Comment by Jerryescandon** [comment]
Updated screenshot
