### ISSUE TITLE
♻️ Use automatic JSX transform

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#10367]
## ♻️ Debt/Refactor

We should probably update to the automatic JSX transform.

## 🕵️ Details

It has beena  few years since React released an automatic JSX transform that has some [minor performance improvements](https://github.com/reactjs/rfcs/blob/createlement-rfc/text/0000-create-element-changes.md#motivation).

## 🙋‍♀️ Proposed Solution

Follow the guide for our setup in [the blog post](https://legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html).

## ✅ Acceptance Criteria

- [ ] React is using automatic JSX transform
- [ ] Explicit imports of `React` are removed
- [ ] Only import required items from react (hooks, types)

**Comment by vd1992** [comment]
And it appears required for the eventual full release of React 19
https://react.dev/blog/2024/04/25/react-19-upgrade-guide#installing

So look into it for sure

**Comment by vd1992** [comment]
Speaking of React 19 👀 
@tristan-orourke 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/ae38deee-75dc-42fc-a27b-cd03230044cb)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/21bd58f4-12f0-4333-9580-8325ea45a628)

**Comment by esizer** [comment]
> And it appears required for the eventual full release of React 19
> https://react.dev/blog/2024/04/25/react-19-upgrade-guide#installing

Wow, good catch! I didn't realize that :stuck_out_tongue:

**Comment by tristan-orourke** [comment]
Hmm, yeah, that useOptimistic looks like it could be a nice pattern
