### ISSUE TITLE
♻️ Remove flag - `FEATURE_PROTECTED_API`

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#10377]
## ♻️ Debt/Refactor

The flag has been true for a while and can be removed.

## ✅ Acceptance Criteria

- [ ] Remove from code
- [ ] Remove from IaC

## 🛑 Blockers

```[tasklist]
### Blocked By
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/10373
```

**Comment by mnigh** [comment]
@petertgiles what is this issue [blocked](https://github.com/GCTC-NTGC/gc-digital-talent/issues/10377#event-12835213721) by?

**Comment by petertgiles** [comment]
> @petertgiles what is this issue [blocked](https://github.com/GCTC-NTGC/gc-digital-talent/issues/10377#event-12835213721) by?

Someone needs to decide that it's been on long enough that we feel comfortable removing the ability to turn it off.  It's been on since June 12th at this point.
https://talent-cloud.slack.com/archives/C066AR2CUV7/p1718195755090329

**Comment by brindasasi** [comment]
Long enough imo. A month already. can go now
