### ISSUE TITLE
🐛 Skills page links to admin edit skills

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#10387]
## 🐛 Bug

The skill name on the non-admin skills page links to an admin page (edit skills).

## 🦋 Expected Behaviour

The skill name on the non-admin skills page should not be a link.

## 📋 Steps to Reproduce

1. Navigate to https://talent.canada.ca/en/skills
2. Hover over a skill name
3. Observe `https://talent.canada.ca/en/admin/settings/skills/:skill-id/edit` URL

## 📸 Screenshot

<img width="878" alt="Screen Shot 2024-05-15 at 10 20 59" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/644b7ffb-2660-4625-a661-ed197da82978">

## 🙋‍♀️ Proposed Solution

Prop drill new optional prop (boolean) called `adminLink` to `SkillTableApi` then to `SkillTable` and conditional render link or not based on value of `adminLink`.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/4a29a868bf29ded2ee757f85a18d0edfc31cdd4d/apps/web/src/pages/Skills/components/SkillTable.tsx#L147-L150

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] skill name should not link anywhere on non-admin skills page

**Comment by petertgiles** [comment]
@Jerryescandon Do you agree that the name of the skill should be plain text instead of a link to the "edit skills" page when the table is viewed on the /skills page?

**Comment by Jerryescandon** [comment]
> @Jerryescandon Do you agree that the name of the skill should be plain text instead of a link to the "edit skills" page when the table is viewed on the /skills page?

On the public table? yeah I agree, that makes sense. As long as the admin table retains this functionality.
