### ISSUE TITLE
✨ New page: Employment equity and recruitment 

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#10381]
## ✨ Feature

We want to include a section on the job advertisement that describes more about how employment equity is handled. It's a fair bit on information though, so we need to display it on a separate page.

Copy for the "More information" section of job ad

### English
**trigger:** How is employment equity considered in this recruitment process

**content:** If you're a member of an employment equity group, you can choose to self-identify on your profile. Learn more about how this information is used in the recruitment process.

### French NOT UPDATED YET
**trigger:** De quelle façon l’équité et l’inclusion sont-elles prises en considération dans ce processus de recrutement?

**content:** If you're a member of an employment equity group, you can choose to self-identify on your profile. Learn more about how this information is used in the recruitment process.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] New page for **Employment equity in this process**
- [ ] New "How is employment equity considered in this recruitment process" section added to job advertisement "more information" section.
- [ ] Delete commented out code for Inclusivity statement. We are replacing it with this new "employment equity" statement

**Comment by gobyrne** [comment]
NOT APPROVED ENGLISH
[Self-identification - GC Talent.docx](https://github.com/GCTC-NTGC/gc-digital-talent/files/15310466/Self-identification.-.GC.Talent.docx)

**Comment by mnigh** [comment]
> NOT APPROVED ENGLISH [Self-identification - GC Talent.docx](https://github.com/GCTC-NTGC/gc-digital-talent/files/15310466/Self-identification.-.GC.Talent.docx)

@gobyrne 

## Suggestion
> Knowing an applicant’s backgrounds

This should be either Knowing an applicant’s background or Knowing applicant’s backgrounds as **an** is singular and **backgrounds** is plural.

**Comment by mnigh** [comment]
@gobyrne now that there is an [Inclusivity and equity](https://talent.canada.ca/en/inclusivity-equity) page linked from job advertisements, is this issue still needed? 

## Screenshot

![Image](https://github.com/user-attachments/assets/f5a64d78-68e7-46f9-9ca3-f268cfff3413)

**Comment by tristan-orourke** [comment]
This is done or at least redundant now.
