### ISSUE TITLE
🔤 IT classification should still be "IT" in French, not TI (AS-SA)

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#10425]
## 🔤 Copy

The IT classification (for example IT-03) has been translated to TI-03 in French, which is incorrect. The classification should be IT in both languages.

Note that the acronym IT for Information Technology is normally translated to TI (Technology de l'Information, but not for the classification.

## 🕵️ Details

Here's where this was noticed on the job ad.

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/1c7aacc5-0af8-424f-ba96-f194104c7324)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the copy has been added or updated appropriately.

- [ ] Fix references in French to the IT classification (more information section of the job ad)
- [ ] Fix references in French to the AS classification (more information section of the job ad)
- [ ] Check to see if we can find this error happening elsewhere

**Comment by mnigh** [comment]
This is easy to fix when it refers to a group and level combined (see screenshot). The trickier part will be finding any instances of the name of the group (IT) by itself as the context will matter whether it needs to be IT or TI in French.

## Screenshot
<img width="488" alt="Screen Shot 2024-05-16 at 16 38 07" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/acafdd5f-e65c-43b0-93cc-248e722d2f14">

**Comment by mnigh** [comment]
Also, if IT is the same in both English and French for the group, is that the same or the AS group? If so, the abbreviations will need to be changed as well:

https://github.com/GCTC-NTGC/gc-digital-talent/blob/58b3ebbdb206cdc4187c3e60bb0971ff5f1655b9/apps/web/src/utils/nameUtils.tsx#L147-L179
