### ISSUE TITLE
Admin - tables - horizontal scroll bar hidden

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#1044]
The horizontal scroll bar for tables like users and pool candidates is only visible at the bottom of the table.  If there are more than about 10 rows then scroll bar is not visible.  For example, on the pool candidates table page it isn't clear that there is an edit column in the table.  If a user wants to edit the first row then they need to scroll to the bottom of the page, scroll to the right, then scroll back to the top of the page, then click edit.  Is there a better way to handle scrolling and visibility on large tables?

![Screenshot 2021-11-04 112458](https://user-images.githubusercontent.com/8978655/140352199-16c7dcf3-3ef2-4cde-9b31-12c3c4e52008.png)

**Comment by tristan-orourke** [comment]
Lets see if our table library has an option to make force the horizonal bar visible.

**Comment by yonikid15** [comment]
Adding pagination using the hook provided by [react table](https://github.com/TanStack/react-table/tree/v7/examples/pagination)
