### ISSUE TITLE
⌨ Manual accessibility testing for Notifications

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#10443]
## ⌨ Accessibility Issue

Work with @esizer to perform manual accessibility testing on the notification feature.

## Paths for testing

1. View notification on nav and activate link
2. Mark all as read
3. View notifications on nav and click to "view all notifications"
4. On notification page, view read vs unread?
5. Account settings page, toggle on/off for families
6. Read an email - send one to team? best effort

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the issue was addressed.

- [x] **Windows** Chrome + JAWS (@esizer)
- [x] **Windows** Edge + Narrator (@esizer)
- [x] **Windows** Firefox + NVDA (@yonikid15)
- [x] **macOS** Safari + VoiceOver (@mnigh)
- [x] **Android** Chrome + Talkback (@esizer)
- [x] **iOS** Safari + VoiceOver (@esizer)
- [x] Basic keyboard (@vd1992)

**Comment by petertgiles** [comment]
Plan to look at this on Friday

**Comment by vd1992** [comment]
Gave the testing a go, asked Eric some questions now and there. Thanks for answering

Issues
https://github.com/GCTC-NTGC/gc-digital-talent/issues/10637
https://github.com/GCTC-NTGC/gc-digital-talent/issues/10638
https://github.com/GCTC-NTGC/gc-digital-talent/issues/10640

**Comment by yonikid15** [comment]
Testing done, looked pretty good overall. 

Issues:
#10646 
Found same issue #10638
Found same issue #10637. When tabbing again the focus should start on the next notification, **not** the panel. Same with entering "mark all as read".
