### ISSUE TITLE
🐛 Storybook running out of memory

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#10471]
## 🐛 Bug

For some reason, we are running into a `FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory` whil trying to run storybook.

## 🦋 Expected Behaviour

Storybook is able to build properly.

## 📋 Steps to Reproduce

1. Run `pnpm run build-storybook`
2. Observe the heap error

## 🙋‍♀️ Proposed Solution

~~There is [a workaround](https://github.com/storybookjs/storybook/issues/6408#issuecomment-722692755) that seems to have some success but we should treat this as temporary if it is what we go with.~~

Workaround did not work.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] `pnpm run build-storybook` works both locally and in github actions

**Comment by esizer** [comment]
Sadly, after the new release of storybbok this is still happening 😭 

Should we try and look into this further?

**Comment by petertgiles** [comment]
Eric to write up an issue to investigate build time and large number of dependencies

**Comment by mnigh** [comment]
@esizer can this issue be closed as resolved now that storybook is using vite? It builds fine for me, how about you?

**Comment by esizer** [comment]
> @esizer can this issue be closed as resolved now that storybook is using vite? It builds fine for me, how about you?

oh, yeah. I forgot we had this issue :sweat_smile:
