### ISSUE TITLE
🐛 Can't submit talent request when not logged in

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#10476]
## 🐛 Bug

It's currently not possible to submit a talent request when not logged in.

## 🦋 Expected Behaviour

Should be able to submit a talent request when not logged in.

## 📋 Steps to Reproduce

1. Log out
2. Try to submit a talent request

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/dc0ce043-d747-42ce-9a1b-6c380ed5f974)

## 🙋‍♀️ Proposed Solution

Seems to have something to do with the canModel guard on communities.  If that guard is removed it works OK.

## ✅ Acceptance Criteria

- [ ] Can submit a talent request when not logged in.
- [ ] e2e test

**Comment by brindasasi** [comment]
Please add an E2E test for this scenario
