### ISSUE TITLE
♻️ Remove artisan-commands.cy.ts

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#10483]
## ♻️ Debt/Refactor

Time to ~move~ delete our Cypress tests 
apps/e2e/cypress/e2e/api/artisan-commands.cy.ts

## ✅ Acceptance Criteria

- [ ] Remove : artisan-commands.cy.ts

## 🛑 Blockers

```[tasklist]
### Blocked By
```

**Comment by mnigh** [comment]
@petertgiles we don't actually use any of the tests in the "real world" from `apps/e2e/cypress/support/artisanCommands.ts`.

do we still still want to keep `artisan-commands.cy.ts` and if not, is there a reason to move it over to Playwright?

**Comment by petertgiles** [comment]
> do we still still want to keep `artisan-commands.cy.ts` and if not, is there a reason to move it over to Playwright?

Yeah, we never really found it useful.  :shrug:  I'm fine with simply removing it.
