### ISSUE TITLE
✨ Inclusivity and Equity page and linking to it from the job ad

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#10508]
## ✨ Feature

We're adding a new informational page about self-declaration and linking to it from the job advertisement. This is instead of previous efforts to include an "inclusivity statement".

## 🕵️ Details

This is a new page that should be linked to from the job advertisement "More information" section. Repurpose the one for the Inclusivity statement.

H3: "How are equity and inclusion considered in this recruitment process?"
texty text: You can learn more about how our team uses employment equity information to shape equity and diversity in hiring by reading our [Inclusivity and equity statement](https://talent.canada.ca/self-declaration). We also provide an [Accessibility statement](https://talent.canada.ca/accessibility-statement) that outline how the platform considers and implements accessible best practices.

New page URL: talent.canada.ca/inclusivity-equity

## 🎨 Design File

[Include a link to the design file (if it exists).](https://www.figma.com/design/DoZfqY9Rm8FkQ3pZT3uEsz/Inclusivity-statement-(All-users)?node-id=1-2)

### 🧑‍🎨 Designer

@substrae for design question
@gobyrne for copy questions

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/7dc07d6d-eec8-4692-bdde-ee9f0419ee95)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/958d30b2-8952-4561-92df-2992f3110fbf)

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] New page created
- [ ] More information section on job advertisement updated with link to this new page

**Comment by mnigh** [comment]
Why is the path `/self-declaration` for a page that has a title of Inclusivity and equity? Shouldn't it be `/inclusivity-equity`?
