### ISSUE TITLE
✨ New language requirement dialog on the job advertisement

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#10554]
## ✨ Feature

Currently our info icon for "Language requirement" on the job advertisement simply links to the PSC website, which is probably not helpful.

This is to replace that link with a dialogue that explains things in detail (and still links to PSC).

## 🕵️ Details

New dialogue for Language requirement.

## 🎨 Design File
https://www.figma.com/design/CdYmWlP6SpT17bw7Q9411Z/Job-advertisement-(All-users)?node-id=750-8136&t=N5QD9v6vywitTObl-4

### 🧑‍🎨 Designer
@substrae 

## 📸 Screenshot

This is the icon that should trigger the dialogue:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/cce1e0b0-92a0-47f5-b86d-04527e5df990)

This is the dialogue:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/7aa976db-8dc2-4b4f-a7f4-cdb491f5799b)

I'll provided the text separately once copy is approved.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] New Dialogue in place

**Comment by gobyrne** [comment]
Here's the copy. The figma is updated now, but there were a couple small changes after the screenshot above was taken.

[Second language proficiency info.docx](https://github.com/user-attachments/files/15535593/Second.language.proficiency.info.docx)

**Comment by gobyrne** [comment]
Might be worth sending this doc as-is to translation.

**Comment by petertgiles** [comment]
There are five links in the dialog.  Could you please provide the French links as well?

**Comment by mnigh** [comment]
- @gobyrne I've added some suggestions to the copy in the Figma file.
- @petertgiles Who is the [designer](https://github.com/GCTC-NTGC/gc-digital-talent/issues/10554#:~:text=t%3DN5QD9v6vywitTObl%2D4-,%F0%9F%A7%91%E2%80%8D%F0%9F%8E%A8%20Designer,-Include%20the%20author) for this issue in case questions need to be asked?

**Comment by gobyrne** [comment]
Document and design updated based on @mnigh feedback. Thanks!

(happy to discuss why something didn't change)

**Comment by gobyrne** [comment]
French links:

- https://www.canada.ca/fr/commission-fonction-publique/services/evaluation-langue-seconde/tests-autoevaluation.html
- https://www.canada.ca/fr/secretariat-conseil-tresor/services/dotation/normes-qualification/relatives-langues-officielles.html
- https://www.canada.ca/fr/commission-fonction-publique/emplois/services/emplois-gc/exigences-linguistiques.html
- https://www.canada.ca/fr/commission-fonction-publique/services/evaluation-langue-seconde.html
- https://www.canada.ca/fr/commission-fonction-publique/services/cadre-nomination/guides-outils/evaluation-langues-officielles-cadre-dun-processus-nomination.html
