### ISSUE TITLE
✨ Migrate department field from Teams to directly on Pool

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#10566]
## ✨ Feature

Every Pool is currently associated with a Team, and each Team belongs to departments (usually one, but in some cases multiple). Teams as such will be deprecated, but Pools still need to be associated with a department - and actually, only a single department.

## 🕵️ Details

Add a `department_id` field to Pools. For all existing pools, set the department_id according to the pool's team department.
QUESTION: what do we do about multi-department teams?

Add `department: Department` field to Pool type in schema.

Add department field to Create Pool form (and matching mutation).

Update PublishPoolValidator to require a department_id.

Whenever displaying the department associated with a Pool, get it directly from Pool instead of through Team. This will affect the following files:
- QualifiedRecruitmentCard.tsx
- CareerTimelineAndRecruitment.tsx
- SearchRequests/SearchPage/hooks.ts

## 🎨 Design File

[Create new process](https://www.figma.com/design/jSZ46wE9Y1Wsf10wR5RETv/Create-new-recruitment-process-(Communities)?node-id=3-19056&t=vTakHqaDvNQ8Qg9Y-1),  [Process information and duplicate](https://www.figma.com/design/em5ArPr044YaIe1Vb1zCZz/Record-of-Decision-(Communities)?node-id=9314-66978&t=RtydYeg0RZbUFMsH-1) by @Jerryescandon 

## 📸 Screenshot

NOTE: this ticket is about adding Department to Pools. Replacing Team with Community is a _different_ ticket. The designs reflect the desired final state of these pages, which will take multiple PRs.

<details><summary>📸 Create new process page</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/459f97b0-50c4-4220-af96-0ca48776a910)

</p>
</details> 

<details><summary>📸 Process information page</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/1b936163-1c11-4a1a-9ff0-cd43fe883079)

</p>
</details> 

<details><summary>📸 Duplicate process dialog</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/14cc6516-afda-4251-ae55-09c8288a7c5a)

</p>
</details> 

<details><summary>📸 Advertisement details (editable) </summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/0d31ddaf-bb93-4c39-8d03-5546b521e975)

</p>
</details> 
<details><summary>📸 Advertisement details (static) </summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/74fef4d3-61b1-4595-a2a4-df490cdfabe2)

</p>
</details> 
## 🙋‍♀️ Proposed Implementation

You can find an update-to-date list of all the places which refer to Team.departments by removing it from the schema and attempting to rebuild the project (`make refresh`). Typescript will error anywhere it is used.

## ✅ Acceptance Criteria=

- [x] Add `department` relationship to Pool. (Eloquent model, data factory, schema, database migration)
- [x] database migration sets department on all existing Pools according to their Team (pick a random one if multiple)
- [x] department_id field added to create Pool mutation. 
- [x] Department select input added to Pool create pool form. 
- [x] Department required for PublishPoolValidator
- [x] Anywhere in UI where a Pool's department is shown, it now comes from this field, instead of from pool.team.departments.

**Comment by petertgiles** [comment]
Query to check for pools with more than one department:
```sql
select pool_id, pool_name, count(*) department_count, string_agg(department_name, ', ' order by department_name) 
from (
	select p.id pool_id, p.name->>'en' pool_name, t.id team_id, t.display_name->>'en' team_name, d.id department_id, d.name->>'en' department_name
	from pools p
	join teams t on p.team_id = t.id 
	join team_department td on t.id = td.team_id 
	join departments d on td.department_id = d.id		
) t
group by pool_id, pool_name
having count(*) > 1
```
