### ISSUE TITLE
🐛 Notes and justification checkbox not saving correctly on assessment dialog

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#10561]
## 🐛 Bug

> when I enter a decision notes and if I click on ''save the change'', if I go back to the skill to see the notes, it doesn't appear.

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/ed97d4fc-1112-4846-ab00-d5bbe7a8ee4d)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/47fadec1-aa0e-4d1b-80d3-5f044834baeb)

## 🦋 Expected Behaviour

Things should save when the save is clicked.

## 📋 Steps to Reproduce

@petertgiles and @brindasasi  reproduced it

1. Open any candidate on the Talent Assessment Tab on any process.
2. Assess any skill as "Not Demonstrated" 
3. Check any Justification check box
4. Add any notes
5. Save result and open the dialog  again 
6. Observe Requirement Decision gets populated but not Justification and notes 

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.
- [ ] Justification check box populated properly
- [ ] Notes shown on the front-end properly

**Comment by brindasasi** [comment]
It looks like the date is getting saved but not populated into the front end properly

![image (4)](https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/5c5a7538-9a6c-459b-a927-78f6b18069e4)
