### ISSUE TITLE
✨ Small update to skill experience dialogue

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#10569]
## ✨ Feature

In the skill-experience dialogue

~Make expandable always expanded~ Move out of expandable
Change copy of first bullet to: "How did you demonstrate this skill in this role?"

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/fd30ccc1-ffde-4851-8109-e535bd2dd24a)

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] ~Expandable always expanded~ Move out of expandable
- [ ] First bullet copy updated

**Comment by petertgiles** [comment]
Is there any reason to keep this as an expandable at all?
