### ISSUE TITLE
✨ Work Email Address verification

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#10574]
## ✨ Feature

This adds a flow to verify your work email during registration and on the profile. We also add in the verified/not verified chips on the profile.

## 🕵️ Details

The work email should already be collecting during registration and visible on the profile (see #10363), but here we are adding a verification step to the registration flow.

## 🎨 Design File

https://www.figma.com/design/L3TpcR1boZNXoSEZ4022zu/Registration-form-(All-users)?node-id=1-3&t=E520U8xrOCRY3yL8-0

### 🧑‍🎨 Designer

@substrae 

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/07e042f8-4efd-45c2-a7f1-15fe7c2c5071)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

## 🛑 Blockers

```[tasklist]
### Blocked By
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/10374
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/10738
```

**Comment by mnigh** [comment]
> We want to add a work email field for users.

@petertgiles what is the use case for collecting a user's work email? what kind of user would want to be contacted at their work email address when applying for jobs that are for another employer?

**Comment by petertgiles** [comment]
> what is the use case for collecting a user's work email

I really don't know know - that's more of a desfam question.  I'm guessing this is intended to be used by people on the hiring side of the application or for gov employees who are interested in movement within the organization.

**Comment by gobyrne** [comment]
Work email verification doesn't do anything until we have a "Career planning" module built. This will be added with Talent Management. I'm gonna ice-box this issue until then.

**Comment by substrae** [comment]
> @petertgiles what is the use case for collecting a user's work email? what kind of user would want to be contacted at their work email address when applying for jobs that are for another employer?

We're not contacting them at their work email, hence why we ask for contact email separately. We collect work email addresses for current GoC employees because it is the only reliable way to verify their status as an employee, something we need to do in order to provide them GoC specific hiring and career tools, as well as verifying requests for hiring manager access.

**Comment by gobyrne** [comment]
This is completed already
