### ISSUE TITLE
✨ Set Freshdesk `type` field value in support form

### ISSUE THREAD

**Issue by marc-donofrio** [GCTC-NTGC/gc-digital-talent#10581]
## ✨ Feature

The ticket type is being added as a subject via the [support form](https://talent.canada.ca/en/support). Set the "Type" field in the Freshdesk ticket to the same as the subject value.

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/42844328/81ea4669-69a3-4682-9526-30884063760e)

## 🙋‍♀️ Proposed Implementation

See https://github.com/GCTC-NTGC/gc-digital-talent/issues/10581#issuecomment-2148752414.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Set the "Type" field value in the Freshdesk ticket to the same as the subject value from the support form

**Comment by mnigh** [comment]
This is possible via setting the value of the `type` [attribute](https://developers.freshdesk.com/api/#ticket_attributes:~:text=a%20new%20contact.-,type,to%20the%20different%20kinds%20of%20issues%20your%20support%20team%20deals%20with.,-created_at) of the `ticket` object.

In the code, adding the following two pieces of code to `/api/app/Http/Controllers/SupportController.php` should do the trick:

```php
// string values available from type field via /api/v2/ticket_fields.
        $type_map =
        [
            'question' => 'Question',
            'bug' => 'Bug',
            'feedback' => 'Feedback',
        ];
```

Adding this to the `$parameters` array:
```php
'type' => array_key_exists($request->input('subject'), $type_map) ? $type_map[$request->input('subject')] : null,
```
