### ISSUE TITLE
✨ Update names of seeded users

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#10608]
## ✨ Feature

Some of our user names cause trouble for us during demos.
- "Applicant Test" gets comments sometimes that it's weird to see things like "Hey Applicant!" and "Hello Applicant" in the app.
- "Barely qualified veteran" is offensive.

## ✅ Acceptance Criteria

- [ ] Our test users like "Applicant Test" and "Admin Test" get realistic names, ~either random~ or preset.
- [ ] Test users with edgy names like "Barely qualified veteran" get softened but still descriptive names

## 🛑 Blockers

```[tasklist]
### Blocked By
```

**Comment by tristan-orourke** [comment]
Gray: the descriptive names are useful (for users like "Barely qualified veteran"), maybe just rephrase that one.

Consistent names for the base users are good (not random)

**Comment by mnigh** [comment]
Is there a list of the specific names that need to be changed and what their replacements will be?

**Comment by petertgiles** [comment]
> Is there a list of the specific names that need to be changed and what their replacements will be?

I'd suggest updating names for every user for every user in api/database/seeders/UserTestSeeder.php.

You could use resources like:
https://www.w3.org/2001/sw/rdb2rdf/wiki/Lists_of_generic_names_for_use_in_examples
https://en.wikipedia.org/wiki/Placeholder_name

For api/database/seeders/PoolCandidateTestSeeder.php, you need to soften "Barely qualified veteran" at least.  Maybe "entry-level veteran" to go with our skill levels?  You can decide if others need to be changed as well.
