### ISSUE TITLE
🐛 Profile download saves as "ApplicationSnapshot"

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#10613]
## 🐛 Bug

When you download the candidates profile it pre populates the file name  as "ApplicationSnapshot" 

## 🦋 Expected Behaviour

Candidate Profile download should save as "ApplicationProfile" 

## 📋 Steps to Reproduce

1. Go to any candidate screening & assessment page
2. Download candidate profile with the new action button. 
3. Observe it pre-populates the name as "ApplicationSnapshot" 

## 📸 Screenshot

Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

Change document title to "ApplicationProfile"

## ✅ Acceptance Criteria

- [ ] Application Profile should be saved as ApplicationProfile.pdf
  - [ ] Change applies to all variants of the document

**Comment by petertgiles** [comment]
need different file names for each file variant and FR translation

**Comment by mnigh** [comment]
## Current behaviour
The three actions currently all have the same document title (and therefore, file name) of:

- Print application: **Application snapshot**
- Print full profile: **Application snapshot**
- Print profile without contact information: **Application snapshot**

### Screenshot
<img width="398" alt="Screen Shot 2024-06-07 at 12 17 23" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/4b74004d-4233-4b5c-813e-73538babee7f">

## Proposed solution

The three actions would have different document titles (and therefore, file names) of:

- Print application:  **Application snapshot**
- Print full profile:  **Application profile**
- Print profile without contact information: **Application profile without contact information**

### Screenshot
<img width="1243" alt="Screen Shot 2024-06-07 at 12 14 40" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/857fdb52-31b9-402a-b2c9-9990ffd67c61">

## @gobyrne
If these are acceptable document titles, could you provide French translations for:

- Application profile
- Application profile without contact information

If the English strings are not acceptable, could you provide suggestions for those as well as their French translations?

**Comment by gobyrne** [comment]
EN:
- Application
- Full profile
- Profile without contact information

FR:
- La demande
- Profil au complet
- Profil sans les coordonnées
