### ISSUE TITLE
✨ Update Edit User page so new roles can be listed and assigned

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#10632]
## ✨ Feature

On the Edit User page accessible to platform admins, admins must be able to view and assign the new Process- and Community-related roles.

## 🕵️ Details

Each set of roles related to a different resource should get its own table and add/update dialog. That means one for Individual roles (already there), one for legacy teams (already there), and now one for Processes and one for Communities.

## 🎨 Design File

[Figma file](https://www.figma.com/design/vZEg5z6aXiJPNB07LamrgY/Admin---Users?node-id=270-28202&t=a8V55QLfSWP8qjKS-1) by @Jerryescandon 

### TABLES

![image](https://github.com/user-attachments/assets/1fca8b0a-9ec7-4a86-9035-a9231f66882c)

![image](https://github.com/user-attachments/assets/5c568cfc-0fce-47f2-a1a4-75076459f4ea)

### Team / Community dialogs
![image](https://github.com/user-attachments/assets/6effc4e8-63aa-4305-978f-7e86494e0777)

### Process dialogs
![image](https://github.com/user-attachments/assets/aba6d884-2383-4f4b-a028-bbf2f0a6e577)

## 🙋‍♀️ Proposed Implementation

User's dropdown in modals should use a paginated query with search.
The pools dropdown will need to work similarly.
Reference the Community table for styling of dialogs and edit columns.
Filter dialog and show/hide columns are unnecessary.

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] On edit user page, three different tables show team-based roles for LegacyTeams, Communities, and Processes
- [ ] Clicking the add role or edit buttons opens a different dialog for each table, showing the list of appropriate resources (all teams, or all communities, or all processes)

## 🛑 Blockers

Issues which must be completed before this one.

```[tasklist]
### Blocked By
- [ ] ticket number
```

**Comment by tristan-orourke** [comment]
@Jerryescandon

**Comment by tristan-orourke** [comment]
@Jerryescandon I don't think we need filters and search bar in these tables, can we remove them on figma?

The edit/delete icons look slightly different. Do you want us to update those icons/colours in all tables? Or use what we already have?

**Comment by vd1992** [comment]
@tristan-orourke 

Will need a way to query Pool/Community information from the `authInfo` object, in order to render things like process name. I don't see an existing way present so I tried something below. Thoughts?

Example changes

![image](https://github.com/user-attachments/assets/710137ab-ae0e-44d5-aa6e-af5964f36128)

Querying then

![image](https://github.com/user-attachments/assets/7796ee1f-6949-451c-a125-c8e2316970f8)

**Comment by tristan-orourke** [comment]
Okay, I see where you're going with this. It seems weird though to add the nested field when its always just `@self` - that should be info that's available on the HasRoleAssignments type directly. 

What data do you need? If its just `name: LocalizedString`, or anything else which is present on all of them, you could add that field to the `HasRoleAssignments` interface.

If you do need data which is specific to each different type, maybe we just replace the HasRoleAssignments with a union type? Something like this...
```
union Teamable = Team | Pool | Community;

type RoleAssignment {
  id: ID!
  role: Role @belongsTo
  teamable: Teamable
  team: Team @belongsTo
  user: UserPublicProfile @morphTo
}
```

My main concern would be authorizing access to the full Teamable models. If we add a `canResolved` directive, like `teamable: Teamable @canResolved(ability: "view")`, will Lighthouse correctly call the correct Team/Pool/Community policy?

**Comment by vd1992** [comment]
Name is something different on the team type

![image](https://github.com/user-attachments/assets/bd96f69c-a4c1-453b-bd2b-9259bb549d03)

**Comment by vd1992** [comment]
Trying 

![image](https://github.com/user-attachments/assets/5f68a424-377e-42f6-b14d-364a1c88e80c)

Then querying, authorization error 

![image](https://github.com/user-attachments/assets/894e48b7-8a4d-4720-8b1f-c668fa81fedb)

Commented out `teamable` then success

![image](https://github.com/user-attachments/assets/a05b13b0-9e55-4810-ad57-173b3c32d887)

**Comment by vd1992** [comment]
Playing around with suggestion from before

Good news: It successfully passes, fetching the nested teamable

Bad news: It always successfully passes, even I want it to fail. Guess I need to keep experimenting

**Comment by vd1992** [comment]
Okay, after further experimentation this seems... to work?

Schema changes

![image](https://github.com/user-attachments/assets/62660672-851e-4fbb-a9e6-0d9a7337ed3a)

RoleAssigment model change

![image](https://github.com/user-attachments/assets/c910a626-8295-49d7-a577-f46c9aaaf00f)

UserPolicy addition

![image](https://github.com/user-attachments/assets/af5d64ad-39cf-4141-b78c-82b9763d4e5a)

**Comment by tristan-orourke** [comment]
Ooh, this is some clever workarounds, especially moving the authorize check to the attribute getter! I wonder if we could combine that strategy with what we were trying the other day, to simplify this...

1. keep the teamable field in RoleAssignment instead of HasRoleAssignments, and add `@guard`
2. In RoleAssignment.php:
```
public function getTeamableAttribute()
    {
        $this->loadMissing('team', 'team.teamable');

        if (is_null($this->team)) {
            return null;
        }

        if (is_null($this->team->teamable)) {
            Gate::authorize('view', $this->team);
            return $this->team;
        }
       
        Gate::authorize('view', $this->team->teamable);
        return $this->team->teamable;
    }
```

**Comment by vd1992** [comment]
> keep the teamable field in RoleAssignment instead of HasRoleAssignments,

Breaks existing frontend, so would require refactoring anywhere teamable was already being queried. For example

![image](https://github.com/user-attachments/assets/c4271f29-3249-45f5-a9ad-27be702cae72)
