### ISSUE TITLE
🐛 Update notifications pane text and `null` state message

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#10639]
## 🐛 Bug

The null state message for the notifications pane includes references to features that do not exist. And the notification pane copy could be better for users implying assistive technologies.

## 📋 Steps to Reproduce

1. Navigate to notifications page
2. Observe copy that does states "As you receive notifications, they'll appear here and automatically be categorized on whether you've actioned or pinned them.

## 🙋‍♀️ Proposed Solution

Implement copy as in this screenshot please:

![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/6b3b1d16-4da7-46a9-9656-286d2e6ae5d0)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] copy updated in pane
- [ ] copy updated in null state

**Comment by gobyrne** [comment]
I merged in #10641

**Comment by esizer** [comment]
The copy seems inaccurate. 

The message is displayed when there are no unread notifications. Saying "You haven't received notifications yet!" implies you have never received any notifications but the user could have and just marked it as read so it would no longer show up.

**Comment by brindasasi** [comment]
@substrae is gonna change the copy for it.

**Comment by substrae** [comment]
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/216eafbf-c55b-4dba-93d2-609f4a202558)

**Comment by substrae** [comment]
Does this work? 
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/e49ce583-bb98-4a83-9cba-238940ecfb62)

**Comment by brindasasi** [comment]
updated A/C with the new image as above
