### ISSUE TITLE
♻️ Update database passwords

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#10631]
## ♻️ Debt/Refactor

As far as I know, our database passwords have never been changed.  We should probably change these and plan to update them periodically.  This will cause a small outage while the app service is refreshed so it should probably be done during low usage hours.

If PowerBI is using the same account we should probably get that moved to its own read-only account first.

## ✅ Acceptance Criteria

- [ ] PRD database password changed
- [x] UAT database password changed
- [x] DEV database password changed

## 🛑 Blockers

```[tasklist]
### Blocked By
```

**Comment by tristan-orourke** [comment]
Where/how do we store and share these passwords?

**Comment by petertgiles** [comment]
> Where/how do we store and share these passwords?

These are in the Azure keyvault for our app.  External uses, like Powerbi, should probably not be using the same accounts as noted.

**Comment by brindasasi** [comment]
I'll update the password after hours tonight.

**Comment by brindasasi** [comment]
Gray mentioned there was a pool closing last night. So we scheduled the update for tonight.

**Comment by brindasasi** [comment]
At scrum we decided we would update this as part of deployment on Sep.26

**Comment by brindasasi** [comment]
This has been completed on Friday Oct.27
