### ISSUE TITLE
🔤 Notifications panel instructions are unnecessary

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#10641]
## 🔤 Copy

Notification instructions are unnecessary and take up a lot of extra space where space is limited (panel).

## 🕵️ Details

- Welcoming a user to a panel seems peculiar. A user doesn't need to be welcomed to every element of the site (they are already welcome to the account page)
- "Click or tap a notification" is ableist language and not accurate for users who are not clicking or tapping.
- Referencing an icon that AT users cannot see is confusing.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/2144101dc47d7415748a749fbb71dde717e68986/apps/web/src/components/NotificationDialog/NotificationDialog.tsx#L145-L158

## 🙋‍♀️ Proposed Implementation

Remove paragraph: Welcome to your notification panel. Click or tap a notification to be taken to the relevant page. Use the <icon></icon> icon to mark a specific notification as read, pin it, or delete it.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the copy has been added or updated appropriately.

- [ ] Notification panel instructions are removed

**Comment by gobyrne** [comment]
This was merged into #10639
