### ISSUE TITLE
✨ Updates to the directive page

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#10647]
## ✨ Feature

Address some changes require to the directive page based on the changes with the directive:

1. New banner
2. Copy changes throughout
3. **Complete your mandatory forms** section overhauled (now called **mandatory reporting**)
4. **General resources** section removed
5. 8 new documents to replace the current ones
6. **Group-specific resources** renamed to **Resources** and PDFs removed (files also updated)
7. New "2024 changes to the Mandatory Procedures" section

 
 
### New copy

**English copy - new text included and changes marked with track-changes**
[Directive page on platform.docx](https://github.com/user-attachments/files/16899927/Directive.page.on.platform.docx)

**French copy - new text included, but changes not highlighted**
[Directive page on platform_FR.docx](https://github.com/user-attachments/files/16894458/Directive.page.on.platform_FR.docx)

### 8 new files to replace current ones

Also the _Department-Specific Recruitment Form_ and _Forward Talent Plan Form_ have been removed completely.

**Contracting form:**

The link to download this file is used on on other Government of Canada pages (canada.ca) so the download URL must NOT change. Those other links must seamlessly switch over to the new file.

[Digital Services Contracting Questionnaire - 2024 revisions.docx](https://github.com/user-attachments/files/16894123/Digital.Services.Contracting.Questionnaire.-.2024.revisions.docx)

[Questionnaire d'octroi de contrats nueriques - révisions 2024.docx](https://github.com/user-attachments/files/16894127/Questionnaire.d.octroi.de.contrats.nueriques.-.revisions.2024.docx)

**Guidance - Manager**
[Guidance_Manager_text_EN.docx](https://github.com/user-attachments/files/16894131/Guidance_Manager_text_EN.docx)

[Orientation_gestionnaire_texte_FR.docx](https://github.com/user-attachments/files/16894133/Orientation_gestionnaire_texte_FR.docx)

PDF version will no longer be available for download

**Guidance - Procurement**
[Guidance_Procurement_text_EN.docx](https://github.com/user-attachments/files/16894137/Guidance_Procurement_text_EN.docx)

[Orientation_approvisionnement_texte_FR.docx](https://github.com/user-attachments/files/16894139/Orientation_approvisionnement_texte_FR.docx)

PDF version will no longer be available for download

**Guidance HR**
[Guidance_HR_text_EN.docx](https://github.com/user-attachments/files/16894140/Guidance_HR_text_EN.docx)

[Orientation_RH_texte_FR.docx](https://github.com/user-attachments/files/16894141/Orientation_RH_texte_FR.docx)

PDF version will no longer be available for download

## 🎨 Design File

@JoshBeveridge 
https://www.figma.com/design/e65IMNNnFVTK0LVfTnzyjR/Directive-on-Digital-Talent-(All-users)?node-id=429-12263&node-type=FRAME&t=JWkFhlr3txOjE69u-0

### 🧑‍🎨 Designer

Include the author of the linked design file's name (or even better, their `@githubUsername`) for future reference.

## 📸 Screenshot

Add a screenshot of the new feature (if possible).

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [x] New banner
- [x] Copy changes throughout
- [ ] Complete your mandatory forms section overhauled (now called mandatory reporting)
- [x] General resources section removed
- [ ] 8 new documents to replace the current ones
- [ ] Group-specific resources renamed to Resources and PDFs removed (files also updated)
- [x] New "2024 changes to the Mandatory Procedures" section

**Comment by mnigh** [comment]
@gobyrne should this issue have the [`blocked: design`](https://github.com/GCTC-NTGC/gc-digital-talent/labels/blocked%3A%20design) label instead of the [`blocked` ](https://github.com/GCTC-NTGC/gc-digital-talent/labels/blocked)label since the issue description mentions a new design feature? 
> Temp banner or new section : "changes to the mandatory procedures"

**Comment by petertgiles** [comment]
Remember: documents live in Azure static hosting now, not the repository.

**Comment by tristan-orourke** [comment]
We've decided its okay if the form updates before the deployment goes live

**Comment by tristan-orourke** [comment]
@petertgiles is happy to upload the files to blob storage even if someone else picks up the other changes
