### ISSUE TITLE
🛠️ Fix playwright trace

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#10654]
## 🛠️ Tooling

We aren't getting our playwright test results uploaded on failure which is making troubleshooting difficult.

## ✅ Acceptance Criteria

- [ ] Playwright report generated in CI
- [ ] Report is uploaded and available in summary

**Comment by petertgiles** [comment]
@esizer Could you refocus this issue (or create a new one) to look at the Playwright trace upload issue directly?
