### ISSUE TITLE
⚙️ Re-usable email verification form component

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#10687]
## ⚙️ Summary

This component is intended to accept and validate email verification codes. Email verification can happen in several different flows and will eventually be used for both contact email and work email.

## 🎨 Design File

This shows the component inside the registration flow.

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/9cb22a83-3556-44e1-9583-f7763aacb2ff)

https://www.figma.com/design/L3TpcR1boZNXoSEZ4022zu/Registration-form-(All-users)?node-id=1-3&t=a3wTjPxGnZCtAvU4-1

### 🧑‍🎨 Designer

@substrae 

### ✅ Design checklist

- [ ] Default component
- [ ] Dark mode component
- [ ] Component variants (allow for work email in the future, but should only work with contact email for now)
- [ ] Dark mode component variants (if applicable)
- [ ] Foundational design info (e.g. color info, icons, helpful values)
- [ ] Mobile (`base` query) layout and space diagram
- [ ] Desktop (`p-tablet` query or larger) layout and space diagram

#### Description

Property description.

#### Screenshot

Property screenshot(s).

## 💡 Interaction states

Summary of interaction states.

#### Description

Hover state description.

#### Screenshot

Hover state screenshot.

#### Description

Focus state description.

### Screenshot

Focus state screenshot.

### Accessibility feature name

Feature description.

## Acceptance

- [x] reusable form component
- [x] can be used for different types of email addresses
- [x] "skip for now" can sometimes not exist
- [x] generates an event so host page can handle navigation/redirects
- [x] throttles "request new code"
- [x] toast messages as provided
- [x] storybook story
- [x] jest test

**Comment by gobyrne** [comment]
Toast notification upon requesting another link to be sent (for now at least).

**Comment by gobyrne** [comment]
Error messages for incorrect codes (and similar). @substrae

**Comment by substrae** [comment]
@tristan-orourke can you let me know if I've missed any error codes you're worried about? In the following ones, feel free to replace the values as applicable (e.g. 1 minute to whatever our actual delay is). 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/2fdd2c97-d92c-459b-8b51-d99cc06033ff)

**Comment by petertgiles** [comment]
@substrae is there a mobile design for this? 


![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/09470e42-bb5a-415b-bf44-12fac85ed759)

**Comment by substrae** [comment]
Hey, sorry - here's something to work from. Note that I've reordered the "Didn't receive a code?" statement to be above the button on mobile only; this is to ensure the troubleshooting tool is visible before the submit to avoid any frustration from being stuck and not knowing what to do next.

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/87883197-c90b-4366-8fbc-c2c21dc6cc26)
