### ISSUE TITLE
✨ Process number needs to be added into additional places

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#10695]
## ✨ Feature
Feedback from UAT. 
Basically wherever the pool has been mentioned process no should be added in there. Most of the pools have exactly same no and process no will be the only thing we have to identify them uniquely. 

On the job poster process no is in the very bottom of the page which is difficult to find

## 🕵️ Details

Process no needs to be added in Pool Candidate table , Other Processes table and in the job poster as well 
(see screenshots) 

## 📸 Screenshot

![Screenshot 2024-06-18 161048](https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/7054f05f-c137-43b0-89de-427401029a54)
![Screenshot 2024-06-18 160335](https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/5ed40a0d-2860-4ef9-b55d-ae3a823dedd7)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Process no should be added in both places mentioned in the screenshots 
- [ ] new column Process number and it is sortable and filterable

**Comment by Jerryescandon** [comment]
1 - Process number should already be in the candidate table as per #10579 (probably hidden by default)
2 - It's ok to add to table on candidate profile
3 - I would recommend @brindasasi and @substrae get together to discuss the specifics of the feedback and best location for this information, assuming current placement didn't work.

**Comment by gobyrne** [comment]
@Jerryescandon actually #10579 only added the Process number to the processes table :/

I don't want to put the process number in the main information of the job advertisements. I'd like to push back on that request. The advertisement is designed for applicants, not for HR.

**Comment by substrae** [comment]
Agree with @gobyrne. Definitely not moving the process number up on the job ad page - it is entirely irrelevant to the primary users of that page and will only create bloat and confusion.
