### ISSUE TITLE
🧪 Update phpunit tests to account for new roles

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#10690]
## 🧪 Tests

Update PHPUnit tests to include tests for new roles: Process Operator, Community Manager, and Community Recruiter.

## 🕵️ Details

Tests which definitely need some attention:
- RolePermissionTest.php
- UserPolicyTest.php
- PoolPolicyTest
- PoolCandidatePolicyTest
- UserTest (testRoleAssignmentsScope)
- UserRoleTest
- UpdateUserTeamRolesTest

Furthermore, do a global search for `assertGraphQLErrorMessage('This action is unauthorized.')`, and consider checking the new roles anywhere that is used.

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt tests were properly updated and remains functional/passing.

- [ ] Existing PHPUnit tests which interact with roles also check the new roles now

## 🛑 Blockers

Issues which must be completed before this one.

```[tasklist]
### Blocked By
- [ ] #10621 
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/10364
```

**Comment by vd1992** [comment]
Blocking on https://github.com/GCTC-NTGC/gc-digital-talent/issues/10364
Multiple things to test need that relation I believe
