### ISSUE TITLE
🐛 Immediately closed pools showing misleading deadline on the job poster

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#10694]
## 🐛 Bug

Pools can now be forcibly closed immediately. In those cases , poster says deadline as the closed date. This will be confusing for the applicant as  the day is not over yet but there is no Apply button given and there is no indication that this job opportunity is closed now. Especially you get the notification to apply to this job and when you go there , there is no button to apply to the job and no indication on why. 

## 🦋 Expected Behaviour

Closed job posters should say so.  
`Deadline : The deadline is now expired. `  ( or something like that) 

## 📋 Steps to Reproduce

1. Create a job poster and publish it. 
2. Observe you get the notification for it.
3. Close the pool using the given option close immediately 
4. Now click on the notification link and go the job poster.
5. Observe there is no apply button but the deadline says today's date and there is no indication of the job is now closed.

## 📸 Screenshot

![Screenshot 2024-06-18 152858](https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/ae359d10-1e21-4e88-b34d-a85903c38204)

## 🙋‍♀️ Proposed Solution

![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/f83cd5f9-0c9b-4b9d-b89e-8b3f983453b1)
![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/16f39ea0-67d0-4015-b2d2-59863507ec50)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] If the pool is closed early it should display above text and the info icon should show the dialog ( Forcibly closed pools can be detected by the reason field? )  
- [ ] If the pool is expired on its own, current functionality remains.

**Comment by brindasasi** [comment]
@GCTC-NTGC/designers  Could any of you suggest what should be happening in here ?

**Comment by substrae** [comment]
@brindasasi I think we should be more literal about our messaging in this unique circumstance. Something like:

>This job was closed early.

And then have a custom dialog that explains why that might happen, and what the user can do as next steps:

>Why is this opportunity no longer available?
>
>In some rare cases, you might be notified about a job opportunity that then indicates that it has "closed early". This happens when the job advertisement is published with incorrect information or there is a human resources requirement that needs to be changed. In order to maintain fairness, these opportunities are closed so that the updates can be performed and published as a new advertisement.
>
> It's likely that a new version of this advertisement will be published in the future, so please check back for more information.

**Comment by brindasasi** [comment]
@substrae could we get a design for this when you have some time as in where to add the dialog? 
This issue could avoid some frustration between applicants and recruiting team.

**Comment by substrae** [comment]
@brindasasi 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/65c4b4ef-4d65-409c-a1a7-7232eb2e7beb)

The "i" info icon should then trigger this custom dialog:

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/49c3347f-50dc-4acc-92e9-345905d60eb4)

**Comment by brindasasi** [comment]
Prioritizing this as applicants actually started calling about recently closed pool 😅
