### ISSUE TITLE
✨ Stepper Page - Hiring Mechanism

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#10757]
## ✨ Feature

Let's fill in the "Hiring Requirements" stepper page.

## 🕵️ Details

Q do we need to protect the user's name?  We consider this part of the public profile currently.
A: Yes, manager doesn't have access to the user's information, including name

Q: What does the review filters button do?
A: For first pass, maybe just add asset filters

Q: what do the two drop downs do?
A: Add filters to only the first table

Q: What are "pre-qualified candiates"
A: Someone who was qualified into a pool or gov employee at the same classification and group level

Q: What does the magnifying glass button do?
A: Opens a details dialog, design TBD

## 🎨 Design File

https://www.figma.com/design/oUIFoHHAZ5FwFcGHc8p7Yt/Manager---Self-referral?node-id=694-12966&t=02O1Hr5NpXu77tDo-4

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/a9a78b07-5ba7-43df-91c5-e2c30cb4caa0)

## ✅ Acceptance Criteria

- [ ] Page contains all fields
- [ ] Fields that exist in data model are saved on submission
- [ ] Successful submission saves the fields and advances stepper state
- [ ] Fields that can't be saved in data model are noted in a Phase 2 issue

## 🛑 Blockers

```[tasklist]
### Blocked By
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/10751
```

**Comment by yonikid15** [comment]
I fear that the table won't fit on most screens. Is it possible if we move the form above, and have the table stretch the full screen?

**Comment by petertgiles** [comment]
Milestone closed
