### ISSUE TITLE
🐛 CommunitySeeder missing from ProdSeeder

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#10767]
## 🐛 Bug

The Community Seeder seeds standard prod data but is missing from the ProdSeeder.

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/50ee9bb2-104b-4b2f-b26d-147a4cc89410)

## ✅ Acceptance Criteria

- [ ] CommunitySeeder is in ProdSeeder

**Comment by brindasasi** [comment]
Good catch. I remember running this seeder alone on prod from a deployment notes. 
Probably I should take a note to check whether this has been added in prod seeder as well.
