### ISSUE TITLE
✨ Switch /manager paths to use protected endpoint

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#10762]
## ✨ Feature

We have a batch of new manager pages coming through.  Since these all need elevated privileges we'll need to make sure they're using the protected endpoint.  Let's create these pages under the `/manager` path.

## :question: Questions

Q: Should we ask IMTD to get the F5 to block page loads under /manager as well?  It would be consistent with the current setup but doesn't really improve UX or security.
- Let's not block the page itself

Q: The current setup relies on having a different root layout for the admin site.  That solution might not make sense with the new unified site layout that desfam is pursuing.  Do we need to think of a new solution?
- We should still keep manager-specific pages under the `/manager` url.

Note: The page `/manager` itself should be public. But other pages under it should be protected.

## ✅ Acceptance Criteria

- [ ] Pages under the `/manager` path use the /admin/graphql endpoint
- [ ] The `/manager` page itself uses the public endpoint

## 🛑 Blockers

```[tasklist]
### Blocked By
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/10793
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/10785
```

**Comment by mnigh** [comment]
@petertgiles The manager home page which would fall under `/manager` is linked on the home page. Would it be removed from the home page or include something about having to log in first? It may not great to suddenly get served with the `restricted.html` page for links that are feature prominently on the "public" facing site.

## Screenshot
<img width="900" alt="Screen Shot 2024-06-21 at 15 54 36" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/67843fce-0328-46dc-b0c1-2bb8f06e4abc">

**Comment by petertgiles** [comment]
> The manager home page which would fall under `/manager` is linked on the home page.

Hmm, good catch.  @substrae and @brindasasi what are you thinking of as far as URLs for the future dashboards, including the manager dashboard?  Is protecting everything under /manager not the right move?

**Comment by tristan-orourke** [comment]
Note: there aren't any pages under `/manager` yet, so you'll have to make something up to test it.

**Comment by tristan-orourke** [comment]
Looks like we won't actually be releasing the manager dashboard for now. We can bring this back if necessary.
