### ISSUE TITLE
🐛 Unable to submit request with no communities

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#10768]
## 🐛 Bug

We recently added community relationship to `PoolCandidateSearchRequest` assuming communities would exist. However, this is not always the case.

## 🦋 Expected Behaviour

Communities should always exist since they are required.

## 📋 Steps to Reproduce

1. Delete communities
2. Attempt to submit a search request
3. Observe the failure

## 📸 Screenshot

![341873368-10f87e8a-23f4-4451-88fb-4ce0004850d8](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/141b00a7-b32d-44d4-be26-674259978a18)
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/a6a3208d-27bb-48df-b4f9-84e6ce3bfc79)

## 🙋‍♀️ Proposed Solution

Ensure community seeders run on all verticals so they exist in those environments.

## ✅ Acceptance Criteria

- [ ] Communities always exist when building an environment
- [ ] Search requests can be submitted after setup

**Comment by petertgiles** [comment]
I added https://github.com/GCTC-NTGC/gc-digital-talent/issues/10767 to fix the seeder.  Can we fix the code on the page it's safer?  Throw an error toast?  Is "pick the first random community" the best fallback?

**Comment by petertgiles** [comment]
Decision: No need to tweak page, this will be fixed by adding communities to the prod seeder.
