### ISSUE TITLE
🐛 Updating Experience with linked Skills can be confusingly slow

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#10783]
## 🐛 Bug

Certain users have reported needing to save experiences / skills several times before it works. 

We've seen in monitoring that UpdateWorkExperience requests have taken up to 18 seconds! We suspect that the operation is taking so long, without ongoing feedback, that user's think it finished but failed, instead of being slow.

The issue is probably in the `Experience.php connectSkills()`, which is looks complex and might very well be slow for a higher number of skills.

## 🦋 Expected Behaviour

1. update____Experience mutations should take no more than a second or two to complete.
2. It should be clear to users when the operation completes vs is still in progress.

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Name and version (if possible).
- **Browser**: Name and version (if possible).

## 📋 Steps to Reproduce

1. Find the log from the production that takes 18 secs and analyse it
2. ...

## 📸 Screenshot

Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

😬 I haven't looked at the connectSkills function since I wrote it - don't have thoughts yet on improving it.

~QUESTION: should we change the UI at all to better indicate when a request is in progress? Talk to designers.~

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] update____Experience mutations should take no more than a second or two to complete.
- [ ] Upon clicking the save button , button goes disabled and caption should say "Submitting" until the request returns. 
- [ ] Close the save dialog only when the request is completed successfully. 
- [ ] Have the dialog open when the request is failed and show the failure toast message.

**Comment by tristan-orourke** [comment]
I tried updating an experience with up to 10 related skills, on production, and the mutations took no longer than 0.6 seconds. With trouble reproducing it, we should focus on investigating the specific requests which were logged.

**Comment by brindasasi** [comment]
@petertgiles is that possible for you to grab a specific query that took 18 secs from the logs?

**Comment by petertgiles** [comment]
> @petertgiles is that possible for you to grab a specific query that took 18 secs from the logs?

There were two queries together which averaged 18 seconds: 12 and 24.  They were identical:
> [2024-06-24 22:38:34] [production.INFO](http://production.info/): Slow Query, 24.071018619, UpdateWorkExperience, https://talent.canada.ca/en/applications/fdcfaf5f-8274-4c42-a73a-2c723bc30244/skills, "mutation UpdateWorkExperience($id: ID!, $workExperience: WorkExperienceInput!) {\n updateWorkExperience(id: $id, workExperience: $workExperience) {\n id\n __typename\n }\n}"

**Comment by petertgiles** [comment]
I started working on a branch with frontend changes.  The experience update forms do not have any indication that the form is busy if the mutation takes a long time and allows duplicate submits.  This becomes obvious if you artificially slow down the API.  I started moving them to submit buttons or at least disabling the button while busy.
https://github.com/GCTC-NTGC/gc-digital-talent/tree/10783-fix-slow-experience-add

**Comment by esizer** [comment]
I'm having a really hard time pin pointing this 😅 I think the issue is, locally it is not really an issue. I tried doing some investigation by logging out times from DB and the steps of the function but since it is all local the numbers are in the magnitude of milliseconds and it is hard to gauge.

I wonder if we can do some testing on dev and get some logs from that so we can see maybe where it is struggling?

**Comment by vd1992** [comment]
Maybe it was a particular hiccup at the exact time and nothing is an issue with the mutation itself? But then, it becomes a case of can we reconstruct said hiccup?

**Comment by tristan-orourke** [comment]
Okay, if it seems quick in testing lets not worry about the mutation itself. Could you double check the other three acceptance criteria?
