### ISSUE TITLE
🐛 `ExperienceSortAndFilter` lacks spacing

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#10784]
## 🐛 Bug

There is not enough space between actions and well or cards.

## 🦋 Expected Behaviour

There should be more spacing between actions and well or cards. 

Figma file for reference (thanks @substrae): https://www.figma.com/design/UeTUDknj3s9ZgLCFF8eTcU/Profile%3A-All-pages-(Applicants)?node-id=1-6739&t=lq8EZV6zlZUrJaGL-0

## 📋 Steps to Reproduce

1. Navigate to `/applicant/career-timeline#manage-your-career-timeline`
2. Observe lack of space between actions and well or cards
3. Navigate to `/applications/:application-id/career-timeline`
4. Observe lack of space between actions and well or cards

## 📸 Screenshots

<img width="1171" alt="Screen Shot 2024-06-25 at 11 26 38" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/e03e54e0-3a11-4742-a0c1-7c64f4831717">
<img width="1079" alt="Screen Shot 2024-06-25 at 11 25 40" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/e8d01ba5-e05a-40af-9639-812dc5c7ffdf">
<img width="1212" alt="Screen Shot 2024-06-25 at 16 47 16" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/9eb4fae2-f27e-41ec-9701-7e1b1a4a45da">

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] more spacing between actions and well or cards

**Comment by brindasasi** [comment]
let's merge this fix but the root cause is the problem with Hydrogen which will be dealt in separate pr
