### ISSUE TITLE
♻️ Avoid use of entire model types in Typescript

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#10799]
## ♻️ Debt/Refactor

Migrate away from using the whole model types and prefer discrete types or fragments.

## 🕵️ Details

We currently use entire models as types (`Pool`, `Department`) to make passing data around easier. However, this causes issues when we encounter non nullable types. Our grapqhl codegen will not mark these as optional. So, when we use the entire type, it forces us to fetch that data to satisfy Typescript. 

This leads to either doing some typescript gymnastics or over fetching of data.

## 🙋‍♀️ Proposed Solution

We have two approaches we could take and likely will need to do both depending on the case:

1. Replace entire types like `pool: Pool` with more specific arguments `{ stream: PoolStream, publishingGroup: PublishingGroup }`
2. Utilize graphql fragments as the argument `poolQuery: FragmentType<typeof HelpFunctionPool_Fragment>`

I think we can follow a good rule of thumb to accomplish this. 

If it is a helper function that only accepts a couple of arguments, just separate them out and make us pass them in individually (option 1).

Then, if you start to see the number of arguments increase to something that seems to be hard to manage (4+?) then we use option 2 and write a fragment for it. Also, if it is a component we should drastically reduce the threshold in which we decide to use a fragment (2+?)

## ✅ Acceptance Criteria

- [ ] Entire model types are no longer used with few exceptions
- [ ] Exceptions are documented to explain why the entire model type was required
- [ ] Document the rule of thumb for how to use fragments

**Comment by vd1992** [comment]
Sometimes all you need to do is import the fragment and use it to define type. 
Example for reference

https://github.com/GCTC-NTGC/gc-digital-talent/pull/10629/commits/0865ff9e2a9e4f04e1d6953468aea8956660be16

**Comment by vd1992** [comment]
### Pull requests

- https://github.com/GCTC-NTGC/gc-digital-talent/pull/10994
