### ISSUE TITLE
✨ Update the main site navigation

### ISSUE THREAD

**Issue by JoshBeveridge** [GCTC-NTGC/gc-digital-talent#10793]
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/859aed48-a49e-4572-a39c-f5361e3d4d2b)

### ✨ Summary

[Visit the Figma file](https://www.figma.com/design/guHeIIh8dqFVCks310Wv0G/Component-library?node-id=1475-27575) • Contact @substrae with design questions

As a part of the UI consolidation work and the incoming user dashboards, we're giving the navigation some much-needed love. This includes the addition of new tools, sub-menus, and an updated mobile menu experience.

Small design update to add resources, etc: https://www.figma.com/design/guHeIIh8dqFVCks310Wv0G/Component-library?node-id=1475-27575&node-type=canvas&t=hOq22rD9Z1Yp7qt0-0 
---

### 🕵️ Details

> [!TIP]
> Layout guidance for all states and variants are included within their respective `details` element. If you have any questions about how to orient or space a particular element, or there is something missing, give @substrae a shout.

#### Variants
The links included in the nav and sub-menus depend on the "active role" (see #11034). 
If the user's role's map to multiple navigation roles, then an extra sub-menu appears on the left of the nav menu, with a label that reflects the current active role, and links to dashboards of all the roles the user has access to. (Note that, thanks to #11034, simply linking to a dashboard should update the active role on the new page.)

The links which appear in the Account submenu also depend on active role.

#### Colors 

<details>
  <summary>Desktop colors</summary>
  <p>The desktop version of the menu should trigger on the <code>l-tablet</code> media query. Because the header remains dark in light mode, the styles for the desktop layout are persistent across both modes. The only exception to this rule is the fly-out for sub-menus, which is detailed below.</p>
  <ul>
    <li>Background: <code>base:all(black.9)</code></li>
    <li>Links: <code>base:all(white)</code></li>
    <li>Active/hovered item: <code>base:all(secondary.lighter)</code></li>
    <li>Divider: <code>base:all(white.5)</code></li>
    <li>Sub-menu background: <code>base(foreground)</code></li>
    <li>Sub-menu border: <code>base:all(1px solid background.darker)</code></li>
    <li>Sub-menu link: <code>base(black)</code></li>
    <li>Sub-menu active/hovered item: <code>base(secondary.darker) base:dark(secondary.lightest)</code></li>
    <li>Notification bell: <code>base:all(white)</code></li>
    <li>Notification dot: <code>base(tertiary)</code></li>
  </ul>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/6074f61d-9b44-463a-b9b4-9a7c7e4cc3ca" />
</details> 

<details>
  <summary>Mobile colors</summary>
  <p>The mobile version of the menu is fully color responsive to the user's chosen mode, with the colors specified as follows:</p>
  <ul>
    <li>Trigger backgrounds: <code>base:all(gray.darkest)</code></li>
    <li>Trigger labels/icons: <code>base:all(white)</code></li>
    <li>Trigger notification dot: <code>base(tertiary)</code></li>
    - 
    <li>Page overlay: <code>base:all(black.light.85)</code></li>
    -
    <li>Background: <code>base(foreground)</code></li>
    <li>Links: <code>base(black)</code></li>
    <li>Active/hovered item: <code>base(secondary.darker) base:dark(secondary.lightest)</code></li>
    <li>Divider: <code>base:all(background.darker)</code></li>
  </ul>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/04f8d524-1fcb-47d5-9a2e-2910c27ba23a" />
</details>

<details>
  <summary>Hover states</summary>
  <p>Hover states should use the <code>secondary.lighter</code> color and persist across light and dark modes.</p>
  <p>The only exception to that rule is within sub-menus where the background does in fact change, meaning the light mode hover should use <code>secondary.darker</code> and swap to <code>secondary.lightest</code> in dark mode.</p>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/1556fd87-83c5-4103-b18f-6d2c829f2fb9" />
</details> 

<details>
  <summary>Focus states</summary>
  <p>Focus states for the desktop menu should also translate to the mobile menu, and remain the same in both light and dark modes. <strong>Note</strong> that the focus states for the first and final element in the row exceed the space available in the container; this is intentional to ensure visual alignment while not focused and enough padding for each element while focused. Reach out if you have any questions.</p>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/7b1c552a-5556-47c7-b0c3-f2d33fe75c1a" />
</details> 

#### Desktop experience

<details>
  <summary>Logged out</summary>
  <p>The following options are presented when the user is completely logged out of the platform:</p>
  <ul>
    <li><em>Home</em> - Takes the user to the root homepage</li>
    <li><em>Find a job</em> - Takes the user to the browse jobs page</li>
    -
    <li><em>Sign in</em> - Takes the user to the sign in info page</li>
    <li><em>SIgn up</em> - Takes the user to the registration info page</li>
  </ul>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/57eaa24b-a648-4939-8593-f3cbd066a89b" />
</details> 

<details>
  <summary>Logged in, applicant, no other roles</summary>
  <p>The following options are presented when acting as an <code>applicant</code> who has no access to other roles:</p>
  <ul>
    <li><em>Home</em> - Takes the user to the root homepage</li>
    <li><em>Dashboard</em> - Takes the user to the applicant-role version of the dashboard</li>
    <li><em>Find a job</em> - Takes the user to the browse jobs page</li>
    -
    <li><em>Your account</em> - Triggers the applicant-variant of the account sub-menu</li>
    -
    <li><em>Notification bell</em> - Opens the notifications pane</li>
  </ul>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/9df9c990-26f8-4ce7-8aa7-a2ccb58a7984" />
</details>

<details>
  <summary>Logged in, applicant, other roles</summary>
  <p>The following options are presented when acting as an <code>applicant</code> who can also switch to one or more roles:</p>
  <ul>
    <li><em>Applicant</em> - Triggers the role sub-menu</li>
    <li><em>Home</em> - Takes the user to the root homepage</li>
    <li><em>Dashboard</em> - Takes the user to the applicant-role version of the dashboard</li>
    <li><em>Find a job</em> - Takes the user to the browse jobs page</li>
    <li><em>Your account</em> - Triggers the applicant-variant of the account sub-menu</li>
    <li><em>Notification bell</em> - Opens the notifications pane</li>
  </ul>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/3bc41a73-6ed2-46d1-a603-7419c0b4d2dc" />
</details> 

<details>
  <summary>Logged in, manager</summary>
  <p>The following options are presented when acting as a <code>manager</code>:</p>
  <ul>
    <li><em>Manager</em> - Triggers the role sub-menu</li>
    -
    <li><em>Home</em> - Takes the user to the root homepage</li>
    <li><em>Dashboard</em> - Takes the user to the manager-role version of the dashboard</li>
    <li><em>Find talent</em> - Takes the user to the talent search</li>
    -
    <li><em>Your account</em> - Triggers the manager-variant of the account sub-menu</li>
    -
    <li><em>Notification bell</em> - Opens the notifications pane</li>
  </ul>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/dd9d5757-60b2-448f-81b7-60c16bd1425a" />
</details>

<details>
  <summary>Logged in, community</summary>
  <p>The following options are presented when acting as a <code>community</code>:</p>
  <ul>
    <li><em>Community</em> - Triggers the role sub-menu</li>
    -
    <li><em>Home</em> - Takes the user to the root homepage</li>
    <li><em>Dashboard</em> - Takes the user to the community-role version of the dashboard</li>
    <li><em>Recruitment</em> - Takes the user to the community processes table</li>
    <li><em>Find talent</em> - Takes the user to the community-specific search table of all qualified users</li>
    -
    <li><em>Your account</em> - Triggers the community-variant of the account sub-menu</li>
    -
    <li><em>Notification bell</em> - Opens the notifications pane</li>
  </ul>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/a1eb9253-0e24-46fa-9ebe-4df937406a95" />
</details>  

<details>
  <summary>Logged in, system admin</summary>
  <p>The following options are presented when acting as a <code>system admin</code>:</p>
  <ul>
    <li><em>Admin</em> - Triggers the role sub-menu</li>
    -
    <li><em>Home</em> - Takes the user to the root homepage</li>
    <li><em>Dashboard</em> - Takes the user to the admin-role version of the dashboard</li>
    <li><em>View users</em> - Takes the user to the platform-wide users table</li>
    <li><em>Manage processes</em> - Takes the user to a table of all processes on the platform</li>
    <li><em>System settings</em> - Triggers the system settings sub-menu</li>
    -
    <li><em>Your account</em> - Triggers the community-variant of the account sub-menu</li>
    -
    <li><em>Notification bell</em> - Opens the notifications pane</li>
  </ul>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/6b70e48d-acbb-42df-ae94-53ca33010efa" />
</details>  

<details>
  <summary>Desktop, when scrolling</summary>
  <p>This is new behaviour, but now that the platform has so many tools and views, I'm proposing that we enable <code>position: sticky</code> behaviour on the <strong>nav element only</strong> so that users can maintain their sense of location and context. This will need to be paired with <code>top: 0px</code> so that the nav sticks to the very top of the viewport when the user scrolls past its initial location.</p>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/57373309-d975-44a4-8c34-447ef67597d5" />
</details>

#### Mobile experience

> [!CAUTION]
> The mobile menu is going to require some thorough manual accessibility testing to ensure that it functions as expected. In practice, it should act in a similar way to a `<dialog>` element, where, when open, the user's focus is looped within the menu and focus can't be transferred to the main page's elements unless the menu is closed (using the trigger or the `ESC` key). 

<details>
  <summary>Closed, logged out</summary>
  <p>By default, the menu is closed and the trigger to open it is pinned to the bottom-right of the screen; this is a departure from our current approach which is to just stack all the menu links at the top of the page, which takes up an enormous amount of vertical space, preventing the page's content from being obvious at first glance.</p>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/e3de861d-3d45-4ad7-8640-98e09443bf7f" />
</details>

<details>
  <summary>Open, logged out</summary>
  <p>When the menu is opened, an overlay is applied to the background, the ability to scroll the main page becomes locked, and the trigger's label and icon should change to <code>x Close</code>. </p>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/7cf416a0-acd2-41f6-9f85-178cf1d1d90e" />
</details>

<details>
  <summary>Closed, logged in</summary>
  <p>When logged in, the menu trigger is accompanied by a notification button. This button should trigger the notification pane, as described in the "Notifications, open" requirements in this list.</p>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/879a42f4-7c89-492d-9e49-aecd04e70882" />
</details>

<details>
  <summary>Notifications, open</summary>
  <p>When the notifications trigger is activated, the icon should swap to an <code>x</code> icon. The notifications pane should then open in the same fashion as the menu.</p>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/60040cda-5802-4a41-9100-ac8a2d50d250" />
  <p>Should the notification pane exceed the available vertical space, it should begin at the top of the viewport and fill the screen below the trigger buttons. The pane should be scrollable and end at the positioning outlined below. This behaviour is the same for when the menu pane itself exceeds the available height, as outlined below in the "Open, larger than screen" requirements below.</p>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/ea744371-e34c-41a9-b2af-6ad5ee479747" />
</details>

<details>
  <summary>Open, logged in, applicant, no other roles</summary>
  <p>When logged in, the "Sign up" and "Sign in" buttons are replaced with a <code>details</code> version of the appropriate account menu. The collapsed and expanded versions are pictured below. Please refer to the previous requirements for spacing.</p>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/6a3d99bd-b97f-47a0-abdf-a154cde0b16c" />
</details>

<details>
  <summary>Open, logged in, applicant, other roles</summary>
  <p>When the user has more than one role available to them, the role switcher sub-menu (as a <code>details</code> element) is added above the main menu, below the theme and language toggles. This image shows the collapsed and expanded states for that sub-menu, as well as its placement.</p>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/0bfe13d9-18ca-4dbb-ba0e-e78ba63d88d4" />
</details>

<details>
  <summary>Open, logged in, manager</summary>
  <p>When switching roles, the menu changes as described in the desktop requirements, but with the mobile layout. The image below shows the manager version, with the account sub-menu collapsed/expanded.</p>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/5abd5b24-a69d-4dca-b253-ff0f7f759f1d" />
</details>

<details>
  <summary>Open, logged in, community</summary>
  <p>When switching roles, the menu changes as described in the desktop requirements, but with the mobile layout. The image below shows the community version, with the account sub-menu collapsed/expanded.</p>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/0e7790e2-2134-46f9-96f7-bf7f1beebdc8" />
</details>

<details>
  <summary>Open, logged in, system admin</summary>
  <p>When switching roles, the menu changes as described in the desktop requirements, but with the mobile layout. The image below shows the admin version, with the account sub-menu collapsed/expanded, as well as a version with the system settings sub-menu expanded.</p>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/f5da2056-2da8-4042-9ada-b7008a1f10be" />
</details>

<details>
  <summary>Open, larger than screen</summary>
  <p>Should the menu be opened on a device that doesn't have enough vertical room to contain the menu, it should open in such a way that the top of the menu starts at the top of the screen, and the menu runs <em>behind</em> the triggers. The menu should then be able to be scrolled vertically to the point where the bottom of the card reaches its natural position as shown below.</p>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/a7a9bca3-fa81-4bfd-bf41-49b9722fb54c" />
</details>

#### Sub-components

> [!NOTE]
> The sub-menus described below are specific the desktop layout of the menu - the mobile version should handle sub-menus as simple `<details>` elements.

<details>
  <summary>Role sub-menu</summary>
  <p>This sub-menu only appears for users who have access to more than the applicant role on their account. Choosing an option from the role menu should take the user to that respective role's dashboard assuming they have the correct permissions.</p>
  <p>The role sub-menu is unique in that it's label changes to match the current selection. This is helpful because it allows the user to see, regardless of their location on the site, which role they're currently acting as.</p>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/8fa9ac18-e205-4c43-8c55-c275458d4125" />
</details> 

<details>
  <summary>System settings sub-menu</summary>
  <p>This sub-menu is specific to the system admin role and allows for easy navigation to the CRUD interfaces for individual data models. Each item in the sub-menu should take the user to that item's respective index table, from where they can manage that particular data model.</p>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/ea2ebdff-6723-49fd-ac13-4779b7fedf0f" />
</details> 

<details>
  <summary>Account sub-menu, applicant</summary>
  <p>The following options are presented when acting as an <code>applicant</code>:</p>
  <ul>
    <li><em>Applicant profile</em> - Takes the user to the screen that allows them to edit their applicant-specific profile information</li>
    <li><em>Career timeline</em> - Takes the user to their career timeline</li>
    <li><em>Skill library</em> - Takes the user to their skill library page</li>
    <li><em>Account settings</em> - Takes the user to their universal account settings</li>
    <li><em>Sign out</em> - Logs the user out of their current session</li>
  </ul>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/5818bae5-3ed8-4ce3-ab44-77d161b4ba77" />
</details> 

<details>
  <summary>Account sub-menu, manager</summary>
  <p>The following options are presented when acting as a <code>manager</code>:</p>
  <ul>
    <li><em>Manager profile</em> - Takes the user to the screen that allows them to edit their manager-specific profile information (note that this doesn't exist yet)</li>
    <li><em>Account settings</em> - Takes the user to their universal account settings</li>
    <li><em>Sign out</em> - Logs the user out of their current session</li>
  </ul>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/5a8b395c-3d79-489d-a65b-fe443df8363d" />
</details> 

<details>
  <summary>Account sub-menu. community</summary>
  <p>The following options are presented when acting as a <code>community</code>:</p>
  <ul>
    <li><em>Account settings</em> - Takes the user to their universal account settings</li>
    <li><em>Sign out</em> - Logs the user out of their current session</li>
  </ul>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/ead56771-fab4-4638-b0e8-c482f2aabef3" />
</details> 

<details>
  <summary>Account sub-menu, system admin</summary>
  <p>The following options are presented when acting as a <code>system admin</code>:</p>
  <ul>
    <li><em>Account settings</em> - Takes the user to their universal account settings</li>
    <li><em>Sign out</em> - Logs the user out of their current session</li>
  </ul>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/e002a3d4-73ea-4e95-aaa6-ba782020fe1a" />
</details> 

---

## Acceptance Criteria

```[tasklist]
### ✅ Requirements
- [x] Update initial colors and spacing
- [x] Add the sticky functionality
- [x] Create and implement the role toggle sub-menu
- [x] role submenu only appears if user is logged in and has roles mapping to multiple nav roles
- [x] Apply the new menu to existing community pages
- [x] Update the guest menu items
- [x] Create and implement the new account sub-menu
- [x] Update the applicant menu items
- [x] Create and add the manager version and menu items with temporary links
- [x] Create and add the community version and menu items
- [x] Create and add the admin version and menu items
- [x] Create and implement the admin-specific system settings sub-menu
- [x] Overhaul the mobile experience
- [x] Perform a manual accessibility check to ensure navigating the menu and sub-menus is coherent and keyboard-friendly
- [x] Apply the new menu to existing guest pages
- [x] Apply the new menu to existing applicant pages
- [x] role submenu contains links to dashboards of nav roles user has access to
- [x] Apply the new menu to existing admin pages
- [x] Remove the Admin Layout story
- [ ] Add rousource submenu and system system settings submenu (admin)
```

## 🛑 Blockers
```[tasklist]
### Blocked by
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/11031
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/11034
```

**Comment by tristan-orourke** [comment]
For the nav items available to Community roles:
- For the labels on the nav links, I suggest using the same wording our users are used to on the current admin site, to make the transition easier. That would mean using "Processes" instead of "Recruitment", and "Candidate search" instead of "Find talent". 
- "Find talent" would be especially confusing, since that also appears on the Manager menu (and the current site) but leads somewhere different.
- I'm guessing this was originally designed for a post-self-referral world, but for now Community roles also need a nav link to view "Talent requests"
- They also need a way to get to the Communities page, analagous to the Teams page which is live on the current site. This is where Community Admins will be able to assign other users to their community.

**Comment by tristan-orourke** [comment]
For the nav items available to Admin roles:
- as of latest conversations with Lauren, the Platform Admin is intended to be able to act in a kind of oversight role. That means they need to be able to view pretty much everything happening on the platform, even if they can't edit stuff. For now, I think that just means they also need any links we decide to add to Community (like Talent requests).
- Skill Families and Announcements should be added to System settings

**Comment by tristan-orourke** [comment]
Lastly... there's a new quasi-role I'm not sure how to handle. I mean, technically its a Role like any other - the Process Operator role. But from a user's perspective, its more like a user has been granted full view+edit permissions on a single Process. If a user has Applicant + Process Operator roles, what nav should they see? How should they get to their processes?

**Comment by substrae** [comment]
Okay, finally getting around to your comments:
* I changed `Recruitment` back to `Processes`
* I changed `Find talent` to `Candidates` (I omitted `... search` as I feel it's not necessary)
* I've temporarily added `Requests` to the community menu
* For managing the community itself, I'm actually going to add this to the dashboard rather than the menu
* I've temporarily added `Requests` to the System admin menu
* I've added `Skill families` to the `System settings` sub-menu
* I've added `Announcements` to the `System settings` sub-menu
* Based on our previous discussions, our initial implementation of sharing is going to enable a restricted version of the role's nav and dashboard that provides access to the data and tools specific to the shared permission; this allows us to leverage the UI we're building rather than building anything dedicated for sharing, which we can look at doing later.

A couple other small changes:
* I've standardized a bit of the language down to single words for consistency
* `System settings` is now alphabetical

Still going through and updating the 24 billion screenshots though 😂
