### ISSUE TITLE
🐛 Notification pane background broken

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#10796]
## 🐛 Bug

The background "greyed out" overlay doesn't appear to be working.  It doesn't appear until the pane is closed and then it prevents any interaction with the page.

## 📋 Steps to Reproduce

1. Open the notification pane.
2. Close the notification pane.
3. Attempt to use the site.

## 📸 Screenshot

https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/3f7de3a7-56f0-4569-ba3a-9d249c1d3858

## ✅ Acceptance Criteria

- [ ] Background overlay appears when you open the pane.
- [ ] Background overlay disappears when you close the pane.
- [ ] You can interact with the site after closing the pane.
- [ ] Playwright/Jest test to confirm this is working

**Comment by vd1992** [comment]
I think this has to do with the children of `<AnimatePresence />` in `NotificationDialog.tsx`
I wonder if it has to do with Vite and specifically Framer Motion stuff, there was other animation issues in the PR

See https://github.com/GCTC-NTGC/gc-digital-talent/pull/10611#issuecomment-2173284258
I don't know if this commit had a role but could offer clues  https://github.com/GCTC-NTGC/gc-digital-talent/pull/10611/commits/5be2315a9766bb903cefa807665e359f6ff76b83

**Comment by vd1992** [comment]
`isOpen` switching from true -> false no longer disappears the nested elements and I can't figure out why it stopped working
The easiest fix is to just break the animation but don't want to resort to that

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/443bf1ec-e06f-4c5b-b794-452c385d71a6)

**Comment by petertgiles** [comment]
Seems like a dependency bump of Framer killed it.  I did a manual bisect search and this PR broke the feature:

**Comment by brindasasi** [comment]
does reverting that pr get this up? If so I would vote to do that.

**Comment by petertgiles** [comment]
> does reverting that pr get this up? If so I would vote to do that.

I just pushed up a PR that rolls back that dependency.
