### ISSUE TITLE
Router - Routing inside of dashboard

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#1081]
Expanding on issue #522 .

Currently the router exists within the dashboard so all routed content appears within the header, footer, and sidemenu.  This includes error messages like a 404-not found.  Is this a problem?  Should the router be lifted up hierarchy?
![image](https://user-images.githubusercontent.com/8978655/140991661-22a86c80-4efb-4059-8c56-3f02fa4b80fe.png)

**Comment by mnigh** [comment]
Navigation menu should still be visible on 404.
