### ISSUE TITLE
🐛 Positioning and order are off for skill table filters/buttons

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#10828]
## 🐛 Bug

Looks like the ordering and layout for the skill table filters and "add" button are a bit wonky.

## 🦋 Expected Behaviour

Ideally they should match the design (see screenshot in _Proposed solution_ for details.

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Windows 11
- **Browser**: Firefox 127

## 📋 Steps to Reproduce

1. Head on over to the skill library page and check out the table on wider-ish screens

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/2b7a31e0-a2df-44f3-8a48-5c5dee52818b)

## 🙋‍♀️ Proposed Solution

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/8cc0cdce-76dd-4e98-9b12-8c404876faec)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] The filters and "add" button are oriented and ordered properly on mobile
- [ ] The filters and "add" button are oriented and ordered properly on desktop

**Comment by brindasasi** [comment]
investigate the existence of this bug in other tables that has search box on the top and fix there as well.
