### ISSUE TITLE
✨ Compute Final Decision on backend and make it sortable

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#10846]
## ✨ Feature

The "Final decision" field, as we're currently calling it, is a property of PoolCandidates which combines the `assessmentStatus` added in #10642 with PoolCandidateStatus. We currently compute this on the frontend for display purposes, but we want to move it to the backend so that candidates can be sorted by this value before pagination.

## 🕵️ Details

The logic for "final decision" goes as follows. (This is based on `getCandidateStatusChip` in `apps/web/src/uitls/poolCandidate.ts`)
```


const TO_ASSESS_STATUSES = [
  PoolCandidateStatus.NewApplication,
  PoolCandidateStatus.ApplicationReview,
  PoolCandidateStatus.ScreenedIn,
  PoolCandidateStatus.UnderAssessment,
];

IF candidate.status is in TO_ASSESS_STATUSES:
  compute FinalDecision based based on candidate.assessmentStatus:
    IF candidate.assessmentStatus == null: // This should only be the case for pre-RoD candidates
      FinalDecision  is "To Assess" // "To Assess: Step 0" or "To Assess: Step 1" would also be fine
    IF candidate.assessmentStatus.overallAssessmentStatus == DISQUALIFIED:
      FinalDecision  is "Disqualified: Pending decision"
    IF candidate.assessmentStatus.overallAssessmentStatus == QUALIFIED:
      FinalDecision is "Qualified: Pending decision"
    IF candidate.assessmentStatus.overallAssessmentStatus == TO_ASSESS:
      FinalDecision is `To Assess: Step {candidate.assessmentStatus.currentStep}`

ELSE IF candidate.status is NOT in TO_ASSESS_STATUSES:
  FinalDecision is mapped from candidate.status:
    [ScreenedOutApplication, ScreenedOutAssessment] => "Disqualified"
    [QualifiedAvailable] => "Qualified"
    [PlacedCasual, PlacedTerm, PlacedIndeterminate, PlacedTentative] => "Qualified: Placed"
    [ScreenedOutNotInterested, ScreenedOutNotResponsive] => "Removed: To Assess"
    [QualifiedUnavailable, QualifiedWithdrew] => "Removed: Qualified"
    [Removed] => "Removed"
    [Expired] => "Expired: Qualified"
```

Another key feature is that when fetching paginated candidates, they can be ordered by FinalDecision. The default ordering should be like this:
```
Qualified
Qualified: Pending decision
To assess step 1
To assess step 2
....
Qualified: Placed
Disqualified: Pending decision
Disqualified
Removed: Qualified
Removed: To Assess
Removed
Expired: Qualified
```

## 🎨 Design File

Include a link to the design file (if it exists).

### 🧑‍🎨 Designer

@Jerryescandon 

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/afa104cb-aeaf-43dc-bfaa-fefc07a8a00c)

## 🙋‍♀️ Proposed Implementation

I'm not sure. It could be a database column which sql is set up to automatically recompute (like priorityWeight), it could be generated on the fly by the sql query (like our skills count - and see also [this comment](https://github.com/GCTC-NTGC/gc-digital-talent/issues/8966#issuecomment-2158872097)), or it could be computed by laravel and stored in and event listener, like with #10642.

If any database columns are added which are computed automatically, prefix the name with `computed_`.

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] The PoolCandidates table can order candidate candidates by Final Decision, and they are sorted according to what's specified in Details.
- [ ] The final decision status is available from the graphql on the pool candidate object
- [ ] PHPunit tests
- [ ] Any frontend changes are out of scope

**Comment by brindasasi** [comment]
@tristan-orourke/ @gobyrne / @Jerryescandon   could you help filling this in?

**Comment by tristan-orourke** [comment]
@Jerryescandon could you double check the status ordering?

**Comment by Jerryescandon** [comment]
> @Jerryescandon could you double check the status ordering?

I feel like maybe we should keep all the "Qualified" statuses together otherwise it will be confusing, how about
Qualified
Qualified: Pending decision
Qualified: Placed
To assess step 1
To assess step 2
....
Disqualified: Pending decision
Disqualified
Removed: Qualified
Removed: To Assess
Removed
Expired: Qualified
