### ISSUE TITLE
🐛 Cannot filter for archived pools

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#10865]
## 🐛 Bug

You can filter for archived pools in the pools table but this returns nothing even if you should see something

## 📋 Steps to Reproduce

1. Archive a pool
2. Attempt to find it in the pools table using the filters

## 📸 Screenshot

Archived

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/a397880d-a155-493c-b245-690b074fdbc4)

Filtering

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/5ef896fc-eb5b-40f3-bbc6-02e2baf60ee7)

Nothing

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/36c928fb-3d12-4598-b4f8-83add86e6e88)

## 🙋‍♀️ Proposed Solution

Scope filters out archived pools always, should only do so when not searching for archived pools

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/1953597f-0b00-481f-abb3-9f0dd40bb00a)

## ✅ Acceptance Criteria

- [ ] When filtering for archived pools, you see archived pools
- [ ] By default the pool table should still load the unarchived pools
- [ ] All the community roles can see the unarchived pools

**Comment by esizer** [comment]
I can't seem to find a permission resource for archived pools. Would it make sense to create a resource for `archivedPool` similar to `publisedPool` and `draftPool` so we can just move this to the `authorizedToView` scope?

```php
public static function scopeAuthorizedToView($query)
{

  // ...

  if(!$user->isAbleTo('view-any-archivedPool') {
    $query->where(function ($query) {
      $query->whereNull('archived_at')
          ->orWhere('archived_at', '>', Carbon::now());
    });
  }
  
  // ...

}
```

**Comment by vd1992** [comment]
Good point, needed if we want to restrict viewership. Well, I guess it is doable without but not as smoothly. 

@tristan-orourke 
Should we have an `archivedPool` resource for ease of view/interact permission purposes?

**Comment by petertgiles** [comment]
The problem isn't that archive pools have a different permission level, right?  It's just that usually you don't want to see them.  Should we just take that scope off the query and ensure that anywhere the query is used is adding a filter by default?

**Comment by esizer** [comment]
> The problem isn't that archive pools have a different permission level, right? It's just that usually you don't want to see them. Should we just take that scope off the query and ensure that anywhere the query is used is ~adding a filter by default~? Tricky, we don't have any negation filters...

I think I was asking about the permission because there are some users who _cannot_ view them (applicants), so showing them by default and only hiding them with a filter seems like it could potentially expose them unintentionally if the filter happens to be removed.

**Comment by brindasasi** [comment]
Archiving pool doesn't affect permissions. Anyone can see archived pools including applicants.
