### ISSUE TITLE
🐛 Error when sending a notification to a user with no preferred lang

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#10862]
## 🐛 Bug

Our [User->PreferredLocale function](https://github.com/GCTC-NTGC/gc-digital-talent/blob/2c0c27f2e1ad20d3b4ed68ff26c548c9a464dba2/api/app/Models/User.php#L198) is hinted to only return strings.  However, it can return nulls and will error out when it does.

## 📋 Steps to Reproduce

1. Manually null out the preferred_lang field for a user. 
2. Attempt to send a notification to them.

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/aa129010-de92-4901-8eaa-cd4ff87e17db)

## 🙋‍♀️ Proposed Solution

The HasLocalePreference trait is actually hinted to return string|null.  We could align with that and then put in handlers for nulls whereever it is used.

Option 2 is to just fallback to one of the languages and continue to promise not to return nulls.

## ✅ Acceptance Criteria

- [ ] No errors when trying to send a notification to a user with no preferred lang.

**Comment by brindasasi** [comment]
Option 1 is preferred. English is fall back.
