### ISSUE TITLE
🐛 Profile print from candidate page missing skills library

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#10866]
## 🐛 Bug

Using "Print full profile" when viewing a candidate is missing skills library content. Probably just need to fetch the fields
Printing from the user profile page confirms the library does exist

## 📋 Steps to Reproduce

1. View candidate page
2. Go to "Print full profile"
3. Scroll to skills library

## 📸 Screenshot

"Print full profile" Candidate page

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/03252378-96ac-42e7-af97-ca5d5c1d870e)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/b32ad767-8876-4065-967b-2d13448d0efc)

And then comparing to the user's page

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/4d671d09-6ef1-4e99-8b7d-63391668347f)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/26ec3e28-3333-4827-859e-efcaab52493e)

## 🙋‍♀️ Proposed Solution

As seen above, the skill library content does exist, likely just isn't fetched on the view candidate page

## ✅ Acceptance Criteria

- [ ] Library fetched for printing on view candidate page

**Comment by esizer** [comment]
I think this is because this button uses the snapshot which does not store top/to improve skills 😬 Was this just an oversight or are we not meant to store those in the snapshot?

**Comment by vd1992** [comment]
> I think this is because this button uses the snapshot which does not store top/to improve skills 😬 Was this just an oversight or are we not meant to store those in the snapshot?

I don't think the skill library is relevant to the application process, so snapshotting it would serve no purpose. Rather you'd want to view the latest library on the user profile page.
Instead, we remove the skill library content from this print view?

**Comment by brindasasi** [comment]
oh we don't have it in snapshot. Then we shouldn't be rendering it. Has it been added recently?

**Comment by esizer** [comment]
> oh we don't have it in snapshot. Then we shouldn't be rendering it. Has it been added recently?

Not super recently. I was wondering if it was intentional to leave it out of the snapshot or not :thinking: That would affect how we solve this problem. Either:

1. Add them to the snapshot
2. Do not render them when requesting the snapshot

**Comment by vd1992** [comment]
I don't see a reason to store the skill library in the snapshot, so I would lean towards the second option

**Comment by brindasasi** [comment]
@GCTC-NTGC/designers could help deciding on the above 2 options?

**Comment by Jerryescandon** [comment]
IDK if this helps. BUT

"Print application" should be getting the info from snapshot (single point in time), and there should be no Skills showcase in the application.

"Print profile" should be getting the data directly from the profile (most up-to-date info) and should include the skills showcase.

We shouldn't be storing skill showcase info in the snapshot because its not needed for an application and when printing the profile, we should get the most up to date info anyway, so we shouldnt pull from the snapshot in that case either.
