### ISSUE TITLE
♻️ Remove AssessmentResultJustification::SKILL_ACCEPTED

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#10898]
## ♻️ Debt/Refactor

We have a justification reason for "skill accepted" but in our UI it is not possible to set a justification when accepting a skill.

## 🕵️ Details

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/a97f1332-589d-4e21-988d-84d55982eba1)

## ✅ Acceptance Criteria

- [ ] Remove enum case from graphql schema
- [ ] Remove enum case from usage in the code (shouldn't be any)
- [ ] Confirm it does not exist in any existing db rows in prod (shouldn't be any)

**Comment by petertgiles** [comment]
@Jerryescandon Could I please get a :+1: :-1:  on this one?

**Comment by Jerryescandon** [comment]
Yeah I think this is a leftover from when we merged the notes and justification fields.

**Comment by brindasasi** [comment]
@petertgiles to check on the prod for existing usage of this field in prod

**Comment by petertgiles** [comment]
I can confirm this doesn't exist in prod.
```sql
select  jsonb_array_elements(justifications) justification, count(*)
from assessment_results ar
group by jsonb_array_elements(justifications)
order by jsonb_array_elements(justifications)
```
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/0802233e-b7e9-4d9a-b65c-ddf13edee5cc)
