### ISSUE TITLE
♻️ `EducationRequirementOption` name has superfluous option

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#10892]
## ♻️ Refactor

`EducationRequirementOption` name has superfluous option in its name.

## 🙋‍♀️ Proposed Solution

Rename enum `EducationRequirementOption` to `EducationRequirement`.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] enum names match what they are without superfluous information

## 🛑 Blockers

Issues which must be completed before this one.

```[tasklist]
### Blocked By
- [ ] #10634
```

**Comment by tristan-orourke** [comment]
Actually, I just looked at our enums, and I think it would be more confusing if we changed this to `EducationRequirement`! It may be the only one which ends with "Option", but we have others that end with "Type" for the same reason.

**Comment by mnigh** [comment]
> Actually, I just looked at our enums, and I think it would be more confusing if we changed this to `EducationRequirement`! It may be the only one which ends with "Option", but we have others that end with "Type" for the same reason.

@tristan-orourke Not sure why the blocked label was added. Would you prefer that I expand the scope of this issue to rename the others that end with "Type" then or close this issue?

**Comment by mnigh** [comment]
@tristan-orourke bump!

**Comment by tristan-orourke** [comment]
I think I blocked it because I didn't anyone to pick this up without more discussion, but I'll go ahead and make a decision. I prefer the name as is, so I'm closing the ticket.
