### ISSUE TITLE
🐛 System Notification spikes performance usage

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#10896]
## 🐛 Bug

We just sent our first system notification and it impacted the site's performance.  We should probably slow this down a bit.

## 📋 Steps to Reproduce

1. Send a system notification to a large number of users

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/cfe951c3-0bdd-4f80-8e5b-10b1825e2c24)

## 🙋‍♀️ Proposed Solution

- Slow down firing the notifications in the foreach loop in the Artisan command?
- Use [delayed dispatching](https://laravel.com/docs/10.x/queues#delayed-dispatching) for emails?
- Add a [sleep time](https://laravel.com/docs/10.x/queues#worker-sleep-duration) between jobs for queue workers?
- Use queued [events](https://laravel.com/docs/10.x/events) to generate the notifications (for pool publish)

## ✅ Acceptance Criteria

- [ ] System notification resource usage is spread out

**Comment by brindasasi** [comment]
I was thinking about this on Friday. Here are my thoughts. 

1. We shouldn't be sending any notification immediately after the event. Atleast for a while until we know our system can handle.
2. All notifications can wait until the EOlike the pool closing date warning emails.
3. Queue the notifications and process it evenly.
4. How about Azure virtual functions to process the notifications? ..that will cost money but guaranteed for scalability.

**Comment by petertgiles** [comment]
Good ideas!

> * We shouldn't be sending any notification immediately after the event. Atleast for a while until we know our system can handle.

Technically, the emails aren't sent immediately since they are queued.  However, I think our queue workers are running too fast.

> * All notifications can wait until the EOlike the pool closing date warning emails.

I agree that none of our notifications are too urgent.  I don't know if we need to wait until EOD but some delay would be fine for sure.

> * Queue the notifications and process it evenly.

They are queued right now, but I think the processing is too fast.

> * How about Azure virtual functions to process the notifications? ..that will cost money but guaranteed for scalability.

It's an interesting idea... It would be a big step up in complexity so I'm not eager to get there.  Right now I think we can trade job latency for system impact but I guess we'll sooner or later get to the point where our scheduled jobs are taking too long anyway.  Essentially we'd need another full copy of the Laravel app pointed at the same database with some queue workers running.  Maybe just another app service with the same artifact and deployment script?  We could even point half of the API requests at it.  Horizontal scaling for the win!

**Comment by esizer** [comment]
Something else we could investigate after doing other optimizations mentioned could be to look at the driver. We are using the database driver (default). It used to be discourage, but is fine to use now. However, it definitely is [not the optimal choice](https://stackoverflow.com/questions/31096217/laravel-queue-beanstalkd-vs-database-what-are-the-differences/31096673#31096673).

Though, that may not be easy since we would need to decide what to use and likely need to interface with IMTD about it so only after we exhaust other options and want to find more room for improvement.

**Comment by esizer** [comment]
Could be reading this wrong but, looks like we already do sleep. Should be increment this or just look at the other solutions? 🤔 

https://github.com/GCTC-NTGC/gc-digital-talent/blob/ca870d6c3618989c02ad37eb4e6ee5d654dd8e03/infrastructure/conf/laravel-worker.conf#L3

**Comment by petertgiles** [comment]
> Should be increment this or just look at the other solutions? 🤔

Oh, you're right!  I think if I were working on this I would focus on:
- adding a short sleep in the foreach loop of the system notification artisan command
- Moving the notification queuing from publishing a pool to a queued event
- Maybe sleeping in that foreach loop as well

**Comment by esizer** [comment]
> * adding a short sleep in the foreach loop of the system notification artisan command

Oh, we could also use [chunking here instead of `all`](https://laravel.com/docs/11.x/eloquent#chunking-results). maybe even in place of a sleep? It should help out a bit.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/ca870d6c3618989c02ad37eb4e6ee5d654dd8e03/api/app/Console/Commands/SendNotificationsSystem.php#L81

**Comment by petertgiles** [comment]
> Oh, we could also use [chunking here instead of `all`](https://laravel.com/docs/11.x/eloquent#chunking-results). maybe even in place of a sleep? It should help out a bit.

Oh, smart!  Yeah, I like that a lot.

**Comment by vd1992** [comment]
Do we also need to worry about execution timeouts? If performance spike is mitigated by slowing down the runtime (spread the peak) do we then have a different problem on our hands?

**Comment by petertgiles** [comment]
> Do we also need to worry about execution timeouts?

It's a valid question.  Anything that is kicked off by a browser request is running in an FPM thread and gets killed after 60 seconds.  This has happened when sending "pool published" notifications since it originates from a browser request.  :skull: Anything that originates from the Artisan CLI or a scheduler worker isn't constrained by that and (I think) has no limits.  So by moving the pool published notifications to a queued event we move the "actual notification queuing" work from an FPM worker to a scheduler worker.  This keeps the browser request snappy :+1: , avoids the timeout :+1: , but means we can't return an error the browser :-1:.  Probably not too big a deal for this notification.  We'll see it in the logs if anything goes wrong.

**Comment by petertgiles** [comment]
I went back and checked our app plan usage and it seems like this spike represented about 50% CPU usage at its peak.  
![image](https://github.com/user-attachments/assets/b213e720-84d7-4b95-8a99-4ed6bd0131e1)

Given that this happened after hours I'm guessing that the pool publishing was much more impactful to our users.  Since we have a single CPU in our app service we need to be mindful of long-running operations that never yield back to the OS.
