### ISSUE TITLE
🔤 error in the From field for notification

### ISSUE THREAD

**Issue by marc-donofrio** [GCTC-NTGC/gc-digital-talent#10895]
## 🔤 Copy

The from field for the email notifications in French is showing:

Talent numériques du GC

It should be:

Talents numériques du GC

**Comment by mnigh** [comment]
@marc-donofrio the value of this is not in our codebase but is set on GC Notify itself. I have changed value of the setting to your suggestion.

## Screenshot 
<img width="1015" alt="Screen Shot 2024-07-05 at 09 04 04" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/272d584f-99f0-4fe3-94f6-af42e9f66aa7">
