### ISSUE TITLE
🐛 AssessmentResultsTable not displaying overall step status correctly

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#10904]
## 🐛 Bug

For some candidates in production, the status icon for the Step columns of the AssessmentResultsTable are incorrect. Candidates which should be considered to have passed step 2 still show a TO ASSESS icon.

Candidates _do_ seem to be placed in the correct columns on the ScreeningAndEvaluation page (the "kanban" page).

## 🦋 Expected Behaviour

The icons in the header row of the AssessmentResultsTable should match the status for each step as the candidate appears on the ScreeningAndEvaluation page.

## 📋 Steps to Reproduce

Unclear yet exactly how to reproduce. @brindasasi or @tristan-orourke can provide the details of a pool in production for which this problem occurs, for further investigation.

## 📸 Screenshot
![Screenshot 2024-07-05 170052](https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/0528839c-1de2-48f2-9167-28c48bd6197c)

## 🙋‍♀️ Proposed Solution

I'm not sure what's wrong with the logic for determining the status icon. However, I have found that AssessmentResultsTable is not using the backend-computed assessmentStatus values which _are_ being used on the ScreeningAndEvaluation page.

The first step to solving this should be to use the backend computed assessmentStatus values.

The frontend util functions used to calculate these statuses should be delete so that they aren't accidentally used elsewhere.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] AssessmentResultsTable uses assessmentStatus.assessmentStepStatuses values computed on backend
- [ ] Status of each step in AssessmentResultTable matches step statuses on kanban page
- [ ] `apps/web/src/components/AssessmentResultsTable/utils.tsx => columnStatus()` and `apps/web/src/utils/poolCandidate.ts => getResultsDecision()` should be deleted, along with any code only used by those functions.

**Comment by brindasasi** [comment]
Essential - Technical  ->  Required for completing the step 
Essential - Behavioural -> Required for completing the step 
Asset - Technical -> NOT Required for completing the step
Asset - Behavioural -> NOT Required for completing the step
