### ISSUE TITLE
🐛 Talent request submission email has instructions to unsubscribe

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#10909]
## 🐛 Bug

The talent request submission email has instructions to unsubscribe.

## 🦋 Expected Behaviour

Talent requests happen without an account and you can't unsubscribe from them.

## 📋 Steps to Reproduce

1. Log into GCNotify
2. Check the template called _Talent request submission confirmation (EN/FR)_

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/442512fc-ae08-4baf-a814-7fa0ff00e19d)

## ✅ Acceptance Criteria

- [x] Unsubscribe message removed from EN
- [x] Unsubscribe message removed from FR

**Comment by mnigh** [comment]
@gobyrne is this something you are working on or have already addressed?
