### ISSUE TITLE
🐛 Permission denied on /tmp/api/storage/framework/views

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#10908]
## 🐛 Bug

I've seen this error a few times in prod since the last deployment:
> file_put_contents(/tmp/api/storage/framework/views/af454003dbbdf3f52f45df0598526b5b.php): Failed to open stream: Permission denied

![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/c7afc005-9256-4dd7-8f00-4ab7743cfea7)

## 🙋‍♀️ Proposed Solution

We probably need grant ownership or write permissions to the www-data user during the post-deploy script.

## ✅ Acceptance Criteria

- [ ] The www-data user can write to the /tmp/api/storage/framework/views directory in the Azure app service.
- [ ] Update the local dev scripts if needed as well.

**Comment by petertgiles** [comment]
Looks like this breaks Graphiql as well.  I needed a quick fix to get it going again:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/7de6000e-ded1-47c3-8804-78233f8c8f72)

**Comment by esizer** [comment]
Any risks to just handing over ownership of the storage dir to `www-data`? That is what the [laravel docs recommend](https://laravel.com/docs/11.x/deployment#directory-permissions).

**Comment by petertgiles** [comment]
> Any risks to just handing over ownership of the storage dir to `www-data`? That is what the [laravel docs recommend](https://laravel.com/docs/11.x/deployment#directory-permissions).

Oh, thanks for looking that up.  Yeah, that makes sense to me.
