### ISSUE TITLE
🐛 Application download missing new language fields

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#10905]
## 🐛 Bug

The application download does not reflect the new language fields that we've added. The profile download however does have them.

## 🦋 Expected Behaviour

Application download should contain all the new language fields.

## 🕵️ Details

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/cfe1c18c-6e24-44b0-9579-19fa9d344306)
(possibly the snapshot hasn't been updated)

## ✅ Acceptance Criteria

- [ ] Application download reflects the new language fields on the site
- [ ] Update the backend copy as well

**Comment by mnigh** [comment]
As discussed with @gobyrne, application snapshots that were taken before the language fields were added to the codebase will only reflect the keys that existed at the time, so this is expected behaviour.
