### ISSUE TITLE
🐛 Claim verification - one rejection cancels the other claim

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#10901]
## 🐛 Bug

I found "perfect priority" who was unverified priority and veteran. They showed as "priority" in the list. When I rejected the "priority" status they showed up as "Citizen or resident" and got unsorted. I expected them to show as "Veteran" since they still had unverified veteran status.

## ✅ Acceptance Criteria

- [ ] If a user has two claims and one gets rejected then the other claim should still be honoured
- [ ] If a user has two claims and both get rejected then neither claim should be honoured
- [ ] Test suite for this feature, probably phpunit now that it's on the backend

## 🛑 Blockers

```[tasklist]
### Blocked By
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/pull/10701
```

**Comment by vd1992** [comment]
It seems to be a frontend not backend issue so it'd be Jest instead?

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/c6bedf68-5039-4734-8850-164a195947f6)

**Comment by petertgiles** [comment]
> It seems to be a frontend not backend issue so it'd be Jest instead?
> 
> ![image](https://private-user-images.githubusercontent.com/40485260/346197968-c6bedf68-5039-4734-8850-164a195947f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMDI5MjYsIm5iZiI6MTcyMDIwMjYyNiwicGF0aCI6Ii80MDQ4NTI2MC8zNDYxOTc5NjgtYzZiZWRmNjgtNTAzOS00NzM0LTg4NTAtMTY0YTE5NTk0N2Y2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDE4MDM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhYzdkZmJmMzMzYzhlNGU5YTY2MzEzYzdlM2JmMWJjZmI0NWQ0N2U0OGRmOWJjN2NhZDMwYThlYzdmMTdhNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.77xBLXOSxXXkX7xOokEaRSv4xOXqScuXfaO6tMbDU0E)

I blocked it on Eric's PR.  So it'll be a backend issue by the time that it's ready.  :smile:

**Comment by petertgiles** [comment]
TODO: Check that "citizen" is not wrongly returned if they aren't a citizen as well

**Comment by petertgiles** [comment]
# Just recording thoughts from main:
## For candidate search table
- It seems like effective category for category sorting is happening on the backend (sortingInput PRIORITY_WEIGHT) but effective category for category display is happening on the frontend
  - I'm not sure if this is taking claims into account at all!
- It seems like the "one rejection cancels the other claim" bug happens for the display 
  - seems like bug isn't happening for the sorting but is hard to tell without the display
- It seems like the "fallback to citizen when they are actually other" bug happens for the display 
  - The bug seems to be happen for sorting as well but it is hard to tell
- It seems like the ASC/DESC is backwards on this table.  It works opposite to the talent placement table

## For the talent placement table
- It seems like the category sorting is happening with the orderByClaimVerification scope
- It seems like the "one rejection cancels the other claim" bug happens for the display 
  - seems like bug isn't happening for the sorting but is hard to tell without the display
- It seems like the "fallback to citizen when they are actually other" bug happens for the display 
  - seems like bug isn't happening for the sorting but is hard to tell without the display

## Screening and assessment table
- It seems like there's no backend sorting at all?
- It seems like the "one rejection cancels the other" bug isn't present here for sorting or display
- It seems like the "fallback to citizen" bug isn't present here for sorting or display but it's hard to tell since there's no display for citizen 

### Proposed solution:
1. Align all three table queries on the same backend sorting logic for effective category
1. Return a localized enum for the effective category from the same backend logic that is driving the sorting
2. Fix any bugs found in that logic, eg "fallback to citizen"
3. Write some phpunit tests around this
4. Delete any frontend code for calculating effective category sort or name
