### ISSUE TITLE
🐛 Vite Watch Mode - `ProfileAndApplicationsApplicant` blocked

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#10917]
## 🐛 Bug

For some reason, the ProfileAndApplicationsApplicant query is CORS-blocked when using Vite watch mode.  The `Access-Control` headers are missing and the content type is set to `text/html`.

## 📋 Steps to Reproduce

1. Start Vite watch mode
2. Navigate to the site running on port 3000
3. Log in
4. Attempt to view your profile

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/0e4abb4c-1719-40de-bdce-67669855381d)

## ✅ Acceptance Criteria

- [ ] Can view profile when using watch mode

**Comment by esizer** [comment]
uhhhh, I think I know what is causing this but I have no clue how or how to fix it 😓 

You will notice, this only happens in two instances:

- Queries that return a `User` and,
- The `poolCandidatesPaginated` query

What do these have in common you may be wondering? They both use the `@self`. No idea why that would be the cause of this though 🤷‍♀
