### ISSUE TITLE
🐛 Do not render empty `<ul></ul>` for notifications pane

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#10916]
## 🐛 Bug

If no notifications are available, the unordered list is still rendered. It probably doesn't need to take up space or exist in the tree

## 📋 Steps to Reproduce

1. Have no notifications
2. Open pane

## 📸 Screenshot

![346673238-1e0e82d2-814e-4310-a48b-c311b8fe5f4e](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/07a1722a-6915-4aba-8bdd-a8d02e459d91)

## 🙋‍♀️ Proposed Solution

Conditional rendering of the list element

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] `<ul />` is removed from html when list is empty

**Comment by mnigh** [comment]
@vd1992 what's the acceptance criteria on this issue?
