### ISSUE TITLE
🐛 Behavioral skills not considered in assessment step status

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#10919]
## 🐛 Bug

Currently, the step status is being reflected immediately after a single essential skill is assessed. We only want this to be reflected once all skills has some sort of assessment decision.

## 🦋 Expected Behaviour

Candidate only passes a step when the following criteria are met for steps other than the first step (application screening):

- All essential (regardless of category) have succeeded
- All asset skills have been assessed, regardless of whether they succeeded or not

## 📋 Steps to Reproduce

1. Login as admin `admin@test.com`
2. Navigate to a candidate in the admin
3. Assess all essential technical skills
4. Observer the overall status for the step (in the column header) updates regardless of essential behaviouirl skills have been assessed

## 📸 Screenshot

![screenshot_08-Jul-2024_14-36-1720463788](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/90b39f53-05ac-4985-a132-6344276fc21b)

## 🙋‍♀️ Proposed Solution

As well as getting a boolean value for essential skills, we should be getting a count of all skills to be assessed on the step. If the number of skills assessed is less than the total number of skills to be assessed, lock in the decision as "to assess". Only change this value and increment once all skills have been assessed.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/bd12fe758377517c4cdda3c84548f4e0de4cf84b/api/app/Models/PoolCandidate.php#L1042-L1044

## ✅ Acceptance Criteria

- [ ] Assessment step status only changes once all skills have been assessed
- [ ] All essential skills must succeed or be on hold before a step can be marked as successful

**Comment by tristan-orourke** [comment]
Regardless of the solution, lets add phpunit regression tests:
- step with multiple essential skills, one has a QUALIFIED result, second has no result at all
- step with multiple asset skills, no essential (might already have this?)
