### ISSUE TITLE
✨Old client service email should be removed everywhere or replaced

### ISSUE THREAD

**Issue by marc-donofrio** [GCTC-NTGC/gc-digital-talent#10910]
## ✨ Feature

The old gcxchange owned (and temporary) client service email should be removed everywhere.

## 🕵️ Details

Old: [gctalent-talentgc@support-soutien.gc.ca](mailto:gctalent-talentgc@support-soutien.gc.ca)
New: [support-soutien@talent.canada.ca](mailto:support-soutien@talent.canada.ca)

Verify in codebase & Azure IaC too.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] no references in the codebase to gctalent-talentgc@support-soutien.gc.ca
- [ ] no references in Azure to gctalent-talentgc@support-soutien.gc.ca

**Comment by mnigh** [comment]
The only [result in the codebase](https://github.com/search?q=repo%3AGCTC-NTGC%2Fgc-digital-talent+gctalent-talentgc%40support-soutien.gc.ca&type=code) for [gctalent-talentgc@support-soutien.gc.ca](mailto:gctalent-talentgc@support-soutien.gc.ca) is the team seeder `contact_email` for the Digital Community Management team.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/92862dd4f08d8905ee2d7c8014233fe38f7b5ede/api/database/seeders/TeamSeeder.php#L25

## Data
On the production site, the Digital Community Management team `contact_email` value is already [support-soutien@talent.canada.ca](mailto:support-soutien@talent.canada.ca), so no content management changes are needed.

### Screenshot
<img width="741" alt="Screen Shot 2024-07-16 at 15 10 12" src="https://github.com/user-attachments/assets/dd523ad8-97e6-400e-923f-5cea832d2b94">

## Azure
On the production site, the `TALENTSEARCH_SUPPORT_EMAIL` value is also support-soutien@talent.canada.ca, so nothing to update in Azure.

### Screenshot
<img width="923" alt="Screen Shot 2024-07-16 at 15 14 59" src="https://github.com/user-attachments/assets/542aaea2-f12d-4386-ae86-1bd26d8ba866">
