### ISSUE TITLE
♻️ Remove vanilla css

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#10933]
## ♻️ Refactor

There are [some files](https://github.com/search?q=repo%3AGCTC-NTGC%2Fgc-digital-talent++language%3ACSS+NOT+path%3A%2F%5Etc-report%5C%2F%2F&type=code) using vanilla css. To be consistent, the css utility library should take care of these so that there are no css files in the repository.

## 🕵️ Details

1. [apps/web/src/components/Hero/hero.css](https://github.com/GCTC-NTGC/gc-digital-talent/blob/0b33ebb7b06794e22919f2339d95c2eec870a2fa/apps/web/src/components/Hero/hero.css)
2. [packages/forms/src/components/CheckButton/check-button.css](https://github.com/GCTC-NTGC/gc-digital-talent/blob/0b33ebb7b06794e22919f2339d95c2eec870a2fa/packages/forms/src/components/CheckButton/check-button.css)

> [!NOTE]  
> [packages/ui/src/components/Alert/alert.css
](https://github.com/GCTC-NTGC/gc-digital-talent/blob/0b33ebb7b06794e22919f2339d95c2eec870a2fa/packages/ui/src/components/Alert/alert.css) would be great to move too, but seemingly not currently possible.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] hero.css, check-button.css files left removed from repository
- [ ] hero.css, check-button.css  css selectors moved to data-h2 attributes

**Comment by tristan-orourke** [comment]
@mnigh can you review the specific places this is used before we decide?

**Comment by mnigh** [comment]
> @mnigh can you review the specific places this is used before we decide?

@tristan-orourke I've re-scoped the issue, https://github.com/GCTC-NTGC/gc-digital-talent/issues/10933#issue-2401201641.
