### ISSUE TITLE
🐛 /admin/graphiql posts to /graphql in prod

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#10967]
## 🐛 Bug

In prod, our /admin/graphiql tool posts to the regular /graphql endpoint.

## 🦋 Expected Behaviour

It should be posting to /admin/graphql

## 📋 Steps to Reproduce

1. Browse to talent.canada.ca/admin/graphiql
2. Send a request
3. Observer that it gets POST'd to /graphql

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/61dfaedb-059b-4569-bcc5-58d9a9ac393d)

## 🙋‍♀️ Proposed Solution

Missing env variable in prod?

## ✅ Acceptance Criteria

- [ ] In Azure, the /admin/graphiql tool posts to /admin/graphql

**Comment by mnigh** [comment]
@petertgiles Has [this PR](https://github.com/GCTC-NTGC/gc-digital-talent/pull/10844) been deployed to prod? I don't see the PR listed in any of the [releases](https://github.com/GCTC-NTGC/gc-digital-talent/releases).

**Comment by petertgiles** [comment]
> @petertgiles Has [this PR](https://github.com/GCTC-NTGC/gc-digital-talent/pull/10844) been deployed to prod? I don't see the PR listed in any of the [releases](https://github.com/GCTC-NTGC/gc-digital-talent/releases).

I think it has - that was a pretty catastrophic failure mode.  :laughing: I would be surprised if Vite had anything to do with it since Graphiql is served from PHP.  But then again, I have no idea what's wrong.  Maybe it never worked in Azure?  This may have been the first time I tried it.

**Comment by petertgiles** [comment]
For reference, that config happens here: api/config/graphiql.php

**Comment by petertgiles** [comment]
Thanks for checking, @mnigh .  Can't reproduce today.
