### ISSUE TITLE
🐛 "Print full profile" on candidate page still uses snapshot data

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#10969]
## 🐛 Bug

It seem like the "Print full profile" action on `/admin/candidates/*id*/application` page still uses snapshot data.

## 🦋 Expected Behaviour

The Print full profile should always pull data from the users up-to-date profile

## 📋 Steps to Reproduce

1. Submit an application
2. Change something on your profile (I changed the City)
3. Go to the admin page and view the application you submitted
4. In the "More actions" sidebar, select Print > Print full profile
5. See that the download does not show the change you made to your profile

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/0fadf86a-059c-4e98-8f6a-774c29218ea2)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Print full profile and Print profile without contact info both show up-to-date profile info from the user's profile

**Comment by vd1992** [comment]
Cannot replicate, I believe resolved by https://github.com/GCTC-NTGC/gc-digital-talent/pull/10906

Off main 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/0f785364-9f3f-463e-9431-f0161ff2fef8)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/e22617bf-555b-4cbd-af3b-aa5ca66ea7b0)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/99947ba1-d2cc-470c-9138-dc2513c3dbff)

![image](https://github.com/user-attachments/assets/2c317181-a46e-4fa7-bcbf-e87d6d54dacd)
