### ISSUE TITLE
🐛 Pool candidate category sorting and display inconsistent

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#10977]
## 🐛 Bug

Right now our "Category" property for pool candidates is handled inconsistently.  Sometimes the sorting uses a scope that takes validation into account, sometimes it doesn't, sometimes it handles it on the frotnend only.  Usually the sorting happens on the backend and calculating the display name happens on the frontend.  The whole system uses a numeric weight value that gets introduced into the business logic, making it harder to maintain.

## 🦋 Expected Behaviour

Sorting and naming should be happening on the backend.  Backend sorting is mandatory to support paginated queries and the naming should happen with the same logic.  Now that we have localized enums it should make the naming easier on the backend and we may even be able to get rid of the numeric weights.  The three big pool candidate tables (pool candidate search, talent placement, screening and assessment) should be using shared logic for sorting and naming category.

## 🕵️ Details

https://github.com/GCTC-NTGC/gc-digital-talent/issues/10901#issuecomment-2225733446

## 📋 Steps to Reproduce

1. Do a "CI seed" to get a mostly empty database
2. Create a "regular user" who is a citizen with no veteran or priority status.
3. Have the regular user apply to the CMO pool
4. Create a "special user" who is not a citizen but claims veteran and priority status.
5. Have the special user apply to the CMO pool
6. Login as an admin and view the two pool candidates in the CMO pool
7. Try accepting and rejecting the veteran and priority claims on the special user to observer category naming and sorting
8. Compare the three pool candidate tables

## 📸 Screenshot

![image](https://github.com/user-attachments/assets/947d9780-44e1-4949-a854-1c5dd9d02112)

## 🙋‍♀️ Proposed Solution

1. Align all three table queries on the same backend sorting logic for category
2. Return a localized enum for the category from the same backend logic that is driving the sorting
3. Remove numeric weight column from database?  Refactor to a dynamically updated enum?  What does this do to the orderByClaimVerification scope?
4. Ensure that the backend logic for category properly handles claim verficiation
5. Fix any bugs found in that logic, eg "fallback to citizen"
6. Write some phpunit tests around this
7. Delete any frontend code for calculating effective category sort or name

## ✅ Acceptance Criteria

- [ ] Category naming comes from the backend
- [ ] Category sorting comes from the backend
- [ ] Tables (pool candidate search, talent placement, screening and assessment) share same category logic in backend
- [ ] No "fallback to citizen" bug
- [ ] No "one rejection cancels the claim other" bug
- [ ] PHPUnit tests
- [ ] Remove frontend category naming and sorting
- [ ] Sorting should go like this
Bookmarked
Priority (unless rejected)
Veteran (unless rejected)
Citizen/Permanent resident
Everyone else

**Comment by vd1992** [comment]
Just to make sure your findings aren't lost @petertgiles 
This can be used to refine and create an issue to work on or edited as needed

**Comment by petertgiles** [comment]
I'm less confident about this plan for the "screening and assessment plan" kanban board due to the unusual "sort of paginated" nature.  Maybe we scope that one out?

**Comment by vd1992** [comment]
Seems reasonable to me, might not work having a unified query including that board/page

**Comment by brindasasi** [comment]
This issue needs more through reviewing with @vd1992  , @esizer  & @Jerryescandon  to sort out more stuff.

**Comment by esizer** [comment]
- Use verified priority wherever possible
- Show citizen badge on kanban
- Sorting:
    1. Bookmarked
    2. Priority (unless rejected)
    3. Veteran (unless rejected)
    4. Citizen/Permanent resident
    5. Everyone else
    
Things to update:
 - Use `scopeOrderByClaimVerification` on candidate search page (all candidates table)
 - Update kanban to use back end sort scope as well

**Comment by vd1992** [comment]
Use verified priority refers to the pool candidate fields, avoid drawing from the user model. As a clarification
