### ISSUE TITLE
🐛 `@self` directive causes graphql to return as `text/html`

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#10980]
## 🐛 Bug

Use of the `@self` directive is causing the response to be `text/html` instead of the expected `application/json`.

## 🦋 Expected Behaviour

All graphql queries return `application/json` and not `text/html`.

## 🕵️ Details

I cannot tell why this is occurring but believe it to be the cause of #10917 but not 100% certain. Though, it seems to be the commonality in the queries that are having issues. You don't even need to query the field that uses the `@self` directive to get the HTML :face_with_spiral_eyes: 

Currently we only use the `@self` directive on two types (`User` and `PoolCandidateWithSkillCount`). It just so happens, queries that use those types are returning as `text/html` and being blocked by CORs in watch mode.

```sh
HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
```

## 📋 Steps to Reproduce

1. Login as an admin `admin@test.com`
2. Open the network tab showing fetch tab
3. Navigate to your dashboard `/applicant`
4. Notice one query is HTML and not JSON
5. Navigate to `/admin/pool-candidates` 
6. Again, notice the HTML content type

## 📸 Screenshot

![screenshot_12-Jul-2024_19-18-1720826337](https://github.com/user-attachments/assets/6856c2ab-ac0a-4518-a8a0-be9e51056f72)

## 🙋‍♀️ Proposed Solution

We only use this directive in two places so I'm wondering if we could maybe avoid it entirely and find a different way of doing the same thing? :thinking: 

#### Method

We could try the [`@method` directive](https://lighthouse-php.com/6/api-reference/directives.html#method) instead of a scope? :thinking: 

The thing is, the sorting may be tricky since we wouldn't have the query available in the method so we may need to also have 

```graphql
type PoolCandidate {
  skillCount(skills: [UUID!]) @method
}
```

```php
class PoolCandidate
{
  public function skillCount(array $skills)
  {
     return $this->user->whereHas('userSkills', function ($query) use($skills) {
        $query->whereIn('skill_id', $skills);
     })->count();
  }
}
```

#### Resolver

We could also just split this query off since skill count is sort niche to the pool candidate table and not used anywhere else.

### User

This is so we can split out the user auth info. Maybe instead of using the `@self` we just use a custom attribute? We could keep the sub type in graphql but instead of using self we could just do:

```graphql
type User {
  authInfo: UserAuthInfo
}
```

```php
class User
{
    public function authInfo()
   {
      return new Attribute(
          get: function () {
            if(!Auth::user()->isAbleTo("view", $this)) return null;
            
             return [
                'sub' => $this->sub,
                /...
             ];
          }
      )
   }
}
```

## ✅ Acceptance Criteria

- [ ] GraphQL queries/mutations only return as `application/json`

**Comment by tristan-orourke** [comment]
I'd definitely have a preference for fixing the self directive, but if we really can't figure it out we can find alternatives.

**Comment by esizer** [comment]
> I'd definitely have a preference for fixing the self directive, but if we really can't figure it out we can find alternatives.

So, I was able to easily get rid of `@self` and it doesn't seem required. However, the two queries continued to return `text/html`. Not sure if the headers were cached or what. But, that makes me suspicious about it being the `@self`, even though the only queries returning `text/html` are the ones that use it 😅 We also lose our access control headers to and I really cannot tell why 😕 

Thouhgh, we can force the headers in at the nginx layer and it works but then we get duplicate headers 😖
