### ISSUE TITLE
🐛 Input backgrounds white on dark mode

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#10986]
## 🐛 Bug

Even with dark mode selected, the backgrounds of inputs are currently white.

## 🦋 Expected Behaviour

Inputs should change to the dark mode colour when enabled.

## 📋 Steps to Reproduce

1.  Change to dark mode
2. Navigate to any page with an input
3. Observe the white background

## 📸 Screenshot

![2024-07-15_16-28](https://github.com/user-attachments/assets/69b6599f-ec30-4996-aefc-c74f9e767de2)

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

- [ ] Inputs have dark mode background when dark mode enabled

**Comment by mnigh** [comment]
@esizer I tried reproducing this on macOS 12.7.5 with Chrome, Firefox, Edge, and Safari on `main` branch locally but could not. Were you able to reproduce with another operating system and browser?

<details>
  <summary>Screenshots</summary>
  <img width="1228" alt="Screen Shot 2024-07-15 at 19 54 11" src="https://github.com/user-attachments/assets/7db745d7-f86b-43a6-b1ff-436f1525f9b1">
<img width="1256" alt="Screen Shot 2024-07-15 at 19 54 01" src="https://github.com/user-attachments/assets/689dd5f3-cc04-468e-9db0-cb5d7e1aa12a">
<img width="1346" alt="Screen Shot 2024-07-15 at 19 54 56" src="https://github.com/user-attachments/assets/dfe57a74-1e57-4859-8110-fdb34f5cce14">
<img width="1299" alt="Screen Shot 2024-07-15 at 19 54 19" src="https://github.com/user-attachments/assets/9b954df0-a496-4886-a254-181415032ae9">

</details>
