### ISSUE TITLE
✨ Add notification bell to Admin UI

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#11019]
## ✨ Feature

Now that the file download feature will make use of notifications, Admins should really be able to see when they have new notifications from their own UI.

## 🕵️ Details

Add the notification icon to the admin sidebar nav, just under the Dashboard link. When the menu is expanded, it should have the text "Notifications". 

In desktop view, clicking the Notifications link should open the notifications dialog from the left, to the right of the nav drawer. 

**NOTE:** The admin nav drawer will very soon be replaced by a unified nav menu. Therefore, I don't want to spend much time on any unique behaviour for the notifications dialog. If it's non-trivial to have it open on the left, it's okay if it opens on the right like on the applicant UI.

## 🎨 Design File

https://www.figma.com/design/fgzxRKjFr4ZUMn5ail1Yc2/Admin---Notification-interface?node-id=111-7725&t=HbsqMGrlmpy9czqm-0

### 🧑‍🎨 Designer

@Jerryescandon 

## 📸 Screenshot

![image](https://github.com/user-attachments/assets/354c117d-7cea-406c-87b4-530625737be6)

## 🙋‍♀️ Proposed Implementation

Something to be careful about - the icon as is won't be visible in light mode in the menu.

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Notifications appear in the admin side nav, under Dashboard
- [ ] The bell icon is visible in light or dark mode
- [ ] clicking it opens notification pane from the left, to the right of the nav drawer (NOTE: skip this if it takes much effort)
- [ ] When expanded the nav menu says "Notifications" next to the icon

**Comment by mnigh** [comment]
@Jerryescandon should the icon for Notifications be `bell-alert` instead of `home`?

## Screenshot
![350526497-4c54bce0-fbe1-4e20-839d-9b4fc127894e](https://github.com/user-attachments/assets/a2adfe58-a69b-4589-acd3-24844f7f7114)

**Comment by Jerryescandon** [comment]
Fixed!
