### ISSUE TITLE
🐛 Faker relationship values all identical

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#11017]
## 🐛 Bug

When we try to create fake values using nested generators and the `faker.helpers.arrayElement` helper, it always selects the same item in the iteration leading to duplicate items.

This is most obvious on the [pool candidates table](https://61e099a1bb1465003a73d3ce-iscinuijry.chromatic.com/?path=/story/components-poolcandidatestable--default).

## 🦋 Expected Behaviour

Sub models are unique per row but remain stable.

## 🕵️ Details

I think this has to do with our `faker.seed(0)` call. We need this to keep data stable for chromatic snapshots. However, it seems it is too stable and forcing `faker.helpers.arrayElement`to always select the same item from a generator regardless of iteration.

## 📋 Steps to Reproduce

1. Start up storybook `pnpm run storybook`
2. Navigate to the "PoolCandidatesTable" story
3. Observe the same data in every row after the first

## 📸 Screenshot

![2024-07-19_08-33](https://github.com/user-attachments/assets/a919a5cf-b9e5-40c5-ab22-23d54cf805f9)

## 🙋‍♀️ Proposed Solution

Honestly, I'm not sure. Maybe we can be more targetted about the seed instead of calling it in every file? Or, look and changing how we do the subfields? Maybe generate a single user every iteration instead of picking it from an array? :thinking: 

## ✅ Acceptance Criteria

- [ ] Fake data that contains sub models are random per iteration
- [ ] Fake data remains stable between builds for snapshots

**Comment by tristan-orourke** [comment]
Do we push the seed setting down a level?
Or we could generate all the relationship values at the faker level, so we can generate n at a time, and pass them in to the children.
