### ISSUE TITLE
🐛 No limit for notification page queries

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#11024]
## 🐛 Bug

There is no limit to how many notification page queries can be requested.

## 🦋 Expected Behaviour

There should be a max number of how many pages can be queried.

## 📋 Steps to Reproduce

> [!WARNING]  
> Be prepared for your machine to 💥 if you do this.

1. Navigate to `http://localhost:8000/en/applicant/notifications?page=10`
2. Change `page` query parameter to something like 10000
3. Observe your machine grind to a halt

## 📸 Screenshot

<img width="719" alt="Screen Shot 2024-07-19 at 14 04 46" src="https://github.com/user-attachments/assets/3322ed41-e4ed-4ef9-84cd-2eac1e7284b8">

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] max number of how many pages can be queried for notifications pagination

**Comment by gobyrne** [comment]
Can we address this at a app-wide level rather than just this query?
