### ISSUE TITLE
Submenu component

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#11033]
## ⚙️ Summary

> [!NOTE]
> The sub-menus described below are specific the desktop layout of the menu - the mobile version should handle sub-menus as simple `<details>` elements.

<details>
  <summary>Role sub-menu</summary>
  <p>This sub-menu only appears for users who have access to more than the applicant role on their account. Choosing an option from the role menu should take the user to that respective role's dashboard assuming they have the correct permissions.</p>
  <p>The role sub-menu is unique in that it's label changes to match the current selection. This is helpful because it allows the user to see, regardless of their location on the site, which role they're currently acting as.</p>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/8fa9ac18-e205-4c43-8c55-c275458d4125" />
</details> 

<details>
  <summary>System settings sub-menu</summary>
  <p>This sub-menu is specific to the system admin role and allows for easy navigation to the CRUD interfaces for individual data models. Each item in the sub-menu should take the user to that item's respective index table, from where they can manage that particular data model.</p>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/ea2ebdff-6723-49fd-ac13-4779b7fedf0f" />
</details> 

<details>
  <summary>Account sub-menu, applicant</summary>
  <p>The following options are presented when acting as an <code>applicant</code>:</p>
  <ul>
    <li><em>Applicant profile</em> - Takes the user to the screen that allows them to edit their applicant-specific profile information</li>
    <li><em>Career timeline</em> - Takes the user to their career timeline</li>
    <li><em>Skill library</em> - Takes the user to their skill library page</li>
    <li><em>Account settings</em> - Takes the user to their universal account settings</li>
    <li><em>Sign out</em> - Logs the user out of their current session</li>
  </ul>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/5818bae5-3ed8-4ce3-ab44-77d161b4ba77" />
</details> 

<details>
  <summary>Account sub-menu, manager</summary>
  <p>The following options are presented when acting as a <code>manager</code>:</p>
  <ul>
    <li><em>Manager profile</em> - Takes the user to the screen that allows them to edit their manager-specific profile information (note that this doesn't exist yet)</li>
    <li><em>Account settings</em> - Takes the user to their universal account settings</li>
    <li><em>Sign out</em> - Logs the user out of their current session</li>
  </ul>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/5a8b395c-3d79-489d-a65b-fe443df8363d" />
</details> 

<details>
  <summary>Account sub-menu. community</summary>
  <p>The following options are presented when acting as a <code>community</code>:</p>
  <ul>
    <li><em>Account settings</em> - Takes the user to their universal account settings</li>
    <li><em>Sign out</em> - Logs the user out of their current session</li>
  </ul>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/ead56771-fab4-4638-b0e8-c482f2aabef3" />
</details> 

<details>
  <summary>Account sub-menu, system admin</summary>
  <p>The following options are presented when acting as a <code>system admin</code>:</p>
  <ul>
    <li><em>Account settings</em> - Takes the user to their universal account settings</li>
    <li><em>Sign out</em> - Logs the user out of their current session</li>
  </ul>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/e002a3d4-73ea-4e95-aaa6-ba782020fe1a" />
</details> 

## 🎨 Design File

[Figma design](https://www.figma.com/design/guHeIIh8dqFVCks310Wv0G/Component-library?node-id=1475-27575&t=UxP3PPvtGnmI3NXy-0)

### 🧑‍🎨 Designer

@substrae 

> [!NOTE]  
> For all layout and spacing guidance, including how this component should respond on smaller devices, please see the Figma file.

### ✅ Acceptance criteria

- [ ] 

#### Description

Property description.

#### Screenshot

Property screenshot(s).

## 💡 Interaction states

Summary of interaction states.

#### Description

Hover state description.

#### Screenshot

Hover state screenshot.

#### Description

Focus state description.

### Screenshot

Focus state screenshot.

### Accessibility feature name

Feature description.

**Comment by yonikid15** [comment]
We already have a Dropdown component that has this functionality
