### ISSUE TITLE
Role switcher dropdown

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#11031]
## ⚙️ Summary

Create a Dropdown that appears on the nav menu and the dashboards, allowing users to switch between different roles. Use the `<DropdownMenu />` component we already have. This component will be purely frontend work, so assume the `currentRole` is being passed in as a prop for now. As well as a switchRole method prop, which is triggered in the dropdown item `onClick`.

The component should fetch localized Role enums, and display them in the correct order. Since the drop down trigger is always the current role, we'll need detailed aria-labels to meet accessibility needs (e.g. "You are currently in the Applicant role. Select to switch roles.", and "Go to your applicant dashboard.").

## 🎨 Design File

https://www.figma.com/design/oZhQe9ahidHFfaiqgREvxa/Dashboard-(All-users)?node-id=1010-18639&t=j4U5JEvsDbOlCAf0-0

### 🧑‍🎨 Designer

@substrae 

> [!NOTE]  
> For all layout and spacing guidance, including how this component should respond on smaller devices, please see the Figma file.

#### Sub-components

> [!NOTE]
> The sub-menus described below are specific the desktop layout of the menu - the mobile version should handle sub-menus as simple `<details>` elements.

<details>
  <summary>Role sub-menu</summary>
  <p>This sub-menu only appears for users who have access to more than the applicant role on their account. Choosing an option from the role menu should take the user to that respective role's dashboard assuming they have the correct permissions.</p>
  <p>The role sub-menu is unique in that it's label changes to match the current selection. This is helpful because it allows the user to see, regardless of their location on the site, which role they're currently acting as.</p>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/8fa9ac18-e205-4c43-8c55-c275458d4125" />
</details> 

## 🛠️ Properties

- currentRole: `string`
- switchRole: `() => void;`

### ✅ Acceptance criteria

- [ ] Component matches design for all views (mobile, dark + light themes, etc.)
- [ ] Create lang files for enum Role on backend. (Possibly re-use translations we have in other parts of the sight)
- [ ] Aria-labels added to drop down trigger and items/links
- [ ] Roles are displayed in the correct order
- [ ] The current role is highlighted when drop down is open
- [ ] Urls for each role is correct
- [ ] Only shows roles that owned by the current user

## 🛑 Blockers
```[tasklist]
### Blocked by
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/11034
```

**Comment by yonikid15** [comment]
Can we get the URLs for all the role links in the dropdown @tristan-orourke? The current roles in the Role enum are:
- Base user (guest)
- Applicant
- Pool operator
- Request responder
- Community manager
- Platform admin

**Comment by tristan-orourke** [comment]
First of all, not every role needs an item in the dropdown. We already have `/applicant` and `/admin`. Managers will have their own item and dashboard. The rest of the roles will be grouped together as Community roles.

As we already have `/applicant` and `/admin`, the natural choices for the Manager and Community role dropdowns would be `/manager` and `/community`. Manager is tricky though because `/manager` is already taken as a public info page. 🤔 

I'm thinking now that we should move the current https://talent.canada.ca/manager page to a different url. Maybe `/manager-info`? @petertgiles and I already talked about this once, and my opinion at the time was that we could just use `/manager/dashboard`, but then, do we change the other dashboard urls to match?
