### ISSUE TITLE
⚙️ Task card component

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/gc-digital-talent#11075]
## ⚙️ Summary

- Create a new `<TaskCard/>` component. This component acts as a wrapper for whatever content needed (list of accordions, text, etc). The card header contains an icon (optional), title (required), heading color (optional), and a link in the top right corner (optional). This is very similar to the `<Card />` component so try using that and incorporating and new properties as needed.

![image](https://github.com/user-attachments/assets/3de36367-3fc0-45cc-8705-64df4860d60e)

## 🎨 Design File

[Figma design](https://www.figma.com/design/oZhQe9ahidHFfaiqgREvxa/Dashboard-(All-users)?node-id=1010-18071&t=5sabmafb44VqvrwG-0)

### 🧑‍🎨 Designer

@substrae 

> [!NOTE]  
> For all layout and spacing guidance, including how this component should respond on smaller devices, please see the Figma file.

### ✅ Acceptance criteria

- [ ] Component matches design
- [ ] Properties are generic and only accept what's needed for the component
- [ ] Title is the correct heading size relative to page
- [ ] Link takes user to new page. If link is undefined, it should not render
- [ ] Heading color shows up correctly
- [ ] Component is added to Storybook
- [ ] NOTE: The `<Well />` displayed in the design is only a placeholder

## 🛠️ Properties

- title - string, required
- icon - IconType, optional
- link - ReactNode, optional
- color - ColorType, optional, default -> "primary"

**Comment by petertgiles** [comment]
Which colours need to be supported?  Primary to quinary?  [All 13](https://github.com/GCTC-NTGC/gc-digital-talent/blob/19962f88245d978f478ff7d626f2146e34041089/packages/ui/src/types.ts#L9)?  How does it look if the color prop is not provided?

**Comment by petertgiles** [comment]
Probably obvious, but I think Storybook stories need to be in the AC.

**Comment by petertgiles** [comment]
Does this component have an aria role?
