### ISSUE TITLE
⚙️ Preview item component

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/gc-digital-talent#11077]
## ⚙️ Summary

- Create new `<PreviewItem />` component. This should be reusable in both the applicant and manager dashboards (possibly other parts of app), therefore keep the component types generic. If needed, we can build more specific components using this one. There are three parts: title, information list (separated by bullets), and a icon.

![image](https://github.com/user-attachments/assets/7b90bc30-5a0f-43e0-ba4e-c5ddf86ba0d2)

## 🎨 Design File

[Figma design](https://www.figma.com/design/oZhQe9ahidHFfaiqgREvxa/Dashboard-(All-users)?node-id=1010-18071&t=5sabmafb44VqvrwG-0)

### 🧑‍🎨 Designer

@substrae 

> [!NOTE]  
> For all layout and spacing guidance, including how this component should respond on smaller devices, please see the Figma file.

### ✅ Acceptance criteria

- [ ] Component matches design
- [ ] Properties are generic and only accept what's needed for the component
- [ ] If optional props are not added, design proportions are still balanced.
- [ ] The icon shows `magnifying-glass-plus` from https://heroicons.com/
- [ ] Information block is separated by bullets and spaced correctly.
- [ ] Component added to Storybook

## 🛠️ Properties

- title - string, required
- information block - list of ReactNode or custom type. See [ProfileDetails.tsx](https://github.com/GCTC-NTGC/gc-digital-talent/blob/11019-add-notifications-to-admin-dashboard/apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/components/ProfileDetails/ProfileDetails.tsx#L1-L136) for reference.
  - This could also be a custom type for easier control on styling 
  -  `{ type: "text" | "link" | "pill", value: ReactNode }[]` and then create mini blocks in the file for each type.

#### Screenshot

![image](https://github.com/user-attachments/assets/203d6862-a21f-4552-80d2-ecdac8fe6299)

**Comment by petertgiles** [comment]
What's clickable on this component?  Just the links in the info block?  The title?  The icons?  The whole thing together?

Why is there an  prop to change the icon but the AC says ` The icon shows the magnifying-glass-plus`?

Is there an aria role?

Could we see a design where the title and info block are wrapping?

Is there a different mobile design?
