### ISSUE TITLE
⚙️ Resource block component 

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/gc-digital-talent#11078]
## ⚙️ Summary

- Create the `<ResourceBlock />` component. These blocks will be used to give the user easy access to other parts of the site, specifically parts of the profile. Additionally, the status icon will give a quick view on if that resource if complete or not.
-  Use the TaskCard component as a wrapper. You might need to add a prop to change position of the title in the heading. 
- The content includes three parts: a link to the resource, a status (check mark or warning icon) representing if it's complete or not, and a short description of resource.
- In the design you can see a block may contain more than one resource. Therefore, we can have a prop which accepts a list of resources or create a compound component (See Dialog or Accordion, which has something like a `<ResourceBlock.Root />` holding the root level props (title, color) and `<ResourceBlock.Item />` (link, description, status).

![image](https://github.com/user-attachments/assets/7b374880-89a7-48c4-a12f-da46397fbc44)

## 🎨 Design File

[Figma design](https://www.figma.com/design/oZhQe9ahidHFfaiqgREvxa/Dashboard-(All-users)?node-id=1010-18071&t=5sabmafb44VqvrwG-0)

### 🧑‍🎨 Designer

@substrae 

> [!NOTE]  
> For all layout and spacing guidance, including how this component should respond on smaller devices, please see the Figma file.

### ✅ Acceptance criteria

- [ ] Component matches design
- [ ] Properties are generic and only accept what's needed for the component
- [ ] Status shows the correct icon
- [ ] Uses the TaskCard component as a wrapper (if possible/not to difficult). Heading is centred.
- [ ] Whole block is clickable
- [ ] Ensure icon is just decorative

## 🛠️ Properties

- color- ColorType, optional, default -> "primary"
- title - string, required
- resource item props
  - link - string, required
  - status - string union, optional
    - eg. status?: "complete" | "incomplete"
  - description - string, required (?)

## Screenshots
![image](https://github.com/user-attachments/assets/79689e7d-38a7-4e4d-b0c7-7aa35a19e1b8)

**Comment by tristan-orourke** [comment]
The card that wraps these resource blocks is a little different from the [task card](https://github.com/GCTC-NTGC/gc-digital-talent/issues/11075), in that the title is centered

**Comment by petertgiles** [comment]
Is there a reason the status is a boolean?   A string union would probably be more expressive and flexible.  And is more consistent with the rest of the codebase.

Is the click target the whole block or just the title?

Why is there an arrow by the title?  Is this a new design for the "opens as a tab" icon?

Is there an aria role for this?
