### ISSUE TITLE
🐛 Teams dropdown throws in bunch of "Not available" options

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#11080]
## 🐛 Bug

While creating a process the Teams dropdown opens up like this 
![Screenshot 2024-07-29 153433](https://github.com/user-attachments/assets/c37f84a9-71e1-40e8-8fb3-aa80eab5dfa8)

## 🦋 Expected Behaviour

Team dropdown should show only available teams. This is happening only on UAT and Prod 

## 🕵️ Details
The query involved is "CreatePoolPage" 
The teams options are pulled from me.authInfo.RoleAssignments and the query returns the results like below as over 100 Roleassignments and all of them are having null value in DisplayName except the DCM team. 
Hence it displays "Not available" for all others
![image](https://github.com/user-attachments/assets/065edf25-e38c-4ada-8eb0-27c014c986b4)

![Screenshot 2024-07-29 153943](https://github.com/user-attachments/assets/da7ebeb3-2223-4c0e-9860-4debf86cee51)

## 📋 Steps to Reproduce
I see this is happening in UAT as well as prod. Something going on here. 

1. Goto create process page in UAT or prod if have admin access 
2. Check out Teams dropdown

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Teams dropdown should only display the teams that the user is part of as the process operator.

**Comment by vd1992** [comment]
I think this is coming from the new teamable teams, that can be community or pool. They don't have display names

![image](https://github.com/user-attachments/assets/ea17cc33-82a1-4811-be94-373d32fbf829)

How the name is generated

![image](https://github.com/user-attachments/assets/448edaf0-9772-4a1c-b88a-fc5d585f71a7)

In your screenshot you can see a pool one here

![image](https://github.com/user-attachments/assets/81a091a9-ae09-4e4a-9507-5f5b4e2365ad)

**Comment by tristan-orourke** [comment]
We need to make sure to only show LegacyTeams in these dropdowns. I think the most reliable way to filter for these to filter out teams with a teamable relation. Maybe null display name is sufficient.
