### ISSUE TITLE
🐛 File download error is sometimes wrong

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#11098]
## 🐛 Bug

If a user tries to download a file that doesn't exist they get an error message saying that the file is over 24 hours old.  However, if some other unexpected reason (permissions issue, app service deployment, etc...) causes the file to not be available then the error message is wrong.  The app doesn't actually know if the requested file used to exist but was cleaned up.  The user probably does know how the old the file is and the false statement increases confusion.

## 🦋 Expected Behaviour

The error message should probably be worded as "_if_ the file is 24 hours old..." instead of confidently declaring it.

## 🕵️ Details

https://github.com/GCTC-NTGC/gc-digital-talent/blob/aa29935a1fea353eeb638051e990f2b88f3e71a9/apps/web/src/components/NotificationList/NotificationDownload.tsx#L47-L55

## 📋 Steps to Reproduce

1. Generate a file (eg profile document)
2. Manually delete the generated file in the backend
3. Click the notification

## 📸 Screenshot

![image](https://github.com/user-attachments/assets/3480206e-a497-407f-8bff-99e00f7437cd)

## 🙋‍♀️ Proposed Solution

- This file is not available. If it's been more than 24 hours since you requested it, please try requesting the download again. If it's been less than 24 hours or the problem persists, contact support for assistance.

## ✅ Acceptance Criteria

- [ ] Error message update

**Comment by NienkeBr** [comment]
@petertgiles Should users contact support for assistance for all the other possible reasons or are there other tips we could give them? If not, I'd suggest the following error message:
- "This file is not available. If it has been more than 24 hours since you requested it, please try downloading it again. If it has been less than 24 hours or the problem persists, contact support for assistance."

**Comment by petertgiles** [comment]
I like it!  The one change I'd recommend is:
> If it has been more than 24 hours since you requested it, please try _requesting_ it again.

Downloading again won't help.  We want them to regenerate the file.  So "requesting", "generating", "starting" or something like that.

**Comment by NienkeBr** [comment]
I see what you mean. I wrote 'download' as you request it by clicking on something that says 'Download [profile/CVS/etc.]', but I think what you suggests also works.
