### ISSUE TITLE
🐛 UAT - Didn't receive email verification email 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#11101]
## 🐛 Bug

I didn't get the email verification email in UAT. My work email is whitelisted and have received emails from our application before.
Supervisor is running with 2 workers and a cron.

Tried "Send another code". Still no email. 

## 🦋 Expected Behaviour

Email should be received when I click on `Verify now` link 

## 📋 Steps to Reproduce

1. Log on to UAT and your whitelisted work email.
2. Go to Profile and applications -> Personal information
3. Click on Verify now
4. Observe no email is coming up

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Email should be sent with verification code upon clicking on `Verify now` 
- [ ] once verification code is entered, the label beside the email address should be changed to `Verified`

**Comment by tristan-orourke** [comment]
Did the new email templates on GC Notify get added to IaC?

**Comment by brindasasi** [comment]
Template ID was there. But it had incorrect value. Correct value got me the email. 
However I don't see any error message when the email is failed to send. 
Will create another issue for that.
