### ISSUE TITLE
🔤 Step 4 of application process - update guidance

### ISSUE THREAD

**Issue by NienkeBr** [GCTC-NTGC/gc-digital-talent#11128]
## 🔤 Copy

Current copy: "If both apply to you, that’s great! Feel free to select the option that best reflects your qualifications."
Current copy French: "Si les deux s’appliquent à vous, c’est formidable! N’hésitez pas à sélectionner l’option qui correspond le mieux à vos qualifications."

Updated copy: "**If both apply to you, select the education criteria**."
Updated copy French: "**Si les deux s'appliquent à vous, sélectionnez les critères d'études.**"
Note: We would like the updated copy to be bolded.

## 🕵️ Details

We're updating the copy to reflect that some departments prefer the education requirement.

![image](https://github.com/user-attachments/assets/4dd33960-c605-4a92-9e77-6282020bf8ab)

### 🧑‍🎨 Designer

@Jerryescandon could you please update this in figma for now? I'll start doing it when I have access etc. Thank you!

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the copy has been added or updated appropriately.

- [ ] Put new copy in place

**Comment by Jerryescandon** [comment]
Updated figma file: [Application: 04 - Education requirements (Applicants)](https://www.figma.com/design/5ncorHL9S02hDD7qAyZTuU/Application%3A-04---Education-requirements-(Applicants)?node-id=1-2&t=2Q52ME1xNh5EfebX-1)
