### ISSUE TITLE
🐛 Error logging is no longer working on the email notification

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#11130]
## 🐛 Bug

I had a wrong template id string on the UAT. I didn't receive any email but I didn't see any laravel error message as well.
After some retries I got 
`"exception": "Illuminate\\Queue\\MaxAttemptsExceededException: App\\Jobs\\GcNotifyApiRequest has been attempted too many times` into failed_jobs table.

But it would be nice to see the laravel log on what went wrong. 

## 🦋 Expected Behaviour

What should be happening?

## 🕵️ Details

We have the code for logging as below 

![Image](https://github.com/user-attachments/assets/2c03a046-1ee7-46e1-b011-ebbf56b235d3)

But looks like it is broken 

## 📋 Steps to Reproduce

1. change any template id into a wrong string ( for ex. verification email ) . ( Make sure to switch back if you are doing this on Dev as this is in a common file for all verticals. Prod will be broken if you left it with wrong string)
2. Trigger the email 
3. Watch laravel logs
4. Observe you don't receive any email but eventually it got into failed_jobs table
5. Observe there is no error log on the laravel

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Error message should be logged in to laravel logs when there is any issue to send email

**Comment by petertgiles** [comment]
Can't replicate locally.
![image](https://github.com/user-attachments/assets/76f68545-d1c1-4823-a124-48f5ece8cca0)

I will check in Azure to try to replicate there.

**Comment by petertgiles** [comment]
Can confirm that the errors are not being logged in UAT.  I don't know why yet.

**Comment by petertgiles** [comment]
I'm still not sure why.  I see a lot of "tried to unsafely use role" warnings so I'm guessing that might be it.  I'll put this down and try to work on [#11144](https://github.com/GCTC-NTGC/gc-digital-talent/issues/11144) instead.

**Comment by petertgiles** [comment]
OK, I think I figured it out.  In Azure we use stdout logging.  Unfortunately, in Laravel, scheduled jobs cannot write to stdout.  This has been brought up many times with many workarounds online.

https://github.com/laravel/framework/discussions/47448
https://github.com/laravel/framework/discussions/38429
https://github.com/laravel/framework/discussions/50085

This is why we currently write output from scheduled jobs to log files. https://github.com/GCTC-NTGC/gc-digital-talent/blob/5d0d521ec6ca1708c3a6421610f9774772ae6f1c/api/app/Console/Kernel.php#L28

I guess the way forward is to pick a nasty workaround and implement it.

**Comment by petertgiles** [comment]
I haven't been able to get anything to work.  😢   The added wrinkle is that we run the workers as the user `www-data` so we don't trample files touched by FPM workers.  Unfortunately, that also means that we can't write to `/proc/1/fd/1` (process 1 /dev/stdout) and get picked up by docker.  Our `/proc/self/fd/1` stream doesn't get to docker logging.  I'm considering a few options:

1) Rig up some sort of log file reader that runs as root, reads log files, and pipes them into stdout.  Sounds super janky.  😬 

2) "Docker conventional wisdom" is that you should only be running one thing in a container.  We could run the laravel workers in their own container.  They could run as root and then would have privileges to write to /proc/1/fd/1.  This is probably the cleanest solution and we may want to run them in a separate container for scaling eventually anyway.  But it's a huge jump in complexity and maintenance effort.

3) We could bypass Docker totally and log into Azure Application Insights.  Unfortunately, the [PHP SDK](https://github.com/microsoft/ApplicationInsights-PHP) went into maintenance in 2022.  It seems like [OpenTelemetry](https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-overview is the hot new thing.  There is an [official PHP library](https://opentelemetry.io/docs/languages/php/) and bunch of packages from others, too.  This sounds great but it will probably take a lot of effort to set up and I'm a little worried about the performance, too.

**Comment by petertgiles** [comment]
A combination of 1 and 3 is to start using [Azure Monitor](https://github.com/spatie/laravel-open-telemetry to collect logs from files.

**Comment by petertgiles** [comment]
Shorter term solution: https://github.com/GCTC-NTGC/gc-digital-talent/issues/11288
Longer term solution: https://github.com/GCTC-NTGC/gc-digital-talent/issues/11289

**Comment by gobyrne** [comment]
Peter's new issues are described and replace this one.
