### ISSUE TITLE
🐛 New job posted email got sent 3 times to users about the same job 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#11152]
## 🐛 Bug

On Aug. 2 Friday around 1:30 pm we have sent 3 notification emails about the new job posted `IT security Analyst ` .

## 🦋 Expected Behaviour

We should not be sending duplicate emails 

## 🕵️ Details

We have 3 published processes in production. Would that align with why 3 times they have been sent out? 🤔
Here is the process details
https://talent.canada.ca/en/browse/pools/4a8e9f9f-56af-4c21-ad58-864351e088d4

## 📋 Steps to Reproduce
Couldn't reproduce in UAT.
Need more investigation on production why this is happened.  

## 📸 Screenshot

Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] New job notification email should be sent only once.

**Comment by tristan-orourke** [comment]
So there's something different about how we trigger New Job emails compared to other emails.

All the duplicate emails happened around the same time. Maybe a restarting process?

**Comment by tristan-orourke** [comment]
This all happened around the same time. Cross-reference this time with other server logs

**Comment by tristan-orourke** [comment]
Let's check with admins to see if the job was closed and opened again? Or check activity log.

**Comment by tristan-orourke** [comment]
Maybe they closed it early, duplicated, fixed, republished?

**Comment by brindasasi** [comment]
Email sent timings are 
Sunday, Friday Aug.2 1:29 PM , 1:32 PM , 1:38 PM for a particular user who reported this issue.
All other emails are within the same time range with the seconds vary.

**Comment by brindasasi** [comment]
Recruitment team confirmed they did NOT make any changes or re publish the pool :(

**Comment by petertgiles** [comment]
I only see the one pool with that name this year.
![image](https://github.com/user-attachments/assets/7c10582e-4eb4-4503-aa91-1053586b9fba)

And it doesn't look like the published date was ever changed.
![image](https://github.com/user-attachments/assets/c9f01dcb-953c-4a2c-b57f-d74f814fe495)

**Comment by petertgiles** [comment]
I looked in the failed_jobs table and found a row for api/app/Listeners/SendNewJobPostedNotification and a TimeoutException.  I think what's happening is the listener job starts queuing individual notifications, gets part way through the list, then times out.  Then it retries a few times.  Every time it runs some subset of the list of users gets notified.  This also explains #11153 .

I think we need to look into extending the timeout duration to a longer period when the job is expected to be long-running.  This will help user file generation as well.

**Comment by petertgiles** [comment]
Will try to measure time for 22,000 notifications
![image](https://github.com/user-attachments/assets/d2bd08b9-95ce-4389-bf10-1a954d6042b7)

Default timeout is 60 seconds.
https://laravel.com/docs/10.x/queues#timeout

**Comment by petertgiles** [comment]
I tried this out locally.
1. Confirmed the default 60 second timeout.
2. Queued about 7400 jobs before timeout.
