### ISSUE TITLE
🐛 New job notification has not been sent to all subscribers in the prod

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#11153]
## 🐛 Bug

A new job posted on Aug. 2 Friday and we have around 22k users subscribed for email notifications.
I see only around 450 messages are sent out. 

## 🦋 Expected Behaviour

All subscribers should get the appropriate emails

## 🕵️ Details

I believe any error in the email queue messes up the whole remaining delivery. 

## 📋 Steps to Reproduce

Need further investigation based on prod incident. 

## 📸 Screenshot

Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] All subscribers should get the email notifications accordingly.

**Comment by tristan-orourke** [comment]
Rate limiting and not retrying, or we hit rate limit, or something wrong with the queue? 
We can check logs for failures (are they all fake emails?)
