### ISSUE TITLE
🐛 On protected endpoint, can send another user's email verification message

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#11155]
## 🐛 Bug

If you're on the protected endpoint it might be possible to send another user their email verification message.  I think this bug was masked due to using the unprotected endpoint in the test.

## 🦋 Expected Behaviour

It should only be possible to send the email verification for the currently logged in user.

## 📋 Steps to Reproduce

1. In api/tests/Feature/UserVerifyEmailTest.php, change `use UsesUnprotectedGraphqlEndpoint;` to `use UsesProtectedGraphqlEndpoint;`
2. Run `./artisan test tests/Feature/UserVerifyEmailTest.php  --filter=testUserCantGenerateNotificationForSomeoneElse`

## 🙋‍♀️ Proposed Solution

Maybe a policy or validator on that the `SendUserEmailVerification` mutation.

## ✅ Acceptance Criteria

- [ ] Test updated or new test written to expose bug
- [ ] Can no longer send email verification to another user, regardless of endpoint.
- [ ] Remove user id from email verification endpoints. Should just use authenticated user's id

**Comment by vd1992** [comment]
How about the `VerifyUserEmail` class or `verifyUserEmail` mutation? Should that be auth-locked too?
