### ISSUE TITLE
♻️ Search page startup is slow

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#11163]
## ♻️ Debt/Refactor

Our search page often takes 5 - 10 seconds to fully load.  Can we improve this?

## 🕵️ Details

It seems like the two slowest queries are CandidateCount and SearchForm which both take over 2 seconds.  

## 🙋‍♀️ Proposed Solution

It makes sense that CandidateCount is a bit slow.  But the SearchForm query which populates the form and prevents the page from even showing is probably unnecessarily slow.  It's all public and pretty static data - can we cache it between users?  Or can we add some indexes?  Or are we overfetching?

Lets focus on the SearchForm query
1. Check for overfetching (are requesting more data than we need?)
2. Do we need to load pools at all, or is there an alternative? If we just need names of pools for the buttons at the bottom, would it be faster to run narrower queries after the candidate count comes back (or include pool name data in the candidate count query)
3. If we want to continue pre-fetching pools, could we filter out some (eg archived)
4. Is there a reason the query is slow, besides quantity of data (lots of policies running, complicated db query, etc?)
5. Finally, could consider [caching](https://lighthouse-php.com/6/performance/caching.html)

## ✅ Acceptance Criteria

- [ ] ~Improve speed of search page startup~
- [ ] Improve speed of SearchForm query used to render Search page

**Comment by esizer** [comment]
Looking into this I noticed a few things that would help but not sure if we can do it.

1. We are querying every single published pool just to derive the classification. I feel like we could just pass along the ID of the pool you are requesting from and then query the required info of just that pool on the request page
2. We are querying all the skills in a pool just to show them on the card. This does seem like helpful information but it ends up being a lot of extra data. On prod, we are are returning 67 pools with a rough average of 15 skills per pool. That means 1005 extra entities that may or may not even get displayed.

### Published pools

I feel like we should be probably just use the ID and then if we need, we can query a subset of pools to display the matching pools on the request page.

```diff
-   const selectedPool = pools.find((pool) => pool.id === values.pool);

    navigate(paths.request(), {
      state: {
        applicantFilter: {
          ...applicantFilter,
          pools: poolIds,
        },
        allPools: values.allPools,
        candidateCount: values.count,
        selectedPool: values.pool, // We can then use this in a `poolPaginatedQuery` on the request page to get classification
-       selectedClassifications: selectedPool?.classification
-         ? [selectedPool.classification]
-         : applicantFilter?.qualifiedClassifications?.filter(notEmpty),
        selectedClassifications: values?.pool ? undefined : unpackMaybes(applicantFilter?.qualifiedClassifications)
      },
    });

```

### Skills

I can see knowing the skills being helpful, however we are over fetching them it seems. We only care about essential skills so we could just apply that filter. Also, it does seem as though we are fetching more than we need. 

```diff
-   poolSkills {
+  poolSkills(type: PoolSkillType.Essential) { 
      id
-     type {
-       value
-       label {
-         en
-         fr
-       }
-     }
      skill {
        id
        name {
          en
          fr
        }
-       description {
-         en
-         fr
-       }
-       category {
-         value
-         label {
-           en
-           fr
-         }
-       }
-       key
      }
    }

**Comment by tristan-orourke** [comment]
Related [#9483](https://github.com/GCTC-NTGC/gc-digital-talent/issues/9483)

**Comment by tristan-orourke** [comment]
Let's ditch the logic of hiding classifications based on published pools

**Comment by tristan-orourke** [comment]
These are the classifications we should show 

![Image](https://github.com/user-attachments/assets/c30ad358-a59c-445a-8aa5-80d39444fc0d)
