### ISSUE TITLE
🐛 Unstable Story - `ThemeSwitcher`

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#11162]
## 🐛 Bug

I often see false diffs as the theme switcher seems to move.

We tried to fix this in [#10851](https://github.com/GCTC-NTGC/gc-digital-talent/issues/10851) but it's still happening.

## 📸 Screenshot

![image](https://github.com/user-attachments/assets/eb7f08ef-9239-47f3-8a2c-c2001b91a4d1)

## ✅ Acceptance Criteria

- [ ] No false diffs on the ThemeSwitcher story.

**Comment by tristan-orourke** [comment]
Nevermind, the admin-specific layout is going away soon.

**Comment by petertgiles** [comment]
The AdminLayout is going away.  Updated issue to just refer to the ThemeSwitcher story itself.
