### ISSUE TITLE
🦔

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#11216]
## 🦔 Spike

Describe the spike.

## 🕵️ Details

More details, background context, or ideas for how to approach this.

## ❓ Questions to answer

What specific questions need to have been answered for this task to be considered complete?

## 🕙 Timebox

How many days are we expected to spend on this?

**Comment by mnigh** [comment]
@tristan-orourke what is this mysterious emoji-only issue for?

**Comment by tristan-orourke** [comment]
I created this by accident and thought I deleted it 😅
