### ISSUE TITLE
🐛 [UAT] Candidate CSV and Word downloads fail for some candidates

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#11229]
## 🐛 Bug

On UAT, file downloads (CSV and Word docs) are working as intended for some candidates, but not for others.  https://github.com/GCTC-NTGC/gc-digital-talent/releases/tag/v2.28.0

## 🦋 Expected Behaviour

CSV and Word downloads should work regardless of the candidate or candidates selected.

## 🕵️ Details

For some candidates, if you try to download as a CSV, you never get a file-download notification. If you select multiple candidates, it seems like any group which contains one of these poison candidates also fails.

For some candidates, if you try to download profile as a word doc, you get the notification and can download the file, but Word crashes when trying to open it. If you select multiple candidates, it seems like any group which contains one of these poison candidates also fails in the same way.

Interestingly, one candidate might work for the CSV but not for the Word doc.

## 📋 Steps to Reproduce

Reproducing on UAT
1. Log in as a Platform Admin / Request Responder
2. Go to https://uat-talentcloud.tbs-sct.gc.ca/en/admin/pools/122160cd-008d-4693-890e-6e05657a7f41/pool-candidates
3. Try to download candidate 72d70f2a-f701-4060-ab96-affc2c847185 (Rosalie). This should work as a CSV download and a Profile download.
4. Try to download candidate 6d093e10-f109-4b10-9fbb-228dc6ebb8d2 (Peter). This should work as a Profile download but not as a CSV.
5. Try to download candidate 9a3aac90-3671-4494-ac92-843b8a0a7599 (Jean). This should work for neither download.
6. Check multiple rows and explore downloading different combinations of candidates.

## 📸 Screenshot

Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] All candidates can be downloaded as CSV (including on UAT)
- [ ] All candidates, when downloaded as word docs, can be opened successfully in Word.

**Comment by tristan-orourke** [comment]
Errors in jobs may not be logged to the main laravel log. You could see exceptions by manually running the code which runs in the job, in tinker.

**Comment by petertgiles** [comment]
For case #4 (Peter), it's a nul to enum parse error at https://github.com/GCTC-NTGC/gc-digital-talent/blob/111a01f27e0743ee555371964e1043d301885d67/api/app/Generators/PoolCandidateCsvGenerator.php#L170



![Image](https://github.com/user-attachments/assets/49aa336a-4e22-4874-8982-30018e97e402)

**Comment by petertgiles** [comment]
For case 5 (Jean) it is exactly the same error for the CSV as for case 4.

For DOCX file there were no errors logged.  Here's the broken file for the DOCX file.

[candidates_2024-08-14_195310.docx](https://github.com/user-attachments/files/16618277/candidates_2024-08-14_195310.docx)

**Comment by petertgiles** [comment]
I bet the lack of error is the old PHP Error vs. Exception vs. Throwable thing.


![Image](https://github.com/user-attachments/assets/5392ed5a-bd1b-495d-9231-721b904fdc01)

**Comment by esizer** [comment]
> I bet the lack of error is the old PHP Error vs. Exception vs. Throwable thing.

I am very much not a fan of error handling in PHP 😭

**Comment by petertgiles** [comment]
I can't replicate this locally.  I've
1. Built v2.28.0
2. Created a user who is as empty as possible
3. Use the PoolCandidate factory to attach a pool candidate to them
4. Successfully generated a CSV for them

The `yesOrNo` function referenced in the UAT error appears to handle nulls just fine.

**Comment by esizer** [comment]
> I can't replicate this locally. I've
> 
> 1. Built v2.28.0
> 2. Created a user who is as empty as possible
> 3. Use the PoolCandidate factory to attach a pool candidate to them
> 4. Successfully generated a CSV for them
> 
> The `yesOrNo` function referenced in the UAT error appears to handle nulls just fine.

Was this being run from main? The error references `sanitizeEnum` which is actually not being called on that line. I tracked it back and it looks like that error could actually be the education requirement.

https://github.com/GCTC-NTGC/gc-digital-talent/pull/11199/files#diff-4f428e76a1bc04d438c27a8c9527ba310fee65dd9c2330e9d33c58c84f927f24R171

**Comment by petertgiles** [comment]
Shoot, you're right.  Line 170 is actually education requirements in v2.28.0.  Duh!   Thanks for the hint.

![image](https://github.com/user-attachments/assets/6bdf9fc4-c749-42d5-9e06-4513fc423356)

**Comment by petertgiles** [comment]
It looks like Open Office and xmlvalidation agree: The issue with the DOCX file is the (unescaped?) & sign.

![image](https://github.com/user-attachments/assets/6fa1df32-65c1-4151-8f5c-63079db54a63)
