### ISSUE TITLE
🐛 Updates needed on the Personal information page under Equity options - Indigenous identity

### ISSUE THREAD

**Issue by NienkeBr** [GCTC-NTGC/gc-digital-talent#11232]
## 🐛 Bug (+ copy)

Four points

1. On the personal information page, under equity options, if you select Indigenous identity and select both either of the first three options and the 'My community isn't listed' option, there's a warning that asks whether you're sure about selecting 'My community isn't listed' (see screenshot in details). This does not happen when only selecting the the option 'My community isn't listed'. Discussed with Gray and the warning should be removed all together.

GOB: Yes, this warning is very specific to the Apprenticeship Program and doesn't make sense on the main site. Ideally leave the code around though so we can use it in the unlikely event IAP decides to turn on their application process.

2. On the French Personal information page, under equity options - indigenous identity, the communities aren't listed alphabetically even though the description says so. We would like to change the order on the French page so it's also true here.

GOB: @mnigh rightly pointed out that the ordering was sensitive here. However, the alphabetical listing was how we felt we could best address the concerns. So it's important that we follow through with it. Let's get those sorted alphabetically in both official languages.

3. Also copy issue in the same section: We should move to using inclusive language for French and it's better for readability/accessibility to use full doublets (e.g. les étudiantes et étudiants) rather than abbreviated doublets (e.g. les étudiant(e)s). In this case that means, please change "Je suis métis(se)" to "Je suis métisse ou métis".  

## 🦋 Expected Behaviour

1. Warning should not pop up, no matter which combination of options you select.
2. Communities are ordered alphabetically on the French page as well: Inuk, Métis, Premières Nations

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

URL: https://talent.canada.ca/en/applicant/personal-information

## 📋 Steps to Reproduce

1. Go to add an indigenous community to you profile. Select any or all of the communities listed (First nations, Inuk, Metis) AND the option 'My community isn't listed'

2. Go to add an indigenous community to your profile on the French side.

## 📸 Screenshot

Add a screenshot (if possible).
1. 
![image](https://github.com/user-attachments/assets/52c07dfb-c09b-4d66-a606-faa0e48f4bff)

2. 
![image](https://github.com/user-attachments/assets/1fe7b425-a5aa-44cb-a163-aeb04b3f3fc9)

3.
![image](https://github.com/user-attachments/assets/ee019f13-5f66-481f-8731-04c26daf98aa)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] The warning doesn't show anymore, no matter which combination of options you select.
- [ ] The French text for Métis reads "Je suis métisse ou métis"
- [ ] The French communities are listed alphabetically (Inuk, Métis, Premières Nations)

**Comment by gobyrne** [comment]
@mnigh any thoughts on how we could alphabetically sort the options in both Official Languages?

**Comment by mnigh** [comment]
> @mnigh any thoughts on how we could alphabetically sort the options in both Official Languages?

We would have to render each one based on the language. Not a great pattern.
