### ISSUE TITLE
✨ Error discriminator for VPN blocking

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#11287]
## ✨ Feature

Right now we have a custom checker in Laratrust that will fail a permission check if the incoming request requires an elevated permission but is not using the protected endpoint.  Is there some way we can mark the error response so that the frontend knows that the permission failure was because of the VPN checker and provide a more specific error message?

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## ✅ Acceptance Criteria

- [ ] The error message from a failed VPN check can be distinguished from a regular permission check failure

**Comment by gobyrne** [comment]
Peter to pick this up at some point and make a call about where to take it.

**Comment by tristan-orourke** [comment]
It's not an _exact_ duplicate, but closing https://github.com/GCTC-NTGC/gc-digital-talent/issues/12071 will provide a workaround we can use instead of this, which we're no closer to figuring out.
