### ISSUE TITLE
🐛 Incorrect French string for Success message displayed after unlinking an experience to a skill

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#11299]
## 🐛 Bug

The French string for `Success message displayed after unlinking an experience to a skill` is the same as the French string for `Success message displayed after linking an experience to a skill`, _Lien établi avec l’expérience!_.

## 🦋 Expected Behaviour

The French string for `Success message displayed after unlinking an experience to a skill` should not be the same as the French string for `Success message displayed after linking an experience to a skill`.

## 📋 Steps to Reproduce

1. Navigate to https://talent.canada.ca/en/applicant/skills
2. Add a new skill
3. Navigate to that skill
4. Switch to French
5. Link an experience
6. Observe toast message _Lien établi avec l’expérience!_
7. Remove this experience
8. Observe toast message _Lien établi avec l’expérience!_

## 🎥 Screen recording

https://github.com/user-attachments/assets/c6c59004-631e-48ab-9195-b8029f032a40

## 🙋‍♀️ Proposed Solution

Get a correct French translation.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/e0c94e9668443477e41e0fc0a716e57f8061505b/apps/web/src/components/ExperienceSkillFormDialog/ExperienceSkillForm.tsx#L99-L104

https://github.com/GCTC-NTGC/gc-digital-talent/blob/e0c94e9668443477e41e0fc0a716e57f8061505b/apps/web/src/lang/fr.json#L3250-L3253

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] French string for `FpDMGu` **Success message displayed after unlinking an experience to a skill** is _Lien avec l’expérience supprimé!_

**Comment by NienkeBr** [comment]
@mnigh French text: "Lien avec l’expérience supprimé!"
