### ISSUE TITLE
🔤 Add education requirement for CR classification

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#11311]
## 🔤 Copy

New education requirement for CR classification. This is so ATIP can post a CR competition in the fall.

The requirement can follow the same pattern as IT with Applied work experience, but the Education requirement is 2 years of secondary school instead of 2 years post-secondary.

### English
**Applied work experience**
Combination of experience, training or education.

**Two years of secondary school**
Successful completion of two years of secondary school.

### French
**Exigences en matière de travail pratique**
Un agencement d’études, de formation ou d’expérience.

**Deux années d’études secondaires**
La réussite de deux années d’études secondaires.

### 🧑‍🎨 Designer

@NienkeBr 

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the copy has been added or updated appropriately.

- [ ] Job process created with CR classification shows the correct (new) education requirement
- [ ] Add CR-04 classification to seeder, using data from prod
- [ ] Education requirement step of the application shows the correct options for this classification. See comment below (from Nienke)

**Comment by gobyrne** [comment]
@NienkeBr can you double check the French? I copy/pasted it all from either our site or the the qualification standards, so high probability that it's fine...

**Comment by NienkeBr** [comment]
Just a comment to make sure that this will also need to be reflected in the application process under the education requirement step. 
English:
> [  ] **I meet the applied work experience option**
>       Combination of experience, training or education.
> [  ] **I meet the two years of secondary school option**
>       Successful completion of two years of secondary school.

French:

> [  ] **Ma situation concorde avec l’option d’expérience de travail appliquée**
> Un agencement d’études, de formation ou d’expérience.
> [  ] **Ma situation correspond à l’option de deux années d’études secondaires.**
> La réussite de deux années d’études secondaires.

![image](https://github.com/user-attachments/assets/5e4a3066-7913-4896-8f6f-2bc6fa68e8c6)

**Comment by gobyrne** [comment]
Thank you for catching that @NienkeBr !!
