### ISSUE TITLE
♻️ Upgrade `laravel-scout-postgres-tsvector` plugin to work with Laravel 11

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#11310]
## ♻️ Refactor

The `laravel-scout-postgres-tsvector` plugin [being used](https://github.com/devNoiseConsulting/laravel-scout-postgres-tsvector) in the gc-digital-talent repo is not compatible with Laravel 11.

## 🕵️ Details

There is a [fork](https://github.com/mobilozophy/laravel-scout-postgres-tsvector) of the aforementioned repo that [allows for the use of Laravel 11](https://github.com/devNoiseConsulting/laravel-scout-postgres-tsvector/compare/master...mobilozophy:laravel-scout-postgres-tsvector:master). 

Publish the new repo on https://packagist.org (where composer pulls from)

## ❓ Question

Q: Do we reference the `mobilozophy/laravel-scout-postgres-tsvector` repo or create our own fork?
Tristan - Let's create our own fork

## ✅ Acceptance Criteria

- [ ] use `laravel-scout-postgres-tsvector` plugin that works with Laravel 11

**Comment by brindasasi** [comment]
I've never done this before but gonna try since its top of the list for so long  :) 
I'm guessing this would involve forking under our repo and update the composer to support Laravel 11. 
Let me try 😅
