### ISSUE TITLE
✨ Search request history on Manager dashboard

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#11346]
## ✨ Feature

The manager dashboard needs to be able to load a list of the manager's search requests and open a preview dialog.

## 🎨 Design

@JoshBeveridge 

[Manager dashboard page](https://www.figma.com/design/oZhQe9ahidHFfaiqgREvxa/Dashboard-(All-users)?node-id=1010-18678&t=vrILuDBzHFB3b4Gq-4)

[Dialog view with mobile + dark/light mode views](https://www.figma.com/design/hPPZeQWidbmcapHl0IKhD8/Talent-requests-(Managers)?node-id=1-2&node-type=CANVAS&t=BgoJf1374u5gLEEf-0)

## 📸 Screenshot

![image](https://github.com/user-attachments/assets/37ebf864-c145-4955-9672-4d4c3fb5115b)

![image](https://github.com/user-attachments/assets/9f1c66d4-cf04-47f6-ab75-ceedade91980)

## 🙋‍♀️ Proposed Implementation

This will require adding a method of getting "my requests" from the API. Maybe a "talentRequests" or "talentRequestHistory" field on the User object.

```graphql
// Schema.graphql
type User {
.
.
.
talentRequest: PoolCandidateSearchRequest!
}
```
```php
// PoolCandidateSearchResult.php
public function getCandidateCountAttribute()
{
    $applicantFilter = $this->applicantFilter();
    $candidateCount = CountPoolCandidatesByPool::candidateCount($applicantFilter);
    return $candidateCount;
}
```

For the sorting, that can be done on the front-end similar to ExperienceSortAndFilter.tsx

### Status badge table
| Enum               | EN                | FR |
|--------------------|-------------------|----|
| NEW                | Submitted         |    |
| IN_PROGRESS        | Under review      |    |
| WAITING            | Awaiting response |    |
| DONE               | Complete          |    |
| DONE_NO_CANDIDATES | Complete          |    |
| NOT_COMPLIANT      | Complete                  |    |

## ✅ Acceptance Criteria

- [ ] Schema is updated to allow a manager to requests their search requests with status, potential match count, and opening date
- [ ] API offers a way for a candidate to load their history of talent request. Since this request can be expensive on the server, let's separate it into two. First request for the talent requests without the candidate count. Second, another request for the candidate count.
- [ ] Create a sorting feature using similar method as [ExperienceSortAndFilter.tsx ](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/apps/web/src/components/ExperienceSortAndFilter/ExperienceSortAndFilter.tsx#L1-L136)
- [ ] permissions ensure a user (even an admin) cannot view another user's request history
- [ ] On page load, a list of the user's search requests is queried from the API and displayed
- [ ] clicking the preview button opens the preview dialog
- [ ] TODO: clicking the "view request" button in the preview does what? A
       ANSWER: Omit the "View request" button in the footer. There should only be the "Close" button.

## 🛑 Blockers

```[tasklist]
### Blocked By
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/10785
```

**Comment by petertgiles** [comment]
@JoshBeveridge It looks like we don't have a null state for the "Your talent searches" box.  Do we need special handling or is just having the component end at the "When you submit a request..." message OK?

**Comment by petertgiles** [comment]
@JoshBeveridge Could you please help me out with the supervisory status field?

In Figma the example is “No, this will not be a supervisory position.”.  Is the other option “Yes, this will be a supervisory position.” ?

I also want to note that these sentences are future tense while the box the user actually clicked is present tense.
"Yes, this is a supervisory position".

**Comment by petertgiles** [comment]
We could also just show the fields used in the admin interface:
'Individual contributor'
'Team lead'

**Comment by tristan-orourke** [comment]
@petertgiles Adding the view-own-searchRequest permission and giving it to BaseUser looks good. 

Looking at the criteria "permissions ensure a user (even an admin) cannot view another user's request history" again... I don't actually feel strongly about this, it could even be removed as a strict criteria. We may eventually allow admins to filter requests by user. But if request history is accessed through its own query, then I would implement it so it returns the history of the current logged in user, making it impossible to get someone else's. If on the other hand, we're querying a searchRequests field on the User type, then it might be possible for platfrom admins to see it.
