### ISSUE TITLE
✨ Site-wide hero update

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#11344]
## ✨ Feature

Updates to the Hero component. All variants now allow for breadcrumbs and non-tab variants optionally allow for body overlap of the hero.

The pattern that we're going for:
1. Pages that are single forms have overlap and dashboards also have overlap
2. Tabs are reserved for page sets with multiple chunks of data
3. All other pages have the standard header

Out of scope:
Update to the mobile tab component

### Desktop options
1. Tabs, no tabs, or no tabs with overlap
2. Centered or not
3. Image or not

**Which makes for all these variants :**

1. Tabs, no image
3. Tabs, with image
5. Tabs, no image, Centered
6. Tabs, with image, Centered
7. No tabs, no image
8. No tabs, with image
9. No tabs, no image, Overlap
10. No tabs, with image, Overlap
11. No tabs, no image, Centered
12. No tabs, with image, Centered
13. No tabs, no image, Centered, Overlap
14. No tabs, with image, Centered, Overlap

### Mobile options
**Mobile**
1. Tabs or no
2. Image or no
3. Always centered

**So only 4 variants for mobile**

1. Tabs, no image
2. Tabs, with image (not in design file, but please dev it)
5. No tabs, no image
6. No tabs, with image (not in design file, but please dev it)

## 🎨 Design

[Hero component figma
](https://www.figma.com/design/guHeIIh8dqFVCks310Wv0G/Component-library?node-id=1698-21757&node-type=frame&t=L2tOxu0diimB9UaR-0)

@JoshBeveridge 

Here are screenshots, just adding it because Figma was aligning the tabs incorrectly sometimes... if it looks weird, check back here or ask Josh.

<details><summary>Desktop</summary>

![image](https://github.com/user-attachments/assets/d46e717b-c95e-4c87-a97e-36193d19ac9d)
![image](https://github.com/user-attachments/assets/9df53d67-a882-43b1-8164-4ab3fb8448f0)

</details> 
<details><summary>Mobile</summary>

![image](https://github.com/user-attachments/assets/cd8f650d-bc55-4b2b-8303-c7568825bc14)

</details> 

## Suggested implementation

- [ ] Create a new hero component
- [ ] Deprecate the old one

## ✅ Acceptance Criteria

- [ ] Desktop variants
  - [ ] Tabs, no tabs, or no tabs with overlap
  - [ ] Centered or not
  - [ ] Image or not
  - [ ] Buttons or not

- [ ] Mobile variants
  - [ ] Tabs, no tabs
  - [ ] Image or not
  - [ ] Buttons or not

- [ ] breadcrumb placement updated

- [ ] Storybook story
- [ ] Design review @JoshBeveridge

**Comment by vd1992** [comment]
Overlap comparison

![image](https://github.com/user-attachments/assets/68871875-54b9-4495-923d-82c1186bf50a)
