### ISSUE TITLE
♻️ Require await eslint rule

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#11377]
## ♻️ Debt/Refactor

Enable and fix `require-await`

## 🕵️ Details

https://typescript-eslint.io/rules/require-await/

## 🙋‍♀️ Proposed Solution

Remove the line disabling this rule and fix any errors associated with it.

## ✅ Acceptance Criteria

- [ ] `require-await` is enabled
- [ ] All errors fixed

**Comment by tristan-orourke** [comment]
Seems fine to me, but I don't feel strongly.
