### ISSUE TITLE
♻️ Only throw error

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#11378]
## ♻️ Debt/Refactor

Enable and fix the `only-throw-error` eslint rule

## 🕵️ Details

This one could be trickey since we are using the response to in a weird way since we don't have data loaders working in `react-router`.

REF: https://typescript-eslint.io/rules/only-throw-error

## 🙋‍♀️ Proposed Solution

I think there are few options here:

1. See if returning the response works
2. Extend the `Error` class in javascript to support status codes so we can render the appropriate error
3. Embed status code in the error message and try and parse it in our boundary

## ✅ Acceptance Criteria

- [ ] `only-throw-error` rule is enabled
- [ ] All errors fixed

**Comment by tristan-orourke** [comment]
I feel like the "proper" way to do this would be extend Error with a custom class, your solution number 2.
