### ISSUE TITLE
♻️ Prefer nullish coalescing 

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#11376]
## ♻️ Debt/Refactor

Enable and fix the `prefer-nullish-coalescing` rule.

## 🕵️ Details

https://typescript-eslint.io/rules/prefer-nullish-coalescing/

## 🙋‍♀️ Proposed Solution

Remove the line disabling this rule and fix any errors associated with it.

## ✅ Acceptance Criteria

- [ ] `prefer-nullish-coalescing` is not disabled
- [ ] All errors fixed

**Comment by tristan-orourke** [comment]
I like this rule. I've already adopted and recommend this pattern.
