### ISSUE TITLE
🐛 During a talent search, the message says there are no candidates

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#11393]
## 🐛 Bug

During a search, the message at the bottom of the page says there are no candidates.

## 📋 Steps to Reproduce

1. Slow down the search (sleep in Laravel middleware, seed lots of users, throttle browser, etc.)
2. Run a talent search

## 📸 Screenshot

![image](https://github.com/user-attachments/assets/af2fd588-474a-4fa4-9256-07540a09b8ec)

## 🙋‍♀️ Proposed Solution

The result copy should probably be hidden while the search is ongoing.  
Maybe the "We might be able to help" card, too?
Maybe the "Submit an empty request" copy under the spinner, too?

## ✅ Acceptance Criteria

- [ ] Search page does not say 0 results while searching
- [ ] Hide the "We may be able to help" card while searching
- [ ] Hide the "Submit an empty request" copy under the spinner, too
- [ ] design review

**Comment by petertgiles** [comment]
@JoshBeveridge could you please provide some guidance on how this can be fixed?

**Comment by JoshBeveridge** [comment]
@petertgiles IMO the entire block below the divider should be hidden with a spinner until results are processed.
