### ISSUE TITLE
✨ Backend work for job poster templates

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#11429]
## ✨ Feature

Create a new data model to store job poster template data and set up the CRUD APIs.

## 🕵️ Details

All job poster template data should be **readable** publicly.

**Create, update, delete** should be restricted to Platform Admin only.

I think this is similar to how skills library is done.

Job Poster Templates have the following fields:

1. Reference number (string)
2. Work stream (one of our pre-defined workstreams)
3. Classification-Level (also from our DB)
4. Supervisory status (NEW - probably an enum with two options: "Individual contributor" or "Supervisor")
5. Title - EN(string)
6. Title - FR 
7. Tasks - EN (string - will be used in a text box that allows for formatting. **We have provided text, but each new line should be displayed as a bulleted item on the page. I will describe this in the data upload issue #11435 )**
8. Tasks - FR
9. Keywords - EN (list - will be used to support searching)
10. Keywords - FR
11. Description - EN (string - might be used in a text box that allows for formatting)
12. Description - FR
13. Work description URL - EN
14. Work description URL - FR
15. List of skills (There will be a many to many relationship between skills and job poster templates)
16. Skills on this list can also have a **Level (1-4)** which relates to the skill levels that we have (will be described in #11435 ) and are either (**Recommended** or **Additional**)
17. Essential technical skills notes (string)
18. Essential behavioural skills notes (string)
19. Asset technical skills notes (string)

## 🎨 Design
https://www.figma.com/design/kTvZVVsdVziRqxanyUgSKZ/Job-template-library?node-id=186-43566&node-type=CANVAS&t=1DTjNyTPhMZHtEtL-0

Here is an Excel file containing example data (some skills still missing the skill key):
New version 2024-09-05
[Job template - Platform Itegration.xlsx](https://github.com/user-attachments/files/16898551/Job.template.-.Platform.Itegration.xlsx)

## ✅ Acceptance Criteria

- [ ] New data model in place
- [ ] Database things (APIs?) in place
- [ ] Permissions, policy in place for new APIs
- [ ] Testing (permissions)

**Comment by tristan-orourke** [comment]
Supervisory Status - is every template going to be either/or, or can some templates apply to suppervisory AND non positions?
Keywords should probably be stored as a list, like we do for Skill keywords.
To associate Skills with Levels, we can create a new pivot similar to PoolSkill.
