### ISSUE TITLE
✨ Initial data upload for Job poster templates

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#11435]
## ✨ Feature

We are creating a library of job poster templates. Now we need to upload a first set of them.

## 🕵️ Details

Add all the data in the excel file to the DB

[Job template - Platform Itegration 2024-09-12.xlsx](https://github.com/user-attachments/files/16981603/Job.template.-.Platform.Itegration.2024-09-12.xlsx)

The data model should be in place from #11429. Now we need to match the column names from the excel file to the data fields in the model and upload.

Some details though:
**Key tasks - examples**
- In the future we intend to have the key task field be populated from a rich text input (that allows for formatting). The intent is also that the "tasks" to appear in a bullet list. In the excel file, each task is separated by a line break. Please ensure the data supports this "bulleted list" formatting for #11434

**Skill levels**
In the excel file we have skill levels identified by number. This is the mapping to the skill levels that we have defined:

Technical skill:
1. EN: `Entry-level` FR: `Niveau d’entrée`
2. EN: `Intermediate ` FR: `Intermédiaire`
3. EN: `Advanced`  FR: `Avancé`
4. EN: `Lead` FR: `Principal`

Behavioural skill:
1. EN: `In early development` FR: `À un stade initial de développement`
2. EN: `Moderately developed` FR: `Modérément développée`
3. EN: `Strongly developed`  FR: `Fortement développée`
4. EN: `Deep-level mastery` FR: `Maîtrise approfondie`

## 🎨 Design

Jamie produced the dataset. @gobyrne can also answer questions.

## Reccomended implementation
Convert excel data to json, set up a seeder like Skill and Skill Family seeder.

## ✅ Acceptance Criteria

- [ ] Seeder which inserts real data (sourced initially from provided excel file)
- [ ] Seeder cam run in production or UAT
- [ ] Template seeder runs in local seeder and CI seeder

## 🛑 Blockers

```[tasklist]
### Blocked By
- [ ] #11429
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/11525
```

**Comment by gobyrne** [comment]
We're avoiding sharing the excel file for now since Jamie is still adding to it.

**Comment by tristan-orourke** [comment]
We will upload templates from excel files only as a one-time thing (or maybe couple times). We don't need a really robust process. Converting the excel data to json or sql by whatever means is probably sufficient.

We did this before for skills and skill families. We have a seeder which can read data from json files.

**Comment by vd1992** [comment]
@tristan-orourke @gobyrne 

Question
There is a "Job poster template key" column, but no such thing was added in https://github.com/GCTC-NTGC/gc-digital-talent/issues/11429 . Should I just ignore it?

**Comment by vd1992** [comment]
Unless my Excel is somehow glitching up, I don't see any skills in the spreadsheet?

**Comment by tristan-orourke** [comment]
I think we can ignore the key column. I'll let Jamie know its not necessary.
