### ISSUE TITLE
🐛 CSV candidates search download error for the recruitment team

### ISSUE THREAD

**Issue by marc-donofrio** [GCTC-NTGC/gc-digital-talent#11442]
## 🐛 Bug

I’ve been trying to download a CSV of 100 candidates since yesterday and I keep getting an error.
 
From candidate search I apply the following filters:
 
    Qualified available
    Placed term
    Placed indeterminate
    Placed casual
    Offer in progress
    Digital Community

About 726 candidates come up, I select view 100 at a time. I’ve been able to download every page of the search results except page 5. When I select all and hit download CSV I get an error notification. 

## 🦋 Expected Behaviour

CSV file downloaded

## 🕵️ Details

Will need to comb through Azure logs, find the error, and decide the solution appropriately. Could be an unexpected field nulled, could be a broken column value

May be related to https://github.com/GCTC-NTGC/gc-digital-talent/issues/11443 ? Same user at play?

## ✅ Acceptance Criteria

- [ ] Problem identified and solution implemented

**Comment by esizer** [comment]
Do we know if  this was the same as https://github.com/GCTC-NTGC/gc-digital-talent/issues/11443 ?

**Comment by petertgiles** [comment]
Not yet...
@marc-donofrio could you please send me the details for reproduction?  I think I would just need the pool ID they were browsing.  The URL they were on when it crashed would work.

**Comment by brindasasi** [comment]
I tried downloading 100s from all candidates with said filters in prod. It looks fine. Need the actual pool id for further investigation.

**Comment by marc-donofrio** [comment]
I will send you the specific error through teams as it includes the user email.
