### ISSUE TITLE
🐛 Submitted application not showing for candidate

### ISSUE THREAD

**Issue by marc-donofrio** [GCTC-NTGC/gc-digital-talent#11441]
## 🐛 Bug

The candidate states that they submitted an application but it is not showing now that the process is closed.

## 🦋 Expected Behaviour

The candidate and the support team should see the application in their account.

## 🕵️ Details

User email: please ask Marc on MS Teams or email.
Process: https://talent.canada.ca/en/browse/pools/2c0ce3e8-65e3-4d48-b142-dda93cbef231

## 🙋‍♀️ Proposed Solution

Can you verify if they submitted an application or was it started but not submitted. (Application in progress or completed)

## ✅ Acceptance Criteria

- [ ] Check Application Insights as well as error logs and Activity Log to see if anything of use/concern is there

**Comment by brindasasi** [comment]
This is the final activity log for the candidate and I din't see the Review & Submit step as the final step.
also note that  pool closed at 2024-09-01T09:06:59 and this update was at 2024-09-01T09:06:45 

{
    "attributes": {
        "updated_at": "2024-09-01T09:06:45.000000Z",
        "submitted_steps": [
            "WELCOME",
            "REVIEW_YOUR_PROFILE",
            "REVIEW_YOUR_RESUME",
            "EDUCATION_REQUIREMENTS",
            "SKILL_REQUIREMENTS"
        ]
    },
    "old": {
        "updated_at": "2024-09-01T08:48:04.000000Z",
        "submitted_steps": [
            "WELCOME",
            "REVIEW_YOUR_PROFILE",
            "REVIEW_YOUR_RESUME",
            "EDUCATION_REQUIREMENTS"
        ]
    }
}

I will dig further for the errors but most likely the pool closed before the submission

**Comment by brindasasi** [comment]
The pool closed at Aug.31st and system would accept upto Sep. 1 2:59 AM  EST which was transparent during the application process.
![Image](https://github.com/user-attachments/assets/888dab71-c898-4c87-8e01-c6c31eb0459e)

Applicant submission event happened around Sep.1 5:07 AM EST 
 ![Image](https://github.com/user-attachments/assets/70754177-7742-473b-8335-e1f3513a76c0)

They were able to update their draft application and proceed thru until submission page.

Submit wasn't successful though. We provided with an error message
![Image](https://github.com/user-attachments/assets/c0b3148a-76ea-41df-bdb3-7a47d000c1ea)
![Image](https://github.com/user-attachments/assets/8f12a041-610e-4ddb-b8bf-5ab244e1320c)

**Comment by brindasasi** [comment]
Applicant probably proceeded with the expired application  thru bookmarked url which is still an issue to fix. Will create a sep bug for that.

**Comment by brindasasi** [comment]
closing as this investigation has been reported back to help desk.
