### ISSUE TITLE
🐛 Download of users application error

### ISSUE THREAD

**Issue by marc-donofrio** [GCTC-NTGC/gc-digital-talent#11443]
## 🐛 Bug

When downloading a specific user, we get an error message.

## 🦋 Expected Behaviour

A download of the application.

## 🕵️ Details

Will need to comb through Azure logs, find the error, and decide the solution appropriately. Could be an unexpected field nulled, could be a broken column value

May be causing https://github.com/GCTC-NTGC/gc-digital-talent/issues/11442 ? Same user at play possibly?

user email: Please ask Marc via MS Teams or email.

## 📸 Screenshot
![image](https://github.com/user-attachments/assets/089d27b4-5f32-47d6-8d91-ef749f57a4d1)

## ✅ Acceptance Criteria

- [ ]  Problem identified and solution implemented

**Comment by marc-donofrio** [comment]
I just attempted downloading the user application, about 9:36. Any errors?

**Comment by tristan-orourke** [comment]
Suggestion: log into SSH to the server, use laravel tinker to trigger document generation for the problem user, and you'll see the error message which causes it to fail.

**Comment by petertgiles** [comment]
Stack trace of error:
   TypeError  array_is_list(): Argument #1 ($array) must be of type array, string given.
--
 0:  () at vendor/laravel/framework/src/Illuminate/Collections/Arr.php:444
 1:  array_is_list() at vendor/laravel/framework/src/Illuminate/Collections/Arr.php:444
 2:  Illuminate\Support\Arr::isList() at app/Traits/HydratesSnapshot.php:59
 3:  App\Models\Experience::hydrateField() at app/Traits/HydratesSnapshot.php:35
 4:  App\Models\Experience::hydrateFields() at app/Models/Experience.php:302
 5:  App\Models\Experience::hydrateSnapshot() at app/Generators/ApplicationDocGenerator.php:44
 6:  App\Generators\ApplicationDocGenerator->App\Generators\{closure}() at vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php:53
 7:  Illuminate\Database\Eloquent\Builder->chunk() at app/Generators/ApplicationDocGenerator.php:39
