### ISSUE TITLE
🔤 Quotations missing around within "More information" expandable? 

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#11467]
Not relevant to the PR itself, but man does that second one not having quotations stick out for me every time I look at it

![image](https://github.com/user-attachments/assets/85ff3af5-36c0-488b-841c-e3e6fa437fe0)

_Originally posted by @vd1992 in https://github.com/GCTC-NTGC/gc-digital-talent/issues/11446#issuecomment-2332446918_
            
## Proposed solution

Add quotes?

## Acceptance criteria

If quotes to be added, quotes added

**Comment by petertgiles** [comment]
@NienkeBr Could you please check on how this is supposed to look to finish out this ticket?

**Comment by NienkeBr** [comment]
I'd very much like for the quotes to be removed. I've actually also included this in the #9418 ticket about application process copy.

**Comment by petertgiles** [comment]
Thanks!  This one is superseded by #9418 then.
