### ISSUE TITLE
✨ Add new Hero to  Admin / Announcements page

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#11486]
## ✨ Feature

Update the announcements page to the new Admin styling (it doesn't follow the pattern though) by applying the new Header component.

## 🎨 Design
[Figma file ](https://www.figma.com/design/jCYrMOPvmtrPyN1SnS4Mab/Admin---Announcements?node-id=14001-10780&t=8DyPNwDsg25esQoO-1)by @Jerryescandon 

## ✅ Acceptance Criteria

- [x] Nevermind for the date picker stuff

- [x] Announcements page (/admin/settings/announcements) uses the new hero component
  - [x] Header  (background, H1 & breadcrumb)
  - [x] H2 and content styling
  
- [x] Design Review by @Jerryescandon 

## Blockers
```[tasklist]
### Blocked by
- [ ] #11344 
```

**Comment by petertgiles** [comment]
Refinement note: Devs feel like having a time component for this function is important.  Having just a day is not enough.

**Comment by Jerryescandon** [comment]
Updated Figma file to include "Hour" and "Minute" fields, I'm guessing we will also need to add some validation:
- Hour field should be between 0 and 23, 
- Minute should be a number between 0 and 59
- I think we should always assume seconds to "00" for simplicity

![image](https://github.com/user-attachments/assets/b2ebfaba-eed0-49b1-9ecd-9855728606ba)
