### ISSUE TITLE
✨ Candy striping for accordion groups

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#11497]
## ✨ Feature

Accordions in "card" mode (as opposed to `AccordionMode="simple"`) should include candy stripping (alternating colored rows). 

~Also, accordion groups should include an optional footer section, which appears below the accordion items but is part of the same overall "card".~

## 🎨 Design

@JoshBeveridge  

example from Job Template design: https://www.figma.com/design/kTvZVVsdVziRqxanyUgSKZ/Job-template-library?node-id=355-21116&node-type=FRAME&t=pnKV4IMENftZID59-0

Component library documentation: https://www.figma.com/design/guHeIIh8dqFVCks310Wv0G/Component-library?node-id=3220-162654&node-type=frame&t=1BoTSwoNVIYrFbNq-0

## 📸 Screenshot

![Image](https://github.com/user-attachments/assets/751b3739-b69e-4a79-bb81-aab3ae4ef853)

## ✅ Acceptance Criteria

- [ ] Add striping to "card" mode accordion groups
- [ ] ~Add footer to accordion on job template page (make it part of the accordion group component)~
- [ ] ~Footer should always display with the same background color (not affected by candy striping)~

- [ ] Design review @JoshBeveridge

**Comment by tristan-orourke** [comment]
@tristan-orourke TODO: extract footer task into own ticket
