### ISSUE TITLE
✨ Increase word count for application fields when navigating in French 

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#11496]
## ✨ Feature

Increase the word counts in French during the application. This is because similar texts in French tends to have more words than in English. To compensate we want to allow people completing the forms in French to have a higher word Ratio should be 5:7.

## 🕵️ Details

Everywhere during the application where we have a word count, we want to allow for a higher count in French.

**It is understood that we cannot prevent people from writing in English on the French page and that this will not be easily detectable. Still, we would like to proceed.**

This will impact 3 fields:
1. Additional details (when adding experiences) **200 words in English : 280 words in French**
2. Skill justification (when connecting an experience to a skill) **160 words in English : 224 words in French**
3. Screening questions (and "general questions", which are open ended questions that are not used for screening) **200 words in English : 280 words in French**

## 📸 Screenshot

**Experience "additional details":**
![image](https://github.com/user-attachments/assets/1e6643de-cbcc-4ebe-9717-9bfc51e2d26f)

**Connect a career timeline experience (skill justification)**
![image](https://github.com/user-attachments/assets/7c89847c-0365-4b71-9b12-6789690d1c3d)

** Additional Questions (Screening and General) **
![image](https://github.com/user-attachments/assets/d32dacf8-a6c8-4a38-8bfc-65aadffc3bf8)

## ✅ Acceptance Criteria

- [ ] Different word limits when viewing Application pages in French 5:7 ratio

**Comment by tristan-orourke** [comment]
Do we have a reusable component for textboxes with a wordcount? Could we build this 5:7 rule into the component logic itself?
