### ISSUE TITLE
🐛 PROD - Application snapshots are not downloadable in old pools

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#11537]
## 🐛 Bug

When trying to download any application from some of the pools we get this error on PROD 
![Image](https://github.com/user-attachments/assets/a4f29409-490e-49db-ab1e-ce371e83f770)
**Impacted pools** 
IT-02/IT-03/IT-04 Enterprise Architecture analyst 
IT-01/IT-02/IT-04 Infrastructure Operations 

## 🦋 Expected Behaviour

All applications should be downloadable without any issue 

## 🕵️ Details
**What we know** 
- Can be reproduced with multiple pools on prod 
- Only be reproduced on certain pools
- Can be reproduced with any application on those particular pools
- All the pools I've reproduced did NOT have a process number or assessment plan  ( relates to older pools) 

Mutation : DownloadApplicationDoc
Actual Error : `[2024-09-16 18:12:41] production.ERROR: array_is_list(): Argument #1 ($array) must be of type array, string given {"userId":"64da9b38-f0df-4e0f-a1ea-47db056adb8f","exception":"[object] (TypeError(code: 0): array_is_list(): Argument #1 ($array) must be of type array, string given at /home/site/wwwroot/api/vendor/laravel/framework/src/Illuminate/Collections/Arr.php:444)
`
Stacktrace: 
![Image](https://github.com/user-attachments/assets/a240221b-ec42-49d8-96af-df4cf610bf1c)

![Image](https://github.com/user-attachments/assets/1a0911e6-dcc0-49e8-b9c3-a7803c4f4589)

## 📋 Steps to Reproduce

If it helps , since the log says Personal Experience I captured in one of the personal exp. for the application 

```
"title": "Coding Experience",
            "skills": [],
            "details": "",
            "endDate": null,
            "startDate": "1983-01-06T00:00:00.000000Z",
            "__typename": "PersonalExperience",
            "description": "Though I am not a formally trained coder, I do have experience from it being one of my hobbies."
```

Can anyone investigate it with the current format? 

## ✅ Acceptance Criteria

All applications should be downloadable in old pools as well as new pools.

**Comment by esizer** [comment]
@petertgiles Do you think maybe this is [the same issue you solved](https://github.com/GCTC-NTGC/gc-digital-talent/pull/11474) recently and it has not been released yet? 🤔

**Comment by petertgiles** [comment]
@esizer I would say it's a very good chance, yeah.  The error message looks the same.

**Comment by brindasasi** [comment]
It didn't help .. this time I get same error in CommunityExperience in prod. But I think the issue with the field 'details' from the base class Experience
