### ISSUE TITLE
🐛 Some pages fail to render in Vite watch mode

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#11578]
## 🐛 Bug

Some pages on the site fail to render with a "We have encountered an unknown error while processing your request." error when using Vite watch mode.  However, if the site is built with a regular dev or prod build then they are fine.

## 🦋 Expected Behaviour

Pages in watch mode should behave exactly the same as pages in a regular build.

## 🕵️ Details

It seems related to the process variable. The second you introduce that in watch mode it fails.
While it does not fail on build...the process is not working.
![image](https://github.com/user-attachments/assets/68edbc96-8b67-4634-ab1b-453a8cf489c9)

## 📋 Steps to Reproduce

> [!Note]
This issue was found in PR #11577.  These steps require that PR to be merged.

1. Build the app in watch mode
2. Start working through an application
3. Add an experience (http://localhost:3000/en/applications/:applicationId/career-timeline/add)

## 📸 Screenshot

![image](https://github.com/user-attachments/assets/83aeb283-2c05-4226-ae17-4aa1732a4a4f)

## 🙋‍♀️ Proposed Solution

![image](https://github.com/user-attachments/assets/2752dc13-d13a-4741-bf10-88a4f04b1fca)

## ✅ Acceptance Criteria

- [ ] Adding an experience to the career timeline works in a watch mode build
- [ ] Any changes to process.env work in Azure

**Comment by esizer** [comment]
> [!NOTE]
> This will require prefixing the env vars with `VITE_` to expose them to the client. If we have these in azure, they will need to updated there as well.
