### ISSUE TITLE
🐛 Prod logs - Null email address

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#11573]
## 🐛 Bug

In the prod logs I'm seeing some errors like this:
```
App\Notifications\Messages\GcNotifyEmailMessage::__construct(): Argument #2 ($emailAddress) must be of type string, null given, called in /home/site/wwwroot/api/app/Notifications/VerifyEmail.php on line 52 {"userId":"d4b21821-2a02-4acd-9934-36c2b8d32f74","exception":"[object] (TypeError(code: 0): App\\Notifications\\Messages\\GcNotifyEmailMessage::__construct(): Argument #2 ($emailAddress) must be of type string, null given, called in /home/site/wwwroot/api/app/Notifications/VerifyEmail.php on line 52 at /home/site/wwwroot/api/app/Notifications/Messages/GcNotifyEmailMessage.php:12)
```

@gobyrne here, I found this on UAT today:
![Image](https://github.com/user-attachments/assets/342cdd77-5057-4936-a586-81e98474312d)

## 🦋 Expected Behaviour

If the email address is null then there's no point in trying to build a GcNotify message to verify the email.  The app should prevent this, at least at the mutation to request verification.

## 🕵️ Details

Reach out to Marc for additional details and to answer questions 

## 📸 Screenshot

![image](https://github.com/user-attachments/assets/c573868d-7a95-4459-b310-8b92a660c00a)

## 🙋‍♀️ Proposed Solution

How is the user even trying to verify a null email address?  Is this log indicating a bug or a gap in the application?

## ✅ Acceptance Criteria

- [ ] It is not possible for a user to attempt to verify a null email address

**Comment by DVPETROVA** [comment]
While in the Government Employee Information section, 5 users reported the work email not saving after the verification process. Once verified, the work email will stay 'green' and 'verified' for a little while, but when leaving and returning to the page it goes back to 'red' and 'unverified'. 
![image](https://github.com/user-attachments/assets/ddc8b063-f5ba-4f90-b6a5-9ff35f81016a)
![image](https://github.com/user-attachments/assets/61ebb28c-3cec-4203-9ace-f64684e92956)
