### ISSUE TITLE
♻️ Larastan: Access to undefined property

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#11590]
## ♻️ Debt/Refactor

Fix all "Access to undefined property" errors.

## 🙋‍♀️ Proposed Solution

REF: https://phpstan.org/blog/solving-phpstan-access-to-undefined-property

Do the following for each ignore line in the config file

 - Confirm the property exists
 - Add PHPDoc to type hint
 - Remove ignore in `phpstan.neon` file

## ✅ Acceptance Criteria

- [ ] No longer ignoring any errors for access to undefined property
- [ ] Larastan passes analysis with no errors

**Comment by brindasasi** [comment]
I'm just looking at these ignores in my PR . Thanks for fixing this 😅
