### ISSUE TITLE
🐛 Tweak nav role context behaviour

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#11659]
## 🐛 Bug

We're finding that a few tweaks to the nav role context would make the new layout experience better.

## ✅ Acceptance Criteria

- [ ] Remove the guest nav role.  The guest experience will be tracked as a null nav role instead.
  - [ ] Pages with no specified roles should leave the current nav role unchanged.
- [ ] The nav role in a tab should survive a page refresh.
  - [ ] The nav role should not sync between tabs.
  - [ ] The nav role does not need to survive tab closure.

**Comment by yonikid15** [comment]
This may get closed if fix is made in #11501. Holding off till that's confirmed
