### ISSUE TITLE
♻️ Remove line about veterans for Internal advertisements (posters)

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#11668]
## ♻️ Debt/Refactor

Internal job posters are not required to give priority to veterans, but we currently state that preference on our new area of selection UI.

## 🕵️ Details

Remove the entire line that starts with an asterisk from the "Who can apply" section for internal job advertisements.

![image](https://github.com/user-attachments/assets/d86ca6f4-8094-4af2-b564-b6b3f9876888)

## ✅ Acceptance Criteria

- [ ] Line about veteran preference removed FOR posters with internal area selection (for employees only)
- [ ] Line about veteran preference remains on other (public) job posters

**Comment by tristan-orourke** [comment]
HR wants this live by Friday 11am

**Comment by JamesHuf** [comment]
This should be done already as part of https://github.com/GCTC-NTGC/gc-digital-talent/pull/11619.

**Comment by tristan-orourke** [comment]
Already done in #11619.
