### ISSUE TITLE
🐛 /en/browse results in a blank page

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#11717]
## 🐛 Bug

When a user navigates to `/en/browse` there's just  blank page.

## 📋 Steps to Reproduce

1. https://talent.canada.ca/en/browse/

## 📸 Screenshot

![image](https://github.com/user-attachments/assets/9ce0bb22-1374-4c7e-a2eb-098dfc1a954a)

## 🙋‍♀️ Proposed Solution

I guess this should be triggering the "not found" page?

## ✅ Acceptance Criteria

- [ ] Navigating to `en/browse/` shows a 404 error instead of a blank page
- [ ] Any route segment which has children but no index page shows a 404 if you go there manually.

**Comment by tristan-orourke** [comment]
This might affect other route segments which have children but no index
