### ISSUE TITLE
🐛 Can't assign community role to any user 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#11743]
## 🐛 Bug

![Image](https://github.com/user-attachments/assets/c681b7ac-83f3-47f9-9e60-aba879e36cb6)

I see things like that .. but the user does have a team and I dont get what team id it requires. 
It happens to almost all users I've tried 

![Image](https://github.com/user-attachments/assets/c0a5f23e-261d-44e3-bef5-fb4d390a259d)

## 🦋 Expected Behaviour
Users and roles can be added to community 

## 📋 Steps to Reproduce

1. Go to en/admin/communities
2. click on any communities
3. click on manage access tab
4. click on add member 
5. try to add any user
6. observe error message

## ✅ Acceptance Criteria

- [ ] Users can be added to communities with roles

**Comment by brindasasi** [comment]
This is still happening on UAT on the upcoming release https://github.com/GCTC-NTGC/gc-digital-talent/releases/tag/v2.34.0
I believe there should be some migration for existing users.

**Comment by brindasasi** [comment]
Also I get this error in the home page and I think it is also related 
![Image](https://github.com/user-attachments/assets/801254ad-0bca-437d-9bf9-beaee98caaaf)
![Image](https://github.com/user-attachments/assets/8540e455-f74d-4eb6-8551-5355f5f65175)

**Comment by tristan-orourke** [comment]
Does the sync user roles script need to run on UAT before it works?

**Comment by brindasasi** [comment]
I ran RolePermission Seeder and still getting the same error.

**Comment by tristan-orourke** [comment]
Try running `php artisan app:sync-pool-process-operator`

**Comment by brindasasi** [comment]
Turned out existing communities are not linked to any team. 
New communities are working fine. 
It's not reproducible in local because we work with seeded data. 

Migration script needed to update existing two communities in UAT & prod .. those are Digital Community & ATIP

**Comment by brindasasi** [comment]
> Also I get this error in the home page and I think it is also related ![Image](https://github.com/user-attachments/assets/801254ad-0bca-437d-9bf9-beaee98caaaf) ![Image](https://github.com/user-attachments/assets/8540e455-f74d-4eb6-8551-5355f5f65175)

This is going to be a sep issue .. but this is also urgent for release as it will affect all applicants.
