### ISSUE TITLE
🐛 Edit User - Team based roles - Add Membership doesn't validate for existing roles

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#11746]
## 🐛 Bug

Add Membership table doesn't prevent the user from adding the same team over and over. 
It doesn't validate the existing membership and gives successful message toast. 
But in the DB it didn't actually save twice which is good. 
It would be nice if it can be prevented in first place. 

![Image](https://github.com/user-attachments/assets/80cb75cb-beae-4e2f-b98f-ae073d895d38)

## 🦋 Expected Behaviour

Add Membership dialog should not show the team that user already belongs to AND no other roles left in that team to assign to. 
If there are multiple roles , UI should only provide the remaining roles. 

OR 

keep the existing and throw an error message user role already exists in the table

## 📋 Steps to Reproduce

1. Go to admin/users/
2. Click Edit on any user 
3. click on Edit User Account 
4. Click on Add Membership on Team based roles section 
5. Observe all the teams including the user already belongs to shows up in the dialog 
6. Click on the team that user already belongs to , select role that user already has ( currently only pool operator)
7. Observe query goes through and success toast message appear
8. Observe there is no change on the table

## ✅ Acceptance Criteria

- [] UI should be clear of what is happening. Either don't provide the duplicate option OR provide the error message properly

**Comment by tristan-orourke** [comment]
If there's no bad data saved to database, and this is just for teams, I'm not concerned. Teams will be going away soon anyway.
