### ISSUE TITLE
🐛 Can't submit an application to a pool with hidden screening questions.

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#11748]
## 🐛 Bug

On the IT-05 pool in prod there is a single screening question.  However, it is not visible during application and is preventing applications from being submitted.

## 📸 Screenshot

![image](https://github.com/user-attachments/assets/1c610440-a440-44c8-b909-40f273387996)

**Comment by brindasasi** [comment]
Couldn't reproduce this in UAT with https://github.com/GCTC-NTGC/gc-digital-talent/releases/tag/v2.33.1 but same errors out on prod. 

I suspect this just because related files are impacted. Probably promise takes too long to return ? 

https://github.com/GCTC-NTGC/gc-digital-talent/pull/11665

**Comment by petertgiles** [comment]
Tristan said that he couldn't see the questions coming back from the API at all so I suspect a backend issue.  I suspect one of the Larastan PRs.  However, I haven't been able to reproduce it yet, either.  :laughing:

**Comment by petertgiles** [comment]
Booyah!  I very carefully recreated the pool locally and replicated the issue.
![Image](https://github.com/user-attachments/assets/efa138a7-f707-485c-806b-7d47638a4226)

Now the real digging begins...
