### ISSUE TITLE
✨ Double check admin dashboard and permissions for new user roles

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#11767]
## ✨ Feature

Ensure new user roles (Community Admin, Community Recruiter, and Process Operator) are allowed to view all the right pages. It seems like we missed at least some cases, so do a full review.

## 🕵️ Details

Compare to what we currently give community managers and recruiters. I think the new community roles need access to the Candidate Search and User Search, and Skills table.

Community Admins should be able to access:
- Communities pages (view table, view single, edit, and manage access)
- Process pages (view table, view single with access to all 4 tabs, edit poster, preview poster, edit assessment plan, and ability to publish)
- Request pages (view table, view single)
- Candidate pages (candidate search ie candidate table, view single)
- User pages (view table, view single User Profile and User Information tabs but not Edit tab)
Community Admin should see links on their dashboard to the following pages:
- Processes
- Talent Requests
- Candidate search
- All users (can we name it User search?)
- Communities
- Skills list
- Job templates

Community Recruiter should be the same as Community Admin, except...
- Can view Community table and details, but can't edit or view manage-access tab
- No ability to publish pools

Process Operator should be able to access:
- Process pages (view table, view single with access to all 4 tabs, can view manage access tab but cannot add or edit rows, edit poster, preview poster, edit assessment plan, without ability to publish)
- Candidate pages (candidate search ie candidate table, view single)
- User pages (view table, view single User Profile and User Information tabs but not Edit tab)
Process Operator should see links on their dashboard to:
- Processes
- Candidate search
- Users
- Skills list
- Job templates
 

## 🙋‍♀️ Proposed Implementation

Note that #10793 should consolidate how frontend permissions are stored and referenced.

Search for uses of `hasRole` to ensure the correct permissions are checked everywhere.

## ✅ Acceptance Criteria

Community Admins should be able to access:
- [x] Nav contains links to Dashboard, Processes, Candidates, Requests and Resources
- Communities pages
  - [x] table view
  - [x] view single community
  - [x] ability to edit
  - [x] manage access tab
- Process pages 
  - [x] table view
  - [x] create new
  - [x] Process Information tab
    - [x] edit poster
    - [x] preview poster
    - [x] edit assessment plan
    - [x] ability to publish
    - [x] screening and assessment tab
    - [x] talent placement tab
    - [x] manage access tab
- Request pages 
  - [x] table view
  - [x] view individual request
- Candidate pages 
  - [x] candidate search ie candidate table
  - [x] individual application
- User pages 
  - [x] table view
  - [x] User Profile tab
  - [x] User Information tab
  - [x] DO NOT have access to Edit User Account tab
 

Community Recruiter should be the same as Community Admin, except...
- Can view Community table and details, but can't edit or view manage-access tab
- No ability to publish pools
So... Community Recruiter should be able to access:
- [x] Nav contains links to Dashboard, Processes, Candidates, Requests and Resources
- Communities pages
  - [x] table view
  - [x] view single community
  - [x] NO ability to edit
  - [x] CANNOT VIEW manage access tab
- Process pages 
  - [x] table view
  - [x] create new
  - [x] Process Information tab
    - [x] edit poster
    - [x] preview poster
    - [x] edit assessment plan
    - [x] CANNOT publish
    - [x] screening and assessment tab
    - [x] talent placement tab
    - [x] manage access tab
- Request pages 
  - [x] table view
  - [x] view individual request
- Candidate pages 
  - [x] candidate search ie candidate table
  - [x] individual application
- User pages 
  - [x] table view
  - [x] User Profile tab
  - [x] User Information tab
  - [x] DO NOT have access to Edit User Account tab

Process Operator should be able to access:
- [ ] Nav contains links to Dashboard, Processes, Candidates, and Resources (but not Requests)
- Process pages 
  - [x] table view
  - [x] CANNOT create new
  - [ ] Process Information tab
    - [x] edit poster
    - [x] preview poster
    - [x] edit assessment plan
    - [x] CANNOT publish
    - [x] screening and assessment tab
    - [x] talent placement tab, without ability to place candidates from table
    - [x] can view manage access tab but cannot add or edit items
- Candidate pages 
  - [x] candidate search ie candidate table, without ability to place candidates from table
  - [ ] individual application, with ability to assess and qualify/disqualify but not place candidates
- User pages (view table, view single User Profile and User Information tabs but not Edit tab)
Process Operator should see links on their dashboard to:
- User pages 
  - [x] table view
  - [x] User Profile tab
  - [x] User Information tab
  - [x] DO NOT have access to Edit User Account tab

## 🛑 Blockers

```[tasklist]
### Blocked By
- [ ] #10793 
```

**Comment by vd1992** [comment]
Should check dashboard page and links (added in #11900)
If page permissions changed, link permissions should change too
