### ISSUE TITLE
✨ New IT Training Fund static page

### ISSUE THREAD

**Issue by NienkeBr** [GCTC-NTGC/gc-digital-talent#11794]
## ✨ Feature

We need a static page on the IT Community Training and Development Fund which was established under the IT collective agreement. The page provides info about the Fund, who's eligible, and the types of programs supported by the Fund.

## 🕵️ Details

The copy is still subject to change.

New page: IT Community Training and Development Fund
URL: /it-training-fund
Page is similar to the Directive page.

**Links**
IT collective agreement link: https://www.tbs-sct.canada.ca/agreements-conventions/view-visualiser-eng.aspx?id=31 
Navigar link: https://navigar.ca/
Sign up for updates: 
- English https://forms-formulaires.alpha.canada.ca/en/id/cm2oraxj700k8d1ec6dumq39e
- French https://forms-formulaires.alpha.canada.ca/fr/id/cm2oraxj700k8d1ec6dumq39e

## 🎨 Design

Design by Jerbo, but questions to Nienke, please. 

[Figma file can be found here](https://www.figma.com/design/Ml1qNqW5t8V0HDcB5ISQZu/IT-Community-Training-and-Development-Fund?node-id=413-19007&node-type=canvas&t=cpQNmgObiuG7dXMu-0).

## 📸 Screenshot

![Image](https://github.com/user-attachments/assets/390204b0-1180-492b-a76b-eb23cb506fbd)

## 🌎 Localization

French translation will be provided when the copy has been finalized.
(copy is almost final though. But no need to send to translation, it will be provided by Nienke)

## ✅ Acceptance Criteria

- [ ] Page built to design (ignore version in figma with accordions, that's a rejected design)
- [ ] Use the new Hero component
- [ ] Copy updated with final copy when ready
- [ ] 4 links go to correct places
- [ ] Design review by @NienkeBr 

```

**Comment by NienkeBr** [comment]
We'll also need to add a block to the homepage under "Check it out" to link to this page. I'll create a separate ticket for this though as we're still discussing the design.

**Comment by tristan-orourke** [comment]
We still need images

**Comment by tristan-orourke** [comment]
Note: the most in-flux copy is on the Employee Eligibility section.

**Comment by Jerryescandon** [comment]
PICS

![christina-wocintechchat-com-c-mgSuxqpzA-unsplash (1)](https://github.com/user-attachments/assets/925e276f-a623-4507-90a7-51b9cf4d6778)
![alvaro-reyes-G3yLB3Fasow-unsplash (1)](https://github.com/user-attachments/assets/b5bb63f4-ec3b-46e0-8b12-219c3f2ed842)

**Comment by Jerryescandon** [comment]
MORE PICS!

![pexels-kampus-8636602 (1)](https://github.com/user-attachments/assets/c0fb40b5-0978-4d39-a22f-6e736ad2c623)
![luke-peters-B6JINerWMz0-unsplash](https://github.com/user-attachments/assets/3d0918e7-3806-4065-ac6a-50ab3befc530)

**Comment by Jerryescandon** [comment]
Github wont let me upload WEBP, so I dropped the relevant pictures [in this google drive folder](https://drive.google.com/drive/folders/1mrGpwHtcIPsVG5N3GlYHdoSUkYBlacro?usp=drive_link).
