### ISSUE TITLE
✨ Add department to job advertisement

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#11801]
## ✨ Feature

We always collect the department that is running a process now. Please add it to the job advertisement.

## 🕵️ Details

Just add the department to the job advertisement as it appears here. This design shows multiple departments, but right now we can only have 1. So just show the one department collected on the "Create process" page.

![Image](https://github.com/user-attachments/assets/c4b2cc31-3ce6-4b5a-96d3-aa51f2af0353)

## ✅ Acceptance Criteria

- [ ] Department added to Employment details section of the job advertisement

**Comment by tristan-orourke** [comment]
If a poster doesn't have a department associated (can't remember if this is possible for old pools) don't show Department label at all
