### ISSUE TITLE
🐛 Community admin dashboard doesn't quite align with their permission

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#11850]
## 🐛 Bug

Community admin can create process and related activities. They can also create community and add members.
But those sections are not visible in their dashboard. 
They can access it via side navbar though 
![Image](https://github.com/user-attachments/assets/69a70d51-cf2c-477a-a4f0-748c36c3eb44)

## 🦋 Expected Behaviour

I believe community admin has all these permissions and should be reflected in the dashboard as well 
![Image](https://github.com/user-attachments/assets/139f3b07-d268-405e-86b1-89ad20d215d2)

## 📋 Steps to Reproduce

1. Login as community@test.com 
2. Go to Admin Dashboard 

## ✅ Acceptance Criteria

- [ ] Community Admin dashboard should align with their permissions
- [ ] Also confirm this change doesn't impact Community Recruiter dashboard

**Comment by tristan-orourke** [comment]
Closing in favour of #11767
