### ISSUE TITLE
✨ Generated files - New work experience fields

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#11869]
## ✨ Feature

Add new the work experience fields to the user generated export files. Experience to not show up in CSV, so no need to update CSV.

## 🎨 Design

[File to google doc example](https://docs.google.com/document/d/1tKlZ381GBaT7eeJ3vAueTiw4MmzkVqQFWCn_b3W_dqU/edit?usp=sharing) by @Jerryescandon 

## ✅ Acceptance Criteria

- [ ] DOCX files match provided design

## 🛑 Blockers

```[tasklist]
### Blocked By
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/11868
```

**Comment by tristan-orourke** [comment]
CSV files don`t show full experiences, so only docx files need to be updated.
