### ISSUE TITLE
✨ Backend - new fields for work experience

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#11868]
## ✨ Feature

We will need new fields added to the work experience model to support new data collection in the UI.

## 🕵️ Details

Refer to https://github.com/GCTC-NTGC/gc-digital-talent/issues/11864 for the UI that this issue will support.

Our work experiences are currently stored in a json object in the `experiences` table shared with other experience types.  This issue probably won't include adding actual columns to any tables.  Or database constraints for foreign references.

Note that organization used to be mandatory but will become conditionally mandatory based on employment category.

## 🎨 Design

@Jerryescandon 

https://www.figma.com/design/piRkRtWAHheoEX5Jq8d9u7/Create%2FEdit-an-experience-(Applicants)?node-id=472-70951&t=NbjSJSxQjUSo26FF-1

## 🙋‍♀️ Proposed Implementation

employment_category - enum
ext_size_of_organization - enum
ext_role_seniority - enum
department - relationship to Department model
gov_employment_type - enum
gov_position_type - enum
gov_contract_end_date - date
gov_contractor_role_seniority - enum
gov_contractor_type - enum
classification - relationship - Classification model
caf_employment_type - enum
caf_force - enum
caf_rank - enum

## ✅ Acceptance Criteria

- [ ] New fields input on new work experience creation
- [ ] New fields input on update existing work experience creation
- [ ] Validator to enforce consistency (eg, no CAF fields when external experience)
- [ ] Can continue to submit work experiences with current UI in place
- [ ] Unit tests for validation of different kinds of experiences
- [ ] New fields returned when querying experiences, same data protection as other experience fields
- [ ] New fields saved in snapshots on pool candidate submission
- [ ] New fields returned when querying snapshot
- [ ] French and English in localized enums
- [ ] Seeder and factory updated
- [ ] Old and new experiences continue to work in edit forms, viewing, downloads, snapshot viewing 

## 🛑 Blockers

```[tasklist]
### Blocked By
```

**Comment by petertgiles** [comment]
Marked as blocked until we have designs for gov contract end date.

**Comment by tristan-orourke** [comment]
Note: additional validation for end date being required in certain situations
