### ISSUE TITLE
✨ One-time in-app notification about work experience updates

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#11875]
## ✨ Feature

We would like to send out a one-time in-app notification about updates to the work experience fields.

## 🕵️ Details

Message EN: We've updated the work experience options on your profile. Please review your career timeline and ensure it’s up to date.
Message FR: Nous avons mis à jour les options d'expérience professionnelle sur votre profil. Veuillez vérifier votre parcours professionnel et vous assurer qu'il est à jour.
URL when clicked EN: /en/applicant/career-timeline
URL when clicked FR: /fr/applicant/career-timeline

## 🙋‍♀️ Proposed Implementation

Prepare an artisan command that queues up all the notifications on demand.

## ✅ Acceptance Criteria

- [ ] In-app notification can be triggered when desired (ie by artisan command)
- [ ] Notification is localized.
- [ ] Notification links to user experiences page
- [ ] Notification is in-app only
- [ ] Notification gets sent to everyone (systems level notification)

## 🛑 Blockers

```[tasklist]
### Blocked By
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/11864
```

**Comment by gobyrne** [comment]
@NienkeBr , actually this first batch of experience updates is only useful for Government folks. If your experience is non-government, you don't have any new options.

Could you re-write with this in mind?

**Comment by gobyrne** [comment]
Maybe? @petertgiles ?

**Comment by petertgiles** [comment]
> Can't we just push this notification to users that say that they're government employees?

Yeah, that should be possible.
