### ISSUE TITLE
Maintenance scripts not working on macOS

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#1188]
`setup.sh: /root/scripts/update_auth_env.sh: /bin/bash: bad interpreter: Permission denied
`

Also happens on other shell scripts in `scripts`.

![Screen Shot 2021-11-19 at 15 27 31](https://user-images.githubusercontent.com/3046459/143060492-67d43140-ce94-422c-8d2c-640dd073fad9.png)

This could be involved with setting executable rights on the script files.

**Comment by mnigh** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/1188?planning-poker) with ZenHub @gggrant @petertgiles @tristan-orourke @yonikid15

**Comment by petertgiles** [comment]
I'm guessing it's a executable permission issue.  A `chmod a+x` might be enough to fix it.
