### ISSUE TITLE
Feature - Admin - Keep Session Alive

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#1192]
The Sign In Canada auth server allows a user to log in and issues tokens that last five minutes.  So a user gets five minutes to use the site before they begin seeing "Unauthenticated" messages again and must manually navigate back to the /admin/login page to request a new token.  A better experience would be to have the site automatically keep the session alive as long as there was activity.  Perhaps we need to add functionality to periodically request refresh tokens.

**Comment by petertgiles** [comment]
I can't get SiC to accept the offline_access scope or issue us a refresh token.  It might take some coordinating with that team to understand how we should be handling this use case.

**Comment by tristan-orourke** [comment]
Splitting this one issue more explicitly into #1271 and #1269.
