### ISSUE TITLE
Feature - Admin - Populate User Sub Field With SiC UUID

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#1193]
The user creation process in the API automatically fills the sub field with the email address.  This behaviour is compatible with the local auth server we use for testing but is not compatible with the Sign In Canada server.  The SiC server issues tokens with a uuid in the sub field.  I suppose we would need some sort of registration process to link a SiC user with an application user.

**Comment by petertgiles** [comment]
GETting https://te-auth.id.tbs-sct.gc.ca/oxauth/restv1/userinfo with a valid token will return the sub and locale for the token's bearer.  This might be able to be used as part of a registration process.

**Comment by gggrant** [comment]
Will lump in with forthcoming registration process issue(s).
