### ISSUE TITLE
✨ New instructor-led training fund page

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#11931]
## ✨ Feature

Instructor-led training fund page that displays cards for each training and links to the registration/application forms for them.

**URL: /it-training-fund/instructor-led-training**

## 🎨 Design

https://www.figma.com/proto/ZhwRYrUAXxXeWeQQ5Yjhi8/Instructor-led-training-fund-page?page-id=413%3A19007&node-id=2819-13326&node-type=canvas&viewport=2722%2C1080%2C0.49&t=YktQROZkba6KkDfZ-1&scaling=min-zoom&content-scaling=fixed

Designer is the @Jerryescandon 

### Training dates
Just a note that training date is either a single day, or a start and end date (if an end date was provided)
![image](https://github.com/user-attachments/assets/4c6c3756-29e4-4221-9e9f-2c4ffbe13a81)

### Link to this page from the training fund page

In the section for **2. Instructor-led classes and bootcamps**:
- Replace **Coming 2024-25** with "Available now"
- Replace the link with a link to the new page that reads
    - EN: Browse training opportunities
    - FR: Parcourir les possibilités de formation

![image](https://github.com/user-attachments/assets/c3244082-235b-4cac-8654-035e9afcbecd)

## ✅ Acceptance Criteria

- [ ] New page /it-training-fund/instructor-led-training
- [ ] Static content on top of page
- [ ] Training opportunities cards show (ordered by application deadline, ascending)
- [ ] Training opportunities past the application deadline do NOT show
- [ ] Logic to show single **training date** (or start and end **training dates**)
- [ ] English only and French only filters work
- [ ] Null state for no trainings
- [ ] Learn more buttons open dialogs which display rich text content and have links to applications
- [ ] Changes to main training fund page
    - [ ] Replace **Coming 2024-25** with "Available now"
    - [ ] Replace the link with a link to the new page

## 🛑 Blockers

```[tasklist]
- [ ] #11930 
```

**Comment by tristan-orourke** [comment]
The line on the cards will be implemented as a "card separator" component in another ticket

**Comment by NienkeBr** [comment]
French translation of copy: [ILT training page for translation-FR_NB.docx](https://github.com/user-attachments/files/17872296/ILT.training.page.for.translation-FR_NB.docx)
