### ISSUE TITLE
🔤 Announcement form success message

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#11934]
## 🔤 Copy

The message that is returned after a successful form submission is lowercase and doesn't provide context like other form messages throughout the site (for example, Classification created successfully!).

### Screen recording
https://github.com/user-attachments/assets/27f9fa26-8f17-408d-a692-ecf4441bd415

### Code
https://github.com/GCTC-NTGC/gc-digital-talent/blob/8df9d8b795db8bbdd016d7ec9d549f6b95520fdc/packages/i18n/src/messages/commonMessages.ts#L102-L106

The string `commonMessages.success` is only used by the announcements form.

## ✅ Acceptance Criteria

- [ ] string `commonMessages.success` is removed
- [ ] Announcement form success message sentence case in both English and French

**Comment by NienkeBr** [comment]
Please use the following messages:
- English: Sitewide announcement updated successfully!
- French: L'annonce à l’échelle du site a été mise à jour avec succès!
