### ISSUE TITLE
🐛 CSV download is missing data, in some cases it provides empty file

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#11963]
## 🐛 Bug

CSV download on Talent Placement tab under a process is broken currently.
It is always missing some rows. 
When there is only 1 candidate is selected it gives empty file.
This bug exists in production as well. 

## 🦋 Expected Behaviour

CSV download should download all selected data. 

## 📋 Steps to Reproduce

1. Go to any process and navigate to Talent Placement tab
2. Select 1 candidate and click download csv. 
3. Observe you get empty file 
4. Select all candidates observe you are missing either 1 or more candidates.

## ✅ Acceptance Criteria

- [ ] CSV download should download all selected data.

**Comment by esizer** [comment]
Do we have any error logs to go along with this?
