### ISSUE TITLE
⌨ Manual accessibility testing for new Nav and new Dashboards

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#11964]
## ⌨ Accessibility Issue

Manual accessibility testing for the new nav and our new dashboards

## Paths for testing

1. New manager dashboard, all sub-pages and all dialogues.
2. New nav, try all links
3. Admin and community dashboards (make sure it works with new nav, and after removing the old one)

## ✅ Acceptance Criteria

After testing the following, create tickets for any issues you find:
- [x] **Windows** Chrome + JAWS (@esizer)
- [x] **Windows** Edge + Narrator (@esizer)
- [x] **Windows** Firefox + NVDA (@esizer)
- [x] **macOS** Safari + VoiceOver (@mnigh)
- [x] **Android** Chrome + Talkback (@esizer)
- [x] **iOS** Safari + VoiceOver (@esizer)
- [x] Basic keyboard (@vd1992)

**Comment by esizer** [comment]
Issues created:

 - https://github.com/GCTC-NTGC/gc-digital-talent/issues/11986
 - https://github.com/GCTC-NTGC/gc-digital-talent/issues/11981
 - https://github.com/GCTC-NTGC/gc-digital-talent/issues/11978
 - https://github.com/GCTC-NTGC/gc-digital-talent/issues/11977
 - https://github.com/GCTC-NTGC/gc-digital-talent/issues/11976
 - https://github.com/GCTC-NTGC/gc-digital-talent/issues/11975
 - https://github.com/GCTC-NTGC/gc-digital-talent/issues/11974
 - https://github.com/GCTC-NTGC/gc-digital-talent/issues/11973

**Comment by vd1992** [comment]
Issues

- https://github.com/GCTC-NTGC/gc-digital-talent/issues/11991
- https://github.com/GCTC-NTGC/gc-digital-talent/issues/11992
- https://github.com/GCTC-NTGC/gc-digital-talent/issues/11994
