### ISSUE TITLE
🔤 Small French copy update for timestamp submission of application

### ISSUE THREAD

**Issue by NienkeBr** [GCTC-NTGC/gc-digital-talent#11987]
## 🔤 Copy

Please update in French how we indicate the date and time an application has been submitted on the applicant dashboard.

## 🕵️ Details

Please change the following on the applicant dashboard:
- Replace “Candidature formulée le cv : {date} {time}” with “Candidature soumise : {date} {time}“

![image](https://github.com/user-attachments/assets/7f431af0-a487-4914-971c-4a28c738a827)

## ✅ Acceptance Criteria

- [ ] Application submission timestamp in French has been updated

**Comment by mnigh** [comment]
@NienkeBr Changing _Candidature formulée le cv : _ to _Candidature soumise le_ is simple. Splitting out time from the date is a bit trickier. 

Does _à_ need to be in between {date} and {time} in French only, or also in English ({date} at {time})?
