### ISSUE TITLE
🔤 Replace "Job templates library" under resources section on admin dashboard

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#11999]
## 🔤 Copy

Replace "Job templates library" under resources section on admin dashboard with "Job advertisement templates".

### Screenshots

<img width="1440" alt="Screen Shot 2024-11-15 at 15 51 21" src="https://github.com/user-attachments/assets/a3da9a2f-f2e8-4134-92aa-aec5afdcdb28">

## ✅ Acceptance Criteria

- [ ] "Job advertisement templates" replaces "Job templates library" under resources section on admin dashboard

**Comment by tristan-orourke** [comment]
@NienkeBr do you have any feedback here?

**Comment by NienkeBr** [comment]
We can replace "Job templates library", however, "Job templates" and "Job advertisement templates" are more tricky. "Job advertisement templates" is more complete and descriptive, but it's long for the navigation. Could we use them both, like we also use "Browse jobs" and "(Active talent) recruitment processes"  when talking about job posters?
If so, I'd replace "Job templates library" with "Job advertisement templates" as I think we have the space there.
