### ISSUE TITLE
🐛 Community Dashboard page opens up outside VPN and giving out the links for protected pages

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#12009]
## 🐛 Bug

New navigation redesign gives out the community dashboard page outside the VPN. 

![Image](https://github.com/user-attachments/assets/26aa3db9-6dfd-4358-8ecd-446db6821dbb)
At this point when you click on processes it loads like 
![Image](https://github.com/user-attachments/assets/f6111efd-83bf-4a7e-84a8-a57cef41c7d3)

This caused lot of panic and confusion. It hides the actual problem that user is NOT under the vpn. 

## 🦋 Expected Behaviour

The user should be informed that they are not under vpn. 

## 🕵️ Details
**Tech details** 
Currently we have `en/admin`  route has been protected under firewall. 
Community Dashboard is `en/community` route which is outside of this and doen't make any api calls yet. 
However if you click on any admin links like processes , candidates , it goes to admin url and hits `admin/graphql `
and currently we don't give any proper error message on UI that the request failed. 

## 📋 Steps to Reproduce

This can only be reproduced in uat,prod with firewall setup. 
Currently UAT is public with admin route is protected under vpn. 
So we can reproduce it here: https://uat-talentcloud.tbs-sct.gc.ca/

1. Get your access to UAT with some admin level role 
2. Create a process or get assigned to existing process as pool operator
3. Click on Community on the new navbar
4. Click on Processess
5. Observe the page is loaded with the empty table

## ✅ Acceptance Criteria

- [ ] When the user is not under vpn and trying to access the community dashboard, there should be an error message on the UI.

**Comment by tristan-orourke** [comment]
We discussed moving the Community dashboard under `/admin`, so that all our "protected" urls are under a single directory. What should our new urls be?

`/community` -> `/admin/community`
or
`/community` -> `/admin/community-dashboard`
or
`/community` -> `/admin/community-dashboard` and
`/admin` -> `/admin/admin-dashboard` 
?

**Comment by tristan-orourke** [comment]
Closing in favour of #12230 and #10371
