### ISSUE TITLE
🔤 Nav menu actions use title case instead of sentence case

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#12016]
## 🔤 Copy

Nav menu actions use title case instead of sentence case.

### Screenshot
<img width="343" alt="Screen Shot 2024-11-19 at 12 47 15" src="https://github.com/user-attachments/assets/14459e86-452e-42b5-9fd7-f84bc83341e8">

## 🙋‍♀️ Proposed Implementation

- Change Close Menu to Close menu
- Change Open Menu to Open menu

## ✅ Acceptance Criteria

- [ ] Text label for button that closes side menu is sentence case
- [ ] Text label for button that opens side menu is sentence case

**Comment by mnigh** [comment]
@NienkeBr thoughts?

**Comment by NienkeBr** [comment]
Absolutely, good catch!
