### ISSUE TITLE
♻️ Update role menu and mobile sub menus

### ISSUE THREAD

**Issue by JoshBeveridge** [GCTC-NTGC/gc-digital-talent#12028]
## ♻️ Debt/Refactor

[Visit the Figma file](https://www.figma.com/design/guHeIIh8dqFVCks310Wv0G/Component-library?node-id=1475-27575) • Chat with @JoshBeveridge for design questions

Two separate issues triggered these minor design changes:
* #12009
* @mnigh brought up that the centered mobile menus were confusing in terms of hierarchy, because there was no consistent alignment

> [!TIP]
> Figures can be found in the Figma file linked above 

As a result, I'd like to make the following changes:
- [ ] When a user with the community or admin roles opens the role sub menu off the network, prevent them from navigating to roles that are network-specific and update the design to mirror _figure 1_ and _figure 2_
- [ ] Update the mobile sub menus to reflect the new designs in _figure 3_ and _figure 4_, where all menu items are left aligned, items with children have no underline and their children are indented

## 🛑 Blockers

> [!NOTE]
> It's likely this will be blocked by #12009, so feel free to spin the alignment changes out into their own ticket and use this one to handle the off network styling and iconography.

```[tasklist]
### Blocked By
```

**Comment by tristan-orourke** [comment]
The mobile nav menu has been split off into #12228

**Comment by tristan-orourke** [comment]
and VPN concerns have been split off into #12230
