### ISSUE TITLE
♻️ Move admin routes as children of root route

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#12032]
## ♻️ Debt/Refactor

There is now no discernible difference between the root route and admin routes so we can likely move away from them being defined separately. 

## 🕵️ Details

We recently moved all the admin pages over to use a nearly identical layout to the root layout but did not move the routes over so we seem to have a redundant `AdminLayout` that simply mirrors the main layout.

This also means our route definition has to add in another top level definition for `${locale}/admin` that applies the same layout.

I think we should be safe to delete the `AdminLayout` now and move all the routes to the root route now.

## 🙋‍♀️ Proposed Solution

 - Reorganize the `createRoute` function to no longer need a separate definition for admin routes
 - Delete the unused `AdminLayout`
 - Possibly remove the admin specific error boundary as well :thinking: 

## ✅ Acceptance Criteria

- [ ] Routes under `/admin` have been moved to the root route definition
- [ ] No visual difference for admin routes
- [ ] Unused code removed

**Comment by mnigh** [comment]
> * Delete the unused `AdminLayout`

🎁 Bonus: this will allow us to close https://github.com/GCTC-NTGC/gc-digital-talent/issues/11162.

**Comment by petertgiles** [comment]
> 🎁 Bonus: this will allow us to close [#11162](https://github.com/GCTC-NTGC/gc-digital-talent/issues/11162).

Sorry, I don't think so.  We still have the ThemeSwitcher:Default story that is unstable.

**Comment by mnigh** [comment]
> > 🎁 Bonus: this will allow us to close [#11162](https://github.com/GCTC-NTGC/gc-digital-talent/issues/11162).
> 
> Sorry, I don't think so. We still have the ThemeSwitcher:Default story that is unstable.

Should probably create another issue then since #11162 is specific to `AdminLayout`.

**Comment by petertgiles** [comment]
Ah, good point. I updated the issue to refer to the ThemeSwitcher story itself.
