### ISSUE TITLE
🐛 Province dropdown in Work Preferences form not initialized properly

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#12033]
## 🐛 Bug

When editing Work Preferences on the Applicant Profile page, current province dropdown is not initialized with the actual current value. Instead, it defaults to the first option in the list (ie Alberta). If you don't notice, and save the form without changing it, your previous location will be overwritten.

## 🦋 Expected Behaviour

If you have previously saved a province value, the current location dropdown should be initialized with that value when you open the editing form.

## 📋 Steps to Reproduce

1. Log in as an applicant
2. Go to http://localhost:8000/en/applicant/personal-information
3. Edit Work Preferences, fill in form, use a current `Province, territory or region` other than Alberta, and save.
4. View Work Preferences. Your province selection should appear.
5. Click Edit work preferences to open the inline form.
6. The province dropdown now contains the value Alberta.

## 📸 Screenshot

![Image](https://github.com/user-attachments/assets/6d38a7fb-1794-414c-8cf2-40c9e11dea0c)

## ✅ Acceptance Criteria

- [ ] When editing Work Preferences, the Province select input initially contains your previously saved value

**Comment by vd1992** [comment]
I think this is related to https://github.com/GCTC-NTGC/gc-digital-talent/issues/11532
And is an issue common to all enum dropdowns due to them being fetched by API
