### ISSUE TITLE
🐛 RichTextInput can't bind to dotted subfields

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#12064]
## 🐛 Bug

Regular text input fields can be bound to dotted subfields, like `name.en` in a form but RichTextInput can't.

## 🦋 Expected Behaviour

RichTextInput should be able to bind to dotted subfields, too.

## ✅ Acceptance Criteria

- [ ] RichTextInput can bind to a dotted subfield

**Comment by esizer** [comment]
Can't seem to reproduce.

![Image](https://github.com/user-attachments/assets/4791e4a6-a8be-46a5-9ad2-f110ce7d366e)

**Comment by vd1992** [comment]
Appears to work?

![image](https://github.com/user-attachments/assets/b3d1510f-4ca4-4c3b-a635-cd60783e0998)
