### ISSUE TITLE
✨ Add "URL" type for inputs

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#12080]
## ✨ Feature

We have a couple of places where users can input URLs, like training opportunities.  Our Input component could be updated to validate these for us.

## 🕵️ Details

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url

https://github.com/GCTC-NTGC/gc-digital-talent/blob/cfdc39d79b38bd333264437e8187b1c791378b86/packages/forms/src/components/Input/Input.tsx#L18

## ✅ Acceptance Criteria

- [ ] It is possible to set the Input type to URL for validation.
- [ ] Use the URL type field on Training Opportunities form

## 🛑 Blockers

```[tasklist]
### Blocked By
```

**Comment by tristan-orourke** [comment]
Concerns - annoying to have to add the scheme; might want to have more control over error messages; do it all ourselves in custom component?
