### ISSUE TITLE
🐛 Work email not saving in profile

### ISSUE THREAD

**Issue by DVPETROVA** [GCTC-NTGC/gc-digital-talent#12147]
## 🐛 Bug

When adding work email in the Government Employee Information section, after saving it disappears again. Users see the red font 'Work Email Not Provided" after screen refresh. 

## 🦋 Expected Behaviour

When adding work email the Government Employee Information section, information is saved and displayed as 'Provided'.

## 📋 Steps to Reproduce

1. Go to your profile, to the Government Employee Information section.
2. Enter your work email and save. 
3. May need to log out and then log back in again to see the issue. 

## Screenshots 

![image](https://github.com/user-attachments/assets/4b161457-1110-4614-b52d-387bcee9521b)
![image](https://github.com/user-attachments/assets/4f5beaa0-9269-46be-9e45-47d495362960)

## ✅ Acceptance Criteria

- [ ] All users can save work email on their profile

**Comment by petertgiles** [comment]
I experienced this locally

**Comment by tristan-orourke** [comment]
Maybe this is experienced as a new user?

**Comment by petertgiles** [comment]
I spent some time trying to recreate this again... and now I can't.  😞

**Comment by tristan-orourke** [comment]
Let's ask helpdesk for some specific users who've experienced this, so we can try investigating them directly in the database.

**Comment by DVPETROVA** [comment]
Sounds good. I'll give you a list of the recent reports.

**Comment by DVPETROVA** [comment]
I think you are right, I think this only happens the first time a user adds their work email to the profile. Please read one of the users observations below: 
"I keep trying to add my work email to my profile, but every time I hit save and then look at the "Government employee information" section, I see "Work email Not provided" displayed instead of the address I typed in. I've done this several times (clicking to edit the section, typing in the email and reviewing all other info, hitting save and getting a confirmation saying the section was updated), but every time when I look at the completed section afterwards it says I have not provided my email. I'm unclear what I could be doing wrong here, as it says the changes were saved and everything except entering my work email worked like expected."
"Actually, there's no need. I think maybe that particular field just doesn't update as quickly as the rest or something because when I logged back in a while later it was filled in. Not sure why it happened, but the problem solved itself."

**Comment by vd1992** [comment]
Some sort of cache issue then maybe

**Comment by petertgiles** [comment]
Dasha sent me a list of users experiencing this in prod and all had work emails saved in the database.  I think Vachan is right that this is some sort of caching issue.  That said, I still can't reproduce this.

**Comment by DVPETROVA** [comment]
Maybe the only way to see it, is to create a new account and go through the process of saving the email. It only happens the first time users do it. They can be trying to save multiple times in the same (first) session with no success. Once they give up and log out, the next time they log in that email appears as saved.

**Comment by brindasasi** [comment]
I tried in UAT creating a new user .. working just fine for me ! sorry :(

**Comment by DVPETROVA** [comment]
I think Peter saw it once, but then couldn't recreate as well... It still keeps happening though. At least one or two people a day report it. I tell them to log out and log back in again, and it seems to help. If they are in the same session, they can't save. After they log back in, the email shows up and everything is good from that point on.

**Comment by DVPETROVA** [comment]
Ha, interesting. Although in my profile my work email is now saved, in my applications (this one is a draft that i am finishing for testing purposes) it shows as "not provided"
![image](https://github.com/user-attachments/assets/8fb43a6f-2177-4a0f-bffd-76f8b889faca)

**Comment by brindasasi** [comment]
Oh I got this issue in prod as well
