### ISSUE TITLE
🐛 Work email validation allows unexpected domains through

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#12144]
## 🐛 Bug

Our work email validation is pretty simple right now - just that it ends with, for example, "gc.ca".  This allows subdomains like "tbs-sct.gc.ca" to be properly approved. However, it also allows domains like dogc.ca to be approved.

## 📋 Steps to Reproduce

1. Enter a work email with a different top-level domain that ends with "gc.ca"

## 📸 Screenshot

![image](https://github.com/user-attachments/assets/aa73b1cc-6a10-41b9-9b78-3e7a61341617)

## 🙋‍♀️ Proposed Solution

Our validation should be smart enough to allow the exact match of top-level domain and subdomains without matching our top-level domains that end with an expected string.  This probably means that the backend validation will needs to be switched to a regex as well.  This is probably better since the frontend can more easily be compared.

## ✅ Acceptance Criteria

- [ ] Exact top-level matches like "example@gc.ca" are approved
- [ ] Matches with a subdomain like "example@tbs-sct.gc.ca" are approved
- [ ] Different top-level domains that end with the same string like "example@dogc.ca" are rejected
- [ ] All of the above apply to frontend validation and backend validation

**Comment by tristan-orourke** [comment]
You could do it without a regex by checking `@gc.ca|.gc.ca`
