### ISSUE TITLE
♻️ Remove Ongoing Jobs publishing group and associated UI

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#12151]
## ♻️ Debt/Refactor

The ongoing jobs UI is broken, we don't intend to use it anymore and it's interfering with our workstreams remodeling. Time to remove it.

## 🙋‍♀️ Proposed Solution

For any jobs that were published in the "IT jobs (ongoing)" publishing group, we could switch them to just "IT jobs" if needed. Since they are no longer published, it shouldn't make a difference.

## ✅ Acceptance Criteria

- [ ] Delete ongoing jobs UI from the browse jobs page
- [ ] Remove "IT jobs (ongoing)" from the list of publishing groups
- [ ] prepare an artisan or tinker command which replaces any current instances of `IT jobs (ongoing)` with `IT jobs`

## Deployment 
Run the migration command.

**Comment by mnigh** [comment]
@tristan-orourke 
 
1. Does this paragraph need to be rewritten to remove its reference to ongoing recruitment?

## Screenshot

![Image](https://github.com/user-attachments/assets/02ef463f-d598-452c-a02d-bf9969d16d27)

---

2. Does this paragraph need to be rewritten to remove its reference to ongoing recruitment?

## Screenshot

![Image](https://github.com/user-attachments/assets/df1d6b31-991a-4815-a1e2-71f60f7552a5)

---

3. Does this sentence need to be rewritten to remove its reference to ongoing recruitment?

## Screenshot

![Image](https://github.com/user-attachments/assets/43ad819a-1c2e-4042-bc23-7bc61c95eebe)

---

4. Does this sentence need to be rewritten to remove its reference to ongoing recruitment?

## Screenshot

![Image](https://github.com/user-attachments/assets/6b472503-729c-476a-85e4-67cdbee3d247)

**Comment by mnigh** [comment]
## Tinker

```
# 1. get all pools that have a publishing group of it jobs ongoing 
$pools = Pool::where('publishing_group', PublishingGroup::IT_JOBS_ONGOING);
# 2. get count of pools that have a publishing group of it jobs ongoing
$pools->count();
# 3. update pools that have a publishing group of it jobs ongoing to it jobs
$pools->update(array('publishing_group' => PublishingGroup::IT_JOBS));
# 4. get count of pools that have a publishing group of it jobs ongoing
Pool::where('publishing_group', PublishingGroup::IT_JOBS_ONGOING)->count();
```

**Comment by mnigh** [comment]
GitHub PRs are broken right now, but started work on a branch: https://github.com/GCTC-NTGC/gc-digital-talent/tree/12151-ongoing-jobs.

**Comment by tristan-orourke** [comment]
Good catch @mnigh, I think these should be re-written.

@NienkeBr can you work with Matt on this?

**Comment by tristan-orourke** [comment]
Updated copy should go to Figma as well

**Comment by NienkeBr** [comment]
Discussed point 3 and 4 with Matt. Suggestion to change the text for 1 and 2 to:

- Check out our job opportunities to find a manager position that inspires you. Apply to play a key role in one of the IT teams at the Government of Canada and make a meaningful impact.
- Consultez nos possibilités d'emploi pour trouver un poste de gestionnaire qui vous inspire. Posez votre candidature pour jouer un rôle clé au sein de l'une des équipes de TI du gouvernement du Canada et avoir un impact significatif.
