### ISSUE TITLE
🐛 Long emails overlapping adjacent sections on user profile

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#12169]
## 🐛 Bug

On the admin user information page, long emails can lead to the text overlapping the adjacent section.

## 🦋 Expected Behaviour

Text wraps in some way that maintains layout/visual integrity without having text overlap.

## 📋 Steps to Reproduce

1. Login as admin `admin@test.com`
2. Update a user to have a long contact email
3. Navigate to their information page `/admin/users/{userId}`
4. Observe it overlaps some text next to it

## 📸 Screenshot

![2024-12-02_14-37](https://github.com/user-attachments/assets/cfe450dc-06a8-47a0-8fea-1ed7d79db1c8)

## 🙋‍♀️ Proposed Solution

May need to reach out to designers. Though, just setting the text wrap could work? :thinking: 

## ✅ Acceptance Criteria

- [ ] Text on the admin user profile/information sections does not overlap
- [ ] Any noticeable visual changes has designer input

**Comment by tristan-orourke** [comment]
@Jerryescandon what do you think about this? Set the email text to wrap?

**Comment by Jerryescandon** [comment]
Absofruitly 🍎
