### ISSUE TITLE
🔤 `GCXchange` spelled incorrectly

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#12190]
## 🔤 Copy

`GCXchange` spelled incorrectly.

## 🕵️ Details

https://github.com/GCTC-NTGC/gc-digital-talent/blob/a75734aebef71dc614718888935514b1c8a0ffde/api/app/Enums/DirectiveForms/AdvertisingPlatform.php#L9

https://github.com/GCTC-NTGC/gc-digital-talent/blob/a75734aebef71dc614718888935514b1c8a0ffde/api/programmatic-types.graphql#L793

https://github.com/GCTC-NTGC/gc-digital-talent/blob/a75734aebef71dc614718888935514b1c8a0ffde/api/storage/app/lighthouse-schema.graphql#L2814

## 🙋‍♀️ Proposed Implementation

Replace  `GCXCHNAGE` with `GCXCHANGE`.

## ✅ Acceptance Criteria

- [ ] no instances of `GCXCHNAGE` in codebase

**Comment by mnigh** [comment]
@petertgiles other than the fact that the directive forms have never being published, any reason not to do this?

**Comment by petertgiles** [comment]
Yeah, it's a typo but it's for a feature that will probably never be released.  Doesn't seem like it's worth the time to me.  :shrug:

**Comment by mnigh** [comment]
> Yeah, it's a typo but it's for a feature that will probably never be released. Doesn't seem like it's worth the time to me. 🤷

[Just in case](https://github.com/GCTC-NTGC/gc-digital-talent/pull/12194) it gets released...😜
