### ISSUE TITLE
✨ URL params for the support page to pre-populate the support form

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#12215]
## ✨ Feature

Create a way for us to pre-populate the support form based on a custom link that sent the user there.

## 🕵️ Details

When a user follows a link for "contact support" or similar, we want to help them out by adding some context to the form. This will help support and the user resolve things faster.

For example, we could add which process the user wants to follow up on, which community the ticket pertains to.

## 🙋‍♀️ Proposed Implementation

There are two relevant input fields on the support page: #subject and #description

The URL params should allow us to set either. For example: (use with caution, Gray wrote this)
`<a href="/en/support?subject=question&description=Add%20your%20question%20here:%0D%0A%0D%0AProcess%20number:%2012345678">`

Tristan says all the weird characters will probably just be handled gracefully by the browser. But regardless, this link should pre-populate the support form with "question" selected for the subject, and the following text in the description field:

```
Add your question here:

Process number: 12345678
```

## ✅ Acceptance Criteria

- [ ] URL params working for the support page

**Comment by tristan-orourke** [comment]
If we want to do more complex things with this later, we could replace the direct subject and description params with a template key.
