### ISSUE TITLE
✨ Add a sign up for updates link to instructor-led training card on training fund page

### ISSUE THREAD

**Issue by NienkeBr** [GCTC-NTGC/gc-digital-talent#12234]
## ✨ Feature

When we published the instructor-led training page, we replaced a link to sign up for updates on the training fund page with a link to the instructor-led training page. We've been asked to also still have the link to sign up for updates.

## 🕵️ Details

https://talent.canada.ca/en/it-training-fund 

Please add a link to "Sign up for updates" on the instructor-led training card on the training fund page.

Please add the "Sign up for updates" link under the "Browse training opportunities" link.

URL to be confirmed by @NienkeBr 

![image](https://github.com/user-attachments/assets/bc1a957c-3bbf-4d76-8d37-61c473612b79)

## ✅ Acceptance Criteria

- [ ] The instructor-led classes and bootcamps card on the training fund page has a link to sign up for updates.

**Comment by tristan-orourke** [comment]
Included in [#12360](https://github.com/GCTC-NTGC/gc-digital-talent/issues/12360)
