### ISSUE TITLE
✨ Add CR-04, PM-05 and PM-06 to the search page

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#12238]
## ✨ Feature

Adding new classifications to the search page.

## 🕵️ Details

CR-04: Clerk
FR: Commis

PM-05: Senior Analyst
FR: Analyste principal

PM-06: Manager
FR: Gestionnaire

## 📸 Screenshot

They should appear in this drop-down.

![image](https://github.com/user-attachments/assets/cee8ac4a-837f-41ab-b18d-b70635aae32d)

## ✅ Acceptance Criteria

- [ ] CR-04, PM-05 and PM-06 appear on the search page select input for classification

**Comment by brindasasi** [comment]
@gobyrne looks like this has been completed already https://github.com/GCTC-NTGC/gc-digital-talent/pull/12139

**Comment by gobyrne** [comment]
Ok, this work was indeed already completed!
