### ISSUE TITLE
✨ Add EX-03, EX-04 and workstream "Executive group" to the Talent Search page

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#12251]
## ✨ Feature

Add EX-03, EX-04 and workstream "Executive group" to the Talent Search page

EX-03: Digital Leader
EX-04: Digital Leader

French for both: _Chef de file du numérique_

## 📸 Screenshot

Add them here
![image](https://github.com/user-attachments/assets/98061f25-fde8-4111-b4cc-0ce494ccccc9)

## ✅ Acceptance Criteria

- [ ] EX-03 and EX-04 added to Talent Search page classification drop-down
- [ ] Executive group workstream added to Talent Search page Stream drop-down

**Comment by mnigh** [comment]
The "Executive Group" `workstream` was added previously in https://github.com/GCTC-NTGC/gc-digital-talent/pull/8422.
