### ISSUE TITLE
🐛 Pool Closing notifications sent out twice on both in-app and email 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#12311]
## 🐛 Bug

On Dec.15 Pool closing notifications for IT-04 Senior Advisor or Manager , IT security has been sent twice on both in-app and email. 

## 🦋 Expected Behaviour

Email notifications for a specific opportunity should be sent only once. 

## 🕵️ Details

Both emails went on 10:00 pm so it doesn't look like the job restarted or something. 

## 📋 Steps to Reproduce

Try checking on Pool closed emails again locally or in our test servers might reproduce the issue. 

## 📸 Screenshot
<img width="1293" alt="Image" src="https://github.com/user-attachments/assets/07ab4109-7ddf-40a4-bd15-6ce32f920b79" />
<img width="1247" alt="Image" src="https://github.com/user-attachments/assets/1413ae6b-58cf-4fec-98dd-f28444651b00" />

![Image](https://github.com/user-attachments/assets/07201c20-87f3-4363-ba16-47f6a4ccbecc)

## ✅ Acceptance Criteria

- [ ] Pool closing soon email for a specific job should be sent out only once 
- [ ] Pool closing soon in-app notification for a specific job should be sent out only once

**Comment by tristan-orourke** [comment]
These are different names 😆
