### ISSUE TITLE
Bug - doctrine/dbal requires php >=8.0.0

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/gc-digital-talent#1249]
# Description
- I found a new error during the `/api` composer install. I believe it started after I merged the new [doctrine/dbal](https://github.com/GCTC-NTGC/gc-digital-talent/pull/1204) update. It looks like it requires us to use PHP8 and above. Should we just revert back to the previous version for now?
![image](https://user-images.githubusercontent.com/22059495/143925562-aca42fc3-2537-47b5-8baf-abc73754fe81.png)

**Comment by mnigh** [comment]
I would recommend going back to [3.1.4 ](https://github.com/GCTC-NTGC/gc-digital-talent/pull/1204) so that it is working again and then we can address #1250 in another issue since it is more involved than reverting back.
