### ISSUE TITLE
Indigenous Vs. Aboriginal

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#1253]
On the Talentsearch site we use the term Aboriginal but on the Admin site (and the search request page) we use the term Indigenous.  It seems we should use the same term across the site.  Do we know which one should be used?
![image](https://user-images.githubusercontent.com/8978655/143947356-f6878ef8-1999-42f9-89e0-a4667f7fbbbd.png)

**Comment by mnigh** [comment]
Change _Aboriginal_ to _Indigenous_
