### ISSUE TITLE
Create a ProdSeeder in api project

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#1267]
# Description
We use Laravel seeders to populate our local environment with data. In some cases, like for CmoAssets and Departments, our seeders contain the exact data we actually want to have in Production. Create a ProdSeeder class which runs all other seeders which are safe and useful to run in production. Ensure it is safe to run this multiple times (ie it will not create duplicates).

**Comment by mnigh** [comment]
Seeders to use for ProdSeeder:
### API
        $this->call(CmoAssetSeeder::class);
        $this->call(OperationalRequirementSeeder::class);
        $this->call(DepartmentSeeder::class);
