### ISSUE TITLE
Inconsistent Pool Candidate table headers and field labels

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#1275]
The table heading **Language** and **Preferred Lang** do not match the associated field labels **Language Ability** and **Preferred Language** for Pool Candidate Table with Create Pool Candidate and Update Pool Candidate.

#### Pool Candidates Table
![Screen Shot 2021-12-03 at 11 37 40](https://user-images.githubusercontent.com/3046459/144640886-d3840d51-a08c-4a5e-8163-d03b872014b5.png)

#### Update Pool Candidate
![Screen Shot 2021-12-03 at 11 38 06](https://user-images.githubusercontent.com/3046459/144640884-35743605-f339-4936-adc5-caedfbcdc7c6.png)

**Comment by tristan-orourke** [comment]
@JoshBeveridge Which version should we use?

**Comment by JoshBeveridge** [comment]
Generally the answer will always be the more descriptive label, assuming it's not too long. In this case the distinction is important too.
