### ISSUE TITLE
Admin - Checkbox label values have appended colon

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#1276]
The colons should be removed as they do not fit with the input's design everywhere they are present in the **/admin** app.

### Screenshot
![Screen Shot 2021-12-03 at 11 38 44](https://user-images.githubusercontent.com/3046459/144642117-aa27adbe-f16e-41e0-b11e-e836ce891cb1.png)

**Comment by mnigh** [comment]
This issue will be resolved as part of #1367.

**Comment by petertgiles** [comment]
PR was a two-parter
