### ISSUE TITLE
Admin - Input label values have appended colon

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#1277]
Remove all instances of these colons to be consistent with the **/talentsearch** app.

#### Talent Search (no colons)
![Screen Shot 2021-12-03 at 12 03 13](https://user-images.githubusercontent.com/3046459/144643362-3734f771-d48d-42fc-aa7f-258133c2fef2.png)

#### Admin (colons)
![Screen Shot 2021-12-03 at 12 02 52](https://user-images.githubusercontent.com/3046459/144643383-36a7002b-832c-4f46-96b6-ae56fea952f6.png)

**Comment by tristan-orourke** [comment]
@JoshBeveridge To colon or not to colon?

**Comment by JoshBeveridge** [comment]
Maybe Jerbo has thoughts on this, but I'm inclined to say no colon... But I don't have a real reason as to why.

**Comment by mnigh** [comment]
> Maybe Jerbo has thoughts on this, but I'm inclined to say no colon... But I don't have a real reason as to why.

Jerbo confirms we are ok to remove the colons.
