### ISSUE TITLE
Recreate the Laravel asset() helper function in Lumen

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#1282]
# Description
In a Laravel blade file, you specify css and js files by wrapping the file name with asset() and mix() helper functions, for example: `asset(mix('css/hydrogen.css'))`. The mix helper function appends a hash to the end of the filename, and the asset helper function uses the ASSET_URL env variable to make it an absolute url.

We've defined an `asset()` helper function in talentsearch, in the file `/bootstrap/helpers.php`, and it does make it an absolute url, but it doesn't seem to take ASSET_URL into account.

For now, can avoid using `asset()` in talentsearch and the relative urls will work. But if we want to use a url prefix like /admin in a lumen project, we will need to make this helper function work properly.

**Comment by mnigh** [comment]
New issue created:

- https://github.com/GCTC-NTGC/gc-digital-talent/issues/3683
