### ISSUE TITLE
Pool Dashboard - update PoolCandidate table with User data

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#132]
# Description
When a Pool Manager is browsing Candidates, they probably want to see User data (name, contact info) at the same time. In the graphql query for the PoolCandidate table, also query for the User attached to each Candidate, and display the following columns in the table:
- Name (user.first and user.last combined into one column)
- user.email
- user.telephone
- user.preferredLang

**Comment by Jerryescandon** [comment]
![image](https://user-images.githubusercontent.com/16977254/124785090-8d6cf480-df14-11eb-9f80-65f14244746c.png)
