### ISSUE TITLE
Common - Storybook Button Radius

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#1360]
Border radius seems not to be working on components even though the attribute `data-h2-radius="b(s)"` is present.

### Screenshots
![Screen Shot 2021-12-06 at 13 05 46](https://user-images.githubusercontent.com/3046459/144899084-fae0b742-91bf-4837-b683-dfa8266c105f.png)

_Originally posted by @mnigh in https://github.com/GCTC-NTGC/gc-digital-talent/pull/1357#pullrequestreview-824293414_

**Comment by yonikid15** [comment]
Add this to common/hydrogen.config.js:
```js
"radius": [
    {
      "key": "s",
      "value": "10px"
    },
    {
      "key": "m",
      "value": "50rem"
    },{
      "key": "l",
      "value": "100%"
    }
  ],
```
