### ISSUE TITLE
🐛 Storybook Color Enum Warning

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#1361]
Warning in console: _Addon controls: Control of type color only supports string, received "enum" instead_ (could be the same [issue raised here](https://github.com/storybookjs/storybook/issues/16322)).

### Screenshots
![Screen Shot 2021-12-06 at 13 07 34](https://user-images.githubusercontent.com/3046459/144899077-1a89a8a3-6d02-4d74-af70-30b5f78930c3.png)

_Originally posted by @mnigh in https://github.com/GCTC-NTGC/gc-digital-talent/pull/1357#pullrequestreview-824293414_

**Comment by vd1992** [comment]
@petertgiles 
This still happening for you? (I'm browsing through things labelled bugs in case you are wondering)

**Comment by petertgiles** [comment]
Yep, for sure.  Seems Button in common is a big culprit.
![image](https://user-images.githubusercontent.com/8978655/173608456-c5d84781-0b69-4199-bd23-2df568f90aa3.png)

**Comment by esizer** [comment]
Was this closed by #6259 ? @mnigh

**Comment by mnigh** [comment]
Closed by #6259.
