### ISSUE TITLE
Admin - Inconsistent input label values for distinguishing language

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#1372]
The **Create CMO Asset** and **Update CMO Asset** forms seem to be the exceptions that use _Name EN_ and _Description EN_.

### Examples

- Name EN vs. Name (English)
- Description EN vs. Description EN (English)

### Screenshots
![Screen Shot 2021-12-07 at 16 04 48](https://user-images.githubusercontent.com/3046459/145107333-a5d664a3-74a1-4376-b2c5-29da4ebf50cc.png)
![Screen Shot 2021-12-07 at 16 05 00](https://user-images.githubusercontent.com/3046459/145107335-f9d60385-d40e-4923-8d36-2bd464e5f81b.png)

**Comment by mnigh** [comment]
@JoshBeveridge which pattern should be followed: _Name EN_ or _Name (English)_?

**Comment by Jerryescandon** [comment]
I will always err on the side of specificity. I prefer _Name (English)_
