### ISSUE TITLE
Refactor talentsearch and admin projects to not involve Laravel/Lumen

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#1387]
# Description
Our react apps don't need to be served via Laravel/Lumen apps. They could be compiled into static files. This would require changes to js compilation, some new html files to replace the blade templates, and changes to htaccess, among other things.

Questions: 
1. Should we combine talentsearch and admin into a single project, with a single set of npm dependencies? In that case, what do we do with the Common folder? Should we use a common public folder for images, js and css, etc, or keep it split up?
2. What bundler would we use? Webpack? We've looked a bit into Vite as well, which looks very nice for local dev

Answers:
1. We can keep components divided up among talentsearch, admin and common directories, but they should all be in the same project, with only a single package.json file. Images, css, etc, may be kept in a single public folder. 
2. We will use webpack. We already use some webpack configuration, though it may need updating.

**Comment by mnigh** [comment]
We will meet as a team to discuss the questions in this issue before estimating.

**Comment by petertgiles** [comment]
A good writeup of how to use a top-level package.json and node_modules directory to support a common project and and two different app projects with npm 7.
https://dev.to/limal/simplify-your-monorepo-with-npm-7-workspaces-5gmj

**Comment by patcon** [comment]
I'm chipping away at getting npm spaces working. This will need a resolution in hydrogen before we can merge all our deps into one workspace package.json: https://github.com/hydrogen-design-system/hydrogen.css/issues/72

**Comment by patcon** [comment]
Bonus: Merging node_modules will bring our file count waaaaaaay down, and so the mounted volumes will be much less slow. I think osx mounts are particularly slow, as setup.sh takes like 10-15 min to run each time. Is that the same for everyone?

**Comment by tristan-orourke** [comment]
Honestly, I'm not sure we even need workspaces. Is there any real downside to making common, admin and talentsearch a single project, with a single package.json file?

**Comment by petertgiles** [comment]
> Is there any real downside to making common, admin and talentsearch a single project

That's an interesting question.  The answer is probably "technically yes but practically no".  Right now the talentsearch bundle can be a bit smaller because it doesn't have a few things like urql auth and react-table.  And we would lose the ability to have different hydrogen configs though right now they are identical.  It could be argued that preventing the projects from diverging is actually a positive thing though.  I would caution that maybe we need some clarity about how the indigenous portal and "other CMO department" will fit into the ecosystem before deciding that.

**Comment by patcon** [comment]
I will admit I was like "ugh workspaces" when I first saw the link dropped (having never found the need for them), but after converting it, it seems like a pretty lightweight transition! And an easy step on the way to a single project, if we want to ditch workspaces later.

I'm also sure that big "theories" of how to organize all the package.json files can consume the oxygen in the room. But if we just want to try it, we can just avoid caring, and then migrating is as easy as:

```
mkdir frontend
git mv admin common frontend/
cd frontend
vim package.json
cat package.json
{
  "name": "frontend",
  "workspaces": [
    "admin",
    "common",
    "talentsearch"
  ]
}
npm install
git rm */package-lock.json
```

plus some docker mount and script updates.

It does all the consolidation in one node_modules and one package-lock.json in `frontend/`. And then the dependabot updates work like a dream <3 https://github.com/patcon/gc-digital-talent/pulls?q=is%3Apr+is%3Aopen+%2Ffrontend

Not ready, but example here: https://github.com/patcon/gc-digital-talent/tree/1387-npm-workspace/frontend (It needs a rebase and conflict resolution, and maybe a rethink of how precious I was about sweeping all the deps from subproject package.json files into the root one)

**Comment by petertgiles** [comment]
Lol, @patcon, you're like a genie that turns ideas into PRs. 🧞
I've never tried workspaces either.  I was just googling around as was like "that sounds like something relevant to the discussion".  I really like what I'm seeing in your branch though!  This seems like a nice way to manage the packages together while still keeping some decoupling between sites.

Good call on leaving auth out.  It will probably be deprecated and then removed at some point in the future.

**Comment by tristan-orourke** [comment]
> Lol, @patcon, you're like a genie that turns ideas into PRs. 🧞

Seconded!

>But if we just want to try it, we can just avoid caring

Good point 😄 Let's go for it.

> Right now the talentsearch bundle can be a bit smaller because it doesn't have a few things like urql auth and react-table

Not that I know anything about bundlers, but I kind of assumed that (with a bit of webpack config) we could still end up with separate bundles for our separate entrypoints, which dependencies only included as necessary.

> And we would lose the ability to have different hydrogen configs though right now they are identical

True. Its possible the Indigenous Apprenticeship Portal and Accessibility Passport will need significantly different looks. But for now at least, admin and talentsearch use the same hydrogen config and mostly the same package.json files. It would be nice to avoid maintaining basically duplicate files.

**Comment by patcon** [comment]
> Let's go for it.

🎉 

> 🧞

haha I've been called "some sort of open source elf", but never that :)

i will admit being overeager to work on this stuff before I start... I know I'll have guilt about dedicating time to these things once I'm officially in, due to ambiguous contribution to user experience.. But yay developer experience!

> I kind of assumed that (with a bit of webpack config) we could still end up with separate bundles for our separate entrypoints

My impression too!

**Comment by patcon** [comment]
I'm on the couch in gathertown if you want a pairing buddy @petertgiles (just wrapping up #1529 as priority)

**Comment by patcon** [comment]
From call with @petertgiles 

- moving react files closer to root. +1 pc
- devserver part
  - maybe defer?
  - spin-out issue todos?
- mix + webpack?
    - https://laravel-mix.com/docs/6.0/extending-mix
- one config per project or one?
    - start with per-project? yes. maybe merge if seems duplicative
- mri for args (2-liner) to keep single webpack env across a few envs, but keep one file
    - https://github.com/compdemocracy/polis/pull/1242/files#diff-d595d4a7af5e68092798ac2af09c8e36399affbcc18151a0c95b4d4eeeb5cd7eR76
