### ISSUE TITLE
Component - Button

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/gc-digital-talent#139]
# Description

Create the [Button component](https://www.figma.com/file/tXs6IdvpuX4jCLBWbJx0C6/Components-and-Patterns?node-id=6%3A15). Depending on the state, the component should follow the format and style guide shown in the wireframe.

- Create a Button component.
- The component will have two variations. A regular button component, and an anchor tag dressed as a button.
- The button props should include label. The label component should be a string, or a react component type, so that we can include icons like in the design. 
- The other props should include ones for styling. Use typescript to limit the different colours that can be used (purple, navy, gold, white).
- There are multiple variations in the designs that needs to be displayed in storybook, therefore the storybook actions should be used to do so.

# Assessment Criteria
  - [ ] Component has all states and follows the format and style guide.
  - [ ] Meets accessibility standards
  - [ ] Responsive (mobile, tablet, laptop)

**Comment by mnigh** [comment]
@JoshBeveridge a few questions related to this issue:

1. is there somewhere in the [Figma Button component](https://www.figma.com/file/tXs6IdvpuX4jCLBWbJx0C6/Components-and-Patterns?node-id=6%3A15) that shows the different states of these buttons such as hover, active, focus, and disabled?
2. how can these states be handled using [Hydrogen](https://github.com/hydrogen-design-system/hydrogen.css) data attributes?

**Comment by mnigh** [comment]
> @JoshBeveridge a few questions related to this issue:
> 
> 1. is there somewhere in the [Figma Button component](https://www.figma.com/file/tXs6IdvpuX4jCLBWbJx0C6/Components-and-Patterns?node-id=6%3A15) that shows the different states of these buttons such as hover, active, focus, and disabled?
> 2. how can these states be handled using [Hydrogen](https://github.com/hydrogen-design-system/hydrogen.css) data attributes?

Answers:
1. [Figma designs to come](https://www.notion.so/Add-States-to-Buttons-62f7bc382a45426892e828436b12e416).
2. @JoshBeveridge is working on ability for hover (and other states to follow) to be controlled via data attributes in Hydrogen.
