### ISSUE TITLE
Storybook - Static assets not loading

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#1455]
There are some static assets not loading correctly in the Storybook for the admin site, on the pool dashboard component.  It might be related to #1377 or it might be that the upgrade to Storybook 6.4.9 has reverted something.

![image](https://user-images.githubusercontent.com/8978655/145833806-5880edee-c0b8-4bcf-9809-bfe91df03bbf.png)

**Comment by mnigh** [comment]
This should probably be fixed, but, what is the point of a Storybook story for the `PoolDashboard` component if the `AuthContainer` and `ClientProvider` components aren't mocked which it relies upon?

**Comment by mnigh** [comment]
The static assets issue is also an issue for **talentsearch** in Storybook (as well as its path for `/graphql`).

![Screen Shot 2021-12-14 at 10 11 20](https://user-images.githubusercontent.com/3046459/146025352-1856fe39-35e6-4655-99bc-eddb0dfe947d.png)
