### ISSUE TITLE
Factor server-side auth code into its own Laravel subproject

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#1461]
# Description
Create a new Laravel project and move the login functionality from /admin to this new project. That means the `/login` and `/auth-callback` routes, and the AuthController.

This will require some modification of the root htaccess file. Ensure it is still possible to log into the admin dashboard.

**Comment by yonikid15** [comment]
Putting this on hold and adding back to Product backlog until the CATS epic is completed.

**Comment by petertgiles** [comment]
After a chat with Tristan we decided to do this by converting /api to a full-Laravel project and integrating the AuthController into it.
