### ISSUE TITLE
Testing -  Add jest support to GC Digital Talent repo and add some sample unit tests

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#1464]
We would like to add some component level testing into our codebase and we think Jest would be right choice for our react components. 

Objective of this issue is 

- add the infra support for jest
-add sample tests

Nice to have 
- add support for viewing code coverage by component-wise

**Comment by mnigh** [comment]
Include basic documentation on our testing methodology in the `README.md `(root).
