### ISSUE TITLE
Create Security Policy on GitHub

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#1469]
> You can give instructions for how to report a security vulnerability in your project by adding a security policy to your repository.

This is basically to provide a way of reporting any security vulnerabilities related to our project.

(source: https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository)

### Acceptance Criteria

- [ ] GitHub repository has a simple `SECURITY.md` file

**Comment by mnigh** [comment]
Choose an email for receiving reports.

**Comment by patcon** [comment]
+100 to this

I'd recommend this as not just on GitHub, but also on the website proper. De-dupe of info where possible.

Let's also make use of security.txt: https://securitytxt.org/

Also, worth mention "bug bounty" program, and clarity on whether it exists or not, and to what degree.

Here's what CDS uses for the their security notice:
https://digital.canada.ca/legal/security-notice/#:~:text=and%20welcoming%20way.-,Bug%20bounty,-Unfortunately%2C%20CDS%20doesn%27t

**Comment by patcon** [comment]
Maybe related: responsible disclosure policy and documentation in the places professionals know to look.
- https://hackerone.com/deptofdefense
- https://www.cbc.ca/news/science/canadian-government-hackers-1.3866336

**Comment by gobyrne** [comment]
@patcon @mnigh do you need input from design for content on this or similar? I don't feel strongly about it if you have other examples to pull text from.

**Comment by mnigh** [comment]
@gobyrne there could be some legal stuff involved here, so i'm not sure what is required to include, what is ok to include, and what is not to include. @patcon did link to [CDS's Security Policy](https://digital.canada.ca/legal/security-notice/) [before](https://github.com/GCTC-NTGC/gc-digital-talent/issues/1469#issuecomment-1111525135), though it is hosted on their website and linked to from their GitHub repos (example: https://github.com/cds-snc/digital-canada-ca/security/policy). It might serve as a template for ours, but would require some changes (for example, they link to a hosted form to submit vulnerabilities so unless we want to create that, we would need to remove that).

**Comment by mnigh** [comment]
Also worth noting, the original estimate of 1️⃣ was for using GitHub's template and having a one sentence in English and French linking to an email address where someone could report a vulnerability.

**Comment by mnigh** [comment]
Simple example:
- https://github.com/cds-snc/gc-articles/blob/main/SECURITY.md

**Comment by mnigh** [comment]
@marc-donofrio does it make sense to send security issues through [gctalent-talentgc@support-soutien.gc.ca](mailto:gctalent-talentgc@support-soutien.gc.ca) or should they go to the generic inbox instead [GCTalentGC@tbs-sct.gc.ca](mailto:GCTalentGC@tbs-sct.gc.ca)?

**Comment by petertgiles** [comment]
Tristan answer: use support box
