### ISSUE TITLE
Talent Search - Unselect education requirement

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#1474]
In the Talent Search search page the filter for the education requirement is a set of radio buttons where none of the options are selected by default.  However, there is no way to unselect one of the options if one of them is accidentally selected and the user does not want any filters.

![image](https://user-images.githubusercontent.com/8978655/146385937-2f0caa90-2577-46c9-9547-e7f5caf381a7.png)

If the first option is the "default, no filters" options then the form should be probably start off with this option selected.  Otherwise the form starts in a state that the user cannot revert back to.

**Comment by petertgiles** [comment]
@tristan-orourke , agree with starting the form with the first option selected?

**Comment by tristan-orourke** [comment]
Yes, starting with the first option selected makes sense. We should also double check the back-end, to ensure that this option does not filter anyone out.
