### ISSUE TITLE
My Skills - Added Skills component 

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/gc-digital-talent#1477]
# Description
- This is the section of the Experience form which shows "Skills attached to this experience". This shows the skills pill list format. 
- Skill pills should be clickable, which calls a removeSkill handler function passed into the component
- It should show some null state text when the list is empty
- If the list has more than 6 skills, show warning text in a yellow box

Question: what's the null state?

**[Experience Form](https://www.figma.com/proto/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?node-id=2340%3A4352&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A2)**

Acceptance Criteria:
- [x] Create AddedSkills component with correct format and styling
- [x] A storybook story to view the component
- [x] Shows null value when there are no skills
- [x] Shows "That's a lot of skills" text when 6 or more in list
- [x] Pills are clickable
- [ ] Simple Jest tests

**Comment by petertgiles** [comment]
Comments:
- "too many skills" notification should not be dismissable
- skill chips could be alphabetical or in order added
- skill chip should have only the X clickable
