### ISSUE TITLE
My Skills - Search bar

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/gc-digital-talent#1479]
# Description
- The skills section of the candidate profile requires a place where candidates can search for a specific skill. Therefore, we need to search bar, that will dynamically update the skills results when a user enters a skill. The issue only requires building the front-end component, which includes creating an input of type search. The search input should be in a self-isolated form (using react-hook-form). There is an excellent [example](https://github.com/GCTC-NTGC/TalentCloud/blob/dev/resources/assets/js/components/SearchBar.tsx) on the Talent Cloud app, which can be used as a reference (heads up! we want to use react-hook-form, not Formik).

**[My Skills wireframe](https://www.figma.com/proto/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?node-id=1760%3A4320&scaling=scale-down-width&page-id=0%3A1&starting-point-node-id=1726%3A3054)**

Acceptance Criteria:
- [x] Build search bar component with input `type=search`
- [x] The form values type should include a `query` value
- [x] The handle submit method prop should take a query as a parameter, and return a `Promise<void>`

**Comment by petertgiles** [comment]
PR  #1645 was merged successfully
