### ISSUE TITLE
API - Class TestUser fails all tests

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#1480]
When running the PHPUnit tests within the class TestUser, all three of the tests result in failures: "No authorization token found.".

### Steps to reproduce
1. `cd infrastructure`
2. `docker-compose exec -w /var/www/html/api php sh -c "./vendor/bin/phpunit tests/UserTest.php"`

**Comment by mnigh** [comment]
We would first need to generate an access token. Then, we would need to use the [postGraphQL function](https://github.com/nuwave/lighthouse/blob/master/src/Testing/MakesGraphQLRequests.php#L65-L83) instead of the graphQL function to be able to pass the access token (Bearer token) via a request header.

**Comment by petertgiles** [comment]
@tristan-orourke Should this have been closed?  The tests are still broken.

**Comment by tristan-orourke** [comment]
If the tests are still broken, I'm not sure why it was closed :/
I'll reopen it

**Comment by mnigh** [comment]
> If the tests are still broken, I'm not sure why it was closed :/ I'll reopen it

It looks like the tests were [marked to be skipped](https://github.com/GCTC-NTGC/gc-digital-talent/pull/1993/files#diff-bc714e73f0e228fef8e2aba3bf3ed22a0ac1cc80d1b2f480913cf775945ddfff) in #1993.
