### ISSUE TITLE
Pool Dashboard - Create a react-admin Data Provider for communicating with GraphQL API backend

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#15]
# Description
React-admin relies on a Data Provider to adapt its own query functions to the backend. Set up the adapter for queries and mutations related to Users and Candidates.

**Comment by mnigh** [comment]
A custom GraphQL data provider will be required as [hasn't been migrated to TypeScript yet](https://github.com/marmelab/react-admin/issues/6124). The package [ra-data-graphql](https://github.com/marmelab/react-admin/tree/master/packages/) might be helpful in building a custom GraphQL data provider.

**Comment by tristan-orourke** [comment]
We've decided to not use react-admin for our dashboard.
