### ISSUE TITLE
Get approval from security to go live

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#1522]
# Description
I know this involves talking to Bruce Barret, an App Scan, updating the System Description, and a lot of acronyms: SIA (Security Impact Assessment), SIP (Security Implementation Plan), SAAR (???). Still fuzzy on the details.

**Comment by tristan-orourke** [comment]
Our work seems to be done, just waiting for VA scan improvements now

**Comment by patcon** [comment]
Do they let us know what tools they run on our app/environment? (specifically wondering about "app scan")

I'm wondering if we can run the same scans. I'm guessing "app scan" might be the typical owasp suite that's standard enterprisey stuff. Which conveniently there are some well-supported github actions implementing :)

https://github.com/marketplace/actions/owasp-zap-baseline-scan
https://github.com/marketplace/actions/owasp-zap-full-scan

**Comment by tristan-orourke** [comment]
Good point @patcon, I'll ask what software they're using.

In the meantime, I'm going to close this issue. We've done the work described in the issue, fuzzy as it was. Any new work that comes up can be defined in a new issue.
