### ISSUE TITLE
Reference config variables instead of env variables in BearerTokenServiceProvider

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#1524]
# Description
Accessing configuration variables with the config helper (eg `config('app.timezone')`) instead of the env helper (eg `env('APP_TIMEZONE')` makes it possible for Laravel to cache the variables to improve performance.

**Comment by tristan-orourke** [comment]
Okay, this is actually in a Lumen project, which does not cache env variables, but using the `config()` helper still allows us to define default values, like 'UTC' for timezone, and is good practice.

**Comment by tristan-orourke** [comment]
Oh, this is annoying, but it turns out the lack of a default value can cause issues on the server, as env variables aren't generally available during the build step.

**Comment by petertgiles** [comment]
> it turns out the lack of a default value can cause issues on the server

@tristan-orourke, could you explain what this means?  For the auth variables I don't think it's possible to provide reasonable default values.  Right now [the logic checks if a variable is missing](https://github.com/GCTC-NTGC/gc-digital-talent/blob/95be35ad40f45ca6e4f16cecc1f5098582a0be5e/api/app/Providers/BearerTokenServiceProvider.php#L19) to switch between local auth and SiC.  Would it work to assign an empty string as a default value?  I should be able to handle that in the logic.

**Comment by petertgiles** [comment]
@tristan-orourke 👀

**Comment by tristan-orourke** [comment]
@petertgiles It's actually APP_TIMEZONE being null which caused an error on the server, and this wouldn't be the case if we used `config('app.timezone')` instead of `env('APP_TIMEZONE')`.

You're right that the AUTH_SERVER env variables don't have appropriate default values, but they can still be registered in config files (without default values), allowing for Laravel to cache them.

**Comment by petertgiles** [comment]
Awesome, thanks, it's clear to me now.
