### ISSUE TITLE
Open Redirect Vulnerability

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#1530]
From [PR #1478](https://github.com/GCTC-NTGC/gc-digital-talent/pull/1478):

I'm concerned about this feature adding an [open redirect vulnerability](https://sec.okta.com/articles/2021/02/stealing-oauth-tokens-open-redirects) to the site.  For example, if there was a link to http://llocalhost:8000/admin/login?from=badsite.evil then the token could be stolen.  I have limited to redirect to accepting only relative urls starting with / but we could still be vulnerable to an open redirect chain.  We could discuss whitelisting valid redirect URLs or using named urls as suggested [here](https://www.netsparker.com/blog/web-security/open-redirect-vulnerabilities-netsparker-pauls-security-weekly/).

**Comment by gggrant** [comment]
Timebox: 2 hours.

**Comment by tristan-orourke** [comment]
We handled this by only allowing path redirects (ie not changing the url domain)
