### ISSUE TITLE
My Skills - Create accordion component

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/gc-digital-talent#1534]
# Requirements
- can open/close on click/`enter`
- the component needs to accept complex children (including other accordions)
- the whole title area and icon should be the event target/trigger
- the trigger should be focusable using `tab`
- the trigger should indicate, using `aria-expanded` whether it is expanded or collapsed
- the contents of the accordion should be hidden from screen readers until it is expanded using `aria-hidden`
- the focusable elements in the contents should be tab targetable only when the accordion is expanded
  - you'll likely need to use `tabindex` to accomplish this

# Data
- title
- subtitle
- content/children
- icon
- default state (i.e. should it be open or closed by default?)

# Look and feel
### Collapsed
![image](https://user-images.githubusercontent.com/6960386/148253583-13169fa3-4afb-4e34-863e-ecc5f0a0b3c0.png)

### Expanded
![image](https://user-images.githubusercontent.com/6960386/148253711-b030e538-c0c7-4ef8-8508-93130c500d82.png)

### Collapsed
![image](https://user-images.githubusercontent.com/6960386/148252303-343bda25-08d8-40b9-9c0e-4d0e30f26007.png)

### Expanded
![image](https://user-images.githubusercontent.com/6960386/148252377-1894fc8f-e591-4c78-b091-9c7db36007f6.png)

### With icon
💡**Note**: that the icon can be anything - this icon is just an example, but all should be sized the same way.

![image](https://user-images.githubusercontent.com/6960386/148252441-e2029e33-3c10-4ebd-a590-7f55b4f1781c.png)

**Comment by JoshBeveridge** [comment]
I've updated the accordion component in the Figma documentation to better reflect our discussions, as well as to include new property information.

https://www.figma.com/file/5w15OeN9YiOR4UX0XKW7so/Digital-Talent---Design-documentation?node-id=0%3A1
