### ISSUE TITLE
My Skills - Create skill families in the backend

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#1539]
# Description

Skill Families are groups of skills, and fall into one of several Skill Categories. In the graphql schema, they can be modeled like this:
```
enum SkillCategory {
  TECHNICAL
  BEHAVIOURAL
}

type SkillFamily {
  id: ID!
  name: LocalizedString!
  description: LocalizedString!
  skills: [Skill]
  category: SkillCategory!
}
```
The SkillFamily relationship should also be added to the Skill definition in the graphql schema:
```
type Skill {
  ...
  families: [SkillFamily]
}
```
Skills to SkillFamilies is a many-to-many relationship, as a few skills can belong to multiple overlapping families. This can be accomplished in the database with a pivot table.

# Definition of done
- [ ] Migration which adds SkillFamilies table to DB
- [ ] Migration which adds skill_skill_family pivot table
- [ ] Eloquent model for SkillFamily
- [ ] Add family relationship to Skill eloquent model
- [ ] A SkillFamilyFactory, linked to Eloquent model.
- [ ] DevSeeder should ensure all skills have an associated SkillFamily. Each family should have 5-10 skills.
- [ ] New types added to graphql schema. Skill type updated in schema.

**Comment by tristan-orourke** [comment]
@petertgiles After checking with Lindsay, it turns out there are _some_ skills which can be in multiple overlapping families. That makes Skill to SkillFamilies a many-to-many relationship, requiring a pivot table in the database. I'll update the issue description accordingly.

**Comment by petertgiles** [comment]
@tristan-orourke is it intentional that SkillFamily does not have a `key` field like Skill?  It would make seeding simpler if there was one.
