### ISSUE TITLE
My Skills - Add skill to user api mutation

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#1541]
# Description
Create a graphql mutation which takes a user id and a list of skill ids, and updates the skills associated with the user. (The Laravel [sync](https://laravel.com/docs/8.x/eloquent-relationships#syncing-associations) method might be useful here.)

The mutation should look something like
```
updateUserSkills(userId: ID!, skillIds: [ID]!)
```

**Comment by tristan-orourke** [comment]
Unnecessary with the new designs

**Comment by mnigh** [comment]
> > Unnecessary with the new designs
> 
> @tristan-orourke can the issue be closed then?

@tristan-orourke any objection to closing this issue as stale?

**Comment by tristan-orourke** [comment]
> > an the issue be closed then?
> 
> @tristan-orourke any objection to closing this issue as stale?

@tristan-orourke has no objection.
