### ISSUE TITLE
My Skills - Build List My Skills Component

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#1546]
# Description
A component which lists the skills currently attached to a user's account. Divides them into two lists: those already linked to at least one Experience, and those not linked to any Experience.

QUESTION: need some finalization on the designs.

QUESTION: what should the arguments to the component be? Simply two lists of skills, or one list of all the user skills plus a list of user Experiences, and then this component figures out the two lists itself?

**[My Skills wireframe](https://www.figma.com/proto/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?node-id=1760%3A4320&scaling=scale-down-width&page-id=0%3A1&starting-point-node-id=1726%3A3054)**

**Comment by tristan-orourke** [comment]
the My Skills section has been removed from designs, as skills are now only added via Experiences
