### ISSUE TITLE
My Skills - Build Dismissible Notification

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#1547]
# Description
Build a reusable component for dismissible notifications. It should be a grey coloured box with a yellow dismiss button on the right. Besides the button, the content of the box should be passed in with the children parameter. When the Dismiss button is clicked, the box should no longer be rendered (can return null).

QUESTION: where should the dismissal be recorded?
- In the browser? That would make it device specific. Do we use a cookie or local storage?
- In the user account, via API? That would make it remember your dismissals across devices. But we couldn't use this solution on pages accessed by guests.

**[Wireframe of a page with dismissible notification](https://www.figma.com/proto/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?node-id=1760%3A4320&scaling=scale-down-width&page-id=0%3A1&starting-point-node-id=1726%3A3054)**

# Definition of 

- [ ] Story for this component in storybook
- [ ] Unit tests for the component not rendering after button clicked.

**Comment by petertgiles** [comment]
Not needed for MVP

**Comment by mnigh** [comment]
@brindasasi is this issue still relevant or can it be closed?

**Comment by brindasasi** [comment]
I think it is not needed any more. but @gobyrne could you confirm?

**Comment by gobyrne** [comment]
Indeed, closing
