### ISSUE TITLE
Remove duplicate lodash in admin bundle.

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#1597]
Lodash appears to be bundled twice in the admin bundle.  Once for the site and once for common.  Can the duplicate copy be removed?![admin_bundle.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/355fc94b-3d37-44fa-ba50-a3d3384434fe)

**Comment by patcon** [comment]
Is this taken care of in #1673 ?

**Comment by tristan-orourke** [comment]
I think the easiest way to fix this is just to continue with combining our react projects into a single project #1387

**Comment by petertgiles** [comment]
Seems like this was solved by the project merge.  Yay!![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/4726075b-9c73-45cb-8c53-4ca6e7ddc398)

**Comment by tristan-orourke** [comment]
@petertgiles where did that visualization come from?

**Comment by petertgiles** [comment]
https://laravel-mix.com/extensions/bundle-analyzer

**Comment by patcon** [comment]
@petertgiles Think it's worth adding to repo? I find it helpful to see what happened when bundlesize jumps

**Comment by petertgiles** [comment]
I don't use it often so I'm not sure I would want it running on every build.  Perhaps it could be added to repo but leave the entry in the mix file commented out?  Then you could easily enable it just when you wanted to inspect the bundle.  On the other hand, we have an open issue to remove mix so it's a limited benefit right now.

**Comment by patcon** [comment]
Re: how to include non-intrusively.

Assuming `mix` works like `webpack`, I've historically added this to the top of webpack config (after install the small [`mri`](https://github.com/lukeed/mri) package):

```js
const mri = require('mri');
// CLI commands for deploying built artefact.
const argv = process.argv.slice(2)
const cliArgs = mri(argv)
```

This allows for `webpack --analyze` (which is not normally a flag), using `cliArgs.analyze` in the code, which can be checked to optionally merge in plugin config like so:
https://github.com/patcon/polis/blob/2b03976d5ba2746d664855c496fd626ef33c301e/client-admin/webpack.config.js#L76

```json5
// admin/package.json
  "scripts": {
    // ...
    "production": "mix --production",
    "analyze": "mix --production --analyze"
  }
```

**Comment by petertgiles** [comment]
@patcon, haha, I should have known you would have a more elegant approach.  I've opened issue #1873 to discuss this.  I'm not sure I'm convinced there's much value to adding this until we've moved from Laravel+Mix to regular Webpack but I certainly won't stand in your way. 😁
