### ISSUE TITLE
Convert .htaccess rewrite rules to nginx

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/gc-digital-talent#1647]
Required for PHP8 upgrade in the Azure environment.

https://azureossd.github.io/2021/09/02/php-8-rewrite-rule/index.html

## To Do
- [ ] consolidate docker's .htaccess into one apache config
- [ ] convert single apache config into nginx format (use online converters?)

## Spin off concerns

`AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.21.0.4. Set the 'ServerName' directive globally to suppress this message`
we're getting the above warning in apache logs. it doesn't seem to cause any issue (serves fine), but is prob worth fixing. Issue is probably in the mock-auth apache site config. will need to ensure fresh login still works when changed.

**Comment by patcon** [comment]
I've got my eye on this one, and have run some tests with docker/nginx. I'll share early if I get to it

Intention:
- Create a docker setup that uses nginx, but without removing original apache support right away. Try to support both working at once, so migration isn't rushed, and other pieces (prod server) can happen whenever.

**Comment by esizer** [comment]
@petertgiles Maybe something that you may be closing?

**Comment by mnigh** [comment]
Estimate?

**Comment by petertgiles** [comment]
> Estimate?

Freebie!  Do we estimate it if closing it is just a side-effect of a PR for another issue?

**Comment by yonikid15** [comment]
#4582 Fixed by this PR
