### ISSUE TITLE
Skills - Create a relationship between Skills and Users in the backend

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#1648]
# Description
Each user should be able to link skills to their profile. To represent this in the database, we can use a skills_users pivot table: a table with user_id and skill_id columns.

Modify the graphql schema to add skills to a User type 
```
type User {
  ...
  skills: [Skill]
}
```

# Definition of done
- migration which creates pivot table
- add relationships to User and Skill eloquent models
- In DevSeeder, associate some number of skills with each user created
- add skills to User type in graphql schema

**Comment by tristan-orourke** [comment]
Unnecessary with current designs

**Comment by brindasasi** [comment]
removing the epic as we are not doing this

**Comment by mnigh** [comment]
> removing the epic as we are not doing this

@brindasasi can this issue be closed as stale then?

**Comment by brindasasi** [comment]
This is stale now
