### ISSUE TITLE
CMO can add applicants who filled out their own profile to a Pool

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#1676]
# Description
After Applicants fill out their own profile, there must be a way for CMO to add them to a pool.

QUESTION: how this works still needs to be discussed.

Some questions/concerns:
- PoolCandidate is currently a pool-specific data model. We could treat it as a snapshot of the profile, and create a way for CMO to instantiate a snapshot and add it to the pool. But is this what we want? If an applicant updates their profile, do we want to new data reflected in the Talent Search?
- How does CMO explore applicants? Can they browse applicant profiles through the admin dashboard? Can applicants request inclusion to a pool? Is it based on prior email communication?
- How, and to what extent, can applicants control how visible they are to CMO and/or managers?

**Comment by gggrant** [comment]
Duplicated in design backlog.

**Comment by gggrant** [comment]
Duplicated in design backlog.
