### ISSUE TITLE
Generic Pagination component

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#1678]
# Description
Create a generic component to handle simple pagination. It should take a list of elements or components, and the number of elements per page. It should display a subset of the items in an unordered list. It should keep track of current page in internal state, and display buttons at the bottom showing navigation controls for the page.

See the Skill Results under the Search Skill By Keyword section of the Experience Form for an example:
**[Experience Form wireframe](https://www.figma.com/proto/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?node-id=2340%3A4352&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A2)**

After completing the component, with a storybook story, add it to the Skill Result component (#1482).

Question: What exactly should the controls be? (eg First & Last plus the 5 pages around current? Or Prev and Next?)
Question: What should be the max number for Skill Results?

**Comment by petertgiles** [comment]
Comments:
- Handles already-loaded dataset
- Example: skills -> "Search by keyword"
- Generic element: no assumptions about what is being paginated
- Parameter for number of items on page
- If items list if fewer than one page then hide the controls
