### ISSUE TITLE
Streamline manual user registration

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#1689]
It sounds like we will be manually registering new users to the application, at least in phase 1.  Is there a way for us to look up sub values for a given user ID or will we have to rely on the user to tell us?  How will they get their own sub value?  Should we display it on the page somewhere so they can copy/paste it easily to send to us?  Or should we have the API server log unexpected sub values so we can pull them out of the log?

**Comment by tristan-orourke** [comment]
Logging unexpected values is a good idea! 

Ultimately, we probably want to redirect them to a registration page,

**Comment by petertgiles** [comment]
Need to look at it with designers.

**Comment by tristan-orourke** [comment]
Turns out we're already logging unknown sub values, great! That fact, along with #1898, I believe cover the spirit of this issue. I'll close this now.
