### ISSUE TITLE
Proposal: Publish storybook for each PR using Chromatic

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#1691]
Right now, we're including component stories in the definition of done, which is rad :)

But review of the components requires pulling locally and spinning up the storybook. And for less technically inclined team members, this might mean they have to rely on someone else to show them, or just withhold feedback and wait for a post-merge deploy. It also prevent PR reviews while on the phone in bed 🙃 #WorkLifeBalanceFail

[Chromatic](https://www.chromatic.com/) is a service that has a paid tier for visually reviewing and diffing components, but is also commons used for **free hosting of per-pullrequest Storybooks**.

And example PR is here: https://github.com/patcon/gc-digital-talent/pull/3

<img width="887" alt="Screen Shot 2022-01-12 at 6 16 31 PM" src="https://user-images.githubusercontent.com/305339/149238239-b326ef7c-bac3-4d67-928d-cf645d036709.png">

Down in the status checks, clicking the "**Details**" link beside "**Storybook Publish**" will bring anyone to the full storybook:
https://61de6c057fec2d003a9bc22f-wyxdorhdgr.chromatic.com/

I've added some logic to merge all our storybooks just for this CI build in GitHub Actions, since Chromatic scripts are really meant to work on a single storybook. (The "UI Tests" status check is something we can ignore, since I'm not suggesting we make use of that feature of Chromatic. Having said that, that's an option later, if we'd like. Note that I checked into it, and I'm unable to hide that check.)

The storybook link at the bottom is updated for every commit, but each commit's published storybook continues to be available by clicking any past commit "status mark":

<img width="602" alt="Screen Shot 2022-01-12 at 6 18 25 PM" src="https://user-images.githubusercontent.com/305339/149238482-a71c6f95-d10a-48af-bdd3-fca83a369181.png">

The code required to make this work was as minimal as possible, and if you'd like me to create a PR, this is the diff:
https://github.com/GCTC-NTGC/gc-digital-talent/compare/main...patcon:publish-storybook

Noteworthy:
- Added a workflow to build/deploy a storybook to chromatic
- Modified `admin`'s storybook config so that `MERGE_STORYBOOKS=true npm run storybook` builds a single omni-storybook that includes `common`, `admin`, `talentsearch`. Running commands without the envvar will build as it always did.
- I've added `generated/lighthouse-schema.graphql` back into version control. This might require discussion, but I believe that committing certain intermediary artifacts will make future CI efforts easier/faster. This was specifically required because that file is an artifact generated from the working [php] API app. Which requires building the whole PHP application in order to generate. (Right now, I can't even get the PHP application to build in CI, due to #1641, so not committing this would be a block.)
  - I can imagine a concern that this committed file would get out of sync with the generated one. To mitigate, we could later add another validation workflow, to confirm in each PR that the committed graphql file is in-sync with a generated one.
- I migrated `talentsearch/resources/js/stories/HomePage.stories.tsx` story from the old format to the new CSF one, to side-step a bug that broke building of the omni-storybook

Curious your thoughts! Let me know submitting a PR upstream would be considered. If so, we could do a more specific code review that way :)

**Comment by patcon** [comment]
Ah, and Chromatic has unlimited collaborators for projects, so there's no restriction there. It just requires permission to **read/write PR status checks** -- it **doesn't need read/write permission on the code**, since the GitHub Action workflow just publishes by pushing to their service.

**Comment by patcon** [comment]
Note: This would also unblock https://github.com/GCTC-NTGC/gc-digital-talent/pull/1449, as we can used the version-controlled `.graphql` file to simply build the bundles and check their sizes, without needing to get the API app working

**Comment by petertgiles** [comment]
Wow, this is very cool!  This could be a great way to get the designers in on PR reviews.

The provided diff looks pretty lightweight, too.  I like your idea of adding a check to make sure the graphql schema is up to date.  I'll bring up this project in the standup today.

**Comment by patcon** [comment]
Merged in #1692 🪨
