### ISSUE TITLE
Testing - Set up github actions to run jest and phpunit tests

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#1693]
A/C
* Add Individual workflow  file for Jest ,  Php unit tests and linting
* Jest & Php tests status checks should be successful for PR to be successful
* Linting failures should not fail the PR

**Comment by patcon** [comment]
I'd be happy to pick this up :) I figure once I start, I'll prob be needed on more user-facing tasks, but for now happy to be an infra-gremlin haha
