### ISSUE TITLE
Allow dev server to run data seeders

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/gc-digital-talent#1763]
Seeders already exist. Need to ensure dev has the dev dependencies required to run the seeders.

**Comment by petertgiles** [comment]
I've confirmed that the same user account will get different `sub` values for different client IDs.  For example, redirect for local dev vs azuer dev vs azure uat.

**Comment by tristan-orourke** [comment]
This involves creating two build artifacts, one which includes dev dependencies (in order to run faker) and one which doesn't.

**Comment by tristan-orourke** [comment]
@petertgiles pointed out that if we create a seeder class which doesn't rely on any Faker-generated data, it may be able to run using the same artifact as Prod!
