### ISSUE TITLE
Fix broken build after package upgrades

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#1777]
Re-ticketed from https://github.com/GCTC-NTGC/gc-digital-talent/issues/1775#issuecomment-1014882009

Looked back over github action log failures to see where it started: https://github.com/GCTC-NTGC/gc-digital-talent/actions/workflows/storybook.yml?page=7

Seems this is two errors from diff package upgrades, but one is masking the other:
1. one has to do with upgrades to `react-intl` (specifically in either common or talentsearch, not admin): https://github.com/GCTC-NTGC/gc-digital-talent/runs/4841948969?check_suite_focus=true#step:6:69 and
    ```
    ERR! [tsl] ERROR in /home/runner/work/gc-digital-talent/gc-digital-talent/talentsearch/resources/js/components/request/CreateRequest.tsx(55,28)
    ERR!       TS2345: Argument of type 'import("/home/runner/work/gc-digital-talent/gc-digital-talent/talentsearch/node_modules/react-intl/src/types").IntlShape' is not assignable to parameter of type 'import("/home/runner/work/gc-digital-talent/gc-digital-talent/admin/node_modules/react-intl/src/types").IntlShape'.
    ```
2. one has to do with `react-hook-form`: https://github.com/GCTC-NTGC/gc-digital-talent/runs/4841948009?check_suite_focus=true#step:6:66
    ```
    ERR! [tsl] ERROR in /home/runner/work/gc-digital-talent/gc-digital-talent/talentsearch/resources/js/components/request/CreateRequest.tsx(173,38)
    ERR!       TS2345: Argument of type 'SubmitHandler<FormValues>' is not assignable to parameter of type 'SubmitHandler<FieldValues>'.
    ERR!   Type 'FieldValues' is not assignable to type 'FormValues'.
    ERR!     Type 'FieldValues' is missing the following properties from type 'Pick<CreatePoolCandidateSearchRequestInput, "fullName" | "email" | "jobTitle" | "additionalComments" | "poolCandidateFilter">': fullName, email, jobTitle, poolCandidateFilter
    ```

EDIT: oops. react-hook-form link fixed.

**Comment by patcon** [comment]
cc: @tristan-orourke this ability to do quick investigation right away in past build logs is actually the benefit of per-package updates and CI that i'd be sad to lose by leaning into a habit of manually upgrading packages in one PR :) With per-package updates, even when a regression is uncovered (even a week later) that didn't previously have coverage to expose it, we can use `git bisect` to auto-run the new test until the failing one is narrowed down, which determines the specific package update that introduced it :)

```
git bisect start HEAD known-good-tag-or-commit --
git bisect run cypress run --spec mynewtest.spec.js
```

If we batch them, and then discover one portion of the upgrade started the issue, then we'll need to re-tease them apart.

**Comment by patcon** [comment]
Ah oops. Seeing it got resolved...! 🎉  https://github.com/GCTC-NTGC/gc-digital-talent/issues/1769

(Guessing the other had to do with common/talentsearch/admin being outta sync)

Sorry if I stepped on toes! I felt responsible for introducing a workflow that was creating noisy failures 😞

**Comment by tristan-orourke** [comment]
@patcon You make a very good point about the value of updating each dependency in separate commits/PRs! I'll link your comment in #1768
