### ISSUE TITLE
Create Experience models in Backend

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#1787]
# Description
There are 5 types of skill. While they share similarities, each one needs its own type definition, model, and database.
```
type WorkExperience {
  id: ID!
  role: String
  organization: String
  division: String
  startDate: Date
  endDate: Date
  currentlyActive: Boolean
  details: String
}
type PersonalExperience {
  id: ID!
  title: String
  description: String
  startDate: Date
  endDate: Date
  currentlyActive: Boolean
  details: String
}
type CommunityExperience {
  id: ID!
  title: String
  organization: String
  project: String
  startDate: Date
  endDate: Date
  currentlyActive: Boolean
  details: String
}

enum EducationStatus {
  COMPLETE_CREDITED
  COMPLETE_UNCREDITED
  IN_PROGRESS
  AUDITED
  INCOMPLETE
}
enum EducationType {
  DIPLOMA
  BACHELORS
  MASTERS
  PHD
  POST_DOCTORAL
  ONLINE_COURSE
  CERTIFICATION
  OTHER
}  
type EducationExperience {
  id: ID!
  institution: String
  areaOfStudy: String
  thesisTItle: String
  startDate: Date
  endDate: Date
  currentlyActive: Boolean
  type: EducationType
  status: EducationStatus
}

enum RecipientType {
  SELF
  TEAM
  PROJECT
  ORGANIZATION
}
enum RecognitionType {
  INTERNATIONAL
  NATIONAL
  PROVINCIAL
  LOCAL
  COMMUNITY
  ORGANIZATIONAL
  DIVISIONAL
}
type AwardExperience {
  id: ID!
  title: String
  issuedBy: string
  awardedDate: Date
  recipientType: RecipientType
  recognitionType: RecognitionType
}
 ```
  
Question: should we have a seperate "currentlyActive: Boolean" field, or just set endDate to null in that case?
 
# Definition of done
- [x] Migration(s?) which add experience tables to DB
- [x] Eloquent models
- [x] Factories, linked to Eloquent models, but don't actually run them yet in any seeders.
- [x] Types added to graphql schema
- [x] We don't need graphql queries to get all or individual experiences. We'll get them based off User/Applicant later.
- [x] The schema re-compiled with `php artisan lighthouse:print-schema --write`

**Comment by patcon** [comment]
> Question: should we have a seperate "currentlyActive: Boolean" field, or just set endDate to null in that case?

👍 set endDate to null in that case

**Comment by tristan-orourke** [comment]
Setting this High Priority, since lots of other issues depend on these types.

**Comment by petertgiles** [comment]
@tristan-orourke I'm having some trouble verifying the accuracy of the model setup.  For example, for *WorkExperience* in the issue definition the *organization* field is supposed to be nullable but in [the wireframe](https://www.figma.com/file/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?node-id=1791%3A3907) it is required.  And do we have wireframes for the other four types of skills?

**Comment by tristan-orourke** [comment]
Well, a field may be _required_ in a form, and still be _nullable_ in the backend.

In GraphQL all fields are nullable by default, and they recommend keeping most of them that way. The argument is that non-nullable fields are more likely to cause a query to fail, and harder to change without breaking backwards compatibility. Here's [an article](https://medium.com/@calebmer/when-to-use-graphql-non-null-fields-4059337f6fc8) that informed my thoughts on it.

My takeaway is that fields should only be non-nullable in the graphql schema if the model really doesn't make any sense without it (eg id should always be non-nullable).

**Comment by petertgiles** [comment]
Thanks, that was really interesting read.  It makes wonder if we should move some of the other constraints like keys and phone numbers down from the graphql schema to the models or database. 🤔

**Comment by tristan-orourke** [comment]
I definitely think it would be good for our schema constraints to match database constraints.
