### ISSUE TITLE
API mutations to Create, Edit and Delete Experiences

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#1789]
# Description
Add mutations to the API schema to create, edit, and delete experiences. Note that experiences comprise 5 different types of models. Unfortunately, each type needs its own mutations, ie `createWorkExperience` + `updateWorkExperience` + `deleteWorkExperience`, `createPersonalExperience` + `updatePersonalExperience` + `deletePersonalExperience`, etc. Sorry, this issue might get a bit tedious. 

These will need to be protected by policies, which means using the `@guard`, `@can(ability: "create")` and `@can(ability: "update", find: "id")` directives. At least you should only need to define a single ExperiencePolicy which can apply to all the Experience models.

[Larvel documentation on Policies](https://laravel.com/docs/9.x/authorization#writing-policies)

Ideally, we'd want to update the Experience-Skill connection with the `sync with pivot data` [nested mutation](https://lighthouse-php.com/master/eloquent/nested-mutations.html#storing-pivot-data) pattern. This would let us specify the skill id and description text we want to associate with an experience, without having to worry about whether that ExperienceSkill already exists. This might require a bit of refactoring of the Experience and Skills models, so that Laravel considers them "relationship + intermediate pivot data", instead of treating ExperienceSkill as its own model. Maybe we can have both? Honestly, still unclear - figuring this out will be the most challenging part of this story. 
  -- @tristan-orourke is ready to help with this part even if not tackling the whole story

Finally, in addition to defining `createWorkExperience` etc mutations, it would also be convenient to allow these operations as nested mutations on the createUser and updateUser models. You should be able to reuse the intput types you already created for the direct mutations. eg something like this:
```graphql
mutation {
  createUser(user: CreateUserInput!)
  createWorkExperience(userId: ID!, experience: CreateWorkExperienceInput!)
}
CreateWorkExperienceInput {
  ...details
}
CreateUserInput {
  ...details
  workExperience: WorkExperienceHasMany
}
# WorkExperienceHasMany is the Nested Mutation type
WorkExperienceHasMany {
  create: [CreateWorkExperienceInput!] # this lets you create a whole array at once, using the same Input type as the createWorkExperience mutation
  # do the same thing for updates and deletes
  # update: [UpdateWorkExperienceInput!] 
  # delete: [ID!]
}
```

# Acceptance Criteria
- [x] Its possible to create, edit and delete experiences through the API
    - [x] through their own mutations
    - [x] or through nested mutations on the User
- [x] Its possible to update the ExperienceSkills attached to experience at the same time
- [x] Its possible to create and delete ExperienceSkills, and edit their text, but not to edit their skill_id or experience_id
- [x] Experiences (and ExperienceSkills) mutations should only be accessible by the users which own them, or admins

**Comment by patcon** [comment]
> APPLICANT role! (Or should it be called CANDIDATE role?)

If people might conceivably not apply, maybe candidate is better future-proof name? 🤷

**Comment by petertgiles** [comment]
We're already using the term _applicant_ in the code, for example #2124, so I'll probably use that unless anyone feels really strongly about it.

**Comment by petertgiles** [comment]
Oops, this is blocked.

**Comment by tristan-orourke** [comment]
Added more details to the issue. In particular, spent some time thinking about this part:
> Ideally, we'd want to update the Experience-Skill connection with the `sync with pivot data` [nested mutation](https://lighthouse-php.com/master/eloquent/nested-mutations.html#storing-pivot-data) pattern. This would let us specify the skill id and description text we want to associate with an experience, without having to worry about whether that ExperienceSkill already exists. This might require a bit of refactoring of the Experience and Skills models, so that Laravel considers them "relationship + intermediate pivot data", instead of treating ExperienceSkill as its own model. Maybe we can have both? Honestly, still unclear - figuring this out will be the most challenging part of this story. 

I really think a good API experience here is allowing the `sync` operation, but it definitely might take some work to figure out.
