### ISSUE TITLE
Skills In Detail (as linked to experience) form component

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#1795]
# Description
Complete a component for the Skills in Detail section of the Experience form.

It should accept a list of skills from its parent for which descriptions must be added. It should also accept a deleteHandler - it doesn't need to manage that state itself.

The detail textarea inputs should be set up to be embedded in a larger React Hook Form. They should be treated as an array of values by the form.

Textarea needs word limit. QUESTION: can we get away with using a character limit instead? Its much simpler, and maybe more common?

[Experience form wireframe](https://www.figma.com/proto/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?node-id=2340%3A4352&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A2)

# Definition of done

- [ ] Component can be viewed in storybook.
- [ ] Handler is called when Remove button clicked
- [ ] Inputs use react-hook-form rules for validation: they are Required, and have word/character limit.

**Comment by petertgiles** [comment]
Use character limit to simplify for now.

**Comment by Jerryescandon** [comment]
Yeah that sounds like a good call, Are you talking about step 3 on the form? we don't necessarily want to discourage submitting experience without skills, so a similar message to the one above would be great, I think gray background is fine. lemme mock up a  quick bad boy

**Comment by Jerryescandon** [comment]
![image](https://user-images.githubusercontent.com/16977254/154566574-58dccf10-c952-44cc-bb7a-397ca5a4854c.png)

**Comment by petertgiles** [comment]
Gonna toss this one back for now.  I'll focus on finishing the logout PR instead.
