### ISSUE TITLE
Assemble entire Experience form

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#1796]
# Description
Assemble a component that includes all sections of the Experience form. Besides the "Addition Information" textarea, all UI components should already be created. They should all be wrapped in a React Hook Form.

Depending on the experience type, the step 1 and data shape needs to be different. Alternatively, there can be 5 different versions of the component, which compose the rest of the form around the correct step 1 component.

Also build a wrapper component around that which handles API operations.

[Wireframe](https://www.figma.com/proto/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?node-id=2340%3A4352&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A2)

# Acceptance Criteria
- [ ] Entire form component viewable in Storybook
- [ ] React-hook form can transform data (if necessary) between a shape that comes from the api, and the shape that the form requires, and back (for submission)
- [ ] Skills added/removed to section 2 are reflected in section 3, and vice versa
- [ ] Skill interactions are validated by unit tests
- [ ] Write graphql API operations to get all data necessary for populating the form, and to submit the form
- [ ] Save unsubmitted form in local storage using hook

**Comment by petertgiles** [comment]
Consider pair-programming for this one
