### ISSUE TITLE
Clients - investigate using Mock Service Worker to mock backend API

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#18]
# Description
Mock Service Worker can be used to intercept network requests and return mocked results. This could be used with Storybook to work with components that fetch their own data (instead of just receive it through props) and to help unit test complete React pages.
Determine whether we have a worthwhile use case for this tool.

**Comment by mnigh** [comment]
@tristan-orourke is [Mock Service Worker](https://storybook.js.org/addons/msw-storybook-addon/) something we still want to look at or not?

**Comment by tristan-orourke** [comment]
Nah, not worth it.
