### ISSUE TITLE
Update Referrer-Policy header on servers

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/gc-digital-talent#1804]
We currently use `no-referrer-when-downgrade` but the vulnerability scan recommended using Chrome's new default (updated last year) which is `strict-origin-when-cross-origin`.

https://developers.google.com/web/updates/2020/07/referrer-policy-new-chrome-default

Update this in the .htacess write-out task in each CI pipeline.

**Comment by mnigh** [comment]
@tristan-orourke or @petertgiles was this changed as part of moving from Apache to nginx? In any case, it looks like this has been changed.

## Screenshot
![Screen Shot 2023-05-04 at 15 17 42](https://user-images.githubusercontent.com/3046459/236306868-88a8f59c-5ac2-448f-b7ae-02ec592c592a.png)

**Comment by petertgiles** [comment]
Could be an nginx default.  Could be added by the F5s.  Wherever it comes from, I guess this issue is good.  Thanks for testing. :+1:
