### ISSUE TITLE
Link Experiences to Users/Applicants

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#1806]
# Description
Each Experience belongs to a User. This is a simple many-to-one relationship, and can be implemented by adding a user_id column to each Experience table/model. This should be a required (non-null) field.

Updating the graphql schema will be slightly more complicated by the fact that the User type should include an experiences field which returns all 5 types of experiences in a single collection. It shouldn't be hard to implement this with some code in the Laravel User model, but I'm not sure of the best way off the top of my head. Maybe an [accessor](https://laravel.com/docs/8.x/eloquent-mutators#defining-an-accessor)?

The graphql model is also slightly complicated by security concerns described in #1846. 

FOR CONSIDERATION: We should proactively consider that an Applicant profile is meant to be shared, but only selectively. I think it might be worth it to create an Applicant or ApplicantProfile type in graphql, which contains the subset of User fields which would be relevant to an interested manager. (Right now, this would exclude sub, roles, pools, and poolCandidates). Experience types could include an Applicant field instead of a User field, though the User and Applicant fields would both include Experience fields.

# Definition of Done

- [x] Necessary changes to database in migrations
- [x] Necessary changes to Laravel models (property docblocks and relationships)
- [x] User Factory should generate some random Experiences and attach them to user
- [x] GraphQL schema types updated
- [x] We don't need graphql queries to get all or individual experiences. We'll get them based off User/Applicant.
- [x] The schema re-compiled with `php artisan lighthouse:print-schema --write`

**Comment by tristan-orourke** [comment]
#1846 isn't quite a dependency, but should be considered at the same time.

**Comment by JamesHuf** [comment]
The models were already linked as part of #2076. We still need to use the factory to create experiences for users and look at creating an Applicant type in GraphQL though.
