### ISSUE TITLE
Removed hardcoded /var/www/html from scripts

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#1858]
Re-ticketed from https://github.com/GCTC-NTGC/gc-digital-talent/pull/1784#issuecomment-1016683850

> Is there a way to remove the hardcoded paths to /var/www/html/?

This will allow running them more easily on a local machine outside docker filesystem

**Comment by patcon** [comment]
See: https://github.com/GCTC-NTGC/gc-digital-talent/commit/1673a302bc72ee294f3102f96fb879a259127632#r65837531

**Comment by gggrant** [comment]
Rendered obsolete by #2217
