### ISSUE TITLE
LanguageRedirectContainer loses URL serach query

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#1866]
I think the LanguageRedirectContainer is losing the URL search query when redirecting to a localized path.  Since the auth container is inside this it never receives the tokens.

Suggested test for `frontend/common/src/components/LanguageRedirectContainer/LanguageRedirectContainer.test.tsx`
```
  test("If url has a search query it should be preserved", async () => {
    HISTORY.push("/home?token=xyz");
    renderContainer();
    expect(HISTORY.location.pathname).toBe("/en/home?token=xyz");
  });
```

**Comment by patcon** [comment]
This is a prime candidate for eventual e2e tests. Thoughts on creating a label to track these and revisit to create some high-value tests, once we have the scaffold running on CI? maybe `e2e-candidate`
