### ISSUE TITLE
Bug - After creating a new Classification on admin panel, it doesn't appear in table right away

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#1874]
# Description
After submitting a new Classification in the admin panel page /admin/classifications/create, you are redirected back to the table. But your new row doesn't appear until refreshing the page.

This issue might exist for other tables as well.

**Comment by tristan-orourke** [comment]
Pools table has the same issue.

**Comment by gggrant** [comment]
Unable to reproduce.
