### ISSUE TITLE
Organize files so all component files are together

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#1877]
Based on this slack discussion: https://talent-cloud.slack.com/archives/C0259G6KXJ6/p1642527594022800

For example:

```
/components
  /Component1
    Component1.tsx
    Component1.test.tsx
    Component1.stories.tsx
    Component1.css?
    index.ts?
```

**Comment by petertgiles** [comment]
Be careful with communication since this will cause a lot of conflicts on the team.

**Comment by patcon** [comment]
Agreed. Might be worth doing partially in multiple PRs base on what isn't being worked on by others

**Comment by gobyrne** [comment]
@esizer suggest breaking this up across the different projects. But delaying for now until after direct intake release.

**Comment by mnigh** [comment]
#5065 by @esizer dealt with a bunch of file structure changes. @petertgiles is this issue still up for discussion or is it now ready to be closed?

**Comment by petertgiles** [comment]
I think the work Eric did pretty much solved this.  Any remaining items (if any) could be dealt with in their own issues.
