### ISSUE TITLE
Admin - Add missing fields to User tables

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#1898]
# Describe
Admins should be able to edit the sub field (text input) of users in Create and Edit forms on the admin dashboard, and should be able to modify the roles of users (multiselect input). This will especially help onboard new users before we have a proper registration flow (as per #1689).

**Comment by petertgiles** [comment]
I want to be sensitive to scope creep but in the context of streamlining onboarding I wonder if we should add a checkbox to set the ADMIN role as part of this story.

**Comment by tristan-orourke** [comment]
Good point @petertgiles. Let's do one better, and add a multiselect dropdown for all roles.
