### ISSUE TITLE
API Server - Create query for getting number of candidates that meet a set of search filters

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#19]
# Description
Create a query that returns the number of candidates matching a set of filters. 

# Question
Get the full list of filters.

**Comment by Jerryescandon** [comment]
Link to search prototype:
https://www.figma.com/proto/cctPDb5clT7S0JuRmkBgoO/MVP?page-id=0%3A1&node-id=1%3A2&viewport=-55%2C362%2C0.22959193587303162&scaling=min-zoom

**Comment by tristan-orourke** [comment]
@Jerryescandon How should selecting multiple checkboxes in a field affect the input? e.g. If you select multiple Conditions of Employment, should we only return candidates that have ALL of them, or ANY of them? In dev terms, are they AND or OR filters?

My guess is that for Classifications we should return candidates that match ANY classification, but the other the checkbox inputs (Conditions of Employment, EE Data, and Skill filters) should only return candidates with ALL filters.

**Comment by Jerryescandon** [comment]
The way we have designed it is:

Classification: OR
Education: ---
Conditions of Employment: AND
Work Location: ---
Language: ---
EE Data: OR
Skills: AND
