### ISSUE TITLE
Bugfix - duplicate moduleNameMapper set in jest config

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/gc-digital-talent#1900]
# Description
It looks like a few of us had the same solution to the common module mapping for the jest config, and somehow they all got through to main. 
![image](https://user-images.githubusercontent.com/22059495/151437407-d0a7a44d-93e6-46fe-aeea-b80a4a91db34.png)

## Acceptance Criteria
- [ ] Remove duplicate moduleNameMappers

**Comment by patcon** [comment]
Oh hey, interesting...! Hm, I hadn't realized this edge case of PRs tests. As in, that all PR tests could run against "merge commits", and show up as passing individually. But after merge, there could still be a failure on mainline even when no PR's showed fails...

Guess I've learned that even when testing every PR thoroughly, I still need to be testing the branch commits themselves (and maybe using README badges to show failed results)

Thanks for posting screenshot, yoni
