### ISSUE TITLE
Applicant Profile page

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#1908]
# Description
This is the page I reach when navigating to my profile.

[Wireframe](https://www.figma.com/proto/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?node-id=2340%3A4185&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A2)

**Comment by petertgiles** [comment]
Looks finito to me!
