### ISSUE TITLE
Work Location Preference form

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#1921]
# Description
The Work Location Preference form, with all fields shown on the wireframe.

Location exemptions is just a string.

At least one checkbox must be checked for form to be validated.

[Wireframe](https://www.figma.com/proto/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?node-id=2485%3A4764&starting-point-node-id=1%3A2)

Show result of submission in a toast notification, and return to profile page if successful.

# Acceptance Criteria
- [ ] Storybook
- [ ] Graphql operations
- [ ] Wrapper component that gets and submits data to API
- [ ] Jest test for:
   - [ ] Can't submit unless form is valid (at least one location selected)
   - [ ] Form submits data in correct shape to submit handler when Save Changes is clicked.

**Comment by RVany** [comment]
@tristan-orourke May I know What is the corresponding database table for graphql operartions?

**Comment by RVany** [comment]
@tristan-orourke labels for work location checklist retrieving from database table/graphqlschema?
