### ISSUE TITLE
Work Preferences form

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#1923]
# Description
The Work Preferences form, with fields as shown on the wireframe.

Not required.

[Wireframe](https://www.figma.com/proto/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?node-id=2485%3A5000&starting-point-node-id=1%3A2)

Show result of submission in a toast notification, and return to profile page if successful.

Create a applicantProfileRoutes file, a sibling to talentSearchRoutes. 
Define a home route within it, and reference it. 
It can be anything for now, even an empty string, and we'll fix it later

# Acceptance Criteria

- [ ] Storybook
- [ ] Wrapper component that gets and submits data to API
No need for jest tests here as the component has very little interactive elements besides standard form elements.

**Comment by RVany** [comment]
@Jerryescandon  
Button icon is not exactly matching the wireframe. 
Any quick suggection please?

` <ArrowSmDownIcon
              style={{ width: "1rem" }}
              data-h2-bg-color="b(black)"
            />`

![Screenshot 2022-03-10 170805](https://user-images.githubusercontent.com/95497896/157765881-79068894-3cad-4a6b-ba01-44ff91d8def2.png)

**Comment by petertgiles** [comment]
I found it!  It's called `save`.

![image](https://user-images.githubusercontent.com/8978655/157886429-b46dbf48-c732-4db5-bd1f-5ecfdf08855b.png)

**Comment by RVany** [comment]
ok thank you! I thought need some styling with Hydrogen.

**Comment by petertgiles** [comment]
Check out frontend/common/src/components/tabs/tabs.stories.tsx for a page with some icons.
And here's what it looks like: [iframe.html?id=components-tabs--skills-to-experience&args=](https://www.chromatic.com/component?buildNumber=1047&historyLengthAtIndex=4&distanceToMoveBack=-2&appId=61e099a1bb1465003a73d3ce&name=Components%2FTabs&specName=Skills+To+Experience&componentInspectorKey=622a941c9362b9003a839cba-1200-interactive-true)

**Comment by RVany** [comment]
@petertgiles @Jerryescandon 
Trying to add some padding between button and icon
both icon nor link not effect in by padding attribute 
`data-h2-padding="b(left,l)"` any erroy in the syntax?

<SaveIcon
              style={{ width: "1rem" }}
              data-h2-bg-color="b(black)"
              data-h2-padding="b(right,sm)"
            />
            <Link href="/" title="" data-h2-padding="b(left,l)">
              {intl.formatMessage(
                {

**Comment by RVany** [comment]
> 

Ya. I referenced it. thank you.

**Comment by petertgiles** [comment]
The syntax looks OK to me.  The reference for hydrogen is on its homepage here: https://hydrogen.design/  Maybe you need to rerun `npm run h2-build`?  Sometimes I'll cheat and just use &nbsp; 😁

**Comment by RVany** [comment]
Me and Brinda broke the button together.  Fix it and try again.   I have a feeling padding is already applied inside the component so its not taking again. I used to do `!important `in normal/vanilla CSS but I don't think its possible in Hydrogen. I want to move to implementing the form so I may use $nbsp;

**Comment by RVany** [comment]
> The syntax looks OK to me. The reference for hydrogen is on its homepage here: https://hydrogen.design/ Maybe you need to rerun `npm run h2-build`? Sometimes I'll cheat and just use `&nbsp;` 😁
@petertgiles 
Finally,I bring the button 99.99% as wire frame.  I found that you guys are using vanilla css in JSX so I applied position absolute and  bottom  9px for icon and padding left to text.
`<span
              style={{
                paddingLeft: "30px",
![Screenshot 2022-03-11 102044](https://user-images.githubusercontent.com/95497896/158018733-3e083287-3cce-452f-9298-20ebdbf31602.png)

              }}
            >`

**Comment by RVany** [comment]
@brindasasi 
I completed the button without Link component. Thank you for the guidance!

**Comment by petertgiles** [comment]
Yoni has made some nice new buttons in https://github.com/GCTC-NTGC/gc-digital-talent/pull/2219 .  You could take a look at those for some ideas.

**Comment by RVany** [comment]
By the way. How I can check the buttons Yoni made? looks like you comitted to main so I just pull the main? Do I need to merge after pull? Or Just pull that branch?

**Comment by petertgiles** [comment]
By the way, I found how to open the Chromatic snapshots for a merged PR. :grin: 
First click `View details`
![image](https://user-images.githubusercontent.com/8978655/158228203-baee85bc-bd0a-45e6-9e24-4bc668d3b4f0.png)
Then you can scroll down to Storybook Details and click `Publish`

**Comment by RVany** [comment]
ok thank you! I will check

**Comment by RVany** [comment]
yes it works but Profile Form Wrapper is giving error ove there. I think it works in local.
