### ISSUE TITLE
Skills and Experience display component

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#1924]
# Description
This component doesn't include the Add New Experience buttons. Just everything from the See Experience sort buttons and below

[Wireframe](https://www.figma.com/proto/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?node-id=2340%3A4769&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A2)

**Comment by vd1992** [comment]
@tristan-orourke 
This appears... done? I don't know what to do with Epics.
