### ISSUE TITLE
Experience Accordion component

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#1925]
# Description
An accordion component representing an Experience. When opened, displays the list of associated Skills, additional information and a Link to the experience's edit form.

Note that the title and subtitle of the accordion are formatted slightly differently for different types of experience:
- work:
  - title:  <Role> at <Organization>
  - subtitle: "Since: <Start Month> <Start Year>" (is this only if still active? is it otherwise <Start Date> - <End Date>?)

[Wireframe](https://www.figma.com/proto/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?node-id=2340%3A4769&starting-point-node-id=1%3A2)

# Acceptance Criteria

- [ ] Storybook
- [ ] Jest tests:
  - [ ] Titles, subtitles and content appear correctly for different experiences

**Comment by tristan-orourke** [comment]
Recent at top. Use end date, if no end date put at top

**Comment by gobyrne** [comment]
Sort by most recent End Date at top.
All items with no end date should be at the top and sorted by most recent start date.

**Comment by Jerryescandon** [comment]
Alright, hold on to your socks. 
I've added the Title and Subtitle for all the types of experiences in the next images,
but also,
we can't fit all the info we collect on the title alone, so I've added a mini section inside every expanded accordion to put in the complete info.

Here you go:

**Personal Experience**
![image](https://user-images.githubusercontent.com/16977254/156054401-c1930e87-c9c9-46f4-8b8b-72424880cd4d.png)

**Work Experience**
![image](https://user-images.githubusercontent.com/16977254/156054608-8c8fb16f-91a1-47f7-98a9-64547097e17d.png)

**Community Experience**
![image](https://user-images.githubusercontent.com/16977254/156054773-3e6733dd-bca0-48d8-90d1-e64acfd4f99b.png)

**Education**
![image](https://user-images.githubusercontent.com/16977254/156054847-e35c8bb1-7a4b-41f4-977c-f88e10258078.png)

**Awards**
![image](https://user-images.githubusercontent.com/16977254/156054882-23807178-2aa3-481a-9b49-cd55de947c11.png)

**Comment by vd1992** [comment]
I was trying to figure out if I could tackle this and was playing around with things. 
Realized this appears to be blocked by #1788

If skills aren't linked to experiences, you cannot make the wireframe accordions I believe

**Comment by tristan-orourke** [comment]
Rewrote the issue to _only_ include the accordion component, not the list sorted by date.
