### ISSUE TITLE
Skill Accordion (with experiences) component

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#1926]
# Description
Similar to #1925, but now each accordion is a Skill, and when opened shows a list of associated Experiences.

QUESTION: how should the list items be formatted for Personal, Award, and Education experience?

[Wireframe](https://www.figma.com/proto/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?node-id=2340%3A4769&starting-point-node-id=1%3A2)

# Acceptance Criteria

- [x] Storybook
- [ ] Jest tests:
  - [ ] Titles and context appear correctly
  - [ ] Experience appear correctly inside the correct skill

**Comment by brindasasi** [comment]
@Jerryescandon 
QUESTION: how should the list items be formatted for Personal, Award, and Education experience?

Let's say if a skill has 1 work and 1 education experience attached to it. 
Do you want to differentiate them with the formatting?

**Comment by brindasasi** [comment]
![image.png](https://images.zenhubusercontent.com/61a7bd49e20af80694dd845e/0b44b38a-8750-4695-abd7-ab9e6e66a8f5)

**Comment by tristan-orourke** [comment]
Rewrote the issue to _only_ include the task of creating the Skill Accordion component, _not_ the act of ordering them in a list.
