### ISSUE TITLE
Ensure that Experience and Skills page is updated after submitting an Edit Experience form

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#1929]
Ensure we don't have a bug like #1874

**Comment by gggrant** [comment]
Check if this is working correctly.

**Comment by vd1992** [comment]
adding blocking dependency
in order to test, it would be important to have all routing up, so you can navigate 
profile page -> edit experience -> profile page
and see whether the changes are working

**Comment by esizer** [comment]
## Summary

I tested the form on the main branch to ensure the experiences changes were being reflected on the Skills and Experiences page. Everything looked to be good.

## Note

I'm not sure if this exactly what we wanted to confirm here. I can take another look if there is some functionality we are missing. I think once we get it up and running this could be a good candidate for a cypress test.

## Screenshots

### Before

<img width="1122" alt="before" src="https://user-images.githubusercontent.com/4127998/167893526-7f687da2-3a9f-4140-8b6b-15bcc659b28f.png">

### During

<img width="713" alt="during" src="https://user-images.githubusercontent.com/4127998/167893610-8b29d4e4-d97e-4204-8c0c-a9294b0188a7.png">

### After

<img width="1130" alt="after" src="https://user-images.githubusercontent.com/4127998/167893653-f3210bca-0c37-444d-8fe8-5953455b1d65.png">

**Comment by tristan-orourke** [comment]
> a good candidate for a cypress test

Good call! If this is already working, we could repurpose this ticket to "Create a e2e test to check this"

**Comment by esizer** [comment]
> > a good candidate for a cypress test
> 
> Good call! If this is already working, we could repurpose this ticket to "Create a e2e test to check this"

I can create a new ticket and add a ref to and then close this.
