### ISSUE TITLE
Move reusable components and helper function files to /common folder

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#193]
# Description
Create a /common folder for sharing code between /admin and the public-facing subproject. Move any reusable components there, like everything in /form and /menu, and the code in /helpers (router and util). Ensure the /admin project is still importing these components and functions.

QUESTION: Will this common folder need its own config? (Like for eslint, prettier, ts, etc.) These common components probably deserve their own storybook page, so it will need a package.json. It seems like this approach involves duplicating dependencies and config files across at least 3 different folders... Is this the right approach?

**Comment by jaysonmc** [comment]
I would imagine so, yes. The file will need it's own config. Really each 'folder' could be a separate repo, so with that framing, then each repo would have it's own config, so each file is no different. Additionally, the /common folder is a lot simpler (presumably) than the other folders. So the configs are must simpelr and have different needs. Given this, it makes sense each one has it's own config.

I suppose another approach is the use of git submodules instead, which could change the situation ... though never tinkered with those yet, so! Don't have a very informed opinion on that approach.
