### ISSUE TITLE
Investigate changes we should make to align with CATS

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#1965]
# Description
To integrate with SiC in production, we must follow the requirements and recommendations laid out for Relying Parties in the following documents:
- https://canada-ca.github.io/CATS-STAE/oidc1-en.pdf
- https://openid.net/specs/openid-igov-openid-connect-1_0-03.html#:~:text=An%20iGov%2Dcompliant%20OpenID%20Connect,OAuth%202.0%20authorization%20server%20functionality.
- https://openid.net/specs/openid-igov-oauth2-1_0-03.html

Look over these docs, figure out what we need to do that we aren't already doing, and define issues for them.

**Comment by tristan-orourke** [comment]
1 day

**Comment by patcon** [comment]
From: https://github.com/GCTC-NTGC/gc-digital-talent/issues/1986#issuecomment-1030050337

> Seems this doc is following RFC 2119, which means all these words "SHOULD" "RECOMMENDS" etc have very specific meaning worth being aware of: https://datatracker.ietf.org/doc/html/rfc2119

**Comment by petertgiles** [comment]
> these words "SHOULD" "RECOMMENDS" etc have very specific meaning worth being aware

Yeah, that's a good point.  I logged all the recommendations as issues as well.  I'm going to interpret them as *we should probably do these soon but they won't prevent us from going live*.

**Comment by petertgiles** [comment]
All topics logged as issues with followup questions noted and answered.
