### ISSUE TITLE
Discussion - Change Impact labels for Change Management Board

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#1967]
# Description
To ease our presentations to CMB, it was suggested we try to categorize every feature we complete according to the magnitude of its impact. Here's a proposal:

-	Trivial: trivial changes include insignificant changes to the UI, such as rewording existing text or minor restyling of elements, that users are unlikely to notice, and refactoring of code that does not change functionality at all.
-	Minor: minor changes include changes to existing UI that are substantial enough to be noticed by users, but do not substantially change the functioning of the app, the creation of non-critical API endpoints such as for the querying of public data, and changes to existing API endpoints that would not be noticed by existing consumers of the API.
-	Major: major changes represent substantial changes to the functionality of the app, such as the addition of new pages, total UI overhauls, creation of new API endpoints with important functionality, and the modification of existing security policies.
-	Emergency: emergency changes are defined not by their user impact, but by their time sensitivity. They may include critical security updates, or highly time-sensitive UI updates.

Need to get on the same page with labels, and decide when/who/how we should apply these.

**Comment by patcon** [comment]
CMB = Corporate Management Branch?

These recommended tags could also be made to align with our own release automation efforts, if we wished. Tools exist for taking PR titles and/or commits, and generating reviewable changelogs broken down into specific categories. No clear idea of which is better, but some of ecosystem is:

- https://github.com/release-it
- https://github.com/commitizen
- https://github.com/semantic-release
- https://github.com/conventional-changelog/

**Comment by gggrant** [comment]
Labels for PRs created.

**Comment by gggrant** [comment]
Definition of Done updated.
