### ISSUE TITLE
Accordion contents panel is transparent

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#1974]
Oops, I think this was missed in the shuffle between PRs.  When the accordion is open the background of the contents panel is transparent.
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/47a84f3b-4c08-45c7-aac3-0e9ce7c2408a)

**Comment by patcon** [comment]
Interesting... Is there anything we could change so this would show up more clearly in chromatic? Like maybe a non-standard/non-white background in the storybook preview renders in general? But I suppose that makes it a little bit less like the aesthetic environment it will exist within on the real site...? 🤷 

If background color is selectable, maybe the default could be the one that makes it most obvious, but then it's still easy to select the one that's more like the components future home 🤔

**Comment by petertgiles** [comment]
It's fixed
