### ISSUE TITLE
ODP-RP02 ODP-RP03 - Support logout

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#1986]
Reference [CATS document](https://canada-ca.github.io/CATS-STAE/oidc1-en.pdf) section 5.2.2
```
[ODP-RP02]
RP implementations SHOULD support OpenID back-channel logout [OIDC-BC] for the receipt of
logout tokens. An RP MAY support the OpenID front-channel logout [OIDC-FC] in the event that
their implementation does not support [OIDC-BC].
[ODP-RP03]
It is RECOMMENDED that RP implementations support [OIDC-RP] for sending front-channel
logout requests to the OP.
```

**Comment by petertgiles** [comment]
Is the ideal setup to support both front-channel and back-channel logout?

**Comment by patcon** [comment]
Seems this doc is following RFC 2119, so "SHOULD" and "RECOMMENDS" are identical strength, and all of this is recommended, but optional: https://datatracker.ietf.org/doc/html/rfc2119

**Comment by petertgiles** [comment]
From Doug with SiC:  The ideal situation is:
1) We provide a logout button that sends the browser to their logout endpoint
2) Our API uses the introspection endpoint to check if a token has been revoked

Doug's notes:
- They whitelist post-logout redirect URIs we need to send them any new ones
- We probably need to send the identity token, not access token, to logout at the endpoint

My note:
- Don't forget to clear out browser local storage of tokens on logout

**Comment by tristan-orourke** [comment]
It seemed to me that, regardless of the specifics of the doc, Doug considers this to be a requirement more than a recommendation.

**Comment by tristan-orourke** [comment]
At the very least, linking to SiC's logout link is a requirement. Neither front-channel or back-channel seems to be a requirement, partly because as far as Doug's concerned we're not _really_ following OIDC, we're following OAuth.

**Comment by petertgiles** [comment]
Sounds good.  I'll move this one to product backlog.

**Comment by petertgiles** [comment]
Defined scope: add logout button that links to SiC and validate tokens using introspection.
