### ISSUE TITLE
ODP-RP05 - Support deep linking

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#1988]
Reference [CATS document](https://canada-ca.github.io/CATS-STAE/oidc1-en.pdf) section 5.2.3
```
Applications SHOULD, and collaborative applications MUST, support deep linking. Deep linking
implies maintaining support for such links across the boundary of an OpenID Connect profile
interaction involving any OP necessary to complete the login process.
It should be possible to request a resource and (authorization permitting) have it supplied as the
result of a successful OpenID Connect profile exchange.
```

**Comment by petertgiles** [comment]
I think our application qualifies as a a collaborative application?  I interpret this to say that if a user clicks a link to a page they should be redirected there after login?

**Comment by petertgiles** [comment]
Moving this to the CATS Recommendations epic

**Comment by patcon** [comment]
> We probably do not count as a collaborative application.

The context gives me the sense that the purpose of the term is to designate any app where links might get shared between users (admins, end-users, moderators, etc). So my rough sense is that we're more Collab than not?

My guess of a archetypical "non-collab app" is like the myCRA tax portal or something, which is a way more isolated experience.

**Comment by petertgiles** [comment]
> So my rough sense is that we're more Collab than not?

Yeah, that was my first guess, too, but Doug thought otherwise.  I guess someone above my pay grade will have to make a call on that. @tristan-orourke ,  @gobyrne ?

**Comment by tristan-orourke** [comment]
This sounds to me like something we definitely want to have, but that we can argue shouldn't block us from going live.

**Comment by tristan-orourke** [comment]
This would mean creating some way of marking routes in our frontend routes as being authenticated-only, and then triggering a login if you try to access those pages while unauthenticated.

**Comment by tristan-orourke** [comment]
Re-ticketed in #2784. This seems more manageable now that we have some authorization functionality.
