### ISSUE TITLE
ODP-RP06 - Preserve POST requests across login

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#1989]
Reference [CATS document](https://canada-ca.github.io/CATS-STAE/oidc1-en.pdf) section 5.2.3
```
It is RECOMMENDED that RPs support the preservation of POST bodies across a successful
OpenID Connect profile exchange, subject to size limitations dictated by policy or implementation
constraints.
```

**Comment by petertgiles** [comment]
Same questions as https://github.com/GCTC-NTGC/gc-digital-talent/issues/1988#issuecomment-1029275251

**Comment by gggrant** [comment]
Don't think this applies to our app.
