### ISSUE TITLE
Ensure routing is working for all Profile Edit forms

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#1994]
# Description
Ensure each profile form page has routing (can be reached via a url) and that the links on the main Profile page work properly.

Set up pages, with correct routing between them, for:
- Main profile page 
- About Me
- Language Information
- Government Information
- Work Location
- Work Preferences
- Skills and Experience
- Create Experience x 5 and Edit Experience x5 (nearly identical pages, but different urls for each type, and for new vs existing items)

**Comment by tristan-orourke** [comment]
Does this merit tests? Jest tests which click around the links?

**Comment by RVany** [comment]
@tristan-orourke Users are directed to Edit forms from the profile page right? What you mean by Placeholder page?
