### ISSUE TITLE
Populate sections of main profile page

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#1996]
# Description
Fill in all the sections which display user data. Each one needs to check if it is missing required data, and if so show a text box and a link to the edit form.

This applies to Pools, About me, language, Gov info, Work Location and Work Preferences

[Wireframe](https://www.figma.com/proto/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?node-id=2340%3A4185&starting-point-node-id=2340%3A4185)

# Acceptance Criteria
- [ ] Includes Graphql operation to get user data.
- [ ] Fill in all the sections which display user data.
- [ ] Each one needs to check if it is missing required data, and if so show a text box and a link to the edit form.

**Comment by vd1992** [comment]
@tristan-orourke @Jerryescandon 
Hey, I am not entirely sure how this page should look when completed. As in, what info from the database goes where in the page and how it should be formatted. 
As well, what are the pieces of info considered to be Required?

**Comment by Jerryescandon** [comment]
So for most fields they should be able to click and see how it looks filled in.

![chrome_8dzf5CN2Xn](https://user-images.githubusercontent.com/16977254/160953094-bc7e8456-9faf-47fa-b0eb-77b4bcec46be.gif)
.
