### ISSUE TITLE
CATS Compliance Section 4.1.1 - Security Requirements

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2032]
This issue provides a checklist of topics to certify with IMTD regarding server configuration for CATSv3 compliance.
Refer to section 4.1.1 of [the certification document](https://canada-ca.github.io/CATS-STAE/oidc1-en.pdf).

[ODP-G02]: Reference [iGov-OIDC] Section 6
All transactions MUST be protected in transit by TLS as described in BCP195.
CATS Support: Constrained
TLS MUST be configured according to the Guidance on Securely Configuring Network
Protocols [ITSP.40.062].

[ODP-G03]
X.509 certificates used for TLS server authentication MUST be issued by a certificate authority
that is recognized by all of the following:
 The Apple Trusted Root Certificate Program
 The Java Trusted Root Certificate Program
 The Microsoft Trusted Root Certificate Program
 The Mozilla Trusted Root Certificate Program
X.509 certificates used for TLS server authentication MUST comply with the following:
 Apple’s Certificate Transparency policy
 Chromium Certificate Transparency Policy
Deployments MUST NOT accept expired certificates.

[ODP-G04]
Deployments MUST perform path validation and check the revocation status of X.509
certificates used for TLS server authentication.

[ODP-G05]
Deployments MUST implement HTTP Strict Transport Security (HSTS) [RFC6797].

[ODP-G06]
All cryptographic algorithms, including signing and encryption operations between RPs
and OPs, MUST be implemented in conformance with  [ITSP.40.111].

**Comment by tristan-orourke** [comment]
Okay, got a response from IMTD. Sounds like the only we have to worry about is 
> [ODP-G04]
Deployments MUST perform path validation and check the revocation status of X.509
certificates used for TLS server authentication.

which they suggested is up to our own app to do.

**Comment by tristan-orourke** [comment]
And it seems like the [Laravel HTTP Client](https://laravel.com/docs/master/http-client) does this automatically:
https://stackoverflow.com/questions/68072879/how-to-disable-ssl-check-with-laravel-http-post
