### ISSUE TITLE
Generic tabbed component

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2037]
A generic component which can work for Skills to Experience on the Experience form, and the Sort Experience tabs on the Skills and Experience page.

[Skills and Experience wireframe](https://www.figma.com/proto/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?node-id=2340%3A4769&starting-point-node-id=1%3A2)

**Comment by tristan-orourke** [comment]
@Jerryescandon

**Comment by petertgiles** [comment]
@gggrant Should the contents of a tab that is not active or open be:
1) invisible
2) hidden
3) not in the DOM at all?

**Comment by gggrant** [comment]
Pretty sure  that #1 is satisfactory.

**Comment by tristan-orourke** [comment]
> @gggrant Should the contents of a tab that is not active or open be:
> 
> 1. invisible
> 2. hidden
> 3. not in the DOM at all?

I'm not sure if this is invisible or hidden, but on the accordion we used `style={{ display: isOpen ? "block" : "none" }}`, which hides it from view and from screen-readers, but leaves it rendered in case there is some internal state we want to preserve.

**Comment by petertgiles** [comment]
> I'm not sure if this is invisible or hidden

Oh, you're using display, not visibility there.  That's another option that I didn't consider.  Well, I'm guessing all the same decision making that was made for the accordion would be the same for this.
