### ISSUE TITLE
Eslint Storybook Dependency Error

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2042]
Recently the Storybook dependencies were moved to the top-level package.json file in #1963.  This has simplified the dependency management but now eslint is complaining that it can't find the dependencies.  I imagine there's a simple configuration fix to help it find them in the new location and suppress the error.
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/2037d5c4-8e2d-4875-ab2a-a0b435a47534)

**Comment by patcon** [comment]
Maybe add it, but just use `"package-name": "*",` in subdir package.json

Seems maybe completely ditching all mention of the package in subdir is was a bad practice, and not a recommended way to simplify. Seeing all the linting tools check to confirm imports in package.json, even on workspaces

**Comment by petertgiles** [comment]
Hmm, seems like we're still getting storybook PRs with just a lock file update in it, too.
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/5bd2cb4a-c67d-45a3-b56e-acc7f9d1a336)

**Comment by petertgiles** [comment]
It's probably not worth trying to hack the dependencies of storybook so they all move together.  Let's just roll it back so that the linting is fixed.

**Comment by patcon** [comment]
Ah sorry, I missed this. I didn't think we need to roll back all the way, just add imported packages into `frontend/*/package.json` with the `"*"` constraint?

Then the general version can still be peeked at in `frontend/package.json` to understand where we are at. We don't get the nice single PR, but we still have legibility into what we're running in one place (frontend/package.json) :)

**Comment by patcon** [comment]
But aaaalso, this all nbd. Happy to stay the course, and next time I'm touching storybook I'll see if I make any sense 🙃

**Comment by petertgiles** [comment]
> just add imported packages into `frontend/*/package.json` with the `"*"` constraint

That change would probably solve the linting errors, too.  Is there an advantage to using the * over the explicit versioning if we're still getting the individual Dependabot PRs?  If so, then lets do it.

**Comment by tristan-orourke** [comment]
Handled in #2043
