### ISSUE TITLE
Catch up with all our linting errors

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2043]

**Comment by gggrant** [comment]
Create new issue(s) for incomplete tasks.

ASAP merge, resolve conflicts.

@patcon

**Comment by petertgiles** [comment]
Issues 2486 - 2497 have been created to break this one into smaller chunks.  One issue per linting rule violated.

**Comment by patcon** [comment]
I think all that's left is consolidating eslint files to one in frontend. Will do that real quick as a chore, then close out the old one
