### ISSUE TITLE
Bug - auth deep linking doesn't work when app hosted behind proxy

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2044]
# Description
AuthController requires the $from parameter to be a url path, no hostname, because we only want to link back to our own site. However, in production, where the app is hosted behind a reverse proxy, a redirect to a path tries to send the browser to the backend url.
ie if you use `from=/en/admin` on the UAT server, you will be redirected to `http://uat-talentcloud-backend.tbs-sct.ca/en/admin` instead of `https://uat-talentcloud.tbs-sct.gc.ca/en/admin`, and this will result in a 403 error.

**Comment by patcon** [comment]
If forwarding headers are preferred, would that resolve this? https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/
