### ISSUE TITLE
Chromatic - Over Limit

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2075]
It looks like we've hit our free monthly limit for Chromatic 14 days into the month.  Should we...
1) Just accept Chromatic diffs will work for a few days each month?
2) Reconfigure the github actions to do fewer automated diffs or diffs in fewer workflows?
3) Look into a paid plan?
4) Some combination of above?

![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/552c83f7-a203-46d6-92cd-30082852d46e)

**Comment by petertgiles** [comment]
Talk to managers about a paid account

**Comment by patcon** [comment]
Should we re-open this? I think we may need some mitigation tactics until this comes through.

Related: Just realized this was a thing which can help us conserve our limited snapshots, but it's a bit advanced to set up (says the instructions):
https://www.chromatic.com/docs/turbosnap

**Comment by petertgiles** [comment]
Well, once we get a paid plan lets see if we run out of snapshots again under our normal usage.  If we do I can open a new, more focused, issue.  I think the low hanging fruit would be to enable the flow for only frontend and disable for dependabot.  It would be nice to have for dependabot but not as important as developer PRs and it's probably where we're blowing most of our snapshots.

**Comment by patcon** [comment]
Organized the later fixes above, just a place to keep em. Some is already done, and there's now a one-liner fix in a new draft PR.
