### ISSUE TITLE
Add viewport support for Chromatic

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#2078]
Re-ticketed from https://github.com/GCTC-NTGC/gc-digital-talent/pull/1992#issuecomment-1030336335

Blocked on https://github.com/GCTC-NTGC/gc-digital-talent/issues/2075

Chromatic can test specific components (or all) on multiple viewport sizes. This would help us :
1. test story variants with long inputs on small viewports,
2. discover regressions we might miss by not doing QA on various viewports

https://www.chromatic.com/docs/viewports

**Comment by esizer** [comment]
For reference, we have done this for the IAP homepage story.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/8605ee3b8ee585c333bada7f98fa1afcfe11398b/frontend/indigenousapprenticeship/src/js/components/Home/Home.stories.tsx#L27-L42
