### ISSUE TITLE
Set Jest to to load hydrogen styles

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2080]
We sometimes use hydrogen styles for structural changes to the pages.  Without the generated hydrogen.css file we can't test this in jest.  Is there a way to configure this?
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/5eff039a-4fdf-413c-8227-1f56327d6924)

**Comment by brindasasi** [comment]
Communicate with the team if this  is not going anywhere. Raise the alarm so we can go ahead with workaround.

**Comment by petertgiles** [comment]
I worked on this for a few hours but didn't get very far.  Most answers that I found on Google were some variant of "Why are you trying to test styling in your unit tests?".  Anyway, I'm going to throw this back in the queue in case anyone else wants to give it a whirl.  I'm attaching some tests in case they help you get started, though.[https://app.zenhub.com/files/364642496/53d75c6b-da80-4d02-b1a7-33709c3dd66b/download](https://app.zenhub.com/files/364642496/53d75c6b-da80-4d02-b1a7-33709c3dd66b/download)

**Comment by brindasasi** [comment]
I spent some time on it and couldn't get very far on this. Discussed with the team and putting this into backlog for now as it is exceeding its value vs effort.

**Comment by mnigh** [comment]
@petertgiles is this still an issue or has hydrogen 2.0 make this possible?

**Comment by mnigh** [comment]
@substrae is this issue something you would have any insight on?

**Comment by substrae** [comment]
Hmm, I'm probably going to need more specific context on what you're trying to accomplish here. If "testing styling in jest" is a no go, then this isn't Hydrogen specific and is more likely an indication that we should be hiding/showing without CSS... though that seems like a pretty bad restriction.

**Comment by substrae** [comment]
You might be able to test for whether the attribute itself is present on the element as a workaround. Assume Hydrogen is doing its job and test that the attribute is being properly set.

**Comment by mnigh** [comment]
@petertgiles the example in the description is no longer in the codebase. is there another example you can provide where this is still a problem?

**Comment by esizer** [comment]
I feel like visual testing does not fall under the purview of jest and these types of tests are better suited to Cypress or storybook. Wondering if this could be closed and we add something to documentation about visual testing (assuming the team agrees).
