### ISSUE TITLE
Improve README as project entry point

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#2081]
Went to go share the link to the repo with some friends at [an outside group doing digital/gov innovation work](https://twitter.com/RadxChange), and realized that the README is missing some contextual pointers (beyond the tech specifics)

I realize that this document is primary a tech resource, and not suggesting it should try to do too much, but with open source, I usually try to have the main entry points invite people to "spider off" in other directions as they learn, so that the README (as the entry for tech people) can bring them totally up-to-speed.

Here's a list of awesome readme we can steal ideas from (yay inspo): https://github.com/matiassingers/awesome-readme

Here's a stellar README from an 18F project: https://github.com/18F/identity-idp#readme

Here are some READMEs I've had some part in shaping (maybe inspo):
- https://github.com/42wim/matterbridge#readme
- https://github.com/compdemocracy/polis#readme
- https://github.com/womenandcolor/women-and-color-frontend/#readme

I've happy to test onboarding from just the README at a civic hacknight, with some outsiders. Might be a neat way to say "hello" to those groups, in an informal capacity :)

cc: @vd1992 for review

**Comment by brindasasi** [comment]
Please check with Matt Jackson with related to info about the project

**Comment by tristan-orourke** [comment]
I'd love to see @patcon's proposed skeleton for our readme, and then we can go to Matt Jackson for a project description and any other copy like that.

**Comment by patcon** [comment]
Spike from Matt Jackson: https://docs.google.com/document/d/147dcivGQZY3r2fuVv8zWN9OleyMYQuqlGgMafb5Hl2o/edit#heading=h.7ijszk5f4lc

**Comment by vd1992** [comment]
are there really any prerequisites? 
contribution guidelines, guidelines for being respectful and the workflow summary I feel

**Comment by mnigh** [comment]
@GCTC-NTGC/developers would be interesting to revisit our root `README.md` over a year after this issue was created. @patcon is there anything still lacking from it you think would be an easy win to add/edit/remove?
