### ISSUE TITLE
Checkbox with long label is awkward

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2091]
The checkbox component looks pretty awkward with a long label.  Can we polish this a bit?
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/63b0204f-0097-4d0e-bffd-30972a8c6e2f)

Here's a Storybook story to get started with.
```
export const LongTextCheckbox = TemplateCheckbox.bind({});
LongTextCheckbox.args = {
  id: "iAgree",
  name: "iAgree",
  label:
    "I agree to share this information with verified Government of Canada hiring managers and HR advisors who have access to this platform.",
  context: "This is a really long string.",
  rules: { required: "This must be accepted to continue." },
};
LongTextCheckbox.parameters = {
  viewport: {
    defaultViewport: "mobile1",
  },
};
```

**Comment by yonikid15** [comment]
This is what the checkbox with a long label looks like now:
![image](https://user-images.githubusercontent.com/22059495/157886459-67b27645-1c5f-4b37-96af-7b66151ebbe0.png)

**Comment by petertgiles** [comment]
It's... different, I guess. 😆   I'm not sure if that's better or worse.

**Comment by JoshBeveridge** [comment]
This is probably how I would go about it...

![image](https://user-images.githubusercontent.com/6960386/157922433-840f936c-c36f-4594-9d7d-2f8c241fcd64.png)

**Comment by mnigh** [comment]
Accidentally reverted in https://github.com/GCTC-NTGC/gc-digital-talent/pull/3051.

**Comment by mnigh** [comment]
New issue created:

- https://github.com/GCTC-NTGC/gc-digital-talent/issues/5590
