### ISSUE TITLE
Research nonce usage

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2134]
We're adding nonce verification in #2086.  We're generating the nonce in our PHP controller and verifying it there alongside the `state` but we have some doubts about the implementation.  The open ID specification could be interpreted as having the nonce generated by the react application in the browser and have it verified there when the id token is returned.  Let's do some research to verify the best implementation.

## 🛑 Blockers
```[tasklist]
### Blocked By
- [ ] #2572
- [ ] #4916 
```

**Comment by gggrant** [comment]
Reach out to Doug from SiC or Po from cybersecurity for best practices.

**Comment by gobyrne** [comment]
Might not be relevant after PKCE work currently underway.

**Comment by mnigh** [comment]
@petertgiles is this issue still relevant or can it be closed as not planned?

**Comment by petertgiles** [comment]
I would say, yes, it's still relevant in the sense that I'm still unsure of our current implementation.  I don't think the "blocked:question" label is appropriate since the purpose of the issue is to answer a question.
