### ISSUE TITLE
Logout landing page

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2135]
When the user is logged out of our auth provider they are redirected back to a whitelisted URL.  Do we want a *You have been logged out* landing page for them to come back to?

**Comment by petertgiles** [comment]
Comments from standup:
- Since the redirection is happening with browser navigation (not javascript) it has to be a real URL
- We can have SiC whitelist as many URLs as we want so we can have multiple landing pages if desired
- With my current PR I'm redirecting back to the regular /admin page which is fine for now

**Comment by tristan-orourke** [comment]
@JoshBeveridge could you add your prototype here?

**Comment by tristan-orourke** [comment]
Will close this in favour of other tickets coming soon!
