### ISSUE TITLE
Hiring managers can use dedicated portal for hiring under  IAP

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#2138]
As a hiring manager I want to use a dedicated portal designed for submitting talent requests under IAP so that we can customize the skills and experience requirement for the candidate requisition

Assumptions : 

- This is a single page application with a submission form hosted under TalentCloud site
- No user registration required.
- This application uses the same db as TalentCloud

Acceptance Criteria : 
- Submission form should be as in https://gc-demo-b13fe2.webflow.io/apprenticeship
- Successful submission should give back the registration no. 
- Failure submission should not wipe out the form details
- Form should have browser side caching enabled to avoid any data loss

Pending Requirements
-  URL name

**Comment by gobyrne** [comment]
It's no longer clear that this will be needed. The request system is not as useful for the apprenticeship program as there are no pre-requisites based on skills and is intended only for entry-level positions.
