### ISSUE TITLE
Hiring manager can access the  submission form with the submit button

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#2143]
As a hiring manager I would like to access the submission form via the landing page in the portal and able to submit the form 
https://gc-demo-b13fe2.webflow.io/apprenticeship

# Acceptance Criteria: 

- [ ] Form should contain the following sections as per the mock up  ( Please note wireframe shows as 2 page . But we are doing them in a single page only) 
  - [ ] Opportunity area
  - [ ] Apprenticeship details 
  - [ ] Condition of employment 
  - [ ] covid-19 policy 
  - [ ] Request form 
  - [ ] Details of the opportunity 
  - [ ] Specifics about your team

- [ ] Form Should have submit and back button 
- [ ] Form should not submit if the required values are missing 
- [ ] Submit button  submits the data into the backend ; upon successful submission get the reg. id back. ; upon failure get the error msg; ( Result will be displayed in the next story )  
- [ ] Back button should take the user to the prev page 
- [ ] If the user moves back and forth without submitting , the form should still retain the values on the browser 
- [ ] Upon any failure , form should still retain the values on the browser 
 

Questions 
- Do we need a new model? 
- Which table we are storing into? 
- Do we need a sep backend story for this ?

**Comment by brindasasi** [comment]
As a hiring manager I would like to access the submission form via the landing page in the portal and able to submit the form 
https://gc-demo-b13fe2.webflow.io/apprenticeship

Acceptance Criteria: 

-Form should contain the following sections as per the mock up 
- Opportunity area
- Apprenticeship details 
- Condition of employment 
- covid-19 policy 
- Request form 
- Details of the opportunity 
- Specifics about your team

- Form Should have submit and back button 
- Submit button  submits the data into the backend ; upon successful submission get the reg. id back. ; upon failure get the error msg; ( Result will be displayed in the next story )  
- Back button should take the user to the prev page 
- If the user moves back and forth without submitting , the form should still retain the values on the browser 
- Upon any failure , form should still retain the values on the browser 
 
Questions 
- Do we need a new model? 
- Which table we are storing into? 
- Do we need a sep backend story for this ?

**Comment by gobyrne** [comment]
Originally this was of high importance for the apprenticeship program, but now they have a process set up and we probably will not need to build it. Closing since we do not expect to complete.
