### ISSUE TITLE
Hiring manager should be redirected to registration confirmation page upon submitting the form

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#2146]
As a hiring manager I should see a pop up notification for registration confirmation upon submitting the form so that I know whether the form has been submitted successfully or not .

Wireframe: 
https://gc-demo-b13fe2.webflow.io/apprenticeship

![Screen Shot 2022-02-24 at 10.49.41 AM.png](https://images.zenhubusercontent.com/61a7bd49e20af80694dd845e/defca0e0-af49-40b3-bac8-14b6ef3b9800)

# Acceptance Criteria
- [ ] Upon successful storing into the db , user should be redirected to registration confirmation page
- [ ] Upon any failure error msg should be appeared on the pop up and form should retain its values 
- [ ] static content should be displayed  on _what you can expect_  as per the wireframe

**Comment by gggrant** [comment]
Required for CMO search page.

**Comment by gobyrne** [comment]
@Jerryescandon can we add this to the "Search page refresh" as well?

**Comment by Jerryescandon** [comment]
Clasing this for now, will make a new one.
