### ISSUE TITLE
Experiment - try connecting Dev server to Azure B2C Auth service

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2148]
# Description
GCExchange team has set up an Azure B2C tenant for us to experiment with using as an alternative to SiC. Try to get Dev authenticating with this service.

It may be as simple as creating a new client and changing the OAUTH url env vars. It may be more complicated - will introspection and logout work exactly the same? Will the fields be all the same?

If there is much different, it may be worth looking at Laravel plugins that can abstract some of this stuff.  https://github.com/metrogistics/laravel-azure-ad-oauth

**Comment by tristan-orourke** [comment]
Timebox 1 day

**Comment by petertgiles** [comment]
Unblocked.  Tristan and I have access to try this now.
