### ISSUE TITLE
Definition of Ready / Definition of Done

### ISSUE THREAD

**Issue by gggrant** [GCTC-NTGC/gc-digital-talent#2209]
Meet with the team to discuss our Definition of Ready / Definition of Done.

Determine criteria for each based on the meeting.

Write each and share with the team.

Ensure team adheres to the Definition of Ready / Definition of Done that was formulated (ongoing).

**Comment by patcon** [comment]
Really glad for these to be in repo 🎉 

I adding some related todos to describe some connection I made to other work happening (re: onboarding)

**Comment by patcon** [comment]
Some thoughts -- 🔍 facts, ❤️ feelings, 💡 ideas:

- 🔍 we have a place to store approved DoD items: http://go.talent.c4nada.ca/done 
- 🔍 we had a short-lived conversational ticket for DoD (this), but it's closed
- 🔍 we discuss potential DoD items at retro
- ❤️  we don't and shouldn't accept all ideas in a retro. we have a specific pace of change that has a limit, and sometimes timing isn't right for a potentially useful idea
- ❤️  I'd like to capture all ideas for DoD, even "bad" ones or ones for which it is not appropriate timing
- 💡 let's have an ongoing place to log a clear hyper-inclusive log of all suggested DoD items
- ❤️  I feel ambivalent about where this lives: GitHub issue, new gdoc, section of existing gdoc, repo markdown file, etc

Specific ideas:
- redirect policy. h/t @petertgiles 
- scripts to smoothly accommodate big changes / migrations in codebase h/t @tristan-orourke
