### ISSUE TITLE
The Submit button component contains non-localized text

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2211]

**Comment by petertgiles** [comment]
I think Yoni just fixed this in #2184 ?
https://github.com/GCTC-NTGC/gc-digital-talent/pull/2184/files#diff-e5e01d599d3e7b53f33db6f0eacd502a60e80f90151fcda75d7fc346c821b0f1

**Comment by tristan-orourke** [comment]
Ah my bad, I was on an old branch!
