### ISSUE TITLE
Radio label formatting

### ISSUE THREAD

**Issue by RVany** [GCTC-NTGC/gc-digital-talent#2214]
In the **issue** [https://github.com/GCTC-NTGC/gc-digital-talent/issues/1923]

- Part of radio labels and checkbox labels are need to be bold ([wireframe](https://www.figma.com/proto/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?node-id=2485%3A4764&starting-point-node-id=1%3A2))
- Typescript giving error when bold effect  apply inside the intl.formatmessage method!
- Items probs of the RadioGroup Component should accept label with type of React.Node as well.
- Its may be very easy fix.

**File Needs to be modify**
frontend\common\src\components\form\RadioGroup\RadioGroup.tsx

**Related Line of code**
`export type Radio = { value: string | number; label: string | React.ReactNode }; 
`
**Issue Occured**
`value: "only-indeterminate",
                  label: intl.formatMessage(
                    {
                      defaultMessage:
                        "...only those of an <bold>indeterminate</bold> duration. (permanent)",
                      description:
                        "Label displayed on Work Preferences form for indeterminate duration option.",
                    },
                    { bold },`

**Comment by RVany** [comment]
Ha Ha.. I am playing with labels.

**Comment by RVany** [comment]
Since the optional preferences are retrieving from db, I think the display order also is an issue if it is a matter.

 [The Issue](https://github.com/GCTC-NTGC/gc-digital-talent/issues/2212) may fix it.

**Comment by RVany** [comment]
This needs to be done to bring bold label in most of the profile forms.

**Comment by vd1992** [comment]
I think we want all form pieces to accept 'String | Element` instead of just `String`. So I think this issue can instead be to ensure all form pieces have their inputs adjusted accordingly.
Is that fine with you, @petertgiles ?

**Comment by petertgiles** [comment]
> I think we want all form pieces to accept `String | Element` instead of just `String`.

Sounds good to me :+1:

**Comment by RVany** [comment]
@petertgiles I was thinking Its resolved by #1921. Isn't correct?
