### ISSUE TITLE
Add API operations to Work Preferences form

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2215]
# Description

Add api operations to populate initial values of form, and to submit values of form.

- Get values of Work Preferences from Applicant object to populate initial values.
- Update the User with new Work Preferences values when submitted. 
- Get/update the accepted OperationalRequirements from User model.
- WouldAcceptTemporary field.

[Wireframe](https://www.figma.com/proto/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?node-id=2485%3A5000&starting-point-node-id=1%3A2)

# Acceptance Criteria
- [ ] API integrated with Work Preferences form.
- [ ] API responds with success/failure toast message.
- [ ] Navigation to Applicant Profile on success.

**Comment by petertgiles** [comment]
Could we add a sort order to this form to match the wireframe while you're working on it?  The enumToOptions function has an optional parameter to request a sort.

**Comment by RVany** [comment]
Do you mean order of the checkboxes? I will check when I reach that point. Are the field labels matching the wireframe?
