### ISSUE TITLE
Remove duplicate User fields from Pool Candidate and wire up User

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2218]
The following fields were added to the User model. They must now be removed from Pool Candidate.
```
    isWoman: Boolean @rename(attribute: "is_woman")
    hasDisability: Boolean @rename(attribute: "has_disability")
    isIndigenous: Boolean @rename(attribute: "is_indigenous")
    isVisibleMinority: Boolean @rename(attribute: "is_visible_minority")

    hasDiploma: Boolean @rename(attribute: "has_diploma")
    languageAbility: LanguageAbility @rename(attribute: "language_ability")
    locationPreferences: [WorkRegion] @rename(attribute: "location_preferences")
    locationExemptions: [String] @rename(attribute: "location_exemptions")
    acceptedOperationalRequirements: [OperationalRequirement] @belongsToMany
    expectedSalary: [SalaryRange] @rename(attribute: "expected_salary")
    expectedClassifications: [Classification] @belongsToMany
    wouldAcceptTemporary: Boolean @rename(attribute: "would_accept_temporary")
    cmoAssets: [CmoAsset] @belongsToMany
```

# Acceptance Criteria:
- [ ] Remove fields from the Pool Candidate model
  - [x] Database migration
  - [ ] Laravel models
  - [ ] Seeders, factories
  - [ ] GraphQL schema
- [ ] Admin site form updates
  - [ ] Pool candidate create
  - [ ] Pool candidate edit
  - [ ] User create
  - [ ] User edit

**Comment by tristan-orourke** [comment]
We should be very careful about removing fields from API - must make sure they're not in use anywhere. Maybe they should just be marked `@deprecated`?

**Comment by vd1992** [comment]
given that this follows the execution of the command found here
https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/api/app/Console/Commands/MigratePoolCandidatesToUser.php

I feel the scope of this issue can be to account for everything rendered obsolete by it, so the CmoAsset-PoolCandidate and Classification-PoolCandidate relations too

Which offsets how I believe there are zero form updates required on /admin now
