### ISSUE TITLE
Write a support script/doc to help dev team use git-bisect

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#2251]
Re-ticketed from https://github.com/GCTC-NTGC/gc-digital-talent/pull/2082#issuecomment-1062114725

`git-bisect` is essentially a way to tell git:
- this is a known-good commit/branch/tag (e.g., some old commit)
- this is a known-bad commit/branch/tag (e.g., usually the HEAD commit)
- this is a `script.sh` that will fail when commit's bad, and succeed when it's good

and then `git-bisect` will keep splitting the difference and auto-running the script. You can walk away and come back to `git` telling you exactly when things went off the rails. That way, you can see the exact change that initiated the failure, and work from there.

This is a really helpful command. We could write a simple script to use as a basis from running `git-bisect` (e.g., a simple build), and make it much easier to use for team members :)

cc: @tristan-orourke @petertgiles

**Comment by gobyrne** [comment]
@brindasasi is adding to our list of ideas for Friday learning session.
