### ISSUE TITLE
Experiment Proposal: Team member READMEs

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#2263]
@patcon had a convo with @petertgiles yesterday about learning to be aware of our own strengths and weaknesses. we discussed "team member READMEs" (aka "developer READMEs").

**Team member READMEs** are a document that act like a project README, but for people. They're often like a one-pager, but can be more or less. They can use a template. They are intended to share what others need to know in order to work best with you. The idea is to be forword-thinking, rather than everyone discovering these things through personal 1:1 interactions (and potential conflict).

This README often includes things like strengths (thing you can offer support on), weaknesses (things you need support on), and default modes/styles of thinking. Also, it can have anything we want (LOVE LANGUAGES???)

How does this proposal for tasks work @JoshBeveridge?

### Open Questions

1. ~~Is it ok if @JoshBeveridge and I pilot something?~~ Yes.
2. ~~should someone else be involved?~~ voluntary additional participation for "pilot"
3. ~~should someone else be involved in this decision/plan?~~ Not needed.
4. How do we track this work? In a GitHub issue? (it's not technical, per se)

### Proposed To Dos
- [x] josh and patcon discuss [others interested in pilot?]
- [x] find/share CDS team member READMEs
  - [x] checked every github profile of [every CDS member with public membership](https://github.com/orgs/cds-snc/people). [EDIT: no luck]
  - [x] [ditto for ONgov](https://github.com/orgs/ongov/people). [EDIT: no luck]
  - [x] ask @sboots for pointers [via Twitter](https://twitter.com/patcon_/status/1506018876387115008) -- @patcon
- [ ] find samples/article of team member READMEs -- all
  - josh: Some basic Google reading:
    - https://www.forbes.com/sites/forbescoachescouncil/2019/09/05/does-your-team-need-your-personal-readme/?sh=79cc472661dd
    - https://hackernoon.com/12-manager-readmes-from-silicon-valleys-top-tech-companies-26588a660afe
    - https://managerreadme.com/
    - "manual of me" [h/t Luke Simcoe](https://twitter.com/Code4Luke/status/1506054386534916098)
    - https://github.com/coderjojo/creative-profile-readme
- [ ] draft prototype READMEs
  - [ ] @patcon 
  - [x] @JoshBeveridge - [initial draft here](https://workflowy.com/s/joshs-readme/WsXzbLFAqwHQOMS5)
  - [x] @petertgiles - [PDF](https://drive.google.com/file/d/1veslJQwbcVhMV6pLTxaiRxth73UFziZ1/view?usp=sharing) :lock:
  - [ ] @brindasasi - TBA
  - [ ] [others?]
- [x] ~~experiment: go/no-go decision? -- josh, patcon, grant~~
- [ ] review one another's drafts [async]
- [ ] integrate feedback [async]
- [ ] share with larger team, get feedback -- DUE: FRI MAR 25
  - [ ] team: go/no-go decision? -- all team
- [ ] spin out new ticket(s)
- add to onboarding: http://go.talent.c4nada.ca/onboarding
  - [x] added stub: https://trello.com/c/qOLk54Cm/32-team-member-readme
  - [ ] write final version
  - [ ] +1 Tristan at onboarding call
- [x] create a landing page for finding all the team READMEs
    - http://go.talent.c4nada.ca/team-readmes
- [ ] decide on a good name (quirky? fun? personality?)
  - ~~developer readme~~
  - team member readme
  - manual of me
  - ... [ideas?]

cc: @tristan-orourke @gobyrne @brindasasi

**Comment by patcon** [comment]
@JoshBeveridge and I just met for 30min (and were joined later by @gggrant @vd1992 @JamesHuf )

### Scratch Notes

* josh: couldn’t find a real best-practice template
* CDS is doing this (really like theirs)
  * [ ] #todo find/share CDS team member readmes
* josh: struggling with balance of repeating info
   * just send ppl to website
   * might not want to have “how I work” info on website
* website has links to other places
* josh: let's be anti-duplicate. link to other places. +1 pc
  * pc: similar to sprawling open source projects that have READMEs that have some sections with just "See [`<shared thing>`](https://example.com)"
  * 💡 pc: could just link out to other place in readme #idea
* high level category ideas
   * josh
      * intro, basic
         * timezone
         * best work hours
         * meeting preferences
      * section for role. hierarchy perspective
      * skills: strengths/weaknesses
      * communication (where, how i prefer)
   * patcon:
      * strength/weakness
         * communication
         * power
      * hierarchy.
      * keybase
      * connections (centers and betweens), networks
      * relationships
      * various duality / axes
        * order / chaos axes
        * other?
      * love languages
      * loom video intro. minimal info, just a hello: me in motion. help baseline my "tone"
      * audio pronunciation of name (linkedin does this)
      * pronouns
      * maps. geojson embed?
* josh: aspiration is that this is content prototype for new website
  * less like CV, more "here's me"
* pc: tools? how we work (tangent)
  * appreciate structure of workflowy over obsidian. less overwhelming.
  * [ ] #todo schedule "workflow swap" session. 
  * workflowy vs obsidian. roam.
* #decision DEADLINE: friday? present to everyone in post-scrum topic.
* 💡  josh: design team did collab version. #idea

**Comment by JoshBeveridge** [comment]
An example of my "User Manual" from my work with CDS

![image](https://user-images.githubusercontent.com/6960386/159568496-1cb31c5e-7365-4530-8587-4fe0fcea8c51.png)

**Comment by patcon** [comment]
The Twitter thread kinda snowballed:
https://twitter.com/patcon_/status/1506018876387115008

- User Manual of Me
  - [Cassie Robinson](https://cassierobinson.medium.com/a-user-manual-for-me-d3a851fbc694)
  - [Sean Boots](https://twitter.com/sboots/status/1506307116830793729)
  - [Kelsey Merkley](https://medium.com/@bella_velo/a-user-manual-to-me-covid-19-edition-f21ef45cfc79)
  - [some guy named Matthew](https://www.manualof.me/s/matthew)

**Comment by JoshBeveridge** [comment]
Updated the initial issue description with a link to my draft Workflowy :)

**Comment by gggrant** [comment]
To discuss at retro.

**Comment by gobyrne** [comment]
We've done a number of these now. Great initiative @patcon. I'll close this issue though, feel free to reopen if needed.
