### ISSUE TITLE
API schema security review

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2266]
# Description
We use [Laravel policies](https://laravel.com/docs/9.x/authorization#writing-policies) and the [@can](https://lighthouse-php.com/5/api-reference/directives.html#can) directive to secure our API. Only certain users have permission to run certain queries and certain mutation.

However, with the way many graphQL types are linked together, it can be possible for us to end up with a schema where models are unintendedly exposed via nesting in other, less secure objects. 

Right now, Pools can be queried by the public. The owner field exposes the User model, which is supposed to be protected. This needs to be fixed, one way or another.

We have talked about wanting to avoid use of field-level permissions. That means we must be very careful of how we link models together. As a starting point, User should probably **never** be nested in a field, since it exposes so much. Instead, we should use other versions of User with only the required data, like Applicant and UserPublicProfile.

As another point, even if two models are symmetrically linked at the database level, they don't need to be symmetrically linked at the schema level. Eg Just because Users have a PoolCandidate, maybe doesn't mean PoolCandidates need a User field.

# Timebox
2 days

# Acceptance Criteria
- [ ] complete a full review of the schema and determine if there are any other models we should be similarly careful about
- [ ] device a strategy to help us avoid this problem in the future
- [ ] document the strategy

**Comment by patcon** [comment]
How quirky would it be to avoid nesting any secured objects for now, and always do a separate call? We could have helpers to "re-stitch" these calls into one object, if we really want to continue building interfaces as if the objects are coming back a single responses.

That would allow us to get more clever with auth logic later, but for now, we have really clear assurances that every api call has proper authentication, and less need to have "ongoing" concern with exposing things.

Disclaimer: I'm lacking a lot of context on how this is happening in the codebase right now, and how hard it would be to implement this "easier" fix I'm suggesting vs the other options :)

**Comment by tristan-orourke** [comment]
Here's a post about creating a custom directive, which I don't think is _exactly_ what we want, but might help. https://stackoverflow.com/a/63405046/19489950

**Comment by tristan-orourke** [comment]
Its actually quite easy to do role-based field-level permissions. For example, only ADMINS and MANAGERS can view this field. But that means that _all_ admins and managers can view the field. The tricky part is getting the field-level permissions to work which take the current user and the current model into account, as in, only the Owner of this object can view this field.

**Comment by tristan-orourke** [comment]
Oh! This, or a custom directive based on it, might give us what we want:
https://lighthouse-php.com/5/api-reference/directives.html#whereauth

**Comment by esizer** [comment]
https://lighthouse-php.com/5/security/authorization.html#custom-field-restrictions

**Comment by tristan-orourke** [comment]
This also related to #2365

**Comment by tristan-orourke** [comment]
## Assumptions
1. Avoiding duplicate code is good. It reduces file size, it reduces work involved in maintaining similar types in different places, and reduces the risk of types drifting apart when they shouldn't.
2. Reducing the number of directives in the schema is good. Directives reduce the simplicity and readability of the schema by adding hidden functionality as well as visual noise.
3. Expressing entity relationships directly in the schema is good. This allows the schema to document the underlying relationships, and gives API clients more flexibility.
4. For performance reasons, it is better to run fewer Policy methods during a given query.

## Arguments
5. Given point 3), we should represent as many relationships as possible in the schema and protect them with field-level permissions, instead of carefully leaving relationships out of the schema and only guarding top-level queries.
6. Given points 2) and 4), we don't want to have to guard every field with its own directive. Therefore, we should design our types such that most of the fields in a type require the same level of permissions. In other words, if a user has been permitted to view a type, most fields should not require further Policy checks. Mostly, relationships to other types should be expected to have field-level permissions.

## Conclusions
7. Given points 5) and 6), we should protect most non-scalar types with field-level permissions, and adopt composable types (re: #2365) is such a way so as to avoid field-level permissions on scalar types (except in rare cases).
