### ISSUE TITLE
Fix api schema vulnerability

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2267]
# Description
Based on #2266, but the quick version.
User should never be nested in another object, because we want to be extra careful about auth permissions on the User object. Remove it from Pool and PoolCandidate, and any other types containing it. If that breaks any existing queries in the app (rerun codegen and then build typescript to find out) then replace the User type in those objects with other, less detailed versions, like Applicant or UserPublicProfile.

# Acceptance Criteria
- [ ] the full User type is never nested in another object

**Comment by vd1992** [comment]
I think it'll be handy to comb through and try and find all instances of User nested within something. In some, like Query I think it makes sense to have User nested?

api/graphql
lines
195, 217, 491, 492, 493

admin/resources/poolcandidatesearchrequestoperations
line
77

admin/resources/poolcandidateoperations
lines
19, 72, 158, 199, 216

Type wise, pool, poolcandidate and query seem to be the ones with user nested in them and they interact with user in admin/resources. I think it is just pool and poolcandidate that need to get User removed?
