### ISSUE TITLE
Recognize all forms of contribution (not just codebase commits)

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#2269]
Re-ticketed from [message in `#gratitudes` Slack channel](https://talent-cloud.slack.com/archives/C035HUXCSJ2/p1647626683141519?thread_ts=1647626414.675719&cid=C035HUXCSJ2).

https://allcontributors.org/

## Rationale

GitHub does a great job of showing all the code contributors on a project. But there are many ways to contribute to open source that aren't code. AllContributors is 1) a specification for a standard file format to recognize contributions to projects of [various types](https://allcontributors.org/docs/en/emoji-key), and 2) a set of tools to make displaying that standard data in READMEs very simple.

We might like to recognize:
| emoji key | our contributors |
|---|---|
| ♿️ `a11y` | fable testers, a11y testers
| 🐛 `bug` | bug filers
| 📝 `blog` | PR content writers
| 💼 `business` | people who make business case for our project
| 💻 `code` | coders
| 🖋 `content` | content writers
| 🎨 `design` | designers
| 💵 `financial` | team members who deal with budget
| 🤔 `ideas` | testers/users who give us feedback/ideas
| 🚇 `infra` | server &  infra maintainers
| 📆 `projectManagement` | scrummasters
| 📣 `promotion` | people giving talks
| 🛡️ `security` | members of security team giving us advice
| 🌍 `translation` | translators (french, indigenous and first nations)
| 📢 `talk` | people giving talks
| 📓 `userTesting` | people doing user testing and a11y testing

### Adding contributors via bot

![](https://allcontributors.org/docs/assets/bot-usage.png)

### Auto-generated README section

<img width="971" alt="Screen Shot 2022-12-14 at 12 34 28 PM" src="https://user-images.githubusercontent.com/305339/207666822-cfef56eb-5ad4-4415-b036-aa314be6a190.png">

## Implementation

- one of these options (not both)
  - All Contributors GitHub Actions
    - https://github.com/marketplace/actions/all-contributors-action
    - https://github.com/ActionwareIO/all-contributors-action
  - All Contributors GitHub App: https://allcontributors.org/docs/en/bot/overview

### To Do

- [x] stub out ticket description
- [ ] make go/no-go decision
- [ ] add stub of `.all-contributors.json`
- [ ] create workflow to auto-generate README section
- update documentation
  - [ ] update `CONTRIBUTING.md` as needed
  - [ ] update `README.md` as needed
- [ ] stretch: enable bot or github action (for adding contributors from PR comments)

**Comment by gggrant** [comment]
To discuss at retro.

**Comment by gobyrne** [comment]
I don't feel strongly about this one. I think we can do better than tags in GitHub.

**Comment by mnigh** [comment]
@petertgiles was this ever discussed at retro (over a year ago 😄) and if so, what was the outcome?

**Comment by petertgiles** [comment]
> @petertgiles was this ever discussed at retro (over a year ago smile) and if so, what was the outcome?

I don't remember ever discussing this.  If someone wants to they can request that it gets discussed at a backlog refinement or sprint planning I guess.

**Comment by tristan-orourke** [comment]
A robot for our scale of project seems like overkill.
Most of our direct contributors are already visible via github.
