### ISSUE TITLE
Allow management of repo settings to occur through standard code review process (aka PR)

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#2302]
Re-ticketed from https://github.com/GCTC-NTGC/gc-digital-talent/issues/2264

There is a bot plugin called "probot:settings" (maintained officially by a GitHub staff member), that allows all the settings for the repo to be managed in a yaml file in `.github/`

https://github.com/probot/settings

### [Proposed] To Dos
- [ ] determine if this is valuable to team
- [ ] confirm these #todos look appropriate
- [ ] consider security implications. is this ok?
  - See: [Security Implications](https://github.com/probot/settings#security-implications) in README, and below
- [ ] authorize probot:settings app https://github.com/apps/settings
- [ ] convert current settings into yaml file
- [ ] create docs explaining how this works for us
  - [ ] add something to on-board about this 
- [ ] optional: ensure mainline is locked down (see below)
- [ ] merge PR to fully enable

#### Security Implications (summary for us)

essentially this plugin elevates everyone with `push` permission, to `admin` permission. We could either (1) be ok with this access for all team members, or (2) we could lock down mainline so no one can skip PR process and required reviews. That way, for (2), no one person's GitHub account is able to change repo settings unilaterally.

cc: @gggrant @tristan-orourke

**Comment by mnigh** [comment]
@petertgiles has there been a discussion on this approach amongst the team and if so, what was the decision?

**Comment by petertgiles** [comment]
I don't remember discussing this.  If someone wants to they can bring it up for backlog refinement or sprint planning.

**Comment by tristan-orourke** [comment]
Hmm. I don't know if I like those security implications. I think its useful to have true `admin` restrictions, even if they're not restricting much.

**Comment by mnigh** [comment]
> Hmm. I don't know if I like those security implications. I think its useful to have true `admin` restrictions, even if they're not restricting much.

I agree. I don't like the fact that it basically eliminates the use of GitHub roles without actually replacing the GitHub role system, thus creating competing authority ecosystems. From a security standpoint, there are quite a few scenarios that make me pretty anxious involving a quick PR approval.
