### ISSUE TITLE
Admin login - invalid state

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2309]
After running the setup.sh script a login on the admin site (to Laravel auth) results in a `Invalidate state` error.
Running an additional `composer install` seems to solve it but I'm not clear why.

May be related to #2304

**Comment by vd1992** [comment]
@petertgiles 
Does this happen anymore? Auth stuff has changed quite a bit

**Comment by petertgiles** [comment]
Yeah, Laravel auth is gone now.  I'm closing this.
