### ISSUE TITLE
Site map for GC Digital Talent WITH URLS

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#2314]
Figjam link: https://www.figma.com/file/n3PLf2KgobMp0kkH7HYx3i/Digital-Talent-and-Indigenous-Apprenticeship-Program---Sitemap?node-id=0%3A1

- Figure out what a good site map needs to be.
- First draft for discussion with Lauren
- If it's easy, include Direct intake. But ignore if it's causing confusion

**Comment by gobyrne** [comment]
Josh completed this. Please review and let us know if it meet your needs @petertgiles

**Comment by petertgiles** [comment]
Oh wow, this is super interesting!  I imagine this will spark a lot of discussion but this is a great start!  You guys rock.
