### ISSUE TITLE
Improve usability of phone number form fields

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2320]
# Description
Right now the API requires a specific format for telephone numbers, but it isn't the most obvious or what people are used to. 

Options:
1. We could make loosen the restriction altogether, just store a string in the database. Simple, easy. Downside - will end up with inconsistent data, making it hard to use in the future if we want to do something real with phone numbers.
2. Change the format - simply require a more familiar 123-123-1234 format, or (123)-123-1234. That only allows Canadian (and US) numbers - but that's maybe not so bad? 
3. Keep the international format in the database, but do some transformations when submitting to the database. Most flexible option, involves slightly more work.

WE'RE GOING WITH OPTION 1

## Acceptance Criteria
- [x] graphql schema still uses a custom scalar for phone number, but that scalar accepts any string as valid
- [x] any telephone number form fields likewise accept any string in frontend validation

**Comment by petertgiles** [comment]
Personally I like option 1.  I feel like sooner or later we're going to want to store a non-compliant string - like someone has a  number in another country with 9 digits or 15 digits or something.  Or they want to add extensions and stuff.  That said, I think we can build a super-smart phone number input component on the frontend that helps the users get it right.

**Comment by petertgiles** [comment]
Found this on wikipedia: https://www.noslangues-ourlanguages.gc.ca/en/favourite-articles/to-drop-or-not-to-drop-parentheses-in-telephone-numbers/

**Comment by petertgiles** [comment]
Possible duplicate: #2499

**Comment by patcon** [comment]
+1 to (1) storing a simple string, but then handle rendering like (2) in the UI, with failover to just whatever is in database. Deal with (3) when there are significant failovers where the above stops working :)

aka WE GO INTERNATIONAL. SO COOL. SO FAMOUS

**Comment by tristan-orourke** [comment]
We'll go with leaving it flexible for now. We could clean up the DB later if it ever became relevant.

**Comment by tristan-orourke** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/2320?planning-poker) with ZenHub @JamesHuf
