### ISSUE TITLE
Cannot update users through admin panel

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2321]
# Description
After recent changes to updateUser mutation, updating users through the Admin panel doesn't work.

# Steps to reproduce
1. Go to User table on admin portal
2. Click edit on existing user
3. Ensure all fields contain values
4. Click submit
5. See error

**Comment by vd1992** [comment]
1. Checked out Main, refreshed environment, attempted to replicate error, error reproduced
2. Checked out this branch, refreshed environment, attempted to replicate error, error did not appear
3. Issue appears resolved

Nice work Peter, I think things are solved? Not sure if anything else was broken.
Solution makes sense, cannot update all those other fields newly added to User, need to exclude them for the time being. Will need to adjust the forms later for the new fields though?
