### ISSUE TITLE
Toast notification not styling correctly

### ISSUE THREAD

**Issue by JamesHuf** [GCTC-NTGC/gc-digital-talent#2354]
Certain toast notifications appear to have the text overflow the bounds of the box as in the image below.

![image.png](https://images.zenhubusercontent.com/61d4c65971f41272c88f9a81/8b4b5e67-ad56-40ad-a3ed-efe43a82705d)

**Comment by JamesHuf** [comment]
Similar image with text colour changed to better stand out
![image](https://user-images.githubusercontent.com/49166751/160457080-16c428dc-40d9-41b7-94c8-d9c909f9e47b.png)

**Comment by gggrant** [comment]
Test on prod server (ensure full error messages aren't exposed).

**Comment by gggrant** [comment]
Divide into separate issues.

**Comment by esizer** [comment]
If we have steps to reproduce, I can take a look at this. I'm not sure if we need to divide. We can "hide" the longer messages with some CSS (follows). Though, developing a policy around max character count would be a good practice as well to avoid needing to truncate error messages.

```css
.toast {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}
```

**Comment by patcon** [comment]
Maybe related to this general "where to log, but not leak too much info" problem, for later (not now 🙂 )

https://github.com/getsentry/sentry 

(Sentry = open core SaaS platform for logging/crash management used by many large orgs)

re: https://github.com/GCTC-NTGC/gc-digital-talent/pull/2524#issuecomment-1104166898 cc @tristan-orourke
