### ISSUE TITLE
Browserlist settings factored out

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2360]
Right now our browserlist compatibility settings (for polyfills) is in the babelrc files.  For clarity and functionality we might want to move these settings out, for example to the package.json files or even to their own files.

QUESTION: package.json or its own file?

**Comment by esizer** [comment]
My preference is to have its own file `.browserslistrc` so it is obvious where we are maintaining the items.  It might not always be obvious that the browser support list is maintained in `package.json` and to be honest, I never even knew that you could have it in `.babelrc` until reading this issue.
