### ISSUE TITLE
Figure out a "feature flag" solution

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2363]
# Description
We need a way to add features to main branch without releasing them to public. (eg routes to new Applicant Profile pages)

This issue currently up for discussion.

**Comment by patcon** [comment]
Drats, I just have not his submit on another comment with resources. I'll dig them up again later.

New link to relevant HN convo with a really interesting answer (never done this myself, but I think I can see the point they're getting at): https://news.ycombinator.com/item?id=30899906

> > Sorry for maybe a silly question, but **how do feature flags work with migrations?** If your migrations run automatically on deploy
>
> **Basically they don't.** Database migration based on frontend deploy doesn't really make sense at facebook scale, because deploy is no where close to synchronous; even feature flag changes aren't synchronous. I didn't work on FB databases while I was employed by them, but when you've got a lot of frontends and a lot of sharded databases, you don't have much choice; if your schema is changing, you've got to have a **multiphased push:**
> 1. push frontend that can deal with either schema
> 2. migrate schema
> 3. push frontend that uses new schema for new feature (with the understanding that the old frontend code will be running on some nodes) --- this part could be feature flagged
> 4. data cleanup if necessary
> 5. push code that can safely assume all frontends are new feature aware and all rows are new feature ready
> 
> **IMHO, this multiphase push is really needed regardless of scale,** but if you're small, you can cross your fingers and hope.

**Comment by petertgiles** [comment]
I'm not sure our needs are complex enough to warrant adding a new dependency or integrate a 3rd party service.  Could we get away with just adding an environment variable or two to webpack and using those in conditionals for components in test?

Google brought me here: https://www.flagship.io/feature-flags-react-app/ which was a pretty good read.  He linked to [this project](https://github.com/sergiodxa/flagged) (among others) which looked good if we do want to go with a new dependency.
