### ISSUE TITLE
Refactor graphql Schema to reduce code duplication

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2365]
# Description
We have a lot of duplication in our graphql schema, eg with User and Applicant, and with certain input types (eg CreateUser and UpdateUser). It would be much easier to maintain if there were some way to modularize and use chunks of these types.

Unfortunately, such features don't appear to be native to graphQL. We can make an effort to use *composition* over *inheritance*, but in some cases (eg User/Applicant) that won't work. 

I have found a library which allows you to inherit types in a way that would be super helpful: https://github.com/nicolasdao/graphql-s2s . We would need to figure out how to get it working along with lighthouse-php.

TIMEBOX: 1 day

## :question: Spike Question
- [ ] What are the best options to refactor out duplication in the schema?

**Comment by tristan-orourke** [comment]
[git push --set-upstream origin feature/self-directive](https://github.com/GCTC-NTGC/gc-digital-talent/tree/feature/self-directive)

**Comment by tristan-orourke** [comment]
Taking another quick look at the [graphql-s2s](https://github.com/nicolasdao/graphql-s2s) library I mentioned above... it's a js library, and won't be much help to our php implementation. 

An alternative approach I was considering would be to define our types in such a way that we can compose types, like User, out of other types, like Applicant. I did a bit of work on a `@self` directive that might aid this, on this unmerged feature branch: https://github.com/GCTC-NTGC/gc-digital-talent/tree/feature/self-directive

**Comment by tristan-orourke** [comment]
## Assumptions
- Avoiding duplicate code is good. It reduces file size, it reduces work involved in maintaining similar types in different places, and reduces the risk of types drifting apart when they shouldn't.
- Reducing the number of directives in the schema is good. Directives reduce the simplicity and readability of the schema by adding hidden functionality as well as visual noise.
- Expressing entity relationships directly in the schema is good. This allows the schema to document the underlying relationships, and gives API clients more flexibility.

## Facts
- The GraphQL spec [does not allow](https://stackoverflow.com/questions/47523384/how-to-inherit-or-extend-typedefs-in-graphql) for inheriting/extending types or inputs as a way to reduce duplication. 
- Others have seen benefit in adding inheritance to the graphql schema. [graphql-s2s](https://github.com/nicolasdao/graphql-s2s) adds this ability to the schema. It could also be implemented with a directive which expands the common code into the inheriting types when the schema is compiled, as [here](https://github.com/jeanbmar/graphql-inherits).
- I have not found an existing implementation of inheritance for [Lighthouse](https://github.com/nuwave/lighthouse) or [graphql-php](https://github.com/webonyx/graphql-php) which it is based on.
- While these methods of inheritance do allow us to avoid duplication of written code, they are still compiled to a graphql-compliant schema which will hide the inheritance relationship from clients.

## Guesses
- The GraphQL maintainers would suggest managing duplication with [composition over inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance#Benefits).
- It would not be that hard to implement our own `@inherits` directive based on [this implementation](https://github.com/jeanbmar/graphql-inherits) for Apollo. We would start with one of the Lightouse [Type directives](https://lighthouse-php.com/5/custom-directives/type-directives.html#type-directives).

**Comment by petertgiles** [comment]
This is super interesting!  

I'm uncomfortable with the option of having to precompile our schema.  I'd like to see some concrete benefits of this before we decided to take on the added complexity and abstraction this would bring.

Is it possible we could take further advantage of [interfaces](https://graphql.org/learn/schema/#interfaces) to simplify our schema?  We've only used them once - for experiences.  And what about [union types](https://graphql.org/learn/schema/#union-types)?

**Comment by tristan-orourke** [comment]
We already have to compile our schema, actually. You'll find some differences between schema.graphql and lighthouse-schema.graphql. Off the top of my head, the `@paginate` directive actually generates a new type in the compiled schema, eg `UserPaginator`.

**Interfaces** could be a partial solution, if we prefer an inheritance-type solution without using a directive. Interfaces would:
  - reduce the risk of types drifting apart when they shouldn't (since same fields are enforced by the interface)
But interfaces would not:
  - fully remove the risk of differences between inheriting types (since the interface doesn't enforce matching directives, I believe)
  - reduce the number of lines of code in the schema (actually it increases 😆, since the interface attributes need to be repeated in each implementation)

**Union types** have a pretty niche use case. They allow you to specify that a field could be one of many different types. It does _not_ create a type which combines the fields of other types. In TypeScript terms, it allows `A | B`, but not `A & B`. We should consider leveraging union types for our Experiences, if we're not already.
