### ISSUE TITLE
Review Git Repo recommendations from Cybersecuity

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2367]
Review any adjustments necessary to comply with recommendations in [GitHub Security Assessment Report](https://docs.google.com/document/d/1fGLNKK64f6lgL1d3UIuCqccAaVTsf5UO/edit?usp=sharing&ouid=116875498920768945538&rtpof=true&sd=true).

Create tickets for individual recommendations.

**Comment by brindasasi** [comment]
[GitHub Security Assessment Action Items.docx](https://github.com/GCTC-NTGC/gc-digital-talent/files/9150965/GitHub.Security.Assessment.Action.Items.docx)

**Comment by brindasasi** [comment]
Below issues have been created for the action items above
#3396 
#3399 
#3428 
#3421
