### ISSUE TITLE
Refresh of admin edit pages fails

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2375]
If you navigate to one of the edit pages in the admin site and do a browser refresh an HTTP 500 page is returned.  This is probably related to the routing changes with the webpack PR.  It also happens on the pool candidates in a pool page.  Maybe it's the UUID in the url?

**Comment by vd1992** [comment]
I've had "Internal Server Error" pop up in some places too for /talent. 
Weirdly enough, sometimes the same link in two places, one returns the page and the other errors.

**Comment by tristan-orourke** [comment]
I'm thinking it happens when there's too many path segments in the url. /en/talent/profile refresh works, but en/talent/profile/government-information does not.

**Comment by tristan-orourke** [comment]
nvm, the talent side might just have incomplete routing.

**Comment by patcon** [comment]
> I've had "Internal Server Error" pop up in some places too for /talent.
> Weirdly enough, sometimes the same link in two places, one returns the page and the other errors.

@vd1992 If I'm understanding you correctly, it's perhaps that navigating "to" the page via clicks is working (?) but that visiting directly fails? If so, that's because the clicks are rewriting the browser via history API (i think?), but the direct visits (or refreshes) are trying to get the page "from scratch" and so apache is trying to serve it (and failing to find the root index.html to serve)

**Comment by petertgiles** [comment]
I did a bit of troubleshooting on this.  I'm getting recursion errors from Apache.  Something going on with routing:
```
[Tue Apr 05 20:42:58.593918 2022] [core:error] [pid 20] [client 172.18.0.1:41950] AH00125: Request exceeded the limit of 10 subrequest nesting levels due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
```

**Comment by vd1992** [comment]
http://localhost:8000/en/talent/profile

Go to Work Preferences section, click on the "Edit" link and then "Click Here" link in the section. One correctly returns the landing page and the other server errors for me.
Depending on your local environment, you might need to check a different section for the "missing fields, click here" text to pop up
