### ISSUE TITLE
Rename experience_skills table

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2403]
The pivot table `experience_skills` should have both model names singular to comply with current convention.  Postgres has table rename functionality so this should be pretty simple.

**Comment by mnigh** [comment]
> The pivot table `experience_skills` should have both model names singular to comply with current convention. Postgres has table rename functionality so this should be pretty simple.

The foreign key aspect of it might make it a bit harder: https://laravel.com/docs/8.x/migrations#renaming-tables-with-foreign-keys
