### ISSUE TITLE
Bounding box checkbox usability issue

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#2406]
https://61e099a1bb1465003a73d3ce-bjfbrmdctf.chromatic.com/?path=/story/form-checkbox--checkbox-with-bounding-box

When clicking the label, "Have a Diploma", checkbox should toggle

**Comment by petertgiles** [comment]
This works for me in Firefox on Linux.  In what environments does it not work?![Peek 2022-04-05 09-39.gif](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/539f4402-9236-4c35-88f9-2abd5e44fa3d)

**Comment by petertgiles** [comment]
You're right - good catch!
