### ISSUE TITLE
🔤 Page-specific descriptions

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2408]
## 🕵️ Details
`SEO` component descriptions should use the page subtitle, if it exists.

## ✅ Acceptance Criteria

- [ ] subtitle value from components used for descriptions in `SEO` component

**Comment by gggrant** [comment]
Possible solution: react-helmet.

**Comment by mnigh** [comment]
Short term proposal to replace placeholder copy, without involving something dynamic like [react-helmet](https://github.com/nfl/react-helmet), would be to replace three instances with static descriptions (though they would need to be translated somehow):

- https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/admin/src/views/dashboard.html#L7
- https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/talentsearch/src/views/page_container.html#L7
- https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/indigenousapprenticeship/src/views/page_container.html

**Comment by mnigh** [comment]
Related to #3086.

**Comment by mnigh** [comment]
@tristan-orourke doing this is technically possible with react-helmet now in the codebase but would require someone (preferably a copywriter) to create copy for each page. is this something that is planned?

**Comment by tristan-orourke** [comment]
This seems like something we'd still want. Right, @gobyrne @substrae ?

**Comment by substrae** [comment]
@tristan-orourke 

For now, can we pull page subtitles for these?

**Comment by tristan-orourke** [comment]
@substrae the subtitle is this?
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/3faf8d9e-930f-4b51-83be-8d987473da15)

**Comment by gobyrne** [comment]
Subtitles sounds like a practical approach to this. Do we have these in our "sitemap" document? Should we?

**Comment by gobyrne** [comment]
Removing blocked tag. Sub-titles are the way forward. Let us know if you need anything else from design.

**Comment by mnigh** [comment]
> Currently no way to set page specific subtitles

We **can** set the `description` prop of the `SEO` component, it just won't be shared anywhere since we are an SPA. Let's do it!
