### ISSUE TITLE
Improve fakeUser generator with more fields

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#2412]
fakeUser currently intentionally does not generate experiences, poolCandidates, or pools 
it will probably be useful for fakeUser to start generating more things once experiences/candidates/pools pop up in more components for testing purposes

https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/common/src/fakeData/fakeUsers.ts#L122

**Comment by gggrant** [comment]
Potential solution: generate different type of user with experiences.
