### ISSUE TITLE
Add detailed Operational Requirement text to WorkPreferencesForm

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2417]
# Description
Now that Operational Requirements have been refactored to an emun (https://github.com/gctc-ntgc/gc-digital-talent/issues/2212), it is simple to add more detailed checklist labels to match the wireframe.

[Wireframe](https://www.figma.com/proto/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?node-id=2485%3A5000&starting-point-node-id=1%3A2)

**Comment by gggrant** [comment]
Resolved by #2214.
