### ISSUE TITLE
URL Alignment With Sitemap

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2421]
Now that we have a sitemap from our designers we should to start to align our actual URLs with it.  

Question: This is a pretty disruptive operation - is the design settled enough for us to start on it?

There are probably many changes but the ones I'm noticing are:
- talent search and request should be under /browse
- profiles should be under /user
- /tc-report should be /talent-cloud

Question: Should profiles/user be under its own site now?

~~https://www.figma.com/file/n3PLf2KgobMp0kkH7HYx3i/Digital-Talent-and-Indigenous-Apprenticeship-Program---Sitemap?node-id=0%3A1~~ http://go.talent.c4nada.ca/sitemap

EDIT: added /sitemap shortlink --patcon

**Comment by gggrant** [comment]
Fix the talentsearch URLs, revisit issue at backlog refinement.

**Comment by patcon** [comment]
Last week, I transposed the sitemap into a flat spreadsheet format to help me reason around it a bit more easily:
https://docs.google.com/spreadsheets/d/11OP6khrn4mSMcy0cQ4cA4SS6AuAU3_HIxv4hii5Zj-4/edit#gid=0

Sharing in case anyone else finds that format a bit easier to think with

**Comment by patcon** [comment]
- [ ] add application urls that are missing
