### ISSUE TITLE
Instances of Button component wrapped with Link

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#2423]
## Issue

There are some instances where we are wrapping the `<Button>` component with `<Link>`. I presume this is to get the styling of a button and the functionality of a link. Unfortunately this results in the following markup being generated:

```jsx
<a>
  <button>
     Link
  </button>
</a>
```

This is [not considered valid HTML](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element) and can cause [issues with accessibility](https://accessibilityinsights.io/info-examples/web/nested-interactive/) and cause assistive technology to act in unexpected ways.

## Example

Currently the only example I have come across is the [CancelButton.tsx](https://github.com/GCTC-NTGC/gc-digital-talent/blob/0514af0b14268a51c1a80ba87a44fdd2dcd25c75/frontend/talentsearch/src/js/components/applicantProfile/CancelButton.tsx#L11-L33) component. 

### Easy Fix

An easy fix would be to add a "link" option to the type prop which would render a Link rather than a button and also provide an optional href prop that is used only when the type is set to link.

### Comprehensive

I'm not sure how necessary this would be, but we could instead us the "as" prop pattern to give the developer control over the rendered component while keeping the button styling. Though, this may add unnecessary complexity in annotating prop types.

#### Example

```jsx
import React from 'react';

const Button = ({ as = "button" }) => {
 const Component = as;
 return <Component>{children}</Component>
}

Button.defaultProps = {
 as: 'h1',
};

export default Button;
```

**Comment by yonikid15** [comment]
Oh good catch. I was under the impression that you could do after looking at a stackoverflow suggestion. I like your suggestions as well. Another simple and declarative approach would be to just use a `<Link/> component. It would be almost identical to the `<Button />` component, but would also require an href prop. Actually, we already have a Link component it would just need to be refactored to have all the different style versions (primary, secondary, etc.) like the Button.

**Comment by esizer** [comment]
>  Another simple and declarative approach would be to just use a `<Link/>` component. It would be almost identical to the `<Button />` component, but would also require an href prop. Actually, we already have a Link component it would just need to be refactored to have all the different style versions (primary, secondary, etc.) like the Button.

I like this idea 👍

**Comment by gggrant** [comment]
Also an issue on the /admin nav.
