### ISSUE TITLE
Bouncy Forms

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#2445]
I am not sure if this is all that important, it is a bit picky. It's just that it looks kind of unpleasant for this to happen, to me

![This is an image](http://g.recordit.co/545ERm22Ta.gif)

**Comment by mnigh** [comment]
@vd1992 are the forms still bouncing? 😄

**Comment by vd1992** [comment]
hopefully not

**Comment by mnigh** [comment]
> hopefully not

Based on your screen recording, it looks like its a react-select input on the `/admin/settings/skills/:skill-id` page. That input still exists and it still bounces from what I observed. It appears that this is an [issue](https://github.com/JedWatson/react-select/issues/4615) with the library itself. There are some solutions available, but not are all that great from what I could observe.

@esizer any thoughts on this one or is this a `wontfix`?

**Comment by esizer** [comment]
> @esizer any thoughts on this one or is this a `wontfix`?

lol yeah, move the input up a bit 😆
