### ISSUE TITLE
Admin - be less strict with required fields

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2455]
# Description
Almost all fields are set to required on the admin dashboard. Some fields should NOT be required.

In PoolCandidates form, none of the multiselects should be required. The User Telephone should not be required.

In User form, telephone should not be required.

**Comment by patcon** [comment]
ah thanks for making the label @tristan-orourke 🙌  (gonna just tweak the nave for brevity and easier ability to filter, ie. without spaces)
