### ISSUE TITLE
Database Disaster Recovery Plan

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2460]
Do we have a database backup?  When a buggy database migration trashes everything do we have a disaster recovery plan?

**Comment by tristan-orourke** [comment]
We don't. We need to work with IMTD to set up regular database backups, and see if we can automatically create backups before deploying.

**Comment by tristan-orourke** [comment]
Lets say this starts with a conversation with IMTD.

**Comment by tristan-orourke** [comment]
Make a Jira ticket request a DR (Disaster Recover) test to test out the current backup. They'll probably spin up a new service from a backup and we can try pointing to it to test things out. After confirming it works, they'll spin it down.

For more options, start by talking to Kevan Adlard about what his team does. They operate in IMTD making use of the full devops tools.

**Comment by tristan-orourke** [comment]
Split into #3345 and #3347
