### ISSUE TITLE
Conditions of Work for MVP

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#2477]
The MVP requires DCMO to input candidate information for the people in their pools. For them to be able to do this, we have to match the exact data that they currently collect.

The conditions of employment list that we are currently using for MVP is instead the ideal list that they are hoping to move to in the future, but not what they have right now. So we have to revert to the list they are using now. When we release profiles this will be revamped.

The conditions of employment show up on the search page and a couple other places:
![image.png](https://images.zenhubusercontent.com/5dc084854553760001149b53/59b81bf8-7e57-43a3-a10a-8607d6bad33d)

English options (for now) should be:
- Shift work
- Work weekends
- Work scheduled overtime
- Work overtime on a short notice

French options should be:
- Travailler des quarts de travail
- Travailler les fins de semaine
- Travailler des heures supplémentaires prévues
- Travailler des heures supplémentaires à court préavis

**Comment by tristan-orourke** [comment]
@gobyrne Are those 4 options *all* the options? Should we remove/hide Drivers Licence, 24/7, Transport and Travel?
