### ISSUE TITLE
Linting - @typescript-eslint/no-non-null-assertion

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2488]
Fix all instances of the linting error with rule [@typescript-eslint/no-non-null-assertion](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-non-null-assertion.md).  If necessary, add a rule disable comment for instances where appropriate and add a justification comment.  

Tips:
- Run `npm run lint --workspaces` from the frontend folder to manually run linting on all subprojects
- The [eslint-formatter-summary](https://github.com/mhipszki/eslint-formatter-summary) package can be handy for generating a linting summary by rule

**Comment by vd1992** [comment]
I was unable to find any instances of this

**Comment by petertgiles** [comment]
Agreed.
