### ISSUE TITLE
Linting - import/order

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2492]
Fix all instances of the linting error with rule [import/order](https://eslint.org/docs/rules/sort-imports).  If necessary, add a rule disable comment for instances where appropriate and add a justification comment.  

Tips:
- Run `npm run lint --workspaces` from the frontend folder to manually run linting on all subprojects
- The [eslint-formatter-summary](https://github.com/mhipszki/eslint-formatter-summary) package can be handy for generating a linting summary by rule

**Comment by vd1992** [comment]
I don't think I saw any instances of this anywhere? File saving automatically handles this ala Prettier, so if it was present it could've easily been accidentally swept up.

**Comment by petertgiles** [comment]
Agreed!  I guess someone corrected them in a different issue. :shrug:
