### ISSUE TITLE
Trim phone numbers

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2499]
I'm finding by experience that it's easy to trip up the phone number validation by accidentally leaving whitespace before or after.  Could we have the forms automatically trim the strings before sending them to the API?

**Comment by petertgiles** [comment]
Maybe it would be less invasive to not trim user input but show a helpful validation message if there is trailing or leading whitepsace.

**Comment by petertgiles** [comment]
Yeah, that's fair, too.  We gotta do something, though.  In our data entry on Friday I had two separate people complaining to me that it was broken because they typed in +123457890 exactly like the validator told them too but it rejected it.  And it was because there was an invisible space at the end. 😭

**Comment by vd1992** [comment]
I think we could add some sort of Regex thing here to delete all non-alphanumeric characters here? or delete whitespace only if we want to preserves things like hyphens 

![image](https://user-images.githubusercontent.com/40485260/164071263-bca7e81e-a26c-4271-8413-cdbada050202.png)

**Comment by tristan-orourke** [comment]
Covered by #2727
