### ISSUE TITLE
Search Page - Operational Requirements Filter

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2516]
🎟️ **Re-ticketed from** [Slack message](https://talent-cloud.slack.com/archives/CB424V61J/p1650373227569169) 🔒 

A blank search page produces a graphql query like this:![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/1f3da6c2-8d7d-4311-bf7f-0e6bbb8baf28)
The issue is that the empty operational requirement filter is being interpreted as "any **non-null** operational requirements" rather than "any operational requirements".  If it is removed, all the candidates are returned.![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/78877c01-e462-42df-aad9-24ea024b25c4)
The SQL query being generated:
![image](https://user-images.githubusercontent.com/8978655/164025696-a28f5364-ee0f-4c12-97ec-9d71b073b3e5.png)
A simpler query for demonstration:
![image](https://user-images.githubusercontent.com/8978655/164026851-de72666f-814e-4292-87bd-60437314aa11.png)

Acceptance Critera:

- [ ] Automated test to detect bug
- [ ] Fix bug

**Comment by patcon** [comment]
From @petertgiles  in slack:

But interesting question... where is the fault? Is (a) the backend correctly interpreting the query and the frontend should not be including the search term?  Or (b) should the backend be interpreting that search term as "any opreq"?
> I'm leaning towards the former.
> But a strong case could be made for the latter.

Agree wth you, that the former (a) feels correct. if it wasn't, then how would one cover the "query space" of "search for items with no operationalRequirements". No matter how rare or odd a request it might be, it should be possible. (and it might make more sense for another param) Not including the key makes sense to tell it "any", whereas empty array is more clearly "none"

**Comment by patcon** [comment]
I wonder if "null" or missing might be better? That's more clear from looking at the query (whereas "absence of whole key" doesn't really describe very well what's coming back, or at least doesn't say anything about the possibility of the filter we're leaving "unused")

**Comment by tristan-orourke** [comment]
In this case, my gut feeling is that an empty array, a null value, and a missing field should all result in the same query - no filtering at all based on the field.

**Comment by petertgiles** [comment]
Agreed.  It doesn't make searching sense to negate operational requirements.  If someone needs to hire someone who definitely cannot work overtime I guess we can make a requirement for that. :laughing:

**Comment by patcon** [comment]
> Not including terms that you don't care about is a bit of a GraphQL convention, as far as I understand.

Ah, maybe "undocumented" graphql metadata describes all this in a way that undocumented REST didn't. Or it might be a misplaced desire I'm dragging from my probing undocumented APIs of gov services :)

In light of this, I will retire the sensibility that the API call itself should document anything, as I think it's from the old-world -- if a public explorer (or a dev's local graphql explorer) will make it legible, it's not important :)

**Comment by tristan-orourke** [comment]
If you want to probe our API it's fully self-documented at https://talent.canada.ca/graphql-playground! 😁

**Comment by patcon** [comment]
Yay! Glad the explorer is public! (I'd also understand if we chose to strip it out, but it being there feels like a nice signal to external developers/explorers that they're not off the golden path of what's welcome :) feels symbolic )
