### ISSUE TITLE
Add security checks to CI, to detect secrets within codebase

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#2523]
This came up from a comment on HackerNews related to the GitHub/Heroku security leaks.

From [HackerNews comment](https://news.ycombinator.com/item?id=31052991) about [Heroku Security Notification](https://status.heroku.com/incidents/2413) (related to recent GitHub sec issues, I believe):

> I'm not a security expert, but if you're reading this and wondering what to do, a good start could be to just assume your repo was accessed, and so to run a tool like gitleaks against your repo. If it detects anything sensitive, I'd see about revoking/deleting those secrets right away.
>
> In general, it's good practice not to check anything sensitive into source code for precisely this reason (if your code is compromised you don't want your secrets to be as well). So it'd also be good practice to add something like gitleaks into your CI/CD pipeline for the future.

---

Suggestion is to add [`gitleaks`](https://github.com/zricethezav/gitleaks) to our CI (and local development toolchain) to help ensure that we're not committing secrets (nor have we ever committed secrets) into the repo. A little bit of sanity check.

As I understand, gitleaks does a few things:
- it searches code being committed
- it can search/remove past instances of secrets being committed, and
- it can run in a local pre-commit hook (on developer system) to ensure secrets are never committed again

cc: @JoshBeveridge (from [related message in Slack](https://app.slack.com/client/T5ZFRSQ3V/CB424V61J) 🔒  re: https://github.blog/2022-04-15-security-alert-stolen-oauth-user-tokens/ )

**Comment by gobyrne** [comment]
@brindasasi confirms Github has this by default.
