### ISSUE TITLE
Stories not sorting in export order

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#2529]
Stories by default are supposed to sort in the order they were exported in the `*.stories.js` file. There is an option to sort alphabetically, but it should not be enabled by default: (the default order is `configure` vs `alphabetical`)
https://storybook.js.org/docs/react/writing-stories/naming-components-and-hierarchy#sorting-stories

@vd1992 and I found a work-around: using letter prefixes, like `ADefaultArgs` and `BStatusYes`. (Number prefixes don't seem to work, as they must start with a letter)

https://github.com/GCTC-NTGC/gc-digital-talent/blob/9ca0c305332a82e762273021f862703217c0ec0f/frontend/talentsearch/src/js/components/GovernmentInfoForm/GovernmentInfoForm.stories.tsx#L28-L52

Anyhow, this is not urgent, but quite annoying. The point of storybook is that the stories files should... tell a story. And the way it's mangling the order is actually making it more difficult to demonstrate the value of using storybook as intended: to show all possible states that a component might exist in.

It basically disincentivizes us from arriving at storybook best-practices: of having (a) multiple stories for a component that (b) linearly-ish walk through all significant component states, while (c) re-using state of prior/other stories with minimal code duplication, and (d) having the `*.stories.js` code's "narrative order" mirror the "narrative order" in the storybook UI. 

The work-around is workable, but has some **downsides** (mostly dev process):
- re-use of prior story data is disincentivized, because it's painful to manage the prefixes (see above for example of storybook best-practices of state re-use)
- changing the order of stories or adding a new one mid-stream is painful, because prefixes must be rejigged and all references to their re-used data also replaced (and therefore it's more tempting to add it to the end, which breaks the linearity of the "story" that is supposed to be moving through)
- links start breaking and giving confusing errors when prefixes change
  - e.g., link to ADefaultArgs works right now: https://61e099a1bb1465003a73d3ce-axrbhnvjhx.chromatic.com/?path=/story/government-info-form--a-default-args
  - but if it were renamed to BDefaultArgs, the link to the story in any documentation would break, kinda like this: https://61e099a1bb1465003a73d3ce-axrbhnvjhx.chromatic.com/?path=/story/government-info-form--b-default-args

**Comment by mnigh** [comment]
Can't reproduce this behaviour anymore.

## Without prefixed letters in `AdminSideMenu.stories.tsx`
![Screen Shot 2023-08-08 at 13 55 58](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/998e6de8-7bad-4985-ad1d-6d9e6decdd86)

## With prefixed letters in `GovernmentInfoForm.stories.tsx`
![Screen Shot 2023-08-08 at 13 57 54](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/13f61db8-a489-467e-83cb-19936989944a)

## Without prefixed letters in `GovernmentInfoForm.stories.tsx`
![Screen Shot 2023-08-08 at 14 00 28](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/74cb72af-2f51-4bda-8fa7-42e18f606ca5)
