### ISSUE TITLE
Home route not working

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#253]
Clicking on the Home button doesn't navigate to HomePage.tsx component, nor does it highlight it as the current page.

![Screen Shot 2021-07-21 at 12 54 41](https://user-images.githubusercontent.com/3046459/126528561-6cd6fa30-d69a-44ac-9e8c-09e0c00266bd.png)

**Comment by gobyrne** [comment]
Just take this out for now, we will re-evaluate dashboard once tool has been used.

Default page should be "All Requests" once it has been developped.

**Comment by mnigh** [comment]
Resolved as a part of #354.
