### ISSUE TITLE
IAP Homepage

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#2532]
## Tasks

- [ ] Blockout homepage/desktop
- [ ] Develop mobile responsive media queries
- [ ] Polish

Working file: https://www.figma.com/file/mbNQCvx6Tnn5HjLNDqTNSt/IAP-3.5.1?node-id=209%3A631

**Comment by gggrant** [comment]
Wireframe: https://www.figma.com/file/nnGvHOqhHOLulsmV3ya4BY/IAP-3.5?node-id=0%3A1
