### ISSUE TITLE
Check that integrity hashes match files on system

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#2557]
Re-ticketed from https://github.com/GCTC-NTGC/gc-digital-talent/pull/2414#issuecomment-1096612244

Currently, we're checking that (1) integrity hashes exist in our lockfile and (2) that they're validly formed. We're not checking that they **(3) match the files in our node_modules**, nor if (4) those hashes match those from NPM (our local cache could be corrupted). **This focusses on (3).**

This should use external packages when possible, as that way the hashes are generated from filesystems and validated has been done in other libraries.

> - validate that decompress contents of cached tarball match contents of node_modules
>    - the cached tarball and cached checksum could match, but maybe our uncompressed files running in node_modules don't match that. we don't confirm that yet

**Comment by patcon** [comment]
While slightly separate, this can also include:

> - confirm integrity hashes match cached tarball. see: https://gist.github.com/patcon/88e7e8332e49abd06b79feb1d0a134bd

**Comment by petertgiles** [comment]
The integrity check workflow was removed in https://github.com/GCTC-NTGC/gc-digital-talent/pull/3663.  The code remains in the repo if we decide we want to move forward with this again.

**Comment by esizer** [comment]
Is there still appetite for this?

**Comment by petertgiles** [comment]
Yarn was going to do this automatically, right? #5338

**Comment by esizer** [comment]
> Yarn was going to do this automatically, right? #5338

Yeah, I'm just not sure when we will get around to that because of the spider web of other issues 😅 I tried getting the auth exchange working after some patch releases but it is still double refreshing 😢 And yarn still seems to want to force that dep to bump 🤷‍♀️

**Comment by mnigh** [comment]
> Yarn was going to do this automatically, right? #5338

@esizer What about pnpm?

**Comment by esizer** [comment]
> @esizer What about pnpm?

Maybe? https://pnpm.io/npmrc#verify-store-integrity

**Comment by tristan-orourke** [comment]
No plans to do this beyond #5338
