### ISSUE TITLE
Investigate switching to frontend auth with PKCE

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2572]
Security consultants have expressed concern that our current auth flow passes authentication tokens in the URI.  This makes them vulnerable since they more visible, for example, in the browser history.  We mitigate this by using very short-lived tokens.  This way the window for attack is fairly limited.  It seems that the accepted best solution for SPAs is to use the authorization grant flow with the PKCE extension.

**Open questions:** Is implementing this form of auth a large improvement over our current "backend helper" approach?  Is it worth the large refactor?

The team has expressed a desire to leverage a library for this functionality.  Patrick likes Auth0, Tristan found https://github.com/GCTC-NTGC/gc-digital-talent/issues/2376#issuecomment-1102769557 and Peter found  https://github.com/GCTC-NTGC/gc-digital-talent/issues/2376#issuecomment-1102780944.

**Comment by patcon** [comment]
PKCE is already supported by the mock auth server that I've gotten working:
https://github.com/navikt/mock-oauth2-server/issues/36

**Comment by petertgiles** [comment]
While researching Azure B2C I found that Microsoft also recommends authorization code flow with PKCE for SPAs.
https://docs.microsoft.com/en-ca/azure/active-directory-b2c/tutorial-register-spa
They mention (but don't actually recommend) MSAL.js.

**Comment by patcon** [comment]
Ok, somehow I didn't get this into an issue when I was doing research last week, but here are the libraries that might be helpful:

| package | star | active? | notes | pkce 
|---|---:|:---:|---|---|
| [bjerkio/oidc-react][] | 189 | :question: | built on `IdentityModel/oidc-client-js` | [maybe](https://github.com/bjerkio/oidc-react/issues/753)
| -- [IdentityModel/oidc-client-js] | 2,300 | :x: | deprecated. | [yes](https://github.com/IdentityModel/oidc-client-js/issues/1362)
| [authts/oidc-client-ts][] | 327 | :white_check_mark: | successor to `IdentityModel/oidc-client-js` | [yes](https://github.com/authts/oidc-client-ts/issues/548)
| [Swizec/useAuth][] | 2,600 | :white_check_mark: | has auth0 and netlify providers, but needs custom (good docs) | [no](https://github.com/Swizec/useAuth/issues/4)
| [openid/AppAuth-JS][] | 841 | :white_check_mark: | official lib of openid org | [yes](https://github.com/openid/AppAuth-JS#:~:text=The%20library%20also%20supports%20the%20PKCE%20extension%20to%20OAuth)
| -- [AxaGuilDEv/react-oidc][] | 316 | :white_check_mark: | actively maintained. built on `openid/AppAuth-JS`. implements service worker for security :tada: | [yes](https://github.com/AxaGuilDEv/react-oidc/issues/346)

`AxaGuilDEv/react-oidc` seems the best choice, as it has PKCE and also service workers. My understanding is that PKCE is only really secure with service workers, which ensure that the refresh token is never accessible to the main browser javascript thread.

   [bjerkio/oidc-react]: https://github.com/bjerkio/oidc-react
   [IdentityModel/oidc-client-js]: https://github.com/IdentityModel/oidc-client-js
   [Swizec/useAuth]: https://github.com/Swizec/useAuth
   [authts/oidc-client-ts]: https://github.com/authts/oidc-client-ts
   [openid/AppAuth-JS]: https://github.com/openid/AppAuth-JS
   [AxaGuilDEv/react-oidc]: https://github.com/AxaGuilDEv/react-oidc/tree/master/packages/react

**Comment by patcon** [comment]
`useAuth` is also interesting, and seems to have great docs and support, but we'd need to write our own provider:
https://useauth.dev/docs/auth-providers (This maybe isn't a bad thing, and maybe we could steal service worker code from the other library?)

**Comment by pamapa** [comment]
@patcon Do you know [react-oidc-context](https://github.com/authts/react-oidc-context)? Might be also a good candidate for your list above...

**Comment by cobraz** [comment]
👋 

[bjerkio/oidc-react](https://github.com/bjerkio/oidc-react) is maintained, albeit rather slow. We're working on bumping to v2, which should give you enough support going forward. It does support PKCE :)

**Comment by patcon** [comment]
Oh hey, thanks so much @pamapa and @cobraz!

I've updated the above table with your helpful feedback 🎉 

(Do either of you feel this resource is useful enough to keep anywhere? Happy to open a PR if you think it's worth maintaining somewhere 😃 )

**Comment by cobraz** [comment]
> (Do either of you feel this resource is useful enough to keep anywhere? Happy to open a PR if you think it's worth maintaining somewhere 😃 )

I would love to have a list in the readme of our package! 🎉 it would be awesome if you to open a pull request!

We can maintain it, and probably add more details on the differences! So it makes it easier for people!

Btw, have you evaluated using cookie-based authentication? For example with ORY Kratos?

**Comment by tristan-orourke** [comment]
I'm closing this as a successful spike. I support @patcon's recommendation to go with the library which uses service workers, as superior protection against XSRF attacks.

Now we will go ahead with implementing this in #4916.
