### ISSUE TITLE
Bug: Government Info Classification not removed on Type change

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#2577]
On the government info form, when changed from either Casual, Term or Indeterminate to Student, the Group and Classification remain set.

Since the Group and Classification fields are not available to students, these should be set to be undefined when the Type gets reverted back to student.

**Comment by tristan-orourke** [comment]
Add some logic to the formValuesToData function. There should already be some logic like this in there.
