### ISSUE TITLE
Translate IAP landing page

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2578]

**Comment by petertgiles** [comment]
[Eric mentioned ](https://github.com/GCTC-NTGC/gc-digital-talent/pull/2539#issuecomment-1116346370)the current content is not final.  It should probably be finalized before we start this.

**Comment by petertgiles** [comment]
Note from Gray: Gotcha. I think we'll use the usual process for translation, but we'll get the translation reviewed by the IAP team before it goes in.
