### ISSUE TITLE
Pool Managers should have access to only a subset of pools

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2580]
# Description

This feature is still being figured out... but roughly...

-There should be a new Role, POOL_MANAGER, which allows a user to create/edit pools and access pool candidates. 
- POOL_MANAGERS can be assigned to TALENT ORGs. 
- Every Pool is assigned to one (or more?) TALENT ORG. 
- POOL MANAGERS can work with Pools in their ORG.

**Comment by petertgiles** [comment]
from https://github.com/GCTC-NTGC/gc-digital-talent/issues/2660#issuecomment-1117535380:
Managers should only see notes for pools they have access to.

**Comment by gobyrne** [comment]
@Jerryescandon , I know you did a lot of design work on this. If there's another issue, please close this one. If not, please add some details here.

**Comment by tristan-orourke** [comment]
Closing in favour of other tickets, now that we have a better handle on #4360.
