### ISSUE TITLE
Automerge Dependabot Patch Updates

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2615]
Now that we have some more robust automated testing in place lets see if we can get dependabot to start automatically merging the patch updates since they are fairly low risk.

**Comment by esizer** [comment]
I looked into this briefly and found a marketplace action, [Dependabot Auto Merge](https://github.com/marketplace/actions/dependabot-auto-merge). I think this may help us but it requires a token with push access to operate.

**Comment by tristan-orourke** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/2615?planning-poker) with ZenHub @patcon

**Comment by mnigh** [comment]
Someone from with an **admin** role would need to work on this issue since the [GitHub action](https://github.com/GCTC-NTGC/gc-digital-talent/issues/2615#issuecomment-1126336266) suggested by @esizer requires adding a secret.

**Comment by vd1992** [comment]
To be completed in #7637
