### ISSUE TITLE
Merge-On-Approval Dependabot PRs

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2616]
We almost always merge dependabot PRs after one approval.  Can we turn on merge-on-approval for dependabot so that a PR will automatically merge once it is approved and the actions complete?

AC
- [ ] Dependabot automatically merges its PRs once all the actions pass and one dev has approved

**Comment by tristan-orourke** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/2616?planning-poker) with ZenHub @mnigh

**Comment by mnigh** [comment]
For reference when working on this issue: [Enable auto-merge on a pull request](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request).

**Comment by brindasasi** [comment]
we would wait for github merge queue.
