### ISSUE TITLE
npm version in github workflows

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#2628]
Two questions:

1. Is there any way to use a global environment variable for these values so that there is a single source of truth?
2. Is there any way to pull this value from somewhere we can actually get the latest version of npm instead of a statically coded?

Files:
https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/.github/workflows/bundlewatch.yml#L27
https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/.github/workflows/jest.yml#L19
https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/.github/workflows/lint.yml#L19
https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/.github/workflows/package-integrity-check.yml#L19
https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/.github/workflows/storybook.yml#L21

**Comment by tristan-orourke** [comment]
Related to part 2 of #2629

**Comment by mnigh** [comment]
New issue created:

- #2759
