### ISSUE TITLE
Use backend filtering on User table search bar

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2640]
Search bar currently runs a client-side filter on any text fields. Convert it add a filter to the query, now that the table is using backend pagination. The text should search the name, email and phone number fields.

For this issue, don't worry about specifying a single field to search on.

**Comment by tristan-orourke** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/2640?planning-poker) with ZenHub @patcon

**Comment by tristan-orourke** [comment]
Please try adding some acceptance criteria as well

**Comment by patcon** [comment]
@petertgiles and eric working together to refactor. back to draft.

**Comment by esizer** [comment]
@petertgiles Looks like this was resolved with #3220 are we safe to close?
