### ISSUE TITLE
Fancy filter in modal

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2641]
## Description

Build the modal component to submit a User filter object to a callback when it is closed. Don't worry about using the filter in a query yet.

## Screenshot: Prototype
[![image][image]][figma]
<sup>[Click screenshot to visit Figma prototype.][figma]</sup>

   [image]: https://user-images.githubusercontent.com/305339/177175957-9f0908bd-6f8f-432f-a987-2448e255b05f.png
   [figma]: https://www.figma.com/proto/XS4Ag6GWcgdq2dBlLzBkay/Admin-v3?node-id=465%3A8698&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=410%3A1984&show-proto-sidebar=1&hide-ui=1

### Notes
- _Multiselect search field_ is a new component
- _Checkbox field_ is a new component (if styled like a boolean switch)

### Acceptance Criteria
- [ ] We add a prop to our multiselect component to allow for the search  
- [x] The header of the modal includes a title and subtitle
- [x] The body of the modal includes a Pools multiselect search field
- [x] The body of the modal includes a Language select field
- [x] The body of the modal includes a Classifications multiselect field
- [x] The body of the modal includes a Conditions of employment multiselect field
- [x] The body of the modal includes a Work location multiselect field
- [x] The body of the modal includes an Education multiselect field
  - we realized the data model is still in flux, so this is behind logic to disable. story shows both.
- [x] The body of the modal includes a Duration preference select field
- [x] The body of the modal includes an Availability select field
- [x] The body of the modal includes a Complete profile checkbox field
- [x] The body of the modal includes a Skill filter multiselect search field
- [x] The body of the modal includes a Government employee checkbox field
- [x] All input values are reset to original form state once the user clicks "Clear filters"
  - "original form state" currently presumed "empty", but could easily be "current" (though maybe "Reset filters" makes more sense for that)
- [x] The modal closes once the user clicks "Show Results"
- [x] The form options are applied to search filters of related form
  - i wasn't sure how to final mutation and submission logic might work, so I assumed this was a separate integration task after this is merged. the onSubmit prop passed to the component is in turn passed an arg with all FormValues
- [ ] Jest tests to confirm the filter object looks right.

**Comment by tristan-orourke** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/2641?planning-poker) with ZenHub @mnigh

**Comment by tristan-orourke** [comment]
Please try adding some reasonable acceptance criteria as well

**Comment by patcon** [comment]
Custom type guard to help use work with multi and single variants of react-select:
https://www.typescriptlang.org/play?#code/PTAEBUE0AUFEGUCwAoFAXAngBwKangJYB2A5gDY4BqAhmQK44A8A8lmgQPZEB8oAvKFbsuoAD6gidMmQDc6bHgCyU9jXpMhnHv1AAnHNQAmXMhkFstAbQC6c1Mky5Q0XRywBnNQxYWuvAcpkqrTemn5i+MTkVCEavjx28k6KGGFEOgDeoABusQBcoO5oulERkgC2AEY4ujKgZNTVZAVFJaSgAL6JyABmdEQAxsLpBO4Agrq61BiM4NwAFNS6JAX9ANZEHADuRACUBUskoKN6BsZEphA2oBkooKdodLrpE1MYAHSjr9OLy7t2HRQKBAoAAwswACKwIHIAZcIqgHocDg6Sx3G65dQFACMABp6o0cM1QAAiHoEXRFEkdXHojKYhgFABM+IaTQKJPcODhREM1NpyGsMJ5CMqS0yDJwBQAzKzCcSSWgABYUvmA+witCgMUALx0kmkwvhWp52RqaEIpAozF0gXYaXAHC8eAE8zcw3cNrSBRcbk8sUYKTS3F2-F4t2Q9wIPVA8y+k2mgdS8QW7q0nt0aV2oYj93u+kez1AafhXvi73K1Cw8zdob4vA470l-3R6vRBae6RLRAzaQA-E3YmJxAbZCg27D4RwKO8yBwSPNTebLdEbXaCA6nbF5kiONmUCLpzhZ-PF1wzboLVFrbaVBv4o7nfMxbp95Oe0eTwul5eVzf15uT66m+QA

**Comment by patcon** [comment]
For later: This is a minimal reproduction of `react-hook-form` "reset" method _working_ with `react-select` MultiSelect, so there's something going on in my/our code that's preventing it:

https://codesandbox.io/s/react-hook-form-react-select-forked-87f87w?file=/src/index.js

**Comment by patcon** [comment]
@Jerryescandon @JoshBeveridge In the mockup (linked above), there's currently **Select** field for Education that includes only options for "Has Diploma" and "Combination".

We have something existing in codebase that corresponds to this, called **"Education Requirements"**. But also, it isn't used anywhere anymore. It also seems ill-fitting to a search of users? (though I may be misunderstanding)

https://github.com/GCTC-NTGC/gc-digital-talent/blob/9d7f60cb2285a8ce7b51c0a8bdd1c68a3753dc7e/frontend/common/src/constants/localizedConstants.tsx#L95-L102

Should this select field instead be a **MultiSelect** populated with opens for **"Education Type"**, as listed here:
https://github.com/GCTC-NTGC/gc-digital-talent/blob/9d7f60cb2285a8ce7b51c0a8bdd1c68a3753dc7e/frontend/common/src/constants/localizedConstants.tsx#L459-L492

**Comment by Jerryescandon** [comment]
> Should this select field instead be a **MultiSelect** populated with opens for **"Education Type"**, as listed here:

Let's use this list instead. I updated the prototype to reflect this.

**Comment by patcon** [comment]
Splitting SelectFieldV2 and MultiSelectFieldV2 components/tests/stories into own PR
