### ISSUE TITLE
Select subset of rows

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2643]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Screenshot: Prototype
[![a screenshot of ...][image]][image-link]
<sup>[Click screenshot to visit Figma.][image-link]</sup>

## Acceptance Criteria
- [ ] Multiple rows can be selected
- [ ] Selected rows are stored in some local state, which can be referenced by other functionality.

   [image]: https://user-images.githubusercontent.com/305339/166574896-aaf72687-608e-412b-87f7-07808ea5964e.png
   [image-link]: https://www.figma.com/proto/XS4Ag6GWcgdq2dBlLzBkay/Admin-v3?node-id=465%3A8698&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=410%3A1984&hide-ui=1
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by tristan-orourke** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/2643?planning-poker) with ZenHub @esizer

**Comment by esizer** [comment]
Estimate based on the following assumed functionality of being able to hold shift to select rows between first and last selection. If this is not expected, i think we can safely drop this to 2-3.
