### ISSUE TITLE
Deeplink Modals/Tabs

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#2650]
h/t @patcon

## Summary

We are essentially looking to have the ability for someone to share a link to a modal to avoid "hidden" content. This would allow users to copy a URL and share it to someone to a page where the modal is open by default.

### Note

There is a [discussion about changing routers](https://github.com/gctc-ntgc/gc-digital-talent/issues/2368) so it would be beneficial to wait until that spike is resolved before we start this but not necessary.

## Approach

This could be accomplished by using optional parameters in the router and if that parameter exists, default the modal state to open.

## Example 

```tsx

// Router.tsx
...
const router = new UniversalRouter({
  path: '/path/segment/:modal?',
  action: ({ params }) => <Page currentModal={params.modal} />
}
...

// Page.tsx
...
interface PageProps {
  currentModal?: string;
}

const Page: React.FC<PageProps> = ({ currentModal }) => {
  const [isOpen, setOpen] = React.useState<boolean>(currrentModal === "learn-more");
  return (
    <a role="button" href="/path/segment/learn-more">Open Modal</a>
    <Modal isOpen={isOpen} />
  );
}
...
```

---

## Notes from Discussion

> However, im not sure how we can make this link obvious? Maybe convert the buttons that control the modals to links with the button role so they can have href to be copied?

@esizer I like your thinking on this! As for the href, I was actually thinking a fully qualified path, like `/en/indigenous-it-apprentice/learn-more`. A path fragment could work, but would probably break any future hope of browser deep-linking, which already uses hashes.

But yeah, wondering if maybe this is something we should hold off on being too clever about until we're 100% locked into a router. I recall we're maybe considering a more accessible router solution than universal-router. I'm finding posts about giving routes to modals, but they all seem to be for react-router:
- https://www.codedaily.io/tutorials/Create-a-Modal-Route-with-React-Router 👈 better one
- https://blog.logrocket.com/building-a-modal-module-for-react-with-react-router/
- [https://www.bennadel.com/blog/3620-most-of-your-modal-windows-should-be-directly-accessible-by-route-in-angular-7-2-15.htm](https://www.bennadel.com/blog/3620-most-of-your-modal-windows-should-be-directly-accessible-by-route-in-angular-7-2-15.htm#:~:text=I%20have%20come%20to%20believe%20%2D%20quite%20strongly%20%2D%20that%20most%20of%20the%20modal%20windows%20within%20an%20application%20should%20be%20directly%20accessible%20by%20route) 👈  deep-link to a hot-take by angular dev who built inVision

But the more I look around, the more I think routes for modals is what we should strive for (or else we're kinda losing browser "features" that plain old html pages already have built into browser for free -- direct linking to content pages, and browser deep-linking to specific words)

_Originally posted by @patcon in https://github.com/GCTC-NTGC/gc-digital-talent/issues/2539#issuecomment-1116470610_

**Comment by petertgiles** [comment]
@esizer @patcon Could we phrase this spike in the form of a clear question (or two)?
How about "What is the best way to link to the content in a modal in our app?"

**Comment by esizer** [comment]
> @esizer @patcon Could we phrase this spike in the form of a clear question (or two)?
> How about "What is the best way to link to the content in a modal in our app?"

I would actually remove the spike. I'm not sure there needs to be any question answered since there is a clear example of how to complete this task in the [`react-router` examples](https://github.com/remix-run/react-router/tree/dev/examples/modal).

**Comment by esizer** [comment]
We have a lot of modals now and I'm not sure how much appetite existed for this in the first place. Safe to close?

**Comment by mnigh** [comment]
> We have a lot of modals now and I'm not sure how much appetite existed for this in the first place. Safe to close?

@tristan-orourke safe to close as unplanned?
