### ISSUE TITLE
Decide on device support

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#2651]
## Summary

When developing the IAP homepage, @vd1992 noticed that it did not look great at 320px, as well @patcon found some issues with 4K screens. This started a discussion on what devices we are targeting for the user facing projects.

We should develop some sort of min-max range for device resolutions we are looking to support and add it to our definition of done.

---

## Discussion on Device Support

> Ah, it that case, yeah I wouldn't sweat the polish quite yet. No point worrying with placeholder
> 
> Are the mobile views as desired? Like with the overlaps? Small Mobile on Storybook is a bit unreadable for example

I would say yes but tentatively. This might be a discussion on device support since the storybook mobile small size is 320px pixels and most phone resolutions (even the smaller ones) start at 360px wide.

I believe 320px is comparable to an iPhone 5 (2012). If we do want to support devices between 320-360px then I can go back and do another pass at this width.

_Originally posted by @esizer in https://github.com/GCTC-NTGC/gc-digital-talent/issues/2539#issuecomment-1116369409_

**Comment by mnigh** [comment]
> We should develop some sort of min-max range for device resolutions we are looking to support and add it to our definition of done.

@esizer Has this essentially been decided with the following?
https://github.com/GCTC-NTGC/gc-digital-talent/blob/8605ee3b8ee585c333bada7f98fa1afcfe11398b/frontend/indigenousapprenticeship/src/js/components/Home/Home.stories.tsx#L27-L30

**Comment by esizer** [comment]
> @esizer Has this essentially been decided with the following?

I wouldn't say so. I did have a good reason for picking these resolutions though. Chromatic allows for viewports between 320 and 1800.

What I did, was I looked at screen resolution market share numbers and selected sensible ones between those two values. 

## Min

iPhones currently have the lowest value resolutions at 375-1242 and since it is a popular device on the low end I chose the low value. They do contain a device at 320 (iPhone 5) but tbh, that is really small by todays standards and likely does not have very high market share.

## Max

This one was simple, the most common large display is 1920 but since chromatic only goes to 1800, I picked the next highest which was 1366 with 17.89% desktop market share as of last month.

**Comment by patcon** [comment]
Related: https://github.com/GCTC-NTGC/gc-digital-talent/issues/3576

**Comment by JoshBeveridge** [comment]
Might or might not be relevant, but Hydrogen's config allows us to specify typography settings at media query values now, so perhaps new settings might alleviate some of the biggest display issues.

**Comment by mnigh** [comment]
Related: https://github.com/GCTC-NTGC/gc-digital-talent/issues/5589

**Comment by mnigh** [comment]
@substrae what size of phone do should we be supporting? would you mind making a decision on this so we can proceed?

**Comment by substrae** [comment]
@mnigh 

Sorry, this ticket's been sitting in my _Later_ bin for a long time. Honestly, I think we should, at minimum, be supporting the iPhone SE 1st generation, which sits at `640px` wide. If we want to go smaller (based on the conversation above), we'll likely need to go through all of our components and pages to make sure they function and respond as expected. This will likely require a new typography setting in the Hydrogen config as well to ensure headings aren't exceeding their allotted space.

**Comment by mnigh** [comment]
## Decision

- Minimum: 320px width (iPhone SE 1st Generation)
- Maximum: 3840px width (4K TV)
