### ISSUE TITLE
Style updates on Requests table

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2655]
Ensure the table styling and placement of buttons matches the prototype.

[Prototype](https://www.figma.com/proto/XS4Ag6GWcgdq2dBlLzBkay/Admin-v3?node-id=396%3A787&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=410%3A1984)

![Screenshot](https://user-images.githubusercontent.com/4313717/168148359-1e0d114c-4d40-4065-bc5a-6f4e95fb2c05.png)

**Comment by gobyrne** [comment]
#3051 will address? @JoshBeveridge

**Comment by JoshBeveridge** [comment]
Same answer as https://github.com/GCTC-NTGC/gc-digital-talent/issues/2656 - tables have been updated to be consistent, but headings might still need to be changed over to the new components.
