### ISSUE TITLE
Update headings on all admin pages

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2656]
Go through all admin pages and match heading styles. The users page is currently correct, so use that as the template.

These are the top level pages that you should check. We can catch others as they come up.
- [ ] Users (already done)
- [ ] Pools
- [ ] Pool Candidates
- [ ] Requests
- [ ] Classifications
- [ ] CMO Assets
- [ ] Departments
- [ ] Skill families
- [ ] Skills

![Screenshot](https://user-images.githubusercontent.com/4313717/168147698-9edaec37-d3e5-4b23-8729-5d74c8140b7c.png)

**Comment by JoshBeveridge** [comment]
Yes this has changed in #3051 so that everything is consistent.
