### ISSUE TITLE
Re-style tab component

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2659]
<img width="684" alt="Screen Shot 2022-05-04 at 11 39 37 AM" src="https://user-images.githubusercontent.com/305339/166718455-5d4a6e14-2146-47a5-bdc3-7d0bf4527522.png">

**Comment by Jerryescandon** [comment]
The drop shadow doesnt show on the live prototype, but these images show it a little better.

![image](https://user-images.githubusercontent.com/16977254/168315485-69aa38d6-f5bb-4489-a4b7-66445be8614a.png)

![image](https://user-images.githubusercontent.com/16977254/168315555-387102c2-e60d-45b8-8dab-2c35370ff2d9.png)
