### ISSUE TITLE
General information tab

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2660]
https://www.figma.com/proto/XS4Ag6GWcgdq2dBlLzBkay/Admin-v3?node-id=429%3A2292&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=410%3A1984&hide-ui=1

<img width="1303" alt="Screen Shot 2022-05-04 at 11 40 00 AM" src="https://user-images.githubusercontent.com/305339/166718539-c0f5894c-72a0-422c-a90a-ea0a8143c865.png">

The Notes data is specific to a PoolCandidate, not a User. We should list a set of Note inputs, one for each Pool the user is in.

## Acceptance Criteria
- [ ] Each interaction (change status, remove from pool, add to pool, save notes) may need its own mutation
- [ ]

**Comment by JamesHuf** [comment]
@Jerryescandon Are the titles for all the sections in the table of contents correct? A few of the titles don't match the ones on the page and while I can understand a few of the changes referring to this section as "Pool information" seems weird. 
![image](https://user-images.githubusercontent.com/49166751/171041070-577600f3-c926-4522-82cb-5d10fdc93fa0.png)

**Comment by Jerryescandon** [comment]
Yeah they were just outdated. I've fixed them to match the sections. They should be 1 to 1.

**Comment by JamesHuf** [comment]
Thanks! That makes more sense.

**Comment by JamesHuf** [comment]
@Jerryescandon What should this text be for the "Open to opportunities" or "Inactive" statuses?

**Comment by JamesHuf** [comment]
And in the next section - Are there any pool candidate statuses (Expired?) which should be unable to be switched to or from?

**Comment by JamesHuf** [comment]
@Jerryescandon A couple more questions (hopefully the last):
1. The pool names in the Pool Status section are underlined - should they link to the details page for the pool?
2. The dialog for remove from pool has the confirm button on the left and cancel button on the right which feels backwards to me - Can you confirm this is the order they should be?

**Comment by Jerryescandon** [comment]
1. Let's not do this for now. (no underline and no linking)
2. That is correct. It's counterintuitive by design because it's a destructive action. So we are trying to add friction to this interaction.

**Comment by JamesHuf** [comment]
1. Sounds good.
2. I can get the theory but it sounds like only a matter of time until someone hits the delete button by accident and goes to close the dialog quick but clicks confirm instead. I'll add it anyway if it's desired though.

**Comment by Jerryescandon** [comment]
Just to be sure, let me dig into that again.

**Comment by tristan-orourke** [comment]
~~Remove~~Disable the "Remove from Pool" button
