### ISSUE TITLE
Candidate Request History tab

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2662]
https://www.figma.com/proto/XS4Ag6GWcgdq2dBlLzBkay/Admin-v3?node-id=429%3A2292&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=410%3A1984&hide-ui=1

<img width="1301" alt="Screen Shot 2022-05-04 at 11 47 57 AM" src="https://user-images.githubusercontent.com/305339/166720000-29539252-37d4-4103-b70a-9e11e930792e.png">

**Comment by gobyrne** [comment]
Closing. This functionality will be needed when we get to self-referrals, but it will also need to have more than just what is shown here. We will re-create once we get there with the designs.
