### ISSUE TITLE
Download Profile functionality

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2663]
button styling done in #2658 

https://www.figma.com/proto/XS4Ag6GWcgdq2dBlLzBkay/Admin-v3?node-id=429%3A2292&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=410%3A1984&hide-ui=1

<img width="1312" alt="Screen Shot 2022-05-04 at 11 48 22 AM" src="https://user-images.githubusercontent.com/305339/166720139-705f9b67-dab2-4b28-b02b-95f8712bd7f9.png">

**Comment by tristan-orourke** [comment]
What should the printed page look like?

**Comment by tristan-orourke** [comment]
Sounds like it should just be the Profile tab, minus the Language Notes, with the accordions expanded.

**Comment by petertgiles** [comment]
Would whoever picks this up mind if I ride-along for pairing?

**Comment by petertgiles** [comment]
No one picked this up, eh?  I guess I'll grab it and at least get it started with some scaffolding while Vany works on the components.

**Comment by Jerryescandon** [comment]
Hey Peter, hit me up to go over the markdown stuff, Im unsure how I could help but happy to give it a try.
