### ISSUE TITLE
Bug - request button missing on Talent Search page

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2668]

**Comment by esizer** [comment]
## Note

I believe it was the change made to move the candidate results into a function to avoided the eslint rule to nested ternary operations. The function that returns the [component is being passed but not called](https://github.com/GCTC-NTGC/gc-digital-talent/blob/ba12db200ce6775a4db0c5e1064af82d1d5bb7fb/frontend/talentsearch/src/js/components/search/SearchContainer.tsx#L196). 

## Possible Solution

```tsx
// Current
{!updatePending ? candidateResults : <Spinner />}

// Solution?
{!updatePending ? candidateResults() : <Spinner />}
```
