### ISSUE TITLE
Errors during build/deploy on Azure should notify devs

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2680]
First, errors during build scripts should cause the task on Azure to fail. This can be accomplished by including `set -e` in the build script.

Ideally, a failure during the build process could notify our slack bot.

The command that runs after the artifact is deployed (including artisan migrate) should also cause some sort of notification if it fails.

**Comment by patcon** [comment]
Not sure if you caught this typo, but noticing it in the azure-pipelines.yml file: (last letter of cypress envvar)
<img width="453" alt="Screen Shot 2022-05-07 at 3 50 48 PM" src="https://user-images.githubusercontent.com/305339/167269687-013ba9d5-d974-4f67-9623-452bd7570b55.png">

**Comment by petertgiles** [comment]
Tried to setup the Azure Pipelines Slackbot but I couldn't make it subscribe to anything.  It looks like there's already an Azure bot in robotfam anyway.
![image](https://user-images.githubusercontent.com/8978655/181094620-d2cc3c94-acff-440e-b801-70c561d8bdd9.png)

**Comment by tristan-orourke** [comment]
If we get the build pipeline working from a YAML file, this will be helpful for reporting errors: https://docs.microsoft.com/en-us/azure/devops/pipelines/customize-pipeline?view=azure-devops#create-work-item-on-failure

**Comment by tristan-orourke** [comment]
Try sending a message to Robert Blott about reporting errors from the startup command.

Just a thought... an alternative approach might be to try to set up monitoring in the logs? Like if we see a specific string show up in the console logs, send some kind of notification. Not sure if that's possible though.

**Comment by petertgiles** [comment]
Robert suggested opening a Jira ticket - https://jira.tbs-sct.gc.ca/browse/AZ-13572
