### ISSUE TITLE
Set Up Snyk

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2691]
We now have approval for funding to use Snyk.

## Acceptance Criteria
- [ ] Work with Gray to get the payment details
- [ ] Set up subscription
- [ ] Integrate it with the project

## 🛑 Blockers
```[tasklist]
### Blocked By
- [ ] #5338
````

**Comment by mnigh** [comment]
@brindasasi any estimate for this issue?

**Comment by brindasasi** [comment]
change the scan frequency from every PR to once every day something like that. We want to test this first before paying for it.

**Comment by patcon** [comment]
confirmed payment good. need to chek on npm workspaces (only supports yarn)

**Comment by brindasasi** [comment]
snyk replied back that supporting npm workspaces are coming out in the near future.
Currently snyk github action works fine with the free plan so far. 
Will leave it that way. So moving it into prod backlog for now.  @gobyrne or @tristan-orourke

**Comment by mnigh** [comment]
@brindasasi is this issue waiting on #5338 or can the issue be closed as stale?

**Comment by mnigh** [comment]
> once we switch to Yarn , this would be a great tool to integrate with. I would prefer to leave it @mnigh

It seems like we are [thinking](https://github.com/GCTC-NTGC/gc-digital-talent/issues/5338) of moving to pnpm instead of yarn now. The support for pnpm in snyk seems unclear: https://docs.snyk.io/scan-with-snyk/supported-languages-and-frameworks/javascript/best-practices-for-javascript-and-node.js#lerna-pnpm. Do @GCTC-NTGC/developers have any thoughts?

**Comment by mnigh** [comment]
@GCTC-NTGC/developers can this issue be closed as not planned?

**Comment by mnigh** [comment]
Closing as [support for pnpm in snyk seems unclear](https://docs.snyk.io/getting-started/supported-languages-and-frameworks/javascript/best-practices-for-javascript-and-node.js#lerna-pnpm).
