### ISSUE TITLE
API Server - Pick End-to-end testing framework

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#27]
# Description
Decide if we're going with Cypress or Robot or David's framework or anything else.

**Comment by tristan-orourke** [comment]
1 day timebox

**Comment by patcon** [comment]
Cypress +100.

I've used it extensively: it's super powerful, popular, extensible, highly documented and runs easily on CI. (Its ability to mock responses and do request interception is really powerful.) Once I get docker builds working in CI, I can copy-paste all my config over and have it up in 15 minutes.

Heck, nevermind docker, even if someone else gets the site building/serving in the GitHub Actions CI environment, I can just pull my Cypress boilerplate over from my work in https://github.com/compdemocracy/polis/tree/dev/e2e

Any framework would need the app building in CI first, so any path needs that. Since Cypress is essentially an effort-free drop-in after that, I could do the minimal setup without us making firm commitment. We could evaluate and if it's not satisfactory, try something else (no hard feelings on sunk costs)

**Comment by patcon** [comment]
@tristan-orourke might I be able to rescope this to "Implement e2e testing framework" and add some TODO checklists?

**Comment by vid** [comment]
Did you settle on something? Happy to set up a few tests with haibun/playwright for comparison.

**Comment by patcon** [comment]
We decided on cypress, but I still have openness to run haibun tests in parallel, on some subset of our tests, to help you exercise your tool (and to allow us to learn, while still leaning more on the tools with thousands of development hours invested internationally)

**Comment by patcon** [comment]
This is now the issue to track #1762

**Comment by vid** [comment]
You're writing your test suite in Cypress. That's about the layer we're comparing to Haibun. The lower level library being used by Haibun is [Playwright](https://playwright.dev/). The goal with Haibun is a slow project to support higher level project descriptions and validation, coupled in an agnostic way to cloud environments. Of course, each approach has its advantages.

**Comment by patcon** [comment]
Sorry, I'm not sure I understand whether your comment was supportive of my proposal or not :)

To clarify: If I'm understanding Haibun correctly, it uses BDD feature specs. I was hoping to eventually use https://www.npmjs.com/package/cypress-cucumber-preprocessor so both Haibun and Cypress can share BDD specs (though first step is just writing cypress tests directly in JS as cypress defaults to).

That way, Haibun can run a subset of our BDD tests --I assume we wouldn't reimplement the "tougher" parts, so not all BDD tests-- and we can support your building Haibun, while still getting the benefits of using Cypress, a tool with support systems for a user-base in the hundreds of thousands.

**Comment by vid** [comment]
Sure, that's a good strategy. 

The comment is around the concept of bundling a functional description as high level tests with individual components and services, all versioned together in a repo that doesn't contain any low level (eg js/nodejs) level code. These can then be used in any combination. Calling that a "flow background" in Haibun, as it develops, which can be re-used across projects. With a Haibun approach, you would use existing versioned modules that already provide the feature functionality. Any custom functionally would ideally be generalized in a module, but custom low level code can be included with a repo (see [example](https://github.com/withhaibun/haibun-e2e/blob/main/local/features/form.feature), which indicates what modules it uses [here](https://github.com/withhaibun/haibun-e2e/blob/main/local/config.json)).

There isn't this generalized approach with cypress-cucumber-preprocessor. So if your components/services use features x, y, z, you'll have to write the low level code that translate that into Cypress (though it's reusable in further feature files), which is more or less equivalent to what Haibun does in terms of "custom code". The proposal of Haibun is to provide common, versioned functionality to drive Playwright (or other testing frameworks; it could support Cypress easily enough, though probably not supporting its GUI features, Haibun does have nice review features for pipelines), services, connecting the local file system, Azure (or other storage providers), etc, through [interfaces](https://github.com/withhaibun/haibun/blob/main/modules/domain-storage/src/AStorage.ts).

In any case, using BDD as a starting point makes it easy enough to compare.
