### ISSUE TITLE
Refactor how initial values passed into SearchForm component 

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2702]
Re-ticketed from https://github.com/GCTC-NTGC/gc-digital-talent/pull/2694#issuecomment-1121460157

# Description
Currently SearchForm tries to grab initial values from location.state. That's a bit unusual, and makes it hard to tell (when reading the code) where that value would even be set in the first place. Turns out, RequestPage may set the state before redirecting back to the Search page, allowing you to edit the same filters you were working on before.

Passing intialValues into the SearchForm as a prop seems like a good start, it would give some more options for jest tests and storybook.

Defaulting it to undefined instead of {} might help avoid some re-rendering.

Instead of using location.state at all, we could simply reuse our SessionStorage hook. That would accomplish the same thing, I think, with a more standard pattern.

**Comment by esizer** [comment]
Related to #4716 ?

**Comment by mnigh** [comment]
Part of #2800?

**Comment by mnigh** [comment]
Hopefully done as part of https://github.com/GCTC-NTGC/gc-digital-talent/issues/2800
