### ISSUE TITLE
Profiles - Have to click twice to jump to sections

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2703]
On Firefox on Linux I need to click the floating section links twice to successfully jump to that section.  The first click jumps to the top of the screen and the second click successfully jumps to the section.![Peek 2022-05-10 09-45.gif](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/b5d250f5-25e4-4ae3-9aa0-10973ff9637c)

**Comment by tristan-orourke** [comment]
Is this also on other browsers?

**Comment by vd1992** [comment]
happened to me too on: on firefox
does not occur on: on edge

**Comment by RVany** [comment]
Yep. In edge and google chrome works fine for me but not landing in same position. I mean some links have space in top but others not.

**Comment by esizer** [comment]
Even worse in Safari, it will not jump down no matter what 👎 

https://user-images.githubusercontent.com/4127998/168361461-9294e2db-2752-4ae7-9093-130611407a22.mov

**Comment by tristan-orourke** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/2703?planning-poker) with ZenHub @petertgiles

**Comment by petertgiles** [comment]
Estimating high since I have no idea how to fix this. :shrug:

**Comment by tristan-orourke** [comment]
May be related to Universal Router
