### ISSUE TITLE
Profiles - Work Preferences always incomplete

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2706]
If I choose to not accept any of the work preferences the summary page says required fields are missing.![Peek 2022-05-10 10-00.gif](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/f7901ed4-c619-41ad-acb9-2a377cda8300)

**Comment by tristan-orourke** [comment]
Just the Work Preferences section logic
