### ISSUE TITLE
Profiles - Can't add new experiences

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2707]
When I fill in my profile the click to add new experiences sends me back to the domain root.![Peek 2022-05-10 10-05.gif](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/0a6a445a-dcb8-417a-ae11-a37e3f736ebc)

**Comment by tristan-orourke** [comment]
Incorrect routing or incorrect links
