### ISSUE TITLE
Get list of User roles

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#2708]
1. Is there a list of user roles other than Administrator? 
2. For these other user roles, what routes/pages would they have access to on the _/admin_ application?

**Comment by mnigh** [comment]
@Jerryescandon wondering if you had any information that you could share on this.

**Comment by gobyrne** [comment]
This is what I imagine so far:
- Admins
- Pool managers (grouped by organisation - any pool manager in an organisation can view and manage applicants or talent requests for all pools in their organisation)
- Talent Seekers : can be sent profiles via requests
- Applicants/Candidates: users with profiles and who can apply to processes
- Unauthenticated

**Comment by gobyrne** [comment]
But for now, all we have is Admin. Applicants/Candidates are soon to be added

**Comment by petertgiles** [comment]
Settled enough for now.  May be reopened later when more decisions are made.
