### ISSUE TITLE
Remove reliance on `x5c` property at /jwks

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#2716]
The staging `/jwks` endpoint: https://te-auth.id.tbs-sct.gc.ca/oxauth/restv1/jwks

**Success criteria:** Finding another way to check token sigs without using `5xc` property.

This would allow us to take a step toward replacing our custom auth app (for local development and CI) with one of the more turn-key mock oauth2 server.

I recommend we remove our usage of the poorly supported (as per a few mock oauth server projects) and unadvised ([as per Google Engineering](https://github.com/google/jws#:~:text=we%20eliminate%20easy%2Dto%2Dmisuse%20options%20such%20as%20%22x5c%22%2C%20%22x5u%22) and also [in-practice](https://www.googleapis.com/oauth2/v3/certs) in their infra) openid feature (the `x5c` property).

## Benefits

This would allow us to more easily benefit from migrating to a mock oauth2 server (for local development and CI). Migrating to a mock server would allow us to abandon our own `auth` app, and the special-case auth code paths within `api` app.

## Relevant code

Where we process the `x5c` property into a config object we use to later check token sigs:

https://github.com/GCTC-NTGC/gc-digital-talent/blob/13ae7e3bb79d564a80c809226ba61966c968c122/api/app/Services/OpenIdBearerTokenService.php#L74-L80

Email from Doug Harris of SiC:
> The “x5c” property contains the same public key represented by the “n” and “e” properties, just presented as an X.509 certificate for any software out there that might prefer the older format. It is completely redundant and ignored by most software I’ve worked with.
>
> As long as your software is still checking the signature on our ID tokens the normal way you can ignore the “x5c”.

Added this to icebox for now. cc @tristan-orourke

**Comment by patcon** [comment]
This is noted missing support from the library we're using: https://github.com/lcobucci/jwt/issues/32#issuecomment-392808889

This is a library suggested for it: https://github.com/acodercat/php-jwk-to-pem

Or this is perhaps better, as a more minimal dep is required, which doesn't pull in phpseclib:
https://github.com/lcobucci/jwt/issues/32#issuecomment-907556410

**Comment by yonikid15** [comment]
This is resolved in #2813
