### ISSUE TITLE
Test - Ensure Experience is updated

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#2717]
## Summary

The purpose of this is to write a cypress test for the workflow of editing an experience.

Ref: #1929 

## Workflow

1. Navigate to Skills & Experiences page
2. Click on Edit Experience button
3. Edit one of the fields
4. Save Form (this should navigate you back to the Skills & Experiences page)
5. Check the updated experience for the changes made in step 3

## Acceptance Criteria

- [ ] Write cypress test
- [ ] Confirm test passes
- [ ] ???

## Screenshot 

<img width="1169" alt="Screen Shot 2022-05-11 at 1 55 24 PM" src="https://user-images.githubusercontent.com/4127998/167915179-a21be2ab-3f98-4598-8c73-dcd9cc8324ef.png">

**Comment by mnigh** [comment]
@esizer is this issue still relevant?

**Comment by esizer** [comment]
> @esizer is this issue still relevant?

I think it will be if we end up writing a test to complete the entire application workflow that includes adding and editing an experience.

**Comment by esizer** [comment]
This no longer exists
