### ISSUE TITLE
Finish Migrating From Email To Sub For Authentication

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2722]
When our schema and user editor was being developed we were using Laravel auth and made three assumptions:
- Users would be authenticated by their email address
- Every user would have an email address
- Email address would never change

Now that we're using SiC these assumptions are not longer valid.  Instead:
- Users are authenticated by `sub` provided by the oauth provider
- Not every user can log in

Now we need to finish this migration:
- [ ] Email address can be blank and edited
- [ ] Sub can be blank and edited

Check:
- [ ] User Model
- [ ] Schema
- [ ] Admin forms
## Acceptance Criteria
- [ ] A user's `email` and `sub` values should be editable and nullable
  - [ ] A user can be created with no `email` or `sub` in the admin interface
  - [ ] An admin should be able to fill these values
  - [ ] An admin should be able to edit these values
  - [ ] An admin should be able to clear these values
  - [ ] An autocreated user should have the `sub` but no `email`
  - [ ] An autocreated user should be able to log in but have no roles and not be able access protected pages
  - [ ] An admin should be able to fill in the fields of an autocreated user to promote them to admin
  - [ ] Login should work with SiC
  - [ ] Login should work with Laravel Auth or Mock Auth (whatever is going by then :smile:)

## Estimated Tasks
Note, some of these are probably already done. Part of this task is double checking that.
- [ ] Update database with new migration
- [ ] Update eloquent models, factories, seeders
- [ ] Update schema queries, inputs, mutations
- [ ] Update Admin User Create and Edit forms

**Comment by tristan-orourke** [comment]
@petertgiles Any idea what the actual Acceptance Criteria are on this?

**Comment by petertgiles** [comment]
Here's my crack it:

## Acceptance Criteria
- [ ] A user's `email` and `sub` values should be editable and nullable
  - [ ] A user can be created with no `email` or `sub` in the admin interface
  - [ ] An admin should be able to fill these values
  - [ ] An admin should be able to edit these values
  - [ ] An admin should be able to clear these values
  - [ ] An autocreated user should have the `sub` but no `email`
  - [ ] An autocreated user should be able to log in but have no roles and not be able access protected pages
  - [ ] An admin should be able to fill in the fields of an autocreated user to promote them to admin
  - [ ] Login should work with SiC
  - [ ] Login should work with Laravel Auth or Mock Auth (whatever is going by then :smile:)

## Estimated Tasks
- [ ] Update database with new migration
- [ ] Update eloquent models, factories, seeders
- [ ] Update schema queries, inputs, mutations
- [ ] Update Admin User Create and Edit forms

**Comment by petertgiles** [comment]
TODO: About Me Profile update for email.
