### ISSUE TITLE
Document process for cutting a release

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#2723]
@tristan-orourke working on fleshing this out

- deploy to UAT server
- permission from xxxx
- ...
- related: azure-pipelines.yml?

**Comment by tristan-orourke** [comment]
https://docs.google.com/document/d/1iCUt_y5WIEtqapZL6S-lm_UIAshLEHeLeA2FjFoYRQY/edit#

**Comment by patcon** [comment]
used for deploy last week 🎉

**Comment by brindasasi** [comment]
Link the documents in Read Me  @patcon
