### ISSUE TITLE
Profile - Government Info - Typo

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2737]
Should be "I Have An Indeterminate Position" (with an n)

![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/70a50396-0729-4c83-a9b4-90ee60120a44)

**Comment by petertgiles** [comment]
@RVany Could you please put through a second PR with the French translation?  I think if the string changes it will get a new hash and the French string won't line up any longer.  Sorry, I should have mentioned that when I created the issue.

**Comment by petertgiles** [comment]
To be clear, I don't think the actual French string needs to change.  I think it just needs to be attached with the new hash.

**Comment by RVany** [comment]
Oh! Totally forgot about the translation. I should wait for a while. @petertgiles Can I make a PR again for the issue after merged to main?

**Comment by petertgiles** [comment]
No worries - I reopened the issue.  Go ahead and just start a new PR for that second change.

**Comment by RVany** [comment]
It looks like didn't translated yet. I searched the description in fr.json but no results. Any other way we can find the corresponding translation?

**Comment by RVany** [comment]
@petertgiles I am also getting a long list of untranlated messages in untranslated.json

**Comment by petertgiles** [comment]
Yeah, there's probably a pretty long list right now.  Let's just update the one you changed for now and not worry about the rest.

**Comment by petertgiles** [comment]
Oh, you're right, that string hasn't been translated yet!  Sorry, that's my bad.  :blush:
