### ISSUE TITLE
Polish Maintenance Scripts

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2756]
There are a few small tweaks to the maintenance scripts needed:

- [ ] The setup script still uses the "older" NPM commands style.  This might be [causing issues for Windows folks](https://talent-cloud.slack.com/archives/C0259G6KXJ6/p1652481252392069).  Let's switch to the workspaces style of command.
- [ ] There is no VS Code build shortcut for the setup script.  Let's add one.
- [ ] The setup script calls `chown -R www-data` several times.  This can cause issues on docker on Linux (and Mac?) where the user can't interact with files.  Can we get away with just change permissions and not owner?
- [ ] All the scripts reference `/var/www/html` which is where the files are in the containers.  Can we remove those to allow the scripts to run locally?  Maybe use an environment variable and fallback to `/var/www/html` if it is not set?
- [ ] The *refresh all* script calls the refresh scripts for the four workspaces all in a row which means hydrogen refresh gets called four times even though it should only be once.  I think we should have a *refresh frontend* script which one runs hydrogen once and call that from *refresh all*.

**Comment by patcon** [comment]
`composer install --prefer-dist` instead of leaving it unspecified. we don't have git on the maintenance container to use source installs anyhow. and it seems some versions or configurations of composer will `composer install` from source when left unsaid, and it's confusing when that happens. re: https://github.com/GCTC-NTGC/gc-digital-talent/pull/2728#issuecomment-1127867215

**Comment by patcon** [comment]
Also, maybe a "clean" flag to remove all the gitignored stuff. Or even just a `clean_all.sh` script to obliterate everything persistent, to kinda reset without re-cloning the repo. Relates to above comment.

**Comment by petertgiles** [comment]
> Also, maybe a "clean" flag to remove all the gitignored stuff

Are you thinking like a `git clean -x`?  This would require git in the container which I'm not sure it is right now.  Maybe just clean the node_modules, vendor, and storage directories?  That would get most of it without an extra dependency.

**Comment by petertgiles** [comment]
I'd like to have the `cp .env.example` do a "preserver ownership" thing so that it's not owned by root

**Comment by patcon** [comment]
> Are you thinking like a `git clean -x`? 

Nice! Didn't know about that. Just wrapping that is a great `clean_all.sh` or `clean_fresh.sh` :)

**Comment by petertgiles** [comment]
You know I'm usually the "split it up" guy but I think these are all small enough to keep them in one.

**Comment by petertgiles** [comment]
Since these are all based on pet peeves of mine I'm slowly accumulating the fixes in a stash that I'm using to dogfood the changes.
