### ISSUE TITLE
Update nodejs to Active LTS version 16

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#2757]
Project currently uses a version of nodejs, 14, that is on Maintenance LTS and will be [end of life in a year from now](https://nodejs.org/en/about/releases/) (2024-04-30).

Ensure Azure uses the same version when building artifacts.

**Comment by petertgiles** [comment]
@formatjs/cli@5.0.1 requires >= 16.5.0

**Comment by tristan-orourke** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/2757?planning-poker) with ZenHub @RVany

**Comment by RVany** [comment]
Honestly, @tristan-orourke I have no idea about the issue, @mnigh Can you please help me to estimate it.

**Comment by mnigh** [comment]
> Can you please help me to estimate it?

Sure, I would estimate this as a **3** because although the change of version is most likely a find and replace of the version in the repository files (see screenshot below), it will also require some effort to test locally as well on the remote servers (uat, prod).

![Screen Shot 2022-06-02 at 08 41 49](https://user-images.githubusercontent.com/3046459/171631610-e688f16a-d5d2-4a01-b9cc-bd994669cd82.png)

**Comment by vd1992** [comment]
a PR to revisit
https://github.com/GCTC-NTGC/gc-digital-talent/pull/2981
