### ISSUE TITLE
Pool Dashboard - Style Dashboard forms

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#276]
# Description
Update dashboard forms so that on full screens, inputs are divided across multiple columns, or for smaller forms (eg User) so inputs are all placed in one narrower column.

# Designs
https://www.figma.com/file/jOGqmmyq7mr3oVdiimiuPW/Admin-Interface---V1.0

**Comment by gobyrne** [comment]
More work has been done on this UI and this issue is no longer relevant.
