### ISSUE TITLE
Successful submission screen for talent request form

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#2762]
email address for "get in touch:
`recruitmentimit-recrutementgiti@tbs-sct.gc.ca`

[Wireframe ](https://www.figma.com/proto/XS4Ag6GWcgdq2dBlLzBkay/Admin-v3?page-id=0%3A1&node-id=1171%3A6074&viewport=-1637%2C-2263%2C0.73&scaling=min-zoom&starting-point-node-id=949%3A5635&show-proto-sidebar=1)

## V1
![image](https://user-images.githubusercontent.com/16977254/169172999-f59ab4a8-bcb6-4f76-b8cb-4216e7b463d9.png)

## V2

![image](https://user-images.githubusercontent.com/16977254/214626302-f016366e-f276-4bb5-a1c4-3a1a6874a3f3.png)

## Acceptance Criteria
- [ ] This is a new page, available at `/search/request/<request-id>`
- [ ] It shows mostly static text, but also the id of the request you just submitted
- [ ] After requesting a talent search, you are directed to this page
- [ ] If someone navigates here by different method, just show the page normally, don't verify or guard

- [ ] Breadcrumb destinations: homepage \ search page \ this page

**Comment by tristan-orourke** [comment]
@Jerryescandon can we get designs that use breadcrumbs that look like the breadcrumbs on the Profile?

**Comment by Jerryescandon** [comment]
Closing this one in favor of https://github.com/GCTC-NTGC/gc-digital-talent/issues/5469
