### ISSUE TITLE
Replace CMO skills filter in request page.

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#2765]
[Wireframe ](https://www.figma.com/proto/XS4Ag6GWcgdq2dBlLzBkay/Admin-v3?page-id=0%3A1&node-id=949%3A5635&viewport=-1637%2C-2263%2C0.73&scaling=min-zoom&starting-point-node-id=949%3A5635&show-proto-sidebar=1)

### **OLD SKILLS**

This change should be made to the NEW SearchForm.

![image](https://user-images.githubusercontent.com/16977254/168658276-21585fff-edca-4138-885a-f9a9c4948bc6.png)

### **NEW SKILLS**

![image](https://user-images.githubusercontent.com/16977254/168658071-4dede2b4-e459-4698-9631-57f011869010.png)

**Comment by tristan-orourke** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/2765?planning-poker) with ZenHub @mnigh

**Comment by esizer** [comment]
The query we are currently using `countPoolCandidates` does not allow to filter by skills. We may need to add this to acceptance criteria and update estimate or create a separate issue blocking this one.

**Comment by mnigh** [comment]
> The query we are currently using `countPoolCandidates` does not allow to filter by skills. We may need to add this to acceptance criteria and update estimate or create a separate issue blocking this one.

@esizer It appears that `countPoolCandidates` has recently been [deprecated](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/api/graphql/schema.graphql#L642) in favour of `countApplicants`. The input, `ApplicantFilterInput`, used by the query `countApplicants` does seem to allow for [skill filtering](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/api/graphql/schema.graphql#L624) or has this not been implemented correctly?

**Comment by esizer** [comment]
> @esizer It appears that `countPoolCandidates` has recently been [deprecated](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/api/graphql/schema.graphql#L642) in favour of `countApplicants`. The input, `ApplicantFilterInput`, used by the query `countApplicants` does seem to allow for [skill filtering](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/api/graphql/schema.graphql#L624) or has this not been implemented correctly?

Very strange, I pulled down main earlier this morning and that was not there 😕 . 

Never mind me then :P

**Comment by tristan-orourke** [comment]
When https://github.com/GCTC-NTGC/gc-digital-talent/pull/3291 is complete, you can pass an ApplicantFilter to the Request page instead of a PoolCandidateFilter.
