### ISSUE TITLE
talent - search results bug

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#2766]
toggling the filter to narrow down and then toggling off does not return back the original number of candidates

https://recordit.co/2mwW9UKKTS

**Comment by esizer** [comment]
To add to what @vd1992 has already found, it has to do with the query to get the pool and the initial query for candidates running concurrently.

## Initial Load

```tsx
  const [{ data }] = useGetSearchFormDataQuery({
    variables: { poolKey: DIGITAL_CAREERS_POOL_KEY },
  });
  const pool = data?.poolByKey;

  const [candidateFilter, setCandidateFilter] = useState<
    PoolCandidateFilterInput | undefined
  >(undefined);

  /**
   * This is running concurrently with useGetSearchFormDataQuery
   *
   * Both candidateFilter and pool are undefined so no filters are passed
   * in the request payload
   */
  const [{ data: countData, fetching: countFetching }] =
    useCountPoolCandidatesQuery({
      variables: candidateFilterToQueryArgs(candidateFilter, pool?.id),
    });
```

### Request Payload

In the request made on mount, you can see we are not passing any variables to the `graphql` operation.

```json
{
  "query": "query countPoolCandidates($where: PoolCandidateFilterInput) {\n  countPoolCandidates(where: $where)\n}\n",
  "operationName": "countPoolCandidates",
  "variables": {}
}
```

## Subsequent Renders

On any render **after** the initial render, we have the pool so it is then passed on each other request so the number of candidates do not match the original number even if we reset all of the filters in the form.

### Request Payload

```json
{
  "query": "query countPoolCandidates($where: PoolCandidateFilterInput) {\n  countPoolCandidates(where: $where)\n}\n",
  "operationName": "countPoolCandidates",
  "variables": {
    "where": {
      "classifications": [],
      "cmoAssets": [],
      "operationalRequirements": [],
      "hasDiploma": false,
      "hasDisability": false,
      "isIndigenous": false,
      "isVisibleMinority": false,
      "isWoman": false,
      "workRegions": []
    }
  }
}
```

## Proposed Solution

I think this should be relatively simple to resolve now that we know what is happening. Apply some `useEffect` logic around the `useGetSearchFormDataQuery` should have this operation block all other logic in the component. We could store the pool in local state and only run the candidate query as a side effect of `pool` and `candidateFilter` state changes.

```tsx
  React.useEffect(() => {
    if (pool) {
      // Get candidates here
    }
  }, [pool, candidateFilter]);
```
