### ISSUE TITLE
Employment duration -  New filter in request page.

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#2768]
[Wireframe](https://www.figma.com/proto/XS4Ag6GWcgdq2dBlLzBkay/Admin-v3?page-id=0%3A1&node-id=949%3A5635&viewport=-1637%2C-2263%2C0.73&scaling=min-zoom&starting-point-node-id=949%3A5635&show-proto-sidebar=1)

Add new filter to the request talent page called "Employment duration". This should be made to the NEW SearchForm.

Any Duration is equivalent to leaving this filter empty.

![image](https://user-images.githubusercontent.com/16977254/168661826-146da1e4-18e1-46e1-a2ef-7f9014eb33e9.png)

## Acceptance Criteria

- [ ] These inputs are connected to the api query
- [ ] UI is done

**Comment by tristan-orourke** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/2768?planning-poker) with ZenHub @patcon

**Comment by Jerryescandon** [comment]
This IS a 3 to 2 options. And it goes like this:

If a manager selects: 
"Any duration"
We return ALL APPLICANTS

If a manager selects: 
"Permanent duration"
We return ALL APPLICANTS

If a manager selects: 
"Term duration"
We return applicants that selected: "Any duration"

The reason for this is so that we capture whether or not a manager already knows what kind of offer they can make for this position and so we can pass that info to DCMO. @gobyrne please confirm.

**Comment by vd1992** [comment]
Thank you!
