### ISSUE TITLE
Replace Conditions of employment

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#2769]
[Wireframe](https://www.figma.com/proto/XS4Ag6GWcgdq2dBlLzBkay/Admin-v3?page-id=0%3A1&node-id=949%3A5635&viewport=-1637%2C-2263%2C0.73&scaling=min-zoom&starting-point-node-id=410%3A1984&show-proto-sidebar=1)

Conditions of employment need to be updated to reflect the fields collected on the New profile. This should be made to the NEW SearchForm.

### **OLD CoE**

![image](https://user-images.githubusercontent.com/16977254/168662193-43f85802-0d97-41c8-aa95-35014b7addb8.png)

### **New CoE**

![image](https://user-images.githubusercontent.com/16977254/168662958-57b7a3bb-562a-4a4e-98c2-cf0e547b3562.png)

**Comment by tristan-orourke** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/2769?planning-poker) with ZenHub @petertgiles

**Comment by petertgiles** [comment]
Looks like some of the enums will carry over but some new one will need to be made.  Probably will need to create a new set of localized constants, maybe gated with a feature flag.

**Comment by Jerryescandon** [comment]
yeah, let's use the language on the profile. e.g.
- "work overtime on short notice"
- "work scheduled overtime"
