### ISSUE TITLE
Profiles - Unexpected value 1.5rem

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2774]
When navigating to the /talent/profile page the console is filled with warnings.

```
Unexpected value 1.5rem parsing width attribute.
Unexpected value 1.5rem parsing height attribute.
```

![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/e80ba7e2-ccc3-4b9e-bc36-4136b5bd8d69)

**Comment by tristan-orourke** [comment]
Is this browser specific?
