### ISSUE TITLE
IAP - Storybook - Need Mobile Snapshot

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2776]
Could we add a storybook story in a mobile size for snapshotting for IAP?

**Comment by petertgiles** [comment]
Might be nice to have French snapshots, too.

**Comment by tristan-orourke** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/2776?planning-poker) with ZenHub @yonikid15
