### ISSUE TITLE
User still considered logged in when token is expired

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2777]
When the user logs in to the admin portal, and then leaves the site for a while, and comes back later, the site will still appear as Logged In, but api calls will fail because the access token is expired.

If the access token is refused, the refresh token should always be used to get a new access token. If the refresh token is rejected as well, the frontend should trigger a logout.

**Comment by vd1992** [comment]
I'm supposed to get logged out of admin portal 🤔 
I don't think that has happened yet, regardless of closing browsers or a day elapsing. Or is this a non-local environment thing?
