### ISSUE TITLE
Pool Details tab (Pool Summary page)

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2797]
[Figma Prototype](https://www.figma.com/proto/XS4Ag6GWcgdq2dBlLzBkay/Admin-v3-(Profile-release)?scaling=min-zoom&page-id=0%3A1&starting-point-node-id=410%3A1984&show-proto-sidebar=1&node-id=752%3A6863)

![image.png](https://images.zenhubusercontent.com/5d9ded8fd25901000101f3f0/855af617-d2df-4983-aaa1-409f3a740b29)

## Acceptance Criteria
- [ ] ...

**Comment by Jerryescandon** [comment]
Old, new pool details page have been design and put in backlog
