### ISSUE TITLE
Write PHPUnit tests for countApplicants query

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2803]
The many filters of the query make it complicated, and we've repeatedly found bugs with it. We need to write a suite of tests to have high confidence in this.

Issues we've found
- selecting all classifications can return a higher number than is actually in the pool you're searching on
- salary range & classification not interacting correctly
- filtering by English or French not including bilingual candidates
- ensure setting isWoman (and other EE fields) to false doesn't exclude women.

**Comment by mnigh** [comment]
These might be already written, but worth double checking.

**Comment by vd1992** [comment]
scope adjusted
