### ISSUE TITLE
Small bugs in talentsearch profile page

### ISSUE THREAD

**Issue by RVany** [GCTC-NTGC/gc-digital-talent#2804]
- When we click the links in the sidebar, first two links are placed very top of the screen but other links have some spaces in the top. 
- The usernames on the profile banner looks not vertically centered.
- Wrong breadcrumbs in edit experience/add experience page.  [wireframe](https://www.figma.com/proto/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?node-id=2340%3A4352&starting-point-node-id=1%3A2)

_**Note**_ All of the above may not a big deal 😀

https://user-images.githubusercontent.com/95497896/169101902-1620a792-cd6a-47c2-ba6e-80cd611baf80.mp4

**Comment by vd1992** [comment]
Ah, yeah I can verify bullet one. Think the issue is with how the Divs are split, some have a bunch of whitespace above the actual header. 

![image](https://user-images.githubusercontent.com/40485260/169111012-60e0382c-355c-44ca-8694-6275d0e2a757.png)

**Comment by vd1992** [comment]
I think bullet 3 should be an easy fix, need to add the missing entry into the crumbs array

![image](https://user-images.githubusercontent.com/40485260/169117823-1da5ac4c-64b9-4669-abe3-c7642d35b8ef.png)

**Comment by tristan-orourke** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/2804?planning-poker) with ZenHub @vd1992
