### ISSUE TITLE
Remove classification group constraint for salary-to-classification filter

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2806]
From slack today:

> Peter
> I'm troubleshooting a search issue that Vachan found right now in the salary to classification query.  I noticed a quirk in the logic that I'm not sure is right.  Right now the logic requires you to have selected a classification in the searched group to do a salary-to-classification match.  So if you're searching for IT-01 the candidate will only be matched on salary if they included at least one IT classification in their profile.  Is this constraint correct or do we want to match on salary regardless of any classifications in their profile?
> 
> Based on Tristan's reply to Gray's question I'm pretty sure the constraint should not be there, right?
> 
> Tristan
> Yep, that does not sound right :confused:
> 

## Acceptance Criteria
- [ ] Ensure this fix applies to PoolCandidates and Users search
- [ ] PHPUnit test

**Comment by tristan-orourke** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/2806?planning-poker) with ZenHub @esizer
