### ISSUE TITLE
Component font consistency

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#2809]
There seems to be some font inconsistency between components. While "empty" and "filled" states might change in colour, it's best if they all have font type and size consistency.

Unsure which should be the base one so I'm tagging @JoshBeveridge on this one.

![image](https://user-images.githubusercontent.com/16977254/169143231-473c8b53-aaa3-4d07-9bd9-342c68d71f9a.png)

**Comment by JoshBeveridge** [comment]
Yeah, agreed. These should all be set to Hydrogen's base font size.

**Comment by tristan-orourke** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/2809?planning-poker) with ZenHub @RVany
