### ISSUE TITLE
Talent passed their expiry date in the pool should not show up in search results

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#2810]
## AC
- [x] apply this change to User and PoolCandidate search
- [x] phpunit tests

**Comment by tristan-orourke** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/2810?planning-poker) with ZenHub @esizer

**Comment by esizer** [comment]
I have little to no confidence in my estimate due to my incredible lack of knowledge on the work that needs to be done on this issue. I will need more experience in lighthouse-php to improve to accuracy of estimates on issues related to it.
