### ISSUE TITLE
Combine Webpack bundling

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2814]
We are consolidating our frontend project more and more:
- Combined hydrogen
- Combined linting
- Combined npm node_modules
- Combined storybook (in Chromatic)

Does it make sense to combine our webpack bundling?  It would have some benefits:
- Single spot for bundling config
- Ability to start watch mode and freely edit any project
- Ability to start a webpack dev server and test any project
- Simpler setup and refresh process

Open questions:
- Can we use webpack to split the project into similar bundles (common, admin, talentsearch, iap) as the current separate bundles so the user doesn't have to download all three sites whenever they visit one?
- Would the new split bundles be about the same size as the current separate bundles?
- Can webpack bundle the whole frontend project reasonably quickly?
- Can webpack bundle just one subproject from a combined config if desired?
- Can a combined webpack config stay reasonably simple and maintainable?

**Comment by petertgiles** [comment]
- also combine .babelrc and .browserlistrc files

**Comment by mnigh** [comment]
@petertgiles is this issue stale now that https://github.com/GCTC-NTGC/gc-digital-talent/issues/5065 is complete?

**Comment by petertgiles** [comment]
Completed in #5065
