### ISSUE TITLE
Admin notes for Language testing

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#2819]
On the "Profile" tab of the Candidate form in the Admin Portal. Add a savable text fields for admins to enter and saves notes about the candidates' language levels.

Question: Where do we keep the data for these notes. It doesn't quite make sense to keep in on the profile because candidates shouldn't actually have permissions to view it.

![image.png](https://images.zenhubusercontent.com/5dc084854553760001149b53/fd95acd1-c48c-4290-8bd0-9981aafcd364)

**Comment by mnigh** [comment]
@gobyrne @tristan-orourke is this still a feature being considering or can this issue be closed as stale?

**Comment by tristan-orourke** [comment]
Seems pretty dead to me
