### ISSUE TITLE
Implement SkipTo navigation

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/gc-digital-talent#2824]
# Description
Install the handy [SkipTo](https://paypal.github.io/skipto/) navigation feature ([github page](https://github.com/paypal/skipto)). 

By default, SkipTo menu will include the following places on the page:

- Heading (e.g h1, h2, h3 and h4 elements).
- ARIA landmarks (e.g. banner, navigation, main and search).
- HTML5 Section Elements (e.g. main, section[aria-label], section[aria-labelledby]

and options:

- The default “access key” is set to 0.
- The menu button by default is visible, but can be configured to appear on keyboard focus only.

All of the above is claimed to be customizable, as well as the styling and text.

**Comment by mnigh** [comment]
### Pros
- [npm package](https://www.npmjs.com/package/skipto) available

### Cons
- not written in TypeScript
- not written in module syntax

**Comment by mnigh** [comment]
@esizer thoughts on using this?

**Comment by esizer** [comment]
> @esizer thoughts on using this?

While not translated (oopsie on my part), we do have a skip link. The other functionality this provides (headings, landmarks, etc) are all built in to most ATs now which I believe is the main target for something like this library.

**Comment by mnigh** [comment]
> > @esizer thoughts on using this?
> 
> While not translated (oopsie on my part), we do have a skip link. The other functionality this provides (headings, landmarks, etc) are all built in to most ATs now which I believe is the main target for something like this library.

It is now translated into French as of https://github.com/GCTC-NTGC/gc-digital-talent/pull/6072!

![Screen Shot 2023-04-04 at 17 05 50](https://user-images.githubusercontent.com/3046459/229922318-4bfb51aa-1b89-4427-8c01-34c7eaa18bd9.png)

@petertgiles can this issue be closed as stale?

**Comment by petertgiles** [comment]
@yonikid15 would you like to see further discussion on this topic?
