### ISSUE TITLE
Improve azure deploy process (version-control & consolidate config)

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#2834]
Re-ticketed from https://github.com/GCTC-NTGC/gc-digital-talent/pull/2683

Goals:
- consolidate config files with development in content and location (.htaccess)
- consolidate config files between environments (htaccess)
- as much as possible, have deploy processes for all environments in version control (azure-pipelines.yml, htaccess, deploy.sh)
- if possible, use `setup.sh` scripts in `deploy.sh`

## Potential To Dos
- [x] remove [`infrastructure/deploy.sh`](https://github.com/GCTC-NTGC/gc-digital-talent/blob/azure-pipeline-file/infrastructure/deploy.sh) in favour of improved [`infrastructure/bin/deploy.sh`](https://github.com/GCTC-NTGC/gc-digital-talent/blob/azure-pipeline-file/infrastructure/bin/deploy.sh)
- [x] set up azure to read from repo -- @tristan-orourke 
  - https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#access-to-github-repositories
  - Instructions for selecting YAML file when multiple: https://stackoverflow.com/a/56809695
- [x] test deploy -- @tristan-orourke 
- fully consolidate [`infrastructure/php-container/src/.htaccess`](https://github.com/GCTC-NTGC/gc-digital-talent/blob/azure-pipeline-file/infrastructure/php-container/src/.htaccess) and [`infrastructure/conf/deploy.htaccess`](https://github.com/GCTC-NTGC/gc-digital-talent/blob/azure-pipeline-file/infrastructure/conf/deploy.htaccess)
  - what's left: https://github.com/GCTC-NTGC/gc-digital-talent/pull/2683#issuecomment-1133455543
  - [x] remove need for serving auth endpoints (done in #2813)
  - [x] ~~fence off indigenous apprenticeship endpoints with `FEATURE_IAP` feature flag~~
    - diff below (already tested) https://github.com/GCTC-NTGC/gc-digital-talent/issues/2834#issuecomment-1133475924
    - No longer necessary, IAP homepage is already in production
  - [ ] actually merge files into one: (`infrastructure/php-container/src/.htaccess`?)
  - [ ] update `deploy.sh` to use new file above
  - in the interest of getting away from scattered `.htaccess` files (htaccess isn't recommended, and nginx doesn't do anything like it)...
    - [ ] optional: consolidate all .htaccess files into single dir (`infrastructure/conf/`?)
    - [ ] update `setup.sh` to copy files from this single dir during setup
- [ ] added feature flag envvars to azure-pipelines.yml
- [x] ensure `azure-pipelines.yml` works/exists for staging + production
- [x] perform mock run of `deploy.sh` in CI environment (maybe scheduled? maybe on commits to mainline?)

## Open Questions
1. Is there a separate `azure-pipeline.yml` for staging and production pipelines? If so, do we want the other in here?
2. Where are environment variables for apache stored in the deploy? Are they in azure-pipeline.yml? If not, can they be?

**Comment by patcon** [comment]
> - [ ] fence off indigenous apprenticeship endpoints with `FEATURE_IAP` feature flag


<details>
<summary>Click to see diff...</summary>

```diff
diff --git a/frontend/.apache_env b/frontend/.apache_env
index 4c1a4ac55..d3f7d78e9 100644
--- a/frontend/.apache_env
+++ b/frontend/.apache_env
@@ -5,4 +5,6 @@ OAUTH_POST_LOGOUT_REDIRECT="http://localhost:8000/admin"
 # OAUTH_LOGOUT_URI="https://te-auth.id.tbs-sct.gc.ca/oxauth/restv1/end_session"
 
 # Feature flags
+FEATURE_PHPINFO=true
+FEATURE_IAP=true
 FEATURE_APPLICANTPROFILE=true
diff --git a/infrastructure/php-container/src/.htaccess b/infrastructure/php-container/src/.htaccess
index 332e9f294..9b4f18b2b 100644
--- a/infrastructure/php-container/src/.htaccess
+++ b/infrastructure/php-container/src/.htaccess
@@ -39,11 +39,12 @@ DirectorySlash off
     # Send localized talent requests also to talentsearch dist folder;
     RewriteRule ^(en|fr)/talent(/(.*))?$ frontend/talentsearch/dist/$3 [L]
 
-    # Indigenous Apprenticeship routes
-    RewriteRule ^indigenous-it-apprentice(/(.*))?$ frontend/indigenousapprenticeship/dist/$2 [L]
-    RewriteRule ^(en|fr)/indigenous-it-apprentice(/(.*))?$ frontend/indigenousapprenticeship/dist/$3 [L]
+    # Indigenous Apprenticeship routes (feature-flagged)
+    RewriteCond expr "'%{ENV:FEATURE_IAP}' == 'true'"
+    RewriteRule ^((en|fr)/)?indigenous-it-apprentice(/(.*))?$ frontend/indigenousapprenticeship/dist/$4 [L]
 
-    # PHP Info page for debugging
+    # PHP Info page for debugging (feature-flagged)
+    RewriteCond expr "'%{ENV:FEATURE_PHPINFO}' == 'true'"
     RewriteRule ^phpinfo.php$ phpinfo.php [L]
 
     # Send all other requests to /tc-report
```
</details>

**Comment by tristan-orourke** [comment]
Estimating as a 5 due to general uncertainty around how this will work.

**Comment by petertgiles** [comment]
> This issue is being prioritized because we hit the character limit on the way we're currently generating the htaccess file in Azure. We should just be importing it from the repo instead!

Solution in #3513

**Comment by petertgiles** [comment]
Woof, this issue is too big!  I think it should be broken up.

**Comment by tristan-orourke** [comment]
Remaining todos split off into https://github.com/GCTC-NTGC/gc-digital-talent/issues/3571
