### ISSUE TITLE
Common component which includes Loading and Error messages

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2862]
We have a common pattern on many pages, where we show a loading message until initial data is loaded, and an error message if something went wrong, and then the real component otherwise. It would be good to have a common component for this, to simplify our page components and ensure we're using consistent messages. It will also make it easier to improve our loading display in the future.

# Acceptance Criteria
- [ ] Every component following this pattern (loading, error, component) should use this common component instead.

**Comment by patcon** [comment]
In case helpful (not necessarily accessible, but works out-of-the-box): https://github.com/davidhu2000/react-spinners
