### ISSUE TITLE
Extract Profile Form onSubmit functionality to common function

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2863]
While the mutation is obviously different for each Profile form, the `.then()` (and `catch()` for that matter) should be mostly the same; throw up the same toast if successful, check for a completed profile, and then redirect to the main profile page. We can always show the same error on a failure too. 
Right now, there are some minor differences in what happens on different forms. It would be good to make them all consistent, and using a common function will help.

- [ ] All profile forms working with this
- [ ] Cypress or Jest test

**Comment by petertgiles** [comment]
Gonna bump this up to 3 and hope for a cypress test!
