### ISSUE TITLE
Linting - Final Steps

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2866]
The bulk of the linting is finished!  There are two final steps:

1. Cleanup remaining linting issues (currently two minor `@typescript-eslint/no-unused-vars` warnings)
1. Update Github Action for linting to not `continue-on-error`

**Comment by tristan-orourke** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/2866?planning-poker) with ZenHub @patcon
