### ISSUE TITLE
Investigate MVP flow for deleted GCKey account

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#2870]
- GCKey allows for the "revocation" of the account, which essentially deletes the whole GCkey account, and a new one needs for be created

**Scenario:** A user signs up for GCKey, then connects to our app and provides an email via the "Welcome" process. The user then revokes/deletes their gckey account, and creates a new one, then tries to log in again. They are now redirected to a welcome process, but can't get further because their email is "taken".

## Open Questions

- from both the user and "admin" side:
    - what is the MVP without a UI? (database queries and/or a script)
    - what is the MVP with a UI?
- how might getting the [optional] email from GCKey change/improve this flow?

**Comment by gobyrne** [comment]
Great question @patcon. Do we have confidence that our app is resilient enough to handle the GCkey being deleted? Or I guess we won't ever know about it...

**Comment by mnigh** [comment]
> Or I guess we won't ever know about it...

I think this is the key point, our application is in no way synced with GCKey other than the initial sign up and will likely never be synced. I would imagine that if the scenario in the description took place, an administrator would need to manually update the email of the user.

@tristan-orourke is this a `wontfix` issue?

**Comment by tristan-orourke** [comment]
Yeah, I think we can call this a wontfix issue. If someone deletes their GCKey and then has trouble logging in, we won't know unless they send a message to our help desk. We can figure out what to do then.
