### ISSUE TITLE
API - File name casing bug

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2873]
Composer is complaining about the casing of the DatasetInferface file.  I think it's not causing any problems, normally.  It does seem to be causing fatal errors during testing on Patrick's laptop but I'm not clear on why.

![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/1cde4bc9-ccb9-48cf-ac66-d03b1fa5f4bb)

**Comment by patcon** [comment]
Ah, sneaky, I didn't spot that case difference :)
