### ISSUE TITLE
Better API error messages

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2883]
We recently updated our graphql error handling to not dump the entire error into a toast.  However, there are certain errors that we probably do want to show the error.  For example, if the email was already in use we would want to clearly tell the user that.  Lighthouse has the ability to set custom error messages: https://lighthouse-php.com/master/api-reference/directives.html#rules .  Could we use that and pass those through to the toast?  Could those error messages be localized?

**Comment by tristan-orourke** [comment]
We need to show errors to the user only if there is something the user can do about it. Unique email constraint is a good example. A good rule of thumb might be that rules in the schema should have custom text.

**Comment by tristan-orourke** [comment]
Spike for how to localize those errors
- have both languages on the API?
- pass back an error code, use something like localized constants?
- ?

**Comment by yonikid15** [comment]
For creating a pool, I was using the same key which caused the duplicate key value violates unique constraint. Same with using the same subject for creating a user. We should definitely add a more user friendly error message.

**Comment by brindasasi** [comment]
Strategies I researched
Backend Validation : 
A nice tutorial I found is in here for this type of implementation.
 https://laravel-news.com/testing-api-validation-errors-with-different-locales 
 It uses php files for translations but I find Laravel can get the translations from json file as well. https://laravel.com/api/5.8/Illuminate/Translation/Translator.html
 Front-end Translation :

**Comment by brindasasi** [comment]
So I was working towards bubbling up the http status code in the response with the custom error messages , I came across these info 
https://github.com/nuwave/lighthouse/issues/279#issuecomment-415707690 and 
https://github.com/nuwave/lighthouse/issues/1694#issuecomment-766841328

**Comment by petertgiles** [comment]
Those comments make sense to me.  The other thing that make me agree with the approach is that URQL needs to be able to interpret if it's an error response that needs to have the auth refreshed.  This could easily put the user in a refresh loop.

I like your idea of handling the translation on the frontend.  Keep it all together, right?  The thing I'm not sure of is how to make sure we're capturing all the messages of the API when we run intl-extract.

**Comment by brindasasi** [comment]
Let me try get that in the PR before the meet up today.

**Comment by brindasasi** [comment]
Basically my thought is to organize all the error messages we add as key ,value pair. 
EMAIL_IS_NOT_UNIQUE : Intl.formatMessage("Email is not unique") in the front end. 
We would be throwing EMAIL_IS_NOT_UNIQUE from the custom exception.
we would resolve that in the front end for the actual error msg. 
We would also make sure Intl.formatMessage("Email is not unique") is getting extracted when we run Npm run intl-extract

**Comment by brindasasi** [comment]
This can also be further improved as one place to organize all the error messages in the front end as well as the back end

**Comment by brindasasi** [comment]
After the spike discussion with the team we decided to move on with validation rules with custom messages on graphQL 
The next step would be to implement the first set of unique validation as per the issue 
https://github.com/GCTC-NTGC/gc-digital-talent/issues/3322 
We would add other validations after.
