### ISSUE TITLE
How to protect sub?

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2887]
The user `sub` field is particularly important as it controls authentication.  Right now it is very easy to swap values, delete values, etc.  This would be a problem for security logging and will make it easy to accidentally render an account unusable without dev intervention.  Should we make it harder to change?  On a separate page?  Add a warning dialog?

**Comment by mnigh** [comment]
@petertgiles might this issue be a candidate for conversion to discussion?
