### ISSUE TITLE
Improve dev seeded data

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2894]
Some of the dev seeded data is not very realistic and makes it tricky to do manual testing and development.

- Our candidates should have expected salary or expected classifications but not both
- Our candidates should actually conform to the requirements of the pool they are in
- Some of our candidates should be expired

**Comment by tristan-orourke** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/2894?planning-poker) with ZenHub @JamesHuf
