### ISSUE TITLE
Bug - Storybook i18n not working

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#2895]
## Summary

We have applied a hack in #2888 to get a storybook displaying both French and English versions of the homepage story. We need to undo this change and properly implement i18n.

## Details

We are currently using [storybook-addon-intl](https://storybook.js.org/addons/storybook-addon-intl). It seems as though the locale is changing (the logo updates) however, the messages are not properly being loaded in `react-intl` so any text localized by it is not updating.

**Comment by esizer** [comment]
Believe this magically fixed itself 🦄

**Comment by esizer** [comment]
> Believe this magically fixed itself 🦄

Nvm, it works while running storybook locally but not while hosted on chromatic.

**Comment by mnigh** [comment]
Seems to work on some stories in Chromatic and not others. Perhaps something to do with how the projects are importing the frCompiled.json file?

**Comment by patcon** [comment]
This should be resolved in the above PR. It was only an issue with the merged storybook we render via chromatic (a special case of the admin storybook), but unmerged local storybooks worked fine

**Comment by patcon** [comment]
Closing as associated PR is merged :)
