### ISSUE TITLE
Add Auth to TalentSearch

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2896]
We have our auth containers available in common now.  It would be a good time to enable auth in talentsearch.  We need auth there for all the profile and direct intake stuff.  Eric made a nice context component for admin with our "container sandwich" inside that could be reused.  I guess we would need log in and log out links?

# Acceptance Critera
- [ ] Root component in talentsearch includes AuthContainer 
- [ ] Profile page and direct intake routes require logged-in and APPLICANT role
- [ ] Cypress test for user without this role denied access profile and direct intake pages?

**Comment by petertgiles** [comment]
Do we want to do it for IAP at the same time?  It's not really need there yet.

**Comment by petertgiles** [comment]
Should we comment out the default AUTH_DEFAULT_USER as admin in the .env.example file after this?  It will be confusing to revert to an admin user when testing applicant pages.

**Comment by tristan-orourke** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/2896?planning-poker) with ZenHub @esizer
