### ISSUE TITLE
Add a APPLICANT role

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2911]
Some pages will require a user to be logged in for use cases such as:
- Filling in their profile
- Applying to a pool

We need to add a role to the system for this activity for the authorization system.

> Question: Will the autogenerated users get this role?  
- Yes! [See comment](https://github.com/GCTC-NTGC/gc-digital-talent/issues/2911#issuecomment-1144174997)

User Acceptance:
- [x] Add new role to graphql schema enum
- [ ] ~Add new role to authentication container type~ (roles not listed in auth containers)
- [x] Set new role to be user by seeders and fakers
- [x] Ensure users created on first login are given APPLICANT role
- [x] Migration which adds APPLICANT role to all users already in database. (Question - should this be a Seeder instead, which we can run manually in production?)
- [ ] ~Add role to protect profile and direct intake routes~ (already in #2896)
- [x] Cypress test for user with this role denied to access admin pages?
- [ ] ~Cypress test for user without this role denied access profile and direct intake pages?~ (moved to #2896)

**Comment by petertgiles** [comment]
Note from Jerbo through Tristan: An APPLICANT is someone who is in the system.  A CANDIDATE is someone who has been assessed and accepted into a pool.

**Comment by tristan-orourke** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/2911?planning-poker) with ZenHub @JamesHuf

**Comment by tristan-orourke** [comment]
> Question: Will the autogenerated users get this role?

Autogenerated users should absolutely get this role. In fact, ALL users should have this role. That includes all seeded users, and all users created when on first login (I think this is what you mean by autogenerated?).

Maybe we should even write a migration which adds this to existing users?

**Comment by tristan-orourke** [comment]
@petertgiles Do you think a migration or Seeder makes more sense, for adding a role to all users already in the system?

**Comment by JamesHuf** [comment]
> In fact, ALL users should have this role.

If all users have this role what is it accomplishing? Couldn't we just check that a user is signed in?

**Comment by petertgiles** [comment]
> If all users have this role what is it accomplishing? Couldn't we just check that a user is signed in?

Technically, yes.  But there's a but of nuance here.

The validation logic gets a bit gnarly when you mix authentication (is the user who they say they are - logging in) and authorization (is the user allowed to do what they want to do).  GCKey is handling authentication but we are handling authorization so it's handy to separate these.

Having a separate role gives us a bit more flexibility, too.  For example, perhaps we want to not give autogenerated users the role and only assign it after they've completed the welcome page? (ref: https://github.com/GCTC-NTGC/gc-digital-talent/issues/2924#issuecomment-1142592557)  Perhaps we want to allow admins to opt-in to being an applicant?  Perhaps we will want to disable users by removing the roles (like if they lock their gckey or are inactive for a certain number of days)?

**Comment by petertgiles** [comment]
> @petertgiles Do you think a migration or Seeder makes more sense, for adding a role to all users already in the system?

Both?  I think we'll need a migration for existing users in prod and UAT and then update the seeder for fakes locally.  I'm not sure I'd want to update the existing users though.  Like I mentioned above, this would be a handy way to trigger the welcome screen on login https://github.com/GCTC-NTGC/gc-digital-talent/issues/2924 .
