### ISSUE TITLE
Discuss how to combine frontend projects

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2917]
# Description
Right now, admin, talentsearch and IAP are organized as separate npm projects. However, we have more and more need to share components between them. And soon, there may also be some navigation between them. It makes more sense now to frame them as a single app.

It may still make sense to keep a separate `common` folder to hold a component library which is less specific to the GC Talent app. It may helpful to frame it like so: anything we might want to reuse in the Accessibility Passport should go in the `common` folder.

## Acceptance Criteria

- [ ] Agree on a directory structure for the final project

**Comment by tristan-orourke** [comment]
Possibly we can just let projects import from each other, as a shortcut.

**Comment by esizer** [comment]
Just mulling things over, looking at our existing architecture they are fairly similar so simply merging them while keeping them pretty much the same should work.

## Proposed Architecture

```sh
frontend/
├── common
└── app/
    ├── .storybook
    ├── public/
    │   ├── images
    │   ├── .htaccess
    │   ├── config.sjs
    │   ├── index.html
    │   └── site.webmanifest
    ├── src/
    │   ├── css/
    │   │   └── app.css
    │   └── js/
    │       ├── api
    │       ├── components
    │       ├── context
    │       ├── hooks/
    │       │   └── use*Routes.ts
    │       ├── lang
    │       ├── pages
    │       ├── routes/
    │       │   └── Router.tsx
    │       ├── tests/
    │       │   └── coverage
    │       ├── types
    │       └── App.tsx
    ├── .babelrc
    ├── .browserslistrc
    ├── .env.example
    ├── .eslintrc
    ├── .gitattributes
    ├── .gitignore
    ├── .nvmrc
    ├── .prettierrc
    ├── .styleci.yml
    ├── codegen.yml
    ├── jest.config.js
    ├── LICENSE
    ├── package.json
    ├── README.md
    ├── tsconfig.json
    ├── webpack.base.js
    ├── webpack.dev.js
    └── webpack.prod.js
```

## Common

This would remain the same.

## App

This holds all of the actual application files and essentially merges `admin`, `talentsearch` and `indigenousapprenticeship` applications into a single directory.

### API 

Keep this pretty much the same while trying to move the `graphql` files to colocate them with where they are used.

### Components

This would be reworked to only include functional components and no longer be the place where page components live.

### Context (optional)

We do some prop drilling and it could be useful to utilize `React.createContext` a little more to prevent this. We could put our context and providers here.

### Hooks

We have a few hooks specific to the applications that could be moved here. This is mainly our route hooks that live in the project root.

### Lang

No change, this would simple contain our i18n `json` files.

### Pages

New directory that would contain page components used in the `Router.tsx` file.

### Routes

We could move the `Router.tsx` file here and split it up nested paths into their own files `applicantProfile`, `admin`, `directIntake`. Though, if we move to `react-router` they have better handling for [nested routes](https://reactrouter.com/docs/en/v6/getting-started/concepts#nested-routes) and we may not need to do this.

**Comment by petertgiles** [comment]
Brainstorming thread here: https://talent-cloud.slack.com/archives/CB424V61J/p1670440607411319
Discussion thread here: https://talent-cloud.slack.com/archives/CB424V61J/p1670610552790639
New epic with children here: https://app.zenhub.com/workspaces/gc-digital-talent-6092dc05157fa30010edaef9/issues/gctc-ntgc/gc-digital-talent/5065
