### ISSUE TITLE
Combine admin, talentsearch and IAP into one NPM project

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2918]
Implement the plan from #2917 

# UAC

- [ ] Before starting, have a plan for how to avoid a nightmare of merge conflicts.
- [ ] Avoid the nightmare of merge conflicts
- [ ] env constants and routing still all works
- [ ] images and css all served from a single folder
- [ ] This may require htaccess changes?

**Comment by esizer** [comment]
Should we:

1. Make epic including the issues @petertgiles created
2. Close this in favour of those issues

**Comment by petertgiles** [comment]
The epic I created is #5065.  I'll close this one.
