### ISSUE TITLE
Add login and register links to talentsearch nav bar (no modals)

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2921]
Our shared navbar on talentseach needs links to the new login and register pages.

[
![image](https://user-images.githubusercontent.com/8978655/171280213-5126b789-1b0d-4381-8eb4-42554624bfd7.png)
](https://www.figma.com/file/UDWAkiGXMt9YGbrfsuSzmr/Interface---Registration-and-login?node-id=6%3A2)

## User Acceptance Critera
- [ ] Can navigate to /[lang]/login-info
- [ ] Can navigate to /[lang]/register

**Comment by petertgiles** [comment]
@JoshBeveridge When a user is logged in does "login" change to "logout" and register disappears?

**Comment by JoshBeveridge** [comment]
@petertgiles Yep!

**Comment by patcon** [comment]
Ah, just found this trick in react-router example docs!

This circumvents the choice between login/register modal but having an accessible url directly there :) it's inspired by how Instagram and Pinterest do things:

When user clicks a login/register link, it opens a modal and pushes a new state to history BUT if that same path is refreshed (or visited directly) it is its own page.

(This is accomplishes with location state, like what allows form state to be returned to)

https://github.com/ReactTraining/react-router/blob/main/examples/modal/src/App.tsx#L131-L134

**Comment by tristan-orourke** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/2921?planning-poker) with ZenHub @petertgiles
