### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2922]
There will page to give a user context before logging in with GCKey.

## Screenshot
  [![screenshot](https://user-images.githubusercontent.com/8978655/171279029-453f188e-fb42-4e1c-96ef-a138915e77a2.png)](https://www.figma.com/file/UDWAkiGXMt9YGbrfsuSzmr/Interface---Registration-and-login?node-id=7%3A4)
<sup>[Click screenshot to visit Figma.](https://www.figma.com/file/UDWAkiGXMt9YGbrfsuSzmr/Interface---Registration-and-login?node-id=7%3A4)</sup>

## User Acceptance Critera
- [ ] Can navigate to /[lang]/login-info to view page
- [ ] When you click login, the post-redirect url should be the profile page
- [ ] Files created in talentsearch directory
- [ ] Cancel goes back to "/"
- [ ] Login starts login process

**Comment by petertgiles** [comment]
@JoshBeveridge We don't have a separate register URL.  Clicking register starts the login process as well?

**Comment by petertgiles** [comment]
@JoshBeveridge is the /[lang]/login URL confusing since our "start login process" URL is /login?

**Comment by patcon** [comment]
Ah, just found this trick in react-router example docs!

This circumvents the choice between login/register modal but having an accessible url directly there :) it's inspired by how Instagram and Pinterest do things:

When user clicks a login/register link, it opens a modal and pushes a new state to history BUT if that same path is refreshed (or visited directly) it is its own page.

(This is accomplishes with location state, like what allows form state to be returned to)

https://github.com/ReactTraining/react-router/blob/main/examples/modal/src/App.tsx#L131-L134

**Comment by tristan-orourke** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/2922?planning-poker) with ZenHub @RVany
