### ISSUE TITLE
Register Page

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2923]
There will be a page to give a user context before registering for GCKey.

[![image](https://user-images.githubusercontent.com/8978655/171276847-81824562-121a-467d-9891-8e77c01d5a16.png)](https://www.figma.com/file/UDWAkiGXMt9YGbrfsuSzmr/Interface---Registration-and-login?node-id=133%3A1144)

## User Acceptance Critera
- [ ] Can navigate to /[lang]/register to view page
- [ ] Post login redirect should be the welcome page
- [ ] Files created in talentsearch directory
- [ ] The three links on the page operate

**Comment by petertgiles** [comment]
Do we have separate links for log in and register?  Our GCKey landing page has both on the same page, right?

**Comment by tristan-orourke** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/2923?planning-poker) with ZenHub @vd1992
