### ISSUE TITLE
Welcome page (url: /create-account)

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2924]
When a user is auto-created they will arrive at this page to be given the opportunity to fill in their user record before using the site.

[![image](https://user-images.githubusercontent.com/8978655/171274055-fd208932-b0c4-42be-914f-b890322b1935.png)](https://www.figma.com/file/UDWAkiGXMt9YGbrfsuSzmr/Interface---Registration-and-login?node-id=0%3A1 
)

Acceptance Criteria
- [ ] Page can be navigated to at /create-account
- [ ] Files created in the talentsearch directory
- [ ] As much initial data is filled into the form as possible (maybe just preferred language?)
- [ ] A mutation saves the updates to the api and a successful save navigates to the user profile flow
- [ ] Form validation prevents incomplete form submission
- [ ] Government form elements only appear (and become required) when the user selects "Yes, I work with the government"

**Comment by petertgiles** [comment]
@JoshBeveridge If a user navigates here with a completed profile should we prefill the fields and allow them to use the page as an editor?  If not, how do we detect that?  Would we assign them the APPLICANT role when they fill this form and check for that?  Would we redirect them to the profiles flow then?

**Comment by JoshBeveridge** [comment]
@petertgiles Theoretically they shouldn't ever reach this page once it's completed. If they somehow did, I would imagine it would simply redirect to their profile, yes.

**Comment by tristan-orourke** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/2924?planning-poker) with ZenHub @yonikid15
