### ISSUE TITLE
EE Data profile edit page

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2927]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Description
Build the whole page.

## Screenshot: Prototype
[![a screenshot of ...][image]][image-link]
<sup>[Click screenshot to visit Figma.][image-link]</sup>

## Acceptance Criteria
- [ ] Each modal is its own form, which causes an API mutation when save is pressed
- [ ] EE data is not required, so this doesn't need to hook into isComplete status
- [ ] Page needs to load initial state, and show which selections are check, as well as pass state into modal forms
- [ ] In this case, Go Back button at bottom of page can simply be a link

   [image]: https://user-images.githubusercontent.com/3046459/171634039-d939b2f7-f97d-44d4-b128-74a8b6e4529d.png
   [image-link]: https://www.figma.com/proto/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?page-id=0%3A1&node-id=3139%3A4380&viewport=6038%2C-16292%2C0.78&scaling=min-zoom&starting-point-node-id=2340%3A4185
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by mnigh** [comment]
Screenshot from description in this issue is now out of date based on figma:

![Screen Shot 2022-06-02 at 08 51 22](https://user-images.githubusercontent.com/3046459/171634039-d939b2f7-f97d-44d4-b128-74a8b6e4529d.png)

**Comment by tristan-orourke** [comment]
If we can model this in the markup as a single checklist (with confirmation modals), that might be a lot easier for screen readers.

**Comment by patcon** [comment]
re checklist. one option is to have a hidden checkbox form group whose state is synchronized with the more complex elements of the component. But the checkbox has aria labels and the rest is ignored by screenreaders via aria attributes. React state is shared between checkbox and more complex visual representation.
