### ISSUE TITLE
Update text and styling on Diversity, Equity and Inclusion section of Applicant Profile

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2928]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Screenshot: Prototype
[![a screenshot of ...][image]][image-link]
<sup>[Click screenshot to visit Figma.][image-link]</sup>

## Acceptance Criteria
- [ ] Displays all EE and indigenous groups selected
- [ ] Shows null state when nothing selected
- [ ] Never shows Error state, since EE is not required
- [ ] ~~Shows indigenous community badge is selected~~

   [image]: https://user-images.githubusercontent.com/4313717/171267229-e168ccf5-b71b-4baf-849f-8d1c62158c06.png
   [image-link]: https://www.figma.com/proto/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?node-id=2340%3A4185&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=2340%3A4185
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by Jerryescandon** [comment]
Updated!!

![](https://files.slack.com/files-pri/T5ZFRSQ3V-F03HN4RM88N/figma_zbzceoce4b.gif)
