### ISSUE TITLE
Pool descriptions are inconsistently required

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#2929]
## Description

1. The description value is not required on the backend to create a pool, and is required on the frontend.
- `CreatePoolInput` **description** is not required: https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/api/graphql/schema.graphql#L831
- _Description (English)_ is required: https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/admin/src/js/components/pool/CreatePool.tsx#L212
- _Description (French)_ is required: https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/admin/src/js/components/pool/CreatePool.tsx#L224

2. The description value is not required on the backend to update a pool, and is required on the frontend.
- `UpdatePoolInput` **description** is not required: https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/api/graphql/schema.graphql#L870
- _Description (English)_ is required: https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/admin/src/js/components/pool/UpdatePool.tsx#L208
- _Description (French)_ is required: https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/admin/src/js/components/pool/UpdatePool.tsx#L220

## Possible Solutions

1. Force **description** in `CreatePoolInput` and `UpdatePoolInput` to be required so that the backend matches the frontend's validation rules.
2. Remove condition of required for a pool's **description** (some frontend conditional logic might need to be written).

**Comment by tristan-orourke** [comment]
Related: #2952

**Comment by mnigh** [comment]
@tristan-orourke since the `wontfix` label was added last year, should this be **closed as not planned**?

**Comment by tristan-orourke** [comment]
Sure. Closing as not planned.
