### ISSUE TITLE
Route validation (uuids)

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#2940]
Re-ticketed from https://github.com/GCTC-NTGC/gc-digital-talent/pull/2910#issuecomment-1143982917

> Not sure if in scope, but noticing this:
> 
> * Given that this exists:
>   ```
>   http://localhost:8000/en/talent/profile/skills-and-experiences/award/831aa53b-be38-47c9-b4d6-0c4bc12b2b99/edit
>   ```
> * I can switch the type, and render still happens: (empty fields)
>   ```
>   http://localhost:8000/en/talent/profile/skills-and-experiences/education/831aa53b-be38-47c9-b4d6-0c4bc12b2b99/edit
>   ```
>   <img width="1033" alt="Screen Shot 2022-06-01 at 2 42 53 PM" src="https://user-images.githubusercontent.com/305339/171479038-92be480d-1ae3-45cb-a920-472bf5b97a94.png">
>
> * I can switch the uuid, and render still happens: (empty fields)
>   ```
>   http://localhost:8000/en/talent/profile/skills-and-experiences/award/00000000-be38-47c9-b4d6-0c4bc12b2b99/edit
>   ```
>   <img width="1143" alt="Screen Shot 2022-06-01 at 2 42 35 PM" src="https://user-images.githubusercontent.com/305339/171479125-7be076b2-d1dc-4fe5-abc7-93105136d071.png">
>
> 
> There should be some redirect/warning when:
> 
> * uuid doesn't exist at all
> * uuid doesn't match type (or maybe "award" part of path is just ignored, and redirected appropriately, as rendering maybe should not happen based on type in path, but based on inferred type from uuid (e.g. technically this should be able to render the page just as well >>> http://localhost:8000/en/talent/profile/skills-and-experiences/831aa53b-be38-47c9-b4d6-0c4bc12b2b99/edit and the "type" in the path is just kinda "path sugar", like human-readable portion of reddit posts: https://www.reddit.com/r/worldnews/comments/uvts08/ => https://www.reddit.com/r/worldnews/comments/uvts08/biden_says_he_would_be_willing_to_use_force_to/

**Comment by tristan-orourke** [comment]
The page should be doing some kind of validation, throwing an error or maybe showing a 404 page if the uuid doesn't match an experience of the correct type.
