### ISSUE TITLE
Table Component - Changing sort order of table takes far too long

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#295]
# Description
When the sort order of a table is changed, it takes a very long time (many seconds) to re-render (at least for tables with more rows). The entire app is frozen during this time. According to a the Performance tab in the chrome inspector, the vast majority of this time is taken up by "Recalculating Style".

# Steps to Reproduce
1. Go to a table that has many rows (like Pool Candidates)
2. Click on a column header to sort by that column
3. Wait as the page freezes for several seconds, until table finishes rendering.

# Images
![Performance Analysis screenshot](https://images.zenhubusercontent.com/5d9ded8fd25901000101f3f0/1ad148db-5169-4862-8536-842af9925ac5)

**Comment by jaysonmc** [comment]
Cannot reproduce on Ubuntu, but others seem to be able to. After doing down the rabbit hole to run the server on my guest OS and access from my host, dragging back in to to-do for someone else who can reproduce it

**Comment by mnigh** [comment]
@jaysonmc I tried reproducing this again out of curiosity (I hadn't tried in a few weeks) and I don't see the slow re-render anymore. @tristan-orourke or @yonikid15, are you still experiencing slow re-renders?

**Comment by yonikid15** [comment]
@mnigh It's is not slow on my end, however we should implement pagination. Also, the styling needs work as well.

**Comment by yonikid15** [comment]
This issue can get closed now since it's not causing anyone trouble. It was so slow before due to the large hydrogen.css file, when it contained all the colors including every opacity from 0-1.
