### ISSUE TITLE
Client-side cross-site scripting

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#2993]
Codeql detected a medium severity vulnerability:

https://github.com/GCTC-NTGC/gc-digital-talent/security/code-scanning/10

**Comment by tristan-orourke** [comment]
We're confident this is a false positive, but don't want to see false positives...

**Comment by esizer** [comment]
This could work: https://pragmaticwebsecurity.com/articles/spasecurity/react-xss-part1.html
