### ISSUE TITLE
Bug - Edit Experience button missing

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#2994]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Description

When on the `/talent/profile/` page, if you filter "By Type" the accordions do not include the button to edit the experience.

## Screenshot

<img width="991" alt="Screen Shot 2022-06-07 at 2 34 25 PM" src="https://user-images.githubusercontent.com/4127998/172457285-2ba02bb0-ce85-4397-91c1-7e347143948f.png">

## Acceptance Criteria
- [ ] Edit Experience button appears when filtering by type

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by petertgiles** [comment]
Uh oh, did I break it in https://github.com/GCTC-NTGC/gc-digital-talent/pull/2967?

**Comment by esizer** [comment]
> Uh oh, did I break it in #2967?

No, @RVany and I noticed it last week and I forgot to create the issue 😓
