### ISSUE TITLE
IAP - Missing site icons

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#3000]
## Description

Missing the following site icons [referenced](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/indigenousapprenticeship/public/index.html#L8-L10):

- /indigenous-it-apprentice/images/apple-touch-icon.png (180x180)
- /indigenous-it-apprentice/images/favicon-32x32.png
- /indigenous-it-apprentice/images/favicon-16x16.png

**Comment by BrookeCameron** [comment]
Code:
`<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#781443">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">
`

[favicon_package_for_IAP.zip](https://github.com/GCTC-NTGC/gc-digital-talent/files/8928090/favicon_package_for_IAP.zip)

**Comment by BrookeCameron** [comment]
Let me know if you have any questions ^^

**Comment by BrookeCameron** [comment]
Revised code / link : 
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="192x192" href="/android-chrome-192x192.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#781443">
<meta name="msapplication-TileColor" content="#603cba">
<meta name="theme-color" content="#ffffff"> 
[IAP_favicon_package_R1.zip](https://github.com/GCTC-NTGC/gc-digital-talent/files/8942737/IAP_favicon_package_R1.zip)
