### ISSUE TITLE
DashboardContentContainer component inconsistently used

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#3014]
## Description
The `CmoAssetTable` component [uses](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/admin/src/js/components/cmoAsset/CmoAssetTable.tsx#L73) the `DashboardContentContainer` yet other similar table components, such as the `ClassificationTable` component, [do not](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/admin/src/js/components/classification/ClassificationTable.tsx#L102). This results in an inconsistent layout with components that use `DashboardContentContainer` having padding and ones that do not use `DashboardContentContainer` do not.

## Screenshots
![Screen Shot 2022-06-09 at 12 44 51](https://user-images.githubusercontent.com/3046459/172904750-57a2ab7a-b9d7-4263-a2bc-634578a95e39.png)
--
![Screen Shot 2022-06-09 at 12 45 07](https://user-images.githubusercontent.com/3046459/172904755-2e131bcf-75f1-4bc1-8973-0a0234fdefaa.png)

**Comment by mnigh** [comment]
Referenced in a previous PR: https://github.com/GCTC-NTGC/gc-digital-talent/pull/2957#issuecomment-1147744149

**Comment by gobyrne** [comment]
Visually fixed in #3051 but not functionally
