### ISSUE TITLE
Refactor routing to use React-Router

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3017]
Discussion in #2368 

Things to think about:
- [ ] recreate role-based authorization we already have
- [ ] ~~Deep-linking modals and tabs~~

## Acceptance Criteria
- [ ] Our universal-router Router helper functions and hooks are deleted
- [ ] routing continues to work the same from a user perspective
- [ ] role-based authorization continues to work the same from a user perspective

**Comment by tristan-orourke** [comment]
Great resources in this comment https://github.com/GCTC-NTGC/gc-digital-talent/issues/3533#issuecomment-1244988917

**Comment by patcon** [comment]
- #todo maybe create e2e test that navigates to each page to see if exists
