### ISSUE TITLE
Create an email for support emails

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3049]
We need a mailbox which will auto-forward all emails to ________

Marco from GCX or Po from cybersecurity may be able to help us with this.

## To Do

- [x] talk to Rosita to get access to ~~`talent.cloud-nuage.de.talents@tbs-sct.gc.ca`~~ `GCTalentGC@tbs-sct.gc.ca`
- [x] talk to Gray about how inbox will be used (to know whether we need another)
- [x] talk to Marco Saad at GCX
  - confirmed that fwd'ing is possible for @tbs-sct.gc.ca emails via IMTD
  - [x] send freshdesk fwd'ing email to Marco -- patcon
    - `dGJzLXNjdGdjY2FnY3RhbGVudGdjQGNkZWdyYXNzLmZyZXNoZGVzay5jb20K`
  - [x] find email with MX record instructions to allow "send as" from Freshdesk -- Marco
  - [x] submit request to contacts at IMTD -- Marco
  - [x] send followup -- @patcon WED JUN 22
    - marco replied. not possible to give timeline
  - [x] send followup -- @patcon WED JUN 29
    - marco replied. still working on it
  - [x] send followup -- @patcon WED JUL 6
  - [x] followup after Marco's TUE JUL 12 meeting with IMTD -- @patcon
  - [x] **create email forwarding with IMTD** 🎉 -- Marco
- [x] request fwding destination email from Marc D'Onofrio (non-public, don't post here)
  - ~~`blocked` on confirmation that fwd'ing possible from our email~~
  - waiting
- potential
  - [ ] set up slack channel (`#freshdesk-support`?)
  - [ ] add incoming email integration
  - [ ] give email to Marc
  - [ ] invite developers into channel and explain purpose

**Comment by patcon** [comment]
Quick convo with Tristan:
- Marc D'Onofrio is managing our help desk
- we need to set up an email to fwd to their freshdesk
- the email should be minimally accessible, ideally no more access that the developers
  - ideally it should delete email after forwarding
  - to confirm: the inbox does not need to be checked or managed directly
- options
  - create new email. contact either Po Tea-Duncan from Cybersecurity, or 
  - repurpose existing email: `talent.cloud-nuage.de.talents@tbs-sct.gc.ca`. Rosita has already set up an email, in our talent.canada.ca footer behind "Feedback" link.
- relevant people (msg on MS Teams)
  - Po Tea-Duncan, Cybersecurity. set up email inbox for us before.
  - Marc Saad, GCXchange. set up email inbox for us before.
  - Rosita. internally coordinated 

**Decision:** Set up the existing email `talent.cloud-nuage.de.talents@tbs-sct.gc.ca` to fwd to `xxxxx@cdegress.freshdesk.com` (will be provided).

## To Do

- [ ] talk to Rosita to get access to `talent.cloud-nuage.de.talents@tbs-sct.gc.ca`
- [ ] get fwding destination email from Marc D'Onofrio (non-public, don't post here)
- [ ] set up forwarding
- [ ] set up auto-deletion from inbox
- maybe
  - [ ] set up slack channel (`#freshdesk-support`?)
  - [ ] add incoming email integration
  - [ ] give email to Marc
  - [ ] invite developers into channel and explain purpose

**Comment by patcon** [comment]
Marco call
- steps for them to set up fwd'ing
  - created new mailbox support@gcx.gc.ca in their "tenant" (not possible for us)
  - created fwding rule, so anything sent to that mailbox would auto-direct to freshdesk mail address
- Marco is confident that fwd'ing can be set up via IMTD, so will msg on our behalf
- has a past email that documents how to set up "send as" within MX record for freshdesk

**Comment by mnigh** [comment]
@tristan-orourke @patcon any estimate for this issue?

**Comment by patcon** [comment]
@mnigh i think it's set at 3, no? Or do you mean something else?

**Comment by mnigh** [comment]
> @mnigh i think it's set at 3, no? Or do you mean something else?

yep, it's now set to `3` (the estimate was set afterward my comment, see timeline of the issue).

**Comment by patcon** [comment]
Marco confirmed that he's setting up our `gctalentgc@tbs-sct.gc.ca` support inbox like so:
- auto fwd to our unique freshdesk incoming email
- delete message daily

there are some VPN and summer vacation delays at IMTD where his contact is, but it has his active attention.

**Comment by patcon** [comment]
sent another followup to Marco last wed, June 30. No update, but he said he'll be in touch.

I'll followup every wednesday, I guess

**Comment by patcon** [comment]
Messaged marco again, and he has a meeting tomorrow with IMTD that he hopes will push things fwd :tada:

**Comment by patcon** [comment]
This is technically done, but I'll followup with @gobyrne to see if there's any role for having help desk fwd things to Slack for the team to have insight into the support request stream
