### ISSUE TITLE
Storybook - first-child is potentially unsafe.

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3062]
Observed in storybook, in the common project:
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/9a5aab02-3e38-4c56-9baa-6c594c9843b9)

**Comment by mnigh** [comment]
There are only two references to the pseudo class `:first-child` in the codebase and neither are part of the Button component but rather the Dialog component's css: https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/common/src/components/Dialog/dialog.css#L48,L49

In any case, this seems to be an issue with the version of storybook (v6.4.16) we are currently using, as well as some other versions of storybook:
- https://github.com/storybookjs/storybook/issues/6998
- https://github.com/storybookjs/storybook/issues/18103

### Solution
Upgrade to [v6.5.8](https://github.com/storybookjs/storybook/issues/6998#issuecomment-1151876307)

**Comment by vd1992** [comment]
I'll just stick a 1 on it
