### ISSUE TITLE
Loading spinner is drawn on top of elements it blends with

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#3088]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

Minimally urgent, as affects an uncommon window size.

## Description

When the window height is low, but width is high, the spinner can be drawn on top of the header elements, and it blends:

<img width="405" alt="Screen Shot 2022-06-16 at 1 32 04 PM" src="https://user-images.githubusercontent.com/305339/174137682-d5047273-1451-46c8-b5fa-828ba8122b8e.png">

Screencap: https://recordit.co/mdzN1RcqwQ

## Options

1. constrain loader within section being loaded, so background will be more knowable, or
2. add a background element behind loader, either transparent or opaque so it will always be visible

I personally think number two is best, since eric went to effort to make it work full-page.

## Acceptance Criteria
- [ ] spinner is visible over whatever element might show on page

   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by tristan-orourke** [comment]
Eric: there's supposed to be a white background which covers the screen, but it seems to be not working right.
