### ISSUE TITLE
Government Information Form not redirected to profile page after submitting the form

### ISSUE THREAD

**Issue by RVany** [GCTC-NTGC/gc-digital-talent#3104]
https://user-images.githubusercontent.com/95497896/174168690-e0df83c6-de3e-4dd1-997e-610552209b2b.mp4

**Comment by vd1992** [comment]
I think I can see why
https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/talentsearch/src/js/components/GovernmentInfoForm/GovernmentInfoForm.tsx#L499

the redirect is nested in the conditional  `res.isProfileComplete`

**Comment by patcon** [comment]
Off-hand, this might be captured in #3084 after merge, but if not, bonus would be a cypress test :)
