### ISSUE TITLE
Add new fields to PoolCandidateFilter

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3106]
## Description

We want to add new fields to PoolCandidateFilter so that it can store requests made on the new Talent Search page
New fields:
- skills
- wouldAcceptTemporary

At the same time, we want to ensure the countPoolCandidates and countApplicants query accept the same object, so that we can migrate everything to using countApplicants without losing backwards compatibility for our requests. To that end, we should remove the ApplicantFilterInput type and use PoolCandidateFIlterInput in both queries. 

In addition to adding the skills and wouldAcceptTemporary fields to PoolCandidateFIlter (and PoolCandidateFilterInput), we need to port over some other fields added to ApplicantFilterInput:

There may be some frontend refactorings to accommodate some name changes from ApplicantFilterInput to PoolCandidateFilterInput:
- poolCandidates -> pools
- expectedClassifications -> classifications
- locationPreferences -> workRegions
- poolCandidates -> pools

There will be some work required to make the `pools` field accomodate the expiryStatus and Status fields. I think this can be done by:
- refactoring UserPoolFilterInput to use a single pool id instead of an array of ids 
- replacing fields of UserPoolFilterInput with and array of UserPoolFilterInput
- replacing instances of ApplicantPoolFilterInput with UserPoolFilterInput
- adding the expiryStatus and statuses fields to the `pool_pool_candidate_filter` pivot table
- We can accomodate @petertgiles desire for as-unfiltered-as-possible defaults, without hurting backwards compatibility, if we use our current schema defaults as database defaults when adding columns in a migration

We can also add a jobLookingStatus to the PoolCandidateFilter, and we can remove the schema defaults if we use good defaults in the migration.

## Acceptance Criteria
- [ ] Add fields to PoolCandidateFilter model. Skills will be a relationship. UserPoolFilterInput data comes from the pivot table.
- [ ] Add new fields in migration. Skills requires a pivot table.
- [ ] Ensure default values are set in migration in order to retain backwards compatibility. ie after migrating candidate data to users (#3148) passing old PoolCandidateFilterInputs to countPoolCandidates and countApplicants should return the same number!
- [ ] Add fields to schema. (types, queries, and migrations)
- [ ] Refactor UserPoolFilterInput to work with `pool_pool_candidate_filter` pivot table
- [ ] Replace uses ApplicantPoolFilterInput with PoolCandidateFilterInput
- [ ] Remove ApplicantPoolFilterInput

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by tristan-orourke** [comment]
Hey @petertgiles @JamesHuf, after some discussion with @vd1992, and taking a look at #3116, I think I see a better way to combine some similar types in our schema, get to the kind of unbiased defaults peter's been advocating for, and retaining good continuity and backwards compatibility as we switch from countPoolCandidates to countApplicants. Please take a look at the new iteration of this issue and let me know what you think.

**Comment by vd1992** [comment]
I sorta feel like there is a bit too much going on for one issue

**Comment by tristan-orourke** [comment]
After discussion with @petertgiles, replacing this issue with a slightly simpler #3256
