### ISSUE TITLE
Welcome Page does not redirect to profiles

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3113]
After completing the welcome page the user is redirected back to the same welcome page.  They should be redirect to the profiles page.

https://images.zenhubusercontent.com/364642496/b3772a1a-d130-4dc8-af04-3106e0d004a4/simplescreenrecorder_2022_06_17_14_38_47.mp4

**Comment by mnigh** [comment]
@tristan-orourke any estimate for this issue?
