### ISSUE TITLE
IAP - Adjust copy in French logo

### ISSUE THREAD

**Issue by BrookeCameron** [GCTC-NTGC/gc-digital-talent#3131]
# **REQUIREMENTS**

- [x] @gobyrne approve French copy 

## ☑ What needs to get done?

- [x] Adjust the current logo with copy in the current French IAP hero image to the attached svg. 

## 📷 Where this change is happening: 
<img width="1346" alt="Screen Shot 2022-06-20 at 2 02 15 PM" src="https://user-images.githubusercontent.com/100953238/174658465-0300ba60-874d-444b-a65b-50098b6fa184.png">

## 📁 File: 
![IT Apprenticeship Logo Horizontal FR White_R1_ Horizontal FR White](https://user-images.githubusercontent.com/100953238/174659759-47a209f6-f1fa-4989-9f93-5df905e2325d.svg)

**Comment by mnigh** [comment]
do you approve the French copy, @gobyrne?

the SVG linked in the description is white text, so it will appear as white on white in the description of this issue. here it is black on white in case you missed it:
![Screen Shot 2022-06-20 at 16 26 25](https://user-images.githubusercontent.com/3046459/174673474-bd053812-1b01-49b8-9cf3-09d70b9485fd.png)

**Comment by BrookeCameron** [comment]
@mnigh Copy has been approved by Gray

**Comment by mnigh** [comment]
@BrookeCameron I noticed that the updated French logo image no longer has the subtitle text that the English logo still has. Is this on purpose? If not, could you send another version of the French logo with the subtitle text? Thanks!

### Screenshots
<img width="1552" alt="Screen Shot 2022-06-24 at 09 36 34" src="https://user-images.githubusercontent.com/3046459/175547753-7506e452-8885-498b-b001-67122625dd32.png">

<img width="1552" alt="Screen Shot 2022-06-24 at 09 36 27" src="https://user-images.githubusercontent.com/3046459/175547759-82cb19f7-b3b3-41cf-9843-937a8e307bd1.png">

**Comment by BrookeCameron** [comment]
📷 screen shot of file on dark background for reference:

<img width="926" alt="Screen Shot 2022-06-24 at 10 02 33 AM" src="https://user-images.githubusercontent.com/100953238/175552464-a351a0e1-a595-409f-a3f3-036324d4a28a.png">

📁 File:
![IAP_Logo_Horizontal_FR_White_with_tagline](https://user-images.githubusercontent.com/100953238/175552322-44405678-51fa-4ea3-9379-927b7cec1b34.svg)
