### ISSUE TITLE
TC Report - Variable not enclosed in double curly braces 

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#3138]
## Description
Accordion variable not enclosed in double curly braces and therefore not parsed:
- https://github.com/GCTC-NTGC/tc-report/blob/main/_includes/accordion.html#L50
- https://github.com/GCTC-NTGC/tc-report/blob/main/_includes/accordion.html#L58

## Acceptance Criteria
- [ ] remove title attribute from accordion

**Comment by mnigh** [comment]
### Possible Solution
Change 
`title="post.linkTitle"` to
`title="{{ post.linkTitle }}"`

**Comment by tristan-orourke** [comment]
Duplicate of #3099
