### ISSUE TITLE
Explore Azure B2C options with IMTD

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3140]
# Description
We're now interested in using Azure B2C as our authentication broker, instead of connecting directly to Sign-in Canada/GCKey. We experimented with this in #2148. We need to communicate with IMTD to find out whether they can set up a B2C tenant for us, and that processes will be required.

**Comment by patcon** [comment]
@petertgiles -- meeting iwth tristan and gray. we're pretty interested.

going to check with anthn and certification folks to. if it's used in other places and can do easily, they'd be down for it.

**Comment by tristan-orourke** [comment]
Marco handled following up with IMTD with this. It sounds like this is still an option in the future, but no way IMTD could set up a tenant for us by August, when we want to go live with Direct Intake. That means we'll definitely have external users by that point, and will need to solve #3203 before moving forward.
