### ISSUE TITLE
user table sort not functioning correctly

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#3146]
## Description
for the users table in /admin
sorting the "email" and "language" columns does not function as expected

https://recordit.co/xUvfALEFpC

Solution: For any table accessors for which we modify the value, or wrap it in JSX, provide a sortBy value as well.

## Acceptance Criteria
- [ ] fix sorting of columns

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by tristan-orourke** [comment]
For the users table, wait for the rebuild to finish.
