### ISSUE TITLE
Migrate PoolCandidate data to User model

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3148]
## Description
Write a migration which copies data from existing PoolCandidates to the corresponding User object.

Copy the following fields:
- isWoman
- hasDisability
- isIndigenous
- isVisibleMinority
- hasDiploma
- languageAbility
- locationPreferences
- acceptedOperationalRequirements
- expectedSalary
- expectedClassifications
- cmoAssets

Note that some of these may require creating new rows in pivot tables.

## Acceptance Criteria
- [ ] After running this migration, any data in existing PoolCandidates which has a corresponding field in the User model is copied to the candidate's User model.

**Comment by vd1992** [comment]
the blocker for this was split here https://github.com/gctc-ntgc/gc-digital-talent/issues/2460#issuecomment-1184591727

so I feel this is still blocked by the issues it was split into, #3345 and #3347

**Comment by vd1992** [comment]
I feel resolving #3345 is essential before progressing on this

**Comment by vd1992** [comment]
as for the migration itself

```
isWoman
hasDisability
isIndigenous
isVisibleMinority
hasDiploma
languageAbility
locationPreferences
acceptedOperationalRequirements
acceptedSalary
```
exist on table `users`

```
expectedClassifications
cmoAssets
```

tables `cmo_asset_user` and `classification_user` exist 

the stuff on the former would require the edit of each row 
the stuff on the latter would involve adding new rows connecting an id from a user to an id for a asset/classification

**Comment by brindasasi** [comment]
it looks like we wouldn't unblock this issue in the current sprint **Sprint: Aug 11 - Aug 24, 2022**  Should we put this back into product backlog ?

**Comment by vd1992** [comment]
no I don't think so, it has a PR attached that is basically good to go and be merged
product backlog doesn't feel like the right place
