### ISSUE TITLE
Edit Pool page - Readonly

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#3162]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Description

*This first issue is to create a readonly version of the page - data is populated from the database but all the action buttons do nothing.  Mutations implemented in #3169*

This page contains an editable form for the information in the pool model.
This page also contains buttons that open modals to change the "Status" of this pool. Which in turn changes the behavior of the Pool Advertisement page.

If the pool status is in DRAFT, you can SAVE, PUBLISH, or DELETE.
If the pool status is PUBLISHED (Active before "Closing Date") you can CLOSE or EXTEND THE DATE.
If the pool status is PUBLISHED (Expired after "Closing Date") you can EXTEND THE DATE or ARCHIVE.

NOTE 01: GENERIC CLASSIFICATION: Leave out this dropdown selector from this issue, it will be addressed at a later point.

NOTE 02: DATE PICKER (yyyy/mm/dd): Date will always be set in Pacific Time at 11:59:59 p.m. (probably handled in the backend mutation) 

NOTE 03: We are not gonna implement "ARCHIVE" yet, just leave the button in but it won't do anything yet.

NOTE 04: CLASSIFICATION PICKER (e.g. IT-01): Front-end will be a 1 selection only (dropdown), but back end will allow multiple selections (just in case we need to allow this down the line). 

## Screenshot: Prototype
![image](https://user-images.githubusercontent.com/16977254/175546064-43c2c3d9-3d57-42dd-88f3-f41fd0112329.png)

## Acceptance Criteria
- [ ] URL "https://talent.canada.ca/en/admin/pools/[ID]/Edit" (Discuss what happens to old one)
- [ ] Create whole form, query for data, no actions taken on button clicks
- [ ] Put behind feature flag "Direct Intake"
- [ ] All modals need to work 
- [ ] Page needs to behave in different way depending on status (Draft, Published (Active), Closed (Published and Expired)

[Link to Edit Pool Advertisement wireframe](https://www.figma.com/proto/b6lDM86QCJQ6iaAh7qrTYH/Admin-v4-(Direct-Intake)?page-id=0%3A1&node-id=1618%3A6064&viewport=-3442%2C1747%2C0.59&scaling=min-zoom&starting-point-node-id=1618%3A6064)

**Comment by Jerryescandon** [comment]
> Do you want to table of contents titles to exactly match the content titles or do you want short forms there?

Mother Fathers!! I forget to update that lil' index every single time. Just use the full titles on each section.

**Comment by petertgiles** [comment]
Hi @Jerryescandon 
Could you please provide the copy for the other statuses?

| Status    | Description                            |
|-----------|----------------------------------------|
| Draft     | This pool has not been advertised yet. |
| Published | ?                                      |
| Expired   | ?                                      |

**Comment by petertgiles** [comment]
Thanks @Jerryescandon , followup question - icons?
| Status    | Description                                                                     | Icon   |
|-----------|---------------------------------------------------------------------------------|--------|
| Draft     | This pool has not been advertised yet.                                          | Pencil |
| Published | This pool is currently being advertised and open to receiving new applications. | ?      |
| Expired   | This pool is being advertised but no longer accepting applications.             | ?      |
| Archived  | This pool is no longer advertised.                                              | ?      |

**Comment by Jerryescandon** [comment]
Published > Speakerphone
Expired > Lock closed
Archived > Folder-open

**Comment by petertgiles** [comment]
@Jerryescandon would you be OK if the publish and close dialogs shared the same format as the view pool page?
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/300ac75c-0f87-40f0-8d2d-064939291a47)
So it would look like this:
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/2d6bee05-cf8a-483d-8896-66d0ba29bc88)
