### ISSUE TITLE
New Pool page

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#3163]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Description
New pool page is an intermediary page that creates new pools based on a couple of required selections. (Classification, Job Title/Stream/Generic????)

This will later on be used to host templates for pools that include pre selected skills and work tasks based on job titles **_(Not relevant to this sprint)._** 

## Screenshot: Prototype
![image](https://user-images.githubusercontent.com/16977254/175389136-9024f6d1-a48c-419c-942b-fe20eebc1cdf.png)

## Acceptance Criteria
- [ ] URL "https://talent.canada.ca/en/admin/pools/create"
- [ ] Put behind feature flag "Direct Intake"
- [ ] User creating the pool becomes pool owner by default
- [ ] After new pool is created, user is navigated to the Edit Pool page
- [ ] Cypress test that user gets navigated to next page after submission

[Wireframe for this bad boy](https://www.figma.com/proto/b6lDM86QCJQ6iaAh7qrTYH/Admin-v4-(Direct-Intake)?page-id=0%3A1&node-id=1656%3A5731&viewport=-3442%2C1747%2C0.59&scaling=min-zoom&starting-point-node-id=1618%3A6064)

**Comment by tristan-orourke** [comment]
For now: Just a Group and Level classification field. Ignore "stream" or "generic".

Also, no key field.
