### ISSUE TITLE
Public Facing Pool Advertisement

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#3164]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Description

A fancy looking version of the pool information, It shows how the information will be perceived by applicants. It is the same URL regardless of the "status" of the pool.

- if pool status is DRAFT/ARCHIVED, link will be visible only to Admin users.
- if pool status is PUBLISHED/CLOSED, link will be visible to everyone.
- if pool status is CLOSED "Apply" buttons will be disabled.
- if pool status is CLOSED "Days remaining" will display closed for submissions message.
- if pool status is PUBLISHED and they hit "Apply" and will be redirected to URL ".../pools/[ID]/apply"

IT level descriptions

### What does IT-01 Technician mean?

```
Technicians (IT-01) provide technical support in the development, implementation, integration, and maintenance of service delivery to clients and stakeholders.

IT Technicians are primarily found in three work streams:
IT Infrastructure Operations
IT Security
IT Software Solutions
```

### What does IT-02 Analyst mean?

`Analysts (IT-02) provide technical services, advice, analysis, and research in their field of expertise to support service delivery to clients and stakeholders. IT analysts are found in all work streams.`

### What does IT-03 Team Lead mean?

```
There are two types of IT-03 employees: those following a management path, and individual contributors.
 Management path: IT Team Leads (IT-03) are responsible for supervising work and project teams for IT services and operations in their field of expertise to support service delivery to clients and stakeholders. IT Team Leads are found in all work streams.
```

### What does IT-03 Technical Advisor mean?

```
There are two types of IT-03 employees: those following a management path, and individual contributors.

Individual contributor: IT Technical Advisors (IT-03) provide specialized technical advice, recommendations and support on solutions and services in their field of expertise in support of service delivery to clients and stakeholders. IT Technical Advisors are found in all work streams.
```

### What does IT-04 Manager mean?

```
There are two types of IT-04 employees: those following a management path, and individual contributors.

Management path: IT Managers (IT-04) are responsible for managing the development and delivery of IT services and/or operations through subordinate team leaders, technical advisors, and project teams, for service delivery to clients and stakeholders. IT Managers are found in all work streams.
```

### What does IT-04 Senior Advisor mean?

```
There are two types of IT-04 employees: those following a management path, and individual contributors.

Individual contributor: IT Senior Advisors provide expert technical advice and strategic direction in their field of expertise in the provision of solutions and services to internal or external clients, and stakeholders. IT Senior Advisors are primarily found in six work streams:

IT Infrastructure Operations
IT Security
IT Software Solutions
IT Database Management
IT Enterprise Architecture
IT Project Portfolio Management
```

## Screenshot: Prototype
![image](https://user-images.githubusercontent.com/16977254/175394894-afab9368-c99e-493f-b468-cdea086a8f94.png)

[Figma prototype](https://www.figma.com/proto/b6lDM86QCJQ6iaAh7qrTYH/Admin-v4-(Direct-Intake)?page-id=0%3A1&node-id=1928%3A3809&viewport=1325%2C4564%2C0.47&scaling=min-zoom&starting-point-node-id=1618%3A6064)

### Closing date message

The closing date message changes styling and copy depending on how close TODAY date is to CLOSING date, here are the rules:

- If TODAY is > CLOSING then the message is: "The deadline for submission has passed"
- or If TODAY is < CLOSING and > (CLOSING - 24 hrs) then: "Closes Today at 11:59 p.m. PST"
- or If TODAY is < CLOSING and > (CLOSING - 48 hrs)  then: "Closes Tomorrow at 11:59 p.m. PST"
- or if TODAY is < CLOSING and > (CLOSING - 72hrs)  then: "Closes in " + n + " days"

![image](https://user-images.githubusercontent.com/16977254/176232188-3f78cd29-0c7d-4a77-bc64-9e9607baa94b.png)

## Acceptance Criteria
- [x] URL "https://talent.canada.ca/en/admin/pools/[ID]/view" (???)
- [x] Put behind feature flag "Direct Intake"
- [ ] Page needs to behave in different way depending on status (Draft, Published (Active), Closed (Published and Expired)
- [ ] Cypress testing for viewing the page as different users in different states
- [x] Jest tests for the date showing correctly, and for content appearing correctly (eg skills)

**Comment by petertgiles** [comment]
Note about expiry date: https://github.com/GCTC-NTGC/gc-digital-talent/pull/3225#discussion_r914216232

**Comment by esizer** [comment]
Correct me if I"m wrong but, should this be placed under `/talent/` and not `/admin/` since it is a public facing page?

**Comment by esizer** [comment]
What should the differences be for each user viewing this? Do admins see different view than applicants?

RE: Cypress testing for viewing the page **_as different users_** in different states

**Comment by tristan-orourke** [comment]
> Correct me if I"m wrong but, should this be placed under /talent/ and not /admin/ since it is a public facing page

Yes that’s right

**Comment by tristan-orourke** [comment]
Okay, it’s not exactly that the page will look different to different users, it’s that if the status is DRAFT or ARCHIVED the page should be inaccessible (404?) to non admins.

**Comment by esizer** [comment]
> Okay, it’s not exactly that the page will look different to different users, it’s that if the status is DRAFT or ARCHIVED the page should be inaccessible (404?) to non admins.

Thanks! This makes sense

**Comment by Jerryescandon** [comment]
Added IT descriptions
