### ISSUE TITLE
Pool Advertisements - Backend Readonly

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3166]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>

## Pool Advertisements - Backend Readonly

Some changes to the backend model will need to be implemented to support the new pool advertisement pages.  New queries will need to be created.

[Link to Edit Pool Advertisement wireframe](https://www.figma.com/proto/b6lDM86QCJQ6iaAh7qrTYH/Admin-v4-(Direct-Intake)?page-id=0%3A1&node-id=1618%3A6064&viewport=-3442%2C1747%2C0.59&scaling=min-zoom&starting-point-node-id=1618%3A6064)

- Only creating models, seeders, and a query are in scope for this issue - mutations will be added in #3169
- Generic classification has not be settled on and is not in the scope for this issue.
- Pool Advertisements have a derived status that should be returned in the query
- Even though the wireframe shows that the Pool Advertisement is associated to a single Classification we want to implement it with a many-to-many relationship on the backend.

| IsPublished | now < ExpiryDate | AdvertisementStatus |
|-------------|------------------|---------------------|
| F           | F                | DRAFT               |
| F           | T                | DRAFT               |
| T           | F                | PUBLISHED              |
| T           | T                | EXPIRED             |

- Expiry date has time and timezone component

## Big Questions
- Will the new fields for pool advertisements be integrated into the existing model or will a separate model be created?
- If a new model, is it a one-to-one relationship with pools or one-to-many?

Answer: We should define a new type in the schema, PoolAdvertisement, which uses the same underlying Model but exposes only the fields which should be visible to the public. We can then create new queries for PoolAdvertisements which, unlike for Pools, don't need to be restricted to Admins. (This is exactly what we did with Users and Applicants.)

## Acceptance Criteria
- [x] Model updates
- [x] Seeders/factories
- [x] Changes top existing type in schema
- [x] Query for PoolAdvertisements which doesn't have role restrictions
- [x] Derived advert status based on isPublished and expiry date

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by tristan-orourke** [comment]
AdvertisementStatus can be implemented as a Laravel "accessor" on the model

**Comment by vd1992** [comment]
@petertgiles @Jerryescandon 
I cannot view the Wireframe 

![image](https://user-images.githubusercontent.com/40485260/177199479-a5cb93d6-e953-44a2-9f2f-3f84bd72237c.png)

**Comment by Jerryescandon** [comment]
> I cannot view the Wireframe

Fixed the share settings, try it now.

**Comment by vd1992** [comment]
> > I cannot view the Wireframe
> 
> Fixed the share settings, try it now.

All good now, thanks!
