### ISSUE TITLE
Pool Advertisements - Backend Mutations

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3168]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>

## Pool Advertisements - Backend Mutations

Some changes to the backend model will need to be implemented to support the new pool advertisement pages.  Mutations will also need to be created.

- ARCHIVE is not included in this sprint

## Acceptance Criteria
- [x] Mutation for creating a pool advertisement [Wireframe for this bad boy](https://www.figma.com/proto/b6lDM86QCJQ6iaAh7qrTYH/Admin-v4-(Direct-Intake)?page-id=0%3A1&node-id=1656%3A5731&viewport=-3442%2C1747%2C0.59&scaling=min-zoom&starting-point-node-id=1618%3A6064)
- [x] Mutations for editing parts of a pool advertisement [Link to Edit Pool Advertisement wireframe](https://www.figma.com/proto/b6lDM86QCJQ6iaAh7qrTYH/Admin-v4-(Direct-Intake)?page-id=0%3A1&node-id=1618%3A6064&viewport=-3442%2C1747%2C0.59&scaling=min-zoom&starting-point-node-id=1618%3A6064)
- [x] Mutation for pool advertisement actions (publish, extend, etc)
- [x] Expiry date for "CREATE" has time of 23:59:59 Pacific Time
- [x] CREATE action sets pool owner to current user
- [x] "Close" action sets expiry date to "now"
- [x] Mutations are checking logic and returning user-viewable errors
  - [x] All mutations are ADMIN only
  - [x] Can only publish if in draft, all fields filled, expiry date in the future
  - [x] Can only delete if in draft

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by tristan-orourke** [comment]
It may make sense to handle the status changes with individual mutations, connected to their own methods on the model.
