### ISSUE TITLE
Edit Pool page - Mutations and Testing

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3169]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Description

*This second issue is to implement all the actions and add testing.*

This page contains an editable form for the information in the pool model.
This page also contains buttons that open modals to change the "Status" of this pool. Which in turn changes the behavior of the Pool Advertisement page.

If the pool status is in DRAFT, you can SAVE, PUBLISH, or DELETE.
If the pool status is PUBLISHED (Active before "Closing Date") you can CLOSE or EXTEND THE DATE.
If the pool status is PUBLISHED (Expired after "Closing Date") you can EXTEND THE DATE or ARCHIVE.

NOTE 01: GENERIC CLASSIFICATION: Leave out this dropdown selector from this issue, it will be addressed at a later point.

NOTE 02: DATE PICKER (yyyy/mm/dd): Date will always be set in Pacific Time at 11:59:59 p.m. (probably handled in the backend mutation) 

NOTE 03: We are not gonna implement "ARCHIVE" yet, just leave the button in but it won't do anything yet.

NOTE 04: CLASSIFICATION PICKER (e.g. IT-01): Front-end will be a 1 selection only (dropdown), but back end will allow multiple selections (just in case we need to allow this down the line). 

## Screenshot: Prototype
![image](https://user-images.githubusercontent.com/16977254/175546064-43c2c3d9-3d57-42dd-88f3-f41fd0112329.png)

## Acceptance Criteria
- [x] Implement all actions in the buttons with API mutations
- [x] Page needs to behave in different way depending on status (Draft, Published (Active), Closed (Published and Expired)
- [ ] Appropriate automated testing (Jest?  Cypress?)

[Link to Edit Pool Advertisement wireframe](https://www.figma.com/proto/b6lDM86QCJQ6iaAh7qrTYH/Admin-v4-(Direct-Intake)?page-id=0%3A1&node-id=1618%3A6064&viewport=-3442%2C1747%2C0.59&scaling=min-zoom&starting-point-node-id=1618%3A6064)

**Comment by tristan-orourke** [comment]
Lets test state transitions and save buttons with Cypress tests.
