### ISSUE TITLE
Remove redundant routes to profile page

### ISSUE THREAD

**Issue by JamesHuf** [GCTC-NTGC/gc-digital-talent#3192]
We currently have three routes for the profile page but only need one. We should remove the ones for `talentSearchRoutes.profile()` and `applicantProfileRoutes.profilePage()`

## Acceptance Criteria
- [ ] Routes for `talentSearchRoutes.profile()` and `applicantProfileRoutes.profilePage()` are removed.
- [ ] References to `talentSearchRoutes.profile()` and `applicantProfileRoutes.profilePage()` are replaced with `applicantProfileRoutes.home()`

**Comment by mnigh** [comment]
@JamesHuf any estimate for this issue?
