### ISSUE TITLE
API Server - Determine data model for Candidate Search Requests

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#32]
# Description
When a manager submits a request for candidates that match a set of filters, that request should be recorded in the database. It must record the set of filters used, the manager's government email, and some more data TBD.

Determine the exact shape of this data for storage, and add it to the GraphQL schema.
Also add tables to db and define Eloquent models.

Data to be collected (based on form designs):
- Full Name
- Government email
- Department / Hiring Organization (this looks like a dropdown, which means we need a list) -> this means another Department type
- Job Title for the position
- Additional details (text field)
- Summary of search filters
- Date requested
- Status -> should be an enum ("PENDING", "DONE") so that its easy to add more states in the future
- Admin notes (text field)

Link to submission form after talent search:
https://www.figma.com/proto/cctPDb5clT7S0JuRmkBgoO/MVP?page-id=0%3A1&node-id=119%3A1549&viewport=-55%2C362%2C0.22959193587303162&scaling=min-zoom

**Comment by Jerryescandon** [comment]
Link to submission form after talent search:
https://www.figma.com/proto/cctPDb5clT7S0JuRmkBgoO/MVP?page-id=0%3A1&node-id=119%3A1549&viewport=-55%2C362%2C0.22959193587303162&scaling=min-zoom

**Comment by tristan-orourke** [comment]
@Jerryescandon 
Department looks like a dropdown, which means we need a list. Do we have a tentative list? What are managers supposed to do if they're not on that list?

**Comment by tristan-orourke** [comment]
Create a Department model at same time

**Comment by tristan-orourke** [comment]
http://donnees-data.tpsgc-pwgsc.gc.ca/ba1/min-dept/min-dept.csv

**Comment by yonikid15** [comment]
The create department model task has been broken out into it's own issue (#481)
