### ISSUE TITLE
Find a way to migrate from SiC auth to another identity provider

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3203]
# Description

Pointing the app to a different OAuth 2.0 identity provider should be easy. The challenge is doing it in a way that existing users don't lose access to their accounts.

If we point to Azure B2C instead of SiC, we can set B2C up to act as a broker and still let users sign in with the same GC Key. However, a naive implementation will probably result in the user returning to our app with a different Sub id in the access token. This means they'll look like an entirely new user account.

We will need a good way for existing users to keep using the app, without a particularly unpleasant experience.

## *Brainstorming some solutions*:
- [ ] Allow our app to connect to multiple brokers directly: sign in with SiC, OR sign in with B2C. (Having to build and maintain this removes one of the advantages of using B2C...)
- [ ] This [Pass through](https://docs.microsoft.com/en-us/azure/active-directory-b2c/idp-pass-through-user-flow?pivots=b2c-user-flow) function sounds like it might allow us to make use of the GC Key token directly, even if they go through B2C. We still have to complicate our app auth, but probably less so than maintaining different auth endpoints.
- [ ] Create some sort of pipeline process which lets a user log in with both methods to overwrite their sub ids or use both.

### Building our own migration pipeline
This requires building our own UX, where someone who's already logged in is prompted to log in with the new provider, and then we can link the two identities on our own. 
- con: requires building special pages and making some additions to the API + database.
- pro: would allow migrating to _any_ identity provider.
This requires some more thinking about how and when we prompt users to do this. Also, it means we need to maintain both login methods for a while. If we want to eventually stop supporting login with the GC Key, then we need a way to warn users, probably by email, ie "You have one year to migrate to our new login account or you will lose access."

**Comment by gobyrne** [comment]
@tristan-orourke any updates to add to this based on recent convos?

**Comment by mnigh** [comment]
@tristan-orourke does this issue still need to be researched? if so, is this happening anytime soon or should it be iceboxed?

**Comment by vd1992** [comment]
@tristan-orourke 
Since SiC will stick around, can this be closed?

**Comment by tristan-orourke** [comment]
Yeah, we can close this. No plans to migrate from SiC right now.
