### ISSUE TITLE
Combine Individual Variant Stories into Single Story

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#3212]
## Description

Currently, we have individual stories for different variants of components which is resulting in a large number of chromatic snapshots. The proposal is to combine the individual variants into a single story where appropriate to reduce the number of snapshots.

Example: https://www.clever-cloud.com/doc/clever-components/?path=/story/%F0%9F%A7%AC-atoms-cc-button--disabled

## Acceptance Criteria
- [ ] Reduce number of stories

**Comment by mnigh** [comment]
@esizer any estimate for this issue?

**Comment by esizer** [comment]
> @esizer any estimate for this issue?

I'd say a 2, does that sound reasonable?
