### ISSUE TITLE
Reduce the number of Storybook stories

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3213]
Right now we are using an excessive number of Chromatic snapshots.  Let's reduce the number of stories we have in our storybook:
- Show the different variants of a component in the same story
- Show the different states of a component in the same story
- Any useless stories to remove?

**Comment by vd1992** [comment]
this feels like it overlaps a lot with #3212 ?

**Comment by petertgiles** [comment]
LOL, Eric beat me to it.
