### ISSUE TITLE
EPIC - Users can Apply to Pools

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3217]
Users can apply to Pool Advertisements.

Remaining Questions
* should Edit pages be new urls or not? (Same for edit experience?) If so, how do we handle breadcrumbs and navigation buttons.
* ~~should url be `pools/id/apply` or `applications/id` ?~~ Work at applications at `applications/:id` urls
* ~~If the former, when/how do we create the application draft?~~ Create an application draft by clicking the Apply button on the job poster. You then navigate to the new application.
* Should we go ahead and rename PoolCandidates to PoolApplications or something?

https://www.figma.com/proto/N9NoPunkqaynjsi89Wrbh0/Direct-Intake---Poster-and-application?node-id=138%3A2905&starting-point-node-id=226%3A4567

![image](https://user-images.githubusercontent.com/4313717/178591441-774f3ef5-183f-4cf5-9e12-539adc3f9d66.png)

**Comment by vd1992** [comment]
appears to be done @gobyrne
