### ISSUE TITLE
Human-readable portion of url for job advertisements

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#3221]
Re-ticketed from https://github.com/GCTC-NTGC/gc-digital-talent/issues/3164

<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Description

Proposal: Have a human-readable portion of url to make it more shareable, but don't use human-readable part of path for url resolution.

Current url format: https://talent.canada.ca/en/admin/pools/00000000-0000-0000-0000-000000000000/view
Proposed url format: https://talent.canada.ca/en/admin/pools/00000000-0000-0000-0000-000000000000/pool-name-it-01-other-arbitary-info/view

### Benefits
- **SEO.** Search engines favour results with information from page in URL. The SEO of advertisements seems more important than any other page.
- **applicant UX.** This will be a link that's shared or saved in bulk during job hunts. It's nice to have a hint at what's inside the link.

Prior art
- Reddit
  - https://www.reddit.com/r/worldnews/comments/vnyya2/rworldnews_live_thread_russian_invasion_of/
  - https://www.reddit.com/r/worldnews/comments/vnyya2/foo (doesn't redirect)
- Trello
  - https://trello.com/b/PMhTjbcA/wip-gc-digital-talent-tech-onboarding-template
  - https://trello.com/b/PMhTjbcA/wip-gc-digital-talent-tech-onboarding (redirects)

### Alternatives Considered
- larger scope, but having human readable IDs in url instead of uuid would make this irrelevant
  - complication: if fields are updated and slug is generated from this field, do urls change break? If so, do we keep old url working? If not, will admins want to be able to change it? (e.g., "i renamed the pool, and the url is now wrong. how do i fix it?"). In comparison, renames are trivial when human-readable path parts are not used for resolution.

## Open Question
1. Do incorrect links "auto-correct" (ie. redirect) to the "current" human-readable link (assembled from proper data), or stay however they were entered? If redirected, is there any cost to that?
2. Is the "/view" suffix necessary, or implied?
3. What should be in the human-readable slug?
4. What do we call this? A `share_url`? Something else?
5. Does the server need to be aware of this at all, or is it just client-side logic in react app?

## Proposed Acceptance Criteria
- [ ] resolves with any human-readable slug
  - https://talent.canada.ca/en/admin/pools/:uuid/pool-name-it-01-other-specific-value/view
  - https://talent.canada.ca/en/admin/pools/:uuid/pool-name-it-01-diff/view
  - https://talent.canada.ca/en/admin/pools/:uuid/pool-name-it-01-other-specific-value-plus-extra/view
- [ ] resolves without a human-readable slug
  - https://talent.canada.ca/en/admin/pools/:uuid/view
- [ ] optional: "corrects" path to current slug
  - visited: https://talent.canada.ca/en/admin/pools/:uuid/pool-name-it-01-diff/view
  - redirect: https://talent.canada.ca/en/admin/pools/:uuid/pool-name-it-01-other-specific-value/view
- [ ] human-readable slug is included in any place url is copied from
- [ ] stretch: server aware of `share_url`?

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by gobyrne** [comment]
This would be nice. We would need French URLs too though.

**Comment by patcon** [comment]
> We would need French URLs too though.

We could, especially since the human-readable part of the url isn't really used to route. But we also don't do this with other parts of the url, and keep the same one. It feels like a stretch goal (and maybe outside the MVP scope) to ensure that each uuid path has both a human-readable french and human-readable english url.

This double-url thing will also also introduce some complicated SEO-related concerns, as we'd have identical content found at various urls (which is punished in search engine rankings, unless done correctly)

**Comment by mnigh** [comment]
@tristan-orourke Is this something we are considering doing?

**Comment by mnigh** [comment]
> @tristan-orourke Is this something we are considering doing?

@tristan-orourke Bump for 2024!

**Comment by tristan-orourke** [comment]
I would love human-readable url slugs, but there's no plan to prioritize them.
