### ISSUE TITLE
Restore french translations for Conditions of Employment / Operational Requirements

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3226]
We changed these in localizedConstants, which means the keys for our french translations no longer match (and aren't correct anyway). Run the translation process (described in frontend/common/README) for the common project. We can probably get translations directly from DCMO instead of going through translation services.

Recent changes to Conditions of Employment: https://github.com/gctc-ntgc/gc-digital-talent/issues/2769

![image](https://user-images.githubusercontent.com/16977254/168662958-57b7a3bb-562a-4a4e-98c2-cf0e547b3562.png)

**Comment by petertgiles** [comment]
Corrine will return translations later today.
