### ISSUE TITLE
Use React StrictMode

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#3228]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Description
StrictMode is a feature that helps with a lot of things (but only when running in development mode), including:
- double mounts each component to compare state and find memory leaks from missing unmount logic, or other mis-use of lifecycle hooks (e.g., useEffect, useMemo, useState)
- warns of specific deprecated methods in the app _and_ any dependant packages. Finding these early helps react version upgrades go smoothly.

StrictMode is the default for apps created with create-react-app, which makes it seem like a decent practice.

Reference: https://reactjs.org/docs/strict-mode.html

## Acceptance Criteria
- [ ] all apps are wrapped in `<React.StrictMode />` component 
- [ ] Do not merge if there are errors (yet) - Bring to stand-up or have a discussion about it.

## Not acceptance criteria
- [ ] all apps run in development mode without error (console or otherwise)

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by esizer** [comment]
Blocked by #2404 due to React 18 making strict mode more strict.

Ref: https://reactjs.org/blog/2022/03/29/react-v18.html#new-strict-mode-behaviors
