### ISSUE TITLE
Create layout components for simple grid system (wrap Hydrogen)

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#3248]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Description
It could be nice to handle grids in a more react-like way. Some UI libraries have grid systems that are pretty nice, like:
- react-bootstrap: https://react-bootstrap.github.io/layout/grid/
- rebassjs https://rebassjs.org/guides/css-grid (h/t @esizer)
- material ui: https://mui.com/material-ui/react-grid/

Might be nice to have components that copied some parts of the component API for one of the above. (@JoshBeveridge mentioned that Hydrogen should support this via flexgrid: https://hydrogen.design/#flexGrid

## Acceptance Criteria
- [ ] We have some components for this
- [ ] Implemented in a few places as demonstration

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by JoshBeveridge** [comment]
Might be worth branching the H2 upgrade branch so that you can use CSS grid instead of flex grid. There are some missing updates on that branch, but I can run them first thing tomorrow.

**Comment by esizer** [comment]
> is this still something we are interested in? Or maybe we're more comfortable with H2 now?

@gobyrne I'd still be interested in tackling this to reduce the amount of hydrogen boilerplate we are writing right now for common layout patterns. Though, I'd put this near the bottom of the priority list.

**Comment by patcon** [comment]
Me too! I'd love for data attributes to be hidden inside a set of layout components, if possible. But yeah, low priority

**Comment by mnigh** [comment]
@GCTC-NTGC/developers any interest in moving this forward or should it be closed?

**Comment by substrae** [comment]
@mnigh Depending on the lift on this one, I can look at implementing it natively into a single `data-h2-grid` attribute. It's been in my backlog for a long time, but hasn't really been a priority.

**Comment by esizer** [comment]
> @GCTC-NTGC/developers any interest in moving this forward or should it be closed?

I think we can likley close this. I looked and we actually don't use the container or grid system a lot and now that we have css grid support in hydrogen I don't think this would offer much benefit.
