### ISSUE TITLE
User table footer not very responsive

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3270]
We've agreed that the admin site does not need full mobile support but the User table needs at least 1550 px width to render without issues in the footer which is pretty excessive.
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/c60be650-e5b6-403b-8152-a53265ced53f)

Less than that and it gets progressively worse.
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/f02bcf04-1f1b-4752-adf0-a8489c636298)

We don't have an official minimum width that needs to be supported but can we make this work better?

**Comment by tristan-orourke** [comment]
Some things we can do here:
- hide excess page buttons at lower widths with media queries (actually show page buttons >2 ? at higher widths)
- move the pagination controls to another line below the buttons

actually just get mobile designs from designers

**Comment by gobyrne** [comment]
Will probably get fixed with with #3487

**Comment by petertgiles** [comment]
It's a little better now.   It looks good to about 1060px now.  Auto-collapsing the sidebar would help a lot.
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/c29e271f-10a7-4287-9bec-4a0d8a21431e)

**Comment by gobyrne** [comment]
I feel like there are way too many pagination buttons. I'll put this in the design backlog for another look.

**Comment by Jerryescandon** [comment]
We might need to consider the possibility of switching from pagination to scroll. 🤔

**Comment by gobyrne** [comment]
There are still issues with this, but it's no longer what is described here. Closing this issue
