### ISSUE TITLE
Fix issue with over-eager accessibility focus in Dialog component

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#3272]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Description
Storybook is acting wonky when Dialog is open, and stealing focus from sidebar. Obviously storybook is no big deal to be on the fritz, but unsure how to evaluate if this is indicative of anything else we might be doing incorrectly.

Reach UI team develops in storybook, so it should be something they would have hit, and they likely have an appropriate mitigation in their own stories: (they don't host their storybook anywhere public, so will need to build locally)
https://github.com/reach/reach-ui/tree/dev/packages/dialog/examples

You can see this behaviour here, when trying to type in Storybook's search field: https://main--61e099a1bb1465003a73d3ce.chromatic.com/?path=/story/components-dialog--basic-dialog

## Screencast
[![](http://g.recordit.co/a674x3QIzZ.gif)](https://recordit.co/a674x3QIzZ)
full mp4: https://recordit.co/a674x3QIzZ

## Acceptance Criteria
- [ ] can open a Dialog-based story, and type in storybook search bar

cc: @esizer (in case you have insight, but very non-urgent)

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by esizer** [comment]
The whole point of the dialog is to steal focus using [react-focus-trap](https://www.npmjs.com/package/focus-trap-react), though i have no idea how we fix this in storybook 🤷

**Comment by mnigh** [comment]
I think this issue has been resolved with the switch from **reach-ui** to **radix-ui** for the `Dialog` component. @esizer, do you mind confirming this in case I misinterpreted the described behaviour?

chromatic storybook on `main` branch: https://61e099a1bb1465003a73d3ce-gqjwjhjech.chromatic.com/?path=/story/components-dialog--basic

**Comment by esizer** [comment]
> I think this issue has been resolved with the switch from **reach-ui** to **radix-ui** for the `Dialog` component. @esizer, do you mind confirming this in case I misinterpreted the described behaviour?

It has not been fixed, though, I'm not sure how much of an issue this is since dialogs are _supposed_ to trap focus and it is working exactly as expected 🤔. This would require we build in an escape hatch for the sole purpose of not trapping users in storybook, causing the dialog to work incorrectly, misrepresenting the components functionality. 

I'm not sure we really need  to do this unless we get direct feedback from someone saying it is an issue.
