### ISSUE TITLE
Format salary range currency in French format

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#3275]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Description
In French Canadian, the format is slightly different than in English:

| Locale | Format |
|---|---|
| `en-CA` | `$10,000.00`
| `fr-CA` | `10 000,00 $`

This needs to be translated in the localizedConstants.tsx file:
https://github.com/GCTC-NTGC/gc-digital-talent/blob/1160efab302e22871df537610ac1c439f8e890dd/frontend/common/src/constants/localizedConstants.tsx#L69-L76

## Acceptance Criteria
- [ ] Salary range is localizable in localizedConstants.tsx
- [ ] every component that uses `SalaryRange` is updated to accomodate localization
- [ ] stories that use `SalaryRange` still work

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by patcon** [comment]
Likely not a good idea to use formatjs's number formatting for such a small case (that is maybe more string-like than number-like), but it exists: https://formatjs.io/docs/react-intl/components/#formattednumber

**Comment by tristan-orourke** [comment]
This is a good point, but we're only using these strings on Admin dashboard, and not for much longer (we're using salaries associated with classifications as soon as we release profiles), so we can ignore this for now.

**Comment by esizer** [comment]
I'm not sure, but this could be helpful.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/0ea2eb7296360cbf8c0cf6d6c2e11179002362bf/frontend/common/src/helpers/localize.ts#L69-L81

**Comment by mnigh** [comment]
@tristan-orourke can this `wontfix` be closed?

**Comment by tristan-orourke** [comment]
wontfix
