### ISSUE TITLE
Bug - Select element background colour inconsistent

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#3282]
### Description
Select element background colour inconsistent across browsers. For example, in Chrome the background colour is white but in Firefox the background colour is grey.

### Screenshot
![Screen Shot 2022-07-07 at 11.06.37.png](https://images.zenhubusercontent.com/5f7b33373ac7b7279de9a3c5/23bcd44c-97dd-4fd8-838a-a674cb009918)

### Acceptance Criteria
- [ ] select element background colour consistent across browsers

**Comment by mnigh** [comment]
This might this be resolved if we use `react-select` and verify its appearance in different browsers.

### Related
- #3128

**Comment by gobyrne** [comment]
This might already be fixed, but even if not, I don't need it fixed. We will be doing some fairly major work on the search page in the near future. Closing this issue.
