### ISSUE TITLE
Bug - Navigation links not center aligned

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#3283]
### Description
`ListItem` component items used in `NavMenu` component not center aligned with `Header` component items on smaller screen widths.

### Screenshot
![Screen Shot 2022-07-07 at 11.15.15.png](https://images.zenhubusercontent.com/5f7b33373ac7b7279de9a3c5/c7782ffc-b4c3-433a-86e1-c747f53bd6ff)

### Acceptance Criteria
- [ ] Navigation links are center aligned

**Comment by mnigh** [comment]
This will be addressed as part of changes in #3051.

**Comment by gobyrne** [comment]
Is addressed in the Hydrogen upgrades PR
