### ISSUE TITLE
Wrong labels for CoE in production

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3285]
The older, deprecated version of the search page is using the new labels for the options.  Those new labels should only be used in the newer version of the search page that is currently hidden behind a feature flag.

In production right now:
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/a85405e0-59ed-490d-a314-bd0c33d27464)

We will probably need to restore the old translations from git and place them in a separate file in the deprecated folder for the older version of the page to use.

**Comment by petertgiles** [comment]
Translations for the overtime options provided by Gray:
Travailler des heures supplémentaires prévues / Travailler des heures supplémentaires à court préavis

prévues = scheduled
à court préavis = on short notice

**Comment by vd1992** [comment]
may need to add the translation elsewhere once overtime enums are tweaked
