### ISSUE TITLE
Create new enum constants for new overtime options

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3286]
The new version of the search page moves from "overtime - short notice" and "overtime - scheduled" to "overtime - occasionally" and "overtime - regularly".

We are currently treating the transition as a simple wording change:
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/686d17ad-8dd5-4e27-ab8b-89c303c3dc9a)

However, they are quite different and should probably get new enum constants values to reflect that instead of reusing the older ones.

**Comment by tristan-orourke** [comment]
If we create new enums, then we should make sure the localizedConstants text for the existing enums is changed to match.
