### ISSUE TITLE
When user goes to `login-info` page, track where they came from and use that as `post-login-redirect`

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3289]

**Comment by petertgiles** [comment]
This would effectively supersede ever sending the user to their profile page automatically since a user cannot be on their profile and then choose to log in.  Is this what we want?

**Comment by petertgiles** [comment]
Would we implement this by adding the `from` query parameter to the login link in the header or by scanning the URL history from the login-info page?  If the latter, would the login-info page give precedence to the query param or the history?

**Comment by tristan-orourke** [comment]
Let's close this. I think going to Profile and Applications page (effectively a personal dashboard page) on login is desired behaviour.
