### ISSUE TITLE
Admin - inconsistent icon use

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#3308]
## Description
Users page uses different icon than its associated menu item. Skill Families menu item uses the same icon as the Users page.

## Screenshot
![Screen Shot 2022-07-11 at 10 34 38](https://user-images.githubusercontent.com/3046459/178294058-25df8279-aaa1-476e-9c8b-0ad1f6002680.png)

**Comment by Jerryescandon** [comment]
Quick fix:
- Keep the single user icon for "Users" and multi user icon for "Skill families"

Long term:
-  skills and skill families probably need their own custom icon, but that requires some @BrookeCameron time
