### ISSUE TITLE
Jest tests are failing but Github Action check passes

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3309]
When Jest tests fail, the Github check should fail!

As an example:
1. Go to PR #3288
2. Go to the Checks tab
3. Go to the Jest Tests check
4. Click Unit Tests
5. Open "Run Unit Tests: All Workspaces"
6. See that some tests failed, but the overall check passed!

Obviously we want to fix the failing jest tests eventually, but first we want to ensure that failing tests will make the Check fail!

**Comment by mnigh** [comment]
Possibily related issue: https://github.com/actions/runner/issues/1851

**Comment by vd1992** [comment]
> Possibly some breadcrumbs?
> 
> ```
> (node:1908) UnhandledPromiseRejectionWarning
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:1908) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
> (node:1908) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```

possibly a smoking gun
looks at the moment to me the possible reason why jest is jesting us
