### ISSUE TITLE
Cypress e2e test failing sporadically (admin-workflows.spec.js)

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#3311]
We're getting sporadic failures of one particular e2e test:
https://github.com/GCTC-NTGC/gc-digital-talent/blob/59bdda46a6672701aa64b7b207c93ded954365af/frontend/cypress/integration/admin/admin-workflows.spec.js#L71-L103

It's happening in line 94:
https://github.com/GCTC-NTGC/gc-digital-talent/blob/59bdda46a6672701aa64b7b207c93ded954365af/frontend/cypress/integration/admin/admin-workflows.spec.js#L94

https://github.com/GCTC-NTGC/gc-digital-talent/blob/59bdda46a6672701aa64b7b207c93ded954365af/frontend/cypress/integration/admin/admin-workflows.spec.js#L15-L24

First failing run I could see with same error:
https://github.com/GCTC-NTGC/gc-digital-talent/runs/7239951241?check_suite_focus=true

List of all e2e tests runs:
https://github.com/GCTC-NTGC/gc-digital-talent/actions/workflows/e2e-tests.yml?page=3&query=

**Comment by mnigh** [comment]
Still occurring in:

- https://github.com/GCTC-NTGC/gc-digital-talent/pull/3482: https://github.com/GCTC-NTGC/gc-digital-talent/runs/7502636679?check_suite_focus=true

**Comment by esizer** [comment]
Possibly resolved by #3568 in the commit [a0cd206](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3568/commits/a0cd2064de4b6e6d2dc57d4730e8eda7ae3dfbd3)

**Comment by petertgiles** [comment]
I haven't really started this after several days.  Throwing it back.
