### ISSUE TITLE
Create a `useOptions` react hook for managing our options

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#3314]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Description

Question: could be create a hook to help us manage options lists? e.g., `useOptions()`.

### Background

- a decent amount of boilerplate logic in our app is manipulating lists of options objects with `label` and `value` keys
  - these are used for checkboxes, Select, MultiSelect and radios
- sometimes these options must be fetched first from database, and have associated fetching/error state
- usually, but not always, the `values` come from a list of enums, either all or _some subset_
- often the presentation of these values differs, whether being shown to an applicant (maybe using first-person text) vs an admin, or in a long form vs short-form (for space limited Select fields)
- sometimes options have sort order, but that seems to be persistent consistent across all variants

### Proposal

Proposed usage: (starting with dream API feels helpful?)

```js
// requesting default set of options with default labels
const { operationalRequirements } = useOptions("operationalRequirements");
// <Select options={operationalRequirements.options} />

// requesting a subset of enums, aka an enum variant, or an "input variant".
// E.g., when a migration is happening, like with operationalRequirements now, where there are legacy values in enum that we don't wish to present in forms.
// Default filterVariant was "v1"
const { operationalRequirements } = useOptions("operationalRequirements", { filterVariant: "v2" } );

// requesting an alternative presentation (for different context). Really just selecting a different set of localizable labels. aka "output variant".
const { operationalRequirements } = useOptions("operationalRequirements", { labelVariant: "candidateDescription" } );

// A set of options that must populate from database, and so wrapping an urql hook.
const { skills } useOptions("skills");
// <Select options={skills.options} isLoading={skills.rawGraphqlResponse.fetching} />
```

On the backend (beneath the hook), we might choose to have `Option` class, instantiated for each field type, helping to enforce the shape and helpers of how we're processing this.

### Open Questions
1. Is this abstraction worth it? Is it helpful to keep this logic standardized and out of components themselves?
2. Would any features not fit within this hook API? (I'm sure I'm missing some examples)
3. How would additional labels work? e.g. "All" or "Any" or "None". Could we standard these in hook?
4. Could submission processing methods eventually also be migrated into a hook like this? (processing seems quite related to the option values we choose to include)

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by mnigh** [comment]
@tristan-orourke is there still a desire to move forward with this?
