### ISSUE TITLE
Refine time zone handling for pool expiry dates

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3315]
A basic time zone system was created for pool advertisements but it now needs to be refined.

## Problems
- The time is stored with an offset but is being shifted to UTC when queried in the API:
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/ff871af3-eb1c-424f-b6d8-43614eda5bbd)
- Codegen is making the scalar for `DateTimeTz` an `any` which is not very useful
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/e491bea3-748f-4b3f-bf67-8d632fd17730)

## User Acceptance Criteria
- Have the API return the datetimetz with the original offset
- Have codegen return a useful type for the frontend
- API returned value should be easily used in the frontend for display and also calculating time difference to now.

## Notes
- I would love to have the API also return the name of the time zone (like "23:59:59 America/Vancouver)  but I don't think Postgres stores that, just the offset
- Is lighthouse returning UTC because that is the time zone Laravel is set to?
- When someone closes the pool do we set the expiry date to "now" in UTC or the time zone of the user's browser executing the mutation?

**Comment by patcon** [comment]
> have the API also return the name of the time zone (like "23:59:59 America/Vancouver)

Feels like the role of the client (rather than a field resolver on server) to take standard time format and convert it to human-readable timezone if desired. I just checked, and we've got two time/date-related libraries already in the lockfile from deps, and hopefully one handles named timezones :)
https://github.com/iamkun/dayjs
https://github.com/date-fns/date-fns

But more generally, assuming the timezone is converted properly, it kinda feels like returning UTC irrespective of the timezone in the DB is the appropriate behavior. We don't know where the user is, so having it vary in responses feels inconsistent.

**Comment by petertgiles** [comment]
> take standard time format and convert it to human-readable timezone if desired

The trouble is, it's not really possible to turn an offset into a time zone without making some assumptions.  For example UTC -7 is Pacific Time in the summer and Mountain Time the rest of the year.  If you assume North America and you know the date you can figure it out.  It doesn't happen often in North America but in other places in the world the start and end date of summer time change from year to year.  It quickly becomes unmanageable.  

If you just want to take UTC and show it in the local time zone that's pretty easy but I think the Pacific Time zone is important to show to the user here.

Good to know about the time/date libraries - that will probably come in useful.

**Comment by tristan-orourke** [comment]
> it kinda feels like returning UTC irrespective of the timezone in the DB is the appropriate behavior. We don't know where the user accessing our API is located, and so having it vary in responses feels inconsistent.

I think I'm in agreement with @patcon on this. Laravel's not storing timezones at all in the database; datetimes are stored as timestamps. That seems like a pretty major convention to break away from. 

It's important to show the time in Pacific Time on the Job Advertisement, but we can do that conversion clientside. (Also when we store it.)

**Comment by petertgiles** [comment]
So for the common use cases, this is the process you'd see?

Display expiry date:
1. Receive unzoned datetime from API
2. convert from UTC to Pacific
3. display date portion

Set expiry date:
1. Form returns unzoned date
2. Set time to 23:59:59
3. Convert from Pacific to UTC
4. Send unzoned datetime in API

Close Pool:
1. Take UTC now
2. Send unzoned datetime in API

**Comment by tristan-orourke** [comment]
That seems like a good summary of the processes I expect.

I don't really want to change all the field names. That seems redundant if every date behaves the same way. I would be okay with using DateTimeTz instead of DateTime in our schema, to make everything explicit.

**Comment by tristan-orourke** [comment]
Oh! And the solution to the codegen types is to add DateTimeTz to the scalars section of our codegen.yml files:
```
    scalars:
        Date: string
        DateTime: string
        Email: string
        PhoneNumber: string
        DateTimeTz: string
```

**Comment by patcon** [comment]
On re-reading, it seems like (with the "submit in UTC" steps and "append a `_utc` suffix) you're trying to ensure that dates in the database are always a single timezone. Do I have that right?

**Comment by patcon** [comment]
Guys! Guys! We're doing it! We're having the tedious timezone conversations we were promised as software developers! 🎉

**Comment by gobyrne** [comment]
Is this still relevant @petertgiles ?

**Comment by patcon** [comment]
> Ensure form is correctly converting to UTC to submit updates

Again, sorry if this is dunce-y, but is this necessary? Can the API not just accept a random date with timezone data from browser, and the laraval API deals with it? I'm unclear why the client form/API needs conversion to UTC, which feels like a footgun maybe? :)

**Comment by petertgiles** [comment]
Good catch!  No, it's no longer relevant - we have settled on always storing UTC for the DateTime type in the database.  I'm not aware of any bugs with this at the moment.
