### ISSUE TITLE
Add Citizen and Veteran fields to backend

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3318]
# Description

Add fields to User model for storing Citizen and Veteran status. 
Add these fields to User table, model, and factory.
Add these fields to schema (User and Applicant types _and_ inputs) so they can be queried and mutated.
Add these fields to fakeUsers.ts
Update the User.getIsProfileCompleteAttribute and User.scopeIsProfileComplete methods to check that Citizen and Veteran status have been set.

These will be used on the profile page like so:
![image](https://user-images.githubusercontent.com/4313717/178591828-80ca8e76-bbb2-4779-9db5-b34f18a279ad.png)

# Acceptance Criteria
- [x] Citizen and Veteran status can be queried on User and Applicant queries.
- [x] Citizen and Veteran status can be set when creating/updating User/Applicant
- [x] Users are seeded with Citizen and Veteran values
- [x] Profiles are not considered complete if Citizen and Veteran values are not set
- [x] Ensure tests are updated or implemented, especially "profile complete" logic

**Comment by petertgiles** [comment]
No consideration of priority in this issue.
