### ISSUE TITLE
Add Citizen and Veteran fields to Profile (summary & edit page)

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3319]
# Description

Add Citizen and Veteran fields to About Me form.
Display these fields on the Profile when they are filled in.

![Profile](https://user-images.githubusercontent.com/4313717/178592571-4f6e27b6-d286-49bd-ad73-ad996ad06f48.png)
![About Me form](https://user-images.githubusercontent.com/4313717/178592623-01e2273c-813b-491b-8148-d34bb419472f.png)
[Figma Prototype](https://www.figma.com/proto/N9NoPunkqaynjsi89Wrbh0/Direct-Intake---Poster-and-application?node-id=138%3A2195&starting-point-node-id=226%3A4567)

# Acceptance Criteria
- [x] Citizen and Veteran fields can be edited on About Me page
- [x] Citizen and Veteran fields appear on user's Profile page when filled in
- [x] Citizen and Veteran fields appear on the Admin view of a profile page, if filled in

**Comment by petertgiles** [comment]
Double check that it comes out in the print profile
