### ISSUE TITLE
Only create chromatic snapshots on-demand

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#3321]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

Re-ticketed [from Slack](https://talent-cloud.slack.com/archives/C0259G6KXJ6/p1657651681812179)

## Description
Right now, we run out of chromatic snapshots included in our plan by the 12th of the month. This costs overage.

We also skip chromatic builds for all dependabot branches, based on the actor being dependabot:
https://github.com/GCTC-NTGC/gc-digital-talent/blob/43a09a0e18542f302476b94a4222994d55226a87/.github/workflows/storybook.yml#L14-L20

But as illustrated by @petertgiles' screencap video, it's easy to force a run of one of these skipped runs, and status checks in PR are crated accordingly:

https://user-images.githubusercontent.com/305339/178577266-e2c6fa5c-fdcb-43ef-803f-df2f60227138.mp4

## Risks
- this special-case scenario of "skip, but re-run will be different" might only work because the "actor" is dependabot when dependabot creates its PRs. In that case, it conveniently works for the human when it's manually triggered, aka `github.actor = "petertgiles"` and `"petertgiles" != "dependabot[bot]"`

## Acceptance Criteria
- [ ] chromatic builds only run when we re-run a workflow that's skipped by default

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by tristan-orourke** [comment]
Ideally we run it once when a PR is first created, once when Main is updated, and also whenever manually triggered.
