### ISSUE TITLE
Application page Wrapper

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3323]
# Description
Build a Wrapper component which can be used on both steps of the Application.

Header:
![Header img](https://user-images.githubusercontent.com/4313717/178601535-7c8f30ed-a207-4b43-acd0-e4720e0910c7.png)
Footer:
![Footer img](https://user-images.githubusercontent.com/4313717/178602757-3f8b58d1-1e79-4676-ad1e-7190c6959595.png)

[Figma Prototype](https://www.figma.com/proto/N9NoPunkqaynjsi89Wrbh0/Direct-Intake---Poster-and-application?node-id=229%3A5735&starting-point-node-id=226%3A4567)

# Acceptance Criteria
Shows the following

- [x] - "My Application" page title
- [x] - breadcrumbs
- [x] - Job Advertisement title
- [x] - Closing Date block
- [x] - button-style links to both Steps
- [x] - footer with breadcrumbs
- [x] - The Step buttons/links can be disabled with a prop.

**Comment by tristan-orourke** [comment]
Reuse code made for the Pool Advertisement page for rendering the date.

**Comment by patcon** [comment]
+1 to same page, and

```js
const ApplicationWrapper = () => {
  const { poolId } = useParams();
  const viewType = poolId ? "foo" : "bar";
  return (
    <div>
      // ...
    </div>
  );
}
```

([useParam](https://v5.reactrouter.com/web/api/Hooks/useparams) is the react-router way, but we could maybe wrap our useLocation to get the same interface, which will make migration to react-router easier later). then logic in component based on which viewType we are 🙂

**Comment by patcon** [comment]
Not sure if this belongs in #3324 or here, but...

+1 to same page, and

```js
const ApplicationWrapper = () => {
  const { poolId } = useParams();
  const viewType = poolId ? "foo" : "bar";
  return (
    <div>
      // ...
    </div>
  );
}
```

([useParam](https://v5.reactrouter.com/web/api/Hooks/useparams) is the react-router way, but we could maybe wrap our useLocation to get the same interface, which will make migration to react-router easier later). then logic in component based on which viewType we are 🙂
