### ISSUE TITLE
Review My Application page (Apply Step 1)

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3324]
# Description
[Figma Prototype](https://www.figma.com/proto/N9NoPunkqaynjsi89Wrbh0/Direct-Intake---Poster-and-application?node-id=138%3A2905&starting-point-node-id=226%3A4567)

This page should be rendered at the url `applications/:id/apply`.

Build the Step 1 page of the application. This is mostly a duplication of the Profile. The differences are:
- The profile is wrapped in the Application Wrapper #3323 
- The Edit links should include a pool id query parameter
- Below the Experience/Skills, missing required skills are listed. The list of required skills comes from the Pool itself. NOTE: only Need to Have, Occupational Skills are shown, Any Nice to Have skills show not be required. And any Transferable skills which are "Need to Have" can be ignored. The Occupational/Transferable category comes from the skill's SkillCategory. Skills and Experience block which shows required skills #3435
- At the bottom are buttons to Continue or Go back to Applications.
- Continue button, and the Step 2 button in Header, should be disabled if profile is incomplete OR if any required (and occupational) skills are missing.

Note: The Transferable/Occupational category comes from the Skill Family, which skills may have several of. If a skill has zero skill families, list it here. Only  Consider a skill to be Transferable (and therefore unlisted) if it has at least one SkillFamily and all are Transferable.

Required Skills are listed like so:
![Requred Skills](https://user-images.githubusercontent.com/4313717/178604201-485ca69c-e165-4c85-9424-207a4a754d55.png)

Buttons at bottom:
![image](https://user-images.githubusercontent.com/4313717/178604745-4f3d9ecd-778d-4e56-b135-5399fa3d3983.png)

# Acceptance Criteria
- [ ] The page appears at the url `applications/:id/apply`. You can use or replace the PoolApplyPage component.
- [ ] The profile is wrapped in the Application Wrapper #3323 
- [ ] The Edit links send you to `/applications/:id/apply/about-me`, `/applications/:id/apply/language-information`, etc instead of the profile routes
- [ ] Below the Experience/Skills, missing required skills are listed. The list of required skills comes from the Pool itself. NOTE: only Need to Have, Occupational Skills are shown, Any Nice to Have skills show not be required. And any Transferable skills which are "Need to Have" can be ignored. The Occupational/Transferable category comes from the skill's SkillCategory.
- [ ] At the bottom are buttons to Continue or Go back to Applications.
- [ ] Continue button, and the Step 2 button in Header, should be disabled if profile is incomplete OR if any required (and occupational) skills are missing.

**Comment by patcon** [comment]
I think this is the right issue for this comment in planning poker...

+1 to same page, and

```js
const ApplicationWrapper = () => {
  const { poolId } = useParams();
  const viewType = poolId ? "foo" : "bar";
  return (
    <div>
      // ...
    </div>
  );
}
```

([useParam](https://v5.reactrouter.com/web/api/Hooks/useparams) is the react-router way, but we could maybe wrap our useLocation to get the same interface, which will make migration to react-router easier later). then logic in component based on which viewType we are 🙂
