### ISSUE TITLE
Sign and Submit page (Read Only)

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3325]
# Description

[Figma Prototype](https://www.figma.com/proto/N9NoPunkqaynjsi89Wrbh0/Direct-Intake---Poster-and-application?node-id=229%3A5735&starting-point-node-id=226%3A4567)

This page should be rendered at the url `applications/:id/submit`.

Build the Step 2 page of the application.
Make use of the Application Wrapper #3323
It is not necessary to add functionality yet to the Submit button. ~~However, the submit button should be disabled if the Profile is incomplete, or if any required, occupational skills are missing.~~  This functionality will be added with draft applications.

Note: The Transferable/Occupational category comes from the Skill Family, which skills may have several of. If a skill has zero skill families, list it here. Only  Consider a skill to be Transferable (and therefore unlisted) if it has at least one SkillFamily and all are Transferable.

![image](https://user-images.githubusercontent.com/4313717/178760815-1030b2db-d957-4c21-bf4b-1899d62d2688.png)

## Acceptance Criteria

- [ ] this page is rendered at the url `applications/:id/submit`
- [ ] details of the current pool appear correctly in the wrapper
- [ ] the submit button is disabled if the user's profile is incomplete or if missing any required occupational skills

**Comment by petertgiles** [comment]
No validation on input box other than something has been added.

**Comment by brindasasi** [comment]
blocked by Hydrogen PR now
