### ISSUE TITLE
Set up Custom Exceptions

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#3328]
Description 
Create custom exception based on this 
https://lighthouse-php.com/master/digging-deeper/error-handling.html#additional-error-information

**Acceptance Criteria**
- [ ] Create a custom validation rule with error code
- [ ] Add custom exception error code to error code class
- [ ] Update helper function to recognize custom exceptions
- [ ] Unit test with English and French validation

**Question**
 We need a proper use case for this custom exception. We could use any business logic requirements but we need atleast one to work here

**Comment by vd1992** [comment]
@brindasasi 
Is this still needing work or was this completed by the various logging PRs you completed like #5176 and #5809 ?

**Comment by brindasasi** [comment]
@vd1992 this has been completed and be closed
