### ISSUE TITLE
Backend mutations for Creating Applications

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3332]
# Description

## Create Draft mutation
Create a mutation which creates a stub application, aka a PoolCandidate, for the currently logged-in user and the specified pool. This PoolCandidate object can be devoid of any data besides the pool, the user, and something that marks it as a Draft (a new status?). 

QUESTION: if the user already has a PoolCandidate for the pool, do we want to throw an error or just return the pool that already exists?

ANSWER: (Gray) I think so... it seems like returning the existing one will solve more problems then it causes. So yes, unless there's a good reason not to.

# Acceptance Criteria
- [ ] Create mutation creates a new PoolCandidate object with very little data, but in a draft status
- [ ] Draft status simply means that the 'submitted_at' field is null (potentially)
- [ ] If user already has a PoolCandidate for the pool, create mutation returns that existing object instead of creating a new one.

**Comment by tristan-orourke** [comment]
Eventually, the submit mutation will also have to create the "snapshot", but that is for another ticket.

**Comment by Jerryescandon** [comment]
| Status | Copy on public |  Programmatically | Has Snapshot | Can be Archived | Can be Deleted | Search results |
| ------- | -------------------- | -------------------- | ---------------- | ------------------- | ------------------ | ------------------ |
| Draft  | "Expires in (time) days" | Yes - default status on application creation| no | no | YES |
| Draft-expired  | "Expired on (date)" | Yes - default status on a draft application past expiry date | no | no| YES |
| New application  | "Submitted and waiting for review"| manual | YES | no | no |
| Application under review  | "Application under review" | manual | YES | no | no |
| Screened in (available)  | "Waiting for assessment" | manual| YES | no | no |
| Screened out - On application| "Application not accepted" | manual| YES | YES | no |
| Under assessment | "Waiting for assessment" | manual| YES | no | no |
| Screened out - On assessment  | "Assessment not passed" | manual| YES | YES | no |
| Qualified - Available  | "Qualified" | manual | no | no| no |
| Qualified - Unavailable  | "Qualified" | manual | no | no| no |
| Qualified - Withdrew  | "Qualified" | manual | no | no| no |
| Placed Casual  | "Completed" | manual | no | no| no |
| Placed Term  | "Completed" | manual | no | no| no |
| Placed Indeterminate  | "Completed" | manual | no | no| no |
| Expired  | "Expired on (date)" | YES - Rule goes here | no | YES | no |
