### ISSUE TITLE
Test existing database recovery plan with IMTD

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3345]
# Description
Make a Jira ticket request a DR (Disaster Recover) test to test out the current backup. They'll probably spin up a new service from a backup and we can try pointing to it to test things out. After confirming it works, they'll spin it down.

Jira is only accessible on the VPN: jira.tbs-sct.gc.ca

**Comment by petertgiles** [comment]
Ticket submitted: https://jira.tbs-sct.gc.ca/browse/AZ-13524

**Comment by petertgiles** [comment]
Spun off #3542

**Comment by petertgiles** [comment]
I did a simple database backup and restore test:
1) Made a backup file with `pg_dump gctalent > gctalent_2022_07_29.sql`
2) Added a new junk user to dev
3) Wiped the database with `psql --comand="drop database gctalent"`
4) Verified that the app was non-functional
5) Recreated an empty database with `psql --command="create database gctalent"`
6) Restored the data with `psql gctalent < gctalent_2022_07_29.sql`
7) Verified that the app was functional
8) Verified the junk user was not present
9) Took another backup with `pg_dump gctalent > gctalent_2022_07_29_after_restore.sql`
10) Compared the backups with ` diff gctalent_2022_07_29.sql gctalent_2022_07_29_after_restore.sql` to ensure they matched

**Comment by petertgiles** [comment]
IMTD restored database server vm tal-devdb01 as tal-devdb02.  I retrieved database backup dumps from tal-devdb02 and verified that they matched the database dumps from tal-devdb01.
