### ISSUE TITLE
Experiment with minimal implementation of AxaGuilDEv/react-oidc

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3348]
## Description
Experiment with implementing simple login with PKCE using AxaGuilDEv/react-oidc. Don't worry about refreshing, or logout, just try to get a basic login working.
While at this, investigate how we could integrate this into our existing frontend auth components.

**Comment by petertgiles** [comment]
Gonna put this one down for now on Gray's request.  Summary so far:
- I have the demo app working with mock auth in this repo: https://github.com/petertgiles/axa-with-mock/tree/first-try
- Seems to work well with Mock Auth
- SiC has problems with CORS on the well-known/configuration page.  Doug says they will fix this on their next sprint.
![image](https://user-images.githubusercontent.com/8978655/180816935-75c1ac5c-cde4-4440-b75a-b72a9daf9b0b.png)

**Comment by tristan-orourke** [comment]
This is no longer necessary, I feel comfortable jumping straight to attempting #4916.
