### ISSUE TITLE
Set up Analytics for talentsearch, admin

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#3351]
### Description
Individual views for talentsearch, admin. Similar to https://github.com/GCTC-NTGC/gc-digital-talent/issues/3219

**Comment by gobyrne** [comment]
Let's see what it will take to implement this for direct intake before sending it to the Safebox.

**Comment by mnigh** [comment]
@brindasasi just a reminder that any changes for IAP that come out of [this issue](#4016) should be applied to `talentsearch` and `admin` as well to avoid the same problem.

**Comment by vd1992** [comment]
is this issue closed? @brindasasi
