### ISSUE TITLE
Update server build process to use new version of node

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3358]
After #3352, we must ensure the build process on Azure uses the same version of node.

**Comment by petertgiles** [comment]
Confirmed that there is a mismatch in the build logs:
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/2126673b-9a5e-4cb5-ae73-7b79c5dd8424)

**Comment by petertgiles** [comment]
Made the change:
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/d4c60a1e-aaec-4416-9cc1-4abc7f0f006a)
Seems to have run OK:
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/c1b02ee0-ec78-4483-ba72-4122ff6c88ec)
