### ISSUE TITLE
Github Actions - Cache service responded with 429

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3379]
It seems like under certain circumstances many of our Github Actions integrations will fail on the `setup-node` action with the error message `Cache service responded with 429`.  This is observed on "Dependabot Monday":
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/c4aed0be-5076-46c8-823a-3ccc6996147e)
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/5ddae01d-f767-4ae2-9ab6-113359c1657f)

Is there a way to mitigate this?

**Comment by yonikid15** [comment]
Duplicate of #3480
