### ISSUE TITLE
Profile text change "About" to "About me"

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#3390]
## Description
Please change the heading of the "About" profile section to "About me". This will make it match the link text on the right as well.

The difference was more noticeable in french. "À propos" should become "À propos de moi"

## Screenshot: Prototype
![image](https://user-images.githubusercontent.com/2494551/179772415-a969a997-767a-4b5d-bf88-0c942ea98bd9.png)

**Comment by mnigh** [comment]
@gobyrne is there a reason the **epic** label was added to this issue?
