### ISSUE TITLE
Formatting inside modal could use some work.

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#3392]
## Description
The formatting on the Diversity and Inclusion modals seems off. @JoshBeveridge will take a look

## Screenshot: Prototype
![image](https://user-images.githubusercontent.com/2494551/179776291-add5ae1d-6251-4af5-b9ef-200c350d9dee.png)

**Comment by gobyrne** [comment]
Probably addressed in #3051

**Comment by JoshBeveridge** [comment]
Dialogs have been updated since this design, so here's Jerbo's latest, which I'll submit a PR for.

![image](https://user-images.githubusercontent.com/6960386/186234297-a92ddffe-64b4-45e1-ad58-b6ec7b0fdc85.png)
