### ISSUE TITLE
Enable 2FA as Mandatory -follow up with the users that are not compliant  

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#3396]
We have currently 9 users not enabled 2FA. We need to review the usage and follow up accordingly .

**Comment by patcon** [comment]
Hopefully this is ok, but this is who is still not enabled:
- [ ] @AMKirouac 
- [ ] @BrookeCameron
- [ ] @mattejackson
- [ ] @MCommonda
- [ ] @RM-1978
- [ ] @RVany

**Comment by gobyrne** [comment]
@brindasasi can you close this now?

**Comment by brindasasi** [comment]
yes we can .. this is done
