### ISSUE TITLE
Github Audit log API integration for alerts 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#3399]
# Description 
Automatically audit account creation, modification, enabling, disabling, and removal actions, and notify appropriate personnel in the event of suspicious activity. 

Use the below API for auditing and set up the alert on chosen events like account creation, modification, enabling, disabling, and removal actions.

https://docs.github.com/en/organizations/keeping-your-organization-secure/managing-security-settings-for-your-organization/reviewing-the-audit-log-for-your-organization

# A/C 

- [x] #5035
- [ ]  Set up alert on activities like account creation, modification, enabling, disabling, and removal actions.

**Comment by gobyrne** [comment]
@brindasasi when should we do this?

**Comment by brindasasi** [comment]
Pretty useful but kind of involved digging into the api and set up notification. Can wait until direct intake delivery imo. But not much longer than that.

**Comment by gobyrne** [comment]
Ok, we're ready on this one @brindasasi , let's tackle next sprint.

**Comment by brindasasi** [comment]
I just realized that in order to work with the API , we needed Github enterprise account.
![Screen Shot 2022-12-13 at 10.27.54 AM.png](https://images.zenhubusercontent.com/61a7bd49e20af80694dd845e/f3687f6a-5089-4439-8f14-55bcb0ba99da)https://docs.github.com/en/enterprise-cloud@latest/admin/monitoring-activity-in-your-enterprise/reviewing-audit-logs-for-your-enterprise/audit-log-events-for-your-enterprise

Apologies on this. I should have encountered this earlier. I don't think we are looking to upgrade anytime soon. Please let me know if I'm wrong on this. 
@gobyrne 
@tristan-orourke

**Comment by patcon** [comment]
Can manually check audit log, just the API that requires $250/user/month enterprise account

**Comment by patcon** [comment]
gray: put in icebox for now

**Comment by mnigh** [comment]
@brindasasi is this issue still relevant or can it be closed as not planned?
