### ISSUE TITLE
Translations for Work Preferences on Profile

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#3402]
## Description
There are several copy and translation fails on Work Preferences section of the Profile. See screenshots and acceptance criteria.

Note that this is all for the V2 of the Work Preferences. Please don't do anything to change V1... we are still using those and have had a few mix ups already.

## List of things to change/fix
- [x] For the copy of the select group on the Work Preference sub-page, update the English to match:
```
I would consider accepting a job that lasts for:
...any duration. (short term, long term, or indeterminate)
...indeterminate duration only. (permanent only)
```
- [x] For the copy of the select group on the Work Preference sub-page, update the French to match:
```
J'envisagerais d'accepter un emploi :
… de toute durée. (à court terme, à long terme ou indéterminée)
… d'une durée indéterminée seulement. (permanent seulement)
```
![image](https://user-images.githubusercontent.com/16977254/179803529-46fa5152-120c-422a-b2ad-ad65274d3095.png)

- [x] From the label of the checkbox group on Work Preference sub-page, removes the word (including ellipsis) "requires..." and replace with just a colon ":"
- [x] On the French version of above remove "exige..." and replace with colon " :" (non-breaking space needed before colons in French)
- [x] Confirm that the checkbox group options on the French page are correctly displaying in French. Right now the first 2 are showing in English.

![image](https://user-images.githubusercontent.com/16977254/179803749-48682ef4-ab01-44e2-a638-278e52885163.png)

- [x] Work preferences summary on the Profile page for the "I would consider accepting a job that lasts for:" section should use the same copy as on the sub-page. For example, right now it says "Permanent duration" on the profile page, but "... only those of an indeterminate duration. (permanent)" on the sub-page select input.  BUT here the catch: We don't want the ellipsis on the summary. Please double check that the changes show up in French too.

- [x] Work preferences summary on the Profile page uses wrong copy for "I would consider accepting a job that". You'll notice that the grammar doesn't work: "I would consider accepting a job that: Availability, willingness..." Instead it should read: "I would consider accepting a job that: requires me to work occasional overtime. For context, those other strings are the ones that should be displayed to managers on the search page. Please also confirm the French options are displaying correctly for this. Currently the English ones are showing up on the French page.

![image](https://user-images.githubusercontent.com/16977254/179805080-2cdc4d6e-d2b8-44cb-92be-89caf38eedc8.png)

- [ ]  Add section to the summary for all the unselected work preferences that user would NOT consider. (as seen in the picture above too)

**Comment by patcon** [comment]
After switching the option label variants to the ones with inline formatting, I'm realizing that it's rendering above, but not properly for the negative framing below. I'll investigate why these aren't working now:

<img width="807" alt="Screen Shot 2022-09-09 at 3 41 25 PM" src="https://user-images.githubusercontent.com/305339/189431045-656d24f3-8a9c-4270-9ab6-89f18fc78311.png">
