### ISSUE TITLE
Equity statements are different on profile and equity pages

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#3408]
## Description

- Equity statements are different on the **profile page** and the **diversity, equity and inclusion page**.
- Equity statements are in a different order on the **profile page** and the **diversity, equity and inclusion page**.

## Screenshots
![Screen Shot 2022-07-19 at 15 44 41](https://user-images.githubusercontent.com/3046459/179836583-9d23b84b-3610-4848-8079-4b942297add5.png)
![Screen Shot 2022-07-19 at 15 44 10](https://user-images.githubusercontent.com/3046459/179836585-218db05c-9389-4e4b-84f4-a78f94a585d4.png)

## Acceptance Criteria
- [ ] Equity statements should be from the same source in every instance
- [ ] Equity statements should be displayed in the same [order](https://github.com/GCTC-NTGC/gc-digital-talent/issues/3408#issuecomment-1189510198) in every instance

**Comment by mnigh** [comment]
@Jerryescandon Could you provide a list of the equity statements (with the correct syntax since there are differences between the two screenshots) and in the order they should be displayed? Thanks in advance!

**Comment by Jerryescandon** [comment]
```
“I identify as a woman”
“I am Indigenous”
“I identify as a member of a visible minority”
“I identify as a person with a disability”
```
