### ISSUE TITLE
Add french keywords to Skill model

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3413]
# Description
Skills currently have Names and Descriptions in French and English, but only a single array of keywords. Split this into two: an array of English keywords and an array of French ones. Make this change to the backend, the API, and modify the admin Skill forms and tables to match.

![Create Skill form.png](https://images.zenhubusercontent.com/5d9ded8fd25901000101f3f0/d2c7489e-5f60-49d9-8d3b-b47b698bdafe)

## Acceptance Criteria
- [x] Modify the graphql schema so that Skill.keywords is a new type with definition `{en: [String!], fr: [String!]}`
- [x] Modify the graphql schema so Skill.keywords can be set properly when creating or updating a skill
- [x] Modify the Skill.php model and the skills table (with a migration) so that localized keywords can be stored
- [x] Modify SkillFactory to generate one random set of keywords, and store it in en and fr with " EN" and " FR" suffixes
- [x] Modify fakeSkills.ts to generate skills in the same way
- [x] Update SkillTable to only show keywords in the current language
- [x] Update CreateSkill.tsx and UpdateSkill.tsx to show two keywords fields, one for each language, and save them properly

**Comment by vd1992** [comment]
I think the acceptance criteria will also need a Migration to update how keywords are stored, correct?

![image](https://user-images.githubusercontent.com/40485260/179851077-05eda21c-36d7-4ab5-920b-e4464053cfe1.png)

**Comment by tristan-orourke** [comment]
@vd1992 

> Modify the Skill.php model and the skills table (with a migration) so that localized keywords can be stored
