### ISSUE TITLE
Search Skills by Keyword should actually use keywords

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3414]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Description

When you "Search Skills by Keyword", the search function should ACTUALLY match skill keywords (in the proper language), not just the skill name.

I think this functionality is in the handleSearch function in the AddSkillsToExperience.tsx component.

## Screenshot: Prototype
[![a screenshot of ...][image]][image-link]
<sup>[Click screenshot to visit Figma.][image-link]</sup>

## Acceptance Criteria
- [ ] If a skill has a keyword, and you enter a fragment of it in the search bar, the skill should appear in the results, even if the name of the skill does not match.
- [ ] If viewing the page in English, only English keywords should be considered. Same for when viewing the page in French.

   [image]: https://user-images.githubusercontent.com/4313717/179849746-4312ba11-707c-4f60-966d-df90dd174a8d.png
   [image-link]: https://www.figma.com/proto/PrvXEDac0HVp7dF7SLWVFm/Candidate-profile-interfaces---V5.0.0?node-id=2340%3A4352&starting-point-node-id=2340%3A4185
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by mnigh** [comment]
@JamesHuf any estimate for this issue?

**Comment by vd1992** [comment]
something else to keep in mind #3498
