### ISSUE TITLE
Offboarding/onboarding Process Checklist 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#3425]
We need to maintain a checklist for both onboarding & offboarding for smooth transition of team members in and out. 

It should be maintained in a common place where it can be easily accessed. 

Possible checklist I could think of 
- Github
- outlook 
- GCDocs
- Phoenix (?)
- Miro 
- Figma 
- Recurrent meeting invites including All staff 
 
A/C 
Prepare the finalized checklist , add it in a common place and the owner of it to keep it updated.

**Comment by petertgiles** [comment]
HR Onboarding:
- PRI
- MyKey
- Peoplesoft
- MyGCPay (4 weeks after hire)
- Benefits (non-casual)

For Devs Only:
- Local environment
- Azure stuff (PC and PS accounts)
- Jira

Offboarding:
- Slack
- Github

**Comment by mnigh** [comment]
@GCTC-NTGC/developers where is the "common place", this repo?

**Comment by tristan-orourke** [comment]
Google docs?

**Comment by petertgiles** [comment]
I think this is a management process, not a dev one.  I don't think it needs to be on the board.
