### ISSUE TITLE
Roles and Permissions for Github Repo

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#3431]
We currently have write permission for every team member in the TalentCloud organization 
It should be moderated and should be permitted with roles and the specific repo they need.

Suggestion would be 

Devs ( Read all / Write for specific repo )
Designers (Read all / Write for specific repo)
Admin ( Read/Write for all )

**Comment by mnigh** [comment]
@brindasasi completed in https://github.com/GCTC-NTGC/gc-digital-talent/issues/5035?

**Comment by brindasasi** [comment]
yes @mnigh we now have moderated permissions . We can close this out.
