### ISSUE TITLE
Skills and Experience block which shows required skills

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3435]
# Description
[Figma Prototype](https://www.figma.com/proto/N9NoPunkqaynjsi89Wrbh0/Direct-Intake---Poster-and-application?node-id=138%3A2905&starting-point-node-id=226%3A4567)

This is the Skills and Experience block component for the Application.

Above the Experience/Skills, missing required skills are listed. The list of required skills comes from the Pool itself.

NOTE: 
- Show only missing skills
- If all skills are somewhere on the profile, remove the entire section.
- Need to Have, Occupational skills are shown
- Need to Have Transferable skills can be ignored
- Nice to Have skills are shown
- The Occupational/Transferable category comes from the skill's SkillCategory.

Note: The Transferable/Occupational category comes from the Skill Family, which skills may have several of. If a skill has zero skill families, list it here. Only  Consider a skill to be Transferable (and therefore unlisted) if it has at least one SkillFamily and all are Transferable.

Required Skills are listed like so:

![image](https://user-images.githubusercontent.com/16977254/180284475-bb61dbd7-d102-4b04-89ea-cbd5e532fb50.png)

# Acceptance Criteria
- [ ] In addition to the props the existing Skills and Experience block accepts, it should accept an array of required skill ids

- [ ] - Show only missing skills
- [ ] - If all skills are somewhere on the profile, remove the entire section.
- [ ] - Need to Have, Occupational skills are shown
- [ ] - Need to Have Transferable skills can be ignored
- [ ] - Nice to Have skills are shown
- [ ] - The Occupational/Transferable category comes from the skill's SkillCategory.

- [ ] Jest tests that confirm, for a given Pool (or required set of skills) and a given set of skills on a profile, the correct Required Skills are displayed.

**Comment by tristan-orourke** [comment]
Some of the logic for distinguishing skill category is done on the Edit Pool page.

**Comment by esizer** [comment]
I believe most of the work for this one was done in #3669 . If I'm correct, it should just need to be extracted out into a separate component.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/34e45b5aa72299541079132b18298cd57468d9d9/frontend/talentsearch/src/js/components/experienceAndSkills/ExperienceAndSkills.tsx#L209-L240

**Comment by yonikid15** [comment]
Completed by #3669
