### ISSUE TITLE
Document how to access server infrastructure 

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3444]
# Description

Write up documentation on how to access and use the platforms required to deploy and monitor releases, and how to access the database.

**Comment by tristan-orourke** [comment]
Here it is! https://docs.google.com/document/d/1zNYTYCTJuSXCPpUQfUfc2cKWqmVLo9efAocWgXt9bBA/edit

**Comment by mnigh** [comment]
This is really great, thanks @tristan-orourke! There is no PR to approve and I haven't gone through step-by-step to try each instruction but it seems very thorough. Did you have a plan to add a link to the document somewhere so that others will know where to access it?

**Comment by brindasasi** [comment]
Link the documents in Read Me  @patcon
