### ISSUE TITLE
Implement sorting in "All candidates" table (Status, Priority should be frozen)

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3449]
As a pool owner I want to view the "All Candidates" table in the pre defined sorting order so that I can review the candidates based on the priority order. 

**For discussion:**
- Status and Priority columns should display lock icon beside its name and clicking on that should not sort the table. Clicking on rest of the columns should sort the table based on that.  ( can we get the icon name? ) 
- Our current setup for Lighthouse sorting requires actual database column names.  Can it use a calculated field?  Maybe server-side sorting will need to be implemented in a different way?

Various fields on the user object cause them to be sorted in different ways.  For example, sort priority should always be given to veterans.  Add a calculated field to the user object that will encapsulate the business logic to provide a sort order that can be used for server-side sorting.

How sorting for user objects should work for "All candidates" admin page (for any given pool). This table:
![image.png](https://images.zenhubusercontent.com/5dc084854553760001149b53/aad87d26-febc-4e51-9777-c1e0b980c34b)

### Second level sorting by Priority
~~For applicants with the same status, they should be sorted in order of "Priority". Priority is a calculated field based on three separate questions that are asked on the profile.~~ This part is complete.

This has been broken into it's own issue #3749.

### Final Sort
For applicants with the same priority oldest applications (the first one to submit their application) should be sorted to the top

**Comment by gobyrne** [comment]
We realised the the veteran and member of CAF fields should be separated out. That will have to happen in the profile as well. But the logic here should be that only "veteran" matters. Member of CAF should be ignored.

**Comment by brindasasi** [comment]
dumb question `unless filter is removed` - how do I remove the filter ?

**Comment by vd1992** [comment]
@petertgiles @brindasasi @esizer 
unless I am missing something, the Lighthouse Directives only allow sorting a column by ascending or descending order
that won't work as there is a very specific order to follow (status NEW goes before all, status APPLICATION REVIEW comes after, that isn't alphabetical 

I think something like a custom resolver using this function might be needed https://www.php.net/manual/en/function.usort.php
then you can manually code all the status comparisons

ie
```
($a, $b)
$a == $b return 0
$a == new return 1
$a == APPLICATION REVIEW && $b == NEW return -1
```
etc

**Comment by esizer** [comment]
> unless I am missing something, the Lighthouse Directives only allow sorting a column by ascending or descending order
> that won't work as there is a very specific order to follow (status NEW goes before all, status APPLICATION REVIEW comes after, that isn't alphabetical

I would look into creating a custom accessor which returns a weighted, numerical value based on the status. i.e.

1. New
2. Under Review
3. Undecided
4. ...

**Comment by vd1992** [comment]
> > unless I am missing something, the Lighthouse Directives only allow sorting a column by ascending or descending order
> > that won't work as there is a very specific order to follow (status NEW goes before all, status APPLICATION REVIEW comes after, that isn't alphabetical
> 
> I would look into creating a custom accessor which returns a weighted, numerical value based on the status. i.e.
> 
>     1. New
> 
>     2. Under Review
> 
>     3. Undecided
> 
>     4. ...

ooh, that is a really good idea

**Comment by gobyrne** [comment]
Much uncertainty about how to approach this. @petertgiles to add notes

**Comment by petertgiles** [comment]
Thoughts on this:
- I like Eric's suggestion to just emit a numeric sort value from the API and hide all the logic on how that sort value is generated.
- I really think this should be implemented with database-driven sorting and filtering.  Loading every row into memory on the server or browser and then filtering and sorting is not a scalable solution for tables that will continually grow with more and more rows.
- The current lighthouse pagination solution in the API requires an actual database column but we want to have a derived value, not a stored one.  That could be very tricky.
  - Should we use something other than the lighthouse pagination?
  - Should we use something like a database view or virtual column?
  - Should we just add some SQL to concatenate on an "ORDER BY (CASE WHEN..."

**Comment by petertgiles** [comment]
Scope changed - just frontend work now.

**Comment by petertgiles** [comment]
Remaining work: clicking on the column header to add a third level of sorting.
