### ISSUE TITLE
Repository missing a description

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#3458]
## Description
The [repository](https://github.com/GCTC-NTGC/gc-digital-talent/) does not have a description.

## Screenshot
![Screen Shot 2022-11-30 at 13 37 36](https://user-images.githubusercontent.com/3046459/204880918-e7b0519d-49e9-4f79-b50e-fcfca46361e1.png)

## Acceptance Criteria
- [ ] add a description for GCTC-NTGC/gc-digital-talent

**Comment by mnigh** [comment]
The description could be something very similar to whatever is used for https://github.com/GCTC-NTGC/gc-digital-talent/issues/3086.

**Comment by tristan-orourke** [comment]
Repository description has been updated to:

GC Digital Talent is the new recruitment platform for digital and tech jobs in the Government of Canada. // Talent numérique du GC est la nouvelle plateforme de recrutement pour les emplois numériques et technologiques au gouvernement du Canada.

**Comment by mnigh** [comment]
@tristan-orourke can you remove the trailing slash from the URL as well?

![Screen Shot 2022-12-22 at 10 44 39](https://user-images.githubusercontent.com/3046459/209170852-228d9565-47bf-473b-9b6b-aefb5ba8c716.png)
