### ISSUE TITLE
H2 front-end parsing 

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/gc-digital-talent#347]
# Notes 
- Currently, Hydrogen's front-end parsing requires the entire H2 attribute to be visible when building. There are some areas within our app that dynamically add properties within the H2 attribute, which need to be replaced to fix this issue (eg. Button component). 

![hydorgen-dos-donts](https://user-images.githubusercontent.com/22059495/129055777-b3baa74e-1614-455b-b346-b5bcaff0c3c3.png)

**Comment by mnigh** [comment]
Any thoughts on how to do this while still being able to limit the [options available](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/admin/resources/js/components/H2Components/Button.tsx#L103) for the Button component? This would also apply to how the [Anchor component would be built](https://github.com/GCTC-NTGC/gc-digital-talent/issues/347) as well.

**Comment by tristan-orourke** [comment]
You know what, this entire issue goes away if we're willing to push the entire compiled CSS file to production.

**Comment by tristan-orourke** [comment]
After discussing extensively with @JoshBeveridge, we think a good compromise is to have H2's optimization script also look for attribute-value combinations in JS objects (eg `{ "data-h2-display": "block" }`) and ensure any dynamic h2 attributes in React components pull them from objects like that.
