### ISSUE TITLE
Equity groups are different on search and equity pages

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#3484]
## Description

- Equity groups are different on the **search page** and the **diversity, equity and inclusion page**.
- Equity groups are in a different order on the **search page** and the **diversity, equity and inclusion page**.

## Screenshots
![Screen Shot 2022-07-25 at 13 40 14](https://user-images.githubusercontent.com/3046459/180840950-ba881b69-46ec-4851-8be8-6cf8dab367a9.png)
![Screen Shot 2022-07-25 at 13 39 39](https://user-images.githubusercontent.com/3046459/180840953-2b0e1ae1-670f-4821-ac64-d8808a4f29aa.png)

## Acceptance Criteria
- [ ] Equity groups should be from the same source in every instance
- [ ] Equity groups should be displayed in the same [order as equity statements](https://github.com/GCTC-NTGC/gc-digital-talent/issues/3408#issuecomment-1189510198) in every instance

**Comment by mnigh** [comment]
@Jerryescandon Could you provide a list of the equity groups (with the correct syntax since there are differences between the two screenshots)? Merci beaucoup!

**Comment by Jerryescandon** [comment]
"Woman"
“Indigenous Identity”
“Member of a visible minority”
“Person with a disability”
