### ISSUE TITLE
Add all classifications to lists in Government Information section

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#3486]
## Description

We are missing the full list of groups and classifications for self selecting dropdown info on the Government Information section.

We should include a full list both in My Profile, as well as the section in the account registration page.

## Screenshot: Prototype

![image](https://user-images.githubusercontent.com/16977254/180863655-755ff0fe-5fe9-4eef-97a6-a879df312a75.png)

## Acceptance Criteria
- [ ] ...

**Comment by petertgiles** [comment]
This is not really a dev issue.  The process is someone will need to log into the admin site and fill in all the details.  I'm not sure where those details will come from, though.

![image](https://user-images.githubusercontent.com/8978655/181020133-a32154ed-75a1-4f94-b7cd-be49c338da0e.png)

![image](https://user-images.githubusercontent.com/8978655/181020292-66f55ab2-2773-454f-9441-d373498e372f.png)

**Comment by Jerryescandon** [comment]
I have moved this to the Design backlog.
