### ISSUE TITLE
Design Polish - Add bold and shadow to headers.

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#3487]
## Description

Add **bold** and a drop shadow to all header titles.

## CURRENT

![image](https://user-images.githubusercontent.com/16977254/180864313-2759c6e1-e2a3-4af6-a8bd-0b5618c61bc0.png)

## NEW AND IMPROVED

![image](https://user-images.githubusercontent.com/16977254/180864831-1fd05fd2-6b1a-4f8b-93d6-5ebd5cb7373b.png)

## Acceptance Criteria
- [ ] Make sure this works on all headers throughout the site.

**Comment by JamesHuf** [comment]
Merged.
