### ISSUE TITLE
User should not be navigated to admin page by default after login 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#3488]
## Steps to Reproduce

- goto talent.canada.ca
- Login with gckey & 2fa

## Expected Result 

- User should be taken to profile homepage 

## Actual Result 

- User is taken to admin page by default and shown an error page 

## Screenshot 

![image (1).png](https://images.zenhubusercontent.com/61a7bd49e20af80694dd845e/70119b62-ba6b-4573-bb6e-f49563a728e9)

**Comment by vd1992** [comment]
possibly triggered here 

![image](https://user-images.githubusercontent.com/40485260/180868631-c27cbafc-01c3-4ec0-9217-1b5b35540d83.png)

config pulled from here  

![image](https://user-images.githubusercontent.com/40485260/180868577-fa91155b-ad8a-421a-b2a1-b5ff9366f14d.png)

**Comment by esizer** [comment]
Not exact duplicates but we have similar issues in #3224 and #3289

**Comment by brindasasi** [comment]
yeah , looks like there is more to this issue. 

- fix navigating to admin by default. instead make it go to profile page for now in this issue. ( #3224 can be closed with this fix) 

- treat #3289 as extension of this solution. Need to go where we came from. But can be worked sep.
