### ISSUE TITLE
🔤 Inconsistent use of punctuation on form labels

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#3492]
## Description
Some radio and checkbox labels end with a period and some do not, including as part of the same set of options.

## Screenshot
![Screen Shot 2022-07-25 at 16 49 17](https://user-images.githubusercontent.com/3046459/180871859-d19d3730-20aa-426f-b14a-e26f7fe0762c.png)

## Acceptance Criteria
- [ ] labels for checkboxes and radio options always end with punctuation if it is a sentence
- [ ] update French copy as needed, as well

**Comment by petertgiles** [comment]
Failed to estimate, might need more discussion on whether labels are full sentences.

**Comment by mnigh** [comment]
The **Government employee information** section form labels for checkboxes and radio options now all end with punctuation if it is a sentence in English and French! This was done as part of #7140 ([merci](https://github.com/GCTC-NTGC/gc-digital-talent/pull/7140#discussion_r1253132671) @petertgiles for 👁️ and @JamesHuf for 🏋️).

## Screenshots

### English
![Screen Shot 2023-12-14 at 10 06 57](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/fedba2ef-46df-4ee0-a916-6d9cf38b789a)

### French
![Screen Shot 2023-12-14 at 10 08 21](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/b48d4de1-ff52-4b42-88d4-f926f719ba0c)

**Comment by mnigh** [comment]
The scope of this issue was very broad and as of now, I can't find any inconsistent use of punctuation on form labels in the profile. Closing this issue as fixed.
