### ISSUE TITLE
Setup for Accessibility testing (storybook for starters)

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#3496]
Gray and patcon felt that storybook was the most appropriate path forward in the short term.

Timeline would be for this work to happen either in the next sprint, or this sprint (PPPRE) if someone finds time.

There were a number of other proposals (opening UAT up to public with or without disabling auth, heroku or other external host) but Gray and patcon both thought they'd present challenges in short-term. Please do chime in if you think differently :)

### Proposed To Dos

- [x] inventory which pages of profile have stories and which don't
- [x] share links with Gray for Fable testing

**Comment by patcon** [comment]
### Proposed To Dos

- [ ] inventory which pages of profile have stories and which don't

**Comment by esizer** [comment]
Going to take a stab at this. Debating an estimate between 3-5, what are your thoughts @patcon ?

**Comment by esizer** [comment]
So, I put together a `UseProfile` story which sets the links using the `hrefTo` function from the recommended addon. It seems to do exactyl what we need it to do but it is not navigating properly. My initial suspicion is that it is related to #3422 . If no one picks this up, I may circle back once that issue has been resolved.

## Example

```tsx
 const [paths, setPaths] = React.useState<Record<string, string> | null>(null);
  const getPaths = React.useCallback(async () => {
    const newPaths = {
      about: await hrefTo("AboutMeForm", "Individual About Me"),
      ...
    };

    setPaths(newPaths);
  }, []);

  React.useEffect(() => {
    getPaths();
  }, [getPaths]);
  
  return (
    <UserProfile
      applicant={fakeUserData as Applicant}
      sections={{
        ...
          about: { isVisible: true, editUrl: paths.about },
        ...
      }}
    />
  );
```

**Comment by esizer** [comment]
@gobyrne These are the links to each story that represent what we currently have for the applicant profiles.

## Links

### Pages

- [User Profile](https://61e099a1bb1465003a73d3ce-rzfdjcyvkz.chromatic.com/iframe.html?args=&id=admin-user-profile--user-profile-null&viewMode=story)
- [Experience and Skills Page](https://61e099a1bb1465003a73d3ce-rzfdjcyvkz.chromatic.com/iframe.html?args=&id=applicantprofile-experienceandskillspage--with-experiences&viewMode=story)

### Forms

- [About Me Form](https://61e099a1bb1465003a73d3ce-rzfdjcyvkz.chromatic.com/iframe.html?args=&id=aboutmeform--individual-about-me&viewMode=story)
- [Language Information Form](https://61e099a1bb1465003a73d3ce-rzfdjcyvkz.chromatic.com/iframe.html?args=&id=language-information-form--language-info-form&viewMode=story)
- [Government Information Form](https://61e099a1bb1465003a73d3ce-rzfdjcyvkz.chromatic.com/iframe.html?args=&id=government-info-form--a-default-args&viewMode=story)
- [Work Location Form](https://61e099a1bb1465003a73d3ce-rzfdjcyvkz.chromatic.com/iframe.html?args=&id=worklocationpreferenceform--individual-work-location-preferences&viewMode=story)
- [Work Preferences Form](https://61e099a1bb1465003a73d3ce-rzfdjcyvkz.chromatic.com/iframe.html?args=&id=workpreferencesform--individual-work-preferences&viewMode=story)
- [Diversity, Equity and Inclusion Form](https://61e099a1bb1465003a73d3ce-rzfdjcyvkz.chromatic.com/iframe.html?args=&id=diversityequityinclusionform--individual-diversity-equity-inclusion-form&viewMode=story)
- [Role and Salary Expectations Form](https://61e099a1bb1465003a73d3ce-rzfdjcyvkz.chromatic.com/iframe.html?args=&id=role-salary-expectation-form--form-empty&viewMode=story)
- [Experience Form](https://61e099a1bb1465003a73d3ce-rzfdjcyvkz.chromatic.com/iframe.html?args=&id=experienceform--individual-experience-form&viewMode=story)

**Comment by gobyrne** [comment]
These look great @esizer. Would it be easy to get the interactive part of the **Diversity, Equity and Inclusion Form** working in storybook? I would like to get that tested.

If that is going to be work, feel free to break it into a separate issue. I intend to immediately start using these links to get the interactive components tested in isolation.

I love that we can use the **Experience Form** to test the skills UI! I'm concerned about accessibility for that one.

**Comment by esizer** [comment]
> Would it be easy to get the interactive part of the **Diversity, Equity and Inclusion Form** working in storybook? I would like to get that tested.

@gobyrne , Got that in with https://github.com/GCTC-NTGC/gc-digital-talent/pull/3636
