### ISSUE TITLE
Inconsistent use of case on Table of Content Navigation 

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#3497]
## Description
Some list items use title case:

- My Status
- My Hiring Pools
- About
- Language Information
- Government Information
- Work Location
- Work Preferences

Other list items use sentence case:
- Diversity, equity and inclusion
- Role and salary expectations
- My skills and experience

## Screenshot
![Screen Shot 2022-07-26 at 12 04 55](https://user-images.githubusercontent.com/3046459/181056192-fe517c39-d08b-43a8-9240-46c4836502fd.png)

## Acceptance Criteria
- [ ] use consistent case for all items

**Comment by gobyrne** [comment]
The whole site needs a case and punctuation audit. How should we approach that?

**Comment by mnigh** [comment]
> The whole site needs a case and punctuation audit. How should we approach that?

Do we have access to a copy editor internally? That would be ideal.

**Comment by petertgiles** [comment]
Closing in preference for  #5810.
