### ISSUE TITLE
Search on "Experience form"

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#3498]
## Description

Hitting ENTER when searching for a skill in the "keyword search" submits the entire form as opposed to just the search results.

It should instead just exit the keyword search and focus on the list of results.

## Screenshot

https://user-images.githubusercontent.com/16977254/181062753-02eda10f-8fc2-4d2e-a901-0585f4e69eb4.mp4

## Acceptance Criteria
- [ ] ...

**Comment by gobyrne** [comment]
Matt suggests something like this:
e.preventDefault()
