### ISSUE TITLE
Profile - Optional Work Preferences checklist label

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#3503]
## Description
The checklist label "I would consider accepting a job that requires…" doesn't make sense when reading the options. For example:
_I would consider accepting a job that requires…...requires me to work occasional overtime._

## Screenshot
![Screen Shot 2022-07-26 at 13 22 08](https://user-images.githubusercontent.com/3046459/181073247-004b050c-a573-4446-9ecf-0f8be3f5b57f.png)

## Acceptance Criteria
- [ ] label copy reads as a full sentence with options

**Comment by mnigh** [comment]
### Possible Solution
Change _I would consider accepting a job that requires…_ to _I would consider accepting a job that…_ and re-translate French version.

**Comment by gobyrne** [comment]
This is covered in #3402
