### ISSUE TITLE
Profile - Required Work Preferences checklist selected

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#3504]
## Description
The Work Preferences form has the option for **...only those of an indeterminate duration. (permanent)** as selected even though the form has not been previously visited and no indication had been made.

## Screenshots
![Screen Shot 2022-07-26 at 13 23 18](https://user-images.githubusercontent.com/3046459/181074912-0f9cffa8-dfe6-4ff1-bd1b-bf4998858128.png)
![Screen Shot 2022-07-26 at 13 23 30](https://user-images.githubusercontent.com/3046459/181074911-7038fa8e-3ab6-4a4c-aebe-19d7381c906c.png)

**Comment by mnigh** [comment]
@Jerryescandon was this on purpose or is this a bug?

**Comment by Jerryescandon** [comment]
I think thats a bug. Should be empty the first time you enter no? cause it's a required field that we want them to fill out.
