### ISSUE TITLE
Empty optional fields should not violate uniqueness validation rules

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#3512]
## Description
Currently, sub is an optional field, with no input it passes in `null`. 
Validation also exists for sub, so attempting to make another user with no sub would be trying to make a second user with sub as `null` which fails validation and would be confusing to understand from a user-perspective. 

This section is probably still a bit in flux so this will be something to keep in mind. 
If sub validation exists, then it is misleading to label it as optional. 
Part of this would also involve more user friendly error messages (toast that _____ field must be unique) which may already be an issue. 

Email too is unique and optional and therefore would cause the same issue. 

## Screenshot: 
![image](https://user-images.githubusercontent.com/40485260/181101007-18dd6dac-4ee8-4ddc-9d20-e374bc47d352.png)

![image](https://user-images.githubusercontent.com/40485260/181099348-bdbb3e9e-516f-458b-a99e-cf54cfcb50fa.png)

## Acceptance Criteria
- [ ] multiple users can be created with empty email and sub fields

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by vd1992** [comment]
error code for graphQL stuff is here #3322

**Comment by tristan-orourke** [comment]
If the laravel validation "unique" rule is causing the issue, it might be fixed by adding "nullable" or "sometimes" rules to the validation.
