### ISSUE TITLE
Deployment - Write HTACCESS throws error

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3513]
There's an error being written out in this step.  It doesn't seem to interfere with deployment but it will block attempts to tighten up error handling.

![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/9c430c89-1ebc-40fd-a384-ebf5b5c6405b)

**Comment by petertgiles** [comment]
Seems like this is happening in the dependencies script, too.

**Comment by patcon** [comment]
Not sure if this is still in sync, but whatever this fix is, could prob use an update here:
https://github.com/GCTC-NTGC/gc-digital-talent/blob/31199440793c8816332b3a96a23bef19450db399/infrastructure/azure-pipelines.noop.yml#L21-L23
