### ISSUE TITLE
LoggedOutPage component contains a broken link

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#3517]
## Description
The `LoggedOutPage` component contains a link that leads to a 404 page:
- https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/talentsearch/src/js/components/loggedOut/LoggedOutPage.tsx#L97

## Acceptance Criteria
- [x] link should go to existing page and not 404
- [x] make link dynamic for current lang value

**Comment by vd1992** [comment]
is this related? I get this in the console

![image](https://user-images.githubusercontent.com/40485260/181316609-b7ad598e-1029-491d-8019-860bf278b91f.png)
