### ISSUE TITLE
Improve Chromatic Automation

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3527]
Our current setup of "run it on demand whenever you want" is not working well for Chromatic.  People usually forget to run it ever and then we're seeing unrelated diffs show up in the snapshots.  Can we find the happy medium?

- Maybe start running it automatically on main for every merge?
- Maybe turn the Merge button yellow?
- Maybe block merges for /frontend until the Chromatic has been manually run once?

**Comment by patcon** [comment]
> Maybe start running it automatically on main for every merge?

```diff
diff --git a/.github/workflows/storybook.yml b/.github/workflows/storybook.yml
index 3adda2fe0..d62db492e 100644
--- a/.github/workflows/storybook.yml
+++ b/.github/workflows/storybook.yml
@@ -13,8 +13,9 @@ on:
 
 jobs:
   deployment:
-    # Never run automatically on first trigger event, only on manual re-run.
-    if: ${{ github.run_attempt > 1 }}
+    # 1. Never run automatically on first trigger event, only on manual re-run.
+    # 2. Always run on main branch.
+    if: ${{ github.ref_name == 'main' || github.run_attempt > 1 }}
     runs-on: ubuntu-latest
     env:
       NPM_VERSION: '8.3.0'
```

**Comment by patcon** [comment]
> - Maybe turn the merge button yellow?
> - Maybe block merges for /frontend until the Chromatic has been manually run once?

CLI tool for setting commit statuses:
https://www.npmjs.com/package/commit-status#cli

(It seems that only success and failure are possible, not yellow warning)

Example usage in workflow:
https://github.com/compdemocracy/polis/blob/dev/.github/workflows/depcheck.yml#L51-L82
