### ISSUE TITLE
Bug - Select component warning for selected

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#353]
### Source of issue
[Select component option code](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/admin/resources/js/components/form/Select.tsx#L64).

### Screenshot
![Screen Shot 2021-08-16 at 12 33 03](https://user-images.githubusercontent.com/3046459/129598221-59423979-0584-4202-8fd5-54759d811497.png)

> Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.

**Comment by yonikid15** [comment]
@mnigh I'm going to wait till #374 gets merged in since it touches the Select component adding a `nullSelection` prop.
