### ISSUE TITLE
Create navigation between profile stories

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#3530]
Spin-off from https://github.com/GCTC-NTGC/gc-digital-talent/issues/3496

Research by Eric: https://github.com/GCTC-NTGC/gc-digital-talent/issues/3496#issuecomment-1195786710

- need to figure out bug in popular storybook addon-link
- no headers or footers needed in new stories for now

### Proposed To Dos

- [ ] Figure out how to allow users to click through links on pages to other pages in Chromatic
- [ ] Put the pages all together for profile

**Comment by petertgiles** [comment]
Now that we can open UAT for testing do we still want to pursue this?

**Comment by gobyrne** [comment]
I guess not. We can always create a new issue if needed. Closing for now.
