### ISSUE TITLE
Setup Automatic Database Backups

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3542]
## Background
Right now we are making manual backups of the database as part of the deployment process.  This protects us in case something goes wrong during deployment (such as a bad migration).  This is good but manual steps are sometimes forgotten.  Also, we should have protection against something going wrong between deployments, too.  We should probably have regular automatic database backups.

## Notes
- IMTD is performing daily backups of our VMs at 8:00 PM Eastern so it would be ideal if a daily backup completed just before then.
- IMTD may be able to set up a dedicated database backup tool someday but VM backups + our database backups will have to do for now.
- Managing our own database backups should allow us to perform a database restore more quickly than IMTD will be able to with the image.

## Questions
- How frequently?  1 hour?  4 hours?  daily?  weekly?
- Retention?  Last 5?  One hourly, one daily and one weekly?
- Method?  pg_dump? pg_dumpall?  something fancy with continous log backups?
- Trigger?  cron?
- Do we have an SLA with our client that determines the answer to these questions?

## AC:
- [ ] Automatic database backups are occurring in prod
- [ ] Restore from automatic backup has been tested on dev or uac

**Comment by patcon** [comment]
some thoughts:
- golang tools are great because they compile to a binary in a very cross-platform way. trying to find a backup tool written in go (or rust even) might be a good starting place. very minor
- not that we should use this, but this was the state-of-the-art tool back maybe 5 years ago (5k github stars). its features are a good indication of what would be good to have in another tool: http://backup.github.io/backup/v4/getting-started/ (it requires ruby, which seems overkill for us to install on OS just for this)

**Comment by patcon** [comment]
> - How frequently? 1 hour? 4 hours? daily? weekly?
> - Retention? Last 5? One hourly, one daily and one weekly?


backup.rb supports the idea of rotations, and felt very robust. So for e.g., that would involve having scripts to write and cleanup:
- "hourly" rotation every hour, keeping 24
- "weekly" rotation ever week keeping 4
- "monthly" rotation every month, keeping 12
- "yearly" rotation every year, kept forever

so worst case for storage, we're keeping 24+4+12 = 40 backups for the current year + 1 for every year, covered very effectively back to the beginning. Decent coverage in case any unnoticed database corruption sneaks in, as that's really the only reason the keep older ones -- to check back once its noticed.

> - Method? pg_dump? pg_dumpall? something fancy with continous log backups?
> - Trigger? cron?

cron seems needed. backup right before deploy also seems prudent.

## Further Questions

- where do we store these? some azure-equivalent to S3? right on our servers? elsewhere?
- do we do a regular restore? if so, how often? on what server?

to answer my own Q: scheduling a regular (weekly?) restore on UAT or some other well-used server also seems prudent.

**Comment by petertgiles** [comment]
>    where do we store these? some azure-equivalent to S3? right on our servers? elsewhere?
    do we do a regular restore? if so, how often? on what server?

In the conversation with IMTD they seemed fine with us doing our database dumps right on the database server, especially since they are so small right now.  This is what I tested [here](https://github.com/GCTC-NTGC/gc-digital-talent/issues/3345#issuecomment-1199774212).

Good idea to regularly practice our restores.  We don't really have a good way to schedule regular exercises right now, as far as I know.  When I did this last week I felt that the "OK, did it actually work" verification step was a little weak so that could use some more thought, too.

**Comment by petertgiles** [comment]
The database tool that IMTD uses but did not set up for us is Commvault.  Here's the page they sent me: https://documentation.commvault.com/v11/essential/87524_postgresql.html

**Comment by patcon** [comment]
> When I did this last week I felt that the "OK, did it actually work" verification step was a little weak so that could use some more thought, too.

We could perhaps find a way to just run the **cypress tests on an automatically restored environment** as part of a restore script? 🎉  Particularly if we can now run nodejs on servers now! 😉

**Comment by petertgiles** [comment]
I just noticed that Laravel has schedule capabilities built in.  Using this instead of cron directly would give us a few benefits:
 - let us keep our jobs in version control
 - add conditional logic
 - use before and after hooks
 - 
https://laravel.com/docs/9.x/scheduling

**Comment by petertgiles** [comment]
Current backups are good enough.  Will icebox until needs change.
