### ISSUE TITLE
Make Pool Key Not Mandatory

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3561]
## Comments
The pool key is currently mandatory for pool creation but it doesn't work well on the Create Pool Advertisement page.  The solution going forward is to make pool key optional (but still unique) so it can be used for the "standard pools" like CMO Digital Careers but not part of the Create Pool Advertisement Flow

## AC
- [ ] DB Migration to make pool key nullable
- [ ] GraphQL Schema Updates to make pool key not mandatory
- [ ] Remove pool key from pool advertisement schema objects (like CreatePoolAdvertisementInput)
- [ ] Admin pool forms -> make pool key not required
- [ ] Admin Create Pool page -> remove key input field

**Comment by vd1992** [comment]
will the "key field" still be around or removed entirely from create pool?

**Comment by petertgiles** [comment]
> will the "key field" still be around or removed entirely from create pool?

Let's leave the key field in the old "pool" models and database tables for backwards compatability.  Anywhere it is left, though, it should be optional.

Let's totally remove it from the new "pooladvertisement" models.

**Comment by tristan-orourke** [comment]
Let's remove the input field from the Create Pool page though.
