### ISSUE TITLE
Consolidate local/prod nginx conf & deploy scripts

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3571]
Split off from #2834 

We now have two nearly ngnix config files: `infrastructure/conf/nginx-conf-deploy/default` and `infrastructure/conf/nginx-conf-local/default`. The former is used by Azure DevOps, the latter by our local dev Docker container. It would be preferable to maintain only a single file. (We could use ENV:APP_ENV as a condition for certain rewrites if we only want them available locally.)

## Screenshot
![image](https://user-images.githubusercontent.com/8978655/217579888-a404e4ee-70e5-4300-89cd-13a77ea6c859.png)

## Possible Implementation
- The setup.sh script could could add debugging lines to a base file
- The post_deploy.sh script could remove debugging lines from a base file (probably less safe)

## Acceptance Criteria
- [ ] A single Nginx conf file works as a base for routing both locally and in Azure

**Comment by patcon** [comment]
Suggested first-step, collapse all our htaccess into one file. This aligned with what needs to happen for nginx (which has no concept of per-folder config)
https://github.com/GCTC-NTGC/gc-digital-talent/issues/3560

**Comment by mnigh** [comment]
@GCTC-NTGC/developers is there still interest in moving ahead with this issue? the two files seem to have quite a few differences between them.

## Screenshot

![Screen Shot 2023-12-13 at 09 40 13](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/4a54533a-a18e-43cc-a708-69b580e569bc)

**Comment by esizer** [comment]
> @GCTC-NTGC/developers is there still interest in moving ahead with this issue? the two files seem to have quite a few differences between them.

Since we do need different configs (i think) I don't think we can get away with having only one file. But, we could have a common file so we don't need to duplicate similar definitions and then use [include](https://nginx.org/en/docs/ngx_core_module.html#include) to add the additional items for each env.

**Comment by tristan-orourke** [comment]
Looks like the differences are...
- enable logging on local
- never cache locally
- a few cases of hardcoding locally when we could use an env variable instead
- extra blocks for local auth, phpinfo and xdebuginfo

**Comment by tristan-orourke** [comment]
Is it really necessary to never cache locally? Especially if we keep cache times reasonably short, eg 1 minute. 

I like @esizer's suggestion of a comment file and include statements for the extra blocks. Would be easier if we referenced env variables on local in the same places we do in the prod script.

**Comment by petertgiles** [comment]
I'd like to continue to keep them separate.  They're never going to match exactly and as long as the two files live close together it's easy enough to diff them and make sure they don't drift apart.  If we start dynamically building them it will just make it harder to read and manage them.

**Comment by tristan-orourke** [comment]
Fair enough. Close for: wise words from @petertgiles
