### ISSUE TITLE
Make Pool Title Required

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#3572]
## Summary

Currently, we have all fields on `createPoolAdvertisement` mutation as optional.

## Problem

This leads to users being able to create an empty pool. The issue being, when using the index page for pools, admins have no context for which pool to edit when there are multiple empty pools. The following screenshot is a representation of when this becomes an issue.

<img width="1224" alt="Screen Shot 2022-08-04 at 10 54 05 AM" src="https://user-images.githubusercontent.com/4127998/182878676-755bdbe3-d502-4438-b5f7-e3b1ce4a7ddc.png">

## Solution

We could make the the `name` field required (present to user as Specific Title). This would provide the needed unique, human readable, identifier and provided much needed context for admins when browsing the pools on `/admin/pools` page.

**Comment by petertgiles** [comment]
Added the design label.  In the current design it is OK to have pools without titles.
![image](https://user-images.githubusercontent.com/8978655/182879975-49f64fad-d075-44a4-a145-2d940fbf45f4.png)

This may be solved when the Job Stream becomes required as that might be the missing identification that is needed but not sure.  Or maybe Specific Title should be required. @Jerryescandon

**Comment by esizer** [comment]
> This may be solved when the Job Stream becomes required as that might be the missing identification that is needed but not sure. Or maybe Specific Title should be required. @Jerryescandon

Possibly, but that design element looks to be a `<select>` which means it lacks the important piece of being **unique**.

**Comment by patcon** [comment]
Hot-take recommendation:
1. add placeholder for each empty field
    - e.g. `<em>not provided</em>`
3. add final column for "Unique ID", to differentiate when needed. make it lower contrast. truncate it like git does.
    - e.g. `<gray>c3750b48...</gray>`

**Comment by Jerryescandon** [comment]
Long story short,  we don't expect DCMO to run a similar process (same group and level + job stream) simultaneously. They will ideally be running only one of each combination at any given time. UNLESS they are running it for something rather specific. (hence the optional title).

So I wouldn't worry too much about the possibility of these looking fairly similar. HOWEVER to decrease the chance of this happening I suggest the following.

- Add the "Specific title"(optional) fields to the new pool creation page. This will promote it's use, but will ultimately fall on DCMO to use it effectively.
- We can also use "date created" for additional identification for these cases.

**Comment by Jerryescandon** [comment]
> Currently, we have all fields on `createPoolAdvertisement` mutation as optional

Can we have them as required? even if they are not used for "new pool" creation?

**Comment by gobyrne** [comment]
@Jerryescandon can you please update the description to reflect the discussion in these comments?

**Comment by Jerryescandon** [comment]
I feel like this bad boy was fixed in https://github.com/GCTC-NTGC/gc-digital-talent/pull/4599
