### ISSUE TITLE
Only run "Docker Smoke Tests" workflow on change to `refresh_*.sh` scripts

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#3573]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Description
The value of the docker smoke tests was highest when we weren't yet running e2e tests, which now run `setup.sh` every commit.

The only value-add of the smoke tests is making sure that the `refresh_*.sh` scripts continue to work. Let's only run them there. (h/t Tristan, who I think suggested this way back.)

## Acceptance Criteria
- [ ] `.github/workflows/docker-smoke-test.yml` only runs when any of the refresh scripts change

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by petertgiles** [comment]
Docker smoke tests not in current CI suite
