### ISSUE TITLE
Add storybook viewports for large desktop screens

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#3576]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

Related: https://github.com/GCTC-NTGC/gc-digital-talent/issues/2651 https://github.com/GCTC-NTGC/gc-digital-talent/pull/3569 https://github.com/GCTC-NTGC/gc-digital-talent/issues/2078

## Description
I reviewed a PR late (after it was merged), and realized the original intent (better support for wide screens) may have been lost in the creation of spin-off PRs from my initial comment. (sorry to not provide feedback in time)
https://github.com/GCTC-NTGC/gc-digital-talent/pull/3569

Original goal of the "large screen" device support was to have (1) large screen size to test in Storybook UI, and (2) the largest screen size snapshot in Chromatic. Whether that conforms to a common screen width feels less important that getting as close to large width monitors as possible (4K = 3840px width) on snapshots and storybook UI viewport selections

Proposal
1. Add "large monitor" viewports for storybook UI (won't work on Chromatic) [reference](https://www.eizo.com/library/basics/eizo_4k_monitors/#:~:text=As%20things%20stand%2C%20the%20majority,referred%20to%20as%204K%20displays.)
    - 4K UHDTV = 3840 x 2160 pixel
    - Full HD = 1920 x 1080 pixels
2. Add a "Chromatic HD (Max Width)" viewport with the top possible on Chromatic
    - 1800 x 1012 px (1.777778 aspect ratio)
3. Use Chromatic HD width in stories where goal is to snapshot HD displays

Reference from Peter:
https://github.com/storybookjs/storybook/blob/master/addons/viewport/src/defaults.ts

```ts
export const CUSTOM_VIEWPORTS: ViewportMap = {
  4k: {
    name: '4K UHDTV',
    styles: {
      height: '3840px',
      width: '2160px',
    },
    type: 'desktop',
  },
  hd: {
    name: 'Full HD',
    styles: {
      height: '1920px',
      width: '1080px',
    },
    type: 'desktop',
  },
  chromaticmax: {
    name: 'Chromatic HD (max width; non-standard)',
    styles: {
      height: '1800px',
      width: '1012px',
    },
    type: 'desktop',
  },
];
```

## Acceptance Criteria
- [ ] large screens have viewport presets in storybook
- [ ] max chromatic width is available in snapshots

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by esizer** [comment]
I'm not sure if this is relevant but, @petertgiles and I discussed this and we wanted there to be some level of compatibility between storybook and chromatic (part of the reason the PR took so long).

That being said, we should look into handling viewports used that are larger than the 1800x1012 supported by chromatic. 

So in the following example, would it make sense to automatically downsize this to `chromaticmax` automatically, or is that too 🪄 magic 🪄 ?

```tsx
const VIEWPORTS = [
  widthOf(INITIAL_VIEWPORTS.4k),
  heightOf(INITIAL_VIEWPORTS.4k),
];
```

**Comment by petertgiles** [comment]
Yeah, I'm still frustrated the configuration is so different and am starting think that combining them is a losing battle.  Perhaps the solution is to decide on a set of Storybook viewports and a set of Chromatic widths and just save them in a well documented common location where they can be referenced from stories.

Deciding on our "standard" sets of viewports and widths should probably be done with the designers and maybe the client, though.

**Comment by esizer** [comment]
> Deciding on our "standard" sets of viewports and widths should probably be done with the designers and maybe the client, though.

I agree, I think this is heavily related to https://github.com/GCTC-NTGC/gc-digital-talent/issues/2651 and maybe discussed there before continuing with viewports until that is decided.

**Comment by patcon** [comment]
heh I just huddled with @esizer as a sanity-check, and just to sync: `{chromatic: { viewports: number[] }}` is an array of two widths for two snapshots -- not an array of `[width, height]` :)

Chromatic doesn't care about height for its snapshots, and just uses whatever height the component takes up. If a component is special-case and needs a specific height, then there's a decorator to force that in a pending PR 🙃  https://github.com/GCTC-NTGC/gc-digital-talent/commit/4d118f259f4ebdabdba846b97f60a12ad2da848a

**Comment by patcon** [comment]
> decide on a set of Storybook viewports and a set of Chromatic widths and just save them in a well documented common location where they can be referenced from stories

here-here! 👍

**Comment by mnigh** [comment]
@esizer is this issue still relevant after https://github.com/GCTC-NTGC/gc-digital-talent/pull/8478 or can this issue be closed?

**Comment by esizer** [comment]
> @esizer is this issue still relevant after #8478 or can this issue be closed?

We are safe to close since we have the viewports updated to match our hydrogen config which are the viewports we support 👍

**Comment by mnigh** [comment]
Closing as resolved.
