### ISSUE TITLE
Pool Advertisement Page Contains Lorem Email

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3583]
What should this email be?  A fixed CMO email or the email of the pool owner or something else?
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/08a81556-7efa-4b37-8b67-5bf53fc4aa47)
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/e905b319-5b9f-4231-b6de-747481c91da4)

**Comment by petertgiles** [comment]
@Jerryescandon

**Comment by Jerryescandon** [comment]
right now:
`recruitmentimit-recrutementgiti@tbs-sct.gc.ca
`

**Comment by petertgiles** [comment]
This should be a parameter to the localized string, too.  We shouldn't have to retranslate the string when the address changes.

**Comment by petertgiles** [comment]
https://github.com/GCTC-NTGC/gc-digital-talent/blob/7575e088b7e616d9298286b3e29694bb25e6bee7/frontend/talentsearch/src/js/talentSearchConstants.ts#L10

**Comment by patcon** [comment]
Alreadt merged
