### ISSUE TITLE
Fix Date discrepancy on Edit Pool page

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3585]
Split off from #3568.

https://github.com/GCTC-NTGC/gc-digital-talent/pull/3568#issuecomment-1205633692

https://talent-cloud.slack.com/archives/C0259G6KXJ6/p1659644285984939

---

## Summary

The use of `<input type="date" />` can cause issues since it uses UTC and does not have the ability to use any other timezone.

## The Issue

Since the date input is forcing us to use UTC, when an admin selects an expiry date it is set to that date at midnight UTC. This results in the expiry date we want (PDT/PST) being the previous day.

### Example

- admin selects date `2022-02-03`
- - date is set to 12:00am UTC
- - converted to PDT this results in `2022-02-02 5:00pm PDT`

### No Library

Right now, we are considering using three separate inputs to set the date rather than a single input.

- number input for year with min value of current year
- select input for month
- number input with max value of 31 and min of 1

#### Note

This will require some level of validation. I believe `date-fns` can be useful here. Possible `isDate` will work here?

### Library

If the three inputs prove difficult, we can research a library to use for picking a date. There would need to be some testing for a11y.

### Acceptance Criteria

- [ ] create new date input component
- [ ] allow users to select date
- [ ] validate the date (don't allow `1200-13-33`)
- [ ] test that the date selected is displayed properly
- [ ] all input[type=date] replaced

**Comment by gobyrne** [comment]
@esizer can you flush out this issue a little? It's not clear to me what needs to be done.

**Comment by esizer** [comment]
> @esizer can you flush out this issue a little? It's not clear to me what needs to be done.

@gobyrne Updated description with some more information based on the slack discussion. Let me know if it needs more detail.

**Comment by petertgiles** [comment]
This issue has a lot of peripheral discussion but if we limit the scope to just the Edit Pool page, it can be closed, I think.

**Comment by mnigh** [comment]
@petertgiles is this still a problem?
