### ISSUE TITLE
Telegraph Pool fields required for publishing better?

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3586]
On the Edit Pool page, all fields are marked as Optional. However, fields are actually required for publishing. Do we want to communicate that to users somehow?

Original discussion:
https://github.com/GCTC-NTGC/gc-digital-talent/pull/3568#issuecomment-1205821393

**Comment by Jerryescandon** [comment]
> On the Edit Pool page, all fields are marked as Optional. However, fields are actually required for publishing. Do we want to communicate that to users somehow?

Are they? I have the majority of them as required on the prototype. The only caveat is that they should allow to "save and go back" even if the required fields are missing.

**Comment by Jerryescandon** [comment]
The one we might need to discuss further is the "Specific title" field.

**Comment by gobyrne** [comment]
I agree with Jerbo. They should say "Required" but validation for it should only be triggered when the user tried to publish. Saving should be allowed with required fields empty.

**Comment by petertgiles** [comment]
Form validation works by making required fields prevent form submission until they are filled.  We have no way to set functionality to "required means required to publish but you can still submit the form without it".

A few options off the top of my head:
1. Use something other than the "required field" tag to communicate fields needed for publishing.
    - Proactively show the list of missing publish fields near the publish button?
    - "Required for publishing" tag or highlight?
2. Save draft changes in the background and make form submission only publish.
3. Only save draft updates if all required fields _in that section_ are complete.

**Comment by vd1992** [comment]
Solved by recent overhauls to edit process page that marks required fields and the complete/incomplete computed value.
