### ISSUE TITLE
Fix Cross-site Scripting (XSS) high severity issue reported by Snyk on Router.tsx

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#3587]
Issue Severity : High
Issue Type:  Code 
Issue Description : 

Below High severity vulnerability  has been detected by snyk in out Router.tsx and needs to be fixed.  
`Unsanitized input from data from a remote resource flows into a React dynamic 'href' attribute, where it is used to dynamically construct the HTML page on client side. This may result in a DOM Based Cross-Site Scripting attack (DOMXSS).
`

Issue Link: 
https://app.snyk.io/org/gctc-ntgc-r4y/project/f850f54c-f7fa-4ae1-98b2-c8bf14a1cd90

![Screen Shot 2022-08-05 at 1 14 58 PM](https://user-images.githubusercontent.com/89482910/183127999-30f45288-5a4b-4054-8ede-25ecdcab7da4.png)

https://github.com/GCTC-NTGC/gc-digital-talent/blob/9cb8c57036caf220b9aab2f16365c8e7df28502e/frontend/talentsearch/src/js/components/Router.tsx#L316

**Comment by mnigh** [comment]
@brindasasi the link in the description (https://app.snyk.io/org/brindasasi/project/772f63b7-fd2f-44a9-8048-bb2bae5b30e2) links to the old **brindasasi** snyk org. Is there a link to the issue for the **gctc-ntgc-r4y** snyk org?

**Comment by brindasasi** [comment]
https://app.snyk.io/org/gctc-ntgc-r4y/project/f850f54c-f7fa-4ae1-98b2-c8bf14a1cd90

**Comment by esizer** [comment]
This could be a false positive.

The `MenuLink` component, by default, uses our `Link` component which does have a helper to sanitize the `href` prop.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/9cb8c57036caf220b9aab2f16365c8e7df28502e/frontend/common/src/components/Link/Link.tsx#L31

## Sanitize Function

https://github.com/GCTC-NTGC/gc-digital-talent/blob/11a1e4dd80668e6f6cc538280e10cc5fb7735362/frontend/common/src/helpers/sanitizeUrl.ts#L1-L35

**Comment by mnigh** [comment]
@brindasasi can you add an ignore flag to this in Snyk?

**Comment by brindasasi** [comment]
This issue is not valid anymore. Snyk code analysis report results as "No issues" on the project.
