### ISSUE TITLE
Build Pipeline - Ubuntu 18.04 deprecated

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3609]
Observed in build logs:
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/cb2142db-b3bf-4169-a0f1-cb297385a378)

**Comment by mnigh** [comment]
Issue referenced:

- https://github.com/actions/virtual-environments/issues/6002

**Comment by mnigh** [comment]
The first brownout is scheduled for October 3, 12:00 UTC - October 3, 14:00 UTC (8am-10am EST).

> To raise awareness of the upcoming removal, we will temporarily fail jobs using Ubuntu 18.04. Builds that are scheduled to run during the brownout periods will fail. The brownouts are scheduled for the following dates and times: https://github.com/actions/runner-images/issues/6002#issue-1325639357
