### ISSUE TITLE
Dep: Bump react-hook-form

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#3633]
## Summary

The latest version of `react-hook-form@7.34.0` introduces some changes to the types. Specifically, they have updated the type for errors which causes issues with out `<InputWrapper />` and `<InputError />` components which accept `error?: string;`. This type is no longer compatible with the type provided by `react-hook-form`.

## Acceptance Criteria

- [ ] Bump dep to `react-hook-form@7.34.0`
- [ ] Resolve type errors with
  - [ ] InputWrapper
  - [ ] InputError
- [ ] Attempt to reintroduce field labels into default error message

**Comment by vd1992** [comment]
appears to have been resolved by 7.35

![image](https://user-images.githubusercontent.com/40485260/197621927-5daf4928-560d-4dc9-844f-98407e12c5a9.png)
