### ISSUE TITLE
🛠️ Add some special cases for Chromatic

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3635]
## 🛠️ Tooling
We've reduced chromatic usage and it's bitten us a few times already.

## 🕵️ Details
I wonder if there's any way we can get chromatic to run automatically if the pr has "storybook" in the name or if something in frontend/common/components is changed.

REF: https://talent-cloud.slack.com/archives/C0259G6KXJ6/p1660051012733749?thread_ts=1659988530.811459&cid=C0259G6KXJ6

## ✅ Acceptance Criteria

The **Chromatic Storybook** GitHub workflow is not skipped in certain scenarios:
- [ ] PRs with `storybook` in the name
- [ ] PRs with `hydrogen` in the name
- [ ] file changes in `packages/forms`
- [ ] file changes in `packages/ui`

## 🛑 Blockers

```[tasklist]
### Blocked By
- [ ] #9304 
```

**Comment by mnigh** [comment]
For running a job based on something like _storybook_ being in the branch name, [here are some docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-branches).

**Comment by petertgiles** [comment]
Or reach or radix

**Comment by vd1992** [comment]
@petertgiles 

Can this be closed? We sort of workaround'd with running it on merges

**Comment by vd1992** [comment]
Sure. I think dependency stuff definitely merits consideration as we've had issues with updates breaking Storybook. 
Not so sure about anything changing component-wise, sometimes in a workflow you might push up changes bit by bit say to resolve testing issues and you don't want Storybook to re-run until things are sorted out.

**Comment by mnigh** [comment]
> I'd like to still leave this up if we can. I think we're getting better about remembering to run and review Chromatic manually but I think it would be better if it could run itself is some scenarios.

@petertgiles What should the acceptance criteria for this issue be then?

**Comment by tristan-orourke** [comment]
Let's take another look at this after #9304

**Comment by mnigh** [comment]
I think this issue can be closed now that TurboSnap has been enabled: https://github.com/GCTC-NTGC/gc-digital-talent/pull/10051. @GCTC-NTGC/developers any reason not to?
