### ISSUE TITLE
Switch search page to classifications as they appear on the profile

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#3639]
Search page should use the same options for classification as on the Roles and Salary expectations page. This is a different model (not the Classification model). This feature is ONLY for the new search page that uses profiles and not for the legacy search.

English copy for select input options:
IT-01: Technician ($60,000 to $78,000)
IT-02: Analyst ($75,000 to $91,000)
IT-03: Technical Advisor ($88,000 to $110,000)
IT-03: Team Leader ($88,000 to $110,000)
IT-04: Senior Advisor ($101,000 to $126,000)
IT-04: Manager ($101,000 to $126,000)

French copy:
IT-01: Technicien(ne) (60 000 $ à 78 000 $)
IT-02: Analyste (75 000 $ à 91 000 $)
IT-03: Conseiller technique (88 000 $ à 110 000 $)
IT-03: Chef d'équipe (88 000 $ à 110 000 $)
IT-04: Conseiller principal (101 000 $ à 126 000 $)
IT-04: Manager Gestionnaire (101 000 $ à 126 000 $)

- [ ] Change the options on the new applicant search.
- [ ] Change how the search works.
- [ ] Add new database field & schema for applicant filter opject.
- [ ] Search uses this new stuff instead of classification
- [ ] Update the filter summary on the request page (after search page)
- [ ] Tests

**Comment by gobyrne** [comment]
We're actually not using the Roles and Salary expectations page anymore (functionally speaking). So this doesn't make sense for now. It could become relevant in the future, so I'll just Ice Box it.

**Comment by mnigh** [comment]
@gobyrne can this issue be closed as not planned then?

**Comment by mnigh** [comment]
> @gobyrne can this issue be closed as not planned then?

@tristan-orourke do you know if this is still a relevant issue?

**Comment by tristan-orourke** [comment]
Closing as not planned. A similar issue may or may not crop up in the future, but that's fine.
