### ISSUE TITLE
Data - Write script to migrate Candidate data from CMO spreadsheet to backend

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#364]
# Description
We want to get existing data on ~150 candidates from a spreadsheet into our database. It should be possible to write a script that converts this to SQL or GraphQL statements which inputs the data directly.

Spreadsheet (headers only): [Candidantes Response via Google Form - Clean.xlsx](https://github.com/GCTC-NTGC/gc-digital-talent/files/7627391/Candidantes.Response.via.Google.Form.-.Clean.xlsx)

**Comment by yonikid15** [comment]
@tristan-orourke Can you post a link to the spreadsheet on here?

**Comment by tristan-orourke** [comment]
Need a graphql script that creats Pool Candidates and their matching Users

**Comment by gggrant** [comment]
After reviewing the spreadsheet, we have determined that the data should be migrated manually. Todo: discuss with CMO.

**Comment by tristan-orourke** [comment]
Closing, since we've decided to do this manually instead.
