### ISSUE TITLE
Make devrobotfam less noisy

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3646]
devrobotfam is very noisy. Suggestions:
- stop Zenhub from posting there
- stop Github from posting there
- stop Azure from reporting DEV deployments

**Comment by petertgiles** [comment]
From #3614

**Comment by tristan-orourke** [comment]
Unsubscribing the github bot on devrobotfam https://talent-cloud.slack.com/apps/A01BP7R4KNY-github?tab=more_info

**Comment by tristan-orourke** [comment]
Removing the zenhub app from slack https://talent-cloud.slack.com/apps/A2GN5QV2M-zenhub?tab=settings&next_id=0

**Comment by tristan-orourke** [comment]
Removing the Azure app https://talent-cloud.slack.com/apps/AFH4Y66N9-azure-pipelines?tab=features

If we do want to have notifications about all azure deployments, it probably makes sense to set up an integration with the newer [Azure Pipelines](https://talent-cloud.slack.com/apps/AFH4Y66N9-azure-pipelines?tab=features) app instead.
