### ISSUE TITLE
Update SingleSearchRequestTable to also accept applicantFilter 

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/gc-digital-talent#3648]
Related: https://github.com/GCTC-NTGC/gc-digital-talent/issues/3016

## Description
Currently, the `<SingleSearchRequestTable />` component is only setup to accept a `poolCandidateFilter`. We need to refactor it to accept either a `poolCandidateFilter` OR an `applicantFilter` so it can show the appropriate table data.  This will require creating another `searchPoolCandidates` query that accepts an `ApplicantFilterInput` in the where clause. Also, in SingleSearchRequest.tsx (where  `<SingleSearchRequestTable />` is called) make sure to filter data from applicantFilter instead of poolCandidateFilter if possible.

If a PoolCandidateSearchRequest contains an applicantFilter instead of a poolCandidateFilter, the request page must use the 2.0 version of the User table, with extra filters and updated style. It must also use the same same search query as the talent-search page 2.0.

## Screenshot: Prototype
[![a screenshot of ...][image]][image-link]
<sup>[Click screenshot to visit Figma.][image-link]</sup>

## Acceptance Criteria
- [ ] SingleSearchRequestTableApi accepts a `poolCandidateFilter` OR an `applicantFilter`
- [ ] If the request has an applicantFilter, the page shows the same users which would have been returned on the Talent Search 2.0 page
    - [ ] Links to the Admin User page with the tabs
    - [ ] Has the nice filters from User Table 2.0
    - [ ] Allows for downloading of user profiles.
- [ ] If a request has a poolCandidateFilter and no applicantFilter, it can be unchanged.

   [image]: https://user-images.githubusercontent.com/4313717/174098348-c22a9852-c598-4ea0-be9f-6837a10df666.png
   [image-link]: https://www.figma.com/proto/XS4Ag6GWcgdq2dBlLzBkay/Admin-v3-(Profile-release)?node-id=410%3A1079&starting-point-node-id=410%3A1984
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by vd1992** [comment]
I am not sure whether acceptance criteria should require it to also work with PoolCandidateFilter as it appears that will be deprecated and removed sometime soon?

![image](https://user-images.githubusercontent.com/40485260/191612370-6e721a49-ebd5-44a5-8791-b5bf5ad08ee8.png)

**Comment by vd1992** [comment]
not sure whether we even have an issue to remove poolCandidateFilter and its associated code yet 

thoughts @petertgiles ?

**Comment by petertgiles** [comment]
> not sure whether we even have an issue to remove poolCandidateFilter

Not that I know of.  :shrug:

**Comment by tristan-orourke** [comment]
Updated the description with description from #3016, which can be combined with this ticket.

**Comment by patcon** [comment]
meeting from yesterday with @yonikid15 and @patcon:
- @Jerryescandon: DCMO will expand or remove filters from the request and save them to find the talent they thing is best for position.
- if manager submits incorrect request, DCMO can change it. whether DCMO requires original for auditability, we don't know

**Comment by patcon** [comment]
convo today with design (@JoshBeveridge @Jerryescandon) and dev (@tristan-orourke @yonikid15 @patcon)
🔒 Slack thread: https://talent-cloud.slack.com/archives/C0259G6KXJ6/p1666720074554459

### Mockup from Jerbo
MVP with warning about filter not saving.

![image](https://user-images.githubusercontent.com/305339/197856300-552f39ff-8d1c-4779-a8c7-03f23ae56ef7.png)
