### ISSUE TITLE
♻️ `educationRequirements` messages, `getEducationRequirement` function not used

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#3649]
## ♻️ Debt
Messages and function to get messages not referenced anywhere in codebase.
- https://github.com/GCTC-NTGC/gc-digital-talent/blob/096f7ef60a01aae77597624eab04142011d72989/packages/i18n/src/index.tsx#L43
- https://github.com/GCTC-NTGC/gc-digital-talent/blob/096f7ef60a01aae77597624eab04142011d72989/packages/i18n/src/index.tsx#L123
- https://github.com/GCTC-NTGC/gc-digital-talent/blob/096f7ef60a01aae77597624eab04142011d72989/packages/i18n/src/messages/localizedConstants.tsx#L268-L286

## Acceptance Criteria

- [ ] unused code no longer appears in codebase

**Comment by mnigh** [comment]
Can this code be removed or is it part of planned updates?

**Comment by tristan-orourke** [comment]
I'd like to resolve #4970 before deciding whether to delete these strings or not.

**Comment by mnigh** [comment]
> I'd like to resolve #4970 before deciding whether to delete these strings or not.

@tristan-orourke #4970 was closed as not planned and #5976 was closed as completed: can these strings be deleted then?

**Comment by tristan-orourke** [comment]
Yeah, if these are still not used anywhere, lets go ahead
