### ISSUE TITLE
Authentication - Add 2FA to our Auth service

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#365]
# Description
Our auth service needs to have 2FA available. Easiest way to do this might be to move from Laravel Breeze to Laravel Jetstream, another pre-built package which includes 2FA.

**Comment by mnigh** [comment]
> I guess this can be closed? We have 2FA with gckey.

@tristan-orourke any reason not to close this issue?

**Comment by tristan-orourke** [comment]
> @tristan-orourke any reason not to close this issue?

Nay!
