### ISSUE TITLE
Remove Docker Smoke Test and Package integrity check yml files from repo 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#3653]
**Description**
We don't get much value out of Docker Smoke Test and Package integrity check in the github actions. 
Hence we stopped in the repo. This issue to remove those yml files from the repo permanently.

**Comment by mnigh** [comment]
@brindasasi Possible duplicate of https://github.com/GCTC-NTGC/gc-digital-talent/issues/3651?

**Comment by brindasasi** [comment]
oopsie daisy
