### ISSUE TITLE
Refactor PoolCandidateStatus to be a computed value

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3659]
## Description
Instead of storing status in the database directory, PoolCandidate.status should be a computed value, based on other fields like `submitted_at` and `expiry_date`.

## Acceptance Criteria
- [ ] Add new statuses to PoolCandidateStatus enum
- [ ] Remove status column from model and database
- [ ] Add new columns to model and database which store timestamps of moving to new status, where required
- [ ] Migrate old statuses - for timestamp just use now (Expired should move to Qualified - Unavailable)
- [ ] Update admin page on profile page (pools section) to allow Admins to change the new statuses. (admins are allowed to set any status)
- [ ] Create accessor on PoolCandidate model which returns a status

**Comment by tristan-orourke** [comment]
| Status | Copy on public |  Programmatically | Has Snapshot | Can be Archived | Can be Deleted | Search results |
| ------- | -------------------- | -------------------- | ---------------- | ------------------- | ------------------ | ------------------ |
| Draft  | "Expires in (time) days" | Yes - default status on application creation| no | no | YES |
| Draft-expired  | "Expired on (date)" | Yes - default status on a draft application past expiry date | no | no| YES |
| New application  | "Submitted and waiting for review"| manual | YES | no | no |
| Application under review  | "Application under review" | manual | YES | no | no |
| Screened in (available)  | "Waiting for assessment" | manual| YES | no | no |
| Screened out - On application| "Application not accepted" | manual| YES | YES | no |
| Under assessment | "Waiting for assessment" | manual| YES | no | no |
| Screened out - On assessment  | "Assessment not passed" | manual| YES | YES | no |
| Qualified - Available  | "Qualified" | manual | no | no| no |
| Qualified - Unavailable  | "Qualified" | manual | no | no| no |
| Qualified - Withdrew  | "Qualified" | manual | no | no| no |
| Placed Casual  | "Completed" | manual | no | no| no |
| Placed Term  | "Completed" | manual | no | no| no |
| Placed Indeterminate  | "Completed" | manual | no | no| no |
| Expired  | "Expired on (date)" | YES - Rule goes here | no | YES | no |

**Comment by tristan-orourke** [comment]
Columns required:
1. submitted_at -> In draft or draft-expired status if this is null
2. under_review_at
3. screened_in_at
4. screened_out_at
5. under_assessment_at
6. screened_in_on_assessment_at -> this puts user in a Qualified Available state
7. screened_out_on_assessment_at
8. unavailable_at
9. withdrew_at
10. placed_casual_at
11. placed_term_at
12. placed_indeterminate_at

Seem to me that if someone runs the mutation to `setState(<status>)`, then we nullify any columns that come later in that list, and set the appropriate date.

Eg if applicant is currently "Qualified Available", and want to set to Placed Casual, we simply add current date to placed_casual_at field.
If applicant is currently "Qualified Available" (screened_in_on_assessment_at), and admin wants to set status to "Application under review", then set columns 3-12 to null and set column 2 (under_review_at) to current time.

**Comment by tristan-orourke** [comment]
@gobyrne why did we move this back to refinery?

**Comment by mnigh** [comment]
> @gobyrne why did we move this back to refinery?

@tristan-orourke or @gobyrne any updates to this issue?

**Comment by tristan-orourke** [comment]
I'm pretty sure this is under review again as we design Record of Decision stuff.

**Comment by vd1992** [comment]
Does #8671 supersede this issue @petertgiles ? Anything to take from this issue or be mindful of?

**Comment by petertgiles** [comment]
I've linked this to the new one.
