### ISSUE TITLE
Add new statuses to PoolCandidate (simple version)

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3660]
## Description
This is a simpler alternative to #3659.

Add new statuses to PoolCandidateStatus enum. We need one status for each state in the following table:
### Status table

| Status | Copy on public (My Applications) |  Programmatically | Has Snapshot | Can be Archived | Can be Deleted | Search results |
| ------- | -------------------- | -------------------- | ---------------- | ------------------- | ------------------ | ------------------ |
| Draft  | "Closes in (time) days" | Yes - default status on application creation| no | no | YES |
| Draft-expired  | "Closed on (date)" | Yes - default status on a draft application past closed date of advertisement | no | no| YES |
| New application  | "Submitted and waiting for review"|  Yes - default when submitting | YES | no | no |
| Application under review  | "Application under review" | manual | YES | no | no |
| Screened in (available)  | "Waiting for assessment" | manual| YES | no | no |
| Screened out - On application| "Application not accepted" | manual| YES | YES | no |
| Under assessment | "Waiting for assessment" | manual| YES | no | no |
| Screened out - On assessment  | "Assessment not passed" | manual| YES | YES | no |
| Qualified - Available  | "Qualified" | manual | no | no| no |
| Qualified - Unavailable  | "Qualified" | manual | no | no| no |
| Qualified - Withdrew  | "Qualified" | manual | no | no| no |
| Placed Casual  | "Temporary placement" | manual | no | no| no |
| Placed Term  | "Completed" | manual | no | no| no |
| Placed Indeterminate  | "Completed" | manual | no | no| no |
| Expired  | "Expired on (date)" | YES - Rule goes here | no | YES | no |

While the PoolCandidate table does have an underlying status column, the model should have a status accessor which adds a bit of logic to the return value:
1. If the PoolCandidate.submitted_at date is null, always return DRAFT or DRAFT_EXPIRED
2. Otherwise, if the expiry_date is passed, and the status is not one of the PLACED/Completed statuses, always return EXPIRED 

## Acceptance Criteria
- [x] PoolCandidateEnum contains an enum for each status in the table
- [x] Status can be manually set to any of the statuses in the table
- [x] If the PoolCandidate.submitted_at date is null, API always returns DRAFT or DRAFT_EXPIRED
- [x] If submitted_at is non-null, and status is NOT Placed Casual, Placed Term, or Placed Indeterminate, then API always returns EXPIRED

**Comment by Jerryescandon** [comment]
Updated "Copy on public" column of table.
