### ISSUE TITLE
Trigger snapshot functionality during Application submission

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3661]
## Acceptance Criteria
- [ ] When application is successfully "submitted", snapshot is created and saved to the PoolCandidate object.
- [ ] Getting the profile data API should return the data with created snapshot json object in it along with the submitted field timestamp

**Comment by esizer** [comment]
I'm not sure if we have a specific method on how we plan on doing this but using an [Eloquent Observer](https://laravel.com/docs/9.x/eloquent#observers) could be useful here.

**Comment by petertgiles** [comment]
I think removing the "test snapshot" functionality from #3707 would be worthwhile to include in the scope of this.  I recommend bumping this up to 3 to include that.
