### ISSUE TITLE
Remove IAP copy of ClientProvider

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3668]
The IAP has its own copy of the Client Provider instead of using the one from Common (or the one from the common ContextContainer.  Lets repoint it to a common component.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/indigenousapprenticeship/src/js/components/ClientProvider.tsx

**Comment by esizer** [comment]
Closed by #4597
