### ISSUE TITLE
♻️ Fully implement the useLocale hook throughout codebase

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#3677]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

Re-ticketed from https://github.com/GCTC-NTGC/gc-digital-talent/pull/3249#discussion_r920089133

## Description
There was interest to try to use hooks more to encapsulate react logic that doesn't make sense to have in our vanilla helper functions as they exist. This is mostly because hooks are intended to allow _use of other hooks_, whereas our vanilla helpers instead accept args that are the _outputs_ of hooks. E.g...

```ts
// current way
const { intl } = useIntl();
const locale = getLocale(intl: IntlShape);

// more react-y way
const locale = useLocale();
// OR (more extensibly)
const { locale } = useLocale();
```

`useLocale()` was added in the above-linked PR, but only used within the scope of the PR. If we'd like to commit to the approach, we should fully migrate.

## Acceptance Criteria
- [ ] all usage of `getLocale` is migrated to `useLocale()`

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by mnigh** [comment]
Team has decided not to go forward with this issue after comments in #7533.
