### ISSUE TITLE
Prevent usage of columns Pool Candidate about to be migrated

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3681]
Before we perform our one-time migration of pool candidate columns we should ensure they don't get repopulated.

## Acceptance Criteria
The following columns in pool_candidates can no longer be populated or changed through the API:
- isWoman
- hasDisability
- isIndigenous
- isVisibleMinority
- hasDiploma
- languageAbility
- locationPreferences
- acceptedOperationalRequirements
- expectedSalary
- expectedClassifications
- cmoAssets

Also delete the pages that use/collect this data:
- create
- update

**Comment by vd1992** [comment]
to refine the acceptance criteria, I believe this involves removing the fields from 
```
input CreatePoolCandidateAsAdminInput
input UpdatePoolCandidateAsAdminInput
```
and then replacing/cleaning whatever breaks from that

**Comment by vd1992** [comment]
@Jerryescandon 
Can you please advise on how the CreatePoolCandidate and UpdatePoolCandidate components should look?

links
[create](https://61e099a1bb1465003a73d3ce-ywxfyjcgcp.chromatic.com/?path=/story/pool-candidates--create-pool-candidate-form)
[update](https://61e099a1bb1465003a73d3ce-ywxfyjcgcp.chromatic.com/?path=/story/pool-candidates--update-pool-candidate-form)

should it just be a matter of removing any inputs mentioned in the issue itself or something more?

**Comment by Jerryescandon** [comment]
I think those two pages will cease to exist, since the information in them will now be accessed otherwise. I recommend we jump into a call to make sure we are all on the same page for this one.

**Comment by vd1992** [comment]
might be best to save this for Sprint planning or something to figure out exactly whether the pages will exist

**Comment by vd1992** [comment]
@gobyrne 

I've shifted this into Product Backlog for your viewing
This is blocking the merging of #3567 
What Create/Update PoolCandidate should look like or whether they need to exist requires decision

**Comment by gobyrne** [comment]
Agree with @Jerryescandon , these pages can cease to exist once we remove the feature flag for direct intake.
