### ISSUE TITLE
My Status radio buttons do not become enabled

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#3686]
Working in Chrome on UAT.

I completed all the sections of my Profile, but the Status section remains disabled.

Expected behavior: The Status section become enabled after completing all required sections of the profile.

![uat-talentcloud.tbs-sct.gc.ca_en_talent_profile.png](https://images.zenhubusercontent.com/5dc084854553760001149b53/b717a145-6819-492b-b765-cce6e550b85f
)

**Comment by esizer** [comment]
@gobyrne Do you remember if it asked you for your citizenship/veteran status? I see we just released 2 days ago which included new fields in order for a profile to be complete (https://github.com/GCTC-NTGC/gc-digital-talent/pull/3564) but I do not see the related fields on the frontend in the About Me section. 

My suspicion is that the backend has the new fields but the frontend is behind (hasn't be built) so those two new fields are not being set.


<img width="978" alt="Screen Shot 2022-08-17 at 9 58 01 AM" src="https://user-images.githubusercontent.com/4127998/185153055-d0e2d738-4c9c-4974-a940-4a70d80ec4e2.png">

**Comment by esizer** [comment]
So @brindasasi was able track this one down. The previous assumption was correct.

## Issue

We recently released a new version to UAT which included #3564 which added the new veteran and citizenship fields to the backend which are required in order for a user's profile to be considered "complete".

Unfortunately, that same release is missing #3664 which includes the form fields to allow users to set these fields. This results in the fields always being null making it impossible to complete your profile.

## Solution

Deploy the changes in #3664 to provide the necessary form fields to complete a profile.

**Comment by brindasasi** [comment]
something to discuss in retro , how to avoid this in future

**Comment by esizer** [comment]
Added to retro board to discuss
