### ISSUE TITLE
Create API end point  to get the data for the All Candidates table

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#3687]
## Description
Create an api end point to retrieve the data for `All Candidates`  table so that admin can review the applicants. 

## Acceptance Criteria
- End point should retrieve the data for below columns
    Status
    Priority 
   Availability
   Candidate Name
   Email
   Preferred Language
  Current Location 
  Date Received 
- If the user is Admin the end point should return the above columns successfully
- If the user is NOT admin , the end point should result in error

**Comment by esizer** [comment]
@brindasasi I may be missing something her but, I was about to work on this issue but think it is already possible under the acceptance criteria with the following query:

```graphql
query PoolCandidates($id: ID!) {
  pool(id: $id) {
    poolCandidates {
      id
      status
      submittedAt
      user {
        priorityWeight
        jobLookingStatus
        firstName
        lastName
        email
        preferredLang
        currentCity
        currentProvince
      }
    }
  }
}
```

## Results

### Anonymous / Non-Admin

<img width="1512" alt="Screen Shot 2022-09-07 at 9 26 09 AM" src="https://user-images.githubusercontent.com/4127998/188890300-54d9978f-677f-4a79-aee0-5d9e9b32a2c2.png">

### Authenticated as Admin

<img width="1512" alt="Screen Shot 2022-09-07 at 9 26 40 AM" src="https://user-images.githubusercontent.com/4127998/188890373-ebc08d8d-2fd6-4b31-af62-383f56429365.png">
