### ISSUE TITLE
Create the "All Candidates" page with the table displayed with the necessary data 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#3688]
Description
All candidates Page should be as displayed as in the figma
https://www.figma.com/proto/b6lDM86QCJQ6iaAh7qrTYH/Admin-v4-(Direct-Intake)?page-id=0%3A1&node-id=1870%3A3055&viewport=3469%2C7991%2C0.82&scaling=min-zoom&starting-point-node-id=1618%3A6064

A/C

1. Below Columns should be displayed 

> Status
> Priority
> Availability
> View
> Candidate Name
> Email
> Preferred Language
> Current Location
> Date Received

2. View Application doesn't do anything in this story 
3. Check box to select all rows or selected rows should work 
4. Paging should work (backend pagination)
5. Clicking on the Columns should display all the columns and selection/deselection in that pop up should reflect in the table 
6. Bread crumbs should be added as per mock up 
7. Go Back button should be added as per mockup

Question 
How about Download CSV ? Should work in this story ? A sep one ? - Yes . Same story. 
We do not need to download status & priority columns

Out of scope 
Sorting logic

**Comment by brindasasi** [comment]
default behaviour of the table

**Comment by JamesHuf** [comment]
The wireframe for this has a text field and button for filters and I'm wondering:
1. Do we actually want filtering for this table?
2. What filters will we want?
3. Is filtering a part of this issue or do/should we have another issue for this?

**Comment by brindasasi** [comment]
filtering should be a sep story.

**Comment by esizer** [comment]
@brindasasi I may be missing something her but, I was about to work on this issue but think it is already possible under the acceptance criteria with the following query:

```graphql
query PoolCandidates($id: ID!) {
  pool(id: $id) {
    poolCandidates {
      id
      status
      submittedAt
      user {
        priorityWeight
        jobLookingStatus
        firstName
        lastName
        email
        preferredLang
        currentCity
        currentProvince
      }
    }
  }
}
```

## Results

### Anonymous / Non-Admin

<img width="1512" alt="Screen Shot 2022-09-07 at 9 26 09 AM" src="https://user-images.githubusercontent.com/4127998/188890300-54d9978f-677f-4a79-aee0-5d9e9b32a2c2.png">

### Authenticated as Admin

<img width="1512" alt="Screen Shot 2022-09-07 at 9 26 40 AM" src="https://user-images.githubusercontent.com/4127998/188890373-ebc08d8d-2fd6-4b31-af62-383f56429365.png">

**Comment by gobyrne** [comment]
Might also close #3687 with this one. Query requires back-end pagination.
