### ISSUE TITLE
Implement sorting in "All candidates" table ( Status , Priority should be frozen)

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#3689]
As a pool owner I want to view the "All Candidates" table in the pre defined sorting order so that I can review the candidates based on the priority order. 

A/C
- Sort order should be #3449

**For discussion:**
- Status and Priority columns should display lock icon beside its name and clicking on that should not sort the table. Clicking on rest of the columns should sort the table based on that.  ( can we get the icon name? )

**Comment by gobyrne** [comment]
We've merged this with #3449
