### ISSUE TITLE
Create the component to display and edit the applicant status in the snapshot page

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#3691]
## Description
As an admin when I click on the view application , snapshot page should open with the applicant status component so that I can review/edit the applicant status. I also want to be able to leave notes about why I changed the status and add an expiry date if it's relevant.

https://www.figma.com/proto/b6lDM86QCJQ6iaAh7qrTYH/Admin-v4-(Direct-Intake)?page-id=0%3A1&node-id=2501%3A3744&viewport=3469%2C7991%2C0.82&scaling=min-zoom&starting-point-node-id=1618%3A6064

## Screenshot

<img width="465" alt="Screen Shot 2022-09-08 at 11 25 47 AM" src="https://user-images.githubusercontent.com/305339/189162416-3e0dae25-cb5f-4242-97f2-79d9318d1add.png">

## Acceptance Criteria
- Applicant pool status values should be pre loaded for selection. Its a `required` column. By default the status would be in `New` (for newly submitted applications)

- Pool status should be the manual values from this table  https://github.com/GCTC-NTGC/gc-digital-talent/issues/3660
          
> New (default value -  covers draft status) 
>           Application under review
>           Screened In (available)
>           Screened Out - On application
>           Under assessment
>           Screened out - On assessment
>           Qualified - Available
>           Qualified - Unavailable
>           Qualified - Withdrew
>           Placed Casual 
>           Placed Term
>           Placed Indeterminate
>           Expired

-  The "Pool Expiry Date" is the same expiry date that we have used in the past for candidates in a pool. It is optional and can always be displayed. (we will revisit this functionality when we refactor statuses, but for now, always showing this field is fine)

- The notes section is a duplicate of the notes section that is provided on the admin view of the candidate (aka applicant) profile. On that profile, there are notes for each pool the person is in and they should be displayed in an editable way here.

- Save Changes should save the applicant status, expiry date (if provided) and the notes section into the db, 

## Dev Notes
 Refer the enums added in #3744 for this implementation

**Comment by brindasasi** [comment]
https://github.com/GCTC-NTGC/gc-digital-talent/issues/3415https://github.com/GCTC-NTGC/gc-digital-talent/issues/3415

**Comment by petertgiles** [comment]
@Jerryescandon it seems like unnecessary complexity to show some statuses directly and map some to different labels (like new for draft).  Would it be acceptable to simply show the statuses as-is?
