### ISSUE TITLE
Hydrogen Upgrade Related Copy Changes

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3694]
Spun off from #3051

- [ ] Add translation code for the new skill accordion label (i.e. This skill has the following related experiences:)
Reverted in [ae5ecf5](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3051/commits/ae5ecf5d2ea7c4e1db0149c0af40b40a55f98cbf)
- [ ] Add translation code for new null text on experience accordions (i.e. No skills have been linked to this experience yet.)
Reverted in [fad5a1f](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3051/commits/fad5a1f6aa8c887100205e8120500e4be82d6aad)
- [ ] Update the label for experience categories in the "filter by type" list so that category names are explicit (e.g. Personal => Personal experiences)
Reverted in [360d9ba](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3051/commits/360d9bad1a93cf0b421da96870a5aceeb5bbebb4)
- [ ] Add translation code for search by keyword label - `frontend/admin/src/js/components/pool/EditPool/AddSkillsToPool.tsx` line 260
Reverted in [04c436c](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3051/commits/04c436c23ed4fbe5ab2760cf8bd12bcb238cd037)
- [ ] Add translation code for multiple labels - `frontend/admin/src/js/components/pool/ViewPool.tsx` lines 377 to 441
Reverted in [44c435e](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3051/commits/44c435e0259563bb82a929944e8e9bf7adafb25e)

**Comment by petertgiles** [comment]
- Since there are just a few strings for this you might be able to get them from Gray.
- Setting to interruption since the strings will have already changed in the Hydrogen PR and gotten disconnected.  They should be fixed before the end of the sprint.

**Comment by petertgiles** [comment]
Changes reverted, no longer urgent interruption

**Comment by JoshBeveridge** [comment]
@petertgiles / whoever takes this task on, do you mind if I sit in and watch? I'd like to learn more about our string implementation so that I can effectively make changes on my own moving forward.

**Comment by petertgiles** [comment]
I asked Gray for French for these strings.

**Comment by petertgiles** [comment]
Gray would prefer if the translation team handle this.  This issue should be completed along with a round of translation so that we don't lose strings on "live" parts of the site.

**Comment by petertgiles** [comment]
Sent strings to Nathan Golden for translation.  Out of office until Sept 6.

**Comment by petertgiles** [comment]
Response from Nathan Golden:

Here is the requested translation. You’ll notice that for four of these bullets, two translations are possible, depending on what you mean by the English text. Don’t hesitate to contact me if you need further clarification.

Bonne journée!

NG

•	This skill has the following related experiences:/Cette compétence possède les expériences connexes suivantes :
•	No skills have been linked to this experience yet./Aucune compétence n’a été liée à cette expérience jusqu’à présent.
•	Filter by/Filtrer par ordre de…
•	Search by keyword/Chercher par mot-clé
•	Your impact/Votre incidence
•	English impact text/Texte ayant une incidence sur l’anglais (if the text itself has an impact on the English text) OR: Texte anglais sur l’incidence (English text that talks about the impact)
•	French impact text/Texte ayant une incidence sur le français (if the text itself has an impact on the French text) OR: Texte français sur l’incidence (French text that talks about the impact)
•	English work text/Texte de travail en anglais OR: (if by “work text” you mean that it’s a “draft”, then the French should be: Ébauche du texte en anglais
•	French work text/Texte de travail en français OR: (if by “work text” you mean that it’s a “draft”, then the French should be: Ébauche du texte en français
