### ISSUE TITLE
Table not refreshed on successful creation of new item (on empty list)

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#3705]
## Description

After creating a new item in an empty table, the user gets redirected back to the table, but the table itself does not get refreshed (cached value does not update), meaning the new item does not appear. 

urql has some documentation on [cache updates](https://formidable.com/open-source/urql/docs/graphcache/cache-updates/#updating-lists-or-links) that work involving updating the cached lists (tables) after the create mutation is finished. However, writing out these updates for every mutation seems like alot of work for such a small edge case.

Video example of the issue:
https://recordit.co/c7aWXrPao9

**Comment by yonikid15** [comment]
Waiting till Tristan gets back to see if has any insight on this.

**Comment by tristan-orourke** [comment]
What tables has this been seen on? I'm having trouble reproducing this on admin tables.

**Comment by Jerryescandon** [comment]
When I saw it I was adding skills to the UAT but that now has a LOT which makes it hard to see again. But yesterday we tested the live site with Maddy and after she tried adding one experience to her profile, the save and go back didnt update the table either, so it looked empty, but after a reload it appeared. I suspect is the same bug.
