### ISSUE TITLE
Selecting a skill on the experience form should not jump away to added field.

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#3708]
## Description

When selecting a skill from the tab component in an experience form, the focus changes immediately to the newly created field on the step below. we should not change he focus at all and let the user keep working on the current component.

## Screenshot: Prototype
![image](https://user-images.githubusercontent.com/16977254/185479619-1fc3efd6-6503-44f2-9499-910672cfeb09.png)
- [ ] ...

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by gobyrne** [comment]
Eric says: Have to make sure we find all other uses of this component so we can ensure we don't mess up those other ones.
