### ISSUE TITLE
Menu shows both skills and skill families selected in admin

### ISSUE THREAD

**Issue by JamesHuf** [GCTC-NTGC/gc-digital-talent#3711]
The side menu highlights both the 'Skills' and the 'Skill Families' items when on the admin pages for skill families.
![image.png](https://images.zenhubusercontent.com/61d4c65971f41272c88f9a81/e3d71778-3671-4b2f-9494-25480787c76a)

**Comment by gobyrne** [comment]
I think this is desired behaviour? @Jerryescandon ?

**Comment by Jerryescandon** [comment]
> I think this is desired behaviour? @Jerryescandon ?

Not really, I'm not sure what's going on there. they are just two different tables as far as I understand.

**Comment by gobyrne** [comment]
I missed the word "Selected". Of course we don't want both selected, my bad.
