### ISSUE TITLE
Memory Leak in LanguageInformationForm.tsx

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#3740]
**Problem** 
Memory leak error on profile page after editing language info form in profile.![185641408-e0329387-bd52-446a-980f-e4f7f35a1099.png](https://images.zenhubusercontent.com/61a7bd49e20af80694dd845e/1a94ed90-6912-4704-9b1b-1f10693fad02)

related PR : https://github.com/GCTC-NTGC/gc-digital-talent/pull/3051

**Comment by petertgiles** [comment]
I had no luck with this one.  :disappointed:   My best guess is that it has to do with the navigate function in router.tsx but I'm really not sure.

**Comment by esizer** [comment]
Should be closed by #4597 but would like confirmation from someone. Our old `useLocation` hook was causing memory leaks and that was replaced so this **shouldn't** be an issue anymore and I can no longer reproduce on that PRs branch.

**Comment by petertgiles** [comment]
> I can no longer reproduce on that PRs branch.

Agreed.  I also can't replicate it on that branch any longer.  :+1:
