### ISSUE TITLE
Form inputs do not match up in height (text, date, select)

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#3743]
Form inputs do not match up in height (text, date, select)
ex.
![image (2)](https://user-images.githubusercontent.com/89482910/185968678-11b93048-4b70-4e78-9d6b-a68bc56b88a6.png)
But the issue exists site wide 

A/C 

All form inputs should have consistent height

**Comment by gobyrne** [comment]
@JoshBeveridge did our H2 update clean this up?

**Comment by mnigh** [comment]
@esizer was this resolved as part of #6895?
