### ISSUE TITLE
Update choices on "Member of the Canadian Armed Forces" question

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#3747]
## Description

We need to separate the responses available in the CAF question in the about me section of the profile

New options:

```
I am not a member of the CAF
I am an active member of the CAF
I am a veteran of the CAF
```

### OLD

![image](https://user-images.githubusercontent.com/16977254/186173881-860bb44a-7c53-4807-8606-7e2ef6facbb4.png)

### NEW 

![image](https://user-images.githubusercontent.com/16977254/186173845-54bea92f-2732-4e18-a964-3ed59a0250ea.png)

## Acceptance Criteria
- [ ] Update the schema to include the new option 
- [ ] Migration for the field 
- [ ]  User should be able to update and edit the options

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by gobyrne** [comment]
I don't think this content is translated yet, but please let me know if you need translations.
