### ISSUE TITLE
Increase table scroll affordance when table width exceeds screen real estate

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#3748]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Description
Certain tables have a tendency to exceed the available width of the viewport, and this creates a horizontal scrollbar that provides access to the rest of the table. It's not immediately obvious in some cases that this is possible, so the intent is to add a visual indicator to tables when a scrollbar is available that will make it clearer.

### Optional ideas that would benefit from design/dev feedback
- adding visible helper text?
- providing context on the SHIFT + scroll keyboard shortcut? (not sure if this is universally applicable across OSes / browsers)
- adding an icon?

## Screenshot: Prototype
![image](https://user-images.githubusercontent.com/6960386/186172915-751d312a-8864-4b26-9e01-e3e9491da4f5.png)

## Acceptance Criteria
- [ ] a shadowed pseudo/child element should appear on the right-hand side of the table when the width of the table exceeds the width of its parent wrapper
- [ ] the shadowed element should appear/disappear when the screen is resized IF the table's wrapper becomes large enough to display the whole table
- [ ] position it within the table's parent, on top of the table so that it fills the height of the parent, and about 10% of the width
- [ ] the shadowed element should use `pointer-events: none;` to avoid conflicting with table elements/buttons
- [ ] we might want to add screen-reader only text in the same fashion that indicates the table is scrollable when it first becomes focused

## Context
From @esizer 
>I think it could be similar to our hook to determine screen size and render it if that is true.
>
>You can change it to be:
>`div.scrollWidth > div.clientWidth`
>
>https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/common/src/hooks/useIsSmallScreen.ts

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by JoshBeveridge** [comment]
@Jerryescandon can you take a peek at the "Optional ideas" section and let me know if anything stands out as a good idea?

**Comment by gobyrne** [comment]
Tables have been reworked. Closing
