### ISSUE TITLE
Create calculated "Priority" field on user object

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#3749]
Broken off of #3449

For applicants with the same status, they should be sorted in order of "Priority". Priority is a calculated field based on three separate questions that are asked on the profile.

These are the three questions:
**From the "About Me" page:**
![image.png](https://images.zenhubusercontent.com/5dc084854553760001149b53/05111357-7ca1-4ce7-8676-4dbe62d7cf29)
![image.png](https://images.zenhubusercontent.com/5dc084854553760001149b53/90251ab6-190e-4842-86a9-6899ff71692d)

**From the "Government information" page:**
![image.png](https://images.zenhubusercontent.com/5dc084854553760001149b53/a5ba4659-ccc4-4c4c-a675-9a0a4253d58a)

This is the logic for calculating the **Priority** column (don't necessarily code it this bad though)....
If "i have a priority entitlement" return Priority
else (
  If "I am a veteran of the CAF" return Veteran
  else
    return citizenship_status (citizen, permanent resident or Other)
)

Sort order should be

1. Priority
Veteran
Citizen or Permanent resident (no sorting between these 2... unless that too complicated, then citizen can be first)
Other (Jerbo listed this as "work visa" on the table, but you can just leave it as "Other" instead)

**Comment by brindasasi** [comment]
Probably a Mutator - which is used to set the computed values during update
OR Accessor - to calculate while retrieving can be used? 
Team to discuss on it & come up with an idea.

**Comment by vd1992** [comment]
@brindasasi @petertgiles 
Peter mentions in the issue this is split off of that #3449 

> Question: Our current setup for Lighthouse sorting requires actual database column names. Can it use a calculated field? Maybe server-side sorting will need to be implemented in a different way?

this could pose a problem, if a calculated field is unsortable, then how this issue is resolved must be mindful of that, alternatively verify a method exists to sort with calculated fields

**Comment by vd1992** [comment]
deployment label attached because solution ended up sliding from Accessors to GENERATED columns
