### ISSUE TITLE
Bug: Edit Pool Test Periodically Fails

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#3751]
## Summary

The edit pool jest test periodically fails when run as part of our `.github/workflows`.

## Error

REF: https://github.com/GCTC-NTGC/gc-digital-talent/runs/7523418060?check_suite_focus=true

```sh
> admin@1.3.2 test
> jest

FAIL src/js/components/pool/EditPool/EditPool.test.tsx (46.963 s)
  ● Edit Pool tests › should have save buttons that emit a save event when the status is draft

    thrown: "Exceeded timeout of 5000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      27 |
      2[8](https://github.com/GCTC-NTGC/gc-digital-talent/runs/7523418060?check_suite_focus=true#step:7:9) | describe("Edit Pool tests", () => {
    > 2[9](https://github.com/GCTC-NTGC/gc-digital-talent/runs/7523418060?check_suite_focus=true#step:7:10) |   it("should have save buttons that emit a save event when the status is draft", async () => {
         |   ^
      30 |     const handleSave = jest.fn();
      31 |     const props = {
      32 |       ...EditPoolStory.args,

      at src/js/components/pool/EditPool/EditPool.test.tsx:29:3
      at Object.<anonymous> (src/js/components/pool/EditPool/EditPool.test.tsx:28:1)
```

## Possible Issue

We are wrapping `fireEvent` in `act`. By default `@testing-library` wraps `fireEvent` in `act`. It is only necessary to wrap in `act` when there is a state change.

### Recommended Use

```tsx
import {render, screen, fireEvent} from '@testing-library/react'

const Button = ({onClick, children}) => (
  <button onClick={onClick}>{children}</button>
)

test('calls onClick prop when clicked', () => {
  const handleClick = jest.fn()
  render(<Button onClick={handleClick}>Click Me</Button>)
  fireEvent.click(screen.getByText(/click me/i))
  expect(handleClick).toHaveBeenCalledTimes(1)
})
```

REF:

- https://testing-library.com/docs/dom-testing-library/api-events/#fireevent
- https://davidwcai.medium.com/react-testing-library-and-the-not-wrapped-in-act-errors-491a5629193b

**Comment by vd1992** [comment]
I made this #3697 
But this one has a possible solution, so I will close mine in favour of yours

**Comment by patcon** [comment]
Potential resolution in https://github.com/GCTC-NTGC/gc-digital-talent/pull/3795

The issue is just that we're doing a lot of heavy async user actions in the test (these happen implicitly, even without `act()`) , which take awhile.

Our options are:
1. bump the timeout and leave the test unaltered for now, or
2. split the test into 7 individual ones

I'm in favour of (1), but mostly just because there's already a PR for it 🙂 ☝️ ☝️ 

If we really want, we could still spawn an issue to split up long-running jest tests.

---

> ## Possible Issue
>
> We are wrapping `fireEvent` in `act`. By default `@testing-library` wraps `fireEvent` in `act`. It is only necessary to wrap in `act` when there is a state change.

Using act() is unrelated, but still something to deal with non-urgently. It would get dealt with as part of an existing rule if we implemented using the existing eslint plugin. For existing issue, see https://github.com/GCTC-NTGC/gc-digital-talent/issues/3794

**Comment by patcon** [comment]
As noted in https://github.com/GCTC-NTGC/gc-digital-talent/issues/3794#issuecomment-1231910136, removing this redundant use of `act()` will not make tests run faster, and in fact might run longer. But I think that's a good thing, as the advice of Kent C Dodds seems pretty unambiguous that we need not be doing this :)

**Comment by esizer** [comment]
> As noted in [#3794 (comment)](https://github.com/GCTC-NTGC/gc-digital-talent/issues/3794#issuecomment-1231910136), removing this redundant use of `act()` will NOT make tests run faster, and in fact might run longer. But I think that's a good thing, as the advice of Kent C Dodds seems pretty unambiguous that we need not be doing this :)

Removing `act()` was not intended to speed tests up, just that it is unnecessary since `fireEvent` is already wrapped in `act()` and is discouraged unless there is an intentional state change as a result of the event.

We also need to keep in mind, that we have some of our render functions wrapped in `act()` since it is required to properly test any page that includes `react-hook-form`. 

SEE: https://github.com/GCTC-NTGC/gc-digital-talent/pull/3068#issue-1271354684

> 2\. split the test into 7 individual ones

I would be in favour of this since we are using jest to create unit tests and having one test cover 7 different cases goes against the philosophy of unit tests. I think if we plan on covering that many test cases this should be moved to cypress and be an e2e test.
