### ISSUE TITLE
Remove "Request" link from navigation bar

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#3752]
## Description

While it's ok to have a direct url to access the request page, we should not encourage or direct people to get to this page on its own since most fields on the request will be empty.

We should remove the request link from the navigation on pages .../search and .../request

![image](https://user-images.githubusercontent.com/16977254/186230918-d56c4839-19a8-420e-af96-e78f46973c38.png)

## Acceptance Criteria
- [ ] Request link is gone from navigation on talentsearch

**Comment by mnigh** [comment]
@Jerryescandon good catch. the devs were talking about the **Request** page itself and how a user can submit a request without any of the required fields (at this point, only group and level is required). which of the following should we do to restrict these types of requests:

1. hide the Submit Request button if the required fields are empty
2. disable the Submit Request button if the required fields are empty
3. hide the Request Form and Summary of filters section and show a message with a link to the Search page
4. other

**Comment by Jerryescandon** [comment]
Ouuuhh I like #3 the best but I'm guessing we are gonna miss a design for this. Let me take a stab at something and bring it back to you.

**Comment by mnigh** [comment]
@Jerryescandon I've created a new issue for the empty request part so that we can go ahead and remove the navigation link in the meantime:

- https://github.com/GCTC-NTGC/gc-digital-talent/issues/3958
