### ISSUE TITLE
Migrate existing users to new profiles

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#3753]
The intent of this work is to migrate existing users that DCMO have added to the database into the new profiles/user tables. The goal is so that they can still be searchable and DCMO can continue to manage them through their pool candidate tables. The profiles will no longer be editable by anyone and there will be no Sign in Canada account associated with them (thus no way to change them going forward). That is all ok.

TODO:
Gray to provide mapping between old and new fields.

**Comment by petertgiles** [comment]
Possibly completed in #3567?

**Comment by gobyrne** [comment]
Ok, seems like it is a duplicate!
