### ISSUE TITLE
Fancy filter changed to  maroon theme after merging with main 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#3756]
**Problem**
It used to be on standard blue theme. However after merged to main , it got switched to old maroon theme. 
![Screen Shot 2022-08-24 at 2.29.09 PM.png](https://images.zenhubusercontent.com/61a7bd49e20af80694dd845e/ee45e23a-131b-491c-9f3e-7e9aaa4c3bad)

**Comment by gobyrne** [comment]
merged
