### ISSUE TITLE
Separate Development code base from Production like code base ( Master Branch )  to be able to do trackable emergency releases ( hotfixes) 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#3791]
### Problem

Currently we treat our Main branch as dev codebase and use the same for making releases. 
Main branch code base currently always ahead of production release version. Hence for any urgent production issue we won't be able to release from our Main Branch. 

Example: 
After  V1.1.1 release , we had a big merge with Hydrogen upgrade branch with Main branch.So main is far ahead of production version code. 
At this time we found an issue with Production environment on IAP home page. 
Now we could not merge the fix with the main and do the next release since hydrogen changes have not been tested in UAT environment yet. 
We decided to do a hotfix based off v1.1.1 but we could not merge back to Main since we have more advanced code. So we had to release from the bug fix branch and did not tag that hotfix. 
After fixed prod env., we applied the hotfix on Main. So next release (v1.1.2) would have that. 

Problem here is the  hotfix went without the tag and wouldn't be able to track or recreate that version of codebase in future. This is a very minor hotfix literally one line of change. But regardless this process could become a headache in future when we find more production issues. 

### Solution 

Option 1: Maintain Master branch that has production version of codebase.
When hotfix is created merge it with both Master and Main. 
So the Master will have all the tagged versions in the released order and anytime we could spin off the specific release version. 

Option 2: Fix the issue in Main. Tag it. Cherry pick only that commit to release. No maintenance of Master Branch.  In this way we cant spin off the exact version of previous releases even with that tag. But atleast the hotfix releases are tagged now.

**Comment by brindasasi** [comment]
up for team discussion

**Comment by petertgiles** [comment]
It would be nice to be able to apply small fixes to the version released to UAT without going all the way to the head again.

**Comment by tristan-orourke** [comment]
This is pretty easy, as long as we tag all our releases. If you need an emergency release, just create a release branch which branches off main at the last tagged commit.
