### ISSUE TITLE
Implement sorting on My Applications Dashboard page 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#3807]
Sort the applications by status. 
Refer the status table here https://github.com/gctc-ntgc/gc-digital-talent/issues/3415#issuecomment-1199836280

**Comment by esizer** [comment]
This is done but may not be sorted properly.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/c2f9d6dad99a6a834f451c1b127c70bd6cf87534/frontend/talentsearch/src/js/components/applications/maps.ts#L42-L58

**Comment by petertgiles** [comment]
Eric has sorted this already in the order of the table provided.  Issue completed.
