### ISSUE TITLE
Estimated Candidates on the home page listed as 0 even though candidates are there in the table

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#3810]
### Problem

After  v1.1.2 deployment to UAT `Estimated Candidates`  on the home page listed as 0. 

### Root cause 

The [PR](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3744 
)  updated some existing pool candidate statuses but missed migration for updating existing records. 

### Solution 

Create a migration to update the status of existing candidates

**Comment by petertgiles** [comment]
I solved this issue on UAT.  It didn't have anything to do with the UatSeeder, I think.  It was just that the search only brings up candidates with the QUALIFIED_AVAILABLE status now and our candidates in UAT weren't in that status.  I changed them all over so it works now.
![image (1)](https://user-images.githubusercontent.com/8978655/188155161-7a75a87a-713e-4434-82a3-1f309c693e23.png)
I recommend not merging the branch in the associated PR.
