### ISSUE TITLE
Create manual seeders for user testing on UAT

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#3816]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

Re-ticketed from related issue https://github.com/GCTC-NTGC/gc-digital-talent/issues/3810

## Description
We'll need a [public] environment for user testing that more closely resembles real interfaces/content for user testing. The current random faker seeders are not user-friendly for this.

Related: https://github.com/GCTC-NTGC/gc-digital-talent/issues/3496 (storybook approach for smaller user tests)

**Pre-requisites** to this work:
- [ ] confirmation that UAT can be open to public for user testing

Peter suggested creating a few (5?) hand-tuned users to manually seed on UAT.

## Acceptance Criteria
- [ ] there are 5 (?) hand-created users in a seeder

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by petertgiles** [comment]
I've asked the SiC team about using shared preset GCKey accounts on the test server.  Will post an update when I get a response.

**Comment by petertgiles** [comment]
Mustapha (with the SiC) team agrees with the premise of disabling MFA for the UAT server and setting up some shared test users.

**Comment by petertgiles** [comment]
For an unrelated issue Doug suggested this account:
Userid: signincanada
PW: Pass1234

**Comment by mnigh** [comment]
Would like to do this, but uncertainty on priority.

**Comment by mnigh** [comment]
@petertgiles is there still a desire to do this after removing `UserSeederUat.php` as part of https://github.com/GCTC-NTGC/gc-digital-talent/pull/8299? if so, can a @GCTC-NTGC/developers update the acceptance criteria to something more specific than  "there are 5 (?) hand-created users in a seeder"?

**Comment by petertgiles** [comment]
I think UAT is working well right now so I don't want to mess with it.  I think the CiSeeder is working well for "clean room" testing, too.
