### ISSUE TITLE
bring GovernmentInfoFormPage in line with other profile forms

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#3817]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Description
I noticed this while reviewing the Application PR, this appears to be introducing some weirdness. It plays well from the /profile side of things but doesn't mesh well when navigating to a form from the Application component
Ought to be brought in line with the other forms in what parameters it takes and how it executes its mutation

example of the mismatch here in Router.tsx
https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/talentsearch/src/js/components/Router.tsx#L151

## Acceptance Criteria
- [ ] bring it to parity with the other forms in the router
- [ ] adjust form component as needed to fit the above change
- [ ] ensure it properly submits from /profile path as well as /apply path

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by gobyrne** [comment]
@vd1992 says:
>  it appears that issue should probably be closed since things have changed quite a bit and the code it references no longer is present
