### ISSUE TITLE
🛠️ `intl-extract` doesn't work on Windows

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3821]
It seems like sometimes running the intl-extract script on Windows (not WSL, not Docker) emits an emtpy en.json file.  I'm not totally sure how consistently this happens or why.

**Comment by JamesHuf** [comment]
You can work around this by shelling into the maintenance container:

1. Shell into the maintenance container with `docker-compose run --rm maintenance bash`
2. Navigate to the folder you want to run the command for. `cd /var/www/html/frontend/admin` for admin.
3. Running `npm run intl-extract` should work now.

**Comment by mnigh** [comment]
@petertgiles @JamesHuf is this still an issue post #5065?

**Comment by JamesHuf** [comment]
It's still an issue for me (as well as php commands like seeding) though the workaround also still works so it's not a big problem. I think @vd1992 is still running non-wsl windows as well so he might have more input.

**Comment by mnigh** [comment]
> It's still an issue for me (as well as php commands like seeding) though the workaround also still works so it's not a big problem. I think @vd1992 is still running non-wsl windows as well so he might have more input.

I wonder if it is related to the glob pattern and the use of single quotes.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/bade5dccc884171baf496de78119e4966d200c2f/apps/web/package.json#L12

@esizer would this work: https://github.com/formatjs/formatjs/issues/3345?

**Comment by esizer** [comment]
> @esizer would this work: [formatjs/formatjs#3345](https://github.com/formatjs/formatjs/issues/3345)?

It should! Also, when I was trying to migrate to yarn, it was complaining about the hash at the end not being in quotes which also could be a problem for Windows.

**Comment by mnigh** [comment]
@GCTC-NTGC/developers does anyone still work on non-wsl windows? if not, can this issue be closed?

**Comment by petertgiles** [comment]
I don't think we want to shut out non-wsl Windows as a platform, even if none of the current developers use it, so I'd like to keep it open. That said, I think we can ice it.

**Comment by JamesHuf** [comment]
This appears to be working for me now.
