### ISSUE TITLE
Print link on users table shows "hand" icon even though link is disabled

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3824]
CSV link behaves correctly though.

In UAT:

![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/4d06934f-9d2a-4d49-a3cd-b4a89110c841)

Acceptance Criteria:
- [ ] Remove "disabled" attribute from link (in all scenarios)
- [ ] If no rows are selected and the link is click, put up a toast notification (see text below) and do nothing else.
- [ ] Update the link to say "Download Profiles" "Télécharger les profils" instead of "Print"

English:
"No users selected"
French:
"Aucun utilisateur sélectionné"

**Comment by petertgiles** [comment]
@Jerryescandon If we hide the link then how will user know to select rows?  How should it look if there are no rows selected?  a11y concerns?  How are non-sighted people going to know how to use it?  

Attribute disabled is not valid for links.

**Comment by Jerryescandon** [comment]
🤔 
I feel like we might need a different approach, maybe a toast notification when clicking these when no rows have been selected?
@JoshBeveridge any ideas on this one?

**Comment by JoshBeveridge** [comment]
Yeah, totally agree - it should be active if no rows are selected, but prompt the user to let them know what's up and then fail.
