### ISSUE TITLE
Docker container running different version of postgresql than prod server

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#3827]
## Description
We are running postgresql 13.2 in our [docker container](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/docker-compose.yml#L4), but on our prod server we are running postgresql 12.11.

## Screenshot
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/d5e7f299-9eaa-48ce-a421-e671762c7218)

## Acceptance Criteria
- [x] Docker container running same version of postgresql as prod server (12.11)

**Comment by petertgiles** [comment]
gctalent=# select * from pg_extension;
  oid  | extname  | extowner | extnamespace | extrelocatable | extversion | extconfig | extcondition
-------+----------+----------+--------------+----------------+------------+-----------+--------------
 14173 | plpgsql  |       10 |           11 | f              | 1.0        |           |
 23423 | pgcrypto |       10 |         2200 | t              | 1.3        |           |
(2 rows)
