### ISSUE TITLE
Elements must have sufficient color contrast

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#3831]
## Summary

Ensures the contrast between foreground and background colours meets WCAG 2 AA contrast ratio thresholds (4.5:1)

## Locations

https://github.com/GCTC-NTGC/gc-digital-talent/blob/759d780c3dbde4012aac0b96515f1b5dacb0334d/frontend/common/src/components/form/Select/SelectFieldV2.tsx#L183-L185

https://github.com/GCTC-NTGC/gc-digital-talent/blob/759d780c3dbde4012aac0b96515f1b5dacb0334d/frontend/admin/src/js/components/pool/EditPool/StatusSection.tsx#L153-L161

https://github.com/GCTC-NTGC/gc-digital-talent/blob/759d780c3dbde4012aac0b96515f1b5dacb0334d/frontend/admin/src/js/components/pool/EditPool/StatusSection.tsx#L153-L161

https://github.com/GCTC-NTGC/gc-digital-talent/blob/759d780c3dbde4012aac0b96515f1b5dacb0334d/frontend/admin/src/js/components/pool/EditPool/StatusSection.tsx#L218-L226

https://github.com/GCTC-NTGC/gc-digital-talent/blob/759d780c3dbde4012aac0b96515f1b5dacb0334d/frontend/admin/src/js/components/pool/EditPool/StatusSection.tsx#L91-L99

https://github.com/GCTC-NTGC/gc-digital-talent/blob/759d780c3dbde4012aac0b96515f1b5dacb0334d/frontend/admin/src/js/components/pool/ViewPool.tsx#L168-L181

https://github.com/GCTC-NTGC/gc-digital-talent/blob/759d780c3dbde4012aac0b96515f1b5dacb0334d/frontend/admin/src/js/components/poolCandidate/PoolCandidatesTable.tsx#L164

https://github.com/GCTC-NTGC/gc-digital-talent/blob/759d780c3dbde4012aac0b96515f1b5dacb0334d/frontend/admin/src/js/components/user/GeneralInformationTab/GeneralInformationTab.tsx#L342-L368

https://github.com/GCTC-NTGC/gc-digital-talent/blob/c8ff1a196d4275a58269f4273774e165366ee676/frontend/talentsearch/src/js/components/search/SearchPools.tsx#L31-L42

https://github.com/GCTC-NTGC/gc-digital-talent/blob/c8ff1a196d4275a58269f4273774e165366ee676/frontend/talentsearch/src/js/components/request/CreateRequest.tsx#L318-L333

https://github.com/GCTC-NTGC/gc-digital-talent/blob/c8ff1a196d4275a58269f4273774e165366ee676/frontend/talentsearch/src/js/components/pool/PoolAdvertisementPage.tsx#L123-L128

https://github.com/GCTC-NTGC/gc-digital-talent/blob/c8ff1a196d4275a58269f4273774e165366ee676/frontend/common/src/messages/commonMessages.ts#L24-L28

**Comment by petertgiles** [comment]
part of this issue will work with designers to pick updated colours
