### ISSUE TITLE
Skill Pickers on Talent Search Missing Skill Definition and elsewhere - update graphQL queries

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3864]
Vachan noticed that the skill picker on talent search is not getting skill definition:

things are a bit different for the separate skill pickers

on admin, edit pool
![image](https://user-images.githubusercontent.com/40485260/188750261-c3b65c53-d001-4403-af76-c2a5c1c274b5.png)

on talent search
![image](https://user-images.githubusercontent.com/40485260/188750297-f11482d6-d2f2-4cc0-85eb-a67598e3cca1.png)

this appears to be due to the difference in these queries

the one for edit pool, it calls description
https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/admin/src/js/components/pool/EditPool/editPoolOperations.graphql#L101

the one for talent search, it does not call description
https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/talentsearch/src/js/api/poolCandidateOperations.graphql#L49

_Originally posted by @vd1992 in https://github.com/GCTC-NTGC/gc-digital-talent/issues/3858#issuecomment-1238715474_

ACCEPTANCE CRITERIA

- [ ] update graphQL query for Talent Search page
- [ ] update graphQL query for /pool/:id/view page

**Comment by vd1992** [comment]
`/pool/:id/view` is also having similar issues
appears to be the same matter, the graphQL page is not requesting a `description`

![image](https://user-images.githubusercontent.com/40485260/189236152-31ade455-b1fa-43c1-8953-fef06646e9e0.png)
