### ISSUE TITLE
Make search page "Classification Filter" limited to 1 classification

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#3870]
The search page currently uses a multiselect for the Classification filter. DCMO has asked to instead limit this to a single selection. It will make it easier to handle candidates on their end, and the user can just fill it out multiple times if they want more classifications.

Please make the change on both current and new search pages (I think we have the other one behind a feature flag).

**Comment by brindasasi** [comment]
I believe this already has been implemented in  https://github.com/GCTC-NTGC/gc-digital-talent/pull/3537
