### ISSUE TITLE
Testing - Write E2E tests for the submit application flow

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/gc-digital-talent#3873]
## Description

Write some E2E tests for when an applicant submits an application. Before writing the tests we should seed a new test applicant that can submit an application, so a *completed profile* and *all the essential skills* for one of the seeded pools. 

## Acceptance Criteria
- [ ] Seed a new test applicant where their profile is complete and has the essential skills for one of the seeded pools.
- [ ] Write E2E tests for submitting an application from start to finish:
    - applicant signs in -> applies for pool -> reviews application -> submits application -> returns to my applications page.

**Comment by brindasasi** [comment]
failure testcase will be implemented later

**Comment by patcon** [comment]
yo here's that pending branch for those cypress tests (it's branched off vachan's branch bc that's where it started, so might look bigger than it really is): https://github.com/GCTC-NTGC/gc-digital-talent/tree/3085-cypress-tests
