### ISSUE TITLE
Create a job advertisement #1

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#3877]
- [x] Build the site
- [x] Test the specified scenario
- [x] Feel free to use a variety of OS and browser combinations
- [x] Create bug issues on the board for any bugs encountered
- [x] Leave a note in this issue of the test path you followed for other testers to refer to

**Comment by brindasasi** [comment]
Could not create a pool in Dev environment. I get internal server error. Works fine in local with latest main though.

**Comment by brindasasi** [comment]
Development server fails to create pool. 
Rootcause : pool_status column is not null in Dev DB. 
I couldn't figure out why. I see an migration for having a default value "NOT_TAKING_APPLICATIONS".  Possible that migration failed (?) 
![dev](https://user-images.githubusercontent.com/89482910/192635661-48f28d2e-1ba4-451c-b50f-350532457bcc.PNG)

**Comment by brindasasi** [comment]
Verified UAT & Prod has the right value 
![prod-pools](https://user-images.githubusercontent.com/89482910/192636858-3bba75e7-ad75-4fd2-a4b2-df3bebc5d566.PNG)

**Comment by brindasasi** [comment]
### Issues

https://github.com/gctc-ntgc/gc-digital-talent/issues/3974

**Comment by brindasasi** [comment]
### Pool Creation 

1.  Draft Pool Creation 

1. Create a Skill Family 
2. Create a skill 
3. Click on pools from side nav bar
4. Click on "+ Create Pool"
5. In the new pool page , select a classification 
6. Click Save 
Assertion : Pool created successfully toast message should pop up and the page should be redirected to edit pool page.

**Comment by brindasasi** [comment]
`After publishing the pool , observe the pool dashboard for pool status column should be changed to "TAKING_APPLICATIONS"` is not working in UAT as well
