### ISSUE TITLE
Create a job advertisement #2

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#3878]

**Comment by petertgiles** [comment]
## Setup
- Checked out main at a392254242b11014ff202b6918748b001fed6747
- Reran setup.sh to "blank slate"
- Testing using Firefox 105 on Linux

## Steps
1. Logged in as "admin@test.com"
1. Navigated to localhost:8000/en/admin
1. Clicked "Pools" in the sidebar and clicked the "Create Pool" button
1. Selected "IT-01" and clicked "Create new pool"
1. Moved to "Pool name and target classification" section
1. Selected stream "Security", Titles "Test EN" and "Test FR", Process Number "1234", and clicked "Save pool name".  Observed "Pool updated successfully!" toast.
1. Moved to "Closing date" section
1. Selected End Date as the end of the month and clicked "Save closing date".  Observed "Pool updated successfully!" toast.
1. Moved to "Your impact" section
1. Entered "Test EN" and "Test FR" for "Your impact" and clicked the "Save introduction" button. Observed "Pool updated successfully!" toast.
1. Moved to "Work tasks" section
1. Entered "Test EN" and "Test FR" for "Work tasks" and clicked the "Save work tasks" button. Observed "Pool updated successfully!" toast.
1. Moved to the Essential skills section
1. On the "Technical skills" tab, selected the "Cyber security" skill group and then beside "Intrusion Technology" clicked "Add skill".  Observed the skill now has the purple check mark and a new chip shows below. Clicked the "Save essential skills".  Observed "Pool updated successfully!" toast.
1. Moved to the Asset skills section.
1. On the "By keyword" tab, typed "emp" and then beside "Empathy" clicked "Add skill".  Observed the skill now has the purple check mark and a new chip shows below. Clicked the "Save asset skills".  Observed "Pool updated successfully!" toast.
1. Moved to the Other requirements section.
1. Entered "Bilingual advanced" for Language requirement, "Top secret" for Security requirement, left Location as "Specific location", Entered "Test EN" and "Test FR" for Specification Locations, set "Publishing group" to "IT Jobs".  Clicked the "Save other requirements".  Observed "Pool updated successfully!" toast.
1. Refreshed browser and observed that all fields were preserved.
1. Clicked Publish, observed the given Closing Date, clicked "Publish pool".
1. Observed that I was returned to the pools table and my new pool was there.

## Bugs filed:
- #4273
