### ISSUE TITLE
Apply to a job advertisement

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#3879]
- [x] Build the site
- [x] Test the specified scenario
- [x] Feel free to use a variety of OS and browser combinations
- [x] Create bug issues on the board for any bugs encountered
- [ ] Leave a note in this issue of the test path you followed for other testers to refer to

**Comment by brindasasi** [comment]
### Issues
https://github.com/GCTC-NTGC/gc-digital-talent/issues/4162

**Comment by brindasasi** [comment]
have a confusion on when do I see Archive application and when do I see delete application ? 
@Jerryescandon

**Comment by Jerryescandon** [comment]
you can only delete applications that have not been submitted. (draft or draft expired)
you can archive applications that have been submitted and also have either A) expired or B) screened out. 
you can NEITHER delete NOR archive applications that are submitted and are currently waiting for assessment.

**Comment by brindasasi** [comment]
> you can only delete applications that have not been submitted. (draft or draft expired) you can archive applications that have been submitted and also have either A) expired or B) screened out. you can NEITHER delete NOR archive applications that are submitted and are currently waiting for assessment.

Makes sense @Jerryescandon .. Thank you!

**Comment by brindasasi** [comment]
Assertions

- [ ]  Creating a pool with expiry tmo should allow candidates to apply 
- [ ] Creating a pool with expiry today should allow candidates to apply ( Not working as there is a bug with UTC date conversion ) 
- [ ]  Creating a pool with expiry date yesterday should not allow it to publish 
- [ ] Changing the published pool expiry date to yesterday should not allow the candidate to apply 
- [ ]  Draft pools should not be listed in Browse pools page 
- [ ]  Applicant can create a draft application for an opportunity by clicking from Browse Opportunities  
- [ ]  Applicant can delete the draft application 
- [ ]  Applicant can submit the application 
- [ ]  Applicant can archive the screened out application 
- [ ]  Applicant can archive the application with expired status 
- [ ]  Applicant should not see Archive for any other status than the above two 
- [ ]  Archived Applications section should show the archived applications if available when expanded. By default it should be collapsed

**Comment by brindasasi** [comment]
Closing as the issues are created and given for review
