### ISSUE TITLE
Complete the profile without applying to a job

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#3880]
- [ ] Build the site
- [ ] Test the specified scenario
- [ ] Feel free to use a variety of OS and browser combinations
- [ ] Create bug issues on the board for any bugs encountered
- [ ] Leave a note in this issue of the test path you followed for other testers to refer to

**Comment by petertgiles** [comment]
- Checked out main at [ae5af54](https://github.com/GCTC-NTGC/gc-digital-talent/commit/ae5af54975e427688019293bc1ad128fad07b4c1)
- Reran setup.sh to "blank slate"
- Testing using Firefox 105 on Linux

- Navigate to localhost:8000/en/talent/profile
- Log in as "newuser"
- Fill in the "Create Account" form and save
- Click "Edit About Me", change the form, save, observe the "saved" toast, review new fields
- Click "Edit Language Information", change the form, save, observe the "saved" toast, review new fields
- Click "Edit Government Information", change the form, save, observe the "saved" toast, review new fields
- Click "Edit Work Location", change the form, save, observe the "saved" toast, review new fields
- Click "Edit Work Preference", change the form, save, observe the "saved" toast, review new fields
- Click "Edit Diversity, Equity, and Inclusion", add the options, go back, review new fields
- Click "Edit Role and Salary", change the form, save, observe the "saved" toast, review new fields
- Observed the "Your profile is now complete" toast
- Click "Edit Skills and Experience", add some skills, click go back, review new fields
- Change status to "Actively looking"
- Observe "My Status updated successfully" toast

Bugs filed:
- #4086 
- #4087
- #4088
