### ISSUE TITLE
Manual Test: Submit a search request #2

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#3885]

**Comment by esizer** [comment]
## Environment

- **OS**: MacOS 12.6 (21G115)
- **Browser**: Safari 15.6.1 (17613.3.9.1.16)

## ⬆️ Setup

1. Checkout `main`
2. Run `setup.sh`

## 📋 Steps Taken

1. Navigate to `/search`
2. Filled out the following filters:
    - Classification: AS-04
    - Education: Can accept a combination of work experience and education
    - Operational requirements: Availability, willingness and ability to work shift-work.
    - Work location: BC, Atlantic
    - Working language ability: Any language (English or French)
    - Employment Duration: Any duration
    - Employment equity: Disability
    - Skills: none
3. Confirmed the candidate count updated with filter changes
4. Confirmed selected filters resulted in the expected 1 candidate
5. Confirmed the results near the bottom of the page toggled between "We can still help" and "Request Candidates" when number changed from 0 to more than 0
6. Confirmed "Request candidates" button directed to the appropriate page with all set filters present in confirmation
7. Confirmed cannot submit form with no required fields
8. Confirmed cannot submit with improperly formatted email address
9. Confirmed toast appeared when submitted and redirected back to search

## 🐛 Noted Bugs

Only apparent bugs encountered already have exisiting issues:

- https://github.com/GCTC-NTGC/gc-digital-talent/issues/3958
- https://github.com/GCTC-NTGC/gc-digital-talent/issues/3628
