### ISSUE TITLE
Submit a search request #3

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#3886]

**Comment by petertgiles** [comment]
## Setup

- Checked out main at a392254242b11014ff202b6918748b001fed6747
- Reran setup.sh to "blank slate"
- Testing using Firefox 105 on Linux

## Steps
1. Log in as "admin@test.com"
1. Clicked "Search" in the header
1. Observed there were 25 candidates by default
1. Selected Classification filter "AS-02" and observed there were now 19 candidates
1. Selected Education of "Required diploma..." and observed 7 candidates
1. Selected CoE option "... overtime (regularly)" and observed 3 candidates
1. Selected Work location of "National Capital" and observed 2 candidates
1. Selected Working language of "English only" and observed 2 candidates
1. Selected Employment Duration of "Indeterminate" and observed 2 candidates
1. Selected Employment equity of "Visible minority" and observed 2 candidates
1. For skills, selected "By keyword" tab, typed "post" and added PostgreSQL and observed 1 candidate
1. Scrolled to the bottom and clicked the "Request Candidates" button
1. On the request page, reviewed the filter summary to ensure it matched selections
1. Filled in the contact info, clicked "Submit Request" and observed the "Request created successfully" toast.

Bugs filed:
# #4276
