### ISSUE TITLE
Manual Test: View a submitted search request #1

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#3889]
- [ ] enable DIRECTINTAKE flag
- [ ] Build the site
- [ ] Test the specified scenario
- [ ] Feel free to use a variety of OS and browser combinations
- [ ] Create bug issues on the board for any bugs encountered
- [ ] Leave a note in this issue of the test path you followed for other testers to refer to

**Comment by vd1992** [comment]
attempting to view my submitted request from #3884 
candidate view does not work as ApplicantFilter does not do anything on the page, it is setup for PoolCandidateFilter

need to complete issue #3648 

![image](https://user-images.githubusercontent.com/40485260/191866185-64a4ee87-3387-4e8d-a5ea-b2ad2744f488.png)
