### ISSUE TITLE
View a submitted search request #2

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#3890]

**Comment by petertgiles** [comment]
## Setup
- Checked out main at 424ef6f56beb613a856bdbdc31cc1eff90c02bb4
- Reran setup.sh to "blank slate"
- Testing using Firefox 105 on Linux
## Steps
1. Logged in as "admin@test.com"
1. Navigated to localhost:8000/en/admin
1. Clicked Requests in the sidebar, clicked "View request" through the list until I found a request that had been seeded with some candidates.  Observed that it showed a "Pending" status.
1. Updated the Personal Notes field and clicked "Save Notes".  Observed a "Notes saved successfully!" toast.
1. Clicked the "Mark this request as done" button. Observed a "...set to done" toast.
2. Clicked the "Back to all results" button and observed that my row shows a "Done" status

## Bugs filed:
(none)
