### ISSUE TITLE
Start an application then delete it

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#3891]
- [ ] Build the site
- [ ] Test the specified scenario
- [ ] Feel free to use a variety of OS and browser combinations
- [ ] Create bug issues on the board for any bugs encountered
- [ ] Leave a note in this issue of the test path you followed for other testers to refer to

**Comment by petertgiles** [comment]
- Checked out main at ae5af54975e427688019293bc1ad128fad07b4c1
- Reran setup.sh to "blank slate"
- Testing using Firefox 105 on Linux

1) Navigate to `localhost:8000/en/talent/profile`
1) Log in as `applicant@test.com`
1) Click on "Edit Role and Salary"
1) Select "Level 1: Technician" and the "save and go back"
1) Verify "My Status" shows "Actively Looking"
1) Click "Browse opportunities"
1) Click "CMO Digital Careers"
1) Click "Apply for this process"
1) Verified that I got an "Application created" toast
1) Click "Go back to my applications"
1) Noticed the application with links for "continue my application" and "delete".  Clicked delete.
1) In the modal, clicked "Delete" again.
1) Noticed that the application is gone from the list

- No bugs found
