### ISSUE TITLE
direct intake placeholder pages need completion or removal

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#3899]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Description
they seem kind of forgotten and could do with updating or removal 

the index page that lists them could use with a little pretty-ing
the second page does not seem to do anything now that `pool/:id/view` exists and probably should be removed

## Screenshot: Prototype
browse pools index page
![image](https://user-images.githubusercontent.com/40485260/189237294-0d9e38b3-082e-412b-9118-25fc63c3c189.png)

page when you click on a pool from the list
![image](https://user-images.githubusercontent.com/40485260/189237325-c2d46940-c2c8-4f97-bbe3-58a727df0fbc.png)

## Acceptance Criteria
- [ ] resolve /view placeholder problem
- [ ] resolve /apply placeholder problem

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by vd1992** [comment]
the second page is rendered obsolete by this 
![image](https://user-images.githubusercontent.com/40485260/189237658-50ff8072-3206-4b84-9b65-27c334b7e49e.png)

**Comment by vd1992** [comment]
@gobyrne 
I think this is probably important to the completion of Direct Intake?

**Comment by gobyrne** [comment]
The Browse pools page will get rebuilt alongside the homepage revamp. So leave that for now.

I agree the we shouldn't have links that go to broken pages. So the second link should probably be removed, or, even better, just get it to forward to the /view page.

**Comment by vd1992** [comment]
> The Browse pools page will get rebuilt alongside the homepage revamp. So leave that for now.
> 
> I agree the we shouldn't have links that go to broken pages. So the second link should probably be removed, or, even better, just get it to forward to the /view page.

I liked @esizer 's suggestion to get rid of the /view altogether and have the poster component completely replace that second link one

**Comment by vd1992** [comment]
one other page to fix

![image](https://user-images.githubusercontent.com/40485260/189722727-638ad65e-cd6a-4cb5-ae19-68cb6200e9dd.png)
