### ISSUE TITLE
Missing or incorrect translations

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#3909]
@gobyrne is making this list of missing translations to make sure they don't get missed in the next batch.

- [x] The priority, veteran and citizenship fields are not translated - BUT I expect that's just because they were just deved and haven't been sent to translation yet.
- [x] #4197
- [ ] "Add skill" on the skill picker is translated to "Ajouter une compétence". This is essentially "Add a skill".  (@Jerbo can we change to "Add this skill / Ajouter cette compétence"?)
![image.png](https://images.zenhubusercontent.com/5dc084854553760001149b53/b25505bd-7175-40cc-9a66-67b298d47223)
- [x] The location exemption text is not translated on the location profile subpage. This one is old, so not sure why it's been missed. (the text is currently not set up for translation but will be addressed along with its placeholder text: https://github.com/GCTC-NTGC/gc-digital-talent/issues/3991#issue-1376405212)
![image.png](https://images.zenhubusercontent.com/5dc084854553760001149b53/5f26edbb-bfe8-4338-b7ec-c96ef5f4e45f)

**Comment by petertgiles** [comment]
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/d3e3ae06-6109-4fdc-8414-d0076dc25052)

**Comment by mnigh** [comment]
The "request" text in Admin is not currently set up for translation:  
- https://github.com/GCTC-NTGC/gc-digital-talent/issues/4118

**Comment by mnigh** [comment]
Create Account > Message after main heading in create account page

![Screen Shot 2022-09-28 at 12 49 07](https://user-images.githubusercontent.com/3046459/193095541-2911d5d0-0d04-49f0-b6e9-9c25835a9eeb.png)

**Comment by brindasasi** [comment]
![image (8)](https://user-images.githubusercontent.com/89482910/193648052-f92ce7bf-6deb-424e-8a4f-755cb5502ab5.png)

**Comment by brindasasi** [comment]
![image (10)](https://user-images.githubusercontent.com/89482910/193648168-3784e860-b0c7-412d-9114-95837e16ea8c.png)

**Comment by mnigh** [comment]
> Closing Date needs to be translated ![image (8)](https://user-images.githubusercontent.com/89482910/193648052-f92ce7bf-6deb-424e-8a4f-755cb5502ab5.png)

This one was [previously untranslatable](https://github.com/GCTC-NTGC/gc-digital-talent/issues/3991#issue-1376405212) but a [PR](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3992) was merged into `main` a few weeks ago so once the next translation round occurs, these should be ready.

**Comment by petertgiles** [comment]
All these are addressed except the third point which was extracted to its own issue.
