### ISSUE TITLE
Migrate Pool Candidates to Users Again

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3949]
PR #3567 to migrate the pool candidate fields to the users table and PR #3837 to remove the ability to add more pool candidates was merged to main.  We caught the issue before it was moved to prod though: The replacement pages for adding pool candidates and direct intake were not ready yet.

The commits to back them out were:
https://github.com/GCTC-NTGC/gc-digital-talent/pull/3940/commits/00f15835c02f8c3d92a774bd10d0c46c74c5ea3c
and
https://github.com/GCTC-NTGC/gc-digital-talent/pull/3940/commits/aa0ad4a3f000be69b81e12852dfc44ed4eafe53a
in PR https://github.com/GCTC-NTGC/gc-digital-talent/pull/3940

AC:
- [ ] ~Make sure CMO has a new way to add pool candidates~
- [ ] ~Reapply the changes from #3837 and #3567~
- [x] re-add the migration

**Comment by tristan-orourke** [comment]
We're planning to launch Direct Intake in our next deployment! Migrating Pool Candidates to Users needs to be part of that.

**Comment by vd1992** [comment]
@tristan-orourke 
for this do you want just the migration or the removal of create/update Pool Candidate as well?

**Comment by vd1992** [comment]
deployment tag present
command to use
`php artisan migrate:pool_candidate_to_user`

from

https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/api/app/Console/Commands/MigratePoolCandidatesToUser.php
