### ISSUE TITLE
Implement PHP Formatting Tool

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#3950]
## Summary

Currently, we do not seem to be using any form of standard code formatting for PHP files. It would be beneficial to implement a formatter to standardize the code formatting.

## Acceptance Criteria
- [ ] VS Code extension recommended in extensions.json
- [ ] VS Code settings set to auto-format on save

**Comment by petertgiles** [comment]
It looks like Laravel 9 has a built-in formatter called [Pint](https://laravel.com/docs/9.x/pint).  Unfortunately it looks like it's just a CLI program so it wouldn't be easy to integrate VS Code "format on save".

**Comment by esizer** [comment]
> Unfortunately it looks like it's just a CLI program so it wouldn't be easy to integrate VS Code "format on save".

Not the most elegant solution, but [someone figured it out](https://codebysamgan.com/how-to-add-laravel-pint-to-vs-code-formatter) 😜
