### ISSUE TITLE
Pool Candidates Table: Sorting based on Status

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3951]
This was split off from #3449 for the backend work.

Sorting based on Status

Here is the full list of statuses. The applicants should be displayed in order the order their status appears here (except for Draft applications which should not even be retrieved from the DB). (So "New application" should be at the top of the table and "placed casual" at the bottom unless fileters are removed).

    Draft - Never visible. This data should not be retrieved from server at all for this table.
    New application
    Application under review
    Screened in (available)
    Screened out - On application - Filtered out by default
    Under assessment
    Screened out - On assessment - Filtered out by default
    Qualified - Available
    Qualified - Unavailable
    Qualified - Withdrew - Filtered out by default
    Placed Casual
    Placed Term - Filtered out by default
    Placed Indeterminate - Filtered out by default

**Comment by esizer** [comment]
Are we doing this in the same way we did the Priority field? By a computed DB value?

**Comment by petertgiles** [comment]
> Are we doing this in the same way we did the Priority field? By a computed DB value?

Yeah, actually it's done already.  I think the only remaining work is to write the query.
