### ISSUE TITLE
Maintenance Scripts - Make runnable outside of container

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3953]
The maintenance scripts are handy but not portable enough to run outside of the maintenance container.  Could this be changed to make them more useful?  At least of our WSL, Linux, and Mac developers?

Honestly, I'm not sure how to do this.  The sticking point for me is the `chown -R www-data ./storage ./vendor` command.

**Comment by mnigh** [comment]
@petertgiles any suggestions on a path forward for this issue?

**Comment by petertgiles** [comment]
I'm interested in this but not ready to do anything.  This issue is pretty low value so I'm closing it for now.
