### ISSUE TITLE
Maintenance Scripts - Clean

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3954]
It would be nice to have a script to return the directory back to pristine condition.  It could be a last resort before deleting the directory and recloning.

My favorite approach right now is to use git clean:
```
git clean -nxdf (dry run)
git clean -xdf (actual run)
```
This would require two things, I think
- Adding git to the maintenance container
- Mounting the entire repo in the container, not just some directories

## Acceptance Criteria
- [ ] Script that runs in the maintenance container and deletes all files not tracked in the repo
- [ ] VS Code task to run script
- [ ] Documentation

**Comment by petertgiles** [comment]
More discussion:
https://github.com/GCTC-NTGC/gc-digital-talent/pull/3937#pullrequestreview-1106158349

**Comment by patcon** [comment]
Implementation here: https://github.com/GCTC-NTGC/gc-digital-talent/pull/3937#issuecomment-1245867059

**Comment by petertgiles** [comment]
Failed to estimate.  Might need more discussion on whether the clean should happen in container, locally, in make.

**Comment by mnigh** [comment]
> Failed to estimate. Might need more discussion on whether the clean should happen in container, locally, in make.

@petertgiles is this issue still relevant or can it be closed as not planned?

**Comment by petertgiles** [comment]
Nah, I'm happy with git clean.
