### ISSUE TITLE
Request Form can send empty requests

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#3958]
## Description
On the Request page, a user can submit a request without any of the required fields (at this point, only group and level is required). To restrict these types of empty requests, hide the Request Form and Summary of filters section and show a message with a link to the Search page.

## Notes
Spun off from comment: https://github.com/GCTC-NTGC/gc-digital-talent/issues/3752#issuecomment-1231829849

**Comment by gobyrne** [comment]
@Jerryescandon this is an edge case, but it's possible to navigate to this page without filling out the search page first. In which case there are no filters. Could you design an intervention for this. I don't think it will be top priority, but would be nice to do sometime soon.

**Comment by Jerryescandon** [comment]
Ok, so I was also taking into account were gonna need to do a little branding to this at one point in the future, o I updated it with the colors too. But the main takeway was, if there are required filters missing, lets just hide the entire thing and add a "Go back" button

## Missing required fields

![Image](https://user-images.githubusercontent.com/16977254/195162188-d0e57aff-2856-4904-9bea-c4e12fbbb053.png)

## Full request

![Image](https://user-images.githubusercontent.com/16977254/195162603-f9f65f32-bd22-4b7d-aaea-5ad74449b315.png)

**Comment by mnigh** [comment]
@Jerryescandon can this issue be closed? There is a PR that has been merged that "allows users to submit requests, even if no candidates were found", https://github.com/GCTC-NTGC/gc-digital-talent/pull/5601. That is not exactly the problem that this issue covers, which is going directly to `/search/request` and submitting a request without any values from the search form. Is this expected behaviour or should these types of requests not be allowed to be submitted? Here's what it would like.

## Screenshots

![Screen Shot 2023-03-07 at 10 10 36](https://user-images.githubusercontent.com/3046459/223463829-f6ee3fc8-a178-4d2d-9c92-a9a5c7b49dd1.png)

![Screen Shot 2023-03-07 at 10 11 35](https://user-images.githubusercontent.com/3046459/223463850-d233918f-f30b-4f33-a1d1-aaa7e2f24cae.png)

**Comment by Jerryescandon** [comment]
This can be closed, I think the intent behind this was met with the newer PR. I think this bad boy can go straight into the bin. 🗑️
