### ISSUE TITLE
✨ Enhance the button component with an optional counter

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#3964]
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/3593327e-aa51-4700-aafb-98aa81a61291)

## ✨ Summary

[View the Figma file here](https://www.figma.com/file/guHeIIh8dqFVCks310Wv0G/Style-library?type=design&node-id=5-11&mode=design) | Please contact @substrae with questions on this portion of the ticket.

Enhances the button component with the ability to support an optional counter value. This is first intended to be used in the `table` component filters button to indicate how many filters are currently selected, but could have broader uses down the road. Color specifications can be found in the Figma file linked above.

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/6c437374-8414-4edd-831c-3e23da567e9a)

<details>
<summary>Original filter button screenshot</summary>
<img src="https://user-images.githubusercontent.com/305339/190278491-274fbe32-ccac-4f3e-9805-29c9c7cbc79e.png" />
</details>

**Comment by substrae** [comment]
Option a)

**Comment by mnigh** [comment]
@substrae is this still a feature that the @GCTC-NTGC/designers want implemented? if so, is there a figma design for this?

**Comment by esizer** [comment]
Done in the button dark mode update, safe to close?

**Comment by substrae** [comment]
@esizer Yep!
