### ISSUE TITLE
Login Page Cancel Link Leads to 404

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#3969]
## Summary

On the `/login-info` page, there is a "Cancel" button. Currently it seems to links to `https://talent.canada.ca/login?from=/en/talent/profile&locale=en`. This takes the user to a 404.

## Location

https://github.com/GCTC-NTGC/gc-digital-talent/blob/b4c2b83e9bc15857304bc8908cf58f7646d77520/frontend/talentsearch/src/js/components/login/LoginPage.tsx#L87-L99

**Comment by patcon** [comment]
Goo catch!
