### ISSUE TITLE
Make the filter dialog fully generic

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3973]
Right now the "fancy filter" filter dialog is closely coupled to the User model and it's properties.  Let's create a new filter component based on the existing one that is fully generic.  Ideally it could be used to filter tables of users, pool candidates, requests, or any other model.

Acceptance Criteria:
- [ ] New, fully generic, filter dialog component
- [ ] Storybook story
- [ ] UserTableFilterDialog re-implemented on top of the new component
- [ ] PoolCandidateTableFilterDialog re-implemented on top of the new component

**Comment by esizer** [comment]
Is a thin wrapper what you envisioned for this? Like something along the lines of a single component that emits an `onSubmit` event or something and takes form fields as a child like our `BasicForm` component?

```tsx
  type FilterDialogProps<T> = {
    onSubmit: SubmitHandler<T>;
    defaultValues: DefaultValues<TFieldValues> | AsyncDefaultValues<TFieldValues>;
    children: React.ReactNode;
  }

  <FilterDialog onSubmit={handleSubmit} defaultValues={{ ... }}>
     <FormFields />
  </FilterDialog>
```

**Comment by petertgiles** [comment]
> Is a thin wrapper what you envisioned for this?

To be honest my expectations were very hazy when I first wrote this issue.  It was a response to the fact that when it came time to buildi the Pool Candidate filter dialog after the user one it was decided that the dialog pretty much had to be rebuilt custom, from scratch.  I'm hoping that there's some amount of common code to build a "filter dialog" that can be used to create a reusable base component and ease the effort of building more in the future.  However, I've never worked on one of these so exactly how much can be factored out and what that would look like - I'm not sure I can answer that.
