### ISSUE TITLE
Display test results (pass/fail/skipped) on summary page of CI run

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#3977]
EDIT: Originally this was about visual test summary reports for just **cypress e2e**, but have expanded to incl **phpunit** reports.

---

Right now, we write e2e tests and organize them in files in `frontend/cypress/integration/`. We can see the ones that have run in the console log of each `e2e-test` run, spread over many screen scrolls.
Example logs: https://github.com/GCTC-NTGC/gc-digital-talent/actions/runs/3062471522/jobs/4943483470#step:9:465

We tend to only write passing tests that we have time to write. We often don't write tests that reasonably cover the features we create, for lack of time. We don't make use of empty "skipped" tests as documentation of this debt.

For non-technical team members, it might be nice if our e2e test results were summarized in one place on GitHub.

For our technical team members, it might be nice to have more of a reason to stub out placeholder tests.

![](https://github.com/dorny/test-reporter/blob/main/assets/mocha-groups.png?raw=true)

## Proposed Solution

Some :mag: facts, :heart: feelings, and :bulb: ideas:

- :mag: cypress by default uses a reporter and prints to the console, using the default `spec` reporter
- :mag: GitHub actions can process common output formats and generate summaries of tests within the GitHub interface
  - they show on the [run summary page](https://github.com/GCTC-NTGC/gc-digital-talent/actions/runs/3062471522)
  - github action = `test-reporter` https://github.com/dorny/test-reporter
  - how it looks: https://github.com/dorny/test-reporter/blob/main/assets/mocha-groups.png
  - :mag: "skipped" tests show up in the test reports
- :mag: there exist other cypress reporters that generate these common output formats
  - docs: https://docs.cypress.io/guides/tooling/reporters#Examples
- :mag: we have already installed the [`cypress-multi-reporter`](https://github.com/you54f/cypress-multi-reporters) used to print to both console and a file.
  - config: `frontend/cypress/reporters-config.json`
- :heart: I feel that the feature implementer has the best context to know what e2e tests should be written, and the freshest context right as they're implementing the feature
- :heart: I feel it's understandable that we don't write all the e2e tests that we know would provide the best coverage, because they take awhile.
- :heart: I feel that it would be beneficial to liberally scaffold out empty e2e tests as part of feature PRs, even if we don't write any
- :bulb: let's install [mocha-junit-reporter](https://github.com/michaelleeallen/mocha-junit-reporter)
- :bulb: let's add `test-reporter` action to our e2e-test workflow to render the results
- :bulb: as part of definition of done, let's start expecting empty placeholder e2e tests using the format `it.skip("should do blah", () => { //...` ([added to retro board](https://easyretro.io/publicboard/Bb8eeNIEzucUDrcOv0T1LaCp71m1/0906705c-1fbf-47a8-80f7-e3e4437e9647))

## Acceptance Criteria

- [ ] cypress workflows generate a test summary in proper format, and stores that as GitHub artifact
  - [ ] configure multi-reporter and add plugin for junit output
- [ ] PHPUnit workflows generate a test summary in proper format, and stores that as GitHub artifact
- [ ] GitHub Action [`dorny/test-reporter`](https://github.com/dorny/test-reporter) run in its own workflow, and generates a visual report in GitHub

format = JUnit-compatible XML?

**Comment by mnigh** [comment]
>For non-technical team members, it might be nice if our e2e test results were summarized in one place on GitHub.

why would any of our non-technical team members be looking at github workflows?

> For our technical team members, it might be nice to have more of a reason to stub out placeholder tests.

are test results not already readable as is?


@tristan-orourke can this issue be closed or is there still interest in moving ahead with it?

**Comment by tristan-orourke** [comment]
I'm happy with how our tests are summarized. We do have this this on the readme already: 
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/409c7577-1c1e-49d4-88da-f89b862d035d)

However, I'm interested in the idea here of leaning into skipped tests, as a way of stubbing out tests right away, even if filling them out isn't a priority.
