### ISSUE TITLE
Create toggle component

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3980]
We need a new toggle component!

Jerbo: "I would imagine it is mechanically just a radio button"

## Designs:
![image (3).png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/6d82ab85-47a7-48c3-9055-e845a6ff7617)
![image (4).png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/8c377bd3-5551-498a-baee-03ed73e33670)

Notes:
Might be able to use some of the theme switcher that Josh built for the hydrogen statically-generated site:
https://gitlab.com/hydrogen-css/hydrogen/-/blob/release/2.0.0-beta.28/docs/src/_includes/components/theme-switcher.njk
https://gitlab.com/hydrogen-css/hydrogen/-/blob/release/2.0.0-beta.28/docs/src/static/scripts/app.js

## AC
- [x] Works with two or more options
- [x] Works with text or icons
- [ ] Works with React Hook Forms
- [x] Has a Storybook story
- [x] Can be localized

**Comment by esizer** [comment]
The first screenshot and all subsequent ones seem like different components to me. The first one seems more like a switch where as the others are toggles. It is a very subtle difference but can be important in regards to accessibility.

## Switch

A type of checkbox that represents on/off values, as opposed to checked/unchecked values.

REF: 

- https://www.w3.org/TR/wai-aria-1.2/#switch
- https://www.radix-ui.com/docs/primitives/components/switch

## Toggle

A type of button that has a state toggles a specific state.

> **Note**: If it is possible to complete a goal with using native HTML, that should be preferred over aria. In the case of a toggle, you can do this by updating the label for the button rather than toggle it using `aria-pressed`. 

REF: 

- https://www.radix-ui.com/docs/primitives/components/toggle
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-pressed

**Comment by gobyrne** [comment]
This is not ment to be used as a Yes/No type checkmark.
