### ISSUE TITLE
Add the toggle component to the review application page

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#3981]
Before: ![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/ea38f04f-7fe4-4ffa-8419-f5bcfbab6433)
After:![image (4).png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/38e9bc17-75d8-4e21-9cf5-7ac922cb3550)

**Comment by mnigh** [comment]
@esizer or @JamesHuf can this issue be closed since it was connected to this [merged PR](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4215) or is there another reason to keep this issue open?

**Comment by JamesHuf** [comment]
Yep, I'm not sure why it didn't go with the PR
