### ISSUE TITLE
Make skills mandatory on search page

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#3986]
As a DCMO talent manager, I want to force talent seekers to select at least one skill, so I can properly process their request.

DCMO is getting a fair number of requests with no "skills" flagged. It should be extremely rare that a manager wants to hire, but doesn't care at all what skill set the employee has. Unfortunately this is happening too often and DCMO has to reach out to the manager again to get more info.

At the same time, there are rare cases where it might be appropriate to not have a skill preference, but DCMO wants this to be an active choice.

Acceptance Criteria
- [ ] Make "skills filter" mandatory on current (old) search page
- [ ] Add an option for "skills filter" that is "No skill preference" FR: "Aucune préférence de compétence"

![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/fa618c52-7f3a-4bb6-9bf9-37aeb63e1daa)

**Comment by petertgiles** [comment]
Flagged by Corinne as important during sprint review today.

**Comment by petertgiles** [comment]
Design from Josh: add an "Other" checkbox and require at least one box to be selected.

**Comment by petertgiles** [comment]
Don't forget to translate it

**Comment by gobyrne** [comment]
This page is going away with Direct intake (in 1 month is the plan). It will take us at least 2 weeks to get a fix up. Originally I thought this would be a 1, but it's come in as a 5.

I will talk to Corinne to let her know we #wontfix (unless she can convince me otherwise).
