### ISSUE TITLE
Search Page for Talent Seekers

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#4]
**As a** Talent Seeker
**I want** to see if anyone in the pool meets my needs

Mapping for classification to pay ranges:
[https://app.zenhub.com/files/364642496/3bda009a-6e87-47c7-84c4-72080777d0c1/download](https://app.zenhub.com/files/364642496/3bda009a-6e87-47c7-84c4-72080777d0c1/download)

**Comment by Jerryescandon** [comment]
Link to search prototype:
https://www.figma.com/proto/cctPDb5clT7S0JuRmkBgoO/MVP?page-id=0%3A1&node-id=1%3A2&viewport=-55%2C362%2C0.22959193587303162&scaling=min-zoom
