### ISSUE TITLE
Activate Homepage for root route

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4026]
The tcreport was copied somewhere else and the new homepage is ready to go up!  Time to remove the root tcreport and take over the route.

Acceptance Criteria:
- [x] Add routes for the home page and Learn More pages
- [x] htaccess changes (locally and deployed)
- [x] The root route brings up the new homepage
- [x] All links on the homepage and Learn More pages wired up for proper navigation
- [x] Besides the home page, routes to other tc-report static content must continue to work:
   - [x] https://talent.canada.ca/en/talent-cloud
   - [x] https://talent.canada.ca/en/talent-cloud/report
   - [x] https://talent.canada.ca/en/terms-and-conditions
   - [x] https://talent.canada.ca/en/privacy-notice
   - [x] https://talent.canada.ca/en/communities/digital-talent
   - [x] https://talent.canada.ca/en/diversity/2000/01/01/301-overview.html
   - [x] https://talent.canada.ca/en/projects/2000/01/01/101-caveat-to-begin.html
   - [x] https://talent.canada.ca/en/hiring/2000/01/01/201-overview.html

Out of scope:
- The tcreport was copied to its new home in #4034

**Comment by patcon** [comment]
Maybe relevant here: https://app.zenhub.com/workspaces/gc-digital-talent-6092dc05157fa30010edaef9/issues/gctc-ntgc/gc-digital-talent/4096
