### ISSUE TITLE
Review home pages in dark mode

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4028]
The home pages (including Learn More) are built and dark mode is set up in Storybook.

Acceptance Criteria
- [ ] Ensure home pages look great in dark mode
- [ ] Ensure home pages are accessible in dark mode
- [ ] Add storybook stories and Chromatic snapshots in dark mode

Out of scope:
- Statefulness will be handled in #4033 or #4029

**Comment by petertgiles** [comment]
I think we have some font issues currently on the home page:
![image](https://user-images.githubusercontent.com/8978655/197009505-63bff10f-d34f-4bad-bc3d-92c6f8399053.png)

**Comment by petertgiles** [comment]
While fixing breadcrumbs in #4807 the flourishes developed some issues in dark mode.
![image](https://user-images.githubusercontent.com/8978655/202726941-c6d65f3c-f735-4422-b33b-eebb73cd707b.png)

**Comment by mnigh** [comment]
@petertgiles is this still something that needs to be done?

**Comment by petertgiles** [comment]
In theory, yes it still needs to be done.  However, I don't think it is high on anyone's priority list.

**Comment by mnigh** [comment]
@GCTC-NTGC/developers is this issue different than https://github.com/GCTC-NTGC/gc-digital-talent/issues/7520?

**Comment by petertgiles** [comment]
I'd say both are superseded by  #4033.
