### ISSUE TITLE
Colour gap on search page

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#4031]
## Summary

There appears to be a gap in the background colour on the `/search` page. It is hard to see on some screens but it is just at the bottom of the "About the Digital Talent Pool" section and spans the entire width of the screen.

## Screenshot

![Screenshot 2022-09-21 133151](https://user-images.githubusercontent.com/4127998/191572378-168875ec-16ee-42ed-8d0e-25ba12706d43.png)

**Comment by petertgiles** [comment]
I can't unsee this now!  😵
