### ISSUE TITLE
Add dark mode toggle to site header

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4033]
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/58def341-503f-478f-8698-6113466f8d8c)

## ✨ Summary

[Visit the Figma file](https://www.figma.com/file/guHeIIh8dqFVCks310Wv0G/Style-library?type=design&node-id=11-4115&mode=design) • Contact @substrae with design questions

The goal of this ticket is to add control functionality to the newly merged dark mode changes. This ticket features updates to the styling of the existing toggle component, as well as ensuring it functions as expected. Note the temporary addition of the `BETA` label - this is intended to show users that this feature is new and that we are currently testing/collecting feedback. While we've done a significant amount of work and have been diligent about changes, I want to encourage the idea that this probably isn't going to be perfect on our first attempt and that we're open to improving the feature.

If it's helpful, and example of how the toggle should function can be found in the [Hydrogen documentation](https://hydrogen.design/en/docs/configuration/configuring-modes/#toggle).

```[tasklist]
### ✅ Requirements
- [ ] Update the toggle component to match the latest designs
- [ ] Ensure the "Preferences" selection triggers the correct mode (light/dark) based on the user's browser preference
- [ ] Ensure the "Light" selection triggers light mode regardless of the user's browser/OS preference
- [ ] Ensure the "Dark" selection triggers dark mode regardless of the user's browser/OS preference
- [ ] Ensure the selected mode is saved in local storage so that it is retained the next time the user visits the site
- [ ] Allow for a prop to control whether the "BETA" label shows in the component or not
- [ ] Design review on Dev vertical before merging
``` 

## 📸 Screenshots

<details>
  <summary>Light mode selections</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/792f841d-1a35-4de5-bcd3-a522f61d77ad" />
</details> 

<details>
  <summary>Dark mode selections</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/137fabf5-02f3-4970-b479-be2626a0a48a" />
</details> 

<details>
  <summary>Without BETA label</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/b80a8bda-0abb-4bbb-a4fd-5fd67f4bd041" />
</details> 

## ❓ Questions
- [ ] Does this require a new context provider?

**Comment by esizer** [comment]
Should we close https://github.com/GCTC-NTGC/gc-digital-talent/issues/5807 in favour of this, or do they have distinct enough goals?

**Comment by substrae** [comment]
@esizer 

It almost feels like #5807 could be an epic that includes this ticket and the dark mode review ticket, etc. If you feel it's redundant though, you're absolutely welcome to close it in favor of the separate ones that also exist.
