### ISSUE TITLE
Fix Cypress

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4035]
Cypress is experiencing many intermittent failures these days.  Suspicions are around caching causing testing of old code and the has diploma checkbox.

## Sporadic Failures

- Talent Search Workflow Tests [`cypress/integration/talentsearch/search-workflows.spec.js`](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/cypress/integration/talentsearch/search-workflows.spec.js#L21)
    - [ ] searches for candidates and submits a request. [example](https://github.com/GCTC-NTGC/gc-digital-talent/actions/runs/3144207648/jobs/5110835775#step:9:543) [example2](https://github.com/GCTC-NTGC/gc-digital-talent/actions/runs/3152257539/jobs/5127326019#step:8:537) `TestingLibraryElementError: Timed out retrying after 8000ms: Unable to find an element with the text` / `expected **findAllByText(`Required diploma from post-secondary institution`)** to exist in the DOM`
- Admin Workflow `cypress/integration/admin/admin-workflows.spec.js`
    - [x] ~~Searches for a user and edits the phone number [example](https://github.com/GCTC-NTGC/gc-digital-talent/actions/runs/3144895181/jobs/5111492216#step:9:92) [example2](https://github.com/GCTC-NTGC/gc-digital-talent/actions/runs/3144947539/jobs/5111696191#step:9:92) `[GraphQL] Validation failed for the field [updateUserAsAdmin].`~~ [fixed by other PRs]
- User Profile Workflow Tests `cypress/integration/talentsearch/profile-workflows.spec.js`
    - [x] ~~Reviews a user profile and makes some edits. [example](https://github.com/GCTC-NTGC/gc-digital-talent/actions/runs/3144895181/jobs/5111492216#step:9:547) [example2](https://github.com/GCTC-NTGC/gc-digital-talent/actions/runs/3144947539/jobs/5111696191#step:9:528) `[GraphQL] Validation failed for the field [updateUserAsUser].`~~ [fixed by other PRs]
    - [ ] Reviews a user profile and makes some edits. [example](https://github.com/GCTC-NTGC/gc-digital-talent/actions/runs/3175611816/jobs/5173874502#step:8:472)
        - https://github.com/GCTC-NTGC/gc-digital-talent/blob/d43127ac817d88e1ad450c9568d916bb282428bf/frontend/cypress/integration/talentsearch/profile-workflows.spec.js#L29-L33
        - From the video of this run, it looks like there's an odd error with ScrollToTop that is not expected, which is happening right before the runner is trying to "clear" the city field. In the video, the city field is NOT clearing, and the page scrolls to the top and idles. So it seems like something is up with scrolltotop kicking off during "clear", instead of focussing the appropriate field and emptying it. And then the submission fails because no content has changed. Perhaps there should be an error though. Need to investigate.

**Comment by petertgiles** [comment]
Seems like it's always the direct intake workflow spec that fails.

**Comment by esizer** [comment]
I'm seeing the following assertion consistently fail as well. Which is odd since reviewing the videos, it definitely does exist within the DOM. 🤔 

https://github.com/GCTC-NTGC/gc-digital-talent/blob/734057df1363acd6a5eb314347da4cd865d86b79/frontend/cypress/integration/talentsearch/search-workflows.spec.js#L68-L71

In regards to direct intake, I believe it is inconsistency in our seeders. We need the have at-least one pool being published and able to apply to. Currently, some items which are random, should be static for at least one pool and user profile. These are

- pool_status -> POOL_STATUS_TAKING_APPLICATIONS
- is_published -> true
- expiry_date -> anything in the future
- essentialSkills -> match the users skills

https://github.com/GCTC-NTGC/gc-digital-talent/blob/734057df1363acd6a5eb314347da4cd865d86b79/api/database/factories/PoolFactory.php#L41-L42

**Comment by patcon** [comment]
I'm gonna figure this out. I haaaate that all the PRs look red...!

**Comment by esizer** [comment]
> TestingLibraryElementError: Timed out retrying after 8000ms: Unable to find an accessible element with the role "button" and name `/Apply for this process/i`

This is related to the seeder, check with @petertgiles he mentioned he had a PR that may resolve this.

**Comment by petertgiles** [comment]
I'm going to abandon the branch, I think, but feel free to crib whatever you want: https://github.com/GCTC-NTGC/gc-digital-talent/pull/4020/commits/a4ce2f11eb7c8c3a79121a680ccac05dd6c4b196

**Comment by mnigh** [comment]
Also noted this failure on the e2e workflow, see this [run](https://github.com/GCTC-NTGC/gc-digital-talent/actions/runs/3144207648):

`System.IO.IOException: No space left on device : '/home/runner/runners/2.297.0/_diag/Worker_20220928-145725-utc.log'`
