### ISSUE TITLE
Error message missing - Getting Started page

### ISSUE THREAD

**Issue by MaddyDaigle** [GCTC-NTGC/gc-digital-talent#4042]
## Description
An error message is missing when logging into the Digital Talent app for the first time on the "Getting Started" page.

## Steps

1. Signed up with GCKey.
2. Linked to Getting Started page (https://talent.canada.ca/en/create-account)
3. Entered all required fields.
4. Received an "Error:creating account failed" message at the top of the screen, while my focus stayed at the bottom of the page.5. 

**Additional issue:**  If you try and toggle to French after this issue occurs, you are stuck in a never-ending loading screen.

## Expectation
I expected to be brought back up to the top of the page and provided with information regarding the error and why the account failed.  I believe it likely failed because the contact email I used was the same as a previous account I created.  Since users may switch between email account (GOC email) but still use the same contact account, this is something to consider.

### Image of "creating account failed"
<img width="785" alt="Screen Shot 2022-09-22 at 2 49 00 PM" src="https://user-images.githubusercontent.com/1794660/191829048-2bb00cd4-da0e-4146-85d2-e1838d8e7c59.png">

### Image of the top of page after error
<img width="1023" alt="Screen Shot 2022-09-22 at 2 36 46 PM" src="https://user-images.githubusercontent.com/1794660/191829057-61c0aa0f-d2fa-4d71-aa74-f7dc3a67f704.png">

**Comment by esizer** [comment]
This is likely because the error comes from the api rather than `react-hook-form` rules so the `shouldFocusError` never got a chance to fire.

**Comment by MaddyDaigle** [comment]
I just added an amendment to the ticket.  There's an issue with toggling to French when this issue occurs - never ending loading screen.
