### ISSUE TITLE
Directory refreshes on Windows creates phantom folders

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4046]
> > the directory refreshes (ie Refresh Admin) still seem to do the same thing
> 
> Thanks for taking a look! What is this issue? It's something that happens with the current scripts already? What folder are they spawning?

yep, an occuring issue, I just don't use Refresh scripts aside from the API one
the one we troubleshooted a few months back where the phantom folders you couldn't open would appear with names like "admin-a89ad"

_Originally posted by @vd1992 in https://github.com/GCTC-NTGC/gc-digital-talent/issues/3937#issuecomment-1247215594_

**Comment by mnigh** [comment]
any @GCTC-NTGC/developers using Windows: is this 👻 folder issue still relevant?

**Comment by mnigh** [comment]
Can't reproduce.
