### ISSUE TITLE
Search Digital Talent - Summary of Filters Inconsistency

### ISSUE THREAD

**Issue by MaddyDaigle** [GCTC-NTGC/gc-digital-talent#4048]
## Description
There is an inconsistency between the fields that are filled out in the  Search Digital Talent form (https://talent.canada.ca/en/search) and the text provided under "Summary of Filters" in the resulting page (https://talent.canada.ca/en/search/request).  Specifically, the "Type of Opportunity" text.

## Steps

1. Filled out entire Digital Talent Pool form as a manager.
2. In the resulting Request form, under **Summary of Filters**, there is text for **Type of opportunity**.  There is no equivalent field in the previous Digital Talent Pool form.

## Expectation
The **Type of opportunity** text should not be in the Request form's **Summary of Filters** section since it is found nowhere in the fields on the previous page.

### Image of Summary of Filters
<img width="904" alt="Screen Shot 2022-09-22 at 4 34 39 PM" src="https://user-images.githubusercontent.com/1794660/191846500-c9c72bd6-ab56-4825-a57c-241f8f10bc73.png">

**Comment by vd1992** [comment]
appears to be more feature flag stuff!

only occurs if passing in type `PoolCandidateFilter` to `/search/request`
https://github.com/GCTC-NTGC/gc-digital-talent/blob/c38103e94426175fc6fa8cde6ec01ccef70bc57f/frontend/common/src/components/SearchRequestFilters/SearchRequestFilters.tsx#L354-L355

attached to this bit that appears to no longer have use but wasn't cleared out
https://github.com/GCTC-NTGC/gc-digital-talent/blob/c38103e94426175fc6fa8cde6ec01ccef70bc57f/frontend/common/src/components/SearchRequestFilters/SearchRequestFilters.tsx#L454

**Comment by vd1992** [comment]
not sure what the acceptance criteria should be in this case as PoolCandidateFilter may be removed soon-ish (?) with Direct Intake
either: 
- remove all instances of type of opportunity 
- clean this as a side effect of removing PoolCandidateFilter

**Comment by gobyrne** [comment]
Seems like this will go away when we switch to the new search (happening soon). Let's #notfix for now and keep an eye on it. @MaddyDaigle
