### ISSUE TITLE
Issue referenced:

### ISSUE THREAD

**Issue by Aboodhassand** [GCTC-NTGC/gc-digital-talent#4050]
Issue referenced:

- https://github.com/actions/virtual-environments/issues/6002

_Originally posted by @mnigh in https://github.com/GCTC-NTGC/gc-digital-talent/issues/3609#issuecomment-1208231207_

**Comment by patcon** [comment]
Going to close this, as it appears to be an automated spam issue that is increasingly common on GitHub. If this is a mistake, please do speak up @Aboodhassand
