### ISSUE TITLE
Inconsistent language used for first_name, last_name labels

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4056]
## Description
The application uses three different labels that corresponds to the same field:
- `first_name`: Given name(s), First Name, First Name and Middle Name
- `last_name`: Surname(s), Last Name, Last Name(s)

## Screenshots
![Screen Shot 2022-09-23 at 15 35 40](https://user-images.githubusercontent.com/3046459/192044880-882efa2f-b664-4227-a313-70d6651e4fa8.png)
![Screen Shot 2022-09-23 at 15 32 47](https://user-images.githubusercontent.com/3046459/192044882-f608e26e-dede-4e3f-b5e1-5a3dd4dd55f9.png)
![Screen Shot 2022-09-23 at 15 29 28](https://user-images.githubusercontent.com/3046459/192044883-c760da8e-ebc4-44fd-a8f0-f0da4dcbf44b.png)

## Acceptance Criteria
- [x] decide on appropriate labels for consistency
- [x] apply new label copy

**Comment by petertgiles** [comment]
These are live pages.  Updated copy should be translated at the same time.

**Comment by petertgiles** [comment]
@Jerryescandon Do the designers agree these should be made consistent?  Which copy should we standardize on?

**Comment by Jerryescandon** [comment]
- `first_name`: First Name
- `last_name`: Last Name
