### ISSUE TITLE
Going to close this, as it appears to be an automated spam issue that is increasingly common on GitHub. If this is a mistake, please do speak up @Aboodhassand

### ISSUE THREAD

**Issue by Aboodhassand** [GCTC-NTGC/gc-digital-talent#4060]
Going to close this, as it appears to be an automated spam issue that is increasingly common on GitHub. If this is a mistake, please do speak up @Aboodhassand

_Originally posted by @patcon in https://github.com/GCTC-NTGC/gc-digital-talent/issues/4050#issuecomment-1256308799_

**Comment by patcon** [comment]
Blocked them from org :tada:
