### ISSUE TITLE
Browse Pools Page has no fallback for a pool without a name

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4073]
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/e9ab6fe9-d435-455d-9302-747cfdc16572)

**Comment by petertgiles** [comment]
This is a placeholder page - might not matter

**Comment by gobyrne** [comment]
This page is getting rebuilt. Let's close for now. Adding as acceptance criteria on the Browse pools page dev issue.
