### ISSUE TITLE
Browse pools page lists unpublished pools

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4074]
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/4842ea96-eac8-4706-a7fa-4a9f53b7cbec)

![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/40ba9b32-893b-4549-b6b7-fc333ee17df1)

**Comment by gobyrne** [comment]
This page is getting rebuilt. Let's close for now. Adding as acceptance criteria on the Browse pools page dev issue.
