### ISSUE TITLE
Icons on candidate application page show while loading

### ISSUE THREAD

**Issue by JamesHuf** [GCTC-NTGC/gc-digital-talent#4092]
Icons on the page for viewing candidate applications show up while the page is still doing some loading.

![This is an image](http://g.recordit.co/qz5ansOoef.gif)

**Comment by vd1992** [comment]
#justwindowsthings 
🪟

**Comment by JamesHuf** [comment]
> #justwindowsthings 🪟

Haha, the loading time definitely is

**Comment by esizer** [comment]
Was unable to reproduce on MacOS Chrome 106.0.5249.61 🤷‍♀️

**Comment by vd1992** [comment]
gave it a try just now, can't seem to replicate it either, Firefox

![image](https://user-images.githubusercontent.com/40485260/193915423-c782449c-b30c-4343-92c3-366154e2ab7c.png)

**Comment by JamesHuf** [comment]
Interesting... it looks like I'm not getting it any more either. 😕

**Comment by mnigh** [comment]
Unable to reproduce this behaviour on any of the following in macOS:
- Google Chrome 106.0.5249.91
- Microsoft Edge 106.0.1370.34
- Firefox 105.0.2

Also, tried throttling in Chrome but still could not reproduce the behaviour.

**Comment by gobyrne** [comment]
Ok, closing issue for now if we are unable to reproduce.
