### ISSUE TITLE
Experiences - Off by one day issue

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4100]
Probably a UTC to local time zone issue.

![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/507dfaa8-c000-4aaa-bf9a-e634227ef1b4)
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/f801d3ac-0d62-4ef0-b2ef-0d561b137f28)

**Comment by tristan-orourke** [comment]
I know this was in the Safebox, I didn't mean to fix it, but I kind of just stumbled onto the solution when considering #4041
