### ISSUE TITLE
Update static site in tc-report folder

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4105]
After #4034, we should be able to update the Jekyll layouts and then run the static site generator right in this repo. 

With a new homepage built in React, this static site will be used exclusively to host the TC Report (and temporarily, still the ToC and Privacy page). To make it easier to maintain, we can reduce the number of links to the rest of the site. We will remove most links from the header (including Login, Register and Logout links), update some links on the Talent Cloud page, and remove the DCMO page.

## Acceptance Criteria

- [x] The static site nav menu includes ONLY a single link, back to the home page, with the text changed to "< Return to GC Digital Talent" / "< Retour à Talent Numérique du GC"
- [x] Delete the home page and DCMO page 
- [x] In the "Where to From Here?" section of the Talent Cloud page, modify the "Visit GC Digital Talent" link to point to the homepage, and change the "Visit the Indigenous Talent program" link to https://talent.canada.ca/<lang>/indigenous-it-apprentice
- [x] Add an entry to htaccess (deploy.htaccess and the local dev version) to add a permanent redirect from:
    - [x]  https://talent.canada.ca/en/communities/digital-talent to https://www.canada.ca/en/government/system/digital-government/gcdigital-community.html
    - [x] https://talent.canada.ca/fr/communities/digital-talent to https://www.canada.ca/fr/gouvernement/systeme/gouvernement-numerique/collectivite-gcnumerique.html

**Comment by petertgiles** [comment]
What's the DCMO page?
https://talent.canada.ca/en/communities/digital-talent ?
