### ISSUE TITLE
Browse Opportunities Page

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4111]
Right now we just have a placeholder page at /browse/pools.

## Acceptance Criteria

- [ ] only lists published pools
- [ ] Some kind of fallback when pool doesn't have a name (???)
- ...

**Comment by gobyrne** [comment]
Yes, we'll also need some way to control which page we are publishing on. Some will need to be published on the executive recruitment page, and IAP will need to be elsewhere as well. Those should not show up on the IT jobs page.

**Comment by tristan-orourke** [comment]
Converting this to an Epic so it can act as an umbrella for issues related to Browse Opportunities page

**Comment by vd1992** [comment]
Complete?
