### ISSUE TITLE
Final round (probably) of translation before Direct Intake release testing 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#4115]
As we are approaching the release , we have added several new strings that yet to be translated. 
We need to send them all for translation and verify for its sanity before Direct Intake Release.

![image (3).png](https://images.zenhubusercontent.com/61a7bd49e20af80694dd845e/3985bd2d-c8a6-4be7-8ca9-db80ce623e2c)

**Comment by petertgiles** [comment]
The tabs from the screenshot no longer exist:
![image](https://user-images.githubusercontent.com/8978655/196516336-0c5e4dd5-8940-42f2-beff-01ae7060bdec.png)

**Comment by JamesHuf** [comment]
Files sent for translation:
[admin-english-to-french.txt](https://github.com/GCTC-NTGC/gc-digital-talent/files/9913836/admin-english-to-french.txt)
[common-english-to-french.txt](https://github.com/GCTC-NTGC/gc-digital-talent/files/9913837/common-english-to-french.txt)
[talentsearch-english-to-french.txt](https://github.com/GCTC-NTGC/gc-digital-talent/files/9913838/talentsearch-english-to-french.txt)
