### ISSUE TITLE
Admin - Action link colour in tables inconsistent

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4123]
## Description
The action links, such as **Edit** and **View Candidates** are purple even though every other link colour is black.

## Screenshots
![Screen Shot 2022-09-29 at 13 42 12](https://user-images.githubusercontent.com/3046459/193105249-74b56b19-8817-47cc-8091-96ecca98db8a.png)
![Screen Shot 2022-09-29 at 13 42 28](https://user-images.githubusercontent.com/3046459/193105252-c088368c-4f3a-4c70-971b-2ce5bd8d8a7d.png)
![Screen Shot 2022-09-29 at 13 42 38](https://user-images.githubusercontent.com/3046459/193105253-579353b8-3805-4dde-a614-5b4b531cebda.png)
![Screen Shot 2022-09-29 at 13 41 59](https://user-images.githubusercontent.com/3046459/193105255-60a5911f-72c9-4638-af59-43dfb3ff4bc5.png)
![Screen Shot 2022-09-29 at 13 43 03](https://user-images.githubusercontent.com/3046459/193105256-4022458f-1bd9-4571-8cd8-dd2a6e941804.png)
![Screen Shot 2022-09-29 at 13 42 56](https://user-images.githubusercontent.com/3046459/193105259-ab9fade3-56c4-41fb-a092-b4d1bb713b55.png)
![Screen Shot 2022-09-29 at 13 42 46](https://user-images.githubusercontent.com/3046459/193105260-6e7ab84d-cf00-47dd-8d92-2b95fa1cb055.png)

## Acceptance Criteria
- [ ] action links in admin tables should be black (as per the design guidance of @JoshBeveridge)

**Comment by JoshBeveridge** [comment]
Just a bit of context - @Jerryescandon might have a preference on color - but my guidance is specifically that links be consistent.

**Comment by Jerryescandon** [comment]
No arguments here. Hit it.
