### ISSUE TITLE
Added experience isn't shown until browser is refreshed

### ISSUE THREAD

**Issue by MaddyDaigle** [GCTC-NTGC/gc-digital-talent#4174]
## Description
When a user adds a new experience item (.../profile/experiences/personal/create) and fully fills it out & saves, it is not shown in the page that lists all experience items (.../profile/experiences) until the page is refreshed.

## Steps

1. Create a new experience item under the "my experiences and skills" section.
2. Fill out the entire page, including required fields. 
3. Click "save and go back".

Notice that the recently created experience does not show up in the resulting page.

### Create new experience
Create and fully fill out new experience (e.g. Twitch Streamer)
<img width="1146" alt="Screen Shot 2022-10-03 at 12 43 35 PM" src="https://user-images.githubusercontent.com/1794660/193633036-1fabc738-da18-4901-885c-caedf4146b06.png">

### Page after submit
Notice that "Twitch Streamer" is not listed.
<img width="1040" alt="Screen Shot 2022-10-03 at 12 44 12 PM" src="https://user-images.githubusercontent.com/1794660/193633232-0403965d-1484-4912-94a2-3f3404ad3d80.png">

## Page after refresh
The new experience will only show if the user refreshes.
<img width="1041" alt="Screen Shot 2022-10-03 at 12 44 59 PM" src="https://user-images.githubusercontent.com/1794660/193633342-b39b1827-a205-414f-b0c1-4f44c1f0890f.png">

**Comment by petertgiles** [comment]
This has probably already been fixed with the caching change in this sprint but is not yet in prod.
