### ISSUE TITLE
List of values for classification is not sync in Search page vs Job advertisement creation page

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#4175]
Here is how UAT is displayed with classifications different from Pool creation and request page. 
Job Advertisement(Pool) creation 
![image (5).png](https://images.zenhubusercontent.com/61a7bd49e20af80694dd845e/0874caf8-2457-4619-9be9-e8c098c89daf)

Search Page 
![image (6).png](https://images.zenhubusercontent.com/61a7bd49e20af80694dd845e/4215edf4-6ab8-4215-8998-dfce165dc42f)

Problem comes when I have a pool of candidates from AS-05 which is not available to search for. 

**Acceptance Criteria**
  
- [ ] Both pages should be served from the same set of seeders.

**Comment by gobyrne** [comment]
Yeah, we need to review what classifications have been added by admins on Prod. I think it's manageable there though.
