### ISSUE TITLE
🏈 Backend Telemetry/Analysis

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4184]
It would probably be good to know things like:
- Which API request are called very frequently?
- Which API requests take a long time to return?

This would allow us to focus on performance optimization in the right places.

Maybe even look into database telemetry to know which queries are taking a long time to run or use excessive memory.

Acceptance Criteria
- [ ] Collect statistics on which requests are received most frequently (`me` queries?)
- [ ] Collect statistics on which requests take a long time to complete (`search` queries?)
- [ ] Document how you collected statistics
- [ ] Open new issues for optimizations dependent on what you found

**Comment by petertgiles** [comment]
Would it happen in AppInsights, Laravel, Postgres?

**Comment by petertgiles** [comment]
Some people on team think a spike might work better.

**Comment by tristan-orourke** [comment]
@petertgiles I think we have this now, right? Can we close it?

**Comment by petertgiles** [comment]
Yeah, for sure.  There's still more we could do but we no longer need a general spike for exploration.
