### ISSUE TITLE
API endpoint which forwards Create Ticket request to Freshdesk

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4187]
Create an api endpoint in our laravel server which forwards a payload to the [Freshdesk api](https://developers.freshdesk.com/api/#create_ticket). It doesn't need to do any validation, just send on the same payload it receives, and return the response it gets from Freshdesk.

The one thing this endpoint has to do, and the reason we won't just send a request directly from the client-side to Freshdesk, is that the server must add a Freshdesk API Key (stored in a new env variable) to the request.

This involves:
    - adding a route to `api/routes/api.php` (while you're add it, you can remove the default unused route)
    - adding a Controller class in `api/app/Http/Controllers`, where the logic is
    - adding a new (empty) key to `api/.env.example`
    - probably an additional line to .htaccess and deploy.htaccess

## Acceptance Criteria

- [ ] Our server accepts a POST request to the route `/api/support-tickets`, forwards the payload to freshdesk (using an env var api key) and returns whatever response it gets.

**Comment by vd1992** [comment]
this could be of use for implementation

https://github.com/freshworks/fresh-samples/tree/master/PHP

**Comment by mnigh** [comment]
We should do this because the freshdesk api key along with the domain can be used to make requests that return sensitive information and we do not want the api key value exposed.

**Comment by mnigh** [comment]
## Deployment Note
@tristan-orourke when deploying to uat and prod, please also deploy IaC to uat and prod up to at least **Release-378**.
