### ISSUE TITLE
✨ Support Page - Submit previous URL with support ticket

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4191]
We want to submit the most recent url the user was on along with the support ticket. This may help clarify where they ran into trouble. This will involve:
1. Working with the helpdesk team to arrange a custom field
2. Building a way to know which url a user came from, before visiting the support page.

For problem 2, the first thing that occurs to me is to use the `state` function of the [History API](https://github.com/remix-run/history/blob/main/docs/api-reference.md). Any links which point to the support page could push the current location into the state, eg at the key `prevLocation`. Our form could check if such a value exists in the state, and include it in the submission if possible. 

I don't know if this is the best solution? The only other place we're using state, when moving between the Search and Request forms, feels janky and confusing to me. Open to alternatives.

## Acceptance Criteria:
- [ ] Capture the URL of the last page the user visited before support
- [ ] Send that URL to the helpdesk in a custom field

**Comment by esizer** [comment]
[`document.referrer`](https://developer.mozilla.org/en-US/docs/Web/API/Document/referrer) may be enough here. It would save us from adding state to every link to the support page.
