### ISSUE TITLE
Support Page - Submit error log with support ticket

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4192]
Josh has suggested it would be useful to automatically submit an error log with our ticket. We could submit an array of errors to Freshdesk as another custom field. We just have to start logging them.

We process errors in the errorExchange in ClientProvider.tsx. In addition to whatever else we do with them, we can add them to a log stored in [session storage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage). Then, we just have to retrieve the error logs in session storage and attach them to a ticket request.

 ## Acceptance Criteria
- [ ] Capture recent log messages (we have a centralized logger now)
- [ ] Attach the recent logs to the submitted support ticket

**Comment by petertgiles** [comment]
Perhaps the saved logger should buffer the last-n errors.

**Comment by petertgiles** [comment]
@marc-donofrio Does this request seem useful to you?  Is it worth working on?

**Comment by marc-donofrio** [comment]
For now, no. If ticket loads increase we can revisit.
