### ISSUE TITLE
Get a Freshdesk API key and add to Production config

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4193]
Talk to Marc D'Onofrio to arrange for an api key to our helpdesk's Freshdesk server. Add this to the Freshdesk API Key env variable in our Azure Prod service via the IAP.

## Acceptance Criteria
- [x] talk to Marc D'Onofrio to arrange for an api key to our helpdesk's Freshdesk server
- [x] add ticket endpoint and api key variable to dev, uat, production, env.example for local dev (added to IaC for all three verticals but waiting to be deployed to uat, production)

**Comment by tristan-orourke** [comment]
If the helpdesk team has any kind of test- or playground-server, it would be great to add a key for that in the Dev and UAT config (and even for local dev).

**Comment by mnigh** [comment]
Teams message sent to Marc D'Onofrio requesting Freshdesk domain and API key as well as any information on a testing environment if available.

**Comment by mnigh** [comment]
## Updates

- We now have a production Freshdesk domain and API key.
- There is no test or sandbox environments available at this time.
- Waiting on Marc to add or update a `email_config_id` (related to #4384) so that we can set the environment variable on dev, uat, prod.

**Comment by mnigh** [comment]
New `email_config_id` value has been deployed to dev with **Release-378**.

**Comment by mnigh** [comment]
## Deployment Note
@tristan-orourke when deploying to uat and prod, please also deploy IaC to uat and prod up to at least **Release-378**.
