### ISSUE TITLE
The skill tabs on the skills picker are not translated, as is the "All Skills" radio button. These are also, new I think, so I assume our next translation batch will fix it.

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4197]

**Comment by mnigh** [comment]
Duplicate of https://github.com/GCTC-NTGC/gc-digital-talent/issues/4115

**Comment by petertgiles** [comment]
These tabs no longer exist.
![image](https://user-images.githubusercontent.com/8978655/196516475-6b0be918-8da9-4941-98d7-16f8d6b031eb.png)
