### ISSUE TITLE
Add a "Publishing Group" column to Pools

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4200]
Add a new field to Pools/PoolAdvertisements which represents where it is to be published. Options are:

- IT Jobs
- Executive Jobs
- Other

This should be represented by an enum in the schema. 

## Acceptance Criteria
- [x] Migration to add column to pools
- [x] document field in model class
- [x] add field and enum to schema (in Pool _and_ PoolAdvertisement)
- [x] populate field in seeder
- [x] populate field in fake js class
- [x] add input to Edit Pool Page (ask @Jerryescandon)

**Comment by petertgiles** [comment]
@Jerryescandon Does this look OK?
![image](https://user-images.githubusercontent.com/8978655/194343500-6d055a23-9d5a-4963-845d-58752070e8a1.png)

**Comment by Jerryescandon** [comment]
That looks good, should it be **required** tho?

**Comment by Jerryescandon** [comment]
actually, all of those seems required to me so, lets not worry about that right now, haha, just ignore it.

**Comment by petertgiles** [comment]
> actually, all of those seems required to me so, lets not worry about that right now, haha, just ignore it.

Yeah, it's a weird artifact of having a lot of small forms on the page together.  None of them are required to save your draft.  I'll make sure it's required for publishing through.
