### ISSUE TITLE
Link and Button components have className bugs

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#4221]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Screenshot: Prototype
<img width="493" alt="Screen Shot 2022-10-06 at 2 18 43 PM" src="https://user-images.githubusercontent.com/305339/194323487-42d482e8-711e-4402-a523-b4751b822d1f.png">

It seems that we're not setting className props in a good way. "undefined" classes are very common, and for Links, non-button types have mashed together class names. There are 3 related issues:

1. Link: "false" class is added when non-button type, instead of no string. https://github.com/GCTC-NTGC/gc-digital-talent/blob/206bf6cb7fd161f3e567af4b44206fe4b1fd7d8e/frontend/common/src/components/Link/Link.tsx#L40
2. Link: "undefined" class is always added, because className prop on Link is optional. https://github.com/GCTC-NTGC/gc-digital-talent/blob/206bf6cb7fd161f3e567af4b44206fe4b1fd7d8e/frontend/common/src/components/Link/Link.tsx#L40
3. Button: "undefined" class is always added, same reason. https://github.com/GCTC-NTGC/gc-digital-talent/blob/206bf6cb7fd161f3e567af4b44206fe4b1fd7d8e/frontend/common/src/components/Button/Button.tsx#L261
    - <details><summary>diff...</summary>
      
      ```diff
          diff --git a/frontend/common/src/components/Button/Button.tsx b/frontend/common/src/components/Button/Button.tsx
      index a15515a67..7487dc5b7 100644
      --- a/frontend/common/src/components/Button/Button.tsx
      +++ b/frontend/common/src/components/Button/Button.tsx
      @@ -258,7 +258,7 @@ const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
           return (
             <button
               ref={ref}
      -        className={`button ${classNames}`}
      +        className={!!classNames ? `button ${classNames}` : "button"}
               // eslint-disable-next-line react/button-has-type
               type={type || "button"}
               disabled={disabled}
      ```
      <summary>

This is technically in prod, but seemingly not affecting user experience, just creating wonky classes.

We could (1) fix this with simple logic, or (2) perhaps defer to using a simple library to enforce common patterns through its API (<1kb, no deps, basically glorified string concatenation libs)
https://bundlephobia.com/package/classnames@2.3.2
https://bundlephobia.com/package/clsx@1.2.1
https://bundlephobia.com/package/classcat@5.0.4

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by patcon** [comment]
Also, maybe worth jest tests of className variations

**Comment by gobyrne** [comment]
@yonikid15 any insights?

**Comment by esizer** [comment]
Are we even using those classes for anything? I think we can safely remove them since 99% of our styling is done in hydrogen. Otherwise, we may want to add [`clsx`](https://www.npmjs.com/package/clsx)

**Comment by mnigh** [comment]
Related #5804.

**Comment by mnigh** [comment]
the `className` attribute was removed from the `Link` component at some point in the last year (I failed to track down the commit where it was done because the file has been moved so many times) and the `classNames` prop will soon be removed from the `Button` component as part of #6170.
