### ISSUE TITLE
Favicon for GC Digital Talent

### ISSUE THREAD

**Issue by BrookeCameron** [GCTC-NTGC/gc-digital-talent#4223]
# **REQUIREMENTS**

## :camera:  Screen caps
- 

![Image](https://user-images.githubusercontent.com/100953238/194354597-7a165588-d17a-4efa-91d7-cc433b70d62f.png)

## 📎 files
- 

[GC_Digital_Talent_favicon_package_v0.zip](https://github.com/GCTC-NTGC/gc-digital-talent/files/9726264/GC_Digital_Talent_favicon_package_v0.zip)

## Code
-
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#2f313d">
<meta name="msapplication-TileColor" content="#ff0000">
<meta name="theme-color" content="#ffffff">

**Comment by gobyrne** [comment]
Does this resolve #4078 ?

**Comment by BrookeCameron** [comment]
@gobyrne if a dev has added it yes - if not no.

**Comment by mnigh** [comment]
> if a dev has added it yes - if not no.

#4078 is not directly related to this issue as it deals with referencing the wrong icon files in the code: creating different icon files won't solve that issue.

**Comment by mnigh** [comment]
I think this issue can be closed based on https://github.com/GCTC-NTGC/gc-digital-talent/pull/4277 being merged into `main`, is that correct @petertgiles?
