### ISSUE TITLE
Display referral path on /not-found page

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#4225]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

Spin-off from: https://github.com/GCTC-NTGC/gc-digital-talent/issues/1904

On 404/not-found page, we should show the referral page we redirected from when it's available. This will help with support requests when ppl arrive on this page.

## Screenshot: Prototype

(needs to be updated with updated design)
<img width="934" alt="Screen Shot 2022-10-06 at 4 05 29 PM" src="https://user-images.githubusercontent.com/305339/194354368-f0882ad1-45b2-47d4-aef3-9e0fb0cbc42a.png">
<sup>[Click screenshot to visit Figma.][image-link]</sup>

## Acceptance Criteria
- [ ] show referral url when referred from within app
- [ ] hide referral url when not available (apache redirect?)
- [ ] make URL monospaced and with copy helper

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by esizer** [comment]
Think we can close this after #4597 since we no longer redirect in that and instead render the 404 page in place at the same path.

**Comment by patcon** [comment]
Agree. I suspect it was misguided to redirect on 404/not-found :) Closing!
