### ISSUE TITLE
Research Cypress for e2e testing with feature flags ON and OFF 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#4227]
### Problem

We need a testing mechanism to test ON and OFF side of feature flags as we constantly introduce bugs related to that. 
We need a automated way of catching those issues earlier. 

### :question: Spike Question
- How can we run e2e testing with feature flags on and off?

Timebox: 2 days

**Comment by patcon** [comment]
Related slack convo: https://talent-cloud.slack.com/archives/C0259G6KXJ6/p1665007016304059?thread_ts=1665006944.546679&cid=C0259G6KXJ6

**Comment by tristan-orourke** [comment]
https://github.com/GCTC-NTGC/gc-digital-talent/pull/4209#issuecomment-1271839207

**Comment by patcon** [comment]
Example of how not running e2e tests on both states of feature flag can lead to issues with deprecated components breaking before we've totally removed the feature toggle that relies on them:

https://app.slack.com/client/T5ZFRSQ3V/threads/thread/C0259G6KXJ6-1669924724.249809?cdn_fallback=1 🔒

**Comment by mnigh** [comment]
I think this is possible, taking a similar approach to what @tristan-orourke mentioned in his [comment](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4209#issuecomment-1271839207) for when can use a feature introduced in Cypress 10 (which we can now). We can map our `.env` file in Cypress config and then within individual tests, set the environment variable as needed (REF: https://docs.cypress.io/guides/guides/environment-variables#Single-test-configuration).

## Screenshot
![Screen Shot 2023-11-08 at 10 51 24](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/9ece0533-db12-456e-8421-9a01ce7e681f)

The question is though for @GCTC-NTGC/developers: is there still an appetite to do this or should this issue be closed?

**Comment by petertgiles** [comment]
> The question is though for @GCTC-NTGC/developers: is there still an appetite to do this or should this issue be closed?

I still think it's valuable.

**Comment by vd1992** [comment]
Unless I am missing things, I am not sure how the other examples will be effective. Our webpack build grabs the environment variables then emits them to a config file which is what the checkFlag functions reference. This is all defined at build time so nothing can be changed in a test suite right? Wouldn't the only way be to conditionally override variables in the place below? So when the build occurs in the e2e workflow, it has to inject some sort of conditional that can be picked up in webpack to override certain environment variables 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/73c2fb5c-ae4b-420b-80f5-c60a53a8a9ac)
