### ISSUE TITLE
Convert pagination to scrolling in Skill Picker

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4230]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

## Screenshot: Prototype
[![a screenshot of ...][image]][image-link]
<sup>[Click screenshot to visit Figma.][image-link]</sup>

## Acceptance Criteria
- [ ] Instead of pagination, skills appear in a scrolling Replace pagination with scrolling. 
    - QUESTION: how to choose the max height?
    - Can we make the skill picker not change size as number of results change?

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by gobyrne** [comment]
@esizer can this be done separately from the other Skill Picker work or are you tackling all together?

**Comment by esizer** [comment]
> can this be done separately from the other Skill Picker work or are you tackling all together?

@gobyrne I'll likely do both. Just noticing that they are fairly rightly coupled.
