### ISSUE TITLE
New message for support form error

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4231]
## Description

If freshdesk request contains an error, show toast to user saying to email us, and mention this error code.

## Copy

- English: "Sorry, something went wrong. Please email {emailAddress} and mention this error code: {errorCode}."
- French: "Désolé. Une erreur s'est produite. Veuillez envoyer un courriel à {emailAddress} et mentionner ce code d’erreur : {errorCode}."

## Acceptance Criteria
- [x] Shows the error code
- [x] Directs user to email our support email ([gctalent-talentgc@support-soutien.gc.ca](mailto:gctalent-talentgc@support-soutien.gc.ca))

**Comment by mnigh** [comment]
This is the string that will need to be updated (don't forget the French string):

https://github.com/GCTC-NTGC/gc-digital-talent/blob/0859779bac1d1a19a2e558527ac4a4735095f573/frontend/talentsearch/src/js/components/support/SupportForm.tsx#L236-L243

**Comment by mnigh** [comment]
The following was sent for translation to French:
```
{
  defaultMessage: `Sorry, something went wrong. Please email {emailAddress} and mention this error code: {errorCode}.`,
  id: "tZLItl",
  description: "Support form toast message error",
}
```
