### ISSUE TITLE
Upgrade cypress from v9 to v10

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#4264]
Re-ticketed from https://github.com/GCTC-NTGC/gc-digital-talent/pull/4209#issuecomment-1271839207

**Priority:** low (?)

v10 Migration Guide: https://docs.cypress.io/guides/references/migration-guide#Migrating-to-Cypress-version-10-0

cc @tristan-orourke confirming priority as low?

## To Do
- [ ] follow migration guide
- [ ] add ability to read env vars for feature flags  in cypress.config.js (where was set manually in cypress.json before)

**Comment by mnigh** [comment]
There were some [dependency incompatibilities](https://github.com/GCTC-NTGC/gc-digital-talent/pull/2938#issuecomment-1144163478) a few months ago but they might be resolved by now. @patcon you could also reopen [this PR](https://github.com/GCTC-NTGC/gc-digital-talent/pull/3004#issuecomment-1149163818) and get dependabot to do some of the dependency work for you.

**Comment by vd1992** [comment]
https://github.com/GCTC-NTGC/gc-digital-talent/pull/4270

**Comment by esizer** [comment]
https://twitter.com/Cypress_io/status/1590129904112218112?s=20&t=vfwtChpJDHflfa6vDOE-pQ

😅

**Comment by mnigh** [comment]
Estimate?
