### ISSUE TITLE
Pool status column on Pools table seems incorrect

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#4267]
## Description
I created a new pool and published in on the UAT
![image](https://user-images.githubusercontent.com/16977254/195174293-552db91d-e3d2-4312-9930-8608cd13ae5b.png)

When looking at the pools table, this table's status shows as "Not taking applications" which seems incorrect for a published pool

![image](https://user-images.githubusercontent.com/16977254/195174756-adb67651-bb3a-4e93-b4a1-1633abd92fea.png)

## Acceptance Criteria
- [ ] ...

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by vd1992** [comment]
I think this was fixed in #4130 but not pushed to UAT yet
