### ISSUE TITLE
Pools Table - Search does nothing

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4280]
https://images.zenhubusercontent.com/364642496/fb0aa20d-e21a-48a3-b707-e654d71b75c8/simplescreenrecorder_2022_10_13_10_08_57.mp4

**Comment by vd1992** [comment]
appears this will be done in #4129 
another issue to connect to that PR lol

![image](https://user-images.githubusercontent.com/40485260/195635305-acd8365d-ab1a-4c0e-9c55-06a486b68b76.png)

**Comment by gobyrne** [comment]
I would suggest just hiding for now. It will take a while to have an unmanageable number of pools.
