### ISSUE TITLE
Create Support placeholder page

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4282]
## Description
The support page is part of Talent Search and will eventually hold a list of FAQs and a Support form. For now, this page will be scaffolded so that the other components can be added somewhere. 

## Acceptance Criteria
- [x] add route for /support
- [x] create SupportPage component

**Comment by gobyrne** [comment]
Looks like @esizer already did this. Thanks @esizer !

**Comment by mnigh** [comment]
Actually, @esizer added the route for /support as part of #4245 but not the component for SupportPage.
