### ISSUE TITLE
Refactor how cypress tests target a table row

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4284]
https://github.com/GCTC-NTGC/gc-digital-talent/pull/4209#issuecomment-1276330292

**Comment by mnigh** [comment]
@tristan-orourke is this still an issue that should be worked on and if so, what is the acceptance criteria?

**Comment by mnigh** [comment]
@GCTC-NTGC/developers is there any will to move this forward or should it be closed as not planned?

**Comment by tristan-orourke** [comment]
I can't find any instance of `cy.findAllByRole("row")` in the code anymore, so I think this is outdated.
