### ISSUE TITLE
Set up a better error message when trying to access the admin site from the off gov network

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4288]
We had to disable post-login redirects to the admin site because it was very confusing to the user when they failed to get there.
https://talent-cloud.slack.com/archives/C5Z1KMX5F/p1658777913248329
If there was a useful message explaining why the site was unreachable and sending them back to the homepage we could re-enable these post-login redirects.

This will probably require coordination with IMTD if it's possible at all.

![image](https://user-images.githubusercontent.com/8978655/195677557-ea78427a-97ac-4797-b879-6d2c77d59001.png)

**Comment by gobyrne** [comment]
Jira issue created. Now waiting for IMTD to respond.
https://jira.tbs-sct.gc.ca/browse/AZ-15104

**Comment by gobyrne** [comment]
slack chat: https://talent-cloud.slack.com/archives/CB424V61J/p1673901156528859

**Comment by petertgiles** [comment]
Thanks Gray!  I've opened a new issue to create the page to be redirect to. #5362

**Comment by gobyrne** [comment]
Ok, let's close this issue then.
