### ISSUE TITLE
User redirected to logged-out page unnecessarily

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4295]
When page has been opened long enough that auth token has gone stale, following any link forcibly redirects user to the logged-out page, instead of where they wanted to go.

a) If user was going to a page which doesn't require authentication, this redirect is disruptive and unnecessary.
b) If user was going to a page which does require being authenticated, it would be more convenient to just redirect directly to the login page, and bring them back to the intended url after.

In either case, a toast describing the situation would be preferable to a redirect to the logged-out page.

## Acceptance Criteria
- When the auth token has gone stale, and the user is going to a page which **DOESN'T require authentication**
  - [ ] **continue** to the page instead of logging out and
  - [ ] **display a toast** saying user has logged out.
- When the auth token has gone stale, and the user is going to a page which **DOES require authentication**
  - [ ] **redirect to login** and
  - [ ] include the intended page as the **post-login redirect**
  - [ ] do NOT show a toast

**Comment by esizer** [comment]
Proposing we have this by #3017 since redirect functionality is changing in that.

**Comment by vd1992** [comment]
was this issue also solved by React Router?

**Comment by vd1992** [comment]
don't really get the entirety of the authentication system, but poking around

- access tokens have a lifespan of 120 seconds
- refresh tokens don't seem to get refreshed alongside access tokens, not sure where the expiry exists for them, isn't in the token itself

this issue pertains to using the site after the refresh token has been stale for 4 hours right?
kind of hard to investigate unless you can tweak the time-to-staleness to something like a minute (just for testing purposes)

**Comment by petertgiles** [comment]
Tristan putting it down due to lack of time.

**Comment by esizer** [comment]
Spent roughly 3 hours on this and could not reliably reproduce the issue and had trouble narrowing it down due to that 😢
