### ISSUE TITLE
Manual Testing: Does having the app open in multiple tabs hinder auth refresh

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4297]
The access token has a lifetime of only 10 minutes. The refresh token is supposed to have a lifetime of 4 hours, and can be used to get new access tokens when required. However, I'm worried that getting a new access token in one tab might not immediately be reflected in a second tab, causing the second tab to error and log you out.

### Steps to test
1. login to account /login on Production
2. open 2 tabs
3. wait 12 (maybe 15) minutes
4. go to your profile in first tab and confirm that a access token refresh occurs
5. go to your profile in second tab and confirm that a new access token appears

### Acceptance Criteria

- [ ] if step 5 fails, create a github issue

**Comment by brindasasi** [comment]
on the repeated test , I found something else 

1. All tokens including has 10 mins expiry time. Nothing has 4 hours. 
2. After around 15 mins ,first kept functioning while the page on second tab logged out. 
3. Refreshing the second tab prompted the alert box with logout and cancel. I clicked cancel and the page refreshed with the new token and start functioning like prev tab.
