### ISSUE TITLE
Manual Testing: is refresh token refreshed when used?

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4298]
The access token has a lifetime of only 10 minutes. The refresh token is supposed to have a lifetime of 4 hours, and can be used to get new access tokens when required. When the refresh token is to get a new access token, can we also get a new refresh token at the same time? If not, you will always time out 4 hours after initially logging in, even if using the app continuously.

### Steps to test
1. login to account /login on Production
2. open 1 tab
3. copy access token, refresh token to clipboard
4. wait 12 (maybe 15) minutes
5. go to your profile in tab and confirm that an access token refresh occurs
7. ensure access token, refresh token has changed

### Acceptance Criteria

- [ ] if step 5 fails (failure is when access token, refresh token have not changed), create a github issue

**Comment by petertgiles** [comment]
Confirmed, after idling for 10 minutes a refresh occurred.  A new access token and refresh token were stored in local storage.  No additional issue created.
