### ISSUE TITLE
Helpful message with JavaScript disabled

### ISSUE THREAD

**Issue by JamesHuf** [GCTC-NTGC/gc-digital-talent#4299]
The site crashes and displays a blank page if a user has JavaScript disabled in their browser. We  want to display some kind of error prompting the user to enable JavaScript if they experience issues.

Note: designers are working on a full design but we'll use a single message for now.

Acceptance criteria:
- [ ] Visiting the site without javascript enabled in the browser displays the message `It looks like JavaScript is disabled in your browser settings or unsupported by the browser itself. JavaScript is required to view this application.` along with the French translation.
- [ ] Visiting the site with Javascript enabled has the same behavior as before.

**Comment by JamesHuf** [comment]
I'm not sure how worried we are about this but it seemed worth making an issue for it at least.

**Comment by mnigh** [comment]
Depending on if this needs a design, adding noscript HTML tags after each of the following would at least alert a user with JavaScript disabled (not 100% on the French string either):

`<noscript>Your browser does not support JavaScript/Votre navigateur ne supporte pas JavaScript</noscript>`

https://github.com/GCTC-NTGC/gc-digital-talent/blob/196cd4cd50ee5432f048c012bd8d28604e806bb5/frontend/admin/public/index.html#L19

https://github.com/GCTC-NTGC/gc-digital-talent/blob/196cd4cd50ee5432f048c012bd8d28604e806bb5/frontend/talentsearch/public/index.html#L27

https://github.com/GCTC-NTGC/gc-digital-talent/blob/196cd4cd50ee5432f048c012bd8d28604e806bb5/frontend/indigenousapprenticeship/public/index.html#L19

**Comment by petertgiles** [comment]
I pitched `Your browser does not support JavaScript/Votre navigateur ne supporte pas JavaScript` to the designers and there was no push back so let's go with that for now.

Josh suggested:
I wonder if we can be more helpful than this? Perhaps link to common (Edge, Firefox, Chrome, Safari) browser documentation?
