### ISSUE TITLE
Skill can be marked as both "Essential" and "Asset" for a pool

### ISSUE THREAD

**Issue by JamesHuf** [GCTC-NTGC/gc-digital-talent#4302]
A skill can be marked as both an 'essential skill' and an 'asset skill' on a pool.

This isn't really a problem but it looks kind of odd.

## Acceptance Criteria
- [ ] Adding a skill as essential prevents it from being added as asset
- [ ] Added a skill as asset prevents it from being added as essential
- [ ] Removing a skill from one category makes it possible to add it as the other
- [ ] Enforced in the API as well as frontend validation

**Comment by mnigh** [comment]
#7953 seems to have solved this in the API but not on the frontend. i've tested locally and can confirm, almost there. 

@petertgiles this issue could probably be re-estimated and brought down from a 5️⃣.

**Comment by vd1992** [comment]
Closing in favour of #8013  
Will decide on some frontend stuff there
