### ISSUE TITLE
Missing apostrophe, quotation mark on submit application to pool page

### ISSUE THREAD

**Issue by JamesHuf** [GCTC-NTGC/gc-digital-talent#4303]
There is a missing apostrophe on the submit application to pool page here:
![image.png](https://images.zenhubusercontent.com/61d4c65971f41272c88f9a81/3f6837a3-01d5-40d5-9577-10b551fd32bd)

**Comment by petertgiles** [comment]
Make sure the translation doesn't get disconnected when the string is updated.

**Comment by mnigh** [comment]
Nice catch @JamesHuf. I actually found another typo in the same screenshot, a missing quotation mark:

## Screenshot
![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3631643463363539373166343132373263383866396138312f33663638333761332d303164352d343064352d393537372d313062353531666433326264](https://user-images.githubusercontent.com/3046459/195862155-da03ef98-689b-4bf2-a01a-5a8db6b424cd.png)
