### ISSUE TITLE
Turn dead string pruning back on when merging new translations.

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4305]
At some point we turned off the feature to automatically remove dead strings from the FR.json files.  This has two side effects:

The files are unnecessarily large are will continue to accumulate dead strings over time.

When new translation files are merged the dev won't notice if the translation ID no longer matches the source because there are so many dead strings already.

I think we should turn on auto-pruning again.

**Comment by gobyrne** [comment]
Any reason in particular that we turned it off @petertgiles ?

**Comment by petertgiles** [comment]
@gobyrne Strangely it seems like it happened during a PR to update the names of CoE values?  It's really not clear to me from that PR why it happened.  It seems like a bunch of translation linting settings were changed during that PR as well?  :confused: 

https://github.com/GCTC-NTGC/gc-digital-talent/pull/3432
