### ISSUE TITLE
The code generator has deoptimised the styling

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4306]
I noticed this warning shows while building up since merging the 404 page:
```
[BABEL] Note: The code generator has deoptimised the styling of /home/peter/repos/gc-digital-talent.worktrees/4282-support-placeholder-page/frontend/talentsearch/src/js/components/404/Icons.tsx as it exceeds the max of 500KB.
```

I'm not sure what it means though.  Does the file need to be broken into smaller files?  Maybe it doesn't matter at all?

Acceptance Criteria:
- [ ] No warnings about components exceeding the maximum size during build

**Comment by esizer** [comment]
Looks like it does not matter. Though, if we want we can just use `<img src="pug.svg" />` instead of the the component.

Ref: https://github.com/babel/babel/discussions/13676#discussioncomment-1183149

**Comment by mnigh** [comment]
> Looks like it does not matter. Though, if we want we can just use `<img src="pug.svg" />` instead of the the component.
> 
> Ref: [babel/babel#13676 (comment)](https://github.com/babel/babel/discussions/13676#discussioncomment-1183149)

Or convert them into pngs? Compare file sizes:
![Screen Shot 2023-02-01 at 13 50 05](https://user-images.githubusercontent.com/3046459/216135635-747150cc-af67-436d-9548-ed3cf62b30e9.png)

**Comment by mnigh** [comment]
@esizer with https://github.com/GCTC-NTGC/gc-digital-talent/pull/6105 resolve this issue?

**Comment by esizer** [comment]
> @esizer with #6105 resolve this issue?

I beleive this was solved as part of a different issue. We are no longer using `Icons.tsx`. Maybe we can create a ticket to delete that file, or update this one? 🤔

**Comment by mnigh** [comment]
> Maybe we can create a ticket to delete that file, or update this one? 🤔

Past me predicted future you 😆 : https://github.com/GCTC-NTGC/gc-digital-talent/issues/6079

**Comment by esizer** [comment]
> Past me predicted future you 😆 : #6079

Perfect, I think this is safe to close now then 👍
