### ISSUE TITLE
Form field data is lost when user switches between languages.

### ISSUE THREAD

**Issue by MaddyDaigle** [GCTC-NTGC/gc-digital-talent#4310]
### Description

When a user enters form fields on any of the Talent Portal profile forms and then switches languages, all the data that was entered is lost.

**Environment:** UA, probably prod as well.

### Why is this an issue?

During user testing, a user expressed that they often switch between languages to make sure they understand what they are asked.  They had to start over every time.

### Expectation

When language is switched, all fields that were filled are saved and can be viewed in both languages.

**Comment by esizer** [comment]
> **Note**
> @tristan-orourke implemented a caching mechanism for our `BasicForm` component. Should just need to make sure all forms are using `BasicForm` and have the `cacheKey` prop set to a unique value.

**Comment by MaddyDaigle** [comment]
@esizer was this change added to UA?  It doesn't seem to be working within the Add Experience page.

Also, this same issue occurs with the manager applicant search functionality.

**Comment by MaddyDaigle** [comment]
Try and switch languages? That’s where I had the issue.. didn’t seem to save stuff.
