### ISSUE TITLE
Need an automatic way of pulling out the report on candidate search requests 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#4346]
### Problem 

As an admin (currently DCMO client)  I would like to pull up the report on candidates search requests grouped by Level and Skills ( CMO assets ) . We used the below script to get the report but would be nice to have it as a web page or as a job dumping the report , so it can be done anytime they want without human intervention. 

### Script 
```
select ps.created_at, ps.full_name, ps.email, ps.job_title, ps.additional_comments, ps.admin_notes, ps.status, c.name, c.group, c.level,cmo.name from 
pool_candidate_search_requests ps inner join classification_pool_candidate_filter cf on cf.POOL_CANDIDATE_FILTER_ID = ps.POOL_CANDIDATE_FILTER_ID
inner join classifications c on c.id = cf.classification_id
inner join cmo_asset_pool_candidate_filter ca on ca.POOL_CANDIDATE_FILTER_ID = ps.POOL_CANDIDATE_FILTER_ID
inner join cmo_assets cmo on cmo.id = ca.cmo_asset_id
group by ps.created_at, ps.full_name, ps.email, ps.job_title, ps.additional_comments, ps.admin_notes, ps.status, c.name, c.group, c.level, cmo.name
order by  ps.created_at, c.group, c.level , cmo.name
```

**Comment by petertgiles** [comment]
Business Intelligence reporting can become a "whole big thing".  I'd urge caution before we decide we want to take this on a start building our own hand-crafted reporting interface.  There are tons of tools out there to do the heavy lifting like [PowerBI](https://powerbi.microsoft.com/), [Crystal Reports](https://www.sap.com/products/technology-platform/crystal-reports.html), etc.  We probably are already licensed for something like this.

**Comment by gobyrne** [comment]
I'll ask IMTD if we can connect PowerBI to our database for this kind of analytics. They have it running in our Azure already.
