### ISSUE TITLE
♻️ Only `me` query should return the entire User object

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4362]
## ♻️ Debt/Refactor

We want to remove the need for Admins to access or edit the entire User object. To make this more robust, only the `me` query should return the entire User object. We should redesign other queries to return more limited aliases of the User, like Applicant or UserPublicProfile, depending on what data is required.

UPDATE: it seems like we want to keep the ability for Platform Admins to view almost all user info. If there are exceptions, we can guard those fields with `@can` directives.

## 🕵️ Details

This can be considered part of #4360, as it is part of our overhaul of permissions.

We need to look through the schema and find all cases where a query or mutation returns a full User object, or it is an attribute of another Type. In almost all of those cases, we should return a more limited version of the User instead, like Applicant or UserPublicProfile. This is because the User type includes much private information, including the users applications, any pools they own, their roles, etc. We must replace the type in the backend schema, as well as any frontend operations which call the updated endpoints.

## 🙋‍♀️ Proposed Solution

I propose three different slices/aliases for User:
- UserContactInfo, which would replace UserPublicProfile:
    ```
    type ContactInfo { 
        id: ID!
        email: Email
        firstName: String @rename(attribute: "first_name")
        lastName: String @rename(attribute: "last_name")
        preferredLang: Language @rename(attribute: "preferred_lang")
    }
    ```
- Applicant, which contains everything necessary for considering a candidate to a pool, including ContactInfo.
- The rest of the User object, which includes the previous two types, as well as other relationships:
```
type User {
  id: ID!
  sub: String
  contactInfo: ContactInfo @self
  applicantProfile: Applicant @self
  legacyRoles: [LegacyRole]
  roleAssignments: [RoleAssignment]
  poolCandidates: [PoolCandidate] #this one might not be accessible to platform admins even if the User is
  pools: [Pool] # pools a user owns. We can deprecate this once we're going through roleAssignments.teams
}
```

There are no existing types which include a User or User[] field, so that's good.

Queries/Mutations which return the full User type:
- me // this one makes sense
- user(id: UUID!) // The only frontend place which uses this is the admin UpdateUser page, which actually, we can continue to allow, protected by a view Any User policy.
- users // There is an AllUsers operation defined in the backend, but it doesn't appear to be used.
- usersPaginated // Used for the admin table. Can be replaced with a call which returns ContactInfo.
- createUser // We still have a CreateUserPage defined, but it is unused and can be deleted.
- updateUserAsUser // This one can probably be replaced with an updateApplicant mutation, since the `UpdateUserAsUserInput` type only includes Applicant/ContactInfo fields anyway.
- updateUserAsAdmin // Just need to make sure admins can only edit Admin Info. And in fact, I think roles should be edited with their own mutation.
- deleteUser // We're not using this anywhere... We can keep this, since it's guarded by a policy, but it should probably only return ContactInfo.

Note: updatePoolCandidateAsAdmin also allows for creation of a User at the same time, and this should also be removed, as per #4634.

QUESTION: How DRY should our overlapping User aliases be? Should the types look something like this? This is related to #2365.
```
type ContactInfo @model(class: "\\App\\User") { 
    id: ID!
    email: Email
    firstName: String @rename(attribute: "first_name")
    lastName: String @rename(attribute: "last_name")
    preferredLang: Language @rename(attribute: "preferred_lang")
}
type Applicant @model(class: "\\App\\User") {
    id: ID!
    contactInfo: ContactInfo @self
    ... # more profile stuff
}
type UserAdminInfo @model(class: "\\App\\User") {
    id: ID!
    contactInfo: ContactInfo @self
    sub: String
    roles: [Role]
}
type User {
    id: ID!
    contactInfo: ContactInfo @self
    profile: Applicant @self
    roles: [Role]
   # should a User be able to view their own sub / admin info?
}
```

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] The `me` query and the user(id) query are the only Query or Mutation which returns a User type.
- [ ] Existing functionality on the site is maintained, even with a more limited API (except perhaps a slight reduction in the fields Admins can edit on Users)

**Comment by tristan-orourke** [comment]
I don't think #2365 is a blocker on this for any reason. I'll work to define this one better.

**Comment by tristan-orourke** [comment]
Aw, darn. After looking at this in more detail, some implementation details may in fact depend on #2365.

**Comment by tristan-orourke** [comment]
Also, after reasoning through this, I wonder if it might be worth reconsidering our stance on field-level permissions. We've discussed this before, in https://github.com/GCTC-NTGC/gc-digital-talent/issues/1846 and https://github.com/GCTC-NTGC/gc-digital-talent/issues/2266. 

Essentially, if we're refactoring our User objects, we could also consider consolidating them - doing away with Applicant and UserPublicProfile entirely - and applying different permissions to each field in the User object.

**Comment by tristan-orourke** [comment]
Link to relevant slack discussion https://talent-cloud.slack.com/archives/C0259G6KXJ6/p1675711524389429

**Comment by vd1992** [comment]
@tristan-orourke 

What is the state of this issue now? Looks rather at odds with how things are now.
The type `Applicant` was rolled into `User` in #7099 , part of a goal to cut down number of types. This issue would have `Applicant` as well as more duplicates/aliases of `User` added.

**Comment by tristan-orourke** [comment]
Yeah, we decided to go in a different direction from thes.
