### ISSUE TITLE
UX - "Your status is available to change" success toast is confusing

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/gc-digital-talent#4363]
## Problem 1
If an applicant completes their profile during the application process, the "All required fields are complete. You can now change your status." success toast is displayed. This may cause some confusion since the Status section does not appear on the Apply page. Perhaps adding more context to the message in this case, and let the user close it themselves instead of autoclosing. (eg. "... You can now change your status in your Profile").

## Problem 2
The profile "Your profile is now complete and you can apply" toast appears when you fill in all the fields except skills. It could be confusing to users who get that toast but still can't apply because they're missing the required skills. Especially if they arrived on the profile page through a specific application.

**Comment by petertgiles** [comment]
This form component is disappearing with the new applicant dashboard.  I'm closing this but feel free to reopen if it's still important.
