### ISSUE TITLE
Restrict skills list to only "Need to have" and "nice to have" skills during an application

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/gc-digital-talent#4365]
When applying to a job, the skills listed on the Experience form page should be limited to only the Need to have and Nice to have skills associated with the job. This means we no longer need an elaborate skill picker, or any search functionality, since the list will be small.

Note: this is only when going through an application! When coming from your profile, there _are_ no asset/required skills, and we should continue to use the SkillPicker component.

![restricted skill list](https://user-images.githubusercontent.com/4313717/197572697-dd5f6977-2bcf-427c-92e9-d8630eaa108b.png)

[Link to Figma prototype](https://www.figma.com/file/spDwyr56BgQKrSdRiHztPL/Skills-and-EX---Poster-and-application-V2?node-id=1150%3A7498)

## Acceptance Criteria
- [x] During an application, Step 2 of the Experience form lists Need to have and Nice to have skills, instead of the skill picker component.
- [x] Skills listed use the same skill accordion component as the skill picker, and the "add skill" button works the same.
- [ ] When editing an existing Experience, we want to hide skills unrelated to this job, but ENSURE THEY ARE NOT DELETED when updating the skills for this job. (Need to be careful about how we use `connect` and `sync` on `UpdateExperienceSkills`.)
- [x] Accessing the Experience form via the user profile continues to use the Skill Picker component allowing user to search all skills.

**Comment by tristan-orourke** [comment]
Display above the skill picker, use the same component as #4390

**Comment by tristan-orourke** [comment]
[Figma link for new design](https://www.figma.com/file/spDwyr56BgQKrSdRiHztPL/Skills-and-EX---Poster-and-application-V2?node-id=1150%3A7498)

After going through more design, the goal has changed from "Show missing required skills list on create/edit experience page during application process" to "Restrict skills list to only "Need to have" and "nice to have" skills during an application.

**Comment by tristan-orourke** [comment]
@Jerryescandon if user already has experiences when applying to a pool, and those experiences have other skills already attached from outside this list, should those skills be hidden during this application?

**Comment by Jerryescandon** [comment]
I posted it on Desfam for thoughts but no one has suggested anything yet. 

My gut reaction for now is to display them as is. Users who have them will have them filled with information, so they would probably know where they came from. And it seems less work for now. Maybe in future iterations we can design a more elegant solution.
