### ISSUE TITLE
Cypress failing test - Pool Candidates - should update pool candidate status

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4368]
This test can intermittently fail if there are no seeded candidates waiting to be reviewed.  Consider adding a candidate to the database before the test using the Cypress commands to ensure that the needed candidate is there.
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/125749af-30b0-40b7-831d-a0163fff30a6)

**Comment by esizer** [comment]
Seems like this issue was a duplicate of the solved #5254

**Comment by petertgiles** [comment]
Agreed!
