### ISSUE TITLE
"Add skill" to "Add this skill"

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4370]
Extracted from #3909:
- [ ] "Add skill" on the skill picker is translated to "Ajouter une compétence". This is essentially "Add a skill".  (~@Jerbo~ @Jerryescandon  can we change to "Add this skill / Ajouter cette compétence"?)
![image.png](https://images.zenhubusercontent.com/5dc084854553760001149b53/b25505bd-7175-40cc-9a66-67b298d47223)

**Comment by mnigh** [comment]
Wouldn't the **added** state copy, Remove skill/Retirer une compétence, need to be changed then as well?

**Comment by mnigh** [comment]
Also worth considering is that there is actually hidden text for screen readers that is part of the strings:

https://github.com/GCTC-NTGC/gc-digital-talent/blob/b040e75c49d8df3481449fb798ecee7336ac8c74/frontend/common/src/components/SkillPicker/SkillBlock.tsx#L105-L110

**Comment by Jerbo** [comment]
@petertgiles  not sure why I am being tagged here.

**Comment by petertgiles** [comment]
@Jerbo Gray wants your input on changing the copy of the skill picker.

**Comment by Jerbo** [comment]
Perhaps he meant Jerob, or something similar? I'm not affiliated with this project.

**Comment by Jerryescandon** [comment]
lol, yeah seems like a good change, also maybe I should change my handle to something more intuitive 😆

**Comment by vd1992** [comment]
one for the highlight reel

**Comment by Jerbo** [comment]
Glad to be of service 😉
