### ISSUE TITLE
🛠️ Set up French Chromatic snapshots

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4371]
It would be good to have some Storybook stories that default to French for Chromatic snapshots.

## Acceptance Criteria

- [ ] Set Storybook to make French stories
- [ ] Set up story for high-value page in French Talentsearch homepage
- [ ] Set up story for high-value page in French IAP homepage

**Comment by vd1992** [comment]
I was thinking about doing something like this
Leverage the Diff to work as an Intl test

At the same time, there are definitely a few components that could be condensed into a single snapshot (one snapshot rendering multiple small components with different states), would be good to clean up some of those too to avoid ballooning the snapshot count too much

**Comment by vd1992** [comment]
tried and no luck so far 😢 
tried playing with parameters, the setIntlConfig function, and jamming IntlProvider in places so far

**Comment by petertgiles** [comment]
> tried and no luck so far cry

Yeah, sounds like my afternoon yesterday.  :laughing: We may have to do something drastic like change from storybook-addon-intl to storybook-react-intl.

**Comment by vd1992** [comment]
well, if we are considering drastic options, I did find a possibility 
disabling the defaultLocale in the storybook operation file and then setting it in each storybook file, this is messy though and breaks storybook so would be lots of work to go through all files

**Comment by petertgiles** [comment]
No clear way forward.  Icebox for now.
