### ISSUE TITLE
✨Restrict which pools are available for searching on the Search page

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4373]
## ✨ Feature

Restrict the search page to counting candidates from `IT_JOBS` and `IT_JOBS_ONGOING` publishing groups. 

## 🕵️ Details

We don't want IAP candidates and exec candidates (in the future) to be included in the counts on the search talent page.

## 🙋‍♀️ Proposed Implementation

The `countApplicants` and `countPoolCandidatesByPool` queries should have a hard-coded scope applied to them which limits the results to candidates in `IT_JOBS` and `IT_JOBS_ONGOING` pools.

The `PoolCandidateSearchInput` input should have a new field added, which accepts an array of publishing group enums, and scopes to the results to candidates in those pools. A multiselect for this field should be added to the PoolCandidatesTable filter - and it should always default to `IT_JOBS` and `IT_JOBS_ONGOING`, so that initial results on a search request page match what the requester saw.

## ✅ Acceptance Criteria

- [ ] Talent Search counts on the client side are restricted to candidates to pools in the IT_JOBS and IT_JOBS_ONGOING publishing groups.
- [ ] It's impossible for non-admins to get candidate counts (via api) for other publishing groups. 
- [ ] Admins can filter PoolCandidates by any publishing group on the PoolCandidates table. The default value of this filter matches the search request.
- [ ] PHPUnit tests

**Comment by tristan-orourke** [comment]
IAP pool doesn't yet exist in production, and if we expire all digital_careers PoolCandidates they shouldn't show up in search anyway. Not a blocker for launching DirectIntake.

**Comment by mnigh** [comment]
@tristan-orourke is this issue still relevant?

**Comment by tristan-orourke** [comment]
Oh shoot, this is still _very_ relevant, since I think we still won't want IAP candidates showing up in search counts. The obvious solution is to filter candidates by pool publishing groups.

**Comment by gobyrne** [comment]
Yes, let's prioritise this.
