### ISSUE TITLE
Modify Search Page to search all pools, not just digital_careers

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4374]
Currently, the search page is hard coded to filter by the digital_careers pool. Remove this restriction so that it counts candidates in all pools.

Note: this will make the way the Request Candidates button is displayed (in a card describing the Digital Careers pool) inaccurate. Do not worry about this for now.

## Acceptance Criteria
- [x] The search page will count applicants in all pools, as long as they meet all other constraints.
- [x] The search page does not rely on any data that comes from a specific pool (ie to populate any text or any form inputs)
- [x] Classification Filter should show only IT-01 , IT-02, IT-03, IT-04
- [x] This does not affect the "deprecated" version of the search - in other words, this change is only visible if APPLICANTSEARCH feature flag is true

**Comment by patcon** [comment]
- tristan: restrain to just hardcoded set, just IT classifications, +1 gray
- on prod we have IT and AS
- not helpful to delete AS on prod
