### ISSUE TITLE
Support Page - Transparent Dropdown

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4376]
Something funky is happening with the dropdown on the support page.  The list is transparent and shows the following component.

![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/db22f18b-e418-4fa6-a273-355f6c4bb0d7)

Solution: Convert support page to using SelectField instead of SelectFIeldV2 (for now)

**Comment by mnigh** [comment]
Seems like this is a `z-index` issue. This is also happening on the other implementations of the `SelectFieldV2` component in `UserTableFilterDialog`:

![Screen Shot 2022-10-18 at 21 44 42](https://user-images.githubusercontent.com/3046459/196577892-e104d1d3-8d5d-4243-a280-5d2e04ce560f.png)

**Comment by mnigh** [comment]
Might be resolved by:

- https://github.com/GCTC-NTGC/gc-digital-talent/pull/4401

**Comment by yonikid15** [comment]
Yea it will be fixed by #4401
