### ISSUE TITLE
Move "Required Skills" on My Experience page during application

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4390]
Move the list of required and asset skills to above the Add Experience buttons.

Also re-style the component.

[FIGMA LINK](https://www.figma.com/proto/spDwyr56BgQKrSdRiHztPL/Skills-and-EX---Poster-and-application-V2?page-id=0%3A1&node-id=138%3A2829&viewport=-176%2C-5109%2C0.49&scaling=min-zoom&starting-point-node-id=226%3A4567)

## Acceptance Criteria
Styling changes:
- title to section
- background color
- spacing changes
- slight text changes

**Comment by Jerryescandon** [comment]
![image](https://user-images.githubusercontent.com/16977254/196973760-3cb92a8d-8ba2-4ff8-ae1a-eeccd9b0cf63.png)

**Comment by tristan-orourke** [comment]
@Jerryescandon

**Comment by Jerryescandon** [comment]
![image](https://user-images.githubusercontent.com/16977254/196996519-cc728e91-e822-4fbd-9227-c3e32f322504.png)
