### ISSUE TITLE
Combine Search Bar and Families filter for Skill Picker

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4392]

**Comment by esizer** [comment]
#4136 includes a component (`DropdownMenu`) that will make this easier.

**Comment by Jerryescandon** [comment]
I think we can confidently NOT do this right meow, in case no one has started this yet
We have received Lauren guidance

**Comment by petertgiles** [comment]
> I think we can confidently NOT do this right meow,

Does this mean we do want to do this but it's not urgent or that this issue should be labelled blocked?

**Comment by Jerryescandon** [comment]
not urgent, the big issue has been fixed by removing skill picker in here and leaving only need to have and nice to have. this would still be useful for "Profile" and "Search talent" pages but its not as urgent in those cases.
