### ISSUE TITLE
When a user views the Skills page of an application for the second (or more) time, display the required skills in red

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4393]
## ✨ Feature

When a user views the Skills page of an application for the second (or more) time, display the required skills in red.

## 🕵️ Details

Add any additional details that could assist with the development of the new feature.

## 🎨 Design File

Include a link to the design file (if it exists).

## 📸 Screenshot

![Figma_Rq2RrvrbcW](https://user-images.githubusercontent.com/16977254/196971269-77a0df73-5cab-47d2-a460-1904911e9597.gif)

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] On the first visit to the application skills page, the behaviour is unchanged
- [ ] On the second visit to the application skills page, the required skills are in red (see screenshot)
- [ ] Any visit to the skills page outside an application context, the behaviour is unchanged

**Comment by petertgiles** [comment]
How do we figure out when a user has visited a page before?  Can we pull that from history?  Should we write hook to tell us what visit number to current page it is?

**Comment by mnigh** [comment]
This issue is the only one left before the https://github.com/GCTC-NTGC/gc-digital-talent/issues/4388 epic can be completed.

@Jerryescandon is this still something that is planned in current designs?

**Comment by Jerryescandon** [comment]
This was based on the old designs, I think we can close this one and make a new one if it comes up.
