### ISSUE TITLE
Improve prod.robots.txt

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4395]
Here's the current situation:
- talentsearch has robots.txt file that makes everything searchable.
- tc-report has a robots.txt file of its own, which disallows everything.
- its currently the tc-report version which is served at the root /robots.txt url.

TODO:
- ~on UAT (and any non-prod environment), serve an alternate robots.txt file which disallows everything.~ #4618 
- on prod, serve a robots.txt that we've thought more carefully about.

## Acceptance Criteria
- [ ] Modify (or create) `infrastructure/conf/prod.robots.txt` file that allows/disallows the following pages/sections:
    - [ ] disallow admin
    - [ ] disallow profile
    - [ ] disallow logged-out
    - [ ] disallow talent search? (@gobyrne ?)
    - [ ] disallow applications or /create-application
    - [ ] allow homepage
    - [ ] allow browse jobs
    - [ ] allow individual job posters
    - [ ] allow tc-report (all of it)
    - [ ] allow iap homepage
    - [ ] allow support page and footer links
    - [ ] allow login info
    - [ ] provide testing plan for reviewers
- Note that all rules should work with or without language codes
- Note that language codes can be arbitrary, because we plan to add more indigenous languages as we go.

**Comment by gobyrne** [comment]
Could we disallow everything on UAT though?

**Comment by tristan-orourke** [comment]
> Looks like the talentsearch robots.txt file doesn't disallow anything, which is fine.
> The robots.txt file in tc-report disallows everything, so let's change that.

But also looks like we're serving the tc-report file, so... less fine.

**Comment by tristan-orourke** [comment]
If we want to serve different robots files on UAT and Prod, how do we do that?
🤔 
Do we serve a response directly from the htaccess file?

**Comment by brindasasi** [comment]
This is working as intended in UAT. Good to go!
