### ISSUE TITLE
Investigate how to procure and set up a subdomain

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4396]
## :question:  Spike Question
- What's involved in getting a subdomain to work (eg report.talent.canada.ca)? Both on the technical and administrative sides.

Timebox: 1 Jira ticket

**Comment by mnigh** [comment]
I am not sure who our "account manager" is but the [request form](http://requestform.portal.gc.ca/tickets.html) can only be filled out and submitted on the network.

>Note: your account manager can submit new Canada.ca sub-domains and change requests to the Principal Publisher using the [Request form for Canada.ca](http://requestform.portal.gc.ca/tickets.html). Sub-domain requests are reviewed by the Treasury Board of Canada Secretariat.

source: https://www.canada.ca/en/treasury-board-secretariat/services/government-communications/canada-content-information-architecture-specification/organizing-content.html#toc3:~:text=Note%3A%20your%20account%20manager%20can%20submit%20new%20Canada.ca%20sub%2Ddomains%20and%20change%20requests%20to%20the%20Principal%20Publisher%20using%20the%20Request%20form%20for%20Canada.ca.%20Sub%2Ddomain%20requests%20are%20reviewed%20by%20the%20Treasury%20Board%20of%20Canada%20Secretariat.

**Comment by mnigh** [comment]
I just submitted a request to Principal Publisher via the [request form](http://requestform.portal.gc.ca/tickets.html) asking about the possibility of creating a fourth-level domain (**report.talent.canada.ca**). 🤞

**Comment by mnigh** [comment]
Positive news from Principal Publisher: "sub-subdomain report.talent.canada.ca does not exist and therefore can be used". Next step is filling out another form that includes DNS information, among other things.

**Comment by mnigh** [comment]
[Jira ticket](https://jira.tbs-sct.gc.ca/browse/AZ-15479) created (on 🔒 network). Feel free to add any additional questions there as well if what I wrote is not enough.

**Comment by brindasasi** [comment]
Tristan prefers blob storage. Keeping it same place and have it url pointed to that would still need the maintenance from us. 
Peter prefers  hosted in a sep space. 
Can we ask Rob for the path forward on blob storage?

**Comment by mnigh** [comment]
To finish this spike, here is the answer to the original question.

## Question
What's involved in getting a subdomain to work (eg report.talent.canada.ca) both on the technical and administrative sides?

## Answer
Create a [TBS Jira](https://jira.tbs-sct.gc.ca/) ticket asking for IMTD to help creating the DNS entry.
