### ISSUE TITLE
Server is ignoring timezone when processing and storing a datetime

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4397]
https://github.com/GCTC-NTGC/gc-digital-talent/issues/4041#issuecomment-1279468760

## Acceptance Criteria
- [ ] When we send a datetime to the API, the api properly converts it from whatever timezone to UTC _before_ storing it.

**Comment by tristan-orourke** [comment]
Or do we just convert every datetime in the api & database to datetimetz?

**Comment by esizer** [comment]
> Or do we just convert every datetime in the api & database to datetimetz?

Actually, the opposite. We are converting everything to a `datetime`. @petertgiles can confirm, but I believe that is correct.

**Comment by petertgiles** [comment]
> We are converting everything to a `datetime`

Yeah, that was what I thought we were doing and got confirmation on with [this post](https://talent-cloud.slack.com/archives/CB424V61J/p1666011311745459) on Slack.
> API fields of type DateTime should always be interpreted as UTC and it is the front end's responsibility to convert to and from a zone as needed
API fields of type DateTimeTz (only PoolAdvertisement.expiryDate right now) should be changed to be DateTime

I think there are very few DateTimes actually being sent to the API.  Most are just backend autogenerated timestamps.

**Comment by petertgiles** [comment]
#4407 adds date-fns-tz and a some helper functions to dateUtils so it's pretty easy to handle this in the frontend now.

**Comment by petertgiles** [comment]
I think this should be closed unless there is a specific form that is sending times in the local zone to the API.
