### ISSUE TITLE
CountApplicants query can return total number, plus number per pool

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4398]
Update countApplicants query to return a map of pool -> number in addition to the total number of candidates.
Return data in shape of:
```
{
  total: Number
  byPool: [
    {poolId: Number }
  ]
}
```

## Acceptance Criteria
- [ ] Test with phpunit test
- [ ] Make use of SQL groupBy to do this efficiently
- [ ] Make sure doesn't break any existing uses of the query (instead of using result as a number can use result.total, or something)

**Comment by vd1992** [comment]
giving some thought to this, will this function within the Schema file or will it require a custom Query Resolver file
if it requires the latter, would that entail duplicating all the query builder into that Resolver file?
