### ISSUE TITLE
actions/checkout inconsistent version

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#4404]
## Description
The versions vary

## Screenshot
![image](https://user-images.githubusercontent.com/40485260/197043450-2955887a-d521-4872-afa6-f956eea1e002.png)

## Acceptance Criteria
- [ ] resolve the discrepancy 

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by mnigh** [comment]
I wonder if it would be worth it to use Dependabot to create PRs for these? 

Article: [Keeping your actions up to date with Dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot)
