### ISSUE TITLE
Refactor: rename PoolCandidateFilterInput in schema

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4415]
Spun off https://github.com/GCTC-NTGC/gc-digital-talent/pull/4129#pullrequestreview-1149904878

The `PoolCandidateFilterInput` type in our GraphQL schema is used to search/filter Pool Candidates, but it now differs significantly from the `PoolCandidateFilter` type (which represent data stored in the database). `PoolCandidateFilterInput` is not used in creating or updating `PoolCandidateFilter` objects, and is only incidentally related. To reduce confusion, we could rename `PoolCandidateFilterInput`.

**Comment by vd1992** [comment]
No longer applicable with #6676
