### ISSUE TITLE
Manual Testing: migration which copies data from Pool Candidates to Users

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4439]
Tests #4359

- [x]  Prepare Test Data with Applicant , Skill & Experience mapping
- [x]  Turn off Direct Intake Flag  on UAT and manually input the user data we created in step 1 
- [x]  Run the migration 
- [x]  Turn on Direct Intake Flag and verify data is in place

**Comment by brindasasi** [comment]
verified both in local & UAT. Tristan opened an issue as above linked. Everything else looks good to me.
