### ISSUE TITLE
Can't navigate from Create Account page

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4441]
The first time a new user logs in they are redirected to the Create Account page.  There's a strange behavior where there are navigation links across the top of that page but if any are clicked they are immediately redirected back to this page.  This would be quite confusing to a new user.

I'm not sure what the best solution would be.  Don't redirect the user here if they want to go somewhere else?  Not give them the links?

https://user-images.githubusercontent.com/8978655/197577752-d8c15de3-7f8d-4960-93bf-8d4fad596ae9.mp4

**Comment by esizer** [comment]
Maybe we could only redirect if they are attempting to access a profile page? i.e `/users/*`? It migt also be important to explain why they keep getting redirected to that page in the alert. Something like:

"In order to access and update your profile, we need to gather some information first. Please, fill out the following form to continue building your profile."

**Comment by esizer** [comment]
@petertgiles I think this may have been solved by #4597 

Can you confirm?

https://github.com/GCTC-NTGC/gc-digital-talent/blob/2e21c514256b1db65ee30e1d40326a7fcb5471df/frontend/talentsearch/src/js/components/Router.tsx#L273-L276

https://github.com/GCTC-NTGC/gc-digital-talent/blob/2e21c514256b1db65ee30e1d40326a7fcb5471df/frontend/talentsearch/src/js/components/createAccount/CreateAccountRedirect.tsx#L24-L44

**Comment by petertgiles** [comment]
Mostly of the links work great!  I get this one at "My applications" now.  I'll close this and open a new one for this.
![image](https://user-images.githubusercontent.com/8978655/203421810-e42063d5-1606-4d16-93ef-9a4c7d077a57.png)

**Comment by petertgiles** [comment]
Opened  #4877
