### ISSUE TITLE
"Apply for this process" button broken if not logged in

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4445]
## Description
If you know the url for a Job Advertisement, you can visit the page without being logged in. However, clicking the "Apply" buttons in that case simply does nothing. It should do something... but what?

1. Should the apply button redirect user to login page, with post-login-redirect sending you to application process?
2. Should the apply button redirect user to login page, with post-login-redirect sending you back to Advertisement page?
3. Should the apply button be disabled, with text instructing user to log in before applying?
4. Should the page simply be inaccessible if not logged in, in which case trying to visit the page redirects you to login first?

## Screenshot
![one of the apply buttons on the Job Advertisement](https://user-images.githubusercontent.com/4313717/197636518-9e44085f-d9f3-4640-abaf-2e316df39465.png)

## Acceptance Criteria
- [ ] ...

**Comment by tristan-orourke** [comment]
Related to #4446

**Comment by Jerryescandon** [comment]
Definitely option 1
