### ISSUE TITLE
Browse Opportunities requires being logged-in

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4446]
Right now, you must be logged in to view the Browse Opportunities page. Is that intended?

Oddly, you do _not_ need to be logged in to view a specific pool advertisement, if you know the url. On the other hand... #4445.

**Comment by tristan-orourke** [comment]
@Jerryescandon could use your feedback on this and #4445

**Comment by Jerryescandon** [comment]
Definitely option 1

**Comment by Jerryescandon** [comment]
Browse opportunities should be available for everyone. 
Should not require log-in.
