### ISSUE TITLE
Upgrade to npm 9

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4449]
Upgrade to NPM 9 

https://github.blog/changelog/2022-10-24-npm-v9-0-0-released/

Acceptance Criteria:
- [ ] v9 used in maintenance container
- [ ] v9 used in github workflows
- [ ] v9 specified in package.json files
- [ ] Turborepo continues to work normally
- [ ] Help your teammates upgrade their local environments

**Comment by vd1992** [comment]
where does that touch
I can find restriction to 8.3.0 in workflows here, latest would be 8.19.2 (pre v9) 

![image](https://user-images.githubusercontent.com/40485260/197875080-11524f4d-3a78-440d-95f3-e66b91541b9e.png)

**Comment by esizer** [comment]
Not a bad idea at all! Though, we should at least block this until general availability slotted in for November 9th.

**Comment by petertgiles** [comment]
> where does that touch

Also the package.json files
![image](https://user-images.githubusercontent.com/8978655/198051547-e968bb3e-4bab-46be-a548-ff767a1d135a.png)

**Comment by petertgiles** [comment]
Related: #2759

**Comment by petertgiles** [comment]
Going to use Yarn
