### ISSUE TITLE
♻️ Dead Code - Unreferenced code

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4452]
## Description
There are several unreferenced parts of code that still exist in the codebase.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/c8745507e19370f205df7ce02f4b3e8b706ac4d1/api/.env.example#L6

https://github.com/GCTC-NTGC/gc-digital-talent/blob/c8745507e19370f205df7ce02f4b3e8b706ac4d1/packages/webpack-config/webpack.base.js#L50-L52

https://github.com/GCTC-NTGC/gc-digital-talent/blob/c8745507e19370f205df7ce02f4b3e8b706ac4d1/apps/web/src/constants/talentSearchConstants.ts#L4-L5

Acceptance Criteria:
 - [ ] Unused code removed from files
 - [ ] Unused keys removed from IaC (compare keys in codebase to .env files)
 - [ ] New IaC pushed to DEV for testing

**Comment by tristan-orourke** [comment]
Clarification -  some of these keys can be removed from the .env files but not the IaC, because they're not used by the respective project, but are used by the api project under the same name.

**Comment by mnigh** [comment]
@petertgiles this issue has changed because of the changes that were part of #5065. Does my updated description make sense?
