### ISSUE TITLE
API Allows users to overwrite applications

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#4463]
## 🐛 Bug

Currently, we only check if a user has already applied to a pool on the client during render. It is possible to have the page open in two different tabs/windows/computers/etc, apply for it in one, then in the separate location, apply again and overwrite the existing application.

h/t @petertgiles for finding this in https://github.com/GCTC-NTGC/gc-digital-talent/pull/4451#discussion_r1005953570

## 🎥 Recording

https://user-images.githubusercontent.com/4127998/198103866-751a9207-a890-4e1c-97b4-d93343664db0.mov

## ☔️ Possible Solution

We need update the mutation to throw the `ValidationException` earlier to prevent this and update the `CreateApplication.tsx` logic, moving it to the backend. 

```graphql
type Mutation {
  createApplication(userId: ID!, poolId: ID!): PoolCandidate
    @can(ability: "create", injectArgs: true)
}
```

```php
// App\GraphQL\Mutations\CreateApplication.php

$exists = PoolCandidate::where('user_id', $user->id)
  ->where('pool', $args['poolId'])
  ->exists();

$pool = Pool::find($args['poolId']);
if(in_array($pool->status, [POOL_ADVERTISEMENT_IS_DRAFT, POOL_ADVERTISEMENT_IS_EXPIRED])) {
  throw ValidationException::withMessages(['you are unable to apply to this pool']);
}

if($exists) {
  throw ValidationException::withMessages(['you have already applied to this pool']);
}

$application = PoolCandidate::create([
  'user_id' => $args['userId'],
  'pool_id' => $args['poolId'],
]);
```

```tsx
// CreateApplication.tsx

const isCreating =  !creating && !mutationData;
const hasRequiredData = userId && poolId;

if(!hasRequiredData) {
  redirect(redirectPath);
}

if(!isCreating) {
  executeMutation({ userId, poolId })
    .then((result) => {
      // Success, move onto application
    })
    .catch((err) => {
      // API throws error so we land here
    });
}

return <Loading />;
```

## ✅ Acceptance Criteria

- [ ] API does not allow users to recreate application
- [ ] API returns error if:
    - PoolCandidate already exists with `userId` and `poolId`
    - Pool is not published
 - [ ] `CreateApplication` logic simplified to handle fallback

**Comment by vd1992** [comment]
I feel this is circling back to this method I had
https://github.com/GCTC-NTGC/gc-digital-talent/blob/ce5194dc0b734ee69cbe89eefbfd391da7a88eb5/api/app/GraphQL/Mutations/CreateApplication.php

from this PR #4319
