### ISSUE TITLE
Remove "New User" button from Users table

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#4472]
Now that users are generated through the public facing side, there's no need for a New User button on the admin side.

![image](https://user-images.githubusercontent.com/16977254/198357036-315a73db-9b55-4375-940a-dcee29a55445.png)

## Acceptance Criteria
- [ ] ...

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by mnigh** [comment]
Feature, not a bug!
