### ISSUE TITLE
Fix Broken Link on on TC site

### ISSUE THREAD

**Issue by BrookeCameron** [GCTC-NTGC/gc-digital-talent#4473]
The old TC page Found here https://talent.canada.ca/en/talent-cloud) has an action that reads: "Visit the Indigenous Talent Program" 

![Image](https://user-images.githubusercontent.com/100953374/198358280-c1848cd1-2840-468e-9535-f3490ea2c3e5.png)

but when clicking on that button, it appears that the link is broken (link found here: [https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftalent.canada.ca%2Fen%2Fcommunities%2Findigenous-talent&amp;data=05%7C01%7CMeagan.Commonda%40tbs-sct.gc.ca%7C5ac9239d90ab433e0f4608dab694faae%7C6397df10459540479c4f03311282152b%7C0%7C0%7C638023048221870606%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&amp;sdata=YZ1Rk3DP5GXaLxoYFzC%2BAkN92FsLZV931%2BJhYn6Y5FQ%3D&amp;reserved=0<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftalent.canada.ca%2Fen%2Fcommunities%2Findigenous-talent&amp;data=05%7C01%7CMeagan.Commonda%40tbs-sct.gc.ca%7C5ac9239d90ab433e0f4608dab694faae%7C6397df10459540479c4f03311282152b%7C0%7C0%7C638023048221870606%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&amp;sdata=YZ1Rk3DP5GXaLxoYFzC%2BAkN92FsLZV931%2BJhYn6Y5FQ%3D&amp;reserved=0](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftalent.canada.ca%2Fen%2Fcommunities%2Findigenous-talent&amp;data=05%7C01%7CMeagan.Commonda%40tbs-sct.gc.ca%7C5ac9239d90ab433e0f4608dab694faae%7C6397df10459540479c4f03311282152b%7C0%7C0%7C638023048221870606%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&amp;sdata=YZ1Rk3DP5GXaLxoYFzC%2BAkN92FsLZV931%2BJhYn6Y5FQ%3D&amp;reserved=0%3chttps://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftalent.canada.ca%2Fen%2Fcommunities%2Findigenous-talent&amp;data=05%7C01%7CMeagan.Commonda%40tbs-sct.gc.ca%7C5ac9239d90ab433e0f4608dab694faae%7C6397df10459540479c4f03311282152b%7C0%7C0%7C638023048221870606%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&amp;sdata=YZ1Rk3DP5GXaLxoYFzC%2BAkN92FsLZV931%2BJhYn6Y5FQ%3D&amp;reserved=0)

Can we have this link fixed to face the IAP homepage (found here: https://talent.canada.ca/en/indigenous-it-apprentice )

Thank you.

**Comment by BrookeCameron** [comment]
@tristan-orourke please advise who to tag to fix this please and thanks 🙂

**Comment by mnigh** [comment]
@BrookeCameron this issue is part of the acceptance criteria for https://github.com/GCTC-NTGC/gc-digital-talent/issues/4105 and will be resolved with https://github.com/GCTC-NTGC/gc-digital-talent/pull/4468.

**Comment by petertgiles** [comment]
#4468 merged
