### ISSUE TITLE
Broken link on Home page

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4476]
## Description
Clicking the **Apply Now** button in the Indigenous Apprenticeship Program section on the Home page leads to a 404.

## Screenshot
![Screen Shot 2022-10-27 at 13 41 16](https://user-images.githubusercontent.com/3046459/198361638-45f05551-c958-4179-9619-9f252fa40b76.png)

## Acceptance Criteria
- [ ] clicking the link goes to Indigenous Apprenticeship Program home page in current locale

**Comment by mnigh** [comment]
### Possible solutions

1. Add / before ${locale} in:
https://github.com/GCTC-NTGC/gc-digital-talent/blob/72ed3b3f858ff687ed8fe62e217605fb276af992/frontend/talentsearch/src/js/components/Home/partials/Opportunities/Opportunities.tsx#L125

2. Use path like in:
https://github.com/GCTC-NTGC/gc-digital-talent/blob/72ed3b3f858ff687ed8fe62e217605fb276af992/frontend/talentsearch/src/js/components/Browse/BrowsePoolsPage.tsx#L276

**Comment by petertgiles** [comment]
I think this is fixed in main now.

**Comment by esizer** [comment]
Can confirm, it seems to work for me on main:


https://user-images.githubusercontent.com/4127998/199241305-64fbf80e-f564-4fd9-ad8c-e5d7ac154e3f.mov
