### ISSUE TITLE
Pool poster title

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#4482]
Oh boy there's a lot going on here and I dont even know where to begin, might need to split these up into tiny ones but here we go.

1. Pool poster title should include Specific title. I think we can use #4479 as guidance for the Pool title
2. Selected an AS classification. But it allowed me to select from the IT streams but  then displayed N/A in the poster title. Question for @gobyrne do we have AS specific streams? In any case, we should not allow AS selection to pull the IT list of streams
- If we do have AS streams, then we need to update that dropdown.
- if not, we need to hide the field from the edit pool when an AS is selected.

![image](https://user-images.githubusercontent.com/16977254/198367435-d4c3e6b4-ec9d-4d57-8c04-c04f31ef0498.png)

**Comment by petertgiles** [comment]
Regarding point 2:
Right now the streams are just a list of strings without any other dimensions like associated classification group.  We would need to get requirements and do some object modelling before it becomes possible to do this in a clean way.

**Comment by tristan-orourke** [comment]
Agreed with Peter on point 2. I'll move point 1 into its own ticket.

**Comment by gobyrne** [comment]
#1 is being fixed. For the rest we are relying on Admins not creating new classifications or using the AS classification to create new advertisements.
