### ISSUE TITLE
Clean up unused French translation strings

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4489]
We have a number of old French translation strings that are no longer used. They should be deleted to avoid confusion.

## References
Argument to remove orphans:
https://github.com/GCTC-NTGC/gc-digital-talent/blob/e498a72e1add9eb4a72246bbdb5a56a6f989f48a/frontend/common/src/tooling/checkIntl.js#L170-L178

Argument to remove orphans previously in use: https://github.com/GCTC-NTGC/gc-digital-talent/commit/60d5c6f31365ddba89f98400b897298ace3f9abc

**Comment by petertgiles** [comment]
Related #4305
