### ISSUE TITLE
"Group and Level" always empty in Summary of Filters

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4500]
PR #4454 changes how the Classification dropdown on the search page works. Instead of applying a filter directly to users' expected-classifications or expected-salary, it will now be used to filter which pools the searcher sees and can make requests for.

However, that's not reflected in the Summary of Filters component, which now will always be blank for "Group and Level":
![image.png](https://images.zenhubusercontent.com/5d9ded8fd25901000101f3f0/f3f2493b-6475-41cc-9964-7abb043189c7)

We need some design feedback on how to deal with this. My suggestion is to hide the "Group and Level" block if the filter doesn't have any (that way viewing old requests still works) and replace it with the Name or description of any Pools we're searching in.

## Acceptance Criteria
- [ ] Instead of showing classifications in the summary based on the "expectedClassifications" field of the filter (which has essentially been deprecated) lets show the classifications associated with any pools used in the filter.

**Comment by brindasasi** [comment]
This page is separate from deprecated Search Summary page. Hence this can be modified easily to display the selected group & level from previous page.

**Comment by brindasasi** [comment]
can be closed with #4528

**Comment by tristan-orourke** [comment]
Okay, well if we want to show classification in the filters, and the classification is just used to select pools, then lets just show the classifications associated with the pool filters.
