### ISSUE TITLE
Unclear to user why continue button is disabled on Application Step 1 page

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4546]
When working on an application, the "Continue to step 2" button is disabled if I don't have all the required skills. But as a user who doesn't know how this works, it's unclear that is the reason why, and what I need to do to continue.

**Comment by tristan-orourke** [comment]
@Jerryescandon here's my own user testing feedback. Probably already covered by someone else, but just in case.

**Comment by Jerryescandon** [comment]
Moved this to design backlog

**Comment by esizer** [comment]
Are we able to close this since we are moving to the new application workflow in the near future?

**Comment by Jerryescandon** [comment]
Yeah, I would think the new application flow would solve this.

**Comment by tristan-orourke** [comment]
Resolved by new Application ux
