### ISSUE TITLE
Date Requested value is not very friendly looking

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4548]
## Description
The Date Requested value is not very friendly.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/966c19094a9f3e7c825c0e36921526320b3d38a7/frontend/admin/src/js/components/searchRequest/SingleSearchRequest.tsx#L176

## Screenshot
![Screen Shot 2022-11-01 at 14 11 44](https://user-images.githubusercontent.com/3046459/199310728-35452a16-d080-4230-9218-cb4ed5dd8f27.png)

## Acceptance Criteria
- [ ] convert **requestedDate** into a friendlier looking format

**Comment by petertgiles** [comment]
It probably needs to be shifted from UTC to the local time zone, too.

Here's one option for date format:
![image](https://user-images.githubusercontent.com/8978655/199521992-083c05d0-3b96-43d8-a368-dace98529460.png)

**Comment by mnigh** [comment]
@Jerryescandon any thoughts from a design perspective?
