### ISSUE TITLE
Allow dependabot to manage action versions

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#4550]
## 👋 Introduction

We previously had a few out of date actions that were throwing warnings which were all manually bumped in #4547. @mnigh suggested setting up dependabot to also track versions of actions.

---

I wonder if it would be worth it to use Dependabot to create PRs for these? 

Article: [Keeping your actions up to date with Dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot)

_Originally posted by @mnigh in https://github.com/GCTC-NTGC/gc-digital-talent/issues/4404#issuecomment-1286060843_

---

## ✅  Acceptance Criteria

- [ ] Setup dependabot to track versions
- [ ] Manually keep an eye on it and wait for it to work?

**Comment by mnigh** [comment]
This should be as easy as changing this value to a value like 15:

https://github.com/GCTC-NTGC/gc-digital-talent/blob/966c19094a9f3e7c825c0e36921526320b3d38a7/.github/dependabot.yml#L73
