### ISSUE TITLE
Bug - Link text to go to IAP homepage on browse IT jobs page

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4558]
## Description
The link text to go to IAP homepage on browse IT jobs page does not include an action and does not lend itself to be translated well with `<hidden>` tags (used for providing context for screen readers) into French.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/66a95cffb5c7a8ffb27a7ba82a775cf255a7054d/frontend/talentsearch/src/js/components/Browse/BrowsePoolsPage.tsx#L281

## Screenshot
![Screen Shot 2022-11-02 at 12 23 13](https://user-images.githubusercontent.com/3046459/199547177-c7279d85-b950-4492-9e68-52de6bce71d6.png)

## Acceptance Criteria
- [ ] button text should fit in with nearby **Visit the talent search page**
- [ ] button text should avoid using `<hidden>`

**Comment by tristan-orourke** [comment]
Copy the homepage
