### ISSUE TITLE
Add indigenous languages to IAP homepage

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4573]
Add a new language selector to the IAP homepage for indigenous languages. This will change the language for this page only, not including the header and footer.

This can be implemented by having the new language switcher pass a second locale and set of compiled messages into another IntlProvider component which wraps the content of the page, but not the header and footer. Each new language will get its own file in `frontend/indigenousapprenticeship/src/js/lang`.

[Figma Prototype](https://www.figma.com/proto/tUuPyWzaZWSEwCflpfOLq6/IAP-Homepage---V3.5.2?page-id=0%3A1&node-id=803%3A625&viewport=-5833%2C2071%2C0.5&scaling=min-zoom&starting-point-node-id=117%3A1358)

![IAP Language Picker.png](https://images.zenhubusercontent.com/5d9ded8fd25901000101f3f0/8c10c582-acfc-4aef-9c2e-13ad06e4a40e)

For now, translations into 4 different languages have been provided, more will be provided in the future.

## Acceptance Criteria
- [ ] Language switcher appears at top of page
- [ ] All language between header and footer changes with language switcher
- [ ] Selecting a language in the language picker links you to the page in the correct language code.
  - [ ] Maybe we use a url query parameter for IL code for now, to not interfere with our existing language system.
- [ ] ensure that links on the IAP page use the `<a href="/support" hreflang="en">` format, if the page isn't already in en or fr

## Out of Scope
- Any change to the existing english-french language provider
- Any change to the existing english-french translation workflow (in terms of the scripts we run)
- Any localization of header, footer, or non-iap page
- Language code in URI path (don't interfere with existing language routing)
- Saved sate, local storage
- Generating JSON files is happening in  #4587
- Proofreading translations
- Fixing layout issues due to language differences
- Graphics with text in them changes

**Comment by tristan-orourke** [comment]
Translations:
[English text being translated.](https://github.com/GCTC-NTGC/gc-digital-talent/files/9930320/014-221021-022_001_TG_TR20760.-.IAP.Homepage.Text.English.to_Michif.docx)
[014-221021-022_001_TG_TR20760 - IAP Homepage Text English to_Michif.docx](https://github.com/GCTC-NTGC/gc-digital-talent/files/9930331/014-221021-022_001_TG_TR20760.-.IAP.Homepage.Text.English.to_Michif.1.docx)
[014-221021-022_001_TG_TR20760 - IAP Homepage Text English to_Plains Cree.docx](https://github.com/GCTC-NTGC/gc-digital-talent/files/9930333/014-221021-022_001_TG_TR20760.-.IAP.Homepage.Text.English.to_Plains.Cree.docx)
[014-221021-022_001_TG_TR20760 - IAP Homepage Text English to_Western Ojibway.docx](https://github.com/GCTC-NTGC/gc-digital-talent/files/9930335/014-221021-022_001_TG_TR20760.-.IAP.Homepage.Text.English.to_Western.Ojibway.docx)
[014-221021-022_001_TG_TR20760 - IAP Homepage Text English to_Mikmaq.docx](https://github.com/GCTC-NTGC/gc-digital-talent/files/9930337/014-221021-022_001_TG_TR20760.-.IAP.Homepage.Text.English.to_Mikmaq.docx)

**Comment by mnigh** [comment]
there would need to be a SVG supplied for each language: https://github.com/GCTC-NTGC/gc-digital-talent/blob/fac8348489d0c5f4c840e2acc165a67ebbbb32c0/frontend/indigenousapprenticeship/src/js/components/Home/Home.tsx#L81

**Comment by petertgiles** [comment]
Here's the actual strings files for the IAP site - exactly what was sent for French translation.  A lot of the tedious work will be to substitute in the right strings to this file for each language.
[en.txt](https://github.com/GCTC-NTGC/gc-digital-talent/files/9932058/en.txt)

**Comment by mnigh** [comment]
Another future consideration for adding other languages is that our `whitelist.yml` files will need to be modified as strings that are the same in English and French might not be equivalent in other languages. Thankfully for `/indigenousapprenticeship`, whitelist.yml is currently empty.

**Comment by mnigh** [comment]
I also noticed that there are some design changes that will need to be made to accommodate for longer string length.

## Screenshots
![Screen Shot 2022-11-04 at 15 01 20](https://user-images.githubusercontent.com/3046459/200334427-d48ece77-f474-45c1-a8b4-d4b58f3cdf03.png)
![Screen Shot 2022-11-04 at 15 01 50](https://user-images.githubusercontent.com/3046459/200334434-24f4b58f-c9d9-4edf-bb7d-aca1155c4cae.png)
![Screen Shot 2022-11-04 at 15 00 41](https://user-images.githubusercontent.com/3046459/200334440-74273588-965d-42d3-9784-48b775734128.png)

**Comment by gobyrne** [comment]
@Jerryescandon How do you get back to original language after selecting an indigenous language?

**Comment by gobyrne** [comment]
This has been split up into other issues.
