### ISSUE TITLE
Manage Requests Disabled

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#4575]
## Description
The button to manage requests from inside the Pool Details is not working properly.
E.g. Digital careers has many requests and this button is not enabled

Context: Even if it was working properly, the fact that it looks disabled is confusing to users.

To do: Remove any fancy logic and just enable it all the time

![image](https://user-images.githubusercontent.com/16977254/199758164-4c97dda7-b278-4b0f-8a8f-e4a1fef8d8a9.png)

## Acceptance Criteria
- [ ] ...

**Comment by vd1992** [comment]
There appears to be no actual logic involved, it is always disabled and has no route/link

![image](https://user-images.githubusercontent.com/40485260/200697172-768f8f46-a2b8-43f2-85d2-27b90226724e.png)

**Comment by vd1992** [comment]
I am not even sure if the component exists for this functionality 😵

**Comment by petertgiles** [comment]
@Jerryescandon where should this button go?  http://localhost:8000/en/admin/talent-requests with a pool filter added?  Or a new page that we don't have yet?

**Comment by vd1992** [comment]
odd, you cannot search by pool on the All Requests page

https://recordit.co/IHNtOQdqVq
