### ISSUE TITLE
Save Buttons dont change state

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#4576]
## Description
In the Pool edit page, after you select essential or asset skill and hit the save button the save button will not change to the submitted state, unlike the other save buttons on this page.

## Screenshot: Prototype
![image](https://user-images.githubusercontent.com/16977254/199759936-92cabcbb-0087-4da0-b84f-5cf4094dd9df.png)

## Acceptance Criteria
- [ ] ...

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by vd1992** [comment]
This could be a bit trickier than it seems, skill selection logic is rather different from the other sections:
- - - - - - - -- - - - - - - - - - - -

### Other Sections

Nest things in a `<Form Provider>`
Submit things using `onSubmit`
Submit logic run through the component `<Submit>`

![image](https://user-images.githubusercontent.com/40485260/201229171-632463f5-f607-442d-9e58-b02993fbe654.png)

submitting uses `FormValues`

![image](https://user-images.githubusercontent.com/40485260/201229288-eb1ef530-8aca-4056-85de-b0424de0e127.png)

**Comment by vd1992** [comment]
### Skills Sections (Essential and Non-Essential)

No `<FormProvider>` containing everything, instead the `<SkillPicker>` is the form
Skills selected exist outside of the component, like props
Submitting handled by a button component

![image](https://user-images.githubusercontent.com/40485260/201229768-2b6bdeb5-cd45-400f-9e22-0401612265d1.png)

Submitting takes the skills selected that exist as a variable, passed in as props for the selector above, then passes it in as an argument for the `handleSave `function. No use of `FormValues`

![image](https://user-images.githubusercontent.com/40485260/201230002-df08f7b3-a8ad-4f65-90f4-638bcafac793.png)

**Comment by vd1992** [comment]
### Solution(s)?

Would need to either replace the button with a bespoke `<Submit>` component or update the existing one's props to allow it to work with the skills section. This allows the skills section to continue to submit in its unique way. 

or

Refactor the logic entirely, possibly nesting the `<SkillPicker>` in another `<FormProvider>` in order to have skills selected exist as a `FormValues` entity to be submitted and replace the button with the current `<Submit>` component.
