### ISSUE TITLE
See definition doesnt change

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#4577]
## Description
Pool edit page > Skill picker
When clicking the see definition, it should change the label to hide definition after being opened

## Screenshot: Prototype
![image](https://user-images.githubusercontent.com/16977254/199760229-92a70d13-b741-4197-959f-fb4e9fded71a.png)

## Acceptance Criteria
- [ ] ...

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by mnigh** [comment]
I'm pretty this is the what is breaking it: https://github.com/GCTC-NTGC/gc-digital-talent/pull/4242#discussion_r992692948

### Works
`onClick={() => setIsOpen(!isOpen)}`

 ### Does not work
`onClick={(currentIsOpen) => setIsOpen(!currentIsOpen)}`

**Comment by tristan-orourke** [comment]
Oh yeah, that's definitely what it was supposed to be! 😅 
`onClick={() => setIsOpen((currentIsOpen) => !currentIsOpen)}`
