### ISSUE TITLE
strings not enclosed in Intls

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#4580]
## Description
strings ought to be wrapped in Intls like a bow on a present

## Locations
https://github.com/GCTC-NTGC/gc-digital-talent/blob/824dc237f43281589a4dd2635f1b1391ea8632e7/frontend/admin/src/js/components/apiManagedTable/useFilterOptions.tsx#L61-L62

https://github.com/GCTC-NTGC/gc-digital-talent/blob/824dc237f43281589a4dd2635f1b1391ea8632e7/frontend/admin/src/js/components/apiManagedTable/useFilterOptions.tsx#L101-L102

## Acceptance Criteria
- [x] wrap 'em

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by mnigh** [comment]
In a few other places as well, but can be a shared string in `common` string.

![Screen Shot 2022-11-07 at 15 34 54](https://user-images.githubusercontent.com/3046459/200409841-92d69c06-a1da-4fe2-9f00-548b92763237.png)
