### ISSUE TITLE
Nginx/PHP 8.1 Azure env scouting 

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4581]
Find out specs of IMTD VM image ([debian <=> ubuntu compat chart](https://askubuntu.com/a/445496/232907))

## Acceptance Criteria
- [x] PHP version: 8.1.6
- [x] nginx version: 1.22.0
- [x] linux distro & version:

**Comment by mnigh** [comment]
Estimate?

**Comment by tristan-orourke** [comment]
The appsvc we're expected to switch to runs:
PHP Version 8.1.6
Nginx version 1.22.0

Asked about OS in a followup question.

**Comment by tristan-orourke** [comment]
I was referred to this github issue: https://github.com/Azure-App-Service/php/issues/79, which says:
>> Do you have any plans for releasing the PHP 8.0 image? Thanks
> See: https://mcr.microsoft.com/v2/appsvc/php/tags/list

I'm not sure exactly how that repo is connected to the list of images available, because the repo only goes up to PHP 7.4, and the list includes 8.1. Also, the tags list includes images which clearly use apache, like `8.1-apache_20221102.2`, so I'm going to ask if we can use that for now.

Also, Robert suggested a tool, [Dive](https://github.com/wagoodman/dive), for investigating images more closely. Its pretty neat! After installing it, run `dive mcr.microsoft.com/appsvc/php:8.1-apache_20221102.2` in your terminal to see all the layers of the docker image, and the resulting folder directory. I'd love to investigate some of these images more with @patcon.

**Comment by tristan-orourke** [comment]
Here's the image we have an azure: [mcr.microsoft.com/appsvc/php:8.1-fpm_20221102.2](http://mcr.microsoft.com/appsvc/php:8.1-fpm_20221102.2)
