### ISSUE TITLE
Get app working locally with Nginx 

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4582]
Re-ticketed from https://github.com/GCTC-NTGC/gc-digital-talent/issues/3560.

Don't need to change the php version.

## Acceptance Criteria
- Replace apache-php docker image with nginx-php docker image in a new docker-compose
- The app works the same. In particular, routing, live-reloading env variables (feature flags). images/resource files served correctly, 404
- Create issues for gaps in e2e testing
- e2e tests continue to pass in old version of docker-compose file

**Comment by petertgiles** [comment]
https://azureossd.github.io/2021/09/02/php-8-rewrite-rule/index.html

**Comment by tristan-orourke** [comment]
We want to make this work with:
PHP Version 8.1.6
Nginx version 1.22.0

Not sure yet what OS version our appsvc will use.

**Comment by tristan-orourke** [comment]
https://github.com/GCTC-NTGC/gc-digital-talent/issues/4581#issuecomment-1304233370
