### ISSUE TITLE
Pin image versions used in Github Actions

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4589]
A lot of our Github Actions use a floating image like "ubuntu-latest".  Let's pin these to specific versions so that the behavior of our CI doesn't change unexpectedly.

**Comment by mnigh** [comment]
@petertgiles Possible duplicate of https://github.com/GCTC-NTGC/gc-digital-talent/issues/4102?

😄

**Comment by petertgiles** [comment]
Oh come on....
Wow, subconsciously I must be pretty worried about these!
