### ISSUE TITLE
Correction to IAP Home Page - French site

### ISSUE THREAD

**Issue by MCommonda** [GCTC-NTGC/gc-digital-talent#4622]
There is a paragraph on the French page that is not translated in French, see screenshot:

![Image](https://user-images.githubusercontent.com/100953374/200368238-acc6a1fb-563a-42db-a401-4f26019b8381.png)

Please change to the following text:

En valorisant et en misant sur le potentiel d’une personne plutôt que sur son niveau de scolarité, le programme élimine l’un des plus grands obstacles qui existent en matière d’emploi dans l’économie numérique. Le programme a été élaboré par, avec et pour tous les peuples autochtones à travers le Canada. Il intègre les préférences et les besoins des apprenants autochtones tout en reconnaissant l’importance de la communauté.

Thanks!

**Comment by gobyrne** [comment]
@mnigh please close if this is done

**Comment by brindasasi** [comment]
Verified this has been fixed.
