### ISSUE TITLE
Bug - Date formatting displayed in French incorrectly

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4625]
spacing looking a little weird on the dates 🤐 

![image](https://user-images.githubusercontent.com/40485260/200396852-ba36c99a-7fa3-4656-893b-d148f003e330.png)

_Originally posted by @vd1992 in https://github.com/GCTC-NTGC/gc-digital-talent/issues/4556#issuecomment-1306082943_

**Comment by mnigh** [comment]
These lines are problematic for i18n that are used in the `getDateRange` function:

https://github.com/GCTC-NTGC/gc-digital-talent/blob/bcde714788b12ece51e8c4081196edfa6e2c9eb2/frontend/common/src/helpers/dateUtils.ts#L21-L22

**Comment by esizer** [comment]
@petertgiles wrote a really good date formatter we are using elsewhere. I think we can replace the `formattedDate` helper with the new `formatDate`.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/70518649212b177e78866304c9eb6f134ba9c908/frontend/common/src/helpers/dateUtils.ts#L69-L78
