### ISSUE TITLE
Implement Lighthouse directive

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4626]
https://github.com/GCTC-NTGC/gc-digital-talent/blob/9968de2525e4614e54d5a66147279df65539f738/api/app/GraphQL/Directives/PluckDirective.php#L13

## Acceptance Criteria
- [x] remove stale comment

**Comment by mnigh** [comment]
@tristan-orourke it appears that the directive has been implemented, can the TODO comment in the code be removed?

https://github.com/GCTC-NTGC/gc-digital-talent/blob/371f673df101139f77228108d10c647027d18db0/api/graphql/schema.graphql#L819-L824

**Comment by tristan-orourke** [comment]
@mnigh Lol, yes. Looks like that particular todo was probably redundant from the get-go.
