### ISSUE TITLE
Decide on a default expiry date, placeholder of year past submission

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4627]
https://github.com/GCTC-NTGC/gc-digital-talent/blob/917d6335def3d30afc8ce30f93e8098a9c583cae/api/app/GraphQL/Mutations/SubmitApplication.php#L34

**Comment by mnigh** [comment]
@GCTC-NTGC/developers is this comment still relevant or is it obsolete and can be removed? if it is still relevant, what do we need to decide on a default expiry date?

**Comment by vd1992** [comment]
it would solve #6363 to make it null instead

**Comment by tristan-orourke** [comment]
Duplicate of #6363
