### ISSUE TITLE
♻️ Remove unused todos

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4637]
## Acceptance Criteria
- [x] Remove unused test stub
https://github.com/GCTC-NTGC/gc-digital-talent/blob/72bb26c0f0bff832ad8abd01abf540a08fc29d82/apps/web/src/components/Table/ApiManagedTable/useFilterOptions.test.tsx#L118

- [x] And for #4643, remove unused todo:
https://github.com/GCTC-NTGC/gc-digital-talent/blob/72bb26c0f0bff832ad8abd01abf540a08fc29d82/apps/web/src/pages/Users/IndexUserPage/components/UserTableFilterDialog/UserTableFilterDialog.test.tsx#L168

- [x] Unused todo:
https://github.com/GCTC-NTGC/gc-digital-talent/blob/72bb26c0f0bff832ad8abd01abf540a08fc29d82/apps/web/src/components/Table/ApiManagedTable/useFilterOptions.tsx#L106

- [x] Unused todo:
https://github.com/GCTC-NTGC/gc-digital-talent/blob/9968de2525e4614e54d5a66147279df65539f738/frontend/admin/src/js/components/apiManagedTable/useFilterOptions.tsx#L39

**Comment by petertgiles** [comment]
@patcon Could you fill out this stub, please?

**Comment by patcon** [comment]
So let's just remove this test stub :)
