### ISSUE TITLE
♻️ Remove `enableEducationSelect` toggle for filter dialog components

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4638]
## Description
Back when we made the filter dialog, we were phasing out the education fields. We had a [toggle](https://github.com/GCTC-NTGC/gc-digital-talent/blob/72bb26c0f0bff832ad8abd01abf540a08fc29d82/apps/web/src/components/Table/ApiManagedTable/useFilterOptions.tsx#L40) to show them when enabled, but could be removed later. These props (`enableEducationSelect`) now default to false, and shouldn't be used anywhere.

## Acceptance Criteria
- [ ] toggle arg `enableEducationType` is removed from `useFilterOptions` hook
- [ ] associated props are removed from all filter dialog components that use it
- [ ] remove associated testing-library tests of `enableEducationSelect`
- [ ] removed the associated TODO comment from #4644

**Comment by mnigh** [comment]
This comment goes on to reference a [figma](https://www.figma.com/proto/XS4Ag6GWcgdq2dBlLzBkay?node-id=1064:5862#224617157 ) file that contains a comment
> for posterity, the data backing this MultiSelect is in flux, and so leaving this out for now.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/12ce25200da28f7c955a393c4b2536a8a7b8db92/frontend/admin/src/js/components/apiManagedTable/useFilterOptions.tsx#L37

@patcon is the data backing this MultiSelect still in flux?

**Comment by mnigh** [comment]
@patcon is the TODO comment still relevant or can it be removed?

**Comment by patcon** [comment]
Updated!

**Comment by patcon** [comment]
Or wait... was this supposed to be turned on, and never was? Like was it that we were _adding_ education type, and wanted that in the filter later? cc: @Jerryescandon @substrae 

Not sure if we should default to having education type filter in the filter dialogs, or the inverse :)
