### ISSUE TITLE
Implement way to return `fetching` states from hook

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4639]
https://github.com/GCTC-NTGC/gc-digital-talent/blob/9968de2525e4614e54d5a66147279df65539f738/frontend/admin/src/js/components/apiManagedTable/useFilterOptions.tsx#L39

**Comment by patcon** [comment]
This TODO can be removed, as it seems to be done already:

https://github.com/GCTC-NTGC/gc-digital-talent/blob/9968de2525e4614e54d5a66147279df65539f738/frontend/admin/src/js/components/apiManagedTable/useFilterOptions.tsx#L134-L138

**Comment by mnigh** [comment]
@petertgiles this TODO can added to #4637 and this issue closed.
