### ISSUE TITLE
Add async filters

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4643]
https://github.com/GCTC-NTGC/gc-digital-talent/blob/72bb26c0f0bff832ad8abd01abf540a08fc29d82/apps/web/src/pages/Users/IndexUserPage/components/UserTableFilterDialog/UserTableFilterDialog.test.tsx#L168

**Comment by petertgiles** [comment]
@patcon if you can remember 5 months back could you fill out this issue with the action required for this todo? :smile:

**Comment by patcon** [comment]
Thanks! This TODO is good to remove. Not important enough since there's talk of ditching react-select
