### ISSUE TITLE
Make mandatory once data model settles

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4644]
https://github.com/GCTC-NTGC/gc-digital-talent/blob/72bb26c0f0bff832ad8abd01abf540a08fc29d82/apps/web/src/pages/Users/IndexUserPage/components/UserTableFilterDialog/UserTableFilterDialog.tsx#L26

**Comment by mnigh** [comment]
Related https://github.com/GCTC-NTGC/gc-digital-talent/issues/4638

**Comment by mnigh** [comment]
@patcon is the TODO comment still relevant or can it be removed?

**Comment by patcon** [comment]
Superceded by https://github.com/GCTC-NTGC/gc-digital-talent/issues/4638
