### ISSUE TITLE
♻️ Remove `typeOfOpportunity` const

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4647]
## 💡 Solution
Remove **typeOfOpportunity**.

### non-deprecated file
https://github.com/GCTC-NTGC/gc-digital-talent/blob/72bb26c0f0bff832ad8abd01abf540a08fc29d82/apps/web/src/components/SearchRequestFilters/SearchRequestFilters.tsx#L490

https://github.com/GCTC-NTGC/gc-digital-talent/blob/72bb26c0f0bff832ad8abd01abf540a08fc29d82/apps/web/src/components/SearchRequestFilters/SearchRequestFilters.tsx#L515-L523

### deprecated file

https://github.com/GCTC-NTGC/gc-digital-talent/blob/72bb26c0f0bff832ad8abd01abf540a08fc29d82/apps/web/src/components/SearchRequestFilters/deprecated/SearchRequestFilters.tsx#L186

https://github.com/GCTC-NTGC/gc-digital-talent/blob/72bb26c0f0bff832ad8abd01abf540a08fc29d82/apps/web/src/components/SearchRequestFilters/deprecated/SearchRequestFilters.tsx#L210-L218

**Comment by mnigh** [comment]
The only references to **typeOfOpportunity** are not linked to anywhere in the API. Can typeOfOpportunity references be removed from the non-deprecated SearchRequestFilters.tsx file?

### non-deprecated file
https://github.com/GCTC-NTGC/gc-digital-talent/blob/371f673df101139f77228108d10c647027d18db0/frontend/common/src/components/SearchRequestFilters/SearchRequestFilters.tsx#L504

https://github.com/GCTC-NTGC/gc-digital-talent/blob/371f673df101139f77228108d10c647027d18db0/frontend/common/src/components/SearchRequestFilters/SearchRequestFilters.tsx#L541-L549

### deprecated file

https://github.com/GCTC-NTGC/gc-digital-talent/blob/371f673df101139f77228108d10c647027d18db0/frontend/common/src/components/SearchRequestFilters/deprecated/SearchRequestFilters.tsx#L199

https://github.com/GCTC-NTGC/gc-digital-talent/blob/371f673df101139f77228108d10c647027d18db0/frontend/common/src/components/SearchRequestFilters/deprecated/SearchRequestFilters.tsx#L223-L231

**Comment by tristan-orourke** [comment]
Delete typeOfOpportnity if its not being populated with anything
