### ISSUE TITLE
Refactor storage utils to not accept undefined store

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4648]
From TODO:
https://github.com/GCTC-NTGC/gc-digital-talent/blob/f3e89b80983de9b525f82c0c7e9f135044790af1/packages/storage/src/utils.ts#L8

Rewrite getFromStorage, setInStorage and removeFromStorage don't accept undefined Stores.

## Acceptance Criteria
- [ ] getFromStorage, setInStorage and removeFromStorage don't accept undefined Stores
- [ ] TODO comment is removed

**Comment by mnigh** [comment]
@GCTC-NTGC/developers not sure who the original comment is from, anyone know? if not, can this comment be removed?

**Comment by petertgiles** [comment]
Gitlens will do a git blame for you in vscode.  :smile: 
 Eric Sizer, 4 weeks ago via PR #5697

**Comment by esizer** [comment]
> Gitlens will do a git blame for you in vscode. 😄

lol this is inaccurate! I think @tristan-orourke originally made the comment but it is attributed to me since I moved the file in the common refactor 😆

**Comment by mnigh** [comment]
@tristan-orourke any thoughts on the TODO comment?

https://github.com/GCTC-NTGC/gc-digital-talent/blob/f3e89b80983de9b525f82c0c7e9f135044790af1/packages/storage/src/utils.ts#L8

**Comment by tristan-orourke** [comment]
Hmm. Taking another look at this...
I think the getFromStorage function is okay. If there's something wrong with the store, it makes sense to return defaultValue.
However, I don't like that setInStorage and removeFromStorage can just fail silently. I'd rewrite this so none of these functions accept undefined stores, and let the error be caught further up.
