### ISSUE TITLE
♻️ Remove `auth.cy.js` comments

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4649]
## Description

The following code should be removed:

https://github.com/GCTC-NTGC/gc-digital-talent/blob/ddddd21dd058e701b405453dc57f288dd4162359/apps/e2e/cypress/e2e/admin/auth.cy.js#L75-L77

## Acceptance Criteria
- [ ] `should fail if the state value is tampered with` skipped test no longer appears in codebase
- [ ] comment for skipped test no longer appears in codebase

**Comment by petertgiles** [comment]
@patcon Could you please help fill in the requirements for this test?  The team is having trouble estimating it without knowing more.

**Comment by mnigh** [comment]
@tristan-orourke can we remove these lines?

https://github.com/GCTC-NTGC/gc-digital-talent/blob/12ce25200da28f7c955a393c4b2536a8a7b8db92/apps/e2e/cypress/e2e/admin/auth.cy.js#L75-L78
