### ISSUE TITLE
Language information form - remove stray comment

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4651]
https://github.com/GCTC-NTGC/gc-digital-talent/blob/fca285a93efbfc7dba2fc47c841c09693af27c24/apps/web/src/pages/LanguageInfoPage/LanguageInformationForm.tsx#L40

Acceptance Criteria:
- [ ] Remove stray comment

**Comment by petertgiles** [comment]
@JamesHuf Could you please add any other acceptance critera you had in mind for "updating this"?  It was 9 months ago so good luck!  :laughing:

**Comment by JamesHuf** [comment]
I suspect this was probably an in-progress comment I should have removed. After a quick test it looks like the form does reset un-rendered values and I can't remember anything else I'd have intended here. I think this can probably be closed.

**Comment by petertgiles** [comment]
Thanks for the check!  I'll change this to a "remove stray comment" issue and maybe if we find a couple we can bundle them together.
