### ISSUE TITLE
Archive Dialog

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4655]
https://github.com/GCTC-NTGC/gc-digital-talent/blob/9968de2525e4614e54d5a66147279df65539f738/frontend/admin/src/js/components/pool/EditPool/ArchiveDialog.tsx#L63

**Comment by vd1992** [comment]
feel like that one is just a line to be deleted

**Comment by mnigh** [comment]
> feel like that one is just a line to be deleted

🤷

**Comment by petertgiles** [comment]
No, we actually do want to add a dialog to archive pool advertisements some day.  Since that will be a new feature request from designers, though, I'm not sure we need this issue to remember to do it.

**Comment by petertgiles** [comment]
Will wait for designer feature request.
