### ISSUE TITLE
Find a way to not need to omit ref

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4656]
https://github.com/GCTC-NTGC/gc-digital-talent/blob/9968de2525e4614e54d5a66147279df65539f738/frontend/common/src/components/Button/IconButton.tsx#L5

**Comment by petertgiles** [comment]
@substrae do you remember anything about this that could help us flesh out the issue?  Why did ref need to be omitted?  Why don't we want to omit it?  What's the strategy for not needed to omit it?
