### ISSUE TITLE
wouldAcceptTemporary is not being saved in ApplicantSearch Requests

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4659]
On the search page, if I set duration to "Term", the countApplicants query happens with `{wouldAcceptTemporary: true}`. (In other cases, wouldAcceptTemporary is null). However, when I go submit the request and check the request in the database, the associated ApplicantFilter has wouldAcceptTemporary equal to null - the correct value was not saved to the database.

**Comment by mnigh** [comment]
Are these the expected database values for each of the options for _Employment Duration_:
1. Any duration (short term, long term or indeterminate) (Recommended), **would_accept_temporary** = `false`
2. Term duration (short term, long term), **would_accept_temporary** = `true`
3. Indeterminate duration (permanent), **would_accept_temporary** = `false`

**Comment by mnigh** [comment]
I've found where `wouldAcceptTemporary` is missing but I want to clarify the logic within `create` before creating a PR.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/c6c7d59a8b8d0151f1bd1f65150687a1756c057f/frontend/talentsearch/src/js/components/request/CreateRequest.tsx#L37-L60

https://github.com/GCTC-NTGC/gc-digital-talent/blob/c6c7d59a8b8d0151f1bd1f65150687a1756c057f/frontend/talentsearch/src/js/components/request/CreateRequest.tsx#L104-L141
