### ISSUE TITLE
Create cypress tests for User table pages (with filter)

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#4666]
Re-ticketed from https://github.com/GCTC-NTGC/gc-digital-talent/pull/4623#issuecomment-1307456587

Both these pages will need coverage:

Talent request candidates list:  `http://localhost:8000/en/admin/talent-requests/:requestId` (might take some trying around to find one with actual users listed, and random filters often have no matches)
Users list: `http://localhost:8000/en/admin/users`

**Comment by petertgiles** [comment]
@patcon do you remember what functionality needed to be tested on these two pages?
