### ISSUE TITLE
`wouldAcceptTemporary` in ApplicantFilter is a boolean but acts like an enum

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4667]
## Description

wouldAcceptTemporary, and the way it works, is currently very confusing. It should be updated to be more intuitively understandable to the devs.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/9edc7906da0dd79abca399b5e6f89789b3f866ed/api/app/Models/ApplicantFilter.php#L18

https://github.com/GCTC-NTGC/gc-digital-talent/blob/9edc7906da0dd79abca399b5e6f89789b3f866ed/api/graphql/schema.graphql#L517

https://github.com/GCTC-NTGC/gc-digital-talent/blob/9edc7906da0dd79abca399b5e6f89789b3f866ed/frontend/talentsearch/src/js/components/search/SearchForm.tsx#L172-L173

Relevant slack discussion: https://talent-cloud.slack.com/archives/C0259G6KXJ6/p1667335340182079

### Proposal A:
Users specify a list of duration types they are interested in. Managers specify the list of duration types they can offer. Filtering works by simple intersection.
```graphql
enum PositionDuration {
  TEMPORARY
  PERMANENT
}
type User {
  ...
  positionDurations: PositionDuration[] # what durations am I interested in
}
type ApplicantFilter {
  ..
  positionDurations: PositionDuration[] # what durations the manager can offer
}
```
Pros: intuitive, flexible, expandable
Cons: Does not build in our domain expectation that every user should be interested in Permanent positions. This could be done at the UI level, if we want.

### Proposal B:
Enums should build in domain expectations about users always being open to Permanent positions (which is what wouldAcceptTemporary does, but very confusingly). To be properly explicit, we need different enums for Users and Filters, and some logic on the User model which maps them for filtering.
```graphql
enum PositionDurationInterest {
  TEMPORARY_OR_PERMANENT
  PERMANENT_ONLY
}
type User {
  ...
  positionDuration: PositionDurationInterest  # what durations am I interested in
}
enum PositionDuration {
  TEMPORARY
  PERMANENT
}
type ApplicantFilter {
  ..
  positionDuration: PositionDuration # what duration the manager can offer.
}
# Filter logic:
if (offeredDuration == TEMPORARY) {
  query->where(positionDuration, 'TEMPORARY_OR_PERMANENT')
}
# In all other cases (offering a permanent position, or not using this filter at all, we do not filter by positionDuration
```
Pros: builds our domain expecations into the data model
Cons: builds our (possibly falacious?) domain expectations into the data model

## Acceptance Criteria
- [ ] Deprecate the current "wouldAcceptTemporary" field without totally deleting or breaking it (good dev practice)
- [ ] Add new fields to schema, according to accepted proposal. Note, input definitions need to be updated as well.
- [ ] Data migration to create new column matching new fields. Should default to null (for future rows) but then also run an sql operation which initializes values for existing rows according to the wouldAcceptTemporary column.
- [ ] Add filters to PoolCandidate and User models
- [ ] phpunit tests for using those filters
- [ ] Ensure that the frontend always uses the new fields instead of wouldAcceptTemporary

**Comment by patcon** [comment]
Related: #4671

**Comment by vd1992** [comment]
having two similar enums, `PositionDurationInterest` and `PositionDuration` seems likely to cause some confusion down the line again as it might get mixed up which goes with which Type or keeping them in sync in all places

I like proposal A, it is easy to grasp

**Comment by tristan-orourke** [comment]
Great, sounds like more interest in proposal A.

**Comment by patcon** [comment]
+1 to proposal A, which leaves the domain expectations to be handled in the query layer, in case complex queries are desired later (perhaps for BI purposes)
