### ISSUE TITLE
Term duration (permanent) vs. Indeterminate duration (permanent)

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4671]
Seems odd to use "Term duration (permanent)" when the user selects "Indeterminate duration (permanent)" on the search form. Do you think we should create an issue to sync up terminology from `talentsearch` and `admin`?

_Originally posted by @esizer in https://github.com/GCTC-NTGC/gc-digital-talent/pull/4669#pullrequestreview-1174082561_

**Comment by mnigh** [comment]
@esizer is this issue still relevant?

**Comment by esizer** [comment]
> @esizer is this issue still relevant?

You know what, I'm not even sure. I went back and looked at my original comment and I can't even remember where the terms are being used. I should have linked to the line of code or added a screenshot... 😢

**Comment by petertgiles** [comment]
I can't find any discrepancies.
![image](https://user-images.githubusercontent.com/8978655/234674583-882222f3-bb2f-4771-8b75-d9d557dba8df.png)
![image](https://user-images.githubusercontent.com/8978655/234675627-a77dd6f8-9d53-4e5f-aa76-089946304053.png)
![image](https://user-images.githubusercontent.com/8978655/234675669-a17e804c-06a4-4dac-942d-8f0f0e49eff9.png)

**Comment by mnigh** [comment]
@esizer is it [closing time](https://www.youtube.com/watch?v=xGytDsqkQY8) for this issue then?

**Comment by esizer** [comment]
> @esizer is it [closing time](https://www.youtube.com/watch?v=xGytDsqkQY8) for this issue then?

Go for it! 👍

**Comment by mnigh** [comment]
Closing as can't reproduce.
