### ISSUE TITLE
List PoolCandidates instead of Users in SingleSearchPage requests

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4672]
After #4623, when an Admin views a single search request, they see a list of Users. They really want to see a list of PoolCandidates, because they're interested in status and priority.

1. build a poolCandidates query which accepts a ApplicantFilter (we're almost there already, actually)
2. build a PoolCandidatesTable which uses an ApplicantFilter instead of PoolCandidateFilter (maybe modify the existing table? I think we want to stop using PoolCandidateFilter at all?)
3. use the PoolCandidatesTable here instead of UserTable.

See these two comments:
- https://github.com/GCTC-NTGC/gc-digital-talent/pull/4623#issuecomment-1307662346
- https://github.com/GCTC-NTGC/gc-digital-talent/pull/4623#issuecomment-1307859883

## Acceptance Criteria
- [ ] SingleSearchRequest page shows a table which matches the table on the PoolCandidates page.
- [ ] The pool candidates shown should follow this logic:
    - find all applicants who meet the requirements of the ApplicantFilter
    - get all PoolCandidates for those users
    - if ApplicantFilter includes a poolId filter, filter the PoolCandidates by those pools
    - Note: These steps are conceptual. the filter algorithm probably shouldn't work exactly like that, but it should return the same results as if it did.
- [ ] Any changes/additions to the PoolCandidates model filtering functionality should be tested in phpunit

**Comment by Jerryescandon** [comment]
Oh I think I just made a ticket related to this:
https://github.com/GCTC-NTGC/gc-digital-talent/issues/4771

**Comment by vd1992** [comment]
issue related to the scope of this one here #4865 
ApplicantFilter doesn't deal in statuses, it filters by the set pair in one of the builders
Also, attempting to change the candidates table away from poolcandidatefilterinput may be messy

It is a little confusing to see the three filter inputs (Applicant, PoolCandidate, and User) and not know which lines up with what

**Comment by tristan-orourke** [comment]
- The primary purpose of *ApplicantFilter* is to save the filters associated with a Search Request.
- The *PoolCandidateFilter* was previously used to save Search Requests, but is now deprecated and replaced by ApplicantFilter. (We still may want to keep its table and definition around for now, so that CMO can look at old requests.)
- *UserFilterInput* is just an API interface that Admins can use to filter/search users. Since it is meant for Admins, it allows for searching on otherwise private fields, or for users which are not normally accessible. UserFilter objects are never saved to the database, but only used for one-time queries.

**Comment by vd1992** [comment]
> * The primary purpose of _ApplicantFilter_ is to save the filters associated with a Search Request.
> 
>     * The _PoolCandidateFilter_ was previously used to save Search Requests, but is now deprecated and replaced by ApplicantFilter. (We still may want to keep its table and definition around for now, so that CMO can look at old requests.)
> 
>     * _UserFilterInput_ is just an API interface that Admins can use to filter/search users. Since it is meant for Admins, it allows for searching on otherwise private fields, or for users which are not normally accessible. UserFilter objects are never saved to the database, but only used for one-time queries.

I see, thank-you, I feel maybe we should leverage `UserFilterInput` to replace `PoolCandidateFilter` on the Admin side instead of `ApplicantFilter`? 
All the extra filtering options would come in handy, like to filter by `pool_candidate_status`. 
Or there was I think something else you mentioned to get around issues with ApplicantFilter with optional fields was it? During the morning meet
