### ISSUE TITLE
Experience not displayed properly on printed 

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#4679]
## Where
- UAT server

## Description
The experience does not display properly when Printing a profile, Instead it shows a giant arrow.

## Screenshot
![image](https://user-images.githubusercontent.com/16977254/200915372-0fad4748-5aa1-4cba-9e62-c570396935cb.png)

## Acceptance Criteria
- [ ]  we need to be able to print the content of the profile experience

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by brindasasi** [comment]
Its not just printing .. the problem is about downloading the content. 
Lets bump up the estimate and try for the longer term solution.
