### ISSUE TITLE
Edit column is not needed on Request page

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#4681]
## Description
Since we moved to new profiles, we dont need access to EDIT profiles anymore in the candidate table of requests page.

## Screenshot: Prototype
![image](https://user-images.githubusercontent.com/16977254/200917896-4360aa80-3de8-4038-b882-6f01b282002b.png)

## Acceptance Criteria
- [ ] Column no longer appears in table

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by gobyrne** [comment]
Let's make sure #4672 fixes this
