### ISSUE TITLE
Formatted JobPoster title not used on several admin pages

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4684]
When viewing User details on the Admin side, we can see a table showing the pools the user is in:
![image.png](https://images.zenhubusercontent.com/5d9ded8fd25901000101f3f0/f06836c2-2285-4b88-8411-b67a00b94421)

The names of the pools here should be in the same format as described in #4574.

*Note:* the existing method of just showing a name will be a definitely problem after generating 36 pools with the same "Digital Careers" name but different classifications and streams.

(It would also be useful if the name of the pool was a link to the pools page, ie `/admin/pools/:poolId`)

Similarly, when viewing a pool info page at `/admin/pools/:poolId` the title at the top should use the full Job Poster Title format:
![image.png](https://images.zenhubusercontent.com/5d9ded8fd25901000101f3f0/e041a1ed-37c4-47a9-ab8f-5b27a0a8cc59)

**Comment by mnigh** [comment]
Estimate?
