### ISSUE TITLE
Remove link to remove users from pool

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#4688]
## Description
The code to make it work appears present, but the function on the users page isn't active
So, we either need to remove it from the page

## Screenshots
inactive elements

![image](https://user-images.githubusercontent.com/40485260/200945144-d600893f-9fea-4a82-b7b6-805067d87d4a.png)

usable code

![image](https://user-images.githubusercontent.com/40485260/200945248-9e0881a5-9dba-4ef6-b5fc-6dc4e0eda24d.png)

## Acceptance Criteria
- [ ] remove link from page
- [ ] remove unused click handler

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by petertgiles** [comment]
@Jerryescandon As we know, "deleting" entities can get very complicated.  Are you OK if the solution is to remove the "Remove from pool" link and allow admins to just change the status to something equivalent like inactive?

**Comment by Jerryescandon** [comment]
Yup I think that's exactly what we should do for now.

Policy wise, we need to keep records of what's going on for 5 years-ish, so until we have an elegant solution to do this type of archiving, we should just rely on the statuses to control who shows or doesn't show up in places.

**Comment by mnigh** [comment]
@petertgiles Duplicate of https://github.com/GCTC-NTGC/gc-digital-talent/issues/5129? I can't find the click handler from the screenshot anywhere in `main` branch (or in the past anywhere, for that matter).

**Comment by Jerryescandon** [comment]
I think definitely a duplicate

**Comment by vd1992** [comment]
duplicate
