### ISSUE TITLE
✨ Add commit data to source code of builds

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#4691]
## Description
@Jerryescandon brought up that it would be great to easily see what features are deployed on the website

We could make this easier by embedding the current commit into the deployed build artifact. I've seen this done by either putting the link very small in the footer, or embedding it into a source code comment (so it's not visible). We could also do it in the console log, though that would be a little more advanced for someone to check.

Related StackOverflow question: **[In Git, how can I write the current commit hash to a file in the same commit](https://stackoverflow.com/questions/3442874/in-git-how-can-i-write-the-current-commit-hash-to-a-file-in-the-same-commit)**

## Proposed Resolution

My **personal preference** would be storing the git hash very small and subtle as `Version: f38fc06` in the visible footer, for all environments, and link it to the github repo file tree at that specific commit. For example (linked to https://github.com/GCTC-NTGC/gc-digital-talent/tree/f38fc065cbe6b58ebe71613f4de025e2494640cc):

### Screenshot of Proposed Change
<img width="1403" alt="Screen Shot 2022-11-10 at 1 08 25 PM" src="https://user-images.githubusercontent.com/305339/201099841-b08094d4-4b0f-4797-bcb9-1d467d16c8cb.png">

## Acceptance Criteria

- [ ] should appear in the footer after the **Date modified** value
- [ ] link to GitHub (releases notes or [index of repo](https://github.com/GCTC-NTGC/gc-digital-talent/))
- [ ] include commit hash or tag (if tag exists) (`tag ? {tag} : {commitHash}`)
- [ ] for every vertical
- [ ] happens automatically ([webpack](https://stackoverflow.com/questions/38400314/including-git-commit-hash-and-date-in-webpack-build)?)

**Comment by patcon** [comment]
We could also **link directly to the commit logs from that commit backwards**, which might make it just a one-click operation for a designer to check out the recent commit history on the live website: https://github.com/GCTC-NTGC/gc-digital-talent/commits/f38fc065cbe6b58ebe71613f4de025e2494640cc

(One gets to that page from the previously-mentioned "file-tree link" by clicking "11,088 commits" link in the top-right corner of the file list:)
<img width="491" alt="Screen Shot 2022-11-10 at 1 16 58 PM" src="https://user-images.githubusercontent.com/305339/201101752-fce14f41-9b92-44cc-b822-d287c0c7e64a.png">

**Comment by petertgiles** [comment]
Team agreed we want to do this, need to agree on specific implementation.

**Comment by brindasasi** [comment]
I would think linking to release tag ( like v2.3.1 ) and that links to our release tag page which consists all our commit history on that release

**Comment by petertgiles** [comment]
I hope we could make it automatic.  If it's easy to forget to update and we accidentally show an old version then the feature is not very helpful.

**Comment by brindasasi** [comment]
thats what I'm thinking as well .. there are scripts to make generate the release tags auto based on file changes. May we extend that into add it in the home page as well?

**Comment by brindasasi** [comment]
blurry idea:  

- Release tag should be read from env var. for that link in the home page
- Env. variable is populated by the git tag that we either add in manually or by script
- A test to validate the link is actually matches with the current release tag 
Question:
Release tag is generated late in the game while deploying. How that will be shown during development?

**Comment by esizer** [comment]
> * Release tag is generated late in the game while deploying. How that will be shown during development?

@brindasasi Do we have git available during build? I had some luck with the following locally:

```js
  const version = require('child_process')
    .execSync('git describe --abbrev=0')
    .toString()
    .trim();
```

![Screenshot 2023-10-30 094755](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/ad3b89b2-ae48-446d-8f48-8f171cc91e04)

**Comment by brindasasi** [comment]
Oh ..This would be very helpful.  I believe it is available. We could test that out in dev env.

**Comment by brindasasi** [comment]
- Deployed this branch in dev and verified without tag and it shows the commit properly 
- Created an unannotated tag as usual and deployed this branch in dev. Still shows the commit sha.  
   This will enforce us to create annotated tags going forward. I guess that shouldn't be an issue. 
Suggestions :
1. When there is no tag present ( local & dev), the page displays the latest commit sha. But it points to the release page. 
 
![image (23)](https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/0e717260-4fe5-4b8e-b152-26cb4b836cc5)

Questions: 
1. Is there any issue linking the commit sha with our repo , to show the commit ?
2. Is there any benefit/concern doing that?
3.  Could we just leave it to empty if tags not present? Showing the tag on UAT & Prod has the real value IMO. 

@GCTC-NTGC/developers
