### ISSUE TITLE
IAP - Possible syntax issues, missing copy in some translations in ojw, crk, mic

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4693]
## Description
Possible syntax issues, missing copy in some of the translations from https://github.com/gctc-ntgc/gc-digital-talent/issues/4587.

### Missing a space (ojw)
![Screen Shot 2022-11-10 at 09 33 07](https://user-images.githubusercontent.com/3046459/201141888-b80bd248-7672-4a1a-9002-b0804a5c7fd4.png)

### Missing some copy after the comma (crk)
![Screen Shot 2022-11-09 at 16 59 02](https://user-images.githubusercontent.com/3046459/201141892-03535aa1-6a7b-49c4-a789-c3cdc22ad89f.png)

### Missing some copy after the comma (mic)
![Screen Shot 2022-11-09 at 16 47 11](https://user-images.githubusercontent.com/3046459/201141898-5a2d2a3e-a0aa-4370-964d-cdf64f894eb7.png)

### Based on emails via translation bureau.

- [x] **ojw**: add space after period
- [x] **crk**: replace comma with period
- [x] **mic**: replace string with: Na ula program eltasikip wjit klusa’sin wjit ila’matultinew aqq l’tmnew ta’n iliankaptasik wejiaq ta’n nemitasik rights aqq toq-lukuti’tijik wjir l’nu’k majuinu’k.

**Comment by mnigh** [comment]
@gobyrne was this issue closed by mistake?

**Comment by gobyrne** [comment]
@mnigh must have... I don't remember ever seeing it :/

**Comment by mnigh** [comment]
English and French strings for each translation to give more options for the translators.

## ojw
- [indigenousapprenticeship_en_for_ojw.txt](https://github.com/GCTC-NTGC/gc-digital-talent/files/10133601/indigenousapprenticeship_en_for_ojw.txt)
- [indigenousapprenticeship_fr_for_ojw.txt](https://github.com/GCTC-NTGC/gc-digital-talent/files/10133604/indigenousapprenticeship_fr_for_ojw.txt)

## crk
- [indigenousapprenticeship_en_for_crk.txt](https://github.com/GCTC-NTGC/gc-digital-talent/files/10133599/indigenousapprenticeship_en_for_crk.txt)
- [indigenousapprenticeship_fr_for_crk.txt](https://github.com/GCTC-NTGC/gc-digital-talent/files/10133602/indigenousapprenticeship_fr_for_crk.txt)

## mic
- [indigenousapprenticeship_en_for_mic.txt](https://github.com/GCTC-NTGC/gc-digital-talent/files/10133600/indigenousapprenticeship_en_for_mic.txt)
- [indigenousapprenticeship_fr_for_mic.txt](https://github.com/GCTC-NTGC/gc-digital-talent/files/10133603/indigenousapprenticeship_fr_for_mic.txt)

**Comment by mnigh** [comment]
Added to branch [feature/4587-i18n-iap](https://github.com/GCTC-NTGC/gc-digital-talent/tree/feature/4587-i18n-iap) and will be resolved as part of https://github.com/GCTC-NTGC/gc-digital-talent/pull/4617:

- [Add space after period](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4617/commits/002321e81470be621c8e6066e1d3bc09be44543e)
- [Replace comma with period](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4617/commits/b60d363c565eed69af37c8ebea06b0ad9a0213fe)
- [Update mic How it works, step 1 content paragraph 1](https://github.com/GCTC-NTGC/gc-digital-talent/pull/4617/commits/ac720f4eabdd0d3f98407e9f30651382276a7997)
