### ISSUE TITLE
Add routing support on web server

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4697]
Make sure our web server can accept other language prefixes other than en and fr and still get to the  SPA index.html.

**Comment by gobyrne** [comment]
It's more complicated than that. Yes we need to be able to link to the page in the indigenous languages... but we also need to know if the header/footer is English or French (this also determines language when you navigate away from homepage.

Can we handle this with a post-type URL thingy? &lang=

**Comment by petertgiles** [comment]
Yeah, it's tricky because we have back-end routing on the web server and front-end routing that happens in the user's browser.  The purpose of this issue is just to make sure that if a user types in `talent.canada.ca/ojb/browse/opportunities` that our webserver serves up `frontend/talentsearch/dist/index.html`.  From that point on it's up to the React app to figure out how to handle it (and out of scope to this issue).

**Comment by petertgiles** [comment]
Unlikely to happen any time soon. Closing for now.
