### ISSUE TITLE
Add an updated language picker

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4699]
Add an updated language picker (needs design for simultaneous primary, secondary choice)

# :heavy_check_mark: Acceptance Criteria
- [ ] Picker added to header (or wherever design says it should be)
- [ ] Picker operates the updated language provider

**Comment by mnigh** [comment]
@petertgiles was this to change the main header's language toggle? are we planning to translate the entire site into more than English and French? 

## Screenshot
![Screen Shot 2023-04-28 at 14 04 25](https://user-images.githubusercontent.com/3046459/235221226-ee1e71d8-4e6d-4c06-a6bb-a6a9f880d114.png)

**Comment by petertgiles** [comment]
> @petertgiles was this to change the main header's language toggle? are we planning to translate the entire site into more than English and French?

Yeah, that was the idea behind this "phase 2" epic.

**Comment by petertgiles** [comment]
Unlikely to happen any time soon. Closing for now.
