### ISSUE TITLE
Tooling for Indigenous languages

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4700]
This issue is to update our tooling to support Indigenous languages

# :question: Questions
- Will our existing extract-merge-compile process work for other languages?
- How does the whitelist work with more than two languages?
- Support for primary and fallback languages might be solved with updated tooling https://github.com/formatjs/formatjs/issues/1089 or just merge at runtime like Eric's phase 1 nested provider.

# :heavy_check_mark: Acceptance Criteria
- [ ] Tooling works with Indigenous languages
  - [ ] Extract
  - [ ] Check
  - [ ] Merge
  - [ ] Compile
  - [ ] Whitelist
- [ ] Documentation updated

**Comment by mnigh** [comment]
@petertgiles do we have a path forward for this or should this be converted to a discussion?

**Comment by petertgiles** [comment]
Honestly, I'm not seeing a way forward on this entire epic.  We don't seem to have the external support needed to make any of this happen.  Let's revisit this once we have phase 1 done.

**Comment by petertgiles** [comment]
Unlikely to happen any time soon. Closing for now.
