### ISSUE TITLE
Honesty pledge (fancy page with carousel)

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#4703]
Part of MLP Epic #4704 

## Description
Honesty pledge (fancy page with carousel)

## Design Acceptance Criteria
- [ ] Passed Usability Test
- [ ] Passed Accessibility Test
- [ ] Product Owner Final Approval

**Comment by gobyrne** [comment]
This is no longer in the forward plan. Closing
