### ISSUE TITLE
Honesty pledge (boring in DEI section)

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#4705]
Part of MLP Epic #4704
 
## Description
Honesty pledge (boring in DEI section)

## Acceptance Criteria
- [ ] ...

**Comment by petertgiles** [comment]
Duplicate of #5316 ?

**Comment by Jerryescandon** [comment]
Yeah, basically that work is global and should affect the entire platform not just IAP, all Indigenous self id options should be available to all users.

**Comment by petertgiles** [comment]
Closing as duplicate.  Reopen if something is unique to this issue.
