### ISSUE TITLE
Indigenous languages in the about me section of profile

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#4706]
Part of MLP Epic #4704 

## Description
Indigenous languages in the about me section of profile

## Design Acceptance Criteria
- [ ] Passed Usability Test
- [ ] Passed Accessibility Test
- [ ] Product Owner Final Approval

**Comment by gobyrne** [comment]
This is still relevant, but we don't need to track it in the dev backlog. Moving to insight tracker and closing.
