### ISSUE TITLE
Remove experience and skills from IAP application process

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#4709]
Part of MLP Epic #4704 

## Description
Take out experience and skills for IAP (to be considered) Re-introduce experience and skills (with reduced list of skills)

## Design Acceptance Criteria
- [ ] Passed Usability Test
- [ ] Passed Accessibility Test
- [ ] Product Owner Final Approval

**Comment by MCommonda** [comment]
We're going ahead with Passion as the only required skill.
