### ISSUE TITLE
Review copy for Experiences

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#4711]
Part of MLP Epic #4704 

## Description
Review copy for all types of experiences needs Lauren's eyes and IAP input (Build once for both IAP and DCM)

## Design Acceptance Criteria
- [ ] Passed Usability Test
- [ ] Passed Accessibility Test
- [ ] Product Owner Final Approval

**Comment by gobyrne** [comment]
This was already rebuilt. Closing
