### ISSUE TITLE
Compression on "Browse jobs" header image

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#4712]
# 🌩️ Summary
Right now the image being loaded into the header is exported at well over 5000px wide, which is resulting in a file size of 12.8MB 🤯
# ✅ Required changes
- [x] Export the image at no more than 800px wide with JPG compression
- [x] Swap it out in the codebase
# 💾 Related files

![AdobeStock_286321074_downsize](https://user-images.githubusercontent.com/100953238/201197770-e052aec4-5224-4a11-8f14-264d552e8793.jpg)

**Comment by BrookeCameron** [comment]
@substrae Image has been downsized

**Comment by substrae** [comment]
Jeez @patcon beat me to it 😂
