### ISSUE TITLE
Signed-out user redirects should go through login info page

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#4713]
## Description
When a user is not logged in and it is trying to reach the Profile page, it immediately  send them to the GC Key site.

We should consider going through the [login info page](https://talent.canada.ca/en/login-info) to give the user a little bit of context as to why we are sending them to GC key site.

For example when an unlogged user clicks this button

![image](https://user-images.githubusercontent.com/16977254/201197562-84e15d3d-1e69-4a66-9089-679424ab0512.png)

Related to #5377

## Acceptance Criteria
- [ ] When not logged in, clicking a link to a protected page should navigate to login-info and then to the target page
- [ ] When logged in, clicking a link to a protected page should navigate directly to that page

**Comment by petertgiles** [comment]
Fixed by #5607
