### ISSUE TITLE
Search page filters data needs to be preserved when going back from summary of filters page 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#4716]
### Problem
When clicking back from search request summary page , search page refreshed and lost all of the selected filters 
We need to cache the filters data on the search page  so that user can come back and make any changes to it 

![Screen Shot 2022-11-10 at 3.23.40 PM.png](https://images.zenhubusercontent.com/61a7bd49e20af80694dd845e/ebd402cd-575b-4bd6-80a3-2d527f50d2fb)

### Acceptance Criteria
- [ ] Navigating to search for the first time brings up default search filters
- [ ] Navigating back to search from a request page restores the previous search filters
- [ ] Navigating to search after successfully submitting a request gives default filters
- [ ] Should searching, not submitting, going somewhere else, should preserve filters if possible

### Recommended Implementation
- URL params

**Comment by esizer** [comment]
## ❓ Question

Would we prefer to store this in `window.localStorage` or `URLSearchParams`? I like the idea of storing it in the url so it can be shared to pre-populate the search form wth some default values.

**Comment by petertgiles** [comment]
Designer Convo:

Peter:
- Should navigating to search after successfully submitting a request give you the default filters or the just-submitted filters?
- Should searching, not submitting, going somewhere else, then returning to search restore the previous search filters?
Josh:
I think reset filters would be the expectation
Basically - if you've deliberately navigated away from the task, resetting filters shouldn't be a shock
But if you've navigated away by accident or want to edit a submission before sending it, then retaining them would be expected

I've updated AC

**Comment by brindasasi** [comment]
[Open Requirement in TestQuality](https://web.testquality.com/site/brinda.sasikumar/project/15300?requirementId=15221)

**Comment by brindasasi** [comment]
About this A/C 
>  Should searching, not submitting, going somewhere else, then returning to search gives default filters

currently if you navigate away from this page deliberately and come back using browser back button retains the filter data. Are we ok to keep that?  @Jerryescandon
