### ISSUE TITLE
User testing plan for the MLP (Minimal Loveable Product)

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/gc-digital-talent#4720]
Develop approach and plan for testing the MLP with applicant, manager and DCM users.

**Comment by RM-1978** [comment]
@gobyrne Please find our draft plan attached for your information. Please don't

[GC Talent User Testing Plan - Fall 2022_Winter 2023.docx](https://github.com/GCTC-NTGC/gc-digital-talent/files/9986160/GC.Talent.User.Testing.Plan.-.Fall.2022_Winter.2023.docx)

 hesitate to reach out with any questions or revisions.

**Comment by MaddyDaigle** [comment]
Assigned myself to this ticket so I can continue with co-design watch it as well. :)

**Comment by RM-1978** [comment]
Maddy, we will need to keep moving on the planning of the Moderated testing and setting it up in simple survey in the meant time so that when Gray approves we are ready to make any adjustments and hit go :)

**Comment by MaddyDaigle** [comment]
Yep! I’ll be setting up simple survey with our questions first thing when I’m in tomorrow.  It’ll be easy to change as we get feedback from @gobyrne. :)

**Comment by RM-1978** [comment]
Hey team! So here is the latest version of the testing plan with the updates from our meetings with @gobyrne and Kelly McGillis. 

Gray, if you are okay with this plan, (please note that we are recommending 8 tests in December to  do a user walkthrough with Lauren during our planned user time with her), we will prepare and submit our requests to Fable. 

[GC.Talent.User.Testing.Plan.-.Fall.2022_Winter.2023 _V2.docx](https://github.com/GCTC-NTGC/gc-digital-talent/files/10058328/GC.Talent.User.Testing.Plan.-.Fall.2022_Winter.2023._V2.docx)
