### ISSUE TITLE
Add turborepo for cached builds

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#4724]
## 👋 Introduction

This is a proposal to add [turborepo](https://turbo.build/repo) to our repo as the build system. This will allow us to cache our builds speeding them up, as well as neat stuff like [only building projects that have changes](https://turbo.build/repo/docs/core-concepts/monorepos/filtering#filter-by-changed-workspaces).

## ⚙️ Setup

The setup is super simple, we can just:

1.  Move our `package.json` to the root and update the workspaces to point to `frontend/*`.
2. Install turbo `npm i turbo`
3. Create minimal `turbo.json` and incrementally adopt it as needed

### Minimal `turbo.json`

```json
{
  "pipeline": {
    "production": {
      "dependsOn": ["^production"],
      "outputs": [
        "./frontend/**/dist/**"
      ]
    }
  }
}

```

## 🧪 Tests

These tests were done running the `npm run production --workspaces` command.

### Before

```sh
# First Run (total 58.171s)
webpack 5.74.0 compiled with 2 warnings in 22734 ms
webpack 5.74.0 compiled with 3 warnings in 10930 ms
webpack 5.74.0 compiled with 2 warnings in 24507 ms

# Second Run - No changes (total 60.769s)
webpack 5.74.0 compiled with 2 warnings in 24151 ms
webpack 5.74.0 compiled with 3 warnings in 11157 ms
webpack 5.74.0 compiled with 2 warnings in 25461 ms

# Third Run - One changes (total 62.601s)
webpack 5.74.0 compiled with 2 warnings in 24552 ms
webpack 5.74.0 compiled with 3 warnings in 11844 ms
webpack 5.74.0 compiled with 2 warnings in 26205 ms
```

### After

Run with turborepo `npx turbo production`

```sh
# First Run - 
Tasks:    3 successful, 3 total
Cached:    0 cached, 3 total
Time:    33.687s 

# Second Run - no changes
Tasks:    3 successful, 3 total
Cached:    3 cached, 3 total
Time:    146ms >>> FULL TURBO

# Third Run - one change
Tasks:    3 successful, 3 total
Cached:    2 cached, 3 total
Time:    26.328s 
```

## Results

Without turborepo, we see that the number rarely shifts off a total build time ~60 seconds. With turborepo and no cache, we already get that down to 33 seconds. If we have a cache, it drops 26 seconds.

**Comment by petertgiles** [comment]
This is being done as part of the workspace combining project.
