### ISSUE TITLE
Review image asset practices

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#4738]
Re-ticketed from https://github.com/GCTC-NTGC/gc-digital-talent/pull/4717#issuecomment-1310890486

## Potential Candidates

(I personally think these could be separate small PRs, if we discuss and realize its worth doing)

- [ ] convert photographic images to jpgs -- @esizer 
  - ref: https://github.com/GCTC-NTGC/gc-digital-talent/issues/4570#issuecomment-1309200192
- [ ] allow webpack to process images (using imports instead of "public" dir) -- @patcon 

cc @esizer

**Comment by petertgiles** [comment]
First point split out to #5355
I've stubbed the second point to #5356
