### ISSUE TITLE
Broken link for IAP on homepage

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#4739]
The link to the Apprenticeship program page is broken on the homepage.

The link has /en/en in it.

![IMG_6165.jpg](https://images.zenhubusercontent.com/5dc084854553760001149b53/04dc3058-34ef-4b9e-b288-cada9d723470)

**Comment by patcon** [comment]
💡 let's create a workflow to check for broken links. will likely need something different for internal (react) vs external. For static sites, a past org used https://github.com/gjtorikian/html-proofer , but maybe that won't work for react
