### ISSUE TITLE
Validate that all links work

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#4741]
Re-ticketed from https://github.com/GCTC-NTGC/gc-digital-talent/issues/4739#issuecomment-1313930927

We noticed that one internal link was broken. We don't currently check any links, though broken links reflect very poorly, and are one of the most common checks that can be automated (all sites need this #3791 

This likely involves a couple different approaches, which are likely separate atomic PRs:
- check **internal links**, within router. new options for this might open when we complete the react-router migration (#3017)
- check **external links**. there are tools to do this on static, non-authenticated websites, but they may not work easily on a website requiring login. https://github.com/gjtorikian/html-proofer
  - we could use cypress tests for this, though that might be more maintenance

## Candidate To Dos
- [ ] research approaches to validate internal react links
- [ ] research approaches to validate external links for websites with auth

**Comment by patcon** [comment]
Tristan suggested I take my name off of this if I'm not able to find time to move it forward. Maybe this will be the psychological hack that lets me reset :grimace:

**Comment by esizer** [comment]
Put a solution up in #5044 but tbh, it kinda sucks. Going to set this aside for someone else to take a look at it.

**Comment by patcon** [comment]
Failed suggestion from DM with eric:

> I wonder about using cypress to login in, and then use cy.task to run a script that gets passed the token to run curl with. Then it can just kinda dump each page, and run another tool on each page...?
> https://github.com/stevenvachon/broken-link-checker

Next suggestion (less stupid): https://talent-cloud.slack.com/archives/CB424V61J/p1670515833127429?thread_ts=1670515204.975969&cid=CB424V61J

> sorry, my first thought was really stupid, but a comparable thing could be done by dumping the rendered html from cypress for each page, and then passing the dumped DOM to curl or some CLI tool to parse like a standard static html page
>
> will add that to the issue (i am new to cy.task, but my impression is that it's for running any arbitary command mid-test)

**Comment by patcon** [comment]
```
cy.get('html:root').eq(0).invoke('prop', 'outerHTML').then(html => {
  cy.task('checkLinks', { html })
});
```

And we can write `checkLinks` to dump the file to a tmp path and run curl on it with specific settings to report broken links, and fail/return if any found :)

**Comment by gobyrne** [comment]
Eric tried this. Insight is: it's not best to do this through Cypress because it's slow

**Comment by mnigh** [comment]
@GCTC-NTGC/developers is there any path forward for this issue?
