### ISSUE TITLE
Update API so that all instances of Pool.name show fully formatted title

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4744]
# Description
There are many places in the app which currently show only the Pool "name", when we now want to show the fully formatted title: ` [Specific title] + " ( " + [Classification] + [Stream/Job title] + " ) "`. We've created several tickets to deal with this on the frondend (#4574 and #4689) but we keep finding more places that need to be changed. A more maintainable solution is to change the backend so that the api can return Specific Title and Full Title, and avoid computing it every time on the frontend.

**Comment by mnigh** [comment]
@tristan-orourke is this issue still relevant?

**Comment by tristan-orourke** [comment]
I don't think so, especially since the IAP at least does NOT want to show the fully-formatted title.
