### ISSUE TITLE
🏈 Can we test a visual diff of printouts?

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4753]
## Intro

We want to leverage Chromatic to detect issues in the profile printout functionality.  We have a high degree of uncertainty if this is possible or how to do it.

Possible approach: work with Chromatic on this, maybe use chatbot

## Spike Question
- [ ] Can Chromatic diff a printed component?

Spike-ish time box: 1 day

**Comment by patcon** [comment]
one option is to use chromatic diffs. but since print styles don't include hydrogen (?) we'd need to get some stories in storybook to not load hydrogen CSS. Right now, this is done in global config in preview.js files like https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/talentsearch/.storybook/preview.js

**Comment by mnigh** [comment]
For reference: https://www.chromatic.com/docs/media-features/#test-print-styles

**Comment by mnigh** [comment]
@GCTC-NTGC/developers

Question: Can Chromatic diff a printed component?
Answer: No.

Chromatic does not render the print dialog and therefore, there isn't a way to produce a snapshot of the print dialog. We could create a storybook story of the PrintDocument component, though there is little style change and a jest test would be more appropriate if we wanted to make assertions on the shape of the information being rendered (for example `compareDocumentPosition` (https://developer.mozilla.org/en-US/docs/Web/API/Node/compareDocumentPosition): https://github.com/GCTC-NTGC/gc-digital-talent/pull/8767/commits/ddcda0aae6e3a6f92090b30a0242b7b47551461a).

**Comment by petertgiles** [comment]
I like the idea of a story for the PrintDocument component.  Even if it doesn't look exactly like the final printed document it would still let us know when there are unexpected changes.

**Comment by tristan-orourke** [comment]
Lets do the PrintDocument component story!

**Comment by mnigh** [comment]
> Lets do the PrintDocument component story! Include at least two users, and test multiple views: anonymous/not-anonymous, profile/application.

Issue created: #9413
