### ISSUE TITLE
Add language validation to application (Interim)

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#4760]
## User Story

As a DCM pool manager, I want to specify the language requirement that will be enforced on job posters, so I don't have to filter through a bunch of applications for people who don't meet that requirement.

As an Applicant, I want to clearly see what the language requirement is while applying (in case I missed it on the Job Advertisement), so I don't waste my time applying to something I'm not qualified for.

## Description

Include a language validation to the application process based on the specified language requirement.

This is an interim solution, we will ONLY focus on adding this for the "Bilingual" requirement selections.

## To-do

If a pool advertisement has selected either "Bilingual Intermediate" OR "Bilingual Advanced" on the advertisement. 

Then, include validation and messaging on the application process.

### Language selection on Pool Application

![image](https://user-images.githubusercontent.com/16977254/202008074-c2525cab-b82d-4eff-9449-c94c0c6638bc.png)

### Wireframe for profile section

![image](https://user-images.githubusercontent.com/16977254/202014409-a140fd6c-b697-497a-b5c4-8c1fd3a85ad8.png)

### Wireframe for language section 

![image](https://user-images.githubusercontent.com/16977254/202014578-5ec1ff58-d360-4aab-8997-35e80d3eae0c.png)

### Profile-Application
(This was last minute, so I'm just adding this here in case @gobyrne wants to update the language )
(Deepl baby!)

ENGLISH: 
```
There is a missing language requirement
For this application process, you need the following language requirement
```

FRENCH: 
```
Il y a une exigence linguistique manquante
Pour cette procédure de candidature, vous devez remplir les conditions linguistiques suivantes :
```

### Language section

ENGLISH:
```
There is a missing language requirement
If you meet this criteria, please add the following application requirements to your profile:
```

FRENCH:
```
Il y a une exigence linguistique manquante
Si vous répondez à ces critères, veuillez ajouter les conditions de candidature suivantes à votre profil :
```

## Acceptance Criteria
- [ ] The API will prevent the creation of the application if the language requirements are not met.
- [ ] The frontend will prevent the creation of the application (and properly communicate) if the language requirements are not met.

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by petertgiles** [comment]
@Jerryescandon just to confirm, the validation should ensure you have checked "Bilingual positions (English and French)" only, right?  It shouldn't care if you've completed an evaluation or are at a certain level?
![image](https://user-images.githubusercontent.com/8978655/215795375-fa5dbba2-82f2-4485-9d49-78be2cd5c307.png)

**Comment by Jerryescandon** [comment]
Correct (For now) since we dont have a way to specify levels on the poster. Should that change in the future, we will tackle it then.
