### ISSUE TITLE
View Advertisement sends to blank page

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#4762]
## Description

When clicking on the "View Advertisement" button on the pool dashboard page for a DRAFT pool, it send you to a blank page

It should send you to a preview of the poster for this pool.

![image](https://user-images.githubusercontent.com/16977254/202024552-279d5515-5738-4060-bbb2-13d7aef98cdf.png)

## Acceptance Criteria
- [ ] ...

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by vd1992** [comment]
ah, it is crashing due to not having handling for null values
- need to refactor things to allow for null cases for everything except classification (which will never be null)

![image](https://user-images.githubusercontent.com/40485260/202279753-89fbd854-8dbb-4b25-aa1b-16d8c2babd6c.png)
