### ISSUE TITLE
Copy is wrong - Term & Permanent

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#4772]
## Description
The requests summary shows "Term duration (permanent)" which is impossible, so this should be either term or indeterminate (permanent).

### Screenshots

This is the one that is wrong:
![image](https://user-images.githubusercontent.com/16977254/202223653-6875c7d3-6a28-4799-9679-7276a4cc7a84.png)

These are the actual possible options:
![image](https://user-images.githubusercontent.com/16977254/202223972-9acd155c-aa89-40dc-98ac-e67720de2635.png)

## Acceptance Criteria
- [ ] ...

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by mnigh** [comment]
@Jerryescandon and I chatted about this issue and I'm not sure how to proceed before these issues are resolved first:

- https://github.com/GCTC-NTGC/gc-digital-talent/issues/4667
- https://github.com/GCTC-NTGC/gc-digital-talent/issues/4671

Currently, if we change the text for 3, it will also change the text for 1:

1. Any duration (short term, long term or indeterminate) (Recommended)
Term duration (permanent)

2. Term duration (short term, long term)
Term duration (short term, long term, or indeterminate duration)

3. Indeterminate duration (permanent)
Term duration (permanent)

The same logic is used for both viewing a request on `/admin/talent-requests/{request-id}` and the summary of filters on `/search/request`

https://github.com/GCTC-NTGC/gc-digital-talent/blob/310c0dc1d3637f2683b8fd6a701f67cd6b9df6ce/frontend/common/src/components/SearchRequestFilters/SearchRequestFilters.tsx#L157-L167
