### ISSUE TITLE
Sorting table by date sorts alphabetically instead of by time

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4774]
The All Requests and Latest Requests tables include a Date Reveived column. When sorting by the column, it sorts the rows alphabetically based on the display string (eg August, November, October, September) instead of based on the underlying string.

## Acceptance Criteria
- [ ] Requests tables sort rows by date (not date string) after clicking the Date Received column.

**Comment by vd1992** [comment]
the default sort for both is chronological, latest first, so one click on it should do nothing while two clicks flips it 🤔 

![image](https://user-images.githubusercontent.com/40485260/202256680-d4c2ce00-73c0-4ad6-8a9e-b93c6f77d2c1.png)

**Comment by tristan-orourke** [comment]
Can be fixed by separating a date value into Accessor and Cell
