### ISSUE TITLE
Build carousel component in storybook

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#4778]
### Screenshot

![Screen Shot 2022-11-17 at 11 11 11 AM](https://user-images.githubusercontent.com/89482910/202498635-036fd56a-a07f-4f1b-88af-a9a9e78b93bc.png)
2834aa78c1.png)

### Mockup 
https://www.figma.com/file/IThJdlxAJqQPJyvX88hAG7/IAP-Honesty-Pledge-V6?node-id=4232%3A5766&t=VYWHaO7976M14OUo-0

### Acceptance Criteria

1.  Carousel Component that can have 3 mono colour images per card.  Center Image should be bigger as per the mock up. 
2.  Each image is link for different actions 
     -   clicking on image 1 is the same as clicking on previous arrow ( chevron ) 
     -  clicking on image 2 will switch it with coloured image and make it selected 
   -  clicking on image 3 is the same as clicking on next arrow   
3. User can select multiple communities. Hence he should be able to navigate away from the picture he selected and click another one. In this case, the selected picture stay coloured in the UI but blurred. The selected value should be preserved. 
![Screen Shot 2022-11-17 at 11 02 47 AM](https://user-images.githubusercontent.com/89482910/202496512-74f33448-fa82-4698-a4e7-226628cfbe1e.png)

    
5. This component should have preserve the value that has been selected. So it can be integrated to other component.
6. Same side swipe for mobile as well

**Comment by mnigh** [comment]
@brindasasi are we still planning to use a carousel component?

**Comment by brindasasi** [comment]
Closing this as not planned
