### ISSUE TITLE
Build self declaration form in storybook (Carousel Version)

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#4779]
### Screenshot 
![Screen Shot 2022-11-17 at 10 15 28 AM](https://user-images.githubusercontent.com/89482910/202484949-0e09b9d2-dae3-4cf8-a389-6404a9b35f04.png)

### Acceptance Criteria 

1.  Integrate the carousel component that has been created in #4778
2.  Indigenous peoples self declaration form content should be added as per the screenshot
3.  Self declaration Radio button group should be added as required field with below values 

       -   “I affirm that I am First Nations (Status or Non-Status), Inuk (Inuit), and or a Métis person”
       -  “I am not a member of an Indigenous group, and I would like to see other opportunities available to me”
4.  When clicking on "I affirm ..." the carousel component and the boxed section underneath should be displayed
5. When clicking on "I am not ..."  it should be displayed like below 

![Screen Shot 2022-11-17 at 10 26 01 AM](https://user-images.githubusercontent.com/89482910/202487372-98532093-eb14-4959-8ddf-74a8cd764c18.png)

6. When selecting an image for Indigenous group  there should be signature component displayed as below 
![Screen Shot 2022-11-17 at 10 28 30 AM](https://user-images.githubusercontent.com/89482910/202488062-17e401b3-1184-4acb-9dc2-e2062b3c2299.png)

7.  When selecting `“I am indigenous and I don’t see my community here.”` below component should be displayed 
![Screen Shot 2022-11-17 at 10 31 06 AM](https://user-images.githubusercontent.com/89482910/202488514-3c2c7456-50df-48ea-993f-465d2853f516.png)

**Comment by mnigh** [comment]
Since https://github.com/GCTC-NTGC/gc-digital-talent/issues/4778 was closed as not planned, so should this issue.
