### ISSUE TITLE
Admin - Add header above dashboard content

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#478]
### Notes

- [Figma design](https://www.figma.com/proto/jOGqmmyq7mr3oVdiimiuPW/Admin-Interface---V1.0?node-id=278%3A0&starting-point-node-id=1%3A2).

**Comment by tristan-orourke** [comment]
For the language language "toggle". In the past we've included the language in the url, and the toggle has simply been a link (with a full page refresh) to the other url. Do we have any reason to do it differently this time, or do we like the same approach?

Personally, I still like that approach, open to discussion.

**Comment by mnigh** [comment]
> In the past we've included the language in the url, and the toggle has simply been a link (with a full page refresh) to the other url.

Does that mean the url structure will need to changed so that it's something like `/admin/en/users` or `/admin/fr/users` and if so, what is the exact structure?
