### ISSUE TITLE
Missing localizable manifests

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4780]
## Description
Missing localizable manifest files. One approach: https://www.w3.org/TR/localizable-manifests/#unitary

## Acceptance Criteria
- [ ] add French translations for any English strings

**Comment by tristan-orourke** [comment]
Do we even need a manifest file? What is it for?

[This](https://developer.mozilla.org/en-US/docs/Web/Manifest) suggest manifest files are mostly for Progressive Web Apps, which we are not.

**Comment by mnigh** [comment]
> Do we even need a manifest file? What is it for?
> 
> [This](https://developer.mozilla.org/en-US/docs/Web/Manifest) suggest manifest files are mostly for Progressive Web Apps, which we are not.

Whether are app checks the boxes of a PWA or not, like any website, it can still be added to a home screen and not having manifest versions for other languages (in our case, French) means it doesn't render a French title of the site.

## Screenshot
![addtohome_ios](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/a442e6c4-7c9d-40aa-91f7-c4db3bd04517)
