### ISSUE TITLE
Manifest file does not contain a name or short_name value in admin

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4781]
## Description
Manifest file does not contain a `name` or `short_name` value in admin:

https://github.com/GCTC-NTGC/gc-digital-talent/blob/e33baa6f5f82dcb459f7f3775f10b252a97afeb4/apps/web/public/admin.webmanifest#L1

## Acceptance Criteria
- [ ] add values for `name` or `short_name`

**Comment by petertgiles** [comment]
Might just be verification after the migration.

**Comment by mnigh** [comment]
**iap** has been resolved but **admin** still bas missing values.

## iap
![Screen Shot 2023-03-07 at 12 33 41](https://user-images.githubusercontent.com/3046459/223503441-e0868c23-8f03-423b-8568-795e00a0ac11.png)

## admin
https://github.com/GCTC-NTGC/gc-digital-talent/blob/e33baa6f5f82dcb459f7f3775f10b252a97afeb4/apps/web/public/admin.webmanifest#L1
