### ISSUE TITLE
Breadcrumb link doesnt work

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#4782]
## Description

HOME link on the breadcrumbs in the Browse page is not working

![image](https://user-images.githubusercontent.com/16977254/202279613-2ad584e7-3624-48fa-95a7-361ada9892dd.png)

## Acceptance Criteria
- [ ] ...

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by vd1992** [comment]
interesting...
appears to be only effecting English-side? I don't see the bug happening locally either

https://recordit.co/TUTKRrQaMT

maybe something else to be scooped up by the everything PR? (#4597)

**Comment by vd1992** [comment]
oh, now I see why I couldn't replicate this issue, only overlaps in null state
