### ISSUE TITLE
Fix card header typo on PoolAdvertisementPage

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#4788]
Re-ticketed from Dasha's [comment in Slack](https://app.slack.com/client/T5ZFRSQ3V/C5Z1KMX5F/thread/C5Z1KMX5F-1668634601.470309): 🔒 

> Good morning :slightly_smiling_face: I know it's early lol sorry about that. DCMO caught this... I believe it should say "education" or "degree"... because underneath it refers to education. Thanks for your help :pray:

On http://localhost:8000/browse/pools/:poolId PoolAdvertisementPage

![Web capture_17-11-2022_956_uat-talentcloud tbs-sct gc ca](https://user-images.githubusercontent.com/305339/202477456-15484f01-8fa4-43b2-8ba0-8819f7cf6623.jpeg)

## Acceptance Criteria
- [ ] Change "2-Year Post-secondary Experience" to "2-Year Post-secondary Education" ([source](https://github.com/GCTC-NTGC/gc-digital-talent/issues/4862#issue-1458636553))

**Comment by mnigh** [comment]
## English
https://github.com/GCTC-NTGC/gc-digital-talent/blob/7cb60975da5742eeaae629d76471d92e9a7e46cf/frontend/talentsearch/src/js/components/pool/PoolAdvertisementPage.tsx#L624-L629

## French
https://github.com/GCTC-NTGC/gc-digital-talent/blob/7cb60975da5742eeaae629d76471d92e9a7e46cf/frontend/talentsearch/src/js/lang/fr.json#L1595-L1598
