### ISSUE TITLE
Screen Reader pauses mid-sentence in many information components

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/gc-digital-talent#4791]
## Description
Screen reader pauses mid-sentence and breaks up copy sentences in weird places when using keyboard navigation. 
Example: 

- My profile information text reads: " Let us know if you want to be contacted for new jobs. Please update your status if your situation." Pause and user has to hit the down arrow key before : " changes." 

## Screenshot: Prototype
![image](https://user-images.githubusercontent.com/101275838/202487101-8eb43845-cef9-4815-a9f8-73cbad664376.png)
[(https://talent.canada.ca/en/users/c12b1a66-002a-4659-8bff-80d134c76d7b/profile)]

## Acceptance Criteria
- [ ] ...

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by petertgiles** [comment]
Possible duplicate of or related to #4868

**Comment by RM-1978** [comment]
No longer an issue with the new update and retesting with additional screen reader users.

**Comment by esizer** [comment]
AT setting causing issues, tester had a maximum characters set per line. (nothing we can do)
