### ISSUE TITLE
When viewing IAP page in indigenous lang, links to other pages telegraph language change

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4797]
When viewing IAP homepage in a language besides English or French, any links to other pages still use the "/en" or "/fr" prefix, and include the `hreflang` attribute to indicate what language the target page is in, eg `<a href="/support" hreflang="en">`.

## Acceptance Criteria
- [ ] Links on a page do not link to a language code that page doesn't support
- [ ] Links to a page in a different language (different from the current content) specify their language in an hreflang.
- [ ] Links to a page in the same language do not specify an hreflang (??? - is this necessary?)

**Comment by gobyrne** [comment]
Indeed, no external links except in header and Footer (which are not translated). So ice boxing this

**Comment by mnigh** [comment]
@tristan-orourke should this issue be closed as can't repro since there are no external links in the IAP home page other than the header and footer?
