### ISSUE TITLE
Fix `npm run dev` e2e tests

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#4798]
Re-ticketed from https://github.com/GCTC-NTGC/gc-digital-talent/pull/4597#pullrequestreview-1183113613

The e2e tests pass with `npm run production`, but not `npm run dev`.

Error during cypress tests looks like this:
https://gist.github.com/patcon/7c0bb3e77bf4ec7e23177c966bd90cd8

Related: #3768

cc: @esizer 

Timebox for initial attempt: 2 days

**Comment by patcon** [comment]
Potential approaches:
- research and figure out why `npm run dev` is throwing error
- strip out react-router error boundary stuff that's causing the unknown behavior

**Comment by mnigh** [comment]
@petertgiles is this issue still relevant after https://github.com/GCTC-NTGC/gc-digital-talent/issues/5592 was closed as completed?
