### ISSUE TITLE
Implement cleaner routing logic via `createRoutesFromElements`

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#4799]
Re-ticketed from https://github.com/GCTC-NTGC/gc-digital-talent/pull/4597#pullrequestreview-1183113613

> implement `createRoutesFromElements` a component-based routing/RequireAuth

With this approach, we can apply each auth rule in a single line instead of wrapping each route component, kinda like so:
https://github.com/GCTC-NTGC/gc-digital-talent/compare/main...GCTC-NTGC:gc-digital-talent:react-router-spike-v2#diff-6cd43a91e81c996c8362d077f7d99869b2c16eafa395fe62796e3fd484a797caR128

```tsx
<Route element={<RequireAuth allowedRoles={[Role.Admin]} />}>
```

This might also leans a little more on `<Outlet />` component, possibly using it inside `<RequireAuth />`

## Screenshot

<img width="942" alt="Screen Shot 2022-11-09 at 1 56 17 PM" src="https://user-images.githubusercontent.com/305339/200849107-aabf241e-f7c9-462e-86f3-716714b9a706.png">

Helpful context:
https://github.com/GCTC-NTGC/gc-digital-talent/pull/4597#issuecomment-1308963659

react-router docs
https://reactrouter.com/en/main/utils/create-routes-from-elements

## Acceptance Criteria
- [ ] Router is updated to use routers from React elements instead of objects as it currently is

cc @esizer

**Comment by mnigh** [comment]
@GCTC-NTGC/developers is this something the team wants to do or can this issue be closed as not planned?
