### ISSUE TITLE
Make render function names more explicit

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#4800]
The overloaded render function of testUtils is simply called `render.`  `render` is the default name, so if it's rendered with other things it is hiding that. Even just `renderWithProviders` gives a hint at what happens below the abstraction in another file, instead of obfuscating and requiring opening it up.

Re-ticketed from https://github.com/GCTC-NTGC/gc-digital-talent/pull/4597#discussion_r1024334790

re: https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/frontend/common/src/helpers/testUtils.tsx

Acceptance Criteria:
- [ ] Update the testUtils render function with a more descriptive name, like renderWithProviders
- [ ] Make sure the function source has good documentation (JSDoc, inline, etc)

**Comment by esizer** [comment]
I believe this was solved in the app merge. 

https://github.com/GCTC-NTGC/gc-digital-talent/blob/3c73cbba6d13ad5c98994c47474c6ad0eb68c431/packages/jest-helpers/src/index.ts#L8

**Comment by tristan-orourke** [comment]
Yep, this is already done 👍
