### ISSUE TITLE
Uncaught Exception on Prod

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#4806]
### Actual Exception 
```
SyntaxError: Invalid regular expression: /C++/: Nothing to repeat
    at new RegExp (<anonymous>)
    at f (https://talent.canada.ca/talent/920.js?id=33037f5ccb1c1267934b:1:4474)
    at https://talent.canada.ca/talent/722.js?id=aa5d9f7f162bfd934c4d:1:12596
    at Array.filter (<anonymous>)
    at b (https://talent.canada.ca/talent/722.js?id=aa5d9f7f162bfd934c4d:1:12552)
    at https://talent.canada.ca/talent/78.js?id=43bf0e98d6c3e3a20ed6:1:17512
    at Object.wo [as useMemo] (https://talent.canada.ca/talent/app.js?id=8b8d77cc03ac1b5f4614:2:275495)
    at n.useMemo (https://talent.canada.ca/talent/app.js?id=8b8d77cc03ac1b5f4614:2:353310)
    at _ (https://talent.canada.ca/talent/78.js?id=43bf0e98d6c3e3a20ed6:1:17478)
    at to (https://talent.canada.ca/talent/app.js?id=8b8d77cc03ac1b5f4614:2:270791)

```

### Exception Detail
<html>
<body>
<div class="event-property-panel-title" role="presentation" style="box-sizing: inherit; margin-top: 15px; display: flex; flex: 0 0 45px; flex-direction: row; padding-right: 20px; color: rgb(0, 0, 0); font-family: wf_segoe-ui_normal, &quot;Segoe UI&quot;, &quot;Segoe UI&quot;, Segoe, Tahoma, Helvetica, Arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="event-property-panel-text" role="presentation" style="box-sizing: inherit; flex: 1 1 0px; margin-left: 10px; overflow: hidden;"><div class="server" role="presentation" title="EXCEPTION" style="box-sizing: inherit; font-size: 16px; font-family: wf_segoe-ui_semibold, &quot;Segoe UI Semibold&quot;, &quot;Segoe WP Semibold&quot;, &quot;Segoe UI&quot;, &quot;Segoe WP&quot;, Tahoma, Arial, sans-serif; text-overflow: ellipsis; white-space: nowrap; overflow: hidden;">EXCEPTION</div><div class="operation" role="presentation" style="box-sizing: inherit; font-size: 12px; text-overflow: ellipsis; white-space: nowrap; overflow: hidden;">Uncaught SyntaxError: Invalid regular expression: /C++/: Nothing to repeat</div></div></div><div class="event-property-panel-main" style="box-sizing: inherit; flex: 1 1 auto; overflow: hidden auto; padding-right: 20px; color: rgb(0, 0, 0); font-family: wf_segoe-ui_normal, &quot;Segoe UI&quot;, &quot;Segoe UI&quot;, Segoe, Tahoma, Helvetica, Arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="event-property-panel-section" role="region" aria-label="Exception Properties" style="box-sizing: inherit; margin-bottom: 15px;"><div class="event-property-panel-section-title" role="presentation" style="box-sizing: inherit; font-size: 15px; font-family: wf_segoe-ui_semibold, &quot;Segoe UI Semibold&quot;, &quot;Segoe WP Semibold&quot;, &quot;Segoe UI&quot;, &quot;Segoe WP&quot;, Tahoma, Arial, sans-serif; padding: 10px 0px; width: 467px; display: flex; flex-direction: row;"><span role="presentation" style="box-sizing: inherit;">Exception Properties</span><div class="float-right" role="button" aria-controls="aria-289" tabindex="0" focusable="true" style="box-sizing: inherit; margin-left: auto;"><span class="text-button" style="box-sizing: inherit; font-family: wf_segoe-ui_normal, &quot;Segoe UI&quot;, &quot;Segoe UI&quot;, Segoe, Tahoma, Helvetica, Arial, sans-serif; color: rgb(1, 92, 218); cursor: pointer; font-size: 14px;">Show less</span></div></div>

Event time | 11/16/2022, 11:42:24.646 AM (Local time) |  
-- | -- | --
Message | Uncaught SyntaxError: Invalid regular expression: /C++/: Nothing to repeat |  
Exception type | Uncaught SyntaxError: Invalid regular expression: /C++/: Nothing to repeat |  
Failed method | f |  
Operation Id | e1f6ec5f072b47029387d8053ef46f70 |  
Parent Id | e1f6ec5f072b47029387d8053ef46f70 |  
Problem Id | Uncaught SyntaxError: Invalid regular expression: /C++/: Nothing to repeat at f |  
Assembly | https://talent.canada.ca/talent/920.js?id=33037f5ccb1c1267934b |  
Severity level | Error |  
Telemetry type | exception |  
Operation name | /en/users/me |  
Session Id | k+8Xt5CoEywWqakN7Oi+/6 |  
User Id | lR7Ik7SshHcZH/Sg68QI9h |  
Device type | Browser |  
Device model | Other |  
Operating system | Windows 10 |  
Client IP address | 0.0.0.0 |  
City | Milton |  
State or province | Ontario |  
Country or region | Canada |  
Browser version | Chrome 106.0 |  
SDK version | javascript:2.8.9 |  
Sample rate | 1 |  

</div></div>
</body>
</html>

<html>
<body>
<div class="event-property-panel-title" role="presentation" style="box-sizing: inherit; margin-top: 15px; display: flex; flex: 0 0 45px; flex-direction: row; padding-right: 20px; color: rgb(0, 0, 0); font-family: wf_segoe-ui_normal, &quot;Segoe UI&quot;, &quot;Segoe UI&quot;, Segoe, Tahoma, Helvetica, Arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="event-property-panel-text" role="presentation" style="box-sizing: inherit; flex: 1 1 0px; margin-left: 10px; overflow: hidden;"><div class="server" role="presentation" title="talent.canada.ca" style="box-sizing: inherit; font-size: 16px; font-family: wf_segoe-ui_semibold, &quot;Segoe UI Semibold&quot;, &quot;Segoe WP Semibold&quot;, &quot;Segoe UI&quot;, &quot;Segoe WP&quot;, Tahoma, Arial, sans-serif; text-overflow: ellipsis; white-space: nowrap; overflow: hidden;">talent.canada.ca</div><div class="operation" role="presentation" style="box-sizing: inherit; font-size: 12px; text-overflow: ellipsis; white-space: nowrap; overflow: hidden;">GC Digital Talent</div></div></div><div class="event-property-panel-main" style="box-sizing: inherit; flex: 1 1 auto; overflow: hidden auto; padding-right: 20px; color: rgb(0, 0, 0); font-family: wf_segoe-ui_normal, &quot;Segoe UI&quot;, &quot;Segoe UI&quot;, Segoe, Tahoma, Helvetica, Arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="event-property-panel-section" role="region" aria-label="Page View Properties" style="box-sizing: inherit; margin-bottom: 15px;"><div class="event-property-panel-section-title" role="presentation" style="box-sizing: inherit; font-size: 15px; font-family: wf_segoe-ui_semibold, &quot;Segoe UI Semibold&quot;, &quot;Segoe WP Semibold&quot;, &quot;Segoe UI&quot;, &quot;Segoe WP&quot;, Tahoma, Arial, sans-serif; padding: 10px 0px; width: 467px; display: flex; flex-direction: row;"><span role="presentation" style="box-sizing: inherit;">Page View Properties</span><div class="float-right" role="button" aria-controls="aria-938" tabindex="0" focusable="true" style="box-sizing: inherit; margin-left: auto;"><span class="text-button" style="box-sizing: inherit; font-family: wf_segoe-ui_normal, &quot;Segoe UI&quot;, &quot;Segoe UI&quot;, Segoe, Tahoma, Helvetica, Arial, sans-serif; color: rgb(1, 92, 218); cursor: pointer; font-size: 14px;">Show all</span></div></div>

URL | https://talent.canada.ca/en/users/6165e87b-d781-4773-aecb-7a15ac24f942/profile/role-salary-expectations/edit |  
-- | -- | --
Browser version | Chrome 106.0 |  
Country or region | Canada |  
State or province | Ontario |  
City | Milton |  
Load time | 280 ms |  

</div></div>
</body>
</html>

**Comment by mnigh** [comment]
This is a problem with the query that the SkillPicker component uses. The error is triggered by inputting various characters including (but not limited to) `+`, `[`, `]`

1. `Uncaught SyntaxError: Invalid regular expression: /+/: Nothing to repeat` (at formUtils.ts:96:15)
2. `Uncaught SyntaxError: Invalid regular expression: /[/: Unterminated character class (at formUtils.ts:96:15)`

Leads back to the function `matchStringCaseDiacriticInsensitive`:
https://github.com/GCTC-NTGC/gc-digital-talent/blob/92cb664302ccfad3944a1721abcc17dad55d681c/frontend/common/src/helpers/formUtils.ts#L96

**Comment by petertgiles** [comment]
You could start this one by writing breaking tests in /frontend/common/src/helpers/formUtils.test.ts

**Comment by petertgiles** [comment]
Long term, this could be superseded by smarter search: https://github.com/GCTC-NTGC/gc-digital-talent/issues/4287#issuecomment-1310492218

**Comment by vd1992** [comment]
characters that crash the page so far...
```
+
*
( )
?
```

a period does nothing, treated like an empty space, makes sense looking at the `replace` function
