### ISSUE TITLE
API - Create Department model

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/gc-digital-talent#481]
# Description:
- Create the department model which includes generating a table migration, and generating an eloquent model.
- The department model fields should include: `id` (string), `department_number` (number), and `name` (localized_string)
- Make sure to seed data as well

Based on this data set:
http://donnees-data.tpsgc-pwgsc.gc.ca/ba1/min-dept/min-dept.csv

**Comment by tristan-orourke** [comment]
Shouldn't department_number be a `number`?

**Comment by yonikid15** [comment]
> Shouldn't department_number be a `number`?

Yes
