### ISSUE TITLE
HIDE skills in detail on profile 

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#4828]
## Description

- Users are being overwhelmed by the amount of skill justifications they need to fill out when they claim it through their Profile.
- Because of how impactful this is, this is being considered as a very high emergency fix
- To reduce this we are considering several solutions to alleviate this problem.
  1. Remove steps 3 and 4 (skills in detail, additional information) from the experience form (DURING PROFILE ONLY)
  2. Add a banner to instruct optimal number of skills
  3. Convert justifications to be optional in profile (needs design)
  4. Hybrid make the first 3 skills require a justification, and all subsequent skills optional (needs design)

### CONCERNS

Concerns for option 1: 
- Skills selected on profile would still show up as required during applications, we would need a fix for that too.
- (Additional concern) Non-poster skills on applications, should we hide them all together?
Option 2:
- Behavioural concerns (is this enough to deter the users?)
Option 3:
- Current design doesn't not convey OPTIONAL interactions really well, even if we just change the label it still might feel required, we would need to implement a new design to better convey that additional justifications are secondary to the interaction.
Option 4:
- LOTS OF DESIGN CONSIDERATIONS

## Screenshot: Prototype
![image](https://user-images.githubusercontent.com/16977254/202797711-01217c4f-9733-4aa1-add7-3d841ae68c92.png)

## Acceptance Criteria (going with option 1)
- [ ] When editing your profile, section 3 and 4 are removed from the Experience page entirely
- [ ] A user can still edit the set of skills associated with an experience, and those changes are saved.
- [ ] If a user already has skills with associated text saved to this experience, that text will not be lost, though it will not be visible. In other words, it can still be retrieved from the API, and would still appear during an application.
- [ ] If an experience already has additional text context, that will not be lost, though it not be visible.

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by tristan-orourke** [comment]
We're going with option `i) Remove steps 2 and 3 from the experience form (DURING PROFILE ONLY)` for now.
