### ISSUE TITLE
Build Self Declaration form (no carousel)

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4857]
## Description
Build the Honestly Pledge form (without carousel) in storybook.

### Screenshot 
![Screen Shot 2022-11-21 at 11:25 AM](https://user-images.githubusercontent.com/4313717/203107184-e94a50e6-fed7-4980-b068-bc5bc087ea96.png))

### Figma Prototype
https://www.figma.com/proto/IThJdlxAJqQPJyvX88hAG7/IAP-Honesty-Pledge-V6?node-id=4521%3A20259&scaling=min-zoom&page-id=4521%3A20212&starting-point-node-id=4521%3A20259

### Acceptance Criteria 

- [ ] 1.  Initially only shows the Self-Declaration radio buttons as required field with below values 

       -   “I affirm that I am First Nations (Status or Non-Status), Inuk (Inuit), and or a Métis person”
       -  “I am not a member of an Indigenous group, and I would like to see other opportunities available to me”
- [ ] 2.  When clicking on "I affirm ..." the Select you Community(ies) component and the boxed My Communities section underneath should be displayed.
- [ ] 3. When clicking on "I am not ..."  it should be displayed like below and link sends you to [GC Digital Talent Homepage](https://talent.canada.ca/en/) 
![Screen Shot 2022-11-17 at 10 26 01 AM](https://user-images.githubusercontent.com/89482910/202487372-98532093-eb14-4959-8ddf-74a8cd764c18.png)
- [ ] 4. When any of the community checkboxes are selected, the icon becomes coloured, and the name of is added in a Pill in the My Communities box.
- [ ] 5. If "I am First Nations" is selected, the radio selection appears below for "I am Status First Nations" and "I am Non-Status First Nations" goes from being empty and disabled to being required. If "I am First Nations" is uncheck, the radio selection goes back to disabled and empty.
- [ ] 6. When "I am Indigenous and I don't see my community here" is selected, its pill is coloured yellow and an informational alert appears: 
![Informational alert](https://user-images.githubusercontent.com/4313717/203133726-5c183fad-9e53-417a-954b-68a9145d17ef.png)
- [ ] 7. When the informational alert is closed, the pill should no longer be coloured yellow.
![After closing alert](https://user-images.githubusercontent.com/4313717/203133820-e4899ca2-cac8-4e46-9fec-a782741c85bb.png)
- [ ] 8. When "I affirm" is selected, and at least one community is selected, a Signature box and submit button (labeled "Sign and continue") should appear under the form.
- [ ] 9. Accessibility review from Rosalie or Maddy

**Comment by gobyrne** [comment]
Still waiting on mobile view from @BrookeCameron
