### ISSUE TITLE
Align month abbreviations with GoC guidelines

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4860]
We're using abbreviated month names in several places in the app, including experience accordion date ranges.  To render this we're using the date-fns format function with token MMM.
https://date-fns.org/v2.29.3/docs/format
This gets us pretty close to the GoC standard but is not quite right.
https://www.noslangues-ourlanguages.gc.ca/fr/cles-de-la-redaction/mois.html
In English, for example, June and July should not be abbreviated and abbreviated months should end with a a period.

Acceptance Critera:
- [ ] Show the full month word everywhere.
Ref: https://github.com/GCTC-NTGC/gc-digital-talent/pull/4819#pullrequestreview-1188713641

**Comment by tristan-orourke** [comment]
Interim solution - show the full month word everywhere.
