### ISSUE TITLE
enable ApplicantFilter to use pool candidate statuses

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#4865]
## Description
ApplicantFilter can't filter by optional statuses, this is required if ApplicantFilter is to replace PoolCandidateFilter (#4672 )
Places like Pool Candidate tables have the ability to filter by chosen statuses

## Screenshot
Here the `available in pools` only allows filtering by PLACED_CASUAL and QUALIFIED AVAILABLE 

![image](https://user-images.githubusercontent.com/40485260/203169411-8922c297-303c-48b7-8b8b-f7da88555ee8.png)

## Acceptance Criteria
- [ ] ...

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by vd1992** [comment]
ApplicantFilter is contained within UserFilter which makes me wonder when you'd pick one over the other as well as the potential for bugs with filtering Pools in two places (provided you don't null out the pool field nested in Applicant when passing in User)

![image](https://user-images.githubusercontent.com/40485260/203171326-34aa6a8d-d758-4465-b596-3645cc80cbae.png)

**Comment by vd1992** [comment]
attempting to add status filtering onto `ApplicantFilterInput` feels like it'll be messy too
`CountApplicants`, `CountCandidatesByPool`, and `CreateApplicantFilterInput` all assume a certain shape for it and all three would need to be changed which feels like a recipe for bugs for a while

might be a good idea to keep `PoolCandidateFilterInput` around and update it to use skills instead of CMO assets
saves the trouble of trying to align `PoolCandidatesPaginated` with `ApplicantFilterInput`

**Comment by tristan-orourke** [comment]
We shouldn't add statuses to ApplicantFilter. If we need to filter by status, we should be querying pool candidates instead. See #4672.
