### ISSUE TITLE
pools & bugs 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#4876]
1. Create a draft pool

2. Click on view pool advertisement
 ![Screen Shot 2022-11-22 at 4.05.35 PM.png](https://images.zenhubusercontent.com/61a7bd49e20af80694dd845e/e0711919-4fab-4b2d-b8be-c01d0f9557b2)

3. Apply For this process button enabled on draft  pool and clicking on that triggers the error 

![Screen Shot 2022-11-22 at 3.40.08 PM.png](https://images.zenhubusercontent.com/61a7bd49e20af80694dd845e/d6b495f7-1489-45c3-8eb2-a4511e77fa3b)

4. Draft pool has dead line as passed
 ![Screen Shot 2022-11-22 at 3.40.00 PM.png](https://images.zenhubusercontent.com/61a7bd49e20af80694dd845e/0f33d2ed-2b8d-42b1-9115-67d1ea233a8a)

### A/C 

- Draft pool should not be allowed to apply. Disable or hide the apply button 
- If the pool expiry date has bot been filled up yet , leave it empty. Do not display as deadline is passed.

**Comment by vd1992** [comment]
we definitely need to keep step 2 since that enables viewing how a draft poster looks, there was an issue about that recently so I am pretty sure we want to keep it

**Comment by brindasasi** [comment]
ok then will change the A/C

**Comment by tristan-orourke** [comment]
This can be closed in favour of #4908.
Applying to draft pools won't be a problem if people can't see draft pools at all.
