### ISSUE TITLE
Users page copy 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#4879]
- For adding the user to pools the text says  "Add user to other pools" 

1.  It doesn't read well  when the user is not in any pool .  Simply "Add user to pool" would be good. 
 ![Screen Shot 2022-11-22 at 3.43.32 PM.png](https://images.zenhubusercontent.com/61a7bd49e20af80694dd845e/7d9e3817-d99d-4a96-b19e-0f6d4e39c596)

In the same scenario like when there is no pool, when clicking on "Add user to pool" link the dialog shows up like "Add to different Pool" 
2. ![Screen Shot 2022-11-22 at 3.36.02 PM.png](https://images.zenhubusercontent.com/61a7bd49e20af80694dd845e/06177b9a-92f1-406b-b5fb-e57b12e0a6b6)

### A/C 
1.  Change text to "Add user to Pool" for both ? ( @Jerryescandon  pls confirm )

**Comment by Jerryescandon** [comment]
Approved, Ship it! :shipit:
