### ISSUE TITLE
Remove From Pool link is disabled on Users page

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#4880]
Remove from pool link is disabled in the users page. I don't see any code for this. Probably forgotten feature? 

![Screen Shot 2022-11-22 at 5.31.52 PM.png](https://images.zenhubusercontent.com/61a7bd49e20af80694dd845e/ab1e0822-b9f5-49c9-8820-3ee1d968edb1) 

### A/C

Clicking on the link should remove the user from the pool and remove any dependencies associated with that.

**Comment by vd1992** [comment]
ah, already up here #4688
