### ISSUE TITLE
Add to New Pool button cancels the dialog in Users page  

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#4882]
1. Click on Users from side menu 
2. On the Users list table click on `view` link to open the individual user page 
3. Click on "Add user to Pool" link 
4. Below dialog will appear and click on "Add to new pool"
![Screen Shot 2022-11-22 at 5.54.02 PM.png](https://images.zenhubusercontent.com/61a7bd49e20af80694dd845e/f194ecea-199a-4c0f-b268-dd60542af40b)
5. Observe it works as same as "Cancel and go back" link 

### A/C
I believe the objective here is to create a new pool & associate the user with it. 

Question  
Should we open the pool creation page ?
How do we navigate back to this dialog ?

**Comment by brindasasi** [comment]
@Jerryescandon  could you please review this?

**Comment by esizer** [comment]
Possibly related to [Bug - Fix extend pool closing date](https://github.com/gctc-ntgc/gc-digital-talent/issues/4899)
