### ISSUE TITLE
Invalid package.json name

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4896]
My editor is complaining that we picked an invalid name for our package.
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/7d65baf8-8e66-4ba5-a4dc-95eb0041f297)
It seems like we have named it with just a scope, no actual package name.  Not a big deal unless we decide to publish in a registry, but still.
https://docs.npmjs.com/cli/v8/using-npm/scope

**Comment by mnigh** [comment]
what about renaming it to `@gc-digital-talent/frontend`?

**Comment by mnigh** [comment]
Might be worth renaming the package names to match the workspaces at the same time, unless there is a reason `common` is different.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/d7559d9ae485ab6ea50f8777afe4e83662fde975/frontend/package.json#L4-L9

https://github.com/GCTC-NTGC/gc-digital-talent/blob/d7559d9ae485ab6ea50f8777afe4e83662fde975/frontend/admin/package.json#L2

https://github.com/GCTC-NTGC/gc-digital-talent/blob/d7559d9ae485ab6ea50f8777afe4e83662fde975/frontend/common/package.json#L2

https://github.com/GCTC-NTGC/gc-digital-talent/blob/d7559d9ae485ab6ea50f8777afe4e83662fde975/frontend/talentsearch/package.json#L2

https://github.com/GCTC-NTGC/gc-digital-talent/blob/d7559d9ae485ab6ea50f8777afe4e83662fde975/frontend/indigenousapprenticeship/package.json#L2

**Comment by mnigh** [comment]
This issue might be resolved during:

- https://github.com/gctc-ntgc/gc-digital-talent/issues/5065

**Comment by mnigh** [comment]
@petertgiles are you still seeing this problem in your editor? I no longer see it.

**Comment by petertgiles** [comment]
Good catch. We no longer have a frontend/package.json file and the one in the root does not have the @ sign.
