### ISSUE TITLE
Handle Invalid Input (UUID) Error in API

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#4921]
## 👋 Introduction

We are using UUIDs in the route parameters to access specific entities in the API. However, since users can put **_anything_** they want in the URL, they can put invalid UUIDs. Unfortunately, this causes our `graphql` server to throw a `500` with not much useful information. This makes it difficult to handle gracefully on the frontend and has lead us to show a generic `404` in the even to **_any_** error.

## 🛑 Error

This is what the error looks like.

```js
[
    {
        "message": "Internal server error",
        "path": [
            "poolAdvertisement"
        ],
        "extensions": {
            "category": "internal"
        }
    }
]
```

## ❓ What is Happening?

The real error is to do with invalid input, we expect a properly formatting UUID to be passed. Unfortunately, instead of sending a proper error code (`400` or `422`) we get a generic 500 error.

## ✅ Acceptance Criteria

- [ ] Determine appropriate status code (`400` or `422`)
- [ ] Handle bad UUIDs on server
- [ ] Send appropriate error to frontend
- [ ] Handle the error for pages

**Comment by petertgiles** [comment]
This is what it can look like with debugging info:
![image](https://user-images.githubusercontent.com/8978655/204035238-28eab021-74bf-4926-bed4-7b44cecafe40.png)

**Comment by esizer** [comment]
> This is what it can look like with debugging info:

Hmm, this is actually good info. Looks like it is a SQL error rather than GraphQL (what I initially thought).

**Comment by petertgiles** [comment]
I wonder what would happen if we implemented ID as a custom scalar in Lighthouse (like KeyString, for example) instead of letting it through as a plain string?  I wonder if we would get a better error or have a chance to hook in a better error?

**Comment by esizer** [comment]
> I wonder what would happen if we implemented ID as a custom scalar in Lighthouse (like KeyString, for example) instead of letting it through as a plain string? I wonder if we would get a better error or have a chance to hook in a better error?

I think you may be onto something here. That should prevent it from even getting to SQL in the first place, right?

Another option could be applying the [Laravel UUID rule](https://laravel.com/docs/9.x/validation#rule-uuid) to all of those queries 🤔
