### ISSUE TITLE
Remove barrel exports (index.ts files)

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#4923]
## Description

For various reasons the team agrees that we should avoid the use of index.ts files.

_Originally posted by @mnigh in https://github.com/GCTC-NTGC/gc-digital-talent/pull/4919#discussion_r1032608466_

## Resources

- https://basarat.gitbook.io/typescript/main-1/barrel
- https://blog.logrocket.com/using-barrel-exports-organize-react-components/
- https://hackernoon.com/react-project-architecture-using-barrels-d086146eb0f6

> **Warning**
Do not remove indexes from packages.
      
## Acceptance Criteria
- [ ] Remove all index.ts files and update the broken references
- [ ] Update style guide to note this recommendation

**Comment by petertgiles** [comment]
Need to have a go/nogo discussion

**Comment by mnigh** [comment]
> Need to have a go/nogo discussion

@petertgiles Did it this discussion happen? If nogo, can this issue be closed?

**Comment by petertgiles** [comment]
No strong feelings in the team but most people seem to be in favour, weakly.

**Comment by vd1992** [comment]
Sometimes they are quite handy, particularly when collecting stuff from a very busy directory to condense into a single location. 
Other times, not seeing the point like in the example below.

![image](https://user-images.githubusercontent.com/40485260/234694392-b9d0e387-79dc-4346-97cc-c7ea640ff294.png)

**Comment by petertgiles** [comment]
> Sometimes they are quite handy, particularly when collecting stuff from a very busy directory to condense into a single location.

That's true.  And I used them to do a bunch of renaming in apps/web/src/validators/profile/index.ts

**Comment by vd1992** [comment]
Don't think this'll be happening anytime soon if ever, gonna chance the wontfix
