### ISSUE TITLE
Send custom events to AppInsights 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#4949]
**Problem**

We don't have enough telemetry about exceptions that are happening in Prod. 
We get the below telemetry but there is no trace for what api has been called in here. 
![Screenshot 2022-11-28 134556.png](https://images.zenhubusercontent.com/61a7bd49e20af80694dd845e/ff0b2954-c115-4ac2-97a2-c2c5a36e219d)

### A/C 

- Investigate what type of telemetry details we can get more out of the box like turning on FETCH tracking 
- How do we use custom events to track the user journey ? -> Add the ability to do send custom events

**Comment by mnigh** [comment]
Sentry is a cool tool: https://docs.sentry.io/product/integrations/source-code-mgmt/azure-devops/
