### ISSUE TITLE
IAP Home Page Copy Correction

### ISSUE THREAD

**Issue by MCommonda** [GCTC-NTGC/gc-digital-talent#4950]
## Description

https://github.com/GCTC-NTGC/gc-digital-talent/blob/ebc02cbf2fadb9f199ee92273707818f9e80abdb/frontend/indigenousapprenticeship/src/js/components/Home/Home.tsx#L790-L793

https://github.com/GCTC-NTGC/gc-digital-talent/blob/ebc02cbf2fadb9f199ee92273707818f9e80abdb/frontend/indigenousapprenticeship/src/js/lang/fr.json#L346-L349

## Acceptance Criteria

- [x] `Talent portal strategy item 4 content` in English should be _Aim to launch the program in the early half of 2023._
- [x] `Talent portal strategy item 4 content` in French should be _Vise à lancer le programme au début de 2023._

**Comment by MCommonda** [comment]
Please change the text that reads 
"Launch
Aim to launch the program in the later half of 2022." to
"Launch
Aim to launch the program in the eary half of 2023."

**Comment by mnigh** [comment]
@MCommonda does this issue block us from publishing the work for https://github.com/gctc-ntgc/gc-digital-talent/issues/4587 once we receive the missing/lacking context strings that had previously been sent for translation? if it doesn't block it, can I create a separate issue for the following?

- [ ] Translate **Aim to launch the program in the eary half of 2023** into Michif (crg), Plains Cree (crk), Western Ojibway (ojw), Mikmaq (mic)
