### ISSUE TITLE
Soft skills should not actually be required to be picked during applications

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#4951]
## Description
Soft skills are important to be assessed by Pool Managers, but are very difficult to self assess and justify in writing, managers tend to to assess these anyway regardless of what was written in an application. Since this is mostly useless work for the applicants is best if we dont require soft skills to be declared and justified during applications. But it is still important to show them on the poster and application.

## To do
All (required or asset) soft (Transferable) skills should be removed from the required box and onto an informational box
These skills should not show up in the experience form either.

```
Required transferable skills
These skills will be assessed after you submit your application:
```

## Screenshot: Prototype
![image](https://user-images.githubusercontent.com/16977254/204652762-a280577a-9368-41dd-a131-940a6a09edb5.png)

![image](https://user-images.githubusercontent.com/16977254/204374459-1bc8b39d-d829-4054-b183-2e53737f1f62.png)

## Acceptance Criteria
- [ ] New alert on skills summary page that indicates which "transferable" skills were listed on the job advertisement, but states that they will be assessed later
- [ ] Transferable skills do not show up on the experience for (so you can't add them at all)
- [ ] Transferable skills are not required to submit your application

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by gobyrne** [comment]
@Jerryescandon can you please isolate all the new copy so we can send to translation? I'm not sure what's new and what's unchanged.

**Comment by Jerryescandon** [comment]
done
