### ISSUE TITLE
Ongoing Recruitments quick filter

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4952]
# Acceptance Criteria
- [ ] A dropdown which allows you to select a work stream, which hides the accordions that aren't the option they've selected
- [ ] Good accessibility

**Comment by petertgiles** [comment]
@substrae Should there be an option in the dropdown to clear the filter?  Otherwise the user won't be able to stop filtering once they've selected one.  What should the option label be?
![image](https://user-images.githubusercontent.com/8978655/206297641-6118c5a3-2875-49a6-a36a-5c4f2b50c117.png)
