### ISSUE TITLE
Showcase and Maintain Code Coverage in CI

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#4953]
### Problem 
We mostly test by the given acceptance criteria  but nowhere document it for future reference. 
There is no visualization on how much test coverage we have on a feature. 
We also want this to be less human resource dependant. 
So I think of only automated tests.
In that case we just want  CI calculates the code coverage and display the percentage as the badge under this ticket. 

### A/C 
Choose a open source tool and configure the CI so that :
- Calculate the current code coverage and make it our bench mark 
- Code coverage should be displayed as a badge 

## Timebox
3 days

**Comment by mnigh** [comment]
@tristan-orourke is this still something we are planning to implement? is there any budget for this type of service?

**Comment by tristan-orourke** [comment]
> Is there a budget?

There's potentially a budget for _anything_, if we think it's useful and can make a case for it. 

I'll leave this one up to @brindasasi. Feel free to add more details and the Review in Scrum label if you think it's worth looking at right now.

**Comment by brindasasi** [comment]
Last time I tried test quality and didn't like the point it had sep. interface and manually maintain it. 
Testspace is free for open source but haven't tried yet and there could more newer tools now. 
Let me re-write the spike properly to explain the objective. This so vague 🙈

**Comment by brindasasi** [comment]
Test space gives something like this 
![Screenshot 2024-03-14 at 10 53 36 AM](https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/6ccd2f8e-fced-4649-b54d-4855413efd3c)

**Comment by brindasasi** [comment]
Added codcov .. really liked it. super easy
https://app.codecov.io/github/GCTC-NTGC/gc-digital-talent/tree/4953-code-coverage-report/api%2Fapp%2FGraphQL



![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/99dab136-aff3-4201-a9e6-da8c44bc7b6c)

**Comment by mnigh** [comment]
> Added codcov .. really liked it. super easy https://app.codecov.io/github/GCTC-NTGC/gc-digital-talent/tree/4953-code-coverage-report/
> 
> ![Image](https://private-user-images.githubusercontent.com/89482910/318959227-99dab136-aff3-4201-a9e6-da8c44bc7b6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwOTE4NjEsIm5iZiI6MTcxMjA5MTU2MSwicGF0aCI6Ii84OTQ4MjkxMC8zMTg5NTkyMjctOTlkYWIxMzYtYWZmMy00MjAxLWE5ZTYtZGE4YzQ0YmM3YjZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDIwNTkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NTdkMTI0NDhjMGQ2NjQyMGVlNTc5NzE1ZmM4YWY1MDA0YjUxMGFlYmFkMDhkMDM0MWVhMTg3MDkwOGIyYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._pKnBr2OO-L6y3s_LAsn4gj9DvrFMFmQeW8Nc5pbSrk)

We had codecov hooked up for talent cloud (you can still see its dashboard in the same account as its part of the same GitHub organization 😄). I'm not sure it was used much more than as a curiosity. This has been discussed a bit before, but I think failing an action for the following may create a bottleneck:

> - Every merge that decreases current code coverage should fail

**Comment by brindasasi** [comment]
> > Added codcov .. really liked it. super easy https://app.codecov.io/github/GCTC-NTGC/gc-digital-talent/tree/4953-code-coverage-report/
> 
> We had codecov hooked up for talent cloud (you can still see its dashboard in the same account as its part of the same GitHub organization 😄). I'm not sure it was used much more than as a curiosity. This has been discussed a bit before, but I think failing an action for the following may create a bottleneck:
> 
> > * Every merge that decreases current code coverage should fail

Oh we decided not to do that. We can set that up in the configurations.

**Comment by brindasasi** [comment]
I'm also looking into getting coverage report from playwright currently.

**Comment by brindasasi** [comment]
we could get coverage for e2e as well with playwright and the effort is not intended chasing towards 100% coverage.
 This will be an indicator of what use cases we don't cover.
