### ISSUE TITLE
Continue Application from job advertisement

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#4954]
### Description

If I am logged in and I have started an application, I should be able to continue my application from the job advertisement.

![image](https://user-images.githubusercontent.com/16977254/204374814-62a95704-68ac-4005-a8ae-0f7ace347fba.png)

### To-do

Make this button available again, instead of starting an application for this poster it should continue the one already created.

![image](https://user-images.githubusercontent.com/16977254/204374971-b302eea3-3ca0-4b65-b60a-4035b3c97155.png)

### FR:
Continuer ma candidature

## Acceptance Criteria
- [ ] ...

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by esizer** [comment]
I could be misunderstanding this issue but I believe it was solved in https://github.com/gctc-ntgc/gc-digital-talent/issues/4892 where we now have three states:

1. No application: "Apply for this process" starts new application
2. Application but not submitted: "Continue my application" takes user to application
3. Application has been submitted: "You have already applied to this" disabled

**Comment by Jerryescandon** [comment]
This sounds about right
