### ISSUE TITLE
Incorrect path in infra docs

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#4958]
## 👋 Introduction

When we updated to use nginx the path to the web root changed but our documentation still points to the apache root.

## ❓ Proposed Solution

Change `infrastructure/README` 

- `docker-compose exec -w /var/www/html/api webserver sh -c "php artisan migrate"`
- `docker-compose exec -w /var/www/html/api webserver sh -c "php artisan db:seed"`

to

- `docker-compose exec -w /home/site/wwwroot/api webserver sh -c "php artisan migrate"`
- `docker-compose exec -w /home/site/wwwroot/api webserver sh -c "php artisan db:seed"`

## ✅ Acceptance Criteria

- [ ] Documentation updated
- [ ] Documented commands function as expected

**Comment by tristan-orourke** [comment]
The `e2e-tests.yml` github workflow and `api/README.md` also still reference the old php docker container.

**Comment by patcon** [comment]
this maaaay have been done as part of some commits i added to https://github.com/GCTC-NTGC/gc-digital-talent/pull/4998/commits

**Comment by esizer** [comment]
> this maaaay have been done as part of some commits i added to https://github.com/GCTC-NTGC/gc-digital-talent/pull/4998/commits

Think we can close, just checked and this has been updated 👍
