### ISSUE TITLE
Update setup.sh for nginx

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4962]
The code is mounted in a new location for nginx.  The setup scripts need to be updated for that.

**Comment by mnigh** [comment]
Some other places too:

![Screen Shot 2022-11-29 at 10 47 13](https://user-images.githubusercontent.com/3046459/204576247-d0ee3ef5-6265-47c5-9d05-dee2484f02bb.png)

**Comment by petertgiles** [comment]
Nevermind, mountpoints in the maintenance container haven't changed.  You can run the scripts just fine still.
