### ISSUE TITLE
🐛 Education Requirement on Search page is impossible to satisfy on Profile

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4970]
# Description
On the search page, it is possible to filter out users without a post-secondary education.
![image.png](https://images.zenhubusercontent.com/5d9ded8fd25901000101f3f0/b438c5f2-e2af-403e-bb76-b7fb4ccd505f)
In the backend, this adds the `hasDipoma=true` filter to the request.

However, while we previously allowed DCM to set the `hasDiploma` field when manually creating Pool Candidates, it doesn't appear anywhere in the profile! This means that any user who signs up and completes their own profile will automatically be excluded from any requests which require a diploma.

# Proposed solution:
 We could continue to submit the Education requirement in the request, but not use it to actively filter out applicants, similar to what we're doing with skills right now

Out of scope 
- We could add something to the profile, but that requires more design work than the alternatives.n(https://github.com/GCTC-NTGC/gc-digital-talent/issues/5976 )

**Comment by tristan-orourke** [comment]
@gobyrne @Jerryescandon I'd appreciate your opinions on this.

**Comment by petertgiles** [comment]
#5976 updated to represent the option 1 "short term" solution

**Comment by vd1992** [comment]
Problem to be addressed in #5976
