### ISSUE TITLE
Make the "unsaved changes" field annotation less trigger-happy

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#4981]
# Context
https://github.com/GCTC-NTGC/gc-digital-talent/issues/4831

Might be resolved with #4980, so using as dependency.

# 🧪 Proposed changes
- [ ] Verify only true changes trigger the unsaved effect, not empty fields that have been visited.
- [ ] Important to verify when adding skills during an application this doesn't trigger everything as well.

**Comment by brindasasi** [comment]
is this story still relevant? 
Team raised concerns on "un saved changes" functionality. 
Wondering is this still in sprint to do list?

**Comment by esizer** [comment]
> is this story still relevant?
> Team raised concerns on "un saved changes" functionality.
> Wondering is this still in sprint to do list?

I believe this is still relevant. The changes that were tentatively decided were:

1. Make alert appear on page load/submission only
2. Change the input messages to be hidden from assistive technology

**Comment by petertgiles** [comment]
Gray to take this back to the designers for clarity on direction.

**Comment by mnigh** [comment]
@gobyrne was there any clarity on direction for this issue? this issue is the only incomplete issue remaining for the epic #4832.

**Comment by gobyrne** [comment]
This is resolved with the new application process. Closing
