### ISSUE TITLE
Implement a centralized mechanism for logging 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#4982]
# Description
We need to build a logger feature that can help us to log the errors locally in dev environment and send the exceptions and custom events to Azure AppInsights in prod environment 

Proposal:
We build a useLogger hook which returns a logger object with `.info`, `.debug` and `.error` methods.  The hook itself tries to check what environment its in and changes its internal implementation for that, switching between console logging and sending to app insights.

QUESTIONS:
- How can our logger tell which environment its in? Note that if we use APP_ENV, then UAT will behave just like Prod. Do we add a new LOGGER_ENV env variable?
- How should the logger act on UAT? Logging to Azure somehow seems useful, but should be distinguishable from Prod.

# A/C 

- [ ] Logger service implemented in a single place and offers methods to log errors and custom events that can be re-usable within the app 

- [ ] Ability to log in different levels of details : Info , Debug , Error ( https://sematext.com/blog/logging-levels/ ) 

- [ ] Logging destination should be changed based on the environment 
       Local - console 
       Dev, UAT - log files ? 
       PROD - AppInsights

**Comment by patcon** [comment]
gray: we have approvals for these costs. UAT can also use zeroinsights.
