### ISSUE TITLE
update deployment script in devrobotfam

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#4987]
Another issue though is that it breaks our deployment reporting in devrobotfam.
![image](https://user-images.githubusercontent.com/8978655/205147480-fb01a5b1-838f-4140-906a-f43bbd0c5fc8.png)
I'm willing to approve because it still alerts if there's a failure but please put an issue on the board to update the script.
![image](https://user-images.githubusercontent.com/8978655/205147683-05a9a25e-048c-433e-b97d-8c7f6cf96ddf.png)

_Originally posted by @petertgiles in https://github.com/GCTC-NTGC/gc-digital-talent/pull/4973#pullrequestreview-1201591177_
      
## Acceptance Criteria
- [ ] Make the post-deployment script less clever by removing the migration counter
- [ ] Reliably fails if there is a failed migration
- [ ] Shows the migrations in Slack

**Comment by vd1992** [comment]
@petertgiles 
Still applicable?

**Comment by petertgiles** [comment]
Yeah, I still want to do this "someday".  Not super important though.
