### ISSUE TITLE
(in progress) ⌨ Accessibility - Profile My Skills List - Include Edit button outside of the expand/collapse

### ISSUE THREAD

**Issue by MaddyDaigle** [GCTC-NTGC/gc-digital-talent#4999]
**IN PROGRESS!!!! Don't code!!!

## ❌ Current behaviour (issue)
Edit link is hidden within an expand and collapse control, therefore is isn't accessible by screen reader unless the item is expanded.

**WCAG 2.1 Criteria:** 2.4.4 - Link Purpose (In Context)

### How to reproduce
1. Environment (prod or UA?) Prod
2. Which browser and/or Assistive Technology? Chrome
3. Step-by-step instructions explaining how to reproduce the problem.

## ✔ Expected behaviour (fix)
Add the edit link next to the icon in the skills list.  Make sure that there is alt text tying the link to the specific experience that will be edited.

(e.g. Edit User Experience Designer at...)

<img width="784" alt="Screen Shot 2022-12-02 at 3 21 33 PM" src="https://user-images.githubusercontent.com/1794660/205379381-98836a8d-7328-4107-9f23-b5e68441926c.png">

### Acceptance Criteria
A set of assumptions which, when tested, verify that the accessibility requirement was met.
- [ ] Criteria
- [ ] Criteria 2

## Additional information (optional)
1. How does it impact users?
2. Related issues, suggestions how to fix

**Comment by esizer** [comment]
@petertgiles Do you agree we can close this now that we _technically_ have this?
