### ISSUE TITLE
Column type of foreign keys should be uuid

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#502]
### Example
![Screen Shot 2021-09-16 at 16 37 55](https://user-images.githubusercontent.com/3046459/133685428-7deca765-e932-469b-b5cb-39f1b2e5b72c.png)

**Comment by mnigh** [comment]
@jaysonmc was there a particular reason you used the `string` method [in the migration](https://github.com/GCTC-NTGC/gc-digital-talent/commit/eae99748f05e7bc08941c4a180df17f2046c830f) rather than the `uuid` method that would match the type of the original id columns?

**Comment by jaysonmc** [comment]
@mnigh Nope. Good call, uuid would've been smarter.
