### ISSUE TITLE
Only show "nice to have" and "need to have skills" on the Snapshot

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#5030]
As an admin, I only want to see relevant information while screening candidates so I can quickly assess them.

## ⚙️ Summary

DCMO is getting application snapshots with 80+ skills on them. This is making the snapshot hard to parse.

We should remove unrelated skill information on the application snapshot.

## Acceptance Criteria
- [ ] Backend operation
- [ ] Only need to have and nice to have skills show up in the **application snapshot** 
- [ ] Only need to have and nice to have skills show up in saved-archived text version of the snapshot
- [ ] Other skills do not show up at all

**Comment by vd1992** [comment]
@tristan-orourke 

I think we might actually need to consider implementing this on frontend as well, both front and backend maybe redundant, so then frontend only (up for debate)

As, this is an existing issue, changing how the snapshot is formed does not fix the existing issue. It only prevents more people from creating applications with gargantuan skill collections, the existing ones remain hard to parse.
Changing how it is rendered will help make already captured snapshots easier to digest, a more thorough solution

**Comment by Jerryescandon** [comment]
Would splitting them into two tickets be an option? 
1. Prevent new applications to come in 
2. Retrofix old applications

**Comment by vd1992** [comment]
> Would splitting them into two tickets be an option?
> 
>     1. Prevent new applications to come in
> 
>     2. Retrofix old applications

I think so?

**Comment by tristan-orourke** [comment]
Splitting this into two tickets is definitely an option. However, my preference would be to ignore issue 2) Retrofix old applications. 

@gobyrne How big of an issue is this, for how many applications? How many of those applications will be left to screen by Jan 11? Is a retrofix for this one set of candidates worth complicating the application snapshot frontend? (The answer is allowed to be yes, even though it will make me sad.)

**Comment by gobyrne** [comment]
We do not need to retrofit.

**Comment by vd1992** [comment]
@gobyrne 
One additional question
If say, after filtering out unrelated skills an experience has zero skills left attached, do we still want to show that experience? Do we still want to save that experience in the snapshot?

**Comment by tristan-orourke** [comment]
I think the answer would be yes, still include all the experience, but I'll get @gobyrne confirm.

**Comment by gobyrne** [comment]
Yes, still save/show the experience even if it has 0 skills attached.

**Comment by vd1992** [comment]
thanks!
