### ISSUE TITLE
Validation of skills during application should check for justifications.

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#5031]
# ⚙️ Summary

We are getting users through the application process that have claimed a skill, but have not filled out a justification.

This was an unintended consequence of removing skill justifications to skills when added on the profile.

The current skill validation used on the application checks only whether a skill is on the profile, but what we really need is to know wether or not a user has justified their skill on the experience.

We should expand the validation of skills to include those skill justifications and create appropriate error messages for them.

Any questions please ask: @Jerryescandon 

### [Visit the Figma file]()

[PURPOSE AND DESCRIPTION]

## 💾 Files and resources

![image](https://user-images.githubusercontent.com/16977254/205987043-81129625-daa2-46a7-91bd-83c92fb7772a.png)

## ✅ Design checklist

- [ ] Component library elements have been used where appropriate
- [ ] Component library elements have been updated where changes where required
- [ ] Newly added interface elements have been added to the component library for reuse
- [ ] Newly added interface elements have been added to Github Discussions using the component issue template
- [ ] The interface is responsive or provides responsive context
- [ ] The interface provides both light and dark mode designs
- [ ] Complex interactions have been prototypes in a way that showcases every step in the flow
- [ ] Empty/null states have been accounted for
- [ ] The design has been reviewed by at least one other team member
- [ ] The design has been presented to the design team
- [ ] The design has been approved by stakeholders

## ✅ Accessibility checklist

**Please refer to [the comprehensive list](https://www.figma.com/file/rRMvm5nq4AMet29PW7bN2p/A11y-annotations?node-id=0%3A1) for more details.**

- [ ] Links have meaningful label text
- [ ] Navigation matches previously established patterns
- [ ] Headings are identified using annotations and follow a logical hierarchy
- [ ] Layout is linear and consistent with established patterns
- [ ] New interactive elements have unique focus states that match the established pattern
- [ ] Tab order has been identified using annotations
- [ ] Relevant images and icons have appropriate `alt` text
- [ ] Use of color meets AA WCAG contrast requirements
- [ ] States or information are not identified by color alone
- [ ] New interactive elements have appropriately sized touch targets on touch devices

## 📸 Screenshot

[SCREENSHOT]

# ✅ Requirements

- [ ] [REQUIREMENT]

## 🛠️ [REQUIREMENT NAME]

[REQUIREMENT DESCRIPTION]

[REQUIREMENT SCREENSHOT]

### [REQUIREMENT NAME]

[REQUIREMENT DESCRIPTION]

[REQUIREMENT SCREENSHOT]

# 🤔 Outstanding concerns

- [CONCERN]

# 📝 Related issues

**Please link all design and development sub-tasks related to this issue here for tracking purposes.**

- [ISSUE #]

**Comment by esizer** [comment]
So, it seems we are checking for the details to be filled out, we just aren't differentiating between "skill is missing" and "skill is present but missing details" in the display.  Unless there are steps to reproduce that I missed.

I'm going to work on differentiating in the meantime but want to make sure I'm not missing something when it comes to preventing submission with missing details @Jerryescandon 

https://github.com/GCTC-NTGC/gc-digital-talent/blob/4c771075275deb6f82a9e46b2c053af31e6fa930/frontend/common/src/helpers/skillUtils.ts#L134-L144

<img width="840" alt="Screenshot 2022-12-13 at 8 59 34 AM" src="https://user-images.githubusercontent.com/4127998/207352523-b3c78d48-675c-44bc-b277-edd2880d8299.png">

<img width="720" alt="Screenshot 2022-12-13 at 8 59 42 AM" src="https://user-images.githubusercontent.com/4127998/207352616-6b78da4b-8072-4811-a30a-0087c2c9eb5d.png">

**Comment by Jerryescandon** [comment]
So for some reason, people are submitting applications with no justification on how they got those skills. My reasoning was that these folks made profiles and added skills there, then when applying to a poster that asked for those skills, they showed up as "done" and were allowed to submit because those skills were on their profile.
