### ISSUE TITLE
Experiment with using a Translation Management System in our translation workflow

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#5034]
# Description
At various times, we've wondered if we might benefit from setting up some kind of integration with a TMS (Translation Management System).

My current expectation is that we'd want to make minimal changes to our use of React-Intl, but use a TMS to manage the content of our language files. This might make it easier for non-devs to work directly on the translations, and maybe edit English copy as well. We can also consider more drastic changes if they seem useful.

An extremely non-exhaustive list of some TMS options:

**[Weblate](https://weblate.org/en/)** - one nice option with weblate which is not available with all platforms is it can be selfhosted for free eg We could run it in a docker image on Heroku or something for, and integrate it can make automated github pull requests to update language files.

| Platform | Pricing | In-context editor | notes | free plan?
|----|----|----|---|---|
| Weblate | https://weblate.org/en/hosting/ | no
| Phrase | [USD$210/admin/mo](https://phrase.com/pricing/#tab-phrase-tms) | [yes](https://phrase.com/blog/posts/use-phrase-in-context-editor/) | =< 10 translators
| Lokalise | [USD$140/admin/mo](https://lokalise.com/pricing) | [yes](https://docs.lokalise.com/en/articles/1592525-livejs-web-in-context-editor) | =< 10 translators | [✅ 500 strings, 2 translators](https://docs.lokalise.com/en/articles/1400453-free-plan)
| Localize | https://localizejs.com/pricing | [yes](https://help.localizejs.com/docs/in-context-editor)
| Transifex | https://www.transifex.com/pricing/ | [yes](https://help.transifex.com/en/articles/6258617-translating-and-reviewing-in-transifex-live) | | [✅ for open source](https://help.transifex.com/en/articles/6236788-open-source-projects)
| Represso | https://respresso.io/pricing/ | [yes](https://blog.respresso.io/index.php/2020/06/22/in-context-translation-with-respresso/)
| CrowdIn | https://crowdin.com/pricing | [yes](https://support.crowdin.com/in-context-localization/)

### Languages

| language | [ISO 639-3](https://iso639-3.sil.org/about/relationships) | ISO 639-1 | alt | [Weblate](https://github.com/WeblateOrg/language-data/blob/main/languages.csv) | Localizely | [Transifex](https://explore.transifex.com/languages/) | [Phrase](https://support.phrase.com/hc/en-us/articles/5709608511516-Supported-Languages-TMS-) | [Lokalize](https://docs.lokalise.com/en/articles/1400544-language-settings)
|---|---|---|---|---|---|---|---|---|
| Michif | `crg` | | | ❌ | ❌ | ❌ | ❌ | ❓ 
| Plains Cree | `crk` | `cr` | `cre` | ✅ [`cr`](https://github.com/WeblateOrg/language-data/blob/main/languages.csv#L112) | ✅ [`cr`](https://localizely.com/language-code/cr/) | ❌ | ✅ `cr` | ✅ `cr`
| Western Ojibwe | `ojw` | `oj` | `oji` | ✅ [`oj`](https://github.com/WeblateOrg/language-data/blob/main/languages.csv#L429) | ✅ [`oj`](https://localizely.com/language-code/oj/) | ❌ | ❌ | ✅ `oj`
| Mi'kmaq | `mic` |  |  | ✅ [`mic`](https://github.com/WeblateOrg/language-data/blob/main/languages.csv#L374) | ❌ | ❌ | ❌  | ❓ 
|

## Acceptance Criteria
- [ ] Evaluate various TMS options and pick one
- [ ] Using a demo account or a self-hosted system, set up a basic integration with our repo that we can try using.

**Comment by petertgiles** [comment]
Timebox: Jan 6

**Comment by patcon** [comment]
We need to relicense from MIT to an OSI-compliant license in order to qualify for a Transifex open source repo. We've chosen AGPLv3. [Slack convo context](https://talent-cloud.slack.com/archives/CB424V61J/p1672934407722579) :lock:

**Comment by patcon** [comment]
Language codes we need the system to handle are listed here: `crg`, `mic`, `ojw`, `crk`
https://github.com/gctc-ntgc/gc-digital-talent/issues/4587#issue-1435162943

**Comment by tristan-orourke** [comment]
For now, we're going with Weblate because it can be self-hosted, allowing it to scale at neglible cost, and because it can be used with arbitrary language codes.

**Comment by petertgiles** [comment]
Next steps:
- Tristan and Pat will prep Megan for chat with Nathan
- Megan will ask Nathan if he is open to using a TMS
- Meeting with devs to decide after response from Megan

**Comment by patcon** [comment]
Closed this as recommended, and will create a new one to track next steps!
