### ISSUE TITLE
Update references to php docker container

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#5039]
With the update to PHP 8 and Nginx, the _php_ docker container was renamed to _webserver_ . However, we still have documentation (and the e2e-tests github workflow) which refer to the php container.

Try doing a global search for this regex string to find all instances of this: `docker.* php`

# Acceptance Criteria
- [ ] example commands in documentation and readme files should refer to correct container name
- [ ] e2e-tests workflow checks logs in the webserver container, not "php" container

**Comment by tristan-orourke** [comment]
Definitely related, though this ticket and #4958 actually identify two different problems 😛

**Comment by patcon** [comment]
this maaaay have been done as part of some commits i added to https://github.com/GCTC-NTGC/gc-digital-talent/pull/4998/commits

**Comment by petertgiles** [comment]
Agreed, this is done.
