### ISSUE TITLE
Update theming of the Accordion component

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#5042]
## ✨ Feature

It's time to update the theming of our accordion component.

## 🕵️ Details

Currently the Accordion component is mostly just used with experiences and a lot of theming is built-in for that use case.  It also uses the old colour scheme.  We use the accordion on the Browse Opportunities page but we've continued to use the old theming for now.  We've received new designs for the Accordion.  They use an updated colour scheme and also have two different styles to use.

## ✅ Acceptance Criteria

- [ ] Refactor the existing Accordion component with a prop to change the styles
- [ ] Implement the two new styles demonstrated in the provided design: "card" and "simple"
     - [ ] Remove the existing "card with old colours" style
- [ ] Ensure spacing and layout conforms to provided design
- [ ] Storybook stories: 
    - [ ] "card" style
    - [ ] "simple" style
    - [ ] nesting, subtitle, and icon features are demonstrated
- [ ] Experience accordions use card style accordions
- [ ] Ongoing recruitment accordions use card style accordions
- [ ] Review from designer

Out of scope: Dark mode happens in #5532 

## 🎨 Design File

Reference design: https://github.com/GCTC-NTGC/gc-digital-talent/discussions/5522

**Comment by esizer** [comment]
The [`<ToggleGroup />`](https://github.com/GCTC-NTGC/gc-digital-talent/blob/5c01b04c66ac822a5c102e95f1ff821fdfdb9e9a/frontend/common/src/components/ToggleGroup/ToggleGroup.tsx) component is a decent example of introducing some theming to the `@radix-ui` primitives.

**Comment by petertgiles** [comment]
@substrae 
1) Do we want accordions to use the new theming colour everwhere?
2) Are there new accordion designs in the pipeline we should be aware of?

**Comment by petertgiles** [comment]
We have a third style of accordion appearing now - the lightweight teal one.
![image](https://user-images.githubusercontent.com/8978655/214615294-2207cd8b-4305-4968-93dd-38bb43bdd31a.png)
Ref: #5457

**Comment by petertgiles** [comment]
Naming so far "prominent" and "lightweight" accordions

**Comment by substrae** [comment]
@petertgiles I've done full documentation for you over at https://github.com/GCTC-NTGC/gc-digital-talent/discussions/5522
