### ISSUE TITLE
Improve database seeder performance

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#5045]
## 👋 Introduction

Our `DatabaseSeeder.php` file is taking >1min to run right now and it is related the code following the normal `*Seeder.php` classes. We should look into moving this custom code into seeder classes and see about seeding more minimal data.

## ✅ Acceptance Criteria

- [ ] Improve seeder performance
- [ ] Reduce numbers of users seeded for basic dev seeder
- [ ] Reduce the amount of custom code in the main `DatabaseSeeder.php` file
- [ ] Hybrid approach: Some carefully created data and some random data

## 🕵️ Details

        > Wait, this seriously takes a minute for the seeder to run? 😨

Unfortunately, yes. The extra stuff we do at the end of the seeder has always been long, this just makes it longer. I wouldn't mind taking a look at it and seeing if we can do some optimizations.

## Update

It is specifically because we seed 150 users then for each user we:

- Generate 1-3 experiences for every category leading to creating 750-2250 experiences
- Create 1 pool candidate for each leading so seeding 150 pool candidates

I'm not sure we need that many users for dev, I bumped the number down to 20 and it only took 25s vs the 1min4s for the 150 users.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/d0b43cb2d82f2baa0ff4e78ccf5663100eacea68/api/database/seeders/DatabaseSeeder.php#L51-L168

_Originally posted by @esizer in https://github.com/GCTC-NTGC/gc-digital-talent/issues/5028#issuecomment-1340024387_

**Comment by vd1992** [comment]
I'd say soft blocked by #4998 
as per the stand-up discussion, seeding has received multiple band-aids because of that test, ought to let that settle first

**Comment by petertgiles** [comment]
One possible approach would be to figure out what we need to make each page look good and carefully make rows for each.  A bit more work to set up the seeder but you could get away far fewer entities and you could make them look more realistic.

**Comment by esizer** [comment]
> One possible approach would be to figure out what we need to make each page look good and carefully make rows for each. A bit more work to set up the seeder but you could get away far fewer entities and you could make them look more realistic.

I was looking at picking this up but was having trouble knowing what we should actually be seeding. I think we may need to decide on this first. We would want to know what each page should look like and likely create some state methods for our factories before breaking up the `DatabaseSeeder` and make it more targeted rather that the shotgun method.
