### ISSUE TITLE
remove TODO for filterByCmoAsset

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#5046]
resolve the TODO here

![image](https://user-images.githubusercontent.com/40485260/206307583-811b5946-8433-40d2-8fc6-57a7dbe3dc46.png)

most likely the complicating factor is needing to remove instances of the filter being used first
only example I found here

![image](https://user-images.githubusercontent.com/40485260/206307766-f63bdcd9-ee81-48ab-98e5-f69a7077264c.png)

**Comment by vd1992** [comment]
might not be able to remove filtering for CmoAssets until is is unused by request tables in /admin

**Comment by gobyrne** [comment]
Closing as this will be handled as part of #4629
