### ISSUE TITLE
Admin - Add Terms & Conditions Page

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#506]
- Referenced in [Footer component](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/admin/resources/js/components/Footer.tsx#L79)
- Needs content
- Needs a route created

Design
https://www.figma.com/proto/eZIjEzZRo92qaqwxIQkZii/Terms-of-service-and-Privacy-notice-interfaces---V1.0.0?node-id=2%3A2&scaling=min-zoom&page-id=0%3A1

**Comment by mnigh** [comment]
### Questions

1. What does the layout of the page look like?
2. Where is the content for the page?

**Comment by tristan-orourke** [comment]
@JoshBeveridge link designs here

**Comment by tristan-orourke** [comment]
Josh will implement these in the same repo as the landing page and report
