### ISSUE TITLE
Admin - Add Privacy Policy Page

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#507]
- Referenced in [Footer component](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/admin/resources/js/components/Footer.tsx#L84)
- Needs content
- Needs a route created

**Comment by mnigh** [comment]
### Questions

1. What does the layout of the page look like?
2. Where is the content for the page?

**Comment by tristan-orourke** [comment]
@JoshBeveridge link designs here

**Comment by tristan-orourke** [comment]
Josh will implement these in the same repo as the landing page and report
