### ISSUE TITLE
Tidy up Talentsearch

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#5070]
# This is the ~~fifth~~ third step in the Combine frontend epic.

> **Warning**
> This is a disruptive process.  Notify your team that you will be working on this workspace.

## :dart: Goals
1. Update the recently moved talentsearch project according to the new best practices

## :heavy_check_mark:  Acceptance Criteria
- [ ] Entire app continues to function as before
- [ ] Talentsearch now follows all the best practices

## :notebook:  References
- Suggested architecture: https://github.com/gctc-ntgc/gc-digital-talent/issues/2917#issuecomment-1160777179
  - Note that this architecture was made before React Router and Nginx were integrated
- Slack threads: [brainstorming](https://talent-cloud.slack.com/archives/CB424V61J/p1670440607411319) and [discussion](https://talent-cloud.slack.com/archives/CB424V61J/p1670610552790639)
- Items of concern during the moves:
  - Updating nginx configs, config.ejs
  - ~~Storybook~~ Storybook will be tidied in a separate issue
  - Maintenance scripts
  - translation files and workflows
  - feature flags, index.html, and webpack
  - documentation
  - jest, cypress
  - hydrogen settings
  - use [absolute imports](https://medium.com/geekculture/making-life-easier-with-absolute-imports-react-in-javascript-and-typescript-bbdab8a8a3a1)
  - [normalizing file naming](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/documentation/style-guide.md#typescript)
  - moving pages to the pages directory
  - moving "not reusable" components out of common

**Comment by esizer** [comment]
I may have completed this as part of #5344 🤔
