### ISSUE TITLE
Admin - filtering users table by "English Only" filters out candidates with preference for English

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#5073]
I viewed a request on Prod. I modified the filters so the only filters were:
- pools: IT-04 software solutions
- Profile Complete: Yes
- Languages: English only

This resulted in zero users appearing in the table. When I removed the Languages filter, three users appeared. However, the Preferred language was English for all three of them. What is going on?

It didn't matter if I selected English only, French only, or Bilingual - any language filter at all would filter out all users.

Also note: when I remove the Profile Complete filter but leave the Languages filter, I see a number of admin_entry users. That means the Languages filter is only filtering out users who have completed their own profiles.

**Comment by vd1992** [comment]
my immediate question is what the language ability of the users was
on the `User` model there is a `preferred_lang` field and a `language_ability` field

`preferred_lang` is either EN or FR
`language_ability` is EN or FR or BILINGUAL 

on say the users table, preferred language comes from the field that shares its name

![image](https://user-images.githubusercontent.com/40485260/206791519-485f9ec5-05e4-4629-a1d8-e940a698947a.png)

whereas language filtering acts on the other field

![image](https://user-images.githubusercontent.com/40485260/206791691-3eb3425b-b4d4-4346-b039-da3c8510f364.png)

this seems like it could set up case that looks odd but it functioning correctly if somehow
user preferred_lang == EN
user language_ability == FR

not guaranteed to be the issue, but need to know the language ability values to diagnose things better

**Comment by vd1992** [comment]
in the specific case in the issue itself
no language filtering was working which makes me wonder if the field `language_ability` was null for the users

**Comment by tristan-orourke** [comment]
Okay, here's the language fields returned by the getUserProfile query for one of these users:
```"preferredLang": "EN",
      "lookingForEnglish": true,
      "lookingForFrench": false,
      "lookingForBilingual": false,
      "bilingualEvaluation": null,
      "comprehensionLevel": null,
      "writtenLevel": null,
      "verbalLevel": null,
      "estimatedLanguageAbility": null,
      ```
      This user is filtered out when the AllUsersPaginated query includes `where: { applicantFilter: { languageAbility: "ENGLISH" }}}`

**Comment by tristan-orourke** [comment]
Okay, the filter checks against the `language_ability` on the users table. My guess is that `language_ability` is a holdover from our earlier, simplified implementation on PoolCandidate, and is never actually set when completeing the profile. Instead, the profile uses the following fields:
```
 "lookingForEnglish": true,
      "lookingForFrench": false,
      "lookingForBilingual": false,
      "bilingualEvaluation": null,
      "comprehensionLevel": null,
      "writtenLevel": null,
      "verbalLevel": null,
      "estimatedLanguageAbility": null,
```
We probably want to approach this in the same way we've handled other similar situations recently: deprecate the language_ability field, make it a computed field based on the `lookingFor<...>` fields, and remove the language_ability column from the db - using it to set the lookingFor columns if they are null.
