### ISSUE TITLE
Table pagination does not reset when contents change

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#5074]
The an admin table has many rows, it is possible to go to a later "page" of entries, then reduce the number of entries, getting yourself stuck on an empty "page".

Steps to reproduce:
1. From /admin/dashboard, view a request. (This is where I tested this, I assume these steps will work on any Admin table.)
2. Ensure the table is set to show 10 results at a time.
3. Adjust the filters until you see between 1-10 results. Note the filters you're using.
4. Adjust the filters so you get more than 10 results. Step the table forward to view "page 2" of the results.
5. Set the filter back to what you used in step 3. You should see zero results, and the option to change table "page" is disabled, even though there should be results.

**Comment by mnigh** [comment]
@tristan-orourke is this the same as #5296?

**Comment by gobyrne** [comment]
We think this is fixed now
