### ISSUE TITLE
Refactor common to packages to use with Turborepo

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#5075]
_Adapted from [a brainstorming Slack thread](https://talent-cloud.slack.com/archives/CB424V61J/p1670440607411319)_
It could be neat to use the [monorepo structure](https://github.com/vercel/turbo/tree/main/examples/with-docker) (which is not far off what was purposed) outlined in [turborepo](https://turbo.build/repo/docs) and introduce it at a later point.
Eric got [something working with it using our existing structure](https://github.com/GCTC-NTGC/gc-digital-talent/issues/4724) and it significantly improved task running.

We could split out common into different packages like:
```
|-- apps
|---- web
|-- packages
|---- ui // visual components
|---- data // all of our faker stuff
|---- hooks
|---- utils
|---- tooling
```
Then we could import like:
```
import Button from "ui/button";
import fakeUsers from "data/fakeUsers";
import useAuth from "hooks/useAuth";
import { formatDate } from "utils/dates";
```

The thought is, ideally we also have some static site in apps/docs where we can eventually have some documentation that is easily accessible and maybe even served on github pages 
Turborepo is [pretty loose on how you structure your app](https://turbo.build/repo/docs/getting-started/add-to-project), they just have some opinions on how it should be done but it works with yarn, pnpm and npm workspaces.
having the apps and packages directory is mostly just for organization to separate supporting code from the actual app itself

We could incrementally split up common too to make it smoother, like start with just the utils or hooks since they are smaller

Acceptance Criteria:
- [ ] Migrate common into discrete packages for turbo

**Comment by esizer** [comment]
Is it safe to close this in favour of #5072 ?
