### ISSUE TITLE
Pool Dashboard - Create a table view for PoolCandidates using react-table

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#51]
This task includes connecting the table to the API. That means writing the client-side graphql operation that queries all PoolCandidates, and creating a component that wraps the table component and includes a urql query hook.

TODO: Decide which columns should be displayed on the table? For reference here are all the possible fields:
```
type Pool {
    id: ID!
    pool: Pool @belongsTo
    user: User @belongsTo

    # cmoIdentifier can be an arbitrary string used to relate this candidate to an external database.
    cmoIdentifier: ID
    # Expiry date for this candidate being in the pool.
    expiryDate: Date

    isWoman: Boolean
    hasDisability: Boolean
    isIndigenous: Boolean
    isVisibleMinority: Boolean

    hasDiploma: Boolean
    languageAbility: LanguageAbility
    locationPreferences: [WorkRegion]
    acceptedOperationalRequirements: [OperationalRequirement]
    expectedSalary: [SalaryRange]
    expectedClassifications: [Classification]
    cmoAssets: [CmoAsset] 

    status: PoolCandidateStatus
}
```
Any type surrounded by [square brackets] represents a list, which we'd have to decide how to represent in a table cell.

**Comment by Jerryescandon** [comment]
Preemptively posting the prototype:
https://www.figma.com/proto/jOGqmmyq7mr3oVdiimiuPW/Pool-Manager?page-id=0%3A1&node-id=102%3A15&viewport=-784%2C285%2C0.4683002829551697&scaling=min-zoom
