### ISSUE TITLE
✏️ Internal guidelines for writing `intl` descriptions

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#5106]
## Description
There are no internal guidelines for writing `intl` descriptions. [Formatjs](https://formatjs.io/docs/react-intl/api/#message-descriptor) provides a description of the purpose of descriptions which is to provide "_context for the translator about how it's used in the UI_".

## Acceptance Criteria
- [ ] create guidelines for how to write standard descriptions

**Comment by mnigh** [comment]
## Description guidelines (ideas)
- A short description of how the string is used
- Avoid mentioning which component or page it's used in
- Avoid ending the description with a period or punctuation

**Comment by petertgiles** [comment]
I wonder if any of the a11y guidelines about how to write descriptive text for images, links, etc could be useful here?
