### ISSUE TITLE
Use Switch for boolean fields on UserTableFilters

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#5115]
## 👋 Introduction

Use the new `Switch` component in the `UserTableFilters` dialog, as originally proposed by @Jerryescandon (we didn't have a Switch component at the time).

Re-ticketed from https://github.com/GCTC-NTGC/gc-digital-talent/issues/3381

## ✅ Acceptance Criteria

- [ ] Switch components used for "Profile complete" and "Government Employee" form fields in `UserTableFilters`
- [ ] Form submissions are processed appropriately
- [ ] Form clears are processed appropriately
- [ ] Dialog forms work on Users and Candidate pages
- [ ] Confirm form field labels still make semantic sense. cc @GCTC-NTGC/designers 
- [ ] Form dialogs render appropriately on all screen sizes.

### Mockup: `UserTableFilters` (original proposal)

Figma mockup: https://www.figma.com/proto/XS4Ag6GWcgdq2dBlLzBkay/Admin-v3-(Profile-release)?node-id=465%3A8698&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=410%3A1984&show-proto-sidebar=1&hide-ui=1

![](https://user-images.githubusercontent.com/305339/179536912-1c718120-7257-428e-9e2c-cf072e17b878.png)

### Story: `UserTableFilters` (current)

https://main--61e099a1bb1465003a73d3ce.chromatic.com/?path=/story/users-usertablefilters--default

<img width="879" alt="Screen Shot 2022-12-14 at 1 52 21 PM" src="https://user-images.githubusercontent.com/305339/207687345-6a2b0967-9ef5-4f44-b4b7-84e18d6df8f5.png">

### Story: `Switch` (current)

https://main--61e099a1bb1465003a73d3ce.chromatic.com/?path=/story/components-switch--default

<img width="478" alt="Screen Shot 2022-12-14 at 1 56 33 PM" src="https://user-images.githubusercontent.com/305339/207687522-7dbb4bf5-76fd-4b9d-890e-4727f09e8392.png">

**Comment by mnigh** [comment]
@Jerryescandon is a design for this forthcoming or should the **updates in progress** label be removed?

**Comment by Jerryescandon** [comment]
uhhhmmm, oh boy, this is soo old, and I dont think anyone is actually working on this. Kill it.

**Comment by mnigh** [comment]
> uhhhmmm, oh boy, this is soo old, and I dont think anyone is actually working on this. Kill it.

@tristan-orourke since the `Switch` component is not referenced anywhere in the codebase should I create an issue to remove it?

**Comment by mnigh** [comment]
Create a new issue to remove the `Switch` component #7297.
