### ISSUE TITLE
Expand language preferences

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#5127]
## Description

Expand Language preferences in user profiles to include:
- Working Ability
- ~~FOL~~
- Written Exam
- Correspondence
- Interview language

## Other Considerations

Note as requirement:  Check how this looks on Admin? Does it show on tables? etc.

## Screenshot: Prototype

![image](https://user-images.githubusercontent.com/16977254/209225471-a11a35ea-c628-481f-8b54-27e17a9f3c80.png)

Vachan says:
migration with two fields
User.php changes
update schema for new inputs (updateUser)
update frontend (language form, profile view, tables, csv, download)

## Acceptance Criteria
- [ ] Two new *Required* language select fields on the Personal Information page of the profile
- [ ] Selected answers show up on the profile page
- [ ] Validation ensures you have selected these before progressing with your profile (like the correspondence language)
- [ ] Translation for the copy
- [ ] Update on the application snapshot to show these
- [ ] Update to all the downloads to include these

**Comment by gobyrne** [comment]
The word "first" shouldn't be there for "exam language preference"

**Comment by Jerryescandon** [comment]
Just to reiterate the conversation we had on the design team, about "First Official Language" and we have several concerns:
- The FOL label as-is is confusing and biased, it will deter diverse applicants from applying and reinforces colonialist values.
- It adds no new value since it is the same information collected on the Language section but worded differently.

Proposed solution:
- Use the information collected on the Language section and relabel it on admin side for HR consumption.

**Comment by substrae** [comment]
@Jerryescandon just to confirm - did we want to go with the dropdowns as well?

![image](https://user-images.githubusercontent.com/6960386/208679375-1cb2a907-0b66-4565-a459-9e9e93af8a50.png)

**Comment by Jerryescandon** [comment]
> @Jerryescandon just to confirm - did we want to go with the dropdowns as well? I think as also wanted to modify the labels to:
> 
> * Select your preferred spoken interview language
> * Select your preferred written exam language
> 

Yeah I think so, this hasn't moved into the sprint yet, But I think we should use the dropdowns if we are dropping FOL.

**Comment by brindasasi** [comment]
@Jerryescandon do we need to add this in the account creation page as well?

**Comment by Jerryescandon** [comment]
Do we have everything that is on the "About me" on the "Getting started"?
I feel like this is not an absolutely must-have info from account creation, it can wait until the user gets to the profile. I would not include it in the "Getting started" if we can avoid it. Unless we are literally copy pasting everything from that page already.

**Comment by brindasasi** [comment]
not really. I can avoid it. Thank you!

**Comment by brindasasi** [comment]
still waiting on translations to come back
