### ISSUE TITLE
Updates to User table for admin

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#5130]
We have a few improvements to the users table for admins.

### Acceptance Criteria
- [x] Hide telephone number column by default
- [x] Add new columns (hidden by default) created_at, updated_at
- [x] Sort the list in reverse chronological (created_at ascending)
- [x] Add column that shows user `jobLookingStatus` (actively looking, open to opportunities, inactive)
- [x] Default columns should be Name - Status - Email - Language - Edit - View

**Comment by mnigh** [comment]
@gobyrne for the step "Add new columns (hidden by default) created_at, updated_at", I can reused "Created" from the Pools table but I don't have anything for "Updated".

What would be the translation for **Updated** in French be, _Actualisé_?

**Comment by mnigh** [comment]
Gray says _Révisé_ for **Updated**
