### ISSUE TITLE
Batch "Add to pools"

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#5131]
## Description

Allow for a user to be added to multiple pools at once, change the all stats to qualified available and only put the expiration date once.

## To-do

Convert current selection for pool to a multi-value or checkbox in the modal when adding a user to a new pool so we can add them to many pools at once. 

Allow date of expiration to the same modal

## Screenshot: Prototype

![image](https://user-images.githubusercontent.com/16977254/207918685-b73fa788-fdb7-4b13-9196-783b7dc607af.png)

## Acceptance Criteria
- [ ] Select pool in the "add to pool dialogue" is a multi-select
- [ ] User should be added to all selected pools

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap

**Comment by tristan-orourke** [comment]
This is done with the `createApplication(userId: ID!, poolId: ID!)` mutation. We can use [aliases](https://graphql.org/learn/queries/#aliases) to [run a single mutation in bulk](https://sylhare.github.io/2022/04/26/How-to-bulk-mutate-in-graphql.html).

**Comment by yonikid15** [comment]
Take a look at section [One mutation on multiple entities](https://sylhare.github.io/2022/04/26/How-to-bulk-mutate-in-graphql.html)

**Comment by tristan-orourke** [comment]
Batching mutations is difficult with our current tooling.

If some requests fail, it would be sufficient to explain which ones did in toast notifications.

**Comment by gobyrne** [comment]
Can we confirm that the status "Qualified available" is what they will get in the pools they are added to? (It's in the description, but not the acceptance criteria)

**Comment by Jerryescandon** [comment]
> Can we confirm that the status "Qualified available" is what they will get in the pools they are added to? (It's in the description, but not the acceptance criteria)

Nice catch, when we designed the first add to pool interaction we didn't even have statuses, but it makes since that the default status to be "Qualified Available". If we wanted to be super thorough we could consider a status dropdown here to allow the user to select which status would be set on all these pools, but Im not sure if that work is worth it since we already have the batch change status as well.

**Comment by brindasasi** [comment]
from the front end , I could see them in the pool candidates list which implied to me they are in that valid status. Also this is existing mutation which is run by over and over. So if it is already working it should now as well. Will check into db on this to double confirm.
