### ISSUE TITLE
Hide, remove, deprecate, delete, destroy the "Role and salary expectations" section of the profile

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#5133]
The roles and salary expectations page is not currently in use and even the intended future use will now be replaced by the "Ongoing Recruitment" feature. So now we can safely remove it.

At a minimum we could simply hide the section on the profile and remove associated validation for it. We also need to remove/hide the corresponding section on the admin view of the profile and the "print profile", and the CSV user & candidate downloads.

At a maximum we could seek out and destroy all references to this in the code.

### Acceptance Criteria
- [ ] Delete role and salary components / pages
- [ ] Delete routes
- [ ] Fix the completion check
- [ ] Deprecate field in api

**Comment by vd1992** [comment]
@tristan-orourke 

this form connects to the `expectedGenericJobTitles` field

another thing to note is that there is also another related field that seems to have been redundant for a while, `expectedClassifications`
it does not appear to be defined anywhere from an applicant's perspective and should also be deprecated at some point?

as well, `expectedSalary` is the same, not controllable by the user anywhere

with the above three fields no longer useful, `scopeClassifications` is also no longer usable as there is nothing to return
this makes all filtering by classification then defunct, which is a filter present on the Users and the Pool Candidates table filter dialogs

so, it would be a good idea to clear up the state of the classifications/genericJobTitles/expectedSalary fields and which are for sure deprecated

**Comment by tristan-orourke** [comment]
Nice catch @vd1992. Sounds like all of these fields should be deprecated.

**Comment by esizer** [comment]
I may be missing something here, but it seems as though we are using this to filter users on the search page 🤔 

https://github.com/GCTC-NTGC/gc-digital-talent/blob/6d1577d25eddee17812d21c2610c190f903ff2e2/api/app/GraphQL/Queries/CountPoolCandidatesByPool.php#L77-L80

https://github.com/GCTC-NTGC/gc-digital-talent/blob/6d1577d25eddee17812d21c2610c190f903ff2e2/api/app/Models/User.php#L413-L543

**Comment by tristan-orourke** [comment]
@esizer @vd1992 References to `expectedClassifications` still exist in the code, but I think Vachan's right that they're not actually being _used_. For example, in line 160 of SearchForm.tsx, where the search page builds a filter object to send to the api, expectedClassifications is always set to the empty list. 

And in places where we might actually be using it, like on some Admin table filters, its not useful, because candidates have no way to add that info to their profile now.

I do think it should be deprecated and removed, but perhaps its out of scope for this ticket and these other fields deserve their own issues.

**Comment by esizer** [comment]
> @esizer @vd1992 References to `expectedClassifications` still exist in the code, but I think Vachan's right that they're not actually being _used_. For example, in line 160 of SearchForm.tsx, where the search page builds a filter object to send to the api, expectedClassifications is always set to the empty list.
> 
> And in places where we might actually be using it, like on some Admin table filters, its not useful, because candidates have no way to add that info to their profile now.
> 
> I do think it should be deprecated and removed, but perhaps its out of scope for this ticket and these other fields deserve their own issues.

okay, thanks! I wasn't sure if we were using it at all and was afraid to start deprecating everything I saw related to it and unknowingly break something 😅

**Comment by vd1992** [comment]
`expectedGenericJobTitles` is the only one users can actually update, so once it is no longer usable the scopeClassifications isn't usable either

**Comment by brindasasi** [comment]
this has to go live with ongoing recruitment feature. 
The plan is to get the approval for this PR but hold on to merge until it is safe to do so. Keep it in blocked column.
