### ISSUE TITLE
IAP Profile Page update for Honesty Pledge

### ISSUE THREAD

**Issue by BrookeCameron** [GCTC-NTGC/gc-digital-talent#5138]
# ⚙️ Summary

### [Visit the Figma file](https://www.figma.com/file/n5wm3rwAmz8cFrzXgBElx0/IAP-Candidate-profile-interface?node-id=4024%3A12750)  #justpingbrooke

Despite the designs using the IAP theme, this applies to the main Digital Talent build.

## ✅ Acceptance Criteria

- [ ] Profile view order changes to put DEI closed to the top: 
 1. about me 
 2. Diversity equity and inclusion 
 3. language info 
 4. work location 
 5. work preferences 
 6. Passions and experiences (skills and experiences) 
<img width="361" alt="Screenshot 2022-12-15 at 1 46 04 PM" src="https://user-images.githubusercontent.com/100953238/207942610-c100c6a9-5e41-4f51-8e27-ccfa1da0628a.png">

Diversity equity and inclusion section changes on profile view: 

- [ ] display community, and icons 
(first image shows just Indigenous identity and 2nd includes other DEI info) 
<img width="445" alt="Screenshot 2022-12-15 at 1 55 40 PM" src="https://user-images.githubusercontent.com/100953238/207944119-510e4d92-5e5f-466e-96aa-1a634e219d3a.png">

- [ ] Other EE groups should appear below indigenous communities (if multiple EE groups selected) using the existing bulleted format.

- [ ] If someone is indigenous, but only has filled out the legacy info, it should only appear as it does now. (so we don't break existing functionality)

**Comment by gobyrne** [comment]
Let's just make this part of the main talent platform instead of only IAP process. We need designs for how the pledge is presented on the Diversity, equity & Inclusion page.
