### ISSUE TITLE
Delete Direct Intake and Applicant Search feature flags in IaC

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#5160]
After v2.2.0 is deployed to Prod, we can delete any references to FEATURE_DIRECTINTAKE and FEATURE_APPLICANTSEARCH in Azure IaC.

Acceptance Criteria
- [x] Version 2.2.0 is ALREADY deployed to Prod.
- [x] No mention of FEATURE_DIRECTINTAKE or FEATURE_APPLICANTSEARCH in any of the 4 files in appsvc folder in IaC.

**Comment by brindasasi** [comment]
This has been completed and deployed into dev. Should I promote to UAT & PROD as well? 
![Screenshot 2023-01-04 135249](https://user-images.githubusercontent.com/89482910/210628933-97d7859c-f238-4e91-bc7b-026e425160a6.png)

**Comment by tristan-orourke** [comment]
@brindasasi go ahead and deploy the IaC changes to UAT. Let's hold off on Prod until we go through the full deployment process.

**Comment by brindasasi** [comment]
**Deployment Notes** 
Below build needs to be triggered during production 
![Screenshot 2023-01-04 150405](https://user-images.githubusercontent.com/89482910/210640164-0679b37c-fa15-45ec-8a5c-3b7e6bc125a5.png)
