### ISSUE TITLE
♻️ Resolve noise of "tsconfig.json missing" warning in logs of local cypress run

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#5171]
## ♻️ Debt/Refactor

Describe the problem with the existing implementation.
Running cypress commands throws an error:

```
Couldn't find tsconfig.json. tsconfig-paths will be skipped
```

## 🕵️ Details

This seems to have started appearing when the cypress v10 upgrade happened.
We are NOT using any ts files in cypress. patcon recalls this as being needed before in order to properly share some config files during cypress runs. aka there was a need, but perhaps it's not needed anymore.

## 📸 Screenshot

<img width="760" alt="Screen Shot 2022-12-16 at 3 23 10 PM" src="https://user-images.githubusercontent.com/305339/208183062-168c5faf-ad7a-4820-a2be-c95194b595b6.png">

## 🙋‍♀️ Proposed Solution

we can remove references to tsconfig.json in the cypress folder to remove the error :)

## ✅ Acceptance Criteria

- [ ] Cypress CI still passes
- [ ] All the local `npm run e2e:*` commands in `apps/e2e` still work fine.

**Comment by petertgiles** [comment]
Team is doubtful there is a straightforward solution.  Estimating very high.
