### ISSUE TITLE
🛠️🐛 Fix Chromatic "Details" links in status checks

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#5181]
Re-ticketed [from Slack message](https://app.slack.com/client/T5ZFRSQ3V/threads/thread/C0259G6KXJ6-1671057856.472799?cdn_fallback=1) :lock:

## 🛠️ Tooling

Fix our Chromatic storybook setup so that the "Details" links for "" and "" no longer point to error pages.

## 🕵️ Details

Example of page with erroring links:
https://github.com/GCTC-NTGC/gc-digital-talent/pull/5108/commits/3d40a1c696213e543dc6d3cfb9d0e03c15dc6341

| Status Check | link working? | Details |
|---|---|---|
| UI Review | :x: |  https://www.chromatic.com/pullrequest?appId=61e099a1bb1465003a73d3ce&number=5108
| Storybook Publish | ✅  | https://61e099a1bb1465003a73d3ce-fyuostsems.chromatic.com/?path=/story/pool-candidates--pool-candidates-table
| UI Tests | :x: | https://www.chromatic.com/build?appId=61e099a1bb1465003a73d3ce&number=4009

@vd1992 says that some links have been working [which? links?], but it's now back to being broken.

## 🙋‍♀️ Proposed Solution

Not sure, needs investigation.

## ✅ Acceptance Criteria

- "Details" link of _"UI Review"_ and _"UI Tests"_ status checks point to a working page for all...
  - [ ] `push` events
  - [ ] `pull_request` events

**Comment by gobyrne** [comment]
Seems to be working now. Presumably problem was not on our end.
