### ISSUE TITLE
🍪 Cookies with Insecure or Improper or Missing SameSite attribute

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#5184]
## Risk:
- Prevent Cookie information leakage by restricting cookies to first-party or same-site context 
- Attacks can extend to Cross-Site-Request-Forgery (CSRF) attacks if there are no additional protections in place (such as Anti-CSRF tokens).
- The SameSite attribute controls how cookies are sent for cross-domain requests.
- The attribute may have three values: 'Lax', 'Strict', or 'None'. If 'None' is used, a website may create a cross-domain POST HTTP request to another website, and the browser automatically adds cookies to this request.
- This may lead to Cross-Site-Request-Forgery (CSRF) attacks if there are no additional protections in place (such as Anti-CSRF tokens).
- Modes and their uses:
    - 'Lax' mode: the cookie will only be sent with a top-level get request.
    - 'Strict' mode; the cookie will not be sent with any cross-site usage even if the user follows a link to another website.
    - 'None' mode: the cookie will be sent with the cross-site requests.
    - The attribute having: 'Lax' or 'None' must have 'Secure' Flag set and must be transferred over https.
    - Example - Set-Cookie: key=value; SameSite=Lax;Secure
    - Setting attribute to 'Strict' is the recommended option.
    - Example - Set-Cookie: key=value; SameSite=Strict

## Official Fix Recommendation:
- Noted cookies include gc_digital_talent_session, XSRF-TOKEN, SRRAffinitySameSite, _gid, _ga, and others with random strings for names.
- Review possible solutions for configuring SameSite Cookie attribute to recommended values.
- Restrict Cookies to a first-party or same-site context.
- Verify and set the SameSite attribute of your cookie to Strict, to ensure that the cookie will only be sent in a first-party context.
- Or, if you want to relax the restrictions of first-party context, then verify and set the SameSite attribute of the cookie to Lax with Secure Flag enabled and transferred over HTTPS.

# Next Steps
- Our cookies were documented in https://github.com/GCTC-NTGC/gc-digital-talent/pull/5382/files
- `_ga` and `TS01*` are outside of our control and can be ignored
- We should try to set other cookies to Strict. If that is impossible, document the reason why.

# Acceptance Criteria
- [ ] The following cookies have a Strict SameSite attribute
  - [ ] ARRAffinity
  - [ ] ARRAffinitySameSite
  - [ ] ~ai_user and ai_session~
  - [x] gc_digital_talent_session
  - [x] XRSF-TOKEN
  - [ ] _long alphanumeric string_, (40 character length)
- [ ] If setting any of those to SameSite=strict is difficult, document in PR and in `documentation/cookies.md`

**Comment by mnigh** [comment]
Some of these cookies might be eliminated by [turning them off in Azure](https://github.com/GCTC-NTGC/gc-digital-talent/issues/2407#issuecomment-1092057418).

**Comment by patcon** [comment]
peter: something also perhaps related to appinsights

**Comment by gobyrne** [comment]
Might resolve #2407

**Comment by patcon** [comment]
tristan: not sure where these cookies are coming from. lots of cookies when we visit, and not sure where they're coming from

peter: prob coming from reverse proxy in front of us. they set one to ensure we always hit same load-balancer.

**Comment by patcon** [comment]
patcon: UK gov does inventory of cookie values, and shares that on website for public. we could do that and communicate it

**Comment by mnigh** [comment]
@vd1992 has documented the [cookies](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/documentation/cookies.md) in #5382. 

@GCTC-NTGC/developers do we have a path forward as a bunch of the cookies are external? also, is this issue not the same as #2407?

**Comment by petertgiles** [comment]
I think they are duplicated.  This one seems much more detailed and is already estimated. I suggest closing 2407.

**Comment by esizer** [comment]
> @GCTC-NTGC/developers do we have a path forward as a bunch of the cookies are external? also, is this issue not the same as #2407?

While this is a different ticket from using `Secure` it sort of overlaps. From what I can see, the only cookies we have that violates this is again, two we do not have control over. The rest are all set to `Lax` with `Secure=true`

 - `_ga` has neither `SameSite` or `Secure` set but comes from google analytics on the base `canada.ca` domain
 - `TS01*` does not set `SameSite` but has `Secure` set true. This is coming from [f5 ](https://my.f5.com/manage/s/article/K54501322)
 
 Technically, the f5 cookie does not violate this because of:
 
 > set the SameSite attribute of the cookie to Lax with Secure Flag enabled and transferred over HTTPS
 
 And I assume the google analytics cookie is from an unrelated site since we do not use it 😅 

---
 
 I guess the question is, can we set those that we do control to `Strict`? 🤔

**Comment by esizer** [comment]
Looks like we should be able to do the laravel ones easily. Just not sure about the azure ones 🤷‍♀ 

https://github.com/GCTC-NTGC/gc-digital-talent/blob/85f4aed2b3c5955ed237a21863ddadd325e312f2/api/config/session.php#L187-L200

**Comment by vd1992** [comment]
The Laravel ones easy yes, the F5 ones would have to be run through IMTD I think?

ARRA cookies, I don't know about changing the settings for them but they can be easily turned off

https://techcommunity.microsoft.com/t5/apps-on-azure-blog/configure-arraffinity-cookie-when-accessing-azure-app-service/ba-p/3842511
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/e657302a-a850-4bd7-9be4-5cb9ebc59a82)

Application insights, I cannot find anything to do with setting sameSite for them ourselves, only thing I could find regarding chatter about the property itself is here

https://github.com/microsoft/ApplicationInsights-JS/issues/1126
