### ISSUE TITLE
It should not be possible to retrieve information about the site's file system structure (eg from 403 responses)

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#5186]
## Risk:
- It is possible to retrieve information about the site's file system structure, which may help the attacker to map the web site
- The web application has exposed the presence of a directory in the site. Although the directory does not list its content, the information may help an attacker to develop further attacks against the site. For example, by knowing the directory name, an attacker can guess its content type and possibly file names that reside in it, or sub directories under it, and try to access them.
- The more sensitive the content is, the more severe this issue may be.

## Concrete examples
The report lists many cases where a path which should not exist returned a 403 response. In most cases I cannot reproduce these - the responses now return 404, as they should. Some cases, however, are still a problem:
1. Any two-character path, eg `/cc`, is parsed by our nginx config as a potential language code and routed to our frontend index with a 200 code initially. The frontend later triggers a redirect to the 404 page, with a 404 status code.
2. A path to a valid frontend directory + an invalid subdirectory, eg `/en/search/asdf`, routes to the frontend index with a 200 status code. When the page renders, the 404 page is shown, but a 404 status response is never triggered. (Should it be? On a SPA like this?)
3. The paths `/temp` and `/en/temp` appear to actually match the problem described in the report. They return a 403 response and a page seemingly generated by Nginx. This can be seen on UAT and Prod, but not local environments.
   ![response generated by the /temp path](https://user-images.githubusercontent.com/4313717/208761633-7ee72225-8976-437a-ab8f-e45b449965a9.png)
   
## Acceptance Criteria
- [ ] We understand why `/temp` is generating a 403 response
- [ ] `/temp` and similar cases return a 404 response instead
- [ ] only `/en` and `/fr` language codes should be considered valid

**Comment by petertgiles** [comment]
My preferred solution to this would be to move tcreport to a separate subdomain and send every single request to our domain to the frontend.  I think the reason this is happening is because we have nginx fallback any unknown path to the tcreport pages.

**Comment by tristan-orourke** [comment]
> My preferred solution to this would be to move tcreport to a separate subdomain and send every single request to our domain to the frontend. I think the reason this is happening is because we have nginx fallback any unknown path to the tcreport pages.

If a subdomain is out of reach, an alternative could be to replace the wildcard routing to tcreport pages with manual routing for every directory in the tcreport. It would be tedious, but doable.

**Comment by petertgiles** [comment]
If we need to keep routing all our apps from the same virtual host it would go a long way towards making things sane if we could limit paths to a few top-level segments.  Something like:
- Everything starting with /api goes to api/public/index.php
- Everything starting with /app goes to /apps/web/dist/index.html
- Everything starting with /tc-report goes to tc-report, routing static files
- Rules for those three but ending in .gif, .jpg, etc routing static files
- Everything else 404s

Having separate top-level rules for browse, support, search, etc is a bit crazy.

**Comment by tristan-orourke** [comment]
We've confirmed that we can create more subdomains, so moving the report to https://report.talent.canada.ca is an option.

_However..._ The existing urls for the report have been shared enough times that I'd still want to maintain Permanent Redirects for the old urls. Which leads me back to the suggestion to create nginx rules for all of the report directories (or a single rule with a complex regex, I guess).

**Comment by tristan-orourke** [comment]
As for this suggestion:
> Everything starting with /app goes to /apps/web/dist/index.html

While it would make the nginx config very nice and easy to deal with, I'm not sure that's worth modifying all our urls and making those urls slightly less nice and easy for end users.

**Comment by petertgiles** [comment]
I put together some ideas in #5978.

**Comment by petertgiles** [comment]
> Any two-character path, eg `/cc`, is parsed by our nginx config as a potential language code and routed to our frontend index with a 200 code initially. The frontend later triggers a redirect to the 404 page, with a 404 status code.

This one could be pretty simple to fix.  Right now the regex is `[a-z]{2}` but it could be changed to something like `[en|fr]`.

> A path to a valid frontend directory + an invalid subdirectory, eg /en/search/asdf, routes to the frontend index with a 200 status code. When the page renders, the 404 page is shown, but a 404 status response is never triggered. (Should it be? On a SPA like this?)

My understanding this that this is a common criticism of SPAs, though mostly for SEO reasons.  Right now our routing rules match with simple "starts with" rules so starting on a real path will get you the index.html with 200 code regardless of whether it's a real page.  With the simple subdomain routing we would simplify the routing even more (easier to maintain) but any path at all would get you a 200 (worse SEO).  Or we could go the other direction and maintain an exact sitemap in our Ngnix rules to really tighten it up to get better SEO at the cost of higher maintenance.  Here's an interesting read: https://thegray.company/blog/single-page-application-spas-404s-seo.

> The paths /temp and /en/temp appear to actually match the problem described in the report. They return a 403 response and a page seemingly generated by Nginx. This can be seen on UAT and Prod, but not local environments.

Yeah, that is interesting.  Our Docker image should match what it's in Azure so I bet this is coming from the upstream reverse proxy.  We would probably have to ask IMTD to confirm that.

**Comment by mnigh** [comment]
@GCTC-NTGC/developers was there any decision on a path forward for this issue?

**Comment by tristan-orourke** [comment]
The /temp file thing is probably to do with F5, not our nginx config, and the rest (serving proper 404s) isn't possible as an SPA. I'm closing this, and creating #9967 based on some of the discussion in the comments here.
