### ISSUE TITLE
Add new status for candidates in a pool

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#5187]
As an admin I want to flag when a candidates has been placed through another pool, so they no longer turn up in searches and I can track which pool they were placed in.

### Description

Add a new status for pools
**English:** Removed - placed through other pool
**French:** Retiré - placé à partir d'un autre bassin

Like the "placed" status, these candidates should no longer show up in searches or requests.

## Acceptance Criteria
- [ ] Add new migration for the "Removed" status (Question: What weight should the "Removed" status be attached too? Weight can be 160 (end of table))
- [ ] Add "Removed" status to PoolCandidateStatus enum in schema
- [ ] Add status to localized constants
- [ ] Update all search queries to remove candidates that have status = Removed
- [ ] Update sorting on the Pool Candidates table based on the new status weight (Question: Do we even want to display removed candidates? The option should be there to see them if you want, but ideally they would be filtered out by default)

**Comment by tristan-orourke** [comment]
Modifying statuses also requires adjusting the generated status_weight column in the table
https://talent-cloud.slack.com/files/U0321V55QN8/F04GB2B8VRT/image.png

**Comment by mnigh** [comment]
@gobyrne some questions about this issue:

> Update all search queries to remove candidates that have status = Removed

> As an admin I want to flag when a candidates has been placed through another pool, so they no longer turn up in searches and I can track which pool they were placed in.

1. Does this include the queries in the /admin as well or is this limited to the /`search` and `/request` queries?

> Like the "placed" status, these candidates should no longer show up in searches or requests.

2. Which placed statuses (there are three: PLACED_CASUAL, PLACED_TERM, PLACED_INDETERMINATE) and again, where does this apply to?

> Update sorting on the Pool Candidates table based on the new status weight (Question: Do we even want to display removed candidates? The option should be there to see them if you want, but ideally they would be filtered out by default)
Was this question ever resolved?

3. Can a REMOVED application be archived?

**Comment by tristan-orourke** [comment]
1. Probably limited to /search and /request. This status should be treated the same as Expired in terms  of where it gets filtered out and where it doesnt.
2. QUALIFIED_AVAILABLE nd PLACED_CASUAL show up in search counts, others do not.
3. The option should be there to see them if you want, but ideally they would be filtered out by default.
4. Yes
