### ISSUE TITLE
✨ Admins need some way of viewing expired candidates in a pool

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#5216]
## ✨ Feature

As an Admin, I should be able to see all candidates in a pool who have expired.

## 🕵️ Details

The poolCandidatesPaginated query, which is used by the PoolCandidates table, locks the query to the ACTIVE expiryFilter scope, meaning any expired candidates will be filtered out. 

## 🙋‍♀️ Proposed Implementation

Remove the expiryFilter scope from the query, and instead add it to PoolCandidateSearchInput. Add an Expiry Status input to the filter dialog, with the options ACTIVE, EXPIRED, and ALL. Default this input to ACTIVE, so the default page behaviour is the same.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] On the PoolCandidatesTable page, admins can change a filter to see all candidates (including expired ones), or only expired candidates
- [ ] By default, the PoolCandidates table continues to filter out expired candidates.
- [ ] Does not affect the behavior of the main search page
  - [ ] test verifies this

**Comment by gobyrne** [comment]
@petertgiles should this also be blocked on the status rework?

**Comment by petertgiles** [comment]
No, I don't think so.  I think it's fine to do now.
