### ISSUE TITLE
🧪 Pool Candidate Test Failing

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#5254]
## 🧪 Tests

The `e2e` test `pool-candidate.spec.js` is consistently failing. 

## 🕵️ Details

The test looks for a **View application** link in the table that does not seem to exist. From testing, it was observed that the test only fails in github actions and is passing locally.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt tests were properly updated and remains functional/passing.

- [ ] `pool-candidate.spec.js` consistently passes locally
- [ ] `pool-candidate.spec.js` consistently passes in github actions
- [ ] No changes to _expected_ application functionality

**Comment by tristan-orourke** [comment]
Update the test to be reliable regardless of seeders. Create the data you need with API calls before running the test.
