### ISSUE TITLE
🐛 Builds are failing in Azure pipelines since the turborepo merge

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#5259]
## 🐛 Bug

The Build Artifact process is failing in azure devops for new commits on main. This has been happening since Dec 30, likely when #5173, which included turborepo, was merged. 

## 🦋 Expected Behaviour

Every new commit to main should trigger a successful build.

## 🕵️ Details
[build error.txt](https://github.com/GCTC-NTGC/gc-digital-talent/files/10345549/build.error.txt)

## 📋 Steps to Reproduce

1. Log in to azure devops
2. Look at the recent builds, and see that they've failed.

## 📸 Screenshot

...

## 🙋‍♀️ Proposed Solution

I believe we need to update `infrastructure/bin/deploy.sh`. If turborepo works in the azure environment, then we should be able to replace most of the deploy file with a single line of `npm run build`. I think?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] New commits to main trigger a successful build in azure devops.

**Comment by esizer** [comment]
I took a look and am more confident that the fix should be fairly simple. I can probably get it in in short order however, im worried about testing since i do not have access to Azure.

Is it possible to confirm a fix without that?

**Comment by tristan-orourke** [comment]
@esizer Not really possible to test without Azure access, until we do https://github.com/GCTC-NTGC/gc-digital-talent/issues/5262. But if you want to try a solution, message me on slack and I'll help test it.

**Comment by patcon** [comment]
Related: https://github.com/GCTC-NTGC/gc-digital-talent/issues/5265
