### ISSUE TITLE
🛠️ Notification for build failures in Azure

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#5262]
## 🛠️ Tooling

We recently had a PR merged that failed to build in Azure.  We only noticed many days later.  How can we avoid this in the future?

Many people think something like this already exists?  A Slack message in devrobotfam or are we misremembering?  Does it exist and got broken somehow?

## 🙋‍♀️ Proposed Solution

A message in devrobotfam?

## ✅ Acceptance Criteria

- [ ] If main fails to build in Azure notify the devs in some way.

**Comment by brindasasi** [comment]
related 
https://github.com/GCTC-NTGC/gc-digital-talent/pull/3614

**Comment by mnigh** [comment]
@petertgiles was there ever a decision made on what the some way was for "If main fails to build in Azure notify the devs in some way"?

**Comment by petertgiles** [comment]
It would be nice to have, even a badge on the home page.  However, I think this problem is so rare that I would be fine closing or icing this one.
