### ISSUE TITLE
🛠️ Test-run `deploy.sh` in GitHub Actions CI

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#5265]
## 🛠️ Tooling

Let's do a test-run of `deploy.sh` in GitHub Actions CI, to help ensure more deploy failures surface in PRs.

## 🕵️ Details

While we can only reproduce _so much_ of the IMTD server environments in GitHub Actions CI steps, we can still test-run `deploy.sh` on PRs to ensure that there's as small a surface area as possible for surprising deploy failures to arise after merging into mainline.

Instigating issue: https://github.com/GCTC-NTGC/gc-digital-talent/issues/5259

Related solution (deploy failure notification): https://github.com/GCTC-NTGC/gc-digital-talent/issues/5262

Further, the very specific pre-setup steps needed to make `deploy.sh` runnable in CI (e.g., installing PHP, setting PHP version) will make it very clear the assumptions of setup that had to take place on the IMTD servers. As in, this would be a **source of "living" documentation of the one-time setup of the IMTD servers**.

## 🙋‍♀️ Proposed Solution

Let's create `test-deploy-script` GitHub workflow with as much parity as possible with how things run on IMTD servers.

## ✅ Acceptance Criteria

- [ ] a new `test-deploy-script` github workflow exists and runs on each PR
- [ ] envvars from azure are set as appropriate in github workflow
- [ ] steps from [`azure-pipelines.yml`](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/infrastructure/azure-pipelines.yml) are included in test run as appropriate, e.g., running `infrastructure/bin/set_php_versions.sh`

**Comment by patcon** [comment]
And catching things earlier pretty much always saves team capacity. One person fixing an issue in PR on their own is more efficient than multiple ppl discussing/resolving deploy failings in scrum :)

**Comment by petertgiles** [comment]
I'm not sure I love this approach.  Our CI testing is already pretty thorough and build failures on main in Azure happen rarely.  I think I would rather be notified that it definitely failed rather than it probably will fail.

**Comment by mnigh** [comment]
> I'm not sure I love this approach. Our CI testing is already pretty thorough and build failures on main in Azure happen rarely. I think I would rather be notified that it definitely failed rather than it probably will fail.

@tristan-orourke is this something you want to pursue or can I close this issue as not planned?

**Comment by tristan-orourke** [comment]
Not currently planned. We can restore this if we discover a deploy issue on Azure
