### ISSUE TITLE
🐛 Unsaved changes text remains after saving application notes

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#5287]
## 🐛 Bug

When reviewing an application, saved changes to the status and notes does not clear the "unsaved changes" messages.

## 🦋 Expected Behaviour

After successfully saving the notes the "unsaved changes" messages should disappear.

## 🕵️ Details

- **Operating System**: Linux - Popos 22.04
- **Browser**: Firefox 108.0

## 📋 Steps to Reproduce

1. Open an application in the admin site
2. Change the status and notes
3. Submit changes
4. Observe the "unsaved changes" messages

## 📸 Screenshot

https://images.zenhubusercontent.com/364642496/aaf7c570-7ded-41ac-998a-50d61d6a10e2/simplescreenrecorder_2023_01_05_14_15_33.mp4

## ✅ Acceptance Criteria

- [ ] After successfully saving the changes the "unsaved changes" messages should disappear

**Comment by gobyrne** [comment]
Yeah, seems like the same problem on a different page.
