### ISSUE TITLE
♻️ Dead Code - Remove Deprecated Role and Salary API Fields

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#5290]
## ♻️ Debt/Refactor

Remove deprecated Role and Salary API fields.

## 🕵️ Details

As part of https://github.com/GCTC-NTGC/gc-digital-talent/pull/5190, we deprecated a few role and salary fields. After some time, we will need these to be removed.

## 🙋‍♀️ Proposed Solution

Delete the fields.

## ✅ Acceptance Criteria

- [ ] Remove associated columns from database
- [ ] Remove associated accessors, policies, any other Laravel objects (may already be done)
- [ ] Also remove from database
  - SalaryRange PHP enum
  - classification_user table
  - users.expected_salary column

## 🛑 Blockers

```[tasklist]
### Blockers
- [ ] #5347
```

**Comment by vd1992** [comment]
@mnigh 
How much overlap does this have with #6226

**Comment by mnigh** [comment]
@tristan-orourke i think you had mentioned recently not removing database fields as part of #6226. should this issue still go ahead or not?

**Comment by mnigh** [comment]
@petertgiles does this still issue still need a blocked label? if so, what is it blocked by?

**Comment by petertgiles** [comment]
Heh, I think based on how sure we are that DCM won't ask for it to be added back in.  :laughing:

**Comment by mnigh** [comment]
> Heh, I think based on how sure we are that DCM won't ask for it to be added back in. 😆

Icebox then?

**Comment by mnigh** [comment]
> Remove deprecated Role and Salary API fields.

I can't find any of these fields in the codebase anymore. @GCTC-NTGC/developers can this issue be closed as stale?

**Comment by petertgiles** [comment]
Looks like James did the honours in https://github.com/GCTC-NTGC/gc-digital-talent/pull/7997.  

I noticed that there's still some cruft around, though.  In the past we haven't cleaned up deprecated data in the database but I'm not sure why.  We should keep our DB clean, too!

- SalaryRange PHP enum
- classification_user table
- users.expected_salary column
