### ISSUE TITLE
♻️  Restore the "Role and salary expectations" section of the profile

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#5305]
## ♻️ Debt/Refactor

Restore the "Role and salary expectations" section of the profile, which was removed recently in https://github.com/GCTC-NTGC/gc-digital-talent/pull/5190.

## 🕵️ Details

We decided that it would be safe to entirely remove the Role and Salary Expectations section of the profile because we would be activating the Ongoing Recruitment feature soon, and that would make Role and Salary Expectations unnecessary. Now, apparently, the Ongoing Recruitment feature is being postponed. 

## 🙋‍♀️ Proposed Solution

Revert the merge of https://github.com/GCTC-NTGC/gc-digital-talent/pull/5190 into main. Restore the `debt_5133_remove-roles-salaries` branch and create a new draft PR to merge it in later.

## ✅ Acceptance Criteria

- [ ] The Role and Salary Expectations section exists on the profile, and can be updated.
- [ ] The work of https://github.com/GCTC-NTGC/gc-digital-talent/pull/5190 is ready to be merged in at a later date.

**Comment by petertgiles** [comment]
Some of this functionality was removed in #5293, too.
