### ISSUE TITLE
🐛 Bug Report - Glitchy form incomplete section for experience creation

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#5312]
## 🐛 Bug

A boolean seems to be passed into the output from somewhere or somehow that garbles the text a bit

## 🦋 Expected Behaviour

No `false` being output to screen or any boolean for all experience forms

## 🕵️ Details

- **Operating System**: Name and version (if possible).
- **Browser**: Firefox

## 📋 Steps to Reproduce

1. Go to profile and go to create an experience
2. Immediately attempt to submit it without filling anything in

## 📸 Screenshot

![image](https://user-images.githubusercontent.com/40485260/211653680-6a75253f-fe95-4c92-ad76-fa4f68d78510.png)

## ✅ Acceptance Criteria

- [ ] Resolve bug

**Comment by patcon** [comment]
eric: related to update to react 18. merged template literals. something to do with ternary or `&&`
