### ISSUE TITLE
✨ Apply new header component to all pages

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#5314]
## ✨ Feature

Apply the header components as described in #5215 to all public facing pages (not admin). The component should already be built in #5298.

## 🕵️ Details

- Standard page header goes everywhere (other are the exception)
- Photo header is applied to the Browse Jobs page and Support/Page
- Centered layout goes on the manager search page

This will apply to all pages, regardless of whether or not they currently are styled for the "new look". This will actually make the pages look closer to the "new look", even though buttons are still the wrong color (for example).

Some pages also don't have headers at all right now. For those, there should still be an H1 (the profile sub-pages, for example). We should use the H1 text in the header and remove any links or similar that are between the header and the current location of the H1 (the **Cancel and go back** links are what we are thinking about right now).

(The homepage uses something else entirely, so don't do home page)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Go through site map, make sure all non-admin pages use the new header component.
- [ ] On edit profile pages, move title and subtitle into new Hero, and remove Go Back buttons.

Site map: https://docs.google.com/spreadsheets/d/17A3n9kCyr0lELtXYfegI8tNxlN1-vJVUK37NExYNHUI/edit#gid=1116634425

**Comment by patcon** [comment]
subpages of profiles don't have headers right now. on some pages there are links between where header and h1 are, and we will get rid of this

**Comment by esizer** [comment]
@petertgiles Can I request this be blocked on #5069 ? This is a selfish ask on my part due to expected merge conflicts so feel free to ignore 😅 

I can do this once the other PR is merged if that helps
