### ISSUE TITLE
Update edit Diversity Equity Inclusion page to include Indigenous Self Declaration 

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#5316]
## ⚙️ Summary

On the edit Diversity Equity Inclusion page, when someone adds the "I am Indigenous" identity, they are presented with the Indigenous Self Declaration form #4857 in a modal.

[Visit the Figma file](https://www.figma.com/file/n5wm3rwAmz8cFrzXgBElx0/IAP-Candidate-profile-interface?node-id=4024%3A12750)

https://user-images.githubusercontent.com/100953238/208692369-13cadd30-f6c2-4921-b14d-ea3ccb883f5e.mov

## Acceptance Criteria

- [ ] Copy changes about DEI in grey info box
- [ ] Mobile version of the pledge inside the Indigenous Identity dialog box 
- [ ] “i am an ally” radio is not present
- [ ] radio is changed to checkbox when single option present

**Comment by patcon** [comment]
can make these changes either on or branched off of the feature branch in the blocking issue

**Comment by petertgiles** [comment]
DEI grey info box copied from Figma:
> This section is optional, however, to be considered eligible for the IT Apprenticeship Program for Indigenous Peoples, you must self declare as Indigenous. If you are a member of one or more of these employment equity groups, and you do not wish to self identify on this platform, there is no obligation to do so. Complete the form below if you meet both of these conditions:

> You are a member of one or more of these employment equity groups.
You would like to be considered for opportunities addressed to underrepresented groups.
