### ISSUE TITLE
Disable pool filter in filter dialog on all candidates page

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/gc-digital-talent#5321]
## ✨ Feature

Allowing managers to add or remove pools in the pool filter on the pool candidates page doesn't really make sense, since you are viewing a specific pool. Disable the pool filter (multi select field) on the pool candidates filter dialog (eg. http://localhost:8000/en/admin/pools/{id}/pool-candidates). 

## 📸 Screenshot

![image.png](https://images.zenhubusercontent.com/5d9df0b9aba55400015a68fe/b2bcd3ad-4ee1-4a5d-b279-442d8d99f550)

## 🙋‍♀️ Proposed Implementation

There should already be a prop called `isDisabled` on the `<MultiSelectField />` component which you can set to true.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Pool filter is disabled in PoolCandidateTableFilterDialog only on the "All Candidates" page (eg. http://localhost:8000/en/admin/pools/{id}/pool-candidates).
- [ ] Pool filter should **still be** usable on the Request page tables.
- [ ] Watch out for the /admin/pool-candidates page, do  not break it

**Comment by tristan-orourke** [comment]
@yonikid15 could you give this ticket a more specific title? 😂

**Comment by yonikid15** [comment]
Already on it 😆

**Comment by petertgiles** [comment]
Might need to be "readOnly" instead of "isDisabled" to ensure it is included in the request.

**Comment by petertgiles** [comment]
We will probably want to hide some other filters when we use this for the screening and assessment page.  Try to make the solution for this issue extensible to that as well, if possible.
