### ISSUE TITLE
🐛 Bug Report - pool table sort not sorting correctly

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#5322]
## 🐛 Bug

Sorting the rows does not work entirely properly for the pools table

## 🦋 Expected Behaviour

Sorting works properly

## 🕵️ Details

The columns that are not sorting properly are "Pool Name" and "Group and Level", likely due to them being complex cells
The simple columns like "Email" sort properly

## 📋 Steps to Reproduce

1. Head to /en/admin/pools
2. Play with sorting

## 📸 Screenshot

Recording
http://recordit.co/EiLFAb3nYa

![image](https://user-images.githubusercontent.com/40485260/211929991-c961ade8-9d25-4534-80a1-89ced25dfe29.png)

## 🙋‍♀️ Proposed Solution

Pool Name sorts by pool name alphabetically
Group and Level sorts by group alphabetically and then level numerically

## ✅ Acceptance Criteria

- [ ] sorting works

**Comment by patcon** [comment]
@esizer react-table allows passing in a sort value to force sorting by. it's now sorting by HTML value

tristan: accessor + cell attributes
