### ISSUE TITLE
Make use of new logger for API failures

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#5336]
## ♻️ Debt/Refactor

Currently we don't log api failures in the system. This is crucial information that we are missing out while investigating  production issues. 

## 🕵️ Details

Now we have that #4982 implemented we can add more logging into App Insights. 
Make it a limited scope for this story only on certain api calls .. probably admin pages currently ? 
 
## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

- [ ]  All admin pages ( pool candidate table ,user table etc) should have the error logging

**Comment by petertgiles** [comment]
https://github.com/GCTC-NTGC/gc-digital-talent/pull/5303#discussion_r1067110620

**Comment by petertgiles** [comment]
Thanks, Brinda, for testing!  ClientProvider errors are already being logged in Azure Insights.
