### ISSUE TITLE
Cookies - What they are and what's spawning them

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#5337]
## Acceptance Criteria

- [ ] List all the cookies on prod
- [ ] Document: Source, purpose, do we control it. For all cookies
- [ ] Add the table or document with this info to our Repo Readme

**Comment by patcon** [comment]
Prior art from UK gov:
https://github.com/DFE-Digital/polis-whitelabel/blob/govuk/main/client-admin/src/content/cookies.md

**Comment by vd1992** [comment]
### ARRAffinity 

- found at paths /search, /pools, /en, and /graphql
- Azure cookie
- More details here https://azure.microsoft.com/en-us/blog/disabling-arrs-instance-affinity-in-windows-azure-web-sites/

disabling

![image](https://user-images.githubusercontent.com/40485260/213255605-ea45a330-6553-45a8-852b-00000eba6c57.png)

**Comment by vd1992** [comment]
### ARRAffinitySameSite 

- found at paths /search, /pools, /en, and /graphql
- Azure cookie
- similar in purpose to ARRAffinity

![image](https://user-images.githubusercontent.com/40485260/213256348-7f06d63f-7158-4a54-a61f-16a9a6beb034.png)

**Comment by vd1992** [comment]
### TS#

![image](https://user-images.githubusercontent.com/40485260/213258307-4d9d4725-399d-49ea-b4e7-44497e88da46.png)

- found at paths /search, /pools, /en, and /graphql
- appears to be a security related cookie for AskF5?
- more info https://support.f5.com/csp/article/K6850

![image](https://user-images.githubusercontent.com/40485260/213259210-6afdd0bf-0d32-4080-8b58-b499ca0aa6ac.png)
