### ISSUE TITLE
♻️ Switch from NPM to PNPM

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#5338]
## ♻️ Debt/Refactor

Right now our main motivation for this is that it would avoid the problem of missing integrity hashes. #2557 / #2558

## 🕵️ Details

It shouldn't be that hard to switch, but there may be some nuances. It makes sense to wait until we're done modifying how we use workspaces (#5065) to do this.

## ✅ Acceptance Criteria

- [ ] Ensure dependabot continues to work
- [ ] Ensure turbo continues to work
- [ ] PNPM used in maintenance scripts
- [ ] PNPM used in Github Actions
- [ ] PNPM used in Azure build
- [ ] PNPM detects missing integrity hashes
- [ ] PNPM detects malformed dependencies
- [ ] PNPM handles workspaces properly
- [ ] Help your teammates update their local environments

## 🛑 Blockers

Issues which must be completed before this one.

```[tasklist]
### Blocked By
- [ ] #9702
```

**Comment by patcon** [comment]
Context in [Slack thread](https://talent-cloud.slack.com/archives/C0259G6KXJ6/p1675258851642519?thread_ts=1674681993.816539&cid=C0259G6KXJ6)

Just realized another great reason to use yarn (or pnpm): the ability to "patch" is built in..!
https://github.com/ds300/patch-package#yarn-v2

This means that when we need a change in an upstream package, we can create a PR for that, but also easily commit a "patch" for that change to our repo. The patch will be auto-applied after we install the upstream package. We use our patch until the PR is accepted upstream, and there's a more seamless flow to work within our codebase even when upstream changes are required.

**Comment by petertgiles** [comment]
I wonder if this will solve the problem where we have problems running npm scripts from npm itself in Docker on Linux?

**Comment by patcon** [comment]
I suspect troubles like in this thread come from the lack of assurances in `npm`, that I understand `yarn` is better with: https://talent-cloud.slack.com/archives/C0259G6KXJ6/p1683727680265059

So using yarn might have side-stepped an issue like this where significant time was lost

**Comment by esizer** [comment]
So, got most of the way through this but cannot build due to do a version mismatch between `@urq/core` and `@urql/exchange-auth` that I cannot seem to resolve. 😢

**Comment by yonikid15** [comment]
Waiting till #4916 is finished before completing this issue.

**Comment by esizer** [comment]
Can I make a suggestion that we update this issue to `pnpm` instead? 

REF: https://dev.to/ayoub3bidi/lets-settle-things-out-2-npm-vs-yarn-vs-pnpm-5e04

**Comment by mnigh** [comment]
> Can I make a suggestion that we update this issue to `pnpm` instead?
> 
> REF:
> 
> * https://dev.to/ayoub3bidi/lets-settle-things-out-2-npm-vs-yarn-vs-pnpm-5e04
> * https://romanglushach.medium.com/comparing-npm-yarn-and-pnpm-package-managers-which-one-is-right-for-your-distributed-project-to-4d7de2f0db8e

Further reading:

https://pnpm.io/feature-comparison
https://pnpm.io/pnpm-vs-npm

**Comment by tristan-orourke** [comment]
Blocked by our use of Cypress

**Comment by esizer** [comment]
> Blocked by our use of Cypress

I decided to take a look at this while babysitting dependabot to see if anything has changed. I was able to resolve one error but another has popped up in its place 😢 Seems it is now `urql` causing issues. I suspect it is a version mismatch 🤔 

<details>
<summary>Error dump</summary>

```sh
@gc-digital-talent/web:build: ERROR in /home/diomedes/Projects/gc-digital-talent/packages/client/src/components/ClientProvider/ClientProvider.tsx
@gc-digital-talent/web:build: 104:10-141:12
@gc-digital-talent/web:build: [tsl] ERROR in /home/diomedes/Projects/gc-digital-talent/packages/client/src/components/ClientProvider/ClientProvider.tsx(104,11)
@gc-digital-talent/web:build:       TS2322: Type 'import("/home/diomedes/Projects/gc-digital-talent/packages/client/node_modules/@urql/core/dist/urql-core-chunk").Exchange' is not assignable to type 'import("/home/diomedes/Projects/gc-digital-talent/node_modules/@urql/core/dist/urql-core-chunk").Exchange'.
@gc-digital-talent/web:build:   Types of parameters 'input' and 'input' are incompatible.
@gc-digital-talent/web:build:     Type 'import("/home/diomedes/Projects/gc-digital-talent/node_modules/@urql/core/dist/urql-core-chunk").ExchangeInput' is not assignable to type 'import("/home/diomedes/Projects/gc-digital-talent/packages/client/node_modules/@urql/core/dist/urql-core-chunk").ExchangeInput'.
@gc-digital-talent/web:build:       The types of 'client.operations$' are incompatible between these types.
@gc-digital-talent/web:build:         Type 'import("/home/diomedes/Projects/gc-digital-talent/node_modules/wonka/dist/wonka").Source<import("/home/diomedes/Projects/gc-digital-talent/node_modules/@urql/core/dist/urql-core-chunk").Operation<any, import("/home/diomedes/Projects/gc-digital-talent/node_modules/@urql/core/dist/urql-core-chunk").AnyVariables>>' is not assignable to type 'import("/home/diomedes/Projects/gc-digital-talent/node_modules/wonka/dist/wonka").Source<import("/home/diomedes/Projects/gc-digital-talent/packages/client/node_modules/@urql/core/dist/urql-core-chunk").Operation<any, import("/home/diomedes/Projects/gc-digital-talent/packages/client/node_modules/@urql/core/dist/urql-...'.
@gc-digital-talent/web:build:           Type 'import("/home/diomedes/Projects/gc-digital-talent/node_modules/@urql/core/dist/urql-core-chunk").Operation<any, import("/home/diomedes/Projects/gc-digital-talent/node_modules/@urql/core/dist/urql-core-chunk").AnyVariables>' is not assignable to type 'import("/home/diomedes/Projects/gc-digital-talent/packages/client/node_modules/@urql/core/dist/urql-core-chunk").Operation<any, import("/home/diomedes/Projects/gc-digital-talent/packages/client/node_modules/@urql/core/dist/urql-core-chunk").AnyVariables>'.
@gc-digital-talent/web:build:             The types of 'context._instance' are incompatible between these types.
@gc-digital-talent/web:build:               Type 'import("/home/diomedes/Projects/gc-digital-talent/node_modules/@urql/core/dist/urql-core-chunk").OperationInstance | undefined' is not assignable to type 'import("/home/diomedes/Projects/gc-digital-talent/packages/client/node_modules/@urql/core/dist/urql-core-chunk").OperationInstance | undefined'.
@gc-digital-talent/web:build:                 Type 'OperationInstance' is not assignable to type 'OperationInstance | undefined'.
@gc-digital-talent/web:build:                   Type 'import("/home/diomedes/Projects/gc-digital-talent/node_modules/@urql/core/dist/urql-core-chunk").OperationInstance' is not assignable to type 'import("/home/diomedes/Projects/gc-digital-talent/packages/client/node_modules/@urql/core/dist/urql-core-chunk").OperationInstance'.
@gc-digital-talent/web:build:                     Type 'OperationInstance' is not assignable to type '{ readonly _opaque: unique symbol; }'.
@gc-digital-talent/web:build:                       Types of property '_opaque' are incompatible.
@gc-digital-talent/web:build:                         Type 'typeof _opaque' is not assignable to type 'typeof _opaque'. Two different types with this name exist, but they are unrelated.
@gc-digital-talent/web:build: 
@gc-digital-talent/web:build: ERROR in /home/diomedes/Projects/gc-digital-talent/packages/client/src/components/ClientProvider/ClientProvider.tsx
@gc-digital-talent/web:build: 142:10-40
@gc-digital-talent/web:build: [tsl] ERROR in /home/diomedes/Projects/gc-digital-talent/packages/client/src/components/ClientProvider/ClientProvider.tsx(142,11)
@gc-digital-talent/web:build:       TS2322: Type 'import("/home/diomedes/Projects/gc-digital-talent/packages/client/node_modules/@urql/core/dist/urql-core-chunk").Exchange' is not assignable to type 'import("/home/diomedes/Projects/gc-digital-talent/node_modules/@urql/core/dist/urql-core-chunk").Exchange'.
```

</details>

**Comment by esizer** [comment]
The PR is ready to go now, I was able to get Cypress working. However, the issue now is that Snyk does not support `pnpm` so idk how bad we really want this 😲

**Comment by petertgiles** [comment]
> The PR is ready to go now, I was able to get Cypress working. However, the issue now is that Snyk does not support `pnpm` so idk how bad we really want this 😲

I'm skeptical of how much value Snyk is giving us over regular GH security alerts.

**Comment by esizer** [comment]
> I'm skeptical of how much value Snyk is giving us over regular GH security alerts.

I was mulling the same thing over earlier today. Either we are really good at not introducing security issues or CodeQL and dependabot are doing the heavy lifting because I only ever see Snyk alerts for `tc-report`

**Comment by tristan-orourke** [comment]
Team decision: let's turn off Snyk and continue this ticket

**Comment by esizer** [comment]
More updates! 😆 So, I merged main in to put my PR iup for review however, `pnpm` is fairly strict on imports which means the changes made in the new duplicate string PR broke it since it needs to import circularly from `apps/web`.

There was some discussion on that PR about making things smoother by [using a single source of truth for lang files](https://github.com/GCTC-NTGC/gc-digital-talent/pull/9678#issuecomment-1984427113) to no longer need to do this.

I think I could get this working easily so created a ticket for it, just need to know if that is something we want to move on?

 - https://github.com/GCTC-NTGC/gc-digital-talent/issues/9702
