### ISSUE TITLE
♻️ Replace `react-helmet` with `react-helmet-async`

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#5346]
## ♻️ Debt/Refactor

We should look into replacing `react-helmet` with `react-helmet-async`.

REF: [The Future of Meta Tag Management...](https://open.nytimes.com/the-future-of-meta-tag-management-for-modern-react-development-ec26a7dc9183#:~:text=React%20Helmet%20is%20no%20longer%20being%20actively%2Dmaintained%20by%20the%20NFL.%20There%20have%20been%20no%20commits%20to%20the%20repo%20in%20months.%20This%20issue%20has%20been%20logged%20in%20their%20tracker%20since%20last%20year.%20All%20of%20these%20things%20being%20true%2C%20I%20decided%20to%20fork%20the%20repo%20and%20solve%20this%20problem.)

## 🕵️ Details

It seems as though `react-helmet` is not actively maintained and has been forked and improved with `react-helmet-async`. This should be a simple update with just adding the required provider and updating our imports.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] Removed `react-helmet` from `package.json` and `package-lock.json`
- [ ] `react-helmet-async` installed
- [ ] Imports have been updated
- [ ] Meta tags are still present and working

**Comment by vd1992** [comment]
this would ideally solve this warning

![image](https://user-images.githubusercontent.com/40485260/212751012-ed58ec85-ccda-4535-b546-057264ff84e9.png)

**Comment by esizer** [comment]
Looks like `react-helmet-async` is our best bet. The only other maintained library I could find was `react-head` which could be great but does not seem very popular.

REF: https://npmtrends.com/react-head-vs-react-helmet-vs-react-helmet-async

**Comment by vd1992** [comment]
further reading for `react-helmet` and `react-helmet-async` matters in the body of this PR
https://github.com/GCTC-NTGC/gc-digital-talent/pull/5345
