### ISSUE TITLE
♻️ Allow webpack to process images (using imports instead of "public" dir)

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#5356]
## ♻️ Debt/Refactor

Allow webpack to process images (using imports instead of "public" dir) 

 @patcon - Could you please fill out this stub?

## 🕵️ Details

Should be as easy as using [webpack asset management](https://webpack.js.org/guides/asset-management/#loading-images) since we are on v5. The more time consuming part would be replacing all of our imageUrl usage with import statements.

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] Get rid of image helper and use import instead for all images in the app 
- [ ] All images in the app loads properly without any issues

**Comment by esizer** [comment]
Should be as easy as using [webpack asset management](https://webpack.js.org/guides/asset-management/#loading-images) since we are on v5. The more time consuming part would be replacing all of our `imageUrl` usage with `import` statements.
