### ISSUE TITLE
Secure Network Error Page

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#5362]
We've asked IMTD for a more informative error message when trying to access the admin site from off-network devices.  They can either display a static page that we provide or they can redirect to a page for us.  We've decided we want the redirect so we have more control over it.  So we need to provide a static error page for ourselves now.

Design: ???

Copy: ???

URL: `talent.canada.ca/external-network-error `

Acceptance:
- [ ] Static page exists
- [ ] Static page can be routed to
- [ ] IMTD has been requested to setup the error redirect

**Comment by gobyrne** [comment]
@petertgiles I suggested we do an error page on our site so that we have more control. While I like the idea of us having this control, I could definitely be convinced. So feel free to advocate for the blob storage if there's good reasons for it.

**Comment by petertgiles** [comment]
I still think a small blob served directly from the f5 is the best way to start.  A beautiful page with themed gradients and a cute SVG illustration would be nice but will probably take months get into a design sprint and then a dev sprint.

I think this would be a fine way to get something up quick:
```
<html>
This page can only be accessed on the secure network. | Cette page n'est accessible que sur le réseau sécurisé.
</html>
```
