### ISSUE TITLE
✨ "Download All" in Tables

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#5364]
## ✨ Feature

Currently, DCM can only download selected items on a table, this limitation makes it hard when they wish to download all items on a table and said table expands across multiple pages.

DCM requires an easy way to download the entire table with all items on a table across ALL the pages.

## 🕵️ Details

We would like the download CSV and Download Profiles to have 2 states

1. Instead of having a disabled button, when no items have been selected the download button should read "Download entire table as CSV" and "Download entire table as PDF" and it should extract everything on the table regardless of the page.
2. As soon as 1 or more items are selected, the download button behavior changes to what we currently have and read "Download selected as CSV" and "Download selected profiles".

## 🎨 Design File

Include a link to the design file (if it exists).

## 📸 Screenshot

![image](https://user-images.githubusercontent.com/16977254/212988934-d7ac5612-3c8a-4b07-b985-9fa908d9581c.png)

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Criteria 1
- [ ] Criteria 2

**Comment by petertgiles** [comment]
Could we explore this a little?  Giving one-click access to download an entire unbound dataset seems unnecessarily risky.  What's the use-case here?  Perhaps we could meet the need by increasing the maximum page size to 100 rows, or even 500?  The reason we switched to api-driven tables was because the datasets (we hope!) will get big enough that they can't be reasonably downloaded into a browser.

**Comment by Jerryescandon** [comment]
@gobyrne said: "I think expanding to 500 rows is a reasonable fix for now"

@Jerryescandon: "I agree that it seems risky, but I would still like to allow this functionality at some point in the future, data analysis is a viable use case. But it might be better placed behind a dropdown menu and a modal for additional precautions, e.g. 'Hey youre about to download a table with 1,458 items, this can take a couple of minutes, do you wanna continue?'"

**Comment by petertgiles** [comment]
Sounds good, thanks!   Yeah, I agree that data analytics needs to happen at some point.

**Comment by petertgiles** [comment]
Created issue  #5366
