### ISSUE TITLE
Requests on admin match locations based on the intersection instead of the union

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#5365]
## 🐛 Bug

When viewing requests on admin portal, adding more locations on the filter lowers the number of matching candidates.

## 🦋 Expected Behaviour

Adding more locations on the filters of request page should only ever match you to more candidates. 

## 🕵️ Details

This is actually working properly on the search page however.

## 📋 Steps to Reproduce

1. Open a request in admin
2. Start adding locations filters
3. Observe that the number of matching people lowers as you add more locations

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Filter dialog location field filters based on the union of the list of locations (OR searching)

**Comment by vd1992** [comment]
I think the issue stems from something else
Upon opening a request, I noticed that the filters due not match the request. 
http://recordit.co/T9JC0JHe2W

In that case, the locations Atlantic, BC, and NCR were present in the request data but not in the filter. 
Adding another location like say Quebec would then drop the results count as you go from no locations -> one location

on the search page you get only 10 candidates so there should be no pagination in the request table

![image](https://user-images.githubusercontent.com/40485260/213015001-f16fe062-71c8-4868-baee-2ba850a81c5e.png)

and the corresponding request

![image](https://user-images.githubusercontent.com/40485260/213015348-4effaa02-7d4b-4040-b20b-722434227a33.png)

**Comment by petertgiles** [comment]
Jamie has been asked to try to reproduce this on request and report back to Tristan.  Standing by for results.

**Comment by petertgiles** [comment]
Bug no longer happens on latest version of prod.
