### ISSUE TITLE
⌨  Sign in and Sign up instead of Login and Register (to match GCKey)

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#5367]
## Insight/Issue:
Inconsistent terms for account creation between GC Digital Talent and GC Key (“register” vs “Sign up”). Also should change Login to sign in to match GC Key. 
### Location:
All GC Digital Talent pages
### Category:
Service design/Copy Issue 
## Reproduction info:

1. Access the Home page with a screen reader (narrator/NVDA)and listen as you go through. 
2. Activate the "Register" button/link
3. Activate "Continue to GC Key and Register" link
4. Find where to register on GC Key using the available instructions.

### Fable Video Clip:
[Register on GC Digital Talent vs sign up on GC Key.](https://app.makeitfable.com/clip/63c32621702a95001a7ca297)
## Expected Behaviour:
Consistent terms for all users in English and French. Consistent terms for all users in English and French. En: Sign-in /Sign up Fr: Se connecter/S’enregistrer
### Notes:
Register links appears in the header of all pages across the platform. However,  when users are ushered to the GC Key portal, they are asked to sign up for a GC Key. Though register is clearer, it adds confusion for screen reader users once they arrive on the GC Key Welcome page and are directed to a sign in component and then must tab through to find a way to “sign up” for a GC Key account.
### Potential WCAG Considerations (if any):
1.3.1 Info and Relationships, 1.3.2 Meaningful Sequence
### Acceptance Criteria: 

- "Log in" is changed to "Sign in" everywhere on the platform
- "Register" is changed to "Sign up" everywhere on the platform
- "Connexion" is changed to "Se connecter" everywhere on the platform
- Change "S'inscrire" to "S'enregistrer" everywhere on the platform
- no URLs to be changed

**Comment by RM-1978** [comment]
@substrae totally happy to chat about these copy recos.

**Comment by substrae** [comment]
I don't have a strong preference here, let's go with what makes it easier for folks.

**Comment by RM-1978** [comment]
Right on Sounds good :)

**Comment by petertgiles** [comment]
Team unsure about this.  Let's review this with Gray.
