### ISSUE TITLE
🐛 Table columns checkboxes erratic behaviour

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#5371]
## 🐛 Bug

When I try to check all the boxes in the Table Columns modal on the Users table on the Admin site it unchecks some boxes when I attempt to check the last box on the list.

In addition, the toggle all seems to be broken, it might be related to this or be something else 🤷 

## 🦋 Expected Behaviour

It should allow me to check all boxes without unchecking anything.

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Windows (TBS tablet)
- **Browser**: Chrome
- UAT / Release 2.3.0

## 📸 Screenshot

![image](https://user-images.githubusercontent.com/16977254/213014562-f872eb76-9148-4c49-9765-a1a6d5532f25.png)

## ✅ Acceptance Criteria

- [ ] User can select all boxes
- [ ] User can unselect all boxes
- [ ] User can select some boxes
- [ ] User can toggle all boxes with the _Toggle all_ box
- [ ] Table state is preserved

**Comment by esizer** [comment]
## 🔍 Location

This is likely occurring here and only on the API Managed Table.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/90ab303980a420d78ace0505f509067665349151/frontend/admin/src/js/components/apiManagedTable/useTableState.ts#L41-L57

## ✅ Working?

The code for handling this on the client table seems to be working.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/90ab303980a420d78ace0505f509067665349151/frontend/admin/src/js/components/Table/Table.tsx#L216-L223

**Comment by tristan-orourke** [comment]
It seems like the problem is specific to the Users table. 🤔

**Comment by esizer** [comment]
> It seems like the problem is specific to the Users table. 🤔

I'm guessing it has to do with the `defaultState.hiddenColumnIds` then. This is specific to the API tables (UserTable, PoolCandidateTable) but `UserTable` is the only one that hides columns by default.
