### ISSUE TITLE
📐 Clean-up "Pool status" section and options in User profiles (Admin view)

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#5373]
# ⚙️ Summary

### [Visit the Figma file]()

As we increase the amount of actions that can be taken to edit the relationship between a user and a pool, I think its worth to revisit how we approach this table, and its many modals. 

For example, can we consolidate all actions into one "Edit" button/link instead that includes both "status" and "expiry date" into a single modal? do we foresee other actions? how does this section fit into this page? Should we keep a log of changes?

Overall we should look at cleaning this up.

## Screenshots

![image](https://user-images.githubusercontent.com/16977254/213019450-30ed3843-2916-46f6-9c2c-66cc1f9a6c6c.png)

![image](https://user-images.githubusercontent.com/16977254/213019487-20fee74f-0bf7-40ad-b543-6be467e5c045.png)

![image](https://user-images.githubusercontent.com/16977254/213019527-83db2b48-1107-4a3e-8e02-b322d2d93d5d.png)

![image](https://user-images.githubusercontent.com/16977254/213019556-dd95066a-4d7c-4c0b-9530-f2d4c68c81f4.png)

## 💾 Files and resources

- [FILE]

## ✅ Design checklist

- [ ] Component library elements have been used where appropriate
- [ ] Component library elements have been updated where changes where required
- [ ] Newly added interface elements have been added to the component library for reuse
- [ ] Newly added interface elements have been added to Github Discussions using the component issue template
- [ ] The interface is responsive or provides responsive context
- [ ] The interface provides both light and dark mode designs
- [ ] Complex interactions have been prototypes in a way that showcases every step in the flow
- [ ] Empty/null states have been accounted for
- [ ] A [content spreadsheet](https://1drv.ms/x/s!Ajx0PiLIqEzSgclOERYCPtg3t9dKyQ?e=BBFKF1) has been created and copywriting has been assigned
- [ ] The design has been reviewed by at least one other team member
- [ ] The design has been presented to the design team
- [ ] The design has gone through at least one round of usability testing
- [ ] The design has gone through at least one round of accessibility testing
- [ ] The design has been approved by stakeholders

## ✅ Accessibility checklist

**Please refer to [the comprehensive list](https://www.figma.com/file/rRMvm5nq4AMet29PW7bN2p/A11y-annotations?node-id=0%3A1) for more details.**

- [ ] Links have meaningful label text
- [ ] Navigation matches previously established patterns
- [ ] Headings are identified using annotations and follow a logical hierarchy
- [ ] Layout is linear and consistent with established patterns
- [ ] New interactive elements have unique focus states that match the established pattern
- [ ] Tab order has been identified using annotations
- [ ] Relevant images and icons have appropriate `alt` text
- [ ] Use of color meets AA WCAG contrast requirements
- [ ] States or information are not identified by color alone
- [ ] New interactive elements have appropriately sized touch targets on touch devices

## 📸 Screenshot

[SCREENSHOT]

# ✅ Requirements

- [ ] [REQUIREMENT]

## 🛠️ [REQUIREMENT NAME]

[REQUIREMENT DESCRIPTION]

[REQUIREMENT SCREENSHOT]

### [REQUIREMENT NAME]

[REQUIREMENT DESCRIPTION]

[REQUIREMENT SCREENSHOT]

# 🤔 Outstanding concerns

- [CONCERN]

# 📝 Related issues

**Please link all design and development sub-tasks related to this issue here for tracking purposes.**

- [ISSUE #]

**Comment by mnigh** [comment]
> # ⚙️ Summary
> ### Visit the Figma file
> As we increase the amount of actions that can be taken to edit the relationship between a user and a pool, I think its worth to revisit how we approach this table, and its many modals.
> 
> For example, can we consolidate all actions into one "Edit" button/link instead that includes both "status" and "expiry date" into a single modal? do we foresee other actions? how does this section fit into this page? Should we keep a log of changes?
> 
> Overall we should look at cleaning this up.

@Jerryescandon is this issue still relevant or can this issue be closed?

**Comment by Jerryescandon** [comment]
Stale issue, close it.
