### ISSUE TITLE
Create a profile should go to the login-info page first

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#5377]
## 🐛 Bug

The "Create a profile" link on the "Browse jobs" page takes the user straight to GCKey without any warning. This is super confusing if the user has never logged into our platform before, because it's essentially taking them straight to another website.

## 🦋 Expected Behaviour

The link should take you to the talent platform's login page.

## 📋 Steps to Reproduce

1. Go to [Browse jobs](https://talent.canada.ca/en/browse/pools)
2. Click on "Create a profile"
3. Witness the confusion

## 📸 Screenshot

![image](https://user-images.githubusercontent.com/6960386/213055998-1d1fbce0-6cc2-4aa8-a082-e3176493f0e8.png)

## 🙋‍♀️ Proposed Solution

Intercept the routing by bringing them to [our login page](https://talent.canada.ca/en/login-info).

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] The "Create a profile" link takes the user to the login-info page
- [ ] Logging into GCKey properly redirects them to where they were going

**Comment by brindasasi** [comment]
[Open Requirement in TestQuality](https://web.testquality.com/site/brinda.sasikumar/project/15300?requirementId=15222)

**Comment by brindasasi** [comment]
@substrae Apply to this recruitment also does the same behaviour. Should we fix it as well ? 
![Screen Shot 2023-01-26 at 4 51 33 PM](https://user-images.githubusercontent.com/89482910/214959681-105bcdeb-bb18-4df0-8251-5ee2eb0dc01c.png)
