### ISSUE TITLE
🐜 Accessibility Bug: Error Identification on Profile Forms

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/gc-digital-talent#5385]
## ❌ Current behaviour (issue)
Difficult to identify error in the form: When there is an error in the form, I am not directed to the specific error, notified of the exact error or told how to fix the error.
### Category: 
Accessibility Bug
## AT configuration: 
- VoiceOver, MacOS, Safari
## Reproduction info: 
1. Create a telephone # error on the About me Form.
2. Try to save and go back.
3. Activate the error link in the block
4. Find the focus point.
## ✔ Expected behaviour (fix)
When there is an error in the form, the screen reader user is directed to the specific input field with the error, or told how to fix the error.
### Screen Captures
![#1234 Screen Capture 1.JPG](https://images.zenhubusercontent.com/625076b8f67c446dd188ffe5/e1d45026-3acd-449f-8998-aadceb3769d9)

![#1234 Screen Capture 2.JPG](https://images.zenhubusercontent.com/625076b8f67c446dd188ffe5/9656d534-816e-4d26-a804-1c42906b6896)
### Acceptance Criteria
A set of assumptions which, when tested, verify that the accessibility requirement was met.
- [ ] Text preceding the error link tells the user how to fix the error in question (e.g., expected input format), and/or
- [ ] Activating the error link takes you to the exact input field to remedy the error.

**Comment by petertgiles** [comment]
Same as #5416 on different page.  Probably same fix for both.

**Comment by petertgiles** [comment]
Closing as duplicate.  Reopen if there's something unique to this one.
