### ISSUE TITLE
♻️ Profile page url includes user-id, but any current logged-in user is shown

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#5413]
## ♻️ Debt/Refactor

When the user goes to their own profile page, the url includes the User's id. However, the implementation of the profile page uses the `getMe` query, meaning the id in the url is entirely irrelevant. If a user logs in and goes to a url representing someone else's profile, they will still see their own profile.

## 🙋‍♀️ Proposed Solution

To make the behaviour of this page more consistent, we should either:
1. Use the `user(id)` query instead of `getMe`, and make use of the id in the url,
2. or change the url so it doesn't show an irrelevant and misleading id.

Solution 1 Advantages:
    - Don't need to change any routing
    - Purely a refactor, as expected behaviour does not change
    - A user with admin priveliges could visit other user profiles using currently set routes
Cons:
    - url is longer and more complicated, impractical to remember or enter by hand
    - almost all users will not have permissions necessary to view other profiles anyway
    - very few users, if any, have permissions necessary to view someone else's profile, and if they do we have a different page for that on the admin dashboard. So this could be maintaining unused & wasted functionality.

Solution 2 Advantages:
    - profile page url becomes shorter and simpler. It would now be easy to share the link that sends a user to their own profile, or for a user to go directly to their profile by entering the url by hand.
    - continuing to use `getMe` query and not having to pull id from id from url is simpler in some ways
Cons:
    - requires a tweak to routing
    - if we're being really thorough, we'll need to add permanent redirects for `users/*/profile` to the new url in our nginx config

**Tristan: Personally, I'm leaning toward solution 2 right now.**

## 🌎 Localization

Required if changing the url.

## ✅ Acceptance Criteria

- [ ] Change the URLs as in the list in Tristan's comment
- [ ] Create redirects for any URLs that don't currently have IDs in them (/applicant and /applicant/skills/showcase)
- [ ] Work with @petertgiles to make sure the notification emails still point to the right place

**Comment by petertgiles** [comment]
I think the reason we ended up with solution 1 originally was a desire to move away from "magic" URLs that show something different depending on who you are.

**Comment by tristan-orourke** [comment]
> I think the reason we ended up with solution 1 originally was a desire to move away from "magic" URLs that show something different depending on who you are.

Hm, yeah. But if the purpose of a page is dealing with your own account, is there anything wrong with account-specific content?

**Comment by vd1992** [comment]
Do we wish to proceed forward on this, I do agree with Tristan that ID strings in the URL that don't do anything can be confusing. It makes it trickier to share links and is misleading as you aren't viewing the profile for a given ID, so someone may erroneously  think they can share a profile via URL

**Comment by mnigh** [comment]
preliminary results:

- **?** in favour solution 1
- **4** in favour solution 2

@GCTC-NTGC/developers anyone strongly opposed to solution 2 or should be removed the **blocked: question** label and forge ahead?

**Comment by esizer** [comment]
I'm wondering if it is time to look into this. We have restructured the applicant facing side to the point where the URLs no longer match the structure and we only have two pages that use the `userId` in the URL anymore. I'm generally not a fan of changing URLs but I think this one makes sense.

In the same idea, I feel like the `/profile-and-applications` segment is superfluous. It kind of acts as the applicant homepage maybe we just use `/applicant` or `/profile` without the addition of `/profile-and-applications` instead?

![Screenshot 2024-03-05 085655](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/8911064d-16f7-4d4a-8d9e-67d13808eec2)
![Screenshot 2024-03-05 090401](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/b16ff601-c902-4905-be5f-e174c8c77394)

**Comment by tristan-orourke** [comment]
Agree 💯 

I think the changes we're looking at would be:
- /applicant/profile-and-applications -> /applicant
- /users/:userId/personal-information -> /applicant/personal-information
- /users/:userId/personal-information/career-timeline -> /applicant/career-timeline
- /users/:userId/personal-information/career-timeline/create -> /applicant/career-timeline/create
- /users/:userId/personal-information/career-timeline/:experienceId/edit -> /applicant/career-timeline/:experienceId/edit
- /applicant/profile-and-applications/skills -> /applicant/skills
- /applicant/profile-and-applications/skills/showcase -> /applicant/skills/showcase
