### ISSUE TITLE
Redirect from legacy search URL

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#5418]
### Description
Before we implemented our site-map the link to the old search page was provided to the PSC. They are using it on their site for the Digital Careers pools: **http://extranet.psc-cfp.gc.ca/sib-dgsi/pools/index-fra.html**. Unfortunately that now takes them to a 404. This was flagged a while back (because people actually do use it) but I thought it would fix on their end. Let's just do it on our end though so I don't have to keep worrying about it.

### Acceptance Criteria

- [ ] https://talent.canada.ca/en/talent/search permanent redirect to https://talent.canada.ca/en/search
- [ ] https://talent.canada.ca/fr/talent/search permanent redirect to https://talent.canada.ca/fr/search
- [ ] Cypress test to ensure these two continue to work

**Comment by petertgiles** [comment]
We have a similar redirect in our nginx routing already.
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/40c2b18b-9910-4ce0-bc5a-cfd6a147f2d5)
