### ISSUE TITLE
MultiSelectField lacks padding/spacing below it

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#5429]
> MultiSelectField lacks padding/spacing below it as can be seen here in the diff

Not part of the scope but, maybe we should create a ticket to add baseline margin on this component to bring it inline with our other form inputs?

https://github.com/GCTC-NTGC/gc-digital-talent/blob/fca285a93efbfc7dba2fc47c841c09693af27c24/frontend/common/src/components/form/Input/Input.tsx#L66

_Originally posted by @esizer in https://github.com/GCTC-NTGC/gc-digital-talent/issues/5425#issuecomment-1399035565_

add spacing/margins around the component so it functions the same as the other inputs in spacing
depending on how this spacing is added it most likely will break formatting of components elsewhere, must adjust other components as a result

## Acceptance Criteria

- [ ] update MultiSelectField to have the same baseline margins as other input components
- [ ] check all components using the input and ensure they are not broken by the formatting change
- [ ] other components, like say fancy filter, must be updated if broken by the input's update

**Comment by esizer** [comment]
We have removed built in spacing from all components in https://github.com/GCTC-NTGC/gc-digital-talent/pull/6895
