### ISSUE TITLE
✨ Assign new Roles to existing Users

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#5437]
## ✨ Feature

All existing users need the Base User and Applicant roles. All existing Admin users need the System Admin, Request Responder and Pool Operator (DCM) roles. When any new user is created, they must be assigned the Base User and Applicant roles.

## 🕵️ Details

When the Pool Operator role is attached to a user, it must be [assigned in the context of a team](https://laratrust.santigarcor.me/docs/7.x/usage/teams.html#roles-assignment-removal) (the DCM team, for existing users).

## 🙋‍♀️ Proposed Implementation

Write a command that syncronizes uses roles based on LegacyRoles. Any users with the Applicant LegacyRole get the new ApplicantRole, any users with the Admin LegacyRole get the new System Admin and Request Responder and Pool Operator ('digital-community-management') roles. Any users without the Admin LegacyRole should lose the system_admin, pool_operator and request_responder roles if they have them.

This command should be safe to run multiple times in production, as user LegacyRoles may change.

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] All existing users have the Base User and Applicant roles. 
- [ ] All existing Admin users need the System Admim, Request Responder, and Pool Operator (DCM) roles
- [ ] The Pool Operator role is only ever attached along with a Team
- [ ] The synchronize command is safe to run periodically in production.
- [ ] Users' LegacyRoles are not changed.

out of scope 

- [ ] When any new user is created, they will be assigned the Base User and Applicant roles.

**Comment by esizer** [comment]
## 🚀 Deployment Instructions

1. Run seeders
  - `./artisan db:seed --class=TeamSeeder`
  - `./artisan db:seed --class=RolePermissionSeeder`
2. Run command
  - `./artisan role:sync`
