### ISSUE TITLE
API - Add a way to query for all Search Requests pertinent to logged-in user

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#544]
# Description
Add a way to query for all PoolCandidateSearchRequests which apply to Pools owned by the current user.

I recommend using the [viewer pattern](https://lighthouse-php.com/master/security/authorization.html#utilize-the-viewer-pattern).

**Comment by gggrant** [comment]
Not relevant until we have roles to manage specific pools.
