### ISSUE TITLE
✨Remove old User Roles

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#5440]
## ✨ Feature

Remove the LegacyRole enum and any reference to it.

## 🕵️ Details

After replacing the LegacyRole enum with our new and improved Roles and Permissions in the backend policies (#5438) and in frontend checks (#5439) we should be able to remove the enum Role entirely, and any references to it.

## 🎨 Design File

Include a link to the design file (if it exists).

## 📸 Screenshot

Add a screenshot of the new feature (if possible).

## 🙋‍♀️ Proposed Implementation

Delete the enum.
Migration to remove the User.roles column.
Edits to User.php, and maybe seeders/tests?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] The LegacyRole enum has been removed from schema
- [ ] The user.legacy_roles column has been removed from database
- [ ] There are no references in code to either of these.
- [ ] User seeder/factories assign new Roles instead of old Admin role

## :stop_sign: Blockers

List any issues which must be completed before this one.

```[tasklist]
### Blockers
- [ ] #5438 
- [ ] #5439 
- [ ] #5441 
```

**Comment by esizer** [comment]
Before we start this, can we confirm there are no active users that do not have new roles? I doubt it but, we rely on the enum for `RoleSync` command. 

Just wondering if we should also remove that command or, update it to no longer rely on the enum?

**Comment by vd1992** [comment]
`RoleSync` was run quite a while ago, so (hopefully) it should be good to be removed?

https://github.com/GCTC-NTGC/gc-digital-talent/releases/tag/v2.7.2
