### ISSUE TITLE
Explore Backend Telemetry/Analysis

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#5442]
## :question: Spike questions:

- [ ] How can we measure which requests take a lot of time in our API?
- [ ] How can we measure which requests occur with high frequency?

Possible approaches:
- Azure AppInsights
- Nginx logging
- Laravel logging
- Postgresql statistics

Timebox: 2 days

**Comment by petertgiles** [comment]
# Postgresql 
- https://pgdash.io/blog/slow-queries-postgres.html
- [pg_stat_statements](https://www.postgresql.org/docs/current/pgstatstatements.html)is available but not active on our server
  - Would require a configuration change and reload on server (IMTD help)
  - Very low-level analysis would be required.  Maybe we would want to try this out locally first.
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/d78a4eed-7db8-488d-b532-f57c5a22a439)
- We can query the `pg_stat_activity` view right now but only shows current connections.  Limited usefulness.

# Nginx
- https://www.nginx.com/blog/using-nginx-logging-for-application-performance-monitoring/#Using-the-NGINX-Built%E2%80%91In-Timing-Variables
  - You can log timings at Nginx but without the query body I don't know how useful it will be.  Unlike REST, we really need the Graphql request bodies to be useful.
  - F5 has a monitoring tool call Amplify that can monitor up to 5 servers for free.  I know IMTD uses F5 load balancers upstream - maybe we're licensed for this already?
  https://www.nginx.com/blog/monitoring-nginx/

# Laravel
- https://laravel.io/articles/how-to-find-the-slowest-query-in-your-application
  - This looks like a simple, useful way to log slow queries.  Getting logging data out of Laravel is pretty easy.
- https://github.com/ilzrv/laravel-slow-query-detector
  - Similar idea rolled into an extension.

# Azure AppInsights
- I found a performance tool but it seems to have limited usefulness for us.  On one hand, this is the only client-side tool we have.  On the other hand it seems to not work well with an SPA as most paths show a 0.00 ms time duration.  Also, the the browser URL and page load time is less interesting to us than the GrqphQL queries and timings.
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/52a0be7e-59e6-4c69-bf16-4e2af622aa82)
- The hitcount per path statistic is very interesting though.
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/678296d7-11fc-4a20-8c17-712f9eaf7679)

# Conclusion
- I'm going to look into some simple Laravel logging and ask IMTD about Amplify.

**Comment by petertgiles** [comment]
I was able to install the Nginx Amplify agent in my local Ngnix Docker container.  I had to run `apt-get update --allow-releaseinfo-change` which felt a little "cowboy" for a production server but otherwise it was quick and easy.
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/ee9521de-dcbf-45e0-bdd9-46d738ae585d)
Looks like I have a bit more configuration to do to get anything useful out of it.  :smile:

**Comment by petertgiles** [comment]
I tried adding
```php
        DB::listen(function ($query) {
            Log::info(print_r([
                'sql' => $query->sql,
                'bindings' => $query->bindings,
                'time' => $query->time
            ], true));
        });
```
and then ran our Cypress suite for some quick-and-dirty analysis.

Our slowest query was a 14s ` select count(*) as aggregate from "users" where...` query with 85 (!!!) bind parameters.  Second place at 13s was a simple `select * from "users" where "sub" = ? and "users"."deleted_at" is null limit 1` query.  I'm not sure why that one was slow.  Maybe we should be adding indexes to the `deleted_at` columns?

I could see us writing queries above some limit to a database in production for analysis.  Maybe sqllite or there's something we could spin up in Azure.  I'm not sure how to log the Graphql query that produced the SQL though, which is pretty important.

**Comment by petertgiles** [comment]
There's a `whenQueryingForLongerThan` function in Laravel, too.
[getSearchFormDataAcrossAllPools](https://laravel.com/docs/10.x/database#monitoring-cumulative-query-time)

An alternative approach that would capture the GrqphQL queries is to use a middleware in Lighthouse, like the AuditQueryMiddleware:
```php
    public function handle(Request $request, Closure $next)
    {
        $start = hrtime(true);
        $next($request);
        $end = hrtime(true);

        $this->logger->info(
            'Slow query',
            [
                'request' => $request->json()->all(),
                'elapsed_time' => ($end - $start) / 1000000000
            ]

        );
    }
```
This doesn't capture what's happening Upstream in Laravel or Ngnix but does capture the exact GraphQL query including the OperationName which should make it much easier to identify the context of a slow request.

**Comment by petertgiles** [comment]
While reading through Laravel optimization sites I noticed some recommendations to removing unused middleware and service providers.  Since we only use a small fraction of what Laravel is usually used for, there is probably some room for improvement there for us.
https://geekflare.com/laravel-optimization/

**Comment by petertgiles** [comment]
Some comments from IMTD about monitoring and Amplify:
- seems like Ampify is free
- they use PRTG Network Monitoring themselves
- Open Canada uses Prometheus with Graphana already

**Comment by brindasasi** [comment]
Agree about AppInsights.. we have the analytics for client side only. Server side measurement would be great.

**Comment by brindasasi** [comment]
> There's a `whenQueryingForLongerThan` function in Laravel, too. [monitoring-cumulative-query-time](https://laravel.com/docs/10.x/database#monitoring-cumulative-query-time)
> 
> An alternative approach that would capture the GrqphQL queries is to use a middleware in Lighthouse, like the AuditQueryMiddleware:
> 
> ```
>     public function handle(Request $request, Closure $next)
>     {
>         $start = hrtime(true);
>         $next($request);
>         $end = hrtime(true);
> 
>         $this->logger->info(
>             'Slow query',
>             [
>                 'request' => $request->json()->all(),
>                 'elapsed_time' => ($end - $start) / 1000000000
>             ]
> 
>         );
>     }
> ```
> 
> This doesn't capture what's happening upstream in Laravel or Ngnix but does capture the exact GraphQL query including the OperationName which should make it much easier to identify the context of a slow request.

This can be used for some sort of alert. When this happens its the breaking point and tell us to go look at the query. It solves only partial. 

I like this one and this approach sounds familiar to me. Every query has its timings.
I'm unsure about the drawbacks you mentioned though. 

```
DB::listen(function ($query) {
            Log::info(print_r([
                'sql' => $query->sql,
                'bindings' => $query->bindings,
                'time' => $query->time
            ], true));
        });
```
Does the Amplify give graphql request info as well?

**Comment by petertgiles** [comment]
> Does the Amplify give graphql request info as well?

Not that I've seen, no.  It only reports aggregated metrics like number of errors, number of slow requests, etc...

**Comment by brindasasi** [comment]
I think we could use both Laravel logging and Amplify as they solve diff purposes.

**Comment by petertgiles** [comment]
Set Up Nginx Amplify #6833
Set up Laravel slow query monitoring with request text #6834
