### ISSUE TITLE
✨ (Search page) Hide filters in accordions

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#5457]
## ✨ Feature

We want to remove the importance of certain filters and highlight other filters, to this effect we want to hide some of the filters currently in the manager Search page and put them inside accordions.

## 🕵️ Details

We will be hiding 3 of the current filter options:
- Education requirement
- Employment duration
- Conditions of employment

We are not changing any of the content for the instructional text nor the interaction itself (beyond the accordion show-hide interaction)

Each accordion includes a subline to represent the current selection of each filter.

## 🎨 Design File

[Link to figma file](https://www.figma.com/proto/UsrB15yicgDCLDQmx3snyl/User-Flows?node-id=3513%3A14886&scaling=min-zoom&page-id=3513%3A11410&starting-point-node-id=3537%3A11514)

## 📸 Screenshot

![image](https://user-images.githubusercontent.com/16977254/215585159-679357ca-7d6a-4c1a-bf85-c88476d3371c.png)

![image](https://user-images.githubusercontent.com/16977254/215586129-535a3b71-e977-4846-8ebb-76ed5320f457.png)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] The three filters hidden inside accordions
- [ ] Subline represents current selection of each filter
- [ ] Search behaviour remains unchanged
- [ ] Accordions always start closed regardless of the filter state (when returning whatever is easiest)
- [ ] Use the lightweight style of accordion

**Comment by petertgiles** [comment]
If the user navigates to the page and the filter is already set should the accordion start open?

Is this a new accordion, or a new look that all accordions should have, or a new style for the existing accordion?

Is the underlined title a link to toggle the accordion open and closed?

Does toggling one filter automatically close the other ones?

**Comment by Jerryescandon** [comment]
> If the user navigates to the page and the filter is already set should the accordion start open?
> 
> Is this a new accordion, or a new look that all accordions should have, or a new style for the existing accordion?
> 
> Is the underlined title a link to toggle the accordion open and closed?
> 
> Does toggling one filter automatically close the other ones?

1. No, it can be closed, the subtitle still shows the selection.
2. I think its a new style of the accordion, I stole this from one of @substrae design for the poster, I imagine they will make their way into the current accordion styling eventually
3. I think so, although I imagine the entire area around the title and subtitle and all the way across is clickable as one big rectangular hotspot
4. Nah, let's keep them separate for now.

**Comment by petertgiles** [comment]
> 2\. I think its a new style of the accordion

Do you want to block this work on developing the new accordion style or build it with the existing "skills-style" accordion?

**Comment by Jerryescandon** [comment]
I think we should build it with our current components and then update it later, the whole page should get an update to the new look and feel eventually too.

**Comment by gobyrne** [comment]
We could break this work up and to the component work separately if we need to. I'll still try to put it all in the next sprint though.

**Comment by petertgiles** [comment]
I have #5042 on the board from the Ongoing Recruitment work to theme the accordions.  It could be in scope for that.

**Comment by substrae** [comment]
As @Jerryescandon mentioned, you can leverage the existing expand/collapse we have for now, but eventually, as #5042 and #5522 are implemented, we should be migrating this UI to the simpler-style.

**Comment by Jerryescandon** [comment]
I moved Work Location back out, keeping it as required and visible based on chats with DCMO. I am also closing #5458 based on this.
