### ISSUE TITLE
✨ (Search page) Change "Work Location" filter to "Optional"

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#5458]
## ✨ Feature
Since we are moving towards hiding any non essential filters into accordions as per #5457 We want to make the 'Work Location' filter optional to avoid having any *Required fields behind any accordion.

## 🕵️ Details

- Make the field optional and allow the form to submit with empty work location
- Behaviour remains the same:
   - an empty work location field should return all users regardless of location preferences.
   - any choice of location would be additive, meaning it should give more users the more locations are selected

## 📸 Screenshot

![image](https://user-images.githubusercontent.com/16977254/214387798-681d8fde-167a-4a8a-aec6-5e27af1b6af2.png)

## ✅ Acceptance Criteria

- [ ] Search can be submitted without work location filter filled
- [ ] Search behaviour exactly the same otherwise

**Comment by petertgiles** [comment]
Gray to verify DCM is OK with this change.

**Comment by Jerryescandon** [comment]
DCMO has asked us to keep this as required. I have updated #5457
