### ISSUE TITLE
✨ (Search page) Submit empty requests

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#5459]
## ✨ Feature

DCM can really benefit from knowing what Managers are looking for in their original requests, specially if their original request returns zero available candidates, this information can guide DCM to future pool advertisements. We want to allow some ways of capturing this information by creating a way to allow Managers to submit empty requests.

## 🕵️ Details

We have created several interventions, each one might require it's own ticket, but I will list them all here:

1.  Different state for the sticky box on the right. This box is the first indicator for (visual) users to know whether there are any candidates that match their request. We want to create a state in case the counter reaches 0, that lets managers know they can still submit their request as is for additional help. 

![image](https://user-images.githubusercontent.com/16977254/214390045-1dc41d56-eace-46b4-98be-a5205f54bbe0.png)

2. Change the interaction in the results from a link to a submit button 

### OLD
![image](https://user-images.githubusercontent.com/16977254/214390370-8506a933-320d-4760-a879-dd26f5778b79.png)

### NEW
![image](https://user-images.githubusercontent.com/16977254/214390346-b60ad2ed-f1f8-45c0-b742-24ba5af8118d.png)

3. Empty Request Content: We should let both the manager and DCM know when a request was created empty originally. Since candidates move a lot in and out of pools and their status change all the time, we should capture when a request was originally created as an empty request, regardless wether or not there are matching candidates at the moment its being viewed. To this effect, we want to add a line that gets passed in the request as a string if the request is empty.

![image](https://user-images.githubusercontent.com/16977254/214392335-f28f5bb1-31b3-4ac8-ab04-b15ac430c649.png)

![image](https://user-images.githubusercontent.com/16977254/214392618-3d78bbc4-ec13-4778-a573-f9d0895ee9c8.png)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Different state for the sticky box on the right with zero results
- [ ] Change the interaction in the results at the bottom from a link to a submit button
- [ ] On request page, different empty Request Content
- [ ] Ensure that the admin table and SSR page function OK with empty fields like pool-id on the request

**Comment by petertgiles** [comment]
Right now every request has to be associated with a pool.  What are the side-effects of submitting a request with no pool?
![image](https://user-images.githubusercontent.com/8978655/214595358-ad27aef9-c8d6-45ee-8233-c8ccf5a33bed.png)

**Comment by Jerryescandon** [comment]
Gray suggested we could create a pool and tie empty requests to that pool specifically, I'm not sure what the best way to deal with this would be. Eventually requests will be tied to Teams, so it will be a different problem then. Any ideas?

**Comment by gobyrne** [comment]
The plan is to make requests against teams instead of individual pool in the nearish future.

Not sure how to handle it in the interim. Is it possible just to pick the pool that matches the IT-level + stream? That might actually be the only way we pass along the it-level and stream? If so, it will be important to include it. If not... I'll take whatever solution is the easiest to implement.

**Comment by petertgiles** [comment]
Tristan's thoughts on this: The API should be OK submitting a request without a pool.  Don't attach the request to a dummy pool, just leave empty.

**Comment by esizer** [comment]
This one is deceptively difficult and may take a considerable amount of time. We have tightly coupled the search page to pools in https://github.com/GCTC-NTGC/gc-digital-talent/pull/4864 

So if the results are 0, we can't determine what classifications were selected since we do all of the logic outside of the form context.
