### ISSUE TITLE
🐛 Scroll bar disappears from mobile admin pages when menu is open

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#5460]
## 🐛 Bug

If you are viewing an admin page in a small enough window to count as mobile layout, and open the side menu, the scroll bar disappears.

## 🦋 Expected Behaviour

I assume the scroll bar should still be visible, and the page should be usable while the side menu is open.

## 🕵️ Details

- **Operating System**: Windows
- **Browser**: Seen in Brave and Edge

## 📋 Steps to Reproduce

1. Log in to Admin dashboard
2. Shrink the window so that the side menu is hidden behind a mobile-style drawer button.
3. Open the side menu.
4. See that the scroll bar disappears until the side menu is closed.

## 📸 Screenshot

![Screenshot of Admin page with scroll bar missing](https://images.zenhubusercontent.com/5d9ded8fd25901000101f3f0/32a6f9eb-ad18-4020-9faf-c19b369a1ce9)

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Users can scroll the main content while the side menu is open , even in mobile.

**Comment by esizer** [comment]
This is half right, on the breakpoint in your screenshot it should be visible and working. However, on mobile devices it should work more like a modal and disappear and lock the scroll. 

I think what happened was we updated our breakpoints with hydrogen v2 but never modified the `useSmallScreen` hook to make use of the new breakpoints.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/b68403753030d83c2843d8600bf0b32e69361423/frontend/common/src/components/SideMenu/SideMenu.tsx#L61-L62

https://github.com/GCTC-NTGC/gc-digital-talent/blob/b68403753030d83c2843d8600bf0b32e69361423/frontend/common/src/hooks/useIsSmallScreen.ts#L4-L7

**Comment by esizer** [comment]
Fixed with https://github.com/GCTC-NTGC/gc-digital-talent/issues/7532

**Comment by vd1992** [comment]
Fixed
