### ISSUE TITLE
🧪 Tests - Storybook: some stories regenerate text every Chromatic UI review

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#5465]
## 🧪 Tests

Some stories keep regenerating text each time the Chromatic deployment and UI review runs. 
This is creating noise as these diffs aren't really meaningful. 

## 🕵️ Details

These stories in particular

![image](https://user-images.githubusercontent.com/40485260/214440779-b5afc461-60d3-4684-b04b-3c39fbd16b78.png)

Example of the noise from text regenerating 

![image](https://user-images.githubusercontent.com/40485260/214440904-dd8302bb-b6be-48e8-95c5-4420c37bed99.png)

## 🙋‍♀️ Proposed Solution

Likely some random generation needs to be adjusted to always seed the same value?

## ✅ Acceptance Criteria

- [ ] Storybook UI review no longer generates noise each run

**Comment by mnigh** [comment]
[Delaying](https://www.chromatic.com/docs/delay) the snapshot might be helpful for consistent rendering.

**Comment by mnigh** [comment]
This was my fault in https://github.com/GCTC-NTGC/gc-digital-talent/pull/5180 😞.

## Possible solutions

1. Use static lorem ipsum copy
2. Use static real copy

**Comment by gobyrne** [comment]
Peter suggests using a seeder with Faker instead of returning to static copy.
