### ISSUE TITLE
Can't log out of profile

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#5467]
## 🐛 Bug

Logging out from the profile page redirects back to the log in page.

## 🦋 Expected Behaviour

Should end up at the "You've been logged out" page

## 🕵️ Details

- **Operating System**: Linux - Pop_OS 22.04
- **Browser**: Firefox 108

## 📋 Steps to Reproduce

1. Log in as an applicant
2. Observe the profile page
3. Click the logout button
4. Observe that you have ended up back on the log in page

## 📸 Screenshot

https://images.zenhubusercontent.com/364642496/5c1dd1a8-0cff-4e40-8e0c-0e133e1697e7/simplescreenrecorder_2023_01_25_10_00_33.mp4

## ✅ Acceptance Criteria

- [ ] Logging out should end up at the "logged out" page always

**Comment by esizer** [comment]
I'm uncertain about this, but I cannot reproduce this on the branch for #5528 . This may have been related to the `.env` issues 🤔

**Comment by vd1992** [comment]
cannot replicate this issue either
am successfully redirected to `/en/logged-out` on logout

**Comment by vd1992** [comment]
two people cannot reproduce issue, likely solved as byproduct of another PR
