### ISSUE TITLE
✨ (Search Page) Confirmation page

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#5469]
## ✨ Feature

Search page needs a confirmation page to assure managers that their request was submitted successfully as well as giving them some information useful for troubleshooting.

## 🕵️ Details

Create a confirmation page that follows the successful submission of a request form. 
- Request ID/KEY might be the only thing worth looking into, I'm unsure if we have something we can use for this but is important to give them a unique identifier they can use for troubleshooting.
- the print button will just print this page as pdf. 
- submit a new request takes the user back to an empty search page.

## 🎨 Design File

[Link to figma](https://www.figma.com/proto/UsrB15yicgDCLDQmx3snyl/User-Flows?page-id=3513%3A11410&node-id=3513%3A15087&viewport=133%2C584%2C0.92&scaling=min-zoom&starting-point-node-id=3537%3A11514)

## 📸 Screenshot

![image](https://user-images.githubusercontent.com/16977254/214644773-9aca5955-2a08-48e9-9059-86f57bc47de5.png)

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

- [ ] This is a new page, available at `/search/request/<request-id>`
- [ ] It shows mostly static text, but also the id of the request you just submitted
- [ ] It has a print button that opens the default browser print dialog (no special view, just default print)
- [ ] It has a button that redirects to the empty Search page
- [ ] After requesting a talent search, you are directed to this page
- [ ] If someone navigates here by different method, just show the page normally, don't verify or guard
- [ ] Breadcrumb destinations: homepage \ search page \ this page

**Comment by petertgiles** [comment]
Possible duplicate:  #2762
