### ISSUE TITLE
✨ (Admin) Standardize breadcrumb navigation

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#5472]
## ✨ Feature

We should standardize all breadcrumb locations on the admin side of the platform. We will move them to the top of the page, just under the GoC/Language banner, and ensure that every page has consistently designed breadcrumbs.

## 🕵️ Details

Use a consistent component and placement for breadcrumbs on all Admin pages, and ensure they appear on all pages (except the Login page).

The content of most breadcrumbs will also change, as shown in [this table](https://docs.google.com/spreadsheets/d/1OflNJCN450hS4_ASzjrJs6JwsWa9zsda_udlqQHDBiA/edit#gid=0). 

Page Title | url | Breadcrumbs
--- | --- | ---
Dashboard | /dashboard | Home
Pools | /pools | Home / Pools
Pool Create | /pools/create | Home / Pools / Create new pool
Pool View | /pools/{id} | Home / Pools / {Pool Name}
Pool Edit | /pools/{id}/edit | Home / Pools / {Pool Name} / Edit
Pool Statitistics | /pools/{id}/statistics | Home / Pools / {Pool Name} / Statistics
Pool Candidates | /pools/{id}/pool-candidates | Home / Pools / {Pool Name} / Candidates
Applicant Snapshot | /candidates/{id}/application | Home / Pools / {Pool Name} / Candidates / {Candidate Name}
Users | /users | Home / Users
User View | /users/{id} | Home / Users / {User Name}
User Edit | /users/{id}/edit | Home / Users / {User Name} / Edit
User Profile | /users/{id}/profile | Home / Users / {User Name} / Profile
User Placement | /users/{id}/placement | Home / Users / {User Name} / Placement
Requests | /talent-requests | Home / Requests
Request View | /talent-requests/{id} | Home / Requests / {Manager Position} - {Manager Dept}
Teams | /teams | Home / Teams
Team Create | /teams/create | Home / Teams / Create
Team View | /teams/{id} | Home / Teams / {Team Name}
Team Edit | /teams/{id}/edit | Home / Teams / {Team Name} / Edit
Team Members | /teams/{id}/members | Home / Teams / {Team Name} / Members
Classifications/Departments/Skills/SkillFamilies |  | Home / {Resource}
Classifications/Departments/Skills/SkillFamilies Create |  | Home / {Resource} / Create
Classifications/Departments/Skills/SkillFamilies Edit |  | Home / {Resource} / Edit

## 🎨 Design File

Ignore the Team and Department subtitles in the breadcrumbs of some of the designs.
[Link to the design file (if it exists).](https://www.figma.com/file/UsrB15yicgDCLDQmx3snyl/User-Flows?node-id=0%3A1&t=DYpy306b9RNvAKT4-1)

## 📸 Screenshot

![image](https://user-images.githubusercontent.com/4313717/217629419-1c5b7e9c-aee3-46bb-95c2-dd61fea5ae9c.png)

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Every page on Admin has breadcrumbs which look consistent.

**Comment by petertgiles** [comment]
@Jerryescandon with the recent theming update we have an "admin look" for the standard breadcrumb component.  Do you want to use this for this change?


![Image](https://user-images.githubusercontent.com/8978655/225075816-422b92c9-df49-4336-b33b-b0e7b4f26d5b.png)

**Comment by Jerryescandon** [comment]
Hecks yeah! standardize it ALL to hell! 🔥 🔥 🔥

**Comment by Jerryescandon** [comment]
Although, I moved all breadcrumbs to the bottom, cause they were crouding up the top space a little bit too much, and the internal nav we added has proved to be much more efficient.
 
 Here's an example:
 
![image](https://user-images.githubusercontent.com/16977254/225085069-efd854d8-1d2a-4b43-a5c7-4be4135cce27.png)

**Comment by petertgiles** [comment]
@esizer How do you feel about breadcrumb links like "edit" and "create"?  Do we need to add context like "`edit <hidden>classification</hidden>`" or is it enough that there's only one link called "edit"?


![Image](https://user-images.githubusercontent.com/8978655/225367249-a16aab02-4799-4327-80e6-01713ad800d3.png)

**Comment by esizer** [comment]
> @esizer How do you feel about breadcrumb links like "edit" and "create"? Do we need to add context like "`edit <hidden>classification</hidden>`" or is it enough that there's only one link called "edit"?

Yeah, it would def help to have what you are editing/creating even if hidden to provide more context 👍
