### ISSUE TITLE
⌨ Accessibility Issue:  New Skill Picker -  Ambiguous ARIA label for the clear button in the Skill Search for or select a skill field 

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/gc-digital-talent#5485]
## ❌ Current behaviour (issue)
The ARIA label for the clear button in the **Search for or select a skill** auto populate field tells a screen reader that the user can search for a term or clear the field with the same feature. This same label appears on all three skill picker dialogue boxes.   
### AT Configuration 
JAWS, Windows, Chrome
### How to reproduce
1. Open JAWS in chrome
2. Access the ["Add Skill to Library" chromatic link](https://61e099a1bb1465003a73d3ce-fmsuaevytj.chromatic.com/?path=/story/components-dialog-skilldialog-addaskilltolibrarydialog--default)
3. Activate the **Claim a skill** button 
4. Navigate using the Tab key to the "Search for or select a skill" field 
5. Enter the text  "HTML"  and tap enter 
6. Tab to get out of the field and listen to the ARIA Label as focus moves to the clear button marked with a "X"
 
## ✔ Expected behaviour (fix)
ARIA Label for the clear ("x") button reads "clear your selection"
### Acceptance Criteria
- [ ] ARIA Label for the clear ("x") button reads "clear your selection"

**Comment by esizer** [comment]
Heh, just took a look at this and it could use some work 😓 

We are just appending the label to the clear action so it would sound odd to hear "Reset Search for or select a skill". I think the solution here would be to force dev's to use an explicit message to clear the field.

**Comment by esizer** [comment]
Unsure if this is suitable but, we are about to update this to allow us to supply a contextual clear label with a default of "Clear your selection"

https://github.com/GCTC-NTGC/gc-digital-talent/blob/9a1e577997abee7696e7b5af62fc6786e94c9d5d/packages/forms/src/components/Combobox/Combobox.tsx#L39-L40

![Screenshot 2023-06-24 135854](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/eee30a64-9c5d-41e0-8f7a-811b3f165479)

**Comment by RM-1978** [comment]
Totally @esizer
