### ISSUE TITLE
🐜 Accessibility Bug: Unsaved changes warning & form labels being read together

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/gc-digital-talent#5486]
## ❌ Current behaviour (issue)
Unsaved changes warning are being read out with the subsequent form label in the Skills and experience forms. They seem to read together like one long line of code. 
### AT Configuration
 JAWS, Windows, Chrome
###Fable Video Clip
[Skills and Experience Form label issue](https://app.makeitfable.com/share/63d1b5a084cfb4002e8a3b2f)
### How to reproduce
1.	Open JAWS
2.	Navigate using your keyboard to the Edit Skills and Experience link in the application profile 
3.	Add some values in the inputs in the Work experience form fields so you get the “unsaved changes” warning
4.	Read the warnings and  form labels in successive order.
5.	Distinguish which label goes with what field.
## ✔ Expected behaviour (fix)
 Form labels are clearly detached for warning messages and associated with input fields. 
### Potential WCAG Considerations (if any): 
[3.3.2 Labels or Instructions,](https://www.w3.org/WAI/WCAG22/Understanding/labels-or-instructions)  [4.1.3 Status Messages](https://w3c.github.io/wcag/understanding/status-messages)
### Acceptance Criteria
- [ ] Warning messages are separated from subsequent form labels. 
- [ ] Each form label is associated with the correct input field.

**Comment by petertgiles** [comment]
Thanks @RM-1978!
I took a screenshot of the word changes getting looped in with the label of the next form element.
![image](https://user-images.githubusercontent.com/8978655/230411561-168f48a1-1201-40e9-85b2-5901f6043f77.png)

To me, this looks like a bug in the AT, not a bug in the site that we can fix.  @esizer do you have an opinion on this?

The only workaround I can think of is we could change the message to simply "unsaved" so that it can't get wrapped to a second line.  Deepl tells me that the French would be "non sauvé" so that wouldn't really help.

**Comment by esizer** [comment]
> To me, this looks like a bug in the AT, not a bug in the site that we can fix. @esizer do you have an opinion on this?
> 
> The only workaround I can think of is we could change the message to simply "unsaved" so that it can't get wrapped to a second line. Deepl tells me that the French would be "non sauvé" so that wouldn't really help.

Yeah, I'm not sure but this may have been solved. We will need to do some testing but we fixed an issue recently with how our messages are being associated with the input which may help.

**Comment by RM-1978** [comment]
Hum, this happened across NVDA and JAWS. @esizer Is there any way that you could manually test this with your JAWS install?

**Comment by petertgiles** [comment]
@esizer thanks for volunteering to test things with JAWS yesterday.  :laughing: When you have some time could you please check this one out to see if it is still happening.  If so, could you suggest how it could be remedied?

**Comment by esizer** [comment]
> @esizer thanks for volunteering to test things with JAWS yesterday. 😆 When you have some time could you please check this one out to see if it is still happening. If so, could you suggest how it could be remedied?

So, I was able to reproduce this issue but I beleive it is just the date input causing it because it reads it in an odd order that does not make sense. I would leave this issue up and we can revisit it once we replace the date input with out own. Does that sound good @RM-1978 and @petertgiles  ?

**Comment by RM-1978** [comment]
@esizer, If I remember correctly, the issue at the time was that the form label for Team, Group or division was not reading for the actual field as a result of an association with the date picker. 
###Fable Video Clip
[Skills and Experience Form label issue](https://app.makeitfable.com/share/63d1b5a084cfb4002e8a3b2f)

**Comment by esizer** [comment]
We no longer show "Unsaved changes" as descriptive text for inputs. Tested and this is no longer relevant. I believe it is safe to close now 👍
