### ISSUE TITLE
⌨ Accessibility Suggestion for drop-down/combo boxes

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/gc-digital-talent#5487]
## ❌ Current behaviour (issue)
First-letter Keyboard Navigation is not possible within our drop-down menus. Screen reader users suggested that we add first-letter keyboard navigation to our combo box drop-down menus (e.g., in the new skill picker components). 
### AT configuration 
Any Screen reader, Windows, Edge/Chrome
### How to reproduce
1. Navigate to a combo box using key board navigation  
2. Activate the box by tapping the enter or down arrow keys 
3. try to jump to any selection in the drop-down menu using a letter key.
### Screen Capture
![image.png](https://images.zenhubusercontent.com/625076b8f67c446dd188ffe5/3baf9333-6155-4988-960b-b8dacabc5b4e)
## ✔ Expected behaviour (fix)
Users can jump to a group within a set of alphabetical drop down options using first-letter navigation. 
### Potential WCAG Considerations (if any): 
[1.3.1 Info and Relationships](https://www.w3.org/WAI/WCAG22/Understanding/info-and-relationships), [1.3.2 Meaningful Sequence](https://www.w3.org/WAI/WCAG22/Understanding/meaningful-sequence), [3.3.2 Labels or Instructions](https://www.w3.org/WAI/WCAG22/Understanding/labels-or-instructions) 
### Acceptance Criteria
- [ ] Users can jump to an alphabetical group of drop down options using first-letter navigation.

**Comment by esizer** [comment]
Hmm, My best guess would be the fact that these are not ordered in any meaningful way. Not 💯 on that, but it is my best guess. If we order these alphabetically, it **_should_** "just work" 🤔

**Comment by Jerryescandon** [comment]
This came up just now on a related discussion, I am very eager to order all lists alphabetically to improve navigation.

**Comment by RM-1978** [comment]
@Jerryescandon Totally agree.

**Comment by petertgiles** [comment]
What's the next step?  Make a list of all the selects and multselects and find the unsorted ones to sort them?

**Comment by Jerryescandon** [comment]
Ideally 😆

**Comment by esizer** [comment]
Just a thought... We know the shape we expect being passed in through the options prop. Could we just do an alpha sort on the label property in the `Select` component?

https://github.com/GCTC-NTGC/gc-digital-talent/blob/01ee71da802749bf379ba24c9767b9a460851f36/frontend/common/src/components/form/Select/Select.tsx#L7-L11

**Comment by Jerryescandon** [comment]
To be honest, I think making the default "alphabetical" for dropdowns and multiselects is a good choice overall, and we should override that on a case by case if needed. I cant think of anything right now tho.

**Comment by petertgiles** [comment]
Thanks, I'll start an issue for that and then we can reevaluate if anything is still needed afterwards.

**Comment by RM-1978** [comment]
Can we leave this issue open  in the icebox until we test this new adjustment with users?

**Comment by esizer** [comment]
Have these been tested again since https://github.com/GCTC-NTGC/gc-digital-talent/issues/5595 was closed? I noticed that https://github.com/gctc-ntgc/gc-digital-talent/issues/6067 uses the skill picker dialogs ( https://github.com/GCTC-NTGC/gc-digital-talent/pull/5054 ) that prompted this issue so I am attempting to resolve the accessibility issues that arose from their testing.

**Comment by esizer** [comment]
Fixed with sorting
