### ISSUE TITLE
Screenreader announces page loading and page loaded

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/gc-digital-talent#5489]
## ❌ Current behaviour (issue)
 DCM pages (from the dashboard to create a pool) do not give feedback to JAWS that the page selected is loading. 

### AT Configuration
JAWS, Windows, Edge 
### How to reproduce in the DCM Portal 
1. Open JAWS
2. Navigate to the following URL:  [Portal Manager Log in](https://uat-talentcloud.tbs-sct.gc.ca/en/admin )
3. Sign-in  using GC Key credentials for an admin account.  
4. Wait for next page to load.
5. JAWS should say loading or selected or expanded because I hit enter and nothing. I don't know if anything happened
### Fable Video Clip 
[Page Loading example in DCM Portal ](https://app.makeitfable.com/share/63d1e673035e44001a77d827)

## Screen Captures: 
![image.png](https://images.zenhubusercontent.com/625076b8f67c446dd188ffe5/f504812b-ba19-43c4-b159-bd97fece27b0)
 ![image.png](https://images.zenhubusercontent.com/625076b8f67c446dd188ffe5/203912d3-4515-4bd1-ae94-e3cd2301478e)
![image.png](https://images.zenhubusercontent.com/625076b8f67c446dd188ffe5/576f948d-fa37-44c5-8ae3-1113ef5b4f89)
## ✔ Expected behaviour (fix)
It would be helpful if there was feedback telling the user what new page is loading once they have initiated a page change. 
### Acceptance Criteria
- [ ]  Update the pending component to announce " *page title loading" at the start of the load and "page loaded" at the end
- [ ] Focus is placed on the first header for the user
- [ ] Screen reader users can orient themselves in a new context (e.g. they know what page has been loaded and where they are  on the  loaded page).

**Comment by petertgiles** [comment]
I just watched the video and it seems as though the tester wanted to hear "loading" and then "page loaded".  We might be able to hook that into the the Pending component which is what shows the spinner when data is loading in the app.  

Would a good acceptance criteria be _Update the pending component to announce "loading" at the start of the load and "page loaded" at the end_?

**Comment by RM-1978** [comment]
I think that if we added the page title for the page that is loading at the start, and then page loaded at the end, it would be much better.
