### ISSUE TITLE
⌨ Pool operator table screen readability

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/gc-digital-talent#5490]
## ❌ Current behaviour (issue)
https://app.makeitfable.com/share/63d1ec1184cfb4002e8a3b31
### AT Configuration
JAWS, Windows, Edge
### How to reproduce
1.	Open VoiceOver, Narrator or NVDA
2.	Log in as an admin
3.	Activate manage pools 
4.	Navigate using your keyboard only to the table using Keyboard Navigation.
### Fable Video Clip 
[Pool Table Navigation with JAWS](https://app.makeitfable.com/share/63d1ec1184cfb4002e8a3b31)
## ✔ Expected Confirmation
Headers and working area can be read by screen readers 
### Acceptance Criteria
- [ ] Manual accessibility review done of the pool tables against relevant WCAG 2 criteria 
- [ ] All Table columns and rows are announced and read when using JAWS.

**Comment by RosalieM1978** [comment]
Once #6932 is resolved, apply fixes to the Pool operator tables.

**Comment by esizer** [comment]
I just did a test of this and could not reproduce the error. My guess would be an unintentional user error where they accidentally jumped to the end of the table which would have brought them to the footer.

@RM-1978  I think this is safe to close as not an issue 👍
