### ISSUE TITLE
⌨ Accessibility Issue: Automatic Focus to IT in Create a pool drop down

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/gc-digital-talent#5491]
## 🗺 Location 
Create a pool dropdown list focus
## ❌ Current behaviour (issue) 
JAWS focus in the "starting group and level" drop-down jumps directly to IT menu options instead of starting at the top of the list. 
### How to reproduce
1. Open JAWS, 
2. Log in GC Digital Talent as an admin
3. Navigate using JAWS and your keyboard to the “ starting group and level” drop down within the Create a pool UI. 
4. Navigate to the pool s UI 
6. Activate Create Pools button/link
7. Find the beginning of the alphabetical list using only sound.
### Screen Capture: 
![image.png](https://images.zenhubusercontent.com/625076b8f67c446dd188ffe5/0ae861bc-2ab9-4c6f-98af-0040870c798f)
## ✔ Expected behaviour (fix)
Focus is positioned at the top of the list when it is activated. 
### Acceptance Criteria
- [ ] Focus is positioned at the top of the list when it is activated.

**Comment by petertgiles** [comment]
Hi Rosalie, could you help me understand this one better?  I don't have access to JAWS but with keyboard navigation I was able to complete the task and the focus did not start at the IT options.

https://user-images.githubusercontent.com/8978655/216422919-85846711-a602-471e-9b02-dfb09af7c6fa.mp4

**Comment by brindasasi** [comment]
@RM-1978 could you look into this?

**Comment by RM-1978** [comment]
Hi @petertgiles  and @brindasasi, 

Here is a video of the issue with a Jaws User. As you can see, this is what our AT Tester experienced on UAT on Dec. 21st. It might be that you have resolved it, but I would be sure to test with JAWS before closing the GitHub issue. 

https://app.makeitfable.com/share/63ebdeddf1fa5a002d8d43c6

**Comment by esizer** [comment]
Fixed
