### ISSUE TITLE
✨ (Admin) List Teams page

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#5496]
## ✨ Feature

This page shows all the teams on the platform in a table, is the highest level page for all team related content. May want to work on this alongside #5511.

## 🕵️ Details

This is a new page and should be reachable through the main navigation.

![image](https://user-images.githubusercontent.com/16977254/214658334-61f1221b-5ae5-4204-b3b7-b5d5e9239058.png)

In addition to having a table that lists all teams on the platform:
- it has a "Create new team" button that leads to #5497
- you can click on Edit team link #5499
- you can click on Delete team link #5500
- you can click on a team name to view that team #5501
- you can click on a view members to view that teams members' subpage #5502

## 🎨 Design File

Link to figma

## 📸 Screenshot

![image](https://user-images.githubusercontent.com/16977254/214869691-e985b51f-b15e-456d-bcaf-a9df5c0ceb5d.png)

## 🙋‍♀️ Proposed Implementation

Use the Table component, not the ApiManagedTable, because there will be few rows. Use the default search functionality, but ignore the Filter button.

Though it may not be implemented, assume the data is coming from a `teams: Team[]` query in our schema, with the Team definition looking like:
```
type Team {
  name: String
  displayName: LocalizedString
  description: LocalizedString
  departments: Department[]
  contactEmail: Email
}
```  
You may want to mock this response in StoryBook to work on this story.

The New Team, Edit Team, View Team, and View Members buttons are links to the following pages, whether the page exists or not:
- new team: `/admin/teams/create`
- view team: `/admin/teams/{name-slug}`
- edit team: `/admin/teams/{name-slug}/edit`
- members: `/admin/teams/{name-slug}/members`

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] The table lists all Teams returned by the `teams` graphQL query 
- [ ] This page is hosted at `/admin/teams`
- [ ] Links direct you to the correct urls, even if they result in 404s for now
- [ ] This page is only accessible with the Admin role

**Comment by tristan-orourke** [comment]
Use the Table component, not the ApiManagedTable, because there will be few rows.

**Comment by tristan-orourke** [comment]
Icon is "office-building" from our usual library

**Comment by tristan-orourke** [comment]
Though it may not be implemented, assume the data is coming from a `teams: Team[]` query in our schema, with the Team definition looking like:
```
type Team {
  name: String
  displayName: LocalizedString
  description: LocalizedString
  departments: Department[]
  contactEmail: Email
}
