### ISSUE TITLE
✨ (Admin) Edit team

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#5499]
## ✨ Feature

Describe the feature that is being requested

## 🕵️ Details

Add any additional details that could assist with the development of the new feature.

## 🎨 Design File

[Link to Figma](https://www.figma.com/file/UsrB15yicgDCLDQmx3snyl/User-Flows?node-id=0%3A1&t=HjevjsYNnRyAt9Nr-0)

## 📸 Screenshot

![image](https://user-images.githubusercontent.com/16977254/214860173-02da07e3-354d-48a4-9821-cc3e2b55cba6.png)

## 🙋‍♀️ Proposed Implementation

This should reuse most of the ui from #5497, with the addition of Description fields.

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Storybook story for this page
- [ ] Page actually available at `/teams/{id}/edit`
- [ ] Available to Admins, not other users
- [ ] Connected to API so that Team can actually be edited.

**Comment by brindasasi** [comment]
@Jerryescandon do we need to enforce the input to be less than the word count?

**Comment by Jerryescandon** [comment]
How do we handle that in other places? like on the poster edit?

**Comment by brindasasi** [comment]
> How do we handle that in other places? like on the poster edit?
Looks like we are enforcing it
![image (1)](https://user-images.githubusercontent.com/89482910/221042185-ebd28dbe-3fb0-4e9f-9f45-262179eeb7b1.png)
