### ISSUE TITLE
✨ (Teams) Add new member

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#5504]
## ✨ Feature

Describe the feature that is being requested

## :stop_sign: Blocked By
- [ ] #5563
- [ ] #5502 

## 🕵️ Details

Adding a user to a team is done by adding a team-specific Role to the user.

## 🎨 Design File

Include a link to the design file (if it exists).

## 📸 Screenshot

![image](https://user-images.githubusercontent.com/16977254/214866027-66a9c654-52ba-472a-b53d-d081db51ca1e.png)

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Criteria 1
- [ ] Criteria 2

## :stop_sign: Blockers

List any issues which must be completed before this one.

```[tasklist]
### Blockers
- [ ] #5502 
- [ ] #5563 
```

**Comment by tristan-orourke** [comment]
This is covered by #5502
