### ISSUE TITLE
✨ A new multiselect component based on the headless-ui combobox

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#5507]
## ✨ Feature

The team would like to see if we can develop a multiselect component to replace our current multiselect components that resolves the a11y issues we are experiencing with them.

## 🕵️ Details

There is frustration with how difficult it is to work with the `react-select` base components and concern that we will not be able to resolve the a11y issues without signification effort.  We want to develop a replacement on the headless-ui combobox and submit that to thorough a11y testing with Fable to see if it is an improvement.

https://github.com/gctc-ntgc/gc-digital-talent/issues/3386
https://github.com/gctc-ntgc/gc-digital-talent/issues/4995

## 🔗 Links

- [Base Combobox component](https://github.com/GCTC-NTGC/gc-digital-talent/tree/main/frontend/common/src/components/Combobox)
- [@headlessui/react Combobox docs](https://headlessui.com/react/combobox)

## ✅ Acceptance Criteria

- [ ] Implements all the features of the current multiselect
- [ ] Does not suffer from the a11y issues of the current multiselect
- [ ] Storybook story
- [ ] Ready for Fable review but not in use in the application yet.

**Comment by mnigh** [comment]
Replaced by https://github.com/GCTC-NTGC/gc-digital-talent/issues/7393.
