### ISSUE TITLE
✨ (Teams) Remove member

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#5508]
## ✨ Feature

Describe the feature that is being requested

## :stop_sign: Blocked By
- [ ] #5563
- [ ] #5502

## 🕵️ Details

Removing a user from a team means (in practice) removing any Roles connected to that team.

## 🎨 Design File

Include a link to the design file (if it exists).

## 📸 Screenshot

![image](https://user-images.githubusercontent.com/16977254/214868115-f84c9b27-ed11-421c-8470-fcee96d83371.png)

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Criteria 1
- [ ] Criteria 2

## :stop_sign: Blockers

List any issues which must be completed before this one.

```[tasklist]
### Blockers
- [ ] #5502 
- [ ] #5563 
```

**Comment by tristan-orourke** [comment]
Overlaps with #5502
