### ISSUE TITLE
✨ Test headless-ui multiselect

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#5509]
## ✨ Feature

We have developed a new multiselect component to address a11y concerns ( #5507 ).  Let's test if it is an improvement.

## ✅ Acceptance Criteria

- [ ] Coordinate testing with Fable for new component
- [ ] Open issues for any problems found
- [ ] Decide if the replacement should be used in the application

**Comment by mnigh** [comment]
@esizer wasn't this already built in #5064?

**Comment by esizer** [comment]
This was tested as part of #8001 . Tickets will be created based on that testing.
