### ISSUE TITLE
🐛 Pools page apply copy confusing

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#5514]
## 🐛 Bug

The `browse/pools` page has a button that says **Apply to this recruitment**. After clicking, a user would expect to be submitting information upon clicking a button with such copy. Instead, the user is presented with another page, `browse/pools/:poolId`, which then includes another button that says **Apply for this process**. As a user, at what stage am I actually applying?

## 🦋 Expected Behaviour

When clicking the button to view a recruitment on the `browse/pools` card, I would expect it to include the word **View** rather than **Apply** since that is the action being taken.

## 📋 Steps to Reproduce

1. Navigate to `browse/pools` page
2. Observe and click button that says **Apply to this recruitment**
3. Observe that no application has been created even though an **Apply** button has been clicked

## 🙋‍♀️ Proposed Solution

Change **Apply to this recruitment** to **View this recruitment**.

## ✅ Acceptance Criteria

- [ ] a user is presented with action copy that matches the actual actions being taken by the application

**Comment by petertgiles** [comment]
@Jerryescandon Thoughts on updated copy for this button?  "View this recruitment"?

**Comment by Jerryescandon** [comment]
I agree, I think I raised this before too, but this one is ultimately @substrae or @gobyrne

**Comment by petertgiles** [comment]
Decided to leave as-is.
