### ISSUE TITLE
🐛 GraphQL error when selecting more than one row in `apiManagedTable`

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#5520]
## 🐛 Bug

When selecting all items in any of the admin tables using apiManagedTable (Users, Pool Candidates) for more than 1 result, a GraphQL error is returned, making the Download CSV or Download Profiles buttons disappear and their function unusable. The error is: **Attempted to lazy load [awardExperiences] on model [App\\Models\\User] but lazy loading is disabled.**

The stack trace references this line: https://github.com/GCTC-NTGC/gc-digital-talent/blob/aa89339bf525d760050427d7da7057ffe03798c6/api/app/Models/User.php#L136

## 🦋 Expected Behaviour

Select all should work without any errors for up to at least 50 items per page.

## 📋 Steps to Reproduce

1. Open browser devtools
2. Navigate to `admin/users`
3. Click **Select all**
4. See errors in network request for **graphql**

## 📸 Screenshot

![Screen Shot 2023-01-27 at 10 41 08](https://user-images.githubusercontent.com/3046459/215126859-4a5bd19b-40ff-4d51-8ee7-6aabc47b20c1.png)

## ✅ Acceptance Criteria

- [ ] apiManagedTable **select all** should work without any errors for up to at least 50 items per page

**Comment by mnigh** [comment]
May be resolved in https://github.com/GCTC-NTGC/gc-digital-talent/pull/5517 by:

- [Add with directives for Applicant type experiences](https://github.com/GCTC-NTGC/gc-digital-talent/pull/5517/commits/1c88abf2949f1c4108cae7819f7825da6bd478fe)
- [Add hasMany directive for Applicant type *-Experiences](https://github.com/GCTC-NTGC/gc-digital-talent/pull/5517/commits/451740c14dfcbe3fe8ee3d1ee273fab9fef605ac)
- [Add with directives for User type experiences](https://github.com/GCTC-NTGC/gc-digital-talent/pull/5517/commits/e55fd86bf75ac1aeef15b590bd30418c02b8924c)

**Comment by petertgiles** [comment]
@mnigh this was resolved in #5517 right?
