### ISSUE TITLE
NotifyTest.php does not comply with psr-4 autoloading standard

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#5524]
## 🐛 Bug

When running composer there is a warning:
```
Class Tests\Unit\NotifyTest located in ./tests/Feature/NotifyTest.php does not comply with psr-4 autoloading standard. Skipping.
```

## 🦋 Expected Behaviour

No warning from composer.

## 🕵️ Details

My guess, it probably doesn't like that the namespace doesn't follow the file path.

## 📋 Steps to Reproduce

1. Run composer install

## 📸 Screenshot

![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/eb277a3a-ce33-4bee-9922-1cbfbeee3110)Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] No warning from composer
- [ ] PHP tests run fine

**Comment by vd1992** [comment]
duplicate of  #5525
guess we can let this one be recycled and edited with a separate issue when something comes up, or closed, your choice

**Comment by petertgiles** [comment]
Oops, double submit.  Thanks zenhub!
