### ISSUE TITLE
Perf: Add `@with` directives for `Skill` type experiences

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#5529]
## Background
The `@with` and `@hasMany` directives for lighthouse trigger eager loading, which is desirable for performance.  We recently added some missing directives for the User -> Experience and Applicant -> Experience relationships.

What about here `Skill` type, should they be added there as well?
https://github.com/GCTC-NTGC/gc-digital-talent/blob/b2820b3644aa1335a2a909c43825e905925dcf72/api/graphql/schema.graphql#L587

_Originally posted by @mnigh in https://github.com/GCTC-NTGC/gc-digital-talent/pull/5517#discussion_r1090970048_
            
## Acceptance Criteria
- [ ] Determine if querying the Skill -> Experience relationship in graphql triggers a lazy load
- [ ] If it does, add the missing directives to ensure an eager load

**Comment by vd1992** [comment]
Does not appear to be an issue to me

![image](https://user-images.githubusercontent.com/40485260/234716694-259fb117-e28a-41f5-ba26-701d61daa16e.png)

Most likely due to the directive on the specific experiences below?

https://github.com/GCTC-NTGC/gc-digital-talent/blob/b2820b3644aa1335a2a909c43825e905925dcf72/api/graphql/schema.graphql#L588-L592

**Comment by vd1992** [comment]
Is this an issue? I feel like we'd have seen warnings in development if it was throwing errors due to Strict we enabled a while ago in #4539

**Comment by mnigh** [comment]
> Is this an issue? I feel like we'd have seen warnings in development if it was throwing errors due to Strict we enabled a while ago in #4539

@petertgiles any thoughts?

**Comment by petertgiles** [comment]
I agree with Vachan.  We would have seen errors in development with the query he's showing.  I guess the hasMany directive is running the eager load.  I think this can be closed.
