### ISSUE TITLE
✨ Add basic Search bar to Pools table

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#5534]
## ✨ Feature

We now have lots of Pools, and navigating the Pools table on Admin would be a lot easier with a search bar.

## 🕵️ Details

It's most important to be able to search by pool name (fully formatted pool name). We will also need to search by status and owner.

## 🎨 Design File

Include a link to the design file (if it exists).

## 📸 Screenshot

Add a screenshot of the new feature (if possible).

## 🙋‍♀️ Proposed Implementation

This may be as simple as letting `search={true}` on the Table component, but we'll need to test that it works as expected. Some columns, like Pool Name, might benefit from being split into [accessor and cell](https://react-table-v7.tanstack.com/docs/api/useTable#column-options).

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Its possible to type Pool Name into a search bar on the Pools table to filter down the visible rows.
- [ ] Its possible to type a Pool Status into the search bar to filter to pools with that status (if it's not too difficult)
- [ ] Its possible to type an owner name into the search bar to filter to pools with that owner (if it's not too difficult)

**Comment by petertgiles** [comment]
> Might also be nice to search by status and owner?

Final decision on if you want to add this to acceptance criteria?

**Comment by tristan-orourke** [comment]
Sure. I think it'll be easy anyway, so they can go in the AC

**Comment by patcon** [comment]
ClientManagedTable
