### ISSUE TITLE
✨ Make Estimated language levels Required fields

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#5535]
## ✨ Feature

Make the self-assess Second language proficiency level field at `/profile/language-info/edit` a required field, instead of optional.

## 🕵️ Details

On the Language Information page of the profile, if one indicates having taken a Language test, then Language Levels appear as required fields. If the user indicates not having taken a test, then they can enter a self-assessed level, but it is an optional field. DCM has requested making the self-assessment level required as well, since they may require an intermediate level or higher to screen people in.

## 📸 Screenshot

![Required test levels](https://user-images.githubusercontent.com/4313717/215613092-1786da94-baf3-48f4-bf05-af018ef1e26f.png)

![Optional self assessment](https://user-images.githubusercontent.com/4313717/215613148-70dfe81e-5d83-4047-a194-d48b6bd1d176.png)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] If the self-assessment language level field appears in a form, it is a required field.

**Comment by tristan-orourke** [comment]
@gobyrne @Jerryescandon Jamie from DCM requested this. Should we go ahead?

**Comment by Jerryescandon** [comment]
I think this would be fine, but looking at it now I think we could make it a little bit more clear that these should be "Your best estimate" basically, the way we've presented it sound like you HAVE to go verify your current language level before selecting anything. maybe we can do the switch to required but we should revisit the copy too.

**Comment by tristan-orourke** [comment]
@Jerryescandon @gobyrne Jamie asked about this again. Can we decide on a copy change?

**Comment by substrae** [comment]
@tristan-orourke @Jerryescandon 

This is being updated as a part of the new profile updates, but if you're eager to make immediate changes, making it required is an easy win, I think.

For reference, here's where we're leaning for the future iteration:

![image](https://user-images.githubusercontent.com/6960386/233454308-58979afe-5681-4f2b-bdcf-b1f536696794.png)

**Comment by tristan-orourke** [comment]
@mnigh I'm not sure what you mean by comparing this to #7313? 

It looks like we got the okay from design to make this required all the back in April, and just haven't prioritized moving this into the backlog 😆. Though that was a long time ago... @gobyrne does this still make sense to do?

**Comment by mnigh** [comment]
> @mnigh I'm not sure what you mean by comparing this to #7313?

Just for reference for whoever picks up the issue as the PR does conditional requirement of a field based on a value of another field.

**Comment by gobyrne** [comment]
This field is required in #8031 so it should get fixed there. Closing
