### ISSUE TITLE
🐛 `MissingSkills` stories all look the same

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#5551]
## 🐛 Bug

All of the story variations render the same thing regardless of which is selected:

- `MissingBothSkills`
- `MissingRequiredSkills`
- `MissingOptionalSkills`
- `MissingSomeSkills`

## 🦋 Expected Behaviour

Should render differently based on case. If not, then there is no apparent need for variation stories. 

## 📋 Steps to Reproduce

1. `npm run storybook`
2. Navigate to  **Missing Skills** stories

## 📸 Screenshot

![Screen Shot 2023-01-31 at 09 31 23](https://user-images.githubusercontent.com/3046459/215796073-e8d94989-7687-4eb7-a20e-8011097df901.png)

## ✅ Acceptance Criteria

- [ ] Each of the four stories properly displays the component in the different states

**Comment by petertgiles** [comment]
The component seems to work OK in the app itself.  Something must have gone wrong with storybook or the fakers.
![image](https://user-images.githubusercontent.com/8978655/216401133-795e9436-13c2-4b42-9ac6-d3f888d1d95a.png)
