### ISSUE TITLE
🐛 Home Page > IAP story invalid background color

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#5552]
## 🐛 Bug

Backgrounds Addon: could not find the default color "white". These are the available colors for your story based on your configuration: light, dark. 

## 🦋 Expected Behaviour

Story should render without any `console` warnings.

## 📋 Steps to Reproduce

1. `npm run storybook`
2. Open browser console
3. Navigate to  **Home Page > IAP > Default** story

## 📸 Screenshot
![Screen Shot 2023-01-31 at 15 58 40](https://user-images.githubusercontent.com/3046459/215882280-fd23487f-0a9a-46c7-aaaa-a28470e8a452.png)

## ✅ Acceptance Criteria

- [ ] story should render without any `console` warnings

**Comment by patcon** [comment]
I recall this being quite straightforward: .storybook/preview.js change, and then change on the story definition itself to change default for that story.
https://storybook.js.org/docs/react/essentials/backgrounds/

**Comment by mnigh** [comment]
> I recall this being quite straightforward: adding new "white" option to `.storybook/preview.js`, and then change on the story definition itself to change default for that story. https://storybook.js.org/docs/react/essentials/backgrounds/

Since the **white** option is only being used for this story, then the following can be changed as to not make it a global option:

## Current code
https://github.com/GCTC-NTGC/gc-digital-talent/blob/01ee71da802749bf379ba24c9767b9a460851f36/apps/web/src/pages/Home/IAPHomePage/Home.stories.tsx#L10-L14

## Replacement code
```
  parameters: {
    backgrounds: {
      default: "white",
      values: [{ name: "white", value: "#fff" }],
    },
  },
```
