### ISSUE TITLE
✨ Implement Roles graphql query

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#5559]
## ✨ Feature

Add the Role type to the graphql schema, and implement a query which lists all Roles. 
Add `isTeamBased` metadata to Role.

```[tasklist]
## 🛑 Blocked By
- [x] #5436 
```

## 🕵️ Details

Add an `isTeamBased` boolean flag to the Role type. This needs to be added to the database, to the php model, and to the `rolepermission.php` seeder config (as appropriate).

The query should be guarded by a policy method which for now, can just check that the user is an admin.

```
type Role {
  name: String;
  displayName: LocalizedString;
  description: LocalizedString;
  isTeamBased: Boolean;
}
```

## 🎨 Design File

Include a link to the design file (if it exists).

## 📸 Screenshot

Add a screenshot of the new feature (if possible).

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Admins can call a `roles` query to get a list of all available roles
- [ ] Role show if they are intended to be team-based or not
- [ ] Roles defined in the seeder config have isTeamBased appropriately defined
- [ ] guest users, and non admins, cannot access this query

**Comment by brindasasi** [comment]
yes team_admin is team based. Applicant , Super Admin are not. They will exist regardless of any team association.
