### ISSUE TITLE
✨ Assignment and Querying of Users to Roles and Teams

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#5563]
## ✨ Feature

Admins need to be able to:
- See which Roles each user has
- If a user has team-based Roles, see which Teams those Roles are associated with
- Know whether a Role is intended to be team-based or not
- See which users are on a team, and which teams a user is on (determined by whether the user has any team-based Roles)
- Assign or remove Roles to Users (team-based and not)

## 🛑 Blocked By
- [x] #5511 
- [x] #5559 

## 🕵️ Details

Add any additional details that could assist with the development of the new feature.

## 🎨 Design File

Include a link to the design file (if it exists).

## 📸 Screenshot

Add a screenshot of the new feature (if possible).

## 🙋‍♀️ Proposed Implementation

- Add roles and teams to the Users type. Use the `@can` directive to ensure related objects can only be viewed with the correct permissions.
```
type User {
  ...
  roles: [Role] @belongsToMany @can('view', resolved: true)
  teams: [Team] @belongsToMany(relation: "rolesTeams") @can('view', resolved: true)
}
```
- When retrieving a user's roles, it should be possible to see if the role is attached to a Team. I think this can be implemented by using Laravel `withPivot`, similar to what we did with Users, Experiences and Skills:
```
type Role {
  ...
  team: Team @can('view', resolved: true) # This will be null unless going through a user-role pivot table
}
```
- Add users (basic info only) to the Teams type. Use the `@can` directive to ensure they can only be viewed with the correct permissions.
```
type Team {
  ...
  members: UserPublicProfile @belongsToMany(relation: "users") @can('view', resolved: true, model:  "User")
}
```
- QUESTION: We have options in how we design the mutations to attach/detach roles. 
  - We could do it all in one _sync_ mutation, something like:
  ```
  input RoleInput {
    roleId: ID!
    teamId: ID # must be set for team-based Roles, and left null for other Roles
  }
  type Mutation {
    syncRoles($userId: ID!, $rolesInput: [RoleInput])
  }
  ```
  - We could split attach and detach and do them one at a time. This may force the client to run a number of mutations at once:
  ```
  attachRole($userId: ID!, $roleInput: RoleInput!)
  detachRole($userId: ID!, $roleInput: RoleInput!) # if a role was attached with a team, it must also be detached with it.
  ```
  - and, we could split up Roles and TeamRoles, whether using sync or attach/detach:
  ```
  attachRole($userId: ID!, $roleId: ID!)
  attachTeamRole($userId: ID!, $roleInput: TeamRoleInput!)
  ```
- We may want to add a `users` relationship visible on teams. This could also show a teamRoles pivot, if we really wanted, though I doubt that's necessary.
- QUESTION: The permissions on all this are a bit thorny, especially if we want to to enable something like `team.users`. Perhaps having a separate query, `teamMembers($teamId!): UserPublicProfile` would be easier. This should be considered carefully in relation to #4362 and #2266.

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

Admins can...
- [ ] See which Roles each user has
- [ ] If a user has team-based Roles, see which Teams those Roles are associated with
- [ ] Know whether a Role is intended to be team-based or not
- [ ] See which users are on a team, and which teams a user is on (determined by whether the user has any team-based Roles)
- [ ] Assign or remove Roles to Users (team-based and not)

Non-admins can...
- [ ] do none of the above

And...
- [ ] phpunit feature tests to verify the above cases.

**Comment by petertgiles** [comment]
Regarding the mutation, I think it would match the rest of our API best if we went with `connect` and `sync` properties on Update* inputs.
![image](https://user-images.githubusercontent.com/8978655/216345219-69ce99ea-4635-4a84-aa68-632f0c095a3b.png)
I guess this input should be used on the UpdateUser mutations rather than its own stand-alone mutation if we're trying to reduce duplication.  But yeah, not sure how that works with the new permissions.

**Comment by tristan-orourke** [comment]
Good point about `connect` and `sync`!

I do feel that the mutation for updating Roles should be seperated from UpdateUser, because in most cases user only wants to do one or the other.
