### ISSUE TITLE
🐛 Hard to submit application with required transferable skills

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#5584]
## 🐛 Bug

When a pool has required transferable skills, it becomes very difficult to submit an application when you are missing those skills on your profile. We are showing required technical skills only when editing experiences on an application. This means, I must leave the application and go to my profile to add those transferable skills. This becomes very frustrating when there are more than 1-2 skills since I must switch back and forth between the job poster and my profile to add those transferrable skills. 

## 🦋 Expected Behaviour

I'm not sure what the expected behaviour is here, I assume we chose to only show technical skills on the application for a reason.

1. Should we also show transferable or,
2. Restrict what skills a admin can make required for a pool

## 📋 Steps to Reproduce

1. Create a pool with required transferable skills
2. Create an applicant missing at least one of the required skills in step 1
3. Try to apply to the pool
4. Go to edit your experiences within the application context
5. See that the transferable skills cannot be added to an experience

## 📸 Screenshot

<img width="1014" alt="Screenshot 2023-02-02 at 10 16 10 AM" src="https://user-images.githubusercontent.com/4127998/216364301-a7b8317b-72cc-4eb0-b0d5-85d9aefaced7.png">
<img width="873" alt="Screenshot 2023-02-02 at 10 15 53 AM" src="https://user-images.githubusercontent.com/4127998/216364302-4756f76f-c49d-4107-b053-7f548194b480.png">

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] A user can apply to an application w/o needing to return to their profile

**Comment by petertgiles** [comment]
@Jerryescandon any insight on this design question?

**Comment by Jerryescandon** [comment]
@gobyrne please confirm

Required transferable skills do not need to be validated or added to a profile in order to submit an application. They are for all intents and purposes exempt from validation. We want to let the user know they exist cause they will be assessed during the process but there's no need to have them tied to a profile or justify them.

**Comment by brindasasi** [comment]
@gobyrne  could you confirm on this?

**Comment by tristan-orourke** [comment]
Transferable Skills are not required as part of Application validation, and that is currently the case.

**Comment by tristan-orourke** [comment]
I just tested, and I was able to submit an application without having the "Need to have" Transferrable skills.

**Comment by esizer** [comment]
> I just tested, and I was able to submit an application without having the "Need to have" Transferrable skills.

Oh, look like this was fixed recently as a side effect of another PR 😅

**Comment by esizer** [comment]
Though, if transferrable are not actually required, should we consider point two?

> 2. Restrict what skills a admin can make required for a pool

**Comment by Jerryescandon** [comment]
Transferable skills can be required for admittance into a pool, they are just not assessed through the initial application.
They should, however, be assessed later on through a different type of assessment, such as an interview or a reference check.
While the platform may not have those assessments yet, they will eventually be a part of "Record of Decision", and at this point we are gonna need to know which transferable skills were deemed 'required' for each pool.
