### ISSUE TITLE
Separate CI Setup.sh

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#5592]
## ✨ Feature

Right now we have a single `setup.sh` script that was written to help developers do a first-time setup of their development environments.  Later, it started being used to run CI in Github Actions, too.  However we're starting to see some diverging needs in the setup.

## 🕵️ Details

- Devs like to see a large amount of random, realistic data in their database.  PHPUnit needs no seeded data at all.  Cypress needs a minimal amount of dimensional data only.  Our full seeders can take a lot of time to run.
- Devs want a dev build from Webpack to get the most amount of debugging and sourcemap data.  Cypress errors out on console errors from a dev build.

## ❓️ Questions (and Answers)
-    Is it a risk to run a different setup locally and in CI?
    -    there's the risk of similar code diverging where it shouldn't, but that's not worse than what we have now
 -   Are there other opportunities to optimize CI with its own setup other than the seeders?
    -    seeders
     -   building in dev mode vs production
  -  Should we have separate scripts or change the behaviour of a single script with option parameters?
     -   Let's try one script with a flag?
  -  Can we bring deploy.sh into alignment with these, too?
     -   Let's not worry about deploy.sh right now

## ✅ Acceptance Criteria

- [ ] setup.sh has a flag to run in CI mode
- [ ] dev mode runs all the regular seeders and builds the app in Webpack dev mode
- [ ] CI mode runs minimal seeders (maybe uat or prod seeder?) and builds the app in Webpack prod mode
- [ ] VS Code build tasks run setup in dev mode

**Comment by tristan-orourke** [comment]
- Is it a risk to run a different setup locally and in CI?
  - there's the risk of similar code diverging where it shouldn't, but that's not worse than what we have now
- Are there other opportunities to optimize CI with its own setup other than the seeders?
  - seeders
  - building in dev mode vs production
- Should we have separate scripts or change the behaviour of a single script with option parameters?
  - Let's try one script with a flag?
- Can we bring deploy.sh into alignment with these, too?
  - Let's not worry about deploy.sh right now
