### ISSUE TITLE
Tooling - Use graphql codegen tools to generate fake data

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#56]
# Description
On the frontend, we often need fake data to populate views in Storybook, or for testing.
We should be able to use codegen tools to generate this fake data very easily, after a bit of overhead of setting up the scripting.
[This](https://www.graphql-tools.com/docs/mocking) should be a good starting point.

**Comment by mnigh** [comment]
@tristan-orourke is this still something we want to do?

**Comment by tristan-orourke** [comment]
Nah, our existing patterns are fine.
