### ISSUE TITLE
🐛 Profile/Application sections inconsistently use possessive pronoun 

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#5608]
## 🐛 Bug

**My skills and experience** and **My Status** use a possessive pronoun when none of the of the other sections titles do. Technically, the could all have 

## 🦋 Expected Behaviour

What should be happening?

## 📋 Steps to Reproduce

1. Visit Profile page
2. Observe **On this page** titles

## 📸 Screenshots

![Screen Shot 2023-02-03 at 14 47 12](https://user-images.githubusercontent.com/3046459/216713629-16aea5e4-31d2-4213-a09a-3f41167c4618.png)
![Screen Shot 2023-02-03 at 14 46 58](https://user-images.githubusercontent.com/3046459/216713630-d1f4728d-d549-428a-8331-b1066f01db7d.png)

## 🙋‍♀️ Proposed Solution

Remove **My** (possessive pronoun) from titles.

## ✅ Acceptance Criteria

- [ ] section titles are consistent in their format and do not contain possessive pronouns

**Comment by petertgiles** [comment]
@Jerryescandon How do you feel about this proposed solution?

**Comment by Jerryescandon** [comment]
Here's Laurens preference from the desfam convo:
![image](https://user-images.githubusercontent.com/16977254/217280399-d9050e6e-958f-4886-af8d-d752728ace48.png)

**Comment by petertgiles** [comment]
OK, then. :laughing: I'll close this one and we'll wait for copy.
