### ISSUE TITLE
🐛 Work location section title does not match breadcrumb

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#5610]
## 🐛 Bug

The **Work location** section title does not match the corresponding breadcrumb.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/6fe290853864a631caceaec4bc1f3950082727ef/apps/web/src/pages/Profile/WorkLocationPage/components/WorkLocationForm/WorkLocationForm.tsx#L134-L145

## 🦋 Expected Behaviour

The **Work location** section title and its corresponding breadcrumb should be the same.

## 📋 Steps to Reproduce

1. Visit `/users/:userId/profile/work-location/edit`
2. Observe heading and breadcrumb

## 📸 Screenshot
![Screen Shot 2023-02-03 at 15 06 51](https://user-images.githubusercontent.com/3046459/216714047-65db78f0-5f19-4879-a127-e8d5cfbcc4aa.png)

## 🙋‍♀️ Proposed Solution

Update breadcrumb to be: Work location. Description of the string should be updated as well.

## ✅ Acceptance Criteria

- [ ] **Work location** section title and its corresponding breadcrumb should be the same in English and French

**Comment by petertgiles** [comment]
@Jerryescandon How do you feel about the proposed solution?

**Comment by Jerryescandon** [comment]
Looks good to me
