### ISSUE TITLE
🐛 `urql` cache not invalidated on logout

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#5613]
> **Note**
> I have since been unable to reproduce this, it may have been some weird issue I created for myself when experimenting with `react-router`

## 🐛 Bug

It seems as though the `urql` cache is not being invalidated on logout which leads to some odd app states. The one example I found was the `PoolAdvertisementPage` shows a "Continue my application" after logging out.

> **Waring**
> This is very problematic for `me` queries that can expose user data on public pages that do not require auth.

## 🦋 Expected Behaviour

Once a user logs out the `urql` cache should be invalidated so all queries need to refire.

## 📋 Steps to Reproduce

1. Login to the application
2. Navigate to a pool advertisement and create a draft application
3. Logout
4. Return to the same pool adverisement in step 2
5. Observe the cached result appears showing a "Continue my application" button that leads to a 404 page

## 📸 Screenshot

![Screenshot 2023-02-04 112041](https://user-images.githubusercontent.com/4127998/216778450-63ea5ca7-a8dd-4ed3-b534-a38228308afb.png)

## 🙋‍♀️ Proposed Solution

Someone has [a decent solution](https://github.com/urql-graphql/urql/issues/297#issuecomment-504782794) but it is a few years old now so it may not work. However, we could draw influence from it in the case it does not work.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] `urql` cache is invalidated on logout
- [ ] All queries are re-fired after logging out
- [ ] Cannot access stale `me` data while logged out

**Comment by petertgiles** [comment]
I wasn't able to recreate this either.  Not saying it's not a problem, just that we need a better steps to reproduce, I think.

**Comment by brindasasi** [comment]
can't be reproduced
