### ISSUE TITLE
GC DT Copy review to implement IAP copy for 'Passions and Experience'

### ISSUE THREAD

**Issue by MCommonda** [GCTC-NTGC/gc-digital-talent#5619]
Careful consideration has been used in drafting the copy in the IAP profile. It is believed that the overall build of the GC DT could benefit from implementing the text that appears in the 'Passions and Experience' section of the IAP profile. Below are the screenshots for context followed by the text for ease copying (if needed):

## Screenshot
![Image](https://user-images.githubusercontent.com/100953374/217034810-76fd211d-9557-40dd-8141-01915d2d150a.png)

**Text:**
1. Community Experience Details
People learn skills from a wide range of experiences like volunteering or being part of non-profit organizations, Indigenous communities, or virtual collaborations. Have you gained experience by being part of or giving back to a community? This could be anything from: helping during events and ceremonies, bartering, DJing at a friend’s wedding, to gaming and streaming.

**Text:**
1. Work Experience Details
Share your experiences gained from full-time positions, part-time positions, self-employment, fellowships, and internships. You don’t necessarily need to share everything. Instead, focus on experiences related to the opportunity that you are interested in.

**Text:**
1. Personal Experience Details
No changes

**Text:**
1. Education Details
No changes

**Text:**
1. Award Details
No changes

**Comment by mnigh** [comment]
some partial copy changes approved by @MCommonda:

**Community Experience Details**

This could be anything from helping during events and ceremonies, bartering, DJ-ing at a friends wedding, to gaming and streaming.

**to**

This could be anything from: helping during events and ceremonies, bartering, DJing at a friend’s wedding, to gaming and streaming.

--

**Work Experience Details**:

Share your experiences gained from full-time positions, part-time positions, self-employment, fellowships or internships. You don’t necessarily need to share everything, instead focus on experiences related to the opportunity you are interested in.

**to**

Share your experiences gained from full-time positions, part-time positions, self-employment, fellowships, and internships. You don’t necessarily need to share everything. Instead, focus on experiences related to the opportunity that you are interested in.
