### ISSUE TITLE
Spacing messed up on Ongoing Recruitment

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#5620]
## 🐛 Bug

Looks like the spacing got messed up on Ongoing Recruitment with the new accordion styles

## 🕵️ Details

- **Operating System**: Linux PopOS 22.04
- **Browser**: Firefox 109.0.01

## 📋 Steps to Reproduce

1. Visit `http://localhost:8000/en/browse/pools`
2. If you want to assign all pools to ongoing to force several accordions `update pools set publishing_group = 'IT_JOBS_ONGOING'`

## 📸 Screenshot

![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/05233895-facf-44d8-8b06-99ce5a8ed9d5)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Spacing updated to restore previous appearance

**Comment by substrae** [comment]
I thought I had fixed this in the #5430 PR, but for some reason when I compiled today they were busted again, so I'm still investigating.

**Comment by brindasasi** [comment]
Indeed. This got fixed in https://github.com/GCTC-NTGC/gc-digital-talent/pull/5430
