### ISSUE TITLE
✨ Page break after each application in the candidate print/download view

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#5622]
## ✨ Feature

As the recruitment team I want a "Page Break" after each individual application in the PDF candidate download so I can easily separate applications.

## 🕵️ Details

It doesn't need to be super slick, but it would be helpful to have a page break after each application. It's probably fine if it results in occasional "double page breaks" or similar.

## ✅ Acceptance Criteria

- [ ] Page break after every application in print view
- [ ] OK if a bit glitchy - works best in Edge and Chrome

**Comment by mnigh** [comment]
@petertgiles did some work on print styles, for reference:

https://github.com/GCTC-NTGC/gc-digital-talent/blob/aeeee8b069cea1818bdfde89b52dbd46532d2ab2/frontend/common/src/constants/printStyles.ts#L1-L17
