### ISSUE TITLE
✨ Hide "Interview language" and "Exam language" by default on Users and Pool Candidate tables

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#5624]
## ✨ Feature

"Interview language" and "Exam language" are hidden by default on Users and Pool Candidate tables

## 🕵️ Details

Add any additional details that could assist with the development of the new feature.

## 📸 Screenshot

![image.png](https://images.zenhubusercontent.com/5dc084854553760001149b53/e3236912-7a71-4fa9-a896-ff64b1c6c104)

## ✅ Acceptance Criteria

- [ ] "Interview language" and "Exam language" are hidden by default on the Users Table
- [ ] "Interview language" and "Exam language" are hidden by default on the Pool Candidates Table

**Comment by mnigh** [comment]
There was a very similar issue recently that asked to remove those columns, #5533, which has been resolved in #5588.

Is this issue meant to bring back (but hidden by default) **Preferred Spoken Interview Language** and **Preferred Written Exam Language** columns in the User and Pool Candidate tables?

**Comment by gobyrne** [comment]
Agreed, closed as duplicate
