### ISSUE TITLE
Check for hydrogen errors in CI

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#5641]
## ✨ Feature

Hydrogen now emits warnings for invalid code.  We should probably check for this in CI.

## 📸 Screenshot

![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/dd4edb49-9b85-4918-a8db-949397107713)Add a screenshot of the new feature (if possible).

## 🙋‍♀️ Proposed Implementation

Maybe add it to the linting workflow?

## ✅ Acceptance Criteria

- [ ] Invalid Hydrogen directives cause a CI step to fail

**Comment by vd1992** [comment]
I'd like to add it in, recently a typo was missed and merged in 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/10c66da8-d2aa-4275-90fe-7b83ee4b70fd)

I attempted to sketch out something to add to a workflow to check for this but am not sure if this is the right approach.

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/74078d19-2a45-4dc1-af73-25de766f70f4)

**Comment by petertgiles** [comment]
I submitted https://github.com/hydrogen-css/hydrogen/issues/270 to request an exit code from h2-build.  That should make this simpler.

**Comment by petertgiles** [comment]
Should be solved by Hydrogen 2.0.2.
https://github.com/hydrogen-css/hydrogen/issues/270#issuecomment-1604628428

**Comment by vd1992** [comment]
Issue was indeed solved by it, experimenting in #6945
