### ISSUE TITLE
🐛 `ClientManagedTable` sorting on some columns causes problems

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#5642]
## 🐛 Bug

Right now we have sort enabled on all columns of the `ClientManagedTable`. This is a little odd when sorting by the "Edit" button and others. Also, when disabling sort, the visual display of the column header is a little odd.

## 🦋 Expected Behaviour

Some columns should not be able to be sorted since it does not make sense to sort them.

## 📋 Steps to Reproduce

1. Navigate to any `ClientManagedTable`
2. Sort by any column that includes a link/button
3. See that the sort doesn't really do much

## 📸 Screenshot

![217311252-52460791-1774-4829-916c-a8d4c2a8ca73](https://user-images.githubusercontent.com/4127998/217333408-0d082a44-e77c-4b07-9307-128456559e07.png)

## 🙋‍♀️ Proposed Solution

Review our tables and determine what columns should have sorting disabled. As well, we should have a visual indicator so users know what columns can be sorted.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Sorting is disabled for the appropriate columns
- [ ] Column headers should be consistent in font between sortable and non-sortable columns
- [ ] Visual indicator for users to determine what columns can be sorted

**Comment by tristan-orourke** [comment]
This table component is being replaced
