### ISSUE TITLE
Associate search request directly with classification and job stream

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#5644]
## ✨ Feature

Currently we associate search requests with a pool and infer the desired classification and job stream from that pool.  In the near future search requests will no longer be associated with a pool.  Therefore the classification and job stream of the request will need to be associated directly with the search request.

## 🕵️ Details

Add any additional details that could assist with the development of the new feature.

## 🎨 Design File

Include a link to the design file (if it exists).

## 📸 Screenshot

Add a screenshot of the new feature (if possible).

## 🙋‍♀️ Proposed Implementation

Add Classification and Stream to ApplicantFilter and CreateApplicantFilterInput as optional fields. Ensure they correctly filter query results.

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [x] When new search requests are submitted, they include Classification and Stream attached directly, _along with_ the pool
- [x] If classification and stream are defined, then show them in the SearchRequestFilters component
- [x] If applicantFIlter.pools is not empty, show the name of each in SearchRequestFilters, instead of just displaying pool classifications.
- [x] When an empty search request is submitted, don't include any Pools, but _do_ include Classification and Stream
- [x] On the Admin side, on PoolCandidate tables, allow for filtering by Classification and Stream. Ensure these filters are initialized correctly by the search request.

**Comment by vd1992** [comment]
the means to connect classification to applicant filters exists, the pivot table exists, it just needs a frontend tweak to populate correctly (currently submitting a request doesn't attach the classification properly)

stream requires work, streams aren't objects but fields on pools, therefore may need a migration to add a stream field onto applicant filter model

![image](https://user-images.githubusercontent.com/40485260/224189976-573d8a3d-aca5-489c-8edc-b91040d8f1b4.png)


![image](https://user-images.githubusercontent.com/40485260/224189739-6f89cae5-a539-4bd7-aaa2-f911341d72e4.png)

**Comment by brindasasi** [comment]
moving this back to in progress as we intend to fix the poolcandidate filter also in this PR.
