### ISSUE TITLE
Update text sorting for text columns

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#5655]
## ✨ Feature

Update the sort order for text columns.

~:question: Should Vue come before asp.net in English?~
~:question: Should Vue come before Évaluation in French?~
See explanation below: https://github.com/GCTC-NTGC/gc-digital-talent/issues/5655#issuecomment-1423136781

## 🕵️ Details

Context https://github.com/GCTC-NTGC/gc-digital-talent/pull/5649#discussion_r1100530249

## 🎨 Design File

Include a link to the design file (if it exists).

## 📸 Screenshot
From the skills table:
![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/241de7da-4d64-47fd-a8aa-8903faafa21f)

## 🙋‍♀️ Proposed Implementation

- Write a util function to normalize strings by lowercasing them and removing diacritics
- Update accessors for text columns to use the new function

## ✅ Acceptance Criteria

- [ ] Text columns are sorted case-insensitively
- [ ] Text columns are sorted diacritic-insensitively

**Comment by mnigh** [comment]
>❓ Should Vue come before asp.net in English? 
>❓ Should Vue come before Évaluation in French?

In French, letters with diacritics do not create a new letter. A [good explanation of this](https://ux.stackexchange.com/questions/115605/alphabetical-grouping-of-accented-words#:~:text=In%20French%20(or,non%20accented%20character.).

Example list using expected ascending order (for either English or French):

1. .NET
2. asp.net
3. Async
4. Evaluation
5. Évaluation
6. Vue

> **Note**
> I am not sure of the sort order if the strings were identical other than a diacritic **Evaluation** or **Évaluation** (that would be a super rare edge case)
