### ISSUE TITLE
🐛 About section has inconsistent spacing

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#5658]
## 🐛 Bug

About section has inconsistent spacing.

## 🦋 Expected Behaviour

About section should have consistent spacing.

## 📋 Steps to Reproduce

1. `npm run storybook`
2. View **User Profile > User Profile Null story**

## 📸 Screenshot
![Screen Shot 2023-02-08 at 12 30 18](https://user-images.githubusercontent.com/3046459/217639645-9ec9a03a-fcee-4f34-8609-7b2632788a25.png)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] **About** section has consistent spacing

**Comment by esizer** [comment]
Looks like this was solved at one point 😆 


![Screenshot 2023-03-10 134746](https://user-images.githubusercontent.com/4127998/224400257-813e52cf-4f19-4cc5-8580-23f9e5585308.png)

**Comment by mnigh** [comment]
> Looks like this was solved at one point 😆

Indeed, @petertgiles as part of #5857:

https://github.com/GCTC-NTGC/gc-digital-talent/commit/b7496cb2cf654fd4bf125ae7bb4ea1c84056a62a#diff-3813add0bf6c770dee3450518460189884077868f0f261cc42cf3ddabfeb35a2

does this function need to remain:

https://github.com/GCTC-NTGC/gc-digital-talent/blob/f5b4498fae499d4fe245645baf4ad07a14de1e80/apps/web/src/components/UserProfile/ProfileSections/AboutSection.tsx#L36-L58

**Comment by petertgiles** [comment]
> does this function need to remain:

Probably not?  :shrug:

**Comment by esizer** [comment]
Fixed in #5857 and new issue opened in #5920
