### ISSUE TITLE
✏️ Update documented sitemap

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#5659]
## ✏️ Documentation

Update the [sitemap](https://docs.google.com/spreadsheets/d/17A3n9kCyr0lELtXYfegI8tNxlN1-vJVUK37NExYNHUI/edit#gid=1116634425) with new pages, titles, and breadcrumbs. I'm thinking in particular about [Admin page updates](https://docs.google.com/spreadsheets/d/1OflNJCN450hS4_ASzjrJs6JwsWa9zsda_udlqQHDBiA/edit#gid=0), but there might be some changes to public pages too (like the request confirmation page).

## 🕵️ Details

Add any additional details that could assist with the implementation of the new documentation.

## 🙋‍♀️ Proposed Copy

(optional) Do you have any copy that you would like to propose?

## ✅ Acceptance Criteria

- [ ] https://go.talent.c4nada.ca/sitemap spreadsheet is up to date again

**Comment by petertgiles** [comment]
Sitemap updated with new pages and titles.  Breadcrumbs are not included in the sitemap.
