### ISSUE TITLE
🐛 Stop getme query partying on the production site with error events 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#5684]
## 🐛 Bug

Below error event repeatedly happening on the prod like every 15 ,20 mins. 
Investigate whether it is a real issue or the logger just assuming its an error as the graphql error array is empty 
`{"message":"ClientProvider onError","error":{"name":"CombinedError","graphQLErrors":[],"networkError":{}},"operation":{"key":-623720476,"query":{"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"getMe"},"variableDefinitions":[],"directives":[],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"me"},"arguments":[],"directives":[],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"},"arguments":[],"directives":[]},{"kind":"Field","name":{"kind":"Name","value":"roles"},"arguments":[],"directives":[]},{"kind":"Field","name":{"kind":"Name","value":"email"},"arguments":[],"directives":[]},{"kind":"Field","name":{"kind":"Name","value":"__typename"}}]}}]}}],"loc":{"start":0,"end":53,"source":{"body":"query getMe {\n  me {\n    id\n    roles\n    email\n  }\n}","name":"gql","locationOffset":{"line":1,"column":1}}}},"variables":{},"kind":"query","context":{"url":"/graphql","preferGetMethod":false,"requestPolicy":"cache-and-network","suspense":false,"meta":{"cacheOutcome":"miss"},"authAttempt":false}}}`

## 🦋 Expected Behaviour

Me query shouldn't be logging errors. Should be fixed if there is any issue. 

## 🕵️ Details

This bug requires work with Azure AppInsights on the tablet

## 📋 Steps to Reproduce

1. Access prod site and stay there for more than 15 mins.  Wait until refresh happens. ( I suspect error happens after that) 
2. Check out the AppInsights transaction log filtered by **custom events**

## ✅ Acceptance Criteria

- [ ] investigate if there is any issue with the me query.  
- [ ] if there is an actual error fix the issue  
- [ ] if it is just a false alarm , fix the logger not to log an error event

**Comment by gobyrne** [comment]
Brinda said something about reproducing this locally.

**Comment by vd1992** [comment]
attempting to replicate

- idled for a while on `https://talent.canada.ca/en/search`
- refreshed page
- checked network and console logs

I think this might be what gets logged to App Insights?
appears a chain happens where getMeQuery -> refresh token -> getMeQuery
the first fails authorization and is immediately rerun after token refreshing, the problem would be then the query being executed before the token action

![image](https://user-images.githubusercontent.com/40485260/219139682-39b52ec9-bd76-4b84-9ce4-fb36735f151f.png)

**Comment by esizer** [comment]
So, I have been looking into this and it may be difficult to avoid logging unhelpful errors like this without possibly missing important errors. 

However, I can think of two approach's (one of which i'm unsure if it is even possible).

1. Only log when the error is not empty
2. Categorize empty errors so they can filtered out?

https://github.com/GCTC-NTGC/gc-digital-talent/blob/5c787a10dc609d51fca60e50aae4d5873497c055/frontend/common/src/components/ClientProvider/ClientProvider.tsx#L186-L192

## 1. Prevent logging empty errors

We could do a simple check:

```tsx
if(!isEmpty(error.graphQLErrors) || !isEmpty(error.networkError)) {
 // Log error
}
```

## 2. Categories empty errors

Is it possible to add some sort of way we could filter out empty errors that are less than useful?

```tsx
const isEmptyError  = isEmpty(error.graphQLErrors) && isEmpty(error.networkError);

logger.error(
  JSON.stringify({
    message: `ClientProvider onError${isEmptyError  ? " (empty)" : ""}`,
    error,
    operation,
  }),
);
```
