### ISSUE TITLE
🐛 `DiversityEquityInclusionSection` renders two first-nations-true.png images

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#5686]
## 🐛 Bug

`DiversityEquityInclusionSection` renders two `first-nations-true.png` images.

## 🦋 Expected Behaviour

`DiversityEquityInclusionSection` renders one `first-nations-true.png` image.

## 📋 Steps to Reproduce

1. `npm run storybook`
2. View `User Profile > User Profile Story 1`, `User Profile > User Profile Story 2`, `User Profile > User Profile Story 3` stories
3. Observe two `first-nations-true.png` images

## 📸 Screenshot

![Screen Shot 2023-02-08 at 09 56 12](https://user-images.githubusercontent.com/3046459/217565941-d232e334-77bb-4eb5-9ae0-3f9d7a1945df.png)

## ✅ Acceptance Criteria

- [ ] `DiversityEquityInclusionSection` should render only one of each image for all cases

**Comment by brindasasi** [comment]
We could get this only when calling the api directly. Likelihood is low and impact is low to the user. Iceboxing for now.

**Comment by mnigh** [comment]
Issue superseded by #7360.
