### ISSUE TITLE
✨ Applicant Dashboard - Create page routing and assemble the full page

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#5691]
## ✨ Feature

As a user I want to see my entire dashboard with my profile , experience , applications and qualified recruitment details in one page so that I have a clear picture of my career path with Government of Canada

### Routing

This page will be the new home for logged-in applicants (replacing "my applications"). For that reason, this page should be the first place they are presented with post-login. In a similar fashion, when a user first registers for the platform, after they've completed the onboarding form, they should be brought here. In both cases, if the user is arriving from an "Apply now" button, they should be brought back to that application process instead.

## 🕵️ Details

The routing should be in place, the new nav created and storybook components exist for the hero, the applications and the recruitments. It's time to put it all together and make it real.

## 🎨 Design File

Figma file: https://www.figma.com/file/jHsXzqMfBtomLa1Gom94Y7/Profile-dashboard?node-id=310%3A4163

<details>
  <summary><strong>📸 Screenshot: full dashboard</strong></summary>
  <img src="https://user-images.githubusercontent.com/6960386/217913070-4d3651c3-178a-44d4-a060-4ec67d874114.png" />
</details>

## :stop_sign: Blockers

Blocked by #5690

### Acceptance Criteria
- [ ] Page exists on the  /dashboard url 
- [ ] Page should be under the feature flag "Applicant Dashboard"
- [ ] When the user registers for the first time and completes the introductory form, they are brought to this new UI unless they are registering through an application to an opportunity, in which case they should be directed back to that application
- [ ]  When the user logs in, they are brought to this new UI unless they are coming through an application to an opportunity, in which case they should be directed back to that application
- [ ] Integrate API to show the data for all the components 
- [ ] Page has Hero components at the top, My applications at the middle and My qualified recruitments at the end. 
- [ ] Nav bar should show as per the mock up (search link should stay in the nav ) 
- [ ] Just confirming that you did NOT remove the search link in the Nav

**Comment by petertgiles** [comment]
The route is a little strange.  Our current profile is at `/en/users/{:user_id}/profile`.  Why wouldn't we use `/en/users/{:user_id}/dashboard`?

**Comment by esizer** [comment]
> The route is a little strange. Our current profile is at `/en/users/{:user_id}/profile`. Why wouldn't we use `/en/users/{:user_id}/dashboard`?

That is a good question. I know the move to include the user id in the URL was made a few months ago but I cannot remember why 🤔 

Should this page also include it? @tristan-orourke

**Comment by tristan-orourke** [comment]
My opinion has changed over time, but I now believe that the profile url shouldn't include user_id at all. (See #5413.) The Dashboard and Profile pages aren't for viewing some arbitrary user, they're intended for the logged-in user to view their own info, and exclusively that. We even use the getMe query, making the user_id meaningless anyway. Aside from purely aesthetic concerns, a non-user-specific link is easier for a user to remember, type in directly, and share in a way which is useful to other people.

Note: this is unlike on the admin side, where admins need to view other user profiles. And if there were ever a case where admins needed to view an applicant's dashboard, we could make a different route for that.

**Comment by petertgiles** [comment]
> My opinion has changed over time, but I now believe that the profile url shouldn't include user_id at all.

I think that's fair.  Could we be a little more specific than just /dashboard then?  For example, the site map document as a possible /en/manager/dashboard.  Could we do /user/dashboard or /applicant/dashboard or something?
