### ISSUE TITLE
✨ Update application "cards" on "My applications" to the future dashboard specs

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#5692]
## ✨ Feature

Update application "cards" on "My applications" to the future dashboard specs.

## 🕵️ Details

The dashboard work by @substrae offers a new way to present applications that a user has submitted. This issue is to rebuild the "card" that we use to present them to users.

The "get support" link should be the email associated with the "pool".
It's ok if archiving functionality goes away. We will be replacing it shortly.

## 🎨 Design File

(see epic)

## 📸 Screenshot

New Draft application card:
![image.png](https://images.zenhubusercontent.com/5dc084854553760001149b53/f8929f03-f4b1-4965-bf0c-f3bf49af8701)

New submitted application card:
![image.png](https://images.zenhubusercontent.com/5dc084854553760001149b53/6e6b861f-912f-4828-ae8a-e75008f4f24b)

This is what the cards currently look like:
![image.png](https://images.zenhubusercontent.com/5dc084854553760001149b53/3b15b991-a38f-4edf-ba93-585fe4fc273a)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

Draft Card 
- [ ] Apply By - should show pool expiry date
- [ ] Draft applications show a "Delete this application" link that, when clicked, triggers a dialog asking the user to confirm their decision to delete the application
- [ ] Continue this application - should open the application page in edit mode 

Submitted Card and Application History card
- [ ] Applied On  - show show the application submitted date
- [ ] View my application link -  when clicked, takes the user to the summary of their application
- [ ] Application status should show inside the pill 

All Cards 
- [ ] Clicking on an application's "See job ad" link takes the user to the appropriate job poster page
- [ ] Clicking on an application's "Get support" link triggers the user's configured email client with the relevant recruitment administrator's email address populated
- [ ]  If there is no data on either of the status the cards don't appear and the page remains as it is right now 
<img width="1474" alt="Screen Shot 2023-02-13 at 10 42 44 AM" src="https://user-images.githubusercontent.com/89482910/218504193-6a93d30b-db3f-49e0-9215-74c6c33bc106.png">

**Comment by brindasasi** [comment]
@gobyrne  Under this story if the cards doesn't have data we don't display the card. Is that correct assumption?

**Comment by brindasasi** [comment]
@substrae Could we make this `View My Application` as last link so `See Job Ad`  and `Get Support` can be on the same order ?

**Comment by brindasasi** [comment]
> @gobyrne Under this story if the cards doesn't have data we don't display the card. Is that correct assumption? ( We don't do the null state for the cards with static text as per the epic. Since we don't have the sections here )

Gray answered yes. Updated AC above

**Comment by brindasasi** [comment]
@substrae  @gobyrne Title looks slightly different from existing. 
Stream is missing and Level is prefixed with a comma on the Job title. Does that correct ? 
What is this `(React)  `. Is this a skill or Title itself ?

**Comment by mnigh** [comment]
Is there a reason why a possessive adjective (_my_) is used in one spot and not (_this_) in the other?

"Continue **this** application" versus "View **my** application".

Similar question to https://github.com/GCTC-NTGC/gc-digital-talent/issues/5514.

**Comment by brindasasi** [comment]
> ✨ Applicant Dashboard - Story book for displaying Application status cards in sections

@GCTC-NTGC/designers  any comments on this?

**Comment by brindasasi** [comment]
> Is there a reason why a possessive adjective (_my_) is used in one spot and not (_this_) in the other?
> 
> "Continue **this** application" versus "View **my** application".
> 
> Similar question to #5514.


@GCTC-NTGC/designers  any comments on this?

**Comment by esizer** [comment]
I think we need a much wider discussion about using consistent use of copy across the app. This was brought up in our last retro about how we don't seem to have "one voice" across the app.

Since this issue is sort of medium to high priority, blocking another key story , still waiting on translations using copy from the design and nearing end of sprint, would it make sense to create a ticket about a copy review so we aren't blocked on changing "this" to "my" for now?

**Comment by RM-1978** [comment]
That works for me. We could also flag it as a cognitive accessibility issue.

**Comment by Jerryescandon** [comment]
I think it's safe to assume that this is Lauren's opinion regarding these matters. And when in doubt, side with the possessive.
![image](https://user-images.githubusercontent.com/16977254/220675429-32427dbb-a3c0-4e86-944b-2fa2033714ac.png)

**Comment by patcon** [comment]
<img width="328" alt="Screen Shot 2023-02-27 at 4 23 54 PM" src="https://user-images.githubusercontent.com/305339/221620738-9976477b-48ff-4533-9da7-df537e4108ef.png">
