### ISSUE TITLE
♻️ useCommonLinkStyles does nothing with type = link

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#5704]
## ♻️ Debt/Refactor

The styling tool for links only works with button links. 

## 🕵️ Details

https://github.com/GCTC-NTGC/gc-digital-talent/blob/eb1abe5786e14b934d484a079bc1aa32af4842dc/frontend/common/src/components/Link/useCommonLinkStyles.ts#L21-L36

this is an issue, as it is called for styling purposes by non button links like here
in which case, it does nothing and returns an empty object

https://github.com/GCTC-NTGC/gc-digital-talent/blob/eb1abe5786e14b934d484a079bc1aa32af4842dc/frontend/common/src/components/Link/MenuLink.tsx#L9-L19

## 🙋‍♀️ Proposed Solution

implement a styling function for `type === "link"`

## ✅ Acceptance Criteria

- [ ] styling links of type link
- [ ] ensure components using useCommonLinkStyles have non-empty objects returned

**Comment by petertgiles** [comment]
Not necessary.  Sorry Vachan, my bad.  I should have been more specific in my issue.

**Comment by vd1992** [comment]
I feel it should still be resolved, at the minimum, `<MenuLink>` should not call a function that does nothing
