### ISSUE TITLE
✨ Search page - Style fix

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#5728]
## ✨ Feature

Some minor cosmetic fixes for the Search page

## 🕵️ Details

1. Add space between sections (Work location and Advanced filters)
2. Reduce visual title style of accordions title and subtitle to next lower one. (body if necessary)

![image](https://user-images.githubusercontent.com/16977254/219435981-aac730dc-a048-4383-8024-58fb98a16d1e.png)

## 🎨 Design File

Include a link to the design file (if it exists).

## 📸 Screenshot

![image](https://user-images.githubusercontent.com/16977254/219433371-2cd4d29e-32b9-444e-b4d0-d911f539510f.png)

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Add space between sections (Work location and Advanced filters)
- [ ] Reduce visual title style of accordions title and subtitle to next lower one. (body if necessary)

**Comment by substrae** [comment]
Yeah, either we fix it everywhere here or create a separate issue for updating them centrally that will then take care of this issue automatically.
