### ISSUE TITLE
✨ Applicant Dashboard - Updates to Profile Page

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#5730]
## ✨ Feature

Updates to the profile based on the new Dashboard page

## 🕵️ Details

The dashboard causes a few changes that required to the existing profile page to help with cohesiveness and clarity:
- Remove the "status" section and ensure its removal doesn't impact candidate and admin functionality
- Remove the "My skills and experience" section
- Delete unused My Hiring Pools section in the code
- Update the "On this page" sidebar to reflect section completion, matching the hero area of the dashboard

This work should all be behind the feature flag.

## 📸 Screenshot
<details>
  <summary><strong>📸  Screenshot: full updated profile</strong></summary>
  <img src="https://user-images.githubusercontent.com/6960386/218156006-43562bf8-ade1-45e0-bc64-519433cc2c52.png"/>
</details>

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

### Changes to the profile
- [ ] Feature flag is in place to keep any of these changes from appearing on the profile until we want them to
- [ ] The profile no longer contains a "My status" section
- [ ] The applicant can still successfully apply to opportunities despite "My status" being removed
- [ ] The "My skills and experience" section has been removed and users can now view their resume information via the dashboard hero area (which links to the Skills and experience page)
- [ ] The "On this page" sidebar showcases completion status of each section and matches the look and feel of the dashboard profile summary in the hero area

**Comment by substrae** [comment]
I think updating the central component with the optional ability to show a status (or even just an icon) is the right way to go here.
