### ISSUE TITLE
✨ Applicant Dashboard - Update Nav

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#5741]
## ✨ Feature

Changes to the Nav to go with new Applicant Dashboard

## 🕵️ Details

We're updating the nav as well to reflect the new dashboard. The dashboard link should be on the right (beside login) and the two current links (my application and my profile) are removed.

Leave the "Search" nav link for now though (even though it's not in the "new nav" screenshot below).

New Nav:
![image.png](https://images.zenhubusercontent.com/5dc084854553760001149b53/5495b71b-14b2-43e0-99d3-6260595d1f41)

Current Nav:
![image.png](https://images.zenhubusercontent.com/5dc084854553760001149b53/262084b3-14da-4cce-9bc7-8e9ef5235b8b)

## 📸 Screenshot

Add a screenshot of the new feature (if possible).

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Just confirming that you did NOT remove the search link in the Nav
- [ ] Nav changes are behind a feature flag (removing the feature flag will make the new page visible)

**Comment by brindasasi** [comment]
overlaps with #5691
