### ISSUE TITLE
✨ Applicant Dashboard - Put it all together

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#5742]
## ✨ Feature

As a user I want to see my entire dashboard with my profile , experience , applications and qualified recruitment details in one page so that I have a clear picture of my career path with Government of Canada

## 🕵️ Details

The routing should be in place, the new nav created and storybook components exist for the hero, the applications and the recruitments. It's time to put it all together and make it real.

## 🎨 Design File

Figma file: https://www.figma.com/file/jHsXzqMfBtomLa1Gom94Y7/Profile-dashboard?node-id=310%3A4163

<details>
  <summary><strong>📸 Screenshot: full dashboard</strong></summary>
  <img src="https://user-images.githubusercontent.com/6960386/217913070-4d3651c3-178a-44d4-a060-4ec67d874114.png" />
</details>

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Page exists on the  /dashboard url 
- [ ] Page has Hero components at the top, My applications at the middle and My qualified recruitments at the end. 
- [ ] All sections are filled up with the proper data 
- [ ] Nav bar should show as per the mock up 
- [ ] Page already integrated with Hero area , this story should integrate with applications and recruitment section

**Comment by brindasasi** [comment]
Team decided to do it with https://github.com/GCTC-NTGC/gc-digital-talent/issues/5691
