### ISSUE TITLE
🛠️ nodejs version 16 soon to be end-of-life

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#5746]
## 🛠️ Tooling

Version 16 of nodejs will be end-of-life later this year, [2023-09-11](https://nodejs.org/en/blog/announcements/nodejs16-eol/).

## 🕵️ Details

[Release schedule](https://github.com/nodejs/release#release-schedule) for nodejs.

## 🙋‍♀️ Proposed Solution

Update nodejs to Active LTS version 18

https://github.com/GCTC-NTGC/gc-digital-talent/blob/f979370980504682e506d0892ebb11ad966ccab9/infrastructure/maintenance-container/Dockerfile#L10-L12

https://github.com/GCTC-NTGC/gc-digital-talent/blob/0dd1915f7490d39e67fbb7a64467630600c0964d/package.json#L7

https://github.com/GCTC-NTGC/gc-digital-talent/blob/f979370980504682e506d0892ebb11ad966ccab9/.nvmrc#L1

https://github.com/GCTC-NTGC/gc-digital-talent/blob/00ba90302d8da00ca8375b66698affe561cc7905/infrastructure/bin/deploy.sh#L23

## ✅ Acceptance Criteria

- [ ] project builds and runs the same using nodejs v18

**Comment by vd1992** [comment]
best way to tackle this might just be to pick a version, change references from 16.16.0 to it and push up a draft PR
then see if any checks fail or npm install fails due to engine incompatibility
