### ISSUE TITLE
🧪 Update `e2e` tests to use TypeScript

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#5754]
## 🧪 Tests

I like TypeScript and the safety it provides and think it would be a great idea to use it for our tests as well! 😄 

## 🕵️ Details

We recently[ updated our `cypress.config.js` to be TypeScript](https://github.com/GCTC-NTGC/gc-digital-talent/commit/f387927d33ee024fc8b315b0aa54ca402cde7154). I'm thinking it might be a good time to convert all of our tests to use typescript and reduce our reliance on JavaScript. 

## 🙋‍♀️ Proposed Solution

Follow[ the guide that cypress has in their documentation](https://docs.cypress.io/guides/tooling/typescript-support#Types-for-Custom-Commands).

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt tests were properly updated and remains functional/passing.

- [ ] Convert one spec to typescript
- [ ] All cypress tests still pass
- [ ] Very limited start - just convert one helper file or test to start with
- [ ] Make a new issue afterwards with remainder of work and lessons learned

**Comment by vd1992** [comment]
So what exactly is the issue's goal?
Criterion 1 is at odds with 3 and 4

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/b537e3c3-1f5c-461d-bd8c-f77411eb3b5f)

**Comment by esizer** [comment]
> So what exactly is the issue's goal?
> Criterion 1 is at odds with 3 and 4

Oh, yeah looks like we forgot to update the first one when we reduced the scope! I'll update it 👍

**Comment by petertgiles** [comment]
Approval from team to updated more than one file.
