### ISSUE TITLE
✨ Feature Request: Create minimum process to connect GitHub repo to TMS

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#5786]
## ✨ Feature

We currently have a demo instance of [Weblate TMS](https://weblate.org/en/) (translation management system):
http://demo.translate.talent.c4nada.ca/

It is set up to show how it can work with a small sample repo containing a small set of demo strings, showing how the pre-processing would need to work, and the `WebExtension JSON` file format that must be version-controlled in the repo. This is the sample repo:
https://github.com/patcon/react-intl-example/tree/main-gctalent-manual-ids-test

This issue is to track steps to prepare our actual repo to be demo-able for the team in a way that is comparable to our actual code repo. 

## 🕵️ Details

_Add any additional details that could assist with the development of the new feature._

The TMS server is provisioned via docker-compose using instructions at https://docs.weblate.org/en/latest/admin/deployments.html#docker

It is tentatively provisioned on a DigitalOcean server hosted by patcon using personal account.

There's a simple script to use the weblate API to provision a demo of the above repo: https://gist.github.com/patcon/36ca9220606359b956a7aba640b80e8f

Here's an example of the PR that Weblate will automatically submit when translations have been created in that system:
https://github.com/patcon/react-intl-example/pull/3

## 🎨 Design File

None.

## 📸 Screenshot

<img width="1436" alt="Screen Shot 2023-02-22 at 8 32 51 PM" src="https://user-images.githubusercontent.com/305339/220752211-817d9fd9-9b8a-4073-b6c2-3fea2235fed8.png">

## 🙋‍♀️ Proposed Implementation

The rough steps involve in setup:

- [ ] add the custom extraction formatter script
- [ ] add the custom compilation formatter script
- [ ] rig up custom formatters to work during `intl-*` run-scripts
- [ ] remove `en.json` from gitignores
- [ ] add the en.json files to version control
- [ ] disable auto-updating of generated uuids
- [ ] convert all ICU JSON format files to webextension JSON format
- [ ] add a webhook to the repo to point to weblate's webhook endpoint
- [ ] Add the weblate SSH key as a deploy key on the repo, so weblate can create PRs
- [ ] add [translation badge](http://demo.translate.talent.c4nada.ca/widgets/demo/#svg) to README
- [ ] Deal with any noisy hints that weblate is offering about our production strings (which didn't show up in simple demo)
- [ ] ...

## 🌎 Localization

None.

## ✅ Acceptance Criteria

WIP

- [ ] Criteria 1
- [ ] Criteria 2

## :stop_sign: Blockers

List any issues which must be completed before this one.

```[tasklist]
### Blockers
```

**Comment by patcon** [comment]
convo between patcon and Tristan: maybe try bringing this fwd in a few weeks when flux of trialing GitHub Projects is in the past.

**Comment by tristan-orourke** [comment]
This can be closed, we don't plan to proceed with this right now.
