### ISSUE TITLE
🧪 Upgrade PHPUnit to v10

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#5789]
## 🧪 Tests

New version of PHPUnit released with many breaking changes, needs to be updated manually.

## 🕵️ Details

See: https://github.com/sebastianbergmann/phpunit/blob/main/ChangeLog-10.0.md

First notable one is the removal of `--verbose` flag which we are using.

>**Note**
> This is not urgent, we have until [February 2nd, 2024 when v9 stops receiving bug fixes](https://phpunit.de/announcements/phpunit-10.html#:~:text=PHPUnit%209%20receives%20bug%20fixes%20until%20February%202%2C%202024).

## 🙋‍♀️ Proposed Solution

Work through the breaking changes to upgrade PHPUnit and get it working

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt tests were properly updated and remains functional/passing.

- [ ] PHPUnit is upgraded to `10.*.*`
- [ ] PHPUnit tests are passing locally and in CI

**Comment by petertgiles** [comment]
Closed in #5869
