### ISSUE TITLE
Title case usage on profile page

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#5810]
## 🐛 Bug

The profile page uses inconsistent case for the sections.

## 🦋 Expected Behaviour

As per Josh:  the [GoC content standards say we should be using sentence case exclusively](https://www.canada.ca/en/treasury-board-secretariat/services/government-communications/canada-content-style-guide.html#wp4-1-1) (with the exception of proper nouns/names)

## 📸 Screenshot

![image](https://user-images.githubusercontent.com/8978655/222228644-6fd78b2c-9b79-40f3-94fd-8674582f6c90.png)

## ✅ Acceptance Criteria

- [ ] Profile page uses sentence case for ToC, titles, and edit links
- [ ] The hero cards in the applicant dashboard match

**Comment by mnigh** [comment]
Related https://github.com/GCTC-NTGC/gc-digital-talent/issues/3497
