### ISSUE TITLE
Hide underline from `<abbr>` tag on hero area of landing page

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#5812]
## Description

`<abbr>` tag in the Title provides an underline for all the abbreviations visually. It is kinda look strange in homepage. 
We need to hide the visual of that underline using css without removing the abbr tag. 
Change needs to be done in only on the landing page title. 

![Image](https://user-images.githubusercontent.com/89482910/222236855-c2117fdb-022a-4450-8f82-1fb098bcf457.PNG)

## 🦋 Expected Behaviour

Title  should show up without any visible underline 

## 🕵️ Details

- **Operating System**: Na

me and version (if possible).
- **Browser**: Name and version (if possible).

## 📋 Steps to Reproduce

1. Navigate to the home page in the site 
2. Notice the underline 

## 📸 Screenshot

Add a screenshot (if possible).

## ✅ Acceptance Criteria

- [ ] Home page  title  show up without any underline
- [ ] Home page description and all other pages are NOT impacted

**Comment by mnigh** [comment]
From what I can tell from the [commit](https://github.com/GCTC-NTGC/gc-digital-talent/commit/30a69f30d526b8537756dac5b53600e08edf7b74#diff-e392793b85bbb065a7d311afa0b9b842121920c34dde861919f6cc8732043299R58) history, this was done on purpose.

There is a similar issue created recently about the styling of the `<abbr>` element though: https://github.com/GCTC-NTGC/gc-digital-talent/issues/5785

**Comment by vd1992** [comment]
the easiest way would be to remove the `<abbreviation>` from

https://github.com/GCTC-NTGC/gc-digital-talent/blob/b1efd62ca0dc5a79fe91a6f0a49617969d8273cb/apps/web/src/pages/Home/HomePage/components/Hero/Hero.tsx#L54-L64


or, refactor the `wrapAbbr()` to inject variable styling found here

https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/apps/web/src/utils/nameUtils.tsx#L102
