### ISSUE TITLE
Cypress test admin/pool-candidates often fails

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#5837]
## 🧪 Tests

The admin/pool-candidates test often fails.  Rerunning it frequently allows it to pass

## 🕵️ Details

![image](https://user-images.githubusercontent.com/8978655/222445549-0c22c741-72fc-4d8e-9053-135c3042e7b6.png)

## ✅ Acceptance Criteria

- [ ] Test reliably passes unless there is an actual problem

**Comment by vd1992** [comment]
unless I am mistaken, this one is due to the test pool ending up on page two
the easiest solution would be to search or bump the page size
