### ISSUE TITLE
Turbo overcaching Jest tests

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#5841]
## 🛠️ Tooling

I think Turbo is overcaching Jest tests and missing changes.  If you just change dependencies (including Jest and plugins) without changing code the Jest results are cached.

## 🕵️ Details

Right now "test" is configured as
```json
    "test": {
      "outputs": ["coverage/**"],
      "dependsOn": ["^build"]
    },
```

I don't think Jest actually uses the built files - should it actually depend on that step?  It should probably be set to input the code and package.json, like "build".  Should "test" actually do any caching at all?

## 🙋‍♀️ Proposed Solution

Disable caching on test.  Or update dependencies to depend on code and dep changes properly.

## ✅ Acceptance Criteria

- [ ] "test" runs Jest without caching if there are file changes.

**Comment by petertgiles** [comment]
It's a big drag that if you up update a test you have to rebuild `web` every time.  👎

**Comment by esizer** [comment]
> It's a big drag that if you up update a test you have to rebuild `web` every time. 👎

Actually, do we even need the `dependsOn` at all? I think this could be just:

```json
"test": {
  "cache": false
},
```

**Comment by petertgiles** [comment]
> Actually, do we even need the `dependsOn` at all?

I'm not sure, maybe not?
I'm not sure about just disabling cache anymore though.  If you change a test in web you don't want to rerun the tests for all the packages, right?

**Comment by esizer** [comment]
> I'm not sure, maybe not?
> I'm not sure about just disabling cache anymore though. If you change a test in web you don't want to rerun the tests for all the packages, right?

I guess we could just read [the documentation](https://turbo.build/repo/docs/handbook/testing) 🤣

**Comment by petertgiles** [comment]
Closing in favour of #5900
