### ISSUE TITLE
🐛 Accessibility Bug Report: Font size and contrast compliance with WCAG 1.4.3

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/gc-digital-talent#5850]
## 🐛 Bug

Check all 

## 🦋 Expected Behaviour

All font sizes conform with WCAG 1.4.3 and WAI criteria. 

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Name and version (if possible).
- **Browser**: Name and version (if possible).

## 📋 Steps to Reproduce

1. Navigate through a sample of 5 pages and examine the foreground image, icon or text.
2. Confirm font-size conforms with the 1.4.3 conformance criteria.  

## 📸 Screenshot

![image.png](https://images.zenhubusercontent.com/625076b8f67c446dd188ffe5/8f6f554a-397e-4642-8bea-53bc436f2d6f)

## 🙋‍♀️ Proposed Solution

- The closer text color is to the background color, the harder it is to read. To figure out what colors your website is using, use a color selector tool to grab a color off your website.
- Color numbers are specified using hexadecimal values. You’ll be able to get its hexadecimal code (for example, #efefef) using a color selector tool. You can then enter this into a color contrast checker and instantly know what your color contrast ratio is.
- Having adequate color contrast makes it easier for everyone, not just people with low vision, to read your content.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- Text sufficiently stands out from the background.
- All text meets a 4.5:1 color contrast ratio regardless of what size your text is.

**Comment by esizer** [comment]
@substrae Do you have any ideas for this?

**Comment by substrae** [comment]
@esizer 

I'm not sure I follow. Is the problem here contrast or font-size?

**Comment by RM-1978** [comment]
This colour gradient was updated after the test in the screenshot with a mustard yellow that now passes. 
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/101275838/f513dad6-651e-441d-b930-1eb67e5b796a)
