### ISSUE TITLE
Chromatic - theme unstable in stories

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#5871]
## 🐛 Bug

Chromatic is triggering false diffs when the theme randomly changes in stories.

## 🦋 Expected Behaviour

The theme should be stable when snapshotting stories in Chromatic

## 🕵️ Details

I've seen it happen in:
- 404 Page:Default
- Digital Talent:Default
- Browse Pools Page:Default 375px
- Browse Pools Page:Default 1366px

## 📋 Steps to Reproduce

1. Let Chromatic run
2. Review the diffs

## 📸 Screenshot

![image](https://user-images.githubusercontent.com/8978655/223747768-56077c49-f39d-4473-b1e1-a275243b2c2f.png)

## 🙋‍♀️ Proposed Solution

- Explicitly set the theme in each story?

## ✅ Acceptance Criteria

- [ ] Chromatic no longer triggers false diffs due to theme randomly changing.

**Comment by esizer** [comment]
We **_should_** be able to do the following where you pick the default theme and colour mod to render (have not tested this with chromatic yet).

```tsx
Default.parameters = {
  theme: {
    key: "default" | "admin" | "iap",
    mode: "pref" | "light" | "dark",
  },
};
```

**Comment by vd1992** [comment]
I am not entirely sure this was solved

see 
https://www.chromatic.com/build?appId=61e099a1bb1465003a73d3ce&number=4509
and
https://www.chromatic.com/build?appId=61e099a1bb1465003a73d3ce&number=4507

which are from after the merger of #5912 which had this as its diff
https://www.chromatic.com/build?appId=61e099a1bb1465003a73d3ce&number=4503
