### ISSUE TITLE
🧪 `DepartmentTest.php` intermittently fails

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#5873]
## 🧪 Tests

The PHPUnit test `DepartmentTest` is failing intermittently due to unique constraints.

## 🕵️ Details

I believe it is because I did not define a `department_number` in creation during the test so it if it gets created with `1` then the later test fails.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/7587d2b1a393b7c19d5f172fec3b7208a7f62d93/api/tests/Feature/DepartmentTest.php#L54-L60

## 🙋‍♀️ Proposed Solution

Update the department creation to specific department numbers to avoid collisions.

```php
$this->department = Department::factory()->create([
  'department_number' => 10
]);

$this->departmentToBeDeleted = Department::factory()->create([
  'department_number' => 20
]);
```

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt tests were properly updated and remains functional/passing.

- [ ] `DepartmentTest.php` consistently passes with no unique constraint collisions

**Comment by petertgiles** [comment]
closed in #5869

**Comment by esizer** [comment]
I am not 100% confident that closed this 😢 Definitely makes it less likely to fail but the error was coming from the factory creating duplicate `department_number` along with the non-unique `uuid`.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/cd6978f76929fa2e0fe96295dd112f40db8a1980/api/database/factories/DepartmentFactory.php#L27

**Comment by esizer** [comment]
Looks like this was not solved 😢 

https://github.com/GCTC-NTGC/gc-digital-talent/actions/runs/4437239271/jobs/7786669668#step:6:235
