### ISSUE TITLE
♻️ Update pool creation with teams

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#5878]
## ♻️ Debt/Refactor

Need to update pool creation to use teams properly. 

## 🕵️ Details

As a placeholder, pool creation automatically connects to the DCM team. This will require updating to connecting a pool to the appropriate team.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/0021af526932cde208fc6dd42da9d31583c0f585/apps/web/src/pages/Pools/CreatePoolPage/CreatePoolPage.tsx#L254-L260

## 🙋‍♀️ Proposed Solution

This can be a bit tricky as a user could be a pool operator for more than one team, in which case,
 `me -> roleAssignments -> poolOperator -> team.id`  
wouldn't be a safe choice.

We don't have a figma design for this, so add the new select input to the form in a way that looks consistent.

## ✅ Acceptance Criteria

- [ ] Instead of automatically adding the dcm team id, Team is selected in a dropdown element on the Create Team page
- [ ] Dropdown is populated with the teams the user belongs to as a pool operator

**Comment by tristan-orourke** [comment]
That's right. We've discussed adding a select input to the Create Teams page populated with all the teams the user belongs to as  a pool operator.
