### ISSUE TITLE
Update Chromatic infrastructure

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#5898]
## 🛠️ Tooling

Chromatic needs to have an infrastructure update.

## 🕵️ Details

![image](https://user-images.githubusercontent.com/8978655/224046772-d27115a4-a122-4b29-a66c-2852e29c7c9f.png)
https://www.chromatic.com/docs/infrastructure-upgrades

## 🙋‍♀️ Proposed Solution

Run the update manually.

## ✅ Acceptance Criteria

- [ ] Infrastructure was updated
- [ ] Nothing is broken

**Comment by mnigh** [comment]
> * [ ]  Nothing is broken

If something did break, are we even able to revert the upgrade?

**Comment by petertgiles** [comment]
> If something did break, are we even able to revert the upgrade?

I don't know, probably not.  :laughing: I guess it'll be your job to try to fix it or put additional issues on the board.
