### ISSUE TITLE
Dependabot high security alerts

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#5901]
## 🐛 Bug

Dependabot has two high current security alerts

## 📋 Steps to Reproduce

https://github.com/GCTC-NTGC/gc-digital-talent/security/dependabot?q=is%3Aopen+severity%3Ahigh

## 🙋‍♀️ Proposed Solution

Hopefully it's as simple as `npm audit fix --force` :shrug: 

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] No high security alerts

**Comment by tristan-orourke** [comment]
May go away with storybook update

**Comment by vd1992** [comment]
High security issues resolved, none appear
