### ISSUE TITLE
🐛 Search page candidate counts mis-match 

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#5913]
## 🐛 Bug

Search page issue again 🙃 

## 🦋 Expected Behaviour

Count per pool should sum to total

## 🕵️ Details

.

## 📋 Steps to Reproduce

1. head to /search, after building off main
2. start adding in filters
3. observe total candidate count and candidate count per pool card

## 📸 Screenshot

![image](https://user-images.githubusercontent.com/40485260/224389744-0bac0f0a-2fd4-4670-b800-150deb43b248.png)

![image](https://user-images.githubusercontent.com/40485260/224389904-675e674b-31d3-49b9-a848-a060068bfc2a.png)

re-seeding

![image](https://user-images.githubusercontent.com/40485260/224391363-fae245b7-68e9-491e-817e-c30124b1f900.png)

## 🙋‍♀️ Proposed Solution

countApplicants is higher in number due to not filtering out suspended candidates

Pool Candidate has a scope for suspended, which is then used in count by pool

![image](https://user-images.githubusercontent.com/40485260/224391922-de4d6976-1e02-40bc-bacb-ff699b4482df.png)

User does not check for suspended in a scope, this would be done by count applicants

![image](https://user-images.githubusercontent.com/40485260/224392311-6b049fc2-33cd-4a78-96a0-aeaca406d76a.png)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] count per pool sums to total count
- [ ] queries return correct users, as in scopes are correctly assigned

**Comment by tristan-orourke** [comment]
I think the fix for this would be to update User.scopeAvailableInPools to also check for suspended applications.

**Comment by vd1992** [comment]
> I think the fix for this would be to update User.scopeAvailableInPools to also check for suspended applications.

the countApplicants query does not use that scope though

![image](https://user-images.githubusercontent.com/40485260/224425386-70cbc7ea-d76a-437a-ae76-948722bb44e3.png)

**Comment by tristan-orourke** [comment]
But ApplicantFilterInput does:
![image](https://user-images.githubusercontent.com/4313717/224426943-9723c9f0-b57c-4c99-a3e2-00370d479d7a.png)

When we use the `pools` field in ApplicantFilterInput, we're saying "filter out users who don't have a valid application in these pools". We use the availableInPools scope to implement that. We no longer want to consider an application valid if its suspended.

**Comment by vd1992** [comment]
correct
man, this search page trips me up sometimes
