### ISSUE TITLE
🐛 Admin users/:id and users/:id/profile not available to Pool Operator and Request Responder

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#5926]
blocked by #5781 , #5783 

## 🐛 Bug

Request Responders and Pool Operators aren't able to view user profiles. Discovered by @vd1992 and first raised [here](https://github.com/GCTC-NTGC/gc-digital-talent/pull/5858#issuecomment-1464727216).

## 🦋 Expected Behaviour

Request Responders should be able to view Applicant profiles (meaning /users/:id and /users/:id/profile), and Pool Operators should be able to view those pages if the user has applied to a pool in their team.

## 🕵️ Details

Currently there are two problems: client-side role checking in Router.tsx, and backend permissions for the applicant.poolCandidates graphql query.

## 📋 Steps to Reproduce

1. Create two pools in two different teams
2. As an applicant, apply to both pools
3. As a user with request_responder role, but not platform_admin, try to go to en/admin/users/:id where :id is that of the applicant user. From there you should be able to view User Profile, but not Edit User account.
4. As a user with the pool_operator in on of the pool teams, you should be able to go to /pools, view candidates in the pool, accept the user into the pool, then follow the link to view the user's profile. In the Pool Status section, you should not see any pools not on your team. From there you should be able to view User Profile, but not Edit User account.

## 📸 Screenshot

Pool Operator gets unauthorized error if the user has applied to any pools in another team.
![Pool Operators gets unauthorized error](https://user-images.githubusercontent.com/4313717/224820774-325ef380-c7c6-4e40-9372-55713a668a48.png)

Pool Operators should see pool status section, but for pools in their own team.
![image](https://user-images.githubusercontent.com/4313717/224822030-5c71a124-d5cb-4ad2-a838-4261a6605202.png)

## 🙋‍♀️ Proposed Solution

In the Router.tsx route tree, a RequestAuth section cannot be more restrictive than its nested routes, or it will block them anyway. Therefore, `path: ":userId"` and its index route should allow all three kinds of admin roles.

The Pool Operators getting an auth error because of the pool status section is more complicated. Several possible approaches:
1. Change the query so that it only returns PoolCandidates in teams which the user is allowed to see. This might require a new graphql query defined, maybe one which accepts a user-id and a list of valid team-ids?
2. Maybe its not so bad if a PoolOperator can see which other pools a user has applied to? Maybe we could make an equivalent of UserPublicProfile for PoolCandidate, or use heavy use of field-level permissions on PoolCandidate, so that _some_ data is available to PoolOperators regardless of the pool.
3. Easiest thing would be to just not render that whole section, for Pool Operators, and not run that part of the query.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] a user with request_responder role should be able to view all Applicant profiles (meaning /admin/users/:id and /admin/users/:id/profile)
- [ ] a user with pool_operator role should be able to view Applicant profiles for users who applied to pools in their team (meaning /admin/users/:id and /admin/users/:id/profile), even if the user also applied to pools in other teams.

**Comment by esizer** [comment]
Attempted to start this but I do not believe it is possible to complete until the `TeamPolicy` and `PoolPolicy` are merged since it relies on those.

**Comment by esizer** [comment]
More details in https://talent-cloud.slack.com/archives/C0259G6KXJ6/p1679507007980029
