### ISSUE TITLE
🐛 Request page - Empty requests should enforce required fields

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#5933]
## 🐛 Bug

DCM has been receiving requests with multiple pools indicated. This should not be possible. When submitting this test request, I only selected group and level, but not a stream, even though it was marked as required, it wasnt enforced for empty requests.

Additionally: When reviewing the request on admin side, ONE applicant showed up. Which means something is off in the results. If there was at least one candidate, it should not have given me an empty request option. 🤔 (see 2nd screenshot) maybe a different issue.

## 🦋 Expected Behaviour

 Even when an empty request is submitted, we should enforce the Classification + level + Stream selection. This would vastly reduced the pools that show up on the request page

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Name and version (if possible).
- **Browser**: Name and version (if possible).

## 📋 Steps to Reproduce

1. ...
2. ...

## 📸 Screenshot

![image](https://user-images.githubusercontent.com/16977254/225115090-7644bd31-a4a2-4fbe-98b8-1bad04e8e3c7.png)

![image](https://user-images.githubusercontent.com/16977254/225115381-ff949a6b-33c1-494c-a570-556e4e339d48.png)

## 🙋‍♀️ Proposed Solution

After #5644 is completed, we'll be able to associate the stream and classification to the request properly. At that point, we can simply avoid adding any pools to empty requests.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Criteria 1
- [ ] Criteria 2

## 🛑 Blockers

Blocked by #5644

**Comment by vd1992** [comment]
for the empty request part of the issue, I feel this can happen downstream of #5644 
the completion of that issue may solve this as a side-effect, or at least make this issue doable

**Comment by esizer** [comment]
> for the empty request part of the issue, I feel this can happen downstream of https://github.com/GCTC-NTGC/gc-digital-talent/issues/5644
the completion of that issue may solve this as a side-effect, or at least make this issue doable

> so blocked by https://github.com/GCTC-NTGC/gc-digital-talent/issues/5644 would be my say

You are correct @vd1992 . The reason more than on pool is attached to a request here is because we do not associate classification or job stream with search requests. So, when an empty request gets submitted we attach all pools and classifications available with the information we do know.

We added #5644 so we can eventually do away with the work around noted previously 👍
