### ISSUE TITLE
✏️ VS Code workspace extension recommendations

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#5938]
## ✏️ Documentation

Add some frequently used VS Code extensions as recommendations for the workspace.

- [Docker](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker)
- [French - Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-french)

## 🕵️ Details

https://github.com/GCTC-NTGC/gc-digital-talent/blob/e7b30c14ca7355de5ca727d05e9bbe9ed4ff492c/.vscode/extensions.json#L2

## 🙋‍♀️ Proposed Copy

- `"ms-azuretools.vscode-docker"`
- `"streetsidesoftware.code-spell-checker-french"`

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the documentation has been added/updated appropriately.

- [ ] `.vscode/extensions.json` lists these new recommendations

**Comment by petertgiles** [comment]
I installed Axe Linter and noticed that it has its own yml file for properly linting custom components.  It might be worth spinning that one off and getting a PR with the configuration already done.
https://docs.deque.com/linter/4.0.0/en/linting-custom-components
