### ISSUE TITLE
⚙️ Build `Inline Editable Form` component

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#5940]
# ⚙️ Summary
The pattern enables users to edit the form text directly on the same page instead of navigating them to another page for editing the text. This is useful when the user may want to make a single edit without the need to refresh the entire form to make it editable.

### [[Visit the Figma file](https://www.figma.com/file/BXYVsu1fo9LS2IySJDUINY/Applicants---Application?node-id=653%3A59471&t=1mqKGZguvjMWyJZF-0)]

**For all layout and spacing guidance, including how this component should respond on smaller devices, please see the Figma file.**

# 💡 Interaction states

## Initial mode (without data) 
![image](https://user-images.githubusercontent.com/89482910/225451393-c0282ea2-a7df-4503-b294-8380a0242761.png)

## Editable mode
![image](https://user-images.githubusercontent.com/89482910/225452114-a18498b9-61bb-4c94-befb-59594d7e812d.png)

## Editable mode - Error state
![image](https://user-images.githubusercontent.com/89482910/225454556-a39eb31f-ae7d-4937-8746-77c9b31c8b90.png)

## Display mode
<img width="548" alt="Screen Shot 2023-03-15 at 5 53 09 PM" src="https://user-images.githubusercontent.com/89482910/225452300-87639d20-81e7-4bf0-87e8-68daccf22f92.png">

## Display mode - Error state 
<img width="530" alt="Screen Shot 2023-03-15 at 6 01 39 PM" src="https://user-images.githubusercontent.com/89482910/225453788-e28790a2-e8b6-4852-a1de-d6505655f5d5.png">

# 🛠️ Properties

## Mode 
Initial, Display, Editable 

## ✅ Acceptance Criteria
- [ ] Component has initial mode, display mode, editable mode 
- [ ] Component can have nested Inline Editable Form component as child as well 
- [ ] added in storybook 
- [ ] axe-linter check for accessibility
- [ ] focus goes to first editable input on the edit mode
- [ ] this is a generic component and so show off this component with simple field list ( doesn't have to be like in the mock up )  

## ✅ Accessibility checklist
- [ ] Tap targets are adequate on smaller screens
- [ ] Color contrast for all modes and states has been checked and cleared
- [ ] Zoom has been considered as layout changes occur
- [ ] `alt` text has been identified and labelled
- [ ] Non-standard states or interactions have been described and provided accessible design context

**Comment by brindasasi** [comment]
@GCTC-NTGC/designers  I can't remember what was the conclusion about `Edit this section`  and `This section is missing required information` copy in these mock ups.

Should we be descriptive and include the section name ? 
OR 
Just `Edit` on the screen as it shows beside the section name  but the screen reader text should say `Edit + <section name>`

**Comment by tristan-orourke** [comment]
Given that this is a generic Higher Order Component which is meant to wrap other components to give them the switching functionality, I don't think we actually need to worry about the specifics of any text right now. That should be something that could be passed in.

Similarly, it seems to me like the errors, and the initial null-state, should be the concern of the display component, not the Inline Form wrapper component, since determining errors (and even if everything it should be considered null) requires knowledge about this form's specific data.

**Comment by tristan-orourke** [comment]
Thoughts about implementation - seems to me like the child components need access to the status (display/editable) and a function to trigger a toggle. I can see this being implemented as either a [Higher Order Component](https://reactjs.org/docs/higher-order-components.html), or with a little Context which both child components access with [useContext](https://beta.reactjs.org/reference/react/useContext).

**Comment by tristan-orourke** [comment]
High priority, since this is a blocker
