### ISSUE TITLE
⚙️  Build Tree view component

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#5941]
# ⚙️ Summary
A tree view widget presents a hierarchical list.

**For all layout and spacing guidance, including how this component should respond on smaller devices, please see the Figma file.**
### [[Visit the Figma file](https://www.figma.com/file/BXYVsu1fo9LS2IySJDUINY/Applicants---Application?node-id=653%3A63152&t=1mqKGZguvjMWyJZF-0)]

# Initial Mode 
![image](https://user-images.githubusercontent.com/89482910/225457337-32270fd8-053f-4846-bc9d-61220c6b16ac.png)

# Display Mode   
![image](https://user-images.githubusercontent.com/89482910/225458112-e9ac1479-2be2-4ef0-909f-578159b7131c.png)

# 🛠️ Properties

## Root Element
Text element to be displayed on the root level 

## Error Text
Error text to be displayed on the root level 

## Children
List of card components that to be displayed on the leaf level 

## 🌎 Localization

English Copy 

> This required skill must have at least 1 résumé experience associated with it.

French Copy

[Place the french copy here] 

English Copy 

> Connect a résumé  experience

French Copy
[Place the french copy here] 

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Component should accept a generic root component which is displayed first
- [ ]  Child components are displayed in a list below the root component, with some space on the left
- [ ]  A line extends down from the left end of the root component down as far as the last child component
- [ ]  The line extends across to child components. This branch can be switched off for individual children
- [ ]  Work with @substrae on getting the lines CSS 

## ✅ Accessibility checklist
- [ ] Tap targets are adequate on smaller screens
- [ ] Color contrast for all modes and states has been checked and cleared
- [ ] Zoom has been considered as layout changes occur
- [ ] `alt` text has been identified and labelled
- [ ] Non-standard states or interactions have been described and provided accessible design context

**Comment by tristan-orourke** [comment]
> Error text to be displayed on the root level

Actually, from the mock-up, it looks to me like the error text is part of a third level, which is below the root, but not connected to a branch

**Comment by tristan-orourke** [comment]
@substrae Question about the horizontal branches - where should they touch the child cards? In the middle of their height? A fixed distance from their top?

**Comment by substrae** [comment]
@tristan-orourke without playing around with the CSS, my guy says a fixed distance from the top, ideally centered with the title of the item passed to it (though that might be tough given we can pass literally anything)
