### ISSUE TITLE
✨Backend: Save step state in application in database

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#5985]
## ✨ Feature

Allow the user to save which steps they've done clicked through on an application.

## 🕵️ Details

This should be saved to the PoolCandidate (ie Application) object. 

## 🎨 Design File

The names of the steps can be decided based on the Application design:
https://www.figma.com/file/BXYVsu1fo9LS2IySJDUINY/Applicants---Application?node-id=636-59839&t=kmjTtgdWWyX0ddZ9-0

## 📸 Screenshot

[Screenshot with steps](https://user-images.githubusercontent.com/89482910/225649515-6dd646ec-8a02-414d-b157-3531ca5acff7.png)

## 🙋‍♀️ Proposed Implementation

Suggested model change:
```
PoolCandidate {
  ...
  submittedSteps: ApplicantStepEnum[]
}
```
New field can be implemented as jsonb column in database.

We also need a new updateApplication mutation, since currently we only have create and submit. Currently the only thing that can be changed without submitting _is_ the submittedSteps, as the most of the "application" actually edits the user profile. How exactly to implement the mutation is left to the implementer, but @petertgiles and @tristan-orourke discussed defining a connectSubmittedStep field based on [Nested Mutations](https://lighthouse-php.com/5/eloquent/nested-mutations.html#hasmany), so that adding submitted steps would work more like connect than sync (meaning users couldn't remove steps after adding them). This would require some mode-level code, probably an eloquent mutation.

updateApplication mutation should be protected by the PoolCandidatePolicy.update method, but for this to work, we'll also need to define a new permission and assign it to the applicant role: update-own-draftApplication.

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] new field added to model, schema, database, factory
- [ ] mutation added which allows applicant to add but not remove submitted steps
- [ ] new mutation can only be called by the owning applicant
- [ ] phpunit tests which test that it works, and that it can only be done by correct users (probably need to update some PoolCandidatePolicy tests as well)

## :stop_sign: Blockers

**Comment by tristan-orourke** [comment]
Adding high priority because this blocks #5961
