### ISSUE TITLE
✨ Make Pools table accessible to Platform Admins

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#5999]
## ✨ Feature

The Pools table page has client-side role checking that restricts it to Pool Operators. Open it up to Platform Admins, but allow them to view all pools instead of only team pools.

## 🕵️ Details

Platform Admins need to see all Pools so they can find Draft Pools which need publishing. (We ended up deciding that Platform Admins are the only role able to publish.) 

When a Pool Operator visits this page they should only see pools in their teams - that's the current behaviour. But Platform Admins should see all Pools, without being in all teams. 

## 🎨 Design File

Include a link to the design file (if it exists).

## 📸 Screenshot

Add a screenshot of the new feature (if possible).

## 🙋‍♀️ Proposed Implementation

I had been trying to avoid this, but I think now that the only way to implement this is to use different queries depending on user role. All Pools if the user has Platform Admin role, and via roleAssignments otherwise. Note that hooks cannot be conditional, but the urql query hooks allow for [pausing execution](https://formidable.com/open-source/urql/docs/api/urql/).

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Platform Admins can visit the Pools table page
- [ ] If user is not a platform admin, they see only pools in their team.
- [ ] If the user is a platform admin, or a platform admin AND a pool operator, they see all pools.
- [ ] Jest tests or integration tests for the two different queries?

## 🛑 Blockers

Blocked by #5781

**Comment by vd1992** [comment]
would something like this work?

auth/roles check on index pool page then conditionally render PoolTableApi1 or PoolTableApi2 
one wrapper limits pools returned to what you have access to, while the other wrapper runs an allPools query

![image](https://user-images.githubusercontent.com/40485260/226421159-813b000a-f66d-49f3-ba59-a165dc834019.png)

![image](https://user-images.githubusercontent.com/40485260/226421261-62e62e00-0b0d-4d2f-a550-c25b2a92963d.png)

**Comment by tristan-orourke** [comment]
Yes, that would also work!
