### ISSUE TITLE
Upgrade to PHP 8.2

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#6003]
> __Warning__
> PHP 8.2 will be unavailabe for the Ubuntu images until Mantic 23.10.  Then it can be used for the maintenance container.

## ♻️ Debt/Refactor

We are required to update our php App Service apps in azure to PHP 8.2 by Nov 25 2024. We should update our docker image at the same time, to confirm locally that everything will still work.

Let's upgrade to PHP 8.2.  It has been out for a few months and is available in Azure.

## 🕵️ Details

https://www.php.net/releases/8.2/en.php

![image](https://user-images.githubusercontent.com/8978655/226343125-6bdae01c-4956-4559-8e78-8f89b4f4f979.png)

## ✅ Acceptance Criteria

- [x] Webserver container uses PHP 8.2
- [x] Maintenance container uses PHP 8.2
- [x] Github CI uses PHP 8.2
- [ ] all three Azure servers use PHP 8.2
- [ ] Everything functions as before

**Comment by petertgiles** [comment]
Putting this back in the product backlog with a blocked label and a description.  I'm getting too many weird npm errors with the _php_ image and I don't want to mess around with _ondrej_ PPA.  Best to wait for _mantic_, I think.

https://packages.ubuntu.com/search?keywords=php

**Comment by mnigh** [comment]
> PHP 8.2 will be unavailabe for the Ubuntu images until Mantic 23.10. Then it can be used for the maintenance container.

We probably don't want to upgrade to version 23 as it is an odd version number meaning it is an interim release with a very short amount of support. We will likely want to wait until April 2024 unless upgrading to PHP 8.2 is a requirement.

> LTS or ‘Long Term Support’ releases are published every two years in April. LTS releases are the ‘enterprise grade’ releases of Ubuntu and are used the most. An estimated 95% of all Ubuntu installations are LTS releases.

> Every six months between LTS versions, Canonical publishes an interim release of Ubuntu, with 23.04 being the latest example. These are production-quality releases and are supported for 9 months, with sufficient time provided for users to update, but these releases do not receive the long-term commitment of LTS releases.

REF: https://ubuntu.com/about/release-cycle

**Comment by petertgiles** [comment]
I'm not too worried about using a non-LTS version of Ubuntu in our maintenance container.  It's not actually used for serving the app, just running dev tools.

**Comment by petertgiles** [comment]
The docker image ubuntu:mantic is now available.  Unblocking.

**Comment by petertgiles** [comment]
Azure says our PHP 8.1 image will deprecate on Nov 25, 2023.  I'll pin this issue as high priority.
