### ISSUE TITLE
🐛 Pool Operators can't view pool candidates profile when the pool candidate has any draft application 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#6005]
## 🐛 Bug

Pool Operators can't view pool candidates profile when the pool candidate has any draft application 

## 🦋 Expected Behaviour

Pool operators should be able to view the applicant profile regardless of whether they have draft application or not. 

## 🕵️ Details

**Error Received :** 
```
graphQLErrors":[
         {
            "message":"This action is unauthorized.",
            "path":[
               "applicant",
               "poolCandidates"
            ],
            "extensions":{
               "category":"authorization"
            }
         }
      ],
```
Query that fails : `GetViewUserData` 

**Root cause** 
public function view(User $user, PoolCandidate $poolCandidate)
    {

        // If the user owns the application, we do not care about status
        if ($user->id === $poolCandidate->user_id && $user?->isAbleTo("view-own-application")) {
            return true;
        }

        $isDraft = $poolCandidate->isDraft();

        // Exit early if user can view any draft application
        if ($isDraft) {
            return $user->isAbleTo("view-any-draftApplication");
        }

        if(!$isDraft) {
            if($user->isAbleTo("view-any-submittedApplication")) {
                return true;
            }

            $poolCandidate->loadMissing('pool.team');
            $candidatePoolTeam = $poolCandidate->pool->team;
            if ($user->isAbleTo("view-team-submittedApplication", $candidatePoolTeam)) {
                return true;
            }
        }

        // Noting passed for deny access
        return false;
    }
## 📋 Steps to Reproduce

1. Login as Applicant
2. Create 2 applications, Leave 1 as draft and submit the other application for a job poster 
3. Login as Pool Operator of that team that job poster belongs to 
4. Try to view the applicant profile 

## 📸 Screenshot

Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

add notDraft scope to Applicant.poolCandidates 

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Pool operators should be able to view the applicant profile regardless of whether they have draft application or not. 
- [ ] Take a closer look at any queries which return or types which include PoolCandidates, and decide if they also need additional scopes.

## 🛑 Blockers

Blocked by {issue numbers}

**Comment by tristan-orourke** [comment]
I suspect Pool.poolCandidates, countPoolCandidates, and searchPoolCandidates all need the notDraft scope as well
