### ISSUE TITLE
🐛 Notes input label

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#6030]
## 🐛 Bug

Label is a bit broken

## 🕵️ Details

Formatting issue?

## 📋 Steps to Reproduce

1. go to pools, pick one, go to view pool candidates
2. click "view profile" on one
3. observe notes section

## 📸 Screenshot
![image](https://user-images.githubusercontent.com/40485260/226989312-f49d4fa2-16e4-44f5-ba0f-239ed283df24.png)

## ✅ Acceptance Criteria

- [ ] label fixed

**Comment by mnigh** [comment]
> I think the problem is that the function used is returning HTML instead of plain text. It should use the `getFullPoolAdvertisementTitleLabel` function instead of `getFullPoolAdvertisementTitleHtml` function.

I was [wrong](https://github.com/GCTC-NTGC/gc-digital-talent/pull/6032#issuecomment-1480042116)!
