### ISSUE TITLE
Guard search against long strings

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#6031]
## 🐛 Bug

The app crashes when a long string is entered into search input.

## 🦋 Expected Behaviour

App should not crash and should not allow such a long string to be entered.

## 📋 Steps to Reproduce

1. Generate a long string (e.g. 60 paragraphs worth of [lorem ipsum](https://www.lipsum.com/))
2. Navigate to https://talent.canada.ca/en/search
3. Paste long string into field with label **Search skills by keyword**

## 📸 Screenshots
![Screen Shot 2023-03-22 at 13 17 20](https://user-images.githubusercontent.com/3046459/226986668-e6e5c756-40c3-417f-a92c-422a7cfb3270.png)

![Screen Shot 2023-03-22 at 13 17 43](https://user-images.githubusercontent.com/3046459/226986663-db479cf0-b6c6-49d7-b3fa-bef8cc9e480e.png)

## 🙋‍♀️ Proposed Solution

Limit inputs to certain amount of characters to avoid app crashing on the front end. For example, using the [`maxlength`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/maxlength) attribute for `input` and `textarea`. Back end validation might also be worthwhile.

## ✅ Acceptance Criteria

- [ ] inputs going to matchStringCaseDiacriticInsensitive have max length validation
- [ ] matchStringCaseDiacriticInsensitive has a guard against long strings

**Comment by petertgiles** [comment]
Any idea where this is crashing?  It looks like the input is being turned into a regex.  Is this just multiselects or all inputs?  If we apply a blanket maxlength to every input and textarea what would a reasonable default be?

**Comment by mnigh** [comment]
> Any idea where this is crashing? It looks like the input is being turned into a regex. Is this just multiselects or all inputs? If we apply a blanket maxlength to every input and textarea what would a reasonable default be?

The **Search skills by keyword** input does indeed use a regex: the `matchStringCaseDiacriticInsensitive` function. In other input elements where there is no regex, there is a more graceful failure within GraphQL and therefore doesn't crash the app, for example:

<img width="1439" alt="Screen Shot 2023-04-06 at 10 41 19" src="https://user-images.githubusercontent.com/3046459/230415877-234b1539-224f-412f-81f4-a9e3a6c91f86.png">

As for blanket `maxlength`, not exactly sure and interested in what others have to say, maybe:

- `input`: 1000 characters
- `textarea`: 10000 characters

**Comment by petertgiles** [comment]
I think putting a limit in the matchStringCaseDiacriticInsensitive function and a validator on any input that goes there is an easy and safe fix.  I'm less confident on a blank change to every input.
