### ISSUE TITLE
🐛 Pool Advertisement Apply Button Spacing

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#6034]
## 🐛 Bug

The apply button lacks top margin on mobile screens causing it to look a little odd.

## 🦋 Expected Behaviour

Apply button should not touch the well above it on mobile screens

## 📋 Steps to Reproduce

1. Navigate to a Pool Advertisement
2. Reduce screen width to a phone size
3. Note the apply button touching the well

## 📸 Screenshot

![Screenshot 2023-03-22 142547](https://user-images.githubusercontent.com/4127998/227002528-143d09cc-e5b9-4565-bbc7-bb886baa8742.png)

## 🙋‍♀️ Proposed Solution

1. Add `margin-bottom` to well or,
2. Add a `column-gap` to the flex container

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Apply button does not touch the well above it on mobile screens

**Comment by tristan-orourke** [comment]
Resolved as part of #6318
