### ISSUE TITLE
✨ Admin: Screening questions added to Edit Pool page.

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#6059]
## ✨ Feature

Add screening questions to the Edit Pool page.

## 🕵️ Details

Pool Operators can add screening questions to pools. They can add up to 3 screening questions. Each question requires an english and a french text field.

## 🎨 Design File

https://www.figma.com/file/BXYVsu1fo9LS2IySJDUINY/Applicants---Job-application?node-id=1276%3A70682&t=BRqSTphBAHyNwnho-1

## 📸 Screenshot

![image](https://user-images.githubusercontent.com/16977254/230458846-b451f5fc-9d7c-4cbb-a5af-06addba3756f.png)

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

- [ ] Admins editing a pool can add new screening questions or edit or remove existing ones.
- [ ] No more than three questions can be added
- [ ] Each question must have english and french text
- [ ] Each question has a textarea input with a word limit (100 words)
- [ ] It is possible to submit a pool with no screening questions
- [ ] When the save button is pressed, questions are saved to the api
- [ ] After the pool is published, it is not possible to edit questions

## 🛑 Blockers

Blocked by #6021 (soft block)

**Comment by petertgiles** [comment]
@Jerryescandon Could you please take a quick peek at the remove button?  Perhaps it could be under the pair of inputs and be red?

**Comment by Jerryescandon** [comment]
Well, I pulled @substrae for a look at the entire thing and we basically did a whole review of "Repeater" as a component, I will add the entire notes from that discussion to this issue and update the look and feel, mobile version and a11y considerations.

**Comment by Jerryescandon** [comment]
Updated the issue for yall

**Comment by petertgiles** [comment]
Awesome, thanks!  We'll discuss this in scrum on Tuesday since this greatly increases the scope of the issue.  We might have to build this page without the new component first or we might pull this issue out of sprint to build the component first.
