### ISSUE TITLE
✨ Application Revamp: Education Requirements page

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#6070]
Education Requirements page. For now the requirements we display can be hard coded. Note that saved experience ids might not exist anymore.

## ✨ Feature

Education Requirements page. For now the requirements we display can be hard coded. 

## 🕵️ Details

- [ ] First the user must select whether they meet the criteria through work experience or education. Before that, the "connect experience" section shows a null state.
- [ ] If "I meet the post-secondary option" is selected, checkboxes for all the user's Education experiences are shown.
- [ ] If "I meet the applied work experience" option is selected, checkboxes are displayed for _every_ experience.
- [ ] Page can be initialized with existing values
- [ ] If a previously selected experience no longer exists, don't error - just ignore the non-existent experience
- [ ] When "I've met the criteria" is clicked, save the selected option and experiences to the Application, along with saving that the Education Requirements step has been submitted, and then continue to the next step.
- [ ] When "Save and quit for now" is clicked, save the selected option and experiences to the Application, and return to the Applicant Dashboard. Do NOT save that the Education Requirements step has been submitted.

## 🎨 Design File

https://www.figma.com/file/BXYVsu1fo9LS2IySJDUINY/Applicants---Job-application?node-id=636-59839&t=uo7LWN6EXZuqdJna-0

## 📸 Screenshot

Check figma for more states.

![Step 4 - Min  education and experience](https://user-images.githubusercontent.com/4313717/230426990-a3d1fee0-2206-445f-a09d-fae9451341b6.jpg)

<details>
  <summary>Education experience null state</summary>
  <img src="https://user-images.githubusercontent.com/6960386/231870836-471c3db8-c438-41eb-8467-4cdef4427cfb.png">
</details>

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] This page exists at the proper route (behind feature flag)
- [ ] On this page, page subtitle and breadcrumbs appear correctly
- [ ] The inner contents of the page (so not the hero and stepper layout) have a storybook story
- [ ] First the user must select whether they meet the criteria through work experience or education. Before that, the "connect experience" section shows a null state.
- [ ] If "I meet the post-secondary option" is selected, checkboxes for all the user's Education experiences are shown.
- [ ] If "I meet the applied work experience" option is selected, checkboxes are displayed for _every_ experience.
- [ ] Page can be initialized with existing values
- [ ] If a previously selected experience no longer exists, don't error - just ignore the non-existent experience
- [ ] When "I've met the criteria" is clicked, save the selected option and experiences to the Application, along with saving that the Education Requirements step has been submitted, and then continue to the next step.
- [ ] When "Save and quit for now" is clicked, save the selected option and experiences to the Application, and return to the Applicant Dashboard. Do NOT save that the Education Requirements step has been submitted.
- [ ] Invalid state in the application triggers stepper error state

## 🛑 Blockers

Blocked by #6069 (soft blocked)

**Comment by petertgiles** [comment]
@substrae What does this page look like if the user has no education experiences on their profile?

**Comment by petertgiles** [comment]
@substrae If you have selected a choice, not saved, but navigate away and back should it save the state?

**Comment by petertgiles** [comment]
Josh will provide a well with copy design for the null state.

**Comment by substrae** [comment]
@petertgiles 

I've updated both the Figma file and the issue summary about with a screenshot. Let me know if you need anything else!

**Comment by brindasasi** [comment]
I'm unassigning myself on this , as I am into getting prod data and will be off tmo and possibly day after tmo.
