### ISSUE TITLE
Cypress test for application revamp

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#6078]
## 🧪 Tests

We should have a Cypress test that works through the new application process in the same way that a real user would, step-by-step, to avoid regression bugs in the future.

## ✅ Acceptance Criteria

- [ ] A Cypress test that works through the new application process, step-by-step
- [ ] The test exercises all the major sections of the flow
- [ ] The test is reliable and does not depend on the pre-existing state of the database.
- [ ] in scope
    - [ ] clicking stepper to jump ahead
    - [ ] hacking url to get jump ahead
- [ ] revert env change as seen in comment below
- [ ] not in scope
    - [ ] ?

**Comment by vd1992** [comment]
As well, once the Cypress test is up, replacing the prior application test, revert this
https://github.com/GCTC-NTGC/gc-digital-talent/blob/3848f92dbaaaa699c5d6f875572a4bde90ab9d17/api/.env.example#L97
