### ISSUE TITLE
Wrong icon on pool advertisement page

### ISSUE THREAD

**Issue by Elisa0122** [GCTC-NTGC/gc-digital-talent#6085]
## 🐛 Bug

The same icon was used for two different headings.

## 📋 Steps to Reproduce

1.  go to this page https://uat-talentcloud.tbs-sct.gc.ca/en/browse/pools/0e5d6e48-5667-4ccf-8bbe-20126218fa1b
2. scroll to the bottom

## 📸 Screenshot

Add a screenshot (if possible).
![Screenshot 2023-03-24 at 4 30 18 PM](https://user-images.githubusercontent.com/83783101/227632576-7457c689-898c-4ef6-bafa-b9dee9861112.png)

## 🙋‍♀️ Proposed Solution

Figma:
![image](https://user-images.githubusercontent.com/8978655/230402261-9033bd6f-5601-4bd0-a5b3-13b202139271.png)
https://www.figma.com/proto/N9NoPunkqaynjsi89Wrbh0/Direct-Intake---Poster-and-application?node-id=226-4567&starting-point-node-id=226%3A4567

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Hiring Policies has a different icon than Contact and administration

**Comment by petertgiles** [comment]
Thanks, Elisa!  I found the design in Figma showing the correct icons.

**Comment by Elisa0122** [comment]
Thank you Peter to take the time to dive into Figma to find the icon next time I will do it myself do avoid you wasting your time.

**Comment by petertgiles** [comment]
No problem.  :smile: Yay teamwork!

**Comment by mnigh** [comment]
It seems as if that Figma file is using v1 of heroicons and our project uses v2. The icon referenced in the Figma file, `clipboard-check`, no longer exists in hericons v2.

## Screenshots (heroicons versions)

![Screen Shot 2023-04-25 at 12 20 54](https://user-images.githubusercontent.com/3046459/234341300-ab187826-78f8-4bee-bb2f-03ccf300788f.png)

![Screen Shot 2023-04-25 at 12 21 18](https://user-images.githubusercontent.com/3046459/234341293-48e4d1d7-ac91-41ed-9f2f-d95e62156d6c.png)

@Jerryescandon Would `clipboard-document-check` be an acceptable alternative to `clipboard-check`? If not, could you provide the name of an alternate v2 heroicon?

## Screenshot
![Screen Shot 2023-04-25 at 12 21 57](https://user-images.githubusercontent.com/3046459/234341464-21d02cdb-704e-4892-ae34-202853fd8450.png)

**Comment by Jerryescandon** [comment]
Yeah this one works fine.
