### ISSUE TITLE
❓ How many users in production have set themselves to inactive, while still having active statuses in pools

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#6091]
## ❓ Question

We're intending to do away with the user specific "Not interested in opportunities" setting, which filters users out of searches. CMO is concerned that if some users have made use of this setting already, and we stop paying attention to it, they might start getting unwanted job offers again.

If we could do a database query to discover which users in pools have set themselves to inactive, then we could at least manually change their pool status if necessary.

## 🕵️ Details

Add any additional details that could assist with answering the question posed.

## ✅ Acceptance Criteria

(optional) A set of assumptions which, when tested, verify that the question has been properly answered.

- [ ] List of pool candidate ids where the pool candidate status is considered active (not draft, not placed, not expired, not screened out) but the user is inactive

**Comment by vd1992** [comment]
running this SQL query would give you the number of users this would concern

```
SELECT COUNT(*)
FROM "users"
JOIN "pool_candidates" ON ("pool_candidates"."user_id" = "users"."id")
AND "users"."job_looking_status" = 'INACTIVE'
AND "pool_candidates"."pool_candidate_status" in ('NEW_APPLICATION', 'APPLICATION_REVIEW', 'SCREENED_IN', 'UNDER_ASSESSMENT', 'QUALIFIED_AVAILABLE')
```

and here is the query flipped around a bit, returning all the pool candidate ids to be concerned with

```
SELECT pool_candidates.id
FROM "pool_candidates"
JOIN "users" ON ("pool_candidates"."user_id" = "users"."id")
AND "users"."job_looking_status" = 'INACTIVE'
AND "pool_candidates"."pool_candidate_status" in ('NEW_APPLICATION', 'APPLICATION_REVIEW', 'SCREENED_IN', 'UNDER_ASSESSMENT', 'QUALIFIED_AVAILABLE')
```

**Comment by vd1992** [comment]
and then update those pool candidates, if you want to, with

```
UPDATE pool_candidates
SET pool_candidate_status = 'EXPIRED'
FROM users
WHERE pool_candidate_status in ('NEW_APPLICATION', 'APPLICATION_REVIEW', 'SCREENED_IN', 'UNDER_ASSESSMENT', 'QUALIFIED_AVAILABLE') 
AND users.job_looking_status = 'INACTIVE'
```

**Comment by vd1992** [comment]
is that then it for this issue?

**Comment by tristan-orourke** [comment]
Thanks! We gotta run it on production now.

**Comment by vd1992** [comment]
> Thanks! We gotta run it on production now.

I'll leave it to Peter (because if there is a glaring flaw in those statements he'll know)

**Comment by petertgiles** [comment]
Here's the breakdown of statuses in prod.  I'll send Tristan the list of 16 pool candidates with an inactive user status privately.

|user_job_looking_status |  pool_candidate_status   | user_count|
|-------------------------|--------------------------|------------|
| ACTIVELY_LOOKING        | DRAFT                    |        129|
| ACTIVELY_LOOKING        | EXPIRED                  |        277|
| ACTIVELY_LOOKING        | NEW_APPLICATION          |         15|
| ACTIVELY_LOOKING        | PLACED_INDETERMINATE     |        222|
| ACTIVELY_LOOKING        | PLACED_TERM              |         31|
| ACTIVELY_LOOKING        | QUALIFIED_AVAILABLE      |        743|
| ACTIVELY_LOOKING        | QUALIFIED_UNAVAILABLE    |        120|
| ACTIVELY_LOOKING        | QUALIFIED_WITHDREW       |         13|
| ACTIVELY_LOOKING        | REMOVED                  |         69|
| ACTIVELY_LOOKING        | SCREENED_OUT_APPLICATION |        151|
| ACTIVELY_LOOKING        | SCREENED_OUT_ASSESSMENT  |          8|
| ACTIVELY_LOOKING        | UNDER_ASSESSMENT         |          2|
| INACTIVE                | EXPIRED                  |          2|
| INACTIVE                | QUALIFIED_AVAILABLE      |         16|
| OPEN_TO_OPPORTUNITIES   | DRAFT                    |         10|
| OPEN_TO_OPPORTUNITIES   | NEW_APPLICATION          |          4|
| OPEN_TO_OPPORTUNITIES   | QUALIFIED_AVAILABLE      |         35|
| OPEN_TO_OPPORTUNITIES   | REMOVED                  |          1|
| OPEN_TO_OPPORTUNITIES   | SCREENED_OUT_APPLICATION |          9|
| OPEN_TO_OPPORTUNITIES   | SCREENED_OUT_ASSESSMENT  |          2|
|                         | DRAFT                    |         65|
|                         | QUALIFIED_AVAILABLE      |          1|
|                         | SCREENED_IN              |          1|
|                         | SCREENED_OUT_APPLICATION |         16|
|                         | UNDER_ASSESSMENT         |          2|
