### ISSUE TITLE
🐛 Bug - Candidate list not populating for Pool managers when viewing manager requests

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/gc-digital-talent#6094]
## 🐛 Bug

if the pool manager is reviewing manager request, they have to activate the filter modal and show the results to be able to see the matching candidates. 

## 🦋 Expected Behaviour

When the pool user pulls up a request, the candidate list appears automatically.
## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Name and version (if possible).
- **Browser**: Name and version (if possible).

## 📋 Steps to Reproduce

1. Pull up a manager request
2. View lack of candidates
3. Activate and show results for auto populated filter (with no modification)
5. View new appearance of the list of candidates 

## 📸 Screenshots
![image](https://user-images.githubusercontent.com/101275838/228255989-d194f479-0702-4308-b785-c66a6b63afef.png)

![image](https://user-images.githubusercontent.com/101275838/228256328-b3deed76-ec85-4d79-b8e7-5f27e87cf703.png)

![image](https://user-images.githubusercontent.com/101275838/228256456-c931940b-5fee-468f-bc44-d3129b6b858f.png)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ]  Candidate list appears when the pool manager pulls up the request. 

## 🛑 Blockers

This issue  may be resulting from something related to the Teams changes.

**Comment by tristan-orourke** [comment]
This must have been resolved at some point.
