### ISSUE TITLE
Fix web config deploy in the writable home root

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#6095]
### Discussed in https://github.com/GCTC-NTGC/gc-digital-talent/discussions/5866

<div type='discussions-op-text'>

<sup>Originally posted by **mnigh** February 27, 2023</sup>
## ❓ Question

Do we still need to "find the web config in the writable home root" or is can this be removed?

## 🕵️ Details

I cannot find any other reference to `config-web.js` in the codebase.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/cb304b872cc32a3b8766616c117fce691ae9ed10/infrastructure/conf/nginx-conf-deploy/default#L90-L93
</div>

## :camera: Screenshot

![image](https://user-images.githubusercontent.com/8978655/228251518-99da3e5a-ca63-43cc-a953-fef7530d2d63.png)

Acceptance Criteria:
- [ ] Add config-web.js back into post-deploy script (removed in https://github.com/GCTC-NTGC/gc-digital-talent/commit/43f2eeee1b87e44e193fc750e5290b5be4dd6250)
- [ ] Ensure the post-deploy script successfully copies it fresh into an Azure apps-svc

**Comment by tristan-orourke** [comment]
Yep, we need to add that back in 😂
