### ISSUE TITLE
🐛 Search Page estimated candidate count is not correct 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#6142]
## 🐛 Bug

During UAT, search page gave estimated candidates as 1 but when we submit the request and open in the view request page it showed more than 1 candidates ( like 4)  

## 🦋 Expected Behaviour
Estimated candidates should match the count of candidates shown in the pool candidates table. 

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Name and version (if possible).
- **Browser**: Name and version (if possible).

## 📋 Steps to Reproduce

1. ...

2. ...

## 📸 Screenshot
![image (17)](https://user-images.githubusercontent.com/89482910/228909405-dc386021-cd41-4aee-84bc-9494652a24ed.png)
![image (16)](https://user-images.githubusercontent.com/89482910/228909398-8eacc433-4340-4eb7-afbc-7f59293eaf74.png)

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Estimated candidates should match the count of candidates shown in the pool candidates table. 

## 🛑 Blockers

Blocked by {issue numbers}

**Comment by brindasasi** [comment]
I'm guessing this is related to this as well https://github.com/GCTC-NTGC/gc-digital-talent/issues/6094

**Comment by vd1992** [comment]
request table does not filter by `expectedClassifications` when you load the table

![image](https://user-images.githubusercontent.com/40485260/228973488-03484ab9-c7db-4872-bc36-4a90554ece1d.png)

it does filter them when you are creating a request

![image](https://user-images.githubusercontent.com/40485260/228973565-777e5f90-3802-4f4d-a5ec-7c1fedd58f90.png)

I think your PR about connecting classification to a request should take care of this issue as a side-effect

**Comment by tristan-orourke** [comment]
Probably fixed.
