### ISSUE TITLE
⚙️ New multi-card component on Manager Home Page

### ISSUE THREAD

**Issue by Elisa0122** [GCTC-NTGC/gc-digital-talent#6148]
# ⚙️ Summary

### [Manager Home Page-version 7](https://www.figma.com/file/6Unzr74GyScHAxiAt5KyVR/Manager-Home-Page?node-id=195-14887&t=U9TL3HKFwc0bgQN8-0)

This component will be used for the Manage your own career section on the manager page

**For all layout and spacing guidance, including how this component should respond on smaller devices, please see the Figma file.**

## ✅ Design checklist

- [x] Default component
- [x] Dark mode component
- [x] Component variants
- [x] Dark mode component variants (if applicable)
- [x] Foundational design info (e.g. color info, icons, helpful values)
- [x] Mobile (`base` query) layout and space diagram
- [x] Desktop (`p-tablet` query or larger) layout and space diagram
- [x] Accessibility considerations
- [x] Hover states (if applicable)
- [x] Dark mode hover states (if applicable)
- [ ] Focus states (if applicable)
- [ ] Dark mode focus states (if applicable)

## ✅ Accessibility checklist

- [x] Tap targets are adequate on smaller screens
- [x] Color contrast for all modes and states has been checked and cleared
- [x] Zoom has been considered as layout changes occur
- [x] `alt` text has been identified and labelled
- [ ] Non-standard states or interactions have been described and provided accessible design context

# 🛠️ Properties
please see the Figma file.

Multi-card component includes a list of expandable areas and the card section that is displayed for the selected item.

Each card (expandable area) has a pre-defined content layout:
- Heading
- Text content
- Image
- Image alt-text
- Button (optional)

# 💡 Interaction states
![Screenshot 2023-03-31 at 12 23 59 PM](https://user-images.githubusercontent.com/83783101/229176471-59837893-160b-4396-8f9d-011cd0745325.png)

## Hover
![Screenshot 2023-03-31 at 12 24 32 PM](https://user-images.githubusercontent.com/83783101/229176571-4b58d5ab-20a7-475f-9ed9-ba57fd9143ba.png)

# 🥰 Accessibility

**Comment by mnigh** [comment]
@GCTC-NTGC/designers is this issue still being worked on?

**Comment by mnigh** [comment]
> @GCTC-NTGC/designers is this issue still being worked on?

@substrae is this issue still being worked on or can it be closed as not planned?

**Comment by substrae** [comment]
@mnigh @BrookeCameron 

I think Brooke was working on this specifically, so you'll have to chat with her.

**Comment by BrookeCameron** [comment]
@mnigh this can be closed as we moved in a different direction. Thanks!
