### ISSUE TITLE
🐛 In unusual circumstances, it is possible for pool unauthorization to crash the Admin User profile page

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#6149]
## 🐛 Bug

User Profile page breaks for some users on Admin side, because the user is unauthorized to view applicant.poolCandidates.[x].pool. 

## 🦋 Expected Behaviour

A Pool Operator user should be able to view the user profile of any user who applied to their pools. We assumed the applicant.poolCandidates.pool query would be safe, since any pools applied to should be public. However, legacy data from the early days of the app, like manager-created applciations, may break this assumption.

## 📋 Steps to Reproduce

1. Log is as an admin on UAT
2. Try to view the Same Testee user.

## 📸 Screenshot

Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

~Add authorizedToView scope to PoolCandidate.pool and PoolCandidate.poolAdvertisment~ 
NOPE! Turns out you can't use scope directive on FIELD_DEFINITIONs.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] If pool operator doesn't have access to view the pool for some reason, the query should return null for that pool but should not include any errors.

## 🛑 Blockers

Blocked by {issue numbers}

**Comment by brindasasi** [comment]
> Turns out we were seeing this in production because the pool was soft-deleted!

just correcting its on UAT. Production doesn't have any pool as soft-deleted yet. So we are good for now. This will become an issue when they delete any pool in future.

**Comment by petertgiles** [comment]
Discussion on best solution here:
https://github.com/GCTC-NTGC/gc-digital-talent/discussions/6158

**Comment by mnigh** [comment]
@tristan-orourke after [discussion](https://github.com/GCTC-NTGC/gc-digital-talent/discussions/6158), is this issue still relevant or can it be closed?

**Comment by tristan-orourke** [comment]
Closing as not an issue on production
