### ISSUE TITLE
🐛 `nullSelection` option has inconsistent format (ellipses vs none)

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#6153]
Raised by @vd1992 in https://github.com/GCTC-NTGC/gc-digital-talent/pull/6147#pullrequestreview-1367749532

## 🐛 Bug

`nullSelection` text is inconsistent, sometimes with trailing ellipses and sometimes without: 
- `Select a classification`
- `Select a classification...`

## 🦋 Expected Behaviour

Remove ellipses

## 📋 Steps to Reproduce

1. View any dropdown with nullSelection enabled.

## 📸 Screenshot

![](https://user-images.githubusercontent.com/40485260/229250541-dc902955-de0b-40e6-a42e-5764bdc838a8.png)

## 🙋‍♀️ Proposed Solution

Propose removing ellipses, since less french-english grammar/conventions to navigate translation process. No loss from not having them. (E.g. translators removing the ellipses, etc.)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Ellipses removed
- [ ] Translations updated

**Comment by petertgiles** [comment]
@Jerryescandon desfam decision?

**Comment by petertgiles** [comment]
Decision: remove the ellipsis
