### ISSUE TITLE
How should we identify a user in a support ticket?

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#6154]
## ❓ Question

We would like to submit a user_id with a support ticket if the user is logged in.  Should this use the unique_external_id field, or should it use a custom field? Talk to Marc D'Onofrio about this.

## ✅ Acceptance Criteria

- [x] Work with Marc to decide exactly how to identify the logged-in user in a support ticket.
- [x] Update #4190 with a clear plan.

"Timebox" : Email/Teams/Slack conversation with Marc

**Comment by mnigh** [comment]
Is @marc-donofrio still the person to discuss this with now that he is on this team or is there another person to chat with about this?

**Comment by mnigh** [comment]
@marc-donofrio agrees with using the unique_external_id field.
