### ISSUE TITLE
Perf - reduce initial JS bundle size

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#6161]
The slowest part of most page loads is the initial JS bundle.  Can this file be reduced in size?

- Are there any deps that can be removed?
- Can anything be lazy loaded that is currently loaded up front?

Notes:
- We only really care about the prod bundle, the size of the dev bundle is secondary
-  #1597 might inspire some analysis
- some overlap with #3638

Eric's note:
> I wonder if we could try and split off more code than just the pages themselves thinking We could also run[ webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer) to see if anything can be shaken out more or split off into its own bundle.

## ✅ Acceptance Criteria

- [ ] Prod initial bundle analyzed
- [ ] Any "easy wins" to reduce bundle size implemented
- [ ] Any useful long-term solutions arising from analysis added to the board

**Comment by vd1992** [comment]
Ran the bundle analyzer to check it out, neat stuff

main chunk overview, size visible in picture for it ~500kb gzip

![image](https://user-images.githubusercontent.com/40485260/231898040-ede91f05-df79-422f-9446-fc6cbdc1e559.png)

**Comment by vd1992** [comment]
If you could pull out just the insights, and not load all heroicons in the app.js file, that's 30% of the bundle right there
the analyzer lets you look at other dist files too, but there are so many and they are so small it is overwhelming and not that worth it

![image](https://user-images.githubusercontent.com/40485260/231900266-7b933cc5-9715-4f27-8691-c17883981a17.png)

**Comment by vd1992** [comment]
The only other thing of note is on the live site this font appears to be download 4 times?

![image](https://user-images.githubusercontent.com/40485260/231903026-871faa1b-7852-4f18-9516-64328803f258.png)

![image](https://user-images.githubusercontent.com/40485260/231903064-7810e70a-5d3e-49bc-9c52-1847463e4f3d.png)

**Comment by petertgiles** [comment]
Wow, cool analysis, @vd1992 !  I agree, that's a huge chunk for icons.  It would be nice to just import the icons we need, like we do with Lodash.  Also agree that it would be good to lazy load Application Insights, if possible.  

I wouldn't worry too much about the other .js bundles.  It's the initial bundle that's critical since the user is staring at a blank screen while that downloads and executes.

The font thing is weird.  I noted it in [my initial _slow load times_ issue](https://github.com/gctc-ntgc/gc-digital-talent/issues/6071#issuecomment-1492040013).  I didn't pursue it further since it happens near the end of the load and has generous caching.
