### ISSUE TITLE
✨ Copy update on search page result counts

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#6174]
## ✨ Feature

Add the word approximately to cards in the search page, e.g. from:
"There are X matching candidates..." to
"There are approximately X matching candidates..."

## 📸 Screenshot

![image](https://user-images.githubusercontent.com/16977254/229824233-3ead2570-2e59-410d-a4ea-793ad2c1866e.png)

## ✅ Acceptance Criteria

- [ ] Copy updated on search page result counts
- [ ] Pluralization respected

**Comment by mnigh** [comment]
@Jerryescandon is the approximately applied even for the case of zero results? Is the following what you had in mind?

## zero
There are approximately 0 matching candidates in this pool.

## one
There is approximately 1 matching candidate in this pool.

## two
There are approximately 2 matching candidates in this pool.

Something about the one result case reads strangely, but I think it is grammatically correct 🤷.

**Comment by Jerryescandon** [comment]
Yeah I think its correct too.
