### ISSUE TITLE
✨ Update Search page title and description

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#6175]
## ✨ Feature

Update the text on the Search page

### OLD:

![image](https://user-images.githubusercontent.com/16977254/229829706-8b0b7f90-3c0d-41be-a4fd-ee4717d12906.png)

### NEW:

```
Search the GC Digital Talent database

About the GC Digital Talent database

This talent database is open to most departments and agencies. Candidates in the database vary from just starting their career to seasoned professionals with several years of work experience. There are several ongoing recruitment processes, which means new candidates are being added every week.
```

## ✅ Acceptance Criteria

- [ ] Copy updated on search page

**Comment by mnigh** [comment]
Related https://github.com/GCTC-NTGC/gc-digital-talent/issues/5369
