### ISSUE TITLE
🛠️ Storybook build directory warning in CI

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#6189]
## 🛠️ Tooling

A warning about the build directory for Storybook is observed in CI

## 🙋‍♀️ Proposed Solution

Some solutions are suggested in the warning message

## ✅ Acceptance Criteria

- [ ] Warning message no longer appears

## 📸 Screenshot

https://github.com/GCTC-NTGC/gc-digital-talent/actions/runs/4610144766/jobs/8148245226#step:8:61

![image](https://user-images.githubusercontent.com/40485260/229925919-35b4be36-29cb-4754-b78f-3cedb8a0b612.png)

**Comment by mnigh** [comment]
## Possible solution
Change `"build-storybook": "storybook build", ` to `"build-storybook": "storybook build -o storybook-static",`
https://github.com/GCTC-NTGC/gc-digital-talent/blob/5fe11924397e368a2cff03eb716692835cad5518/apps/web/package.json#L20

**Comment by mnigh** [comment]
👀 https://storybook.js.org/docs/api/cli-options#api-commands

> Passing options to these commands works slightly differently if you're using npm instead of Yarn. You must prefix all of your options with --. For example, npm run storybook build -- -o ./path/to/build --quiet.
