### ISSUE TITLE
🐛 The allPools query on the Admin Pools page is crashing (server out of memory)

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#6190]
## 🐛 Bug

The pools table isn't loading because the API server runs out of memory when executing the allPools query. This only happens with higher numbers of pools.

## 🦋 Expected Behaviour

allPools query should execute without errors and in a reasonable time.

## 🕵️ Details

This depends on the number of pools. The error didn't happen when I had ~30 pools, but it did happen at ~130. I originally saw this on UAT, which has ~130 pools.

I'm pretty sure this is happening because we've added a kind of circular nesting in the allPools query in indexPoolsOperations.graphql, which causes the size of the query output to explode:
```
pools {
  team {
    pools { ... }
  }
}
```

## 📋 Steps to Reproduce

1. (if running docker) enter the webserver cli: `docker-compose exec -w /home/site/wwwroot/api webserver sh`
2. enter the Laravel CLI: `php artisan tinker`
3. seed a bunch of pools: `Pool::factory()->count(100)->create(['team_id' => Team::first()->id])`
4. log in as admin@test.com
4. go to http://localhost:8000/en/admin/pools

## 📸 Screenshot

Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

Remove the nested `pools` block from allPools in indexPoolsOperations.graphql

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] The Admin / Pools page loads correctly for a platform admin when there are ~200 pools

**Comment by vd1992** [comment]
Can confirm I noticed the `allPools` query to already be noticeably slower than other queries. https://github.com/GCTC-NTGC/gc-digital-talent/issues/6071#issuecomment-1492560252
Didn't think it'd start crashing already at the 130 pool mark. 😬
