### ISSUE TITLE
📐 Manager home page

### ISSUE THREAD

**Issue by BrookeCameron** [GCTC-NTGC/gc-digital-talent#6193]
# ⚙️ Summary

### [[Visit the Figma file]](https://www.figma.com/file/6Unzr74GyScHAxiAt5KyVR/Manager-Home-Page?type=design&node-id=463-17310&mode=design&t=8FwSvypZvt4uJ2b3-4)

This is a homepage for managers to inform them how they can use GC Digital Talent. This page is broken into five sections with key tasks for the managers

## 💾 Files and resources

Page URL: https://talent.canada.ca/manager

Files are in each section with relevant alt-text

## 📸 Screenshot
<img width="402" alt="Screenshot 2023-07-10 at 11 48 01 AM" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/9bd4606e-0373-4af9-b8c5-308f50ec0f7b">

# ✅ Requirements

- [ ] Header
- [ ] What we can do for you
- [ ] Create a profile
- [ ] Manage your career
- [ ] The Directive on Digital Talent 

## 🧢 Section 1: Header

Using the same header as the 'user' homepage but with a new image
Heading: Managers community
Subheading: Grow your career and find talent for your team.
Update button copy to: Find talent and Directive responsibilities

Image: 
![AdobeStock_172684190_vignette](https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/af2e0904-8158-42d6-9ea1-5e9e1422c920)
Alt text: two people co-working at a table looking at a laptop and phone. 

## 📸 Screenshot
<img width="801" alt="Screenshot 2023-07-10 at 11 55 51 AM" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/e80c1684-1843-4df3-8607-a56b6ff594eb">

## ✨ Section 2: What we can do for you

Component: content block group component
Context: an overview of how the managers can use our tool and quick links to each tool, think of this as a summary for the page

### Content block 1

Header: Find talent
Body copy: Search our database to find fully qualified talent, ready to hire without further competition. Work with our team to finalize your HR documentation so you can make an offer and get talent in place quickly and easily.
button copy: Find talent
Button link: https://talent.canada.ca/en/search 

### Content block 2

Header: Run a recruitment process
Body copy: Work with our team to run your own recruitment process on the GC Digital Talent platform and take advantage of modern features like our applicant tracking system, skills-based hiring, and equity advancement approaches.
Button copy: Contact us 
Button link: open email to gctalent-talentgc@support-soutien.gc.ca with "I'm interested in running a recruitment process" as the subject line

### Content block 3

Header: Gain data insights
Body copy: Coming Fall 2023 
Check out our new Digital Talent Data Portal for trends, insights and ideas to strengthen your own talent planning and recruitment strategies.
Button copy: Learn more 
Button link: https://talent.canada.ca/en/directive-on-digital-talent

📸 Screenshot:
<img width="805" alt="Screenshot 2023-07-10 at 11 56 05 AM" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/d104fd39-fd40-409b-9aac-58b3eed49b8e">

##
 🌊 Section 3: Create a profile 

Component: Create a profile hero from the main GCDT Homepage

Please note: The image and copy is different from the main GCDT Homepage 

Copy: Your profile is at the heart of the platform. Tell your story, show how you developed your skills, and use your profile to apply for jobs.  Whether you’re hunting for a job now or just thinking about the future, a strong profile is your path to new opportunities.
Button copy: Create a profile
Button links to: https://talent.canada.ca/en/login-info?from=%2Fen%2Fusers%2Fme

Image: 
![profile_hero_banner_4](https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/13862613-5122-46ce-94a9-495682a37eaf)
alt text: smiling person looking at laptop.

##📸 Screenshot 
<img width="803" alt="Screenshot 2023-07-10 at 11 56 30 AM" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/d5976b03-70b7-41d0-a36e-eb6d253622f5">

## 💼 Section 4: Manage your career

Component x3 cards

### Card 1: 
Header: Get hiring experience
Body copy: New to being a manager? Looking to gain some experience in hiring and learn more about HR processes? 
Put your name forward to spend a few hours participating on an interdepartmental team assessing candidates and running job processes on the GC Digital Talent platform.
Button copy: Contact Us 
Link: open email to gctalent-talentgc@support-soutien.gc.ca with "I'm interested in gaining hiring experience" as the subject line
Image: 
![AdobeStock_385944020](https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/a723bf11-f6e6-48f9-9ee8-18aa316d9512)
Image alt text: a diverse group of five people all huddled around one laptop.

### Card 2: 
Header: Apply for manager jobs 
Body Copy: Check out the most recent manager recruitment processes for specific opportunities or apply to ongoing recruitment in any of the IT generic work streams. Check back often for new opportunities. 
Button copy: Browse jobs 
Button Link: Will link to Manager jobs if no specific jobs link to the main browse jobs page
Image: 
![AdobeStock_188238803](https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/f6128e33-514c-4da2-9fbf-2bef929fcb9b)
Image alt text: Group of four diverse women sitting around a table with documents.

### Card 3: 
Header: Ready for an executive role?
Body copy: Wondering whats next for your career? Interested in being considered for executive opportunities in the GC digital community? The Digital Community Management team does ongoing talent mapping for managers who are ready for the next step. Check out our digital executives page to see what’s out there.
Button copy: Learn more 
Button link: Link to Executive recruitment page (Lauren would like these pages built at the same time so when this gets published it can link to the executive page)
image: 
![AdobeStock_123658621](https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/67d6ca30-c91d-4f5b-a3ba-c17e659fa3df)
Image alt text: Diverse group of four executives greeting one-another.

📸 Screenshot:
<img width="802" alt="Screenshot 2023-07-10 at 11 56 41 AM" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/43f97f85-9e38-4a79-81e8-067d96712631">

## 🔍 Section 5: Directive on Digital Talent 

Header: Directive on Digital Talent 
Body copy: The GC Digital Talent platform offers a handful of helpful resources to make completing your responsibilities under the Directive on Digital Talent as easy as possible. This includes online forms, implementation guidance, and links to the Directive. 
Button copy: Learn more
Button Link: [link to the directive on digital talent page](https://talent.canada.ca/en/directive-on-digital-talent)

📸 Screenshot: 
<img width="802" alt="Screenshot 2023-07-10 at 11 56 58 AM" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/0fa9a54d-5440-4ba5-8fcb-7766fc5a9a05">

**Comment by BrookeCameron** [comment]
this is ready to be passed off and dev'd @gobyrne

**Comment by petertgiles** [comment]
Thanks for all the detail here!  I love that you've mapped out all the buttons and links.
A couple of questions:
1. Could you update the links to actual URLs and email addresses to take the guesswork out for the dev?
2. How will we handle links to pages that don't exist yet?  For example, executive recruitment.
3. How will we handle links with context-dependent text?  For example, I see three links with the text "Learn more".

**Comment by petertgiles** [comment]
Copy nitpicks.  :smile: 
- Missing apostrophe: `Wondering whats next for your career?`
- `The Digital Community Management team does ongoing talent... ` Didn't they change their name?

**Comment by petertgiles** [comment]
Has a URL been selected for the page?

**Comment by BrookeCameron** [comment]
@marc-donofrio can you confirm what email address I should link for the contact us for the following sections:
1. Run a recruitment process
2. Get hiring experience

**Comment by marc-donofrio** [comment]
It should be: gctalent-talentgc@support-soutien.gc.ca
