### ISSUE TITLE
♻️ Bump `urql` to v4

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#6219]
## ♻️ Debt/Refactor

A new major version was released with some breaking changes.

## 🕵️ Details

I don't beleive the breaking changes affect us, though to be safe we should probably bump maually to avoid unexpected surprises. 

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] `urql` is bumped past v4
- [ ] App builds and functions properly

**Comment by mnigh** [comment]
Related https://github.com/GCTC-NTGC/gc-digital-talent/issues/5981?

**Comment by esizer** [comment]
> Related #5981?

Yeah, I'm not 100% sure how tightly coupled they are. I don't think this one will be too difficult to bump so maybe they could be done at the same time? 🤔
