### ISSUE TITLE
♻️  Remove/rename ExpectedClassification and ExpectedSalary from the code 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#6226]
## ♻️ Debt/Refactor

There are many issues associated with it but I try to minimize the scope in here. 
We don't have `Expected Classification` any more in the db. 
We have Generic Job Titles column and the code should represent this naming everywhere 

## 🕵️ Details
When the user selects Roles and Salary expectation in user profile page
<img width="918" alt="image" src="https://user-images.githubusercontent.com/89482910/230413368-27df6106-43e0-462d-971c-995828ef88c3.png">

table `generic_job_title_user`  has been used to store this information.
In the model we have both Expected Classification and Expected Generic Job Title
We use either one in the pages and it becomes confusing. 
We need to remove Expected Classification everywhere in the code and consistently use expectedGenericJobTitles

Ex. Rename expectedClassifications into expectedGenericJobTitles in ApplicantFilter type and all the code that reference to this. 
```
type ApplicantFilter {
  id: ID!
  hasDiploma: Boolean @rename(attribute: "has_diploma")
  equity: EquitySelections
  languageAbility: LanguageAbility @rename(attribute: "language_ability")
  operationalRequirements: [OperationalRequirement]
    @rename(attribute: "operational_requirements")
  locationPreferences: [WorkRegion] @rename(attribute: "location_preferences")
  wouldAcceptTemporary: Boolean
    @rename(attribute: "would_accept_temporary")
    @deprecated(reason: "replaced with positionDuration")
  positionDuration: [PositionDuration] @rename(attribute: "position_duration")
  expectedClassifications: [Classification]  # Filters applicants based on the classifications they've expressed interest in.
    @belongsToMany(relation: "classifications")
  skills: [Skill] @belongsToMany
  qualifiedClassifications: [Classification] @belongsToMany # Filters applicants based on the classifications pools they've qualified in.
  qualifiedStreams: [PoolStream] @rename(attribute: "qualified_streams") # Filters applicants based on the streams of the pools they've qualified in.
  pools: [Pool] @belongsToMany @can(ability: "view", resolved: true)
}
```

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] Remove expectedSalary and expectedClassifications from the API

## 🛑 Blockers

Blocked by {#5644}

**Comment by tristan-orourke** [comment]
Let's hold off on this until after we're done #5347.

**Comment by mnigh** [comment]
@tristan-orourke  `expectedSalary`and `expectedClassifications` only appear as deprecated fields on the `User` type:

https://github.com/GCTC-NTGC/gc-digital-talent/blob/fc5232c1bfb0b169ceb1320a57154133db9c663f/api/graphql/schema.graphql#L98-L103

is this issue still relevant?
