### ISSUE TITLE
🐛 Accessibility Bug Report

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/gc-digital-talent#6235]
## 🐛 Bug

Describe the issue you encountered.

## 🦋 Expected Behaviour

What should be happening?

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Name and version (if possible).
- **Browser**: Name and version (if possible).

## 📋 Steps to Reproduce

1. ...
2. ...

## 📸 Screenshot

Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Criteria 1
- [ ] Criteria 2

## 🛑 Blockers

Blocked by {issue numbers}

**Comment by petertgiles** [comment]
empty issue
