### ISSUE TITLE
🐛 `watch` script does not listen for changes to the language files

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#6243]
## 🐛 Bug

The `watch` script does not listen for changes to the language files (en.json, fr.json) besides the first run.

## 🦋 Expected Behaviour

The `watch` script should listen for changes to the language files (en.json, fr.json) and re-compile on any changes made to either file.

## 📋 Steps to Reproduce

1. `npm run watch`
2. Change something in fr.json
3. The change is not reflected in the browser.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] `watch` script listens for changes to the language files (en.json, fr.json) and re-compiles upon change

**Comment by petertgiles** [comment]
@esizer concerns with this one?

**Comment by esizer** [comment]
> @esizer concerns with this one?

My only concern is that I'm not sure if it is even possible 😢 `@formatjs/cli` does not seem to support any sort of `watch` functionality 👎 

REF: https://formatjs.io/docs/tooling/cli

**Comment by mnigh** [comment]
> > @esizer concerns with this one?
> 
> My only concern is that I'm not sure if it is even possible 😢 `@formatjs/cli` does not seem to support any sort of `watch` functionality 👎
> 
> REF: https://formatjs.io/docs/tooling/cli

😢 and it doesn't look like this is coming anything soon, if ever: https://github.com/formatjs/formatjs/issues/2021

@petertgiles should I close this issue as won't fix?

**Comment by petertgiles** [comment]
not possible
