### ISSUE TITLE
✨ Remove "Apply" button from closed pools.

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#6248]
## ✨ Feature

The button for "Apply to this process" is still visible on Closed pool advertisements. We should remove this button to not mislead users that find themselves in this page, even though this page should not be easily accessible, it still exists on the public facing side.

## 🕵️ Details

HIDE the APPLY TO THIS PROCESS button from this page when the advertisement is CLOSED

## 📸 Screenshot

![image](https://user-images.githubusercontent.com/16977254/231263095-ca9e8e23-05ff-4c4a-884a-165880c95101.png)

## ✅ Acceptance Criteria

- [ ] HIDE the APPLY TO THIS PROCESS button from this page when the advertisement is CLOSED

**Comment by tristan-orourke** [comment]
Rolled into #6318
