### ISSUE TITLE
♻️ Update `microsoft/applicationinsights-web` to v3

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#6279]
## ♻️ Debt/Refactor

It seems like AI v3 has some breaking changes.

## 🕵️ Details

#6277

https://microsoft.github.io/ApplicationInsights-JS/upgrade/v3_BreakingChanges.html

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] @microsoft/applicationinsights-web at version >= 3.0.0

**Comment by mnigh** [comment]
Related to #7426.

**Comment by vd1992** [comment]
Closed with #7485
