### ISSUE TITLE
✨ Add Storybook Accessibility Addon

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#6280]
## ✨ Feature

Storybook has an [accessibility addon](https://storybook.js.org/addons/@storybook/addon-a11y) that runs axe-core against stories and presents any errors to developers. 

## 🕵️ Details

I feel as though this is a good way to surface errors earlier in development and cover more edge cases with all of the variations we have on components. 

## 🙋‍♀️ Proposed Implementation

Install, configure and test the accessibility addon.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] `@storybook/addon-a11y` installed
- [ ] Addon configured and working as expected
- [ ] Create issues on the board for problems surfaced by tool

**Comment by petertgiles** [comment]
How does this work?  Would it run all testing on startup or just when you open the story?  Would this integrate with CI or just be used during manual review?

**Comment by esizer** [comment]
> How does this work? Would it run all testing on startup or just when you open the story? Would this integrate with CI or just be used during manual review?

They don't actually specify when it runs but based on the source code it appears to run when you open the story. While[ it can integrate with CI](https://storybook.js.org/docs/react/writing-tests/accessibility-testing#automate-accessibility-tests-with-test-runner) I imagine we would start small and just get it working while doing manual reviews initially.

**Comment by RM-1978** [comment]
That is amazing folks!

**Comment by yonikid15** [comment]
I wasn't able to get this working on v6.5.16. I'll wait till https://github.com/GCTC-NTGC/gc-digital-talent/pull/6259 is merged and try again using the latest version (currently [v7.0.7](https://www.npmjs.com/package/@storybook/addon-a11y))
