### ISSUE TITLE
✨ (Search page) Include skills and copy on request pool cards

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#6281]
## ✨ Feature

DCM wants to increase transparency and better manage the expectations of managers submitting requests by adding information regarding the pool from which the candidates got screen through.

## 🕵️ Details

To this effect, we suggest making some changes to the current cards that show up at the end of the results page.

1 - Include a link to the now closed poster so managers can look at the advertisement that was used.
2 - Include the essential skills assessed during this pool
3 - Replace "pool owner" for "Process run by" + Team + "at" + Department

## 🎨 Design File

[Include a link to the design file.](https://www.figma.com/file/UsrB15yicgDCLDQmx3snyl/User-Flows?type=design&node-id=4734%3A12707&t=SvUa0rQyqqo4yYNs-1)

### OLD DESIGN 

![image](https://user-images.githubusercontent.com/16977254/231805645-be5b5334-dba2-479b-83d7-a625aad2db7d.png)

### NEW DESIGN

![image](https://user-images.githubusercontent.com/16977254/231804331-b7b9afbd-25c8-456c-8ac2-e86ae6a7df95.png)

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

On Pool cards at bottom of search page:
- [ ] Include a link to the now closed poster so managers can look at the advertisement that was used.
- [ ] Include the essential skills assessed during this pool
- [ ] Replace "pool owner" for "Process run by" + Team + "at" + Department

**Comment by brindasasi** [comment]
@Jerryescandon should the job advertisement be opened in a sep tab?

**Comment by Jerryescandon** [comment]
> @Jerryescandon should the job advertisement be opened in a sep tab?

that's probably a good idea

**Comment by brindasasi** [comment]
@Jerryescandon Currently as per the code team can be part of multiple departments.
How do you want that to display here ?

> "Process run by" + Team + "at" + Department

Also it is possible to have pool without team currently. In that case it will display 
"Process run by N/A at N/A"
Not sure if this is even a real use case in production.
But wondering your opinion on that.

**Comment by Jerryescandon** [comment]
I guess we can add a null state for those NA to be defaulted to the DCM team:
null state team: "Digital Community Management team"
null state department: "Treasury Board of Canada Secretariat"

For multiple departments we should just append all available depts. into one with an " and "
