### ISSUE TITLE
⌨ Accessibility Issue: Location of automatically detected input errors is not clear

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/gc-digital-talent#6294]
## ❌ Current behaviour (issue)

Error message alert does not direct the user to the experience component where a field error requires their attention on the following pages: 
  - **_Review and Submit_** your application.

**WCAG 2.1 Criteria:** 3.3.1 (AA): If an input error is automatically detected, the item that is in error is identified and the error is described to the user in text.

### How to reproduce

1. Navigate to [Work Experiences](https://uat-talentcloud.tbs-sct.gc.ca/en/users/528357e6-0ff7-4809-8f90-0bca8198aaf7/profile/experiences/work/create)
2.  Create an error by forgetting one of the need to have /essential criteria. 
3.  Go to the Review and submit my application page.
4. Find your error  on the Work experience page using the error message guidance on the Review and Submit page.

## ✔ Expected behaviour (fix)

If an input error is automatically detected and suggestions for correction are known, then a clear mechanism is available for reviewing, confirming, and correcting the exact error  information before finalizing the submission.

### Acceptance Criteria

A set of assumptions which, when tested, verify that the accessibility requirement was met.

- [ ] Error messages contain a clear mechanism to correct the error information where it appears in the platform before finalizing the submission.

**Comment by gobyrne** [comment]
This whole piece is currently being re-built. Let's just make sure we don't get the same problem on the new UI.

**Comment by esizer** [comment]
WE also have overlap with #3679 so closing this for now.
