### ISSUE TITLE
🐛 Rule against duplicate emails should be case insensitive

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#6297]
## 🐛 Bug

It's possible for two users to have the same email, if the casing is different.

## 🦋 Expected Behaviour

Emails should always be saved to database in lowercase. When we check for duplicate emails, we should be case insensitive.

## 🕵️ Details

There is a person who created two user accounts in production. Both have the same name, and both have the same email - except one of the emails is capitalized.

## 📋 Steps to Reproduce

1. Create a new user.
2. Set you email to Admin@test.com. It should fail, but doesn't.

## 📸 Screenshot

Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

Emails should always be saved to database in lowercase. When we check for duplicate emails, we should be case insensitive.
- change validator for email to case insensitive
- force saved emails to lowercase (lighthouse directive or Laravel setter)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Emails should always be saved to database in lowercase. 
- [ ] It is not possible to give yourself an already taken email by just changing the casing.we should be case insensitive.

## 🛑 Blockers

Blocked by {issue numbers}

**Comment by vd1992** [comment]
should address any existing duplicates within the issue scope I think 

1. command to remove duplicates (append a random couple of characters onto repeat emails)
2. implement a mutator/setter with a `toLowerCase()` like in https://laravel.com/docs/10.x/eloquent-mutators#defining-a-mutator

other things are possible I guess like directives

**Comment by tristan-orourke** [comment]
Hmm. If we use a mutator to force emails to lower case, then we'll avoid any future case-based-duplicate issues, without having the existing duplicates cause an error. Then we can handle it on a case by case basis in the prod database.
