### ISSUE TITLE
✨ Alternative education requirement for AS classification

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#6299]
## ✨ Feature

In the near future we will be posting some AS classification job advertisements on the site. These jobs have a different education requirement than IT jobs, so we will need to have a way to change it.

## 🕵️ Details

Here is the English copy for the AS classification education requirement. The first criteria (combination experience) is unchanged!

> **Combination Experience** 
> 2 or more years of combined experience in a related field including any of the following:
> - On-the-job learning
> - Non-conventional training
> - Formal education
> - Other field related experience
> 
> **OR**
> 
> **A secondary school diploma or a satisfactory score on the Public Service Commission test**
> Successful completion of a secondary school diploma (high school graduation) or a satisfactory score on the Public Service Commission test approved as an alternative to a secondary school diploma.

## 🎨 Design File

Include a link to the design file (if it exists).

## 📸 Screenshot

This is the current education requirement on the job advertisement

![image.png](https://images.zenhubusercontent.com/5dc084854553760001149b53/4c4b8feb-f7d9-404c-8e13-6450314aa7e2)

## 🙋‍♀️ Proposed Implementation

Add a select to the Pool Edit page that lets you choose between education requirements for that specific poster.  The select will allow the editor to choose between preset education requirements and will display the copy of the section.  This select can be added to the "Other" section of the edit pool page.

In the backend, a new field will be added to pool type with an enum for the selected education requirement.

## 🌎 Localization

> Un diplôme d’études secondaires ou des résultats satisfaisants à l’examen de la Commission de la fonction publique
Obtention réussie d’un diplôme d’études secondaires (diplôme d’une école secondaire) ou résultats satisfaisants à l’examen de la Commission de la fonction publique ayant été approuvé comme étant une alternative au diplôme d’études secondaires.

## ✅ Acceptance Criteria

- [ ] Migration to add column to pool table, prefill all existing pools with "IT 2 year post secondary" option but no default for column.
- [ ] In the schema, a new field for the education requirement with enums
- [ ] Two options to start with: the current "IT 2 year post secondary" option and the new "secondary school diploma / commission test" for AS
- [ ] On the edit pool page, a select to choose the option
- [ ] Pool must have education requirement to be published
- [ ] Selected education requirement shows on the pool advertisement page

**Comment by petertgiles** [comment]
Will discuss possible implementation details on Monday.

**Comment by petertgiles** [comment]
Translation of education requirement requested.

**Comment by petertgiles** [comment]
Suggested field name: required_education

**Comment by mnigh** [comment]
@gobyrne does working on #8394 change the requirements for this at all?
