### ISSUE TITLE
🐛 Null state for sections on view pool page

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#6306]
## 🐛 Bug

It looks a bit odd to me to just have a blank space under sections, especially since some may be intentionally left empty and it isn't a case of something failing to load. 

## 🦋 Expected Behaviour

Null state for sections. 
Most are not going to stay empty, but some are optional and so may stay empty like asset skills and screening questions. 

## 📋 Steps to Reproduce

1. /en/admin/pools/:id
2. observe the blank spaces under sections with no data

## 📸 Screenshot

![image](https://user-images.githubusercontent.com/40485260/232616140-80622d7c-d579-4ef4-b405-dc429336a847.png)

## 🙋‍♀️ Proposed Solution

Copy can be debated. 
Maybe something like a simple "None" underneath.
Like 
`pool?.screeningQuestions ? <QuestionsElement/> : <p>Not provided</p>`

## ✅ Acceptance Criteria

- [ ] Blank spaces no longer blank
- [ ] Placeholder copy: none but with brackets too: "(None)"

**Comment by petertgiles** [comment]
@Jerryescandon Copy for "no skills"?  "None"?

**Comment by Jerryescandon** [comment]
I would go with none but with brackets too:
"(None)"

**Comment by esizer** [comment]
@Jerryescandon We already have a `"Not provided"` string in the codebase that is translated and we use elsewhere. Would that work in place of `"None"`

**Comment by Jerryescandon** [comment]
It's better than nothing. I think grammatically is a little weird. But convenience is king, and I don't wanna block this cause copy discussions can take while. So, I say let's use `"Not provided"` and if we receive a request from DCM or the product team later to change the copy we can do it at a later date.
