### ISSUE TITLE
♻️ Filter out closed pools from Browse opportunities

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#6307]
## ♻️ Debt/Refactor

Currently, `/en/browse/pools` queries for all published pools by query `publishedPoolAdvertisements`.
This grabs everything published, so active and closed. The front-end filters out closed pools, but as the number of closed pools increases, the greater the graphQL operation full of pools to be filtered out. 

All the closed pools are viewable in the network tab, which may present an issue as some closed pools it may be desired to not expose them for whatever reason on a page with no authorization. 

## 🕵️ Details

![image](https://user-images.githubusercontent.com/40485260/232625587-602986e8-0974-4a7a-83a5-f33e59a49def.png)

## 🙋‍♀️ Proposed Solution

Query can filter out closed pools (optional filter/scope?)
Tristan's suggestion: add an argument to existing query

## ✅ Acceptance Criteria

- [ ] Browse opportunities no longer grabs closed pools
- [ ] (optional) Remove frontend filtering code

**Comment by brindasasi** [comment]
this could possibly be one of the reasons why browse pools page often throws error event in production.
