### ISSUE TITLE
✨ Application Success page

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#6309]
## ✨ Feature

Success page when application is successfully submitted.

## 🕵️ Details

Add any additional details that could assist with the development of the new feature.

## 🎨 Design File

https://www.figma.com/file/BXYVsu1fo9LS2IySJDUINY/Applicants---Job-application?node-id=636-59839&t=9Q3MVJHmXh2CmTY6-0

## 📸 Screenshot

![Submission confirmation](https://user-images.githubusercontent.com/4313717/232821085-0e2b15a3-fc53-40a7-8624-fbe33b456e76.jpg)

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Page exists under the given url  applications/:id/welcome 
- [ ] Page is accessible only when the feature flag "Application Revamp" is ON 
- [ ] Hero subtitle and breadcrumbs are correct
- [ ] The confirmation number is the id of the PoolCandidate (application) object
- [ ] Links are correct: TODO @gobyrne and @substrae need calls on these links
  - [ ] "Find and complete security clearance forms" -  where does this link to?
    - I believe this link already exists, does it not? It should link to the actual canada.ca links for the security forms though. 
  - [ ] "Update profile and contact information to ensure you receive notifications" - @substrae where does this link to? ~The dashboard~, the profile, ~or the edit contact info page~?
  - [ ] "Submit an application to ongoing recruitment talent pools" - link to the Browse Pools page?
- [ ] "Go to my dashboard" is simply a link to the dashboard
- [ ] All steps of the stepper show green checkmarks

**Comment by petertgiles** [comment]
@substrae Could you please provide the URLs for the links?

**Comment by substrae** [comment]
@petertgiles 

- "Find and complete security clearance forms" - https://www.tbs-sct.canada.ca/tbsf-fsct/330-60-eng.asp
  - @gobyrne do you mind confirming that this link is okay to use?
- "Update profile and contact information" - `Home > Dashboard > Profile information`
- "Submit an application to ongoing recruitment talent pools" - `Home > Browse jobs > #OngoingRecruitment
  - Our headings don't have `id` values apparently, so this will need to be added.
- "Go to my dashboard" - `Home > Dashboard`

**Comment by esizer** [comment]
I noticed the copy makes a specific reference to the IAP. Is this supposed to be dynamic based on some context/value (publishing group)? @substrae 

> ...matches criteria for the **Indigenous Apprenticeship Program**...

**Comment by substrae** [comment]
@esizer 

Oh, this might have been legacy text - we can make it generic for now.

> ... matches the criteria outlined by the opportunity.
