### ISSUE TITLE
📐 Executive home page

### ISSUE THREAD

**Issue by BrookeCameron** [GCTC-NTGC/gc-digital-talent#6312]
# ⚙️ A page for executive talent to browse jobs and learn about how they can use the GCDT portal.

## 💾 Files and resources

Page URL: https://talent.canada.ca/executive 

images with alt text are provided in their respective sections

# ✅ Requirements

- [ ] Header
- [ ] Executive recruitment processes
- [ ] What we can do for you
- [ ] Create a profile
- [ ] EXposition
- [ ] The Directive on Digital Talent 
- [ ] Update link to exec page on the manager home page

Screenshot 📸:
<img width="802" alt="Screenshot 2023-07-10 at 11 56 58 AM" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/1cb25044-b8f8-446a-b8e1-242657ca453c">

## 🧢 Section 1: Header 

Image: 
![Exec_hero](https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/76fc8a58-7912-4d60-bef7-37add0cd5e99)
Image alt text: Diverse group of four executives greeting one-another

Heading: Welcome executives
Sub-heading: Find and apply to digital executive opportunities in the Government of Canada.

📸 screenshot: 
![Screenshot 2023-07-10 at 1 11 55 PM](https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/395ff35f-e275-4e59-87da-9b5a092fa256)

## 🚀 Section 2: Executive recruitment processes 

Component: job poster preview (will show the most recent Exec recruitment) If nothing is there it will show the no job state of the component. 

Heading: Executive recruitment processes
Body copy: This platform allows you to apply to recruitment processes that make it easy for senior executives and HR recruitment teams to find you. This page offers you a snapshot of our open recruitment processes. Come back and check this page often!

No job state heading: More opportunities are coming soon!
Body copy: New opportunities are posted throughout the year. By starting your profile now, you’ll be better positioned to submit a strong application when the time comes. 

📸 screenshot No jobs state: 
![Screenshot 2023-06-20 at 10 14 23 AM](https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/c037e96c-9ff1-459e-beea-f1c4ba9543f2)

## 🧩 Section 3: What we can do for you

Component: content block group component
Context: an overview of how the execs can use GCDT

### Content block 1
Header: Find pre-qualified executive talent
Body copy: If you’re a senior leader in the GC Digital Community and you’re looking for executive talent, reach out to our team for recommendations and a list of pre-qualified candidates along with their profiles. 
button copy: Contact us
Button link: email to gctalent-talentgc@support-soutien.gc.ca subject line I'm looking for pre-qualified executive talent 

### Content block 2 
Header: Manage your career
Body copy: Check out the most recent manager recruitment processes for specific opportunities or apply to ongoing recruitment in any of the IT generic work streams. Check back often for new opportunities.  
button copy: Browse jobs
Button link: Browse jobs page (hopefully with a manager or exec job)

### Content block 3
Header: Get hiring experience
Body copy: Not all executives have had the chance to run their own staffing processes. If this is an area of development for you, consider gaining experience by volunteering on an interdepartmental team running a process on the platform.
button copy: Contact us
Button link: email to gctalent-talentgc@support-soutien.gc.ca subject line I'm interested in gaining hiring experience

📸screenshot: 
![Screenshot 2023-07-10 at 1 16 48 PM](https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/aa041620-5b35-4af2-b35a-a500ee9982eb)

## 👤 Section 4: Create a profile

Component: Create a profile hero from the main GCDT Homepage

Please note: The image and copy is different from the main GCDT Homepage 

Copy: Your profile is at the heart of the platform. Tell your story, show how you developed your skills, and use your profile to apply for jobs.  Whether you’re hunting for a job now or just thinking about the future, a strong profile is your path to new opportunities.
Button copy: Create a profile
Button links to: [Send the user to create a profile on GCDT](https://talent.canada.ca/en/login-info?from=%2Fen%2Fusers%2Fme)

Image: ![Profile_hero_exec_2](https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/832c92b5-55f2-4a1d-bc80-380e97d13251)

alt text: mature woman smiling at laptop.

##📸 Screenshot 
![Screenshot 2023-07-10 at 1 18 39 PM](https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/698c0557-7d36-4869-b75c-7e25a59258d6)

## ✨ Section 5: EXposition

Subheading: Who is EXposition for?
Body copy: Are you a leader looking to attract or promote high-potential talent within the digital (IM, IT or Data fields) community? Do you have talented employees to nominate at the EX minus one to the EX-03 group and level? Are you from the human resources community and interested in interdepartmental opportunities for your digital workforce?
If your answer is yes to one or several of the questions above, we have the solution you are looking for. Since 2019, we have built trust with hundreds of digital leaders from dozens of organizations across the GC to help talented employees optimize their skills, achieve their potential, develop new experiences, and engage in the succession planning process.
Subheading: Learn more about our 4 services and discover how we can help you achieve your goals!

Expansion block 1: 
Heading: Digital Community Support 
Body copy: Conducted 573 personalized 1:1 career management and support meetings with aspiring executives and executives in the 2022-2023 fiscal year.

Expansion block 2: 
Heading: Identification of Digital Talents – Talent Management Roundtable Discussions
Body copy: Across the years, hundreds of nominees at different groups and levels (EXposition focus on EX while EXtend EXposition focus on the non-EX groups and levels) have been brought forward and their nominations are compiled in the Digital Talent Management Repository. This Talent Management repository is the primary data source when organizations require to obtain Referrals throughout the year.

Expansion block 3: 
Heading: Referrals Services
Body copy: Completed 42 placements of C-Suite and other leadership positions this fiscal year promoting digital talent management which doubled the placements in 2022-2023 previous fiscal year. Note that the digital talents are identified at the interdepartmental annual talent management roundtable discussions.

Expansion block 4: 
Heading: Digital Community Mentorship Program
Body copy: Launched the third cohort of the Digital Community Mentorship Program for members of an Employment Equity groups.

Button copy: Contact us
Button link: email to gctalent-talentgc@support-soutien.gc.ca subject line "EXposition"

📸 screenshot: 
<img width="760" alt="Screenshot 2023-07-11 at 2 06 09 PM" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/29a04420-73eb-401f-abc2-1870bcc0c6ae">

## 🔍 Section 6: The Directive on Digital Talent

Header: Directive on Digital Talent 
Body copy: The GC Digital Talent platform offers a handful of helpful resources to make completing your responsibilities under the Directive on Digital Talent as easy as possible. This includes online forms, implementation guidance, and links to the Directive. 
Button copy: Learn more
Button link: https://talent.canada.ca/en/directive-on-digital-talent 

📸 screenshot: 
![Screenshot 2023-07-10 at 1 29 18 PM](https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/340c6a7e-071c-4d3b-9f96-5045f87c4e65)

**Comment by BrookeCameron** [comment]
@marc-donofrio do you want all "contact us" emails to be sent to gctalent-talentgc@support-soutien.gc.ca ?

**Comment by petertgiles** [comment]
Looking great!  I have a few suggestion to consider.

> Heading: Welcome executives

This sounds like a command to welcome the executives.  Consider "Welcome, executives".

> Header: Find prequalified executive talent
Body copy: If you’re a senior leader in the GC Digital Community and you’re looking for executive talent, reach out to our team for recommendations and a list of pre-qualified candidates along with their profiles.

Are you going with "prequalified" or "pre-qualified"?

> Are you from the human resources community interested in interdepartmental opportunities for your digital workforce?

Should be "from the human resources community _and_ interested"?  Or is the community interested?

> Subheading: Learn more about our 4 services and discover how we can help you achieve your goals!

I think generally number less than ten are written out.

**Comment by BrookeCameron** [comment]
1. Lets leave the heading as is - this is what Lauren wanted
2. pre-qualified 
3. we can add the and 
4. okay we can change it to "four"

**Comment by mnigh** [comment]
@BrookeCameron I've added a few comments and questions in the [figma file](https://www.figma.com/file/6uS74wZZsQujmvcYyujU83/Candidates---Executive-homepage---Version-1?type=design&node-id=256-11078&mode=design&t=t1QDuPOPiJPyCKrW-4), one of them is a clear typo:

## Content block 3
### Header: Get hiring experience
#### Body copy

Not all executives have had the a chance to run their own staffing processes.

to

Not all executives have had the chance to run their own staffing processes.

**Comment by BrookeCameron** [comment]
> 

noted and changed
