### ISSUE TITLE
✨ Application Revamp: entry point routing

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#6320]
## ✨ Feature

If you go to the url `/applications/:id` without any further paths, the app should route you to the correct application page based on your current progress.

If the application is already submitted, you are sent to the Success page. Otherwise, you are sent back to the earliest un-submitted step. If an instructional page for that step exists, the user should land there.

## 🕵️ Details

Add any additional details that could assist with the development of the new feature.

## 🎨 Design File

https://www.figma.com/file/BXYVsu1fo9LS2IySJDUINY/Applicants---Job-application?node-id=636-59839&t=i9s88SenDXvyHt0M-0

## 📸 Screenshot

Add a screenshot of the new feature (if possible).

## 🙋‍♀️ Proposed Implementation

Not sure. The logic could live in ApplicationLayout. It might be better performance to redirect in a [react-router loader](https://reactrouter.com/en/main/fetch/redirect). The logic should still be in a ApplicationLayout function, or maybe a utility file?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] If you go to the url `/applications/:id` of a complete application, you are redirected to the success page
- [ ] If you go to the url `/applications/:id` of an in-progress application, you are redirected to the earliest step you have not submitted yet
- [ ] If you are redirected to a step with an instructional page, you land on that page

**Comment by petertgiles** [comment]
The uh-oh page has logic like this to return to the correct page already
