### ISSUE TITLE
✨ Statistics on Pool Information page

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#6325]
## ✨ Feature

Add a couple of quick statistic counters on the Pool Information page to aid DCM on looking at how many people they have in their current pools.

## 🕵️ Details

The number in "Draft" should be the total number of candidates with the status 'Draft"
The number in "Total applications received" should count everyone else NOT in "Draft"

## 🎨 Design File

[LINK TO FIGMA](https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Record-of-Decision?node-id=1919%3A3386&t=I4EDtr5smt0HLkY2-1)

## Implementation
- Recommend create new fields on pool object for aggregates since draft objects will not be queryable.

## 📸 Screenshot

![image](https://user-images.githubusercontent.com/16977254/233111100-76415411-40e8-41ee-8001-ac56489a2025.png)

## ✅ Acceptance Criteria

- [ ] Add Statistics section to pool information page
- [ ] Add the two metrics to the section

**Comment by petertgiles** [comment]
@Jerryescandon Is this issue complete? Just this new section with the two metrics?

**Comment by petertgiles** [comment]
@Jerryescandon Matt recommends "Statisicts" instead of "Quickstats" due to translation.  OK?

**Comment by gobyrne** [comment]
This functionality will be addressed in Record of Decision. We don't think it's worth working on it before then.
