### ISSUE TITLE
✨ Copy change - ongoing recruitment *process* on browse jobs page

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#6351]
## ✨ Feature

We want to standardize how we use the word recruitment on the browse jobs page. The occurrences of  "recruitment" in the ongoing recruitment section should be followed by the word "process".

But not in the heading! French is a little more complicated :/

## 📸 Screenshots

![image.png](https://images.zenhubusercontent.com/5dc084854553760001149b53/766a8f2c-d185-4052-b1f5-a9cec2544a56)

![image.png](https://images.zenhubusercontent.com/5dc084854553760001149b53/05d52356-5f24-4bc1-98ff-ead9c51966e4)

## 🌎 Localization

(EN) recruitment -> recruitment process

(FR) pas de recrutement actif -> pas de processus de recrutement actif
(FR) des lots de recrutement passif -> des processus de recrutement passif

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] On "browse jobs" page all instances of _recruitment_ are changed to _recruitment process_ (except the heading)
- [ ] French copy updated, too

**Comment by petertgiles** [comment]
@gobyrne Should the copy by retranslated or is the French copy already acceptable?

**Comment by petertgiles** [comment]
Apply to "an ongoing recruitment process"?
Apply to "ongoing recruitment processes"?

**Comment by vd1992** [comment]
Per acceptance criteria: 
"On "browse jobs" page all instances of recruitment are changed to recruitment process (except the heading)"

Buttons on that page need updating too?

![image](https://user-images.githubusercontent.com/40485260/235011381-81e5f1aa-5155-48c2-9130-37209c090e57.png)

**Comment by petertgiles** [comment]
Gray says yes
