### ISSUE TITLE
✨ Priority change to Category

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#6354]
## ✨ Feature

On the Pool Candidates table we want to change the label from the "Priority" column to  "Category" for HR reasons.  No changes to applicant side of application.

## 📸 Screenshot

![image](https://user-images.githubusercontent.com/16977254/233402436-c5030978-4f3d-4d11-bac1-73489f26e29b.png)

![image](https://user-images.githubusercontent.com/16977254/233403554-fc097422-f340-4114-9375-8479344d7098.png)

## ✅ Acceptance Criteria

- [x] The Priority column is changed to Category
- [x] Columns and Filters dialog also updated
- [x] FR: `Catégorie`

**Comment by petertgiles** [comment]
What is the HR approved French name?

**Comment by Jerryescandon** [comment]
@gobyrne 
```catégorie``` ?

**Comment by petertgiles** [comment]
@Jerryescandon do we need updated designs for these forms?

Government info:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/bd9e4ccf-675b-4e4e-9710-a3494a415c46)
Create account:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/9900c529-019b-4bc6-9645-ab936c752d92)
Static profile:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/da0d68f9-1313-4df0-b92e-cd6e4e2757f2)

**Comment by Jerryescandon** [comment]
> @Jerryescandon do we need updated designs for these forms?

This change is only for the admin facing table, not for the applicant.
