### ISSUE TITLE
✨ Remove pool candidate Auto-Expiry date and make it optional

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#6363]
## ✨ Feature

We have a feature that was very useful during migration that is now causing issues.

New applications or new placements into a pool automatically add an expiry date. This was helpful for migration, but new applications should NOT have an expiry date until after someone has been qualified. 

DCM has asked us to remove the rule that sets expiry date automatically when someone is added to a pool, and leave it as optional during the status change dialogs.

## 🕵️ Details

Add any additional details that could assist with the development of the new feature.

## ✅ Acceptance Criteria

- [ ] remove the behaviour that sets expiry date automatically when someone is added to a pool - probably CreateApplication mutation

**Comment by petertgiles** [comment]
Currently the "change status" dialog does not have a field to change the expiry date.  Does it need to be added as part of this issue?
![image](https://user-images.githubusercontent.com/8978655/234000006-020be8ea-6ed8-4f50-be75-e2dd17f230a7.png)
![image](https://user-images.githubusercontent.com/8978655/234000041-ffb8f890-1222-47ee-8a29-d430b9e402d4.png)

**Comment by Jerryescandon** [comment]
Yeah. That makes sense.

In addition, we should make the "expiry date" optional in the "Add user to pool" dialog to maintain consistency with their request.

**Comment by vd1992** [comment]
one thing to keep an eye out for maybe is what to do with the status CANDIDATE_STATUS_DRAFT_EXPIRED

relevant mutation

![image](https://user-images.githubusercontent.com/40485260/234328783-832f4eeb-4eb3-4916-8a77-9cc4b500b29b.png)

**Comment by vd1992** [comment]
There is already a "change expiry" dialog right next to it.
Do we really need to duplicate it in "change status"?

![image](https://user-images.githubusercontent.com/40485260/234941664-e46eb9b4-a72f-4d9d-905a-af4d3f6feaea.png)

**Comment by petertgiles** [comment]
rewritten as #7079
