### ISSUE TITLE
🐛 IAP logo in Mi'kmaq missing capital T

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#6371]
## 🐛 Bug

              Oops, lost the capitalization of the T.
![image](https://user-images.githubusercontent.com/8978655/234013585-16cf06a7-7e70-47b1-a898-f78cc30a4ce1.png)

_Originally posted by @petertgiles in https://github.com/GCTC-NTGC/gc-digital-talent/pull/6362#discussion_r1175301273_

## 📋 Steps to Reproduce

1. View [iap-logo-mic.svg](https://github.com/GCTC-NTGC/gc-digital-talent/blob/feature_6328_iap-mic/apps/web/src/assets/img/iap-logo-mic.svg)
2. Observe **It** instead of **IT**

## 🙋‍♀️ Proposed Solution

Change `iap-logo-mic.svg` file so that it reads **IT** instead of **It**.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] `iap-logo-mic.svg` reads IT

**Comment by BrookeCameron** [comment]
📁
![IAP_Logo_white_Mi kmaq_ Horizontal FR White](https://user-images.githubusercontent.com/100953238/235680415-b6dfcbbb-1db8-4581-b15e-4011907a6fb4.svg)


Revised Mi kmaq heading!

**Comment by mnigh** [comment]
Attached is a cleaned up SVG file without `id`, `xml`.

## 📁 File
![iap-logo-mic](https://user-images.githubusercontent.com/3046459/235709580-45a3de86-4b19-4138-ae10-fdcc8c1387b8.svg)
