### ISSUE TITLE
🐛 Sorting Pools by Group and Level not working in Descending order

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#6374]
## 🐛 Bug

Sorting Pools (in Admin table) by Group and Level works in Ascending order, but not descending.

## 🦋 Expected Behaviour

Ordering the pools table by Group and Level Ascending works as expected. AS goes before IT, alphabetically, and it orders levels correctly within a classification.

When you sort descending, changes the order of the Groups, but still sorts the levels in ascending order, when it should be descending.

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Name and version (if possible).
- **Browser**: Name and version (if possible).

## 📋 Steps to Reproduce

1. Go to /admin/pools
2. Sort by Group and Level asc, then desc
3. See that levels still appear in ascending order (1,2,3,4,5)

## 📸 Screenshot

Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] When sorting Pools table by Group and Level in desc order, levels are sorted in correct order

**Comment by vd1992** [comment]
It was intentionally set to just sort by group rather than group _and_ level. 
So undoing that would probably wrap this up quickly.

![image](https://user-images.githubusercontent.com/40485260/234374036-59a82be4-9d0b-46f2-91be-b4af6bacbdfc.png)
