### ISSUE TITLE
✨ Update frontend to use feature flags provided by API

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#6387]
> __Warning__
Possible blocker: It won't be possible to move the api to a different subdomain if we rely on getting runtime variables from the api.  How can we find the api if we need to contact to the api to get its url?

## ✨ Feature

Following discussion in #6375 we want to try having the feature flags provided to the frontend through the graphql api.

## 🙋‍♀️ Proposed Implementation

1. Feature flags are already loaded into the Laravel config.  See #6378.
2. Add feature flags to the graphql schema.  No permissions required to read.
3. Update the feature flags hook and non-hook accessors in the frontend to use graphql.  See https://github.com/GCTC-NTGC/gc-digital-talent/discussions/6375#discussioncomment-5712752 .
4. Remove feature flags from app/web .env file.
5. Remove config.ejs stuff from webpack.
6. Remove config file copy from post-deploy.
7. Remove config.js routing from nginx config.

## ✅ Acceptance Criteria

- [ ] Feature flags are read only from graphql
- [ ] Config.js method removed
- [ ] Everything works as before

**Comment by mnigh** [comment]
@petertgiles are we still planning to move the api to a different subdomain? if not, can this issue move ahead?

**Comment by petertgiles** [comment]
I no longer like this approach, to be honest.  I'm still not totally satisfied with our runtime variable system but I don't think pulling everything from the API is a good idea.

Unless someone else wants to champion it, I'd close it.
