### ISSUE TITLE
🐛 MicCompiled.json needs to be added to gitignore

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#6390]
## 🐛 Bug

The new MicCompiled file needs to be added to the gitignore file

## 📸 Screenshot

![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/ef6765a7-45d2-4a86-bbaf-de8552818863)

## ✅ Acceptance Criteria

- [ ] Rebuilding the app doesn't result in any untracked files

**Comment by mnigh** [comment]
@petertgiles This has already been added as part of #6362: https://github.com/GCTC-NTGC/gc-digital-talent/blob/c99d2f76581946732bb88db09922c04b57bad946/apps/web/src/lang/.gitignore#L5

**Comment by petertgiles** [comment]
Oh shoot, I must have been on an old branch.  Thanks!
