### ISSUE TITLE
♻️ `UserSeederUat` should add new roles

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#6405]
## ♻️ Debt/Refactor

UserSeederUat creates users with legacy roles, but not the new roles.

## 🕵️ Details

Add any additional details that could assist with the development of the new feature.

## 🙋‍♀️ Proposed Solution

Sync roles like we do in UserSeederLocal

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] Users created by UserSeederUat have non-legacy roles

**Comment by vd1992** [comment]
Having the seeder truncate by default and then copy the logic of `UserSeederLocal` as proposed is the easiest. 
But is that fine? Is there a reason UAT seeding is non-destructive?

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/8c4e3830-df91-4805-8c34-7f0bfdd5e9a1)

**Comment by tristan-orourke** [comment]
@vd1992 yeah, we want to keep seeding non-destructive on UAT.
