### ISSUE TITLE
🐛 Platform Admin Role - Edit User Page throws unauthorized error 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#6406]
## 🐛 Bug

Platform Admin Role - Edit User Page throws unauthorized error 

## 🦋 Expected Behaviour

Platform Admin should be able to edit the user 

## 🕵️ Details

UserName query fails 

## 📋 Steps to Reproduce

1. Login as Platform admin
2. Go to view users page and try to edit an user 

## 📸 Screenshot

![Screenshot 2023-04-25 at 10 01 32 AM](https://user-images.githubusercontent.com/89482910/234605680-86e87e3b-c9a5-4240-92b0-6d07256d8b68.png)
![Screenshot 2023-04-25 at 10 04 14 AM](https://user-images.githubusercontent.com/89482910/234606156-f10ee2cb-9049-454d-8a6c-c10d24710bea.png)

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Platform admin should be able to update the user without any error 

## 🛑 Blockers

Blocked by {issue numbers}

**Comment by vd1992** [comment]
## 🖥️ Deployment

Run `php artisan db:seed --class=RolePermissionSeeder`
