### ISSUE TITLE
🐛 Classification Level needs to be editable on the update classification page

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#6410]
## 🐛 Bug

Classification Level needs to be editable on the update classification page. Currently it is disabled. 

## 🦋 Expected Behaviour

Level should be editable 

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Name and version (if possible).
- **Browser**: Name and version (if possible).

## 📋 Steps to Reproduce

1. Navigate to /en/admin/settings/classifications 
2. Click on Edit for any classification

## 📸 Screenshot

![Screenshot 2023-04-25 at 10 28 38 AM](https://user-images.githubusercontent.com/89482910/234614178-ee0e85ab-8643-4221-aa4c-3c916b8925fd.png)

## 🙋‍♀️ Proposed Solution

Add `level: Int!` to:
https://github.com/GCTC-NTGC/gc-digital-talent/blob/fc5232c1bfb0b169ceb1320a57154133db9c663f/api/graphql/schema.graphql#L1272-L1277

Remove `disabled` prop: https://github.com/GCTC-NTGC/gc-digital-talent/blob/fc5232c1bfb0b169ceb1320a57154133db9c663f/apps/web/src/pages/Classifications/UpdateClassificationPage.tsx#L167

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Level should not be disabled on the edit page
- [ ] Editing the Level should be updated in to the db

**Comment by mnigh** [comment]
@GCTC-NTGC/developers any reasons not to allow the `level` field to be updated in "classifications"?

**Comment by vd1992** [comment]
What would the use case be? The official title or salary range of AS-01 may change but it'd never become AS-02

**Comment by petertgiles** [comment]
> What would the use case be?

This is really a business question.  @brindasasi was this request driven by the client for a use case we're not imagining?  The only thing I can think of is something like "we want to add a new level between 3 and 4 so all the current 4's become 5".

We've seen the group change before, though.  CS -> IT.

**Comment by tristan-orourke** [comment]
I don't see a use case for this. Do we want to update the form instead? Remove the 'required' attribute?

**Comment by mnigh** [comment]
@brindasasi do you remember if this issue came about as a request from a client?

**Comment by tristan-orourke** [comment]
I remember @brindasasi bringing this up, I'm pretty sure she was just logging this as an inconsistency.

**Comment by brindasasi** [comment]
@mnigh @tristan-orourke  not from the client .. This form allows the user to modify group but not the level . That sounds strange to me. Hence logged in. 
Not sure if this is a requirement.

**Comment by vd1992** [comment]
Not a requirement then so we shall leave it, should however, update the page so the field you cannot do anything with isn't marked required.
