### ISSUE TITLE
🐛 ApplicantFilterTest > query relationships  regularly failing

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#6439]
## 🐛 Bug

The test seems to fail with some regularity in the CI, atleast.

## 🦋 Expected Behaviour

Test should consistently pass

## 🕵️ Details

```sh
  at tests/Feature/ApplicantFilterTest.php:343
    339▕                         'pools' => [
    340▕                             [
    341▕                                 'id' => $filters[0]->pools->first()->id,
    342▕                                 'name' => $filters[0]->pools->first()->name,
  ➜ 343▕                                 'key' => $filters[0]->pools->first()->key,
    344▕                             ],
    345▕                         ],
    346▕                     ],
    347▕                 ],
```

## 📋 Steps to Reproduce

1. Run PHPUnit a few times `php artisan test`
2. See that the test fails at least once

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Test still checks for expected result
- [ ] Test passes consistently

**Comment by vd1992** [comment]
The involved queries are deprecated, and so may be removed soon-ish? In which case, adjust effort accordingly. 

Test

https://github.com/GCTC-NTGC/gc-digital-talent/blob/7720007c0c9193f448e2b23243b62d458f009401/api/tests/Feature/ApplicantFilterTest.php#L257-L272

Schema

https://github.com/GCTC-NTGC/gc-digital-talent/blob/7720007c0c9193f448e2b23243b62d458f009401/api/graphql/schema.graphql#L1021-L1034
