### ISSUE TITLE
IAP Application

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#6460]
Modify the Application when applying to the IAP pool.

https://www.figma.com/file/BXYVsu1fo9LS2IySJDUINY/Applicants---Job-application?node-id=322-31431&t=B3DmGu4KMyi5po0D-0

**Comment by mnigh** [comment]
@tristan-orourke can this `epic` issue be closed now that all the related issues (10 of 10) have been completed?
