### ISSUE TITLE
✨ Re-add search box to request table

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#6465]
## ✨ Feature

After the query is set to be backend-driven the search box will need to be added back in.

## 📸 Screenshot

![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/d35d7a9a-da43-40dd-9e82-c7a0a7415dc2)

## ✅ Acceptance Criteria

- [ ] Search box re-added
- [ ] text search should filter out rows which don't have matching text in any of the following columns:
  - fullName
  - email
  - jobTitle
  - additionalComments
  - adminNotes
- [ ] Works in a similar way to other backend-driven tables such as _User_
- [ ] Changes to API are tested in phpunit

**Comment by vd1992** [comment]
@Jerryescandon 

What should each option in the search dropdown be called? 
"All columns" is the default for no selection across our tables. 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/1cc63c9f-b1d6-4881-bbbe-b83d56fd081f)

**Comment by petertgiles** [comment]
The form labels, for reference:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/556dd4c0-088b-42fb-9997-96f07f922654)

**Comment by Jerryescandon** [comment]
So ideally it's the name for each column, which I guess we should make sure we have a short label for, for example:
**Full name** in the **Request form** becomes **Manager** in the column title

so:

| Request form | Column title |
|--------|--------|
| Full name | Manager |
| Department / Hiring Organization | Department |
| Government email | Email |
| Job title for this position | Job title |
| Additional comments | Details | 
| Admin Notes | Notes |

**Comment by vd1992** [comment]
Thank you!
