### ISSUE TITLE
✨ Update the Success page for IAP

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#6484]
## ✨ Feature

The text for the Application Success page should be slightly different for the IAP

## 🕵️ Details

Waiting for final details from @BrookeCameron 

## 🎨 Design File

https://www.figma.com/file/8piNhFaBjcxssBB8LAGxEY/IAP-User-flows?type=design&node-id=269-77412&t=828ocLgaA824uw8h-0

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/c9aff105-c093-4214-99cf-98513da39478)

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

| String | En | Fr |
| --- | --- | --- |
| Msg Body | Thank you for your interest in becoming an IT apprentice with the Government of Canada. Your lived experience, skills, passion and interests are warmly received and acknowledged. A member of the Office of Indigenous Initiatives team will contact you within the next three to five business days to discuss your application. | ??? |
| Link to Profile | Update profile and contact information to ensure you receive notifications. | ??? |

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] On IAP, success page text matches new design

**Comment by tristan-orourke** [comment]
@BrookeCameron is the version in Figma good to go, content-wise?

**Comment by BrookeCameron** [comment]
@tristan-orourke Nay, please use [this version](https://www.figma.com/file/8piNhFaBjcxssBB8LAGxEY/IAP-User-flows?type=design&node-id=269-76293) as I've updated the buttons for consistency, and some minor copy changes (with annotations)

**Comment by BrookeCameron** [comment]
we are still waiting on the confirmation copy from the IAP team but should be receiving that later today!
