### ISSUE TITLE
♻️ Bump `@testing-library/cypress` to `9.0.0`

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#6510]
## ♻️ Debt/Refactor

Breaking changes need manual bump.

## 🕵️ Details

You can find breaking changes on the [release page](https://github.com/testing-library/cypress-testing-library/releases/tag/v9.0.0).

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] `@testing-library/cypress` is on version `>= 9.0.0`
- [ ] `e2e` tests still run and pass as expected

**Comment by mnigh** [comment]
Closed as part of #6678.
