### ISSUE TITLE
🐛 Application Revamp: Edit experience causes infinite loop

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#6533]
## 🐛 Bug

Clicking "Edit" on an existing experience causes an infinite load loop

## 🦋 Expected Behaviour

Clicking the edit link should navigate to the edit experience page

## 📋 Steps to Reproduce

1. Start an application, advance to the "Create your resume" page
2. Click "Edit" on an experience
3. Observe that navigation never completes

## 📸 Screenshot

https://images.zenhubusercontent.com/364642496/93c76d42-35bd-4d67-adc2-f277badd2e92/simplescreenrecorder_2023_05_08_14_45_20.mp4

## ✅ Acceptance Criteria

- [ ] Clicking the edit link should navigate to the edit experience page

**Comment by vd1992** [comment]
Can't play the video, but is it the same as #6523 ?

**Comment by petertgiles** [comment]
Oh yeah, that's it.
