### ISSUE TITLE
🐛  Uncaught Exception occurred in prod environment (ErrorEvent: ResizeObserver loop completed with undelivered notifications.)

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#6542]
## 🐛 Bug

Uncaught Exception occurred on user profile personal experience creation 

## 🕵️ Details

**Link:** https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22:%22e45226c5-f9e9-4979-9016-96ba27b156cb%22,%22ResourceGroup%22:%22rg_tbs_talent_2_PaaS%22,%22Name%22:%22TalentCloud%22%7D/DataModel/%7B%22eventId%22:%22885985f5-eec3-11ed-a80a-002248af5527%22,%22timestamp%22:%222023-05-09T23:44:40.57Z%22%7D

**Operation Name:**  ~profile/experiences/personal/create

**Problem Id:** ErrorEvent: ResizeObserver loop completed with undelivered notifications.

**Exception Type:** ErrorEvent: ResizeObserver loop completed with undelivered notifications.

**Method:** Unknown

**Outer Exception Type:** ErrorEvent: ResizeObserver loop completed with undelivered notifications.

**Outer Exception Message:** ErrorEvent: ResizeObserver loop completed with undelivered notifications.

**Operating System:** Windows 10

**Browser version:** Firefox 112.0

## 📋 Steps to Reproduce

BS can't reproduce in Mac with Firefox 
PG can't reproduce in Linux with Firefox

## ✅ Acceptance Criteria

- [ ] Determine how to reproduce
- [ ] Provide a fix

**Comment by petertgiles** [comment]
I remember when we discussed this as a team there was a suspicion that this was related to the dropdown menu on the skill picker.  If so, this error may soon disappear as we have a [new skill picker](https://github.com/GCTC-NTGC/gc-digital-talent/issues/5054) inbound.  Of course, we may see it again when we use the dropdown for other things.

I did some Googling on this and it seems like this error is usually related to scroll animations stuttering.  It may be that this can only be reproduced on low-performance devices or with certain extensions running.  The consensus seems to be it's a harmless error that can be ignored.  I suggested rescoping this issue updating our code to prevent this error from being logged.

https://www.google.com/search?q=ResizeObserver+loop+completed+with+undelivered+notifications+site:stackoverflow.com

**Comment by petertgiles** [comment]
Next steps: Brinda will try to ignore it in Azure

**Comment by mnigh** [comment]
> Were we able to ignore this or is it still an issue? 🤔

@brindasasi bump for 2024! is this now being ignored in azure or is it still an issue?

**Comment by brindasasi** [comment]
The error logs still show up on Azure randomly.

**Comment by mnigh** [comment]
> The error logs still show up on Azure randomly.

@brindasasi Is it not possible to filter out/ignore these types of errors in Azure?

**Comment by mnigh** [comment]
> ## 🕵️ Details
> **Operation Name:** ~profile/experiences/personal/create

Isn't this a legacy route anyway? We use `/users/:user-id/personal-information/career-timeline/create` now and have for a little while.

**Comment by brindasasi** [comment]
yes..I just looked up and the error is happening on the new url .. last time it was on March 3rd  
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/3aae2854-2e22-467a-b4dc-35dd2ed309e8)

**Comment by brindasasi** [comment]
It is still happening on prod in the same area, Create or Edit experience. :(

**Comment by esizer** [comment]
> yes..I just looked up and the error is happening on the new url .. last time it was on March 3rd on **Edit**

Do we get a user agent to go along with that error and is that the only page this appears on? I have been trying very hard to reproduce this issue and cannot 😢 Last time I looked it up, someone said that it could be caused by browser extensions. I looked into it and I can;t find any components on that page that even use the `ResizeObserver` api 😕

**Comment by brindasasi** [comment]
So far I've seen only on that page.
