### ISSUE TITLE
✨ Add "Duplicate pool" button

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#6546]
## ✨ Feature

A new button at the bottom of the "Edit pool" page that creates a duplicate pool.

## 🕵️ Details

This button creates a new pool, and pre-populates MOST of the information with the data from the origin pool.

The only data not copied over is:

- **Status**: the status of the duplicated pool should be set to 'Draft'
- **Closing date**: the closing date should be left empty
- **Specific title**: specific title should be specific title + "(copy)" in both english and french "(copie)" e.g: "React specialist (copy)"

When pressing the button, a dialog will open up to verify the action before proceeding.

Duplicating successfully will navigate the user to the "Edit pool" page of the newly created pool.

If there are unsaved changes on the pool, the duplicate should fail and inform the user of unsaved changes.

### TOASTS
Green toast notification for success:

`"Success: This pool has been duplicated successfully."`

Red toast notification for UNSAVED CHANGES error:

`"Error: You have unsaved changes on this pool, please save all field before duplicating this pool."`

Red toast notification for OTHER errors:

`"Error: Something went wrong, please try again in a minute or contact your administrator."`

## 🎨 Design File

Include a link to the design file (if it exists).

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/f6d17007-e3af-407e-a05e-2127550744d4)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/44c9ddd7-141e-4d58-a004-617c2d6e5f9b)

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] If there are unsaved changes on the page, duplicate button throws a toast saying you have to save everything first
- [ ] Duplicate Pool button creates a new pool which is a duplicate of current pool, except for status, closing date, and specific title (detailed above)
- [ ] If pool creation is successful, throw a toast and navigate to edit page of new pool
- [ ] If pool creation fails, show error toast

**Comment by vd1992** [comment]
Pool creation is limited in its input, so as is, the approach would be
- send create pool mutation with classification of the pool on the page
- mutation successful and returns id of created pool
- send update pool mutation with the returned id and the rest of the info of the pool on the page
- mutation successful and returns id again, then re-direct to the new pool and toast success
- error and stop if any mutations had failed

Thoughts, @tristan-orourke  ?

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/b8868339-4563-4cce-875b-ee21c85b3e0f)

**Comment by tristan-orourke** [comment]
Yep @vd1992, that's the logical process with the API as it is.

However, it might be worth it to update the createPoolAdvertisment mutation so it can accept the same input as updatePoolAdvertisment. Then the cloning can be done with one step. Everything in `UpdatePoolAdvertisementInput`, so it's not even a breaking change.
