### ISSUE TITLE
🐛 "On this page" not vertically align with first heading on application pages

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#6572]
## 🐛 Bug

"On this page" is not lined up with the first heading on application pages.

## 🦋 Expected Behaviour

Top of "Step X of X" should line up with "Review your submission"

## Screenshots

![Screen Shot 2023-04-25 at 15 38 13](https://user-images.githubusercontent.com/3046459/234385048-c65930df-0cc9-4562-bd6b-4d6dd6746d41.png)
![Screen Shot 2023-04-25 at 15 37 49](https://user-images.githubusercontent.com/3046459/234385051-f0688858-b76c-41f7-a63d-8cc97ca733a7.png)
</div>

**Comment by esizer** [comment]
I tried my best to fix alignment, got it close. But, is it close enough?

![toc-alignment.png](https://images.zenhubusercontent.com/624af7203bd4eddbbafed4b8/ad56c3ed-a0f3-44b9-97e4-68390537aafd)
