### ISSUE TITLE
✨ Enable soft delete to archive pools

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#6578]
## ✨ Feature

We have had this button (non-functional) on the "Edit pool" page for a long time and it's becoming more and more useful as pools start to expire. This would remove the clutter from the current Pools table and make them easier to manage.

### "Archive" button

The "Archive" button should only be visible if the pool's current status is "Closed". 

The "Archive" button should prompt a dialog to confirm the archive action.

When confirmed, the pool's status should change from "Closed" to "Archived"

### "Un-archive" button 

When a pool has been archived. A new button appears  next to this status to "Un-archive" this pool.

The "Un-archive" button should only be visible if the pool's current status is "Archived"

The "Un-archive" button should prompt a dialog to confirm the un-archive action.

When confirmed, the pool's status should change from "Archived" to "Closed"

### ⚙️ New functionality in other pages

"Archived" pools should be **hidden by default** in the Pools table

"Archived" pools should **NOT show up** on a the request page as options to submit requests. Nor it's candidates be counted towards the request results.

"Archived" pools should **NOT show up** on lists of pools available for "Add user to pool" in the pool information section on a user's information page.

"Archived" pools should **NOT show up** on lists of pools available for "Batch change status" in the pool information section on a user's information page.

On the candidate public facing side, an "Archived" pool behaves the same as a "Closed" pool for the purposes of any logic tied to it.

## 🎨 Design File

Include a [link to the design file](https://www.figma.com/file/tH8X3HEgXsQVGTa2eheH8P/Pool-Updates---Admin-(elisa)?type=design&node-id=1618%3A6064&t=CQyQmZR1UhCudnQW-1) 

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/43c9bd59-98c8-4eac-95c0-7a87cf8f3a1c)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/65dd798d-aa5c-4a48-8e1c-23476db9c2f2)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/9f38db47-c2cb-42e4-9692-3ae4a5a74500)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/882e8f81-42ef-47e8-aa88-3123ba971488)

## 🙋‍♀️ Proposed Implementation

Use the soft-delete functionality built-in to Eloquent models.  The deleted_at column already exists in the database table.

**Comment by petertgiles** [comment]
How are we implementing this?  A new timestamp `archived_at`?  Just soft delete - there's already a `deleted_at` column?  A status column?

**Comment by petertgiles** [comment]
Proposed implementation : soft delete, 1 issue

**Comment by vd1992** [comment]
For reversing this, might be best to leverage this: 

https://laravel.com/docs/10.x/eloquent#retrieving-only-soft-deleted-models

A query to grab all archived pools and only them, then you can reverse whichever as needed. You need the list of what is archived to then navigate to the appropriate pool's page. 
This is important as you need some method then to reach what is archived as you may not have the id saved on hand.

**Comment by vd1992** [comment]
@Jerryescandon 

I think a place to find pools that are archived will also be handy, otherwise it could be hard to interact with archived pools. 
That could be its own issue though

**Comment by Jerryescandon** [comment]
ARCHIVED POOLS CAN GO KICK A ROCK VACHAN!

**Comment by Jerryescandon** [comment]
I think a filter on the main pools table might be good enough for now tho

**Comment by vd1992** [comment]
Thanks for the answer
There isn't any filtering yet for the pools table so that will probably need to be its own addition and issue 😅

**Comment by petertgiles** [comment]
@Jerryescandon Could you please update the Figma link in this issue?
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/54f6d426-22e5-4aaf-ade0-404d23a5a0d1)

**Comment by petertgiles** [comment]
@Jerryescandon Could you take a second look at this sentence?
> All users associated with this pool will be able to see it on their profile information.

I would expect "see it on their profile" or "see it in their profile information".

**Comment by Jerryescandon** [comment]
"in" instead of "on" makes sense to me.

🤔 although the profile information page is only admin, but candidates would be able to see this too on their dashboard and stuff, so we doulc also make something like

"Any user associated with this pool will be able to view and regain any associated access to it." 

too convoluted????

**Comment by petertgiles** [comment]
> too convoluted????

It's a bit much.  :laughing:  I'll make the small change to "in" for now but let me know if you find something you're happier with.

**Comment by tristan-orourke** [comment]
Talked to DCM about archiving pools with candidates in them...
On the one hand, they don't expect to archive pools with active candidates in them. They expect to want to archive pools that were created by mistake, or never published, or are expired and empty of candidates. However, from their perspective, this is mostly about managing a cluttered admin UI.  I think therefore we should avoid cascading effects.

So: don't soft-delete PoolCandidates in a soft-deleted pool. They should still show up in searches if they would otherwise. And the poolCandidate.pool should be accessible even if soft deleted.
