### ISSUE TITLE
✨ PHP linter for GitHub workflow ci and VS Code

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#6580]
## Description
The GitHub workflow that is used to [lint](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/.github/workflows/lint.yml) the codebase does not run a linter for PHP even though our API is written in PHP. Discussed in https://github.com/GCTC-NTGC/gc-digital-talent/discussions/6454

## Acceptance Criteria

- [ ] PHP linter works for both GitHub workflow ci and VS Code

**Comment by vd1992** [comment]
To be done in #7697
