### ISSUE TITLE
✨ Move the api and tcreport services to their own subdomains

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#6583]
## ✨ Feature

To help simplify routing, we want to move the API service to its own subdomain (domain api) and also the tcreport (domain report).

## 🙋‍♀️ Proposed Implementation

Refer to #5978 for information on the website setup
Refer to #4396 for information on the subdomain procurement

## ✅ Acceptance Criteria

- [ ] Mock auth works normally
  - [ ] login, logout, refresh
- [ ] Sign In Canada works normally
  - [ ] login, logout, refresh
  - [ ] local, dev, uat, prod
  - [ ] Will need to work with SIC team to add new callback endpoints
- [ ] graphql, ticketing, and any other api endpoints continue to function normally
- [ ] permanent redirect entries add to routing to maintain existing links for major tcreport pages
- [ ] env values updated locally and in Azure

**Comment by mnigh** [comment]
@petertgiles what is the status of this issue?

**Comment by petertgiles** [comment]
> @petertgiles what is the status of this issue?

I'm a bit interested but I don't think it's high on anyone's priority list.

**Comment by mnigh** [comment]
Related discussion https://github.com/GCTC-NTGC/gc-digital-talent/issues/5186#issuecomment-1437555550.

**Comment by mnigh** [comment]
@petertgiles should this be put in the icebock, closed, or something else other than the nebulous no status?

**Comment by mnigh** [comment]
@petertgiles are you still interested in moving this forward or can 🎅 wield his holiday 🪓 and close this?

**Comment by petertgiles** [comment]
Yeah, I guess we can close it.  I'd still like to do this someday but I can repoen it then.  In the meantime we have managed to simplify our Nginx routing file in other ways.
