### ISSUE TITLE
✨ Improve readability of printed profiles

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#6588]
## ✨ Feature

Current printed profiles seem to have a big problem in terms of readability, the visual hierarchy is cumbersome and extremely hard to parse for any useful information. We want to improve the quality of the Printed profiles by adding a little formatting to the output. 

## 🕵️ Details

[This is the current state of the printout.](https://drive.google.com/file/d/1rS-9NlK49xb8_hKmcH-npx2M7vpyp-9x/view?usp=sharing)

[This is the proposed formatting.](https://docs.google.com/document/d/13epIYbnfFdYc-T1_d8SqCKhaJcAVJEXDYkhGBmzLLdA/edit?usp=share_link)

In the images below you can see a quick comparison between formatting. If we remove some of the excess copy, exchange the default font, and use a more sensible use of bolding and titles we can reduce much of the visual noise.

## 🎨 Design File

Include a link to the design file (if it exists).

### OLD EXPERIENCE FORMATTING

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/5a830888-e930-4147-9e0f-104c89aaf0ab)

### NEW EXPERIENCE FORMATTING

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/b91028b7-1c22-4b7c-a06f-a2454e969772)

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] New fonts match design for the profile downloads
- [ ] New heading hierarchy should match designs
- [ ] Experiences shown as a list instead of headings
- [ ] Needs to work with single and multiple profile downloads
- [ ] Check to make sure it works with edge

**Comment by gobyrne** [comment]
This looks good, these will be sent to managers, so definitely worth the extra effort to tidy them up.

**Comment by mnigh** [comment]
@Jerryescandon is there a reason you decided to use title case instead of sentence case? It would be a lot easier if we could use sentence case for reuse of strings.

**Comment by mnigh** [comment]
> > @Jerryescandon is there a reason you decided to use title case instead of sentence case? It would be a lot easier if we could use sentence case for reuse of strings.
> 
> where exactly? on the experiences? I am mostly interested in parsing / visual hierarchy to be more logical. (from big to small) Although we should make sure it should still makes sense when sifting through it with a keyboard I guess?

The profile section titles (related to #6808). I see that you have accepted my suggestions in the google doc, thanks!
