### ISSUE TITLE
🐛 Pool Candidates Table storybook renders Unexpected Application Error

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#6595]
## 🐛 Bug

Pool Candidates Table renders table in storybook with **Unexpected Application Error**.

`TypeError: Cannot read properties of undefined (reading 'user')`

## 🦋 Expected Behaviour

Pool Candidates Table renders table in storybook without **Unexpected Application Error**.

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Name and version (if possible).
- **Browser**: Name and version (if possible).

## 📋 Steps to Reproduce

1. Run storybook
2. Navigate to **Pool Candidates Table**
3. Observe **Unexpected Application Error**

## 📸 Screenshots

![Screen Shot 2023-05-15 at 10 31 34](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/72949a29-8aad-4b47-b8bd-33a049236c0a)
![Screen Shot 2023-05-15 at 10 33 46](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/832d9263-12f7-48c4-b176-e3dd0c832ff5)
![Screen Shot 2023-05-15 at 10 33 19](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/eb347cc0-0759-424c-81b5-8ffaf388e226)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Pool Candidates Table renders table in storybook without **Unexpected Application Error**
- [ ] Solved in the Review Resume story as well #6599

**Comment by vd1992** [comment]
Same issue with Review Resume

https://www.chromatic.com/build?appId=61e099a1bb1465003a73d3ce&number=4854

**Comment by mnigh** [comment]
> Same issue with Review Resume
> 
> https://www.chromatic.com/build?appId=61e099a1bb1465003a73d3ce&number=4854

@vd1992 I've created a new issue out of the story you flagged since it uses different component: https://github.com/GCTC-NTGC/gc-digital-talent/issues/6599
