### ISSUE TITLE
✨ Request status upgrade

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#6601]
## ✨ Feature

DCM needs more granularity when tracking requests, they want to add more statuses to accurately track and manage the progress of any request.

## 🕵️ Details

Replace the status button "Pending > Done" for a dropdown and a save button that would allow different statuses to be selected.

We'll also need to update the filter added in #6365 

## 🎨 Design File

Include a[ link to the design file](https://www.figma.com/file/dDo0sUzYFyplp7DvlLHKYJ/Admin---Requests-details?type=design&node-id=104%3A493&mode=design&t=xdbyzY5g5fzcXaw3-1)

## 📸 Screenshot

Instead of "Other (see notes)", use "Waiting (see notes)" for the blocked status.

![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/b66c1399-a9eb-428d-8100-09654a719dd3)

## 🙋‍♀️ Proposed Implementation

Add startedAt and blockedAt fields to the request.

Conceptually, the status dates follow an order: startedAt -> blockedAt (optional) -> doneAt. The latest non-null value determines what we consider its status to be. If all three are null, the request is Pending. If blockedAt is non-null, the status is Waiting, regardless of whether startedAt is null or not. 

When the status changes, the date for that status is reset, and all 'later' dates are nullified.

We could have a computed column which keeps the final status up to date, as we've done elsewhere.

OR

Filtering and ordering by the status column might be vastly simpler if we switch to a single STATUS enum column, and track changes with some kind of [history table](https://medium.com/sammich-shop/simple-record-history-tracking-with-laravel-observers-48a2e3c5698b) if we really want.

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Request Responder users can change request status between the 4 shown statuses
- [ ] Status appears on the request table. Ordering by status column orders rows in intuitive order (pending, started, blocked, done; or the reverse)
- [ ] Requests can be filtered by all statuses, on the Requests table

**Comment by gobyrne** [comment]
@Jerryescandon figma and screenshot update please for these options.
1. New
2. In progress
3. Waiting (See notes)
4. Done

**Comment by vd1992** [comment]
The enum status method is the simpler solution, but are there any possible downsides to be wary of? Any expected features on the 
horizon that will not play nice with it?

**Comment by vd1992** [comment]
@Jerryescandon 
The design file linked appears locked, does it need to be unlocked?

**Comment by Jerryescandon** [comment]
> @Jerryescandon The design file linked appears locked, does it need to be unlocked?

fixed it

**Comment by vd1992** [comment]
> > @Jerryescandon The design file linked appears locked, does it need to be unlocked?
> 
> fixed it

Sorry, but it still is trying to get me to login or sign-up. All I am doing is clicking the link under "Design file"

**Comment by Jerryescandon** [comment]
> > > @Jerryescandon The design file linked appears locked, does it need to be unlocked?
> > 
> > 
> > fixed it
> 
> Sorry, but it still is trying to get me to login or sign-up. All I am doing is clicking the link under "Design file"

fixed it again 😬

**Comment by vd1992** [comment]
> > > > @Jerryescandon The design file linked appears locked, does it need to be unlocked?
> > > 
> > > 
> > > fixed it
> > 
> > 
> > Sorry, but it still is trying to get me to login or sign-up. All I am doing is clicking the link under "Design file"
> 
> fixed it again 😬

All good now, thank you!
