### ISSUE TITLE
❓ Did changing cache policy improve load times of static assets?

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#6604]
## ❓ Question

Did #6257 make #6162 redundant?

## 🕵️ Details

After doing #6257, are we happy with load times? You can compare current with previous findings from #6070. 

## 🕙 Timebox

2 hours

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] #6162 is either closed, or has additional comments explaining how its still necessary

**Comment by vd1992** [comment]
Not sure what to check exactly but here it goes

Live site, homepage. Caching enabled. 
Visit page. then refresh. Quickest due to memory cache

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/104ba57b-7d7d-42ad-92ae-9205f3438973)

Visit page, close browser. Re-open browser, navigate to page. Not as quick due to disc cache.

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/f07b2019-1eba-48dc-849d-e6f92eb74969)

**Comment by vd1992** [comment]
App.js headers

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/9ef0af58-9841-4521-b80c-b8b1bd8c7ab2)

**Comment by vd1992** [comment]
Appears to be caching successfully, and feels snappy to me. Refreshing to use the memory cache feels nigh-instantaneous 

https://recordit.co/GBF1wshsYe

I think it might not be worth the effort fretting over this more. Rather, optimize images a bit more (#6165) and consider HTTP2.

**Comment by petertgiles** [comment]
For reference, the HTTP/2 issue: https://github.com/GCTC-NTGC/gc-digital-talent/issues/8350

**Comment by petertgiles** [comment]
I think it's worth focusing in on the original question of the spike:
> Did https://github.com/GCTC-NTGC/gc-digital-talent/pull/6257 make https://github.com/GCTC-NTGC/gc-digital-talent/issues/6162 redundant?

Remember that 6162 is about using the Azure CDN to improve download speeds of static content for _first time_ downloads, not locally caching assets for repeat visits.  So, if you disable your local cache and force everything to be downloaded fresh, are you getting good reliable speed on your static content downloads are is there room for improvement if we had the content coming from a nearby CDN?  We hoped that marking assets as public in 6257 would allow a user's ISP to do some caching for them.

**Comment by petertgiles** [comment]
We did some comparisons of downloading the initial JS bundle uncached between Niagara (closer to Toronto) and Calgary (farther away).  The results were pretty variable which makes it difficult to assign much significance to the results.  It averaged out to about 250ms in Niagara vs 300ms in Calgary.  It suggests that we might see a slight improvement by adding a CDN but the advantage would be slight enough to not make it worth worrying about now.

**Comment by vd1992** [comment]
Spike resolved, parent issue 🧊 'd for now
