### ISSUE TITLE
✍️ Update and fix inconsistent date formatting on the candidate application index

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#6649]
## 🌟 Details

It seems that the candidate view of their application list, when viewed in French, is showing multiple problematic copy:
- Deadline passed text is showing in English
- Date formatting is inconsistent across states (see screenshot included below)

## 🗃️ Tasks

- [ ] Ensure that "The deadline for submission has passed." is properly translated and showing in French
- [ ] Enforce a consistent date format in French, specifically following `day month year time`
  - e.g. `1 septembre 2023 02:59`

## 📸 Screenshots
<details><summary>Examples of incorrect formatting and English text</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/bfa947cd-2ab8-4a9d-9ce9-ff6d10504fb0" />
</details>

**Comment by vd1992** [comment]
The "the deadline for..." string also appears as untranslated on the new job poster page.
I believe both are output by the function `relativeClosingDate`, appears its intl process breaks somewhere

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/75bc5b86-fd8d-4aa0-a9c5-90984f1a7418)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/d99a12ac-9ddd-4f01-817f-1cd5d94f5461)

**Comment by mnigh** [comment]
> The "the deadline for..." string also appears as untranslated on the new job poster page. I believe both are output by the function `relativeClosingDate`, appears its intl process breaks somewhere
> 
> ![image](https://user-images.githubusercontent.com/40485260/239380593-75bc5b86-fd8d-4aa0-a9c5-90984f1a7418.png)
> 
> ![image](https://user-images.githubusercontent.com/40485260/239380815-d99a12ac-9ddd-4f01-817f-1cd5d94f5461.png)

All of the `intl` strings in https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/packages/date-helpers/src/index.ts are missing French translations.
