### ISSUE TITLE
✨ Add modal to request page "skill match" column

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#6658]
## ✨ Feature

To improve the speed at which DCM validates the experience of requested candidates against the skills in a request, we want to include a modal that opens up from the skill match column that includes the experiences tied to the skills requested.

This would make it easier to find the right candidate by allowing DCM to view the relevant skill information without leaving the request page, and limiting the experience that shows up to only the ones relevant to a specific request. (As opposed to experiences on profile which show all experiences).

## 🕵️ Details

On the request page, on the results table, make the "Skill matches" column a clickable column

Clicking on the skill match number opens up a dialog that showcases ONLY the relevant experiences to the skills selected for that individual candidate.

The modal is read only, no other interaction happens.

If a skill is linked to a profile, but has no experiences attached it shows a null state.

## 🎨 Design File

Include a link to the design file (if it exists).

## 📸 Screenshot

https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/3be61cce-b3ee-4d14-9cc3-235956378388

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/a8e55c8d-5954-45da-be07-4d22ef05111e)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/bf7982f8-9d71-46ca-b9e7-aa5e14bb6598)

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] The skills that show on the modal are the skills used as filters applied to the table NOT the skills submitted on the request itself
- [ ] If a skill is linked to a profile, but has no experiences attached it shows a null state
- [ ] In the dialog use the skill UI from the profile snapshot view

**Comment by vd1992** [comment]
Don't worry about skills filtering at first, to be improved upon later.
The skills within the modal do not need to be interactive either.
