### ISSUE TITLE
♻️ Tables missing foreign key constraints

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#6709]
## ♻️ Debt/Refactor

The following tables are missing foreign key constraints for the fields listed (as sub-items):

- applicant_filter_classification
    - applicant_filter_id
    - classification_id
- applicant_filter_pool
    - applicant_filter_id
    - pool_id
- applicant_filter_qualified_classification
    - applicant_filter_id
    - classification_id	
- applicant_filter_skill
    - applicant_filter_id
    - skill_id
- classification_user
    - classification_id
    - user_id
- generic_job_title_user
    - generic_job_title_id
    - user_id
- generic_job_titles
    - classification_id
- permission_user
    - user_id
- pools
    - team_id
- role_user
    - user_id
- team_department
    - team_id
    - department_id

## ✅ Acceptance Criteria

- [ ]  table have appropriate foreign key constraints via migrations

**Comment by mnigh** [comment]
@petertgiles here is a list of tables with fields that end in "_id" that do not have a foreign key constraint. are any of these false positives or do they all need a foreign key constraint?

- applicant_filter_classification
    - applicant_filter_id
    - classification_id
- applicant_filter_pool
    - applicant_filter_id
    - pool_id
- applicant_filter_qualified_classification
    - applicant_filter_id
    - classification_id	
- applicant_filter_skill
    - applicant_filter_id
    - skill_id
- classification_user
    - classification_id
    - user_id
- experience_skill
    - experience_id
- generic_job_title_user
    - generic_job_title_id
    - user_id
- generic_job_titles
    - classification_id
- notifications
    - notifiable_id
- permission_user
    - user_id
- personal_access_tokens
    - tokenable_id
- pool_candidate_education_requirement_experience
    - experience_id
- pools
    - team_id
- role_user
    - user_id
- team_department
    - team_id
    - department_id

**Comment by petertgiles** [comment]
> are any of these false positives

Wow, thanks for pulling all these! :exploding_head:   Looking at this list reminds me that there will be some we can't do - the polymorphic relationships.  Since these point to more than one table we can't constrain them.  So that would be all the `*able_id` fields and the experience_id fields.  All the rest should be good to go, though. :+1:
