### ISSUE TITLE
♻️ Update graphql-codegen/ dependencies to v4

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#6726]
## 🕵️ Details

Bump
graphql-codegen/typescript
graphql-codegen/typescript-operations
to 4.0.0

Put both dependencies in this issue as I feel they probably need to be updated simultaneously. 

https://github.com/GCTC-NTGC/gc-digital-talent/pull/6716
https://github.com/GCTC-NTGC/gc-digital-talent/pull/6722

https://github.com/dotansimha/graphql-code-generator/tree/HEAD/packages/plugins/typescript/typescript
https://github.com/dotansimha/graphql-code-generator/tree/HEAD/packages/plugins/typescript/operations

## ✅ Acceptance Criteria

- [ ] Dependencies updated

**Comment by mnigh** [comment]
Closing as stale since these dependencies will be removed as part of https://github.com/GCTC-NTGC/gc-digital-talent/issues/8720.

**Comment by mnigh** [comment]
Closing as stale since these dependencies will be removed as part of https://github.com/GCTC-NTGC/gc-digital-talent/issues/8720.
