### ISSUE TITLE
🛠️ Add shellcheck to lint our bash scripts

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#6730]
## 🛠️ Tooling

Bash scripting is finicky, and sometimes hard to track best-practices and bugs between sh and bash and other shells. It also often fails quite silently. Let's set up simple linting to never have to worry about checking for the obvious things manually

## 🕵️ Details

Initiated from this PR: https://github.com/GCTC-NTGC/gc-digital-talent/pull/6708#pullrequestreview-1446315312

Found an obscure getopts bug while dropping the script manually into https://www.shellcheck.net/

## 🙋‍♀️ Proposed Solution

Implement the github action for running shellcheck automaitically via reviewdog. Reviewdog is a tool that turns each lint catch into a comment, including a suggested fix if available.

https://github.com/reviewdog/action-shellcheck

<img width="1064" alt="Screen Shot 2023-05-26 at 4 03 07 PM" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/305339/988caec1-66a9-4154-9785-5b596e388355">

## ✅ Acceptance Criteria

- [ ] shellcheck runs in its own github action
- [ ] review comments are created for errors
- [ ] all existing warnings are addressed (perhaps 20 small fixes)
  - [ ] `infrastructure/bin/deploy.sh`
  - [ ] `infrastructure/bin/post_deployment.sh`
  - [ ] `infrastructure/bin/set_php_versions.sh`
  - [ ] `infrastructure/bin/substitute_file.sh`
  - [ ] `maintenance/scripts/lib/common.sh`
  - [ ] `maintenance/scripts/refresh_all.sh`
  - [ ] `maintenance/scripts/refresh_api.sh`
  - [ ] `maintenance/scripts/refresh_frontend.sh`
  - [ ] `maintenance/scripts/setup.sh`
  - [ ] `maintenance/scripts/update_env_appkey.sh`

**Comment by mnigh** [comment]
@GCTC-NTGC/developers is this something we are interested in doing or not?

**Comment by brindasasi** [comment]
am neutral. should we close it then?
