### ISSUE TITLE
⚙️ Update the Accordion component

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#6734]
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/8352d5e6-ce21-450a-af19-4f20db6eccb4)

## ✨ Summary

[Visit the Figma file](https://www.figma.com/file/guHeIIh8dqFVCks310Wv0G/Style-library?type=design&node-id=5-20&mode=design) • Contact @substrae with design questions

Related to [#6735](https://github.com/GCTC-NTGC/gc-digital-talent/issues/6735)

As a part of the experience card updates, the accordion (AKA expansion, drawer, expand-collapse, details, etc.) has been updated to provide a bit more flexibility and usage contexts.

```[tasklist]
### ✅ Requirements
- [ ] Accordions can have two visual styles: simple and card
- [ ] Accordions can be grouped and are spaced as conveyed in the design
- [ ] Accordion groups should have the ability to be toggled all open/all closed (the button to this isn't part of the component, as it varies depending on the context)
- [ ] Accordion labels should NOT be underlined
- [ ] Accordions have the designed focus states
- [ ] All standard accordions on the site have been replaced/updated with this design
- [ ] The spacing has been updated component-wide
- [ ] The divider between trigger and content has been removed
``` 

### Accessibility

- Accordions should announce their interactivity and current state to AT
- Generally, accordion titles should be written as an action (e.g. Show more..., Learn more about..., Reveal information on...)
- Where applicable, accordion titles should be able to change to reflect their state (e.g. show >> hide)

<details>
  <summary>📸 Focus states</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/43e81624-773c-4620-89f1-2dc0d6ff731f" />
</details> 

### Typography

Accordion trigger elements should adapt based on the font-size applied to the title value. The Figma file provides designs for the 3 options currently in use: `copy`, `h6`, and `h5`. Note that the size and stroke on the chevron icon changes to match the heading level.

<details>
  <summary>📸 Typography examples</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/e1b99930-4322-4a5b-b24f-2ff24d63bad1" />
</details> 

### Grouping accordions

<details>
  <summary>📸 Simple group</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/4dbea643-420e-46aa-884a-303c9feb2465" />
</details> 

The older card-style accordion has been deprecated in favor of this more generic card-style that can be used in multiple contexts. 

<details>
  <summary>📸 Card group</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/fc7d53bc-85c4-425b-af04-cf477f1ed1d0" />
</details>

**Comment by RM-1978** [comment]
Related to:  #7006

**Comment by mnigh** [comment]
@substrae can this issue be closed?

**Comment by substrae** [comment]
Have the accordions been updated? If yes, absolutely!

**Comment by vd1992** [comment]
@mnigh @substrae 

I don't think this was completed

https://61e099a1bb1465003a73d3ce-lwyajisope.chromatic.com/?path=/story/components-accordion--default

This issue was blocked by #6735 but I don't see that issue having resolved this?

**Comment by substrae** [comment]
@vd1992 

Okay - weirdly enough, you would think that this issue would block #6735, not the other way around (updating a central component over a single instance of that central component). Let me know if there's anything I need to do here to move things forward.

**Comment by vd1992** [comment]
@substrae 

There appears to be some confusion as we've got a separate component, `Collapsible`, that appears to overlap significantly with this component in question, the `Accordion` 
We will probably need to pull you in a scrum or backlog refinement meeting to move things forward on this,

**Comment by petertgiles** [comment]
Decision from Josh and Eric: will continue to refer to this as Accordion.  This issue has nothing to do with the Collapsible component.

**Comment by petertgiles** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/6734?planning-poker) with Zenhub @brindasasi @esizer @JamesHuf @mnigh @tristan-orourke @vd1992 @yonikid15
