### ISSUE TITLE
⚙️ Create a QualifiedRecruitmentCard for the Resume page

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#6737]
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/02876d74-3769-4cff-bbc3-886ce12417c8)

## 🌟 Details ([Figma file](https://www.figma.com/file/2VF8cE4cctTBQUkPBcVxUG/3.-Patterns?type=design&node-id=703-60935))

This card is for representing a pool a user has qualified in, ie a "Qualified Recruitment", and is primarily intended for the Qualified Recruitments section of the the Resume page (#6773)

- Data types that have their own card on profiles are being given a theme color, in this case, recruitments are using `secondary`
- The card has been contains a simple accordion which lists the required skills of the pool
- The layout and language around card sub-actions has been updated, including the addition of `aria-label` text

### Accessibility

- Because experience cards are repeated in a list, it's important that interactive elements inside the card contain descriptive `aria-label`  values to ensure that link-navigation via AT reads things out properly
  - "Show this recruitment's skill assessments" >> "Show assessed skills for the IT-02 Web technician (Java) recruitment process"
  - "Hide this recruitment's skill assessments" >> "Hide assessed skills for the IT-02 Web technician (Java) recruitment process"
  - "Change your availability" >> "Change your availability for the IT-02 Web technician (Java) recruitment process"
  - "Copy recruitment ID" >> "Copy the IT-02 Web technician (Java) recruitment process' ID"

### Typography

- The card title should use the `h6` font-size while being whatever HTML heading is relevant for the page context
- The recruitment type should use the `secondary.darker` color
- The separator bullet should use `black`
- The "Awarded on" label and date should use `black.light`
- The details expansion should use the `copy` size variant`
- Label and value pairs inside the expansion all use the `copy` font size, with labels bolded 
  - The "Behavioural skills" section, if applicable, uses the `globe-americas` Heroicon from the `mini` set with the `secondary` color
  - The "Technical skills" section, if applicable, uses the `bolt` Heroicon from the `mini` set with the `secondary` color
- The availability message and copy ID link use the `caption` font-size; links are bolded 

### Size

Note that the top and bottom right corners use the `rounded` border-radius value and the card itself uses the `larger` box-shadow value.

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/caf9b008-8346-4479-b6d4-a85a0f15a540)

### Card groups

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/e203a2bc-6cb9-45d5-af53-3b554a153f03)

### Targeted recruitment vs. Ongoing recruitment

The only distinction between the two is that their type is indicated on the card below the title. For both, the expansion contains the assessed skills that were linked to the job advertisement.

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/6ad6b221-f11a-4938-983b-93ddad7fa28c)

### Qualified states

- All qualified states use the `success` variant of the chip component and contain the `shield-check` Heroicon from the `mini` set

####  Open availability

- The "open availability" message uses the `check-circle` Heroicon from the `mini` set with the `success` color

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/6e2c52d9-2cfe-41cd-b7ad-e9b2df90c06a)

##### Change availability dialog

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/31678a08-3321-435b-b3da-edc13592719b)

#### Closed availability

- The "unavailable" message uses the `no-symbol` Heroicon from the `mini` set with the `error` color

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/7fd71653-6b47-4644-8911-65f5859faf0f)

#### Hired

- The "you've been hired" message uses the `star` Heroicon from the `mini` set with the `quaternary.dark` color

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/3dd2d94d-b9e9-4f3c-8de9-86107684de3c)

### The expired state

- Uses the `error` variant of the chip component
- The "expired recruitment" message that replaces the availability control uses the `lock-closed` Heroicon from the `mini` set with the `gray.darker` color

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/29eafab9-e6b9-43cd-bf8a-10e32f39975d)

## Acceptance Criteria
These criteria apply to the card when isApplicantPlaced is true.
- [ ] The card has the described layout, colors, and typography
- [ ] The card displays whether the pool was a targeted or ongoing recruitment
- [ ] A simple accordion has been added to the card, which shows which required skills were part of the Pool
- [ ] A user can suspend their application, as long as the pool hasn't expired or they haven't been placed
- [ ] `Copy recruitment id` is a button which copies pool id to clipboard
- [ ] All interactive elements have aria-labels
- [ ] Hide the date for now - we do not currently record the "accepted-at" date
- [ ] For now, Accordion trigger text does not need to change based on open/close state, just use the "Show" version.
- [ ] This component is used on the Resume page (soft mutual dependency with #6773)

**Comment by tristan-orourke** [comment]
Replaced by combined issue #6747

**Comment by tristan-orourke** [comment]
Making this a standalone issue again, splitting it off from #6747

**Comment by tristan-orourke** [comment]
This should likely be a separate component, but it can be based on and very similar to TrackApplicationsCard

**Comment by tristan-orourke** [comment]
Only applications in the following states make sense for this component:

Status | Badge
-- | --
QUALIFIED_AVAILABLE | Qualified
QUALIFIED_UNAVAILABLE | Qualified
QUALIFIED_WITHDREW | Qualified
PLACED_CASUAL | Qualified
PLACED_TERM | Qualified
PLACED_INDETERMINATE | Qualified
EXPIRED | Expired (in red)

For the other states, I guess you can ignore the badge, or base it on what is shown in #6738 as a backup

Not-Qualified Statuses | Badge
-- | --
DRAFT | Continue draft (button)
DRAFT_EXPIRED | Submission date passed
NEW_APPLICATION | Application received
APPLICATION_REVIEW | Application under review
SCREENED_IN | Application pending assessment
SCREENED_OUT_APPLICATION | Screened out
UNDER_ASSESSMENT | Application pending assessment
SCREENED_OUT_ASSESSMENT | Screened out
REMOVED | Removed (in red) ???

**Comment by esizer** [comment]
> ### Targeted recruitment vs. Ongoing recruitment
> The only distinction between the two is that their type is indicated on the card below the title. For both, the expansion contains the assessed skills that were linked to the job advertisement.

How do we determine if a recruitment is targeted or ongoing? Is this something we are currently doing or something we will be introducing?
