### ISSUE TITLE
⚙️ Update the TrackApplicationsCard component

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#6738]
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/bad928c7-f954-426d-9be0-95f03344ef39)

## 🌟 Details ([Figma file](https://www.figma.com/file/2VF8cE4cctTBQUkPBcVxUG/3.-Patterns?type=design&node-id=703-60937))

Update the application summary card used on the Applicant Dashboard.

This component is currently called TrackApplicationsCard.

This includes the following changes:
- Data types that have their own card on profiles are being given a theme color, in this case, applications are using `primary`
- Language around the recruitment type is being added
- The layout and language around card sub-actions has been updated, including the addition of `aria-label` text
- Additional links on the card, depending on status

### Accessibility

- Because application summary cards are repeated in a list, it's important that interactive elements inside the card contain descriptive `aria-label` values to ensure that link-navigation via AT reads things out properly
  - "Continue draft" >> "Continue your application draft to the IT-01 Application developer (React) job"
  - "Review application" >> "Review your application to the IT-01 Application developer (React) job"
  - "Review job ad" >> "Review the IT-01 Application developer (React) job advertisement"
  - "Visit résumé" >> "Visit the IT-01 Application developer (React) recruitment on your résumé"
  - "Manage availability" >> "Manage your availability for the IT-01 Application developer (React) recruitment"
  - "Get support" >> "Get support for the IT-01 Application developer (React) job"
  - "Delete application" >> "Delete your application to the IT-01 Application developer (React) job"
  - "Copy application ID" >> "Copy your IT-01 Application developer (React) application's ID"

### Typography

- Card headers should use the `h6` font-size value but use the proper markup for their contextual placement on the page
- Recruitment type and deadline content should use the `copy` font-size value
- Card footer content should use the `caption` font-size value

### Size

Note that the top and bottom right corners use the `rounded` border-radius, and the card uses the `larger` box-shadow value.

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/f659ab81-b2c0-4fb7-a4ab-e88956f3185e)

### Card groups

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/1c239485-c290-4978-80af-a0ee61b61f0a)

### Targeted recruitment vs. Ongoing recruitment

The only distinction between the two is that their type is indicated on the card below the title.

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/7ddd8150-f2cd-4dd2-ba92-ae4a2454696d)

### Draft states

**All draft states include**
- The title is clickable and takes the user to continue their application
- The card contains a "Continue draft" button
- The card sub-actions allow the user to 
  - Check the job ad
  - Email the relevant pool owner/team for help
  - Delete the application (which prompts a confirmation dialog, described below)
  - Copy the application ID 

**Urgent draft state**
- Urgent drafts differ only in that the "Apply by" date is highlighted using `error.darker` for emphasis
- This should trigger when there is less than 3 days left to apply

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/d4669cb5-9703-4561-90dd-22b11a0d870d)

#### Deletion confirmation dialog

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/fd0baa7c-c311-474c-ae86-7d5a5deb621d)

### Pending states

**All pending states include***
- The card title is no longer clickable
- The "Continue draft" button is replaced by a `primary` status chip
- "Apply by" has changed to "Applied on"
- The card sub-actions allow the user to
  - Check their application (read only)
  - Check the job ad
  - Email the relevant pool owner/team for help
  - Copy the application ID

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/18f31595-0e19-4cc1-8e54-62bfd4d57ec2)

### Decision states

**All decision states include**
- The card title is still non-interactive
- The status chips are now unique (see below)
- The card sub-actions are unique, barring the ability to check their application, view the job ad, get support, and copying the application ID (see below)

**The qualified state**
- "Apply by" changes to "Applied on"
- The qualified status chip uses the `success` variant and contains the `shield-check` Heroicon from the `mini` set
- The card sub-actions include
  - Viewing the qualified recruitment on their résumé page
  - Managing their availability (same link as above)

**The screened out state**
- "Apply by" changes to "Applied on"
- The screened out status chip uses the `secondary` variant
- The card sub-actions include
  - Deleting the application (prompts the same dialog explained above)

**The missed submission date state**
- "Apply by" stays as is
- The missed date status chip uses the `error` variant
- The "Apply by" date is highlighted using `error.darker`
- The card sub-actions include
  - Deleting the application (prompts the same dialog explained above)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/1837af48-ed25-4373-b9a0-9a98180b273e)

## Acceptance Criteria
These criteria apply to the card when the applicationIsDraft is true, or when isApplicantPlaced is false.
- [x] The card has the described layout, colors, and typography
- [x] The "urgent draft" state is triggered when the submission time is less than 3 days away
- [x] The card displays whether the pool was a targeted or ongoing recruitment
- [x] Drafts, and only drafts, can be deleted using the designed modal
- [x] #7071
- [x] The described changes are applied when the application is submitted, moved under review, screened out, or expires as a draft
- [x] Get support action is an email link, using the support email associated with the Pool's Team QUESTION: or the TALENTSEARCH_RECRUITMENT_EMAIL? @gobyrne which email should we use?
- [x] Visit resume, an action which appears on Qualified applications, links you to the Resume page, scrolling directly to this recruitment (soft dependency on #6773)
- [x] Manage availability, which also only appears on Qualified applications, links you to the `Account and privacy settings > recruitment availability` section of the Profile (soft dependency on #6772)

**Comment by tristan-orourke** [comment]
Replaced by combined issue #6747

**Comment by tristan-orourke** [comment]
I screwed up, and I'm un-combining this from #6747

**Comment by tristan-orourke** [comment]
Status | Badge
-- | --
DRAFT | Continue draft (button)
DRAFT_EXPIRED | Submission date passed
NEW_APPLICATION | Application received
APPLICATION_REVIEW | Application under review
SCREENED_IN | Application pending assessment
SCREENED_OUT_APPLICATION | Screened out
UNDER_ASSESSMENT | Application pending assessment
SCREENED_OUT_ASSESSMENT | Screened out
QUALIFIED_AVAILABLE | Qualified
QUALIFIED_UNAVAILABLE | Qualified
QUALIFIED_WITHDREW | Qualified
PLACED_CASUAL | Qualified
PLACED_TERM | Qualified
PLACED_INDETERMINATE | Qualified
EXPIRED | Expired (in red)
REMOVED | Removed (in red) ???

**Comment by brindasasi** [comment]
@tristan-orourke @substrae 
Does the applications with qualified status card appears here as well? 
Figma says so. 
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/c1377d55-adbb-4703-ade2-8d30159e6ffa)

But would that be redundant of what QualifiedRecruitment would also do ? 
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/790bae69-07de-46a5-b040-a41e5cd72e5d)

**Comment by substrae** [comment]
@brindasasi 

It does - it's only redundant because we've conflicted the ideas of "application" and "recruitment". In reality, one is showing your application and it's status, the other is showing a recruitment you're a part of, and your status in that recruitment. Your application's status and your status in a recruitment are two different things.

**Comment by brindasasi** [comment]
@gobyrne reported this as a bug few days ago 🤔
https://talent-cloud.slack.com/archives/CB424V61J/p1686592096754639

**Comment by substrae** [comment]
@brindasasi 

That bug is slightly different - nothing should show up in your recruitment list unless you've been assessed and admitted into a pool. Gray's bug was that he applied and suddenly had both an application and a qualified recruitment, when in reality he should have only had an application because he hadn't been assessed and admitted yet.
