### ISSUE TITLE
✨Response time change for requests confirmation page

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#6742]
## ✨ Feature

We've been asked to change the advertised time to respond to requests. This appears on the request summary page after you submit a request.

## 🕵️ Details

Current text:
EN: You will receive a follow up on your request within the next 2 to 4 business days.
FR: Vous recevrez un suivi sur votre demande dans 2 à 4 jours ouvrables.

New:
EN: You will receive a follow up on your request within the next 5 to 10 business days.
FR: Vous recevrez un suivi sur votre demande dans 5 à 10 jours ouvrables.

## 📸 Screenshot

![image.png](https://images.zenhubusercontent.com/5dc084854553760001149b53/3d412848-da4b-4de6-bca9-8cc72bbda254)Add a screenshot of the new feature (if possible).

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Update the number of days to expect for follow up.
- [ ] Quick check/search to see if this statement appears elsewhere

**Comment by mnigh** [comment]
@Jerryescandon can you update the Figma file accordingly? This statement, related to response time for search requests, only appears on the request confirmation page.
