### ISSUE TITLE
✨ Update the ApplicationCard component

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#6747]
## ✨ Feature

Update the ApplicationCard component used on the Applicant Dashboard.

## 🕵️ Details

@substrae's new designs have the ApplicationCard looking a bit different depending on whether your application has been accepted or not, and were initially described in two different issues: 

- [ ] #6738
- [x] #6737

Due to our implementation of the ApplicationCard, I think they would more easily be tackled in a single PR.

# Pre-acceptance Details

## 🌟 Details ([Figma file](https://www.figma.com/file/2VF8cE4cctTBQUkPBcVxUG/3.-Patterns?type=design&node-id=703-60937))

The application summary card is being updated with a few changes:
- Data types that have their own card on profiles are being given a theme color, in this case, applications are using `primary`
- Language around the recruitment type is being added
- The layout and language around card sub-actions has been updated, including the addition of `aria-label` text

### Accessibility

- Because application summary cards are repeated in a list, it's important that interactive elements inside the card contain descriptive `aria-label` values to ensure that link-navigation via AT reads things out properly
  - "Continue draft" >> "Continue your application draft to the IT-01 Application developer (React) job"
  - "Review application" >> "Review your application to the IT-01 Application developer (React) job"
  - "Review job ad" >> "Review the IT-01 Application developer (React) job advertisement"
  - "Visit résumé" >> "Visit the IT-01 Application developer (React) recruitment on your résumé"
  - "Manage availability" >> "Manage your availability for the IT-01 Application developer (React) recruitment"
  - "Get support" >> "Get support for the IT-01 Application developer (React) job"
  - "Delete application" >> "Delete your application to the IT-01 Application developer (React) job"
  - "Copy application ID" >> "Copy your IT-01 Application developer (React) application's ID"

### Typography

- Card headers should use the `h6` font-size value but use the proper markup for their contextual placement on the page
- Recruitment type and deadline content should use the `copy` font-size value
- Card footer content should use the `caption` font-size value

### Size

Note that the top and bottom right corners use the `rounded` border-radius, and the card uses the `larger` box-shadow value.

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/f659ab81-b2c0-4fb7-a4ab-e88956f3185e)

### Card groups

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/1c239485-c290-4978-80af-a0ee61b61f0a)

### Targeted recruitment vs. Ongoing recruitment

The only distinction between the two is that their type is indicated on the card below the title.

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/7ddd8150-f2cd-4dd2-ba92-ae4a2454696d)

### Draft states

**All draft states include**
- The title is clickable and takes the user to continue their application
- The card contains a "Continue draft" button
- The card sub-actions allow the user to 
  - Check the job ad
  - Email the relevant pool owner/team for help
  - Delete the application (which prompts a confirmation dialog, described below)
  - Copy the application ID 

**Urgent draft state**
- Urgent drafts differ only in that the "Apply by" date is highlighted using `error.darker` for emphasis
- This should trigger when there is less than 3 days left to apply

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/d4669cb5-9703-4561-90dd-22b11a0d870d)

#### Deletion confirmation dialog

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/fd0baa7c-c311-474c-ae86-7d5a5deb621d)

### Pending states

**All pending states include***
- The card title is no longer clickable
- The "Continue draft" button is replaced by a `primary` status chip
- "Apply by" has changed to "Applied on"
- The card sub-actions allow the user to
  - Check their application (read only)
  - Check the job ad
  - Email the relevant pool owner/team for help
  - Copy the application ID

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/18f31595-0e19-4cc1-8e54-62bfd4d57ec2)

### Decision states

**All decision states include**
- The card title is still non-interactive
- The status chips are now unique (see below)
- The card sub-actions are unique, barring the ability to check their application, view the job ad, get support, and copying the application ID (see below)

**The qualified state**
- "Apply by" changes to "Applied on"
- The qualified status chip uses the `success` variant and contains the `shield-check` Heroicon from the `mini` set
- The card sub-actions include
  - Viewing the qualified recruitment on their résumé page
  - Managing their availability (same link as above)

**The screened out state**
- "Apply by" changes to "Applied on"
- The screened out status chip uses the `secondary` variant
- The card sub-actions include
  - Deleting the application (prompts the same dialog explained above)

**The missed submission date state**
- "Apply by" stays as is
- The missed date status chip uses the `error` variant
- The "Apply by" date is highlighted using `error.darker`
- The card sub-actions include
  - Deleting the application (prompts the same dialog explained above)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/1837af48-ed25-4373-b9a0-9a98180b273e)

# Post-acceptance Details

## 🌟 Details ([Figma file](https://www.figma.com/file/2VF8cE4cctTBQUkPBcVxUG/3.-Patterns?type=design&node-id=703-60935))

The recruitment process card is being updated with a few changes:
- Data types that have their own card on profiles are being given a theme color, in this case, recruitments are using `secondary`
- The card has been converted from a single expansion element to a card containing a generic expansion
- The layout and language around card sub-actions has been updated, including the addition of `aria-label` text

### Accessibility

- Because experience cards are repeated in a list, it's important that interactive elements inside the card contain descriptive `aria-label`  values to ensure that link-navigation via AT reads things out properly
  - "Show this recruitment's skill assessments" >> "Show assessed skills for the IT-02 Web technician (Java) recruitment process"
  - "Hide this recruitment's skill assessments" >> "Hide assessed skills for the IT-02 Web technician (Java) recruitment process"
  - "Change your availability" >> "Change your availability for the IT-02 Web technician (Java) recruitment process"
  - "Copy recruitment ID" >> "Copy the IT-02 Web technician (Java) recruitment process' ID"

### Typography

- The card title should use the `h6` font-size while being whatever HTML heading is relevant for the page context
- The recruitment type should use the `secondary.darker` color
- The separator bullet should use `black`
- The "Awarded on" label and date should use `black.light`
- The details expansion should use the `copy` size variant`
- Label and value pairs inside the expansion all use the `copy` font size, with labels bolded 
  - The "Behavioural skills" section, if applicable, uses the `globe-americas` Heroicon from the `mini` set with the `secondary` color
  - The "Technical skills" section, if applicable, uses the `bolt` Heroicon from the `mini` set with the `secondary` color
- The availability message and copy ID link use the `caption` font-size; links are bolded 

### Size

Note that the top and bottom right corners use the `rounded` border-radius value and the card itself uses the `larger` box-shadow value.

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/caf9b008-8346-4479-b6d4-a85a0f15a540)

### Card groups

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/e203a2bc-6cb9-45d5-af53-3b554a153f03)

### Targeted recruitment vs. Ongoing recruitment

The only distinction between the two is that their type is indicated on the card below the title. For both, the expansion contains the assessed skills that were linked to the job advertisement.

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/6ad6b221-f11a-4938-983b-93ddad7fa28c)

### Qualified states

- All qualified states use the `success` variant of the chip component and contain the `shield-check` Heroicon from the `mini` set

####  Open availability

- The "open availability" message uses the `check-circle` Heroicon from the `mini` set with the `success` color

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/6e2c52d9-2cfe-41cd-b7ad-e9b2df90c06a)

##### Change availability dialog

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/31678a08-3321-435b-b3da-edc13592719b)

#### Closed availability

- The "unavailable" message uses the `no-symbol` Heroicon from the `mini` set with the `error` color

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/7fd71653-6b47-4644-8911-65f5859faf0f)

#### Hired

- The "you've been hired" message uses the `star` Heroicon from the `mini` set with the `quaternary.dark` color

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/3dd2d94d-b9e9-4f3c-8de9-86107684de3c)

### The expired state

- Uses the `error` variant of the chip component
- The "expired recruitment" message that replaces the availability control uses the `lock-closed` Heroicon from the `mini` set with the `gray.darker` color

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/29eafab9-e6b9-43cd-bf8a-10e32f39975d)

## 🎨 Design File

[Pre-acceptance figma design](https://www.figma.com/file/2VF8cE4cctTBQUkPBcVxUG/3.-Patterns?type=design&node-id=703-60937&t=nLANsnPG4uJgcGPS-0)

[Post-acceptance figma design](https://www.figma.com/file/2VF8cE4cctTBQUkPBcVxUG/3.-Patterns?type=design&node-id=703-60935&t=DYhv0PVwTfhtxL9F-0)

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/bad928c7-f954-426d-9be0-95f03344ef39)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/02876d74-3769-4cff-bbc3-886ce12417c8)

# Pre- and Post- acceptance

## 🙋‍♀️ Proposed Implementation

Work with the existing ApplicationCard, which already checks for the state of the application.

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

These criteria apply to the card when the applicationIsDraft is true, or when isApplicantPlaced is false.
- [ ] The card has the described layout, colors, and typography
- [ ] The "urgent draft" state is triggered when the submission time is less than 3 days away
- [ ] The card displays whether the pool was a targeted or ongoing recruitment
- [ ] Drafts, and only drafts, can be deleted using the designed modal
- [ ] The interactable elements have aria-labels
- [ ] The described changes are applied when the application is submitted, moved under review, screened out, or expires as a draft

These criteria apply to the card when isApplicantPlaced is true.
- [ ] The card has the described layout, colors, and typography
- [ ] The card displays whether the pool was a targeted or ongoing recruitment
- [ ] A simple accordion has been added to the card, which shows which required skills were part of the Pool
- [ ] A user can suspend their application, as long as the pool hasn't expired or they haven't been placed
- [ ] All interactive elements have aria-labels
- [ ] Hide the date for now - we do not currently record the "accepted-at" date
- [ ] For now, Accordion trigger text does not need to change based on open/close state, just use the "Show" version.

**Comment by brindasasi** [comment]
Regarding the copy "As you were hired" - Being hired is  different from Being qualified. Are sure about this? 
IMO, "hired" should be used when actually all the paperworks are done and the person got the job. This status just means the person has been qualified for a job.

**Comment by tristan-orourke** [comment]
@brindasasi I'm pretty sure the "As you were hired" text appears when the application has a PLACED status, which does mean you were hired.

**Comment by brindasasi** [comment]
That makes sense to me. Thank you ! 🙂

**Comment by tristan-orourke** [comment]
I misunderstood https://github.com/GCTC-NTGC/gc-digital-talent/issues/6738 and https://github.com/GCTC-NTGC/gc-digital-talent/issues/6737 and messed up by combining them. I'm gonna break them up into separate tickets again. Sorry about this!
