### ISSUE TITLE
🐛 Error alert appears "You have already applied to pool" when the user has not applied yet 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#6751]
## 🐛 Bug

When the user tries to apply the position he already created draft an error alert appears. 
Its not preventing him to continue the draft application. 
However that error popup looks buggy 
(Another annoying side effect , It also fills up Application Insight error log ) 

## 🦋 Expected Behaviour

User should be able to continue the draft application without any error 

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Name and version (if possible).
- **Browser**: Name and version (if possible).

## 📋 Steps to Reproduce

1. Go to https://talent.canada.ca/en/browse/pools
2. Click on any job and create draft application
3. Log out 
4. Now repeat the step 1
5. Click Apply button for the same job you created draft 
6. You will be directed to login page .. enter your credentials
7. You will be redirected back to the job page 
8. Observe the error alert appears 

## 📸 Video

https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/5b66f20d-9baf-429d-b5f5-40d63e6586a4

## 🙋‍♀️ Proposed Solution

Two options:
1. In CreateApplicationPage, check if the user already has an application _before_ running the createApplication mutation. Navigate to the existing mutation if it exists.
2. In CreateApplicationPage, ensure the APPLICATION_EXISTS error is ignored if that is the only error returned. (The CreateApplication mutation on the backend is set up to return the error, but also return the existing application id, so navigating to the application already works.) This has the advantage of only ever requiring a single api call, but you'd have to figure out how to override the core error handler in ClientProvider for this one case, and I don't know if that's possible.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] There shouldn't be any error when clicking the job that the user has not applied yet.

**Comment by tristan-orourke** [comment]
Related to #5352 (but maybe slightly different?)
