### ISSUE TITLE
✨ Change gravatar for github.com organization GCTC-NTGC

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#6752]
## ✨ Feature

Main icon is currently just a run-of-the-mill stock image of lightning in a bottle, we are no longer talent cloud, so it makes less sense. Also having no GC identifier makes this project look less legitimate. 

I propose we update the icon for this (and consequently all sub repositories) with a better image that represents this as a product of the Government of Canada.

This might be up to Gray, im not sure who owns this.

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/92da5b22-3b80-4d7a-a06f-d0d74beab11b)

## 🙋‍♀️ Proposed Implementation

![Robot](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/4b9d2b72-8684-40ad-8c3d-e93c952d8123)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] gravatar for github.com organization GCTC-NTGC changed

**Comment by mnigh** [comment]
> This might be up to Gray, im not sure who owns this.

Only organization admins can change this, which includes @gobyrne.

**Comment by mnigh** [comment]
@Jerryescandon since it should be a square and hopefully not include copy as it could be a variety of sizes, what about the favicon (a scalable version png though) we use on the site that @BrookeCameron created?

**Comment by Jerryescandon** [comment]
@BrookeCameron and I put something together to avoid any copy, it's unofficial, but I think it's better than the cloud in a jar. I updated the issue. I'm passing this on to @gobyrne now.

**Comment by gobyrne** [comment]
Updated :D
