### ISSUE TITLE
♻️ Make optional skills justifications visible on Admin Snapshot view

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#6769]
## ♻️ Debt/Refactor

Add optional skills justifications, if filled out, to snapshot view. 

## 🕵️ Details

Optional skills are listed in some posters and answers should be displayed somewhere if filled out by an applicant. 

(Jerbo here) I added a couple more small fixes to the snapshot in here

1 - Rename the section to simply "Application"
2 - Rename the skills sections on admin side to "HR" language and call them "Essential skills" and "Asset skills" respectively
3 - Add "Asset skills" section

[Link to figma](https://www.figma.com/file/BXYVsu1fo9LS2IySJDUINY/Applicants---Job-application?type=design&node-id=636%3A54957&t=eN9WQXne2pTQYuY1-1)

<details><summary>Screenshot</summary>
<p>

![Frame 40](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/6ad96353-7f7b-4c07-ada1-920462937655)

</p>
</details> 

## ✅ Acceptance Criteria

- [ ] Optional skills section added to where requested

**Comment by vd1992** [comment]
@esizer 
@Jerryescandon

**Comment by tristan-orourke** [comment]
@Jerryescandon can we get a link to an updated figma design?

**Comment by Jerryescandon** [comment]
Updated issue
