### ISSUE TITLE
✨ Update User Profile page

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#6772]
## ✨ Feature

Update User Profile page to match new figma designs. The biggest changes are:
- use the inline forms from the Application v2
- new Account and Privacy section
- rework DEI section

## Details

<details><summary>📸 Empty (Expanded)</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/a86dbca6-b52d-451c-ab09-87c97aa367ff" />
</details>

<details><summary>📸 Empty (Collapsed)</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/b0bd78f9-983a-4591-8592-984a4eaa506b" />
</details>

<details><summary>📸 Mid-edit (Expanded)</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/947d3a8a-e3aa-47d7-9956-c74cfff4a559" />
</details>

<details><summary>📸 Mid-edit (Collapsed)</summary> 
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/881a9fed-4bf2-401b-bba4-7484c1284293" />
</details>

<details><summary>📸 Completed (Expanded)</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/6a2b0be9-a4ea-4283-a087-4e3c0b50b3b8" />
</details>

<details><summary>📸 Completed (Collapsed)</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/54a97152-844b-4915-92c8-2739cee0590a" />
</details>

##### Affirmation edge case

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/c6aac9de-a8e0-4768-81e9-2697a2c67798)

##### DEI dialogs

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/f4409a5c-fe18-47e1-83a3-cd7ba47444e2)

## 🎨 Design File

[Figma file](https://www.figma.com/file/UeTUDknj3s9ZgLCFF8eTcU/Applicants---Profile-V8?type=design&node-id=1-6308&t=BaxsgWiLRD7ouY9m-4)

## 📸 Screenshot

Add a screenshot of the new feature (if possible).

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Update title and subtitle
- [ ] Update breadcrumbs, contingent on APPLICANT DASHBOARD feature flag being true
- [ ] Copy the inline form functionality from the application ([Figma file](https://www.figma.com/file/2VF8cE4cctTBQUkPBcVxUG/3.-Patterns?type=design&node-id=412-36669)). This page and the application should use the same components, and even the same layout (?)
- [ ] Work Location is moved to preferences section
- [ ] Roles and Salaries section is gone
- [ ] DEI Updates - these should be reflected on the Application as well, as it should use the same components.
  - [ ] Rework the DEI section content and collapse relevant information into an expansion
  - [ ] accordions should be collapsed by default
  - [ ] Rework available DEI cards to show the definition by default
  - [ ] Rework the DEI claim cards to show the new layout and affirmation
  - [ ] Update the DEI dialogs to reflect new additions (see Indigenous identity, visible minorities)
  - [ ] The DEI section does not have an initial null state, because it is entirely optional
  - [ ] For now, we can continue to display the selected indigenous communities in a list as we have been
- [ ] Update "read" view to be more consistently displayed in a grid
- [ ] Add the "Account and privacy" section
  - [ ] Add login and authentication expansion
  - [ ] Add functionality for managing recruitment inside the "Manage recruitment availability" expansion. This should show ApplicationCards for Qualified Available applications.
  - [ ] DO NOT worry about account deletion for now
  - [ ] These accordions should default to closed and use the "Show..." trigger text
  - [ ] added to the "table of contents"

**Comment by tristan-orourke** [comment]
@substrae when you can, can you confirm the default state for the Account and privacy accordions? Should they start open or closed?

**Comment by substrae** [comment]
@tristan-orourke closed

**Comment by petertgiles** [comment]
Please uncomment the link to Account and Privacy on DashboardHeading.tsx and point it to the section on this page.

**Comment by tristan-orourke** [comment]
Only applications with the following states should be considered Qualified Recruitments, which appear in the "recruitment availability" section.

Status | Badge
--- | ---
QUALIFIED_AVAILABLE | Qualified
QUALIFIED_UNAVAILABLE | Qualified
QUALIFIED_WITHDREW | Qualified
PLACED_CASUAL | Qualified
PLACED_TERM | Qualified
PLACED_INDETERMINATE | Qualified
EXPIRED | Expired (in red)
