### ISSUE TITLE
✨ Update nav bar

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#6774]
## ✨ Feature

Amalgamate profile/dashboard nav links

## 🕵️ Details

If APPLICANT_DASHBOARD feature flag is True, then update the nav bar.
  - [ ] Remove My Applications
  - [ ] Remove My Profile
  - [ ] Replace "My Dashboard" with "Profile and applications"

## 🎨 Design File

https://www.figma.com/file/jHsXzqMfBtomLa1Gom94Y7/Applicants---Dashboard?type=design&node-id=866-29940&t=Qd1SkE7sq7QsNQ2j-0

## 📸 Screenshot

Add a screenshot of the new feature (if possible).

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

If APPLICANT_DASHBOARD feature flag is True, then update the nav bar:
  - [ ] Remove My Applications
  - [ ] Remove My Profile
  - [ ] Replace "My Dashboard" with "Profile and applications"

**Comment by esizer** [comment]
Should admin still show up on the left or does it make sense to move it over to the right with the other links related to the current user?

**Comment by tristan-orourke** [comment]
Oh, good question. I'd lean towards keeping it on the left to not clutter the right side, but I don't feel strongly. @substrae ?

**Comment by substrae** [comment]
@tristan-orourke 

To be honest, I don't think admin should be in the nav at all. If anything, we could add it to the footer, or simply give out the link.

**Comment by tristan-orourke** [comment]
@substrae yeah it only shows up if you have admin privileges. It's a very nice convenience.
