### ISSUE TITLE
♻️ Bump @radix-ui/react-accordion from 1.1.1 to 1.1.2

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#6792]
## ♻️ Debt/Refactor

Manual bump of `@radix-ui/react-accordion` to `1.1.2`.

## 🕵️ Details

It appears as though there were some changes that broke our current implementation. This may be due to us rendering empty `Accordion.Root`. The error message is not very helpful however, it seems as though it is coming from the context provider creation.

https://github.com/radix-ui/primitives/blob/333eaf790a294c3af6092f2dcf870f27092d2a57/packages/react/context/src/createContext.tsx#L72

## 🙋‍♀️ Proposed Solution

Review each accordion implementation to make sure items exist before rendering. This is the possible solution:

```tsx
const items = []; // Empty array!

# Current (?)
<Accordion.Root>
   {items.map(item => <Accoridon.Item />)}
</Accordion.Root>

# Change To
{items.length ? (
  <Accordion.Root>
     {items.map(item => <Accoridon.Item />)}
  </Accordion.Root>
) : null}
```
## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] `@radix-ui/react-accordion` on `1.1.2`
- [ ] App builds and functions with no console errors (run in dev mode)g

**Comment by petertgiles** [comment]
TODO: check if this is still a problem

**Comment by mnigh** [comment]
We are getting a dependabot error for `@radix-ui/react-collapsible` because `@radix-ui/react-accordion` is pinned to a version, so let's do this!

## Screenshot
![Screen Shot 2023-07-20 at 10 21 16](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/cd3eead6-39a5-4973-aa46-1f9151118e5e)
