### ISSUE TITLE
✨ Indigenous Community status as a sentence, not list

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#6799]
## ✨ Feature

The `DiversityEquityInclusion` section of the profile should display Indigenous Community status as a sentence, not a list.

## 🕵️ Details

Instead of reading: "I affirm that X, X, or X", it should be "I affirm that X, and X, and X, and X". Then, not a list on its own line.

## 📸 Screenshot

![Screen Shot 2023-11-20 at 12 26 17](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/0e8dba61-cdb7-4044-8532-6ddf4dcfbc1f)

## 🙋‍♀️ Proposed Implementation

> [!NOTE]  
> Sentence should not be wrapped in quotes.

### Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/c6aac9de-a8e0-4768-81e9-2697a2c67798)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] `DiversityEquityInclusion` section of the profile displays Indigenous Community status as a sentence

**Comment by mnigh** [comment]
@tristan-orourke can you add more detail to this issue if it is still relevant?

**Comment by tristan-orourke** [comment]
This seems low priority to me. But, @substrae or @BrookeCameron, if you still want us to do this, can you provide more information/examples for how to build the sentence?

**Comment by substrae** [comment]
@tristan-orourke @BrookeCameron 

I'll leave it to Brooke to make a call here in terms of need and priority.

**Comment by BrookeCameron** [comment]
@tristan-orourke Hmmmm ... @MCommonda and I aren't sure where this change is coming from. In the Figma files this is what I have (see screenshot below). 
<img width="942" alt="Screenshot 2023-09-12 at 10 41 46 AM" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/62fff4ea-8c24-4378-b5d1-ff593216e192">

**Comment by mnigh** [comment]
> Hmmmm ... @MCommonda and I aren't sure where this change is coming from. In the Figma files this is what I have (see screenshot below). <img alt="Screenshot 2023-09-12 at 10 41 46 AM" width="942" src="https://user-images.githubusercontent.com/100953238/267367574-62fff4ea-8c24-4378-b5d1-ff593216e192.png">

@BrookeCameron i've updated the description of this issue (with the help and memory of @esizer, 🙇 ) to better reflect what the intended change was to be. as for the purpose of this change, it seems like it had to do with trying to avoid "ordering" the communities. if this is issue is longer relevant and there is no design in the works, then please close this issue as not planned.

**Comment by petertgiles** [comment]
Closing as there is no clear direction.  Feel free to reopen if needed.
