### ISSUE TITLE
♻️ User profile My status section no longer used

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#6804]
## ♻️ Debt/Refactor

The **My status** section and form are no longer used in the user profile.

## 🕵️ Details

Add any additional details that could assist with the development of the new feature.

## 🙋‍♀️ Proposed Solution

Remove **My status** section and form from the codebase

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] my status section and form no longer appear in the codebase

**Comment by mnigh** [comment]
@GCTC-NTGC/designers any objection to this issue?

**Comment by Jerryescandon** [comment]
Objection?!?! if anything I would make it an interruption!

**Comment by RM-1978** [comment]
Agree 100% @Jerryescandon
