### ISSUE TITLE
✨ Notes on Requests and Pool Candidates Table

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#6818]
## ✨ Feature

Add a searchable Notes column to the Pool Candidates and Requests tables.

## 🕵️ Details

This is the PoolCandidates table that appears on the SingleSearchRequest page and Pools page.

Add a column for the `notes` field on the Pool Candidates. It should be hidden by default. QUESTION: do we wrap the text or cut it off with ellipses? ANSWER: cut off after a certain number of characters.

Add an input field to the filter dialog which searches on the notes column, filtering out candidates whose notes don't contain the input text. This filtering should be case insensitive.

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/7f8db0d8-8cf9-4fd8-bbb3-c9dc6e4bc3d1)

## ✅ Acceptance Criteria

- [ ] Notes column is added to PoolCandidates table, but is hidden by default. Notes cuts off with ellipses after a reasonable number of characters.
- [ ] Whether hidden or not, you can search by note text. This search is case insensitive.
- [ ] Any changes to the api, like a new scope, are tested in phpunit tests.
- [ ] Notes column is added to Requests table - behaves the same way as PoolCandidates table
- [ ] Add to the search bar column selector as well

**Comment by tristan-orourke** [comment]
@Jerryescandon this came up in discussion with the Recruitment team, we think this would be useful for them. Anything to add before I bring it to dev team for estimation?

**Comment by Jerryescandon** [comment]
Can the search work if we put the text behind elipses?

**Comment by Jerryescandon** [comment]
Like this?

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/df61a08f-604c-4eb1-a820-65665e908b54)

**Comment by tristan-orourke** [comment]
Yeah, basically. Would the `read more` expand the text in place? (vs linking to a different page)

**Comment by tristan-orourke** [comment]
Jerbo note's that ideally, the `read more` button expands the text into a thick row which has the entire note text. If that's difficult, we can simply cut off with ellipses and ignore `read more` for now.

**Comment by tristan-orourke** [comment]
What are the accessibility concerns for something like this? I suppose for a screen reader, it would be fine to read the entire text by default.

**Comment by esizer** [comment]
So, we had a meeting with Fable today about tables and there seemed to be a vehement distain for interactive elements  in tables (I assume this does not also include links). I'm not sure if this counts or not though, something to keep in mind.

**Comment by tristan-orourke** [comment]
@esizer Does that include checkboxes?

**Comment by esizer** [comment]
> @esizer Does that include checkboxes?

No, we asked about checkboxes and those were fine since selecting rows is useful. From my interpretation, it was items that are used to show/hide any sort of content. i.e, this component and dropdowns.
