### ISSUE TITLE
🐛 User and PoolCandidates table don't search full name by default

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#6826]
## 🐛 Bug

On the User and PoolCandidate tables, you can search by full name if you select "name" in the search bar dropdown. However, if you search by All Columns, a full name will return 0 results, because it tries to find the full text in the firstname column and lastname column individually.

This is very confusing to users, who tend to think our search is just broken.

## 🦋 Expected Behaviour

Whatever we do on the backend to make fullname search when you select Name in the dropdown should also work if you have the default All Columns selected.

## 📋 Steps to Reproduce

1. ...
2. ...

## 📸 Screenshot

Successfully searching by full name
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/ec0985bd-123c-4e9e-89e4-ac3a7014a095)

Full name has no results on default search
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/378da884-b2a3-4e47-89cb-5dabc8858ba9)

First or last name still works
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/df44a137-d8bf-455c-a7be-a33b37a5831d)

## 🙋‍♀️ Proposed Solution

In User::scopeGeneralSearch, use the same technique as in scopeName to capture full-name matches.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] On the users table, searching by full name will return users whether Name or All Columns is selected in the search bar
- [ ] On the PoolCandidates table, searching by full name will return users whether Name or All Columns is selected in the search bar

**Comment by vd1992** [comment]
Can I suggest going down this path? Having general search as being a scope that is a composite of various scopes. 
I think that would be good for representing how general searching works as well as prevents possible mistakes by having one filtering mechanism controlled in one place and then called as needed. 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/01edc186-a0e4-4205-b19c-7f9fc4bb5049)

**Comment by tristan-orourke** [comment]
@vd1992 if that works that's a great idea!

**Comment by vd1992** [comment]
> @vd1992 if that works that's a great idea!

Seems to work as desired

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/b90100f0-e784-4c9a-98fe-cf744942523d)
