### ISSUE TITLE
🐛 Copy mismatch on Location Exemptions 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#6829]
## 🐛 Bug

Work preferences say "Location specifics" in the Profile page and upon editing the section says "Location exemptions" 
(BTS: During UAT, it confused the user and she said she couldn't find location specifics anywhere in the form. )

## 🦋 Expected Behaviour

Edit and Review sections should refer to same copy whatever has been decided to show 

**Location specifics** OR **Location exemptions**

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Name and version (if possible).
- **Browser**: Name and version (if possible).

## 📋 Steps to Reproduce

1. Go to new Application Process "Review your profile" step 
2. Observe the copy for Work Preferences section **Location Specifics** and click **Edit work preferences**
3. Observe you find **Location Exemptions** in the edit form instead of **Location Specifics**

## 📸 Screenshot

<img width="1027" alt="Screenshot 2023-06-07 at 10 38 47 AM" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/ec0b593c-2d95-4944-8fe6-b3d82ec545af">
<img width="959" alt="Screenshot 2023-06-07 at 10 38 57 AM" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/e7d5bbb2-c565-4afc-8ee3-f6c920200413">

## ✅ Acceptance Criteria

- Edit and Review sections should refer to same copy  - please use **Work location exceptions** for the label.

**Comment by mnigh** [comment]
Please use **Work location exceptions** for the label.
