### ISSUE TITLE
"remove me" vs "actively looking" update for new dashboard

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#6831]
## DESCRIPTION

In the new dashboard, users can use the "remove me" to stop receiving requests from pools they have qualified in. This means a global status for "Actively looking" no longer works, and each pool must have their own individual "availability status"
<details><summary>Remove me on new dashboard</summary>
<p>
<img src=https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/cae68ee2-6998-4ab3-b81b-346bcfd053f7/>
</p>
</details> 

**Anywhere where the global status would show up (or get used to filter), it should be replaced by the individual availability status (per pool).**

### Users page
Remove the Personal status column.

### User Information page
Remove the personal status section. Add a column to the Pool status table to indicate the availability status per pool.
<details><summary>Old user information page</summary>
<img src=https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/2d703b7d-0094-4adc-9465-4b01691113e4/>
</details> 
<details><summary>New user information page</summary>
<img src=https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/54dd65c5-ed76-439a-a49f-189443482ebe/>
</details> 

### Individual Request page
~This new individual "availability status" should determine whether a user wants to be referred to a request based on the matching pools to that request. ~
Already done.

Question for @GCTC-NTGC/designers and @gobyrne : If no specific pools are selected in a request, should user's names show up?
Option A: Users show up in a request result ONLY if a pool they are in has been selected in the filters.
Option B: Users show up in a request result WHEN a pool they are in has been selected in the filters OR if NO pool has been selected in the filters.

### Pool Candidates page
~This status also shows up in the candidates table in a pool. it should be updated to show the individual availability status.~
Already showing pool-based status.

## Acceptance Criteria
- [ ] Remove personal status from User Information page
- [ ] Add suspended status column to Pool Candidate mini-table on the snapshot and Profile pages

**Comment by gobyrne** [comment]
To the question, I was expecting

> Option A: Users show up in a request result ONLY if a pool they are in has been selected in the filters.

**Comment by tristan-orourke** [comment]
If a user is suspended in all pools, whether they show up or not is determined by the Candidate Status filter:


![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/bfc27c41-45f1-4b67-a86c-e7bd0764a9a5)
