### ISSUE TITLE
✨ Update IAP nav bar

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#6886]
## ✨ Feature

Update the nav bar which appears on the IAP Home page

## 🕵️ Details

1. Remove the nav bar from indigenous translations. This will make it easier to update, and it appears above the language menu anyway.
2. Add Login + Register / Logout to the right side of the bar
3. Rename "Home" to "IT Apprenticeship Program for Indigenous Peoples"
4. Add a second link in the nav bar, to GC Digital Talent

## 🎨 Design File

(Figma link updated)

[Figma](https://www.figma.com/file/8piNhFaBjcxssBB8LAGxEY/IAP-User-flows?type=design&node-id=484-64366&t=vAD1HUYHCC9cpFL9-4)

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/5afc62b5-864c-4c00-8cfe-29ceaf358cf3)

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Home link renamed
- [ ] Link to main GC Talent home is added
- [ ] Login and Register appear on this page
- [ ] Login and Register switch to Logout if logged in

**Comment by tristan-orourke** [comment]
@BrookeCameron We talked about this last week - can you confirm I have the details right, and consider text for the new links? Then, could you update the figma design?

**Comment by BrookeCameron** [comment]
@tristan-orourke the link has been updated with copy and approved by myself and @MCommonda
