### ISSUE TITLE
✨ Hide empty optional fields in experience cards

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#6905]
## ✨ Feature

Experience forms contain some optional fields, If these are left empty, we should hide the label from the accordion when saved.

### Empty field on form

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/64369ff4-293f-476f-9849-11daf2ae0770)

### Empty label on accordion

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/f4c549ac-bfc4-40fa-83a5-7381fe20e681)

## ✅ Acceptance Criteria

- [ ] Empty optional fields (and their separators) on experience cards are hidden after saving

**Comment by vd1992** [comment]
@Jerryescandon 

Is this issue still applicable? In one of the user profile issues, it appears the accordion was updated with null state text in mind

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/a7d53aa1-e0d8-48c1-baf9-ef21265f5c2f)

**Comment by Jerryescandon** [comment]
Nope, I think null states are good enough
