### ISSUE TITLE
🐛 We should not allow users to edit the steps from submitted applications

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#6906]
## 🐛 Bug

1. I submitted an application.
2. I went to the dashboard.
3. Clicked on "View this application"
4. In this already submitted application, I was able to go to any step and edit the information from within these steps.

While this didn't actually change the info on the application snapshot. It is misleading that users are able to edit info through this path.

## 🦋 Expected Behaviour

Ideally, remove access to the stepper at all, and replace with a snapshot of their own. Should probably have some design intervention.

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Name and version (if possible).
- **Browser**: Name and version (if possible).

## 📋 Steps to Reproduce

1. ...
2. ...

## 📸 Screenshot

Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Criteria 1
- [ ] Criteria 2

**Comment by mnigh** [comment]
@Jerryescandon is this issue still being worked on?
