### ISSUE TITLE
✨ Candidate profile updates (Part 2)

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#6930]
# ✨ Details

This issue is the second part of a series of updates to candidate profiles, along with a handful of other central UI component enhancements.

#### 🧩 Profile update epics

- #6731 
- #6930

# 🗃️ Requirements

```[tasklist]
## ⚙️ Component updates
- [ ] #6931
- [ ] #6932 
- [ ] #6990
```

```[tasklist]
## ☑️ Form updates
- [ ] #5053 
- [ ] #5645 
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/6352
```

```[tasklist]
## 📃 Page updates
- [ ] #6934
- [ ] #6935
- [ ] #6936
```

**Comment by petertgiles** [comment]
11 of 11 Issues completed
