### ISSUE TITLE
📃 Update the "Profile and applications" page

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#6934]
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/0a736947-123b-41f3-9a76-e3f438bd9865)

<details><summary>📸 Full page screenshot</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/2690f09b-1f02-4126-946f-4d4e48833570" />
</details> 

# ✨ Details ([Figma file](https://www.figma.com/file/jHsXzqMfBtomLa1Gom94Y7/Candidates---Profile-and-applications?type=design&node-id=1097-34868))

As a part of the second round of candidate profile updates, I've made a handful of small changes to the dashboard, while also updating the hero card layout to account for the forthcoming skills functionality.

Tasks for this issue have been broken into their own tickets as requested by @tristan-orourke 

#### 🔄️ Previous iterations
- #6731

# 🗃️ Requirements

```[tasklist]
## 📓 Subtasks
- [ ] #6937
- [ ] #6938
- [ ] #6939
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/6989
```

**Comment by esizer** [comment]
Was this meant as an epic? I see all of the items closed, can we close this one now?

**Comment by substrae** [comment]
@esizer Yeah, I think it was. Close away!
