### ISSUE TITLE
📃 Update the "Create or edit experience" page

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#6935]
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/58ab5592-9186-435e-8941-1818f05079a3)

<details><summary>📸 Full page screenshot (create)</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/91e2706b-d59d-4591-ae1b-282ee988fc19" />
</details>

<details><summary>📸 Full page screenshot (edit)</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/02d9ecb8-cc0a-402e-85ec-2b3bb86f1ee9" />
</details>

# ✨ Details ([Figma file](https://www.figma.com/file/piRkRtWAHheoEX5Jq8d9u7/Candidates---Create-or-edit-experience?type=design&node-id=64-107861))

This ticket aims to update the functionality of adding and editing a résumé experience to match the new application process, alongside a few new enhancements.

**Please note:** Where relevant, features that are described here and that should NOT translate to the application experience have been marked with a ⚠️ emoji.

# 🗃️ General requirements

```[tasklist]
## 🌎 Page-wide updates
- [ ] Ensure all copy is updated to match
- [ ] Ensure font sizes are all updated to match
- [ ] Ensure icons are updated and match sizing and color
``` 

# 🗃️ Page section requirements

```[tasklist]
## 📚 Instructions
- [ ] Ensure all copy is updated to match
- [ ] Ensure icons are updated and match sizing and color
```

<details><summary>📸 Instructions - Create - Collapsed</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/e9fff81a-3057-4a50-98cc-4b188a910dae" />
</details> 

<details><summary>📸 Instructions - Create - Expanded</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/3e8e7c5b-1213-43c2-af27-99be62cbcdc1" />
</details> 

```[tasklist]
## 📚 Experience type selection
- [ ] Ensure all copy is updated to match
``` 

<details><summary>📸 Select an experience - Create - Expanded</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/676b7994-667a-4dfe-bf3d-774f0d8fb722" />
</details> 

```[tasklist]
## 📚 Experience details
- [ ] Ensure all copy is updated to match
- [ ] Prevent the user from seeing a form until a type is selected
- [ ] Update all experience form layouts to match
``` 

<details><summary>📸 Provide a few details - Locked state</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/c921a56e-5991-4161-bbd7-575f52fe62fb" />
</details> 

<details><summary>📸 Provide a few details - Work experience form</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/fc2d4796-4a33-47d1-9328-d047a9400d47" />
</details> 

<details><summary>📸 Provide a few details - Education experience form</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/911351c0-c5da-4b2d-803c-a6e9128ceaaf" />
</details> 

<details><summary>📸 Provide a few details - Community experience form</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/5335d3c6-9b99-4c41-b4e2-9dcd726de1de" />
</details> 

<details><summary>📸 Provide a few details - Personal experience form</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/01dcb599-a7a7-4e82-b5eb-213ea514602d" />
</details> 

<details><summary>📸 Provide a few details - Award experience form</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/6573de9f-53f6-4532-9dc2-fb7938dbfbea" />
</details> 

```[tasklist]
## 📚 Additional info
- [ ] Ensure all copy is updated to match
- [ ] Prevent the user from seeing a form until a type is selected
``` 

<details><summary>📸 Additional details - Locked</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/81272f2a-0dd9-4a23-80a3-e1de98e9e588" />
</details> 

<details><summary>📸 Additional details - Unlocked</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/5df71ba9-65da-4f99-8ad6-215c61ae9bf1" />
</details> 

```[tasklist]
## 📚 Link featured skills ⚠️
- [ ] Prevent the user from seeing a form until a type is selected
- [ ] Allow for skills linked via an application to be edited here
- [ ] Build a null state for when users have no skills linked yet
- [ ] Allow users to add new skills to the experience by implementing the skill browser dialog
- [ ] Allow users to delete skills from the experience
``` 

**Please note:**
- Featured skills use the same linking functionality designed for the application when applying a skill justification

<details><summary>📸 Featured skills - Locked - Collapsed</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/eeb7fe90-a30d-4877-b298-98a295210582" />
</details> 

<details><summary>📸 Featured skills - Locked - Expanded</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/664400fb-d769-4909-9d93-b049fad91e81" />
</details> 

<details><summary>📸 Featured skills - Unlocked - No skills</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/55e5454b-fae9-4c55-8f4f-6dab77d6c5b4" />
</details> 

<details><summary>📸 Featured skills - Unlocked - With skills</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/d18817b3-42c6-491e-ac07-ede85031bd33" /> 
</details> 

### The skill browser dialog

When clicking "Add a new item", the skill browser dialog should be triggered and should include:
- Skill category filter
- Skill family filter
- Skill combobox
- Skill definition
- Expansion describing what to do if the user can't find a skill

See issue #5053 for more details.

<details><summary>📸 Skill browser dialog</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/c8b41362-6bdd-4ff1-b5ab-6e2df0cd8787" />
</details>

# 🗃️ State and other requirements

```[tasklist]
## 🔄️ The differences between creating and editing
- [ ] Update the page title, subtitle, and breadcrumbs
- [ ] Update the navigation sidebar
- [ ] Update the main section title and instruction content
- [ ] Remove the ability (and section) to select the type of experience
- [ ] Update the page actions to remove "Save and create another" and add "Delete this experience"
```

Comparison screenshots can be found below for visual and text differences.

<details><summary>📸 Creating vs. editing - Banner</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/3174591f-58b1-421f-8502-2761e0deeffb" /> 
</details> 

<details><summary>📸 Creating vs. editing - Sidebar</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/18308905-51f3-4037-a630-c0e8576daca2" /> 
</details>

<details><summary>📸 Creating vs. editing - Instructions</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/d97ca03c-f791-44e7-868a-761ded049167" /> 
</details> 

<details><summary>📸 Creating vs. editing - Hidden type selection</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/70408cb9-7d55-4a22-aa12-254efb7caa47" /> 
</details> 

<details><summary>📸 Creating vs. editing - Page actions</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/9b1a7455-bab9-4818-8150-9f91c185c2d1" /> 
</details>

**Comment by mnigh** [comment]
Would be good to finish #7320 before this gets implemented.
