### ISSUE TITLE
📃 Create the "Skill library" page

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#6936]
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/d068d2ca-c113-4ff4-8728-2931e3dd2f7f)

<details><summary>📸 Full page (Empty)</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/d348c193-0865-49e0-b235-f3ca82c6c34a" />
</details>

<details><summary>📸 Full page (Complete)</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/ed5cf5ad-1dd3-4613-83e5-07382398b2d4" />
</details>

# ✨ Details ([Figma file](https://www.figma.com/file/FhRhwczL8JI6JC8eVFlWOm/Candidates---Skill-library?type=design&node-id=141-19757&mode=design&t=IWy4rRdaWNUXQXLc-0))

Adds brand new functionality that allows users to link a skill directly to their profile without the need to link experiences. This is the first step in the addition of the skill showcase functionality. Subsequent pages will include a way to view a single skill (clicking its name in the tables), organize skills into showcases, and a way to manage those showcases.

# 🗃️ General requirements

```[tasklist]
## ⚙️ The skill table
- [ ] Ensure the table null state exists
- [ ] Ensure table headings are appropriately named and sort functionality is available if indicated
- [ ] Ensure font sizes and colors match
- [ ] Ensure skill names are clickable in preparation for the eventual skill view
- [ ] Ensure the alternate mobile table matches the design
- [ ] Allow users to add skills using the skill browser dialog
- [ ] Skill table has three columns: skill name, number of associated experiences, and skill level (which may be missing)
- [ ] The skill name in the table is a link to Individual Skill Page (#7378)
``` 

**Please note:** 
- The tables on this page leverage the table component originally described in #6932
- The placeholder example word in the search input changes depending on whether you're looking at the behavioural or technical skill table.

<details><summary>📸 Skill table - No skills</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/f69fac3b-8769-46fa-b354-129607453395" />
</details> 

<details><summary>📸 Skill table - With skills</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/740ae5af-abf6-47bf-ad2d-0bc9a033e1d2" />
</details> 

<details><summary>📸 Skill table - On mobile devices</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/fd3df2c6-9fbc-4b67-a631-8c86701987b8" />
</details>

### The skill browser dialog

When clicking "Add a new skill", the skill browser dialog should be triggered with the skill list limited to the correct category context the button was pressed (i.e. if they add a new skill to behavioural skills, only show behavioural skills in the list).

See issue #7394 for more details.

<details><summary>📸 Skill browser dialog</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/0f67bd56-af0d-4460-b0fd-a1ca4c13e0d6" />
</details>

# 🗃️ Page section requirements

```[tasklist]
## 📚 Behavioural skills
- [ ] Ensure copy matches
- [ ] Ensure iconography is the correct size and color
- [ ] Ensure the skill table search placeholder matches
``` 

<details><summary>📸 Behavioural skills - No skills</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/fcd5d708-1c35-4846-add9-51ecd73b1316" />
</details>

<details><summary>📸 Behavioural skills - With skills</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/095ced72-e9f7-42e2-9ddf-b771058b9650" />
</details>

```[tasklist]
## 📚 Technical skills
- [ ] Ensure copy matches
- [ ] Ensure iconography is the correct size and color
- [ ] Ensure the skill table search placeholder matches
``` 

<details><summary>📸 Technical skills - No skills</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/036a908a-f886-4004-9ae1-d0a4bd6361b5" />
</details>

<details><summary>📸 Technical skills - With skills</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/147894be-ee19-4e88-903c-23e8f68d8a58" />
</details>

# 🗃️ State and other requirements

```[tasklist]
## 🔄️ When skills are missing a claimed level
- [ ] Ensure that skills can be added without a level through the application (and eventually showcase)
- [ ] Ensure the table indicates when a skill is missing
``` 

This state occurs when a candidate adds a skill to their profile through an application or the skill showcase. In those contexts, we don't ask them to specify their skill level as it would confuse the task at hand. When these skills are added without a level, the relevant table column should convert to a "Missing" link that takes the user to the skill view to update their level.

<details><summary>📸 Missing skill level</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/b0f135e2-30b7-495b-a0e5-0052720439cf" />
</details>

## Acceptance Criteria

- [ ] routing for page
- [ ] all of above criteria

**Comment by mnigh** [comment]
Would be good to finish #7320 before this gets implemented.

**Comment by esizer** [comment]
Question, right now we sync the state of the table with URL automatically. This is just a tiny bit odd when using two tables on a single page. It syncs fine, but that sync happens for both tables at once.

Example, 

1. Sort by name on table 1
2. Sort by skill level on table 2
3. Reload page
4. Both tables sorted by skill level 

This is fine when the tables have the same shape of data but could cause some issues if we plan on displaying completely different tables on the same page.

Should we,

- Allow for the table to disable syncing with a URL or,
- Allow us to override the keys we sync with to do each table individually
- Do both?

**Comment by substrae** [comment]
@esizer

You can ignore my opinion here, but I would argue that for this to be done right, we should be allowing for any number of tables to be individually synced.
