### ISSUE TITLE
♻️ Update all references to the "Profile and applications" page

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#6939]
# ✨ Details ([Figma file](https://www.figma.com/file/jHsXzqMfBtomLa1Gom94Y7/Candidates---Profile-and-applications?type=design&node-id=1097-34868))

This ticket aims to ensure that references to the "Dashboard" page in the breadcrumb functionality are migrated to the new name "Profile and applications".

# 🗃️ Requirements

```[tasklist]
- [ ] Ensure crumbs referring to the "Dashboard" now say "Profile and applications"
- [ ] rename components
- [ ] update url and add permanent redirect from old url
- [ ] missing breadcrumb for My profile page
```

**Comment by tristan-orourke** [comment]
Might be covered by #6773

**Comment by petertgiles** [comment]
Will rescope
- rename components
- url with redirect
- missing breadcrumb for My profile page

**Comment by esizer** [comment]
What is the desired path? `/profile-and-applications`?
