### ISSUE TITLE
✨ Add mutations for UserSkills

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#6942]
## ✨ Feature

We want to add mutations to create, edit, or delete UserSkill directly. This will mostly be straightforward, except for the fact that deleting a UserSkill has consequences for ExperienceSkillRecords.

## 🕵️ Details

A user can create a UserSkill with or without extra details (skill level and isCurrent[name pending]). The user must have the Policy ability to `update` the specified user. Validation should cause creation to fail if the User already has a record with the same Skill.

A user can update a UserSkill with a new details. It is not possible to change the user or skill id. The user must have the Policy ability to `update` the specified user.

A user can delete a UserSkill if they have the Policy ability to `update` the specified user.

Deleting a UserSkill also soft-deletes it from all experiences. 

If you add a skill to an experience, and it's already there but soft-deleted, then we restore the previous version, including justification text, and the matching UserSkill if necessary.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] A user can create a UserSkill with or without nullable details. 
- [ ] To create a UserSkill The user must have the Policy ability to `update` the specified user. 
- [ ] Validation should cause creation to fail if the User already has a record with the same Skill (unless the existing skill is soft-deleted, in which case it is restored without error).
- [ ] A user can update a UserSkill with a new claimedLevel. It is not possible to change the user or skill id. 
- [ ] To update a UserSkill, he user must have the Policy ability to `update` the specified user.
- [ ] A user can delete a UserSkillRecord if they have the Policy ability to `update` the specified user.
- [ ] UserSkills are only soft-deleted.
- [ ] Deleting a UserSkill also soft-deletes that skill from all experiences. 
- [ ] Restoring a UserSkill does not automatically restore matching experiences.
- [ ] If you add a skill to an experience, and the ExperienceSkill is already there but soft-deleted, then we restore the previous version, including justification text, and the matching UserSkill if it is currently soft-deleted.
- [ ] PHPUnit tests created for soft deletion and restoring interactions
- [ ] PHPUnit feature tests for all of the mutations

**Comment by petertgiles** [comment]
What are the possible values for `claimedLevel`?

I added an enum for the skill picker in the directive form questionnaire but I don't know if it will be exactly the same.  If it is, that enum can probably get moved to the main schema file and renamed.
https://github.com/GCTC-NTGC/gc-digital-talent/blob/5385fb31b251be4e17428cfe9e96d1a2179c42e7/api/graphql/directiveForms.graphql#L99
