### ISSUE TITLE
🐛 Typo in button `font-size`

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#6943]
## 🐛 Bug

I made a typo and now hydrogen is annoyed 😢 

## 🦋 Expected Behaviour

Hydrogen builds with no errors, no typos, valid css.

## 🙋‍♀️ Proposed Solution

Just fix the typo.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] No typo
- [ ] Valid css is built
- [ ] No hydrogen errors

**Comment by vd1992** [comment]
Yeah I saw that and that made me want to pull in this issue https://github.com/GCTC-NTGC/gc-digital-talent/issues/5641
