### ISSUE TITLE
✨ Include all information in requests table

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#6955]
## ✨ Feature
We want to improve the requests table to include all data related to a request. This is the first step to automate the production of spreadsheet reports in order for DCM to conduct their own analysis on requests information 

## 🕵️ Details

In short, in the requests table we should have a column for every point of data submitted in the request details.

Columns that contain multiple items such as "Skills", "Employment Equity" or "Conditions of employment" should consolidate all items into one cell and comma separate those values.

Related to #6603 

<details><summary>Column labels </summary>
<p>

| Request form | Column title |
|--------|--------|
| Full name | Manager |
| Department / Hiring Organization | Department |
| Government email | Email |
| Job title for this position | Title |
| Additional comments | Details | 
| Status | Status | 
| Date requested | Date received | 
| Date done | Date done | 
| Classification filter  | Group and level | 
| Stream | Stream | 
| Selected skills | Skills | 
| Education level | Education requirement | 
| Working language ability | Language | 
| Employment duration | Duration | 
| Work location | Location | 
| Employment Equity | Employment Equity | 
| Conditions of employment / Operational requirements | Operational requirements | 

</p>
</details> 

## 🎨 Design File

[Include a link to the design file (if it exists).](https://www.figma.com/file/IvhkKCgFgMXmY2AcbsFcGk/Admin---Requests-page?type=design&node-id=3%3A1150&t=K8KvhtKyn7LvrzXf-1)

## 📸 Screenshot

<details><summary>Requests details to consider</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/01ed3ddc-2575-4099-bebd-43b17dc92b3c)

</p>
</details> 

<details><summary>Default columns on requests table</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/87d1a379-eae2-4238-a82f-1a9f8fcdd61c)

</p>
</details> 

<details><summary>Example of new columns on request table</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/ebb66300-c58b-472a-a2cc-1c5cd4ecf13e)

</p>
</details> 

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Criteria 1
- [ ] Criteria 2

**Comment by gobyrne** [comment]
@Jerryescandon I'm closing this as not-planned. It is getting reworked for self-referral.
