### ISSUE TITLE
✨ Download requests table spreadsheet

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#6957]
## ✨ Feature

Include a new button under the requests table that downloads the requests table as a CSV file.

## 🕵️ Details

The download button should only download the "Visible" rows. Meaning, if the filters are active and are being used to show only a subset of the entire database, then the button should download only those being shown and NOT the entire unfiltered table.

While this may not have a big effect right now, it will become increasingly more useful as the Filter grows more powerful.

This feature is dependant on #6955 so that we can include all information related to requests.

There should only be one row per item.

### English or French

Cells should only contain values in one language, and that language should match the currently selected language on the platform. 

<details><summary>Do NOT do this</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/754e3667-1775-4d12-b186-0e23db448dd9)

</p>
</details> 

<details><summary>DO This</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/a2e408da-55c7-408e-b479-e5ab9dceed82)

</p>
</details> 

### Multiple values

Cells with multiple values like "Skills", "Employment Equity" or "Conditions of employment" should concatenate the list in the cell as comma separated e.g:

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/b7e2ad77-6120-4d23-b2d6-0e91e3cca313)

## 🎨 Design File

[Include a link to the design file (if it exists).](https://www.figma.com/file/IvhkKCgFgMXmY2AcbsFcGk/Admin---Requests-page?type=design&node-id=3%3A1150&t=K8KvhtKyn7LvrzXf-1)

## 📸 Screenshot

<details><summary>Requests table new download button</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/0173c2ef-11c6-483f-a0a4-e2540b4ce622)

</p>
</details> 

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Criteria 1
- [ ] Criteria 2

**Comment by gobyrne** [comment]
@Jerryescandon closing this one too, but feel free to re-scope them for post self-referral. I get that these admin pages will still exist in some form.
