### ISSUE TITLE
Resolve npm warnings and high-risk vulnerabilities

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#696]

**Comment by gggrant** [comment]
Dependabot provides security patches, providing that there are no constraints in the lockfiles. We currently have 26 alerts, none of which can be resolved.

Neither `npm update` or `npm audit fix` are able to run because of upstream dependency conflicts.

Unsure how to proceed with this.

**Comment by mnigh** [comment]
@tristan-orourke would [switching from npm to yarn ](https://github.com/GCTC-NTGC/gc-digital-talent/issues/5338) resolve this issue?

**Comment by mnigh** [comment]
As Grant stated previously, we rely on Dependabot for flagging vulnerabilities. We currently have 3 alerts, all of which we are unable to fix due to upstream dependency conflicts.
