### ISSUE TITLE
✏️ Email the GC Notify team about setting up a team account for us

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#6974]
## ✏️ Communication

Talk to GC Notify about getting a team/org account

## 🕵️ Details

Add any additional details that could assist with the implementation of the new documentation.

## 🙋‍♀️ Proposed Copy

(optional) Do you have any copy that you would like to propose?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the documentation has been added/updated appropriately.

- [x] We have the accounts we need to use GCNotify in production

**Comment by mnigh** [comment]
We already have an account with multiple team members already added for Talent Cloud, maybe we just need to change some of the names and sending email addresses?

**Comment by tristan-orourke** [comment]
Yeah, seems like our existing account is all good. I updated the name from Talent Cloud to GC Digital Talent, and I'll find out what email addresses we want to use.
