### ISSUE TITLE
🐛 Pool candidates table filter doesn't work properly 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#6986]
## 🐛 Bug

Pool candidates table filter doesn't work properly. 
Active candidates filter brings up suspended and suspended filter does not bring up all suspended candidates 

## 🦋 Expected Behaviour

Active filter should bring up only active candidates
Suspended filter should bring up all suspended candidates 
All filter should bring up both statuses

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Name and version (if possible).
- **Browser**: Name and version (if possible).

## 📋 Steps to Reproduce

1. Make sure you are active candidate in a pool
2. Suspend your candidacy through Remove Me link in the dashboard 
3. Go to pool candidate table  and make sure to show the candidacy status column 
4.  Filter by "Active" status ( it is default filter anyways )
4. Observe the record you suspended will show up under "Active" filter 
5. Filter by "Suspended" status 
6. Observe the record you suspended will NOT show up under "Suspended" filter 😅

## 📸 Video 

https://images.zenhubusercontent.com/364642496/c54a0f78-fd0f-44f8-a4ca-26fee3e459de/20230615104220311.mp4
## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Active filter should bring up only active candidates
- [ ] Suspended filter should bring up all suspended candidates 
- [ ] All filter should bring up both statuses

**Comment by tristan-orourke** [comment]
It seems to work for some candidates who we suspended via script? But doesn't seem to work if you suspend yourself via applicant dashboard.

**Comment by vd1992** [comment]
Okay, seems to do with the `where()` itself, given a string of the format `YYYY-MM-DD HH:MM:SS`, it sorts comparing until the space so disregarding hours, minutes, and seconds. 

Testing this in PHP unit...
Left is the query/assertion, middle is the candidates seeded, right is the run itself. 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/d5bdd524-0835-4d9c-bf34-2d8db76e9ba5)

**Comment by vd1992** [comment]
If you update `suspended_at` for your pool candidate in Adminer and push it back by a full day, then the filtering seems to work again. 

Trying something like this and then refresh the table. 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/a2907e80-14ee-4974-b859-0da43de49c98)

**Comment by vd1992** [comment]
Scope in question, whereDate() is used for expiry filtering too so this bug is likely present for that too.

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/adcad2ce-c258-4222-bf87-b59ec42ba8e6)

**Comment by vd1992** [comment]
Just using `where()` should work, it is how filtering out drafts is working

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/e19b728a-48e7-4852-a8e8-bd727c006e01)
