### ISSUE TITLE
Finalize functionality on Skill block (links and validation)

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#6989]
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/7159050d-9e02-4dc2-91e3-cde895b21e9e)

# ✨ Details

[Visit the Figma file](https://www.figma.com/file/jHsXzqMfBtomLa1Gom94Y7/Candidates---Profile-and-applications?type=design&node-id=1311-42259&mode=design) • Message @substrae with design questions.

Finalize the Skill block on the _Profile and applications_ page, which currently has no links and validation.

## Link paths

- `Behavioural skill library` links to the #6936 and scrolls the user to the relevant page section title
- `Technical skill library` links to the #6936 and scrolls the user to the relevant page section title
- `Top skills` links to the eventual `Skill showcase` page and scrolls the user to the relevant page section title
- `Skills to improve` links to the eventual `Skill showcase` page and scrolls the user to the relevant page section title

## 🔄️ States

Like the 2 cards that preceded it, this card contains content completion states. The completion states are determined by the following rules:
- The `skill library` items need to have at least 1 skill

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/4fe6baee-fd97-4d63-bf2a-8ab21ecdee01)

## ✅ Acceptance Criteria

```[tasklist]
### Tasks
- [ ] links work correctly
- [ ] completion states match specs
```

**Comment by mnigh** [comment]
@tristan-orourke is this issue a stub with no description on purpose?

**Comment by tristan-orourke** [comment]
Got the details in, thanks for the reminder @mnigh

**Comment by substrae** [comment]
Done!

**Comment by vd1992** [comment]
@substrae 
One more question, what is the validation supposed to be? When it is red and when is it green?

**Comment by substrae** [comment]
@vd1992 

For the skill libraries, invalid if there is 0 skills in either category (i.e. 0 technical skills or 0 behavioural skills).
For the skill showcases, invalid if any showcase is entirely empty in either category; showcases don't have to be full to be valid, they just have to have a minimum of 1 entry in each.

**Comment by vd1992** [comment]
Thank you!

**Comment by vd1992** [comment]
Also blocking on #7388 per acceptance criteria  
"Comments: "// TO DO: Update with proper path" resolved"

Those require the existence of these pages and links to exist first

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/10e30086-6e4f-4581-89db-27a87e589653)

**Comment by esizer** [comment]
@yonikid15 was nice enough to resolve the TO DO's in his PR so I removed it from AC and removed the blocker! 👏
