### ISSUE TITLE
⚙️ Update the table of contents component

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#6990]
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/8b39849a-14ea-4cc2-ab9a-11074ded189a)

# ✨ Details ([Figma file](https://www.figma.com/file/T1R64oNWog10OXiBnuiMkz/2.-Components?type=design&node-id=758-5887))

We've never formally established design standards for the table of contents, so this ticket aims to do so, alongside establishing common variants and use cases.

# 📐 Standards and layout

## Accessibility

We'll want to ensure that the table of contents is using proper landmark elements to identify itself as a navigation. Generally, we should build it using a `nav` element, with nested `ul` and `li` elements.

## Color and typography

- The table of contents label/header should use the `h6` font size, bolded
- Standard text links should use the `copy` font size and be `black`
- Incomplete states should use the `x-circle` Heroicon and both the icon and text should use `error.darker`
- Complete states should use the `check-circle` Heroicon and both the icon and text should use `success.darker`
- If included, buttons should be `secondary` and `solid`

## Layout and size

<details><summary>📸 Hydrogen layout diagram</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/a0b4fe3e-c268-45ff-90cc-8c00f07386ae" />
</details> 

# 🎨 Variants

## With a button

Some pages require a fixed primary action that will follow the user down the page as they complete tasks. In these cases, a `secondary`, `solid` style button with a custom label should be used.

<details><summary>📸 ToC with a button</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/ec7dc903-9f26-4de3-aa88-e58a93a53343" />
</details> 

## Tracking completion

In some cases it is beneficial to show the user their status when completing multiple sections in a long form. The table of contents should be able to adapt to show the user which sections on the page have been successfully completed. The criteria for what constitutes "complete" will be determined on section-by-section basis for each individual page.

<details><summary>📸 ToC with tracking - Incomplete</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/5d555d98-a8ba-42bb-b5d7-e75f090d74ae" />
</details>

<details><summary>📸 ToC with tracking - Complete</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/2931ffd2-d9af-4f67-a6ad-d0d4ebbed1a7" />
</details>

## Acceptance Criteria
- [ ] Table of contents uses a nav, ul and li elements
- [ ] Items can be nested
- [ ] Typograph and Layout matches specs
- [ ] Status icons (optional) match specs
- [ ] Can include a button at bottom which matches specs
- [ ] Table of Contents follows user down the side

**Comment by tristan-orourke** [comment]
@substrae 
- Will bullets ever need to be icons?
- If some items have completion status, and some don't how do we handle that - should they fallback to "Complete", or be black text with bullets?
- We switched the text in the blocks on the Dashboard page to black for completed items, not green. Can we make that consistent here?

**Comment by substrae** [comment]
@tristan-orourke 

- Not to my current knowledge, but it feels like this would be good future proofing to do now
- Sounds like a use case for the first point - we don't want to show error/complete states for items with no state, as it would be confusing
- Yes, absolutely - follow the dashboard design for this
