### ISSUE TITLE
🐛 Date parser incorrectly parsing `Date`

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#7000]
## 🐛 Bug

Currently our date parser is parsing only `DateTime` causing issues with `Date`'s from the API. 

## 🦋 Expected Behaviour

Parser properly handles `Date` objects.

## 🕵️ Details

Since a `Date` has no time associated with it, the parser takes it as midnight then converts it from `UTC` to local time. Any negative timezone will convert the date to previous day.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/bb219bd81dd431194f7b426721fa08923a1290db/packages/date-helpers/src/index.ts#L150-L152

## 📋 Steps to Reproduce

1. Create an experience with date from the first day of the month
2. Check the card and confirm that date appears on the last day of the previous month

## 📸 Screenshot
![246448138-a9d162ad-de07-418f-b9eb-d5a4e9459cd0](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/8512c35e-40f1-4466-b670-39e49860c300)

## 🙋‍♀️ Proposed Solution

1. Different parser for `Date`
2. Allow the parser to handle both `Date` and `DateTime`

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] `Date` from the API is parsed and formatted correctly
- [ ] `DateTime` still functions as expected

**Comment by petertgiles** [comment]
I'd suggest that the use case you're describing is misusing this function. :smile: The name of the function and the parameter signature show it's only supposed to handle DateTime strings in UTC, not zoneless Date strings.   I think we usually use just a regular `new Date(str)` for this use case.

This function could be made a lot smarter, though.  We could have it detect Date strings and parse them in the local time zone or just throw an exception to help prevent accidental misuse like this.

**Comment by esizer** [comment]
> I'd suggest that the use case you're describing is misusing this function. 😄 The name of the function and the parameter signature show it's only supposed to handle DateTime strings in UTC, not zoneless Date strings. I think we usually use just a regular `new Date(str)` for this use case.
> 
> This function could be made a lot smarter, though. We could have it detect Date strings and parse them in the local time zone or just throw an exception to help prevent accidental misuse like this.

That makes a lot of sense. I actually just looked and saw that `AwardContent` seems to be the only spot where this is apparently misused. I guess just updating that to the following should resolve the issue.

```tsx
formatDate({
  date: new Date(awardedDate),
  intl,
  formatString: "PPP",
})
```

**Comment by vd1992** [comment]
So is the acceptance criteria then just to implement the above solution?
