### ISSUE TITLE
✨ Add column and filters for Permissions on USER table

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#7004]
## ✨ Feature
As a platform admin, I want to see who has elevated permissions on the platform so I can more easily manage access.

## 🕵️ Details

On the USERS table we are adding a new column "Permissions". We also want to be able to filter by this column so Platform Admins can quickly see who the other Platform Admins are (or Request Responders or Pool Operators).

## 🎨 Design File

Include a link to the design file (if it exists).

## 📸 Screenshot

<details><summary>Screenshot</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/6e65c506-3991-4619-b1c6-88f0c420aa87)

</p>
</details> 

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Permission column on USER table shows: Platform admins, Request Responders and Pool Operators
- [ ] USER table can be filtered for: Platform admins, Request Responders and Pool Operators

**Comment by petertgiles** [comment]
Comment from Gray: not necessary to show team of team-roles but could be nice
