### ISSUE TITLE
✨Add an "Expand all" component for all accordions on the Job Posters and the "Profile and applications page" 

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/gc-digital-talent#7006]
**Description:** Screen reader user often open the majority of accordion items on these pages for an initial scan. 

**Potential solution:** Fable users suggest adding a button component before the first instance of accordions. This will allow  candidates to reveal all the hidden accordion content on the page.  This way, the platform won’t inadvertently hide sections from screen reader users or force users to decide which headings to click on and to click on one at a time, which can be cumbersome. 

**Job Poster example**

![Image](https://user-images.githubusercontent.com/101275838/246909183-894a31e8-cc1d-4de7-b74a-7c058fcae56f.png)

**Comment by gobyrne** [comment]
Putting this in the ice-box. Intent is to re-design the job poster. This is important... but it shouldn't need to wait to much longer.

**Comment by gobyrne** [comment]
Ok, this isn't only for the job poster there are 2 sections of the "Manage your career timeline" (for example) that also need expand-all. With @RM-1978 and @esizer we decided that the expand-all can be per section of the page instead of for the whole page.

**Comment by substrae** [comment]
@gobyrne We had already decided they would be per section. They just have to be designed and implemented on a case-by-case basis.

**Comment by tristan-orourke** [comment]
@gobyrne @substrae Does #8023 replace this one? Can this be closed?
