### ISSUE TITLE
New "supervisory" field on request form

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#7008]
DCM would like to know if the position in a request is a Team Lead or Individual Contributor type of position? to learn this we are adding a new required field to the form.
 
Might be worth merging or waiting for https://github.com/GCTC-NTGC/gc-digital-talent/issues/7232 to be done first

 ## MANAGER SIDE
 
<details><summary>Request form</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/e0181bae-0598-46b8-8937-7e7cde97f969)

</p>
</details> 
 
## ADMIN SIDE

<details><summary>Request page</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/0966cee1-3d78-4395-bae7-31f88ff23b0f)

</p>
</details>

**Comment by Jerryescandon** [comment]
Add question to requests "is this a manager position"?

**Comment by gobyrne** [comment]
@Jerryescandon update please

**Comment by Jerryescandon** [comment]
I'm not sure about the copy for this either on the form or on the admin side. Should we push the copy "Team lead vs Contributor"? or should we go with something more generic like "This position will supervise other employees"??

**Comment by petertgiles** [comment]
Merged into #7232
