### ISSUE TITLE
🐛 Download CSV button missing when looking at 500 item pages

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#7018]
## 🐛 Bug

**DCM has pools with over 1500 applicants**.  They wish to download the entire list of applicants (CSV spreadsheet) for assessment tracking. Currently to make this happen, they increase the items per page on the table to the highest possible (500) and then download per page, however **when loading the 500 items, the Download CSV button at the bottom of the table fails to load.** 

This does not happen when loading 10, 50 or 100 items at a time, but makes the process of downloading all users a tedious process. 

I have created a different issue to allow users to download the entire table regardless of number of pages.

This issue should focus on fixing the button not loading when switching to 500 items.

 
## 🦋 Expected Behaviour

Button to download CSV should appear at the bottom of the table when page is set to 500 and there's 3 or more pages on the table.

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Name and version (if possible).
- **Browser**: Name and version (if possible).

## 📋 Steps to Reproduce

1. Go to Pool candidate table with more than 500 candidates
2. Set the table to show by 500
3. Click download all 

## 📸 Screenshot

Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Button to download CSV should appear at the bottom of the table when page is set to 500 and there's 3 or more pages on the table.
- [ ] Download 500 records at a time should work fine as well

**Comment by brindasasi** [comment]
#8523 might solve this issue

**Comment by yonikid15** [comment]
#8974 and/or #8956 might fix this issue. We can check back to this after they are merged.

**Comment by mnigh** [comment]
> #8974 and/or #8956 might fix this issue. We can check back to this after they are merged.

@brindasasi is this still an issue or can it be closed as completed?

**Comment by brindasasi** [comment]
This has been completed.
They can download any number of candidates now 🥳
