### ISSUE TITLE
✨ Contact us on the IAP 

### ISSUE THREAD

**Issue by BrookeCameron** [GCTC-NTGC/gc-digital-talent#7023]
## ✨ Contact us on the IAP 

Contact us dialog box available on every page

requested by the IAP team

## 📸 Screenshot of button
<img width="1585" alt="Screenshot 2023-06-22 at 3 28 43 PM" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/c62757a2-6499-46e6-ae67-a4176b12faa3">

## 📸 Screenshot of open dialog box 
<img width="1251" alt="Screenshot 2023-06-22 at 3 29 34 PM" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/c5eddf43-4303-4fec-85dc-0fe9418ab39c">

## 🙋‍♀️ Proposed Implementation

Add extra button below stepper that is contact us that opens up the IAP contact us dialog box

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] opens the dialog box
- [ ] you can contact the team and access this at any point during the application process

**Comment by petertgiles** [comment]
Hi Brooke.  Is it important to have three input boxes like this to send email from the page?  In other places we've provided a clickable email link that will open in the user's preferred email handler.
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/a770fa3a-2c22-4688-a5c1-d82358e998d6)

Also, is "IA Program" a contraction used by the team?

**Comment by BrookeCameron** [comment]
No the three input boxes doesn't matter, the team ultimately just wants an easy way for people to by able to contact them throughout the application process. I'm fine if the copy is literally this in a dialog box

**Comment by petertgiles** [comment]
@BrookeCameron OK if the link is just a regular looking button instead of a psudo-step?

**Comment by BrookeCameron** [comment]
@petertgiles yes that's fine with me!

**Comment by BrookeCameron** [comment]
updated Figma and screenshots @petertgiles , @gobyrne & @MCommonda
