### ISSUE TITLE
✨ Hide work duration section on IAP

### ISSUE THREAD

**Issue by BrookeCameron** [GCTC-NTGC/gc-digital-talent#7024]
## ✨ Hide work duration section on IAP

Under work preferences on the IAP application please remove the _"I would consider acceptation a job that lasts for:*"_ and the radio button as it does not apply to the IAP application process

## 📸 Screenshot
![Screenshot 2023-06-20 at 3 35 30 PM](https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/e3e8820a-c859-497f-bd40-70f7bfbeb778)
Part to remove highlighted with big red box. 
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/2c3ec49e-79c9-4d5a-98cb-7cf1f9d510c0)

## ✅ Acceptance Criteria

As long as its not there the team is happy

**Comment by gobyrne** [comment]
"Any duration" should be selected by default if we are hiding this section

**Comment by BrookeCameron** [comment]
I agree with @gobyrne
