### ISSUE TITLE
🐛 Experiences - Should be called Additional details everywhere

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#7026]
## 🐛 Bug

The experience card section "Tasks and responsibilities" connects to "Additional information" in the form, I find this confusing to follow. For profile and related cluster. 

## 🕵️ Details

You can find and update experiences from 
`/en/users/:id/profile/resume-and-recruitments` after the merging of #7001

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/7367facb-3d53-4793-9978-8213b70d842b)

## 🙋‍♀️ Proposed Solution

Unify copy to "Additional details" style to make it clearer the two sections are connected. 
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/6e77761d-e7cd-4550-a08c-4b139ec34862)

## ✅ Acceptance Criteria

- [ ] Copy unified to "Additional details" style as shown in Josh's design
- [ ] Update anywhere in the app this data appears

## 📓 Footnote

This is what editing an experience within an application looks like, ~probably what it should match up with.~

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/a36dbb79-2e92-4a90-adf3-b64b6183e1b4)

**Comment by petertgiles** [comment]
@substrae OK to update "Additional information..." to "Tasks and responsibilities" heading, subtitle, and label?

**Comment by substrae** [comment]
@petertgiles @vd1992 

Other way around - all instances of this element should match the latest designs in #6935.

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/0f2f586a-e0e3-4d63-83bd-506cf79e59d8)

**Comment by petertgiles** [comment]
@substrae Is there an updated design for the experience card or should we sit tight for now?

**Comment by substrae** [comment]
@petertgiles 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/6e77761d-e7cd-4550-a08c-4b139ec34862)

**Comment by petertgiles** [comment]
@substrae Should we expand the scope of this issue to include anywhere in the app that it appears?

**Comment by substrae** [comment]
@petertgiles 

Yep - experience forms should be centralized and propagate everywhere, as should the experience cards
