### ISSUE TITLE
🕵️  Investigate solutions to voice control item numbers not appearing

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#7074]
## ♻️ Debt/Refactor

Currently, pages that need to request API data frequently have issues with not displaying item numbers when using voice control software. We need to investigate possible solutions for this.

## 🕵️ Details

The current belief is that this is related to our loading strategy. We need to investigate possible solutions to see if this is the case. See the following for more information:

- https://github.com/GCTC-NTGC/gc-digital-talent/issues/6954#issuecomment-1597615032

## 🙋‍♀️ Proposed Solution

> **Note**
> This issue very commonly occurs on the create pool page in admin so it could be a good place to target any testing

1. Investigate our `<Pending />` component to see if it is interfering with item number generation
2. Investigate using `react-router` [loaders and actions](https://reactrouter.com/en/main/guides/data-libs) for the page so see if loading all data at once fixes this

### 1. Pending strategy

> **Note**
> This is probably something we should do regardless of its impact on this specific issue

Right now, regardless of where the data is being loaded on the page, we simply hide everything on the page. The idea is that this overlay is causing some issue with the software's ability to determine interactive elements since. Since we still get numbers for other immediate items, this is less likely.

### 2. Loaders and Actions

This will allow us to gather all relevant information for a specific page _before_ rendering it. This should hopefully make all interactive elements present at the same time and reduce the chance of voice control software from missing some in its initial generation.

## :question: Main question to answer
What is best way to solve the issue of voice control numbers not appearing - short-term and long-term.

Timebox: 3 days

**Comment by RM-1978** [comment]
This issue has come up once  again in our latest round of AT usability testing with Fable. I am thinking that this Spike might need to be prioritized soon.

**Comment by esizer** [comment]
## 🕵️‍♀️ Findings

Another round of testing was done on the following platforms:

 - Windows - Voice Access
 - Android - Voice Access
 - MacOS - Voice Control
 - iOS - Voice Control

Overall, the test was very successful. The only platform where there were issues was Windows. While using Windows there were a number of issues completing tasks with voice access.

### 🪟 Windows specific issues

 - Numbers presented were inconsistent (sometimes it added them to an input, sometimes it did not)
 - While all inputs have accessible names, some could not be accessed using them (seemed to occur mostly on `input[type=number]` and `select` elements)
 - Using the `select` input was frustrating since the dropdown menu could not be accessed using either numbers or accessible name (had to say keyboard keys to press "press tab, press down arrow, press enter")
 - Windows was significantly slower than the other platforms while complete all tasks

While there were a lot of annoyances, nothing was blocking. Users should be able to submit applications and navigate the application with windows but it is not ideal and fairly frustrating. 

It is hard to pinpoint any specific issue since all platforms except windows perform well, especially since the issues are all present on native HTML elements. I believe this may be because windows accessibility features are not as good as other platforms but cannot confirm as of yet 🤷‍♀️ .

### 🔄 `<Pending />`

This did not interfere in any of the platforms, most were able to place numbers on elements obscured. Windows was inconsistent even on a full loaded, static page. I still believe we could change how we use this component in some places (hiding the entire page while we load the options for a select list seems to be heavy handed).

### ⏬ Loaders

While this could have benefits, I do not think it will fix the inconsistency on Windows since the other platforms had no issue finding and assigning numbers to inputs that appeared asynchronously or conditionally.

## 🙋‍♀️ Recommendation

I'd still like the explore the options in this ticket at some point but, I do not think they will solve the problems we see with voice access on windows.

**Comment by RM-1978** [comment]
Thanks @esizer! In the end, did you decide to change the input label for the signature box to be more intuitive? (e.g. "Click Signature box"  instead  of "Full name."

**Comment by esizer** [comment]
> In the end, did you decide to change the input label for the signature box to be more intuitive? (e.g. "Click Signature box" instead of " Click full name."

This may be a question for the copy caucus. We actually just recently changed it from "signature" to "your full name" 😅 

> I am also wondering if the Windows performance might be an issue for folks who might prefer this set up or want to use their Government laptops to apply for a different Government position. Should we direct them to use their personal MacOS platform instead of their work tools?

We could! I'm hoping that users that rely on this technology are aware that windows is subpar and use alternatives to begin with but I'm not sure 🤷‍♀️

**Comment by esizer** [comment]
> Thanks Eric. I'm glad it wasn't as bad as we thought. 😅 It sounds like the big opportunity is improving Windows behaviour. Short of "fixing Windows" is there anything we could do to help it work better?

It is hard to say. Windows struggled with many tasks and was generally worse than other devices/OS's even with other things outside of using the number's to navigate 😢
