### ISSUE TITLE
🐛 Talent Search page is crashing on UAT

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#7077]
## 🐛 Bug

On UAT, Talent Search page is just showing that a GraphQL error happened. I've traced this to an error in the `publishedPools` query, which returns pools, but also returns an internal error.

## 🦋 Expected Behaviour

Talent Search page should work fine on all verticals.
publishedPools query should not cause an internal server error!

## 🕵️ Details

This has been reproduced on and off the TBS network.

The error:
```
  "errors": [
    {
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 7,
          "column": 5
        }
      ],
      "path": [
        "publishedPools",
        14,
        "key"
      ]
    }
  ],
```
## 📋 Steps to Reproduce

1. Go to https://uat-talentcloud.tbs-sct.gc.ca/en/search

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/1a09e62d-ecdd-40a1-a79a-417ef8063712)

## 🙋‍♀️ Proposed Solution

The error makes it seem like there's an illegal key string in one of the pools. We should look at the pool keys in the database, and if that's the case, determine how this happened so it doesn't happen again.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] publishedPool does not cause an internal server error.
- [ ] We're confident this will not happen again on UAT or on Prod

**Comment by vd1992** [comment]
Weird, you cannot set the field `key` for a pool anywhere so how did that happen?

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/e4018500-efe4-4da4-887c-4ae2e7cc4e28)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/59386d93-bfa2-493e-b2da-5e48eda4c7c6)

Seeding adds keys to pool via factory 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/46f4ad5e-6663-450e-bcb6-6689d6b503f8)

**Comment by vd1992** [comment]
Is `pool.key` used for anything even? 

Anyway, think I found the source
Given the above how pool key is never set and thus null, the duplication of pools is messing up.
If `key = null` which is the case, then it is generating a key of `_1234567` or whatever the timestamp from `time()` is

Duplicate key should first check the original pool has a non-null key. 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/fdf5ec0d-0122-41be-8592-2b4fcf970b79)
