### ISSUE TITLE
✨ Application expiry date only set manually

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#7079]
> **Note**
> This is an issue rewrite of https://github.com/GCTC-NTGC/gc-digital-talent/issues/6363 for clarity.  Refer to that issue for discussion and background.

## ✨ Feature

We currently set the application expiry date to match the pool closing date for DRAFT applications and to one year in the future for NEW_APPLICATION applications.  CMO would like us to not set the expiry date automatically ever.
> It throws them off that there is an expiry date at all, if they havent been qualified yet. Since expiry dates should ONLY be assigned to qualified candidates
from DCMs perspective, any new application should come in without an expiry date set

## ✅ Acceptance Criteria

- [x] Expiry date is not automatically set anywhere 
   - including application creation or [submission](https://github.com/GCTC-NTGC/gc-digital-talent/blob/dfd30a8cac2898ec996a765c7efda8d74be181d5/api/app/GraphQL/Mutations/SubmitApplication.php#L40)
- [x] Expiry date is not a required field in any form, and the picker can be cleared to set a date to null
   - including the admin _Expiry date_ and _Add to pool_ dialogs on the user page or the notes on the snapshot page
- [x] Having a null expiry date is interpreted as the application not being expired for the purposes of searches, lists, etc

**Comment by vd1992** [comment]
Things to check on include

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/fd8d2b39-2cac-4470-9742-e0d04aa66c26)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/a0062321-d6f1-48c9-8130-2063b1c92c24)

**Comment by petertgiles** [comment]
@Jerryescandon When there's no expiry date, there's no link to set an expiry date.  Do you want a null message like "Change expiry date" or something?
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/fe477832-fb28-49cd-9ceb-b4065e618b6b)

**Comment by Jerryescandon** [comment]
Doh! Yeah that makes sense. Good catch 🪝
