### ISSUE TITLE
🛠️ Work with IMTD to set up a BI tool

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#7081]
## 🛠️ Tooling

Our client often has a need for [raw data](https://github.com/GCTC-NTGC/gc-digital-talent/issues/7021) and [reports](https://github.com/GCTC-NTGC/gc-digital-talent/issues/5307).  It would be convenient to lean on a BI tool to allow them to extract this data.

## 🙋‍♀️ Proposed Solution

We know other teams are using Microsoft PowerBI already.  This seems like the obvious candidate to use.  IMTD would probably need to be engaged to set it up.

## ✅ Acceptance Criteria

- [ ] A BI tool is set up
- [ ] A simple proof-of-functionality report is set up on it

**Comment by tristan-orourke** [comment]
We spoke with Kim Beal. She let us know the following:
- We can install Power BI on our surface tablets right already through the company portal.
- We should also be able to install Power BI on our VMs by going through IMTD. From there Power BI should be able to connect to the database directly, and we can start using it right away.
- Her team could set us up with a "self-service shared workspace", which would let many accounts on our team share access to the same reports. This would involve an MOU, she'll email me about pricing.
- If we wanted to publish the reports directly, that would be a higher-tier service. Not all Power BI report tools/products are accessible, so those are restricted in the publishable version. Other apps which use this integrate via the TAP portal, so this might not be an option for us anyway.
- She can share their accessibility standards document so we can follow it ourselves even with the basic tier.

**Comment by tristan-orourke** [comment]
Next step - ask IMTD to install Power BI on our -PS account VMs.

**Comment by petertgiles** [comment]
Tool has been set up and logins mailed out
