### ISSUE TITLE
🐛 No apply button in IAP Hero in Firefox

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#7095]
## 🐛 Bug

The apply now button doesn't appear for me in Firefox.  It appears OK in Chromium and Electron.  the apply now button in the About the Program section appears OK in Firefox.

## 🕵️ Details

- **Operating System**: Linux PopOS 22.04
- **Browser**: Linux 112.0

## 📋 Steps to Reproduce

1. Navigate to http://localhost:8000/en/indigenous-it-apprentice

## 📸 Screenshot

![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/11306542-90ab-4a1c-8735-900604087dbf)

## ✅ Acceptance Criteria

- [ ] Button should appear in Firefox

**Comment by mnigh** [comment]
Looks like a `z-index` problem.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/0255b6818a4f37063a795919e1070d15d536348a/apps/web/src/pages/Home/IAPHomePage/Home.tsx#L151

## Screen recording

https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/6bc36f42-510e-4346-8406-be6d1bb4e08e
