### ISSUE TITLE
🐛 IAP referred to as "IT Indigenous Apprenticeship Program"

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#7113]
## 🐛 Bug

> IAP should always be "IT Apprenticeship Program for Indigenous Peoples" NOT "Indigenous Apprenticeship Program"

Source: https://github.com/GCTC-NTGC/gc-digital-talent/issues/6593.

## 📋 Steps to Reproduce

1. Navigate to `/en/login-info?from=/en/indigenous-it-apprentice&personality=iap`
2. Observe **IT Indigenous Apprenticeship Program** text
3. Navigate to `/en/register-info?from=/en/indigenous-it-apprentice&personality=iap`
4. Observe **IT Indigenous Apprenticeship Program** text

## 📸 Screenshots

![Screen Shot 2023-06-27 at 16 08 54](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/30b12a4e-7746-4a5d-95cf-588771851d62)
![Screen Shot 2023-06-27 at 16 17 19](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/e538fa47-5d50-4300-a811-dcbbd9fe2f67)
![Screen Shot 2023-06-27 at 16 17 44](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/e4001e74-f9a2-4820-b28e-fa5dda3f7001)

## 🙋‍♀️ Proposed Solution

Replace instance of "IT Indigenous Apprenticeship Program" with "IT Apprenticeship Program for Indigenous Peoples". Make sure French equivalent is appropriately translated.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [x] no references in the codebase to **IT Indigenous Apprenticeship Program**
- [x] no references in figma files to **IT Indigenous Apprenticeship Program**

**Comment by petertgiles** [comment]
An eslint rule to prevent it from happening again.
```
"no-restricted-syntax": [
      "error",
      {
        selector: "Literal[value=/Indigenous Apprenticeship Program/i]",
        message:
          "The name of the program is IT Apprenticeship Program for Indigenous Peoples.",
      },
    ],
```

**Comment by BrookeCameron** [comment]
You are correct @mnigh ! The changes have been made to the Figma file, thanks for catching this.
