### ISSUE TITLE
🐛 DateInput min validation doesn't work with optional inputs.

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#7137]
## 🐛 Bug

DateInput min validation doesn't work with optional inputs.

## 🦋 Expected Behaviour

If the value is null, don't validate that is meets the minimum value.

## 📋 Steps to Reproduce

1. Add an DateInput component where the `min` validation rule is set but not the `required` rule.
  - https://github.com/GCTC-NTGC/gc-digital-talent/blob/89c6d77c6e511d0993f34fbc2e19a30785dda699/apps/web/src/pages/Users/UserInformationPage/components/ChangeDateDialog.tsx#L143 
2. Attempt to submit the form with no date.
3. Observe that the `min` rule is violated.

## 📸 Screenshot

![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/4ca0ca6d-5e37-4130-9567-b5e8dca03a5e)

## ✅ Acceptance Criteria

- [ ] The `min` rule doesn't fail for null
- [ ] The `min` rule properly checks non-null values
- [ ] Add `min` validation back to apps/web/src/pages/Users/UserInformationPage/components/ChangeDateDialog.tsx and apps/web/src/pages/Users/UserInformationPage/components/AddToPoolDialog.tsx

**Comment by esizer** [comment]
Oooops! Assuming I was right on the validation rule, adding a check should resolve this.... maybe 🤔 

https://github.com/GCTC-NTGC/gc-digital-talent/blob/1718bcea93c7b2e6a49bcc07e33b639cfe1d0c5e/packages/forms/src/components/DateInput/DateInput.tsx#L72
