### ISSUE TITLE
♻️ Apply GraphQL naming conventions

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#7141]
## ♻️ Refactor

Apply GraphQL conventions for naming.

## 🕵️ Details

Use consistent case for GraphQL queries, fragments, mutations, etc.

## 🙋‍♀️ Proposed Solution

1. Use `camelCase` to name fields and arguments.
2. Use `UpperCamelCase` for naming GraphQL types.
3. Name ENUM types using `CAPITALIZED_WITH_UNDERSCORES` style.
4. Avoid redundancy using `get` in your Query resolvers,  `fragment` in fragments, etc)

**Source**: https://graphql-rules.com/rules/naming

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] GraphQL query, fragment, and mutation names are consistent and follow proper naming conventions
- [ ] Add documentation to coding conventions doc

**Comment by vd1992** [comment]
Blocking this on #4662 as that issue would likely cause a lot of changes to the graphQL files making this issue possibly ill-advised to do first

**Comment by vd1992** [comment]
To be completed through #8681
