### ISSUE TITLE
🐛 Nginx static analysis warnings

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#7155]
## 🐛 Bug

The Nginx Amplify static analysis tools raised a few warnings about ways we can improve our configuration.

### Missing default.conf from /etc/nginx/conf.d

The default.conf file is missing from /etc/nginx/conf.d directory. A new nginx package may automatically add default.conf without a warning. Since your nginx.conf contains the [include](http://nginx.org/en/docs/ngx_core_module.html#include) directive for conf.d/*.conf files, a new default.conf will be automatically read by nginx. This may result in an unpredictable nginx configuration.

Create an empty default.conf file in /etc/nginx/conf.d (or copy the original default.conf from the standard nginx package).

### Missing server_name in a virtual server configuration

When nginx accepts a request, the first step is to [determine](http://nginx.org/en/docs/http/request_processing.html) which virtual server the request should be routed to. Without a [server_name](http://nginx.org/en/docs/http/ngx_http_core_module.html#server_name) directive set for a virtual server, the request may hit the wrong one.

Always configure a unique [server_name](http://nginx.org/en/docs/http/ngx_http_core_module.html#server_name) directive for a [server](http://nginx.org/en/docs/http/ngx_http_core_module.html#server). Make sure the [server_name](http://nginx.org/en/docs/http/ngx_http_core_module.html#server_name) contains all possible site names.
Check the following file:
/etc/nginx/sites-enabled/default, line 13
Regex location has no regex pattern

### Regex [location](http://nginx.org/en/docs/http/ngx_http_core_module.html#location) has a valid modifier, but does not have a regex pattern.

Performance-wise it is more efficient to configure exact or prefix matching for locations that do not require regex matching. It is also less prone to errors. Please refer to the documentation describing [location](http://nginx.org/en/docs/http/ngx_http_core_module.html#location) directive to learn more.
Check the following file:
/etc/nginx/sites-enabled/default, line 66

### Regex location has no anchors in regex pattern

Regex [location](http://nginx.org/en/docs/http/ngx_http_core_module.html#location) has a regex pattern without ^ or $. This is a configuration style that is prone to errors. It may also lead to a situation when requests partially matching the regex pattern are incorrectly routed to this location.

Always use ^ or $ achor in a regex pattern.
Check the following file:
/etc/nginx/sites-enabled/default, line 66

## 📋 Steps to Reproduce

1. Log into amplify.nginx.com
2. Navigate to Analyzer \ Static Analysis

## 📸 Screenshot

![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/90caf468-2bcf-48f8-a00a-42b062f52b11)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] No warnings from static analysis tool

**Comment by vd1992** [comment]
Estimate didn't get added or accidental product backlog addition?

**Comment by petertgiles** [comment]
I don't remember. :sweat_smile:  I'll move back to refinery.

**Comment by petertgiles** [comment]
The changes in #9968 will affect this in a big way.  The dev should probably run the static analysis again before starting this.

**Comment by petertgiles** [comment]
Only four warnings now.  I updated the issue.

**Comment by brindasasi** [comment]
@petertgiles could you invite me to this site? I don't think I've access 🤔

**Comment by petertgiles** [comment]
There's no main shared account for us on the service since we decided not to use it.  You can sign up for a free account if you want to try it out, though.
https://amplify.nginx.com/signup/
