### ISSUE TITLE
♻️ Refactor Experience tables to simplify queries

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#7157]
## ♻️ Debt/Refactor

Create a single table which connects experiences to users. This will simplify database queries. This should be done without modifying the api schema.

## 🕵️ Details

Answers on stackoverflow suggest that our Experience model *should* be implemented in the database with a single Experience table for common data, 'extended' by subtype tables. Then the experience_skill table would reference the base table. This would make some of our sql queries simpler! 
- https://stackoverflow.com/questions/59183196/what-is-the-most-efficient-way-to-model-the-relationship-between-these-entities/59232905#59232905
- https://www.softwaregems.com.au/Documents/Article/Database/Relational%20Model/Subtype.pdf
- https://www.softwaregems.com.au/Documents/Documentary%20Examples/IDEF1X%20Introduction.pdf

## 🙋‍♀️ Proposed Solution

https://docs.google.com/drawings/d/1JUPihw8wqnHkir68lXzwZpFYNUUKQrtb2j1PI_kGMGQ/edit?usp=sharing

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] You can get all the experiences, and all the ExperienceSkills, of a single user with a single query.
- [ ] The api schema is unaffected.

**Comment by vd1992** [comment]
@tristan-orourke 

Did you complete this issue as a side effect?

**Comment by tristan-orourke** [comment]
No, this is different from what I've done.

**Comment by vd1992** [comment]
This could be handy too, example implementation in Postgres
https://stackoverflow.com/questions/5466163/same-data-from-different-entities-in-database-best-practice-phone-numbers-ex/5471265#5471265
