### ISSUE TITLE
🎢 Fix right margins for "Add an experience" modal

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/gc-digital-talent#7158]
### Description
Copy as well as  Link outline extends off the right side of the modal.

## How to reproduce
1. Log in and navigate to Resume and recruitment
2. Open Add new Experience modal
 
### Screenshot
![Image](https://user-images.githubusercontent.com/101275838/250663734-aa351798-0d4c-4ac7-a4d2-5882a173a47d.png)

### Acceptance criteria 

- [ ] Right-side copy wraps within the modal margins 
- [ ] Link outline wraps within the modal margins

**Comment by petertgiles** [comment]
Reproduced in Firefox and Chromium
