### ISSUE TITLE
🐛 Skill requirements validation gap

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#7168]
## 🐛 Bug

I was able to proceed through the submission process with a validation error showing on the Skill requirements step of the stepper.  I'm not sure exactly what was setting it off.

## 📋 Steps to Reproduce

1. Start a new application
2. Fill in the skill requirements
3. Submit application

## 📸 Screenshot

![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/a9d4547f-49d1-477e-8715-8005878d8de5)

## ✅ Acceptance Criteria

- [ ] Should not show a validation error if the step is actually OK

**Comment by petertgiles** [comment]
It also disturbs me that the page submits OK - so it's using a separate validation path.  The form and the stepper should use the same validation.

**Comment by vd1992** [comment]
It seems you can replicate it by

- pick a pool form the browse page and note the required technical skills
- head to `/en/users/:userId/profile/career-timeline-and-recruitment/:experience/:experienceId/edit`
- add the required skills, do not fill in anything for "skills in detail", that section is optional, update the experience
- head to the pool from above and apply, you can go right through the skills page without needing to update anything
- stepper alert raised

Appears the core of the issue may be that the stepper requires a "skills in detail" for skills, but this isn't replicated for validation on "continue" or "submit". Given you can add skills with "skills in detail" from profile pages, it is likely to occur sometimes

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/e3700c33-e121-4964-af3e-8ddb9ea118f9)
