### ISSUE TITLE
🐛  Experience "save and go back" issues

### ISSUE THREAD

**Issue by marc-donofrio** [GCTC-NTGC/gc-digital-talent#7172]
## 🐛 Bug

The save and go back button is giving several users errors or not going back. When the skills do save, they sometimes duplicate.

## 🦋 Expected Behaviour

The info should be saved and the user taken to the previous page.

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

User quote: My Profile: Saving education details can duplicate entries. Filling out education details, clicked "Save and go back", button changed to simply "Save". Clicked "Save" button, then without further input after a few seconds browser went back to list of all experiences and skills on my profile, where the one entry was duplicated into two. Deleting one of the two did not delete the other, and the two appeared to have the exact same contents.

User quote:  Issue happens in latest versions of Edge & FF. When I view the browser console I see a 403 Forbidden error, referrer policy strict-origin-when-cross-origin POST https://talent.canada.ca/graphql.

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/42844328/5e9e8b57-66c2-4aa1-92f5-368fe1dc8bd1)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/42844328/487e3e2b-73d1-447a-a4d4-1f8bfb0aeec1)

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Criteria 1
- [ ] Criteria 2

**Comment by petertgiles** [comment]
Was able to recreate quickly clicking the save button to generate duplicate experiences.  Not sure 403 is coming from though.

**Comment by petertgiles** [comment]
The repeated submission problem has been split off to #7212.

**Comment by marc-donofrio** [comment]
Here is some more details:

Is the user logged in? Yes
What were they trying to do?  Add new experiences
On what page? Profile - Experience and Skills - Add Experience

Note: this seems to occur with adding skills too.

**Comment by petertgiles** [comment]
Spun off remaining issue to  #7522
