### ISSUE TITLE
🐛 SnapshotTest intermittently failing

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#7204]
## 🐛 Bug

The SnapshotTest PHPUnit test is intermittently failing.

## 🕵️ Details

```
  FAILED  Tests\Feature\SnapshotTest > create snapshot                         
  Failed asserting that two arrays are equal.
       'positionDuration' => Array (...)
       'experiences' => Array (...)
       'poolCandidates' => Array (
  -        1 => Array (...)
  +        0 => Array (...)
       )
       'isProfileComplete' => true
   )
  

  at tests/Feature/SnapshotTest.php:88
```

## 📋 Steps to Reproduce

1. Test tests/Feature/SnapshotTest.php

## 📸 Screenshot

![image.png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/0cd86770-3cf5-4fd8-b3b9-51555f0954d1)

## ✅ Acceptance Criteria

- [ ] Test reliably passes

**Comment by petertgiles** [comment]
Probably fixed in  #7173

**Comment by petertgiles** [comment]
Eric guesses this is due to the expiry date being set or not set

**Comment by petertgiles** [comment]
> I can't even get it to fail on my machine despite running the test file over 50 times

That's very strange.  I see it fail in CI about 20% of the time, I estimate.

**Comment by vd1992** [comment]
> > I can't even get it to fail on my machine despite running the test file over 50 times
> 
> That's very strange. I see it fail in CI about 20% of the time, I estimate.

If you get a chance, please try running too and see how frequently it fails for you
I'm using this command

`for i in {1..30}; do docker-compose exec -w /home/site/wwwroot/api webserver sh -c "./vendor/bin/phpunit ./tests/Feature/SnapshotTest.php"; done`
