### ISSUE TITLE
♻️ Upgrade Prettier to 3.0

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#7205]
## ♻️ Debt/Refactor

Prettier 3.0 is out but seems like it has some breaking changes around how it interacts with eslint.

## 🕵️ Details

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/15589ae0-7a04-4cdc-80fe-ba0567ea4715)

## 🙋‍♀️ Proposed Solution

https://prettier.io/blog/2023/07/05/3.0.0.html

## ✅ Acceptance Criteria

- [ ] Prettier is at >= 3.0

**Comment by vd1992** [comment]
Gave it a go, got formatting mismatches between VS Code format on save and Eslint. Maybe something to try again after a few dependency bumps
