### ISSUE TITLE
✍️ Update work region labels

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#7214]
Update the list of locations on the search page to read:

- Telework
- National Capital Region (Ottawa/Gatineau)
- Atlantic (NB, NS, PE and NL)
- Quebec (excluding Gatineau area)
- Ontario (excluding Ottawa area)
- Northern (NU, NT, YT)
- Prairies (AB, SK, MB)
- British Columbia

![Image](https://user-images.githubusercontent.com/2494551/250934613-a189aa37-0fa0-43ad-8b42-be9a54fcd62a.png)

AC:
- [ ] Descriptions updated on search page
- [ ] OK to propagate shared strings out into application

**Comment by mnigh** [comment]
@gobyrne Some of the abbreviations used aren't very official. How about using the [two letter codes](https://www.canadapost-postescanada.ca/scp/fr/soutien/sujet/directives-adressage/symboles-et-abreviations.page) instead (which, conveniently, are the same in English and French)?

- Telework
- National Capital Region (Ottawa, Gatineau)
- Atlantic (NB, NS, PE, NL)
- Quebec
- Ontario
- Northern (NU, NT, YT)
- Prairies (AB, SK, MB)
- British Columbia

**Comment by RosalieM1978** [comment]
@mnigh Hum these abbreviation are the offocial[ Canadian postal abbreviations](https://www.canadapost-postescanada.ca/cpc/en/support/articles/addressing-guidelines/symbols-and-abbreviations.page).

**Comment by petertgiles** [comment]
@gobyrne Are you OK if this change propagates throughout the application anywhere work location appears (profile forms, view application, search page, admin pages, etc)?
