### ISSUE TITLE
🐛 Snapshot not found

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#7217]
## 🐛 Bug

DCM has reported several instances in which they view a candidate in an ongoing recruitment pool but then gets a "Snapshot not found" error.

- The applicant has their status as "New"
- We have asked around and there seems to be **NO ONE** has placed this candidate directly into this pool.
- This is an ongoing recruitment pool
- We assume that this candidate applied using the application process.
- We assume they applied and no snapshot got generated, but they got placed into the pool.

To whoever picks up this ticket, ask jerbo for the name of the user.

## 🦋 Expected Behaviour

Snapshot should get generated and tied to every user that applies to a pool (Ongoing recruitment pools included)

## 🕵️ Details

![MicrosoftTeams-image (3)](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/878b731c-8708-4e28-8f8c-6e039de29458)

## 📋 Steps to Reproduce

Find examples in prod in this message:
https://talent-cloud.slack.com/archives/C0259G6KXJ6/p1690384537785269

## ✅ Acceptance Criteria

- [ ] Submission should fail if snapshotting fails. 
- [x] Figure out how to reproduce the issue
- [ ] Close the gap
- [ ] If unable to figure out what's wrong, implement a way to figure it out (extra logging, etc).

**Comment by petertgiles** [comment]
Gray, Jerbo, and I have the name of a user in prod this is happening to.  If you pick up this issue, request the name from one of us.

**Comment by vd1992** [comment]
> * We assume that this candidate applied using the application process.
> 
> * We assume they applied and no snapshot got generated, but they got placed into the pool.

I think the signature field for pool candidates will only be null if added by admin, so if the signature field is non-null, it was through the application process and the failed step was within the snapshot chain.

**Comment by tristan-orourke** [comment]
Could this be relevant...? https://github.com/GCTC-NTGC/gc-digital-talent/pull/7374

**Comment by petertgiles** [comment]
I checked out the example user and noticed they have an experience that is mostly nulled out:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/dbae04c7-ef5b-47c9-b8e5-e02fe10c8009)

I replicated it locally, too.  When submitted the application the user gets a "something went wrong" toast and the form remains in the background the application is marked as submitted and the snapshot is null.  In the Laravel log file:
```
[2023-09-01 20:21:38] local.ERROR: Call to a member function format() on null {"userId":"redacted","exception":"[object] (Error(code: 0): Call to a member function format() on null at /home/site/wwwroot/api/app/Http/Resources/WorkExperienceResource.php:23)
```
