### ISSUE TITLE
Priority number conditionally required if "I have a priority entitlement" selected

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#7220]
Priority number should be required if applicant selects "I have a priority entitlement" on the "Government Information" section of the profile.  It is still optional when creating an account.

### Additional details

From Julie:

> Hi Jerbo! Can we please make the priority number field here mandatory if a candidate selects that they have priority entitlement? I think some candidates are confusing this field as EE priority entitlement (even though we link to the explanation) 

![Image](https://user-images.githubusercontent.com/16977254/248818632-8beb78c5-e6fe-4fb2-b7cb-f4f4329bbe24.png)

### Acceptance Criteria
- [ ] "Priority number provided by the Public Service Commission of Canada" is required if applicant selects "I have a priority entitlement" on the "Government Information" section of the profile.
- [ ] Exists on profile page, application page
  - [ ] NOT a required field on create account page
- [ ] Backend and frontend validation (is step complete, is profile complete)

**Comment by gobyrne** [comment]
@petertgiles what would it take to have this continue to be "not required" on the "Create account" page?

**Comment by petertgiles** [comment]
Yeah, we could do that and still have it be part of the "is section complete" and "is profile complete" checks required to submit applications.

**Comment by gobyrne** [comment]
Ok, can you update the acceptance criteria please? And maybe re-estimate or bump up the estimate?
