### ISSUE TITLE
New "Screened out" statuses "No longer interested" and "Not responsive"

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#7221]
## Description

DCM wishes to be able to mark and track candidates who have been invited to participate in assessments but are either **No longer interested**, or have **Not responsive** to participate in the assessments and cannot be moved forward in the process.

For all intents and purposes, candidates placed in these statuses have been **screened out** and will no longer be considered for assessment or referred to managers.

## TO-DO

Add two new statuses to the pool-candidate relationship:
 - `Screened out - No longer interested` 
 - `Screened out - Not responsive`

Things to consider for both statuses:

- Since these applicants have not been properly assessed, the link on the Action column shows the  **Application Snapshot** in the candidates table.
- These new statuses are hidden by default in the candidates table.
- Candidates with this status do not show up on requests.

On the Profile and Application tracker side:

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/213bbf67-5add-480e-9485-565e936c50f2)

## Acceptance Criteria

- [ ] `Screened out - Not responsive` and `Screened out - No longer interested` added on admin-facing ui
- [ ] `Screened out` added on applicant-facing ui

**Comment by gobyrne** [comment]
@Jerryescandon and @gobyrne flush this out for dev

**Comment by gobyrne** [comment]
Looks good now, thanks

**Comment by esizer** [comment]
@Jerryescandon or @tristan-orourke , where in the sort order should these go? We are currently applying these weights to screened out statuses:

```SQL
when pool_candidate_status = 'SCREENED_OUT_APPLICATION' then 60
when pool_candidate_status = 'UNDER_ASSESSMENT' then 70
when pool_candidate_status = 'SCREENED_OUT_ASSESSMENT' then 80
```

**Comment by Jerryescandon** [comment]
These are theoretically applicants that were deemed to have passed their application but ar being screened out before any assessment so... 65?
