### ISSUE TITLE
♻️ Move Application Insights out of initial bundle

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#7228]
## ♻️ Debt/Refactor

From: https://github.com/GCTC-NTGC/gc-digital-talent/discussions/6508

Application Insights is a big part of our initial bundle.  If we can lazy-load it from a separate bundle then it would improve the experience for the user when the application boots faster.

## ✅ Acceptance Criteria

- [ ] Application Insights is not included in the initial bundle
- [ ] Telemetry works as before.

**Comment by esizer** [comment]
I was abler to split it out but I think I missed something because it only ended up doing `142kb` 🤔 

![Screenshot 2023-10-24 090324](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/bf687ab5-c0f6-4b48-b6ec-8117b7865b75)

**Comment by petertgiles** [comment]
142 seems right, accordion to Bundlephobia.  If you can get the 31kB reactjs plugin as well then you're golden.
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/2722dfd9-70a1-4abc-bb72-8d27a6e1f675)

**Comment by esizer** [comment]
> 142 seems right, accordion to Bundlephobia. If you can get the 31kB reactjs plugin as well then you're golden.

I guess I should have followed the links. I was expecting it to be larger for some reason 😆 . Sounds like im on the right track then.

**Comment by esizer** [comment]
I posted [a PR](https://github.com/GCTC-NTGC/gc-digital-talent/pull/8306) and we decided to close it since we didn't see any benefit. Should this issue be closed now?
