### ISSUE TITLE
Switch to profile should happen at "Screened in" not at "Qualified"

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#7231]
### User story
As a pool operator, I want the full applicant profile to be easily available as soon as I screen them in, so that I can base decisions off as much info as possible.

### Description
We only show the snapshot for pool candidates (to pool operators) until the candidate's status is set to Qualified at which point we also show their full profile.

Update this so that all statuses EXCEPT "new application" and "application review" give access to the full profile. 

**Here are all the statuses for reference:**
![Image](https://user-images.githubusercontent.com/2494551/252743158-32a2eba3-9190-4b97-ba62-9d53bf85ff01.png)

**Candidate info page:**
![Image](https://user-images.githubusercontent.com/2494551/252744689-d3ed0219-8ba9-4195-9004-982c29554918.png)

**View user page:**
![Image](https://user-images.githubusercontent.com/2494551/252744813-16e5070f-6f7b-4b9d-b89b-0026ec132551.png)

### Acceptance Criteria

- [ ] When browsing Pool Candidates, the View user page (instead of Candidate info page) is shown for all statuses except "new application" and "application review"

**Comment by vd1992** [comment]
Not needed at the moment
