### ISSUE TITLE
✨ Directive on Digital Talent: Digital Services Contracting Questionnaire

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#7234]
## ✨ Summary

The first of 3 (maybe 4) forms that we'll be adding to the site for managers to complete and submit on a semi-regular basis. These forms don't demand any new input UI, meaning they can leverage existing components. Where applicable I've added lo-fi mockups for more complex elements like repeaters so that you have a point of reference to work from for the UI.

There will be 2 phases to the development of these forms and their experience across the site:
- Phase 1 consists of us creating the data model in the database for each form, creating pages and UI for each form, and storing submissions in the database for data querying purposes
- Phase 2 is more elaborate and brings the forms behind a "manager" series of features that will require new authentication requirements, a manager dashboard, save-as-draft functionality, and more

### 📌 Resources

- Print version (Ask @substrae)

```[tasklist]
### Standard requirements
- [ ] Create feature flag `DIRECTIVE_FORM_CONTRACTING_QUESTIONNAIRE`  (routing and links only appear if flag is TRUE)
- [ ] The form has its own page component included a storybook story, linked to from the Directive on Digital Talent page, as well as the Manager homepage when its ready
- [ ] The form's dedicated page has introductory copy as outlined in the print version of the form
- [ ] Additional instruction has been added to the top of page (see Figma)
- [ ] Form submits to database
- [ ] The Directive on Digital Talent page has an updated block to link to the page (see screenshot below)
```

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/32638dcb-ff22-45e3-b017-ad947411f4b5)

## 💽 Data model

As outlined in [the Directive on Digital Talent Figma file](https://www.figma.com/file/QPLlxobrg2ZQCW5nf1HDFx/DoDT-forms?type=design&node-id=12-7776&mode=design), the first form has been formatted into a logic flow that explains where branching logic/decisions alter the experience and completion requirements. These flows provide context on what type of input is required, as well as whether the input triggers children and/or whether an existing data model is being referenced.

```[tasklist]
### Logic requirements
- [ ] The form only shows relevant information based on the user's current answers
- [ ] The form correctly (and accessibly) presents new fields when a relevant option is chosen in parent fields
- [ ] The form pulls data from existing data models as required
``` 

Example of the flow:

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/2c7bbdd1-7550-45d9-8fcd-3768635932ef)

**Comment by petertgiles** [comment]
The backend was done in #7273.  This issue now represents just the frontend work.

**Comment by mnigh** [comment]
Related: https://github.com/GCTC-NTGC/gc-digital-talent/issues/7577
