### ISSUE TITLE
EPIC: FABLE RESULTS (Q1 2023-24 TESTS)

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/gc-digital-talent#7237]
This round of Fable Testing focussed on the following steps of the Application process: 

1. Applicant profile 
2. Applicant résumé
3. Education requirement
4. Skills requirement 
5. Screening questions

**Comment by esizer** [comment]
This Epic has no issues associated with it. Is it safe to close?

**Comment by RM-1978** [comment]
Yep
