### ISSUE TITLE
✨ Job poster changes

### ISSUE THREAD

**Issue by BrookeCameron** [GCTC-NTGC/gc-digital-talent#7245]
## ✨ Feature

A couple of minor copy changes to the job poster 

## 🕵️ Acceptance Criteria

changes to the following sections
- Location, language, and security
- Contact and accommodation
- Hiring policies 

Please note all changes have been marked with comments on the figma file 

## 📸 Screenshot [changes marked in red]
<img width="182" alt="Screenshot 2023-07-12 at 3 00 45 PM" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/51a5c3ad-bde0-4bd7-938d-f179229a922d">
<img width="587" alt="Screenshot 2023-07-13 at 9 20 13 AM" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/27413c56-d48b-4897-87ed-5d436c6fe79d">

## 📍Location, language, and security

Change copy from "Remote optional" to "Remote, hybrid or on-site"

## 📧Contact and accommodation 

change copy from "Do you require accommodations? or do you have any questions about this process? Please contact the Digital Community Management Office if you require any accomodations during this application process.Email: fames@acanteipsum.ca" to be more general. 

New copy: "Please contact the [[Name] team](example@email.com) by email if you have **any questions** or **require an accommodation** during this process." 

## 💼 Hiring policies  

Change the title from "Hiring policies" to "Who can apply?" 
change body copy to "Persons residing in Canada, and Canadian citizens and Permanent residents abroad. 
Preference will be given to veterans, Canadian citizens, and to permanent residents." 

Please note that this title copy change should also be reflected in the nav bar

**Comment by gobyrne** [comment]
@petertgiles This almost overlaps with #7219, but not quite.

**Comment by RM-1978** [comment]
It is also somewhat related to #7370 and #7006.
