### ISSUE TITLE
May instead of Can for no results on search page

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#7278]
## Request for Recruitment Team

I think we changed this in one place, but it also appears in another.

This is (sort of, other than the typo) good:
![Image](https://user-images.githubusercontent.com/2494551/253325607-e0f10395-32c2-4e2c-a63d-940074cbe245.png)

This is not good:
![Image](https://user-images.githubusercontent.com/2494551/253325771-d2d90329-e0f1-4d62-9801-f5ad38b618d4.png)

On the search page, when there are no results, we show the following text:

> We didn't find any matching candidates.
> We can still help! 

Please change second line to:

> We may be able to help! 
> FR: Nous pouvons peut-être vous aider!

### Acceptance Criteria

- [ ] "We may be able help!" should be "We may be able to help!" everywhere
- [ ] Search results at the bottom of the page also reads "We may be able to help!" FR:"Nous pouvons peut-être vous aider!"

**Comment by mnigh** [comment]
Closed with #7286.
