### ISSUE TITLE
♻️ Bump `typescript-eslint` to v6

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#7281]
## ♻️ Debt/Refactor

A new major version of `typescript-eslint` was released with some breaking changes.

## 🙋‍♀️ Proposed Solution

You can follow the breaking changes listed in the article, [Announcing typescript-eslint v6](https://typescript-eslint.io/blog/announcing-typescript-eslint-v6/).

- Bump to the latest version of `typescript-eslint`
- Fix any breaking changes

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] `typescript-eslint` is on >= 6
- [ ] Lint checks pass

**Comment by vd1992** [comment]
Appears to have been handled automatically (?) in #7421
