### ISSUE TITLE
✨ Remove text and icon for placed statuses in `QualifiedRecruitmentCard`

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#7300]
## ✨ Description

`QualifiedRecruitmentCard` for "placed" statuses should not show text or icon.

## 📷 Screenshot

<img width="1219" alt="Screen Shot 2023-07-27 at 10 44 16" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/01b3b2d8-5b01-4640-9ac1-4358d758a2ea">

## 🙋‍♀️ Proposed Solution

Update conditional logic in `getAvailabilityInfo` to remove icon and text:

https://github.com/GCTC-NTGC/gc-digital-talent/blob/9973dacd67d1660c61d620b68cbbec524436e50f/apps/web/src/components/QualifiedRecruitmentCard/utils.ts#L98-L107

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] `getAvailabilityInfo` renders no copy or icon based on three "placed" statuses

**Comment by substrae** [comment]
@Jerryescandon @mnigh 

I'm thinking something like this?

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/0ac9165b-3a59-4cae-be06-3fb8b12c1045)

**Comment by Jerryescandon** [comment]
Love it. Ship it.

**Comment by mnigh** [comment]
> ![image](https://user-images.githubusercontent.com/6960386/254283209-0ac9165b-3a59-4cae-be06-3fb8b12c1045.png)

@substrae I think these statements are all a bit verbose and use technical language (see: recruitment) and would benefit from a professional copywriter that would simplify the copy itself, but I would suggest that at the very least, "you might still received opportunities" should be changed to "you might still receive opportunities" as it is using the wrong verb tense.

**Comment by mnigh** [comment]
@gobyrne does this issue need to move to development or is it not needed?

**Comment by gobyrne** [comment]
It's needed, but not ready yet

**Comment by Jerryescandon** [comment]
Aight baby, I got some approval from DCM on the copy for this status:

`Congrats! As you were hired into a term position from this recruitment, you will no longer receive opportunities related to it. Contact us for more information`

The "contact us" link should open a mailto to the pools' main email.

Additionally I have a [spreadsheet ](https://docs.google.com/spreadsheets/d/16OjYysdlrsSP8IrQJLL7UXYzPA6iskJnlRzeMQ8gDJc/edit?usp=sharing)for better tracking these.

**Comment by petertgiles** [comment]
@Jerryescandon There's quite a lengthy discussion on this issue.  Gray just queued this up for the next sprint so I want to confirm: the final scope for this issue is just to remove the text and icon for the placed statuses?

**Comment by Jerryescandon** [comment]
> @Jerryescandon There's quite a lengthy discussion on this issue. Gray just queued this up for the next sprint so I want to confirm: the final scope for this issue is just to remove the text and icon for the placed statuses?

Correct.
