### ISSUE TITLE
🐛 "Number of Skills Matched" column not ordering correctly

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#7302]
## 🐛 Bug

"Number of skills matched" column not ordering correctly on PoolCandidates table.

## 🦋 Expected Behaviour

Ordering table by this column should order by the count number, ascending or descending.

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Name and version (if possible).
- **Browser**: Name and version (if possible).

## 📋 Steps to Reproduce

1. ...
2. ...

## 📸 Screenshot

Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

After we turned the value from a number to an inline button which opens a modal, its probably trying to sort based on the text instead of the number value.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] When ordering PoolCandidates table by Skills Matched column, users with most skills matched appear at the top (or bottom) as expected

**Comment by vd1992** [comment]
Is it? I think it appears to be working at its sort, sorting within the status/category groups. 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/e0e51f85-49de-43ac-8099-3b573b9c1580)

**Comment by esizer** [comment]
> Is it? I think it appears to be working at its sort, sorting within the status/category groups.

Yeah, I think it is but it is super confusing 😵‍💫  because it sorts by status and category first then skill count. The locks are meant to indicate that but I'm not sure how clear that is 🤔
