### ISSUE TITLE
🐛 Track Application Card -  Update action links

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#7309]
## 🐛 Bug

Visit Resume link points to recruitment section on resume page which is counter intuitive to the user.
We need to change the text for the link. 

## 🦋 Expected Behaviour

Track Application Card -  

- [ ] Change "Visit Résumé" to "Manage Recruitment"  
- [ ] Change aria-label to "Manage the {title} recruitment on your career timeline"
- [ ] Remove "Manage availability" link

## 📸 Screenshot

![image (22)](https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/13dac6c1-ca66-46c9-b97d-6cde767e9e12)

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Change "Visit Resume" to "Manage Recruitment"  
- [ ] Change aria-label to "Manage the {title} recruitment on your career timeline"
- [ ] remove "Manage availability"

**Comment by vd1992** [comment]
Per acceptance criteria
'Change aria-label to "Manage the {title} recruitment on your résumé"'

Should it be that, given we're phasing out usage of "resume" in #7305
