### ISSUE TITLE
♻️ Upgrade Lighthouse `nuwave/lighthouse` to version 6

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#7321]
## ♻️ Refactor

Lighthouse `nuwave/lighthouse` released a new major version in March 2023. We should upgrade from version 5 to version 6!

## 🙋‍♀️ Proposed Solution

Upgrade guide: https://github.com/nuwave/lighthouse/blob/master/UPGRADE.md#v5-to-v6

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] application builds and runs as before

**Comment by vd1992** [comment]
Looking through it, definitely some changes of note that may be tricky.
