### ISSUE TITLE
🧪 Test to ensure snapshot queries stay in sync

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#7323]
## 🧪 Tests

We currently have two queries that should stay in sync:
- api/app/GraphQL/Mutations/PoolCandidateSnapshot.graphql used to generate the snapshots
- apps/web/src/pages/Profile/ProfilePage/profileOperations.graphql used to query live data
 
Unfortunately they have drifted apart over time.  It's a bit weird to have a test that spans projects but I think it's worth it in this case.  The test will need to be a little clever since the two queries aren't totally identical - one is a `users` query and one is a `me` query.

## 🙋‍♀️ Proposed Solution

A PHPUnit test that loads up both files and compares them.  It might need to parse the JSON to do a proper comparison.

## :question: Questions
- Can PHPUnit read a file that's above the project root?  That might be tricky.

## ✅ Acceptance Criteria

- [ ] An automated test warns if the two files go out of sync
- [ ] Existing files put back in sync

**Comment by vd1992** [comment]
Maybe an altenative would be to check in CI instead, like with this test
https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/.github/workflows/check-lighthouse-schema.yml

**Comment by petertgiles** [comment]
> Maybe an altenative would be to check in CI instead

I like it!
