### ISSUE TITLE
Request table changes for View Request link

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#7349]
## ✨ Feature

From UAT, we got the feedback that DCM team  don't like that View + Job Title for Action Link column 

## 🕵️ Details
We updated the links on the request table to use the submitted job title instead of just saying "view request". Unfortunately, these job titles are not informative to the request responders. Instead we want to change it to something that helps them understand what the request is.

Working with the recruitment team, we decided to use the classification and stream to generate this text.

Format: "View [ group-level] [stream] request"
Example: View IT-04 Software solutions request

Additionally since this repeats some info in the other columns (stream and classification) we can now hide those columns by default. We don't want to remove the columns completely though, because we still want to be able to sort by them if needed. But we can still hide Classification and stream columns by default on this table now.

### Current 
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/d2599f41-5f4f-4913-afdd-cfad5ebbd87d)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Column header changed back to "View request"
- [ ] View request link uses the text format "View [ classification-level] [stream] request" (FR: Voir la demande pour [group-level] [stream])
- [ ] "Stream" and "Group & Level" columns are hidden on the request table by default
-  [ ] Job title does not need to be a column at all

**Comment by vd1992** [comment]
Does the "Job title" column also need to be added back?

**Comment by mnigh** [comment]
> Does the "Job title" column also need to be added back?

@Jerryescandon are you to confirm or deny this?

**Comment by Jerryescandon** [comment]
Not as per our last conversation. However we also debated the link needing to be descriptive too. We landed on making the link:
**View [Group and level] + [Stream] request**

And in this case, what happens to current "Group and Level" and "Stream" columns? 
Answer: hide them by default but keep them as part of the table for filtering purposes

@gobyrne can you confirm?

**Comment by Jerryescandon** [comment]
From the man himself:

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/1f813c47-e53f-4380-8ea8-a3ce8f96bead)

**Comment by gobyrne** [comment]
I updated the issue details and acceptance criteria

**Comment by brindasasi** [comment]
@gobyrne  @tristan-orourke 
Could you check for this issue on Aug. 2 with Julie as she will be giving an final confirmation on this one
