### ISSUE TITLE
✨ Implement `SkillBrowser` component inline version

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#7352]
## ✨ Feature

Implement inline version of `SkillBrowserDialog` called `SkillBrowser` component on `SearchPage`.

## 🎨 Design File

[Talent Search](https://www.figma.com/file/9V8kBIWxOXRaN9dkcVCU1o/Manager---Talent-search?type=design&node-id=204-1593&mode=design&t=1E5MWAvwf6py5aYJ-0)
[Job Application V6 (Select an experience)](https://www.figma.com/file/BXYVsu1fo9LS2IySJDUINY/Candidates---Job-application---Version-1-to-6?type=design&node-id=547-49171&mode=design&t=1E5MWAvwf6py5aYJ-0)
[Pools Record of Decision (Add Essential and Asset Skill modals)](https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Pools---Record-of-Decision?type=design&node-id=3513-11411&mode=design&t=1E5MWAvwf6py5aYJ-0)

## Component  Screenshot 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/101275838/f998d64e-d152-4446-a931-6c290fa023ad)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Implement inline `SkillBrowser` component on `SearchPage`
- [ ] Remove the old component from the code

**Comment by mnigh** [comment]
@Jerryescandon are there any other locations that the inline skill browser component should be implemented? also, could you add a link to a figma design file if there is one? thanks!

**Comment by RM-1978** [comment]
> @Jerryescandon are there any other locations that the inline skill browser component should be implemented? also, could you add a link to a  design file if there is one? thanks!

Hi @mnigh  and @Jerryescandon,  @esizer and I took a look at instances of the old skill picker on UAT. We suggest reducing the scope of this ticket to implementing the inline version of the SkillBrowser component on  the SearchPage.

**Comment by gobyrne** [comment]
@Jerryescandon can you update the figma for the search page with the new skills component pretty please?

**Comment by Jerryescandon** [comment]
Updated the [Search page figma gile](https://www.figma.com/file/9V8kBIWxOXRaN9dkcVCU1o/Manager---Talent-search?type=design&node-id=204%3A1594&mode=design&t=4Ifid8rPgXnfbekL-1) to match
