### ISSUE TITLE
🦾 Manual evaluation of the  date picker component with Narrator and VoiceOver

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/gc-digital-talent#7359]
## ⌨ Accessibility Review

Manual evaluation of the component with Narrator and VoiceOver to be sure that there are no issues with these out-of-the box readers. Fable tester recommended test because they Were testing using JAWS and NVDA.

### WCAG 2 Criteria

[2.1.1 Keyboard](https://www.w3.org/WAI/WCAG22/Understanding/keyboard)
[2.1.2 No Keyboard Trap](https://www.w3.org/WAI/WCAG22/Understanding/no-keyboard-trap)
[2.1.3 Keyboard (No Exception)](https://www.w3.org/WAI/WCAG22/Understanding/keyboard-no-exception)
[2.1.4 Character Key Shortcuts](https://www.w3.org/WAI/WCAG22/Understanding/character-key-shortcuts)

See: [Diverse Abilities and Barriers ](https://www.w3.org/WAI/people-use-web/abilities-barriers/#cognitive)for more information 

## 🦋 Expected Behaviour

Our date picker works seamlessly for narrator and VoiceOver 

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Windows 11, Mac OS
- **Browser**: Edge, Safari, Chrome
- **Assistive Technology**: Narrator, VoiceOver

## 🧪 Testing Steps

1. Open a  (Year month, day) date picker with Chrome and narrator/Voice over 
2. Open a (Year month) date picker with Chrome and narrator/Voice over
3. Interact with the components
4. Enter a date manually not using the combo box
5. Create an error (enter an really old date or a future date) 
6. Try first letter navigation for the month6. Arrow through the months 
7. Adjust the combo or edit box for the year does to see if it changes when using the VO arrow keys.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the issue was addressed.

- [ ] Year, month, day field inputs work can handle multiple input methods (e.g. typing and keyboard navigation)
- [ ] Error handling is present for each field

## 🙋‍♀️ Proposed Solution

Discuss proposed solutions if required.

**Comment by vd1992** [comment]
Timebox <1 day

**Comment by esizer** [comment]
I just realized, we wanted to get the custom validation in before assessing this component. Is that still the case or should I remove the blocker?

**Comment by RM-1978** [comment]
We tested it with both readers,   However, want to make sure it doesn't perform differently when the custom validation is added.  (see dependency above). #7324 has not been prioritized in the last two sprints.  As a result, our final test is delayed. Recommend adding the validation and this ticket to the "V sprint."

**Comment by substrae** [comment]
@brindasasi Are you referring to the situation where the user tries to submit an invalid date? Ideally our front-end limitations prevent them from entering a non-existent calendar date in the first place. In other situations where the data has further limitations (such as it needs to be within a range, then yes, I agree that it should read out the year, month, and day, and the also say "this date must be between X and Y".

**Comment by gobyrne** [comment]
This was closed after conversation with Lee and Eric. It has already been reviewed and improvements are identified. The functionality in substrae last comment will be broken off into another ticket and error message copy can be improved in a new ticket as well.
