### ISSUE TITLE
🐛 Non-status and status First Nations values both true

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#7360]
## 🐛 Bug

Both "I am Status First Nations" and "I am Non-Status First Nations" First Nations values are able to be saved in the profile.

## 🦋 Expected Behaviour

If one option is true, the other cannot be.

## 📋 Steps to Reproduce

1. Navigate to profile, Diversity, equity, and inclusion section
2. Click Edit this information for I affirm that I am First Nations (status or non-status), Inuk (Inuit), or a Métis person.
3. Check "I am Status First Nations" and "I am Non-Status First Nations" checkboxes for First Nations field
4. Submit form
5. Observe both values saved

## 📹 Screen recording

https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/9b34018c-048f-465f-87a0-dc9ecfe3409a

## 🙋‍♀️ Proposed Solution

If one checkbox option is checked, the other cannot be.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] both "I am Status First Nations" and "I am Non-Status First Nations" First Nations values cannot be saved simultaneously
- [ ] create regression test to avoid behaviour in future
- [ ] Error message from Gray: "Please select either Status First Nations or Non-Status First Nations."

**Comment by petertgiles** [comment]
How would this work in the UI?  If you check one box does the other become unchecked and disabled?  Or do the pair of boxes get changed to radio buttons like before?

**Comment by mnigh** [comment]
> How would this work in the UI? If you check one box does the other become unchecked and disabled? Or do the pair of boxes get changed to radio buttons like before?

@GCTC-NTGC/designers can you chime in here?

**Comment by substrae** [comment]
@petertgiles @mnigh 

We need these to be checkboxes because radio options don't allow you to unselect something. Checkboxes will uncheck others in the same group that have a matching `name` attribute, if I'm remembering correctly.

**Comment by Jerryescandon** [comment]
**Josh**
: The `name `thing should work just fine


**Eric Sizer**
: Josh is correct, we can give them the same programmatic name say `first-nations` then a value of `status` or `non-status` and checking one should uncheck the other.


**Jerbo**: do we need to announce it tho?

**Josh**
: Nope - they're treated like every other checkbox - the label just needs to be clear that only one can be selected


**Eric Sizer**: We could use the context prop to let users know so they aren't confused and think it is a bug

**Josh**: For sure. If we wanna be like super duper extra clear

**Comment by petertgiles** [comment]
>  We could use the context prop to let users know so they aren't confused and think it is a bug

Copy, please?  I imagine "your identity can't include" might be a little sensitive.

**Comment by RM-1978** [comment]
I agree @petertgiles. I am wondering if we could work with @BrookeCameron and @MCommonda  to adapt text from the recent Honesty Pledge definition work that they did in the Figma file below: 

[Honesty Pledge:  Archived Version 3 ](https://www.figma.com/file/IThJdlxAJqQPJyvX88hAG7/IAP-Honesty-Pledge?type=design&node-id=4648-56446&mode=design&t=jgsURyFPHfQ9mtJ1-0)

> See  the Indigenous as defined for this program frame for details.

**Comment by RM-1978** [comment]
I am not sure we should do something that is technically possible, but heuristically challenging for users, especially for a11y.  I am concerned about establishing a [new and unfamiliar user heuristic t](https://aelaschool.com/en/interactiondesign/10-usability-heuristics-ui-design/) that is inconsistent with the rest of the platform and other web platforms.

I propose instead that we explore : [HTML radio buttons allowing multiple selections](https://stackoverflow.com/questions/20982993/html-radio-buttons-allowing-multiple-selections) as a potential solution??

**Comment by substrae** [comment]
>I am concerned about establishing a [new and unfamiliar user heuristic t](https://aelaschool.com/en/interactiondesign/10-usability-heuristics-ui-design/) that is inconsistent with the rest of the platform and other web platforms.

This isn't accurate - I've encountered this behaviour many times in the past. With a proper label, there is no issue with proceeding with this direction.

**Comment by substrae** [comment]
@esizer 

Allowing them to select both and providing an error afterwards seems more confusing to me. We're assuming there will be a problem without actually knowing. So in this case, if we're _convinced_ that the checkbox approach will not work for specific reasons, we should be going back to the original layout of a single "I am First Nations" checkbox that then triggers two radio options below to show up.

**Comment by substrae** [comment]
@RM-1978 

No, you were clear. I have seen checkboxes used this way in the wild for this specific type of question, which is why I suggested it. The only alternative is to revert back to the original combination of a single checkbox, that reveals two radio options. I leave it up to @esizer to make a call on which is more accessible.

In terms of validation, because this question can in fact be left blank, there is no need to validate it further if it's empty. I think Eric's code was suggesting that we present an error if both boxes are checked at the same time.

**Comment by RM-1978** [comment]
@susbstrae 

> In terms of validation, because this question can in fact be left blank, there is no need to validate it further if it's empty. I think Eric's code was suggesting that we present an error if both boxes are checked at the same time.

Ah yes, you are correct, @esixer and i discussed two types of validation yesterday, I remember now that it was the multi-select behaviour for checkboxes that he suggested we solve for.

**Comment by petertgiles** [comment]
Added message from gray: Please select either Status First Nations or Non-Status First Nations.
