### ISSUE TITLE
✨ Make ExperienceSkill soft-deletable

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#7363]
## ✨ Feature

ExperienceSkills, the pivots between experiences and UserSkills, should be soft-deleted instead of deleted by default. Connecting a skill/userSkill to an experience should restore the appropriate soft-deleted entry, if one exists.

## 🕵️ Details

UserSkills already use soft-delete, and the `syncSkills` and `connectSkills` methods of Experience will restore the appropriate UserSkill if a soft-deleted row exists, before linking to it.

Now we want the ExperienceSkill entry itself to also use soft-delete. The main goal is to preserve the details field on the pivot table in the following situation:

1. I link a skill to an experience, and write out details for it. This creates a UserSkill, and an ExperienceSkill which links to it.
2. I delete the skill from my library, which automatically (soft-)deletes any linked ExperienceSkills  (see #6942)
3. I re-add the skill to the experience. This restores the soft-deleted UserSkill _and_ ExperienceSkill.
4. I see the details text I previously wrote without having to re-write it.

## 🙋‍♀️ Proposed Implementation

The tricky thing here is that ExperienceSkill is implemented using [Laravel pivot table](https://laravel.com/docs/10.x/eloquent-relationships#defining-custom-intermediate-table-models) features, and...
> Pivot models may not use the SoftDeletes trait. If you need to soft delete pivot records consider converting your pivot model to an actual Eloquent model.

So if we want to use built-in soft-delete features we'll need to convert ExperienceSkill into an actual model, and make sure it doesn't affect the API. If that's too hard, we might be able to fudge it with some clever global scopes.

Besides that, this will mostly involve code changes to the `syncSkills`, `connectSkills` and `deleteSkills` methods of the Experience.php class.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] ExperienceSkills deleted with the `deleteSkills` or `syncSkills` methods are soft-deleted
- [ ] When creating experienceSkills with `syncSkills` or `connectSkills`, if a soft-deleted experienceSkill already exists for the relevant UserSkill, restore it instead of creating a new record.
- [ ] The functionality of the API from an outside perspective is not affected at all.
- [ ] PHPUnit tests

**Comment by vd1992** [comment]
Just trying to get a feel for what is going on. 
So if the soft delete doesn't work, would another solution then be to:

- Add a field called, say, "is hidden" to pivot table "experience_skill" that default to false
- deleting sets it to true, connecting sets to false, sync sets to true or false variably
- scope added called `notHidden` that queries `where('is_hidden", false)`
