### ISSUE TITLE
Announce Job Poster page titles to AT

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/gc-digital-talent#7370]
## 🕵️‍♀️ Details

**💻AT Configuration** 
NVDA, on Chrome, in Windows 11

**Testing Step:** 

Navigate to the " Asset skill test (IT-03 Information and Data Functions)'' link and select it.

**Tester Feedback:**

1. When I clicked on the see " Asset skill test (IT-03 Information and Data Functions)'' link and the page changed, I did not receive any verbal feedback from Voiceover. Upon link activation, the page didn't tell me it changed/updated.
2. After clicking the continue application link I received no verbal feedback from voiceover confirming the page had updated.

**Related WCAG Criteria**

1.3.1 Info and Relationships: Information, [structure](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html#dfn-structure), and [relationships](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html#dfn-relationships) conveyed through [presentation](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html#dfn-presentation) can be [programmatically determined](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html#dfn-programmatically-determined) or are available in text.

## 🧪 Testing

1. Navigate to " Asset skill test (IT-03 Information and Data Functions)''job poster pages with a screen reader on.
2. Listen for the loading state to be announced (if the page actually takes time to load)

## **🌟Potential solution**

 - Focus the page title on page load for every job poster which has enough context to allow a user to know they can access the Job poster information. 

**Related issues**
- https://github.com/GCTC-NTGC/gc-digital-talent/issues/7245
 - [[a11y] Announce Page Loading #5922](https://app.zenhub.com/workspaces/gc-digital-talent-6092dc05157fa30010edaef9/issues/gh/gctc-ntgc/gc-digital-talent/5922)

**Comment by esizer** [comment]
Having a hard time reproducing this one. We already put focus on the heading 1 on all page loads across the site. Since the issue mentions both VoiceOver and NVDA, I tested both but could not reproduce the issue.

- FireFox + NVDA (recommended pairing)
- Safari + VoiceOver

**Comment by esizer** [comment]
Tested and can no longer reproduce.
