### ISSUE TITLE
Mismatch labels for Tasks and Responsibilities vs Additional Details

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#7371]
### Details
We now use the "additional information" section of the "add experience" instead of the original "task and responsibilities" what we used with "work expeirnece". We never updated the label for work experience though.

### Acceptance Criteria
- [ ] Task and responsibilities section of the work experience card is re-named to "Additional information"
- [ ] Check to make sure all the other 4 types of experience are also label "Additional information"

### Original issue

> Another small bug  I think tasks and responsibilities is mislabeled on the manage your resume page when you're editing experience... currently says additional information for this experience but is linked to tasks and responsibilities 

![Image](https://user-images.githubusercontent.com/2494551/254604230-b9e275ca-f8e2-42d0-abea-fd77d5d4a8d8.png)

![Image](https://user-images.githubusercontent.com/2494551/254604157-e581c33e-22d5-4356-ab1d-899873822ac5.png)

**Comment by vd1992** [comment]
I believe this is to be addressed in https://github.com/GCTC-NTGC/gc-digital-talent/issues/6935
Per the discussion in closed issue https://github.com/GCTC-NTGC/gc-digital-talent/issues/7026

**Comment by mnigh** [comment]
@yonikid15 can you review to see if this will be closed by #7026?

**Comment by yonikid15** [comment]
> @yonikid15 can you review to see if this will be closed by #7026?

Yes, this should be closed by #7026 @mnigh

**Comment by mnigh** [comment]
Closed as part of https://github.com/GCTC-NTGC/gc-digital-talent/issues/7026.
