### ISSUE TITLE
✨ Skill Library - individual skill page

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#7378]
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/04a9d5ee-2f12-4ba3-a5f4-7b14df775871)

## ✨ Feature

On this page, a user can update the details of a UserSkill (like skill level and whether they're using the skill in a current role), as well as manage links between this skill and any experiences.

## 🕵️ Details

This page has two sections:
1. Skill level self-evaluation: shows the skill definition, and contains a form for editing UserSkill details. The delete button next to the save button opens a modal for confirmation.
2. Experiences featuring this skill: we can reuse the list of experience cards from elsewhere. "Link a new skill" opens a modal where you can search your experiences. (Do we already have this modal on the Application-Skills page?) "Edit" opens a modal where you can edit the experience-skill details or remove it.

QUESTION: what url should this page be at?
ANSWER: `/applicant/profile-and-applications/skills/:skill-id`

## 📸 Screenshots

For convenience only - remember to work from figma to stay up-to-date!

<details><summary>Full page (Incomplete)</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/ddf0653b-06a1-4727-958e-a3362de9c100" />
</details>

<details><summary>Full page (Complete)</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/f8390f8e-d640-4834-9011-b0dcb050020d" />
</details>

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] This is behind SKILL_LIBRARY feature flag
- [ ] Route exists for new page
- [ ] Table of contents
- [ ] User can update level and isCurrent for this userSkill
- [ ] User can delete skill via modal
- [ ] User can see all experiences this skill is linked to
- [ ] User can add, remove, or edit linked ExperienceSkills
- [ ] Everything is connected to API

**Comment by petertgiles** [comment]
> /skills/skill-name
I recommend using the skill ID, not the name.  Names change.

**Comment by petertgiles** [comment]
Currently missing copy for skill levels.
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/d531da93-0327-4658-b01b-1f80b30b8025)

**Comment by vd1992** [comment]
Who can we ask to get the missing copy for this? This issue is otherwise good to go I think.
