### ISSUE TITLE
✨ Add skill level and currentlyUsed to UserSkills

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#7380]
## ✨ Feature

Add two fields to UserSkills: skill level and the "is this skill currently used or was used in the past" field (name pending).

## 🕵️ Details

We need these details to support #7378. 
Both these fields must be nullable.

- Four enums
1. BEGINNER
2. INTERMEDIATE
3. EXPERT
4. LEAD

- `currentlyUsed` should be an enum
- What should we call this second field? `WhenSkillUsed`

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Fields added to schema
- [ ] Fields added to database
- [ ] Fields added to factory
- [ ] After seeding, applicant@test.com user has some UserSkills with these fields filled in, and some where they are null

**Comment by petertgiles** [comment]
I added an enum for the skill picker in the directive form questionnaire but I don't know if it will be exactly the same here.  If we want to reuse it, that enum can probably get moved to the main schema file and renamed.
https://github.com/GCTC-NTGC/gc-digital-talent/blob/5385fb31b251be4e17428cfe9e96d1a2179c42e7/api/graphql/directiveForms.graphql#L99

**Comment by petertgiles** [comment]
> But we've found the meaning of enums more clear in the past, and more options can be added.
Definitely

> A number might also be easier for sorting?
This is a great point.  We also might need to do things like "greater than or equal to intermediate" or "less than expert".  On the other hand, this might be over-engineering.  Even if two or three options get added manual sorting and filtering is easy.

**Comment by petertgiles** [comment]
> What should we call this second field?

Maybe WhenSkillUsed?
