### ISSUE TITLE
🏈 Form submission handlers should return a `Promise`

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#7384]
## 🏈 Spike

Right now, because of how we structure our `handleSubmit` functions, the `formState.isSubmitting` is not reliable.

## 🕵️ Details

This is likely to do with the fact that `react-hook-form` needs us to pass either an `async` function or one that returns a `Promise`.

REF: https://github.com/react-hook-form/react-hook-form/issues/1363#issuecomment-610681167

I do not believe we can simply return the result of a `urql` mutation since it is an instance on `OperationResult` and not a promise. I'm not sure how or if we can some how standardize our submission handlers to use the result of a `urql` query to keep `isSubmitting=true` while the mutation runs so we can more reliably use `formState` instead of prop drilling the `fetching` boolean from `urql`

### Context

This is mostly for being able to disable certain elements on a form (submit button) to prevent duplicate submissions. See the conversation at the following link for more details.

REF: https://github.com/GCTC-NTGC/gc-digital-talent/pull/7318#issue-1812387332

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] Can we use `urql` to make our submission handlers work with `react-hook-form` state?

## ⏲️ Timebox
2 days

**Comment by esizer** [comment]
This may no longer be needed. Since [v7.48.0](https://github.com/react-hook-form/react-hook-form/releases/tag/v7.48.0), `react-hook-form` now allows us to control this through a disabled option to the hook.

**Comment by vd1992** [comment]
Disabling the form upon submit and then enabling in the 
```
  const handleSubmit: SubmitHandler<FormValues> = async (formValues) => {
    // disable here
    return mutation(
      formValuesToSubmitData(formValues),
    )
      .then((response) => {
        // reverse here
        if (response) {
```
block seems the most straightforward approach?

**Comment by esizer** [comment]
> block seems the most straightforward approach?

Yeah, I think we could likely close this and create an issues to add that into our forms 👍

**Comment by vd1992** [comment]
You can have the honours of doing so

**Comment by esizer** [comment]
> You can have the honours of doing so

Created new issue https://github.com/GCTC-NTGC/gc-digital-talent/issues/8467 closing in favour of it.
