### ISSUE TITLE
Language level text should use full names of test type

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#7385]
On the language information page of the profile. The different language levels are named a bit confusingly. For example, one of them is just "comprehension". We should switch to clearer names.

Current:
![Image](https://user-images.githubusercontent.com/2494551/256015680-856f7f44-21cb-42ca-bc8d-783ee4964694.png)

Update to:
> Reading | Writing | Oral Interaction

French:
> Lecture | Écriture | Expression orale

## Acceptance Criteria

- [ ] labels update where language levels are used

**Comment by mnigh** [comment]
> Update to:
> 
> > Reading | Writing | Oral Interaction
> 
> French:
> 
> > Lecture | Écriture | Expression orale

@gobyrne Are these official terms that are widely used for language skills? 

TBS uses the following:

- Written Comprehension
- Written Expression
- Oral Proficiency

REF: https://www.canada.ca/en/treasury-board-secretariat/services/staffing/qualification-standards/relation-official-languages.html#introduction

Canada School of Public Service uses the following:

- Reading comprehension
- Written expression
- Oral interaction

REF: https://www.csps-efpc.gc.ca/lt/index-eng.aspx

**Comment by mnigh** [comment]
@gobyrne a few questions:

1. should the column names for the CSV and the labels for the print documents be changed as well (Comprehension Level becomes Reading Level; Second language level (Comprehension, Written, Verbal) becomes Second language level (Reading, Writing, Oral interaction))?
2. should the categories between parentheses be title case or sentence case: Niveau de connaissance de la langue seconde (Lecture, Écriture, Expression orale) or Niveau de connaissance de la langue seconde (lecture, écriture, expression orale)?
