### ISSUE TITLE
✨ Build backend to support "Skill showcase"

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#7387]
## ✨ Feature

We need to build the backend which will allow us to build the "Skill showcase" page #7386.

## 🕵️ Details

For their Skill showcase, users can define the "top skills" and "skills you'd like to improve". They can do this separately for Behavioral and Technical skills, for a total of 4 lists. Order matters for each of these lists, since users can choose how to order skills.

## 🎨 Design File

Figma: https://www.figma.com/file/9Bq2VP39MW4hXKH7RfrovZ/Candidates---Skill-showcase?node-id=143%3A27334&mode=dev

## 📸 Screenshot

<details><summary>For convenience only - remember to work from figma to stay up-to-date!</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/ad662ade-5fb4-4fb3-9994-ad501f37cf41" />
</details>

## 🙋‍♀️ Proposed Implementation

I think we should just add two nullable Int fields to UserSkill. For sake of discussion lets say they're `topShowcaseNumber: Int` and `improveShowcaseNumber: Int` (better names decided by implementer).

If the number is null for a UserSkill, it's not in the list. Otherwise, it can be set to any number by the api mutation. We don't check for uniqueness, because Behavioural and Technical skills share the same field. We leave it up to the frontend to decide how many are allowed in each list - it will be easy for the frontend to sort them, whatever the numbers are, so I'm not worried about validating the values.

Update: actually, considering we'll want to set the order for [a number of skills at the same time](https://www.figma.com/file/LXvsSV76DcjExZZMCX0Iif/Candidates---Update-a-skill-showcase?type=design&node-id=2-3787&mode=design&t=nuKnPz9nmiUI8EgK-0) (#7378), it might be a pain to set the number with a migration for each skill individually. Maybe we need a mutation which simply takes an array of skill ids and syncs it up. It could even be the above implementation in the database if we handle it with migration class.

Even for querying, we _could_ do the ordering on the backend. Use a Laravel Accessor to put a field on the User object which gives the ordered lists straight up, like...
```
type User {
  userSkills: [UserSkill]
  topBehaviouralSkills: [UserSkill]
  topTechnicalSkills: [UserSkill]
}
```
I don't know if that's better than letting the client figure it out, but something to consider.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] When querying UserSkills, the client will be able to determine which skills are in the showcase lists and in what order
- [ ] When updating UserSkills, the client will be able to change the showcase lists
- [ ] Factory and seeder are updated so that `applicant@test.com` user has some skills in each list.
- [ ] PHPUnit test

**Comment by vd1992** [comment]
Blocking this on the skill migration issue #7575 as a change in how to access the category of a skill will impact the logic of how this feature will be implemented.
