### ISSUE TITLE
🐛 Salary ranges not translated

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#7396]
## 🐛 Bug

Currently, our salary ranges are hardcoded but should be processed by formatjs so we can present properly formatted currency for specific locales.

## 🦋 Expected Behaviour

Salary ranges are added to formatjs so they can be translated.

## 🕵️ Details

You can find proper formatting on the [writing tips plus](https://www.noslangues-ourlanguages.gc.ca/en/writing-tips-plus/canadian-dollar-symbol) page.

### Location

https://github.com/GCTC-NTGC/gc-digital-talent/blob/54bb6c750fa169aca3d80d3b8f36a8d4b4d98216/packages/i18n/src/messages/localizedConstants.tsx#L131-L138

## 🙋‍♀️ Proposed Solution

Add to `defineMessages` and translate the strings.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Salary ranges are processed by formatjs
- [ ] Currencies are translated properly
- [ ] change **$100,000 - plus** to **$100,000 +** (fr: **100 000 $ +**)

**Comment by mnigh** [comment]
Since @vd1992 astutely pointed out that these strings are not actually used anywhere, closing this issue in favour of #7446.
