### ISSUE TITLE
🛠️ Re-enable `no-unused-modules` eslint rule

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#7453]
## 🛠️ Tooling

The eslint rule for `no-unused-modules` has been disabled since it was causing eslint to no longer work in VSCode.

## 🕵️ Details

It seems as though this specific rule does not work with non-standard config names, we need to figure out how to work around this issue.

## 🙋‍♀️ Proposed Solution

The rule is too slow to run effectively in local environments. Run it only on CI.

- ~Wait until the library fixes the issue?~
- ~Define specific config for each package with this rule~

Maybe look into [combining configs](https://eslint.org/docs/latest/use/configure/combine-configs#apply-a-config-object-to-a-subset-of-files)? :thinking: 

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt tooling was properly updated and remains functional.

- [ ] eslint still functions in CLI and IDE
- [ ] eslint is checking for unused modules
- [ ] performance is not affected
- [ ] no-unused-modules rule runs in CI but not locally

**Comment by tristan-orourke** [comment]
@esizer is this still an issue?

**Comment by esizer** [comment]
> @esizer is this still an issue?

Yeah, I was actually meaning to come back to some of these linting issues now that we have fixed the lint config.

**Comment by petertgiles** [comment]
Problem is due to issues within the eslint library itself.  Unsure if this has been fixed yet.

**Comment by tristan-orourke** [comment]
If its slows down local eslint servers because linting runs all the time locally, can we run it in CI but not locally?
