### ISSUE TITLE
🐛 Profile `StatusItemTitle` aligned inconsistently

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#7454]
## 🐛 Bug

`StatusItemTitle` aligned inconsistently.

## 🦋 Expected Behaviour

`StatusItem` titles within `HeroCard` components should all be aligned the same way.

## 📋 Steps to Reproduce

1. Navigate to`/applicant/profile-and-applications`
2. Switch to French
3. Observe `StatusItem` titles within `HeroCard` components are not all left-aligned

## 📸 Screenshot

![Screen Shot 2023-07-31 at 13 42 28](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/6698453c-9ad1-425f-9f0f-ba0159e88c1a)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] `StatusItem` titles within `HeroCard` components should all be left-aligned
- [ ] changes to component should not break other pages

**Comment by petertgiles** [comment]
One more example:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/fdbb3c5c-6288-4c2b-8230-60813ce51886)
