### ISSUE TITLE
🐛 Storybook Hot Reload Broken

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#7460]
## 🐛 Bug

Storybook hot reload no longer works after upgrading to V7.  A change to the story results in a "Couldn't find story" error.  The only resolution is to full stop Storybook and restart it.

## 📸 Screenshot

![image (10).png](https://images.zenhubusercontent.com/6172cf6e898e11fd20507433/f379ac4f-0f4c-428a-b7e1-593e28234b65)

## ✅ Acceptance Criteria

- [ ] If Storybook is already running, when a change is made it should automatically perform a hot reload and show the change.

**Comment by vd1992** [comment]
Think I found what encapsulates the problem in https://github.com/storybookjs/storybook/issues/21349
Unfortunately, issue is still open and not sure why casing is throwing problems for us? As we aren't hardcoding folder names (other than app or web or src which are always lowercase) anywhere I think

**Comment by petertgiles** [comment]
Good find!  The symptom is exactly what I'm seeing.  I'm not sure about the workaround, though.  I can't think of any directories with uppercase characters, including the workspace directory.  This is a good clue, though.  I bet it has something to do with the path settings.

**Comment by vd1992** [comment]
Only place so far I can tell where the path globbing seems to come in to play. 
Unless I am missing something, may not be able to do anything until the issue gets addressed (someday) by the storybookjs team. 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/493ae0b1-5209-43e5-ad0b-0169c3900993)

**Comment by petertgiles** [comment]
No way forward right now - icebox
