### ISSUE TITLE
🐛 `TrackApplicationsCard` actions not left-aligned, breaking out of parent container

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#7465]
## 🐛 Bug

`TrackApplicationsCard` actions are center-aligned instead of left-aligned. Additionally, on smaller screens, the action titles break their parent container.

## 🦋 Expected Behaviour

1. `TrackApplicationsCard` actions should be left-aligned
2. Action titles should fit within their parent container

## 📋 Steps to Reproduce

1. `npm run storybook`
2. Search for `TrackApplicationsCard`
3. Change viewport to smaller size
4. Observe action title alignment and titles breaking out of container

## 📸 Screenshots

![Screen Shot 2023-08-01 at 11 49 55](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/71bc023d-d0d6-40b4-b217-4d92d0860036)
![Screen Shot 2023-08-01 at 11 52 31](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/4b1d8a75-42ee-4e12-b702-b14dce429672)

## 🙋‍♀️ Proposed Solution

1. `TrackApplicationsCard` actions text left-aligned
2. Action titles break to single column on smallest break point

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] `TrackApplicationsCard` actions should be left-aligned
- [ ] Action titles should fit within their parent container
- [ ]  Text should wrap to the size of the card

**Comment by mnigh** [comment]
@GCTC-NTGC/designers do you approve of the proposed solution?

**Comment by Jerryescandon** [comment]
What is single column, each link would display one per row? that is possibly best.

**Comment by mnigh** [comment]
> What is single column, each link would display one per row? that is possibly best.

Yes, exactly that.

**Comment by Jerryescandon** [comment]
Ship it

**Comment by RM-1978** [comment]
@esizer and I feel that it might be best if it were left justified and wrapped?
