### ISSUE TITLE
🐛 Abbreviation mismatch broken translation

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#7467]
## 🐛 Bug

Intl string broken

## 🕵️ Details

Either needs an abbreviation function added along with an abbreviation, or the abbreviation removed from the French 

## 📋 Steps to Reproduce

1. Observe at `/fr/admin/users/:id/profile`

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/4f7057b7-7ff5-46b4-88db-f62686e46d4f)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/2f7e1139-9c2f-4a0b-97d3-2cfbba1f42a0)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/d26df0ec-ac70-4649-a3b2-f4295bddc9a2)

## ✅ Acceptance Criteria

- [ ] Translation fixed

**Comment by mnigh** [comment]
We have this exact string used for the same purpose in `ProfileDocument`:

## English
https://github.com/GCTC-NTGC/gc-digital-talent/blob/7a25fcc647913922bb5ad6a1dc35ce72ed4bc111/apps/web/src/components/ProfileDocument/ProfileDocument.tsx#L294-L300

## French
https://github.com/GCTC-NTGC/gc-digital-talent/blob/7a25fcc647913922bb5ad6a1dc35ce72ed4bc111/apps/web/src/lang/fr.json#L7443-L7446

I suggest we use the same `defaultMessage` and add in a `dividingColon` afterwards, what do you think @GCTC-NTGC/developers?
