### ISSUE TITLE
🧪 `ExperienceTest.php` intermittent failure

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#7483]
## ♻️ Debt/Refactor

Intermittent test failure. 

## 🕵️ Details

Test `testSkillRelationshipsWorkWithPivot` in `ExperienceTest.php`

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/3778d0b0-9a36-4e55-99c8-a3a61062990f)

## ✅ Acceptance Criteria

- [ ] Test suite passes reliably (5+ runs) in CI and locally

**Comment by vd1992** [comment]
Cannot seem to replicate this locally, seems like it'll be tricky to get to the bottom of or ensure that it is fixed.

**Comment by mnigh** [comment]
@GCTC-NTGC/developers is anyone seeing this test fail lately or can this issue be closed?

**Comment by vd1992** [comment]
From what I can tell, no, PHP Unit cleaned up its act for the time being
https://github.com/GCTC-NTGC/gc-digital-talent/actions/workflows/phpunit.yml?query=is%3Afailure

**Comment by mnigh** [comment]
Back again: https://github.com/GCTC-NTGC/gc-digital-talent/actions/runs/9654164339/job/26627872719?pr=10776#step:7:566

**Comment by esizer** [comment]
Still not fixed enitrely

**Comment by vd1992** [comment]
Total zombie issue
🧟 💀

**Comment by esizer** [comment]
> Total zombie issue
> 🧟 💀

Maybe it was a fluke when I saw this? Have you witnessed it recently @vd1992 ? We may be safe to close finally? 🤞

**Comment by vd1992** [comment]
Unfortunately not yet, saw it once again recently. It is infrequent

**Comment by vd1992** [comment]
Five days ago 

https://github.com/GCTC-NTGC/gc-digital-talent/actions/runs/10198776808/job/28214385537

**Comment by petertgiles** [comment]
I just ran it on a loop for about 15 minutes (~200 runs) and no failures.  :face_with_spiral_eyes:

**Comment by esizer** [comment]
> I just ran it on a loop for about 15 minutes (~200 runs) and no failures. 😵‍💫

Close it and someone can re-open if they see it agian? Maybe be smarter than me and link the last failed run for reference :sweat_smile:

**Comment by vd1992** [comment]
Ran all tests locally, off main, and immediately saw it happen 🤷‍♂️ 

![image](https://github.com/user-attachments/assets/e2f90d54-e070-4d8e-9661-5ade7144c904)

**Comment by tristan-orourke** [comment]
I ran the test 50 times without issue. @vd1992 I think there might be something wrong in your environment...

**Comment by mnigh** [comment]
I just ran `for run in {1..20}; do php artisan test ./tests/Feature/ExperienceTest.php; done` and no failures.

It is weird that is failing in CI still occasionally though. Maybe the CI machine is actually just @vd1992's machine though? 😆

**Comment by vd1992** [comment]
Running just the file doesn't cause it to fail for some inexplicable reason, I got it to fail above by running all the tests

**Comment by esizer** [comment]
Guess what?

https://github.com/GCTC-NTGC/gc-digital-talent/actions/runs/10303204029/job/28518649911?pr=11175 😲

**Comment by vd1992** [comment]
Haven't seen it since that last instance, too infrequent to stress over 💤
