### ISSUE TITLE
🧪 MissingSkills Jest Test Broken

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#7515]
## 🧪 Tests

The "should ignore added skills with empty experienceSkillRecords detail field" test has broken with the upgrade to Faker V8.  I think there were some assumptions about how the random data looked that are no longer valid.  I spent some time trying to fix it in #7481 but gave up after a while.

## ✅ Acceptance Criteria

- [ ] Test reliably passes with Faker at V8.

**Comment by vd1992** [comment]
The Storybook also yields clues that something changed

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/2b5db878-e706-4aea-b7c0-a92ce11c93a6)

**Comment by petertgiles** [comment]
> The Storybook also yields clues

Ooh, that's nice!  Yeah, the first assertion that fails is "assert there are four lists" which this clearly shows.  I got past that by ensuring there were both technical and behavioural skills seeded.  The next assertion was around how many items are in each list and that's when I gave up.   :laughing:   This screenshot is great, though.  Super helpful!

**Comment by vd1992** [comment]
I suggest rewriting the relevant test and story to use more explicitly defined skills and skill families. 
The component takes random required, optional, and added skills. Which in turn have random skill families which then have randomly set skill categories (behavioural, or technical, or if two skill families might have both). 
Too much randomness makes this tricky. 
And the stories should be in sync with the Jest tests using the same input data so you can visualize it.
