### ISSUE TITLE
Test Dark Mode

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#7520]
## 🧪 Tests

This issue represents the dev effort in a sprint to review and audit the dark mode update (#5807).  It may require several devs to spend some time.

> __Note__
There will be no PR associated or merged with this issue.  Just close it when #5807 is done.

## ✅ Acceptance Criteria

- [ ] #5807 has been approved by the team

**Comment by petertgiles** [comment]
Superseded by  #4033.

**Comment by RM-1978** [comment]
## Manual Accessibility Testing Steps

- [ ] Select and document a representative sample of pages (with URLs) and features for testing.
- [ ] List pages to be tested with urls
- [ ] Document Automated tools and AT configurations (Operating System, Browser, Technology)
- [ ] Confirm the checks below with Keyboard, colour contrast checker and automated testing tools.
- [ ] Review pages using the AT chosen configuration.

## Non-Technical checks
- [ ]  Confirm that the heading structure is hierarchical.
- [ ]  Check for consistent use of white space so pages are easy to scan.
- [ ]  Review non-text elements for information or functional value, proper labelling and/or alternative text for non-text elements with value.
- [ ]  Confirm that objects with informative or functional value have meaningful alternative or ARIA labels.
- [ ]  Review colour contrast for a contrast ratio of 4:5:1 between foreground and background.
- [ ]  Review colour contrast for perceived colour contrast in addition to computed values.
- [ ]  Confirm link texts are descriptive and that their "underline" signifier is present. Alternatively, they should have a contrast ratio of 3:1.
- [ ]  Confirm that key pages do not rely solely on colour to convey meaning or instruction.

## Technical checks

- [ ]  Test for the presence of proper landmarks roles and labels (e.g., Main, Nav, aside, section , header, footer)
- [ ]  Confirm that all components/widgets have appropriate ARIA roles.
- [ ]  Review page titles and headings for descriptive titles and proper structure.
- [ ]  Review reading order and focus management (focus order, component triggers, modals, etc.).
- [ ]  Confirm that meaningful graphical elements (those with informational value) have a contrast value of 3:1.
- [ ]  Confirm that touch targets are usable (24pi x24 pi vs 48pi x 48pi range)
- [ ]  Create a page example with text size enlarged to 200% to test text resizing and reflow.
- [ ]  Test any new selectable components (toggle buttons, radio buttons, checkboxes, list boxes, text boxes, etc.) to see if it triggers an expected change in context.
- [ ]  Confirm if users have multiple ways to navigate to each page in the pattern.
- [ ]  Check French-language pages for proper default language.
- [ ]  Confirm that the platform does not require users to re-enter information they have already provided (e.g., in a previous step of the RoD process).

Plain Language confirmations
 - [ ] Confirm that the copy reflects the light mode with fidelity.
- [ ]  Check that documents are broken into separate topics using semantic headers.
- [ ]  Check that short lists and bullets are used to organize information when appropriate.
- [ ]  Flag if information on each page is presented in more than two semantic heading levels.
- [ ]  Check that page titles and copy are crafted with key words that our readers would use when doing a web search for our product.
- [ ]  Verify that readers who do not have knowledge of our platform can read related pages on the site.
- [ ]  Check that copy explains things succinctly so each page can stand on its own.
- [ ]  Check that link language should describe what your reader will get if they click the link (e.g., Never use “click here” or “ Learn more” as links).
- [ ]  Verify that unnecessary or redundant words have been eliminated.
