### ISSUE TITLE
♻️ Rework the First Nations identity interaction in the candidate DEI dialog and the Self-declaration form

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#7525]
## ♻️ Summary

As a part of the decision to not use related checkboxes for single-selection of the two options, the decision is to reverse the change and return to a single checkbox that then triggers a radio set. As a part of these changes, the interaction has been updated to provide a clearer interaction for both the DEI profile dialog and the Self-declaration component.

Resolves:
- #5388
- #7360

## 🗨️ DEI profile dialog

[View the Figma file here](https://www.figma.com/file/guHeIIh8dqFVCks310Wv0G/Style-library?type=design&node-id=288-42987&mode=design&t=zVXKevgu3VuWAP15-4) | Please contact @substrae with questions on this portion of the ticket.

```[tasklist]
### Acceptance Criteria
- [ ] The "First Nations" checkbox label now identifies status to help clarify the intent of the option
- [ ] The signature copy and input is now hidden if all 4 options are unselected
- [ ] Whitespace has been updated to help with breathing room
- [ ] Identity icons have been realigned with their respective inputs to ensure the animal's feet generally align with the bottom of the input
- [ ] Criteria met in the DEI dialog and the application self-declaration step
``` 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/f8cb3211-9f63-4e1f-a2dc-ec90c80cdbd5)

## 👤 Self-declaration component

Please contact @BrookeCameron with questions on this portion of the ticket.

**Comment by BrookeCameron** [comment]
@gobyrne we can move forward with this. @GCTC-NTGC/developers Please make the same adjustments as issue #7873 that @petertgiles completed.
