### ISSUE TITLE
♻️ Create storybook for `CreateAccountPage.tsx`

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#7528]
## ♻️ Debt

There is no storybook story for `CreateAccountPage.tsx`.

## 🙋‍♀️ Proposed Solution

Create storybook story for `CreateAccountPage.tsx` and incorporate `GovernmentInfoForm.stories.tsx` into it (and then remove `GovernmentInfoForm.stories.tsx`).

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] storybook story exists for `CreateAccountPage.tsx`
- [ ] `GovernmentInfoForm.stories.tsx` no longer exists

**Comment by vd1992** [comment]
Do we really want to remove that form's story? It is really easily to manipulate states in it as you can pass them in as props
`CreateAccountPage` takes in no props as it assumes a fresh user, therefore you cannot conveniently manipulate the page by passing in different user args. 

Trying to graft the `GovernmentInfoForm` story into the `CreateAccountPage` seems like it'd be complex, is it worthwhile to make a story that complex? 

Assuming we want to render different states, `CreateAccountPage` renders the default version of that form.
