### ISSUE TITLE
♻️ Restore the Access to Information and Privacy stream on the Talent Search page

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#7601]
> [!NOTE]  
> Blocked until the pools are considered ready.

## ♻️ Debt/Refactor

Undo #7600.

## 🕵️ Details

Once we have some candidates in an ATIP pool, we can allow that stream to be requested for talent.

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] Users can filter by Access to Information and Privacy stream when searching for talent

**Comment by mnigh** [comment]
@tristan-orourke did we ever get some candidates in an ATIP pool?

**Comment by mnigh** [comment]
> @tristan-orourke did we ever get some candidates in an ATIP pool?

@gobyrne same question, did we ever get some candidates in an ATIP pool?

**Comment by gobyrne** [comment]
@mnigh We are still waiting for them to come to us on this.

**Comment by mnigh** [comment]
Resolved in #9294.
