### ISSUE TITLE
✨Manager Request Form Updates

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/gc-digital-talent#7606]
## ✨ Feature

New form section to capture Manager talent requirements and sourcing plans.  

## 🕵️ Details

Add any additional details that could assist with the development of the new feature.

## 🎨 Design File

Include a link to the design file (if it exists).

### 🧑‍🎨 Designer

Include the author of the linked design file's name (or even better, their `@githubUsername`) for future reference.

## 📸 Screenshot

Add a screenshot of the new feature (if possible).

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Criteria 1
- [ ] Criteria 2

**Comment by mnigh** [comment]
@RM-1978 is this issue still being worked on or can it be closed as not planned?

**Comment by RM-1978** [comment]
Issue was already taken care of in another issue
