### ISSUE TITLE
🛠️ A11y Axe testing on components

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#7649]
## 🛠️ Tooling

We want to move away from testing Axe with Jest since it is slow and doesn't include Hydrogen styles.  We would like to test in a browser, like Cypress, but want to run it on components, not full pages.

## 🙋‍♀️ Proposed Solution

https://storybook.js.org/docs/react/writing-tests/accessibility-testing#automate-accessibility-tests-with-test-runner ?

## ✅ Acceptance Criteria

- [ ] Can add tests for components/stories
- [ ] Migrate Axe tests away from Jest

**Comment by esizer** [comment]
I believe this could be either re-scoped or closed in favour of #7670
