### ISSUE TITLE
♻️ Remove deprecated `applicants` query

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#7652]
## ♻️ Debt/Refactor

This query is deprecated.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/11cb180ed2735083c63e73122008cf6c5c1d27bd/api/graphql/schema.graphql#L675-L681
## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] `applicants` query removed from schema file
- [ ] References to this query have been removed or replaced

**Comment by petertgiles** [comment]
Currently in use.  Should go out of use when we switch to async batch extracts.

**Comment by esizer** [comment]
Unblocked once #11199 is merged. I'm pretty sure we are removing the [only usage of this query](https://github.com/GCTC-NTGC/gc-digital-talent/pull/11199/files#diff-09bb7763b3c32e49b84409a6734fb40598baa56d603a51a6ca2f2f09f40c1e1aL170) in that PR.
