### ISSUE TITLE
♻️ Remove deprecated `poolCandidates` query

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#7656]
## ♻️ Debt/Refactor

This query is deprecated.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/8762bf97614beefcdc90507504caa78a6eab9b18/api/graphql/schema.graphql#L701-L707

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] `poolCandidates` query removed from schema file
- [ ] References to this query have been removed or replaced

**Comment by petertgiles** [comment]
Currently in use.  Should go out of use when we switch to async batch extracts.

**Comment by esizer** [comment]
This is unblocked now, we removed last usage when migrating downloads to the server.
