### ISSUE TITLE
♻️ Remove deprecated `users` query

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#7660]
## ♻️ Debt/Refactor

This query is deprecated.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/4a0f4626d258886c3d8ea7ec85adb413d24473ec/api/graphql/schema.graphql#L685-L692

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] `users` query removed from schema file
- [ ] References to this query have been removed or replaced

**Comment by vd1992** [comment]
Is used in below operation, and will need a replacement decided first. Which will come about when the role permission adding ability no longer fetches all users. 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/e1d017a9-298e-4952-9b10-9a232ee49b15)

**Comment by mnigh** [comment]
> Is used in below operation, and will need a replacement decided first. Which will come about when the role permission adding ability no longer fetches all users.
> 
> Issue #8243
> 
> ![image](https://private-user-images.githubusercontent.com/40485260/278479363-e1d017a9-298e-4952-9b10-9a232ee49b15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNjc4MTQsIm5iZiI6MTcwNzE2NzUxNCwicGF0aCI6Ii80MDQ4NTI2MC8yNzg0NzkzNjMtZTFkMDE3YTktMjk4ZS00OTUyLTliMTAtOWEyMzJlZTQ5YjE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDIxMTE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0YmRjNDJmYmEwODk2ZTU3ZWU1OTJmNWVmM2ZiMTI5NDQzOWE3YjVlNWY4OWQxNTZmNmE4M2YzMjE5N2ZkOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LfovOxZcwiqAnqdRplBO-ogrtbGr80VWA3Yt4rBjIR8)

@vd1992 Was there ever a replacement decided upon?

**Comment by vd1992** [comment]
Could potentially leverage the query to be added in https://github.com/GCTC-NTGC/gc-digital-talent/issues/9064?

**Comment by mnigh** [comment]
> Could potentially leverage the query to be added in #9064?

@GCTC-NTGC/developers are we able to work on this or are we still blocked?

**Comment by esizer** [comment]
> are we able to work on this or are we still blocked?

I only see it left in two places, both are defined but not used.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/4a0f4626d258886c3d8ea7ec85adb413d24473ec/apps/web/src/pages/Users/userOperations.graphql#L1-L12

https://github.com/GCTC-NTGC/gc-digital-talent/blob/4a0f4626d258886c3d8ea7ec85adb413d24473ec/apps/web/src/pages/Teams/teamsOperations.graphql#L137-L160

I deleted both and the app still built and functioned as expected. Seems like it should be safe to remove it 👍
