### ISSUE TITLE
✨ Add "Personal and contact information" section in printed profiles

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#7668]
## ✨ Feature

Replace the "Status" section currently on the printed profile for the entire "Personal and contact information" section from the new profile designs.

## 🕵️ Details

Add any additional details that could assist with the development of the new feature.

## 🎨 Design File

Include a link to the design file (if it exists).

### 🧑‍🎨 Designer

Include the author of the linked design file's name (or even better, their `@githubUsername`) for future reference.

### Currently:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/65c119a2-5145-4972-9ffd-3c111e1dbacc)

### Add this section to the printed profile
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/2298f7a1-9613-4cd4-a904-0045aab03f77)

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Criteria 1
- [ ] Criteria 2

**Comment by vd1992** [comment]
Already addressed
