### ISSUE TITLE
🏈 a11y Axe testing on components

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#7670]
## ✍️ Details

We want to move away from Axe testing with Jest since it is slow and doesn't include Hydrogen styles. We would like to test in a browser, like Playwright, but want to run it on components, not full pages. 

This way, we will catch more WCAG conformance issues and accessibility/ usability issues 

REF: https://playwright.dev/docs/accessibility-testing

## ✅ Acceptance Criteria

- [ ] provide answer for how we can migrate Axe tests away from Jest

**Comment by vd1992** [comment]
time 1 day

**Comment by esizer** [comment]
We have been looking at Evinced to add to our tooling. They offer a [Cypress JS SDK](https://developer.evinced.com/sdks-for-web-apps/cypress-sdk) we could use with cypress. If we do not, I think just using [cypress-axe](https://www.npmjs.com/package/cypress-axe) would work for this.

**Comment by gobyrne** [comment]
@esizer does introducing Playwright change this at all?

**Comment by esizer** [comment]
> @esizer does introducing Playwright change this at all?

Good catch, it will affect this. Thankfully Playwright has [a good guide](https://playwright.dev/docs/accessibility-testing) on how to do this. I'll keep this on my radar and update scope once the team decides if we want to commit to the migration 👍
