### ISSUE TITLE
Pause "Selected" queries for tables unless at least one row selected.

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#7681]
# Description

Our tables which have selectable rows issue a request to the API even before a single row is selected.  This query should probably be paused until a row is selected.

# Context

              This probably has nothing to do with your PR and you can ignore it.  :laughing:  It makes me crazy that this table makes a search request when there is nothing selected.
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/6beca9a5-d199-441d-a735-5cf28c6ab26c)

_Originally posted by @petertgiles in https://github.com/GCTC-NTGC/gc-digital-talent/pull/7588#discussion_r1302122700_
            
# Acceptance Criteria
- [ ] Tables with selectable rows do not issue a "selected items" query until at least one row is selected.

**Comment by vd1992** [comment]
@esizer 
Was this resolved with https://github.com/GCTC-NTGC/gc-digital-talent/pull/7588#discussion_r1302167040 ?

**Comment by esizer** [comment]
> Was this resolved with [#7588 (comment)](https://github.com/GCTC-NTGC/gc-digital-talent/pull/7588#discussion_r1302167040) ?

Technically no, but we could just do this when we re-implement the tables 🤷‍♀️
