### ISSUE TITLE
♻️ Replace ClientManagedTables on /admin with new Table component

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#7691]
## ♻️ Debt/Refactor

We have a better table component to use now.

## 🕵️ Details

Client-driven tables should be relatively easy to replace with the new table component. Do so for all existing tables!

We can also uninstall react-table, a dependency used for ClientManagedTable.

## ✅ Acceptance Criteria

- [ ] existing client-driven tables replaced with new Table component
- [ ] old ClientManagedTable removed from codebase
- [ ] uninstall react-table@7.8.0 
- [ ] apps/web/src/types/react-table-config.d.ts can also be removed

**Comment by vd1992** [comment]
Keep an eye on pagination and watch for bugs
