### ISSUE TITLE
✨ Allow Admins to delete Skill Families and archive Skills

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#7698]
## ✨ Feature

UI to delete Skill Families and archive (soft-delete) Skills.

## 🕵️ Details

We're adding a small section below the Submit button on the Edit Skill page and Edit Skill Family page. The section will consist of a section title, a descriptive sentence, and a button. The buttons will open a modal with additional text, where you trigger the delete/archive mutation or cancel. On a successful mutation, user is sent to the table page.

This is based on the Archive Pool UI.

## 🎨 Design File

Look here to see how the Archive Pool modal looks: https://www.chromatic.com/component?appId=61e099a1bb1465003a73d3ce&csfId=forms-edit-pool-form--expired-pool&buildNumber=5531&k=64e6819e5ade094f68c1f2a7-1200px-interactive-true&h=14&b=-3

We don't have full figma designs. Feel free to ask @Jerryescandon if you need more details.

Add this to the bottom of the Edit Skill page, though with slightly different text: "This will prevent this skill from appearing in most places on the platform."
![image (8)](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/e509f7ba-64ac-486c-b3ae-eb4665aaa6fe)

The archive button opens a modal. (Get text from the Localization section below.)
@Jerryescandon can we get a figma modal design which matches the Archive Pool modal?

The additions to the Edit Skill family page should look the same, though use different text

### 🧑‍🎨 Designer

@Jerryescandon 

## 📸 Screenshot

See above

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization
Strings for Archive skill:

| String | English | French |
| -- | -- | -- |
| title/button | Archive skill | ??? |
| short description | This will prevent this skill from appearing in most places on the platform. | ??? |
| longer description | You're about to archive this skill: **{Skill name}** An archived skill will not appear as an option when adding skills to a job poster, when adding skill to an applicant profile, or when filtering by skills on the talent search page or on admin tables. If they have already added the skill, archived skills will continue to be visible as part of an applicant's profile or application snapshot. | ??? |

Strings for Delete skill family:

| String | English | French |
| -- | -- | -- |
| title/button | Delete skill family | ??? |
| short description | This will **delete this skill family from the platform**. | ??? |
| longer description | You're about to delete this skill family: **{Skill name}** This cannot be undone. | ??? |

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Platform admins can delete skill families.
- [ ] Platform admins can archive skills.

**Comment by tristan-orourke** [comment]
@mnigh Could copy-caucus review my proposed copy here?

**Comment by mnigh** [comment]
@Jerryescandon is this issue still being worked on or can it be closed as not planned?
