### ISSUE TITLE
📝 Copy changes to the search page

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/gc-digital-talent#7718]
## 📄 Copy Requirements
Talent seekers (manager users) need to get the correct information from the copy on the search page.

## Details
The text at the top of the search page needs to be update as follows:

### H1 new text 
> **Find digital talent**

### Top centered div new text
> **Are you looking to hire digital talent?**
> If you are looking for talent, you have found the right place. Our talent database is open to most departments and agencies. Complete a request to find qualified candidates. Candidates are assessed for their skills and grouped into pools to meet your staffing needs.

### How to use this tool section new text

> **How to use this tool**
> Use the filters to specify your requirements. We will show you an estimated number of candidates who match your criteria as you enter your information. Select **Request candidates** when you are done. Doing so will bring you to a form where you can provide your contact information and submit your request.

## Screenshot
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb09KIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--9ca233e401ffb1e5cdf14db653be92c75ba67750/image.png)

## ✅ Acceptance Criteria

Set of assumptions verifying that the issue was addressed when tested.

- [ ] H1 updated
- [ ] Centered div at top of page updated
- [ ] How to use this tool section updated
- [ ] Equivalent French updates are made
- [ ] Design review before merge (Inc French copy) @RM-1978  
- [ ] Change shared copy on request page too

**Comment by RM-1978** [comment]
[Talent Search Page for Managers.docx](https://github.com/GCTC-NTGC/gc-digital-talent/files/12433633/Talent.Search.Page.for.Managers.docx)

**Comment by vd1992** [comment]
Do we need to change the indicated header on the request page too as it is the same as changing copy on the search page? 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/18694186-35eb-44b4-a05b-d6001269d6c4)
