### ISSUE TITLE
✨ Improvements to printed profile - including contact info

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#7738]
## Description
This issue addresses comments from the recruitment team about the printed profiles:
- Adding the full contact information into the profile

## 🕵️ Details

1. Add a new section "Contact information" at the top of the printed profile (just below users name) with Email, Phone, Current City, Province and all 3 language fields from the Personal and contact information section of the new profile.

![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/907d4f23-72db-4ea4-8e65-d9b134acca3d)

2. Rename the download link to "Print profile"

3. Add another download link (beside the existing one) with text "Print profile (anonymized)"

### 4. Update printed profile with contact info

Add contact info to current printed profile sections  so we can have a complete profile when downloading

### 5. New partial profile download option

To-do list for new anonymized variation of the printed profile:
- The name of the user should only be displayed as [First name] [first letter of Last Name]
- Remove the contact information section so the profile can not be identified easily
- Update the button in the "Admin - User profile" page to include new download variant (single download)
- Update the buttons at the bottom of any candidate table to include new download variant (batch download)

#### SCREENSHOTS 

<details><summary>Download interaction on Admin - User profile</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/be48025d-1a24-42ac-8dfd-9734fa607011)

</p>
</details> 

<details><summary>Download interaction on Admin - Pools - Manage candidates</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/83e3b2f5-2e10-4bbc-bb4d-700d2d186e1e)

</p>
</details> 

[Link to figma file for profile update](https://www.figma.com/file/gqC6F2F1WbBxZMsFCiOkF0/Admin---User-Profile?type=design&node-id=401%3A3593&mode=design&t=tBSdmgpdfFgJOcdX-1)

[Link to figma for table update](https://www.figma.com/file/zUSn85QtLHbhtjlBhdfT6C/Pools---Record-of-Decision-(Copy)?type=design&node-id=5115%3A12979&mode=design&t=E6NHuPeg7RXL2FZL-1)

## 🎨 Design File

https://docs.google.com/document/d/13epIYbnfFdYc-T1_d8SqCKhaJcAVJEXDYkhGBmzLLdA/edit#heading=h.picugz4qrg9l

### 🧑‍🎨 Designer

@Jerryescandon 

## ✅ Acceptance Criteria

- [ ] Add new download link and rename old one
- [ ] Add new section "Contact information"

**Comment by brindasasi** [comment]
This branch has a dropdown of option which is not mentioned in the original story. 
![Screenshot 2023-08-29 at 10 38 07 PM](https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/8db7d1c7-1472-42c5-90f6-8c4b426d719d)
Probably there was some discussion between dev & designers which is not recorded in this issue. 
@Jerryescandon could you update the A/C , so I know what this story is expected to deliver?

**Comment by petertgiles** [comment]
@brindasasi Yes, we discussed during planning and estimation.  The addition of second link is represented by detail point 3 (Add another download link) and AC point 1 (Add new download link and rename old one).  The exact design of the second link was not specified by the designer and so was left up to the dev.  It looks like Matt was working on a dropdown menu but you could work on a different link placement or request that Jerbo provides you with a detailed design for the link.

**Comment by brindasasi** [comment]
@petertgiles thanks for the clarification . Working with Jerbo on this atm
