### ISSUE TITLE
🐛 Any 401 tells the user the account was deleted

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#7763]
## 🐛 Bug

We recently added the ability to delete user accounts.  If a user with a deleted account attempts to log in then they get a message that their account was deleted.  Unfortunately, if another API error results in a 401 it also displays the "account deleted" message even if the account was not deleted.

## 🦋 Expected Behaviour

The user should only get the "account deleted" message if their account was actually deleted.  For other 401 errors they should probably get a generic "Something went wrong, please contact support" error.

## 📋 Steps to Reproduce

1. Intentionally break the introspection query:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/e6d90876-892e-4a7c-89c2-896c40b21166)

2. Try to log into the site.

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/85ad2ef8-e543-4ca1-8b8b-93162f1ee81c)

## ✅ Acceptance Criteria

- [ ] If the account is actually deleted, show the "account deleted" page
- [ ] For other 401's a generic error message is displayed

**Comment by petertgiles** [comment]
I need to test if this is still a problem.  Eric reworked the "user deleted" functionality to not return 401s.

**Comment by vd1992** [comment]
Still appears to happen, infrequently, unsure of how to replicate yet

**Comment by vd1992** [comment]
I got a way of seemingly reliably replicating it without breaking things in a complicated way

- Log in as admin, navigate to `/en/admin/dashboard`
- idle, do not click anything, for maybe 12 minutes
- type into address bar `http://localhost:8000/en/` to navigate to talent side

https://recordit.co/57ePrpKJcD

**Comment by petertgiles** [comment]
I'm no longer able to replicate this either by breaking the introspection query (like the original issue writeup) or by manually mangling the stored token.  I wasn't able to replicate Vachan's method either.  :shrug:

**Comment by tristan-orourke** [comment]
Note: you can change `tokenExpriy` field in `mock-oauth2-server.json` to speed up testing

**Comment by petertgiles** [comment]
Closing in preference for #7924.
