### ISSUE TITLE
🐛 Combobox cannot initialize with a default value

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#7770]
## 🐛 Bug

When the Combobox component is in a form with default values (like an edit form) it does not display anything.  Apologies in advance if I just don't know how to do it properly.  :sweat_smile: 

## 📋 Steps to Reproduce

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/dd057881-9ffd-4d67-af41-3f3804352ea0)

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/6e5d2bb4-4328-4653-8670-afe0ba8df63a)

## ✅ Acceptance Criteria

- [ ] The component should show the default value when the form is initialized with one.

**Comment by esizer** [comment]
This is a bug for sure. I should have this fixed as part of #7393 👍
