### ISSUE TITLE
Add filter to request table - Employee of Government of canada

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#7816]
## ✨ Feature

As a Request Responder, I want to filter candidates by "Government Employee" so I can more easily fulfill requests from managers that only want to see internal candidates.

## 🕵️ Details

Add a "Government Employee" filter to the Candidate Results table (on Request page).

The "Government Employee" filter exists on our Users table, but is not currently on the Candidate Results table.

### 🧑‍🎨 Designer

Gray created this issue, but I'll ask Josh to review.

@substrae - This seems fine as is. Slot the filter in the same place for consistency, but otherwise the styles will reuse existing components.

## 📸 Screenshot

This is what the "Government employee" filter looks like on the USERS table.

![Image](https://user-images.githubusercontent.com/2494551/265743659-3ca8abbf-a140-4284-9c4c-6898691b3525.png)

## 🙋‍♀️ Proposed Implementation

Implement in a similar way to the users table, but on the Request table!

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] "Government employee" filter added to Candidate Results table

**Comment by vd1992** [comment]
Implementation wise it would be adding it to the `PoolCandidate` filter system, so 
adding a scope to the pool candidate model, updating schema, and then the frontend filter connection.
This would then also appear on all instances of view pool candidates. 

As an aside, is there an upper limit before the (pool candidate) Fancy Filter becomes overwhelming to look at?

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/be9ff85e-fe7a-46d7-a80e-af860033188e)
