### ISSUE TITLE
🐛 Soft-deleted experiences appear on Career Timeline page

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#7828]
## 🐛 Bug

Soft-deleted experiences are showing up on Career Timeline list.

## 🦋 Expected Behaviour

They should not!

## 🕵️ Details

Reported by @esizer

Caused by User->experience relationships including `withTrashed` scope. This was added as part of https://github.com/GCTC-NTGC/gc-digital-talent/pull/7593, but seems to have been left in from an earlier version of the work as an oversight.

## 📋 Steps to Reproduce

1. ...
2. ...

## 📸 Screenshot

Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

Remove `withTrashed` from user->experience relationships.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] If you delete an experience, it no longer appears on your career timeline
- [ ] If an admin (soft-)deletes a User, then someone goes to view their profile anyway, they should see their experiences.

**Comment by vd1992** [comment]
So far, deleting an experience makes it inaccessible from your timeline

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/1ea15478-f8d7-4725-8cff-3f3751fa1dc0)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/407aac58-7360-4d6c-94b7-09dfb1afba26)

Navigating directly to a deleted experience yields a null-ed page

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/004fc812-435d-4563-85bc-166db9ef06ae)

applications submit successfully, and the snapshot does not contain the deleted experience

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/b8ed49ee-eee4-419d-9237-4f3540d222f2)
