### ISSUE TITLE
✨ Separate index.html page for IAP and GCDT homepages

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#7840]
## ✨ Feature

For performance reasons it would be good to have separate index.html pages for the IAP and GCDT homepages.  This would allow the browser to start downloading static assets like images before the javascript application has downloaded and booted.  You would update the Nginx config to only serve up these custom index.html files when the exact URL of the homepages is requested.

## ✅ Acceptance Criteria

- [ ] When the exact URLs of the IAP and GCDT homepages is requested the server delivers an index.html file with the images set to preload
- [ ] Set up is manageable for easily adding more static pages when needed

**Comment by petertgiles** [comment]
Unfortunately, it seems like preloading the largest image on the homepages worsens the performance.  On both pages the lighthouse score actually drops.  When the biggest image is preloaded with the "Fast 3G" throttling the DOMContentLoaded and Load events are slower by about 24%.  It seems like when the image is preloaded it slows down the simultaneous download of the JS bundle and delays all the rest of the assets that the bundle requests.  The final Finish event is only about 0.5% faster for the IAP homepage and about 8% slower for the GC Talent homepage.

I'd recommend focusing our efforts on prerendering the entire page so that the page can be rendered and showing content before the JS bundle has to get downloaded and executed.  One small improvement might be to deprioritize the Google font download.  It seems like this usually goes before the JS bundle which slightly slows down the entire page load.

**Comment by petertgiles** [comment]
I recommend closing this as not planned unless anyone else has any ideas to try.

**Comment by petertgiles** [comment]
> Better to focus on initial bundle and image sizes.

Initial bundle:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/c8bc332b-3a37-49c7-8150-92f267afca1d)
I'm still grumbling about the size of Microsoft Application Insights, especially since we can't move it out of the initial bundle.  Framer motion is really big - that might be a good candidate for lazy loading if we take it off the IAP homepage load.

Top images:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/44e3d7a3-2fbd-4216-81e6-8b71bd718492)
A couple of good ones to reduce, like the gloves.

**Comment by esizer** [comment]
> I'm still grumbling about the size of Microsoft Application Insights, especially since we can't move it out of the initial bundle. Framer motion is really big - that might be a good candidate for lazy loading if we take it off the IAP homepage load.

I actually added `framer-motion` for some animation but knowing the size, id suggest migrating to `react-spring`. 

But, as a first step, we could look at [reducing the bundle size](https://www.framer.com/motion/guide-reduce-bundle-size/).

 - https://bundlephobia.com/package/react-spring@9.7.3
 - https://bundlephobia.com/package/framer-motion@10.16.4

**Comment by vd1992** [comment]
Well, maybe let us spin off an issue for Framer-Motion and get some sort of win out of this

**Comment by petertgiles** [comment]
> Well, maybe let us spin off an issue for Framer-Motion and get some sort of win out of this

https://github.com/GCTC-NTGC/gc-digital-talent/issues/8404
