### ISSUE TITLE
✨ Statically generated logout page

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#7867]
## ✨ Feature

We currently have one completely static page - the secure network page.  It would be good to have the logout page static as well.  This would allow the page to quickly come up to inform the user without fully rebooting the application and trying to establish a new auth context.

## 🕵️ Details

We would still want the page to match the look-and-feel of the main site so it would be good for it to use the same CSS and components and header/footer.  Some sort of static generation tool like Astro or 11ty could be used?  Could we integrate this without blowing up the complexity of our app?  Could we eventually use this same approach for other static pages like the IAP home page?

Right now our logout page does have two bits of functionality - the language redirect and the clearing the stored tokens.  Could we still make this happen on a static page?

## ✅ Acceptance Criteria

- [ ] Logout page statically generated
- [ ] Logout page still localized in EN and FR and clears stored tokens

**Comment by tristan-orourke** [comment]
This has nice Acceptance Criteria but incredibly nebulous Proposed Implementation 😆 . But I still like the suggestion. @petertgiles do you have a more concrete idea on implementation at this point?

**Comment by petertgiles** [comment]
> This has nice Acceptance Criteria but incredibly nebulous Proposed Implementation 😆 . But I still like the suggestion. @petertgiles do you have a more concrete idea on implementation at this point?

This came out of early SSG/SSR discussions.  It would be a way to dip our toes into SSG with what I think would be the highest value page but would basically be a spike.  It would be up to the implementer  to try out Astro, 11ty, or whatever else they wanted.

That said, it seems like we are moving towards SSR instead of SSG so maybe we're not interested in this anymore.
