### ISSUE TITLE
✨ Add relationships from skill to pool to schema

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#7868]
## ✨ Feature

In #7680 a pair of relationships from Skill to Pool was fixed.  This relationship does not yet exist in the schema and so let's add it.

## ✅ Acceptance Criteria

- [ ] The skill relationships `poolsEssentialSkills` and `poolsNonessentialSkills` are added to the schema
- [ ] The "authorized to view" scope guards them

**Comment by esizer** [comment]
I believe we have since deprecated these types of relationships in favour of `Pool.skills.type`. Is that correct and if so does that mean this can be closed as not planned?

**Comment by vd1992** [comment]
Yes, deprecated in favour of `pool.poolSkill`
Will make sure an issue exists for it
