### ISSUE TITLE
🐛 Incomplete experience-skills block applying without error message

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#7872]
## 🐛 Bug

If user has any experience-skills without details, they fail validation on the Skills step of the Application. However, the error message is the same as if you are missing skills entirely, making it very confusing for the user.

## 🦋 Expected Behaviour

Show a better error message?

## 🕵️ Details

Currently, any forms where you can add skills to experiences require details before submitting, so most users should not encounter this situation. However, I know that previously we had users add the skill without details, so there may be users out there with existing experience-skills which would trigger this. Also, our API allows for adding Experience-Skills without details, so this could be a problem in the future.

## 📋 Steps to Reproduce

1. Log in as an applicant
2. Apply to a job. Continue the application as far as Skill Requirements step
3. Add skills to all the experiences
4. Replace the details for one of those experience-skills with `null`. This can be done via `/graphiql` or by directly editing the database.
5. Reload the page
6. Try to submit and continue
7. See the unhelpful error message

## 📸 Screenshot

Misleading error message:

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/91fd753f-89b4-4327-977e-b465c9710bcf)

## 🙋‍♀️ Proposed Solution

I think we just need to give a different error message for missing details compared to missing skills. Or possibly update the current message to cover both situations: "Please connect at least one career timeline experience to each required technical skill **and ensure each skill has details about how you used it."**

Preference is to use different error messages for different cases.  If that proves too difficult, fallback to simple solution of single longer error message.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] If application fails validation because a user-skill is missing `details`, user is shown a helpful error message

**Comment by petertgiles** [comment]
Since this is not a regular form we can't use regular form validation.  We might need custom logic to scroll to the right tree item and change the colour.

**Comment by vd1992** [comment]
Done in #8026
