### ISSUE TITLE
🐛 Storybook/Chromatic missing Hydrogen's font-size element application

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#7877]
## 🐛 Bug

Generally, the font sizes all seem weird in the Chromatic snapshot (everything is base `16px` instead of `18px`); I assume this is because it's missing Hydrogen's `html` font-size element application.  Maybe we can look into getting this into storybook? Seems like it would be important for reviews.

Reference first point in:
https://github.com/GCTC-NTGC/gc-digital-talent/issues/7752#issuecomment-1710190388

## 📸 Screenshot

  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/2ef0c396-56bc-42e7-8f78-b430b2287670" />

## ✅ Acceptance Criteria

- [ ] Storybook using Hydrogen's font-size element application

**Comment by esizer** [comment]
Is this still an issue? It looks to be 18px to me in all three:

- localhost
- storybook
- chromatic

![Screenshot 2023-10-31 083021](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/de11a81a-7f9a-43c9-993f-6a12330484cf)
![Screenshot 2023-10-31 083258](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/941e1559-e6b6-4008-949a-8aa6db880d4d)
![Screenshot 2023-10-31 083315](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/1a3e300d-bf04-48bc-a09c-10d9dac4cf25)

**Comment by petertgiles** [comment]
Hmm, I wonder if the original issue was just that the base font size changes between wide and narrow viewports?
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/3ad1fb44-a895-4d33-9a61-0db42ab7667e)
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/4122b513-0947-4d29-82a1-9bd7f3bfff17)
@substrae could you please double-check?

**Comment by esizer** [comment]
> Hmm, I wonder if the original issue was just that the base font size changes between wide and narrow viewports?

Yeah, I noticed that the sidebar in storybook creates a weird viewport that doesn't take much reducing to flip to a lower viewport (`laptop =< 1600px`) which causes the font size to drop to `16px`

![Screenshot 2023-10-31 091648](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/bef85791-5b12-4812-b2f0-6aaf7d05823c)

**Comment by substrae** [comment]
@esizer @petertgiles 

Oh, look at that. I didn't realize the viewport was artificially reduced.
