### ISSUE TITLE
✨ Hide ongoing recruitment if there are no jobs 

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#7884]
## ✨ Feature

The ongoing recruitment section of the "browse jobs" page does not handle itself gracefully when it is empty. We should hide it if there are no live ongoing recruitment jobs.

## 🕵️ Details

Hide the ongoing recruitment section of the "browse jobs" page there are no live ongoing recruitments.

In the scenario where the ongoing recruitment section is hidden: users should see the "Active talent recruitment processes", then any jobs that are live (OR the "No opportunities are available...") without the "Apply to ongoing recruitment" section showing up at all.

## 📸 Screenshot

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdlNRIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--29cbe64648ce44dce58e772dff144a7f84ed9d64/image.png)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Apply to ongoing recruitment section of "Browse jobs" page hides when there are no ongoing recruitment jobs live

**Comment by vd1992** [comment]
Suggestion for implementation
Make component conditionally rendered based off length of array `ongoingRecruitmentPools`

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/e2758019-480e-4502-8dae-b31792c0fedc)
