### ISSUE TITLE
♻️ Try Auth Bump Again

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#7887]
## ♻️ Debt/Refactor

We found an issue with the auth bump branch during deployment and had to quickly roll it back.  Let's try to bump these dependencies again.

## 🕵️ Details

Original PR: https://github.com/GCTC-NTGC/gc-digital-talent/issues/6547
PR Revert: https://github.com/GCTC-NTGC/gc-digital-talent/issues/7886

## ✅ Acceptance Criteria

- [ ] urql bumped back to version 4
- [ ] prod builds authenticate properly

**Comment by vd1992** [comment]
Potential clues for getting to the root of it

https://github.com/GCTC-NTGC/gc-digital-talent/issues/7885#issuecomment-1716746351
