### ISSUE TITLE
✨ BasicForm error summary does not support field array validation

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#7888]
## ✨ Feature

The BasicForm error summaries do not support validation on the field arrays themselves.  For example, required or minLength.  The validation prevents form submission but no error.

https://react-hook-form.com/docs/usefieldarray

## Proposed implementation

It's a bit tricky because we usually use the Repeater component in field arrays but not always.  Hopefully we will get a good design for errors with the Repeater update in  https://github.com/GCTC-NTGC/gc-digital-talent/issues/7928.  For other uses of the field array we should have a minimal frame or fieldset component to contain the array component children that can be used to scroll to the right spot and attach an error message.

## ✅ Acceptance Criteria

- [ ] BasicForm displays field array validation errors in error summary
- [ ] Clicking the name of the field array scrolls to the correct form section 
Impossible to set focus since it isn't a specific field element?

**Comment by vd1992** [comment]
Discussion to continue per scrum

**Comment by petertgiles** [comment]
Submitting to Insight Tracker for design help.

**Comment by petertgiles** [comment]
Yes and no.  Originally #7813 was about errors in form.fieldArray.field and this one is about errors in form.fieldArray but I think you knocked out both in #7888.  If so, go ahead and close this one.

**Comment by petertgiles** [comment]
Awesome, yeah!

**Comment by esizer** [comment]
Fixed in https://github.com/GCTC-NTGC/gc-digital-talent/pull/8301
