### ISSUE TITLE
✨ Finalize Assessment Plan Page

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#7916]
## ✨ Feature

The assessment plan builder is the first step in the Record of decision (RoD) flow. It allows us to capture the list of assessments to be used during the staffing process, the order in which they will be performed, and the skills that each assessment will be targeting.

It features a repeater component with dialogs for details, and a table to overview how the skills and assessments are related to each other.

## 🕵️ Details

Add any additional details that could assist with the development of the new feature.

1. The title includes a chip/label to show the plan's current state
2. The plan is complete when ALL skills have been attached to at least one assessment
3. If a skill is missing an assessment, a waning will be displayed at the top
4. The list always include "Application screening" locked in the number one spot
5. IF "screening questions (at the time of application)" is selected, then:
     - It will always be listed on the second spot
     - the dialog does not offer optional fields for a different assessment title
     - the dialog changes to include a repeater (limit 6) to add the screening questions in english or french
6. IF the repeater has 4 or more assessments, a warning message will show underneath it
7. IF the repeater has only the application, display a warning for... too few assessments.
8. IF an assessment has no skills a warning will be displayed inside the repeater item (where skills would usually go)
9. There is a table at the end of the page that shows the information captured on the repeater but it is not editable

## 🎨 Design File and Designer

[Link to figma file](https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Pools---Record-of-Decision?type=design&node-id=5437%3A34317&mode=design&t=11Dob6JX6BOb3lle-1) by @Jerryescandon 

## 📸 Screenshots

<details><summary> Full page screenshot</summary>
<p>

![Frame 40](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/0d5074fa-23fa-4f26-b8f8-5397336b9188)

</p>
</details> 

<details><summary>Dialog (regular)</summary>
<p>

![Assessment details - Repeater dialog 01](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/97e12440-41a1-42f0-9bd2-f2e41f1214c9)

</p>
</details> 
<details><summary>Dialog (with screening questions) </summary>
<p>

![Assessment details - Repeater dialog](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/133e0f09-fe19-45e1-bf15-efaf7b885e7b)

</p>
</details> 

## ✅ Acceptance Criteria

- [ ] Add accordions if copy is available
- [ ] Add card repeaters to "organize" section
- [ ] Wire up dialogs
- [ ] Add skill summary table
- [ ] Review with Jerbo
- [ ] "Save plan and go back" saves fieldset changes (reorder, delete)

**Comment by vd1992** [comment]
spin off issue (TODO)

- create backend model (and relations?)

**Comment by tristan-orourke** [comment]
@Jerryescandon can the screening questions in the dialog also use our usual repeater, where you can reorder items and delete any of them, instead of just "Remove last question"

**Comment by Jerryescandon** [comment]
> Hey @Jerryescandon, would you be okay if those Skill chips are initially implemented as a normal checklist?

Yeah no problem 👍, updated the figma and screenshots

**Comment by petertgiles** [comment]
Regarding IF the repeater has only the application, display a warning for... too few assessments.

**Comment by Jerryescandon** [comment]
I think we talked about these but lemme write em out anyway.

> So at least one additional assessment beyond the application is mandatory?
Incorrect, the "1. Application screening" could be the bare minimum without any other assessment. The rule should only validate that ALL skills have at least one assessment. (Theoretically speaking, if no behavioral skills were selected, then the assessment plan would be complete using only the initial application)

> The application step is automatically calculated by the application and is not editable? Behavioural skills are automatically set as n/a?
Correct. "1. Application screening" is set for default as the first assessment, cannot be removed, edited, or changed in order. And it only includes technical skills. NO behavioral skills should be included.

> Is there copy for the three collapsibles?
Yes, I will add it in the issue details.

**Comment by petertgiles** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/7916?planning-poker) with Zenhub @brindasasi @esizer @JamesHuf @mnigh @tristan-orourke @vd1992 @yonikid15

**Comment by tristan-orourke** [comment]
@petertgiles did I understand correctly in standup that assessment step order numbering is an issue when adding Screening Questions after other steps?

What if we reserved number 2 for screening questions. Other steps would start at 3, whether we have screening questions or not. We only use the number for sorting, right? So there's no problem with there being a discontinuity, I think?
