### ISSUE TITLE
✨ Update pool publishing validation

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#7920]
## ✨ Feature

Update pool publishing validation to account for the assessment plan

## 🕵️ Details

The assessment plan has its own validation in the frontend.  If the assessment plan is incomplete that should prevent publishing in the backend as well.

## 🙋‍♀️ Proposed Implementation

At a minimum update `PublishPoolValidator.php` with a status check 

## :question: Questions
Q: Do we want to tie this to a feature flag?
A: Yes, the assessment plan login should not activate if the RoD flag is false.

## ✅ Acceptance Criteria

- [ ] update validator
- [ ] uses the same logic as the frontend (fail if thereAreUnassessedPoolSkills or thereAreAssessmentStepsWithNoSkills)
- [ ] tied to RoD feature flag

**Comment by tristan-orourke** [comment]
Blocked because we're not sure we actually want to do https://github.com/GCTC-NTGC/gc-digital-talent/issues/7918

**Comment by petertgiles** [comment]
I've reworked this for RoD.
