### ISSUE TITLE
✨ Assessment plan backend work

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#7922]
## ✨ Feature

The backend work to enable #7916

Only AssessmentStep is in scope for this issue.  AssessmentResult will be developed later.

## 🕵️ Details

Create the assessment model/table and needed relations
Fields: assessment type, optional name JSONB localized
Relations: process/pool it belongs to, many-to-many with skills 
Policy, pool operator only? 

Create/Update/Delete operations for assessments

Added to pool type in schema allowing querying of all assessments on a process

## 🎨 Design 

suggested data model:

```mermaid
classDiagram

class Pool { }

class AssessmentStep {
    Int sortOrder
    AssessmentType type
    LocalizedString title
}

class ScreeningQuestion {
    Int sortOrder
}

class ScreeningQuestionResponse {
    String answer
}

class PoolCandidate

class pool_skill {
    PoolSkillType type (essential)
}


Pool "1" o-- "0..*" AssessmentStep
Pool "1" o-- "0..*" ScreeningQuestion
ScreeningQuestion "1" -- "0..*" ScreeningQuestionResponse
PoolCandidate "1" o-- "0..*" ScreeningQuestionResponse
Pool "1" o-- "0..*" PoolCandidate
Pool "0..*" o-- "0..*" pool_skill
AssessmentStep "1" o-- "0..*" pool_skill
pool_skill "0..*" o-- "1" Skill
```

### 🧑‍🎨 Designer

@Jerryescandon 

## :question: Questions
- Should we add records for "application screening" and "screening questions" to the database or just leave them implied?

Answer: Yes, real records in database.  Step 1 should be created when draft pool is created.  Association with skills will need to dynamically change.  Screening question step should by dynamically added/removed when moving between 0 and 1 screening questions.  Perhaps use Laravel listeners.

- Should screening questions be attached to the pool or moved to an assessment step?

Answer: Will leave screening questions alone for now - no changes.  It will be up to the UI to query them separately and slot them in the right place.

- How will we associate screening questions with some skills?

Answer: there is a real record in the database for step 2 to hold the links to skill_pool

- If a skill is removed from a draft pool, its link to an assessment step is automatically removed as well?

Answer: yes

- Should we add the "all skills have assessment steps" rule to the "pool is complete" validator?  Maybe later so we don't block the pool publishing process?

Answer: yes, will happen in #7920

- Do we need a model for the assessment plan or just leave it in Pool?

Answer: no
  

## ✅ Acceptance Criteria

- [ ] AssessmentStep model created in database with pivots as needed, model created with relations
- [ ] can call to API to create or update or delete an AssessmentStep instance
- [ ] policy restriction on assessment mutation limiting it to PoolOperator (in team)
- [ ] seed some pools with a few assessments (via factory) 
- [ ] Add new permissions (in [Google Sheets](https://docs.google.com/spreadsheets/d/1RC7wufxwjLEvaEunHsfZfOzBefg218dvvzkDwKSiQjI/edit?usp=sharing) and seeder)
- [ ] can query a pool and see assessments (role: PoolOperator (in team), all request responder, all platform admin)
- [ ] PHPUnit tests

**Comment by tristan-orourke** [comment]
Wow, great use of mermaid markup!

Yes, the queries and mutations for this should both be pool-operator only. I think we'll want field-level permissions on assessment-plan related stuff in the schema.

The "ideal" model is a really good idea... It will block this issue, but lets make another one for refactoring pool-skills.
