### ISSUE TITLE
🔤 Copy change to the career timeline page

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#7936]
## ⌨ Details

The instructive text under the "Manage your career timeline" section of the Career timeline and recruitment UI  defines a career timeline self-referentially: "

Current copy: "This section is similar to your traditional career timeline and describes your experiences across work, school, and life." to read: 

New copy: "This section is similar to your traditional resume. This is where you can describe your experiences across work, school, and life."  

## 📸 Screenshot

![Image](https://user-images.githubusercontent.com/101275838/269040341-7a739b1c-c739-4805-9ad5-b9a53f80946e.png)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the issue was addressed.

- [ ] "Manage your career timeline" section updated to match copy above.

**Comment by petertgiles** [comment]
@gobyrne We want the word with the accented e like before, right?

**Comment by petertgiles** [comment]
I'm confused by these requirements:
>   "Manage your career timeline" section updated
Change shared copy on Career timeline and recruitment page too

The "Manage your career timeline" section is on the "Career timeline and recruitment" page isn't it?  Is there more than just the single place to change this copy?

**Comment by petertgiles** [comment]
> ensure that every single context forces ATs to read it as résumé

Could you please describe how to force ATs to read a word a certain way?

**Comment by RM-1978** [comment]
@petertgiles and @tristan-orourke, in this particular case, the sentence context and the American spelling would hopefully  force screen readers to read the word properly so that people are not traditionally resuming.

**Comment by gobyrne** [comment]
Sorry I'm coming in late. I've unblocked. In our testing the word resume gets read correctly as long as there are no accents and it's clearly a noun in the sentence (and not a verb). The proposed text above should do the trick.
