### ISSUE TITLE
🛠️  Pin Postgres versions for Github workflows

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#7940]
## 🛠️ Tooling

The Postgres versions for linting and PHP workflows is set to "latest", but it'd be best to match all other cases, currently "12.15"

## 🕵️ Details

Pin the version to whatever is the current version used locally and on servers.

This was initially attempted in #7939 but proved to be a bit on the trickier side due to needing to set up Postgres extensions.
Scroll to comments to see what threw issues, https://github.com/GCTC-NTGC/gc-digital-talent/pull/7939#issuecomment-1726316799 and https://github.com/GCTC-NTGC/gc-digital-talent/pull/7939#issuecomment-1726389636

## ✅ Acceptance Criteria

- [ ] Workflows have Postgres pinned correctly
- [ ] CI succeeds with workflows adjusted accordingly for the set version

**Comment by mnigh** [comment]
😞 Not sure this is going to be possible: https://github.com/orgs/community/discussions/42127#discussioncomment-6705869
