### ISSUE TITLE
Fix "printing" of snapshot page that just broke

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#7945]
## Details
As an request responder, I want to be able to save the application snapshot, so I can share it with departments for their HR records.

During the last deploy, printing the application snapshot (simply by asking the browser to print the webpage) got a lot worse. The longer term fix is to provide a "print" or "download" feature for the snapshot. We will likely add that in the near future, but in the meantime, Tristan felt like we could simply clean it up. If it happened during the last deploy, it should be relatively easy to diagnose and fix.

## Screenshot

![Image](https://user-images.githubusercontent.com/2494551/269304723-c39c8f72-8979-4ad0-bf52-db63d73a0772.png)

## Acceptance Criteria

- [ ] Browser print function works well on the snapshot page (without pieces of the snapshot overlapping)

**Comment by petertgiles** [comment]
Related: #4753

**Comment by petertgiles** [comment]
Decision: will not be simple, let's make a proper print button
