### ISSUE TITLE
♻️ Link Pools to Skills with a single pivot table (instead of two)

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#7949]
## ♻️ Debt/Refactor

Pools are linked to Skills via two pivot tables currently, one for essential skills and one for asset. Some future work (starting with #7922) would be easier if this used only a single pivot table, which held additional details about the connection (starting with whether its an optional or asset connection).

## 🕵️ Details

Current model
```mermaid
classDiagram

class Pool { }

class pools_essential_skills { }

class pools_nonessential_skills { }

Pool "1" o-- "0..*" pools_essential_skills
Pool "1" o-- "0..*" pools_nonessential_skills
pools_essential_skills "0..*" o-- "1" Skill
pools_nonessential_skills "0..*" o-- "1" Skill
```

Ideal data model:

```mermaid
classDiagram

class Pool { }

class pool_skill {
    PoolSkillType type (essential/asset)
}

Pool "1" o-- "0..*" pool_skill
pool_skill "0..*" o-- "1" Skill
```

## 🙋‍♀️ Proposed Solution

The question is, do we update the graphql schema at the same time as updating the database implementation?

I think it would be easiest to leave the schema as is, and rewrite the `Pool->essentialSkills` and `Pool->nonessentialSkills` to be `hasManyThrough` relationships. Later we can deprecate these fields in the schema in favour of a new `PoolSkill` type (which includes an essential/nonessential enum field) and gradually shift queries over to that.

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] Pools are connected to Skills via a single pivot table in the database
- [ ] The migration properly moves all existing relationships to the new table before deleting the current pivot tables
- [ ] Tests, seeders, and current queries and mutations (like setting pool skills) continue to work.

**Comment by vd1992** [comment]
Question @tristan-orourke 

What should the uniqueness constraint now be?
skill and pool, therefore preventing a pool from having a single skill as both essential and asset
or, skill, pool, and type, allowing a pool to have a skill as essential and asset?

**Comment by tristan-orourke** [comment]
Skill and pool. Preventing a pool from having the same skill as both essential and asset is a nice bonus.
