### ISSUE TITLE
♻️ Allow users to filter by owned skill when adding to skill showcase subpages

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/gc-digital-talent#7951]
## ♻️ Debt/Refactor

When adding a skill on the update showcase sub pages (top/improve behavioural, top/improve technical), we want applicants to have a new filter option in the `<SkillDialog />. This new filter option would be called something like "skills owned by me". 

## 🕵️ Details

The list of options should appear first.
The list of skills should only contain skills owned by user in that category.

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/22059495/6f6d507e-3822-47e4-9245-54d3d32e8a6d)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] Shows new select item in dialog allowing user to filter by own skills
- [ ] Only shows skills in that category

**Comment by brindasasi** [comment]
This has been implemented already
