### ISSUE TITLE
✨ Add "Skill showcase" to profiles on Admin

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#7990]
## ✨ Feature

Now that we have a new "Skills showcase" section collecting information on the applicant side, we need a way to display this information on admin side for request responders to view and share.

## 🕵️ Details

Add  a new "Skills showcase" section to the profile on Admin side.

- not part of applicant snapshot
- use the same components as applicant side with some small copy changes ("my" to "applicant's")

<details><summary>Location in Profile page</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/54bdc88d-3a39-4065-b1c0-9d92f53ce04a)

</p>
</details> 

## 🎨 Design File

[Link to figma](https://www.figma.com/file/gqC6F2F1WbBxZMsFCiOkF0/Admin---User-Profile?type=design&node-id=401%3A3593&mode=design&t=YnCd8S5lt6wuGS08-1) by @Jerryescandon and @substrae 

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/099d42c1-ece2-4e16-8821-d47bb8dfaa32)

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

- [ ] Skill showcase appears in user profile in admin app
- [ ] No changes to profile snapshot

**Comment by gobyrne** [comment]
@Jerryescandon do we have these changes described for the profile download?

**Comment by gobyrne** [comment]
Never mind I found it #7992

**Comment by petertgiles** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/7990?planning-poker) with Zenhub @brindasasi @esizer @JamesHuf @mnigh @tristan-orourke @vd1992 @yonikid15

**Comment by petertgiles** [comment]
@Jerryescandon Is the printed profile in scope for this?  Or just the displayed version?

**Comment by vd1992** [comment]
Re-purposing the showcase component will require some thought and planning as they should not carry-over their functions and links.
The edit link would need to be gone and the skills themselves no longer a link to the `UserSkill` instance. 
Among some other copy changes, there will be a number of things to render dependent on context. 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/892448dc-b55a-43fe-8790-1cb2313eb82e)
