### ISSUE TITLE
✨ Add new "Skill showcase" section to printed profiles

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#7992]
## ✨ Feature

Similar to #7990 but for the printed profiles

### 🧑‍🎨 Designer

@Jerryescandon 

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/098c3a89-d476-4a35-a188-7de4444bbaf4)

## ✅ Acceptance Criteria

- [ ] Skill showcase appears in printed profile as per design
- [ ] Limited by feature flag (if it still exists)

**Comment by petertgiles** [comment]
@Jerryescandon This should appear in both the anonymous and non-anonymous versions, right?

**Comment by petertgiles** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/7992?planning-poker) with Zenhub @brindasasi @esizer @JamesHuf @mnigh @tristan-orourke @vd1992 @yonikid15

**Comment by Jerryescandon** [comment]
> @Jerryescandon This should appear in both the anonymous and non-anonymous versions, right?

Yessir
