### ISSUE TITLE
✨ Keyword search for candidate tables

### ISSUE THREAD

**Issue by BrookeCameron** [GCTC-NTGC/gc-digital-talent#7994]
## ✨ Feature

Adding a "search by keyword" drop down selection and a search to search open text fields on Candidates profile.

### This is to help admin find candidate names, or specific information that it not covered by our filters. 

example 1: You know can remember a candidate when to the University of Brisbane, but can't remember any other info - you would be able to search University of Brisbane and candidates with that info anywhere on their profile would appear in the search. 

Example 2: You are looking for someone named Kevin with RCMP security clearances. You would separate items by using commas i.e. "Kevin, RCMP security clearance" and it would return all of the Kevin's with RCMP security clearances. 

### Search items are separated by commas, not spaces. 

Example 1: Process engineering, Forestry would retrieve candidates that have both "process engineering" (entire term / phrase) and "forestry" on their profile. 

Example 2: Process, engineering, forestry would retrieve candidates with all three words on their profile but It does not have to include the entire phrase. 

### Filters and where the data is pulled from
Default selection = Full profile 
Full profile = any open text fields the candidate has entered on their profile including screening questions, and notes written by request responders
Name = candidates name
Email = candidates email 
Screening question = any open text fields from screening questions 
Experience description = All text fields on Experiences (from User profile, not snapshot)
Skill justification = The text relating skills to experiences (from User profile, not snapshot)
Notes = PoolCandidate notes (written by Request Responders)

## 🎨 Design File

https://www.figma.com/file/XfZp1ilheNVVZRSXtuEoNR/Admin---candidate-tables?type=design&node-id=19-43079&mode=design&t=336Hxb7KhJMrXydJ-4

### 🧑‍🎨 Designer

@BrookeCameron 

## 📸 Screenshot
<img width="889" alt="Screenshot 2023-09-21 at 2 48 57 PM" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/52a86ef9-0695-443d-863f-944858ee7fb2">
<img width="851" alt="Screenshot 2023-09-21 at 2 49 39 PM" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/f22dadd6-518a-4ae5-babc-44772bc58a3a">

## :hammer_and_wrench: Proposed implementation
We ran two spikes to investiagte some options:
#8090
#8089

As a team we decided that a standalone search service like Meilisearch was probably too much for our needs now but might be a good option in the future if we outgrow an integrated search tool.

We would like to start with using the [Postgresql Full Text Search](https://www.postgresql.org/docs/current/textsearch.html) feature to search against text indexes. There is lots of interest in using [Laravel Scout](https://laravel.com/docs/10.x/scout) as an interface to this tool to manage updates and searches. There's [a package](https://laravel-news.com/postgresql-full-text-search-for-laravel-scout) that might make this easy.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] works with existing filter menu
- [ ] Only request responders can search all candidates (who have applied to at least one job) 
- [ ] Implemented across tables (same user permissions apply) 
- [ ] Design review by @BrookeCameron

**Comment by petertgiles** [comment]
Thanks for this one Brooke - it's very cool.  :sunglasses: It will probably take some dev discussion to figure out implementation.  Here are some quick thoughts to get the ball rolling:
- Running a giant graphql query that joins all the tables together to run a search on demand is probably not viable long-term.
-

**Comment by petertgiles** [comment]
Thanks for this one Brooke - it's very cool.  :sunglasses: It will probably take some dev discussion to figure out implementation.  

Here are some quick thoughts to get the ball rolling:
- Running a giant graphql query that joins all the tables together to run a search on demand is probably not viable long-term.
- It looks like Postgresql has some pretty great text search features built-in already: https://www.postgresql.org/docs/current/textsearch.html
- Postgresql has a large ecosystem of extensions that we could look into as well
- Text search might even be a feature we want to expose to talent searchers eventually?
- Privacy might be a big concern and difficulty if we want to do thing like make certain fields available to search for some people and not others.  We might have to maintain multiple indexes for different audiences.
- The requirement about separating fields with commas is pretty unusual, I think.  Most search engines that I know of just take a whole string and use their own smarts to bring back matches.  It might be an extra problem for some text fields that could have commas in them like person names, business names, or city names.
- A giant application would probably implement this functionality as its own microservice but that's probably overkill for us, at least at first.
- The way we localize things in the frontend could make this tricky for some fields.  Some enums have changed, like we will want "Inuk" to match "Inuit".  And all our fields are in English, so "Femme" will have to match "is_woman".

**Comment by esizer** [comment]
I'm thinking that since our search is slowly getting more complex, it might be beneficial to start leaning on some third-party resources. I have no used it yet but, [meilisearch](https://www.meilisearch.com/) is fairly popular (38.9K ⭐ on GitHub) and is under the MIT license.

We can host it ourselves (possibly on the same instance [using docker](https://www.meilisearch.com/docs/learn/cookbooks/docker)) and it will maintain a persisted indices of our records leading to faster search and results. It also does fuzzy search with relevancy rankings which is otherwise tricky.

We could also use this to do a site-wide search on the admin side so admins can search our different models anywhere without having to navigate to a different page and use the table.

**Comment by tristan-orourke** [comment]
I'm not necessarily opposed to a third party search, but I would definitely propose trying out the Postgres textsearch features first, since it's basically a thrid-party resource which we _already_ have integrated.

**Comment by petertgiles** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/7994?planning-poker) with Zenhub @brindasasi @esizer @JamesHuf @mnigh @tristan-orourke @vd1992 @yonikid15

**Comment by brindasasi** [comment]
1. Create a new column in the pool_candidates table to stored the vectorized data
2. Create a function 
ex. 
CREATE OR REPLACE FUNCTION update_profile_snapshot_vectorized() RETURNS TRIGGER AS $$
BEGIN
    NEW.profile_snapshot_vectorized := to_tsvector('english', COALESCE(NEW.profile_snapshot::TEXT, ''));
    RETURN NEW;
END;
You can also combine multiple columns from different tables (email id from users table) 

3. Create a trigger for the above
4. Create GIN index for the column 
5. To use the Laravel Scout driver , create the model  like 
https://github.com/devNoiseConsulting/laravel-scout-postgres-tsvector
6. update the front end to work this set up

**Comment by brindasasi** [comment]
So currently we are doing only the "Full profile" search. 
We wouldn't do below options: 
```
Name = candidates name
Email = candidates email
Screening question = any open text fields from screening questions
Experience description = All text fields on Experiences (from User profile, not snapshot)
Skill justification = The text relating skills to experiences (from User profile, not snapshot)
Notes = PoolCandidate notes (written by Request Responders)
```
@gobyrne  @BrookeCameron 
Any preference how do you want the dropdown appear for the options that we are not going to implement under this story? 
Should we just default to "Full Profile" and disable it ..so user can't see the other options?

**Comment by brindasasi** [comment]
The changes that are NOT mentioned in the Acceptance Criteria , but exists in the screenshot are 
1. Title Change ( Pool candidates to Candidate search)
2. URL Change ( Admin->poolcandidates to Admin->candidatesearch) 
3. Dropdown Label Change : Search pool candidates to Search by keyword
4. Dropdown item change : Entire table -> Full Profile 

For #1 & #2 
This is a big change to separate the keyword search into its own page. We are still under experimental on this feature and we will eventually add this once the first phase of search feature is live and have some user feedback on it.  
For #3 
@BrookeCameron can we get together on this? This table is common component and it shows up on 3 different pages. 
1. Pool Candidates ( All pools )
2. View Candidates ( for a particular pool ) 
3. Single Request Page ( Pool candidates table underneath search request ) 

I just want to make sure the change you would like to see here (#1)  would still be applicable for all other pages ( #2 and #3) as well. 
 For #4 
 I've added this under #8238

**Comment by petertgiles** [comment]
The only change I would scope to this issue is 4, to be honest.

**Comment by brindasasi** [comment]
Discussed with Brooke and we decided we don't need #1 & #2 
We still want to do label change "Search by keyword" I will add that under #8238 itself as just a copy change.
We can this close this story as nothing else left in here.
