### ISSUE TITLE
🐛 Date inputs look disabled in Firefox

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8003]
## 🐛 Bug

The date inputs look grey and disabled in Firefox.

## 🦋 Expected Behaviour

The date inputs should be darker, like in Chrome

## 📋 Steps to Reproduce

1. Open the Date Input story in Chromatic

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/81e960b4-c405-4b27-8168-befcb2e08354)

## ✅ Acceptance Criteria

- [ ] Date inputs should look active, not disabled, in Firefox
- [ ] Look should be similar between Firefox and Chrome

**Comment by mnigh** [comment]
This might be an issue with the selected state as the `Select` component has inconsistent styles between Chrome and Firefox as well.

## Screenshot
![Screen Shot 2023-09-26 at 17 11 41](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/18a474f4-991a-48bb-8ab6-6e738e4329f8)

**Comment by petertgiles** [comment]
Could someone please check if Safari looks OK?

**Comment by mnigh** [comment]
> Could someone please check if Safari looks OK?

These are from https://61e099a1bb1465003a73d3ce-pnafigplbv.chromatic.com/.

## Screenshots (`DateInput`)
![Screen Shot 2023-09-27 at 09 28 18](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/12dfab86-1210-4936-b69f-5ed76eda4b68)
![Screen Shot 2023-09-27 at 09 28 31](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/a22e1461-472e-41af-aa51-e84dbabd2199)

## Screenshots (`Select`)
![Screen Shot 2023-09-27 at 09 27 30](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/1103017e-e364-4026-8c19-89e2820e354b)
![Screen Shot 2023-09-27 at 09 27 37](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/e4d5d4c3-2c88-4867-bcf7-13e7bfeebbbe)
![Screen Shot 2023-09-27 at 09 28 45](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/86b76ea1-0d9e-461e-a313-e1d09acfb8fe)

**Comment by petertgiles** [comment]
Yeesh, it doesn't look disabled but does look pretty ugly.  :grimacing:
