### ISSUE TITLE
🐛 useLocale doesn't work in Storybook

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8005]
## 🐛 Bug

The useLocale hook doesn't work in storybook but always returns "en".  The locale object from useIntl does work.

## 📋 Steps to Reproduce

1. Make a storybook story.
2. Call useLocale.
3. Switch the locale to FR in the Storybook controls.
4. Observer that useLocale is still returning "EN".

## 🙋‍♀️ Proposed Solution

I guess this is because one of the contexts is not part of the Storybook preview?

## ✅ Acceptance Criteria

- [ ] Calling useLocale in a Storybook story returns the correct locale

**Comment by mnigh** [comment]
> I guess this is because one of the contexts is not part of the Storybook preview?

yes, `locale` is not a [decorator](https://storybook.js.org/docs/react/writing-stories/decorators) but a [parameter](https://storybook.js.org/docs/react/writing-stories/parameters) in storybook because the i18n [addon](https://storybook.js.org/addons/storybook-addon-intl/) we use.

**Comment by esizer** [comment]
Oh yeah, we probably shouldn't be using this hook in normal pages/components 😬 This hook is meant to get and set the locale for the `IntlProvider`  and `Router`. I would not ever expect it to function in storybook as we expect it too. While we could get it knowing, I don't think it will work in tandem with that locale of the messages 😢 

We could re-scope this issue to be: remove use of `useLocale` in pages/components?

**Comment by petertgiles** [comment]
> We could re-scope this issue to be: remove use of `useLocale` in pages/components?

I like that.  Perhaps we could add an eslint ban rule (with rule overrides in the right places) to avoid accidentally readding them back in.

**Comment by mnigh** [comment]
Re-scoped in https://github.com/GCTC-NTGC/gc-digital-talent/issues/10133.
