### ISSUE TITLE
✨ Hide "Additional details" from experience accordions

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#8014]
## ✨ Feature

When the "Additional details" section is empty in an experience accordion (Application snapshot page) the section should just be hidden instead of showing just the title.

## 🕵️ Details

Add any additional details that could assist with the development of the new feature.

## 🎨 Design File

Include a link to the design file (if it exists).

### 🧑‍🎨 Designer

Include the author of the linked design file's name (or even better, their `@githubUsername`) for future reference.

## 📸 Screenshot

Add a screenshot of the new feature (if possible).

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Criteria 1
- [ ] Criteria 2

**Comment by petertgiles** [comment]
@Jerryescandon Could you please include a screenshot of what you want to remove?  When I check the application snapshot, the details section is not empty in the experience accordions.
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/8afb7fc0-6f01-4fdb-a0f1-4a98bb636b6b)
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/b90c8cfe-b8b1-47f0-92ec-4c447230cfa0)

**Comment by Jerryescandon** [comment]
Maybe I didn't word it correctly, it is not a bug where the content is not displaying correctly, very much the opposite.

In the case where the user did not include any additional details, the section shows up with just the title (cause there is no content to show), it would be best if in those cases it just didn't show at all.

**Comment by petertgiles** [comment]
Is this happening much in production?  That field is required to add an experience to the profile.
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/adb04d8f-eed0-4c45-aa4b-3d90716f9b5c)

**Comment by Jerryescandon** [comment]
> Is this happening much in production? That field is required to add an experience to the profile. 

I guess it shouldn't, it kept happening to Gray while we were reviewing in UAT, so he asked for this ticket. But I guess it shouldn't be a problem if it is mandatory.
