### ISSUE TITLE
⌨ Enhance the skip links and add expand-all functionality

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#8023]
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/45620a7e-ae3f-42fc-a5ec-b7c6f29b8da7)

## ✨ Summary

[Visit the Figma file](https://www.figma.com/file/guHeIIh8dqFVCks310Wv0G/Style-library?type=design&node-id=638-3872&mode=design&t=x5qEz3BbWcXpgkkN-4) • Chat with @substrae for design questions

As an initial step towards enabling expand-all/collapse-all functionality for our accordion components, this issue kicks off an accessibility-first update that will provide handy page-wide controls for tab users.

```[tasklist]
### ✅ Requirements
- [ ] Update the skip links' styles to match the design
- [ ] Add a button that expands or collapses all collapsible content on the page (see the details section for more information)
``` 

#### Skip link styles

The design of the skip links has been updated to leverage our focus styles to help make their visibility clearer and more consistent.

<details>
  <summary>📸 Skip link style example</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/9144bbdd-62f1-4311-b0ff-73fd8c49aeea" />
</details> 

#### Expand all / Collapse all trigger

This new button should allow tab/keyboard users to immediately expand or collapse all collapsible content on the page. There are a few implementation nuances however:
- If no accordions on the page are open, the button should expand all accordions on the page
- If the user has opened a few accordions on the page, the button should still expand all accordions on the page
- If the user has expanded ALL accordions on the page manually or using the button, then the button should collapse all accordions on the page

<details>
  <summary>📸 Expand all styles</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/f528115e-f5bd-4b2b-b4ed-e8f7c089c0a8" />
</details> 

<details>
  <summary>📸 Collapse all styles</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/258b0339-872f-47ab-acf6-71f10a8c80fb" />
</details>

**Comment by RM-1978** [comment]
@gobyrne  and @substrae We decided that the expand all functionality would be per section. They just have to be designed and implemented on a case-by-case basis. https://github.com/GCTC-NTGC/gc-digital-talent/issues/8023 has been ready to go for a while, and was the first step from our original discussion.

From the discussion in ticket #7006 , we can see that we need an' expand all function on 

1. The job poster 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/101275838/ff12373a-fbe2-4c9e-93f0-3427fc3ad21f)

2.  Two sections of the "Manage your career timeline" (for example) that also need expand-all.
3. Advanced filters on the Talent Search 
4. Any new instances of text or input fields hidden under multiple accordions.

**Comment by gobyrne** [comment]
Ok, this global solution is clever, but kinda awkward. Let's just do the hard work to surface all the places that need Expand All and implement on a case-by-case. Closing this one, will open a spike or similar

**Comment by substrae** [comment]
@gobyrne Make sure you create a second issue to handle the style updates that were covered in this issue as well.
