### ISSUE TITLE
♻️ Update the way deadlines are displayed and provide more concrete information

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#8027]
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/122d4237-bb42-430e-981c-9558a63d34f9)

## ✨ Summary

[Visit the Figma file](https://www.figma.com/file/CdYmWlP6SpT17bw7Q9411Z/Candidates---Job-poster?type=design&node-id=122-360&mode=design) • Chat with @substrae for design questions

This ticket aims to make application deadline requirements clearer for candidates. We've received feedback that they are occasionally misunderstood in their current state. By combining simpler language with optional detail, we're hoping this will make things clearer. 

```[tasklist]
### ✅ Requirements
- [x] Change the job poster label to "Deadline"
- [x] Change the date statement to say "Apply on or before `date`" where `date` is the final day to apply
- [x] Add a button containing the `information-circle` Heroicon that triggers an information dialog
- [x] Ensure the button's `alt` text reads "Learn about how application deadlines work."
- [x] Add the information dialog along with the copy provided
- [x] Update the date statement on the application card to match the job poster format
- [x] Update the date on the "Browse jobs" cards to match
```

#### Updating the poster information

First up is how we display deadline dates on the job poster itself. We're proposing that we try an "Apply on or before" phrasing to avoid the complexity and confusion that arises from mentioning time zones. By combining this simpler approach with a more details dialog (described below) triggered by the new info icon, users should have enough information to make clear decisions about when to apply.

<details>
  <summary>📸 Job poster deadline layout</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/2ac397b1-a054-4294-819b-557449ab0cc4" />
</details> 

<details>
  <summary>📸 Job poster deadline info button hover styles</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/bbc9ca0d-06c8-4cd7-914e-b3257f6d36a2" />
</details> 

<details>
  <summary>📸 Job poster deadline info button focus styles</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/0b61d1ae-7fc7-41db-b168-c2b986e9736c" />
</details> 

#### Providing a details dialog

The details dialog itself will explain how deadlines work and provide BOTH the Pacific-based midnight closing time/date AND the user's current time zone's closing time/date for extra clarity. 

<details>
  <summary>📸 Job poster deadline details dialog</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/2ca0d9d1-a354-4b0b-9819-6e68e050d50f" />
</details> 

#### Updating the job application card component

Similarly, the job application card component will need to be updated to reflect this new, simpler format.

<details>
  <summary>📸 Job application card updates</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/35a10662-73d9-4eb9-9957-be8d7f457abd" />
</details>

**Comment by gobyrne** [comment]
@substrae to discuss:

1. Distance icon to date text
2. Alt text for info button
3. List with 1 item

**Comment by brindasasi** [comment]
No bullets needed for Item no. 3 above

**Comment by petertgiles** [comment]
@substrae Could we possibly shorten the alt-text on the info button? By the nature of it being a dialog trigger ATs already say:
"button, collapsed, {name}, activate to open" So all that additional text is redundant.  Can we shorten to "Details behind how application deadlines work." or even just "deadline explanation"?

**Comment by substrae** [comment]
@brindasasi Sorry - I spoke with @gobyrne about this but hadn't had the time to update the ticket. I'll update the designs to switch from a `<ul>` to CSS indents

@petertgiles Yep, sure thing. I'll update the requirements

**Comment by substrae** [comment]
Before I forget - Gray and I also chatted about the admin implications of these changes, and I'll have a separate ticket up for that soon. I'll tag this one to make sure things are linked.
