### ISSUE TITLE
♻️ Rework the candidate facing language form

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#8031]
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/3f077519-7dc8-4146-b4fb-8a5d33556fd7)

## ✨ Summary

[Visit the Figma file](https://www.figma.com/file/guHeIIh8dqFVCks310Wv0G/Style-library?type=design&node-id=645-13939&mode=design&t=aFwephSwg37U2NK9-4) • Contact @substrae with design questions

This issue aims to address a few bits of feedback we've received regarding the language selection being confusing and not necessarily returning the answers we need from candidates. The flow has been enhanced, with the addition of a few new fields, updated copy, and some interaction changes.

```[tasklist]
### ✅ Requirements
- [ ] Update existing input labels
- [ ] Add a new second question that appears if the user chooses "Bilingual" that asks the user to specify their first official language
- [ ] Bring the second language proficiency up below the first official language question and update its copy (it should now appear for everyone)
- [ ] Change the exam question to a single checkbox (from a radio group) and update its copy
- [ ] If the exam question is selected, show a new expiry question (recommend new enum)
- [ ] Ensure the exam level questions only appear if the exam checkbox is selected
- [ ] Change the level questions to radio groups (from selects) and update their copy
- [ ] Update data model, seeders, API, factory, schema, etc...
- [ ] Ensure the new fields are tested in ~Cypress~ Playwright
- [ ] database migration to remove old column and create new columns
- [ ] snapshot rich view workaround (with comment to remove in 6 months or a year)
- [ ] CSV downloads
```

## 🔍 Details

Below you will find screenshots of the 3 possible states the language form can be in.

<details>
  <summary>📸 Single language</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/35ef77e2-26eb-4989-9386-2c3248251407" />
</details>

<details>
  <summary>📸 Bilingual and no exam</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/75d0e947-17a9-486e-8c28-1de8b6e79c4b" />
</details> 

<details>
  <summary>📸 Bilingual with exam</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/03dae1c6-4395-43db-b44e-309f340fb964" />
</details> 

<details>
  <summary>📸 Read only state</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/44c39813-565e-43cc-b409-80794db13d6e" />
</details> 

### Migration plan
| BilingualEvaluation | first_official_language | second_language_exam_completed | second_language_exam_validity
|---------------------|-------------------------|-------------|-------------|
| COMPLETED_ENGLISH   | French                  | true        | true
| COMPLETED_FRENCH    | English                 | true        | true
| NOT_COMPLETED       | ( null )                   | false       | false

**Comment by gobyrne** [comment]
Notes:

1. Love the new copy for PSC exam
2. Are we not collecting level for people who have NOT completed an exam anymore? 
3. ugg... I just have a feeling that we will get ourselves into trouble by trying to put a name to the language levels, can we avoid that?

**Comment by substrae** [comment]
@gobyrne 

Good catch on 2; I'll update the ticket.

In terms of us getting in trouble... why? It's clear that our users don't understand the levels as they are, and I'm happy to change the labels to something more official if they exist. I don't see any harm in adding extra context though.

**Comment by petertgiles** [comment]
Couple of comments and questions:

- I think we're trying to get away from input labels that provide instructions or descriptions.  I recommend removing the "select the" and "select" parts of the labels.

- I think we would be converting our "bilingual_evaluation" field to "first_official_language" and "exam_status" fields, right?  Is this right?

| BilingualEvaluation | first_official_language | exam_status |
|---------------------|-------------------------|-------------|
| COMPLETED_ENGLISH   | French                  | true        |
| COMPLETED_FRENCH    | English                 | true        |
| NOT_COMPLETED       | null                    | false       |

- @esizer Are links in context messages working out OK?

**Comment by esizer** [comment]
> * Are links in context messages working out OK?

For sure! We can add as many links is as reasonable within our context messages 👍

**Comment by substrae** [comment]
@petertgiles 

- I think we might want to spin the copy changes out of this ticket and into another where we address this on the profile wholesale, because this isn't the only place I think it happens. Thoughts?
- Yep that seems correct to me at first glance; @gobyrne do you see any problem with this?

**Comment by petertgiles** [comment]
Yeah, we definitely have a lot of input labels to revisit but I'd like to not add to that list.    😁 I'd suggest "Language of positions you would like to be considered for" and "Your first official language" as some small changes to help.

Also, could you please add the URLs (EN and FR) for the links?

**Comment by petertgiles** [comment]
I think bilingual status is not part of search so this won't affect it?  It will mess up application snapshots, though, unless we want to derive old values for a while.

**Comment by substrae** [comment]
@petertgiles 

Okay, those two suggestions sound fine to me then. In terms of the links, I believe they're already in the existing language form. I suppose in hindsight, 4 links to the same resource is overkill 😂 I've updated the ticket so that there is only a single link.

**Comment by gobyrne** [comment]
@substrae could you also take a look at how this info is presented on the profile? Here's an example of how it can be presented in an ambiguous way:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1FSQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--87f673e40b72bedd6c43736ddd8541a4b8dbcbd1/image.png)

**Comment by substrae** [comment]
@gobyrne 

The image you linked is "private" and so I can't see it; not sure where else this appears on the profile 🤔

**Comment by petertgiles** [comment]
@substrae I'd like to get this issue moving again.  I think these are the remaining items:
- update requirements, design, and screenshots with updated labels
- confirmation on the migration table from Gray
- update design and screenshots with the readonly view

**Comment by petertgiles** [comment]
Also, is a new "first official language"  field going to overlap with the existing "preferred contact language" field?
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/95d4768e-499e-40be-8c81-5ece3cf49443)

**Comment by substrae** [comment]
@petertgiles Okay I've updated the labels, added new screenshots, and included a read-only view. These questions shouldn't overwrite or invalidate the communication language question, as it's totally reasonable for a person to speak one language first and prefer to be communicated with in their second language.

**Comment by gobyrne** [comment]
This looks ready for Lauren's review Josh, lets bring it next time we meet with her. I'd like to hear what she thinks about the descriptive labels on the PSC letter grades. The challenge is that while they aren't well described, there are specific meanings attributed to them. And the lack of simple descriptions is absolutely deliberate by the PSC. They are deliberately avoiding making a statement about your language levels and instead simply report back a grade that you got on the exam. (IMO)

Oh, Recruitment team brought up the question of expired language results. Apparently in the EX process a user got held up, not wanting to submit because some of the results were expired. Ideally, I'd like to handle it with an extra line of copy, but we could add a checkbox to the effect "one or more of these exam results may be expired".

**Comment by RM-1978** [comment]
@gobyrne, I think that you are right to raise this. I understand from a colleague in Equity at ESDC that PSC avoids this because screening out based on expired language levels 1) introduces administration bias (it is easier to hire someone with current levels, but candidates are supposed to have their levels evaluated/confirmed as part of any staffing process).

**Comment by gobyrne** [comment]
@RM-1978 actually it's broader than that. We must consider all people for positions regardless of their evaluated language levels even if they are expired (or non-existant for that matter). The language levels are not merit criteria, they are a condition of employment, so the candidate always gets a chance to take the exams again if they want. (it's probably a little more complicated than that, but essentially that's it)

So all our matching (on search page) and similar cannot use these levels. Instead, we match on whether or not the candidate indicates that they would **like to be considered** for the English, French or Bilingual positon.

The levels and (potentially) their expiry are collected for administrative purposes (or maybe based on user need in this example).

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/f1af8792-232f-4655-b2ff-65510b308630)

**Comment by substrae** [comment]
@gobyrne Can you provide @petertgiles with direction here? If we want to add a line of text along the lines of: "Please provide the latest exam results you have available, even if they're expired." then that's probably fine and I can add that in. If we want to take things to Lauren, dev should probably pause.

**Comment by gobyrne** [comment]
On letter grades, I actually found a sport on the PSC website where they describe them further. And I was totally wrong :/

https://www.canada.ca/en/public-service-commission/jobs/services/gc-jobs/language-requirements-candidates.html

So A, B and C are all exactly what @substrae has in the designs.

For the record, X just means you failed and E isn't a level, instead it's at the C level but you are Exempted from ever having to re-test. Not sure if that changes what we should put in our list.

Also, should we include Code P?

**Comment by gobyrne** [comment]
Lets discuss with Lauren in the next design meeting with Lauren.

**Comment by gobyrne** [comment]
We discussed with Lauren and Josh made the changes on the Application UI, I think we're still waiting on UI for how to display the selected choices from @substrae though.

**Comment by substrae** [comment]
@gobyrne Yep. On my todo list, but below a lot of other stuff in priority. Let me know if you want me to pivot for an hour or two to get this out the door.

**Comment by substrae** [comment]
@gobyrne @tristan-orourke @petertgiles 

Just a heads up that this ticket has finally been updated with the latest designs and copy. Gimme a shout if you have any other questions.
