### ISSUE TITLE
♻️ Update the progress stepper component

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#8032]
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/f035e240-b8a0-4299-9320-95334b59bacc)

## ✨ Summary

[Visit the Figma file](https://www.figma.com/file/guHeIIh8dqFVCks310Wv0G/Style-library?type=design&node-id=5-26&mode=design) • Chat with @substrae for design questions

The primary goal of this ticket is bring the progress stepper's styles more in line with the table of contents component so that they visually echo each other. Icons have been changed for visual clarity, and an optional button has been added.

```[tasklist]
### ✅ Requirements
- [x] Update whitespace and general styles to match the design
- [x] Update the "edit", "complete", and "error" icons to match the design
- [ ] ~~Ensure that an optional button is available~~ (edit: this button gets [added externally](https://github.com/GCTC-NTGC/gc-digital-talent/issues/8032#issuecomment-1775576667))
- [x] Storybook story is updated
```

**Comment by esizer** [comment]
> Update whitespace and general styles to match the design

Can we be provided the new values so we can match the expected values exactly?

> Ensure that an optional button is available

We already do this and it is external to the actual component so I'm not sure this applies. We can do this with:

```tsx
<Sidebar>
   <Stepper />
   <Button />
</Sidebar>
```

And it is being done on the IAP application.

![Screenshot 2023-10-23 123131](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/33d70224-7562-4859-8c9d-4d2000593a14)

**Comment by substrae** [comment]
@esizer @yonikid15 

* Do they not show in the Dev inspector mode in Figma? I was under the impression that gave you all the values (so I had stopped filling issues with that kind of info). Let me know if not and we can take a look at better ways to communicate it.
* Yep, that works just fine!

**Comment by yonikid15** [comment]
Yup I see the values in the figma design 👍

**Comment by esizer** [comment]
> * Do they not show in the Dev inspector mode in Figma? I was under the impression that gave you all the values (so I had stopped filling issues with that kind of info). Let me know if not and we can take a look at better ways to communicate it.

Oh wow, okay so it does it just isn't very clear 😅 I see the `--whitespace-x-025` which I assume is the same as `x.25`.

![Screenshot 2023-10-24 095644](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/cfb84e22-519c-4973-8c85-e7232b0d25e4)

**Comment by substrae** [comment]
Yeah, that would be it 😓
