### ISSUE TITLE
✨ Automatic handling of certain assessment step types

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#8034]
## ✨ Feature

Some assessment step types need handling automatically rather than be client driven. 

## 🕵️ Details

Creation of a draft pool should trigger the creation of an assessment step of type `APPLICATION_SCREENING`
This assessment cannot be destroyed unless the pool is deleted, syncs with all technical PoolSkills, and is locked to `sortOrder = 1`
This must be dynamic as the associated skills will change after this step is created. 

If screening questions are added to a pool, an assessment step must occupy `sortOrder = 2`  with type `SCREENING_QUESTIONS_AT_APPLICATION`
If screening questions are deleted so none exist, their assessment step record must be deleted. 

## 🎨 Design File

Include a link to the design file (if it exists).

### 🧑‍🎨 Designer

Include the author of the linked design file's name (or even better, their `@githubUsername`) for future reference.

## 📸 Screenshot

Add a screenshot of the new feature (if possible).

## 🙋‍♀️ Proposed Implementation

Laravel listener on `setEssentialSkills` and `setNonessentialSkills` methods that triggers re-syncing of pool skills to assessment step application screening. 

Boot methods running on creation and deletion of `ScreeningQuestion` models that check if the appropriate assessment step exists, and create/delete `AssessmentStep` as needed. 
ScreeningQuestion created -> check if assessment step exists -> create or do nothing
ScreeningQuestion deleted -> check if parent pool has more than zero screening question remaining -> delete assessment step if zero

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Creating a pool creates an application screening assessment
- [ ] Adding/deleting screening questions automatically updates the screening question assessment
- [ ] Screening questions can be added, with skills, in the frontend, too

**Comment by petertgiles** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/8034?planning-poker) with Zenhub @brindasasi @esizer @JamesHuf @mnigh @tristan-orourke @vd1992 @yonikid15
