### ISSUE TITLE
🐛 Tall dialogs seem to break scrolling capabilities

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#8086]
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/90b94881-fc95-429b-872a-df2207395409)

## ✨ Summary

Chat with @substrae for more information

This was found on the skill library page when adding a new skill (type didn't matter). After choosing a skill from the skill list, the level question appears, but you can't scroll back up to the top of the dialog from the point pictured above, you can only scroll down.

Radix docs:
https://www.radix-ui.com/primitives/docs/components/dialog#scrollable-overlay

```[tasklist]
### ✅ Requirements
- [ ] Ensure that users can scroll up to the top and down to the bottom of all dialogs regardless of height.
```

**Comment by petertgiles** [comment]
Firefox testing in responsive mode.

https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/6f400578-13f5-4159-acb3-6fd3ac4ec00b
