### ISSUE TITLE
🏐 Assess Laravel Scout for profile search 

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8089]
## ✨ Feature

We're trying to decide the best way to implement keyword search for #7994.  One possibility might be Laravel Scout with the database driver.

## 🕵️ Details

https://laravel.com/docs/10.x/scout

## :thinking: Considerations:
- Can this integrate well with restrictions like policies and roles?
- Can this be used to search with multiple clauses?
- How far will this scale?

## 🎨 Design File

See #7994.

## :clock1: Timebox

2 days

## :question: Main question

**Is Laravel Scout with the database driver a good choice to implement a backend for #7944 ?**

**Comment by brindasasi** [comment]
Loved everything about MeiliSearch until I figured this about their Roles & Policies feature
<img width="755" alt="Screenshot 2023-10-13 at 10 58 38 AM" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/b70f0049-9065-45ff-9465-9915d6bfcb16">

**Comment by brindasasi** [comment]
currently Meilisearch has [Tenant tokens](https://www.meilisearch.com/docs/learn/security/tenant_tokens?ref=blog.meilisearch.com#what-are-tenant-tokens-and-how-are-they-different-from-api-keys-in-meilisearch)
which can be used to implement Role Based Authentication.

**Comment by petertgiles** [comment]
Discussion complete.
