### ISSUE TITLE
🏐 Assess PostgreSQL Full Text Search for profile search 

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8090]
## ✨ Feature

We're trying to decide the best way to implement keyword search for #7994.  One possibility might be PostgreSQL Full Text Search.

## 🕵️ Details

https://www.postgresql.org/docs/current/textsearch.html

## :thinking: Considerations:
- Can this integrate well with restrictions like policies and roles?
- Can this be used to search with multiple clauses?
- How far will this scale?
- Can this provide any relevancy ordering?

## 🎨 Design File

See #7994.

## :clock1: Timebox

2 days

## :question: Main question

**Is PostgreSQL Full Text Search a good choice to implement a backend for #7944 ?**

**Comment by brindasasi** [comment]
**PostgreSQL Full Text Search** 


Full text search in postgres can be done by 

Option 1: 

on the fly queries like 
```
SELECT *
FROM pools
WHERE to_tsvector(pools.name::text || ' ' || pools.key_tasks::text) @@ to_tsquery('CMO');
```
in this case the column values are parsed dynamically and then searched for the given term. 
 
Option 2 -  with pre-parsed document stored as a new column :

As the description suggests, the searchable column values are pre-parsed and stored as a single document with the type tsvector. A trigger is required to keep this document updated when the value of this column changes. 

In our scenario, for profile search, we  search within profile snapshots which doesn't change. For that column this pre-parsing would be very beneficial as this it reduces the search time tremendously.
Something like this we create a vectorized column (tsvector data type)

`UPDATE pool_candidates SET profile_snapshot_vectorized = to_tsvector('english', COALESCE(profile_snapshot::text, ''))`

We can also set up index to further optimize the performance
`create index profile_snapshot_vectorized_idx on pool_candidates using GIN (profile_snapshot_vectorized) `
Now we have the super efficient column with parsed & indexed , searching can be done in this column as before. 

We can have as many as vectorized columns as we want. 

If the search column is available for the user to edit , a trigger can be added as below to keep this parsing uptodate. 

Create a function 

```
CREATE OR REPLACE FUNCTION update_profile_snapshot_vectorized() RETURNS TRIGGER AS $$
BEGIN
    NEW.profile_snapshot_vectorized := to_tsvector('english', COALESCE(NEW.profile_snapshot::TEXT, ''));
    RETURN NEW;
END;
```

Create the trigger 
```
CREATE TRIGGER update_profile_snapshot_vectorized_trigger
BEFORE INSERT OR UPDATE ON pool_candidates
FOR EACH ROW
EXECUTE FUNCTION update_profile_snapshot_vectorized();
```

Questions: 
### 1. Can this integrate well with restrictions like policies and roles?
Yes. It is. As far as I researched , there is no difference or no new methods to respect the policies. 
Search queries are used as before and they can be connected with the policies as usual. 


       ```
 $results = DB::table('pool_candidates')
            ->select('id', 'profile_snapshot', 'notes')
            ->whereRaw("profile_snapshot_vectorized @@ to_tsquery('english', ?)", [$query])
            ->get();

        // Filter results based on Laravel policies
        $filteredResults = $results->filter(function ($poolCandidate) {
            if (!auth()->user()->can('view', $poolCandidate)) {
                throw new AuthorizationException('You are not authorized to view this pool candidate.');
            }
            return true;
        });

        return $filteredResults;
```
In our case these policies have already been defined and we could just use it for our new search queries on these vectorized columns.

### 2. Can this be used to search with multiple clauses?
 
Yes. Below query would search for both database and managment


```
SELECT
    *
FROM
    pool_candidates
WHERE
    profile_snapshot_vectorized @@ to_tsquery('english', 'Database & Management');
```

for the graphql it could go like this 

```
class PoolCandidateResolver
{
    public function searchPoolCandidates($rootValue, array $args, GraphQLContext $context, ResolveInfo $resolveInfo)
    {
        $queries = $args['queries'];

        $results = DB::table('pool_candidates')
            ->select('id', 'profile_snapshot', 'notes')
            ->where(function ($queryBuilder) use ($queries) {
                foreach ($queries as $query) {
                    $queryBuilder->orWhereRaw("profile_snapshot_vectorized @@ to_tsquery('english', ?)", [$query]);
                }
            })
            ->get();

        return $results;
    }
}


 ### 3. Can this provide any relevancy ordering?
Yes.  Below query searched 

SELECT
    id,
    profile_snapshot,
    notes,
    ts_rank(profile_snapshot_vectorized, to_tsquery('english', 'Database & Management')) AS rank
FROM
    pool_candidates
WHERE
    profile_snapshot_vectorized @@ to_tsquery('english', 'Database & Management')
ORDER BY
    rank DESC;

When I tested above query it ranked profile with database and mangement keywords with most occurrences with the higher rank than the less occurrences. 

Apart from occurrences , you can also specify weight for each search column so that you can optimize the relevancy of the search.
For ex. if we were to search both notes & profile_snapshot columns , notes column can be lowered in ranking than the other. 

```
SELECT
    id,
    profile_Snapshot,
    notes,
    (ts_rank(profile_snapshot_vectorized, to_tsquery('english', 'Database & Management')) * 0.8) +
    (ts_rank(to_tsvector('english', COALESCE(notes::text, '')), to_tsquery('english', 'Database & Management')) * 0.2) AS rank
FROM
    pool_candidates
WHERE
    (profile_snapshot_vectorized @@ to_tsquery('english', 'Database & Management')) OR
    (to_tsvector('english', COALESCE(notes::text, '')) @@ to_tsquery('english', 'Database & Management'))
ORDER BY
    rank DESC;
```

### Scalability 

Although PostgreSQL is not a full fledged search solution with all the bells & whistles , as per my reading it is doing quite well for an application like our size. 
Here is an article with benchmark testing with similar dedicated pre-parsed column approach. 
It does quite well for some millions of documents 
https://betterprogramming.pub/building-a-scalable-event-driven-search-architecture-with-postgres-full-text-search-4780b87a34ef


In my research so far, I'm pretty impressed with PostgresSQL on below points 

1. Easy to get up & running with the configuration than the most other search engines like Elastic Search. 
2. Higher level customization is also available like you can specify the language to search on.  
Default is English but you can also specify French. 
For my surprise it can also be searched in indigenous languages that have proper dictionaries 
Disclaimer : "I did not try. But it looks promising"  
```
-- Set the text search configuration to use Cherokee language
SET default_text_search_config = 'cherokee';

-- Perform a Full Text Search in Cherokee
SELECT * FROM my_table WHERE my_text_column @@ to_tsquery('CherokeeKeyword');

```
3. It can also be used to search partial queries. Below query would search profiles that has words contain "datab" instead of giving "database" 

 ```
SELECT
    id,
    profile_Snapshot,
    notes
FROM
    pool_candidates
WHERE
    profile_snapshot_vectorized @@ to_tsquery('english', 'datab:*');
```

**Comment by petertgiles** [comment]
> if a searchable document is more than 19k words this would stuck in throat it seems

That's an interesting Reddit thread.  It seems like you just lose the positional data after 19K?  So you can no longer query for words being close together.  That's seems like not too bad a loss for extremely large documents, at least for us.

**Comment by petertgiles** [comment]
Discussion complete.
