### ISSUE TITLE
♻️ Make minor modifications to the candidate-facing skill table

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#8091]
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/c2b3bcad-4137-4374-b5c3-7d3259410043)

## ✨ Summary

[Visit the Figma file](https://www.figma.com/file/guHeIIh8dqFVCks310Wv0G/Style-library?type=design&node-id=108-39250&mode=design&t=JfScQNdCl3fNhF2Z-4) • Chat with @substrae for design questions

We noticed a few small state-related things, as well as would like to make a few small copy enhancements. First and foremost, when performing a search and no results are found, the table is missing a null state. We've also updated the "add" button text and default empty null state text.

```[tasklist]
### ✅ Requirements
- [ ] Update the create button's label to "Add a new skill"
- [ ] Update the default empty state's text to match
- [ ] Add a message for when no search results exist
``` 

## 🔍 Details

<details>
  <summary>📸 Default null state</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/5610fb70-99f5-49f8-8d41-a7456d0ffe5f" />
</details> 

<details>
  <summary>📸 No search results</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/5186bf97-1606-47bc-9e72-dee4933a58d6" />
</details>

**Comment by petertgiles** [comment]
@esizer I know the responsive table has a null state.  Does it have a "no search results" state already or is that new functionality?

**Comment by esizer** [comment]
> Does it have a "no search results" state already or is that new functionality?

It does not but by the looks of it, we can follow the exact same pattern and render a different message based on the existence of filters. This one should be an easy win 👍
