### ISSUE TITLE
Table component - Data fetch for printing reloads bottom of table

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#8099]
### Details
When the "check all" checkbox on the table component is clicked, it immediately fetches all the data for these profiles. To prevent printing (or download) of profiles before the data is fetched, we replace the bottom of the table with our spinner component until it's done.

This functionality is just a bit awkward. One user reported that they didn't realise the bottom of the table changed when they clicked the "check all" button. Of course, nothing actually changes on the UI, just that the spinner appears and then disappears. It's hard of a user to figure that out though.

There's also the case where a user is viewing 100+ rows at a time and clicks the "checkall" with no intention of downloading.

Anyway, we should come up with a more graceful solution that doesn't use the spinner on the bottom of the table.

**Slack convo:**
https://talent-cloud.slack.com/archives/CB424V61J/p1695737638175039

### Acceptance Criteria

- [ ] Data is only fetched when the "download" button is clicked.
- [ ] Data is fetched in the background (with no change to UI) and we somehow stall the download until that finishes if link is clicked

**Comment by gobyrne** [comment]
Possible duplicate of #8956

**Comment by esizer** [comment]
As long as we are okay with dropping the AC portion "(with no change to UI)" this will be solved with https://github.com/GCTC-NTGC/gc-digital-talent/issues/8970. We do change the UI (add a small spinner next to the button) but only to indicate to a user that the application is doing something while they wait since it takes a few seconds to get the data and generate the document.

**Comment by esizer** [comment]
@gobyrne Do you mind if I close this as solved with https://github.com/GCTC-NTGC/gc-digital-talent/pull/8970 ? We no longer reload the entire footer, just show a  spinner next to the action button.

![Screenshot 2024-02-12 102540](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/f82edb18-2bcb-4779-9be4-740c6f94c62a)
