### ISSUE TITLE
♻️ Update the candidate profile and applications page content

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#8100]
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/2a72cc6c-bb3c-43e6-9246-513e7e2d5606)

## ✨ Summary

[Visit the Figma file](https://www.figma.com/file/jHsXzqMfBtomLa1Gom94Y7/Candidates---Profile-and-applications?type=design&node-id=1333-7938&mode=design) • Chat with @substrae for design questions

This ticket covers minor text updates as a part of the changes to the skills pages. These are generally being changed for clarity and ease of use when it comes to the profile flow.

I've opted to change "Profile information" to "Personal information" here because there has been discussion of the word profile being confusing here given that you're already looking at a summary of your profile in its entirety.

I've noticed the change to "Career timeline" from "resume" has made the middle card way too long, so I've shortened that title for now.

The rest are directly tied to the skills pages as discussed.

```[tasklist]
### ✅ Requirements
- [x] Update "Profile information" to "Personal information"
- [x] Update "Career timeline and recruitments" to "Career timeline"
- [x] Update "Skill showcase" to "Skill library"
- [x] Ensure the Skills library card links to the library, not the showcase
- [x] Ensure the links, titles, breadcrumbs, urls in the page subtitle are updated to match
```

**Comment by petertgiles** [comment]
In addition to the link in profile page are we also changing the page being linked to?
- URL
- Title
- Breadcrumbs

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/45541b65-3386-4578-8995-310748d833b4)

**Comment by substrae** [comment]
@petertgiles 

If it's not a huge deal, changing these would be great! Ideally we could redirect the URL to point to the new one just in case anyone has bookmarked the page, but no biggie if not.

**Comment by petertgiles** [comment]
> Ideally we could redirect the URL

We do when we can but probably not in this case, since it's a dynamic URL with an ID in it.

**Comment by petertgiles** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/8100?planning-poker) with Zenhub @brindasasi @esizer @JamesHuf @mnigh @tristan-orourke @vd1992 @yonikid15

**Comment by petertgiles** [comment]
Decision in scrum: don't do code renames (variables, components, etc)
