### ISSUE TITLE
♻️ Update copy on the skill showcase

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#8103]
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/2318a5f7-0810-4d2d-9ef1-8883afba953c)

## ✨ Summary

[Visit the Figma file](https://www.figma.com/file/9Bq2VP39MW4hXKH7RfrovZ/Candidates---Skill-showcase?type=design&node-id=271-3881&mode=design) • Chat with @substrae for design questions

The primary focus of this ticket is to improve the sense of place when it comes to the Skill showcase page and helping users understand it's broader position with the skill library. These changes are mostly copy related.

```[tasklist]
### ✅ Requirements
- [x] Remove "Manage all skills" links from both page headings
- [x] Update the breadcrumbs so that Skill showcase is a child of Skill library
- [x] Update the button in the Table of contents to "Return to skill library"
```

## 🔍 Details

<details>
  <summary>📸 Breadcrumb changes</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/f206d35d-ec47-4a9b-87af-5cd3c7260694" />
</details> 

<details>
  <summary>📸 Table of contents changes</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/689e5bef-6aa0-4e52-b155-06b937492e85" />
</details>

**Comment by petertgiles** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/GC-Digital-Talent-6092dc05157fa30010edaef9/issues/GCTC-NTGC/gc-digital-talent/8103?planning-poker) with Zenhub @brindasasi @esizer @JamesHuf @mnigh @tristan-orourke @vd1992 @yonikid15
