### ISSUE TITLE
✨ Skill Summary Table for Assessment Page

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8127]
## ✨ Feature

The assessment plan builder is the first step in the Record of decision (RoD) flow. It allows us to capture the list of assessments to be used during the staffing process, the order in which they will be performed, and the skills that each assessment will be targeting.

It features a repeater component with dialogs for details, and a table to overview how the skills and assessments are related to each other.

This issue covers just the Skill Summary Table.

## 🎨 Design File and Designer

[Link to figma file](https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Pools---Record-of-Decision?type=design&node-id=5437%3A34317&mode=design&t=11Dob6JX6BOb3lle-1) by @Jerryescandon 

## 📸 Screenshots

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/5500f46e-9add-4794-ab7c-328058c592c6)

## ✅ Acceptance Criteria

- [ ] Component built in Storybook
- [ ] Design review with designer

**Comment by vd1992** [comment]
What is "Planned assessment"? 
Just a status check that a `PoolSkill` instance is connected to one or more `AssessmentSteps` right and not a new field?

**Comment by brindasasi** [comment]
is it going to use the new responsive table for this?

**Comment by petertgiles** [comment]
> is it going to use the new responsive table for this?

Yes, always use responsive table

**Comment by petertgiles** [comment]
> ust a status check that a `PoolSkill` instance is connected to one or more `AssessmentSteps` right and not a new field?

Yes, at least one assessment per skill
