### ISSUE TITLE
⚙️ Card repeater

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8161]
## ⚙️ Summary

Our current repeater component is built to exist inside of forms.  We need a component that allows a display of generic non-form content with reorder, remove, and edit events.

## 🎨 Design File

[Include a link to the design file (if it exists).](https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Pools---Record-of-Decision?type=design&node-id=5437-34317&mode=design)

#### Screenshot

@Jerryescandon 
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/e2c6f43e-44fb-4a51-b71a-73971ce88644)

## Acceptance Criteria
- [ ] Repeats content
- [ ] Has events for reorder, remove, edit
- [ ] No form state
- [ ] Can prevent different events from different items
- [ ] Context message
- [ ] Add button
- [ ] Implement in
  - [ ] ~Skills list in skill showcase~ #9035
  - [ ] Steps list in assessment builder
  - [ ] ~screening questions list in admin pool editor~ #8676

**Comment by yonikid15** [comment]
After talking with the designers, it looks like there was some confusion on why we needed a separate Repeater component. #7916 The assessment plan page does have a form and save button so we can move forward with the regular Repeater with the additional features added there.

**Comment by brindasasi** [comment]
We discussed to close it down as not planned

**Comment by brindasasi** [comment]
we revisited this story and decided this approach would make more sense and easier than updating the repeater comp.

**Comment by brindasasi** [comment]
Is there any accessibility concerns that we need to take care for the locked cards?  
Should we have the screen reader to read out about the locked card ? 
@GCTC-NTGC/designers

**Comment by esizer** [comment]
I think we may need to re-estimate this one now that we have more context on it. The original ticket ( #6242 ) to create a repeater was based on the immense amount of heavy lifting `react-hook-form` was doing for us and that was a 5 😅 

Now that we need to write all that heavy lifting ourselves and add additional functionality, I'm thinking this needs to be higher than 3 and probably also higher than a 5 since it is more work than the original ticket 😬 

There will be a lot of accessibility concerns involved here as well:

- state management
- focus management
- keyboard shortcuts
- AT announcements

**Comment by petertgiles** [comment]
@esizer if that's the case then maybe it's better to make the customizations to the regular repeater after all?  And just accept the weirdness that comes from leaning on react-hook-form to do that heavy lifting.

**Comment by vd1992** [comment]
Can we revisit this issue in standup, to figure out whether to remove it from sprint or whatever else

**Comment by brindasasi** [comment]
@gobyrne mentioned we can move the locked cards out of this repeater. 
we still need to deal with the focus issue on edit and delete buttons.
@Jerryescandon we would like to discuss with you on this

**Comment by brindasasi** [comment]
we are not implementing this way. closing this issue
