### ISSUE TITLE
🐛 User can't review their own application when the pool is expired (Prod issue)

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#8163]
## 🐛 Bug

User can't review their own application when the pool is expired. They get unauthorized error. 

## 🦋 Expected Behaviour

User should be able to review their submission status and application id. 

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Name and version (if possible).
- **Browser**: Name and version (if possible).

## 📋 Steps to Reproduce

1. ...
2. ...

## 📸 Screenshot

Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Criteria 1
- [ ] Criteria 2

**Comment by mnigh** [comment]
@brindasasi i attempted to reproduce this behaviour locally but i was not able to. by "pool is expired", am i correct to assume this means the pool's closing date is in the past? 

are you able to provide any of the following:

- steps to reproduce
- details of the unauthorized error
