### ISSUE TITLE
✨ Update the admin sidebar menu

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#8175]
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/4642cc24-245c-4f09-bd23-bffb0bf26775)

## ✨ Summary

[Visit the Figma file](https://www.figma.com/file/guHeIIh8dqFVCks310Wv0G/Style-library?type=design&node-id=652-29771&mode=design) • Contact @substrae with design questions

As a part of the larger admin-facing UI refresh, this ticket aims to reorganize and update the admin sidebar menu to make it clearer and easier to use.

The pin and popover elements have been spun off into #8902.

```[tasklist]
### ✅ Requirements
- [ ] Update the icons for each item
- [ ] Reorganize the items into categories as depicted
- [ ] Update the active item color to `base(secondary.lighter)` and `base:iap(secondary.lightest)`
- [ ] Ensure the menu's width is fixed to match
- [ ] Ensure that the menu's state is saved in local memory so that users can return to the same state next time
- [ ] Ensure mobile menu opens from the left
- [ ] Ensure mobile menu overlay appears and uses `black.light.9`
- [ ] Ensure the mobile menu, while open, is scrollable if the vertical height exceeds the viewport available
- [ ] Ensure these changes don't affect display of items based on permissions/roles
``` 

### On landscape tablets, laptops, and desktops

- We're updating the information architecture by categorizing menu items and giving them distinct icons

<details>
  <summary>📸 Menu closed</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/3fce4097-532a-4b1a-bfa9-9df435495a71" />
</details> 

<details>
  <summary>📸 Menu open</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/b1ebaa81-f2c6-44bb-a4c8-36fc174f6a22" />
</details> 

### On mobile devices and portrait tablets

Not much is changing on mobile in terms of behaviour - the look and feel should be reflected. The bar remains sticky at the top, and triggers the menu to open from the left.

<details>
  <summary>📸 Menu closed</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/f0bb321b-512e-488a-a091-f265fbee6e0e" />
</details> 

<details>
  <summary>📸 Menu open</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/1b59937d-d1f1-4acd-9d69-61b213fc03ce" />
</details>

**Comment by mnigh** [comment]
## Questions
1. the one heading is **Data**, isn’t everything data?
2. what is **Employment conditions**, is that a new page?
3. are we also changing copy based on the screenshot?

**Comment by substrae** [comment]
@mnigh @brindasasi 

* After chatting with Gray, _Data_ is now _Platform data_; this category aims to consolidate CMS related content into one section - as such, we've moved _Teams_ into the _Processes_ category for clarity
* _Employment conditions_ was a remnant from older designs that I wasn't aware didn't exist, so it's been removed
* Yes, copy should change to match what's here, including page titles - I've updated a handful of small things based on feedback Gray passed along to me
* This might have also been a legacy design thing, but as I understood it, the `+` expanded a second menu level with the user's active recruitments; I realize this doesn't exist in prod, but it has appeared in designs in the past. If this has been omitted until now, we can chat about spinning this off into a separate ticket. Users with access to dozens or hundreds of recruitments would pose a problem, so it might be more reasonable to break this away and pair it with a "Pinned recruitments" feature that allows a user to pin recruitments they're actively working on to the menu. CC @Jerryescandon in case he has thoughts
* In terms of pinning/unpinning - I didn't see a need for "unpinning" because collapsing the menu effectively unpins it
* _Account settings_ is also up in the air, because we don't apparently have a place for admin users to manage things like their personal / contact information, so I've removed it for now

**Comment by mnigh** [comment]
> * After chatting with Gray, _Data_ is now _Platform data_; this category aims to consolidate CMS related content into one section - as such, we've moved _Teams_ into the _Processes_ category for clarity

I think the distinction between "CMS related content" and non-"CMS related content" is arbitrary and having a section with item it similar to including only one list item in an `ul` element. Also, adding section headers takes up more space and makes it even tighter on small screens.

> * _Employment conditions_ was a remnant from older designs that I wasn't aware didn't exist, so it's been removed

👍 

> * Yes, copy should change to match what's here, including page titles - I've updated a handful of small things based on feedback Gray passed along to me

That broadens the scope of this issue, especially if URLs need to be changed (which, we shouldn't be doing often, if at all, without very careful consideration). Copy flux should also be something we try to avoid, otherwise it confuses users.

> * This might have also been a legacy design thing, but as I understood it, the `+` expanded a second menu level with the user's active recruitments; I realize this doesn't exist in prod, but it has appeared in designs in the past. If this has been omitted until now, we can chat about spinning this off into a separate ticket. Users with access to dozens or hundreds of recruitments would pose a problem, so it might be more reasonable to break this away and pair it with a "Pinned recruitments" feature that allows a user to pin recruitments they're actively working on to the menu. CC @Jerryescandon in case he has thoughts
> * In terms of pinning/unpinning - I didn't see a need for "unpinning" because collapsing the menu effectively unpins it

Pinning a menu like this is not a pattern I have ever seen on websites. The fact that we also need a custom icon seems like not a good idea.

> * _Account settings_ is also up in the air, because we don't apparently have a place for admin users to manage things like their personal / contact information, so I've removed it for now

We do have a place admin users can manager things like their personal information in `/admin`, but it requires navigation right now to get there:

1. Users table
2. Search for themselves
3. Edit (`/admin/users/:user-id/edit`)

We could be linking directly to the current user though with a link on the admin side of things with something like `/admin/users/:current-user-id/edit`, if need be. There is also the ability to edit a lot of this from the non-admin side at `/users/me`.

**Comment by substrae** [comment]
>I think the distinction between "CMS related content" and non-"CMS related content" is arbitrary and having a section with item it similar to including only one list item in an ul element. Also, adding section headers takes up more space and makes it even tighter on small screens.

This might be arbitrary to you, but it's not in the grander scheme of user roles and task completion. Having a single item in a category is the case right now, but I anticipate it not being so in the future, so the category is warranted. I'm not concerned about the vertical space added by the headers, as it allows us to properly categorize information for the end user as this interface scales.

>That broadens the scope of this issue, especially if URLs need to be changed (which, we shouldn't be doing often, if at all, without very careful consideration). Copy flux should also be something we try to avoid, otherwise it confuses users.

URLs can remain the same. Copy has only changed in 2-3 places to enhance clarity, because the labels as they are right now are not as clear as they can be or contain typos (see _Pools candidates_).

>Pinning a menu like this is not a pattern I have ever seen on websites. The fact that we also need a custom icon seems like not a good idea.

The pattern is something I see extremely frequently - my notes app open next to this window has the exact same pattern. The fact that we require a custom icon is a limitation of the icon set we chose to work with, not an indicator of the value of the feature.

>We do have a place admin users can manager things like their personal information in /admin...

Until we have dedicated UI for this, I'm find omitting it. Linking to an edit view of a user table doesn't seem like an experience we should be highlighting.

**Comment by petertgiles** [comment]
Decision in standup: OK to spin out the hovering/pinning functionality.
