### ISSUE TITLE
✨ Toggle forms show stale data while page data refreshes

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8176]
## ✨ Feature

We have started to use the toggle forms more.  They're used in the use profile (both regular and during application) and the edit pool page.  One of the gaps of this component is that when the formed is saved there is a short time period while the "readonly" version of the form flips up again but displays the old information while urql is still trying to fetch the new information from the database.  On a slow connection this could be a noticeable amount of time that user believes their information has been saved but the old information is displayed.

Experience with a slow connection simulated:
https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/ad4ff378-e9c3-4c16-872b-16b6a4e399c1

## 🕵️ Details

Context discussion: https://github.com/GCTC-NTGC/gc-digital-talent/pull/8119#discussion_r1349146349

## 🎨 Design File

Include a link to the design file (if it exists).

### 🧑‍🎨 Designer

Include the author of the linked design file's name (or even better, their `@githubUsername`) for future reference.

## 🙋‍♀️ Proposed Implementation

Grey out a busy form with an overlay?  Show a spinner?  

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Criteria 1
- [ ] Criteria 2

**Comment by gobyrne** [comment]
@Jerryescandon any thoughts on how this component would handle it?

It's also not clear that it's really a problem, but worth considering.

**Comment by petertgiles** [comment]
Closing in preference for #8309
