### ISSUE TITLE
✨ Skills quick summary sidebar

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8213]
## ✨ Feature

The assessment plan builder page should have a quick summary sidebar.

Quick notes:
- Mostly behave the same as the table of contents
- They are a mini summary of what's on the table
- If a skill is missing an assessment then it is red
- If it has at least one assessment then it's green
- Warning on the total - warning if too few assessments (1) or too many (4+)
- The link at the bottom scrolls to the skill summary section on that page

## 🎨 Design File and Designer

[Link to figma file](https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Pools---Record-of-Decision?type=design&node-id=5437%3A34317&mode=design&t=11Dob6JX6BOb3lle-1) by @Jerryescandon 

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/87cc7ea8-92cf-4ed8-8242-22d5aa002a09)

## ✅ Acceptance Criteria

- [ ] Sidebar added to page
- [ ] Received data and correctly displays output

**Comment by petertgiles** [comment]
@Jerryescandon our status items currently use circle-exclamation for items in the error state.
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/b313d519-b58c-4d93-9de9-4c1797201bad)
Are you OK to use that with this component, or change all status items to use circle-x, or not use the same status items for this?

**Comment by Jerryescandon** [comment]
circle-exclamation is fine.
