### ISSUE TITLE
✨ Asessment Results Backend

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8218]
## ✨ Feature

This issue is to build the backend to support

## 🕵️ Details

Note that education assessment is not associated with a skill
Education assessments have different justifications than skill decisions

## 🎨 Design File

@Jerryescandon 
https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Pools---Record-of-Decision?type=design&node-id=5832-119940&mode=design&t=METgDKnumopcIjdX-4

## 🙋‍♀️ Proposed Implementation

WIP data model

```mermaid
classDiagram

class Pool { }

class AssessmentResult {
    AssessmentDecision decision
    [Justification] justifications
    string otherJusticationNotes
    DecisionLevel level
    
    string notes
    AssessmentResultType type (skill/education)
}

class AssessmentStep {
    Int sortOrder
    AssessmentType type
    LocalizedString title
}

class PoolCandidate

class pool_skill {
    PoolSkillType type (essential)
}


Pool "1" o-- "0..*" AssessmentStep
Pool "1" o-- "0..*" PoolCandidate
Pool "0..*" o-- "0..*" pool_skill
AssessmentStep "1" o-- "0..*" pool_skill
AssessmentResult "0..*" -- "1" AssessmentStep
AssessmentResult "0..*" -- "1" pool_skill
AssessmentResult "0..*" -- "1" PoolCandidate
```
```
JustificationEnum {
  EDUCATION_NOT_ENOUGH_EVIDENCE
  EDUCATION_THEY_DID_GREAT
  SKILL_SOMETHING
  SKILL_SOMETHING_ELSE
}
```
## :question: Question and Answer

Q: Each evaluation is between exactly one assessment step and one pool_skill?
A: No, some special assessments (like education) might not have a skill.

Q: Where does the education fit into the assessment?
A: A special assessment decision that only exists on the Initial Application

Q: Are all the screening question evaluated together against each different pool_skill?
A: Yes, all question considered together.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Migration, Mode, Factory, Seeder
- [ ] Validator confirms consistency between result type, justifications, notes
- [ ] Schema, Policies
- [ ] Tests

**Comment by vd1992** [comment]
@Jerryescandon 
I've a few questions about the issue to try and clarify some things about the goal.

1. How many enums are involved? I see `Justification` which is an array, but are `AssessmentDecision`, `DecisionLevel`, and `AssessmentResultType` also enums? If so, what are their values? Is `AssessmentResultType` as in the mark-up only either education or skill?

2. How does the Justification array work? It appears to be various states, "skill-something" or "education not met". So multiple are allowed to be selected? Are there any restrictions on how many or what can be selected?

3. What is the full set of Justification Enums? "Skill_something" appears to be a placeholder for example 

4. I assume we need create, update, and deletion mutations for assessment result as a part of this issue too?

**Comment by vd1992** [comment]
`AssessmentDecision`
demonstrated
not_demonstrated
not_sure
if null -> pending

**Comment by vd1992** [comment]
`Justification` 
accepted_education_information
accepted_education_work_experience_equivalency
accepted_education_combination_education_work_experience
failed_education_not_relevant
failed_education_requirement_not_met
accepted_skill
failed_skill_not_sufficiently_demonstrated
failed_not_enough_information
failed_other

**Comment by vd1992** [comment]
`DecisionLevel`
at_required
above_required
above_and_beyond_required

For skill type only

As well, field decision_note for successful skill assessments
