### ISSUE TITLE
♻️ Rewrite policies with safer fall-through conditions.

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#8220]
## ♻️ Debt/Refactor

When a policy method fails early, particularly due to additional conditions based on the `$request` input, the condition may be missed if other parts of the code change or are renamed. This can lead to a situation where refactors may lead to a policy succeeding where it should fail - a security risk.

## 🕵️ Details

Review all the Policy classes. In cases where a method returns `false` early based on a condition, rewrite the method to return false as a default, and only return true in more specific cases. This should be more robust to future refactoring. 

## 🙋‍♀️ Proposed Solution

PoolCandidatePolicy.php has some examples of exactly what we want.

The following classes have some methods which could use this treatment:
- [ ] UserPolicy.php
- [ ] PoolPolicy.php
- [ ] AssessmentStepPolicy.php

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] Less specific conditions should cause policy methods to fail, not to pass

Q: Are the three policy files the whole scope of this issue?  Or should all policy files be reviewed?
A: The above 3 policies are needed to be changed. Other policies are compliant right now.

**Comment by petertgiles** [comment]
Are the three policy files the whole scope of this issue?  Or should all policy files be reviewed?
