### ISSUE TITLE
🐛 Row selection column issues

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#8222]
## 🐛 Bug

We have two minor issues with the row selection column on the new table.

- The padding is off between the header and cells causing a misalignment
- It does not cancel out the min width causing some unnecessary whitespace

## 📋 Steps to Reproduce

1. Navigate to `/admin/users`
2. Observe the misalignment of checkboxes and extra whitespace on the row selection column 

### Current

![Screenshot 2023-10-12 145452](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/0914059a-eaaa-4181-8b14-3d9dd7e56cbf)

### Expected

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/a902e8f3-0bca-415e-884a-e37299ed4ce2)

## 🙋‍♀️ Proposed Solution

- Override min width on row selection column
- Adjust padding for row selection column to align with header checkbox

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Row selection column only takes up the necessary horizontal space
- [ ] Row selection cells line up with row selection header checkbox

**Comment by petertgiles** [comment]
Do the storybook stories need to be updated to use the new "shrink" on their checkboxes?

**Comment by esizer** [comment]
> Do the storybook stories need to be updated to use the new "shrink" on their checkboxes?

Oh, maybe that is too magic but they should automatically shrink. We never have to explicitly define the row selection column for the new tables to they are auto generated for us. I should note, this was only done for the new table. Should we backport this to the `ApiManagedTable` or leave it as is since there is plans to replace?

**Comment by petertgiles** [comment]
Oh, OK, no worries.  I guess it didn't shrink as much as I expected and wasn't sure if it was working.  :laughing:  Now that the Chromatic diffs are in I can see it's working.  Love it.

**Comment by esizer** [comment]
> Oh, OK, no worries. I guess it didn't shrink as much as I expected and wasn't sure if it was working. 😆 Now that the Chromatic diffs are in I can see it's working. Love it.

Yeah, I was expecting it to get smaller as well 😢
