### ISSUE TITLE
🐛 UAT  Sign-in errors

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/gc-digital-talent#8227]
## 🐛 Bug
Getting a 404 when trying to log into access the user dashboard on UAT.  Copy refinement is dependent on having access to up-to-date UAT copy.

## 🦋 Expected Behaviour

I should be able to log in using one of my platform admin user accounts. 
## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Windows / MacOS
- **Browser**:  Chrome, Edge, safari

## 📋 Steps to Reproduce

1. Activate Sign in link from homepage. 
2. Sign-in using platform admin credentials
3. Observe the error in the screen shot below  

## 📸 Screenshot

![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/101275838/279d4abe-290a-45b7-8aef-2ac3f8b3b852)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] User can log into UAT. 
- [ ]  User dashboard copy can be accessed.

**Comment by petertgiles** [comment]
Sounds like @brindasasi solved this.
https://talent-cloud.slack.com/archives/C5Z1KMX5F/p1697490045574089
