### ISSUE TITLE
✨ Improve fieldset a11y descriptions on digital contracting questionnaire

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8230]
## ✨ Feature

Some of the questions on the digital contracting questionnaire rely on large paragraphs or lists of text to inform the form input label.  We have linked these descriptions with aria-describedby but have found that they're not actually read out to the user.  Unfortunately, it seems that any solutions to this problem will require significant form reworking.

Context: https://github.com/GCTC-NTGC/gc-digital-talent/pull/7771#discussion_r1344338515

## 🙋‍♀️ Proposed Implementation

One option considered was to refactor the question from a list followed by yes/no to instead use a checkbox list.  This would force the user to interact with the individual list items though we only record if any boxes are checked.  

Another options would be to rework the form input so that the label of the question doesn't refer directly to the descriptive paragraph.

Is there any technical way to force the fieldsets of radio or checkboxes properly read the descriptive lists when the focus enters the fieldset?

## ✅ Acceptance Criteria

- [ ] All the questions on the digital contracting questionnaire are either self-sufficiently clear or read the needed descriptive text when focused.

**Comment by gobyrne** [comment]
Could be worthwhile revisiting these forms as a whole. But until then, this works even if it's not idea. I will close.
