### ISSUE TITLE
🐛 Pool operator unable to view fellow team members

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#8232]
## 🐛 Bug

Pool operator cannot view fellow team members through the teams table. 

## 📋 Steps to Reproduce

1. Log in as pool@test.com
2. Attempt to view team members for your teams, like Test Team
3. Observe error toast

## 📸 Screenshot

![gif](http://g.recordit.co/lsnw7h9ik5.gif)

## 🙋‍♀️ Proposed Solution

Guessing problem stems from the query in question for the page. 
Pool operators cannot utilize `users`

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/b3354dbe-8654-4a4f-862e-9f2df64723b0)

## ✅ Acceptance Criteria

- [ ] Pool operator abilities work as expected 
- [ ] Add members button only visible for platform admin and community managers

**Comment by esizer** [comment]
> Pool operator abilities work as expected

What do we consider "expected" here? 😅 We discussed what we want to expose but I don't remember what we decided? Can we just use the `view-team-user` permission? 🤔 

Looks like it is failing on `view-any-userBasicInfo` permission since only community managers and platform admins have this permission.

Should we create a new `view-team-userBasicInfo` and check to see if the users are on the same team and have that permission?

**Comment by vd1992** [comment]
Oh yeah, I think we talked about it in meetings but never wrote it down. 
To double check if I recalled correctly
@tristan-orourke 

Pool operators can view their team members but what they can see is just basic info slices right?

**Comment by tristan-orourke** [comment]
Correct. Pool Operators can view the basic info of other people on their team. I'm pretty sure this should _**not**_ require any change to permissions. Instead of using the `users` query, go through the `team` query: `team.roleAssignments.user`.

**Comment by vd1992** [comment]
My mistake on the source of the error, the operator can it seems view fellow team members, it is the table failing to load due to a different query failing. The add team member dialog fails when logged in as a pool operator as it can't query all users to fill the dropdown. 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/82e0db57-2b81-4455-8efd-d2952c6ae152)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/ed2528d4-0b7d-4794-8ad1-dc274c6fcf33)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/8c71a7aa-13fa-485f-997c-3a9dfab03c64)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/0252fb1c-6be3-4b7c-8117-9f1bf4c579f8)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/8c1ebba1-680e-4a85-8b5c-46d8bbe5dd92)

**Comment by vd1992** [comment]
The failing permissions in this case

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/5d94d47e-7709-49be-927e-2c15bae05ed1)

**Comment by tristan-orourke** [comment]
Oh, interesting. Pool Operators don't have permission to add users to a team in the first place! Could we only render `AddTeamMemberDialog` if the user has an appropriate role? (And shift the `useAllUsersNamesQuery` into the Dialog component?)

> Only Platform Admins should be able to viewBasicInfo
Speaking of appropriate roles, this is out of date. Community Managers also get this permission now.
