### ISSUE TITLE
🐛 Cannot delete a team

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#8233]
## 🐛 Bug

Cannot delete teams in the teams table. 

## 🕵️ Details

Edit link works fine. 
Given it is a cell with two actions, the second action probably just is missing or not rendering right. 

## 📋 Steps to Reproduce

1. Navigate to teams table and attempt to delete a team

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/22273ce8-423f-48da-bee7-8d4f743a130d)

## ✅ Acceptance Criteria

- [ ] Remove the delete button from the table

**Comment by petertgiles** [comment]
@Jerryescandon the delete button isn't a mistake, right?  You should be able to delete a team?

**Comment by Jerryescandon** [comment]
> @Jerryescandon the delete button isn't a mistake, right? You should be able to delete a team?

A privilege reserved for the highest of Admins

**Comment by vd1992** [comment]
Think it was working before but maybe got broken along the way with the table updates. 
Has an API point gated by policy and everything

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/d4d2d69e-341f-4301-bfca-d0245d5d2731)

**Comment by brindasasi** [comment]
The issue to implement this feature is still open ? 
https://github.com/GCTC-NTGC/gc-digital-talent/issues/5500

**Comment by brindasasi** [comment]
I remember the last discussion on this with @tristan-orourke , we didn't have UI for this  at that time. We wanted to think about it when we actually need it. We need to define _restore_ strategy before enabling this. 
I believe this button is appearing by mistake.
 
Btw, Here is the original PR that added this policy
https://github.com/GCTC-NTGC/gc-digital-talent/pull/5899

**Comment by vd1992** [comment]
Ah, so get rid of the button then for now?

**Comment by brindasasi** [comment]
Let's confirm it with @tristan-orourke

**Comment by tristan-orourke** [comment]
Yes, let's just hide the delete button for now. Actually implementing deletes for teams requires some more design consideration, as described in #5500.
