### ISSUE TITLE
✨  Pool Candidate Keyword search

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8238]
## ✨ Feature

This issue is to complete the some initial backend work to support #7994.  It will only include one index to get started with.

## 🕵️ Details

We ran two spikes to investiagte some options:
#8090
#8089

As a team we decided that a standalone search service like Meilisearch was probably too much for our needs now but might be a good option in the future if we outgrow an integrated search tool.

We would like to start with using the [Postgresql Full Text Search](https://www.postgresql.org/docs/current/textsearch.html) feature to search against text indexes. There is lots of interest in using [Laravel Scout](https://laravel.com/docs/10.x/scout) as an interface to this tool to manage updates and searches. There's [a package](https://laravel-news.com/postgresql-full-text-search-for-laravel-scout) that might make this easy.

## Question and Answer

Q: I think it also needs to account for policy on search results, filter for can-view.
A: Using the existing search input should mean no changes to policy necessary

Q: we create an individual vectorized column for each field that needs to be indexed
A: Single column for entire user profile as a document

Q: Can we confirm the searchable fields from the list below ?

A:Users table
 email
first_name
last_name
telephone
current_city
Pool_Candiates
notes
All experiences table( work, personal, community, award )
  award - title, issued_by, details
  community - title, org, project, details
  education- areaofstudy, details, institution, thesis
  personal - description, details, title
  work - details, division, org, role
skill - justification

## 🙋‍♀️ Proposed Implementation

h/t @brindasasi 
>    Create a new column in the pool_candidates table to stored the vectorized data

>    Create a function
    ex.
    CREATE OR REPLACE FUNCTION update_profile_snapshot_vectorized() RETURNS TRIGGER AS $$
    BEGIN
    NEW.profile_snapshot_vectorized := to_tsvector('english', COALESCE(NEW.profile_snapshot::TEXT, ''));
    RETURN NEW;
    END;
    You can also combine multiple columns from different tables (ex. email id from users table)

>    Create a trigger for the above

>    Create GIN index for the column

>    To use the Laravel Scout driver , create the model like
    https://github.com/devNoiseConsulting/laravel-scout-postgres-tsvector

## ✅ Acceptance Criteria

- [x] Setup new column to hold index
Full profile = any open text fields the candidate has entered on their profile including screening questions, and notes written by request responders.  No numbers or enums.  Not snapshot.
- [x] Index keeps itself up to date
- [x] Integrate into existing graphql schema pool candidate search filters
- [x] Accepts an array of string search terms

**Comment by vd1992** [comment]
I think it also needs to account for policy on search results, filter for can-view.

**Comment by brindasasi** [comment]
yes. This work should ensure the policy has been respected.
Please correct me if I'm wrong 🙈, 
what we discussed yesterday is
- we create an individual vectorized column for each field that needs to be indexed
- We modify existing candidate search end point to search through these columns as well

is that correct ?
In that case wouldn't it be a lot of columns?
Should we take a hybrid approach? 
Like columns that need specific processing like more sensitive or columns that needs to be given special ranking on the results can be separate and columns that do not require any special processing can be put together in a composite vectorized column.

**Comment by brindasasi** [comment]
id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at timestamp(0) without time zone,
    updated_at timestamp(0) without time zone,
    email character varying(255) UNIQUE,
    first_name character varying(255),
    last_name character varying(255),
    telephone character varying(255),
    preferred_lang character varying(255),
    deleted_at timestamp(0) without time zone,
    sub character varying(255) UNIQUE,
    current_province character varying(255),
    current_city character varying(255),
    looking_for_english boolean,
    looking_for_french boolean,
    looking_for_bilingual boolean,
    bilingual_evaluation character varying(255),
    comprehension_level character varying(255),
    written_level character varying(255),
    verbal_level character varying(255),
    estimated_language_ability character varying(255),
    is_gov_employee boolean,
    current_classification uuid REFERENCES classifications(id),
    location_exemptions character varying(255),
    is_woman boolean,
    has_disability boolean,
    is_visible_minority boolean,
    has_diploma boolean,
    location_preferences jsonb,
    expected_salary jsonb,
    accepted_operational_requirements jsonb,
    gov_employee_type character varying(255),
    department uuid REFERENCES departments(id),
    citizenship character varying(255),
    armed_forces_status character varying(255),
    has_priority_entitlement boolean,
    priority_number character varying(255),
    priority_weight integer GENERATED ALWAYS AS (

**Comment by brindasasi** [comment]
Can we confirm the searchable fields from the list below ? 
**Users table** 
    email character varying(255) UNIQUE,
    first_name character varying(255),
    last_name character varying(255),
    telephone character varying(255),
    preferred_lang character varying(255),
    current_province character varying(255),
    current_city character varying(255),
    bilingual_evaluation character varying(255),
    comprehension_level character varying(255),
    written_level character varying(255),
    verbal_level character varying(255),
    estimated_language_ability character varying(255),
    location_exemptions character varying(255),
    location_preferences jsonb,
    expected_salary jsonb,
    accepted_operational_requirements jsonb,
    gov_employee_type character varying(255),
    citizenship character varying(255),
    armed_forces_status character varying(255),
    priority_number character varying(255)
**Pool_Candiates**
notes 
**All experiences table( work, personal, community, award )** 
title , description , details  fields 

**screening_questions**
question

**Comment by vd1992** [comment]
A bunch of those are enums and so not worth searching I think

**Comment by vd1992** [comment]
I'm not too sure how far you got @brindasasi, but I am a bit concerned about the suggested package. 
It hasn't been updated since April which in itself isn't a big deal but it is a fork of a repo that was abandoned. So, a little concern from me that it might too be abandoned or never really took over supporting the package. 

https://github.com/devNoiseConsulting/laravel-scout-postgres-tsvector 
was forked from 
https://github.com/pmatseykanets/laravel-scout-postgres

**Comment by brindasasi** [comment]
No .. I haven't started anything on the ticket. But the regd. the package I thought the team agreed to try it out. 
@GCTC-NTGC/developers ?

**Comment by vd1992** [comment]
I'm a bit bearish on it due to something being abandoned already being involved. 
This might be a big feature, expanded on a bunch, so I think stability should be a concern, so that things don't break and throw us in a bind when Laravel 11 or something comes around.

**Comment by petertgiles** [comment]
Good, catch.  And it's definitely one guy working on it alone.  :grimacing: 

I was a bit skeptical of using Scout and this addon in the first place.  I haven't gotten too far into this project but it seems like it would be a convenience rather than a necessity.  How much convenience it adds would determine whether we want to add it, I guess.  It looks like it supports PHP 8.2 already so no immediate problems.  And we could drop it and work around that later if it does turn out to be abandoned, maybe?  I guess it's up to whoever picks up this issue to feel it out?
