### ISSUE TITLE
♻️ Remove `cypress-multi-reporters` dependency

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#8247]
## ♻️ Debt/Refactor

The `cypress-multi-reporters` is not necessary.

## 🕵️ Details

> By default, Cypress uses the spec reporter to output information to STDOUT.

REF: https://docs.cypress.io/guides/tooling/reporters

We are only using `spec` right now anyway.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/e36b6c13a7c181bb0de3c8560b9f12e83fbec2cb/apps/e2e/cypress/reporters-config.json#L2

## 📸 Screenshot

![Screen Shot 2023-10-18 at 13 36 54](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/8c708933-67d9-453c-8eb6-5a99045a346c)

## 🙋‍♀️ Proposed Solution

Remove `cypress-multi-reporters` dependency and associated files.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] GitHub actions and reporting remains the same

**Comment by esizer** [comment]
Removed as part of the dependency review:

 - https://github.com/GCTC-NTGC/gc-digital-talent/issues/8308
