### ISSUE TITLE
🔤 Update error message copy for firewall rejections

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8283]
## 🔤 Copy

I was thinking, our current error message if the firewall kicks back a request is something like "check your input for hidden characters".  Now that we know that it's a lot more than just hidden characters that can set that off, should we change it to something like "It looks like there's something wrong with your request.  Please try again or contact support for help."?

## 🕵️ Details

https://github.com/GCTC-NTGC/gc-digital-talent/blob/0d3464a8e34e010c6d2e2c922f5685938854a8e0/packages/i18n/src/messages/errorMessages.ts#L102-L107
https://github.com/GCTC-NTGC/gc-digital-talent/blob/0d3464a8e34e010c6d2e2c922f5685938854a8e0/packages/client/src/exchanges/specialErrorExchange.ts#L24-L30

## 🌎 Localization

_Votre demande n'a pas été complétée. Veuillez réessayer ou contactez notre équipe pour obtenir de l'aide._

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the copy has been added or updated appropriately.

- [ ] Requests rejected by the firewall cause a toast with the message "Your request wasn't completed. Please try again or contact our team for help."

**Comment by gobyrne** [comment]
@petertgiles I feel like this got addressed already, right? If so, please close

**Comment by petertgiles** [comment]
It's less of an issue now that the firewall rules have been tunes but I think this is still needed.  The error message happens less frequently but it's misleading.

**Comment by mnigh** [comment]
@petertgiles what's the acceptance criteria for this issue?

**Comment by petertgiles** [comment]
- [ ] Requests rejected by the firewall cause a toast with the message "...."

**Comment by petertgiles** [comment]
@gobyrne How do you feel about
> Your request wasn't completed. Please try again or contact support for help.

**Comment by mnigh** [comment]
> @gobyrne How do you feel about
> 
> > Your request wasn't completed. Please try again or contact support for help.

can @GCTC-NTGC/designers, @marc-donofrio, or someone else 🧑‍⚖️ to move this issue ahead?

**Comment by substrae** [comment]
@mnigh @petertgiles 

I have designs for this as a part of the new roles we're introducing. I'll add them to this ticket when we're ready to hand them off.

**Comment by mnigh** [comment]
> @mnigh @petertgiles
> 
> I have designs for this as a part of the new roles we're introducing. I'll add them to this ticket when we're ready to hand them off.

@substrae i am a bit confused. this issue is just to add copy in a toast (existing component), why do we need a design?

**Comment by mnigh** [comment]
Right now, the logic does not match the error. If a 403 status or a Request Rejected network error comes back from the request response, we should be displaying a more generic error and not `errorMessages.specialCharacters` ("The text cannot be saved. Please ensure the text has no formatting or special characters and try again.").

https://github.com/GCTC-NTGC/gc-digital-talent/blob/8496939af0aad25bee15aa20b394e884f2111a49/packages/client/src/exchanges/specialErrorExchange.ts#L19-L25

**Comment by substrae** [comment]
@mnigh Oh sorry, I misunderstood - this is specific to submission through the firewall - I thought it was about trying to access a page locked behind the firewall, which is what I'm designing for.
