### ISSUE TITLE
🐛 `testAllTeamMembersCanBeReadFromResponse` intermittently failing

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#8303]
## 🐛 Bug

Seems as though this test is failing due to the randomness of the order being returned.

## 🦋 Expected Behaviour

Order of the response should no matter and test passes consistently.

## 🕵️ Details

We get the expected result but the order is different from the JSON assertion we provide. 

## 📋 Steps to Reproduce

1. Run the test `php artisan test ./tests/UpdateUserTeamRolesTest.php` multiple times
2. Note that is fails some of the time

## 💻 Results

```sh
Unable to find JSON: 

[{
    "data": {
        "updateUserTeamRoles": {
            "id": "c17da304-c94a-4833-bf98-8105bbc88216",
            "roleAssignments": [
                {
                    "role": {
                        "name": "pool_operator"
                    },
                    "user": {
                        "id": "a6fe514f-ea69-42bd-be64-66766745fd34"
                    }
                },
                {
                    "role": {
                        "name": "pool_operator"
                    },
                    "user": {
                        "id": "141d9717-8518-42ff-b4ac-30ae2323cfec"
                    }
                }
            ]
        }
    }
}]

within response JSON:

[{
    "data": {
        "updateUserTeamRoles": {
            "id": "c17da304-c94a-4833-bf98-8105bbc88216",
            "roleAssignments": [
                {
                    "role": {
                        "name": "pool_operator"
                    },
                    "user": {
                        "id": "141d9717-8518-42ff-b4ac-30ae2323cfec"
                    }
                },
                {
                    "role": {
                        "name": "pool_operator"
                    },
                    "user": {
                        "id": "a6fe514f-ea69-42bd-be64-66766745fd34"
                    }
                }
            ]
        }
    }
}].
```

## 🙋‍♀️ Proposed Solution

Probably one of the two:

- Find a way to get assertion to pas regardless of order
- Order response so it is consistent

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Test consistently passes as expected

**Comment by esizer** [comment]
I tried running this 50x locally and it never failed (and it shouldn't've). Yet, I have still seen it pop up from time to time in CI 😖

**Comment by vd1992** [comment]
> I tried running this 50x locally and it never failed (and it shouldn't've). Yet, I have still seen it pop up from time to time in CI 😖

So, just like that other tricky one we had in the past
https://github.com/GCTC-NTGC/gc-digital-talent/issues/7204 solved in https://github.com/GCTC-NTGC/gc-digital-talent/pull/7243
