### ISSUE TITLE
Add the team as a sub-title on Pool page

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#8307]
## 🐛 Bug

When a pool is created, it must be created as part of a team. This assignment is irrevocable. However, when looking at the Process Information page, or the Pool Advertisement edit page, there's no indication of which team its part of. If the user is part of multiple teams, they may want an easy way to see which team this pool is part of. Currently the only way to check is to go back to the pools table, which has a Team column.

I know this has been frustrating for me during testing. Before working on this, it might be worth confirming if this has ever been an annoyance for those using this in production.

## 🦋 Expected Behaviour

`/pools/:id`, `/pools/:id/pool-candidates` and `/pools/:id/edit` pages should indicate somewhere which team the pool is part of.

## 🕵️ Details

Add the pool as a subtitle on pool page (see # 2 in Jerbo's comment below)

## 📸 Screenshot

Table shows team:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/a41d31fb-8336-4391-8cb5-3a0f82945274)

But once working on a specific process, team is nowhere to be found
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/cac83575-0cb2-4ec7-8904-4b422c467ce8)

same on the edit page
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/60ca8aba-3906-4507-bf35-cd6796b322f2)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Team added as subtitle to `/pools/:id`, `/pools/:id/pool-candidates` and `/pools/:id/edit` pages

**Comment by gobyrne** [comment]
@Jerryescandon tell us where and how to display the team name

**Comment by Jerryescandon** [comment]
We had added it as a sub-title here. But we were banking on the headers getting re-worked at some point, since repeating "Process information" 3 times is a bit of an overkill. 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/78d77478-582f-473c-8751-76116d08413e)

If we don't wanna go this route, we can add it in the subtitle after a comma.
