### ISSUE TITLE
✨ Usability improvements to admin Skills table

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#8339]
## ✨ Feature

A few minor changes to the Skills table and edit form to make it easier to update many Skills in one sitting.

> every time i navigate into a skill, the default table set up comes back. Cause I’m doing this on a surface, the edit buttons don’t appear because the screen is too small to see the right side. I have to turn off the columns every time I go back to the screen to see the edit button… or go to the bottom of the table, scroll right and come back up to the skill.

> Would be great if the skills table kept the columns I’ve turned off… basically, keep table preferences navigating in and out of the table during a single work session

## 🕵️ Details

- Hide keywords column by default (it's not generally useful)
- Remove column for Edit button, and make skill name clickable instead. (Or instead, put action column on the left? Goal is not to have to scroll for action button. @Jerryescandon?)
- When submitting skill form is successful, if previous url was the skills table, then go back to the table with filters/state intact

## 🎨 Design File

Include a link to the design file (if it exists).

### 🧑‍🎨 Designer

Refer to @tristan-orourke and @Jerryescandon 

## 📸 Screenshot

Add a screenshot of the new feature (if possible).

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Keywords column is hidden by default on the skills table
- [ ] Link to edit a skill should be on the left of the table
- [ ] If I change table state (filters, search, columns, or page) then edit a skill, and successfully submit changes, I should return to the table in the state I left it.

**Comment by Jerryescandon** [comment]
Yeah, I think making the skill name clickable is the fastest way to get to the skill info/edit page. This would allow us to remove the edit column and keep the keyword column since it would no longer get in the way to reach the edit button.

Agree on the last point too.
