### ISSUE TITLE
🐛 Directive Forms - Missing the date on the error message (UAT env)

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#8344]
## 🐛 Bug
Error message for Expected end date of the contract  field  

## 🦋 Expected Behaviour

Error message should show `Value must be greater than <Expected start date>.`

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Name and version (if possible).
- **Browser**: Name and version (if possible).

## 📋 Steps to Reproduce

1. Navigate to directive form 
2. Just fill out a date for Expected start date and add a value for end date earlier than the start date.
3. Press Enter and observe the text shows as "Value must be greater than ."

## 📸 Screenshot
![Screenshot 2023-10-25 at 3 54 03 PM](https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/202bfa04-cfef-4353-bd40-21689638c3bc)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Error message should show `Value must be greater than <Expected start date>.`

**Comment by vd1992** [comment]
Appears fixed by something

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/0b739cc8-9fa1-47c7-afde-3ad799caf818)
