### ISSUE TITLE
✨ Allow more admin pages to make use of `state.from` to return to table as it was

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#8345]
## ✨ Feature

Basically repeat #8339 for as many admin pages as possible, it would be useful for many of them.

## 🕵️ Details

Add any additional details that could assist with the development of the new feature.

## 🎨 Design File

Include a link to the design file (if it exists).

### 🧑‍🎨 Designer

Include the author of the linked design file's name (or even better, their `@githubUsername`) for future reference.

## 📸 Screenshot

Add a screenshot of the new feature (if possible).

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Admin forms which return user to a table index page when submitted, will return them to the table in the state they left

**Comment by brindasasi** [comment]
![](https://files.slack.com/files-pri/T5ZFRSQ3V-F064NLBJZ0E/image.png)
