### ISSUE TITLE
✨ Assessment steps list

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#8356]
### Assessment step
The assessment step list is meant to capture all decisions made regarding a candidate's application to a recruitment process. If a candidate has been fully qualified, the assessment step list would reflect an application where the skills have been approved at every level. We should be able to track where an application failed and why, and if there are any pending assessment steps required for a candidate.

This assessment step list is located in the application page, and it would replace the current "status" dropdown.

### Assessment step & requirements lists

Each step is an accordion that contains the list of every requirement that an applicant needs to pass for that assessment. Requirements start off in the "To Assess" state. The state can be updated by pool operators using the inputs inside the modal associated with that requirement (see modals section below).

A successful assessment needs to have ALL REQUIRED skills marked as successful/screened in. The ASSET skills DO NOT affect the state of the assessment as a whole.

<details><summary>📸 Screened in / Successful</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/acc8d49e-d3ef-4b3f-a017-59b316012031)

</p>
</details> 

An unsuccessful assessment has at least one or more unsuccessful/screened out requirements that are ESSENTIAL.
<details><summary>📸 Screened out / Unsuccessful</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/3b575ae4-5ae6-4840-931f-ff8f2f2c2c39)

</p>
</details> 

A "To assess" assessment has one or more "To assess" requirements AND no "unsuccessful/screened out" ones.
<details><summary>📸 To assess</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/f3a78588-57cb-42e5-9872-24d272a98aa4)

</p>
</details> 

### Aria labels

<details><summary>Details</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/6880cb89-039f-43a4-94dc-d8e6b8c76629)

</p>
</details> 

## 🎨 Design File

[Design file](https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Pools---Record-of-Decision?type=design&node-id=5832%3A119940&mode=design&t=8dKYoZwQmehsoZIP-1) by @Jerryescandon 

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria 
- [ ] Assessment step list is located in the application page instead of application status
- [ ] Each assessment step is listed as accordion and start with "To assess" status (yellow icon)
- [ ] Each assessment step will be updated to "Successful" (Green icon) or "Unsuccessful" (Red icon) based on the decision logged via the modal dialog 
- [ ] A successful assessment needs to have ALL ESSENTIAL skills marked as successful/screened in. 
- [ ] If one of the essential skills are failed, the assessment step needs to be marked as "Unsuccessful" 
- [ ] A "To assess" assessment has one or more "To assess" requirements AND no "unsuccessful/screened out" essential skills
- [ ] The ASSET skills DO NOT affect the state of the assessment step status.
- [ ] For each step , there should be a link "Assess this skill" that opens up the corresponding modal
- [ ] Once the decision is saved for an assessment step, the link should show "Reassess this skill" and allow the user to edit
- [ ] Expand all should expand all steps

**Comment by petertgiles** [comment]
Jerbo might want to tweak the overall status calculation.  Pulling out for now.

**Comment by tristan-orourke** [comment]
The design here doesn't seem to match the [newest version](https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Pools---Record-of-Decision?type=design&node-id=6874-39127&mode=design&t=cSnVNHwBnVsLczoP-0) in figma. I'll just block this while I confirm if this needs updating.

**Comment by tristan-orourke** [comment]
Replaced with #8961
