### ISSUE TITLE
✨ Mutation updates for assessment step actions

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8362]
## ✨ Feature

The assessment step builder page has suggested a few changes for the assessment step mutations.

## ✅ Acceptance Criteria

- [x] If screening questions are added or removed, DONT automatically create an assessment step
- [x] If a screening question step is added/updated, force it sort order 2 regardless of the mutation parameters and reflow the sort order of other steps in the same pool
- [x] If a screening question step is added and there is already a screening question step, error out the mutation
- [x] If the screening question step is deleted, also hard delete all the screening questions
- [x] If the regular screening question delete mutation is called, do a HARD delete
- [x] Custom mutation to allow create/edit screening question assessment step with screening questions?  Also should have a sync method, not create/update/delete. Update the Assessment Plan builder page to use this new mutation.
- [x] Custom mutation to allow syncing multiple assessment steps in one mutation for reordering?  Or just for moving? 
  Update the Assessment Plan builder page to use this new mutation.

**Comment by vd1992** [comment]
> If a screening question step is added/updated, force it sort order 2 regardless of the mutation parameters and reflow the sort order of other steps in the same pool

Might it be easier to go with Tristan's suggestion of just as Application screening is locked to `sortOrder = 1`, do the same for screening questions and lock `sortOrder = 2`, and then additional assessments get added at `sortOrder = 3` and above. So, a placement at 2 is not always present if a process has no screening

**Comment by petertgiles** [comment]
> Might it be easier to go with @tristan-orourke 's suggestion of just as Application screening is locked to `sortOrder = 1`, do the same for screening questions and lock `sortOrder = 2`

Yeah, that would be better than reflowing the others.    We would have to make sure that any mutation calls for other step types have a floor of "3" for sort order then.
