### ISSUE TITLE
✨ Repeater updates for assessment step actions

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8363]
## ✨ Feature

The assessment step builder page has suggested a few changes for the assessment step mutations.

Or do we want to abandon this in favor of [a non-form component](https://github.com/GCTC-NTGC/gc-digital-talent/issues/8161)?

## ✅ Acceptance Criteria

- [ ] Allow preventing individual actions (move up, move down, delete, edit) independently for each fieldset
- [ ] Remove numOfLockedItems prop in preference for above
- [ ] Figure out solution for returning focus to edit and delete buttons from dialog (add custom delete button like custom edit button?)
- [ ] Figure out solution to maintain focus on a move button after a move operation

**Comment by brindasasi** [comment]
we can close this issue in favour of implementing https://github.com/GCTC-NTGC/gc-digital-talent/issues/8161

**Comment by brindasasi** [comment]
We re-open this issue in favour of closing #8161 
we realized it would be lot easier to update rather than the new component
