### ISSUE TITLE
✨ Education requirement for executives

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#8394]
## ✨ Feature

Need this new education requirement for executives

## 🕵️ Details

This education requirement actually has 3 options, so we will need to have a slightly different UI. We will also need to account for it on the application (education step), then on snapshot and snapshot download.

On the education step, "I meet the professional designation option" is the new option. 

**QUESTION** The modified text for the "degree" and "applied work experience" steps also shows up here right?

### Education section on job poster
![image (16)](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/9d82af7d-50bb-47b3-b1e7-c97de5d81166)

### New option on education step of application
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/4561e606-28bd-4ada-b326-e189b0bddc94)

### Snapshot needs to be updated to show the new option
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/b6063398-eeec-4259-b9db-fe61ccfdbfc1)

## 🌎 Localization

Use this copy in the sections. The section headers can stay as they are in the screenshot. But for EX we are gonna use this standard text (including for "applied work experience").

**English**
- [Eligibility](https://www.canada.ca/en/treasury-board-secretariat/services/staffing/qualification-standards/core.html#elig) for a recognized professional designation in one of the provinces or territories of Canada
- [Acceptable](https://www.canada.ca/en/treasury-board-secretariat/services/staffing/qualification-standards/core.html#acce) combination of education, training and/or experience
- Graduation with a [degree](https://www.canada.ca/en/treasury-board-secretariat/services/staffing/qualification-standards/core.html#deg) from a [recognized post-secondary institution](https://www.canada.ca/en/treasury-board-secretariat/services/staffing/qualification-standards/core.html#rpsi)

This copy goes at the bottom of the "degree" section. I don't have it translated though:
Have a degree from outside Canada? [Learn more about foreign degree equivalencies](https://www.canada.ca/en/public-service-commission/jobs/services/gc-jobs/degree-equivalency.html).

Also, change "2 years post secondary" to "Graduation with degree" in the section header please 

**French**
- [Admissibilité](https://www.canada.ca/fr/secretariat-conseil-tresor/services/dotation/normes-qualification/centrale.html#admis) à un titre professionnel reconnu dans une province ou un territoire du Canada
- Agencement [acceptable](https://www.canada.ca/fr/secretariat-conseil-tresor/services/dotation/normes-qualification/centrale.html#acc) d’études, de formation et/ou d’expérience
- [Grade](https://www.canada.ca/fr/secretariat-conseil-tresor/services/dotation/normes-qualification/centrale.html#Dipl) d’un [établissement d’enseignement postsecondaire reconnu](https://www.canada.ca/fr/secretariat-conseil-tresor/services/dotation/normes-qualification/centrale.html#eepr)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] New education section on job advertisements when EX classification is selected
- [ ] New option is available to select on the job application 
- [ ] New option displays correctly on the application snapshot 
- [ ] New option displays correctly on the application snapshot download

**Comment by brindasasi** [comment]
We would seed locally and admins would add it in prod and UAT environments
