### ISSUE TITLE
✨ Log changes to key models

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#8395]
## ✨ Feature

We want to log when important models are created, updated or deleted. We can set this up to happen automatically for our chosen models.

## 🕵️ Details

At minimum, an activity log entry should include
- what entity was changed
- who initiated the change (if it was a logged-in user)
- what attributes were changed

For now, lets add this activity logging to the following models:
- User
- Pool
- PoolCandidate
- Requests

These will give us audit logs on changes to Users, and history on the flow through the pipeline for Pools, applications, and requests.

## 🎨 Design File

Include a link to the design file (if it exists).

### 🧑‍🎨 Designer

Include the author of the linked design file's name (or even better, their `@githubUsername`) for future reference.

## 📸 Screenshot

Add a screenshot of the new feature (if possible).

## 🙋‍♀️ Proposed Implementation

Use https://spatie.be/docs/laravel-activitylog/v4/introduction.

Set it up to [log model events](https://spatie.be/docs/laravel-activitylog/v4/advanced-usage/logging-model-events).

QUESTION: are there any attributes we should ignore logging? We don't have to worry about passwords, but is there anything else sensitive?
Ans: Log everything except sensitive info. 

QUESTION: do we want to add any special descriptions or values to certain events? For example, we could treat "change status" as a special event, with its own description or key/values, instead of just another UPDATE event. 
Ans: No

QUESTION: Its possible when setting up model-event logging to log changes to related models as well. We should consider if we want to do that now for any of these models. 
Ans: We could split that into sep ticket. No for now. Please log changes to applicant filter as part of search requests. 

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Basic model-event activity logging is set up for Users, Pools, PoolCandidates, and PoolCandidateSearchRequests
- [ ] Log everything and add the exception for sensitive columns ( password)
- [ ] Single activity_log table for all activity logs. Include Model name as part of each record so that we can filter that out. 
- [ ] Sanity tests to verify the logging as diff user ( test to log as per the logged in user , activities are logged properly etc)

**Comment by brindasasi** [comment]
@tristan-orourke 
how do you envision this ? Single activity table per model ?

**Comment by brindasasi** [comment]
we include all fields from user table
