### ISSUE TITLE
 ✨ Modal for screening decisions

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#8397]
## User Story

As a pool operator , I want to have a modal dialog to record my decisions for each type of assessment step so that I can have a clear visual of a candidate's assessment status.

### MODALS

Inside every assessment list, there is a list of requirements with links to a modal where pool operators can create the "record of decision"

There are 4 possible modals that can appear on this page:
1. Application screening education requirement modal
2. Application screening skill modal
3. Screening questions skill modal
4. Generic assessment skill modal

#### Application screening education requirement
Modal includes:
1. Selected requirement option: Education requirement option selected by the applicant
2. Supporting Evidence: Education requirement justification selected by the applicant (experiences the applicant selected on the education requirement step of the application)
3. Requirement decision: **Education requirement ROD** 

<details><summary>Not sure</summary>
<p>

![Not sure](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/ffb032ee-383f-4215-b2fe-d452227a82b0)

</p>
</details> 

<details><summary>Demonstrated</summary>
<p>

![Demonstrated](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/77e418a3-43cd-41b6-9d1d-9c7c157006a4)

</p>
</details> 

<details><summary>Not demonstrated</summary>
<p>

![Not demonstrated](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/0a480b83-5fac-416c-8ce7-f38a122192b3)

</p>
</details> 

#### Application screening skill 
Modal includes:
1. Skill and level definition
2. Supporting evidence: Experiences and skill justifications by the applicant (only for the relevant skill) 
3. Requirement decision: **Skill ROD** 

<details><summary>Demonstrated</summary>
<p>

![Dialog](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/9531cb56-6a8f-4b35-80ee-616445d2f155)

</p>
</details> 

<details><summary>Not demonstrated</summary>
<p>

![Dialog-2](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/7a3b7669-f2a9-4a27-bae0-bf7c249cd28f)

</p>
</details> 

<details><summary>Not sure</summary>
<p>

![Dialog-1](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/7cef6215-3ff6-4b85-9d64-8677a5f4da36)

</p>
</details> 

<details><summary>With skill and level definition expanded</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/546e9a49-6d13-447a-afe5-2431b3da99cc)

</p>
</details> 

#### Screening questions skill
Modal includes:
1. Skill and level definition
2. Screening questions and the answers provided by the applicant
4. Requirement decision: **Skill ROD** 

<details><summary>With screening question expanded</summary>
<p>

![Screening question evaluation](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/eb193c12-02e9-406c-9473-f95e0907e92b)

</p>
</details> 

#### Generic assessment skill
Modal includes:
1. Skill and level definition
2. Notes for this assessment: Assessment notes
5. Requirement decision: **Skill ROD** 

<details><summary>Details</summary>
<p>

![Generic assessment skill modal](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/94e70db2-8125-4443-9052-335f7639c3a1)

</p>
</details> 

#### Skill ROD

When the skill is NOT demonstrated, the notes are optional by default.  IF The user selects "Other reason for screening out", then the notes are required.

<details><summary>Demonstrated skill options</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/3c683292-1e93-4c18-9212-033ad73bf764)

</p>
</details> 

<details><summary>Not demonstrated skill options </summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/7f6597f2-7227-4b57-9188-10e6e193536e)

</p>
</details> 

#### Education (ROD)

When the education is NOT demonstrated, the notes are optional by default.  IF The user selects "Other reason for screening out", then the notes are required.

<details><summary>Demonstrated education options</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/ec041678-3593-4762-bada-6bb1800b4043)

</p>
</details> 

<details><summary>Not demonstrated</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/c0d87048-093e-4de2-a1ad-dd7dc14f0c37)

</p>
</details> 

## 🎨 Design File

[Figma design file](https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Pools---Record-of-Decision?type=design&node-id=5832%3A119940&mode=design&t=8dKYoZwQmehsoZIP-1) 

[Custom icons folder](https://drive.google.com/drive/folders/1rMC4d6hkmufcVeCvhd_buYBiClIslaKf?usp=drive_link)

Designer: @Jerryescandon 

## 📸 Screenshot

Add a screenshot of the new feature (if possible).

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] All forms are integrated with API and submit 
- [ ] Create and Update decisions should work

**Comment by brindasasi** [comment]
@Jerryescandon , @BrookeCameron  Could we get the combined icons for the RoD ?

**Comment by Jerryescandon** [comment]
I have added a link to a folder with custom icons.

In addition, at the request of Lauren and Anne Marie, we are changing all thumb-up icons for checkmark icons and all thumb-down icons for 'x' marks.

I am updating all images to reflect this.
