### ISSUE TITLE
🐛 Edit advertisement information page - skills dialog

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#8398]
## 🐛 Bug

On the edit a pool page. 
- Cannot set a skill level
- Mismatched copy up top, "your career timeline" 

## 📋 Steps to Reproduce

1. Navigate to editing a pool
2. Click adding skills button

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/0683547f-5b2c-45a2-8bc3-9935e8083016)

## ✅ Acceptance Criteria

- [ ] Copy to use: "Add a skill to this process"

**Comment by brindasasi** [comment]
We realize this ticket might need a refactoring. 
The dialog that has been used here , is a common component that has been used in career timeline and directive forms as well. 
Eric suggests instead of using contexts, we could just pass in custom string for titles.

**Comment by brindasasi** [comment]
@GCTC-NTGC/designers can help us with what copy should be displayed for the title and the subsection , when this dialog appears in Edit Pool Advertisement page

**Comment by Jerryescandon** [comment]
For the title:
`Find and link a skill to this process`

I think we should remove the subtitle.

**Comment by RM-1978** [comment]
> For the title: `Find and link a skill to this process`
> 
> I think we should remove the subtitle.

I agree @Jerryescandon with removing the subtitle, but I also think we should write the title in plainer language. I suggest: 
`Add a skill to your career timeline`

**Comment by Jerryescandon** [comment]
> `Add a skill to your career timeline` or `Add a skill you gained through this experience`.

I like this, in this case we are adding skills to job advertisements, so it should be:
`Add a skill to this process`
