### ISSUE TITLE
♻️ Reduce initial bundle size used by Framer Motion

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8404]
## ♻️ Debt/Refactor

Currently, Framer Motion makes up a pretty big chunk of our initial bundle.  Can we reduce this?

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/1af472a4-204c-4f80-a342-74335caa5939)

Context:
https://github.com/GCTC-NTGC/gc-digital-talent/issues/7840#issuecomment-1789601147

## 🙋‍♀️ Proposed Solution

Simply moving Framer to a lazy loaded bundle might work only if that bundle isn't immediately required by a page load.  I know the IAP site uses Framer, for example.

On the Framer site they have a link discussing how to reduce bundle size: https://www.framer.com/motion/guide-reduce-bundle-size/.  Perhaps the LazyMotion component can defer the loading until after the page has loaded.  Or perhaps we can import only what we need (like we do with Lodash) to help tree shaking.

Or perhaps we can use react-spring instead of framer-motion.
    https://bundlephobia.com/package/react-spring@9.7.3
    https://bundlephobia.com/package/framer-motion@10.16.4

## ✅ Acceptance Criteria

- [ ] The initial bundle size used for animation is reduced for a home page load.
- [ ] If lazy loading is used, the additional bundle isn't immediately required for a home page load.

**Comment by esizer** [comment]
I did the changes they recommended and it actually resulted in a larger bundle? 😖 


![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/cb269900-ea58-4617-bca1-12af0900d493)


## Before

![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/31321a35-d58b-42fb-b9b6-050c9e937f59)

![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/4b6319aa-3667-4336-a742-6d979e0121b1)

## After

![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/b9d5ac08-4d23-4b42-b166-5052dc37a390)

![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/c5ea6adc-84b4-4276-830b-e3468c128df6)
