### ISSUE TITLE
♻️ Consolidate enum getter functions

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#8411]
## ♻️ Refactor

Getter functions for enums should be consolidated into a single DRY function as they all do the same thing.

## 🕵️ Details

There are many functions, but some examples include `getYesNoUnsure`, `getContractAuthorities`, `getContractValueRange`, etc. They all work like this:

```
export const getType = (
  equityGroup: keyof typeof type,
): MessageDescriptor =>
  getOrThrowError(
    types,
    equityGroup,
    `Invalid '${type}'`,
  );
```

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] single DRY function replaces all enum getter functions
- [ ] references to function calls update to use new generic function
- [ ] Type safety maintained

**Comment by esizer** [comment]
I have a working idea, just want to run it by before I go and do the work to convert everything. I don't tihnk it will reduce the amount of code we have but, it will mean we only need to import one function instead of choosing between 40 similar ones 🤷‍♀️ 

```tsx
type AllEnums = AwardedTo | AwardedScope | ...; // Union type of all enums

// Constrain the type for use in map (otherwise we get an overload error)
type ApiEnum = {
  [key in AllEnums]: string;
};

// This will be a massive map containing all possible messages
const enumMessageMap = new Map<keyof ApiEnum, MessageDescriptor>([
  /**
   * Awarded To
   */
  [
    AwardedTo.Me,
    defineMessage({
      id: "pPPm5b",
      defaultMessage: "Me",
      description: "The award was given to me.",
  }),
  ],
]);

export function getEnumMessage(value: keyof ApiEnum): MessageDescriptor {
  const message = enumMessageMap.get(value);

  if (!message) {
    throw new Error(`Invalid API key ${value}`);
  }

  return message;
}


{intl.formatMessage(getEnumMessage(AwardedTo.Me))}
```

**Comment by yonikid15** [comment]
> I have a working idea, just want to run it by before I go and do the work to convert everything. I don't think it will reduce the amount of code we have but, it will mean we only need to import one function instead of choosing between 40 similar ones 🤷‍♀️

This looks great, but there are some Enum key's that get used twice for different contexts. For example, `technicalSkillLevels` and `technicalSkillLevelDefinitions`. So, you would need to import the message maps and add it as a second param.. or create a separate file.

**Comment by esizer** [comment]
> This looks great, but there are some Enum key's that get used twice for different "contexts". For example, `technicalSkillLevels` and `technicalSkillLevelDefinitions`. So, you would need to import the message maps (for that context alone) and add it as a second param 😢 ..or create a another file with localized constants for different "contexts".

So, after talking with @tristan-orourke I think we are going to close this issue as not planned 😢 

We have a few reasons including the one @yonikid15 mentioned. While it would ne nice to make this a little more DRY, we still see some value about being explicit about what we are getting. Unles someone can figure out how to constrain the value being passed in to a specific enum, this could make our types a little too permissive.

As an example, if we want to get skill level, we could make some mistakes.

```tsx
   // This totally fine with the approach I suggested
   const skillLevel = getMessage(PoolSkillType.Essential);
   
  // This will not work under our current approach
   const skillLevel = getSkillLevel(PoolSkillType.Essential);
```

Unless someone with more TypeScript skills than me wants to poke around and try and solve this! 😄
