### ISSUE TITLE
♻️ Remove `FEATURE_RECORD_OF_DECISION` flag

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#8415]
## ♻️ Debt/Refactor

Remove the `FEATURE_RECORD_OF_DECISION` flag some time after it has been enabled.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] Flag removed from codebase
- [ ] Flag removed from IaC
- [ ] Remove debt code (eg. RODViewPoolCandidatePage.tsx)

## 🛑 Blockers
```[tasklist]
### Blocked By
- [ ] #8834
```

**Comment by mnigh** [comment]
@tristan-orourke is this issue being blocked by any other issues, or ones that haven't been created yet?

**Comment by tristan-orourke** [comment]
Not blocked by any issues... let's check in at scrum.
