### ISSUE TITLE
⚙️ Application Information Component

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#8453]
## ⚙️ Summary

The existing application snapshot display on the Candidate Information page at `/admin/candidates/:poolCandidateId/application` is to be replaced with this new, accordion styled listing.  Following the accordion is the career timeline shown as a list of experience cards.

## 🎨 Design File and 🧑‍🎨 Designer

@Jerryescandon 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/8769a6cb-89d9-4d1b-8598-6697528e18f0)

![Screenshot 2023-11-16 at 10 08 37 AM](https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/37a50227-68d1-4c0e-a940-6545b43372ab)
https://www.figma.com/proto/em5ArPr044YaIe1Vb1zCZz/Pools---Record-of-Decision?type=design&node-id=6874-39127&t=44EpZJTrDP9LlAeH-0&scaling=min-zoom&page-id=5437%3A34104&starting-point-node-id=6251%3A25181

> [!NOTE]  
> For all layout and spacing guidance, including how this component should respond on smaller devices, please see the Figma file.

## :question: Question & Answer

Q: Where did the "snapshot as code" toggle go?
A: We're going to try to go without it.  If we're careful, the listing should be able to handle changes gracefully.

Q: What about the view experience link on experience cards?
A: This should link to the experience _in the snapshot_ so it should never be missing.  It should scroll down to the experience in the career timeline section of this same page.

## Acceptance Criteria

- [ ] Changes hidden behind Record of Decision feature flag
- [ ] Candidate Application snapshot should be displayed here 
- [ ] Default state - all sections are collapsed 
- [ ] Expand All - should expand all sections including the nested accordions
- [ ] All information is read only ( Ignore if you see Edit in the screenshot) 
- [ ] Print application - existing application snapshot print functionality 
- [ ] No nested accordions - Education & experience should be just listed as above screenshot 
- [ ] View Experience - Should be linked to the experience in the career time line
- [ ] Career timeline subsection with sort and filter controls
- [ ] Accordions should keep their title as is when they got expanded ( No "Hide content" )

**Comment by brindasasi** [comment]
@Jerryescandon @substrae Could you talk it thru to simplify this design further ?

**Comment by mnigh** [comment]
@brindasasi aren't design issues meant to for the design repo? https://github.com/GCTC-NTGC/design-gc-digital-talent/issues. wondering why we need the `design` and `updates in progress` labels?

**Comment by brindasasi** [comment]
I think it came from the component template.. we can remove it

**Comment by Jerryescandon** [comment]
>  View Experience - Should be linked to the experience in the career timeline ( do we need this ? What if the user deleted that? )

The career timeline is ALSO part of the "Application snapshot" information. It is not from the up-to-date profile. It should remain consistent with the information submitted at the time of application, meaning, any relationship between the skill and career and experiences should exist.

**Comment by petertgiles** [comment]
Pulling into "Ready to develop" to replace #8356 which was pulled out.
