### ISSUE TITLE
🐛 Admin navigation icons do not match

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#8458]
## 🐛 Bug

The admin navigation icon do not match current page for classifications, skills, and skill families.

## 🦋 Expected Behaviour

The icon of the current page should match that of the current navigation item.

## 📋 Steps to Reproduce

1. Navigate to `/admin/settings/classifications`
2. Observe mismatched icons

## 📸 Screenshot

![Screen Shot 2023-11-09 at 14 39 54](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/6cd15cd9-06b9-4bcd-9a77-26c8b00f17ab)

![Screen Shot 2023-11-09 at 12 36 38](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/0d613939-d22d-4fda-a0ee-d999a4821ca5)

![Screen Shot 2023-11-09 at 12 36 28](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/1b3ecb2c-3cc5-4210-86ec-30e82bc4c30b)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] icon of the current page matches that of the current navigation item

**Comment by mnigh** [comment]
@GCTC-NTGC/designers is this something you are able to address?

**Comment by Jerryescandon** [comment]
I think some of these have been preemptively updated, but I think this will be addressed on https://github.com/GCTC-NTGC/gc-digital-talent/issues/8175

**Comment by petertgiles** [comment]
In scope of #8175
