### ISSUE TITLE
🐛 Buttons using positive actions are using negative colour

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#8460]
## 🐛 Bug

Create and save actions are using red buttons. Red buttons are usually interpreted as negative actions.

## 🦋 Expected Behaviour

They should not use red which is used for negative actions such as delete.

## 📋 Steps to Reproduce

1. Navigate to `/admin/pools/create`
2. Observe red button for creating a pool

## 📸 Screenshots

![Screen Shot 2023-11-09 at 12 04 16](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/33e3da55-b63d-4722-9c16-599d7fbfc66a)
![Screen Shot 2023-11-09 at 12 04 40](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/93ed66e9-d156-4b0d-9691-3aad20f8d62c)
![Screen Shot 2023-11-09 at 12 06 46](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/387c6f2b-c1f8-41df-8f16-a8ece72d0145)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] non-destructive buttons should not be red and replaced by`secondary` colour

**Comment by Jerryescandon** [comment]
I agree, I checked the Figma and it shows secondary color on these. Maybe this was just overlooked during review. 🤷 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/af70101f-5436-4f50-9b31-42f410c697b4)

**Comment by mnigh** [comment]
> I agree, I checked the Figma and it shows secondary color on these. Maybe this was just overlooked during review. 🤷
> 
> ![image](https://user-images.githubusercontent.com/16977254/283525132-af70101f-5436-4f50-9b31-42f410c697b4.png)

@Jerryescandon how about the Create new pool page button Create new pool, what colour should that be?

**Comment by Jerryescandon** [comment]
> how about the Create new pool page button Create new pool, what colour should that be?

Secondary as well please. 🙏
