### ISSUE TITLE
♻️ `UserPlacementPage` is empty and not linked anywhere

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#8462]
## ♻️ Debt

The component and page `apps/web/src/pages/Users/UserPlacementPage/UserPlacementPage.tsx` is not referenced and is an empty page. The page was added as a placeholder #5693.

## 🙋‍♀️ Proposed Solution

1. Delete `apps/web/src/pages/Users/UserPlacementPage/UserPlacementPage.tsx` file
2. Remove reference in `Router`
3. Remove reference in `useRoutes` 
4. Removed any unused i18n strings

https://github.com/GCTC-NTGC/gc-digital-talent/blob/21dde6b7475efd4d9220fc7836365f81e97410f7/apps/web/src/components/Router.tsx#L399-L406

https://github.com/GCTC-NTGC/gc-digital-talent/blob/21dde6b7475efd4d9220fc7836365f81e97410f7/apps/web/src/hooks/useRoutes.ts#L99-L100

## 📸 Screenshot

![Screen Shot 2023-11-09 at 16 02 30](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/f79fbcdb-409b-4c44-a879-f986f76d1450)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] `UserPlacementPage` is no longer part of codebase

**Comment by vd1992** [comment]
Easter egg!
