### ISSUE TITLE
♻️ Implement `react-hook-form` disabled option

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#8467]
## ♻️ Debt/Refactor

The latests version of `react-hook-form` allows setting a `disabled` option to disabled form inputs. It could be useful to start implementing this on our forms.

## 🕵️ Details

We are currently attempting to use the `fetching` property from `urql`, or have our submit handlers return promises to use the `isSubmitting` from `react-hook-form`. Neither of these are working very well, so we could use this to disabled the form inputs and submit buttons.

## 🙋‍♀️ Proposed Solution

```tsx
const Form = () => {
  const [disabled, setDisabled] = useState<boolean>(false);
  
  const useForm({ disabled });
  
  const handleSubmit = () => {
     setDisabled(true);
     executeMutation()
       .then(() => {
         // Do some stuff
         setDisabled(false);
       });
  }
  
  return (
    <FormProvider>
      <Submit disabled={disabled} />
    </FormProvider>
  );
}
```

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] Forms control the `disabled` option
- [ ] Form inputs and submit buttons are disabled while submitting\
- [ ] Scope - BasicForm component

**Comment by vd1992** [comment]
So does the scoping include replacing all existing implementations then?

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/af845bfd-8c72-4074-a2ab-c1e7200b7691)

**Comment by esizer** [comment]
> So does the scoping include replacing all existing implementations then?

I think so, but not sure 😅

**Comment by vd1992** [comment]
The `BasicForm` component does not contain a submit element. 
The submit element is passed in as children, so its state is controlled a level above. 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/16413786-ea04-4017-b841-550b32ee0e72)

A level above like here in this case the form actions component

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/f9a02ef7-7476-4028-b3f2-ca1ad98e6626)

Does this make things tricky?

**Comment by vd1992** [comment]
Icing for now per agreement on practicality/effectiveness with Eric

**Comment by esizer** [comment]
I think we are in a good spot for now with this. Can't see it providing a ton of benefit so will close.
