### ISSUE TITLE
🐛 Using scrollbar to scroll tall dialogs closes the dialog

### ISSUE THREAD

**Issue by marc-donofrio** [GCTC-NTGC/gc-digital-talent#8472]
## 🐛 Bug

When trying to use a tall dialog it cannot scrolled down to the bottom with the scrollbar.  Clicking on the scrollbar immediately closes the dialog.  Scrolling with a mouse wheel or trackpad works OK.

## 📸 Screenshot

[unable to add more than three skills.docx](https://github.com/GCTC-NTGC/gc-digital-talent/files/13322226/unable.to.add.more.than.three.skills.docx)

https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/22e947f6-a8c4-4372-8220-85fd7d97cf2b

## ✅ Acceptance Criteria

- [ ] Click-and-drag on the page's scrollbar should scroll the dialog, not close the dialog.

**Comment by petertgiles** [comment]
@substrae Could I ask for a desfam perspective on this one?  Technically I can replicate this on my tablet in Edge.  Clicking on the "outer" scrollbar does in fact close the dialog and the very bottom of the dropdown is hidden unless I scroll to the bottom of the list.  Is there a bug here?  What is our acceptance criteria?

**Comment by brindasasi** [comment]
@GCTC-NTGC/designers  any suggestions?

**Comment by substrae** [comment]
@petertgiles @brindasasi 

Sorry for the delay! So clicking the scroll bar shouldn't trigger the dialog to close 🤔 That solves the problem, right? It does seem odd to me though, that the user can't scroll with their mouse wheel? Is this something you also noticed Peter?

**Comment by petertgiles** [comment]
> Is this something you also noticed Peter?

Yeah, the scrollbar doesn't work on any tall dialog boxes.  For example, the Indigenous declaration, in Firefox.

https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/22e947f6-a8c4-4372-8220-85fd7d97cf2b

> that the user can't scroll with their mouse wheel?

Yes, the scroll wheel (or two-finger scroll) works fine which is probably why we never noticed that the actual scroll bar doesn't work.

**Comment by substrae** [comment]
@petertgiles Thanks for the video - this looks like a problem with how our dialog component handles exterior clicks - it's possible the event listener is sitting on an element that encompasses the scroll bar, which would capture clicks on the bar itself. Ideally the even should only trigger when the background is clicked.
