### ISSUE TITLE
♻️ Rename PHP functions to meet convention

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#8479]
## ♻️ Debt/Refactor

Per our convention and https://www.php-fig.org/psr/psr-1/#43-methods
Methods should have camel-case naming

## 🕵️ Details

Example snake-cased methods

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/f8ad8f91-bb63-4479-85f1-ea908ccdf6ba)

## 🙋‍♀️ Proposed Solution

Rename to camel case. 

## ✅ Acceptance Criteria

- [ ] Camel casing the main way anywhere you find

**Comment by petertgiles** [comment]
Camel case seems consistent with the PHPUnit docs, too. https://docs.phpunit.de/en/10.4/writing-tests-for-phpunit.html
