### ISSUE TITLE
♻️ Form Repeater refactor

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8491]
## ♻️ Debt/Refactor

The repeater has been updated and extended a few times.  It might be time for a refactor to freshen it up.

Two things come to mind:
1. Focus on the up and down buttons is lost when the cards move.   This is not good for a11y.
2. The API is very large and a lot of redundant data has to be passed down to the fieldsets.  It would be nice if there was an internal context that the fieldsets could access.

## Proposed Solution

Look at card repeater created in #8161 for inspiration.

## ✅ Acceptance Criteria

- [ ] Focus on the up/down buttons is not lost when the cards move.
- [ ] Fieldsets don't have to have redundant data passed into them that the root already knows.

**Comment by petertgiles** [comment]
This component should become a lot simpler when #8161 is done.

**Comment by tristan-orourke** [comment]
@petertgiles is there still work left to do on this since #8161?

**Comment by petertgiles** [comment]
As far as I know, yes.  However, 8161 is a great example, now, of the changes to be made.
