### ISSUE TITLE
🐛 Digital Services Contracting Questionnaire error links do not work

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#8537]
## 🐛 Bug

When clicking an error message link on the Digital Services Contracting Questionnaire, neither the **Expected start date of the contract** and **Expected end date of the contract** links work.

## 🦋 Expected Behaviour

When clicking the links, they should each navigate to the field that they describe.

## 📋 Steps to Reproduce

1. Navigate to `directive-on-digital-talent/digital-services-contracting-questionnaire`
2. Click **Submit** button at the end of the form
3. Select the **Expected start date of the contract** error message (or the **Expected end date of the contract**)
4. Observe link does not have any effect in navigation

## 🎥 Screen recording

https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/df06ad4b-2d96-47a3-a2ba-4b6e2a16db54

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] clicking on the field name navigates to the form field

**Comment by vd1992** [comment]
Investigating

Error set wants to link to this, `contractEndDate` 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/664849d2-6e6d-48ab-b193-d70c652908b6)

But the date input generates a pair of inputs with a suffix attached, like `contractEndDateYear`

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/4a3e1faf-2d19-4cc8-9752-1d736b9e8caa)

Navigating to `contractEndDateYear` instead works

https://recordit.co/yRRqKdCAlF

Solution may be page specific or require changes to component `DateInput`
