### ISSUE TITLE
♻️ Migrate the Terms and conditions, Privacy policy pages to the main application

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#8549]
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/319804b2-e555-4d31-b094-92a8a5070e7a)

## ✨ Summary

[Visit the Terms Figma file](https://www.figma.com/file/SzJ4cEsK4kADalruL2HPvT/Candidates---Terms-and-conditions?type=design&node-id=1-3&mode=design) • [Visit the Privacy Figma file](https://www.figma.com/file/nYPGodo0LxtK26DjzHzUn7/Candidates---Privacy-policy?type=design&node-id=1-3&mode=design) • Contact @substrae with design questions

This ticket's primary aim is to migrate the _Terms and conditions_ and _Privacy policy_ pages off the Talent Cloud report website and onto the main application and static content pages. There are also a few fixes for incorrect heading sizes.

```[tasklist]
### ✅ Requirements
- [x] Migrate the _Terms and conditions_ English and French content to the main app
- [x] Migrate the _Privacy policy_ English and French content to the main app
- [x] Ensure the designs match the Figma files / screenshots provided
- [x] Note the name change from _Privacy notice_ to _Privacy policy_; this is to align with our current footer and requires one text change in the _Terms and conditions_ design in the first paragraph
```

## 🔎 Details

<details>
  <summary>📸 Terms and conditions</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/0aca1421-b082-45cd-a5b2-a79a5b871ff0" />
</details> 

<details>
  <summary>📸 Privacy policy</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/111b323a-92d0-48de-819a-bc521a6067d9" />
</details>

**Comment by petertgiles** [comment]
- these are top-level paths, watch the nginx routing
- do we remove the original pages from tc-report?

**Comment by petertgiles** [comment]
Decision from scrum: remove migrated tc-report pages from repo.  Remove the links to them from the tc-report template as well.

**Comment by petertgiles** [comment]
Blocked while it goes through the copy review.

**Comment by RM-1978** [comment]
@gobyrne, the Departmental copy editing and translation teams are working on the final proofreading and translation of these texts now as part of our latest comparative reading request. Lauren saw them in November. I will update the thread as soon as these pieces are through the pipeline. 

I have included an excerpt here of the text being worked on: [GCDT Terms, Conditions, Privacy notice_01-04-2024.docx](https://github.com/GCTC-NTGC/gc-digital-talent/files/13832632/GCDT.Terms.Conditions.Privacy.notice_01-04-2024.docx)

**Comment by gobyrne** [comment]
@RM-1978 No need to block this work on the copy review. Create a separate issue for that when it's ready.

**Comment by RM-1978** [comment]
@gobyrne, no problem. I will create a ticket for the copy as soon as I I have an updated and approved terms and condition and privacy statement (hopefully also ATIP-vetted) in hand for GC Digital Talent.
