### ISSUE TITLE
🐛 Enhance the support form submission experience during local development

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#8581]
## ✨ Summary

This (low priority) ticket covers an issue caused when submitting the _Contact and support_ form on local development environments that results in a blank, white screen.

### Steps to reproduce
- Open the project locally on `main`
- Navigate to the _Contact and support_ page
- Complete the contact form
- Submit the form
- Witness a vast nothingness

### Expected outcome

While @petertgiles has mentioned that we don't have a development Freshdesk instance to take advantage of here, it would be nice to at least prevent the white screen of infinity. Perhaps an alert when you try to submit the form indicating this isn't possible in local development environments?

In an ideal world, it would take you to the submission confirmation page with fake data so that we could leverage the flow in user testing (but also for design-viewing purposes).

```[tasklist]
### ✅ Requirements
- [ ] Recreate the issue locally
- [ ] Enhance the experience based on one of the two solutions described above
```

**Comment by mnigh** [comment]
> Perhaps an alert when you try to submit the form indicating this isn't possible in local development environments?
It is possible to submit the form in local development environments with the appropriate values added to the `api/.env` file so a specific message like that would not be accurate.

> In an ideal world, it would take you to the submission confirmation page with fake data so that we could leverage the flow in user testing (but also for design-viewing purposes).
The `SupportForm` component already mocks the submission process in a storybook story. See Chromatic: https://61e099a1bb1465003a73d3ce-csrsarfulq.chromatic.com/?path=/story/forms-support-form--default

As for preventing a white screen locally when the freshdesk endpoint and api key are not added to the `api/.env` file , the following code should do that, the last screenshot being the result.

## Screenshots
![Screen Shot 2023-11-23 at 10 27 28](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/ee199648-8621-44c4-8659-6515b1c9f9e4)

![Screen Shot 2023-11-23 at 10 27 36](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/51ebaaee-dece-48d5-b69d-87a32b343432)

![Screen Shot 2023-11-23 at 10 26 30](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/23a534bf-f98c-4d4e-8b6e-b00a851d9a9f)
