### ISSUE TITLE
🔤 Copy update in Reason for the talent request 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#8583]
## 🔤 Copy

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzBDQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dcf4146ed3455be2e6a0a25b0ab5df9aaa240a99/Screenshot%202023-11-23%20at%2010.34.40%20AM.png)

## 🌎 Localization

_Apprenez-en advantage_ changes to _Apprenez-en davantage_

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the copy has been added or updated appropriately.

- [ ] Copy to be updated as per the screenshot
- [ ] change all the occurrences with this spelling
- [ ] Please create a branch from the release tag  v2.12.5 and apply your fix onto it  and merge the release branch into the main. This will avoid me getting untested changes into production 
Ex.  `git checkout -b Release-v2.12.5 v2.12.5`

**Comment by mnigh** [comment]
It seems as though there are several instances of _Apprenez-en davantage_ and _Apprenez-en avantage_ but no _Apprenez-en d'avantage_: should others be changed as well?

## Screenshot
![Screen Shot 2023-11-23 at 10 40 42](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/a886a153-55e0-4081-8930-e76ed29d380a)

**Comment by brindasasi** [comment]
good question ..
@RM-1978 , @gggrant  is it something needs to be replaced over all ? or it depends the place where it appears?  Any idea?

**Comment by gobyrne** [comment]
This example should be "davantage" and without apostrophe.

**Comment by RM-1978** [comment]
> good question .. @RM-1978 , is it something needs to be replaced over all ? or it depends the place where it appears? Any idea? 
 Yes the correct formulation would be "davantage" in all of these cases. For more information on why these homophones are often confused, please see this resource from the [Office de la langue française du Québec](https://vitrinelinguistique.oqlf.gouv.qc.ca/22059/lorthographe/homophones-lexicaux/les-homophones-davantage-et-davantage).

**Comment by gobyrne** [comment]
@mnigh in the list you gave, the 2 "avantage" should be "davantage" instead.

**Comment by mnigh** [comment]
> Yes, instances of "apprenez-en avantage," "apprenez-en d'avantage," or " apprenez-en plus" should be replaced with "apprenez-en davantage" across the platform for consistency.
> 
> For more information on why these homophones are often confused, please see this resource from the [Office de la langue française du Québec](https://vitrinelinguistique.oqlf.gouv.qc.ca/22059/lorthographe/homophones-lexicaux/les-homophones-davantage-et-davantage).

Here are all of the instances of  _apprenez-en plus_ (1 instance), _apprenez-en avantage_ (2 instances), and _apprenez-en d'avantage_ (no instances) in our codebase. @gobyrne, can you confirm that these three instances should be changed to  _apprenez-en davantage_ then?

## 1) ..._ou apprenez-en plus sur certaines recherches derrière cette plateforme_

### Full string in French
https://github.com/GCTC-NTGC/gc-digital-talent/blob/34f4b58e9e0c6e4784922c1e1eaa7258ecafd4ce/apps/web/src/lang/fr.json#L754-L757

### Full string in English
https://github.com/GCTC-NTGC/gc-digital-talent/blob/34f4b58e9e0c6e4784922c1e1eaa7258ecafd4ce/apps/web/src/pages/Auth/SignedOutPage/SignedOutPage.tsx#L78-L84

### Full string in English
https://github.com/GCTC-NTGC/gc-digital-talent/blob/34f4b58e9e0c6e4784922c1e1eaa7258ecafd4ce/apps/web/src/pages/Auth/UserDeletedPage/UserDeletedPage.tsx#L82-L88

## 2) ..._Apprenez-en advantage sur les équivalences..._

### Full string in French
https://github.com/GCTC-NTGC/gc-digital-talent/blob/34f4b58e9e0c6e4784922c1e1eaa7258ecafd4ce/apps/web/src/lang/fr.json#L2990-L2993

### Full string in English
https://github.com/GCTC-NTGC/gc-digital-talent/blob/34f4b58e9e0c6e4784922c1e1eaa7258ecafd4ce/apps/web/src/messages/applicationMessages.ts#L131-L137

## 3) ..._Apprenez-en advantage sur la..._

### Full string in French
https://github.com/GCTC-NTGC/gc-digital-talent/blob/34f4b58e9e0c6e4784922c1e1eaa7258ecafd4ce/apps/web/src/lang/fr.json#L7758-L7761

### Full string in English
https://github.com/GCTC-NTGC/gc-digital-talent/blob/34f4b58e9e0c6e4784922c1e1eaa7258ecafd4ce/apps/web/src/pages/SearchRequests/RequestPage/components/RequestForm.tsx#L391-L402
