### ISSUE TITLE
♻️ Update and consolidate the admin-facing Header UI component

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#8584]
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/9ae7cacc-bbe5-4419-a671-55eac502e39c)

## ✨ Summary

[Visit the Figma file](https://www.figma.com/file/guHeIIh8dqFVCks310Wv0G/Style-library?type=design&node-id=912-2455&mode=design) • Contact @substrae with design questions

The goal of this ticket is to standardize the header UI element used on admin-facing page. Right now, the implementation is currently inconsistent across pages due to it having evolved over the course of design elements being produced. This component should centralize the styling and children elements so that updates propagate to all pages moving forward.

```[tasklist]
### ✅ Requirements
- [ ] Update the component design to match
- [ ] Add a tab variant using the updated `TabGroup` UI component
- [ ] Ensure the Government of Canada banner and `Breadcrumbs` components are using the same component as the applicant-facing `Header` / `Hero` component, but also make sure that the padding or lack-thereof matches the designs in both cases (they are different)
- [ ] Ensure all header elements are aligned with matching padding and that page content aligns with these elements in all cases
- [ ] Ensure dark mode styles are applied and that Storybook contains light and dark side-by-side comparisons (see other component stories for examples, `Button`, `Hero`, etc.)
- [ ] Ensure all admin pages use this new header in the correct variant
- [ ] Remove all `Breadcrumbs` elements from admin-facing page footers
``` 

### Tab variation

The admin interfaces are unique in that they sometimes require a tabbed interface. [Updates to the tab component](https://github.com/GCTC-NTGC/gc-digital-talent/issues/8582) should block this ticket to ensure design integrity.

<details>
  <summary>📸 With tabs</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/ae26310b-dec8-414a-a73a-e86cdb2d89be" />
</details> 

### Dark mode

If you have any questions about styling dark mode, reach out to @substrae. Don't forget that you can use the `:all` Hydrogen modifier to force a style to persist across modes when necessary.

<details>
  <summary>📸 With crumbs</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/b2802573-c2fb-47d4-a715-088cba3ef548" />
</details>

<details>
  <summary>📸 With tabs</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/7192368f-88d7-47a0-9e61-b212a44bac92" />
</details>

### Menu states

<details>
  <summary>📸 Menu pinned</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/c5ae501d-423e-4192-a282-56d3964abe05" />
</details> 

<details>
  <summary>📸 Menu collapsed</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/5a498d9a-b0da-43bd-8e36-f637c408d2d5" />
</details> 

### Mobile experience

<details>
  <summary>📸 With crumbs</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/86270b65-6e70-4902-bd7b-b3b3f98bf2f9" />
</details>

<details>
  <summary>📸 With tabs</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/d0df28d5-f119-4581-ad41-bcc836594edd" />
</details>

**Comment by esizer** [comment]
Are the tabs meant to replace the sub nav we already have? Also, are we converting them to tabs instead of links or is it just styled to appear like tabs?

![Screenshot 2023-11-23 105319](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/d3909809-743c-4f4c-a7fb-550f403fcf36)

**Comment by substrae** [comment]
@esizer I think it makes sense for these to be (and act like) tabs, personally. I'm going to loop @Jerryescandon in here though, as he originally designed this specific piece and I want to reflect his original intent.

**Comment by petertgiles** [comment]
If they're "real" tabs it might make navigation trickier.  We would need to add some logic to sync up the tabs with the URL if we want to make it possible to bookmark the "page".  And then if you want to add a ScrollTo link to a certain id on a certain tab?  It gets messy.

**Comment by petertgiles** [comment]
Also, I'm not sure our tab component can lazy load content so all our "pages" might have to get loaded into the virtual dom at once.

**Comment by substrae** [comment]
Is it worth creating a prop on the `TabGroup` component that allows for the choice of virtual routes vs. true links?

**Comment by esizer** [comment]
Also, I noticed the "tabs" variant does not include breadcrumbs. Is this because we will _never_ use this variant on anything but a top level page? Or will they just appear in a different location when using this variant? 🤔

**Comment by Jerryescandon** [comment]
idk, the old original design was meant as a form of navigation, so I was in fact envisioning these as "themed" like tabs, but functioning as regular links.
