### ISSUE TITLE
✨ Bookmark a pool candidate

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8598]
## ✨ Feature

Pool operators would like a way to bookmark a pool candidate that they want to keep an eye on.

## 🎨 Design File

by @Jerryescandon 
https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Pools---Record-of-Decision?type=design&node-id=6872-37861&mode=design&t=7j6ZyDxN1M9FKKor-0

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/626989a5-13ed-4c74-924f-aba89432815d)

## 🙋‍♀️ Proposed Implementation

Add a boolean isBookmarked field to the PoolCandidate query types and mutations.  Read and write should be restricted in the same way as other "manager fields" like notes.

Suggestion/note: Mutation that returns boolean to avoid reloads. Caution advised 

## ✅ Acceptance Criteria

- [ ] field added to database and API
- [ ] Proper restrictions on access and mutation
- [ ] Shows up in the assessment tracker
- [ ] Sorts row to top of assessment tracker when bookmarked
  -  isBookmarked
  -  Decision
  -  isPriority
  -  isVeterant
  -  alpha by last name
  -  alpha by first name
- [ ] Clicking icon in assessment tracker toggles bookmarked status
  - [ ] Prevent the table from reloading and causing a re-sort

**Comment by Jerryescandon** [comment]
One thing im worried about here is: Should bookmarking a candidate force a re-load to show them at the top immediately?
- I'm leaning towards NO. Bookmarking someone should not reload the current sorting, but refreshing the page or table should move that candidate to the top of their status group. and Vice-versa. Un-bookmarking should not move the candidate down util the table reloads.

**Comment by vd1992** [comment]
Backend
- Compact mutation that takes a pool candidate id, toggles the bool field and just returns true. 
- Custom mutation class, reuse `updateAsAdmin` policy. 

Frontend
- Fetch bookmarked field, functions as setting default
- Clicking bookmark toggles it, firing off the mutation, does not reload so bookmark status is decoupled from the graphQL cache into component state
- Sorting exists, need to incorporate this into the sort

Question
Does bookmarking override all other sorts? Currently it sorts by assessment decision then priority then veterancy. 

An aside, this has a sort of experimental feel as we see how diverging state from the graphQL cache effects components

**Comment by petertgiles** [comment]
@Jerryescandon please confirm?

Current sorting order is:
- Decision (success/unsucces/to-assess)
- isPriority
- isVeteran

New sort ordering:
- Decision
- isBookmarked
- isPriority
- isVeterant
- alpha by last name
- alpha by first name

**Comment by petertgiles** [comment]
Jerbo corrected that isBookmarked is top sort factor
