### ISSUE TITLE
✨ New link previews

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#8614]
## ✨ Feature

When we share a link to our platform, currently there is no image that goes with it. This issue will fix that!

## 🕵️ Details

This is what we do not want:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/f244f439-1837-4bf7-a1c0-c4aca5622853)

## 🎨 Design File
These are the images to use (in two different sizes). Separate images are given for IAP and GC Digital talent... hope that's ok.

GCDT

![Generic Facebook EN](https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/2cb6e594-08eb-4a2a-ae75-4075cb1dd576)
![Generic Facebook FR](https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/126b6f68-c896-4a54-99cf-dced2487ddee)
![Generic LinedIn FR](https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/c742e382-62a3-48e5-a878-a16c11b5657f)
![Generic LinkedIn EN](https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/f1e7d511-8f5b-4d3a-ae4c-8bea2debbbcf)

IAP 

![Generic Facebook EN IAP](https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/de25ebbd-5f13-43e3-a08f-7f967c50696a)
![Generic Facebook FR IAP](https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/45d5f61a-ec73-44b6-a4f5-03f9545f627d)
![Generic LinedIn FR IAP](https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/9adff397-e6c6-4390-adee-8eaa9aa6d07a)
![Generic LinkedIn EN IAP](https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/c3c5554d-04e3-4fc9-b53d-8a7b9223a1e1)

### 🧑‍🎨 Designer

The Brookster (@BrookeCameron)

## 🙋‍♀️ Proposed Implementation

We should be following the standards set out by Open Graph: https://ogp.me/

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Image shows up when a link is shared.
- [ ] Different ones for IAP
- [ ] Titles show in share previews
- [ ] Subtitles show where appropriate in share previews

Start with main landing page, basic implementation. Additional variants to come later
Test with UAT, opened to public?

**Comment by vd1992** [comment]
Would be added within here, right? The property `og:image`


![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/80a3fa99-fd04-4cb9-af7e-83b98befb030)

**Comment by tristan-orourke** [comment]
@gobyrne @BrookeCameron can we get images which combine French and English? If you share a link to https://talent.canada.ca, there's no way to know if it should be EN or FR.
