### ISSUE TITLE
🛠️ Azure monitoring alerts

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8651]
## 🛠️ Tooling

Now that we have a consolidated dashboard in Azure, lets set up alerts for when something is going wrong.

## ✅ Acceptance Criteria

- [ ] Determine the threshold for an alert for each key metric.
- [ ] Determine to whom and how alerts will go out.
- [ ] Set them up and test them.

**Comment by petertgiles** [comment]
This is what it looks like when the server becomes unresponsive.  It should help inform the alerts:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/1a45381c-bc4f-46cb-b3a8-7772ae879e22)
I suggest:
Memory: 400 MB
CPU Time: 4 min
Response Time: 1.5 sec
4xx: 60 req
5xx: 10 req

We haven't seen the database go unresponsive yet, but here is the steady state:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/3a18a439-6bf9-49f2-a0f6-395938cb6e31)
I suggest:
CPU: 75%
disk: ?
Memory 6 GB

**Comment by petertgiles** [comment]
Jira ticket AZ-19083 submitted.

**Comment by petertgiles** [comment]
Slack alert rejected.  I've asked them to send to TBS email addresses instead.

**Comment by tristan-orourke** [comment]
IMTD is now sending these alerts to dev emails!
