### ISSUE TITLE
✨ Detailed logout messages

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8652]
## ✨ Feature

Our logout experience is a bit rough.  We have a few places where we could easily make it better.

- Remove the "user deleted" page to avoid an extra redirect
- Add a place for detail messages on the logged out page to help inform the user
  - Add the "your account is inactive" message to this page
  - Add a "your session has been ended" message for when the app forcibly logs the user out
  - Any other special cases?

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/b31c4e00-54db-4348-b6ba-0057ca6b1ad9)

## ✅ Acceptance Criteria

- [ ] User deleted page removed
- [ ] A spot for messages added to the logged out page
- [ ] A message telling the user when they have been forcibly logged out
   - Exact copy "Your session has expired, please sign in again."
- [ ] A message telling the user when their account has been deleted
   - Exact copy "This account has been deleted. If the problem persists, please sign up for a new account."

**Comment by petertgiles** [comment]
Possible duplicate: #7811

**Comment by gobyrne** [comment]
Yes, this would resolve #7811. I'll close it in favor of this one.

Marc suggested some text. We use the terms "sign in" and "sign up" on the site, not login and register. With that in mind, here's marc's text. I'll update for our site

> Here are my suggests for the copy:
> Token: "Your login session has expired, please login again."
> (let me know if this makes sense for an invalid token or if there are other reasons a token become invalid.)
> Deletion: "Your account has been deleted. To access the platform again, please register for a new account."

**Comment by gobyrne** [comment]
Ticket updated, block removed.

**Comment by yonikid15** [comment]
Do we want the design to look something like this:

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/22059495/8d601c8e-3c20-4f1b-ab43-d8e491b38008)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/22059495/9497ba86-b2b9-4658-927b-828234dcf37b)

**Comment by marc-donofrio** [comment]
I like this! Maybe a red X for the deleted account prompt? Otherwise all good for me. I can't think of other reasons for logouts except when the user purposely logs out.

**Comment by petertgiles** [comment]
@gobyrne OK to proceed with Yoni's designs?
