### ISSUE TITLE
🔤 French fixes on the job poster

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#8660]
## 🔤 Copy
These 3 changes on the French job poster

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/4b8c157f-ade6-4466-be6a-bb51d21e4036)

**hébergement** should be **mesures d’adaptation**

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/0893e606-b9b4-4d6e-85d9-cd9f1967f811)

**Publication** instead of **publicité**

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the copy has been added or updated appropriately.

- [ ] All 3 French copy issues fixed
- [ ] Observe other places that contain those words/phrases and spin-off issue?

**Comment by mnigh** [comment]
Some important information to consider.

## hébergement (1 instance)
https://github.com/GCTC-NTGC/gc-digital-talent/blob/8c765ade8d25cf1974d400da3a71954e31fcfaac/apps/web/src/lang/fr.json#L2410-L2413

## localisation (2 instances)

https://github.com/GCTC-NTGC/gc-digital-talent/blob/8c765ade8d25cf1974d400da3a71954e31fcfaac/apps/web/src/lang/fr.json#L2194-L2197

https://github.com/GCTC-NTGC/gc-digital-talent/blob/8c765ade8d25cf1974d400da3a71954e31fcfaac/apps/web/src/lang/fr.json#L3446-L3449

> [!CAUTION]
> **Location** is translated elsewhere as _Emplacement_ (`7VCuZQ`, `UGaZR2`)

## publicité (1 instance)

https://github.com/GCTC-NTGC/gc-digital-talent/blob/8c765ade8d25cf1974d400da3a71954e31fcfaac/apps/web/src/lang/fr.json#L5102-L5105

> [!NOTE]
> _Publicité_ is translated from **Advertisement** in English: is this meant to be the word **Process** in English (_Processus_ in French)? REF: https://github.com/GCTC-NTGC/gc-digital-talent/discussions/5865
