### ISSUE TITLE
🔤  Consistent French translation for accommodation 

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/gc-digital-talent#8669]
## 🔤 Copy

There was an incorrect translation of accommodation to **_Hébergement_**  on the platform. According to [Termium](https://www.btb.termiumplus.gc.ca/tpv2alpha/alpha-eng.html?lang=eng&i=1&srchtxt=ACCOMMODATION&codom2nd_wet=1#resultrecs), correct translation for the term is "Mesure d'adaptation". 

## 🕵️ Details

- [ ]  Find and replace "hébergement" with "Mesure d'adaptation" or "Mesures d'adaptation" depending on context. 
- [ ] Ensure that all French instances of "(workplace) accommodation" are consistently translated as "mesure(s) d'adaptation."  

## 🙋‍♀️ Proposed Implementation

Change all French instances of "(workplace) accommodation" are consistently translated as "mesure d'adaptation."  

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the copy has been added or updated appropriately.

- [ ] All French instances of "(workplace) accommodation" are consistently translated as "mesure d'adaptation."

**Comment by mnigh** [comment]
> > @RM-1978 is this issue different than #8660?
> 
> Hi @mnigh, Yes this is a bit different. When I saw the issue described in #8660, I wondered if there might be other instances on the platform (e.g., ITAIP pages, Application process pages or existing Job posters) that might need to be adjusted for consistency. Perhaps @petertgiles's dandy Translation script might be useful for this.

I can confirm that there is only one reference in our application (codebase) to the word _hébergement_.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/8c765ade8d25cf1974d400da3a71954e31fcfaac/apps/web/src/lang/fr.json#L2410-L2413

## Screenshot
![Screen Shot 2023-12-04 at 15 58 44](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/b090d7fc-5279-4710-8f36-0f7f1412c1a4)

As for job posters and anything else that is stored in a database, that would be a bit trickier and would require a sql query on the production database or, a manual search of the [published jobs](https://talent.canada.ca/fr/browse/pools). I would argue however, that any strings in the database would be up to the publisher of the content itself to maintain as the developers do not necessarily have access. @petertgiles translation script is made to run inside our application for identifying duplicate strings, not for making a database query.

**Comment by RM-1978** [comment]
Thanks @mnigh for confirming. I think with the info you provided, we can close this issue. @esizer and I just wanted to make sure that you got the time you needed.
