### ISSUE TITLE
✨ Add new RoD columns to pool's candidate table

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8675]
## ✨ Feature

There are a few small changes to the pool's list of candidates table (IndexPoolCandidatePage).
/admin/pools/:poolId/pool-candidates

## 🎨 Design File

@Jerryescandon 
https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Pools---Record-of-Decision?type=design&node-id=6906-21324&mode=design&t=LDMdZtnUX80lfuM1-0

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/f6be3a0e-fbe7-4c95-aca7-7d177c7fd24d)

## Details

This table shows what to display in the Final Decision and Job Placement columns for each Pool Candidate Status.

| Pool Candidate Status       | Final Decision | Job Placement        |
|-----------------------------|----------------|----------------------|
| DRAFT                       | To assess | Not available        | 
| DRAFT_EXPIRED               | To assess | Not available        | 
| NEW_APPLICATION             | To assess | Not available        | 
| APPLICATION_REVIEW          | To assess | Not available        | 
| SCREENED_IN                 | To assess | Not available        | 
| UNDER_ASSESSMENT            | To assess | Not available        | 
| SCREENED_OUT_APPLICATION    | Disqualified   | Not available        | 
| SCREENED_OUT_NOT_INTERESTED | Removed        | Not available        | 
| SCREENED_OUT_NOT_RESPONSIVE | Removed        | Not available        | 
| SCREENED_OUT_ASSESSMENT     | Disqualified   | Not available        | 
| QUALIFIED_AVAILABLE         | Qualified      | Not placed           | 
| QUALIFIED_UNAVAILABLE       | Removed        | Not available        | 
| QUALIFIED_WITHDREW          | Removed        | Not available        | 
| PLACED_CASUAL               | Qualified      | Placed casual        | 
| PLACED_TERM                 | Qualified      | Placed term          | 
| PLACED_INDETERMINATE        | Qualified      | Placed indeterminate | 
| EXPIRED                     | Removed        | Not available        | 
| REMOVED                     | Removed        | Not available        | 

Notes: 
- DRAFT and DRAFT_EXPIRED candidates should never appear in this table, but I've included fallbacks to put in the code just for completions sake.
- For now, its okay if sorting by Final Decision or Job Placement columns continues to sort by status behind the scenes. We can improve that later in #8960.

## ✅ Acceptance Criteria

- [ ] No columns are locked for sorting
  - [ ] Default sort order is still first by Category then by Status
- [ ] Add bookmarked column
  - [ ] Clicking ability to toggle status
  - [ ] Deferred sort (no reload on toggle)
  - [ ] Title with icon: alt text is "Bookmark"
  - [ ] default sort order becomes Bookmark, category, final decision
  - [ ] default visible
- [ ] Move name to be the second column
  - [ ] Remove "View" column and make clicking the name the new link to view
- [ ] Add "Final decision" column with colored pills
  - [ ] default visible
  - [ ] use shared custom sort orders for statuses
- [ ] Add "Job placement" column with possible values "Placed - (type)", "not placed" or "not available"
  - [ ] default visible
  - [ ] ~~sort: "not placed", "placed casual", "placed term", "placed indeterminate"~~
  - [ ] sort uses the same order as for statuses
  - [ ] Can remain not clickable for now
- [ ] Keep the current Status column in the table before the "Final decision" column, but hide it by default IF the RoD feature flag is true

**Comment by tristan-orourke** [comment]
@Jerryescandon Are we sure about the sort order unlock?

**Comment by esizer** [comment]
Question for either @tristan-orourke or @Jerryescandon 

For the point

 - Remove "View" column and make clicking the name the new link to view

Currently this link is dynamic based on the status and either goes to the application or user profile based on status. Should this functionality be maintained or update to only go to application? If maintained, how do we distinguish the logic to visual users?

**Comment by Jerryescandon** [comment]
We can have the name link go to the application, since the application page contains a link to the up-to-date profile.
