### ISSUE TITLE
✨ Update General Questions UI

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8676]
## ✨ Feature

We want to separate the general questions associated with the pool directly with the screening questions associated with an assessment step.  This will allow us to ensure that the general questions are not associated with a skill and cannot be used in the assessment plan.  It will also allow us to make skill associations mandatory for every assessment plan step.

## 🎨 UI Screenshots

**Admin - Advertisement information** [Figma file](https://www.figma.com/file/e2DTvyppj41m6slFWTDZ0U/Admin---Job-advertisement-creation?type=design&node-id=52%3A40341&mode=design&t=po4ttDN8MiQ7QUfn-1) 
(Related ticket #8751 )

We have separated the General questions from the Screening question, "General" questions will appear on the advertisement information page as a repeater that can be used during the poster creation while "Screening" questions will be added during the assessment plan builder and tied to skill (skills would be required).

<details><summary>📸 Empty</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/156687db-429b-4146-ad50-97f36bb5494f)

</p>
</details> 

<details><summary>📸 Modal</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/9637c66d-6463-40ed-8ff1-3d8cfc010595)

</p>
</details> 

<details><summary>📸 Full</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/e79de454-8422-4cab-94ea-b7389ba45b5a)

</p>
</details> 

## 🎨 Design File

Rename ScreeningQuestion to GeneralQuestion

```mermaid
classDiagram

class Pool { }

class AssessmentStep {
    Int sortOrder
    AssessmentType type
    LocalizedString title
}

class GeneralQuestion {
    Int sortOrder
}

class GeneralQuestionResponse {
    String answer
}

class PoolCandidate

class ScreeningQuestion {
     Int sortOrder
}

class ScreeningQuestionResponse {
    String answer
}


Pool "1" o-- "0..*" AssessmentStep
Pool "1" o-- "0..*" GeneralQuestion
GeneralQuestion "1" -- "0..*" GeneralQuestionResponse
PoolCandidate "1" o-- "0..*" GeneralQuestionResponse
Pool "1" o-- "0..*" PoolCandidate
AssessmentStep "1" o-- "0..*" ScreeningQuestion
PoolCandidate "1" o-- "0..*" ScreeningQuestionResponse
ScreeningQuestion "1" o-- "0..*" ScreeningQuestionResponse
```

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Ability to edit general questions added back into the admin pool editor
- [ ] General Questions UI matches new design and uses new Card Repeater
- [ ] Copy checked, no mix-ups between general and screening questions copy, additions as needed such as below

generalQuestions version of 
![299756803-73d8ea8e-e681-4799-9246-91e0d5b386e6](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/ce26fa32-e0dd-4bcd-80b7-ea47b8c53b2f)

**Comment by tristan-orourke** [comment]
What would the UI look like on the Application, for the new question type? How are Screening questions and General questions differentiated? Are they differentiated? Are they on different steps?
