### ISSUE TITLE
🐛 Prod error logged: null token parse

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8723]
## 🐛 Bug

We get this error logged occasionally in prod:
> Lcobucci\JWT\Token\Parser::parse(): Argument #1 ($jwt) must be of type string, null given, called in /home/site/wwwroot/api/app/Http/Controllers/AuthController.php on line 86 {"exception":"[object] (TypeError(code: 0): Lcobucci\\JWT\\Token\\Parser::parse(): Argument #1 ($jwt) must be of type string, null given, called in /home/site/wwwroot/api/app/Http/Controllers/AuthController.php on line 86 at /home/site/wwwroot/api/vendor/lcobucci/jwt/src/Token/Parser.php:26)

## ✅ Acceptance Criteria

- [ ] Find out where we try to parse the null
- [ ] Gracefully handle it to prevent the Lcobucci exception and stack trace

**Comment by mnigh** [comment]
`$idToken` could be `null` on line 81, but not sure about how to gracefully handle it to prevent the exception.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/defd67584442596344b87382e568c4e430a5f830/api/app/Http/Controllers/AuthController.php#L81-L86

what about this as a solution:

```
if (!($idToken)) {
    $token = null;
    throw new Exception('No token provided.');
} else {
    $token = $config->parser()->parse($idToken);
}
```

**Comment by vd1992** [comment]
What would gracefully handling it look like?

Skimming through: 
`AuthController.php`
`OpenIdBearerTokenService.php`

I see a bunch of throwing like `InvalidArgumentException`, `Exception`, and `UnauthorizedException` when something isn't right

**Comment by petertgiles** [comment]
> I see a bunch of throwing like `InvalidArgumentException`, `Exception`, and `UnauthorizedException` when something isn't right

Hmm, you're right.  This is a controller so we could be directly raising HTTP responses but it seems like for other errors it's InvalidArgumentException.  Maybe using the existing pattern is best:
```php
        throw_unless(
            strlen($state) > 0 && $state === $request->state,
            new InvalidArgumentException('Invalid session state')
        );
```
I don't mind this actually.  If we did this we would get a good in-context error message in our logs and wouldn't be getting a stack track from deep inside another library.
