### ISSUE TITLE
♻️ RoD copy passover 

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#8728]
## ♻️ Debt/Refactor

Some copy still need revision or updating to reach the desired state. This could take some time to receive so it is being spun off to prevent blocking other work. 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/da26a1e4-b814-4b5b-ad61-94a091a7320a)

## 🕵️ Details

Copy to be added or replaced for the RoD epic/scope to be added in here later

## 🌎 Localization

- PENDING

## ✅ Acceptance Criteria

- [ ] Satisfactory copy for everything gated by `FEATURE_RECORD_OF_DECISION`
- [ ] Demonstration level descriptions https://github.com/GCTC-NTGC/gc-digital-talent/pull/8653#discussion_r1414023161

**Comment by tristan-orourke** [comment]
Not yet happening
