### ISSUE TITLE
✨ 2023 Holiday banner

### ISSUE THREAD

**Issue by BrookeCameron** [GCTC-NTGC/gc-digital-talent#8756]
## ✨ 2023 Holiday banner

Adding a variation to the Alert component for the 2023 Holiday break

## 🕵️ Details

This is reusing the alert component - the differences is the side bar with the icon is hidden and the image is added. 

## 🎨 Design File

https://www.figma.com/file/L0t0egWEGFs8xBG5lFKvmK/Holiday-banner?type=design&node-id=0-1&mode=design

### 🧑‍🎨 Designers

@BrookeCameron & @substrae 

## 📸 Screenshot
<img width="801" alt="Screenshot 2023-12-08 at 1 55 10 PM" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/6d69a9c2-d409-4a3a-9c4d-b01f1d1e44ac">

### Copy
Heading: Happy Holidays! 
Body copy: It's time for a well-deserved break; you earned it! 
There will be no job postings during the holidays (Dec 22-Jan 7).
So kick back, relax, and enjoy the holiday season with your loved ones. See you in the new year!

### Assets (pngs) 
Light mode: 
![Holiday_2023_graphics](https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/7db30662-369a-4840-a76a-0a3bd1cccc2c)

Darkmode: 
![Holiday_2023_graphics_darkmode](https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953238/06314b4e-9ce7-4b1a-bce6-6c777019cc4b)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Review with Designers
- [ ] Image scales with the width

**Comment by tristan-orourke** [comment]
@BrookeCameron couple questions:
- which pages should this appear on? Browse Jobs, Homepage, and Exec home page?
- do you have webp image files?
- Can we ignore the little "x" and not make it dismissible?

**Comment by BrookeCameron** [comment]
@tristan-orourke Please go ahead with it being on the Homepage and Exec homepage
