### ISSUE TITLE
🔤 Work stream term inconsistently translated in French

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#8766]
## 🔤 Copy

The term **stream** is inconsistently translated in French. [Termium](https://www.btb.termiumplus.gc.ca/tpv2alpha/alpha-eng.html?lang=eng&i=1&srchtxt=WORK+STREAM&codom2nd_wet=1#resultrecs) has multiple definitions and multiple translation for French, none of which are _flux_.

## 🕵️ Details

French copy contains _flux_ and _volet_ (but never _champ de travail_) and are both used to refer to the same sort of stream, though _volet_ has more instances and at least appears in termium.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/66ecf58dd6898793674ffdcc59a9488a892e440a/apps/web/src/lang/fr.json#L2122-L2125

https://github.com/GCTC-NTGC/gc-digital-talent/blob/66ecf58dd6898793674ffdcc59a9488a892e440a/apps/web/src/lang/fr.json#L4258-L4261

https://github.com/GCTC-NTGC/gc-digital-talent/blob/66ecf58dd6898793674ffdcc59a9488a892e440a/apps/web/src/lang/fr.json#L5698-L5701

## 🙋‍♀️ Proposed Solution

Change all instances of _flux_ to _volet_.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the copy has been added or updated appropriately.

- [ ] a single term is consistently used to refer to a work stream in French

**Comment by RM-1978** [comment]
thanks for Flagging this @mnigh! I checked in with the design team (@substrae) and we are okay with your proposed solution to match the language around "stream, work stream."
