### ISSUE TITLE
♻️ Make `cy.overrideFeatureFlags` type more strict

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#8780]
## ♻️ Debt/Refactor

Update the command to use a more strict type.

## 🕵️ Details

The command was originally developed as a spike but worked well so was merged. However, the weak type used while testing the feature was not updated.

 - https://github.com/GCTC-NTGC/gc-digital-talent/pull/8762#discussion_r1425471792

## 🙋‍♀️ Proposed Solution

Update the following type to use `Record<"string", boolean | null>` for the `flags` arg.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/2333100c25645528a7bd053d1be2508876df48c6/apps/e2e/cypress.d.ts#L64

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] `cy.overrideFeatureFlags` has a stricter type
- [ ] The type is enforced and functions as expected

**Comment by esizer** [comment]
@tristan-orourke Do we want to still pursue this now that we plan on migrating to Playwright? While writing the new implementation I did try and make it more strict with:

https://github.com/GCTC-NTGC/gc-digital-talent/blob/60a9659903204c76ef406985a1edd80b2c8af4f5/apps/playwright/utils/featureFlags.ts#L4-L6

If it is still too loose, maybe we can rescope this for Playwright?

**Comment by tristan-orourke** [comment]
This seems trivial, lets just make the one-line code change 😆

**Comment by tristan-orourke** [comment]
"Easy Peasy"
