### ISSUE TITLE
🐛 Tab focus styles are a bit off

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#8785]
## 🐛 Bug

The new tab focus styles have a few minor styling oddities:
* The font weight of focused tabs shouldn't change - they should retain the styles of their current state
* The font color of a focused tab, regardless of its current state, should change to `black`

<details>
  <summary>📸 Tab state designs</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/404d0b3f-e5c0-4a6f-8b6a-992c686eddf2" />
</details> 

## 📋 Steps to Reproduce

1. Run Storybook
2. Navigate to the tab stories
3. Focus the tab components

```[tasklist]
### ✅ Requirements
- [ ] Focused tabs shouldn't modify font weight
- [ ] Focused tabs should always have a `black` font color
```

**Comment by esizer** [comment]
> * Focusing tabs removes their bottom border (only the active tab should ever have the bottom border removed)

While the other two are valid, I'm not so sure about this one. The border remains intact on focus for me.

![Screenshot 2023-12-14 080343](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/38dcb5f1-63d1-4eb7-aca2-bb2cb6a4ecfe)

**Comment by substrae** [comment]
@esizer It might have just been my monitor's super bad pixel rounding. Sometimes single pixel lines disappear entirely for me.

**Comment by petertgiles** [comment]
Confirming that it doesn't appear to be an issue.
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/df976e4e-5a15-44a1-9782-4ad0ae80bdad)
I'll update the scope.
