### ISSUE TITLE
🐛 Robots.txt not found

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8810]
## 🐛 Bug

I noticed in our HTTP 4xx logs that robots.txt is not coming up.

## 📋 Steps to Reproduce

1. Browse to `https://talent.canada.ca/robots.txt`
2. Observe that it is not found and tries to redirect to `en/robots.txt` which also doesn't exit.

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/e894d109-8bdd-47a0-a7e2-288d7296c827)

## 🙋‍♀️ Proposed Solution

Nginx routing problem?
Problem with the $ROBOTS_FILENAME environment variable?

## ✅ Acceptance Criteria

- [x] Navigating to `https://talent.canada.ca/robots.txt` brings up the prod robots file.

**Comment by mnigh** [comment]
> [!NOTE]  
> The same behaviour occurs for `/robots.txt` on dev and uat servers.

**Comment by mnigh** [comment]
> [!IMPORTANT]  
> The problem was that the value for the config file was incorrect since implementation in https://github.com/GCTC-NTGC/gc-digital-talent/pull/4909#issue-1463613392. 

I have tested and deployed the fix to the dev server.

- [ ] **dev** `robotsFileName` value `dev.robots.txt` (currently missing an **s** in `dev.robot.txt`)

What remains to be finished involves changes to the IaC repo in Azure. The appsvc config file `robotsFileName` value should be and deployed to dev and prod:

- [ ] **uat** `robotsFileName` value `dev.robots.txt` (currently missing an s in `dev.robot.txt`)
- [ ] **prd** `robotsFileName` value `prod.robots.txt` (currently missing an s in `prod.robot.txt`)

**Comment by petertgiles** [comment]
@brindasasi Could you please review Matt's deployment instructions and let him know ("approve") when he can close this issue?

**Comment by brindasasi** [comment]
Yeah I can fix that today in UAT & prod.. doesn't need separate deployment for this.

**Comment by mnigh** [comment]
Thanks for committing and deploying the variable value changes, @brindasasi. I can confirm that `prod.robots.txt` is being served at https://talent.canada.ca/robots.txt and `dev.robots.txt` is being served on dev and uat.

## Screenshot
![Screen Shot 2023-12-20 at 09 49 52](https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/ad744cb9-65cd-410e-bd76-aca412efa4a1)
