### ISSUE TITLE
♻️ Remove the holiday alert component

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#8811]
## ♻️ Debt/Refactor

The holiday alert is set to be hidden on January 8th, after which it can be deleted from the repo. 

## 🙋‍♀️ Proposed Solution

Delete component `<HolidayAlert />`

## ✅ Acceptance Criteria

- [ ] Component holiday alert is gone

**Comment by petertgiles** [comment]
Blocked until January 8th
