### ISSUE TITLE
🐛 Skill rankings requires refresh to show changes

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#8814]
## 🐛 Bug

The pages related to ranking skills requires the user to refresh the page to see the items they have added.

## 🦋 Expected Behaviour

User should not need to refresh the page after adding a skill to the top/to improve skills pages.

## 🕵️ Details

This one seems a little odd and I can't quite tell what is causing it. It looks as though, when adding a new skill, we do two things:

1. Create/update the skill
2. Fire off a second mutation to update the ranking

I don't think that is the cause though. Since our repeater is a form field, but does not act like a form field here (something that we should stop doing or create a separate repeater as previously talked about) it never gets updated.

## 📋 Steps to Reproduce

1. Login
2. Navigate to `/applicant/profile-and-applications/skills/showcase/top-5-behavioural-skills`
3. Add a skill
4. Notice that the repeater is not updated with the new skill

## 📸 Recording

https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/ba18b1f5-4741-4a69-8053-f20cbc5d8a2b

## 🙋‍♀️ Proposed Solution

I feel like we have two options, likely the "easy" option makes most sense but we should consider the more complete one 🤔 

1. **Easy**: Use the `react-hook-form` `setValue` function to update the skills when the API cache changes
2. **Complete**: Create a non-form version of the repeater so we don't need to hack around the fact that we are not using it like a form input

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Adding a skill to your top/to improve skills appears without the need for a refresh
- [ ] Write a cypress test to confirm this previously mentioned behaviour
- [ ] Implement using the "easy" option for now.

**Comment by vd1992** [comment]
We do have an issue outstanding concerning the repeater component https://github.com/GCTC-NTGC/gc-digital-talent/issues/8491
Though it doesn't contain any specific must-change or versioning

**Comment by petertgiles** [comment]
Reopened  #8161 for the "complete" solution.

**Comment by vd1992** [comment]
> This one seems a little odd and I can't quite tell what is causing it. It looks as though,

It appears recent too, as of 
PR https://github.com/GCTC-NTGC/gc-digital-talent/pull/8121
Recording https://recordit.co/imrrXJUohq
this bug wasn't occurring so it crept in at some point maybe with repeater card changes somehow? A little concerning for things that haven't been touched to become buggy
