### ISSUE TITLE
🛠️ Stop API HTTP request logging in console logs

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8816]
## 🛠️ Tooling

In Azure, everything that gets written to the console gets save in Azure Logging for analysis.  Our Azure console logs are full of lines like this:
> 127.0.0.1 - 05/Dec/2023:15:12:28 +0000 "POST /graphql" 200

I guess Laravel is logging every single request to the API with the HTTP status code.  This is redundant, though, because Azure already has a separate log for the details of every HTTP request.  In the console log, this is just noise (and probably extra cost).  Can with stop this?

If you view the Docker container logs locally you can see it, too.
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/69c304b1-a192-4876-8d5b-0ac2efa4c522)

## ✅ Acceptance Criteria

- [ ] Stop Laravel from logging the HTTP details of every request in Azure
- [ ] Ensure that Azure continues to log all requests in some other way

**Comment by petertgiles** [comment]
If this is Nginx and we want to keep logging this, I suggest redirecting it into a log file instead of emitting to the console where Azure picks it up.

**Comment by yonikid15** [comment]
Unfortunately, I was unsuccessful at turning the logs off. Dropping `access_log off;` in the server or within the `location = /graphql` doesn't seem to have any effect. I tried a few other things like `access_log /dev/null;` (which is not the recommended way of disabling it`. Hopefully someone else has better luck.
