### ISSUE TITLE
🛠️ Block URLs at the firewall

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8817]
## 🛠️ Tooling

We have a couple of URLs that are showing up in our HTTP 4xx logs as obvious vulnerability scans.  Let's block them at the firewall so that they never hit our server (and server logs).

## 🕵️ Details

/wp-login.php
/xmlrpc.php
/.env
/docker-compose.yml

## 🙋‍♀️ Proposed Solution

Request IMTD to block these paths at the firewall

## ✅ Acceptance Criteria

- [ ] Requests to the urls is blocked before our web server

**Comment by petertgiles** [comment]
I'm seeing a lot of /cart.json too.  Is that worth blocking as well?

**Comment by mnigh** [comment]
> I'm seeing a lot of /cart.json too. Is that worth blocking as well?

Yes, unless we plan on switching to shopify 😉

**Comment by brindasasi** [comment]
This has been completed. I accessed these urls and got error page and those access weren't showed in our logs. I hope it looks fine.
@petertgiles could you check and confirm?

**Comment by petertgiles** [comment]
Nice!  Yeah, I see the error message now.  Looks like the logs show it stopping after 2PM yesterday. :axe: 
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/93ce0b7b-6c02-49bf-93ec-e4e8bd8fe3c2)
