### ISSUE TITLE
🔤 Consolidate English strings and update translations

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8822]
## 🔤 Copy

> [!NOTE]  
> This issue is a refocused issue from #8463.  Refer back to that one for more context.  

We have many instances where multiple English strings with the same defaultMessage have been translated into different French strings.  Let's consolidate these English strings and use the updated translation.

## 🕵️ Details

h/t @RM-1978 for providing the updated translations.

The list of 86 new translations can be found in https://github.com/GCTC-NTGC/gc-digital-talent/files/13731311/Master_GCDT.translation.consistency_client.verified.12-20-2023.no.GCKey.xlsx .

## ✅ Acceptance Criteria

- [ ] Consolidate the multiple English strings to the same hash ID.
  - [ ] Syncing up the descriptions is fine.  Move to a shared messages file only where it's easy and makes sense.
- [ ] Upload the new translations from the workbook.

**Comment by RM-1978** [comment]
Hi @petertgiles Please note that I moved the translation consistency work for the GC Key FAQs  from this issue to issue #8599 
As you predicted, we now have just over 85 instances remedy in the list attached. 

[Master_GCDT.translation.consistency_client verified 12-20-2023 (no GCKey).xlsx](https://github.com/GCTC-NTGC/gc-digital-talent/files/13731311/Master_GCDT.translation.consistency_client.verified.12-20-2023.no.GCKey.xlsx)

Happy Holidays! 🎅

**Comment by petertgiles** [comment]
Thanks!  I updated the issue description.
