### ISSUE TITLE
🐛 Employment Equity section not showing Indigenous selection correctly on Admin "user information" page 

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#8825]
## 🐛 Bug

Indigenous Identity is not appearing correctly on the "User Information" page of the admin portal. The Employment Equity section there does not indicate indigenous identity for users who do have it. (It may, in some cases, indicate a user is indigenous when they are _not_, though I'm having trouble reproducing that.)

## 🦋 Expected Behaviour

If you look at the "User _Profile_" page or the Application snapshot, then indigenous identity appears correctly, including showing which communities the user is part of. However, the "User _Information_" page uses an older component. I'm guess it doesn't parse the communities enum correctly. We should probably just delete the Employment Equity component used on that page, and replace it everywhere with the component used on the User Profile page.

## 📋 Steps to Reproduce

1. Log in as a platform admin
2. In the users table, find a user who has claimed membership in an indigenous community (you can do this on your own profile, for simplicity)
3. Compare the Employment Equity blocks on the User Information and User Profile pages.

## 📸 Screenshot

"User Information" equity block:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/d6fb5b3b-8dd3-42aa-bb31-791470d93a1d)

"User Profile" equity block:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/c92f0b83-8a99-461b-a09d-db981f720eb2)

## 🙋‍♀️ Proposed Solution

See Matt's suggested solution below.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Equity Information appears consistent for a given user, wherever it is viewed

**Comment by mnigh** [comment]
Quick fix is removing the faulty logic (there should be no `!`) I introduced in: https://github.com/GCTC-NTGC/gc-digital-talent/pull/8748/files#diff-8214cac587ecf74db6882436afb46413e6b5dcff728d20ec29bc9fe7df3ef049R17
