### ISSUE TITLE
❓ Should the "User Information" equity data match the UI of the "User Profile"?

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#8827]
## Introduction

Employment Equity is displayed very differently on the User Profile and User Information pages in the admin portal. Do we want to make them consistent?

## 🦋 Details

When an admin looks at a "User Profile", they see equity information the same way the user themself sees it. 
- It is titled "Diversity, Equity and Inclusion"
- It uses sentence phrasing and first- and second- person pronouns
- Indigenous identity includes details about which specific community, and icons

On the "User Information" page the equity data is simplified
- titled "Employment Equity"
- each selection is simply a bullet point with a check mark
- indigenous identity is a simple yes/no value, no communities are listed

## The Question

Do we still want this difference in views? The second is older and less detailed, but may be a "cleaner" representation of what HR needs to know.

Its worth noting that the "printed" package admins can download to send to managers is closer to the "User Profile" view.

## 📸 Screenshot

"User Information" equity block:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/d6fb5b3b-8dd3-42aa-bb31-791470d93a1d)

"User Profile" equity block:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/c92f0b83-8a99-461b-a09d-db981f720eb2)

"Printed profile" equity block:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/1e038d1f-8167-4611-aa08-0523fadef3ba)

**Comment by gobyrne** [comment]
My first thought is that the difference is primarily to best present the info to the different users. However, we should add in community on the "User information" page now that we collect it (like we do for the printed profile).

@MCommonda @RM-1978 anything else?

**Comment by MCommonda** [comment]
@gobyrne @tristan-orourke I agree that the Indigenous community from which the user is affiliated should be reflected in both views.

**Comment by RM-1978** [comment]
@gobyrne and @tristan-orourke, I agree with Meagan that the data should be consistent across UIs. I also agree  with the value on presenting it a little differently to a manager to reflect the context in which it is found. For example, it could read: 

_Employment equity information
- Candidate affirms that they are affiliated with 
-  Candidate identifies as a person with a disability

**Comment by gobyrne** [comment]
I'll create a separate issue for Josh to take a look at this section of the profile... it could use some work.
