### ISSUE TITLE
✨ Pool: Skill Levels

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8828]
## ✨ Feature

Pools currently have a list of skills associated with them.  We need to add skill levels to those associations.

## 🎨 Design File

@substrae 

Pool editor:
https://www.figma.com/file/e2DTvyppj41m6slFWTDZ0U/Admin---Job-advertisement-creation?type=design&node-id=52-40341&mode=design&t=cs4ucOAt8RuZ44or-0

Pool advertisement:
https://www.figma.com/file/CdYmWlP6SpT17bw7Q9411Z/Candidates---Job-advertisement?type=design&node-id=260-5309&mode=design&t=83ZYhqDekaDoFFyC-0

## 📸 Screenshot

Pool editor:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/27d5a77a-cf28-47fc-a275-5faf7a0e8134)

Pool advertisement:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/6ac8a71e-c0c5-42aa-a5b4-d3692f84b2f4)

Dialog:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/17c94703-d3e0-441a-a4d7-5447ca40ebfa)

## ✅ Acceptance Criteria

- [ ] add skill levels to `PoolSkill` model
- [ ] deprecate essentialSkills and nonessentialSkills fields
- [ ] remove canOnParent directive from Pool.poolSkills
- [ ] switch from essentialSkills/nonessentialSkills to poolSkills everywhere in the client
- [ ] migration, database field, Eloquent model
- [ ] seeder, factor updates
- [ ] Graphql query update, mutation update
@substrae Should existing pools in the database use the Entry Level option?
@petertgiles I think this can't be the case - we will likely need to allow existing pools to exist without them. Answer: leave the existing pools null.
- [ ] Pool editor, editable state
- [ ] Pool editor, readonly state
- [ ] Pool advertisement, accordion
- [ ] Pool advertisement, "understanding skill levels" dialog
- [ ] frontend "pool can publish" validation update
- [ ] backend "pool can publish" validation update
- [ ] Skill levels are required to publish
- [ ] Old pools without skill levels are still viewable

**Comment by vd1992** [comment]
@substrae 

I think the design of the skill level select still needs to be added to Figma, please do so when you can.
As in, expanded out so you can see what the copy should be for that level select. It will be different than our existing skill level select for users to fill their library. 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/935bd18e-b472-4f00-a610-31b5e84dab66)

**Comment by substrae** [comment]
@vd1992 

The designs can be found in the skill form section of our Style library file. I've tossed a screenshot here for good measure. Lemme know if you have trouble finding it.

https://www.figma.com/file/guHeIIh8dqFVCks310Wv0G/Style-library?type=design&node-id=97-30604&mode=design&t=337NLABGwQAJEHNJ-4

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/ea1a5ec5-3c2f-47a3-b038-d5160e7395a7)
