### ISSUE TITLE
✨ Pools: Rework adding screening questions

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8832]
## ✨ Feature

The pools editor is reworking the screening questions section to get rid of the "don't forget to save your changes" scenario.

## 🕵️ Details

When the time comes to work on this ticket, reach out to @gobyrne and @substrae to talk about the conflicts between RoD and this ticket. 

## 🎨 Design File

@substrae 

https://www.figma.com/file/e2DTvyppj41m6slFWTDZ0U/Admin---Job-advertisement-creation?type=design&node-id=52-40341&mode=design&t=cs4ucOAt8RuZ44or-0

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/a4fffdd9-5dd3-4bbc-b3c6-9663f8e1150b)
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/b5cf0a6e-0525-424e-8ed8-39090dbe8827)

## ✅ Acceptance Criteria

- [ ] limit: three questions
- [ ] reordering mutation happens immediately
- [ ] removal opens a "are you sure" dialog
- [ ] editing or creating opens the "manage" dialog

**Comment by tristan-orourke** [comment]
This is now redundant with #8676
