### ISSUE TITLE
🐛 Prod logged error: location exemption too long

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8837]
## 🐛 Bug

Our server is logging errors that users are trying to enter location exemptions that are too long.

## 📋 Steps to Reproduce

1. Log in and navigate to /users/:yourUserId/personal-information
2. Edit the Work preferences section and try to enter a value longer than 255 chars in the "Please indicate if there is a city that you would like to exclude from a region." field.

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/af0ea691-b1a8-4b5c-8c44-8da006b895ec)

## 🙋‍♀️ Proposed Solution

~Option 1: Add frontend validation to reject strings longer than 255 chars and switch to input field~
Option 2: Migrate the backing database column from varchar(255) to text type.

Since the input is a text area and not a single line input, I think 2 is more appropriate. @gobyrne agrees, acceptance criteria updated

## ✅ Acceptance Criteria

- [ ] Long input will be successfully saved.

**Comment by gobyrne** [comment]
Ok, I agree with option 2. Updated the description and acceptance criteria
