### ISSUE TITLE
🐛 User is forced to log out during pool creation 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#8840]
## 🐛 Bug

During UAT, user was forced to log out during pool creation TWICE.
First time , user created the pool and click on "Publish Advertisement" button. 
She was taken to log out page without any warning. 

Second time , user logged back and was in middle of creating a pool and saved location information. User got bunch of errors as below in the screenshot before she was taken to log out page. Pool was saved in draft state though.

Third time, user logged back in , changed location again, then she was able to publish the pool the draft pool she already created. 

## 🦋 Expected Behaviour

Pool creation should be fine without forced log out. 
Dasha, Lee reported the same problem in prod & uat respectively. 

## 📋 Steps to Reproduce

This is very intermittent.

## 📸 Screenshot

<img width="1115" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDV5QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2e53252005d06dd5635aec2c9499344190681b0b/image.png" alt="image.png" />

Error log for the above error
![image (28)](https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/af96e2e0-e80b-4d5c-8540-7bebff494487)

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Pool creation should be smooth without any forced log out

**Comment by RM-1978** [comment]
Thanks so much for catching this bug. @petertgiles, might this issue be linked to: https://github.com/GCTC-NTGC/gc-digital-talent/issues/8779 [accessibility](https://github.com/GCTC-NTGC/gc-digital-talent/issues?q=is%3Aissue+is%3Aopen+8779+label%3Aaccessibility)  [feature](https://github.com/GCTC-NTGC/gc-digital-talent/issues?q=is%3Aissue+is%3Aopen+8779+label%3Afeature)

**Comment by petertgiles** [comment]
> Thanks so much for catching this bug. @petertgiles, might this issue be linked to: #8779 [accessibility](https://github.com/GCTC-NTGC/gc-digital-talent/issues?q=is%3Aissue+is%3Aopen+8779+label%3Aaccessibility) [feature](https://github.com/GCTC-NTGC/gc-digital-talent/issues?q=is%3Aissue+is%3Aopen+8779+label%3Afeature)?

Related definitely, but maybe not quite the same.  I think the first issue that users are having their sessions ended prematurely.  The second issue is that when the session does end, the UX is not ideal.  The first issue is pretty bad on its own but I think that the second issue is exacerbating it.

**Comment by petertgiles** [comment]
Closing in preference for  #8845
