### ISSUE TITLE
🐛 Accessibility bug: Update the required field error message with programmatic instructional text.

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/gc-digital-talent#8851]
## 🐛 Accessibility Bug

There is no instructional text for **required fields** on how to fix them.  

## 🙋‍♀️ Proposed solution
 
Replace the current pattern with:

EN:  {Label}: This field is required. Please enter a value.
FR:  {Label}: Ce champ est obligatoire. Veuillez inscrire une valeur.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] All code instances of a **required field** follow the new instructional pattern.

**Comment by petertgiles** [comment]
These fields already come up with an error message "{Label}: This field is required."  You just want to add "Please enter a value." to the end of the error message?
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/f4247733-b340-46f1-b6aa-70ccb06fe204)
