### ISSUE TITLE
♻️ Bump `date-fns` to `>3.0.0`

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#8886]
## ♻️ Debt/Refactor

Our date library released a new major version that has come with some breaking changes.

## 🕵️ Details

REF: https://github.com/date-fns/date-fns/releases/tag/v3.0.0

The main changes to deal with are how imports work. They not exclusively use named imports. Most of the work should be updating all imports to this.

Another great change is that the entire library is now written in TypeScript and they rely more on the type checker so functions _should_ have a bit smaller footprint.

## 🙋‍♀️ Proposed Solution

Bump both `date-fns` and `date-fns-tz` to `>=3.0.0` and resolve all breaking changes:

 - [`data-fns`](https://github.com/date-fns/date-fns/releases/tag/v3.0.0).
 - [`date-fns-ts`](https://github.com/marnusw/date-fns-tz/releases/tag/v3.0.0)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] `date-fns` is on version `3.0.0` or later
- [ ] `date-fns-tz` is on version `3.0.0` or later
- [ ] Breaking changes resolved

**Comment by petertgiles** [comment]
A bit early.  Let's wait until 3.1 or after the holidays.

**Comment by petertgiles** [comment]
It's after the holidays and 3.1 has been released.
https://github.com/date-fns/date-fns/releases/tag/v3.1.0

**Comment by mnigh** [comment]
this issue is blocked by the fact that `date-fns-tz` is not yet compatible with `date-fns` `>3.0.0`:
- https://github.com/marnusw/date-fns-tz/issues/260

**Comment by mnigh** [comment]
stable release of `date-fns-tz` compatible with `date-fns` `>3.0.0` coming soon:
- https://github.com/marnusw/date-fns-tz/pull/273

**Comment by esizer** [comment]
> stable release of `date-fns-tz` compatible with `date-fns` `>3.0.0` coming soon:

It has been released https://github.com/marnusw/date-fns-tz/releases/tag/v3.0.0
