### ISSUE TITLE
🏐 - Find out if GCKey can measure signup/login dropoff

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8887]
## ✨ Intro

We would like to know the dropoff rate as someone moves through GCKey.  This would be very hard for us to do.  Ask the SIC team if they can measure this.

## :question: Main Question

Can the SIC team measure the dropoff rate through GCKey?

## :beverage_box:  Timebox
- 1 email

## ✅ Acceptance Criteria

- [ ] If yes, update #5530 with the instructions.
- [ ] If no, add a note to #5530.

**Comment by brindasasi** [comment]
idk any one on the SIC team. Can someone please drop a contact email id for this? 
@tristan-orourke 
@petertgiles

**Comment by petertgiles** [comment]
That team's shared mailbox is

**Comment by brindasasi** [comment]
Email sent
![waiting-patiently-waiting](https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/e810cdea-2d5e-4038-ab5e-ab1b6a000322)

**Comment by brindasasi** [comment]
I got the reply from SIC team that their team has been refocused on some other project and can't look into this report for their clients. But they can connect with us to GCKey team as they are their authentication provider. Should we want to continue directly dealing with GCKey team?

**Comment by brindasasi** [comment]
I got the message from GCKey team

> We inquired with our developers, and we were able to get a drop off rate of about 21% for the last 30 days of all GCKey transactions.
> We unfortunately do not have capacity to further augment the code to provide more client specific reporting and we were told the GCKey team would not be able to discern the clients being redirected from Sign In Canada.

**Comment by tristan-orourke** [comment]
We got our answer!
