### ISSUE TITLE
🔤 View inconsistently translated in French

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#8896]
## 🔤 Copy

The string **view**, meaning the same thing everywhere, has been translated in different ways in French.

### View = Affichage
https://github.com/GCTC-NTGC/gc-digital-talent/blob/f6b0ce8cab1a021cd178995d2ee5bb03c4403fc0/apps/web/src/components/PoolCandidatesTable/tableMessages.ts#L15-L19

https://github.com/GCTC-NTGC/gc-digital-talent/blob/f6b0ce8cab1a021cd178995d2ee5bb03c4403fc0/apps/web/src/lang/fr.json#L5882-L5885

### View = Voir
https://github.com/GCTC-NTGC/gc-digital-talent/blob/f6b0ce8cab1a021cd178995d2ee5bb03c4403fc0/apps/web/src/messages/adminMessages.ts#L14-L18

https://github.com/GCTC-NTGC/gc-digital-talent/blob/f6b0ce8cab1a021cd178995d2ee5bb03c4403fc0/apps/web/src/lang/fr.json#L4030-L4033

##### Consulter

- View notifications = Consulter toutes les notifications
- View all notifications = Consulter toutes les notifications
- View and manage your notification history. = Consultez et gérez l'historique de vos notifications.
- View up-to-date profile = Consulter le profil à jour
- View experience = Consulter l’expérience
- View Notes = Consulter les notes
- ~View full summary = Consulter le résumé intégral~
- View assessment plan = Consulter le plan d’évaluation
- View the job poster for this recruitment process = Consulter l’affiche d’emploi pour ce processus de recrutement
- View experience for {experienceName} = Veuillez consulter l’expérience pour {experienceName}

> [!NOTE]  
> Not sure why in French _veuillez_ (please) is included in the French translate when it is not there in English.

##### Afficher
- View open pools = Afficher les bassins ouverts
- View team members = Afficher les membres de l’équipe
- View user = Afficher l’utilisateur

##### Voir
- View results = Voir les résultats
- View Candidates<hidden> for {label}</hidden> = Voir les candidats<hidden> pour {label}</hidden>
- View my application = Voir ma demande
- View advertisement = Voir l’annonce
- View {name} <hidden>{hiddenLabel}</hidden> = Vue {name} <hidden>{hiddenLabel}</hidden>

REF: https://github.com/search?q=repo%3AGCTC-NTGC%2Fgc-digital-talent+%22View++language%3ATSX&type=code

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the copy has been added or updated appropriately.

- [ ] the word **view** translated in French consistently
- [ ] unused [`tableMessages.view`](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/apps/web/src/components/PoolCandidatesTable/tableMessages.ts#L4-L8) removed

**Comment by mnigh** [comment]
@gobyrne 

1. Which French verb should we be using for the verb to view: _consulter_, _afficher_, or _voir_?
2. Can `veuillez` be removed from this string in French? `View experience for {experienceName} = Veuillez consulter l’expérience pour {experienceName}`

**Comment by gobyrne** [comment]
1. I'd like to standardise on "Voir", I think it can just be swapped in for those other verbs.
2. Yes
