### ISSUE TITLE
✏️ Document how to set up a new Freshdesk instance

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8900]
## ✏️ Documentation

Document how to set up a new Freshdesk instance and test it in a `freshdesk.md` file in documentation directory.

## 🕵️ Details

https://developers.freshdesk.com/api/

## ✅ Acceptance Criteria

- [ ] Where to add the new api key and endpoint
- [ ] How to collect the product ID and email config ID
- [ ] How to test

**Comment by mnigh** [comment]
For reference, there is some internal documentation with the code already: https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/api/config/freshdesk.php
