### ISSUE TITLE
🐛 Classification forms have incorrect error message for minimum value requirement

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#8959]
## 🐛 Bug

Salary inputs on our CreateClassification and UpdateClassification forms (for the admin platform) have a `min` value rule with the error message "Value must be greater than 0." when technically they actually accept a value of 0 or greater.

## 🦋 Expected Behaviour

If the error message is "must be greater than 0" then the minimum value should be 1.

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Name and version (if possible).
- **Browser**: Name and version (if possible).

## 📋 Steps to Reproduce

1. ...
2. ...

## 📸 Screenshot

Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] If the error message is "must be greater than 0" then the minimum value should be 1.

**Comment by gobyrne** [comment]
@tristan-orourke, I admire your commitment to the truth... but I would recommend just closing this. If it bugs you that much, we can pull it in... it's obviously easy to fix.

**Comment by tristan-orourke** [comment]
Yeah, I'll close this. When I was investigating the ticket in the first place I though there were going to be more problematic instances of incorrect min messages, but then this was it.
