### ISSUE TITLE
♻️ Upgrade to Node.js 20 and NPM 10.

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#8963]
## ♻️ Debt/Refactor

The latest (as of now) LTS version of Node.js is 20 and it comes with NPM 10.  Since we're on Node.js 18 and NPM 8 we should consider upgrading.

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/79747b4c-a103-4399-9cc7-dfc12a2408c3)

## ✅ Acceptance Criteria

- [ ] package.json and lock files updated
- [ ] Maintenance container updated
- [ ] GH workflows updated
- [ ] Help your teammates update their environments

**Comment by tristan-orourke** [comment]
I love "help your teammates" as an acceptance criteria <3
