### ISSUE TITLE
IAP manager homepage

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#9008]
### Details
This is a new page "Hire an IT apprentice" for the IAP. Page does NOT need to be translated into indigenous languages.

Suggested URL: talent.canada.ca/**indigenous-it-apprentice/hire**

contact the team email: [edsc.patipa.jumelage.emplois-itapip.job.matching.esdc@hrsdc-rhdcc.gc.ca](mailto:edsc.patipa.jumelage.emplois-itapip.job.matching.esdc@hrsdc-rhdcc.gc.ca)

### Blocked Design
Still missing from design:
- [x] Manager package - accessibility review and theme
- [x] Alt text review with @MCommonda and @RM-1978 
- [x] @substrae cleanup of figma file and dark mode if required

### Screenshot
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/100953374/53101ef5-6f72-4f49-81bc-9f45618310b2)

### Figma file
https://www.figma.com/file/GPnW22jecfvifZRtWwZFTl/Hire-an-apprentice_Manager-Page_ITAP-edits?type=design&node-id=487-1879&mode=design&t=EhBHGqrADVbLglX3-0

### **Webp images**
https://drive.google.com/drive/folders/10fUq8m3vB4dv6YoFeHFlgLser7uquhMo?usp=sharing

### Acceptance criteria

- [ ] New page on IAP site (at suggested URL)
- [ ] New page matches Figma design and content
- [ ] Images use alt-text from Meagan in the comment below
- [ ] Images scaled to web standards
- [ ] New nav item on the IAP site "Hire an IT apprentice"
- [ ] Alt text for images: https://docs.google.com/document/d/1SyWi4Y1OGRjW7R5BYbL_fglZcrjDkPOflSrhWqAhLUg/edit?usp=sharing
- [ ] Download buttons should download this file: [ITAPIP Manager Package Text_FINAL_with frame.docx](https://github.com/GCTC-NTGC/gc-digital-talent/files/13939504/ITAPIP.Manager.Package.Text_FINAL_with.frame.docx)
- [ ] Contact the team link: edsc.patipa.jumelage.emplois-itapip.job.matching.esdc@hrsdc-rhdcc.gc.ca
- [ ] Add Chromatic snapshot 
- [ ] Dark mode tested/implemented?

**Comment by MCommonda** [comment]
Alt. text: https://docs.google.com/document/d/1SyWi4Y1OGRjW7R5BYbL_fglZcrjDkPOflSrhWqAhLUg/edit?usp=sharing

**Comment by MCommonda** [comment]
Manager's info package (which is to be made available for download) in English: 

[ITAPIP Manager Package Text_FINAL_with frame.docx](https://github.com/GCTC-NTGC/gc-digital-talent/files/13939504/ITAPIP.Manager.Package.Text_FINAL_with.frame.docx)

**Comment by tristan-orourke** [comment]
We will also need the manager package in French (though we can get started without it)

**Comment by petertgiles** [comment]
Is there a link to this page from anywhere?

**Comment by petertgiles** [comment]
Could you please add a list of where all the links go and what all the buttons do?

**Comment by petertgiles** [comment]
Could we please get mobile views?

**Comment by substrae** [comment]
@yonikid15 @petertgiles

A mobile view has been added to the Figma file. We're working on the `webp` images, but because Brooke originally sourced and edited them, we don't have access to the resolutions we need at the moment. We'll let you know when we have something to work with. @MCommonda is gonna provide the links and pathing info you need.

**Comment by MCommonda** [comment]
[Action buttons for IAP managers page.docx](https://github.com/GCTC-NTGC/gc-digital-talent/files/13965347/Action.buttons.for.IAP.managers.page.docx)
