### ISSUE TITLE
🐛 Table filters in url initially being applied

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#9013]
## 🐛 Bug

If you use the browser Back function to return to a table page, the filters and page number from when you were previously on the page will not be applied (even though they are visible in the url parameters).

## 🦋 Expected Behaviour

If you set table filters or change the page, and go to another page, then go "Back", the table should be in the state you left it.

## 📋 Steps to Reproduce

1. Log in as admin
2. Go to a pool candidates page
3. Change some filters and go to page 2
4. Click a candidate to go to the candidate page
5. Click "back" in the browser
6. The table should be on page 2 with the same filters applied, but it is not

## 📸 Screenshot

Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Table filters and page in the url parameters should be applied immediately when the page loads, if present
- [ ] Test solution in prod env

**Comment by tristan-orourke** [comment]
Hunch: If it seems to work locally, maybe this is caused by useEffect firing twice vs once in production?

**Comment by esizer** [comment]
Tested with local prod build and it seems to function as expected 🤔 Also checked and for this specific use case we do not rely on `useEffect`.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/cbe6c0f061ef3bc201669092defeaf4654645918/apps/web/src/components/PoolCandidatesTable/PoolCandidatesTable.tsx#L160-L169

https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/2c00efae-1bd4-41f5-a2b2-be5d03f107bb

**Comment by tristan-orourke** [comment]
@esizer the filters and the page number _look_ like they're correct, but aren't the names of the candidates actually different from what they should be? Compare 12 seconds to 27 seconds in your video.
