### ISSUE TITLE
✨ Add basic filters to Assessment Step tracker

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#9016]
## ✨ Feature

Add filters to the Assessment Step tracker which allows for filtering by name, and hiding various statuses.

## 🕵️ Details

Add a search bar which filters users by name, to quickly find the status of a particular candidate.

Add switches which allow for hiding users in certain statuses from each column.

The figma design includes a "More filters" button, but we can leave it out for now.

## 🎨 Design File

https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Pools---Record-of-Decision?type=design&node-id=6872-37861&mode=design&t=A1V8ZwHD6eu2g4XZ-0

### 🧑‍🎨 Designer

@Jerryescandon 

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/0969ebf6-56af-4bf8-ba0e-3dbf35e10d7c)

## 🙋‍♀️ Proposed Implementation

The filters could be build as part of the Assessment Step Tracker component or in its parent component.

The search bar can filter out candidates before even passing them to the (rest of the) Assessment Step Tracker.

The statuses to hide (or show) can be passed into the individual Assessment Step Tracker columns as props, and they can simply avoid showing any candidates (and totals) in those statuses.

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Search bar above the Assessment Step Tracker. If any text is in the search bar, filter out any candidates whose names do not match (case insensitive)
- [ ] 4 switches for 4 statuses, default to ON. If any switch is turned OFF, then each assessment step hides any candidates in that status for that step. (Also hides the total count for that step.)

**Comment by tristan-orourke** [comment]
@Jerryescandon can you confirm: should the status filters should hide the total counts for the status along with the individual candidates?

**Comment by Jerryescandon** [comment]
Confirmed!
