### ISSUE TITLE
✨ "Go to next candidate" and "Go to previous candidate" on Candidate assessment page

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#9017]
## ✨ Feature

Admins' workflow will be much smoother if they can go directly from one candidate assessment to the next, without having to go back to the previous table first.

## 🕵️ Details

IF you go from the Assessment Step tracker to a Candidate page, we can pass along the list of candidates from the assessment step column you clicked on, along with the step of the column you clicked.

IF that list is available (it will not be if you reached the Candidate page in any other way) THEN show the "Go to next candidate link", which goes directly to the next candidate in the list. The list should be passed to that next page as well. Same goes for "Go to previous candidate".

IF there is a list but you're already on the last (or first) candidate, the link should go back to the Assessment Step tracker instead. The arrow switches direction and the copy changes to "Back to assessments tracker".

## 🎨 Design File

https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Pools---Record-of-Decision?type=design&node-id=6874-39127&mode=design&t=A1V8ZwHD6eu2g4XZ-0

### 🧑‍🎨 Designer

@Jerryescandon 

### Next/Previous candidate links

![Image](https://github.com/GCTC-NTGC/design-gc-digital-talent/assets/16977254/7f740a66-cc83-4157-9563-fca50f8c3db2)

### Order based on Assessment Step Tracker list

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/d46c5c98-cba3-4a6a-b8d6-4604aded406f)

## 🙋‍♀️ Proposed Implementation

Pass the list of candidates (just need an id, for the link) to the page using the history state api, along with the current index. When clicking the Next or Previous candidate links, modify the index and pass it to the next page along with the list.

If no list has been passed, don't show the "Currently screening" and "go to next step" section at all.

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] If you go from the Assessment Step Tracker to a Candidate page, the Step you clicked on appears under "Currently Screening", and "go to next candidate" and "go to previous candidate" links appear
- [ ] The order of the next/prev candidate list is based on the list as it appeared on the Assessment Step tracker (including any filtering which was applied)
- [ ] If you go from a Candidate page where this block appears, it chains to the next candidate page IF you follow the link to get there.
- [ ] If you reached the candidate page in any other way, the Current screening and Go to next candidate section is not rendered
- [ ] If you've reached the end of the list, the link sends you back to the assessment tracker instead. The arrow also switches direction and the copy changes to "Back to assessments tracker".
- [ ] If you're at the start of the list, the "go to previous candidate" instead says "Back to assessments tracker"
- [ ] (update) Above the Next / Previous links, it should read `Step #: <name of step>` where the step is the column you clicked in the Assessment Tracker page (the column which next and previous navigate you through)

**Comment by tristan-orourke** [comment]
@Jerryescandon What should the link read if you've reached the end of the list and it's sending you back to the assessment step tracker?

**Comment by Jerryescandon** [comment]
> @Jerryescandon What should the link read if you've reached the end of the list and it's sending you back to the assessment step tracker?

"Back to assessments tracker"

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/6768b7ab-4a6c-465f-bdec-2b61bab68d35)

**Comment by gobyrne** [comment]
might be worth combining with #9237

**Comment by tristan-orourke** [comment]
Added in "Go to previous candidate" from #9237
