### ISSUE TITLE
Filters on Request page - department not in alphabetical order

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#9023]
## Details
On the request page, you can filter the table by department, but the list of departments is not in alphabetical order.

Let's sort it alphabetically!

NOTE: Update base component

![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/b0f21731-f575-4707-9295-75c775739aed)

## Acceptance Criteria

- [ ] Department filter is sorted alphabetically on Request page
- [ ] Update base component to sort alphabetically
- [ ] alphabetical handling of capitalization
- [ ] handling of French accented characters
- [ ] handling of non-alphanumeric characters

**Comment by petertgiles** [comment]
I'd like to see some tests for corner cases:
- alphabetical handling of capitalization
- handling of French accented characters
- handling of non-alphanumeric characters
