### ISSUE TITLE
✨ Consolidate generic table actions on second column

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#9032]
## ✨ Feature

We should standardize the first and second column on every table to include row-item-names and then all actions related to this item using an "action menu" component.

This improves table readability, we standardize expectations, and we allow ourselves some room to add more complex actions without the need for new columns.

## 🕵️ Details

Add any additional details that could assist with the development of the new feature.

## 🎨 Design File and Designer

Include a link to the design file (if it exists) by @Jerryescandon 

## 📸 Screenshot

Add a screenshot of the new feature (if possible).

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Criteria 1
- [ ] Criteria 2

**Comment by mnigh** [comment]
@Jerryescandon how many actions would there be for each table? are you working on designs for the tables that would be changed?

**Comment by Jerryescandon** [comment]
We will cleanup tables in the future, imma close this one in favor of the "Cleanup admin" epic we have in the works
