### ISSUE TITLE
🐛 [Prod bug] Order mismatch between candidates shown in a table and downloaded in spreadsheet

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#9040]
## 🐛 Bug

"We are trying to pull the screened out candidates from the PM-04 process and are having issues. Initially, the board report is blank. We have to reset the results page before it will populate. We have to pull the entries 50 at a time, and even when that works the candidates are not in the same order on the spreadsheet as they appear on the page. So for example, I have 50 candidates on screen, I pull a board report of 50 entries, and then there are names on the report that are not on the page I am pulling the data from. Does this make sense? We are double checking who is screened out so we want to make sure nobody is missed."

## 🦋 Expected Behaviour

The candidates in a downloaded spreadsheet or printable page should match the candidates and order of the selected rows in the table.

If you downloaded after clicking "Select all", then all the candidates in the table, and no more, should appear in the downloaded file.

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Name and version (if possible).
- **Browser**: Name and version (if possible).

## 📋 Steps to Reproduce

1. ...
2. ...

## 📸 Screenshot

Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] The candidates in a downloaded spreadsheet or printable page match the candidates (and ordering) of the selected rows in the table.
- [ ] If you downloaded after clicking "Select all", then all the candidates in the table, and no more, should appear in the downloaded file, in the same order they appear in the table.

**Comment by brindasasi** [comment]
I can't reproduce this anymore in local or UAT.
