### ISSUE TITLE
✨ Update Screening/General questions on Application

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#9041]
## ✨ Feature

Update the application to reflect the fact that Screening Questions have become General Questions (#9034), and then new Screening Questions have been added (#9038).

## 🕵️ Details

**NOTE: All the changes on this page must be hidden behind the RoD feature flag!**

**Candidates - Application Step 6: Additional questions** [Figma file](https://www.figma.com/file/9nYcfEsF4u6UuVR4lWnYnL/Candidates---Application-Step-6%3A-General-questions?type=design&node-id=0%3A1&mode=design&t=3jrPUbJHCRTEQy9F-1)

The candidates application flow would need updates in 3 places: the instructions page, the questions page and the application review page.

The instructions would see a change in copy, the questions page would actually present BOTH the screening and general questions with each appearing in its own section, and finally we would add them both as static version to the application review page.

<details><summary>📸Instructions page </summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/c0d40dce-5dfa-4f2f-a973-88c0dbcab5ff)

</p>
</details> 

<details><summary>📸Work page </summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/1d7a41b1-96ed-4fc4-92bd-7a99286c4c11)

</p>
</details> 

 <br>

**Candidates - Application Step 7: Review page** [Figma file](https://www.figma.com/file/BXYVsu1fo9LS2IySJDUINY/Candidates---Job-application---Version-1-to-6?type=design&node-id=636%3A59839&mode=design&t=KfYZ0LXeWghleeOT-1)

<details><summary>📸Review page </summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/28669587-da44-411c-957e-c99b6062365a)

</p>
</details> 

 <br>

**Admin - Candidate application page** [Figma file](https://www.figma.com/file/9nYcfEsF4u6UuVR4lWnYnL/Candidates---Application-Step-6%3A-General-questions?type=design&node-id=0%3A1&mode=design&t=3jrPUbJHCRTEQy9F-1)

<details><summary>📸Application page </summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/0c93ba69-31e3-4db0-bd3e-2e7128396ea4)

</p>
</details> 

 <br>

### 🧑‍🎨 Designer

@substrae 

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] All changes part of this ticket ONLY APPEAR if RoD feature flag is true
- [ ] Application UI updated on the instructions page, the questions page and the application review page.
- [ ] Applicants can create and edit their ScreeningQuestionReponses AND GeneralQuestionResponses
- [ ] Managers with permission to review a PoolCandidate can see both types of responses
- [ ] Application validation (frontend AND backend) is updated so that all general questions AND screening questions must be answered for application to be ready to submit. (This change also requires feature flag to activate)
- [ ] Update Application validation jest test, or create if doesn't exist yet
- [ ] Update phpunit application submission test (to check new validation) or create one if it doesn't exist yet

**Comment by vd1992** [comment]
@tristan-orourke 
I don't think this is ready to be developed, it appears to need the completion of
https://github.com/GCTC-NTGC/gc-digital-talent/issues/9034
https://github.com/GCTC-NTGC/gc-digital-talent/issues/9038
Per feature section and issue goal
