### ISSUE TITLE
🛠️ Add a new dev pipeline to install the build with dev dependencies

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#9056]
## 🛠️ Tooling
 
 Add a new dev pipeline to install the build with dev dependencies so that faker for bulk data generation and  end to end testing can be run in azure.

## 🕵️ Details

We need this pipeline so that we can run the all kinds of automated testing(E2E , load, performance) on latest main with bulk data on azure environment. This will help us speed up the release process while ensuring quality.

## 🙋‍♀️ Proposed Solution

- [ ] Create a dev-deploy.sh to include dev deps 
- [ ] Create a dev-azure-pipelines.yml to deploy dev-deploy.sh 
- [ ] Create a new Azure pipeline that can deploy from dev-azure-pipelines.yml 

## ✅ Acceptance Criteria

- [ ] a new pipeline exists and generate the build artifact, in prod mode, but with access to faker and data seeders.
- [ ] creating a new release from that pipeline should install the selected artifact into the dev env.

**Comment by tristan-orourke** [comment]
We actually want the project build in "prod" mode, despite adding some dev tools.

For now, just add access to faker.
