### ISSUE TITLE
The x to clear skills picker doesn't work on the search page

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#9060]
## 🐛 Bug

Using Edge browser, the x on the skills picker used to clear the contents of the text search does not work.

## 🦋 Expected Behaviour

x in skills picker should clear contents of the input

## 🕵️ Details

- **Operating System**: Windows 10
- **Browser**: Edge (works fine in Chrome)

## 📋 Steps to Reproduce

1. In edge browser go to /en/search
2. Select a skill family, then Type in the skill input text field
3. Press the x to clear the input field

I tried this on a different skills picker on our site and it worked ok.

## 📸 Screenshot

![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/22438641-b5e6-4acc-8f84-af5abc7004dd)

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] x clears the text input field on skills picker

**Comment by tristan-orourke** [comment]
Reproduced in Chrome as well
