### ISSUE TITLE
Showing results values at the bottom of tables sometimes don't reflect the filters

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#9061]
## 🐛 Bug

When filters are applied, some tables to not update the number of "showing" results properly.

This currently works properly on the users table & candidates table, but not on the Pools table or Skills table for example.

## 🦋 Expected Behaviour

When you filter, the "showing" results should always adjust to reflect the filters.

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Name and version (if possible).
- **Browser**: Name and version (if possible).

## 📋 Steps to Reproduce

1. navigate to Pools page on admin UI
2. type something in the filter like "as"
3. Look at the "showing results 1-10..." copy at the bottom of the table. The total number of records does not reflect the filter.
4. try this on the users table to see how it should work

## 📸 Screenshot

Notice that it shows 11-20 of 261. But we are on "Show 10" and there are only 2 pages available for pagination.

![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/3a1e1d9f-9472-4fd8-afb1-453555a74021)

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Filters consistently affect the "showing" results on all tables

**Comment by tristan-orourke** [comment]
Seems like the "Showing results of" is not working properly for client-side-driven tables. They need to apply the filters to that number as well.
