### ISSUE TITLE
Skills in the showcase bring you back to the library

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#9062]
## 🐛 Bug

When you click a skill in the **Skills showcase**, if you click "save", you are brought to the **skills library**.

## 🦋 Expected Behaviour

When you click a skill in the **Skills showcase**, if you save it, you are brought back to the **skills showcase**.

## 📋 Steps to Reproduce

1. Go to skills showcase
2. Click a skill
3. Click save
4. You are brought to the Skills library

## 🙋‍♀️ Proposed Solution

Use a "from" key parameter in url.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Saving a skill in skills showcase brings you back to the place you came from (ie showcase OR skills library, depending.)
- [ ] Check if you can get to this skill page from anywhere else, and unsure we send you there correctly as well.

**Comment by tristan-orourke** [comment]
Note: you can get here from multiple places - the skills library OR the skills showcase. It should send you back to the appropriate one.
