### ISSUE TITLE
🐛 [Prod] Entering the same month,year for experience end date field throws error in prod

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#9063]
## 🐛 Bug

Entering the same month,year for experience end date field throws error in prod. We added this functionality in the last release but looks like it doesn't work any more.

## 🦋 Expected Behavior

Entering the same month,year for experience end date field should be allowed. 

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Name and version (if possible).
- **Browser**: Name and version (if possible).

## 📋 Steps to Reproduce

1. Edit currently active experience on your profile
2. Uncheck the "I am currently active .. " check box
3. Observe new end date box appears
4. Enter the same date as start date 
5. Observe the error ( apparently I get diff error messages in diff env. local, uat, prod  but that's still ok for this bug. We just don't want any error thrown.) 

## 📸 Screenshot

<img width="1075" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzduQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--914a550cfaf3925f69bea204e1640ae7a26da81f/Screenshot%202024-01-22%20at%2010.37.43%20AM.png" alt="Screenshot 2024-01-22 at 10.37.43 AM.png" />

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Entering the same month,year for experience end date field should be allowed.

**Comment by yonikid15** [comment]
#8925 Previous attempt to fix issue

**Comment by vd1992** [comment]
Cannot seem to replicate 😕 

https://recordit.co/KoPirXMTd7

**Comment by brindasasi** [comment]
oops .. I figured it is only happening when you edit the experience which doesn't have end date previously.
That means , editing an "Currently Active" one. 
I remember this is the exact specific scenario we tried in UAT as well. 
https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/76e41861-a04f-4bc0-91ad-97cc9692fd90

**Comment by brindasasi** [comment]
A/C updated
