### ISSUE TITLE
✨ Integrate full text search into query builder

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#9071]
## ✨ Feature

Currently the full text search in the user model executes its own query first then integrates the IDs into the query builder separately.  This is working but has a couple of drawbacks.  The first is that the performance lessened since we're requesting the data with two operations serially with two separate queries.  The second is that any existing query scopes are not applied to the text search query and potentially many of the resulting IDs have to be thrown out.  The third is that the database cannot cache or optimize the query because the parameter count and values change every time.

Let's try to integrate the full text search feature directly into the query builder to optimize performance and flexibility.

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/d7c91218-f1bf-4e9c-ab63-89aafa489508)

## ✅ Acceptance Criteria

- [ ] scopeGeneralSearch adds to the query builder without running its own query
- [ ] Index updating and results continue to function currectly

**Comment by tristan-orourke** [comment]
Will this work?
```
return $query->search($combinedSearchTerm)->usingWebSearchQuery()
```

**Comment by tristan-orourke** [comment]
If it doesn't work easily, can re-estimate
