### ISSUE TITLE
♻️ Improve seeding performance

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#9072]
## ♻️ Debt/Refactor

The database seeding takes considerably longer these days, almost two minutes on my workstation.  Can this be improved?

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/1753d7e3-28c8-4090-9705-54c213f07e8e)

## 🙋‍♀️ Proposed Solution

I think a big portion of this is the new full text indexing.  Maybe push indexing to a queue?  Or don't index seeded seeded models at all?

## ✅ Acceptance Criteria

- [ ] Database seeding performance improved

**Comment by esizer** [comment]
Duplicate of https://github.com/GCTC-NTGC/gc-digital-talent/issues/5045 ?

**Comment by petertgiles** [comment]
> Duplicate of #5045 ?

Lol, it was only one minute back then.  :skull: 
I guess the problem is now worse, for a second reason.  I'm not sure if that's a duplicate or not.  :laughing:

**Comment by esizer** [comment]
> Lol, it was only one minute back then. 💀
> I guess the problem is now worse, for a second reason. I'm not sure if that's a duplicate or not. 😆

Yeah, I'd really like to get these fixed. It is also chewing up a lot of action mintues since we run those seeders in CI 😢

**Comment by tristan-orourke** [comment]
Hmm. I don't love the idea of skipping the indexing - some functionality does rely on it. Maybe we could allow you to optionally skip it somehow though, if you know you're only running tests without it?

Putting it in a queued job is an interesting idea as well.

**Comment by petertgiles** [comment]
#9654 made a big improvement here.  I'm going to close this.
