### ISSUE TITLE
♻️ Use alphabetical sorting function across app

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/gc-digital-talent#9074]
## ♻️ Debt/Refactor

- Alphabetical sorting is now built into `<Combobox />`. Remove all other redundant alphabetical sorting across the app (e.g [filteredSkills](https://github.com/GCTC-NTGC/gc-digital-talent/pull/9066#issuecomment-1907137116)). 
-  The `<Select />` component has a house built `sortingOptions()` function. [Intl.Collator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator) works well and is built into JS. Refactor `sortOptions()` in the `<Select />` component to use new [alphaSortOptions](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/packages/forms/src/utils.ts#L265) funtion.
## ✅ Acceptance Criteria

- [ ] Remove all redundant alphabetical sorting for `<Combobox/>`. (Suggestion: Find all instances of `.sort()` and determine if it can be removed or refactored?).
- [ ] Refactor `<Select />` components sortingOptions to use new sorting function. Then remove all redundant alphabetical sorting as well.
- [ ] Ensure all options that require custom sorting use `doNotSort` prop.

**Comment by vd1992** [comment]
In some instances the sort is redundant, like sorting options passed into the `<Combobox />` which now has its own sort

**Comment by yonikid15** [comment]
> In some instances the sort is redundant, like sorting options passed into the `<Combobox />` which now has its own sort

Ya my bad we should be removing any sorting in most instances. I'll update the text.

**Comment by tristan-orourke** [comment]
Note: OptionGroups in `<Select>` may pose a challenge. Hopefully we can sort the groups by the same sort function as within the groups.
