### ISSUE TITLE
✨ New status for candidates again - "Tentatively placed (verbal or email confirmation)"

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#9076]
## ✨ Feature

New candidate status to help us with metrics on hiring. "Tentatively placed (verbal or email confirmation)"

## 🕵️ Details

In dropdowns on the admin side, use this copy:
- EN: Offer in progress
- FR: Offre en cours

The candidate should still show up in searches, ~so nothing special about this new status~ which requires it to be added to some functions in backend scopes.

## Proposed Implementation
 
Call the enum PLACED_TENTATIVE.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] New status available for pool operators and request responders to set for candidates
- [ ] Applicants looking at their application status don't see this - the card still shows `Ready to hire` chip - same as QUALIFIED_AVAILABLE
- [ ] Tentatively Placed candidates DO still appear in searches. That means that any scopes in User.php or PoolCandidate.php which currently check for QUALIFIED_AVAILABLE and PLACED_CASUAL should now also allow PLACED_TENTATIVE
- [ ] Test coverage for ensuring PLACED_TENTATIVE candidates show up in searches

**Comment by Jerryescandon** [comment]
Two things: 
1. The copy I got from Lauren for this status was " `Tentatively placed (verbal or email confirmation) ` "
2. And two, the only other related copy to this new status would be on the cards appearing on the career timeline page on public facing side on: `.../personal-information/career-timeline` We just need to make sure the chip associated with this status is `Ready to hire`

**Comment by tristan-orourke** [comment]
Seems like this is primarily motivated by wanting to be able to track and report how many users have been found a match but don't _actually_ have a new job yet.

We may be better off waiting for #8671 and storing this as a `tentativelyPlacedAt` date instead of a full STATUS.

**Comment by tristan-orourke** [comment]
After learning more about the use of this status I think it's okay to treat it like the other PLACED statuses for now.

**Comment by tristan-orourke** [comment]
Confirmed that we should use "Offer in progress" on the admin side for now.
