### ISSUE TITLE
🐛 [Prod] Searching users by "full profile" does NOT match partial-word matches for any field

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#9088]
## 🐛 Bug

~On the Users table, the search bar is set to search "full profile" by default (or its supposed to be), but if I type in an email of a user who is present in the database, I get no results. If I switch the search option to "filter by email", then it works.~

Turns out that if search bar is set to search "full profile" then search terms only match full tokens. You can match peoples email, but only if you write out the whole email.

## 🦋 Expected Behaviour

The default search bar behaviour should show users who match by name OR email OR telephone.

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Name and version (if possible).
- **Browser**: Name and version (if possible).

## 📋 Steps to Reproduce

1. Log in as a platform admin
2. Go to Users table
3. enter a user's email in the search bar  - see how they don't show up
4. switch search option to "Filter by email" - now they show up

### Filtering by full profile 
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/f2651716-16fd-4290-abf4-a927a508a05a)

### Filtering by email
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/686fde82-0ed3-44aa-96dd-2b6c5e543650)

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] By default the search bar on the users table shows matches against email OR full name OR telephone
- [ ] Make sure this works on the pool candidates table as well

**Comment by vd1992** [comment]
The same outcome occurs when searching by other fields, like telephone. As far as I can tell, this is an issue of it not partially matching results. It matches exactly instead. 

This stems from the utilization of `usingWebSearchQuery()` which searches using method `websearch_to_tsquery`

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/674365e5-ba47-4e19-b8f6-c132f711dc80)

The web search is the most flexible and leninent making it recommended for direct user input, it executes some operations like AND matching but the issue is it won't prefix-match. 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/f4744cec-4a4c-4c93-a2ea-66502b688908)

Searching by `usingTsQuery()` which is `to_tsquery`  allows use of prefix-matching, but it is a much more delicate and syntax-strict method. 
Prefix-matching is what allows for partial matches.

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/1a78baa0-8dad-434f-9c23-9df8e3e15f28)

**Comment by tristan-orourke** [comment]
Thoughts from scrum
- users probably expect partial matching to just work
- we could make partial matches work by doing our own pre-parsing and adding asterisks
- our users probably aren't using comma separated terms. Can we confirm that? Would it make more sense to use the quotes to join terms rather than commas to split terms?

**Comment by tristan-orourke** [comment]
I was thinking of a survey we could ask users to see how they *expect* search to work in different edge cases:

There are two candidates, Alice and Bob.

Alice has the following written for an education experience:
  - "I spent 4 years studying Computer Science, with a focus on data and analytics."

Bob has the following written on two different job experiences:
  - "At this job, I worked at a computer all day."
  - "I was a data science researcher at ICE Enterprises."

For each of the following cases, if you entered the search term in the search bar exactly as written, which users would you expect to see?

1. `computer science`
	a. only Alice
	b. only Bob
	c. Alice and Bob
2. `"computer science"`
	a. only Alice
	b. only Bob
	c. Alice and Bob
3. `computer science data`
	a. only Alice
	b. only Bob
	c. Alice and Bob
	d. neither
4. `"computer science" data`
	a. only Alice
	b. only Bob
	c. Alice and Bob
	d. neither	
5. `computer science, data`
	a. only Alice
	b. only Bob
	c. Alice and Bob
	d. neither
6.  `"computer science data"`
	a. only Alice
	b. only Bob
	c. Alice and Bob
	d. neither
7. `data science`
	a. only Alice
	b. only Bob
	c. Alice and Bob
	d. neither	
8. `data, science`
	a. only Alice
	b. only Bob
	c. Alice and Bob
	d. neither
9. `"data science"`
	a. only Alice
	b. only Bob
	c. Alice and Bob
	d. neither
10. `ali`
	a. only Alice (partial match on Alice's name)
	~b. only Bob~
	~c. Alice and Bob~
	d. neither (require a full match)
11. `ice`
	a. only Alice
	b. only Bob (it's weird to match the end of a name instead of the beginning)
	c. Alice and Bob (Alice's name and Bob's workplace)
	d. neither
12. `research`
	~a. only Alice~
	b. only Bob (partial match on "researcher")
	~c. Alice and Bob`
	d. neither (require a full match)

**Comment by tristan-orourke** [comment]
Blocked as we decide how exactly (and to what extent) we want to support partial matches.

**Comment by tristan-orourke** [comment]
@gobyrne I could walk you through this in more depth if you want

**Comment by vd1992** [comment]
For reference, what I tried: 

This change in the model 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/7d6853b4-e83a-4b93-8c47-17393340e35e)

Then allows a partial match with prefix-matching

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/b144ec58-6df8-4523-9da7-04ae0c6fb8ed)

But the search gets more fragile, for example, space-separated input errors

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/f41c55ae-7813-4d73-a240-4bd47b7b2c0c)

**Comment by tristan-orourke** [comment]
Removed redundancy to shorten my survey:

There are two candidates, Alice and Bob.

Alice has the following written for an education experience:
- "I spent 4 years studying Computer Science, with a focus on data and analytics."

Bob has the following written on two different job experiences:
- "At this job, I worked at a computer all day."
- "I was a data science researcher at ICE Enterprises."

For each of the following cases, if you entered the search term in the search bar exactly as written, which users would you expect to see?

1. `computer science`  
    a. only Alice  
    b. Alice and Bob
2. `computer science data`  
    a. Alice and Bob  
    b. neither
3. `ali`  
    a. only Alice (partial match on Alice's name)  
    b. neither (require a full match)
4. `ice`  
    a. only Alice  
    b. only Bob (it's weird to match the end of a name instead of the beginning)  
    c. Alice and Bob (Alice's name and Bob's workplace)  
5. `research`  
    a. only Bob (partial match on "researcher")  
    d. neither (require a full match)
6. If you want to find someone with the complete phrase `computer science` along with single word `data`, what would you type?  
    a. computer science, data  
    b. "computer science" data

**Comment by tristan-orourke** [comment]
https://talent-cloud.slack.com/archives/CFCE2FSR4/p1708009802495899

@substrae's answers to my survey:
1. b 
2. a
3. a (caveat: wrapping "ali" in quotes should match full words only)
4. a (caveat: wrapping "ice" in quotes should match full words only)
5. a (caveat: wrapping "research" in quotes should match full words only)
6. b

@gobyrne's answers:
1. b
2. a
3. a
4. b
5. a
6. b

So there was some disagreement about whether a partial search term should match the ends of words. 

However, so far there is agreement that
1. partial matches seem to be desirable (not currently implemented)
2. by default, each word should be considered a separate search term
3. multi-word search terms are better indicated by quotes than split by commas

And @substrae suggests that any term wrapped in quotes should require an exact match, not a partial match.


5.

**Comment by substrae** [comment]
@tristan-orourke 

I can add this to my list, sure. Can't make any promises on when I'll get to it, but if you need it urgently, maybe ping @gobyrne and I so we can chat about prioritizing it.

**Comment by tristan-orourke** [comment]
@substrae I don't think it's urgent...

**Comment by petertgiles** [comment]
For reference, we're currently using the  `websearch_to_tsquery ` function to build our queries.  It is designed to mimic the way web searches work.  It is easy to test in a database client.

![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/6ff7c0df-480c-4b60-8bd1-d2a8302b0e7e)

**Comment by tristan-orourke** [comment]
Closing this in favour of new, more specific tickets #9957 and #9956
