### ISSUE TITLE
Pool Dashboard - Add ErrorToast component which displays all errors returned from urql

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#91]
# Description
The ErrorToast component itself should be based on work we did in Talent Cloud, where errors could be pushed to a React Context high in the component hierarchy, and result in dismissible Toast elements.

While we could write code at every urql operation which checks for errors in the result, the easiest way to catch and display all errors is probably with the [errorExchange](https://formidable.com/open-source/urql/docs/api/core/#errorexchange) which can be configured when creating the urql client. ("Exchanges" are urql's plugins.)

**Comment by mnigh** [comment]
[Alert component styles in Figma](https://www.figma.com/file/tXs6IdvpuX4jCLBWbJx0C6/Components-and-Patterns?node-id=376%3A1297), thanks @JoshBeveridge.
