### ISSUE TITLE
🐛 Broken story Application Info

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#9128]
## 🐛 Bug

The story is broken. Probably need to update props to account for recent changes maybe from GraphQL migrations?
Error mentions cannot read `essentialSkills` off undefined. 

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/168393f1-78e8-4e10-a85d-dd739cbbdcb4)

## ✅ Acceptance Criteria

- [ ] Story builds

**Comment by mnigh** [comment]
The prop was changed in #8973 from `pool` to `poolQuery`: https://github.com/GCTC-NTGC/gc-digital-talent/pull/8973/files#diff-6fa6f0230b29ca56390c1dc7a42d5f589a78c094963ca71faeaeb0632ea1cfdb

**Comment by mnigh** [comment]
The following fixes the story, though not sure it has the desired `essentialSkills` or not.

## Screenshot
<img width="1003" alt="Screen Shot 2024-02-05 at 11 22 55" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/a9ee6d24-d509-4200-bd92-841bff1811d4">
