### ISSUE TITLE
♻️ Add retries to every SIC call

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#9130]
## ♻️ Debt/Refactor

We know that our connection to Sign In Canada (SIC) can sometimes be unreliable.  Let's add some retries to every SIC call.   We started with  #8836 and this can be a good model.

## ✅ Acceptance Criteria

- [ ] Every SIC call in api/app/Http/Controllers/AuthController.php has retries
- [ ] Every SIC call in api/app/Services/OpenIdBearerTokenService.php has retries
- [ ] Make the number of retries a config variable, which defaults to 3 but could be changed with an env variable (apply to the #8836 retries as well)

**Comment by tristan-orourke** [comment]
Note: hard to test :'(
