### ISSUE TITLE
Deep dive on Azure AppInsight data

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#9132]
## ✨ Spike

@brindasasi recently showed some page views data from Azure that shows the user flow and drop-off from page to page on our site. We want more of this! So much more.

This spike is to put aside some time to sort through all the data and pull out as many insights as possible that we think might be useful.

Also of interest is figuring out a good way to report regularly on this data.

@RM-1978 is available for support analyzing data and has some specific questions they would like answered.

## Timebox
2 days - see how far you get in 2 days and show the results. More time can be allocated afterwards based on how useful the results are.

## ✅ Acceptance Criteria

- [x] Get access to Azure AppInsights, and server monitoring dashboards to the following people, Gray, Lee, Rosita, Matt J, Marc, Josh
- [x] Ensure those non-devs are given permissions which ONLY include AppInsights and Azure Dashboards, not other azure functions (like for deployments)
- [x] ask IMTD about an easier way to export data

Spend time working with new users to show how to access:
- [ ] Charts, plots, figures that show us information about how users use our site.
- [ ] Super bonus if you can figure out user drop-off after being sent to GCkey.
- [ ] Worked with @RM-1978 on specific insights they are looking for
- [ ] Strategy proposed for regularly reporting on this data (try to minimize dev work required please)
- [ ] @RM-1978 present (or co-presents) results at QA weekly meeting

**Comment by brindasasi** [comment]
Server monitoring dashboards? I don't think I have access to them. 
@petertgiles could get us the access to that ? 
I can get App Insights permission for all above.
@gobyrne you should be able to view the App Insights Dashboard with your PC account. 
Let me know if you need help with that.

**Comment by petertgiles** [comment]
> @petertgiles could get us the access to that ?

I just nagged Carl about it.  It's been over a week and no one has been assigned yet.

**Comment by brindasasi** [comment]
Hosting a learning session for new users. 
A new issue has been created to collect additional metrics
https://github.com/GCTC-NTGC/gc-digital-talent/issues/9375

**Comment by tristan-orourke** [comment]
👏
