### ISSUE TITLE
Remove expiry dates for anyone who is prior to being qualified

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#9136]
## Details
Some pool candidates were erroneously given expiry dates when they applied. In practice, these expiry dates are only supposed to be assigned when candidates are "Qualified" in a pool.

The erroneous expiry dates are problematic because we filter those people out on pool tables using the "Expiry status" filter. To address this, we would like to remove expiry dates for anyone with a status that is prior to "Qualified" in the pool operator flow.

So remove expiry dates for all candidates with the following statuses:
- Draft
- Draft expired
- New application
- Screened in
- Application review
- Under assessment
- Screened out - Application
- Screened out - Assessment
- Screened out - No longer interested
- Screened out - Not responsive

## Acceptance criteria
- [ ] Database operation or artisan tinker commands have been run which remove expiry dates from candidates in the specified statuses

**Comment by tristan-orourke** [comment]
Do we want this as a migration / seeder? Or should we just run database operations directly?
