### ISSUE TITLE
"Filter by" button doesn't show default "Full profile"

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#9138]
## 🐛 Bug

The "Filter by" select button doesn't show the default option if its selected.

When I select any option other than the default, it appears in the text of the button. eg "Filter by Candidate Name" or "Filter by Email". But if Full Profile, the default, is selected, then the button just says "Filter by".

## 🦋 Expected Behaviour

The filter bar should say "Filter by Profile" when the default is selected.

## 🕵️ Details

This applies to all instances of the Table, not just the User or Pool Candidate table.

## 📋 Steps to Reproduce

1. Look at any table on the app
2. Change the filter by option to something other than default
3. Change it back to the first option

### Filter by default
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/a526faf9-3b2b-4b8c-a80a-a3ca7ae25ef5)

### Filter by other
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/e4ba3b7d-a251-41e1-b580-16b2dc637848)

## 🙋‍♀️ Proposed Solution

Show "Filter by Profile" text when on the default option

## ✅ Acceptance Criteria

- [ ] The text of the default Filter by option appears on the select button when it is selected

**Comment by tristan-orourke** [comment]
@substrae what do you think about this proposed change?

**Comment by substrae** [comment]
@tristan-orourke 

Gonna tag @Jerryescandon as well, because I feel like this was his original design. Personally, I think we could replace "Filter by" entirely with the label, so if the default is "All profile info", it would simply say that. The problem with this type of component is that when the label becomes long, it begins to lose its visual meaning and signifiers.

As an aside, wouldn't the default _always_ be "all info"? It feels misleading to me for us to have a filter option that pre-filters without user input.

**Comment by Jerryescandon** [comment]
I do agree that if the default is "All profile info" then we should just rename it to that, and for simplicity, keep everything else as "Filter by" + ColumnName

**Comment by tristan-orourke** [comment]
> As an aside, wouldn't the default always be "all info"? It feels misleading to me for us to have a filter option that pre-filters without user input.

We're not pre-filtering the results without user input. This label is describing _how_ we use the user input, after they enter it. Are we matching what they type against emails, or against names, or doing our best to match against anything the user has typed (the default "full profile" option).

**Comment by gobyrne** [comment]
Ok, let's go with "Filter by profile" for now. Designers can propose a broader improvement separately if they like. I agree it's a little confusing with the different copy here "Search by keyword - Filter by profile - Filters".

**Comment by gobyrne** [comment]
It should probably "search in" instead of "filter by"

**Comment by substrae** [comment]
I'm not convinced we need a prefix phrase at all here. The drop down could just say "All info" and then each option selected changes it. 🤔 "Filter by" and even "Search in" feel both confusing and redundant to me.

**Comment by mnigh** [comment]
1. **Full Profile** should be sentence case, not title case.
2. **Full Profile** does not make sense for all the non-user or non-candidate tables (i.e. most of them). Not sure why, but it was changed from **Entire table** in [this commit](https://github.com/GCTC-NTGC/gc-digital-talent/commit/56fb8fe406285822fe8a6b88c35550eab86c9ec6) as part of https://github.com/GCTC-NTGC/gc-digital-talent/pull/8539.

## Screenshots
<img width="721" alt="Screen Shot 2024-02-13 at 09 15 57" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/290ae605-ef1a-450a-bb4d-8ddd51223e01">
<img width="783" alt="Screen Shot 2024-02-13 at 09 15 48" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/e09e6d2f-7351-416c-ac2f-81b3da95c36c">
<img width="886" alt="Screen Shot 2024-02-13 at 09 15 18" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/9762dd6c-40bb-4e44-8be0-776ce5905d29">
<img width="726" alt="Screen Shot 2024-02-13 at 09 15 10" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/911e7839-3196-4184-84bd-30e2a7891ab3">
<img width="739" alt="Screen Shot 2024-02-13 at 09 14 59" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/065badd9-91af-40af-9766-81afd3a95682">
<img width="810" alt="Screen Shot 2024-02-13 at 09 14 10" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/7f86a0b2-b6e7-4fea-a531-bd1996af7954">
<img width="667" alt="Screen Shot 2024-02-13 at 09 16 11" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/56dbea9b-da07-4d06-bc89-776d23e96136">

**Comment by tristan-orourke** [comment]
I'm going to close this in favour of #9517
