### ISSUE TITLE
✨ Add Job Placement dialog to Pool Candidates table

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#9140]
## ✨ Feature

The status have been updated and reworked for Record of Decision, among these statuses are the collection of "Job placement" statuses. These statuses allow DCM to track candidates AFTER they have been qualified into a pool and serve two purposes.

1. It allows DCM to metaphorically "close" the case on a candidate's file once that candidate has successfully been offered a job through this particular pool and that way they can stop referring that candidate.
2. It allows DCM to track for statistical purposes how a candidate's file progresses after it's been qualified and where it currently sits across on the hiring process.

## 🕵️ Details

With this in mind. We have designed an interaction that should allow QUALIFIED candidates to have an additional sub-status, that will affect whether or not they appear on talent searches.

In addition, when a candidate has gained been placed or tentatively placed, we want to know in which department they have been placed. Thus, the department dropdown field only shows IF one of the 4 placed options has been selected.

This new field means we would need an extra column on the Candidates table to view this information and possibly filter by it as well.

| Job placement status | Appears on searches | Placed department field |
|--------|--------|--------|
| Not placed | TRUE | FALSE |
| Tentatively placed (Verbal or email confirmation) | TRUE | TRUE |
| Placed casual | TRUE | TRUE |
| Placed term (Letter of offer on file) | FALSE | TRUE |
| Placed indeterminate (Letter of offer on file) | FALSE | TRUE | 

## 🎨 Design File

[Figma link](https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Admin---Processes%2FPools%2FRecruitments---Record-of-Decision?type=design&node-id=7574%3A18921&mode=design&t=icX0dsgRx5MIF6OC-1) by @Jerryescandon 

## 📸 Screenshot

<details><summary>📸 Candidates table</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/e61aea9e-88ed-4edf-a019-66553d700e12)

</p>
</details> 

<details><summary>📸 Job placement modal</summary>
<p>

![image](https://github.com/GCTC-NTGC/design-gc-digital-talent/assets/16977254/4ee58c63-ca76-4d97-8e4c-7add0fa37cfa)

</p>
</details> 

<details><summary>Placed status / dialog link on Pool Candidates page</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/205d4060-c845-41d2-b616-924fe62cd87a)

</p>
</details> 

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Job Placement column added to Pool Candidates table after Job Placement column, which shows placed department if it exists
- [ ] Job Placement column text in Pool Candidates table is a clickable link which opens Placement Dialog
- [ ] From placement dialog, user can place user in a department or remove placement. This uses the mutations added in #9192 
  - Department input is removed is "not placed" is selected, but is required for any other selection
- [ ] The same Job Placement link appears on the Pool Candidate page, if the user is Qualified, just under the "Revert Decision" button. It opens the same placement dialog.

## 🛑 Blockers

```[tasklist]
### Blocked by
- [ ] #9192
```

**Comment by gobyrne** [comment]
This addresses #9076 ... so we'll probably just do it all here

**Comment by tristan-orourke** [comment]
Question about how we store data, because it will affect our reporting and analytics options:

If a candidate goes from Placed (casual) to Placed (term), the easiest thing to do (from dev perspective) is overwrite the original record. But in that case we lose information about when the first placement happened, or that it even happened at all. Is this a problem? Is it worth designing around?

Now consider a candidate going from Placed (tentative) to Placed (term) - are the answers the same?

**Comment by gobyrne** [comment]
For now, either is acceptable, but within the next year, I'd like us to build out something that will allow us to preserve a history of all similar actions done on candidates. A candidate history that shows all their assessments, all the notes on the file as they change, all the removal and placement actions taken... etc.

**Comment by tristan-orourke** [comment]
Need to add Placed Department to model
Add link to open dialog on Pool Candidate page as well, just under Revert Decision button
