### ISSUE TITLE
🐛  Bookmarking a candidate fails on UAT 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#9142]
## 🐛 Bug

Bookmarking a candidate fails on UAT 

## 🦋 Expected Behaviour

Bookmarking should work without any issues when RoD flag is off and ON

## 🕵️ Details

1.  This happens only on UAT. 
2.  Running the role permission seeder doesn't help 
3.  Migration ran successfully.
<img width="1220" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNE1MQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--38b8bfe59e74862310f65ca9d472da90bf57f9fc/Screenshot%202024-01-29%20at%203.59.25%20PM.png" alt="Screenshot 2024-01-29 at 3.59.25 PM.png" />
4. is_bookmarked columns exists with default value as "f" 

## 📋 Steps to Reproduce
1. Go to UAT 
2. Open the pool Candidates table 
3. Bookmark a candidate 

## 📸 Screenshot

![Screenshot 2024-01-29 154421 (1)](https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/912af98f-3701-49f6-8176-3b03a7882d67)

This is the actual error 

`GraphQL Error: Failed to find class poolCandidate in namespaces [App, App\Models] for directive @can.
`

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Bookmark a candidate should work without any issue

**Comment by brindasasi** [comment]
so the class name is `PoolCandidate` not `poolCandidate`
my guess is local environment might have different configuration or autoloaders, that handle case sensitivity differently than prod env.s .
I would like to fix the case & test it first.

**Comment by tristan-orourke** [comment]
Seems to work on local but not UAT
