### ISSUE TITLE
🐛 Refresh endpoint returns content type text/html

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#9148]
## 🐛 Bug

The response from the refresh endpoint has content type text/html.  Our app is smart enough to recognize JSON and parse it correctly but Cypress isn't.

## 🦋 Expected Behaviour

The content type should be application/json, like the responses from Lighthouse.

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/47d50445-f9a5-4a4c-a814-28b8ee9b4a44)

## ✅ Acceptance Criteria

- [ ] Refresh responses have the JSON content type

**Comment by mnigh** [comment]
Should be as easy as adding https://laravel.com/docs/10.x/responses#json-responses to: 

https://github.com/GCTC-NTGC/gc-digital-talent/blob/f5d1c5c34dee114b917e03e5f7d393601ef648c3/api/app/Http/Controllers/AuthController.php#L139
