### ISSUE TITLE
🐛 Prod logged error - Attempt to read property on null

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#9153]
## 🐛 Bug

We occasionally have exceptions logged in production that look like this:

> Attempt to read property "id" on null {"exception":"[object] (ErrorException(code: 0): Attempt to read property \"id\" on null at /home/site/wwwroot/api/app/Models/PoolCandidate.php:677)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/ee93cf7f-765a-4750-8285-e95cce88d998)

It seems like this scope is being called with no authorized user present?

## 🦋 Expected Behaviour

Uncaught framework exceptions from Eloquent models should not be happening in production under normal circumstances

## 📋 Steps to Reproduce

_Unknown_

## 🙋‍♀️ Proposed Solution

1. Find out how to reproduce it
2. Decide on the solution
  - If it is a normal occurrence then prevent the exception from being thrown, or catch and deal with it
  - If it is due to a bug, fix the bug

## ✅ Acceptance Criteria

- [ ] It is no longer possible for this exception to occur in prod

**Comment by tristan-orourke** [comment]
This exception might be correctly logging some other bug
