### ISSUE TITLE
🐛 [WIP] Assessment Step logic is suspect

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#9155]
## 🐛 Bug

Describe the issue you encountered.

## 🦋 Expected Behaviour

What should be happening?

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Name and version (if possible).
- **Browser**: Name and version (if possible).

## 📋 Steps to Reproduce

1. ...
2. ...

## 📸 Screenshot

Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Criteria 1
- [ ] Criteria 2

## 🛑 Blocked By

```[tasklist]
### Blocked By
- [ ] #8961 
```

**Comment by tristan-orourke** [comment]
Also add better tests

**Comment by mnigh** [comment]
@tristan-orourke what part of the Assessment Step logic is suspect? is this issue still relevant?

**Comment by tristan-orourke** [comment]
This was a reminder to ourselves to test the Assessment Step logic when we could, but I think is covered by jest tests now (not to mention much user testing)
