### ISSUE TITLE
🐛 ChunkLoadingError after deployment

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#9185]
## 🐛 Bug

Our client was getting ChunkLoadingError occurrences from React Router after deployment.

## 🦋 Expected Behaviour

After deployment, clients should automatically be requesting the new chunks.

## 🕵️ Details

https://talent-cloud.slack.com/archives/C0259G6KXJ6/p1706213554653299

## 📋 Steps to Reproduce (maybe?)

1. Load up application
2. New deployment with new file names
3. Load application again

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/97d6b7db-1827-44b3-9c38-047a8589d91e)

## 🙋‍♀️ Proposed Solution

??

## ✅ Acceptance Criteria

- [ ] Cached clients can transparently keep working after new deployments with new chunk file names

**Comment by tristan-orourke** [comment]
One option, if we can't stop the errors: at least try to catch the error and show useful message in toast (maybe refer to FAQ?)

Could F5 be doing something unexpected to our headers?

Is the index and entrypoints cached? (shouldn't be)

**Comment by tristan-orourke** [comment]
Looks like the app.js entry point is being cached for too long!

**Comment by tristan-orourke** [comment]
Try using [chunkhash] instead of [contenthash]

**Comment by esizer** [comment]
> Try using [chunkhash] instead of [contenthash]

Looks like this is not the case:

- Initial: `app.de59b2db802516f1ee4b.js`
- Change: `app.142c49e195b872134e70.js`
- No Change: `app.43c2f13c4f980e0af696.js`

The odd thing is, the hash changes even with no changes 😅 My next best guess is that we are caching the `index.html` file at the f5 level which would override our `Cache-Control` headers since the user would be served the old file regardless of it being cached in the client.

**Comment by petertgiles** [comment]
> > Try using [chunkhash] instead of [contenthash]
> 
> Looks like this is not the case:
> 
>     * Initial: `app.de59b2db802516f1ee4b.js`
> 
>     * Change: `app.142c49e195b872134e70.js`
> 
>     * No Change: `app.43c2f13c4f980e0af696.js`
> 
> 
> The odd thing is, the hash changes even with no changes 😅 My next best guess is that we are caching the `index.html` file at the f5 level which would mean our `Cache-Control` headers aren't doing much since the user would be served the old file regardless of it being cached in the client.

I wonder if it's these guys:
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/95d3a5f5-df2a-49f6-9fd1-84013da55e21)
It would be pretty easy to test: just temporarily change those to constants.

**Comment by esizer** [comment]
Something that can't be helping is that our JS files are cached for a year 😆 

![Screenshot 2024-02-13 112500](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/75623708-d6a7-4df9-9c10-6139e0b72a8f)

**Comment by petertgiles** [comment]
> Something that can't be helping is that our JS files are cached for a year 😆

Yeah, just the ones with a hashed name, though.  In theory a file with a hashed name should never change - it will get a new name if it changes.

**Comment by esizer** [comment]
> Yeah, just the ones with a hashed name, though. In theory a file with a hashed name should never change - it will get a new name if it changes.

That is the bit that is confusing me. The names should be changing and my other guess that the f5 is caching should mean that a client cache clear _shouldn't_ fix the issue but apparently is🤷‍♀️
