### ISSUE TITLE
🐛 Logging out in a second tab doesn't log out the first tab

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#9188]
## 🐛 Bug

When a second tab ends the user's session the first tab doesn't go to the logged-out page on navigate.  Instead the user gets a 404 type page or even the create account page.

## 🦋 Expected Behaviour

When the session has ended in a different tab, the first navigation of the first tab should redirect to logged-out.  This is the same behaviour that currently happens if the token expired.

## 📋 Steps to Reproduce

1. Log in in tab 1
2. Open app in tab 2
3. Log out in tab 1
4. Attempt to navigate in tab 2

## 📸 Screenshot

https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/cb55e302-c222-43cf-b108-19ac5afa2f75

## ✅ Acceptance Criteria

- [ ] When the session ended in tab 1, tab 2 should redirect to logged-out on navigation
- [ ] Unskip cypress test "will affect all tabs when logged out" in login-logout.cy.ts

**Comment by vd1992** [comment]
Requires completion of #8654
Blocking and shifting pipelines
