### ISSUE TITLE
🐛 "Skill families" page also shows "skills" page as activated in the Admin nav

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#9195]
## 🐛 Bug

When on the skills family page, both the skills and skill families link is bolded in the nav

## 🕵️ Details

- **Browser**: Chrome

## 📋 Steps to Reproduce

1. Click on skill families in Admin UI nav
2. Check to see if both Skills and Skill Families are bolded in the nav

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/9c705418-7a08-43f0-a43e-317606e626ce)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Only skills family is bolded in the admin nav when on the skills family page

**Comment by esizer** [comment]
Just need to add `end` prop to the skills link.

REF: https://reactrouter.com/en/main/components/nav-link#end
