### ISSUE TITLE
✨ Add "Revert final decision" modal to Pool Candidate page

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#9197]
## ✨ Feature

After assessors make the decision to Qualify or Disqualify a candidate, they should be able to change their mind.

## 🕵️ Details

If the candidate is Qualified or Disqualified, the "Record final decision" button is replaced with a "Revert final decision" button, which opens the "Revert qualified decision" or "Revert disqualified decision" dialog, depending on current status. This should open a new modal - one of two different ones, depending on whether applicant is Qualified or Disqualified.

The new modals should trigger the revertFinalDecision mutation, created in #9190.

The Pool Candidate page should immediately be updated (the Record final decision button should appear.)

Here's how to interpret PoolCandidate.status

| PoolCandidateStatus                 | interpretation |
| --------------------------------- | ---------------- |
| SCREENED_OUT_APPLICATION | Disqualified
| SCREENED_OUT_ASSESSMENT | Disqualified
| QUALIFIED_AVAILABLE              | Qualified
| EXPIRED                                    | Qualified
| All other statuses                      | N/A (mutation will throw an error)

## 🎨 Design File

[Design file](https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Admin---Processes%2FPools%2FRecruitments---Record-of-Decision?type=design&node-id=8165-20928&mode=design&t=o2pTls0JmG0q1lfN-0) by @Jerryescandon 

### Record final decision, Revert final decision, reinstate candidate
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/205d4060-c845-41d2-b616-924fe62cd87a)

### Revert Qualified decision
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/941c1f26-9f95-49fe-b1e8-79c7fe975a76)

### Revert Disqualified decision
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/490b8255-5f3f-4d09-bc28-935aad8355d4)

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

- [ ] If the candidate is Qualified or Disqualified, the "Record final decision" button is replaced with a "Revert final decision" button, which opens the Revert Qualified decision or Review Disqualified decision dialog, depending on current status
- [ ] Modals submit to revertFinalDecision mutation
- [ ] If candidate is "placed" hide the "revert final decision" button

## 🛑 Blockers
```[tasklist]
### Blocked By
- [ ] #9190
```

**Comment by gobyrne** [comment]
@Jerryescandon to describe how this interacts with the "placed" function.

**Comment by gobyrne** [comment]
Hide the "revert final decision" if candidate is placed.
