### ISSUE TITLE
🐛 Chromatic workflow intermittently failing

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#9211]
## 🐛 Bug

It seems the chromatic is having an issue building somewhat consistently. Running it a second time usually passes.

## 🦋 Expected Behaviour

Chromatic consistently builds properly in GitHub actions.

## 🕵️ Details

- List of workflow failures: https://github.com/GCTC-NTGC/gc-digital-talent/actions/workflows/chromatic.yml?query=is%3Afailure
- Example of failure: https://github.com/GCTC-NTGC/gc-digital-talent/actions/runs/7789367163/job/21240807638

## 🙋‍♀️ Proposed Solution

It seems as though it is failing on the path alias `~/*`. Maybe start there and see where it gets you? 

https://github.com/GCTC-NTGC/gc-digital-talent/blob/89cf3f2cadd51d76ef3c4925a66c9f1d62dbf097/packages/storybook-helpers/main.ts#L71-L76

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Chromatic consistently builds in GitHub actions with no errors

**Comment by esizer** [comment]
## Update

After some updates to storybook, it seems like this may have just been a bug with that. I seem to be unable to reproduce now. Going to let this linger for a bit more to see if it pops up again.

**Comment by esizer** [comment]
I still can't figure this out 😖 I narrowed it down a bit though. It seems to only happen when we merge stories from `packages/**` and `apps/**`.

I tore down our entire config and started a brand new storybook project and added onto the config until it broke and it has something to do with that. If you do it with only one of the paths it does seem to work 🤔 It is made even more fustrating by the fact that when I pass the debug flag, it returns the correct path 👎 



![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/01d0499d-5a31-4052-8161-995c90e81c45)
![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/2c023bb6-26e9-4418-9145-b36650d690f7)

**Comment by mnigh** [comment]
Looks like it the last failure was March 4, 2024 which was over a week ago: https://github.com/GCTC-NTGC/gc-digital-talent/actions/workflows/chromatic.yml?query=is%3Afailure. Issue solved? 🤞

**Comment by esizer** [comment]
Looks like this is no longer an issue. I haven't seen any failures related to this and my local is working well too :+1:
