### ISSUE TITLE
🛠️ Record of Decision deployment tasks!

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#9215]
## 🛠️ Tooling

When turning on Record of Decision, remember to do the following!

## 🕵️ Details

Add any additional details that could assist with the changes/additions being made.

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt tooling was properly updated and remains functional.

- [ ] Before turning on, ensure we've tested that old candidates can still be worked with effectively (in all statuses)
- [ ] Directly after turning on, run the artisan command created in #9214

**Comment by vd1992** [comment]
RoD is indeed "on" but the second portion of the acceptance criteria needs to be done. That is its own issue though making this issue lack a purpose as far as I can tell. 
The flag has been removed so there is definitely no going back now.

Closing as unneeded
