### ISSUE TITLE
🐛 Sorting not working right for notes column of Pool Candidates table

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#9218]
## 🐛 Bug

Sorting the Pool Candidate table by Notes column doesn't seem to work

## 🦋 Expected Behaviour

Results should be ordered alphabetically by notes, with empty notes at the bottom (or top).

## 📋 Steps to Reproduce

1. Log in as an admin
2. Go to "candidate search" (http://localhost:8000/en/admin/pool-candidates)
3. Sort by Notes column (ensure at least a few candidates have notes)

## 📸 Screenshot

Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

Probably the column isn't referenced by the right name?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Pool Candidates can be sorted by Notes column alphabetically

**Comment by tristan-orourke** [comment]
I might just be confused by the locked sorting... 🤔

**Comment by esizer** [comment]
> I might just be confused by the locked sorting... 🤔

Mind checking again now that we have https://github.com/GCTC-NTGC/gc-digital-talent/issues/9318 in? It should make more sense now 😛

**Comment by mnigh** [comment]
> > I might just be confused by the locked sorting... 🤔
> 
> Mind checking again now that we have #9318 in? It should make more sense now 😛

@esizer Most of columns that are allowed to be sorted seem to sort alphanumerically correctly, with the possible exceptions of:

- **Category**: not sure if values that have bolded purple text are weighted differentially somehow and therefore would be sorted non-alphanumerically, but this is not indicated anywhere in the UI.
- **Notes**: this is not sorting alphanumerically at all, but also probably shouldn't be a column that is allowed to be sorted anyway.

## Screen recording

https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/c5829a0d-86ea-4cb5-b79e-ccd800724ea8

**Comment by tristan-orourke** [comment]
The current **Category** sorting looks correct, it is indeed sorted by priority weight. I'm not sure how/if to communicate that - I expect it would be _fairly_ intuitive to anyone sorting by that column? 😅 

There's probably not much reason to sort by notes, but if its in the table it might as well work - no reason it can't.
