### ISSUE TITLE
✨ Add "No security clearance" to remove candidate dialog

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#9234]
## Description

Add a new option to the "Remove" candidate dialog in the "Screening and assessment" application page.

`Candidate did not receive the necessary security clearance`

### Design

[Figma file](https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Admin---Processes%2FPools%2FRecruitments---Record-of-Decision?type=design&node-id=8165%3A21175&mode=design&t=OuAcTvAiquxGMfhr-1) by @Jerryescandon 

![Image](https://github.com/GCTC-NTGC/design-gc-digital-talent/assets/16977254/b396c285-b173-40a3-9c85-d6ffd80ef8e4)

### Acceptance criteria

- [ ] New option `Candidate did not receive the necessary security clearance` available in remove candidate dialogue

**Comment by tristan-orourke** [comment]
Planning to deal with with security clearance in a different way
