### ISSUE TITLE
✨ Add "Previous candidate" to assessment step navigation

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#9237]
## Description

Add a go to previous candidate navigation link at the end of the more actions menu to allow pool operators to view the previous candidate on the step assessment list.

## Design

[Figma file](url) by @Jerryescandon 

### Screenshot

![Image](https://github.com/GCTC-NTGC/design-gc-digital-talent/assets/16977254/7f740a66-cc83-4157-9563-fca50f8c3db2)

### Acceptance criteria

- [ ] Go to previous candidate button added below more actions menu

**Comment by tristan-orourke** [comment]
Closing in favour of merging with #9017
