### ISSUE TITLE
🛠️ Get hot reloading working locally

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#9243]
## 🛠️ Tooling

It would be nice to have hot-reloading working locally.  It would make UI-heavy dev work much more pleasant.

## 🙋‍♀️ Proposed Solution

https://webpack.js.org/guides/hot-module-replacement/

https://github.com/gaearon/react-hot-loader

https://github.com/pmmmwh/react-refresh-webpack-plugin

## ✅ Acceptance Criteria

- [ ] Code changes appear in the browser automatically without a page refresh
- [ ] Hydrogen still works

**Comment by mnigh** [comment]
@petertgiles can this issue be closed as resolved now that https://github.com/GCTC-NTGC/gc-digital-talent/pull/10611 was merged?
