### ISSUE TITLE
Api server - Users table requires sub column not part of CreateUserInput

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#926]
# Description
We added a non-nullable 'sub' column to the users table. This column is to link a user in the api database to users/tokens from the authentication service.
The column is non-nullable, but isn't set in the CreateUser mutation. This causes the CreateUser mutation to error.
When creating a new User, the sub field should be set to match the email field. This should be handled in the Laravel model, not the schema.

**Comment by tristan-orourke** [comment]
There's a lighthouse directive that should make this easy, ask me about it whoever takes on this task

**Comment by petertgiles** [comment]
@tristan-orourke do you remember the directive needed?
