### ISSUE TITLE
♻️ Eliminate language redirect on auth error

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#9300]
## ♻️ Debt/Refactor

Right now our auth error process has a lot of redirects.  One of them is that when detecting an auth error the user is sent to /logged-out and then immediately has to do the language redirect again.  This causes the app to have to boot two or three times after an error.  If we sent the user back to the localized logged-out page then we could eliminate one of these redirects and reboots.

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/6544b4fd-0473-458b-874d-b170df9a5a75)
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/2f74db9c-0ca2-4ba3-be07-b5110a3ed468)

## 🙋‍♀️ Proposed Solution

2) Send the user to a localized logged-out page when ending the session.

## ✅ Acceptance Criteria

- [ ] The user does not experience an unnecessary language redirect when an auth error happens

**Comment by brindasasi** [comment]
I think this should have been resolved by #9299
