### ISSUE TITLE
🛠️ Enable Chromatic TurboSnap

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#9304]
## 🛠️ Tooling

Enable Chromatic TurboSnap.

## 🙋‍♀️ Proposed Solution

- Add onlyChanged: true to `chromatic.yml`. REF: https://www.chromatic.com/docs/setup-turbosnap/#configure
- Change `chromatic.yml` to fire on push and not pull_request

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt tooling was properly updated and remains functional.

- [ ] TurboSnap works on Chromatic GitHub workflow
- [ ] save 💰
- [ ] Test that it recognizes Hydrogen config change

**Comment by tristan-orourke** [comment]
Blocked until TurboSnap is out of beta

**Comment by tristan-orourke** [comment]
`npx chromatic` with project token to trigger locally

**Comment by mnigh** [comment]
> `npx chromatic` with project token to trigger locally (for testing)

`npx chromatic --project-token <your-project-token>`

REF: https://www.chromatic.com/docs/cli/#quick-start

> The project token is available on the Manage → Configure page of your project.

REF: https://www.chromatic.com/docs/faq/#where-can-i-find-my-project-token
