### ISSUE TITLE
✨ Add Change Expiry Date to new Candidate page

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#9313]
## ✨ Feature

For candidates who are qualified and have an expiry date, there should be a way of updating the expiry date without reverting decision and qualifying all over again.

## 🕵️ Details

The "Change expiry date" button should appear in the sidebar control if candidate currently has a non-null expiry date. The button opens a dialog with a single-date-input form, with the current expiry date pre-set. The date field is required, but can be updated without restrictions on values.

### Sidebar Controls
https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Admin---Processes%2FPools%2FRecruitments---Record-of-Decision?type=design&node-id=8165-22212&mode=design&t=BYBLA4BX6IkFELVi-0

### Dialog
https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Admin---Processes%2FPools%2FRecruitments---Record-of-Decision?type=design&node-id=8436-36475&mode=design&t=BYBLA4BX6IkFELVi-0

### 🧑‍🎨 Designer

@Jerryescandon 

### Sidebar Controls

![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/0ca35fd0-ce6e-49c0-823a-2391b92671c3)

### Dialog
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/063b38b5-d71a-430e-8a53-716d1b063c89)

## 🙋‍♀️ Proposed Implementation

May have to rerun the qualify candidate mutation.

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

- [ ] After a candidate has been qualified, an assessor should be able to change the expiry date if necessary
- [ ] The option to change expiry date should not appear if expiry date isn't already set to a non-null value
- [ ] Any date should be considered valid

**Comment by gobyrne** [comment]
I don't see a specific reason for this to be blocked on Design. We updated the screenshot of the side-bar though.

**Comment by tristan-orourke** [comment]
Does the qualify candidate mutation have validation around expiry date values?

**Comment by esizer** [comment]
What statuses are considered "qualified" and trigger this button to be displayed? Right now we have the following but, it does not seem correct for this scenario (i.e placed statuses probably shouldn't allow changing of expiry date 🤔 )

https://github.com/GCTC-NTGC/gc-digital-talent/blob/5c259f4a821bf4826a944f07ad849a721e35a0f7/apps/web/src/constants/poolCandidate.ts#L3-L11

**Comment by vd1992** [comment]
> What statuses are considered "qualified" and trigger this button to be displayed? Right now we have the following but, it does not seem correct for this scenario (i.e placed statuses probably shouldn't allow changing of expiry date 🤔 )
> 
> https://github.com/GCTC-NTGC/gc-digital-talent/blob/5c259f4a821bf4826a944f07ad849a721e35a0f7/apps/web/src/constants/poolCandidate.ts#L3-L11

Not sure if it is desired for this issue, but we do have a qualified equivalent grouping of statuses all effectively treated as equal to qualified available

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/53b7b196-767e-4909-8a6d-dd5ac804ef6b)
