### ISSUE TITLE
✨ Update chip appearance of Candidate Status

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#9316]
## ✨ Feature

Update the way some Candidate Statuses are represented in the chip whip appears on the Candidates table and the Candidates page

## Details

This updates the work of #8675.

| Pool Candidate Status       | Final Decision | Colour |
|-----------------------------|----------------|---------|
| DRAFT                       | To assess* | *
| DRAFT_EXPIRED               | To assess* | *
| NEW_APPLICATION             | To assess* | *
| APPLICATION_REVIEW          | To assess* | *
| SCREENED_IN                 | To assess* | *
| UNDER_ASSESSMENT            | To assess* | *
| SCREENED_OUT_APPLICATION    | Disqualified   |  red
| SCREENED_OUT_NOT_INTERESTED | Removed: To assess      |  grey
| SCREENED_OUT_NOT_RESPONSIVE | Removed: To assess        | grey
| SCREENED_OUT_ASSESSMENT     | Disqualified   |  red
| QUALIFIED_AVAILABLE         | Qualified      | green
| QUALIFIED_UNAVAILABLE       | Removed: Qualified        |  grey
| QUALIFIED_WITHDREW          | Removed: Qualified        | grey
| PLACED_CASUAL               | Qualified      | green
| PLACED_TERM                 | Qualified      | green
| PLACED_INDETERMINATE        | Qualified      | green
| EXPIRED                     | Expired: Qualified        | gray
| REMOVED                     | Removed: To assess        | gray

### To Assess status requires additional logic!
This logic is related to how we display candidates on the Assessment Tracker page.
1. If the candidate has been disqualified in any _required_ assessments, then the status should show a red "Disqualified: Pending decision"
2. If the candidate shows as Successful or On Hold for every step of the Assessment Tracker, and is successful in the final step, then status pill should show a green "Qualified: Pending decision"
3. If the candidate shows as Successful or On Hold for every step of the Assessment Tracker, but "On Hold" for the final step of the tracker, then show a yellow "To assess: Step n" where n is the number of assessment steps
4. Otherwise, show a yellow "To assess: Step n" where n is the number of the first step which would show as "To assess" on the Assessment Tracker

Here are some examples showing how a candidate appears for each assessment step in the tracker, and how the overall status should appear:

S1: Demonstrated
S2: Hold
S3: To Assess
==> To Assess: Step 3

S1: Demonstrated
S2: Hold
S3: Demonstrated
==> Demonstrated: pending decision

S1: Demonstrated
S2: Hold
S3: Hold
==> To Assess: Step 3

S1: Demonstrated 
S2: Demonstrated
S3: Hold
==> To Assess: Step 3

S1: Demonstrated
S2: Hold
S3: Demonstrated
S4: Hold
==> To Assess: Step 4

## 🎨 Design File

https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Admin---Processes%2FPools%2FRecruitments---Record-of-Decision?type=design&node-id=8165-22301&mode=design&t=BYBLA4BX6IkFELVi-0

### 🧑‍🎨 Designer

@Jerryescandon 

### Status on Candidate page header
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/12f14931-559f-4077-a5d4-3d537fb6c34f)

### Statuses in Candidate table
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/a49cc99f-7188-4365-8353-756a87d07a8f)

## 🙋‍♀️ Proposed Implementation

Use the functions from #9022 to determine "To assess" status

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Status chips in Candidates table and in header of Candidate page follow the table
- [ ] Status of candidates in assessment follows the extra logic
- [ ] Jest tests for complicated statuses (may be useful to reference tests for Assessment Step Tracker)

**Comment by vd1992** [comment]
Per criteria

> Status of candidates in assessment follows the extra logic
> Jest tests for complicated statuses (may be useful to reference tests for Assessment Step Tracker)

We've an issue marking the assessment step logic as needing investigation, given this builds on that this complicates things right?

Investigation issue https://github.com/GCTC-NTGC/gc-digital-talent/issues/9155
Spun off PR https://github.com/GCTC-NTGC/gc-digital-talent/pull/9146
PR comment in question https://github.com/GCTC-NTGC/gc-digital-talent/pull/9146#discussion_r1473037670

**Comment by tristan-orourke** [comment]
@Jerryescandon can I use the same pill in the table and on the Candidate page header? Right now the only difference is the triangle icon in "To assess" in the header.

**Comment by Jerryescandon** [comment]
yeah we should be reusing it
