### ISSUE TITLE
✨ Hide the "Remove candidate" button from on the new Candidate page

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#9317]
## ✨ Feature

We are now planning to launch Record of Decision before completing the remove/reinstate dialogs for the Candidate page. Comment out the non-functional "Remove candidate" button

## 🎨 Design File

[Include a link to the design file (if it exists).](https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Admin---Processes%2FPools%2FRecruitments---Record-of-Decision?type=design&node-id=6874-39127&mode=design&t=sBK6pWkxBxTIdc27-0)

### 🧑‍🎨 Designer

@Jerryescandon 

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4313717/f4da8119-d7c0-4bde-a5b6-c8c76951d0d3)

## 🙋‍♀️ Proposed Implementation

Just comment it out. You can leave a TODO comment with a reference to #9198 to the "Remove candidate" button.

## ✅ Acceptance Criteria

- [ ] non-functional "Remove candidate" button does not appear

**Comment by tristan-orourke** [comment]
Try to do something to hold onto the translated string. Maybe instead of commenting it out, use an always false conditional.

**Comment by Sahillather002** [comment]
can i work on it

**Comment by tristan-orourke** [comment]
@Sahillather002 thanks for your interest. In general, if any open source contributor submits a PR, we will happily review it and accept it if useful. 

However, we don't have the capacity to engage much with outside contributors right now, and we expect it may be difficult for you to know where and how to contribute usefully. In this case, this ticket has already been picked up by one of our own devs.
