### ISSUE TITLE
🐛 `user-info` test intermittently failing

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#9366]
## 🐛 Bug

The "User information" page on admin has a subtitle for the username. In the test, we routinely check for this to determine if thee current role can access that page. Sometimes, the assertion times out.

## 🦋 Expected Behaviour

The assertion does not timeout when the text exists.

## 🕵️ Details

The following location is the assertion that times out.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/475a0652fae649493b438398bace9fabab84cc51/apps/e2e/cypress/e2e/admin/user-info.cy.ts#L119-L121

https://github.com/GCTC-NTGC/gc-digital-talent/actions/runs/7910133858/job/21592236559#step:8:6672

## 📋 Steps to Reproduce

1. Build `npm run build`
2. Open cypress `npm run e2e`
3. Run the `user-info` spec many times
4. It may fail? Seems to happen only in GH actions

## 📸 Screenshot

![User Information Page -- tests the behavior of admin user information page with different user roles (failed)](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/20c1f35a-53e1-44ab-840e-5ace2efc66c8)

## 🙋‍♀️ Proposed Solution

Maybe add a wait on the slowest graphql request to give it time to think? 🤔 

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Test still makes the same assertion
- [ ] Consistently passes locally and in GH actions

**Comment by brindasasi** [comment]
do we want to rewrite in playwright? I forgot what we decided on ?
