### ISSUE TITLE
🐛 `dotenv` update causes failures in cypress

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#9367]
## 🐛 Bug

The recent update to `dotenv` (not merged) adds in node specific code (unsurprisingly 😅 ) and since cypress is run in the browser this is causing failures.

## 🦋 Expected Behaviour

Cypress can run on the latest version of dotenv.

## 🕵️ Details

Recently, dotenv added an `fs.existssync` to support multiple file paths. This code can only be run in node and not the browser so it is causing failures in our tests.

We use dotenv in the feature flag override function to parse the env file and override parts of it to our runtime vars. This used to work because, while being a node lib, dotenv had no node specific code. It now does so we will need to rework this function.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/475a0652fae649493b438398bace9fabab84cc51/apps/e2e/cypress/support/featureFlagCommands.ts#L3-L7

## 📋 Steps to Reproduce

1. Bump dotenv to the latest version
2. Build the app `npm run build`
3. Run cypress `npm run e2e`
4. Observe the immediate failure of any spec

## 🙋‍♀️ Proposed Solution

I suspect you may be able to use the [configuration api](https://docs.cypress.io/api/plugins/configuration-api#Usage) with the `setupNodeEvents` to add all env vars to the config. Then you could access those with [`Cypress.env()`](https://docs.cypress.io/guides/guides/environment-variables#Test-file) in the command instead of `process.env`?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] dotenv is on latest version
- [ ] Cypress runs as expected
- [ ] Feature flag override still functions

**Comment by mnigh** [comment]
@esizer looks like this was [addressed](https://github.com/motdotla/dotenv/blob/master/CHANGELOG.md#1645-2024-02-19) by the library and you [merged](https://github.com/GCTC-NTGC/gc-digital-talent/pull/9444) the fix already. any reason to keep this issue open or can it be marked as fixed by https://github.com/GCTC-NTGC/gc-digital-talent/pull/9444?

**Comment by esizer** [comment]
Fixed by #9444
