### ISSUE TITLE
🔤 Candidate statuses in title case (English)

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#9385]
## 🔤 Copy

We currently display candidate statuses in title case, we should be using sentence case.

## 🕵️ Details

https://design.canada.ca/style-guide/#:~:text=example%2C%20Operation%20PROVISION)-,Titles%2C%20headings%20and%20subheadings,use%20punctuation%20at%20the%20end%20of%20page%20titles%2C%20headings%20and%20subheadings,-Exceptions

## 🙋‍♀️ Proposed Implementation

Update the English statuses to be sentence case.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the copy has been added or updated appropriately.

- [ ] English candidate statuses are displayed in sentence case
- [ ] French messages are untouched and still connected properly

**Comment by vd1992** [comment]
There is one French status to change, so check the French too

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/9dd10f8e-d353-4b06-b8da-ca1d8b71f014)
