### ISSUE TITLE
♻️ `ProfileDocument`, `ApplicationPrintDocument` storybook stories

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#9413]
## ♻️ Debt

Add `ProfileDocument` and `ApplicationPrintDocument` component storybook stories.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] storybook story for `ProfileDocument` single user
- [ ] storybook story for `ProfileDocument` multiple users
- [ ] storybook story for `ProfileDocument` single user anonymous
- [ ] storybook story for `ProfileDocument` multiple users anonymous
- [ ] storybook story for `ApplicationPrintDocument` single user
- [ ] storybook story for `ApplicationPrintDocument` single user anonymous

**Comment by petertgiles** [comment]
Blocked until Storybook is running properly again.

**Comment by petertgiles** [comment]
We're migrating this to the backend soon so not much value in making stories right now.
