### ISSUE TITLE
🐛 Snapshot Screening Questions Not Visible in pre-ROD page

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#9414]
## 🐛 Bug

Now that screening questions are "general questions" the snapshots don't properly snapshots that were taken before the property name change.

Ref: https://talent-cloud.slack.com/archives/C066AR2CUV7/p1708108162326449

## 🦋 Expected Behaviour

The page should be smart enough to render the questions stored under the old property name.

## 📋 Steps to Reproduce

1. View a candidate snapshot taken before the property name change.
2. Observe that no questions are shown
3. Flip ON the ROD flag and observer that they are visible

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/6152d469-60b1-458d-8986-32123814af8b)
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/9c6b4a51-f05f-4f1c-b252-2d5bcb6cdb30)

## 🙋‍♀️ Proposed Solution

The ROD version of the page has a fix already implemented.  Copy this to the pre-ROD version of the page

## ✅ Acceptance Criteria

- [ ] Snapshots with "screening questions" viewable in pre- and post- ROD snapshot pages
- [ ] Snapshots with "general questions" viewable in pre- and post- ROD snapshot pages

**Comment by esizer** [comment]
I'm a little confused about this issue. This seems to be an out of date snapshot so it is doing exactly as we intended. Did we not add the code view to handle this exact scenario where a snapshot has fallen behind the current data model so we didn't need a ton of conditional logic on this page? The code was updated as intended and other than there not being a null message, this is doing exactly what we except 😕 

https://github.com/GCTC-NTGC/gc-digital-talent/blob/ef6903fedd685937b2f0d54a5d77c043dff43b5f/apps/web/src/pages/PoolCandidates/ViewPoolCandidatePage/ViewPoolCandidatePage.tsx#L408-L410
