### ISSUE TITLE
🔤 Update application process copy

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#9418]
## 🔤 Copy

This is a medium size copy update happening across many pages.

## 🕵️ Details

The attached file show what text should be changed. Highlighted in the screenshots is the text to replace, and provided below is the new text. 

[Application process copy edits - NB.docx](https://github.com/user-attachments/files/17080756/Application.process.copy.edits.-.NB.docx)

> [!IMPORTANT]  
> Some of these strings are used by components in the profile and should also be changed to match. <details><summary>Examples</summary><img width="632" alt="Screen Shot 2024-05-10 at 10 01 35" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/22492198-0a72-4cee-921f-5ceca5d97715"><img width="667" alt="Screen Shot 2024-05-10 at 09 59 31" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/e638a5ef-c541-4f27-a91e-035801f76491"></details>

## 🌎 Localization

The document includes both the English and French copy changes.

## ✅ Acceptance Criteria

- [ ] Quotation marks removed for questions under **More information** in the recruitment process overview
- [ ] Updated copy in place on the **Welcome** page of the application process (English + French)
- [ ] Updated copy in place in the **Review your profile** step of the application process (English + French)
- [ ] Updated copy in place in the instructions of the **Review your career timeline** step of the application process (English + French)
- [ ] Updated copy in place in the **Add an experience** section of the **Review your career timeline** step of the application process (English + French)
- [ ] Updated copy in place in the instructions of the **Skill requirements** step of the application process (English + French)
- [ ] Updated copy in place in the **Skill requirements** step of the application process (English + French)
- [ ] Updated copy in place in the instructions of the **Additional questions** step of the application process (English + French)

**Comment by mnigh** [comment]
> The attached file shows what text should be changed. Highlighted in the screenshots is the text to replace, and provided below is the new text.
> 
> [FINAL-Simplified copy Application workflow-FR-REV-NG.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGgxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ad85f796065546566a4430ce5087fe7625809c7/FINAL-Simplified%20copy%20Application%20workflow-FR-REV-NG.docx)
> 
> [Simplified copy Application workflow-EN (003).docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHAxQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ea2f4aedd66fc33083223867b54df5b00824b2c/Simplified%20copy%20Application%20workflow-EN%20%28003%29.docx)

@gobyrne I'm not sure if there are screenshots within the linked documents or if they were meant to be included in the issue description, but in any case, the `docx` files were uploaded to zenhub and the organization's account has been closed so they are no longer accessible.

**Comment by gobyrne** [comment]
@mnigh I've re-attached the files.

@substrae can you please update the figma files then removed the blocked-design label?

**Comment by substrae** [comment]
On it, though it might take a bit of time, as we haven't touched the files for these pages in a while, so there's a bit of clean up and migration to do.

**Comment by gobyrne** [comment]
@NienkeBr might be worth looking through this. This is essentially the culmination of the rounds of editing & translation that we did with the "special" translation team that we were working with.

I asked Josh to apply the copy changes to the current application process designs, but I think he tried to merge it with some other changes he was working on and it got stuck.

Let's chat about it next time we meet.
