### ISSUE TITLE
🔤 "Find talent" copy update

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#9419]
## 🔤 Copy

There is new copy updates required on the talent search page

## 🕵️ Details

Add any additional details that could assist with the implementation of the new or existing copy.

## 🎨 Design File

[Design file](https://www.figma.com/file/9V8kBIWxOXRaN9dkcVCU1o/Manager---Talent-search?type=design&node-id=581%3A5139&mode=design&t=JpsA7WmKd0T4tfiA-1) by @Jerryescandon 

## 🙋‍♀️ Proposed Implementation

<details><summary>Screenshot of current design</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/597827bd-f020-46c0-91d9-fb787872d1e9)

</p>
</details> 

### NEW text in English

If you are looking for talent, you have found the right place. Our talent database is open to most departments and agencies. Complete a request to find qualified candidates. All candidates in pools were assessed and successfully qualified.

Use the filters to specify your requirements. We will show you an estimated number of qualified candidates who match your criteria as you enter your information. Select “Request candidates” when you are done. Doing so will bring you to a form where you can provide your contact information and submit your request.

### NEW text in French

Si vous êtes à la recherche du talent, vous avez frappé à la bonne porte. Notre base de données de talents est ouverte à la plupart des ministères et des agences. Veuillez remplir une demande pour trouver des candidats qualifiés. Tous les candidats qualifiés dans des bassins ont été évalués et ont réussi l’évaluation.

Utilisez les filtres pour préciser vos exigences. Nous vous montrerons un nombre estimatif de candidats qualifiés qui répondent à vos critères, au fur et à mesure que vous entrez votre information. Veuillez sélectionner « Demande de candidats ». Vous verrez alors apparaître un formulaire à partir duquel vous pourriez fournir vos coordonnées et soumettre votre demande.

## NO CANDIDATES 

When no candidates match a request, we’d like to update the message in the box on the right to this:

### NEW text in English

Estimated candidates

We didn't find any matching candidates.

However, we have candidates in our talent database who haven't been assessed yet but may meet your needs.

Submit an empty request and we will try to help.

### NEW text in French

Nombre approximatif de candidats

Nous n’avons trouvé aucun candidat qui répond à vos critères.

Par contre, nous avons des candidats dans notre base de données de talents qui n’ont pas encore été évalués mais qui pourraient répondre à vos besoins.

Veuillez soumettre une demande vide et nous essayerons de vous aider.

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the copy has been added or updated appropriately.

- [ ] Criteria 1
- [ ] Criteria 2

**Comment by petertgiles** [comment]
This section reads ambiguously to me:
> We didn't find any matching candidates.
We have candidates in our talent database who haven't been assessed yet and may be able to help!

The candidates in our database may be able to help?  We may be able to help assess them? We may be able to help ourselves find more candidates?

**Comment by mnigh** [comment]
> All qualified candidates in pools were assessed and successful.

1. Are we not moving away from using the term **pool**?
2. What were the candidates successful at?

**Comment by gobyrne** [comment]
Thanks, I'll take this back. I agree it's not great. 

On pools: definitely copy for applicants should not refer to pools. For gov folks though, "pool" is technical HR language and it could be acceptable.

**Comment by gobyrne** [comment]
Corinne and I worked to address the comments. It's slightly better now.
