### ISSUE TITLE
🐛 Missing translations for assessment builder modal

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#9421]
## 🐛 Bug

Translations are missing

## 🕵️ Details

Not sure how the checks missed this 😕 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/6b2392c6-1d94-474f-9572-a56aa9f15412)

## 📋 Steps to Reproduce

1. Head to assessment plan builder, switch to French, open modal

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/5ab35439-b895-4979-839f-0261c057a223)

## ✅ Acceptance Criteria

- [ ] No missing French for Assessment plan

**Comment by mnigh** [comment]
> Not sure how the checks missed this 😕

 The objects are not wrapped in `defineMessage()`: https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/apps/web/src/pages/Pools/AssessmentPlanBuilderPage/components/AssessmentDetailsDialogLabels.ts
