### ISSUE TITLE
🐛 Admin side menu appears over dialogs

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#9429]
## 🐛 Bug

On medium to small screen sizes, the admin side menu is appearing over dialogs.

## 🦋 Expected Behaviour

Dialogs should appear over all other elements on the page.

## 📋 Steps to Reproduce

1. Login to admin
2. Reduce screen size to a medium size (`l-tablet` or `p-tablet`)
3. Open the side menu in admin
4. Open a dialog
5. Observe the menu overlapping and obscuring the dialog

## 📸 Screenshot

![Screenshot 2024-02-21 133959](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/1626f94e-dcbc-4b06-9f1b-0a1fe3b1b601)

## 🙋‍♀️ Proposed Solution

Probably just adjust z-index? Or, it could be a media mismatch 🤔 

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Admin side menu only obscures content on mobile devices
- [ ] Dialogs appear over other content on admin pages

**Comment by petertgiles** [comment]
Related: https://github.com/GCTC-NTGC/gc-digital-talent/issues/8902
