### ISSUE TITLE
🔤 DEI copy update for cognitive accessibility 

### ISSUE THREAD

**Issue by RM-1978** [GCTC-NTGC/gc-digital-talent#9430]
## **Description:**

Idea conflict between the texts of the component legend and the checkbox label in three EE category UIs (person with a disability, Visible minority and Women) might make it hard for some users to understand how they can self-identify with that community on our platform.

### **Screen captures**

![image](https://github.com/GCTC-NTGC/design-gc-digital-talent/assets/101275838/676a33a6-a0cb-4ed4-9283-6a8b4e3001d0) 
![image](https://github.com/GCTC-NTGC/design-gc-digital-talent/assets/101275838/d8ad056a-8192-48f5-9bda-b57fa37b3a5f)

![image](https://github.com/GCTC-NTGC/design-gc-digital-talent/assets/101275838/9136a75f-bbda-4d56-ba8b-14e4344fa30c)

## **Proposed Solution**
Simplify the relationship between the legend and the checkbox labels. Change the texts to: 

 - Legend label: "Based on this definition, I identify as:"
 - Checkbox labels:  [ ] "a person with a disability.",   [ ] "a member of a visible minority.", [ ] "a woman."
 
 FR:
  - Legend label: "Selon la définition fournie, je m'identifie en tant que :"
   - Checkbox labels:  [ ]  "personne en situation de handicap.", [ ]  "membre d'une minorité visible.", [ ]  "femme."

## **Acceptance Criteria**
- [ ] Proposed change is implemented
- [ ] Confirm change on Application, Profile, and Admin view of profile & snapshot. 
- [ ] Change reads well with a screen reader

**Comment by gobyrne** [comment]
What's going on with the line breaks in those screenshots?

**Comment by petertgiles** [comment]
I thought we were moving away from form labels with incomplete sentences and colons?
