### ISSUE TITLE
🐛 Screening and assessment board - fallback title

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#9432]
## 🐛 Bug

Fallback to the step type, IE Application screening, if no optional title input 

## 📋 Steps to Reproduce

1. Head to `en/admin/pools/:id/screening`

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/9a6e5ce1-b50d-41e6-99eb-f00143cbf732)

## 🙋‍♀️ Proposed Solution

Adjust rendering column title to use the Enum value display of the assessment type if no optional title provided.

## ✅ Acceptance Criteria

- [ ] Should use the enum to diplay the assessment type if no optional title is provided.

**Comment by mnigh** [comment]
#8898
