### ISSUE TITLE
🛠️ GitHub action for duplicate i18n strings

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#9434]
## 🛠️ Tooling

Create a GitHub action for duplicate i18n strings.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt tooling was properly updated and remains functional.

- [ ] GitHub action adds a comment to PR when with list of duplicate strings being introduced from PR

**Comment by petertgiles** [comment]
Is this still needed after #9678 ?

**Comment by mnigh** [comment]
> Is this still needed after #9678 ?

I don't think so since the jest test is run in the ci.
