### ISSUE TITLE
🛠️ Warning when duplicate strings during `intl-extract` script

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#9435]
## 🛠️ Tooling

Display warning when there are duplicate strings with a list of the strings during `intl-extract` script. Possibly during `check-intl` as well.

## Proposed Implementation

- Add an existing duplicates to a whitelist to avoid worrying about them

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt tooling was properly updated and remains functional.

- [ ] warning displayed with list of strings when there are duplicate strings during `intl-extract` script
- [ ] can ignore duplicate strings by adding them to a whitelist

**Comment by petertgiles** [comment]
It looks like Jest has built-in snapshot testing that can be used with any serializable value!
https://jestjs.io/docs/snapshot-testing#does-snapshot-testing-only-work-with-react-components

This would be a possible implementation: use a Jest snapshot as the whitelist.  It is already built in to our CI process and will alert us any time an unexpected change occurs.  When a change is expected (more dups or less) then the dev can simply commit an updated snapshot.
