### ISSUE TITLE
🐛 Assessment steps with only asset skills

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#9436]
## 🐛 Bug

Assessment Steps with only Asset skills initially appear in the "To assess" status until you add one result decision. They should _always_ appear as Qualified.

## 🦋 Expected Behaviour

Only asset skills & asset skill not assessed - Qualified
Only asset skills in step & all asset skills assessed - Qualified
Asset and Required skills in step & only required skills assessed - Qualified

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Name and version (if possible).
- **Browser**: Name and version (if possible).

## 📋 Steps to Reproduce

1. ...
2. ...

## 📸 Screenshot

![306431677-f3832e78-19f0-4b39-8692-9eb6ceb58b3f](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/e1b713bf-c362-46df-9492-3d5ea18410c7)

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] When a step only has asset skills, it always appears as Qualified
- [ ] If a step assesses Asset and Required, asset skills are ignored for determining Step status.

**Comment by mnigh** [comment]
@vd1992 were the answers to your questions and this issue itself resolved by https://github.com/GCTC-NTGC/gc-digital-talent/pull/9645?

**Comment by vd1992** [comment]
No, that one is dealing in `skill.category`, this deals in `poolSkill.type`
I think this one needs refinement or reviewing, will stick the label on

**Comment by tristan-orourke** [comment]
Nevermind, @Jerryescandon actually kind of likes that it initially appears as yellow before some interaction.
