### ISSUE TITLE
🏐 Can we reliably do tables in print exports? 

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#9496]
## ✨ Feature

Up to this point we have tried to keep print exports very simple.  There is now some interest in adding tables into exports for use with RoD.  

## :question: Main question

Can add tables to print exports so that they reliably render across browsers?

## :beverage_box: Timebox

?

**Comment by tristan-orourke** [comment]
Consensus in scrum is - we _can_ do tables in print exports, but they won't reliably look good
