### ISSUE TITLE
🐛 When there is no candidate, step tracker shows a div with scroll bar unnecessarily 

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#9519]
## 🐛 Bug

This is a minor cosmetic issue. When there is no candidate , the default step tracker shows an empty div with scroll bar. It would be nice not to show that. 
![image (1)](https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/06bc81b8-7502-43f1-9271-6598301cc003)

## 🦋 Expected Behaviour

Keep the bottom div but hide the scroll bar. 

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Name and version (if possible).
- **Browser**: Name and version (if possible).

## 📋 Steps to Reproduce

1. Go to any brand new pool with 0 candidates
2. Observe Step 1

## 📸 Screenshot

Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Hide the unnecessary scroll bar on the bottom div of step tracker

**Comment by esizer** [comment]
Even when we remove the scrollbar I still think this will look a little silly. Should we also add a message to this like "No candidates in this step" or something? 

![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/8609fc28-884e-4d96-9667-e89ee252a711)
