### ISSUE TITLE
🐛 Screening decision dialog not closing after save

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#9526]
## 🐛 Bug

The dialog to assess candidates under the "Screening and assessment" section does not close once the item is saved.

## 🦋 Expected Behaviour

After saving the form, the dialog should close since it is not longer needed.

## 📋 Steps to Reproduce

1. Login as admin
2. Navigatge to a pool
3. Navigate to the "Screening and assessment tab"
4. Click on a user with the "To assess" status
5. Click on the "To assess" button on row in the table
6. Edit the form and submit
7. Confirm it remains open

## 📸 Screenshot

![Screenshot 2024-02-27 114200](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/33df1489-0794-45c7-a8cc-d121697d421d)

## 🙋‍♀️ Proposed Solution

I think we will need to update the controlled state for `ScreeningDecisionDialog` and then close it after success on the api call whenre it says `// Do something`

https://github.com/GCTC-NTGC/gc-digital-talent/blob/cb8f981abf65edc1a1cb12a5df0c87439abc9fc9/apps/web/src/components/ScreeningDecisions/ScreeningDecisionDialog.tsx#L528

https://github.com/GCTC-NTGC/gc-digital-talent/blob/cb8f981abf65edc1a1cb12a5df0c87439abc9fc9/apps/web/src/components/ScreeningDecisions/ScreeningDecisionDialog.tsx#L544

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] `ScreeningDecisionDialog` closes on success

**Comment by RM-1978** [comment]
Thanks @brindasasi! We are a team. I will get you the rest of my notes asap.
