### ISSUE TITLE
🐛 First assessment does not update assessment results table

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#9527]
## 🐛 Bug

When completing the first assessment result for a candidate. the changes are no reflected in the table until a refresh.

## 🦋 Expected Behaviour

Table updates on creation of assessment results.

## 📋 Steps to Reproduce

1. Login as admin
2. Navigatge to a pool
3. Navigate to the "Screening and assessment tab"
4. Click on a user with the "To assess" status
5. Click on the "To assess" button on row in the table
6. Edit the form and submit
7. Confirm the table is not updated
8. Refresh page
9. Observe the table shows correct info

## 📸 Screenshot

https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/a8c989c5-8873-4344-a32c-d4bc289d0e10

## 🙋‍♀️ Proposed Solution

Likely need to add `additionalTypenames` to the query's context.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Creation of assessment results are always reflected in the table without need of a refresh

**Comment by brindasasi** [comment]
@RM-1978 Eric is ahead of us ! 😅

**Comment by tristan-orourke** [comment]
I could be wrong, but my guess is this is related to #9526, since they're both fixed by a page refresh.
