### ISSUE TITLE
♻️ Migrate `e2e` tests to Playwright

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#9528]
## ♻️ Debt/Refactor

Migrate all of our Cypress tests to Playwright.

## 🕵️ Details

We have made the decision to migrate from Cypress to Playwright. We already have a few tests migrated so you can follow the patterns developed there. If you need some help, the [documentation for Playwright](https://playwright.dev/docs/intro) is very well done and easy to follow.

## 🙋‍♀️ Proposed Solution

Follow existing patterns developed in `apps/playwright` or create new ones where needed to move all tests from `e2e` to `playwright`.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] `apps/e2e` folder removed
- [ ] All existing Cypress tests have been migrated to Playwright
- [ ] Playwright commands renamed to be more general ie `e2e:playwright:chromium` -> `e2e:chromium`
- [ ] Cypress workflow removed
- [ ] Add `README.md` for Playwright
- [x] Add badge to project `README.md` (completed in #9969)

**Comment by petertgiles** [comment]
Let's break this up to different files.

**Comment by petertgiles** [comment]
Replaced by #10480 - #10492
