### ISSUE TITLE
✨ New public skills page 

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#9540]
## ✨ Feature

We're getting sooo many requests for people to browse our skills. We decided it's just best if we create a new page to view and browse all skills. Minimal dev effort for now please! We can iterate on it if needed.

## 🙋‍♀️ Proposed Implementation

1. New page should be at **talent.canada.ca/skills** or similar
2. Create a new page and add a filterable table with all the skills.
3. Descriptions (in description column) should wrap if they are long.
4. Default number of items on the table should be 20
5. No links to this page from other pages yet 🤷‍♀️

## 🎨 Design File

[Figma file](https://www.figma.com/file/f9Vpe5c2bAWXmtwlyueJDq/Candidates---All-skills?type=design&node-id=813%3A380&mode=design&t=jeBoGBIp48rvjy72-1) by @Jerryescandon 

## 📸 Screenshot

 
![All skills page](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/0972a8a3-87f2-4766-9700-644059b2fa72)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/0098b851-98c6-4ca3-bcc0-cac476d362d1)

## 🌎 Localization

EN: All skills
Explore all the skills on our site.

FR: Toutes compétences
Découvrez toutes les compétences sur notre site.

## ✅ Acceptance Criteria

- [ ] New page at new url `/skills`
- [ ] Skills table has columns for name, family, category and description
- [ ] Skills are filterable by category and family in filter dialog
- [ ] Search bar filters by name and/or description
- [ ] Default number of table items is 20
- [ ] Table uses client-side filtering
- [ ] Add cant find skill `<Well />` at the bottom of the page

**Comment by tristan-orourke** [comment]
@Jerryescandon can we make the title "Skills" instead of "All skills", for consistency with our other single-resource-table pages?

**Comment by Jerryescandon** [comment]
Done! Also, I think the default number of items on the table should be 20, I updated the issue description.
