### ISSUE TITLE
✨ Implement fragment masking

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#9543]
## ✨ Feature

Implement fragment masking for components/api requests.

## 🕵️ Details

Now that we have fully migrated to the new `client-preset` for `graphql-codegen` we can start making use of the fragment masking. We opted to not do this to increase the speed at which we completed the migration since it may be a lot of work.

Right now, we just use one main query for pages and avoid breaking it up into fragments. But, we should try to break it up and allow components to define the fragments they require. This way, we prevent over/under fetching.

## 🙋‍♀️ Proposed Implementation

We have some[ documentation on how to implement this](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/documentation/graphql.md#%EF%B8%8F-component) as well as a few working examples in the codebase already. You can also follow the[ blog post about using fragment masking](https://the-guild.dev/blog/unleash-the-power-of-fragments-with-graphql-codegen).

You will need to look at the existing components that consume data from the API and:

1. Create a fragment for them
2. Update props to accept the fragment instead of the full type that is generated
3. Mask that fragment
4. Fix any issues that result from the new fragment type
5. Apply those fragments to the page level queries

### Example

https://github.com/GCTC-NTGC/gc-digital-talent/blob/57337dbe576a80b06774ced129cdd0796385d559/apps/web/src/pages/Skills/SkillShowcasePage.tsx#L30-L89

```[tasklist]
### Tasks
- [ ] #9706
- [ ] #9709
- [ ] #9710 
- [ ] #9711 
- [ ] #9712 
- [ ] #9713 
- [ ] #9714  
```

**Comment by mnigh** [comment]
@esizer can this "epic" issue be closed now?
