### ISSUE TITLE
♻️ Update application confirmation copy and add link to survey

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#9551]
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/09e5771b-f800-4483-aeab-18c37d92a585)

## ✨ Summary

[Visit the Figma file](https://www.figma.com/file/i7FhmyCoacRFSPmK6b7h7C/Application-confirmation?type=design&node-id=2%3A3&mode=design&t=Cmfg0WlS0PLVKyQT-1) • Contact @substrae with design questions

This ticket aims to update a few small copy elements on the application confirmation page as well as add a new link to our post-application survey.

```[tasklist]
### ✅ Requirements
- [ ] Update the next step link labels to match
- [ ] Add the new "Tell us about your experience" button and link it to the survey ([English](https://forms-formulaires.alpha.canada.ca/en/id/clsdw2j7t00igxd8211b53rlv), [French](https://forms-formulaires.alpha.canada.ca/fr/id/clsdw2j7t00igxd8211b53rlv))
- [ ] Ensure the survey link opens in a new tab
- [ ] Change the existing dashboard button label and swap it to an 'inline' style button
- [ ] Triple check dark mode
```

```[tasklist]
### 🔗 Related
- [ ] #9550 
``` 

## 🔍 Details

<details>
  <summary>📸 Full page (light)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/1362906c-9db4-4237-9583-48928728b088" />
</details> 

<details>
  <summary>📸 Full page (dark)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/ce1c613e-942d-4f19-b460-4935ecd30868" />
</details>

**Comment by esizer** [comment]
I'm a little confused by the "related" task list? Is that like a soft blocker? How is this related to the stepper updates? Should I be doing something in that ticket that impacts this one or vice versa? 😕

**Comment by substrae** [comment]
@esizer 

Sorry, I was using it as a way to relate issues together in a mini-epic fashion. They aren't necessarily blocked by each other but they should be released together. Does that make sense?
