### ISSUE TITLE
✨ New header for talentsearch side

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#9552]
## ✨ Feature

New header with notifications bell icon which indicates unread notifications

## 🕵️ Details

Icon changes to alert mode if user has unread notifications, so will need to query for logged in user's notifications. 

## 🎨 Design File

https://www.figma.com/file/bIvDLraUxqGxDBuerPJlNI/Candidates---Notifications?type=design&node-id=813-380&mode=design

### 🧑‍🎨 Designer

@substrae 

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/8df3b20e-4b60-41e8-94da-29bc4ac37e9e)

## ✅ Acceptance Criteria

- [ ] Header updated with icon for notifications panel to be plugged into
- [ ] Having unread notification changes the icon

## 🛑 Blockers

Issues which must be completed before this one.

```[tasklist]
### Blocked By
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/9557
```

**Comment by tristan-orourke** [comment]
Folding this into #9553
