### ISSUE TITLE
♻️ Remove intermediary main admin page

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#9604]
## ♻️ Debt/Refactor

It would be nice to remove this intermediary page `/admin` that just shows a link to `/login-info` and uses a one-off custom component.

## 🕵️ Details

The main `/admin` URL doesn't seem that necessary anymore, all it does is link you to login and the only people landing here are the ones with  a direct link since we never link to it unless you are already logged in. As well, this is the only place that uses the `CardLink` component so we could get rid of some unnecessary code and redirects.

## 🙋‍♀️ Proposed Solution

Move everything from `/admin/dashboard` up a level to `/admin` ensuring to keep the `RequireAuth`. This would remove an unnecessary redirect and any anonymous user navigating directly to `/admin` should get redirected to the login with `RequireAuth`. 

Also, you can remove the `CardLink` component since it will be orphaned after this change.

## ✅ Acceptance Criteria

- [ ] Removed `/admin/dashboard` path
- [ ] Admin dashboard page component moved to `/admin`
- [ ] Route is wrapped in `RequireAuth` in the `Router`
- [ ] `CardLink` removed
- [ ] Unauthenticated and unauthorized users cannot access `/admin`

**Comment by tristan-orourke** [comment]
I think we initially set it up like this so that anonymous users could land on a page without `RequireAuth`. However, I don't see anything wrong with redirecting them straight to login.

**Comment by esizer** [comment]
> I think we initially set it up like this so that anonymous users could land on a page without `RequireAuth`. However, I don't see anything wrong with redirecting them straight to login.

Yeah, save them a click and remove some code 😛

**Comment by tristan-orourke** [comment]
@Jerryescandon feels weird about sending a user to our sign-in partner before they even land on our site. We want to keep the landing page to get them oriented on our own site.

This page may disappear soon, as designers are re-thinking how to connect Admin and Applicant sections of the site (such as with a combined header/nav menu).

We can discuss removing the CardLink component separately.

**Comment by esizer** [comment]
> @Jerryescandon feels weird about sending a user to our sign-in partner before they even land on our site. We want to keep the landing page to get them oriented on our own site.

The proposal was to send them to the `/login-info` page, not sign in canada. You cannot get to this page without typing it in the address bar. Do we actually even have many visits to this page in our analytics?

**Comment by Jerryescandon** [comment]
> The proposal was to send them to the `/login-info` page, not sign in canada. You cannot get to this page without typing it in the address bar. Do we actually even have many visits to this page in our analytics?
> 
> This page does the exact same thing as `/login-info` but with a different design. The ticket was just so we have one page to login instead of a separate one for admins that is not linked anywhere and possibly not even in use by anyone.

Oh, well in that case I think it would be fine
