### ISSUE TITLE
❗ [Notification] New job posted

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#9621]
## ✨ Purpose

Let existing users know that a new job has been posted on the platform.

## ❗ Trigger

A pool is published.

## 👀 Audience

All users with the Applicant role (so all users).

### Email templates (English and French)

Hey {{user.firstname}}, 

You signed up to be notified when new opportunities are posted on GC Digital Talent.  

A new opportunity is now available! Find out if this is a fit for you and apply: 

((opportunity.title)hyperlinked) 

**standard email notification footer**

Objet :
Un nouveau poste est affiché sur Talents numériques du GC 

Corps du texte :
Vous avez accepté de recevoir des avis lorsqu’un nouveau poste est affiché sur Talents numériques du GC. 

Un nouveau poste y est maintenant affiché! À vous de juger s’il vous convient et de présenter votre candidature :
((opportunity.title)hyperlien)

**standard email notification footer**

### In-app string (English and French)
A new opportunity is now available! Find out if this is a fit for you and apply.

Un nouveau poste y est maintenant affiché! À vous de juger s’il vous convient et de présenter votre candidature.

### Link

Links to the job poster page

## 💾 Content

- This belongs to the "Job alerts" family of notifications (see #9555)
- Must store pool id?

## ✅ Acceptance Criteria

- [ ] Email template exists in GC Notify
- [ ] Notification class exists in Laravel
- [ ] Notification is triggered by appropriate event and send to appropriate users (including NOT any users who are ignoring this notification's Notification Family)
- [ ] Please confirm that the "Job alerts" notification family is not "checked" by default on the Notifications settings. This family really needs to be opt-in (not opt-out).
- [ ] Notification type added to schema
- [ ] Notification type rendered appropriately on frontend
- [ ] Tests
- [ ] Yes, we've added the in-app notification back in. Please ensure it's there.

## 🛑 Blockers

Issues which must be completed before this one.

```[tasklist]
### Blocked By
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/9640
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/10357
```

**Comment by marc-donofrio** [comment]
Email: [noreply@canada.talent.ca](mailto:noreply@canada.talent.ca)
Subject: {{opportunity.title}} has been posted! 

Hello,

A new opportunity is now live!

You may view and apply to the opportunity here {{opportunity.url}}

Regards,
{{platform_name}}
*******************************
Courriel : [noreply@canada.talent.ca](mailto:noreply@canada.talent.ca)
Objet : {{opportunity.title}} a été publiée !

Bonjour,

Une nouvelle opportunité est maintenant en ligne !

Vous pouvez consulter et postuler à l'opportunité ici {{opportunity.url}}

Salutations,
{{platform_name}}

**Comment by tristan-orourke** [comment]
Notes from Lauren
- lets get rid of the "hello"
- give more context about us
- "a new opportunity is now live on the GC Digital Talent platform"
- "you expressed interest" or "you have asked to be notified"
- "log in to apply"
- Might be worth reminding user of base link
- why you're receiving this and how can you unsubscribe (you have to log in)
-

**Comment by gobyrne** [comment]
marc has sent the copy to translation
