### ISSUE TITLE
♻️ Merge the skill library tables

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#9624]
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/d2f66847-645e-400b-b0bc-56bcd5794cbf)

## ✨ Summary

[Visit the Figma file](https://www.figma.com/file/FhRhwczL8JI6JC8eVFlWOm/Candidates---Skill-library?type=design&node-id=378-21156&mode=design) • Contact @substrae with design questions

This ticket aims to simplify the skill library page by merging the behavioural and technical skill tables into a single library table. We're increasingly recognizing that the division between behavioural and technical skills is meaningless to our applicant user group, so this, in combination with the skill browser dialog updates listed in the related section of this ticket, should make the experience much clearer.

> ⭐ Please note that you can ignore the changes to the header layout for this ticket. 

```[tasklist]
### ✅ Requirements
- [ ] Update the page subtitle to match
- [ ] Update the section title to match
- [ ] Update the section instructions to match
- [ ] Alter the search input's label to refer to "your skills"
- [ ] Add the + icon to the "Add a new skill" button
- [ ] Skill picker (when opened on this page) should not filter by Technical or Behavioural
- [ ] Triple check dark mode
``` 

```[tasklist]
### 🔗 Related
- [ ] #9623
- [ ] #9625 
``` 

## 🔍 Details

<details>
  <summary>📸 Empty state (light)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/650b54aa-a0a5-49f5-96e5-ab7cd625a41c" />
</details> 

<details>
  <summary>📸 Empty state (dark)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/72517989-f4b0-4781-8957-d5b4d45cb640" />
</details>

<details>
  <summary>📸 No matching search results (light)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/ee17f167-930c-4e3d-a7e6-5553ee22b743" />
</details> 

<details>
  <summary>📸 No matching search results (dark)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/d373d78b-8fa2-4f38-a228-03ef059c1b3d" />
</details> 

<details>
  <summary>📸 Full table (light)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/0d6c1f4f-71a5-468c-a50b-59f3a3d7b909" />
</details> 

<details>
  <summary>📸 Full table (dark)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/b310d2a0-0627-47e8-8364-06f880e6dfc2" />
</details>

**Comment by esizer** [comment]
I think the AC "Add the + icon to the "Add a new skill" button" should be moved to #9623 since that button actually appears as part of the dialog and not the table. But that is just a minor detail, you could also just update the trigger of the dialog in this ticket 😅
