### ISSUE TITLE
🐛 Discrepancy between "All skills" on Request page and on Job Poster skill picker

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#9630]
## 🐛 Bug

On production, on the Request page, the skill picker shows 271 skills under All skills. On the Job Poster form skill picker, we see 262 skills under All skills. Where is this discrepancy coming from?

Also, some skills don't appear under All skills, but can be found if you know their skill family. Some examples:
- Develop organization policy
- Application of Cybersecurity Principles
- Support Government of Canada Reporting Cycles

## 🦋 Expected Behaviour

- All skills should appear under "All skills"
- Skill count should be consistent across all skill pickers

## 🕵️ Details

Not sure what the cause is yet, or whether this can be reproduced easily on local.

## 📋 Steps to Reproduce

1. Go to https://talent.canada.ca/en/search
2. Open the skill picker. Note number of skills under "All skills"
3. Log in as an admin
4. Go to create or edit a job poster
5. Open the skill picker
6. Note number of skills under "All skills"

## 📸 Screenshot

Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] All skills appear under "All skills"
- [ ] Skills available (and the count) should be consistent across all skill pickers

**Comment by esizer** [comment]
Silly question but, does the pool have skills? 😅 Skills already assigned do get filtered out which would cause "All skills" to be lower.

**Comment by vd1992** [comment]
Locally I see 270 skills in both places

**Comment by tristan-orourke** [comment]
Ask for screenshots or try to reproduce in production to confirm cause

**Comment by tristan-orourke** [comment]
Not a problem. Turns out this just because we remove skills from the skill picker once they'be been added once on the Job Poster builder.

**Comment by vd1992** [comment]
> Not a problem. Turns out this just because we remove skills from the skill picker once they'be been added once on the Job Poster builder.

Well hypothesized, @esizer
