### ISSUE TITLE
♻️ Connect "cant find skill" skills dialog info to public skills page

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/gc-digital-talent#9634]
## ♻️ Debt/Refactor

- Remove the "can't find skill" accordion on the skills dialog. Adds a link in the dialog footer, linking it to the new public Skills page. That link should bring the user to the "cant find skill" `<Well />` (should link have an id).

## 🕵️ Details

Add any additional details that could assist with the development of the new feature.

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] Remove the "can't find skill" accordion on the skills dialog
- [ ] Replace accordion with a link which reads "???" and links to "Can't find skill" Well on the public Skills page

## 🛑 Blockers

Issues which must be completed before this one.

```[tasklist]
### Blocked By
- [ ] ticket number
```

**Comment by tristan-orourke** [comment]
@yonikid15 is there only one component which has the current "can't find skill" accordion?  Could you add a screenshot?

**Comment by tristan-orourke** [comment]
@yonikid15 @Jerryescandon what should the new link read? Is it just "Can't find skill?"
Is there a figma design?

**Comment by Jerryescandon** [comment]
> what should the new link read? Is it just "Can't find skill?"

YUP! from @substrae 

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/64d1fc48-3645-4605-b4a8-eac6fd852891)

**Comment by substrae** [comment]
@yonikid15 @tristan-orourke @Jerryescandon 

This is all described in #9623

**Comment by tristan-orourke** [comment]
Subsumed into #9623
