### ISSUE TITLE
🐛 Unstable Chromatic snapshots - Manager's Home Page, Executive's Home Page

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#9636]
## 🐛 Bug

The manager's home page and executive's home page for mobile have an unstable snapshots that are creating nuisance diffs in Chromatic.

## 📸 Screenshots

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/1e97fdfb-047a-40a7-9681-040514b0b389)

<img width="1440" alt="Screen Shot 2024-04-11 at 16 06 21" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/1be5fc3e-cabd-45b9-99d1-542cbc6df750">

## ✅ Acceptance Criteria

- [ ] Stories create stable snapshots in Chromatic

**Comment by tristan-orourke** [comment]
Something about sourceSet?
Overlapping widths?

**Comment by vd1992** [comment]
Executive page too
https://www.chromatic.com/build?appId=61e099a1bb1465003a73d3ce&number=6748

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/0ff874e6-a1fe-4146-b625-e2d99e653ef9)

**Comment by vd1992** [comment]
The last 8 runs on main have been clean, hopefully it spontaneously resolved but it could have gotten even trickier to troubleshoot
https://www.chromatic.com/builds?appId=61e099a1bb1465003a73d3ce&branch=main

**Comment by mnigh** [comment]
> The last 8 runs on main have been clean, hopefully it spontaneously resolved but it could have gotten even trickier to troubleshoot https://www.chromatic.com/builds?appId=61e099a1bb1465003a73d3ce&branch=main

No [Chromatic failures in 2 weeks](https://github.com/GCTC-NTGC/gc-digital-talent/actions/workflows/chromatic.yml?query=is%3Afailure), @GCTC-NTGC/developers anyone opposed to closing the issue?

**Comment by vd1992** [comment]
Maybe Storybook 8 will fix it, or, make it easier to diagnose via running Chromatic diffing locally so you can try and replicate it
https://storybook.js.org/blog/storybook-8/

Waiting to update to V8 in https://github.com/GCTC-NTGC/gc-digital-talent/issues/9752

**Comment by esizer** [comment]
Wasn't fixed :cry:
