### ISSUE TITLE
✨ Extra chip on process title

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#9637]
## Description

The header used in an individual process is getting reused on all 3 pages (main page, advertisement info page, and assessment plan page). This is misleading and confusing.

The chip label that we see only refers to the "Advertisement information" page.

## 🦋 Expected Behaviour

Each of these three pages should have it's own header.

1. On main process page: KEEP current title and subtitle and REMOVE chip
2. On advertisement information: CHANGE title and subtitle, KEEP chip label
4. On assessment plan page: REPLACE by MOVING up the title and subtitle currently under the breadcrumbs, and updating the copy in the "organize assessment approach" instructions.

### Advertisement information page
**New title:**
`Advertisement information`

**New subtitle:**
`Define the information and requirements for this recruitment process.`

### Assessment plan
**New title:**
`Assessment plan`

**New subtitle:**
`Select, organize and define the assessments used to evaluate each skill in the advertisement.`

**New copy**

```
Use this section to define which assessments will be used as part of your assessment process. Make sure every skill is assessed at least once to complete your assessment plan.

You can also change the order in which you plan to perform these evaluations. The only exceptions are the “Application screening” and the “Screening questions (at the time of application)” assessments which will always be the first and second steps in any pool advertisement.
```

## 📸 Screenshot

<details><summary>CURRENT process header</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/99598667-13f1-4fdc-98cf-e409d3b58b6d)

</p>
</details> 

<details><summary>CURRENT advertisement information header</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/ac4540c2-d123-4eaf-9975-43602e47940d)

</p>
</details>  

<details><summary>CURRENT assessment plan</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/494bb21c-b0d7-49c3-b83f-f4b15f91cf3f)

</p>
</details> 

<details><summary>NEW advertisement information header</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/640954f1-205b-4ff8-9a89-b380a6879988)

</p>
</details> 

<details><summary>NEW assessment plan header and copy</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/7afec6e6-5190-4afb-a2c1-685b4dde7799)

</p>
</details> 

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] On main process page: KEEP current title and subtitle and REMOVE chip
- [ ] On advertisement information: CHANGE title and subtitle, KEEP chip label
- [ ] On assessment plan page: REPLACE by MOVING up the title and subtitle currently under the breadcrumbs, and updating the copy in the "organize assessment approach" instructions.
- [ ] `<title>` meta remains unchanged.

**Comment by tristan-orourke** [comment]
> On advertisement information: CHANGE title and subtitle, KEEP chip label

@Jerryescandon What should the new title and subtitle be?

**Comment by Jerryescandon** [comment]
Updated the ticket!

**Comment by tristan-orourke** [comment]
@Jerryescandon Do you want the chip removed on the Assessment Plan page?

**Comment by tristan-orourke** [comment]
@Jerryescandon there's some concern that the titles of the Job Poster form and Assessment Plan pages should include the name of the job, to avoid being exactly the same title for different processes.

**Comment by Jerryescandon** [comment]
> @Jerryescandon Do you want the chip removed on the Assessment Plan page?

Yes and no, CURRENTLY we are showing two chips, I only wanna keep the relevant to the assessment plan.

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/494bb21c-b0d7-49c3-b83f-f4b15f91cf3f)

**Comment by Jerryescandon** [comment]
> @Jerryescandon there's some concern that the titles of the Job Poster form and Assessment Plan pages should include the name of the job, to avoid being exactly the same title for different processes.

🤔 Maybe I'm missing something, but since we don't have visibility on other posters I dont think it helps much knowing this posters name, but we also have it on the breadcrumbs too 🤔 huddle me up fam.

**Comment by esizer** [comment]
Okay, so my main concern about title changing was document title (think tab). Not really the page title. An example would be in github, if you are on a PR and switch to the "files changed" sub-page you will notice the tab title does not update so if you leave that tab it is still clear that the main context of that tab is the PR.

So if you have multiple tabs open to that page but on different pools the tab is clear about what pool you are viewing/editing and doesn't just specify that it is an "assessment plan".

I don't think it changes the effort but if everyone is onboard then I'd say just add in the AC that that `<title>` meta remains unchanged.

Something else we could do is add both like "{poolName} | Assessment plan | GC Digital Talent" (but titles should be fewer than 60 characters for SEO)
