### ISSUE TITLE
❗[Notification] Talent Request submission confirmation

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#9639]
## ✨ Purpose

Send a talent seeker an email to confirm that we've received their request, and give them a record they can refer to later. It must contain their request reference number (the id of the request).

This notification is a bit unusual in that it is only an email notification, there is no in-app version, since a user can submit a request without being logged-in.

## ❗ Trigger

A talent search request is submitted.

## 👀 Audience

An email will be sent to the "Government of canada email" submitted with the Candidate Search request.

QUESTION: should we send an email to the hrAdvisorEmail as well?
ANSWER: No. That's just for recruitment team to use when the manager gets closer to hiring.

### Email templates (English and French)

Subject: GC Digital Talent request confirmation {{request.id}}

Hey {{Full name}}, 

You have submitted a talent request on GC Digital Talent. 

We have received your request. Your tracking number for this request is:  

{{60d3902e-3a00-42b9-aad0-a940f38514e5}}

You will receive a follow up on your request within the next 5 to 10 business days. 

**Standard email footer**

Subject: Talent numérique du GC - Confirmation de votre demande {{request.id}}

Bonjour {{prénom et nom}},

Vous avez soumis une demande d’emploi sur Talents numériques du GC.

Votre numéro de suivi pour cette demande est : 6cf54c08-01aa-4a41-8034-e1aa9a29c9c2

Vous recevrez un suivi sur votre demande dans 5 à 10 jours ouvrables.

### In-app string (English and French)

There is no in-app notification.

### Link

Should the email notification contain a link to the talent search page?

## 💾 Content

- This is NOT part of a notification family that can be controlled on the notification settings at this time (this form can be submitted unauthenticated). But maybe we should create a placeholder called "manager talent requests" (see #9555)
- Needs to contain request id
- QUESTION: do we want to show the details of the search filters (and the results) in the email?
- ANSWER: Yes... but skip for now.

## ✅ Acceptance Criteria

- [ ] Email template exists in GC Notify
- [ ] Notification class exists in Laravel
- [ ] Notification is triggered by appropriate event and send to appropriate users (including NOT any users who are ignoring this notification's Notification Family)
- [ ] Bilingual email (since we don't have their preferred language of correspondence)
- [ ] Tests?

## 🛑 Blockers

Issues which must be completed before this one.

```[tasklist]
### Blocked By
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/9640
```

**Comment by marc-donofrio** [comment]
Email: [noreply@canada.talent.ca](mailto:noreply@canada.talent.ca)
Subject: Your opportunity {{opportunity.title}} confirmation number is {{opportunity.id}} 

Hi {{requester.name}},

Thank you for your submission to the {{portal_name}}. We received your request and the confirmation number {{opportunity.id}} has been created for you! 

To view the status of the opportunity, please visit
{{profile.url}}

Sincerely,
{{portal_name}} team
***********************
Courriel : [noreply@canada.talent.ca](mailto:noreply@canada.talent.ca)
Objet : Votre opportunité {{opportunity.title}} numéro de confirmation est le {{opportunity.id}}

Bonjour {{requester.name}},

Merci pour votre soumission au {{portal_name}}. Nous avons reçu votre demande et le numéro de confirmation {{opportunity.id}} a été créé pour vous !

Pour voir le statut de l'opportunité, veuillez visiter
{{Profil URL}}

Sincèrement,
Équipe {{portal_name}}

**Comment by tristan-orourke** [comment]
If you're logged in as you submit a request, we could provide an in-app notification

**Comment by gobyrne** [comment]
Marc has already sent this to translation
