### ISSUE TITLE
❗[Notification] Application expired

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#9641]
## ✨ Purpose

Let applicant know that a poster for which they started a draft application has closed. This gives us the chance to explain that the deadline has passed and they will not get a chance to submit now.

## ❗ Trigger

Triggered by a cron job which regularly looks for recently closed jobs. Since our posters normally close at the same time of day, this could be run every 24 hours. Alternatively, we could possibly combine this with the check from #9640

## 👀 Audience

Users with an unsubmitted application for the now closed job poster will get this notification.

### Email templates (English and French)

Content of this notification if received as an email.

### In-app string (English and French)

How does this notification appear on the notifications page?

### Link

QUESTION: should this link to the user's list of applications on their dashboard?

## 💾 Content

- What Notification Family does this belong to? (see #9555)
- Personalized notification should include job poster id, application id and the job poster closing time.

## ✅ Acceptance Criteria

- [ ] Email template exists in GC Notify
- [ ] Notification class exists in Laravel
- [ ] Notification is triggered by appropriate event and send to appropriate users (including NOT any users who are ignoring this notification's Notification Family)
- [ ] Notification type added to schema
- [ ] Notification type rendered appropriately on frontend
- [ ] Tests?

## 🛑 Blockers

Issues which must be completed before this one.

```[tasklist]
### Blocked By
- [ ] ticket number
```

**Comment by marc-donofrio** [comment]
Email: noreply@canada.talent.ca
Subject: Opportunity {{opportunity.title}} has been closed

Hi {{requester.name}},

The opportunity - {{opportunity.title}} - has been closed.

The deadline for submission has passed and we are no longer taking submissions for this opportunity. Please visit the site again to see new opportunities when they are posted.

Sincerely,
{{portal_name}} Team
{{ContactUs.url}}
**********************
Courriel : noreply@canada.talent.ca
Objet : L’opportunité {{opportunity.title}} a été clôturée

Bonjour {{requester.name}},

L’opportunité - {{opportunity.title}} - a été clôturée.

La date limite de soumission est passée et nous n’acceptons plus de soumissions pour cette opportunité. Veuillez visiter à nouveau le site pour voir les nouvelles opportunités lorsqu’elles sont affichées.

Sincèrement,
{{portal_name}} Équipe
{{ContactUs.url}}

**Comment by tristan-orourke** [comment]
More context: "The opportunity - {{title}} - **on the GC Digital Talent** platform has been closed."

One of the first sentences of each of our emails should mention the platform name.
1. positioning sentence
2. action sentence

**Comment by tristan-orourke** [comment]
Move to "the GC Talent platform"

**Comment by gobyrne** [comment]
We already let the know the deadline is approaching. We don't need to pub them to tell them about something they have lost access to. If they go looking for it, they will find it expired on the site.

Marc agrees with Gray
