### ISSUE TITLE
❗[Notification] Application Status Changed

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#9642]
## ✨ Purpose

Inform applicants of changes to their application status.

## ❗ Trigger

Final decision or removed recorded by pool operator. 
Reverting included

## 👀 Audience

Only the applicant themselves should receive a notification. 

### Email templates (English and French)

**EN Email Subject** 
 
GC Digital Talent application status updated 

**EN Email body** 

Hey {{user.firstname}}, 

You applied to {{Job Title - links to advertisement}} on GC Digital Talent. We want to let you know that there’s an update to your status. To view the new status, {{visit your profile } {link: track application section of dashboard}}. 

_Email footer_

**FR Email Subject** 
Mise à jour de l’état d’avancement de votre demande sur Talents numériques du GC

**FR Email body** 
Vous avez postulé à [____](url) sur Talents numériques du GC. L’état d’avancement de votre demande a été modifié. Pour voir son nouvel état, veuillez [consulter votre profil](url).

_Email footer_

### In-app string (English and French)

EN In-app Notification copy:  

The status of your application for {{opportunity.title I profile-dashboard}} has been updated. 

EN In-app Notification copy:  
L’état d’avancement de votre demande pour {{opportunity.title}} a été mis à jour.

### Link

Link to the Track your applications page (dashbaord)

## 💾 Content

- What Notification Family does this belong to? (see #9555)

## ✅ Acceptance Criteria

- [ ] Email templates exists in GC Notify
- [ ] Notification classes exists in Laravel
- [ ] Notification is triggered by appropriate event and send to appropriate users (including NOT any users who are ignoring this notification's Notification Family)
- [ ] Notification type(s) added to schema
- [ ] Notification type(s) rendered appropriately on frontend
- [ ] Tests?
- [ ] Remove existing experimental status notification

## 🛑 Blockers

Issues which must be completed before this one.

```[tasklist]
### Blocked By
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/9640
```

**Comment by marc-donofrio** [comment]
Email: [noreply@canada.talent.ca](mailto:noreply@canada.talent.ca)
Subject: Opportunity {{opportunity.title}} status changed to {{status.title}}

Hi {{requester.name}},

The status for the opportunity - {{opportunity.title}} - has been updated to {{status.title}}.

If you have questions regarding this change, please contact us using the link in our signature to submit a ticket to request more details.

Sincerely,
{{portal_name}} Team
{{ContactUs.url}}

*******************
Courriel : [noreply@canada.talent.ca](mailto:noreply@canada.talent.ca)
Objet : Modification du statut pour l’opportunité {{opportunity.title}} à {{status.title}}

Bonjour {{requester.name}},

Le statut de l’opportunité - {{opportunity.title}} - a été mis à jour à {{status.title}}.

Si vous avez des questions concernant ce changement, veuillez nous contacter en utilisant le lien dans notre signature pour soumettre un billet afin de demander plus de détails.

Sincèrement,
{{portal_name}} Équipe
{{ContactUs.url}}

**Comment by tristan-orourke** [comment]
@marc-donofrio Thinking further, I think we should consider this to be multiple notifications from the user's perspective, depending on what the status is being changed to:

- Confirmation of application submission
- Application has been screened out (disqualified)
- Application has been screened in (qualified)
- Application has been removed (with specific reason - see #9198)
- Application has led to a placement (Tentative, Casual, Term or Indeterminate)
- Application has expired 

Also, there was a suggestion that we need to be careful of how much we say in an email - some of these (or all of them?) should tell the user to sign in to the app for more details (for example, not saying in the email that they've been disqualified).

**Comment by gobyrne** [comment]
@marc-donofrio is sending to translation
