### ISSUE TITLE
♻️ Consolidate and simplify the chip component

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#9651]
## ✨ Summary

[Visit the Figma file](https://www.figma.com/file/guHeIIh8dqFVCks310Wv0G/Style-library?type=design&node-id=5-14&mode=design) • Contact @substrae with design questions

The app currently has too many variations of the `Chip` / `Pill` component, only some of which actually match designs provided in the style library. The goal of this ticket is to consolidate the existing `Chip` and `Pill` components into a single `Chip` component, bring the styles inline with Figma, and address how and when to use each of the two styles.

There should only be 2 different styles of chip:
* The standard chip, which has color variations, an optional icon on the left, and an optional dismiss button on the right
* The `Combobox` specific chip, which has a single color option, no icon on the left, and always has a dismiss button on the right

For all intents and purposes, the standard chip should be what we use in every instance except for the `Combobox`. 

There are also issues with our use of chips in certain locations that don't warrant them (see tables), however that is out of scope for this ticket.

```[tasklist]
### ✅ Requirements
- [ ] Consolidate the existing `Chip` and `Pill` components into `Chip`
- [ ] Retain the separation between the standard `Chip` and the `Combobox` selection blocks
- [ ] Ensure the standard `Chip` has the correct color variations
- [ ] Ensure the standard `Chip` has the correct padding and gap values (`x.5, x.15`, `x.25` respectively)
- [ ] Ensure the standard `Chip` has an optional icon that is colored and sized properly (`x.5`)
- [ ] Ensure the standard `Chip` has an optional dismiss button that is colored and sized properly (`x.5`) and uses the `x-circle` mini Heroicon
- [ ] Ensure the icon alignment is centered with the text
- [ ] Ensure that dismissable chips have the correct `hover` and `focus-visible` effects
- [ ] Ensure the standard `Chip`'s text is bolded
- [ ] Triple check dark mode
- [ ] Triple check the IAP theme
```

##  🔍 Details

<details>
  <summary>📸 Chips (light mode)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/822e2cda-d3e9-43c1-9633-ce982a73f747" />
</details> 

<details>
  <summary>📸 Chips (dark mode)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/884b9e02-e4be-455d-828d-5b64fba25ac2" />
</details>

**Comment by esizer** [comment]
While working on this, I thought of an idea to work on in the future and wanted to record it before I forget.

I was testing the focus styles and realized I would really like arrow key navigation and a focus loop. Everything I got to the end I wanted to loop back but the only way is back stepping.

Also, right now, each chip acts as a tab stop and it would be really nice to skip past it with a single tab press 😅 

We already have a similar working example in the board component:

https://github.com/GCTC-NTGC/gc-digital-talent/blob/809b09c1cb433f3a70932ca263d09932772a551d/packages/ui/src/components/Board/Board.tsx#L149-L170
