### ISSUE TITLE
🐛 Remove parentheses around skill accordion subtitle

### ISSUE THREAD

**Issue by vd1992** [GCTC-NTGC/gc-digital-talent#9657]
## 🐛 Bug 

Remove them

## 📋 Steps to Reproduce

Seen at `http://localhost:8000/en/browse/pools/:id#skill-requirements`

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/5eae5eaa-0908-40bf-9b79-ed11247b8501)

## ✅ Acceptance Criteria

- [ ] Removed them

**Comment by tristan-orourke** [comment]
Closing in favour of duplicate #9672
