### ISSUE TITLE
🐛 Bilingual evaluation showing for monolingual profiles

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#9675]
## 🐛 Bug

The display value for bilingual evaluation still appears after selecting a monolingual option.

## 🦋 Expected Behaviour

When selecting a monolingual language option, no bilingual fields should be displayed on the profile.

## 🕵️ Details

I think this only happens when you first have "bilingual" selected and then switch it back to a monolingual option. I assume we are just not nulling out the database value or the conditional check is not strict enough.

## 📋 Steps to Reproduce

1. Login as an application
2. Naigate to the personal information page
3. Edit the language information
4. Select "bilingual" as an option
5. Save
6. Edit again, switching back to a monolingual option
7. Save
8. Observe the bilingual evaluation still appears

## 📸 Screenshot

![Screenshot 2024-03-07 084901](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/3cb34167-4504-4935-a4b6-ce1b396b2f5f)

## 🙋‍♀️ Proposed Solution

- Ensure we are properly nulling the database when unsetting the field.
- Ensure the conditional is strict enough

## ✅ Acceptance Criteria

- [ ] Bilingual evaluation does not appear unless the use has selected a bilingual option

**Comment by tristan-orourke** [comment]
Probably fixed by #8031
