### ISSUE TITLE
🔤 Consolidate "Education Requirement" french copy

### ISSUE THREAD

**Issue by yonikid15** [GCTC-NTGC/gc-digital-talent#9679]
## 🔤 Copy

There's currently two different french translations for **"Education Requirement"**. We need to use _[Exigence d’études](https://github.com/GCTC-NTGC/gc-digital-talent/issues/9679#issuecomment-2000173551)_ in French.

## ✅ Acceptance Criteria

- [ ] Replace all instances of other french copy with "Exigence d’études".
- [ ] If possible, add the message to one of the message files that fits the best and get the message from there.

**Comment by mnigh** [comment]
> There's currently two different french translations for **"Education Requirement"**. We need to pick one and stick with that.
> 
> * [ ]  "Exigence d’études"
> 
> OR
> 
> * [ ]  "Exigences pédagogiques"

@gobyrne do you have a preference?

**Comment by gobyrne** [comment]
"Exigence d’études" please (I asked recruitment team)
