### ISSUE TITLE
Add synchronous Server-Side Pool Candidate Word download

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#9688]
## ✨ Feature

Let's make our server-side Pool Candidate Word report usable, but generated synchronously for now.

## ✅ Acceptance Criteria

- [ ] Client can request the report from the UI
- [ ] client-side file generation removed
- [ ] Check that user is authorized to see data (fully guarded, auth, policies, etc)
- [ ] Generate file in-request and respond with file directly (synchronous)

## 🛑 Blockers

```[tasklist]
### Blocked By
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/9686
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/10634
```

**Comment by petertgiles** [comment]
Need to make a decision: is this actually an easy in-between step if we have to fiddle with server settings to allow it to complete?

**Comment by brindasasi** [comment]
Decision is to go with async download for both word & csv. We'll skip this.

**Comment by tristan-orourke** [comment]
We'll skip making a synchronous download and jump right to #9692
