### ISSUE TITLE
Add synchronous Server-Side Pool Candidate CSV download

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#9690]
## ✨ Feature

Let's make our server-side Pool Candidate CSV report usable, but generated synchronously for now.

## Recommended Solution

CSV generation has already been handled in https://github.com/GCTC-NTGC/gc-digital-talent/pull/9988.
Now we just to download the file from a rest endpoint.

## ✅ Acceptance Criteria

- [ ] Double check CSV generation to make sure it still matches javascript version, which may have changed
- [ ] Client can request the report from the UI
- [ ] Request for API should be a separate REST end point not the graphql 
- [ ] client-side file generation removed
- [ ] Check that user is authorized to see data (fully guarded, auth, policies, etc)
- [ ] Generate file in-request and respond with file directly (synchronous)

## 🛑 Blockers

```[tasklist]
### Blocked By
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/9687
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/10634
```

**Comment by brindasasi** [comment]
@petertgiles 
so we have this async download implementation [#9693](https://github.com/GCTC-NTGC/gc-digital-talent/issues/9693) 
we should be able to leverage that in here. Should we change A/C on that? 
Is there anything I'm missing on that?

**Comment by petertgiles** [comment]
#9693 is the async version while this issue is the sync version.  The sync version should be easier to implement so I have it as a first step and a blocker for the async version.

**Comment by petertgiles** [comment]
The spike with a file download: https://github.com/GCTC-NTGC/gc-digital-talent/issues/9685

**Comment by brindasasi** [comment]
@petertgiles is there anything else blocking on this to implement?

**Comment by petertgiles** [comment]
I think that for the Word document we decided to skip the "sync" step and jump right to "async".  This issue can probably be closed.
