### ISSUE TITLE
✨ Make Pool Candidate Word download async

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#9692]
## ✨ Feature

Let's convert the synchronous server-side generated PDF report to be run off-request asynchronously.

## 🙋‍♀️ Proposed Implementation

https://github.com/GCTC-NTGC/gc-digital-talent/pull/9606
https://github.com/GCTC-NTGC/gc-digital-talent/pull/8757

## ✅ Acceptance Criteria

- [ ] Client can request a report to be generated, and they are told to wait for completion
- [ ] Server executes the query and generates the report in an asynchronous worker
- [ ] Client is notified the report is ready with an in-app notification
- [ ] Client is notified if the report generation failed with an in-app notification
- [ ] Client can download the file from the server
- [ ] Only the user who requested the report can download the file (or use signed, sharable links?)
- [ ] generated file should be localized 
- [ ] A scheduled job running overnight deletes any files over 24 hours old
- [ ] Toast message while processing the download: "Preparing your file for download. You will receive a notification when it is ready."
- [ ] Success Notification: "`Your file is ready for download: <file name>`."
- [ ] Failure Notification: "`There was a problem on our end. <filename> failed to download. If you continue to receive this error, please get in touch with our support team`."
- [ ] File should be available for 24 hours for download.
- [ ] Clean up will be happening every night and will clean the files more than 24 hours old.

## 🛑 Blockers

```[tasklist]
### Blocked By
- [ ] #9688
- [ ] #9685
- [ ] #9684
- [ ] #10634
- [ ] #9693
```

**Comment by brindasasi** [comment]
@petertgiles can we do subscriber model for this report generation event to display the notification banner?

**Comment by petertgiles** [comment]
Subscriptions could be a cool way to implement this so we don't have to poll for notifications though we've never done them before.  We have a spike on the board to explore this sometime.
[#8760](https://github.com/GCTC-NTGC/gc-digital-talent/issues/8760)

**Comment by mnigh** [comment]
https://github.com/GCTC-NTGC/gc-digital-talent/issues/9693 is still listed as a blocker in this issue's description. should the [blocked: dependencies](https://github.com/GCTC-NTGC/gc-digital-talent/labels/blocked%3A%20dependencies) label be applied to this issue?

**Comment by esizer** [comment]
> #9693 is still listed as a blocker in this issue's description. should the [blocked: dependencies](https://github.com/GCTC-NTGC/gc-digital-talent/labels/blocked%3A%20dependencies) label be applied to this issue?

Yeah, I think we should keep this blocked ont hat ticket. There is a lot of overlap and I am trying my best to make the solutution there extensible so we can reuse it for a bhnc of different files so waiting on that will make this easier. i.e

We have a file generator class that provides some nice helpers and requires some methods to be implemented. 

https://github.com/GCTC-NTGC/gc-digital-talent/blob/9693-async-candidate-csv/api/app/Generators/FileGenerator.php

As well, the event/listener/noticcation are all generic thing that only take a file name. So waiting for that to get merged in first would make sense.

https://github.com/GCTC-NTGC/gc-digital-talent/blob/9693-async-candidate-csv/api/app/Events/UserFileGenerated.php

**Comment by tristan-orourke** [comment]
Maybe the route prefix match should just be `/api/`
