### ISSUE TITLE
♻️ Consolidate lang files

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#9702]
## ♻️ Debt/Refactor

Goal is to consolidate all of the files in `packages/i18n/src/lang` and `apps/web/src/lang` to have one source of truth.

## 🕵️ Details

I don't think there is any need to keep these files separate. The initial thought was to separate re-usable messages that are needed for packages. However, I'm not sure the pros  (if any) outweight the cons. If we do this we will have some benefits in easing the workflow at bit:

- One source of truth for lang (`/packages/i18n/src/lang`)
- No more need to run check twice, we could just do `npm run check-intl`
- Easier testing (we are merging files to check for duplicates right now)

## 🙋‍♀️ Proposed Solution

Update the `i18n` package to scan both itself and `apps/web` for extraction. Then, update anywhere we import messages to use the new single source of truth.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] `apps/web/src/lang` removed
- [ ] Intl based commands removed from `apps/web`
- [ ] Single source of truth for messages
- [ ] References to `apps/web/src/lang` removed

**Comment by tristan-orourke** [comment]
Sounds like this isn't necessary for now
