### ISSUE TITLE
🔧 Make slow query logging easier to parse

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#9704]
## ♻️ Debt/Refactor

We now have slow query logging but it is difficult to parse for analysis.

```php
 $this->logger->info(
                'Slow query',
                [
                    'request' => $request->json()->all(),
                    'elapsed_seconds' => $elapsedSeconds,
                ]
            );
```

1. The request dump spans many lines.
2. The elapsed seconds is at the very end, several lines later.

## 🙋‍♀️ Proposed Solution

Log it as a single line with the elapsed_seconds before the dump.  Let's also pull out the operation name.  Can we get referring URL in the request, too?

```
Slow query, 9.7, ViewPoolPage, https://talent.canada.ca/pools/123-456, query ViewPool Page \n { query with newlines removed \n } \n
```

## ✅ Acceptance Criteria

- [ ] Middleware and triggers logging the same way
- [ ] elapsed seconds moved before request dump
- [ ] operation name extracted and moved before request dump
- [ ] referring url logged before request dump (if possible)
- [ ] request dump has newlines escaped so that it is logged on a single line
- [ ] request dump is the last item on the line

**Comment by tristan-orourke** [comment]
referrer url: `request()->headers->get('referer');`
