### ISSUE TITLE
🔧 Make admin audit logging easier to parse

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#9705]
## ♻️ Debt/Refactor

Our admin audit logging is difficult to parse for analysis.

```php
        if (! is_null($user) && $user->hasRole('platform_admin')) {
            $message = 'GraphQL request from platform admin user ['.$user['email'].']';
            $this->logger->info(
                $message,
                $request->json()->all()
            );
        }
```

1. The request dump spans many lines.
2. The user email is not separated by delimiters on both sides

## 🙋‍♀️ Proposed Solution

Log it as a single line with the email delimited out.  Can we get referring URL in the request, too?

```
Admin request, user@example.org, https://talent.canada.ca/pools/123-456, query ViewPool Page \n { query with newlines removed \n } \n
```

## ✅ Acceptance Criteria

- [ ] Middleware and triggers logging the same way
- [ ] email delimited by commas
- [ ] referring url logged before request dump (if possible)
- [ ] request dump has newlines escaped so that it is logged on a single line
- [ ] request dump is the last item on the line

**Comment by brindasasi** [comment]
@petertgiles  do you want to see 

> Admin request ,

instead of 

> GraphQL request from platform admin user ?

Admin user sounds more generic than platform admin user. 
Only platform admin operations are logged under this query rt ?

**Comment by petertgiles** [comment]
> @petertgiles do you want to see

I'm not picky, as long as it's a static token that can be queried for.  I thought we could shorten it a bit from what's there but you can use whatever you think is best.

**Comment by brindasasi** [comment]
Does it look good with referer url?  Should I remove 'referer:' ? 
```php
[2024-03-18 19:41:49] local.INFO: Request from platform admin, admin@test.com, referer: http://localhost:8000/en/admin/dashboard, {"operationName":"AdminDashboard_Query","query":"query AdminDashboard_Query {\n  me {\n    id\n    firstName\n    lastName\n    __typename\n  }\n}","variables":[]}
```

**Comment by petertgiles** [comment]
> Does it look good with referer url? Should I remove 'referer:' ?

Very nice!  Yeah, please remove the "referer: " string.
