### ISSUE TITLE
♻️ `fakeGenericJobTitles.ts` not used within other modules

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#9707]
## ♻️ Debt

`fakeGenericJobTitles.ts` not used within other modules.

## 🙋‍♀️ Proposed Solution

Delete `packages/fake-data/src/fakeGenericJobTitles.ts` file.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] `packages/fake-data/src/fakeGenericJobTitles.ts` file is not referenced and does not exist in the codebase

**Comment by esizer** [comment]
I have always been confused by generic job titles. I see code for it pop up all the time but have never actually directly interacted with it. Was it just deprecated and never removed? 🤔
