### ISSUE TITLE
♻️ Replace the `pools` query with a `poolsPaginated` query

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#9718]
## ♻️ Debt/Refactor

We have a lot of pools at this point, and the number will continue to grow. We should deprecate the `pools` query and replace it with a paginated version. 

The client should switch to using the paginated version under the hood, but this change should be invisible to users.

## 🕵️ Details

Note: `publishedPools` query will remain non-paginated for now.

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] `pools` query deprecated and not used anywhere client-side
- [ ] use of `pools` query replaced with a `poolsPaginated` query

## 🛑 Blockers

Issues which must be completed before this one.

```[tasklist]
### Blocked By
```

**Comment by esizer** [comment]
Something to note is that we use this query for filters. I'd suggest whoever works on this refers to the user input in the [`AddTeamMemberDialog`](https://github.com/GCTC-NTGC/gc-digital-talent/blob/main/apps/web/src/pages/Teams/TeamMembersPage/components/AddTeamMemberDialog.tsx)
