### ISSUE TITLE
♻️ Make deploy artifact smaller

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#9726]
## ♻️ Debt/Refactor

Right now our Azure Pipelines deployment script simply installs dependencies, builds the app, then zips the entire working directory.  This results in artifacts larger than 700 MB and many useless files being shipped around during deployment.  We probably need only the api directory, the apps/web/dist directory, the tc-report, and a few config files for post-deploy.

https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/archive-files-v2?view=azure-pipelines

## 🙋‍♀️ Proposed Solution

- If the azure pipelines doesnt support glob patterns I guess in deploy.sh we could copy all the files to a one folder and just ZIP that folder instead of the working dir.
- Multiple zip steps and multiple artifacts?
- https://github.com/MicrosoftDocs/azure-devops-docs/issues/1213#issuecomment-998679799

## ✅ Acceptance Criteria

- [ ] Azure pipelines only adds needed files to the artifact.

**Comment by mnigh** [comment]
> ## ♻️ Debt/Refactor
> Right now our Azure Pipelines deployment script simply installs dependencies, builds the app, then zips the entire working directory. This results in artifacts larger than 700 MB and many useless files being shipped around during deployment. We probably need only the api directory, the apps/web/dist directory, the tc-report, and a few config files for post-deploy.
> 
> https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/archive-files-v2?view=azure-pipelines
> 
> ## 🙋‍♀️ Proposed Solution
> * If the azure pipelines doesnt support glob patterns I guess in deploy.sh we could copy all the files to a one folder and just ZIP that folder instead of the working dir.

Possibly does support glob patterns? REF: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=azure-devops
