### ISSUE TITLE
🐛 Screening decision dialog does not hide skill accordion if info does not exist

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#9730]
## 🐛 Bug

When screening a user, in the event that the skill they are assessing does not contain a description, the accordion appears but is empty.

## 🦋 Expected Behaviour

When a skill does not have a description, we should show a null message or hide this entirely. 

## 📋 Steps to Reproduce

1. Find or create a skill with no description
2. Create an assessment for that skill
3. Create an applicant to assess for that step/skill
4. Open the screening dialog for that skill
5. Confirm the well and accordion appear empty

## 📸 Screenshot

![Screenshot 2024-03-13 084303](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/996c97c0-4eda-4d2d-9527-cf7be070700b)

## 🙋‍♀️ Proposed Solution

1. Show a null state instead of hiding the contents
2. Hide entire section

## ✅ Acceptance Criteria

- [ ] Empty skill in screening dialog has a null message or
- [ ] Is hidden entirely

**Comment by vd1992** [comment]
Not sure about this issue, description is not optional, so aside from erroneous seeding this should not occur

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/f45262b7-c175-4b99-89d1-58c7ba1c1985)

But that is irrelevant. the dialog in question doesn't appear to be skill related to begin with though, that is the education review

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/b2b183fd-57a4-41b4-abc5-53d36f75a7d8)

**Comment by esizer** [comment]
> Not sure about this issue, description is not optional, so aside from erroneous seeding this should not occur

That is weird! I totally have seen empty descriptions on prod 🤔
