### ISSUE TITLE
🐛 Email validation gap on support page

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#9733]
## 🐛 Bug

It is possible to enter an email address that will pass frontend validation but fail backend validation.  Unfortunately, the error message is very vague when this happens.

## 🦋 Expected Behaviour

Option 1 is just improve the error message so that the user knows what went wrong and can try to correct it.  We can't control Laravel's or different browser's email address validation.

Option 2 is that we could consider removing all validation on the email field.  It could be argued that the support form is too important to allow to fail or that users may want to intentionally obfuscate their email address in a way that a human might be able to interpret.

## 📋 Steps to Reproduce

The example I found in the server logs was `validemail*temp*@gmail.com` in Chrome, as shown in the screenshot.

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/e8168b7e-0c91-4513-b6d7-f319e4b877de)

## ✅ Acceptance Criteria

- [ ] Improve backend validation error toast
- [ ] Respond with a 400 error response, not 500, if that's what we get from api

**Comment by mnigh** [comment]
I think this is actually related to email validation on [Freshdesk's API](https://developers.freshdesk.com/api/#create_ticket:~:text=email%20%E2%80%A0-,string,-Email%20address%20of) which accepts a `string` but doesn't mention any of the validation rules behind the scenes for creating a contact.

For example, this is the error that comes back using with `validemail*temp*@gmail.com` in the email field:

```json
{"field":"email","message":"It should be in the 'valid email address' format","code":"invalid_value"}
```

 `invalid_value`

> This code indicates that a request contained an incorrect or blank value, or was in an invalid format.

REF: https://developers.freshdesk.com/api/#create_contact:~:text=in%20this%20error.-,invalid_value,-This%20code%20indicates

## Conclusion
Although the * character is valid for the local-part of an email address, my guess is Freshdesk has email validation that flags anything with the * character as an invalid email address. We don't actually know what Freshdesk's email validation rules are, so adding something to the toast that is returned wouldn't be helpful (for example, "Sorry, you _might_ have entered an invalid email address according to Freshdesk's faulty validation" 😉). We could open a ticket with Freshdesk, though [don't hold your breath on a fix](https://community.freshworks.com/archives-freshdesk-11421/email-validation-fails-for-internationalised-email-18609).

**Comment by mnigh** [comment]
> > For example, this is the error that comes back using with `validemail*temp*@gmail.com` in the email field:
> 
> Oh, you're right! That's exactly the error message that is logged in the server. Since that's a layer of validation that we can't remove I guess we have to go with a better error message option.

What would the better error message be though?

**Comment by petertgiles** [comment]
> What would the better error message be though?

Keep it simple.  "Invalid email address.  Try again or send an email to ...."

**Comment by mnigh** [comment]
> > What would the better error message be though?
> 
> Keep it simple. "Invalid email address. Try again or send an email to ...."

If they try again, it will be the same result: failure. I've sent an email to Freshdesk asking to alter their conditions for valid email addresses. Who knows, maybe they will do listen 🤷.

**Comment by mnigh** [comment]
Good news! I heard back from Freshdesk support and they mentioned they use a service called verifalia to verify email addresses. They sent a link to https://verifalia.com/validate-email. I entered `validemail*temp*@gmail.com` and it's not being blocked because it's a malformed email address but...because it's the mailbox for the email address does not exist!

So, I think we should just close this issue as we can't help folks who are entered mailboxes that are fake!

## Screenshot
<img width="754" alt="Screen Shot 2024-03-15 at 11 08 58" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/668a8a74-ec79-4769-9ca4-c304823a2c7b">

**Comment by vd1992** [comment]
500 is the response

The response contents is very simple though

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/1161d234-33c7-4276-8cea-a5326ea12b6a)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/35252df0-073e-45dd-b495-bcc49e17f710)
