### ISSUE TITLE
♻️ Bump storybook to v8

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#9752]
## ♻️ Debt/Refactor

Bump storybook to its latest major version (8).

## 🙋‍♀️ Proposed Solution

Update all `package.json` files to use the latest version of storybook and follow [the guide](https://storybook.js.org/docs/migration-guide?ref=storybookblog.ghost.io) to fix any breaking changes.

## ✅ Acceptance Criteria

- [ ] All storybook deps are on `^8.0.0`
- [ ] Storybook and chromatic still build successfully
- [ ] Works with `storybook-react-intl`

**Comment by mnigh** [comment]
Blocked by addon `storybook-addon-intl` incompatibility with v8: https://github.com/truffls/storybook-addon-intl/issues/184

**Comment by floriangosse** [comment]
A new version of `storybook-addon-intl` is currently in the development. Unfortunately, the is a blocker for this release as well. You can read about it here: https://github.com/truffls/storybook-addon-intl/issues/184#issuecomment-2012024102

As soon as the new of the addon is published I will post an update.

**Comment by floriangosse** [comment]
storybook-addon-intl@4 was just released: https://github.com/truffls/storybook-addon-intl/releases/tag/v4.0.0
