### ISSUE TITLE
🐛 Null state on Assessment Step title shouldn't be shows as 'N/A' on the assessment screening dialog

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#9758]
## 🐛 Bug

On the Assessment step, title is optional field. But when we omit it, it shows as N/A on assessment screening dialog. 
![Screenshot 2024-03-14 154038](https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/003aa722-474c-4957-add6-8eccdd147664)
![Screenshot 2024-03-14 145950](https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/a6b3d025-c381-4a85-9ba4-f6c81dcf90a0)

This particular issue was requested by recruitment team during UAT.

## 🦋 Expected Behaviour

Do not add "N/A" on the title of a dialog. Just omit it if it is not available to show. 
## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Name and version (if possible).
- **Browser**: Name and version (if possible).

## 📋 Steps to Reproduce

1. Create any Assessment Step without Title for any pool
2. Go to Assessment Screening Dialog for that pool

## 📸 Screenshot

Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Do not add "N/A" on the title of a dialog. Just omit it if it is not available to show. 
- [ ] Update assessment title labels for consistency to `Assessment title (English)` and `Assessment title (French)`

**Comment by vd1992** [comment]
Should probably be a quick fix of using this util function

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/f3ccf0f3-0508-4077-b43e-4cf7fcfb6598)

**Comment by tristan-orourke** [comment]
@Jerryescandon we want to update the label for the Assessment title input to be consistent with our other forms -  do you want to update figma?
