### ISSUE TITLE
🐛 Applicant can't review his own old application that was before submitted steps are implemented

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#9760]
## 🐛 Bug

When submitted steps are empty , those applications are throwing errors while reviewing it
I think these applications are submitted before assessment steps are implemented. 
![Screenshot 2024-03-14 141639](https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/790cc326-c976-42c3-a1ed-9868d02a6c7d)

When I click on the Let's go button , I get the below  error

![Screenshot 2024-03-14 141717](https://github.com/GCTC-NTGC/gc-digital-talent/assets/89482910/5b9c6bae-1f95-4a54-90eb-b9be6fcaf7df)
## 🦋 Expected Behaviour

What should be happening?

## 🕵️ Details

Add any additional details that could assist with troubleshooting/fixing the issue.

- **Operating System**: Name and version (if possible).
- **Browser**: Name and version (if possible).

## 📋 Steps to Reproduce

1. Submitted steps should be empty for this error to happen

## 📸 Screenshot

Add a screenshot (if possible).

## 🙋‍♀️ Proposed Solution

(optional) Do you have a proposed solution?

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] In this case , Application Summary page should be displayed instead of the stepper

**Comment by gobyrne** [comment]
Definitely a bug, but becomes less and less a problem as time goes on. We haven't got specific complaints, so not intending to fix for now.
