### ISSUE TITLE
✨ Convert "Other reason" text area to "Decision notes" and make it conditionally required for all actions

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#9790]
## ✨ Feature

Julie has been using the RoD feature, she likes the "other reason" notes field but wishes it could also be available during the other justification selections NOT JUST the "other reason..." selection.

It would be simpler if this field was just renamed to "Decision notes" and have it appear by default regardless of the type of decision (Demonstrated, Not demonstrated, etc...)

Have the field be OPTIONAL:
- If the decision is "Demonstrated"
- If the decision is "Not demonstrated (Disqualified)" AND the justification one or both of:
   - "Not sufficiently demonstrated to meet the requirement."
   - "Not enough information provided."

Have the field be REQUIRED:
- If the decision is "Not demonstrated (Disqualified)" AND the justification includes:
   - "Other reason for screening out." (even if other justifications are selected)
- If the decision is "Not demonstrated (Hold for further assessment)"

This change should apply to all type of assessments. Application, screening questions, generic assessment, etc.

## 🕵️ Details

Add any additional details that could assist with the development of the new feature.

## 🎨 Design File

Design file by @Jerryescandon 

### CURRENT

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/29931a50-6445-4393-9073-079f4f5f59b9)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/bc1d3212-1b1b-4a43-81e7-54a4da61c022)

### PROPOSED

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/747917af-3ef4-4ecb-b1b4-1f0dd6b11ac0)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] "Other reason" text area renamed to "Decision notes"
- [ ] Decision notes text area is always available in this modal
- [ ] Decision notes is conditionally required based on logic above

**Comment by yonikid15** [comment]
This is replaced with #9900
