### ISSUE TITLE
♻️ Unreferenced variables, unreferenced or redundant css selectors

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#9798]
## ♻️ Debt

There is code that is legacy and not referenced by the application or is redundant. 

## 🕵️ Details

1. There are no references in the codebase to css classes for `content-inner` or `dashboard`.
https://github.com/GCTC-NTGC/gc-digital-talent/blob/5dcaa7363b4f7c432d3078c558cbea15e878d720/apps/web/src/assets/css/app.css#L49-L55

2. This selector is redundant since it is already applied. The `className` attribute can also be removed.
https://github.com/GCTC-NTGC/gc-digital-talent/blob/5dcaa7363b4f7c432d3078c558cbea15e878d720/apps/web/src/assets/css/app.css#L44-L47
https://github.com/GCTC-NTGC/gc-digital-talent/blob/5dcaa7363b4f7c432d3078c558cbea15e878d720/apps/web/src/components/Layout/Layout.tsx#L125-L127
https://github.com/GCTC-NTGC/gc-digital-talent/blob/5dcaa7363b4f7c432d3078c558cbea15e878d720/apps/web/src/components/Layout/IAPLayout.tsx#L81-L83

3. The class` footer` never has any styles applied.
https://github.com/GCTC-NTGC/gc-digital-talent/blob/5dcaa7363b4f7c432d3078c558cbea15e878d720/apps/web/src/components/Footer/Footer.tsx#L74

4. The class` indigenous-community-image` never has any styles applied.
https://github.com/GCTC-NTGC/gc-digital-talent/blob/5dcaa7363b4f7c432d3078c558cbea15e878d720/apps/web/src/components/Profile/components/DiversityEquityInclusion/CommunityIcon.tsx#L29
https://github.com/GCTC-NTGC/gc-digital-talent/blob/5dcaa7363b4f7c432d3078c558cbea15e878d720/apps/web/src/components/UserProfile/ProfileSections/DiversityEquityInclusionSection.tsx#L147
https://github.com/GCTC-NTGC/gc-digital-talent/blob/5dcaa7363b4f7c432d3078c558cbea15e878d720/apps/web/src/components/UserProfile/ProfileSections/DiversityEquityInclusionSection.tsx#L157
https://github.com/GCTC-NTGC/gc-digital-talent/blob/5dcaa7363b4f7c432d3078c558cbea15e878d720/apps/web/src/components/UserProfile/ProfileSections/DiversityEquityInclusionSection.tsx#L167
https://github.com/GCTC-NTGC/gc-digital-talent/blob/5dcaa7363b4f7c432d3078c558cbea15e878d720/apps/web/src/components/UserProfile/ProfileSections/DiversityEquityInclusionSection.tsx#L177

5. The class `experience-category` never has any styles applied.
https://github.com/GCTC-NTGC/gc-digital-talent/blob/5dcaa7363b4f7c432d3078c558cbea15e878d720/apps/web/src/components/UserProfile/ExperienceByTypeListing.tsx#L37

6. The class `Input--Checkbox` never has any styles applied.
https://github.com/GCTC-NTGC/gc-digital-talent/blob/5dcaa7363b4f7c432d3078c558cbea15e878d720/packages/forms/src/components/Checkbox/Checkbox.tsx#L80

7. The class `combo` never has any styles applied.
https://github.com/GCTC-NTGC/gc-digital-talent/blob/5dcaa7363b4f7c432d3078c558cbea15e878d720/packages/forms/src/components/Combobox/Multi.tsx#L220

7. The class `card`, `card__header`, `card__body` never have any styles applied.
https://github.com/GCTC-NTGC/gc-digital-talent/blob/5dcaa7363b4f7c432d3078c558cbea15e878d720/packages/ui/src/components/Card/Card.tsx#L67
https://github.com/GCTC-NTGC/gc-digital-talent/blob/5dcaa7363b4f7c432d3078c558cbea15e878d720/packages/ui/src/components/Card/Card.tsx#L77
https://github.com/GCTC-NTGC/gc-digital-talent/blob/5dcaa7363b4f7c432d3078c558cbea15e878d720/packages/ui/src/components/Card/Card.tsx#L92

8. `PoolTest_Query` not referenced anywhere.
https://github.com/GCTC-NTGC/gc-digital-talent/blob/5dcaa7363b4f7c432d3078c558cbea15e878d720/apps/e2e/cypress/e2e/api/artisan-commands.cy.ts#L139-L140

9. The `php-container` is not referenced anywhere (removed in #4871).
https://github.com/GCTC-NTGC/gc-digital-talent/blob/8e28f316ddb329ee1d354da3f0a2cca7a6ff3440/.github/dependabot.yml#L84-L89

## 🙋‍♀️ Proposed Solution

Get rid of them and anything they use that is only referenced by them.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt was addressed and expected functionality has not been affected.

- [ ] legacy code referenced removed

**Comment by petertgiles** [comment]
How did you find these?  Do you have a CSS linting tool that brought this up?

**Comment by mnigh** [comment]
> How did you find these? Do you have a CSS linting tool that brought this up?

No, just 🕵️ powers.
