### ISSUE TITLE
Pool Dashboard - Create table view for Pools, and connect to API

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#98]
Create a Table component which displays all columns of a list of Pools.

Write a client-side graphql operation which queries for all Pools, and create a wrapper component which runs the query and passes pools to the table component.

TODO: Decide which columns should be displayed on the table? For reference here are all the possible fields:
```
type Pool {
    id: ID!
    owner: User
    name: LocalizedString
    description: LocalizedString
    classifications: [Classification]
    assetCriteria: [CmoAsset]
    essentialCriteria: [CmoAsset]
    operationalRequirements: [OperationalRequirement]
    poolCandidates: [PoolCandidate]
}
```
Any type surrounded by [square brackets] represents a list, which we'd have to decide how to represent in a table cell.

**Comment by Jerryescandon** [comment]
Preemptively posting the prototype:
https://www.figma.com/proto/jOGqmmyq7mr3oVdiimiuPW/Pool-Manager?page-id=0%3A1&node-id=102%3A15&viewport=-784%2C285%2C0.4683002829551697&scaling=min-zoom

**Comment by jaysonmc** [comment]
Regarding: 
"TODO: Decide which columns should be displayed on the table? For reference here are all the possible fields:"

Today we discussed at standup and decided to implement initially with the fields identified [here](https://github.com/GCTC-NTGC/gc-digital-talent/issues/98#issuecomment-864263878). Run that by users, and if there is a need to filter extra columns, address at that point (as optionally displaying columns that are list values will required some further discussions / thinking).
