### ISSUE TITLE
🛠️ Dependabot not updating `pnpm-lock.yaml` with package updates

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#9847]
## 🛠️ Tooling

Since moving to pnpm, Dependabot is not updating the `pnpm-lock.yaml` file when a new package update PR is created.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the debt tooling was properly updated and remains functional.

- [ ] Dependabot updates `pnpm-lock.yaml` when new package update PR created

**Comment by vd1992** [comment]
Lets not link a PR to this until it truly is solved 😆

**Comment by esizer** [comment]
Going to send to the :ice_cube: :brown_square:  since it is kind of being passivley checked and there is no clear path forward. Also, we do plan to rollback if either us or dependabot can't figure this out.

 - https://github.com/GCTC-NTGC/gc-digital-talent/issues/9990

**Comment by mnigh** [comment]
Fixed in https://github.com/GCTC-NTGC/gc-digital-talent/pull/10085 (typos in dependencies).
