### ISSUE TITLE
Keep only "Decision notes" box on Generic assessment RoD

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#9852]
## Details

The "Notes for this assessment" textarea is no longer required in the generic assessment modal because in #9790 we made the "Decision notes" textarea always available and gave it some smart requirement logic.

Delete the "Notes for this assessment" text area from the generic assessment modal.

## Design

[Design file ](https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Admin---Processes%2FPools%2FRecruitments---Record-of-Decision?type=design&node-id=8738%3A32603&mode=design&t=UvdtFuhMYWPUDPox-1)by @Jerryescandon 

## Screenshot
![Image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/0e5837e7-9229-4eeb-8ef2-fcfc71e0d12f)

```[tasklist]
### Blockers
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/9790
```

## Acceptance criteria
- [ ] Delete/remove/destroy the "Notes for this assessment" textarea that appears at the top of the generic assessment modal.
- [ ] Migration to combine any notes into the "Decision notes" box discussed in #9790 so that no data is lost.

**Comment by yonikid15** [comment]
This is replaced with #9900
