### ISSUE TITLE
🐛 No filter for new "Community manager" role in "All users" table

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#9862]
## 🐛 Bug
On the All users page, the table allows us to filter by "Roles and permissions", but the new role "Community manager does not appear in the filters list. In addition, "Community manager" does not appear in the "Roles and permissions" column in the All users table.

## 🦋 Expected Behaviour

Community manager should be a filter on the All users table and show show up in the Roles and permissions column.

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/89344714-300e-470d-a76b-20b05163c2e9)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/52ea56b0-666d-4df3-93f4-1ea7c8e6ecbc)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the bug was addressed.

- [ ] Community manager added to filters on the All users table
- [ ] Community manager shows up in the Roles and permissions column of the All users table

**Comment by yonikid15** [comment]
I believe this is a simple fix if it's just a frontend issue. We just need to add it to the roles accessor logic.
https://github.com/GCTC-NTGC/gc-digital-talent/blob/8031-refactor-language-form/apps/web/src/pages/Users/IndexUserPage/components/utils.tsx#L27-L47

```jsx
export function rolesAccessor(
  roleAssignments: RoleAssignment[],
  intl: IntlShape,
): string | null {
  if (!roleAssignments) return null;

  const roles = roleAssignments.map((roleAssignment) => roleAssignment.role);
  const rolesFiltered = roles.filter(notEmpty);
  // custom selection of roles of note for table viewing, most likely kept in sync with options in the filter dialog
  const rolesToDisplay = rolesFiltered
    .filter(
      (role) =>
        role.name === ROLE_NAME.PlatformAdmin ||
        role.name === ROLE_NAME.PoolOperator ||
        role.name === ROLE_NAME.RequestResponder,
        // add here
    )
    .map((role) => getLocalizedName(role.displayName, intl));
  const uniqueRolesToDisplay = uniqueItems(rolesToDisplay);

  return uniqueRolesToDisplay.join(", ");
}
```
