### ISSUE TITLE
Close Early button on published Processes

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#9863]
## Feature
There is no way to close published processes immediately.

The only way to edit published processes is with the "Extend closing date" button. Technically, you can actually shorten date in the dialog opens, not just extend it - though that's a bit confusing and unintuitive. However, the earliest you can set the closing date to is "Today at midnight pacific time". 

We want the ability to close posters immediately. If only to fix mistakes.

## Details
Add a new option to the "Extend closing date" dialogue for "close immediately". Also prompt the user for a required justification and save it.

## Design 
[Design file](https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Admin---Processes%2FPools%2FRecruitments---Record-of-Decision?type=design&node-id=8738%3A33771&mode=design&t=UvdtFuhMYWPUDPox-1) by @Jerryescandon 

### Current dialogue
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/2494551/afbaeb77-d82e-4595-85b0-0c9a838af4cd)

### New dialogue

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/749f93c9-18e0-4f78-93fb-6c4e10c30692)

### New functionality
https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/515a0f80-aa5a-4fc6-a145-63c01bcc9c92

```[tasklist]
## Acceptance criteria
- [ ] Link on Process information tab changed from "Extend closing date" to "Change closing date".
- [ ] Extend closing date dialogue renamed to "Change closing date"
- [ ] Radio button added to "Change closing date" with 2 options (Extend closing date and Close immediately)
- [ ] Close immediately option Prompts user to add a required "Reason for closing". "Change closing date" option leaves the rest of the dialogue unchanged
- [ ] Button adjusts to radio button selection as well
- [ ] If close process immediately button is trigger, the process closing date is changed to the current time (or one minute in the past... whatever works best)
```

**Comment by mnigh** [comment]
> This message will be sent to any candidates who have already applied to this process.

@Jerryescandon

1. How would this message be sent to any candidates who have already applied to this process? Is the notification feature not still behind a feature flag and not available?
2. How would this message be sent to candidates who are currently filling out an application?

## Screenshot

<img width="813" alt="Screen Shot 2024-03-26 at 11 41 32" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/f2c7f632-64fa-4de0-b407-2d8d3e5ae1e6">

**Comment by Jerryescandon** [comment]
> 1. How would this message be sent to any candidates who have already applied to this process? Is the notification feature not still behind a feature flag and not available?
> 2. How would this message be sent to candidates who are currently filling out an application?
> 

This was very wishful thinking on my part. Ive chatted with Gray and we are going in the opposite direction instead.

NEW DESIGN

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/623131fa-7c81-4d6e-a961-d5c590fe3eb0)
