### ISSUE TITLE
✨ Add link to Skills page from admin side

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#9880]
## ✨ Feature

Recruitment team works everyday with the skills list, we want to make it easy for them to find the new public version of the skills table since the one on admin should be restricted to roles that can edit the skills data.

## 🕵️ Details

Add a new item to the main navigation on Admin side.

Link should open the skills page at:
`https://talent.canada.ca/en/skills`

Add a new item on Admin dashboard landing page

EN: Skills list
FR: Liste de compétences

Update the old link with a new icon and this text:
EN: Skills editor
FR: Éditeur de compétences

## 🎨 Design File

[Design file](https://www.figma.com/file/guHeIIh8dqFVCks310Wv0G/Style-library?type=design&node-id=683%3A3746&mode=design&t=L4Ta7hz4QUR8ZQoU-1) by @Jerryescandon 

### NEW SKILLS > SKILLS LIST | OLD SKILLS > SKILLS EDITOR

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/f351b55f-5357-4111-ae41-da00c4da7ed8)

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Link to new skills page added to "Recruitment" nav
- [ ] Link to new skills page added to "Recruitment" dashboard

**Comment by gobyrne** [comment]
@Jerryescandon to provide updated link text and icon for the admin-only skills link

**Comment by Jerryescandon** [comment]
Done, replaced the `bolt` icon for a `lightbulb` a new icon for the old skills page (now renamed to `Skills editor`)
