### ISSUE TITLE
✨ Add localization to backend report generation

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#9893]
## ✨ Feature

With backend report generation, we'll need add localization so that reports can be generated in both English and French.  In addition to the report template needing to be localized, there is all the "localized constants" logic that turns an enum to a string that needs to be available on the backend, too.

## :question: Questions

Q: How hard will it be to maintain a totally separate localization pipeline for the backend?

Q: Is it possible to move all the localized constants logic to backend so that all the strings and mapping don't need to be maintained and synchronized between the two?

## ✅ Acceptance Criteria

- [ ] Report can be generated in either French or English

## 🛑 Blockers

```[tasklist]
### Blocked By
- [ ]  #9890
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/10029
```

**Comment by brindasasi** [comment]
This will be resolved by https://github.com/GCTC-NTGC/gc-digital-talent/issues/10634
