### ISSUE TITLE
Allow community admin to edit non-critical details of live job advertisement

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#9907]
## User story
As a community admin (or anyone who can publish posters) I want to be able to edit live job posters so I can fix typos and similar.

## Feature

Show "Edit advertisement" link on Advertisement information card (Only for community admins & platform admins)

Allow community admins (or platform admins) to edit the text sections of the job advertisement. Specifically:

1. Special note
2. Your impact
3. Work tasks
4. About us
5. What to expect post-application
6. What to expect post-admission

When attempting to save a field, request a justification in a modal before saving the changes.

LOGIC FOR JUSTIFICATION MODAL

- IF the process status is DRAFT, DO NOT SHOW MODAL
- IF the process status is PUBLISHED, SHOW NEW MODAL when clicking "Save changes"

## Proposed implementation
 
From @petertgiles : 

For how to handle the database field:
>  I suggest just always showing the field blank in the dialog and let every submission overwrite the database value that was there.  The model property will show just the last justification and the changelog can be used to review the field over time if needed.

For how to handle validation:
> I think I would start by pulling out the validation logic from the publish mutation to a batch of reusable rules (maybe already done?) so it can also be called by the "update published pool" mutation.  But yeah, the validation would be identical between "publish pool" and "update published pool" I think. 

### Card (Admin only)

![Image](https://github.com/GCTC-NTGC/design-gc-digital-talent/assets/16977254/09541ca0-7b02-4a3a-8f1d-163df86114ae)

### Save changes (Triggers modal)

![Image](https://github.com/GCTC-NTGC/design-gc-digital-talent/assets/16977254/7a9ecc43-0902-4721-8f33-d02305c61cab)

### Modal

![Image](https://github.com/GCTC-NTGC/design-gc-digital-talent/assets/16977254/203bc0bc-04a9-4cd6-a4ee-3446e5702a67)

## Acceptance criteria
- [ ] Admins (community and platform) get an edit button for published job advertisements
- [ ] They can edit the 6 fields listed above
- [ ] They are prompted to record a justification before saving a change
- [ ] Backend rejects any changes that fail the validation logic for publishing processes
- [ ] New mutation & new policy applicable for publish pool and check permission for publish pool

**Comment by petertgiles** [comment]
We have a changelog table already, so that seems like a natural place.  It might be a little weird to log a change to a field that is not saved in the model's table though.  Maybe we should just have "change justification" field.

Validation is going to by tricky.  The pool editor page sections have fairly weak validation on their own because it is assumed each change is not final on its own.  The backend validation only fires once, when the pool is published.

**Comment by tristan-orourke** [comment]
Good points @petertgiles. 

I like the idea of adding a "change justification" field to the Pool table. We could keep the proposed modal UI, regardless of backend implementation.

We could force editing a published poster to go through a different mutation, one which requires the "justification" and which does the same validation as for publishing.

**Comment by tristan-orourke** [comment]
It's a little more involved, but we could add a new field (like "change_justification") to an activity log entry without adding it to the database model. In the the mutation handler, we could [disable automatic logging](https://spatie.be/docs/laravel-activitylog/v4/advanced-usage/logging-model-events), then [manually log with a custom field](https://spatie.be/docs/laravel-activitylog/v4/basic-usage/logging-activity#content-tap-activity-before-logged), then [re-enable](https://spatie.be/docs/laravel-activitylog/v4/advanced-usage/logging-model-events#content-enable-logging-again) the regular logs.

**Comment by gobyrne** [comment]
I don't understand the advantage of that last comment from Tristan, but Peter's proposed implementation seems solid. I'll work those into the issue.

**Comment by gobyrne** [comment]
Hm... validation is a good question. Is it possible/reasonable to fire the full publish validation for any post-publish changes to these fields?

**Comment by gobyrne** [comment]
@petertgiles I summarized these in the "proposed implementation" section... still lots of questions though. Could you take another look?
