### ISSUE TITLE
🔤 Back to inconsistently translated in French

### ISSUE THREAD

**Issue by mnigh** [GCTC-NTGC/gc-digital-talent#9914]
## 🔤 Copy

Links or buttons that use the copy **Back to** are inconsistently translated in French, using _Retourner au_, _De retour au_, or _Retour à_.

## 🕵️ Details

1. Back to assessments tracker = Retourner au suivi des évaluations
2. Back to process details = De retour au traitement des détails
3. Back to requests = Retour à demandes
4. Back to teams = De retour aux équipes

### Screenshots 
<details><summary>📸 Images</summary>

#### Back to assessments tracker
<img width="776" alt="Screen Shot 2024-03-27 at 10 27 23" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/c4452b19-d38c-4b86-8787-787e8a91dd05">

<img width="805" alt="Screen Shot 2024-03-27 at 10 27 58" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/28adeb15-06bf-4377-b742-bb6813c47885">

#### Back to process details
<img width="700" alt="Screen Shot 2024-03-27 at 10 24 33" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/6a195630-6e14-4b9f-94af-c9de943249ea">

<img width="711" alt="Screen Shot 2024-03-27 at 10 24 50" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/dc89738a-1112-493b-af7e-c0081a541f36">

#### Back to requests
<img width="870" alt="Screen Shot 2024-03-27 at 10 32 12" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/ada3f502-e69c-411d-b2ad-808811c6c268">

<img width="857" alt="Screen Shot 2024-03-27 at 10 32 24" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/e6301e9c-b8c7-4734-ada2-eba3a8295931">

#### Back to teams
<img width="766" alt="Screen Shot 2024-03-27 at 10 33 27" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/a22fad91-7452-4aed-8af4-573adac96d81">

<img width="774" alt="Screen Shot 2024-03-27 at 10 33 40" src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/3046459/b6bc6e17-50dc-4ae5-bf9d-67eee159ee10">

</details>

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the copy has been added or updated appropriately.

- [ ] Links or buttons that use the copy **Back to** are consistently translated in French

**Comment by mnigh** [comment]
@gobyrne could you provide some guidance on this please?

**Comment by gobyrne** [comment]
Yeah, these translations all individually makes sense, but agree we should be consistent.

I'd like to standardise on "retourner" as it signals well that an action is being taken:

Back to assessments tracker = Retourner au suivi des évaluations
Back to process details = Retourner au traitement des détails
Back to requests = Retourner aux demandes
Back to teams = Retourner aux équipes
