### ISSUE TITLE
✨ Not compliant status for `PoolCandidateSearchRequest`

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#9947]
## Details
As a request responders, I also want a way to flag that requests were not submitted properly, so...

To address this, add a new request status
EN: Not compliant
FR: Non conforme

If we have sorting weights, put this one last. But otherwise, I'm not fussed about sorting.

```[tasklist]
## Acceptance criteria
- [ ] Not compliant status added for requests
```

**Comment by mnigh** [comment]
@gobyrne i'm not sure i understand what a request that is not compliant, but doing [adding a honeypot field to the form](https://github.com/GCTC-NTGC/gc-digital-talent/issues/9970) might reduce or eliminate the need for a spam status.

**Comment by gobyrne** [comment]
Thanks Matt, yeah they don't seem to need the spam one. I removed it.

**Comment by mnigh** [comment]
> As a request responders, I also want a way to flag that requests were not submitted properly, so...

To address this, add a new request status
EN: Not compliant
FR: Not compliant

@gobyrne How could a request be improperly submitted? What standards would a request not be compliant with?

In any case, am I correct to assume that Not compliant in English is not _Not compliant_ in French and just a copy and paste oversight?
