### ISSUE TITLE
🐛 Flaky test - testCreateSnapshot

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#9975]
## 🐛 Bug

This test fails about 1 in 4 runs.

## 📋 Steps to Reproduce

1. `while php vendor/bin/phpunit tests/Feature/SnapshotTest.php --filter=create --stop-on-failure; do echo; done`

## 📸 Screenshot

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/cee59805-7510-41d8-9cdc-3fb36a21f911)

## ✅ Acceptance Criteria

- [ ] Test accurately checks snapshots
- [ ] Test is reliable

**Comment by esizer** [comment]
Was going to look into this but can't seem to get it to sail 😢 Ran 25 times with no failure 🤷‍♀

**Comment by petertgiles** [comment]
> **Update**: nvm 😓

Shoot, maybe it was my bad and I actually introduced it in this PR.  :grimacing:
